### PR TITLE
Nathan fix route permissions

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR adds more permissions to have access to pages where they are relevant.

## Main changes explained:
- Remove `seeProjectManagement` and `seeProjectManagementTab` outdated permissions
- Updated Header to check for more permissions for access to Other Links
- Updated routePermissions.js with additional relevant permissions

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. login as an Owner user
5. go to Other Links -> Permissions Management -> Manage User Permissions
6. give a volunteer account one permission at a time for each permission
7. login with your volunteer (you will have to log out and back to update permissions if you were logged in in another tab/window)
8. go to the dashboard
9. Check that the links in Header -> Other Links/Reports work according to the Description column in [The Permissions Spreadsheet](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit#gid=0). For example, users with `getReports` should have access to Reports->Reports in the Header.

**Jae's Note: I want to get this merged ASAP, so DM Nathan if any of this isn't clear.** 

## Notes
1. `getReports`: Reports->Reports
2. `getWeeklySummaries`: Reports->Weekly Summaries Reports
3. `getUserProfiles`, `postUserProfile`, `deleteUserProfile`, `changeUserStatus` : Other Links-> User Management
4. `seeBadges`, `createBadges`, `updateBadges`, `deleteBadges`: Other Links-> Badge Management
5. `postProject`, `deleteProject`, `putProject`, `getProjectMembers`, `assignProjectToUsers`, `postWbs`, `deleteWbs`, `postTask`, `updateTask`, `deleteTask`: Other Links -> Projects
6. `postTeam`, `putTeam`, `deleteTeam`, `assignTeamToUsers`: Other Links -> Teams
7. `postRole`, `deleteRole`, `putRole`, `putUserProfilePermissions`: Other Links -> Permissions Management

### CODE REVIEW

**Review by Coops023 — APPROVED** [review]
Hello i have reviewed the functionality of this new feature by:

- Log in as volunteer and check dashboard, not able to view reports
- Logging as owner user
- Other links -> permissions management -> Manage user permissions
- adding permissions to volunteer user
- logging back to vulunteer user check for new permissions in dashboard. 
- New permissions were there as expected. 

PR-1950-adding

PR-1950-dashboard

As far as i can tell, the feature works as expected. Well done.

**Review by XiaohanMeng — DISMISSED** [review]
Hello, I've thoroughly tested this PR by following these steps:
- Logged in as a volunteer to check the dashboard, where I was unable to view reports.
- Logged in as an owner user.
- Accessed Other Links -> Permissions Management -> Manage User Permissions.
- Granted permissions to the volunteer user.
- Logged back in as the volunteer and checked the dashboard for the newly granted permissions.

The new permissions were correctly in place, confirming that the PR functions as intended and demonstrates remarkable efficiency.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/dfb904c0-f78b-4a08-9ab0-34415483574c

**Review by TapanPathak — APPROVED** [review]
Hi, I tested your functionality of this new feature by:

1. Logging as owner user
2. Gave Volunteer permissions 
3. Logged In as Volunteer
4. New Permissions for Reports were there


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/05256db4-cc72-4b9f-9375-f4e2f615b068

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested your PR and all the intended changes are working properly. I logged in with an owner account and gave my volunteer account permissions for badge management and report management. The permissions were being reflected in my volunteer account and I could access the functionalities related to the permissions. Please refer the attached video for reference.  


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/bc8bcc40-4f8c-4eaf-a089-c9eb4ac57685

**Review by DiegoSalas27 — DISMISSED** [review]
Hey Nathan. This is a lot of work. I Just wanted to add something as a means to improve the readability of the project. As you are reusing strings in different components to verify permissions, it would be better to use constants so that no typos may occur. I am attaching a video of how I came up with a simple solution to it.

You PR works perfectly well, this is just a comment so feel free to choose what makes more sense to you. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26840798/9b6c3043-fca9-4a2c-80a5-d0140aa55c69

**Comment by skaush21** [comment]
Hey Nathan, I tested the reports features and they work

These were the steps I took:
* Logged in as volunteer to check dashboard, did not have access to reports
* Logged in as owner user
* Accessed Other Links -> Permission Management -> Manage User Permissions.
* Granted all report permissions to volunteer users
* logged back in as volunteer and checked dashboard, I am able to access reports
* reports are visible: Reports -> Reports
* weekly summaries are visible: Reports -> weekly summaries
* Anayltics reports and weekly summaries were accessible separately
* new permissions appeared when added. 
* Report permissions and features work 
I took a look at the code as well and everything seems to be in order.




https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/1b13e704-3455-4a28-94f1-c8b30007ef65

**Review by skaush21 — APPROVED** [review]
Hey Nathan, I tested each tested the reports features separately as well as together.

These were the steps I took:

* Logged in as volunteer to check dashboard, did not have access to reports
* Logged in as owner user
* Accessed Other Links -> Permission Management -> Manage User Permissions.
* Granted all report permissions to volunteer users
* logged back in as volunteer and checked dashboard, I am able to access reports
* reports are visible, Reports -> Reports
* weekly summaries are visible, Reports -> weekly summaries
* Anayltic reports and weekly summaries were accessible separately.
* new permissions appeared when added. 
* Report permissions and features work 
I took a look at the code as well and everything seems to be in order.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/eef14620-c480-4c8c-8282-19afdb7229a0

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and everything worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/d228605d-bbc8-45f1-bde5-505d14cfdc43

**Review by chrischenlixing — DISMISSED** [review]
image
image
Logged in as a Volunteer: Initially, the volunteer couldn't view reports on the dashboard, indicating restricted access.

Switched to Owner Account: Accessed the system as an owner to adjust permissions.

Accessed Permissions Management: Via "Other links" > "Permissions management" > "Manage user permissions," I updated the volunteer's permissions.

Verified Changes as Volunteer: Logged back in as the volunteer and confirmed the new permissions were active and functional on the dashboard.

The evaluation confirmed the feature's effectiveness in managing and applying user permissions smoothly.

**Review by lacnoskillz — DISMISSED** [review]
Nice work @nathanah 
I pulled your code and it works as described
When I created a new volunteer account with little to no permissions I was able to confirm adding them works. Badge permissions gave the account ability to give users and self badges, Projects gave user access to projects link and ability to delete or add projects etc.. etc.. for each permission.

## NOTE
I did notice some accounts have default permissions that cant be changed and I assume thats by design. Like not being able to remove permission to view Reports page. Or remove Permission to Badge management or Projects for my admin account. see below video of me trying to remove reports and user permission to my volunteer account

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/c0756d56-849c-43e6-8c83-450544897f6a

## Here is a video showing me successfully giving my account user permissions access

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/6a1dffe8-3dd2-479f-95d8-1a4df28bc1a5

## side note I noticed a bug for assigning badges on user profile that I will add to the bugs doc. but probably irrelevant to your code. see below video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/a0857cf0-2465-4077-a066-59d3adfca0f8

Really great work!

**Comment by one-community** [comment]
Great reviews everyone!

**Comment by one-community** [comment]
Reminder to request changes when things need to be changed, don't just comment.

**Review by Renanluizssx — DISMISSED** [review]
Hi @nathanah, i tested your application and it's running correctly

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/3e03e910-80fb-4a28-92dd-453f5883cb99

**Comment by psharma1984** [comment]
@nathanah  your code works as described. Snapshots for reference below
Screenshot from 2024-02-20 11-59-59
Screenshot from 2024-02-20 12-00-07
Screenshot from 2024-02-20 12-01-03

**Review by psharma1984 — DISMISSED** [review]

**Review by Gugor99 — DISMISSED** [review]
### Report
As required I checked in as volunteer confirming that I had no view on the reports. Therefore, I logged in as owner and changed the permissions for reports. Once logged in as volunteer again I was able to see the various reports as expected.
I encountered no bugs and the implementation works smoothly, well done!
### Screenshots
Cattura1
Cattura2
Cattura3

**Comment by beblicarl** [comment]
this functionality works as intended and the code is great

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.23-16_19_24.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/ae4c0549-e22b-4db1-ae23-7c9f118f3a00)

**Review by beblicarl — DISMISSED** [review]

**Comment by one-community** [comment]
> Hey Nathan. This is a lot of work. I Just wanted to add something as a means to improve the readability of the project. As you are reusing strings in different components to verify permissions, it would be better to use constants so that no typos may occur. I am attaching a video of how I came up with a simple solution to it.
> 
> You PR works perfectly well, this is just a comment so feel free to choose what makes more sense to you. Great work!
> 
>  Screen.Recording.2024-02-16.at.12.38.30.PM.1.mov

Thank you for this, we're adding it as a new request on the Bugs Doc!

**Pull request merged**
