### PR TITLE
Hot fix of category inheritance

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
This is a hot fix of task improvement system where new task does not have its project category as default value when creating. Add "Unspecified" option to task category list so that it matches project category list. 

## Main changes explained:
- Make AddTask component to get its mother task category (or project category if level one task) when mounting, and set it as the default category in modal
- Make AddTask component's default Assigned value to be true
- fix misspelling bugs
- fix a project reducer bug

## How to test:
1. check into current branch 
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to dashboard → Projects → remember a project's category and click into that project → click into any wbs 
6. try adding a new level one task (use the AddTask button on top of  tasks table) and check if its default category is the same as the project's in modal
7. change an existing task's category to something other than project's category, and try creating a subtask under it, check if the subtask's default category is the same as its mother in the modal.

## Screenshots or videos of changes:
Project category
project category
New level one task category
new level one task category
Subtask category under housing mother task
subtask category under housing mother task

### CODE REVIEW

**Review by DavidC0126 — COMMENTED** [review]
Hi @wang9hu, 
I have tested your PR and it works as intended.

1.  I added a new task in a WBS that its default category is Energy, and the new task is the same as the project's in modal.
new_task_cat
project_cat
2. I then changed an existing task's category to something other than project's category, and try creating a subtask under it, it turned out that subtask's default category is the same as its mother in the modal.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/6271d124-9b2c-4de6-8c3b-990a38c45bd7

**Review by eduvarjaor — APPROVED** [review]
Hi @wang9hu 

I tested this PR and everything worked as intended. Great job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/f6478312-5173-4050-9bc3-de11d5c716e9

**Review by robertoooc — APPROVED** [review]
Hi @wang9hu, I tested your branch and it did perform as expected. Went through all the options and had no problem at all.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/07973f2f-9580-41bb-8635-bc792ab561b5

**Comment by iTvX** [comment]
I have tested your PR, and the default category with the subtask always stems from its parent task. You can verify this by watching the video below, where I have tested all the cases you mentioned. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/573969b5-a510-4812-bd19-2c889324c660

**Review by Jiyuanxia — APPROVED** [review]
Hello, @wang9hu! I have reviewed your pull request and conducted testing. The implementation functions as intended. The subtasks' categories are consistent with their respective mothers', and this consistency remains even when the mother's category is modified. Well done!

Projects page shows project .Z test's category is unspecified:
Screenshot 2023-08-10 144517

Category of .Z test's new task is same as its mother's:
Screenshot 2023-08-10 144800

Change category of  .Z test to food:
Screenshot 2023-08-10 144850

Category of  .Z test's subtask changes to food too:
Screenshot 2023-08-10 144915

**Review by eduhorta — COMMENTED** [review]
Hi @wang9hu.

I've created a task under the category of "Unspecified". 
After that tried to add a task and the category was still "Unspecified".
Changed to "Society" and clicked save.

Now after clicking on this task and then edit the category is "Housing".
Adding a sub task the category shows "Society" and when hit save I get a popup saying the data base has changed.
Page refreshes.
I try to edit the first task and the category shown is "Housing".
Added a subtask again with the category "Society" and hit save
When clicking on edit on the subtask the category is "Housing"

Here is a video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/e23bf348-34c2-439f-b879-736dc6c19336

Is this the expected behaviour?

**Review by navneeeth — APPROVED** [review]
LGTM!

Tested by logging as an admin user and navigating to Dashboard -> Other Links -> Projects and remembered a project category and clicked into its WBS. Tried adding a new level one task and the default category tested to be the same as the project category. Tried changing an existing task's category and when I tried adding a child task (subtask), it inherited its parent's category by default successfully. Nice implementation!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/11162409-d1b4-42f3-8b86-42b86eb76ec6

**Review by sxiong5 — COMMENTED** [review]
Hey @wang9hu, I have tested your PR, and it worked as expected!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/408300d0-fcd2-4f08-bd83-7ff438b86540

Just one more could be optimized! When creating the subtask under a task, the default option is shown as unspecified, while its parent task is not, but after it is created, it's the same (that's what we want). But this might be confusing. It can be better to let the default option be shown as its parent's category.
Screenshot 2023-08-10 at 16 28 56
Screenshot 2023-08-10 at 16 29 27

**Review by TheDescendant39 — COMMENTED** [review]
Hi @wang9hu, I tested your PR and everything seems to work well. Great Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/d481e3a8-3e7a-4ff7-b346-89ffd9fbbc06

**Review by winghojackyli — APPROVED** [review]
Hi @wang9hu , I've tested the PR and it works as intended. 
I added a new level one task and its default category matches its project category. 
I added another level one task with category different with the default category. Then, I added a child category under it and their category matches. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/f032ccc7-299e-40ec-a350-57d89d1eac54

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this is Yufu. I have viewed the changes, and works on my device.
image

**Comment by AnishPandita** [comment]
Hi @wang9hu The PR works as intended and I was able to replicate the results.
Screenshot 2023-08-10 at 4 03 18 PM
Screenshot 2023-08-10 at 4 03 49 PM
Screenshot 2023-08-10 at 4 04 52 PM

**Review by yunshan111 — APPROVED** [review]
Tested your PR, LGTM.

image

**Comment by wang9hu** [comment]
> Is this the expected behaviour?

@eduhorta I added this behavior to the PR455(backend) and PR1032(frontend) to make sure that users with the permission will not make changes at the same time to keep the database consistent across all users. I guess someone made a change while you are testing my PR. Please try it one more time and let me know if it happens again.

**Review by ramyaram2092 — APPROVED** [review]
Works as expected . Good job 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/93504f1c-b54b-4847-8965-df43155ae741

**Review by veronicacheng2 — APPROVED** [review]
Hi @wang9hu, I have tested according to instructions and everything works as intended

1. Level one task will inherit the category from the project 
2. Subtask will inherit the category from level one task

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/af687dd5-b482-461a-b6c6-b9b3388c0c2a

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @wang9hu 

I tested your PR and unfortunately  it does not work for me. The app throws a "404 Not Found" 
The app throws on existing projects and on a project I created. 

See video and screenshot. 

I am using a mac and I've checked into your branch and the developpment branch for the backend. 
I am also using Nvm and Npm 14.17.6


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/c970aba1-4c70-4575-801b-4c34522366a2

Screenshot 2023-08-10 at 9 08 07 PM
Screenshot 2023-08-10 at 9 09 21 PM
Screenshot 2023-08-10 at 9 09 54 PM

**Comment by n0vay** [comment]
I am not able to add tasks.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/3137423b-9167-4fde-ba3d-ee9dc1d8654e


image

**Review by ThapeloMasasa — APPROVED** [review]
The changes work as expected.. Good job!!!

Screenshot 2023-08-10 at 11 12 08 PM
Screenshot 2023-08-10 at 11 11 56 PM

Screenshot 2023-08-10 at 11 12 19 PM

**Review by EdwinLauM — APPROVED** [review]
Hey @wang9hu. Code changes work as expected! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/f620ce77-c15a-4ab8-abad-8af250d7fb16

**Review by jerryren527 — APPROVED** [review]
Hello @wang9hu,

I appreciate the comprehensive instructions you provided. I have successfully tested your proposed changes and can confirm that they work as intended! Both tasks and sub-tasks now inherit the default category from the project they are associated with.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/aae44ba5-7365-441c-a16a-76880e3c91d1

During my testing, I discovered a bug that occurs after creating a new project and selecting its category through the form positioned above the table of project names. However, I believe that this issue lies outside the scope of this PR. The focus of this PR is on ensuring that tasks and sub-tasks inherit a default category that matches their respective projects, which we confirmed works as intended.

The screen recording and voice-over demonstrates the bug. It appears that the initially selected option in the "Select Category" dropdown menu reverts to "Unspecified" when navigating away from the Project page and then returning back to it. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/6a41bf9a-9eea-49e4-9861-b3982bc917a2


However, when updating the category of an already existing project through the dropdown in the "Category" column, the category remains correctly assigned and consistent even after navigating away and returning to the Project page.

I will look into adding this bug into One Community's Phase 1 Bugs and Needed Functionality Documentation.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
