### PR TITLE
Anny create quick setup function and modal for new team members

### PR DESCRIPTION
**Pull request by astrjc0326**
# Description
image

## Related PRS (if any):
This frontend PR is related to the[ #644  backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/644).

## Main changes explained:
- Created the QuickSetUpModal
- Only can be seen for Owner and Admin
- Created a new title with team and project to assign
- Setup the title with only a click and save the change

## How to test:
1. check into current branch at frontend and backend side
2. do `npm install`, `npm run build` and `npm run start:local`  to run this PR locally
3. Clear site data/cache
4. log as admin user or Owner to add a title and interact with quick-setup code
5. go to View profile→ Add a Title → Click on the Quick-Setup code
6. check if the userprofile updates

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/4a5f27d1-eb20-41dc-9fc8-276105ce96c5

### CODE REVIEW

**Comment by DragonSlayer2401** [comment]
There appears to be a few console errors preventing me from going to the profile. When I go to the profile I get a white page. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/d5fc63a7-d7a1-44bf-878b-902d5cc4c7d1

**Review by Alforoan — CHANGES_REQUESTED** [review]
I get errors when I click on the view profile button.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/81d4a51b-a81d-4651-9693-9dc8ef02fbb9

**Comment by astrjc0326** [comment]
Hello @Alforoan and @DragonSlayer2401, thank you both for bringing this to my attention! 
I forgot to push some changes I made on the backend side. 
I have just updated it. 

You can now test it again by running `git pull` on the backend code, followed by `npm run build` and `npm start` to update the backend code and then test it with the frontend. I apologize for any confusion, and I appreciate your feedbacks.

**Comment by keyunhuangg** [comment]
Hello, I checkout and pull your branch to get the newest update. But I also have issue with getting an error when clicking view profile button.
Screenshot 2023-12-14 at 4 04 53 PM

**Review by this-journey — CHANGES_REQUESTED** [review]
Hello @astrjc0326 ! I'm running into several issues.  Upon any sustained wait before trying to click on the "Welcome" drop down it becomes un-clickable.  If I catch it in the first couple seconds then I am able to get to my profile.  Once I'm there the "Add A New Title" button is not functioning.  I've attached a video for reference.  I'm receiving an async error in the console.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/da21645d-2593-492b-942c-f5f9a2e335b5

**Review by Alforoan — APPROVED** [review]
Everything works as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/9b6d429d-a456-4c62-99dc-f4c08fc06aa8

**Pull request closed without merging**
