### PR TITLE
Cillian: Add invisibility indicator to Team members page

### PR DESCRIPTION
**Pull request by CillianRen**
Screenshot 2024-09-20 180226

Description:
Added an invisibility indicator to the Teams page to clearly show which members are invisible. The indicator is displayed as a hidden eye icon (👁‍🗨) next to the names of invisible members.

Modified TeamMembersPopup.jsx to include the hidden eye icon for members marked as invisible, allowing team members to quickly differentiate between visible and invisible members.
This addresses the need for quickly identifying who is invisible or visible on a team, as outlined in the feature request.
Fixes # (high priority bug)

Related PRS (if any):
No related backend PR.

Main changes explained:
Updated TeamMembersPopup.jsx to add a hidden eye icon (👁‍🗨) next to invisible members.
The visibility status is set via the user’s profile settings (Profile > Teams > Visible/Invisible).
How to test:
Check into the current branch (Cillian_impl_invisibility_indicator).
Run npm install to ensure all dependencies are installed.
Clear site data/cache before testing.
Log in as an admin user.
Navigate to Teams > select a team to view the list of team members.
Confirm that invisible members have the hidden eye icon (👁‍🗨) next to their names, while visible members do not have the icon.
Test the functionality in both light and dark modes to ensure the visibility indicator is displayed clearly in both.
Screenshots or videos of changes:
Screenshot 2024-09-20 174959
Screenshot 2024-09-20 174903

Note:

This PR implements the invisibility indicator for team members. Reviewers should check if the icon appears correctly and verify that the invisible status is set via the user profile settings (Profile > Teams > Visible/Invisible).

### CODE REVIEW

**Review by anirudhsk2107 — DISMISSED** [review]
Tested the changes in light and dark mode. The icon is visible clearly in both of them.
I also changed the visibility of the account and checked in the table if they're updated in both modes and it seems to be working fine. 
Screen Shot 2024-09-21 at 2 12 30 AM
Screen Shot 2024-09-21 at 2 06 29 AM
Screen Shot 2024-09-21 at 2 07 05 AM
Screen Shot 2024-09-21 at 2 13 29 AM

**Review by ashmita123 — DISMISSED** [review]
I tested it in both light and dark modes, and the icon is clearly visible in both.
Everything looks good and functions as expected.


https://github.com/user-attachments/assets/d40bcd30-c3ac-4e74-b9c8-afea05192e0f

**Review by ArtemisNyx3 — DISMISSED** [review]
image
image
Working up to spec 👍🏽

**Review by panchalvatneu — APPROVED** [review]
Took a while for the change to appear but it works!

image

**Review by sam19981 — APPROVED** [review]
Changes work as expected.

Screenshot 2024-09-21 at 10 38 01 PM

Screenshot 2024-09-21 at 10 38 16 PM

**Review by slidracoon72 — DISMISSED** [review]
#2702
@CillianRen
1. Confirmed that invisible members have the hidden eye icon (👁‍🗨) next to their names, while visible members do not have the icon.
2. Tested the functionality in both light and dark modes to ensure the visibility indicator is displayed clearly in both.

Video Demonstration:
https://www.loom.com/share/6a1c11937d0a4d77a5c7811776778719?sid=cb07800f-65cd-4ffa-9c20-81686a622223

**Comment by beblicarl** [comment]
this functionality works as expected and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Review by Dk-21 — DISMISSED** [review]
### PR 2702
@CillianRen 
Tested and Working as Instructed
PR-2702(2)
PR-2702(1)

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR and its working as expected in both light and dark modes.
Screenshot 2024-09-27 164204
Screenshot 2024-09-27 164216

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.
Screenshot 2024-09-29 134653

**Review by lcohen730 — APPROVED** [review]
Invisibility indicators are visible in light and dark modes. Works as expected.

Screenshot 2024-09-30 at 22 43 51
Screenshot 2024-09-30 at 22 44 31

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
