### PR TITLE
Roberto - Lint Fix Timer Component

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
Lint fix for the Timer component `src/components/Timer`

## Main changes explained:
- Removed component from .prettierignore and .eslintignore
- Formatted component 
- Created an index.js file for the component

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. go to dashboard→ Timer
4. verify function Timer functionality completely works
5. set up ESLint and Prettier in VSCode
6. check all files in `src/components/Timer/**` don't have errors

## Screenshots or videos of changes:
Screenshot 2023-09-11 at 5 47 40 PM

### CODE REVIEW

**Review by Sssky-18 — APPROVED** [review]
Hi @robertoooc, I tested this fix on the Timer component, and the code looks fine because in my computer, the code does not show any bugs or errors after setting up the ESLint and Prettier in VSCode. Besides, the timer also works well after running your code. Therefore, I think your fix is successful on the Timer, congrats!   

PR#1288_code

PR#1288_timer

**Review by Haoj1 — APPROVED** [review]
@robertoooc Timer works good and there is no error in Time.jsx. Good job

**Review by GaryB93 — APPROVED** [review]
Verified Timer folder was removed from .eslintignore and .prettierignore files and tested to see if I could create ESlint errors in Timer.jsx file. Verified functionality of Timer component. Good work!
Screenshot 2023-09-12 at 1 46 03 PM
Screenshot 2023-09-12 at 1 42 49 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I checked your code locally and it is error free. I also tested your fixes by running the application and the timer is working perfectly! 


week 3 - PR1
week 3 - Pr1 (2)

**Review by navneeeth — APPROVED** [review]
Hello @robertoooc, I have reviewed your changes and they work as intended! The function timer functionality completely works and I set up ESLint and Prettier in VSCode and found no errors in `src/components/Timer/**`. Good implementation!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/cc2abbea-4015-4725-adcf-8ed7fbfd4045

**Review by DavidC0126 — APPROVED** [review]
Hi @robertoooc  I tested your PR and it works as described.
FE
UI

**Review by tsunami776 — APPROVED** [review]
I followed the steps in the PR and tested both the timer and linting for files in the timer directory. The timer functions as expected, and there are no errors in `src/components/Timer/**`.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/0f6e19ae-a91b-41df-aa26-734e4a9924e9

**Comment by AnishPandita** [comment]
Hey I tested the PR and it works well. Checked the timer and files for any errors. All seems to function good.
Screenshot 2023-09-12 at 6 03 12 PM
Screenshot 2023-09-12 at 6 02 24 PM

**Review by Jiyuanxia — APPROVED** [review]
Hi @robertoooc , I have reviewed your pull request and tested it. It works as you intended. Good job!

Screenshot 2023-09-14 235705
Screenshot 2023-09-14 235722

**Review by gabi-lima — APPROVED** [review]
Working as expected! Well done!
image
image

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions! The feature is working perfect.

The timer is working correctly.
Screen Shot 2023-09-17 at 12 38 31 AM

No errros in all files from src/components/Timer/**
Screen Shot 2023-09-17 at 12 39 10 AM
Screen Shot 2023-09-17 at 12 39 04 AM

**Review by Chris33871 — APPROVED** [review]
Hi @robertoooc ,

I reviewed the changes and it looks good, good job 👍 

PR1288-1
PR1288-2

**Comment by beblicarl** [comment]
This works

issue #1288

**Review by beblicarl — APPROVED** [review]

**Review by Shiwani99 — APPROVED** [review]
Hi,
I tested your PR. Timer works as intended. I also checked if the timer folder path is removed from prettierignore and eslintignore. There are also no errors in the timer.jsx file. I'm attaching screenshots of what I tested.

Screenshot 2023-09-19 at 11 51 41 AM

Timer.jsx
Screenshot 2023-09-19 at 11 53 20 AM

**Comment by iTvX** [comment]
I tested your pr, and I didn't see any error in my IntelliJ IDEA. Good Job!

CleanShot 2023-09-20 at 14 12 23@2x

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I tested this PR. It works. 
Screenshot 2023-09-22 at 11 36 07 PM
Screenshot 2023-09-22 at 11 36 29 PM

**Comment by Shubhu0** [comment]
Hi @robertoooc The PR was tested and reviewed and it is working as intended. Good job!

image

**Review by EdwinLauM — APPROVED** [review]
Hey @robertoooc, tested your PR and works as expected! Timer works and no errors on the code either

Screen Shot 2023-09-30 at 5 58 27 PM

Screen Shot 2023-09-30 at 5 58 47 PM

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
