### PR TITLE
Lucile information points on everything of interest

### PR DESCRIPTION
**Pull request by LucileTech**
# Description
3. (PRIORITY HIGH) Jae: Make everything of interest have an “i” by it explaining how it works (WIP - Lucile) 
Need someone to through the whole app and create a spreadsheet of every area that doesn’t already have an “i” by it that should. Then help get those all added! 
Organize the spreadsheet (or Google Doc) with the same sections you see on this doc
Include in the doc pictures of where you plan to put each “i” so I can approve them
To keep the app simple for the most common user class of Volunteers, also include/decide which “i”s should be visible to everyone but Volunteers
Make those “i”s blue (#00CCFF) so it’s clear it is a special thing visible only to certain classes
Make all “i”s editable by Owner class so changes in use, meaning, etc. can easily be updated by the Owner

## Main changes explained:
Here is the link to the Google Doc for info points management: https://docs.google.com/document/d/1f2s1Y7oivAqgwDLBjALtOloIcR0hQ3iAEw5l2v5eZBo/edit?usp=sharing

This document contains: 

Existing info points: Historical info points present in production that have been made editable by owners in this PR

Non-Editable/Mouse-hover info points: Info points that appear with a mouse hover and therefore are not modified in this PR.

New info points added: New editable info points added in this PR

New info point ideas: Please feel free to put your info point ideas in this Google Doc

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as an owner user
4. go to the different pages to see if the info points are editable when clicking on it
5. log as admin user
6. go to the different pages to see if the info points are displayed but not editable
7. log as regular user
8. go to the different pages to see if the info points are displayed but not editable
6. Please, add info point ideas in [this Google Doc
](https://docs.google.com/document/d/1f2s1Y7oivAqgwDLBjALtOloIcR0hQ3iAEw5l2v5eZBo/edit?usp=sharing)if you feel that some parts of the app have to have an info point

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111132148/5ad5d569-188c-411d-bb01-fdf63686ec2f

### CODE REVIEW

**Comment by one-community** [comment]
You raised PR #1000! 👍 😃

**Comment by Vishala09** [comment]
Everything works great. Awesome work. 

Testing as Admin User 
Tested i's(EditableInfoModal) : 

- Timelog Component : 2 i's
image

- Leaderboard Component : 3 i's
image

- Reports Component : 4 i's
image
image

- User Management (NewUserPopup.jsx) Component: 2 i's
image

- Badge Management Component : 1 i
image

- Project Component : 1 i
image

-Project Table Header Component : 1 i
image

- PermissionsManagement : Multiple i's for each role
image

- UserProfile and Badges Component : 3 i's
image

- BasicInformationTab Component : 1 i
image

- Weekly Summary Reports Page : 1 i
image

- RoleInfoModal in Formatted Report : 1 i
image

An opened Information Modal
image

1. After opening the pop up , you could see the header is moved to the left by adding a padding space on right. Can you make sure not to add the space when the modal is opened?
2. This `i` on top of Tasks and Timelog is sort of hanging in the middle of the page. Can you place it somewhere else so that it is clear what the particular `i` represents. (Just a suggestion) . Same request on User Management Page.

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works an intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/a1809933-4b6f-4c4e-8630-8ff5450a8206

**Review by Sssky-18 — DISMISSED** [review]
Hi @LucileTech, I tested this PR using my Admin and Volunteer account, and for both of them, the information buttons worked as expected. Each button when I clicked it showed the popup with correct text, and I tested almost all of the pages, and every button pointed to the correct text. 
PR#1000
PR#1000_1
PR#1000_2
PR#1000_3

**Comment by one-community** [comment]
Thank you everyone, moved to final review!

**Review by JeffLi117 — APPROVED** [review]
Changes work as intended when tested with my Admin and Volunteer account. Below are the views that I have when I checked each information button:

image
image
image

Good job!

**Comment by Lin1404** [comment]
Hi @LucileTech , I have tested your PR for owner/admin/regular user and it works as intended. Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/805774a7-b91b-492e-af1c-cc3663d513f2

**Review by Lin1404 — DISMISSED** [review]

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
This thing is huge, so I'm going to mainly highlight the areas that aren't functioning as intended. I'm going down the whole google docs sheet to ensure I hit everything as well as a manual scan myself. These changes are requested due to it probably not functioning in the intended manner such as the weekly summary page, items not being aligned like they are in the mockups, alignment issues in the css, and the first issue noted below that would enhance the user experience.

<h1>Issues</h1>
1. Everything says "Welcome to Information Page!" , I think it would be better if there was a props manually passed down to instead say the specific modal info name. 


2. I'm on the timelog url and the dashboard info modal is present there. 
pr1000 dashboard info modal butotn present on timelog url


3. usermanagement info modal button isn't centered like it is in the google doc mockup.(does function though)
pr1000 usermanagement info modal alignment off


4. in weekly summaries report page, the Info modal button next to some of the role names is blue despite being noneditable. It should probably be greyed out like the rest of the info modals since this isn't an area I imagine you'd want to be editing the info modal.
pr1000 weekly summaries reports page role modal info not editable despite being blue


5. This is an issue in a lot of different places, but much more of an issue here in the create new user info modal popup. The margins are off and causing the button to stack directly next to the element to the left
pr1000 create new user modal spacing bad


6. Leaderboard info modal button is too close to element on the left
pr1000 leaderboard icon alignment off



7. badge management info modal button alignment isn't centered like mockup
pr1000 badge info modal management page alignment off


<br/>
<br/>
<br/>

<br/>

<br/>
<h2>Here's the remainder of my screenshots declaring proper functionality in the rest of the app.</h2>
- Note how you have no idea what info modal that it's even for most of the time due to the title always being "Welcome to Information Page"

pr1000 add intangible time entry modal noneditable works
pr1000 badge info management modal works
pr1000 create new user info modal works
pr1000 editable 1
pr1000 editable 2
pr1000 editable 3
pr1000 editable 4
pr1000 editable 5
pr1000 editable 6
pr1000 editable 7
pr1000 editable 8
pr1000 editable show total people report
pr1000 editable show total team report
pr1000 main info modal on userprofile page works
pr1000 noneditable 1
pr1000 permissions modal working as noneditable
Pr1000 projects info modal works
pr1000 reports page head i
pr1000 roles info modal works for each role
pr1000 tasks and timelogs info modal works
pr1000 user management info modal editable
pr1000 user profile badge number modal works
pr1000 user profile badges modal works
pr1000 userprofile role change info modal works
pr1000 wbs info modal works

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Great job on integrating areaTitle into the different modals! Really helps with the user experience.

There is one spot where the areaTitle props wasn't passed down. Once that's added in, I'll approve 100%.

in ~~ Other Links > Permissions Management > click any of the blue I icons next to a role. currently the areaTitle props is not there. Makes me appreciate typeScript a little more since it catches these things(HGN is .jsx, so it happens)

If you could add the following code below to allow areaTitle to change dynamically depending on the Role Name

Screenshot 2023-11-01 at 1 01 17 PM
Screenshot 2023-11-01 at 1 01 49 PM


~ one more thing that's totally optional, but can be an easy fix if you want to do it.
    The usermanagement icon is vertically aligned to the top of the container, but should be centered.
pr1000 user management centered now



Everything else checks out and looks fantastic. All of the areas of concern I had before that were essential were addressed

**Comment by LucileTech** [comment]
> Great job on integrating areaTitle into the different modals! Really helps with the user experience.
> 
> There is one spot where the areaTitle props wasn't passed down. Once that's added in, I'll approve 100%.
> 
> in ~~ Other Links > Permissions Management > click any of the blue I icons next to a role. currently the areaTitle props is not there. Makes me appreciate typeScript a little more since it catches these things(HGN is .jsx, so it happens)
> 
> If you could add the following code below to allow areaTitle to change dynamically depending on the Role Name
> 
> Screenshot 2023-11-01 at 1 01 17 PM Screenshot 2023-11-01 at 1 01 49 PM
> 
> ~ one more thing that's totally optional, but can be an easy fix if you want to do it. The usermanagement icon is vertically aligned to the top of the container, but should be centered. pr1000 user management centered now
> 
> Everything else checks out and looks fantastic. All of the areas of concern I had before that were essential were addressed

Thank you for your detailed review Kurtis! Everything asked is now pushed.

**Review by KurtisIvey — APPROVED** [review]
Props were added in for areaTitle into PermissionsManagement.jsx & padding was added to the userManagement info modal icon 👍🏻 It all looks great and is ready to go. Fantastic job.

css fix:
Screenshot 2023-11-01 at 9 25 06 PM

passing of props into PermissionsManagement.jsx
Screenshot 2023-11-01 at 9 28 20 PM
Screenshot 2023-11-01 at 9 28 06 PM

**Pull request merged**
