### PR TITLE
Shrey-Changed the CSS to get a fixed size for timer and button

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
 Fix “more work needed button” formatting 
”more work needed, reset this button" can be put after a line break so that the time bar is consistent with the other user tasks time bar which will look more uniform.
For admin account, the icons for bell, and tick are alson not uniform, depending upon the task name length.(2nd Screenshot)

## Main changes explained:
- Fixed the length of task progress/timer bar, irrespective of task info content size.
- The bell icon, remove, info kept on moving because of task info content, fixed the position so that they look more uniform
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any admin/owner/manager/mentor user and also as Volunteer user.
4. go to dashboard→ Tasks→ task→…
5. verify the that after the button state is changed, the timer in the right is consistent with other user progress bar/timer bar.
6. for admin/owner/manager account also verify that the icons are consistent and the progress bar/timer is consistent too.
7. go to Timelog→ Tasks and check the same.
## Screenshots or videos of changes:
Before:
The timer bar was inconsistent, and the icons also kept on changing their positions

Screenshot 2023-08-24 at 3 26 59 AM

[New Recording - 8_24_2023, 3_23_28 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/2dcd7c8b-48f4-4798-b173-6f0cac437fd0)

After:
Timer size is consistent and the icons position are also uniform
[New Recording - 8_24_2023, 3_16_33 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/0f44a0fa-8289-4a07-aef2-7259975a58cc)

### CODE REVIEW

**Review by tsunami776 — APPROVED** [review]
Tested with Owner and Volunteer accounts. The length of the task progress bar is now fixed irrespective of task info content size. After submitting reviews, the bell icon and other icons also have fixed positions instead of moving. Task progress bar and icons work as described in the PR.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/97cabb5b-f24d-4917-b5fa-aa83347b5845

**Review by belagaam — COMMENTED** [review]
Tested the PR as per the instructions. Everything works as expected on the Admin and Owner account. Good work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/ecaa927f-26e2-404d-8498-e8a30e975b99

**Comment by Jiyuanxia** [comment]
Hi @Shreyj14, I have reviewed your pull request and tested it. It works as you intended. Good job.
Screenshot 2023-08-24 164115
Screenshot 2023-08-24 164207

**Review by DavidC0126 — APPROVED** [review]
Hi @Shreyj14 I tested your PR and it looks good to me.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/d15028d0-8721-4b32-91e4-00f40cd12062

**Review by Haoj1 — APPROVED** [review]
Good job @Shreyj14 ! CSS of the timer and button looks good on my browser. On a large screen, the whole task bar can be entirely displayed. On small screen, 13'' Mac, the timer hides behind the right corner and displays after sliding right.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/a8b20200-edda-48af-8cec-b1d2c092fb8a


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/f732dc1d-9776-4f79-b1ff-004abc5e27b9

**Review by yunshan111 — APPROVED** [review]
Tested this PR, LGTM.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/699faf46-49f9-4cfb-a025-67c38f9a83ac

**Comment by Shreyj14** [comment]
> Great work with the icon placement and the progress bar sizing. I do have a question about the purpose of the Status column when logged in as Admin, seeing as it looks like that column isn't being used and the alignment for the Progress title doesn't align with the progress bars.
> 
> Also, I think it would be more intuitive if after clicking the Submit Review button it would disable the button and change the text to "In Review".
> 
> As far as testing those buttons, how do I get the "Ready for review" button to show up in Tasks as well as the "More work needed" button?
> 
> Screenshot 2023-08-24 at 2 53 58 PM
> 
> Screenshot 2023-08-24 at 3 01 29 PM

Hi @GaryB93, I believe the logic here is that for admins, you wont see more work needed, button as you see in volunteer account, instead it will take it has Ready for review were you can accept it or move back it to the unsubmitted stage. You might have to look at the code to understand that logic. In this PR i have only tried to make changes to the layout, all the other logics have been implemented earlier. To see the difference you can run the devlopment branch and see, what changes I have made.

**Review by n0vay — APPROVED** [review]
Good Job!
Small suggetion, the bell icon has some extra paading on the right.
image

**Comment by beblicarl** [comment]
Tested this functionality and it works as intended.

[screencast-localhost_3000-2023.08.25-14_37_07.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/9049b48b-33cf-4a55-9b52-165e91a7680c)

**Review by beblicarl — APPROVED** [review]

**Review by veronicacheng2 — APPROVED** [review]
Hi @Shreyj14, I have tested the PR. The sizes of the timer and button look good.

Logged in as Admin:
image

Logged in as Volunteer:
image

**Review by harshidad — APPROVED** [review]
Changes looks Good!
Fixed size for timer and button_1 #1169
Fixed size for timer and button_2 #1169

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change work perfect on my device @Shreyj14
image

**Review by ramyaram2092 — APPROVED** [review]
Hello @Shreyj14  the css looks good 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/21d98532-7e24-4f1f-b829-c5b340dcf595

**Review by ss23046 — APPROVED** [review]
Hi @Shreyj14 ,
I have tested the PR, LGTM! 
Screen Shot 2023-08-26 at 6 07 57 PM
Screen Shot 2023-08-26 at 6 09 05 PM

**Review by yaow62023 — APPROVED** [review]
I've tested your pull request across all account types, and all the features are working as expected.

**Review by zuhang2000 — APPROVED** [review]
I tested your PR following your instructions. Everything works as expected. The icon and the buttons look uniform in all cases. The view is much better than before. Good job!

**Pull request merged**
