### PR TITLE
Edwin - Create way to show how many times a deadline has been updated 

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-06-29 at 6 03 50 AM

## Related PRS (if any):
This frontend PR is related to the BE PR [#429](https://github.com/OneCommunityGlobal/HGNRest/pull/429)

## Main changes explained:

- Added a new backend property for a task to track `deadlineCount`
- When estimated hours of a task is edited and updated, increase the `deadlineCount` by one 
- Display this deadlineCount in the team member tasks component in the progress bar

## How to test:

1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as Admin/Owner user
4. go to Dashboard -> Team Member Tasks
5. click on any task you want to edit -> edit -> update "Estimated Hours" in the edit modal and click update
6. go to Dashboard -> Team Member Tasks
7. The notification icon on top of the progress bar should increment

## Videos/Screenshots of changes:

Admin/Owner account:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/19f5cd0e-b22c-46a2-a1b2-aaa9edda02b2

## Notes:

If the task itself is edited but the estimated hours remain the same, the deadlineCount **Should Not** increment, thus the notification icon should remain with the same count

### CODE REVIEW

**Comment by beblicarl** [comment]
@EdwinLauM This PR works as intended. Great work !!

[increment-deadline-count_3000-2023.06.29-14_00_22.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/4e8a1a19-e758-45b5-b545-cf552c0a00b3)

**Review by beblicarl — APPROVED** [review]

**Review by cone-7 — APPROVED** [review]

**Comment by Jiangwei-shi** [comment]
This PR works as intended. When the mouse is over the red dot will show the due date follow-up count
image

**Review by mahamakhan — COMMENTED** [review]
Changed it a few times and the number changes when the hours are changed. 

image

**Comment by Lucas-E** [comment]
Great job everybody! Moving this one to final review!

**Comment by igorrochadasilva** [comment]
Hi @EdwinLauM !
I hope you have a good day : ) 

This PR works as intended. When I updated the estimated hours, the counter increased from 3 to 4 inside the red circle. Good job!


[increment-deadline-count-2023.07.04.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39310911/6b776839-fde7-4dbb-a50d-f362b7518d21)

**Review by NidaZaki — APPROVED** [review]
I tested this PR and everything works as intended!

**Pull request merged**
