### PR TITLE
Roberto fix view other user dashboard

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
Screenshot 2023-12-28 at 5 51 39 PM

## Related PRS (if any):
Test this FE with latest Backend development

## Main changes explained:
- Updated Timelog.jsx, Header.jsx, and Dashboard.jsx to rely on checking session storage data, if there exists a variable `viewingUser` it will update the state of these components and children components according to that users' data. Mounted event listeners to them so they can listen in on the changes happening to the session storage which emits a dispatched event.   
- Moved Popupbar component to directly stick with the header/ nav bar so user is always aware across the entire website if they are viewing someone else's account.
- Updated popupbar.test and leaderboard.test to adjust to new changes.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ leaderboard → click on any user's red/green circle by their name 
6. verify that this results in your entire dashboard and header view being adjusted to that user, check the 'activity for user name', the hours, current week log, summary report, badges, tasks, and infringements are all updated appropriately.
7. Scroll down and make sure the team member task list is updated accordingly, do the same for the leaderboard, and then also check the timelog.
8. Now view the header/nav bar, if you click on timelog it should still show that users' according data, go to user profile and make sure it leads you to that viewing user profile.
9. Feel free to open a new tab and compare that the state is only affecting that one original tab.
10. Stop viewing the user by clicking on the X that shows up on the yellow bar that says 'viewing header for ...', make sure it reverts all the data back to your logged in user.
11. Test with multiple accounts and different level permissions, make sure only admin and owner's are allowed to edit other people's dashboard data.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/c217cd9f-58cb-42c0-bb37-494b18ec2833

if you're not logged in as an owner/admin your dashboard component should have a tint like this, also make sure only owner can be edited by other owners:
Screenshot 2024-01-17 at 12 04 29 AM

## Notes:
Any questions or clarifications feel free to ask.

### CODE REVIEW

**Review by KevHnh — DISMISSED** [review]
All functionalities mentioned works smoothly. I tested on a volunteer account and can't see other team members on the leaderboard (I believe the same goes for all volunteer accounts). 

Only noticeable issue is owner and admin accounts fetch team members' tasks and maps it all at once which hurts performance as shown by the lag when trying to switch tabs or exit the viewing state. (Might be an active bug already -- will check)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/5eaf62ca-a43b-4088-aea4-50c557974080

**Comment by Cavein254** [comment]
@robertoooc  
Reviewed the pr as a administrator and the code function as intended. I also viewed other as other team's profile and viewed the result as expressed in this pr. An issue noticed is lag in performance possibly due to the amount of data the application is receiving.

Screenshot 2024-01-21 004323



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/f95e1683-f9b2-4830-b00b-42de0264702c

**Review by X1aoZhang99 — COMMENTED** [review]
Hi Roberto,

I've just tested your PR, all functionalities worked as intended. I noticed a small issue, when I am on a user's profile page and then click on 'X', the page remains on that user's profile instead of returning to the logged-in user's profile. I'm not quite sure if this is correct. Please refer to the video. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/73f44862-db99-402e-855d-a4270d242d73

**Review by Nahiyan-16 — CHANGES_REQUESTED** [review]
## Hi Roberto
Looks like the dashboard interface updates visually.
**Did notice that the four icons above the clock and underneath the profile picture are not responding**
**Also when viewing a user profile and proceeding to click the X button, it doesn't update the page accordingly**

Screenshot 2024-01-23 183413
Screenshot 2024-01-23 183454

**Review by Renanluizssx — DISMISSED** [review]
Hi @robertoooc, I've tested your application and it lives up to your claims.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/1a1079f7-ce91-4c36-808b-4bcd4f28ebd0

**Review by SaiDeepak-NEU — COMMENTED** [review]
Reviewed the changes listed in the PR and tested the features by logging in as admin and clicked on a volunteer profile. Page is rendering user information on confirming.

Validated activity username, timelog, team member tasks, profile page and badges information.

Screenshot (23)
Screenshot (22)
Screenshot (21)
Screenshot (20)

Also tested on clicking the 'x' on the yellow test bar, the page prompts back to the logged in user profile.

Note: One thing i am skeptical is about the user name also changing on the nav bar on top. I think that should not be the case as I am logged in as a different user and the information should only change below the navbar and the header showing information that i am currently viewing dashboard of another user. Look at the attached picture for reference
Screenshot (23)_Edited

That is only my opinion so feel free to give it a thought and I am open to further discussion about it.

**Review by yvonnep165 — DISMISSED** [review]
Hi @robertoooc,
I have tested the codes with the admin account and volunteer account and all functionalities mentioned work smoothly as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/7feaba67-7014-41c5-b903-8be895efea0d

**Review by Sophie-lei — DISMISSED** [review]
Hey! I just tested this PR review. I logged in as owner role and I can view other people's profile successfully.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/504a6536-08b6-425c-acc4-d0f0b8a8e108

**Review by 666saofeng — CHANGES_REQUESTED** [review]
Hi Roberto, I tested to view Jay volunteer dashboard. The page cannot render. Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/deb9cb0a-a403-4e20-8d76-7c5e83c06844

**Comment by galgalinidhi** [comment]
Hi @robertoooc, I get the following error during compilation although I have leaflet installed.

**Comment by galgalinidhi** [comment]
Hi @robertoooc, the functionality works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/c1d23014-f896-4a3e-93c1-7c1385664aab

**Review by ClemarNunes — DISMISSED** [review]
I tested the pull request and didn't find any issues other than those mentioned above. All mentioned features worked as expected. The only observation is regarding performance, which seems to be affected by the large volume of data the application is receiving, as mentioned. Great job, @robertoooc!  

PR2

**Review by SRamen1999 — APPROVED** [review]

**Review by SRamen1999 — CHANGES_REQUESTED** [review]
After testing this PR there are some bug I discovered.

If you view another account and log out before leaving the viewed account it shows the yellow bar on the log in page. And if you log onto a different account it keeps you on the viewed account.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/6ac7245d-cccc-4487-80a7-029e09526815

Another bug I discovered is the four icons do not respond when you view another account. Also if you view the profile and then exit the users account it doesn't refresh the page properly. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/aa7fa9d5-d71f-4a15-a516-6713be24165b


Both owner and admin accounts can edit viewed accounts. If you're not logged in as an owner/admin the dashboard component has a tint and you cannot edit anything.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/d7325c85-e520-40b3-bbd5-57b2db649ae1

**Review by peterson337 — DISMISSED** [review]
I tested it and it worked as advertised.

one comunnity

**Review by Pandani07 — DISMISSED** [review]
I tested this as a volunteer and I could not see anyone else's dashboard. As an admin, I could see someone else's dashboard and everything works as intended by Roberto


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/0480c464-f9f4-4036-b955-c8fa83ec58e2


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/fbb08b50-4688-4ff7-b7ec-f17dac350636

**Comment by xmyoot** [comment]
Hello, I tested the PR by logging in as a admin user and tested the functionality please reference the photos below, I am able to peek on others dashboards successfully:

Clicking Button:
PR#1845(testingAdminClickTest)

Viewing the Individuals Dashboard:
PR#1845(testingAdminAccessToDashboards)

**Review by mohabbasd — DISMISSED** [review]
Hello, this PR is running just like how it is meant to be. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/94a9ea17-16a8-46a7-b41a-05d21097834b

**Comment by TapanPathak** [comment]
Hello, I reviewed the PR by logging in as Admin and Volunteer. As a volunteer, I couldn't view anyone else's dashboard. For an admin, all functionalities operated according to PR.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/058f06ed-a8fa-42fc-8d1f-78961f62e4e6

**Review by TapanPathak — DISMISSED** [review]
Hello, I reviewed the PR by logging in as Admin and Volunteer. As a volunteer, I couldn't view anyone else's dashboard. For an admin, all functionalities operated according to PR.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/5a812399-770d-4270-9583-8a589d027cce

**Comment by nnamdixobi** [comment]
The changes run as expected

**Review by XiaohanMeng — COMMENTED** [review]
Hi, I've reviewed the PR using both Admin and Volunteer accounts. It's great to see that as a volunteer, the leaderboard only shows my own data, while as an Admin, I can view others' dashboards as well. However, I encountered an issue: when clicking "X" on the volunteer profile page, the display doesn't revert back to the Admin profile but remains on the Volunteer profile instead. This issue is demonstrated in the video provided.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/30d3b39e-4ffa-4fdc-bc65-43de1b272a7f

**Comment by robertoooc** [comment]
@XiaohanMeng, the user profile page is not intended to change when you close out of the view user popup, the change occurs in the navbar, so if you were to click the user profile icon again it would redirect you to your corresponding account

**Comment by XiaohanMeng** [comment]
> @XiaohanMeng, the user profile page is not intended to change when you close out of the view user popup, the change occurs in the navbar, so if you were to click the user profile icon again it would redirect you to your corresponding account

Got it, thanks for the explanation.

**Comment by nnamdixobi** [comment]
Looks good and runs as expected however you might want to maintain consistency in state initialization in the code. Like you could consider initializing the popup state using the useState hook with false as its default value

**Review by Jingyii800 — DISMISSED** [review]
You did a great job. All functions work well, as you described in the statement. Only in admin or owner woles can you view others' dashboards. When I switch the role to volunteer, I can only view my dashboard. 
When click on "X" button, I can exit the person's dashboard and get back to the admin dashboard. Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/4b697b2e-b39e-449d-9210-fc193ab4986e

**Review by Coops023 — DISMISSED** [review]
Hello, i checked the functionality of your new feature by:

- Logging in as an admin user.
- Clicking the red/green circle next to username.
- Ensuring the dashboard and header changes to that username's details.

Everything has worked as intended, well done!

PR-1845-1

PR-1845-2

**Review by brandta-1 — COMMENTED** [review]
# Review
Able to test functionality for Volunteer and Admin roles. The function works for an Admin going into a Volunteer, and a Volunteer going into an Admin. Additionally, when exiting the other profile's dashboard, a redirect to the home dashboard could be nice (see video 01, still on other user's badge page).

# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/7648afd1-72d4-45c1-b02a-e8f7f6e7cf4e


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/5f5961d0-10ad-451b-af1a-a2527cac649b


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/e2502980-dd52-468a-8a39-2b6437a13ce7

**Comment by Gugor99** [comment]
### Review

**Comment by Gugor99** [comment]
###Review
I really liked your implementation and it worked as expected. As you can see in the attached pictures, modal, timelog, tasks and leaderboard are displaying correctly. Also only under a owner/admin account is possible to actually change data from the chosen profile. Well done!
Cattura1
Cattura2
Cattura3
Cattura5
Cattura6

**Review by Gugor99 — DISMISSED** [review]

**Comment by Weiyao-Li** [comment]
I followed each step for testing: checked out the current branch, ran npm install and npm run start:local, and cleared site data/cache. Logged in as an admin, I navigated through the dashboard to the leaderboard, interacted with user indicators, and verified the dashboard and header updated to reflect the chosen user's data accurately. This included checking activity, hours, logs, reports, badges, tasks, and infringements. Scrolling ensured the team and leaderboard updates were correct, as well as the timelog. The header/nav bar remained accurate when navigating, and viewing the user profile functioned as intended. Opening a new tab confirmed the changes were localized. Exiting the view mode by clicking the 'X' on the yellow bar effectively reverted to my data. Testing across multiple accounts with different permissions affirmed only admins and owners could edit dashboard data. Here is my complete steps:

Screenshot 2024-02-23 at 17 40 59
Screenshot 2024-02-23 at 17 40 28
Screenshot 2024-02-23 at 17 40 25
Screenshot 2024-02-23 at 17 39 59
Screenshot 2024-02-23 at 17 39 53
Screenshot 2024-02-23 at 17 39 08
Screenshot 2024-02-23 at 17 38 34
Screenshot 2024-02-23 at 17 38 17
Screenshot 2024-02-23 at 17 36 52

**Review by psharma1984 — DISMISSED** [review]
Hi @robertoooc The PR works as expected. Tested with admin account and was able to see the dashboard, leaderboard and tasks of other users. Tested with volunteer account too and wasn't able to access others dashboard. Well Done !!!

[screen-capture.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/5c32880a-da12-4d84-9098-5004a2c46e8c)

**Review by MALAV1308 — DISMISSED** [review]
Hello, I have reviewed your PR and it's working properly as per test cases mentioned above. The performance issue need to be addressed. Overall, fantastic job.

**Review by PratimaSingh02 — DISMISSED** [review]
Hello Roberto,
I could successfully execute all the steps mentioned in the PR.
1. Could switch to any user's profile
Screenshot (46)
2. Every element on the dashboard got adjusted as per the profile being viewed
Screenshot (47)
3. Team memeber task list has also been updated
Screenshot (48)
4. Timelog also updated
Screenshot (49)
5. Can see the user's profile page
Screenshot (50)
6. Multi-tab state has been maintained
Screenshot (51)

Note: Switched back to my account but can still see the previous user's details

**Comment by DiegoSalas27** [comment]
Hi Roberto,

I was trying to test your PR, but I am facing an issue that I am explaining in the video I have attached. If you happen to know why this is happening please let me know.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26840798/bb343d34-a2f4-4fe6-8b2f-069118941a94

**Review by bhuvan-dv — DISMISSED** [review]
Working as expected
PR-1845 jumped to profile view
PR-1845 Jump to personal dashboard modal

**Comment by robertoooc** [comment]
@DiegoSalas27, the problem you're facing seems to be the same problem many people have been noticing on the dev site (mentioned very frequently on coding problems slack channel). As I'm aware a quick fix has been to clear local storage and cookies to fix this. Currently I think a fix for this problem is being developed and might help in resolving that issue.

**Review by Sarthak32 — DISMISSED** [review]
I have tested this using different accounts It works as expected. Also the tint appears regardless of it's owner or not .
Screenshot 2024-03-17 115147
Screenshot 2024-03-17 115204
7c12f65)

**Review by Tiantian-C — COMMENTED** [review]
All the function has completed as described!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/3e76dac2-e11c-4c81-baa9-02a25ec361e5

**Review by cvtqx — DISMISSED** [review]
Everything works as described!

Tested this PR as admin and owner and I was able to view other user's profile page, dashboard etc and interact with it. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/e2460b68-1b4d-4974-9a57-fc4216bce9d5

When opening a new tab the state was not affected and I was taken to my own profile:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/12bc7c4d-e2ca-42b3-9404-4e9b52b24dce

Upon clicking on the X I was taken to my original account.

When testing from a volunteer or manager's account I did not see any other members in the leaderboard.

Screen Shot 2024-03-28 at 11 17 30 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
