### PR TITLE
Saideepak equipment details

### PR DESCRIPTION
**Pull request by SaiDeepak-NEU**
# Description
Implemented the equipment details page in the bmdashboard as part of the phase 2 development.
319460727-d1c220e2-a82d-4f65-91ba-9e1c555db8de

## Related PRS (if any):
This frontend PR is related to the [837](https://github.com/OneCommunityGlobal/HGNRest/pull/837) backend PR. To test this frontend PR you have to checkout the branch mentioned in the [837](https://github.com/OneCommunityGlobal/HGNRest/pull/837) backend PR
…

## Main changes explained:
- Created EquipmenrDetails.jsx and EquipmentDetail.css
- Added routing for equipment details
-  Added the url and added pages like equipmentactions, equipmentreducers, equipmentconstants etc
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally(npm start)
3. Clear site data/cache
4. log as any user eg: volunteer, owner or admin
5. go to http://localhost:3000/bmdashboard and login again
6. Navigate to http://localhost:3000/bmdashboard/equipment/65c16ef325834114ac9427e0
7. Verify the design from the figma template https://www.figma.com/file/kpwXZP2pLtOJ1Fn2u7Sivn/HGN-PII?type=design&node-id=430-5449&mode=design , you can find the template under the name E/T Detail Page
8. Verify the details of the page from the database from buildingInventoryItems collection.
9. Feel free to change the id in the url to any other id in the database and verify the webpage data.

## Screenshots or videos of changes:
1. Login to BMdashboard
Screenshot (131)
2. Navigate to equipment detail page
Screenshot (132)

## Note:
The scope of this PR is only limited to a few data fields namely Belongs to Project, Class, Name, Number, Ownership, Rental Duration, Current Usage. All other fields are just populated with hardcoded dummy data as there are no such fields in the database. We are still working on updating the database to appropriate values.

### CODE REVIEW

**Review by hbodgal — DISMISSED** [review]
Everything looks good except 2 minor differences. The Title of the Page is different and "P" of the project needs to be Capital. Please refer the image:
image

**Comment by SaiDeepak-NEU** [comment]
> Everything looks good except 2 minor differences. The Title of the Page is different and "P" of the project needs to be Capital. Please refer the image: image

The title of the page differs because it's the same design for both Title Detail page and Equipment Detail Page.

**Review by ImzIssa — CHANGES_REQUESTED** [review]
Hey, I've reviewed your PR and your changes look good. 
However, I've noticed a few things that slighlty differ from the figma.
The "Link to Buy/Rent" and the "Description" are acual Links instead of titles
Instead of the $ sign you used USD

PR 2114

Was this intentional?

**Review by aaryaneil — CHANGES_REQUESTED** [review]
The changes look good except for minor details that look off from the Figma design, like the number doesn't have a hashtag, the prices don't have the "$" symbol instead have "USD" and the links are hyperlinks.
Screenshot 2024-04-05 at 12 50 35 PM
Screenshot 2024-04-05 at 12 52 26 PM

**Comment by SaiDeepak-NEU** [comment]
Changed USD to $ sign and fixed the capital P in project. As far as the links are considered, we are going with hyperlinks unlike shown in the design with actual links. Thank you for observing and mentioning the changes and for your Review. @aaryaneil and @lmzlssa if you can change your review to approved, we can merge these changes into development quickly

**Review by lacnoskillz — DISMISSED** [review]
Hello @SaiDeepak-NEU 
I pulled both front-end and backend code and see your changes and they look great!
I see your page looks just like the figma. and as you had mentioned earlier you are using hyper links now.
Here is your changes

pr 2114

Also looks Good on iphone/mobile Niceee

pr 2114 mobile view

They look great and follow the figma design

pr 2114 figma


I would just suggest commenting out your console logs before you merge

pr 2114 console logs

Nice work and happy coding!

**Review by hbodgal — APPROVED** [review]
Looks good to me.

image

**Review by ShengjieMao — APPROVED** [review]
The page looks good and displayed as described in the instruction.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
