### PR TITLE
Fix badge earned date

### PR DESCRIPTION
**Pull request by BaileyM96**
# Description
DASHBOARD COMPONENT 2 - (PRIORITY MEDIUM) Jae: Need a “Details” button or other way to see when specific badges were earned. Some badges are earned multiple times, so the button needs to show all dates when they were earned.
Dashboard → Badges Section → Badges Report

## Related PRS (if any):
This frontend PR is related to the #311 backend PR and #755 Frontend PR.

## Main changes explained:
- Fixed dropdown button in the Badge Report modal and user profile section that show all dates for each earned Badge.
- Removed some code that used the built in Date method and replaced it with moment js.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ View Profile→ Featured Badges→ Assign Badge→ Confirm→ Select Featured→ Save Changes
5. go to dashboard→ Scroll the screen→ Badges→ Badge Report Button
6. verify that the "Dates" button lists the earned dates.

## Screenshots or videos of changes:

Adding Badges in View Profile

[_Details_ button test in user profile.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/3e86274b-ca43-4454-9d78-32c4393533ba)

Verifying Badges in Badge Report

[_Details_ Badge report on dashboard.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/4a281f4c-4a9b-45ca-aff4-5627c2394ed8)

### CODE REVIEW

**Review by TheDescendant39 — APPROVED** [review]
Hi @BaileyM96, I followed your test steps and can confirm that the changes work well. Great Job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/6dc60955-4083-4e36-b050-f30590834573

**Review by DavidC0126 — APPROVED** [review]
Hi @BaileyM96,

I tested your Pr and everything works as described.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/5ec4f45e-be60-4fc1-a52a-3e3ba41824a8

**Review by robertoooc — APPROVED** [review]
Hi @BaileyM96, I tested your branch and it performed as expected. Nice work.

Updating Badges: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/bd4abcd4-12e6-46a8-82fb-dd054048df4b

Dashboard Badge: 
Screenshot 2023-08-15 at 9 39 46 AM

**Review by yurisokolovicz — APPROVED** [review]
Dear @BaileyM96 
The earned badge date has been corrected. It is working properly in both admin and owner accounts. Please check the videos below.

**Badges earned today:**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/ac6095ca-45f3-46a3-8d3e-f68857e9959d

**Badges earned yesterday:**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/a8a8f880-502f-44dd-a366-8b4d12e8bcfb



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/00dc1dcd-9497-414f-87c5-7667f03c8a21

**Review by navneeeth — APPROVED** [review]
LGTM! Good implementation. Logged in as an admin user and tested both the changes:
**Adding Badges in View Profile:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/66920362-86a4-4677-9b64-7f5d2e89e5e8

**Verifying Badges in Badge Report:**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/fb2db2cf-49a2-4b4b-9a2d-b78dae09b90b

**Review by winghojackyli — APPROVED** [review]
Hi @BaileyM96 , I've tested the PR and it works as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/1c9b1b77-8e58-4a73-8e57-24b4169b3fc5

**Comment by AnishPandita** [comment]
Hi, followed the PR and everything is working as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/3a98280f-11bd-4f4f-9241-40c80baa4998

**Review by belagaam — CHANGES_REQUESTED** [review]
I tested your PR and everything works except when I go to Badge Report on Dashboard and click on Save Changes (even if I make any changes or not) I cannot close the pop-up window.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/caad0398-908b-4b06-b2a5-a2d2f0c0d85d

**Review by jerryren527 — COMMENTED** [review]
Hi @BaileyM96!

Thank you for your clear instructions. I am able to test your changes without any problems. The dates of badge assignments to users are now visible and accurate within both the "Select Featured" modal and the "Badge Report" modals.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/89b15625-055a-43dd-9903-8b17a89872e3

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/76dc8d23-a1ae-424c-8cda-7f70350efc0d

However, I do have some questions concerning the intended behavior in specific scenarios related to your changes:

1. What is the intended behavior when assigning the same badge to a user more than once on the same date? Currently, the same date will appear multiple times in “Earned Dates” column, as demonstrated in the screen recording below. Is this the intended behavior?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/686744f5-7b9b-4c39-910d-b0bf755fde3c

2. What is the intended behavior when decreasing the count for a badge? The dates that appear in the “Earned Dates” column appear unchanged. Is this the intended behavior?

3. Lastly, I encounter the same issue as @belagaam when clicking on “Save Changes” in the Badge Report modal. An error gets thrown and crashes the app. Do you suggest this bug get added in the Phase 1 Bugs and Functionality documentation? 

Thank you for your consideration of these inquiries!

**Review by yunshan111 — APPROVED** [review]
Tested this PR, LGTM.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/45382a17-ed92-4ff1-94cd-91ce36f7a66c

**Review by luisarevalo21 — APPROVED** [review]
Hello @BaileyM96 

I reviewed your PR and works as intended. Great work!

I created new badges for my admin account and when viewing I could see it was earned on the correct date. 
I adjusted the badges by adding another and could see the changes.
I returned the the dashboard and selected badge report and could see the same information and all the badges. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/f9343182-da41-43a9-8abd-551615b1e0be

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great!

[screencast-meet.jit.si-2023.08.17-12_57_48.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/8ed1a670-73e1-4e8c-b1b4-20651e2c653c)

**Comment by Lin1404** [comment]
Hi @BaileyM96 , I tested this PR and the functionality works as intended.

image
image

**Review by Lin1404 — APPROVED** [review]

**Comment by Shreyj14** [comment]
Hi @BaileyM96,

I tested your Pr and everything works as described.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/5a25ecd1-51e7-426f-b455-48478ba1b6a9

**Review by harshidad — APPROVED** [review]
Tested - working as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/10c748cb-7a4b-4da0-8fcc-ad4312b19a62

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this one to final review!

**Review by n0vay — APPROVED** [review]
Tested, works as intended. Good Job!
image

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change work well on my device! 
image
image

**Review by veronicacheng2 — APPROVED** [review]
Hi @BaileyM96, I tested the PR and it looks great!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/52368a76-a008-46e6-a77b-e841d0ce18d4

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
