### PR TITLE
Jeffrey fix letter code dropdown

### PR DESCRIPTION
**Pull request by JeffLi117**
# Description
image

## Related PRS (if any):
none
…

## Main changes explained:
- Add a handler function that fires when the new team code has been accepted and sent to database
- Said handler function updates state (teamCodes, selectedCodes, and summaries) within WeeklySummariesReport.jsx to accurately reflect the changes within that would occur if updated data were pulled from the database, but without refreshing

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as admin user
4. go to Other Links → Reports → Weekly Summaries Reports
5. select a team code from the dropdown that has a label of (1)
6. change the team's code (input element next to Media URL) to a code that does not exist yet
7. ensure that the initial team code from step 5 is not present within the dropdown menu
8. click on the dropdown again and see if that new team code is reflected in the dropdown menu
9. select that team code to ensure the correct number of members are populated on the screen
10. select another team code
11. change the team's code to a code that DOES exist already
12. click on the dropdown and check that the team code from step 11 is updated correctly
13. select that team code to ensure the correct number of members are populated on the screen

## Screenshots or videos of changes:

Before change: 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/5617d750-d275-40d3-8a95-f787b5a30c61

After change:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/3b30d14c-2207-455a-819d-2fc9be638131

### CODE REVIEW

**Review by kavya151 — CHANGES_REQUESTED** [review]
Hi @JeffLi117 , I have run PR#1453 locally and its working as intended as per drop down i.e When a team code is changed to a new team code or updated team code, the team member count is reflecting accurately in real-time when selected from the drop-down.
Where as, When a newly created team code is selected, or an existing teamcode  that is updated is selected from dropdown, it displays 0 team members or shows only the old team members or until a manual refresh is performed.
Check the below videos for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/10a6188f-6213-48ce-9506-ddb4c9fe5078


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/7128f8f3-8d8e-4d45-a989-6251f4d316c3

If the PR is related to just realtime updating in the drop down Please let me know I will approve the PR

**Comment by JeffLi117** [comment]
> Hi @JeffLi117 , I have run PR#1453 locally and its working as intended as per drop down i.e When a team code is changed to a new team code or updated team code, the team member count is reflecting accurately in real-time when selected from the drop-down. Where as, When a newly created team code is selected, or an existing teamcode that is updated is selected from dropdown, it displays 0 team members or shows only the old team members or until a manual refresh is performed. Check the below videos for reference.
> 
>  Screen.Recording.2023-11-11.at.1.09.13.AM.mov 
>  Screen.Recording.2023-11-11.at.1.10.48.AM.mov 
> If the PR is related to just realtime updating in the drop down Please let me know I will approve the PR

Thanks for letting me know about this issue! I'll work on resolving this - I thought I had addressed it but I must have messed up somewhere. I'll tag you/request another review when I fix it.

**Comment by olenadanykh** [comment]
Hi @JeffLi117, I've tested your PR, and I didn't experience the error mentioned by @kavya151. Everything works as expected on my end. The total number of team members updates smoothly without needing a manual page refresh, proving effective for both existing and newly created teams. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/3fff9185-e7e6-4b81-9d97-b7f64d927f28

**Comment by JeffLi117** [comment]
> Hi @JeffLi117 , I have run PR#1453 locally and its working as intended as per drop down i.e When a team code is changed to a new team code or updated team code, the team member count is reflecting accurately in real-time when selected from the drop-down. Where as, When a newly created team code is selected, or an existing teamcode that is updated is selected from dropdown, it displays 0 team members or shows only the old team members or until a manual refresh is performed. Check the below videos for reference.
> 
>  Screen.Recording.2023-11-11.at.1.09.13.AM.mov 
>  Screen.Recording.2023-11-11.at.1.10.48.AM.mov 
> If the PR is related to just realtime updating in the drop down Please let me know I will approve the PR

@kavya151 I think the issue in your videos is a problem I had in my previous commits - but when I checked again on my end, I can't replicate the problem. Is it possible you don't have the latest version of this PR?

**Pull request closed without merging**
