### PR TITLE
shrey_conditional_render_google_grayed_icon

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Conditionally render google doc icon to only show if profile has google doc link 

- Currently, on the weekly summary reports page to the right of the name value this icon is present: This icon is there whether the profile has a google doc link or not, which gives the appearance of it being there.
-  To make this page more user friendly, I suggest implementing a conditional operator to render the google doc icon with a different appearance if the profile does not have a google doc link. Maybe a grayed out version?

## Main changes explained:
- Grayed out the google doc icon, if there is not google doc link present.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ Reports→ Weekly Summaries Reports→…
5. verify that google doc icon is grayed out for users who have no google link

## Screenshots or videos of changes:
Before:
All the google doc icons were colored for all users.
Google_doc_colored

Screenshot 2023-08-19 at 4 23 57 PM

After:
Only the user with google doc link present have the icon in colored
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/ef79d3ed-09af-4d04-bdf0-b2298d43a3c4

### CODE REVIEW

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, the new feature works as intended. The Google dock icon grayed out for the account did not set up the link. Check the video below for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/aa1e8e2d-d483-46a2-8820-d6ac6f665d57

**Review by ss23046 — APPROVED** [review]
Hi @Shreyj14 
Tested the PR, works perfectly! The icon is grayed out for the users who don't have the link.
Screen Shot 2023-08-19 at 1 59 36 PM

And for those who have it set up:
Screen Shot 2023-08-19 at 1 59 56 PM

**Review by Cirakuze — APPROVED** [review]

**Review by TheDescendant39 — APPROVED** [review]
Hi @Shreyj14, I verified that the google doc icons work as expected.
Screen Shot 2023-08-19 at 3 51 03 PM

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-08-19 173024

**Review by harshidad — APPROVED** [review]
Working as mentioned in PR.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/7240fc65-3535-41d2-9045-39bff176cbc2

**Review by EdwinLauM — APPROVED** [review]
Hey @Shreyj14, changes work as expected! Good job! 

Screen Shot 2023-08-19 at 7 55 58 PM

**Review by n0vay — APPROVED** [review]
Works as intended.  but there is no check if the link provided is actually a google doc.
image

**Review by arcan9 — APPROVED** [review]
Hi, it's working as intended. Google icon for those without link set up is greyed, while those with the link are colored.

Screenshot 2023-08-19 at 10 28 34 PM

Screenshot 2023-08-19 at 10 29 26 PM

**Comment by one-community** [comment]
Excellent job everyone. I see Edwin's approval here too, so merging this!

**Pull request merged**
