### PR TITLE
Aishwarya purchase consumable request form (frontend)

### PR DESCRIPTION
**Pull request by Aishwaryak01**
Description
Adds Purchase Request: Consumable page and form to the BM Dashboard (Phase 2).

Related PRS (if any):
Backend PR 784 must be running to test this branch.

Main changes explained:
Adds an ability to initiate a purchase request for a consumable to be used on a specific project.
request must include quantity and priority level, with an optional 'preferred brand' field.
adds actions and reducers to store tool types data in redux store
adds error handling to fetch request on page load
adds success and error toasts after submitting purchase request

How to test:
follow checkout instructions for backend PR 670
git checkout Aishwarya purchase consumable request form (frontend)
npm install
npm run start:local
log in to HGN as a volunteer user
navigate to http://localhost:3000/bmdashboard and enter credentials again
navigate to http://localhost:3000/bmdashboard/consumables/purchase

Test basic form submission:
Project and Consumables options should auto-load into respective fields
Enter info into all required fields (Preferred Brand is optional) and click Submit
Note whether a success toast notification is received
Optional: check Network tab in browser tools to check for a 'consumables' request with status code 201 (Created).

Test form validation:
Test that Submit button is disabled unless all required fields are entered
Test that entering a decimal or technically-allowable letter 'e' (ex: 10e10) in Quantity field results in a validation check/error.
Note: there are validation checks for all form fields, but these are harder to test without manipulating the HTML.
Test that Cancel button clears form and returns user to previously visited page.

Test error handling:

To test error handling on initial page load, you can deactivate the backend server and reload the page. This will load an error page with code 503.
Screenshots or videos of changes:

image

Notes:
Please remember to either Approve or Request Changes. Do not just leave a comment.
Please leave a review for BOTH front and backend branches after you have finished testing!
Permissions are currently not being built into the Phase 2 codebase. All functionality should be accessible to volunteer users.
The form will eventually only be accessible to Building Manager users. Purchase requests will be limited to the BM's own projects. For now these limitations are not in place.

### CODE REVIEW

**Review by abdel-lall — COMMENTED** [review]
This looks good overall. Could you add a little bit of space between these buttons? Everything else works as described.
Screenshot 2024-03-02 222843

Screenshot 2024-03-02 222405

Screenshot 2024-03-02 222635

Screenshot 2024-03-02 222805

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested your PR and everything works correctly. The form submission, validation and error handling works as intended. Please refer the videos and screenshot attached for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/15ddeeef-7c3c-45e5-9846-cf2003abc489

PR 2018 error

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/d49271f2-ea9e-4325-b55f-43d993341de1

**Comment by dhairya-mehta** [comment]
Hey, I tested the PR and verified all the test cases!
image
image

**Review by Pandani07 — DISMISSED** [review]
PR works as expected. Tested after deactivating backend server as well

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/159a4575-2b8b-4e03-8371-1b898b95f760


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/7a92e362-5d2e-4fb2-b5c6-76f978c945d6

**Comment by Aishwaryak01** [comment]
> This looks good overall. Could you add a little bit of space between these buttons? Everything else works as described. Screenshot 2024-03-02 222843
> 
> Screenshot 2024-03-02 222405
> 
> Screenshot 2024-03-02 222635
> 
> Screenshot 2024-03-02 222805

Sure

**Review by 20chen-7 — DISMISSED** [review]
Function looks good and code looks nice! well done!

Screenshot 2024-03-14 at 10 28 07 PM
Screenshot 2024-03-14 at 10 21 47 PM

**Review by tdkent — DISMISSED** [review]
Have tested this PR and can confirm the functionality of both the front and backend works as intended:
- form validation
- form cannot be submitted unless all required fields have inputs
- project and item-type options load into respective inputs
- successful form submission results in success toast
- error page loads with information if backend is disconnected

The backend processes also work correctly (see backend review).

Agree with previous reviewers space can be added to separate buttons, but this is not necessary for this PR.
buttons



Aside from the conflicts, this branch is ready to be merged.

**Review by ImzIssa — DISMISSED** [review]
Hey, I've tested your PR and the validation, error handling and everything else all works as intended. Nice work!

https://www.loom.com/share/d67751d774d549e98be9caa63dfc6ee7?sid=cd96c233-1725-44d0-a8e0-eae8867789d4

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
