### PR TITLE
Jerry - See User Management Tab (Full Functionality)

### PR DESCRIPTION
**Pull request by jerryren527**
# Description

see user management tab description

**EDIT (Sept 20, 2023)**: Please checkout PR #1312 and follow the instructions to run that PR. That PR should address the problems that many of your have faced with this PR. Thank you!

The main motivation of this pull request is to allow an Owner account to assign the “_See User Management Tab (Full Functionality)_” permission to an account that does not have that permission by default (e.g. a Volunteer account).

## Related PRS (if any):

None. But similar code changes in FE PR #1189 . 

## Main changes explained:
- Conditionally render `Other Links->User Management` option in the header for a Volunteer account that had the “_See User Management Tab (Full Functionality)_” permission added by an Owner account.
- Similarly, an Owner account can remove a Volunteer account’s “_See User Management Tab (Full Functionality)_” permission and the `Other Links->User Management` option in the header will no longer be visible/accessible.
- Added `RoutePermissions.userManagementFullFunctionality` to the `routePermissions` prop of the `ProtectedRoute` component (`src/routes.js`).
- Added “userManagementFullFunctionality” key-value pair to `RoutePermissions` in `src/utils/routePermissions.js`
- For the “_See User Management Tab (Full Functionality)_” permission on the Permissions Management page, updated the "i" description to: _Make the "Other Links" -> "User Management" button appear/accessible and be able to create, delete, and update users_.

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. Log in as Owner -> Other LInks -> Permissions Management -> Manage User Permissions
4. Enter the username of an account that does not have the “_See User Management Tab (Full Functionality)_” permission by default (i.e., a Volunteer account). Click on Submit.
5. Login the Volunteer account (if already logged in, make sure to log out and log back in). The “Reports” button should appear with ONLY the “User Management” option visible/accessible.
6. The volunteer account can create, delete, and update users in the User Management page.
7. The Owner account can also remove the “_See User Management Tab (Full Functionality)_” permission. Click on Submit. Log into the Volunteer account and see that the "Reports" button is no longer visible/accessible.

## Screenshots or videos of changes:

Development branch:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/3029034e-9976-4620-97a9-192fd334b4d6

Current branch:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/14cca011-fbb7-4f7a-b950-6f988ab04ad2

## Note:

Due to a general problem, your Owner account may have the “Other Links” button in the header disappeared. You can try Empty Cache and Hard Reset (instructions in the screenshot below):

Screenshot 2023-08-29 at 3 07 09 PM

Or create a new Owner account. I had issues creating new accounts in localhost, so I created a new Owner account in the HGN dev app. Hopefully your new Owner account will have the “Other Links” button in the header.

### CODE REVIEW

**Review by robertoooc — CHANGES_REQUESTED** [review]
Hi @jerryren527, I tested your branch and found some success in most of the meant functionality. I was able to assign the User Management Permission to a volunteer role, that volunteer role was also able to update and delete accounts. An issue I had was when it comes to creating accounts, I don't think your changes directly interfered with this but that was something that I encountered and don't know if anyone else will also encounter.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/e61e72d1-0f97-4a8f-bd08-52158a0ce3f4



Error message: Indicates missing "createdDate" in body payload
Error Message

**Review by gabi-lima — APPROVED** [review]
Everything working as it should for me, even creating users by designated profile with permission.

Captura de tela 2023-08-30 160011
Captura de tela 2023-08-30 160029
Captura de tela 2023-08-30 160122

**Review by yurisokolovicz — APPROVED** [review]
Dear @jerryren527 

You did excellent work; the entire functionality is working. Please check the video below.

1 - Enter the username of an account without the "See User Management Tab (Full Functionality)" permission (e.g., a Volunteer account) and click Submit.
2 - Log in to the Volunteer account (if already logged in, log out and log back in). The "Other Links" button should now appear, showing only the "User Management" option.
3 - The Volunteer account can now perform user management tasks such as creating, deleting, and updating users.
4 - The Owner account also has the ability to remove the "See User Management Tab (Full Functionality)" permission. After clicking Submit, log in to the Volunteer account and observe that the "Other Links" button is no longer visible or accessible.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/d2d0eed4-2dc3-4168-81ac-78f7933d125e

**Review by Haoj1 — CHANGES_REQUESTED** [review]
@jerryren527 I checkout to your PR and give the user management permission to another user, but I cannot create a new user. Other features delete, edit works tho.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/ab1e94fa-c3a8-40c3-b7f1-9533d61b5e3d

**Review by DavidC0126 — APPROVED** [review]
Hi @jerryren527  I tested you PR and it works as intended.

permission
otherlinks
user_management
after_remove

**Review by GaryB93 — CHANGES_REQUESTED** [review]
I was able to change the permissions for a volunteer account so they can see the User Management tab and was able to delete a user with that volunteer account. I was unable to create a user or edit a user. I used the most up-to-date dev backend.

Please advise.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/7ba098c4-a273-43df-a9dd-8c2aeac5065f

**Comment by AuroraLovesWhales** [comment]
Hi @jerryren527. I have tested your PR and am facing the same issue as the comments above. I cannot create a new user under the permission.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/9d4020d2-7bb9-467d-aa70-ac1a0e97e82c

Similarly, when I try to make an update to an existing user account, an unexpected error occurs and the entire page freezes. Please see error detail from the recording below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/fa50e9ae-9e42-416f-8d03-e269e54633a3

**Review by winghojackyli — CHANGES_REQUESTED** [review]
Hi @jerryren527 , I've tested the PR but it cannot grant user permission to create user. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/c7bb60fd-8268-4ca1-aed0-726e9cc346c9

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @jerryren527 

I tested your PR and parts of it works.
I was able to provide the rights to my volunteer account.
However, once logged in I was able to view the user management, however, like others have pointed out when attempting to create an new account an error occurs. 



Screenshot 2023-09-03 at 8 52 48 PM

Screenshot 2023-09-03 at 8 52 31 PM

Screenshot 2023-09-03 at 8 52 22 PM

**Review by Shiwani99 — CHANGES_REQUESTED** [review]
Hi,
I tested your PR now and like mentioned above when I give user management permission to volunteer and try creating an account I'm getting an unexpected error message. I also noticed one thing that when I try to delete a user from volunteer account that user does not get deleted as it reappears after a refresh or after I move to a new page and come back to the user management page. I'm able to edit user. I'm attaching a screen recording of how it looks in my end.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/817e569e-1325-48ed-9e79-d8b685756b9c

**Comment by jerryren527** [comment]
Hi @robertoooc , @Haoj1 , @GaryB93 , @AuroraLovesWhales , @winghojackyli , @luisarevalo21 , @Shiwani99 ,

Thank you for your code reviews and bringing to my attention problems with the current branch. I have created FE PR #1312 and BE PR [#539](https://github.com/OneCommunityGlobal/HGNRest/pull/539) that should address the problems that you all have experienced testing this branch. If you have the time, I would greatly appreciate if you can test out those PRs!

**Pull request closed without merging**
