### PR TITLE
Jiadong replace badges section

### PR DESCRIPTION
**Pull request by yunshan111**
# Description
image
image

## Related PRS (if any):
This frontend PR is related to the #https://github.com/OneCommunityGlobal/HGNRest/pull/895
…

## Main changes explained:
replace badge section on the dash board to Timlog component
add number indicator
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
4. log as admin user
5. go to dashboard -> Other Links -> Badge Management -> assign a new badge to another user.
6. log out
7. Log in as the user who was recently assigned the badge.
8. Check the number indicator on the dashboard.
9. Click on the "Badge" tab to view the assigned badge.
10. Check if the number indicator reset to 0.

JAE'S ADDITION: IF GOING TO THE BADGES MANAGEMENT PAGE CRASHES THE APP FOR YOU, PLEASE COMMENT TO LET US KNOW AND THEN ADD IT TO THE TOP OF THE BADGES BUGS SECTION ON THE BUGS DOC. THEN COMMENT THERE FOR MY APPROVAL. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/4f18ff23-d1f3-4562-bd42-c5b69542eb6c

### CODE REVIEW

**Review by hbodgal — DISMISSED** [review]
Yes counter resets to 0. It works Fine. 

image

**Comment by alla0810** [comment]
1. checked out to Jiadong_Replace_Badges_Sectiong branch.
2. errors while login as admin.
3. many errors resolved after waiting for around 10secs, but some of them still remain.
4. badge count updated successfully, and 'badge' tab appears after 'Weekly Summaries' tab.
5. But unlike above mentioned, red number indicator not shown
6. badge count reset after another badge assigned by admin

client branch name

errors while login as admin

resolved after around 10sec

badge count not shown

**Review by aaryaneil — COMMENTED** [review]
Reviewed the changes and left a review on the [backend](https://github.com/OneCommunityGlobal/HGNRest/pull/895#pullrequestreview-1998740775)

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account and all described features work. It's nice that it doesn't allow clikcing on AssignBadge button before selecting a name. Good job!

**UI Suggestion 1:** When assigning badges and searching for the names, current UI show up as bullet lists. It's not very intuitive that user are choosing from a bullet list. Make it such that hovering over names will highlight the name would be a good alternative. The screenshot below is the bullet list I refer to:
Screenshot 2024-04-18 at 7 29 21 PM

**UI Suggestion 2:** The modal of selecting new badges displayed a long list. The Confirm button is at the very bottom which I didn't realize during the first try. A good alternative would be a list with scrollbar, such that the bottom row will always show up. The screenshot below is the badge list I refer to:
Screenshot 2024-04-18 at 7 53 58 PM

---
**Screenshots of functioning features:**
Confirmation of assigning badges:
Screenshot 2024-04-18 at 7 26 20 PM

Red indicator shows number of badges added: 
Screenshot 2024-04-18 at 7 29 37 PM

Clicking on Badge tab will reset the indicator to 0:
Screenshot 2024-04-18 at 7 29 40 PM

Pop up message that does not allow assigning badges until user entered a name:
Screenshot 2024-04-18 at 7 38 08 PM

**Review by SRamen1999 — DISMISSED** [review]
Everything works as expected. I am able to assign a new badge with an admin account. When logging into the account that was assigned the new bad the number indicator on the dashboard increased. When clicking on the badge tab the number resets to 0.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/992e3fcf-8baf-4b45-9405-fe1d9cb281e9

**Review by Tiantian-C — COMMENTED** [review]
Everything works fine!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/987c5f12-91bd-47d3-a13d-db101937aed1

**Review by Parth-tech — COMMENTED** [review]
Hey Jiadong,
I experienced a couple of issues while reviewing the PR. 

Steps performed:
1. Checked into the frontend and backend branch.
2. Executed `npm install`
3. Started backend server along with front-end server

Issues Faced:
1. I could not find the `Badges Tab` on my dashboard. 
2. The badgemanagement website would not load due to error (attached a screenshot). I  resolved the issue by commenting out the IF statement and simply returning 0 (BadgeDevelopmentTable.jsx -> FilterBadges Function -> comment IF statement.)

Screenshot 2024-05-04 at 11 19 10 PM
Screenshot 2024-05-04 at 11 19 23 PM
Screenshot 2024-05-04 at 11 36 22 PM

**Comment by cgomezhub** [comment]
to many erros during runnind this branch, please check out

Screenshot 2024-05-06 121933
Screenshot 2024-05-06 122329

**Review by cgomezhub — CHANGES_REQUESTED** [review]
to many erros during runnind this branch, please check out

Screenshot 2024-05-06 122329
Screenshot 2024-05-06 122633

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi, 
I've tried to review your changes. None of the changes expected are showing up for me

1. There is no Badges tab in the owner account
image

2. There is no badges tab in a volunteer account either
image

3. When I try to navigate to the badge management tab in the owner account, the application crashes, I have to refresh the localhost to get back to the dashboard.
image

**Review by peter6866 — CHANGES_REQUESTED** [review]
I have checked into your branch but have encountered the following errors:
1. Going to badge management page will crash the app.
image
2. no badges tab in the Dashboard.
image

**Review by Kavil-Jain-514 — COMMENTED** [review]
The //badgemanagement is crashing, throwing errors
image

**Review by Sandhya1236 — DISMISSED** [review]
I checked out the current branch, ran npm install and the necessary commands to set up the PR locally. I logged in as an admin user and navigated to the dashboard -> Other Links -> Badge Management to assign a new badge to another user. However, the Badge Management page failed to load due to an error in the FilterBadges function within the BadgeDevelopmentTable.jsx
image

**Review by dikshitakejriwal — CHANGES_REQUESTED** [review]
When I navigate to the badge management tab, the website crashes and throws a lots of errors as shown in the screenshot. 
Screenshot 2024-05-28 at 3 36 29 PM
Screenshot 2024-05-28 at 3 37 00 PM

**Review by Infinite-Turkey — CHANGES_REQUESTED** [review]
image
When I was trying to navigate to http://localhost:3000/dashboard/badgemanagement, nothing happened. But I could see the badge in my profile.

**Review by vishavk1992 — COMMENTED** [review]
i have tested this PR with backend PR . I was abled to assign badge but when it tried to confirm the badge then i got error message "OOPS something is wrong" 
PR-2146
pr-2146-1

**Review by nyelmela — COMMENTED** [review]
I attempted to test this PR by following the steps: checked into the current branch, ran `npm install`, and started the PR locally. I logged in as an admin user, navigated to the dashboard -> Other Links -> Badge Management, and tried to assign a new badge to another user. However, I encountered an error message saying "Oops, something went wrong" when attempting to assign the badge. 

image

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey @yunshan111 
When i tried to test out the PR, i had some  errors in the console .
Here is the attached LOG file for your reference
[localhost-badge.log](https://github.com/user-attachments/files/16395269/localhost-badge.log)
Thank You

**Pull request closed without merging**
