### PR TITLE
Shaun  people report page edit

### PR DESCRIPTION
**Pull request by ShaunSully88**
Merging my work as I won't be working on it anymore, someone new taking over. No issues with code, everything can be seen in my week 6 video on Dropbox as well as commit history.

### CODE REVIEW

**Comment by one-community** [comment]
Thank you Shuan!

**Comment by PrabhjotSembhi** [comment]
@one-community I think we can close this.

**Comment by one-community** [comment]
What the heck, I thought all of Shaun's work was merged ages ago... I'm going to share with Yiyun to get it checked in.

**Comment by EvianTan** [comment]
Closed it, I created a new one for this bug #687

**Pull request closed without merging**
