### PR TITLE
Yixiao CheckboxCollection unit test

### PR DESCRIPTION
**Pull request by JYXiao-2021**
# Description
Create a unit test for the CheckboxCollection component to confirm whether it working as intended.

## Main changes explained:
- Create file CheckboxCollection.test.js to do the unit test.

## How to test:
1.check into current branch
2.do npm install to run this PR locally
3.run npm test CheckboxCollection.test.js

## Screenshots or videos of changes:
Screenshot 2023-10-28 at 10 07 52 PM

### CODE REVIEW

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-01 at 1 19 36 AM

**Review by Shuhua-L — APPROVED** [review]
Hi, @JYXiao-2021 I ran the tests locally and everything passed as expected, nice work!

Screenshot 2023-11-01 at 3 28 33 PM

**Review by DavidC0126 — APPROVED** [review]
Hi @JYXiao-2021 I tested the PR and it works as described.

Screenshot 2023-11-01 at 8 20 25 PM

**Review by Jiyuanxia — APPROVED** [review]
Hi @JYXiao-2021 , I have reviewed your pull request and tested it. It works as you intended. Well done!
Screenshot 2023-11-02 133741

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
