### PR TITLE
Anne fix UI issues for Task table under people report page

### PR DESCRIPTION
**Pull request by Annezhang673**
# Description
Screen Shot 2024-09-07 at 12 17 03 PM
Screen Shot 2024-09-07 at 12 17 12 PM

## Related PRS (if any):
For backend use development branch
Previous PR [PR #2005](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2005)

## Main changes explained:
- Update file PeopleTableDetails.css

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin user
5. Add multiple tasks (combine with both short task name and long task name) for User A following [this instruction](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa). (make sure to add task hours)
6. go to dashboard→ reports→ people->User A (who has been assigned with tasks with one or more longer task names)
7. Check there's no text overlap between columns. 
8. Check the "End Date," is not moved under the first column, "Task," when resizing the screen.

## Screenshots or videos of changes:
Please refer to the following video for the bugs fixed. Note that I have already created the tasks and assigned to testing account prior. 

https://github.com/user-attachments/assets/57c4dc95-3619-4224-b2f7-cc71b3f89a6d

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by jinxyou — DISMISSED** [review]
The UI fix seems to be working fine. Great work!
Screenshot 2024-09-06 222455
Screenshot 2024-09-06 222505
Screenshot 2024-09-06 222519

**Review by linkhanthtel — DISMISSED** [review]
Texts are no longer overlap for screen size (375px and above). Nice work!

PR #2650
PR #2650 (2)

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.

image

Thank You

**Review by mohangadde1 — DISMISSED** [review]
image
working as expected, no overlapping of text.

**Review by CillianRen — APPROVED** [review]
image
The UI changes works great

**Review by SMitta11 — DISMISSED** [review]
Tested this and it works as expected .
But I have added 3 tasks for this user and it is showing only 2. It am not sure if it is related to this PR but could you please check if this expected result.
Screenshot:
Screen Shot 2024-09-07 at 6 49 27 PM
Screen Shot 2024-09-07 at 6 51 08 PM

**Review by Jingyii800 — DISMISSED** [review]
I have tested this feature and it worked as expected. Even though the task name is very long, the text won't overlap.

https://github.com/user-attachments/assets/2ba2c82f-1d46-4b3c-b8c8-9b1d13ef30ca

**Review by vishavk1992 — DISMISSED** [review]
i have tested this PR and it works as expected

Screenshot 2024-09-10 154344

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/8b1f6f0a-850e-4312-9303-ce8e374950bb

**Comment by KurtisIvey** [comment]
Hi Anne, I noticed there were merge conflict on this. Looks like it's just a CSS thing, but we'd love to get this moved to final review asap once it's cleared up

**Review by one-community — CHANGES_REQUESTED** [review]
This PR overlapped with this one. Please carefully fix conflicts and add this into your PR too: 
image

**Review by Watchdog00 — APPROVED** [review]
I have completed the testing and got the expected results. Good job!

**Comment by navya9989** [comment]
I have tested this PR and Everything is working as Expected
2650 #PR

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
