### PR TITLE
Howie make task link requried for submission

### PR DESCRIPTION
**Pull request by HowieMiao**
# Description
Added a requirement to add a link when submitting a task for completion

## Related PRS (if any):
N/A

## Main changes explained:
Updated src\components\TeamMemberTasks\ReviewButton.jsx to require a https:// link to allow submission

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard
6. verify that when submitting a task for completion without a **VALID** link it blocks you
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/d6fc2c43-2ae3-4ca4-8208-3e6d0170264f

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nishitag5 — APPROVED** [review]
The changes are working as expected. Verified this functionality in Dark mode.


https://github.com/user-attachments/assets/5375b330-1c4e-4d2d-a27c-ff9d923d7539

**Review by jinxyou — APPROVED** [review]
The function is working fine. Great work!
image

**Review by ArtemisNyx3 — APPROVED** [review]
[Nikita PR 2703 Test.webm](https://github.com/user-attachments/assets/0fa7067c-dbb8-42b6-a1b3-b66879dc40df)
Working up to speck 👍🏽

**Review by mohangadde1 — APPROVED** [review]
image
works as expected

**Review by sam19981 — APPROVED** [review]
changes work as expected.

Screenshot 2024-09-21 at 5 15 51 PM

Screenshot 2024-09-21 at 5 16 18 PM

Screenshot 2024-09-21 at 5 16 41 PM

**Review by ashayk9 — APPROVED** [review]
The functionality is working as expected
Screenshot 2024-09-21 at 4 45 34 PM

**Review by nevatiarishabh — APPROVED** [review]
I have tested the PR. Everything is working as expected.

Screenshot 2024-09-21 at 6 22 26 PM

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working as expected in light and dark mode. 
Screen Shot 2024-09-24 at 12 14 09 AM
Screen Shot 2024-09-24 at 12 21 39 AM

**Review by nikhilgiri0226 — APPROVED** [review]
image

It works as expected. It requires link.

**Review by mrinalini-raghavendran19 — APPROVED** [review]
Looks good to me and works as expected. Attaching screenshots of the working feature:

1.
Screenshot 2024-09-24 at 5 44 11 PM

2. shows that link is invalid if it is: 
Screenshot 2024-09-24 at 5 44 35 PM

**Review by SFA23SCM35V — APPROVED** [review]
Tested the PR by verifying task submission blocking for invalid links and confirmed the feature works correctly in both light and dark modes. All functionalities are working as expected.

**Review by ziyanw52 — APPROVED** [review]
I test this in dark mode and it works.
I also test by using some case such as add space before & after the link, and it do shows that this is an invalid link. Great job!

Space befre:
131727412950_ pic_hd

Space after:
141727412967_ pic_hd

**Review by neeharikakoniki — APPROVED** [review]
This PR adds a requirement for a valid "https://" link when submitting a task, ensuring proper validation during task submission. The feature works as expected in both regular and dark modes.

image

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and verified that when submitting a task for completion without a VALID link it blocks you.

Screenshot 2024-09-27 144354
Screenshot 2024-09-27 144425

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and its working as expected.


https://github.com/user-attachments/assets/4328bbd1-2566-4036-9f1f-a88bef097b2b

**Review by khushijain03 — APPROVED** [review]
Changes are working as expected. 
Screenshot 2024-09-27 at 7 29 25 PM


Screenshot 2024-09-27 at 7 30 06 PM

**Review by Gauravmg6 — APPROVED** [review]
The changes are working as expected.
Screenshot 2024-09-29 135748

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
