### PR TITLE
Jianjun - all three total report feature

### PR DESCRIPTION
**Pull request by juneluo**
# Description (7/22 Update)
**(PRIORITY HIGH) Jae: Create “Tasks Summary” on the Reports page**
**Note here: to avoid confusion, change 'task' to 'project' in this feature.**
Admin/Owner Login → Reports → Reports
In the view below, I need a “Total Tasks Report” button to see exactly how many new tasks have been worked on for a designated time period
Tasks must have had at least 1 hour logged to them to count 
Should be able to choose the period of time and the result should show on this page or as a Modal
Should include a “Total Hours” section showing total tangible time logged to all tasks during the selected period
Would like to run a “details” report that will list all the tasks too, with clickable names to visit their details
Need an “i” by the button to explain what the button does (all of the above)
This is needed because it is a metric we’re using from here on forward to measure the growth and progress of our nonprofit. So I want to be able to easily run this for individual months and/or an entire fiscal year to compare results with previous years.
A bar graph visualization of each month when seeing the yearly summary would be super helpful too

**(PRIORITY HIGH) Jae: Create “People Summary” on the Reports page**
Admin/Owner Login → Reports → Reports
In the view below, I need a “Total Team’s Report” button to see exactly how many total teams have contributed time to the project for a designated time period
Teams must have had at least 10 hours logged for them to count/be included
Should be able to choose the period of time and the result should show on this page or as a Modal
Should include a “Total Hours” section showing total tangible time logged to all teams during the selected period
Would like to run a “details” report that will list all the teams and hours contributed for each team for that time period too, with clickable names that will show who was on each team
Need an “i” by the button to explain what the button does (all of the above)
This is needed because it is a metric we’re using from here on forward to measure the growth and progress of our nonprofit. So I want to be able to easily run this for individual months and/or an entire fiscal year to compare results with previous years.
A bar graph visualization of each month when seeing the yearly summary would be super helpful too

**(PRIORITY HIGH) Jae: Create “Teams Summary” on the Reports page**
Admin/Owner Login → Reports → Reports
In the view below, I need a “Total People Report” button to see exactly how many total people have contributed time to the project for a designated time period
People must have had at least 10 hours logged for them to count/be included
Should be able to choose the period of time and the result should show on this page or as a Modal
Should include a “Total Hours” section showing total tangible time logged by all team members during the selected period
Would like to run a “details” report that will list all the people and hours contributed by each for that time period too, with clickable names to visit their profiles
Need an “i” by the button to explain what the button does (all of the above)
This is needed because it is a metric we’re using from here on forward to measure the growth and progress of our nonprofit. So I want to be able to easily run this for individual months and/or an entire fiscal year to compare results with previous years.
A bar graph visualization of each month when seeing the yearly summary would be super helpful too

## Main changes explained:
- Add three buttons that can hide or show the total report with data tips.
- For each feature, create the information card that shows the number of total qualified teams/people (with more than 10 hours) or projects (with more than 1 hour) and the total tangible time logged in this period.
- Two bar graph to show the number of the valid projects/members/teams monthly or yearly.
- A detail table listing all the teams/members/projects and the hours in the period.
- The detail table can show the list of team members or direct to the user profile page or project report page by clicking the team/user/project name.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. Admin/Owner Login → Reports → Reports
5. try to select different start/end date and then click the three buttons.

## Note:
Note that the two bar graph will not always show in this section. It depends on the length of the time period you select.
Now the conditions are as following:
The time period is less than one month: no bar graph.
between one month to about twelve month: show monthly bar graph.
The start date and the end date are in different year: show yearly bar graph.

### CODE REVIEW

**Comment by n0vay** [comment]
This functionality works as intended. This is great work!!
image

**Comment by n0vay** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/bac7ee11-6273-400d-a762-c9d4f38ac7e1



A small feedback from my side, if we click on Project people or teams from the category, then the report goes down too much. Maybe a scrollable list in a contained box would be a way to go.

**Comment by n0vay** [comment]
image


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/a9388744-8178-4297-9029-a84489daf4ed

image

The screen goes blank and opens a new window if the date is changed frequently

**Comment by juneluo** [comment]
> image
> 
>  Desktop.2023.07.15.-.14.31.15.03.mp4 
> image
> 
> The screen goes blank and opens a new window if the date is changed frequently

Great catch! The bug is caused by "when there is no qualified data in the year selected", for example, selecting time range before 2018. The latest commit will fix this problem. Thank you very much for the test and review.

**Review by shiva2096 — COMMENTED** [review]
Hi @juneluo 

The report is getting generated as expected, however there is no graph when the date range length is 1 month or less. Please ignore if this is an expected behaviour.

1. Data Range > 1 month
Screenshot 2023-07-15 at 2 55 53 PM

2. Date Range <= 1 Month
Screenshot 2023-07-15 at 2 56 05 PM

**Comment by juneluo** [comment]
> Desktop.2023.07.15.-.14.13.53.02.mp4 
> A small feedback from my side, if we click on Project people or teams from the category, then the report goes down too much. Maybe a scrollable list in a contained box could be a way to go.

As for this concern, I agree that it will be inconvenient to view when the list is too long. Now I set that the category list will be closed when we view(click) the total report button. I think when these three total report page button have been finished, we can also set that these three component will be closed when we view the category list data. So that we can avoid scrolling down to find another component.

**Comment by juneluo** [comment]
> The report is getting generated as expected, however there is no graph when the date range length is 1 month or less. Please ignore if this is an expected behaviour.

@shiva2096 Thanks for the review! Yes, so far the bar graph is expected to show and compare the growth and it will not show any graph if the time range is within a month.

**Comment by iTvX** [comment]
It looks good, and I like the UI.

However, I encountered some bugs. As evidenced in the video recording, the 'i' button near the total task report is not functional. Similarly, the 'i' button near 'show information' does not display any content upon clicking. Moreover, others 'i' buttons seem to overlap; they don't automatically disappear when a new 'i' button is clicked.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/8b140941-79ec-4f11-829e-f32c7393ad34

**Review by n0vay — APPROVED** [review]
Good Job!

**Review by HectorAgudelo — DISMISSED** [review]
This PR works as intended. However, on the graph when hovering, number of teams with more than 10 hours and the number of month should be better align. Probably showing the number of teams at the top of the bar and the number of months at the bottom of each year.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/56de59d5-9af8-47b5-b7a8-14e99c177bfd

**Comment by Jiangwei-shi** [comment]
I have already tested the current PR. The results are as expected. However, I also found that the "i" key near the "total task report" doesn't function. It probably lacks content. Moreover, I suggest that the duration of this tooltip should not be too long. As soon as the mouse leaves the "i" key, the tip should disappear immediately.
image
image

**Review by siddharthmohite — DISMISSED** [review]
This is amazing! Works Great.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37925823/206e63d9-da2c-4902-bc2a-246fe98f4351

**Review by NidaZaki — DISMISSED** [review]

**Review by AaronPersaud — CHANGES_REQUESTED** [review]
Hi, I've tested it and it works great!

<b>Choosing different date ranges and viewing the reports </b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/beaa0ec3-323a-465b-a23b-85d3c8ad8696

- "Total Team Report" tooltip is displayed on hover
- date picker works and user can manually edit the dates
- data and the respective graphs are displayed
- toggling Show/Hide details works

I noticed, however, that the tooltip for "Show details/Hide details" is not appearing for me. Looking at the code, I see you've implemented it and it looks fine, so I'm not sure why it isn't showing up. Can you confirm if it shows up for you?

<b>Show/Hide details tooltip not displaying</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/72fbfbfc-1964-4244-b656-a5d390a804be

I also have a few suggestions, although some might be outside the scope of this PR.

1.) Date pickers usually don't allow you to have the `endDate` before the `startDate`. There should be a way to have the `endDate` disable any dates values before `startDate`.

end_date_before_start_date

2.) The "Select a Filter" section is not related to the datepicker and reports section (Please correct me if I'm wrong). I feel like it'd make more sense to have these as 2 separate divs.

split_into_2_divs

3.) I feel like if there are no groups for the given time frame, we don't need the table header as there's no data to follow. I guess the show/hide button would also not be required for this scenario.

heading_noteams

All in all, great work!

**Comment by AriaYu927** [comment]
Hi @juneluo , I've tested your PR and it works perfect. Thanks for your work! 

However, I have a suggestion that might out of the scope of this PR. During test, I noticed that the "total team report" button works as a toggle button. So, it would be great if the text on button can change between sth like "total team report" and "hide total team report".

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/f606cae6-463e-48d2-8d01-b054c05494e8

**Review by BaileyM96 — COMMENTED** [review]
Good evening @juneluo I tested everything and it all works great! I did have a few issues that other users have reported

## Issues
1. When you open the developer log there is a few errors that point to the index.js file.
2. When opening the the "People" tab the graph gets pushed all the way down to the bottom of the page.
3. If you delete the start date the page becomes blank

## Video Walkthrough

Basic functionality working:

[PR #1005 add total team report.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/471a9911-1aca-409b-a2e1-767947e58056)

Video of bug:

[PR #1005 Add total team report ERROR.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/9b6109a5-39dd-4e8b-8921-e053c0393d50)

## Images

Image of errors in log:

PR #1005 log error  add total team report feature

**Review by luisarevalo21 — COMMENTED** [review]
Hello @juneluo 
I reviewed your PR and looks great. 


toggling members works.
picking a range to generate the report works
data is displayed on the graph


A few things I noticed, some people have also noted it as well. 
-the total task "i" doesn't show anything its blank 
Screenshot 2023-07-17 at 8 15 18 PM


- the delay when hovering over an "i" should be increased, hovering away should make the display disappear. 
- the "i" next to show details doesn't display when i click on "total team report" but does display on total people report 
- Also in this video if I hover over the text on the bar graph it continues to flash, that should be fixed. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/c7b25773-a489-4954-a158-08df8f69d75d

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/0fc705dd-e04e-4425-bc75-52911d12bc68

- when fetching from total people report, theres no text above the spinner but when i fetch from total team report there is text. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/2b8f58e3-5a63-4a72-ba43-32a4972b8785


-lastly, I think there should be a y-axis for the graph displaying what the y-axis is, which should be hours for this case. Since the x-axis is displaying the years.

**Comment by juneluo** [comment]
**Update:**
1. The 'total project/task report' feature was out of scope in this PR, but now all three 'total report feature' changes have been committed in this branch, this PR now includes all three report features.
2. Remove the delay of the data tip hovering.
3. Fix the no display bug of the data tip of the total team report card.
4. Fix the text flash problem in the bar graph and change the location of the months text as the suggested by the reviewers.
5. Show one feature at a time and automatically hide the other components. (for example, the previous opened section will not be pushed down by showing another section, it will be hidden)
6. Fix the bug: If you delete the start date the page becomes blank.
7. Fix the bug: the end date selected can be earlier than the start date. (It will not save the change if the date is invalid)
8. The button will have text 'show' or 'hide' according to the section selected.
9. Remove the hide/show detail button if there is no data in the selected time.

Note:
1. The warning seems to be not caused by the new features, i believe it will be better to fix them in another PR to accelerate the update in this PR.
2. The date picker seems to also be used as filters by the existing features other than the new features, so for now I am not going to make it a separate component with the three new buttons. The layout can be improved in the future with updated user flow.

**Review by yurisokolovicz — COMMENTED** [review]
Hi Jianjun,

Overall, excellent work! Just some minor adjustments needed.

I have the same suggestion as the guys above, but I can see that the "i" has been fixed. The Projects, Teams, and People sections, along with the show/hide button, are working fine. I no longer see the problem of the graphic appearing below the total/project/people/team at the bottom of the page. However, sometimes there's an issue with a "key-propertie" and a "personId" error appearing in the console. Please check if these errors are related to your modifications in the software.

Please review the video to see that things are working well in Chrome and to identify the errors I've mentioned. Also, take a look at the screenshot regarding the "key" prop and 'personId' error.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/e60a7a3b-7d2d-4577-b649-08de6c57e9ce


Screenshot from 2023-07-24 14-24-29
Screenshot from 2023-07-24 14-31-02

**Comment by juneluo** [comment]
> I have the same suggestion as the guys above, but I can see that the "i" has been fixed. The Projects, Teams, and People sections, along with the show/hide button, are working fine. I no longer see the problem of the graphic appearing below the total/project/people/team at the bottom of the page. However, sometimes there's an issue with a "key-propertie" and a "personId" error appearing in the console. Please check if these errors are related to your modifications in the software.

Thanks for the review. However, the warning of the customized component prop like 'projectId', 'personId' or 'teamName' are not caused by the content of this PR (they appear when you click the cards below 'select a category'). If you test it on the development branch, they will appear. The problem may be solved by create a link wrapper, however, I believe it will be a good idea to solve them in another PR so that we can follow the 'no multiple tasks/fix in one PR' rule.

**Review by eduvarjaor — COMMENTED** [review]
Hi @juneluo

This PR looks great.

But just an observation: tested with 3 time periods and in all, the bar graph appears.

1) Less than 1 month:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/a4f8c699-6830-4859-9e63-cce9673c6cba

2) 1 month ~ 12 months:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/3d2f3a67-407e-481c-aebc-2c2b42ee2efb

3) 1+ year:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/f2e02e9d-7290-4123-9a16-3fc333a1d0ba

**Review by AaronPersaud — APPROVED** [review]
Hi, I've tested again and it's looking great!

<b>Show/Hide Details Tooltip appearing</b>

image

- I can see the tooltip now

You also managed to address all the changes I requested, nice work!

1.) The date picker now stops you from choosing an end date that's before the set start date.

2.) I did not realize that the existing features also used the date picker, thank you for pointing this out. I agree with you leaving the component as is and not breaking into two divs.

3.) The "show/hide details" button is not shown when the date range has 0 teams that meet the criteria as requested.


<b>No "show/hide details" button with 0 teams</b>

image

**Comment by Shreyj14** [comment]
Hi @juneluo  Nice job on fixing the changes requested above. I tested the PR and was able to see the new changes requested earlier.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/6aacbda0-e79d-49cf-8556-9044f9d2f83a

**Review by Indujaks — APPROVED** [review]
The reports are displayed as expected! Greate Job.
Screenshot 2023-07-31 at 5 47 18 PM

**Review by zuhang2000 — CHANGES_REQUESTED** [review]
Hi I test this PR given your instructions. I test if this feature works as expected in three different cases: the time range is within 1 month, between 1 month and 1 year, and spanning over years. However, I do encounter several bugs when I tried with these different time range.

1. For the first test case that the time range is within one month, the graph is not showing which is as expected. But it is reporting errors. You may see those in the following screenshots.
Screen Shot 2023-08-03 at 11 38 45 PM
Screen Shot 2023-08-03 at 11 38 58 PM

2. For the second test case that the time range is within one year, it does show the graph in the beginning. However, when I set the time from 01/01/2019 to 10/01/2019, the graphs are gone when clicking all three buttons and reporting errors. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/9a333e0e-22b3-4f62-bbc4-f82560eeac40

I also notice that the when the time range spans several months, the numbers on the axis are overlapping with each other. The information are not shown clearly. You may check my recording here.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/1be88dfb-bfbd-4a2b-898d-7cef435e80de

3. For the third case that the time range spans over years. I found that no matter what time range I selected, the graphs are always showing the time range from 2018-2023. It does not update accordingly when I enter different time range such as 2019-2020 and 2019-2021.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/2bf21e14-2f0b-4fe8-be9d-00c27b045536

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, I have tested all three new buttons. All the features are work as intended. Check the video below. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/99163835-641e-410b-aa69-a5fe2785c577

The screen shoot show some error message, both pr#1005 branch and development branch have the same issue. 
Screenshot 2023-08-06 at 12 50 32 PM

**Review by navneeeth — APPROVED** [review]
LGTM!

Tested the buttons to generate reports for Projects, People, and Teams by changing the Start Date and End Date:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/4d049fe3-3090-4d98-a99e-746cf44663b8


-

**Review by yunshan111 — APPROVED** [review]
Tested your changes, LGTM!

image

**Review by Jiyuanxia — COMMENTED** [review]
Hi @juneluo,I have reviewed your pull request and conducted testing. I'm pleased to report that everything is working as expected. Great job!

Total project report with clickable name list
Screenshot 2023-08-10 180611

Project details after clicking the project name
Screenshot 2023-08-10 181046


Total people report with clickable name list
Screenshot 2023-08-10 180621

Total team report with clickable name list
Screenshot 2023-08-10 180641

"i" by the button to explain what the button does
Screenshot 2023-08-10 181206

Total project report with clickable name list when the time period is less than a month
Screenshot 2023-08-10 180918

**Review by DavidC0126 — APPROVED** [review]
Hi @juneluo, the PR works as described. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/3e0c3307-a130-4945-b2d2-c415ab34723d

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works good on my device. @juneluo 
image
image
image

**Review by ThapeloMasasa — APPROVED** [review]
The reports are displayed as expected

Screenshot 2023-08-11 at 7 29 15 PM

Screenshot 2023-08-11 at 7 30 49 PM

Screenshot 2023-08-11 at 7 34 35 PM

**Comment by Lin1404** [comment]
This functionality works as intended. Good Job!

image
image
image

Date changed:
image
image
image

**Review by Lin1404 — APPROVED** [review]

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this one to final review!

**Review by veronicacheng2 — APPROVED** [review]
Hi @juneluo, I tested the PR and everything works perfectly. I can view all the reports, hide the reports and see the details of the report. Good job!

#### Total Team Report
image


#### Total People Report
image

#### Total Project Report

**Comment by AnishPandita** [comment]
Hey, I tested the PR and the functionality around viewing of reports works well.
Screenshot 2023-08-26 at 2 35 44 PM
Screenshot 2023-08-26 at 2 34 56 PM
Screenshot 2023-08-26 at 2 34 47 PM

**Review by EdwinLauM — APPROVED** [review]
Hey @juneluo! Changed work as expected and it looks good! Great job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/6ee6db8d-335e-4ddd-a8b2-c65c69b7f30b

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/b4dbcbc5-6d2f-43fe-9b16-4a388c732a24

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/4fa916a2-bc01-41e4-a1cd-5ffd827281c0

**Pull request merged**
