### PR TITLE
Jiangwei - create unit tests for the TeamTable component

### PR DESCRIPTION
**Pull request by Jiangwei-shi**
# Description
Create a unit test for the TeamTable component to confirm whether it working as intended.

## Main changes explained:
- Create file TeamMembersPopup .test.js to do the unit tests

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. open file src → tests → TeamTable .test.js
4. run npm run test src/__tests__/TeamTable.test.js 

## Screenshots or videos of changes:
This is the result it's supposed to get:

屏幕截图 2023-10-28 214355

## Note:
If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by zuhang2000 — COMMENTED** [review]
Hi, I've tested your PR following your instructions. Your PR seems good to me. All tests passed.
Screenshot 2023-10-28 at 11 45 22 PM

**Review by savio-henrique — APPROVED** [review]
Hi @Jiangwei-shi , I've tested your PR, all tests passed without any errors! Great work! :+1: 

# Screenshot

terminal

**Review by wantingxu7 — APPROVED** [review]
Hi @Jiangwei-shi 
i've run the command "npm run test src/__tests__/TeamTable.test.js" and got the "PASS" massage. Good work!

**Review by luisarevalo21 — APPROVED** [review]
Hello @Jiangwei-shi ,

I tested your PR and works as intended. Great work!
Running your test passes all the test as stated. 

Screenshot 2023-10-30 at 7 50 50 PM

**Review by DavidC0126 — APPROVED** [review]
Hi @Jiangwei-shi I tested it and it works as intended.
teamtable

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I run the `npm run test src/__tests__/TeamTable.test.js` and all the test cases are passed. Great work!

Screenshot 2023-10-31 at 4 15 22 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great work! 

Screenshot 2023-10-31 at 11 53 36 PM

**Review by tsunami776 — APPROVED** [review]
Hi @Jiangwei-shi, the mock data and tests in your unit test look good to me. I ran the unit test locally and all tests passed with no error thrown. Nice work!
CleanShot 2023-11-02 at 21 46 31

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-11-02 235224

**Review by malikjahanzaib — APPROVED** [review]
Hi @Jiangwei-shi, all tests passing. Nice job!!!

Screenshot:

image

**Review by kavya151 — APPROVED** [review]
Hi @Jiangwei-shi , I have reviewed the PR and all the tests passed. Good job!
Screenshot 2023-11-04 at 8 58 25 PM

**Review by cvtqx — APPROVED** [review]
All tests pass, great job!
Screen Shot 2023-11-10 at 5 39 45 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
