### PR TITLE
Xiao F Create way for owner to edit & update ChatGPT prompt text

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-11-10 at 11 19 59

## Related PRS (if any):
To test this front-end PR you need to checkout the [#603](https://github.com/OneCommunityGlobal/HGNRest/pull/603) back-end PR.

## Main changes explained:
- Update file `src/components/WeeklySummary/CurrentPromptModal.jsx` to get and update prompt with a fallback prompt if error occurs
- Create and update multiple files for reducer function of get and update prompt

## How to test:
1. Check into current branch
2. Do `npm install` and `npm run start:local` to run this PR locally
3. Clearing cache/site data
4. Log in as owner user
5. Go to dashboard -> Summary -> View and Copy Current AI Prompt -> Edit prompt -> Save
6. Check if prompt is updated
7. Check if 'Copy Prompt' works as intended
8. Log in as roles other than owner
9. Go to dashboard -> Summary -> View and Copy Current AI Prompt -> Make sure 'Edit' does not appear

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/69ddb11d-4889-4fe4-b841-2af83f120c47

## Note:
N/A

### CODE REVIEW

**Review by Jiyuanxia — COMMENTED** [review]
Hi @tsunami776 , I have reviewed your pull request and tested it. It works as you intended. Well done!

prompt is editable
Screenshot 2023-11-16 184932

successfully edited after refreshing
Screenshot 2023-11-16 185011

copy functions well
Screenshot 2023-11-16 185024

edit button disappear while logging as volunteer role
Screenshot 2023-11-16 185106

**Comment by this-journey** [comment]
Just finished reviewing your changes and everything works as intended.  See attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/68d3a57a-db47-4627-9eb1-0bf2df078cb4

**Comment by DragonSlayer2401** [comment]
I tested your PR on both an Owner and Volunteer account. On the owner account, the edit button appeared, and the edit functionality worked as intended. On the volunteer account, the edit button did not appear as intended. On both accounts, I was able to copy the prompt as intended. Please see the overview video for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/5d74f02d-4433-4641-8172-3f3ee02ab046

**Review by ZichanYang324 — DISMISSED** [review]
Hi @tsunami776 

I have tested all the new features, and all of them worked as intended.
(1) When I log in as Owner, I can click on the edit prompt and change the current prompt. 
(2) After saving the prompt, I can also use the copy function, no error occurred.
(3) When I log in as a Volunteer, I cannot edit the prompt, I only see the latest change for the prompt. 
(4) the copy function worked very well for the volunteer role.

Here are the two videos for the test process.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86720318/eade18a4-29c8-48ae-98eb-ca6d82de70f8


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86720318/1b501ffc-2139-44cf-839c-6d952e613a2a

**Review by sucheta90 — COMMENTED** [review]
Hi @tsunami776 I conducted tests on this PR both as the Owner and as a Volunteer. Upon my initial login and clicking the "View and Copy Current AI Prompt," I noticed that the default prompt was not displayed. However, I managed to rectify this by clicking the edit button and pasting the prompt into the box, successfully saving it. I believe it would be beneficial if the default prompt could be set in the initial state. This would allow users to easily copy the prompt in the case of a Volunteer, and Owners could then have the option to edit the prompt as needed.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/da94b44f-5586-45b8-9184-16ef48e04c3d

I don't see any issues other than the one mentioned earlier. Overall, the features are working as intended. Great job!

**Review by pika-chu11 — DISMISSED** [review]
Hi @tsunami776 , I have tested your PR with different roles of account. The code works as intended that only the **Owner** have the permission to edit the ChatGPT prompt text while other account like _Manager, Mentor, CoreTeam, Volunteer, and Admin_ cannot do that.
Great Job!
Check the video below for details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/5496b817-ed29-4589-a47e-6ab26ce7940d

**Review by Alforoan — DISMISSED** [review]
It all seems to work as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/26456a13-7159-47aa-b2ba-d3ea051cbc55

**Review by keyunhuangg — DISMISSED** [review]
Everything works as it described.
1) Logged in as owner, edit and save the current ai prompt. 

Screenshot 2023-12-22 at 12 51 09 PM

2) clicked the copy button and paste it onto the summary text box
Screenshot 2023-12-22 at 12 51 27 PM

3) logged in as volunteer and the edit button is not present
Screenshot 2023-12-22 at 12 52 09 PM

**Review by ljrirene — APPROVED** [review]
Good job Xiaofei, everything works perfectly on my side.

Uploading Screen Recording 2023-12-23 at 17.47.19.mov…

**Review by ljrirene — DISMISSED** [review]
Good job Xiaofei, everything works perfectly on my side.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/79ac8aa2-e445-405e-9ba4-5ab24869ca4b

**Comment by mianmiantea2019** [comment]
Hi @tsunami776 , I have reviewed your pull request and tested it. It works as intended.  Good Job!

- Logged in as owner, edit and save the current ai prompt.

test1510_1

test1510_2

Logged in as volunteer, the edit button is not present and see the updated prompt

test1510

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by cvtqx — APPROVED** [review]
Tested this PR and everything works as described.
1. Logged in as admin and I do not see Edit button:
Admin

2. Logged in as owner, I see the Edit button and am able to edit the prompt successfully:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/f20c040c-ef3d-4e0b-a0fd-261b80d753b8

**Comment by Haoxiang310** [comment]
Tested using both owner account and admin account.
Edited the prompt using owner account:
PR5-#1510(owner)
In the admin account, the prompt cannot be edited:
PR5-#1510(admin)

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
