### PR TITLE
Eduardo - Bug fix project report page freezes

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
When accessing Project Report's page the browser completely freezes.

## Main changes explained:
Added a termination condition to the while loop on the `get_task_by_wbsId function`.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to Reports -> Reports -> Projects -> Pick Any
5. verify if the page render correctly

## Screenshots or videos of changes:

BEFORE:
image

AFTER:
Screenshot 2023-07-12 10-01-21

### CODE REVIEW

**Review by HectorAgudelo — APPROVED** [review]
The issue seems to be fixed. The pr was tested and the changes to the code do what they are supposed to. When declaring variables try to use let or const accordingly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/db21ebcf-02b4-4104-90dd-c2cb32a4599e

**Comment by beblicarl** [comment]
This functionality works as intended and the code looks good. Great work! 

[screencast-hgnapplication_react_beta.surge.sh-2023.07.12-16_36_12.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/2c95a7e4-3717-461e-bb8b-158b4f2097b2)

**Review by beblicarl — APPROVED** [review]

**Review by tdkent — APPROVED** [review]
Tested Reports > Reports > Projects > Project, loading several different projects, clicking through to user profiles, etc. The page remained responsive with no crashes. 

Nice work!

- Note: I was not able to replicate the page freeze bug on the development branch.

Testing Video:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/60835b58-1214-495a-81e5-22fc34bfedfe

**Review by BaileyM96 — CHANGES_REQUESTED** [review]
Good evening @eduhorta I tested your changes and everything works as intended. Great work!

## Issues 

I ran into a bug while testing your feature and the it is on the Reports --> Projects --> Project --> Tasks. When clicking on the actual word "Active" it unchecked the "Assign" button. That feature might not be related to your PR but is something to note.

## Videos

Video walkthrough to show feature works as intended:
[Page Freeze #999.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/6beb0893-e634-4c16-bce6-e55349b9528a)

Video of Tasks bug:
[Button bug on tasks  in projects.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/e290d5e1-5280-4637-8f4d-79d024679c8b)

**Review by siddharthmohite — APPROVED** [review]
The code works as intended. There is no page freeze when accessing the reports page. As someone pointed out, there is an issue with the active button when clicking on the word part of it, the assign button gets checked.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37925823/fe920e32-9e77-4f55-b7eb-144208a53375

**Review by AaronPersaud — APPROVED** [review]
I've tested it and it looks good! No freezing for me.

<b>Navigating through Projects section without crashing</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/d4f67ddc-053d-4082-aa17-62d65a518df3

- able to click through the pagination and the toggling 
- able to click the dropdowns 
- project loads all the members and tasks without freezing, even where there's several members/tasks

One strange thing I noticed was I was able to replicate the issue on [https://hgnapplication_react_dev.surge.sh/](https://hgnapplication_react_dev.surge.sh/) but I couldn't replicate it locally on the development branch.

**Review by luisarevalo21 — APPROVED** [review]
Hello @eduhorta,

I tested your PR and works as intended great job!
The app no longer freezes and continues to run no problems. 

A side note: I agree with [HectorAgudelo](https://github.com/HectorAgudelo), use "let" and "const" instead of "var" for best practice. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/b8e1d21b-a4f9-4c36-a575-c6819c859813

**Comment by luisarevalo21** [comment]
Hello @eduhorta,

I tested your PR and works as intended great job!
The app no longer freezes and continues to run no problems. 

A side note: I agree with [HectorAgudelo](https://github.com/HectorAgudelo), use "let" and "const" instead of "var" for best practice. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/b8e1d21b-a4f9-4c36-a575-c6819c859813



> Good evening @eduhorta I tested your changes and everything works as intended. Great work!
> 
> ## Issues
> I ran into a bug while testing your feature and the it is on the Reports --> Projects --> Project --> Tasks. When clicking on the actual word "Active" it unchecked the "Assign" button. That feature might not be related to your PR but is something to note.
> 
> ## Videos
> Video walkthrough to show feature works as intended: [Page Freeze #999.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/6beb0893-e634-4c16-bce6-e55349b9528a)
> 
> Video of Tasks bug: [Button bug on tasks in projects.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/e290d5e1-5280-4637-8f4d-79d024679c8b)

For those who can fix this bug.
The error is in Checkbox.jsx. the "htmlFor" is set to "assign" which should be "id" instead since it's being passed down via props and provides the correct name.

**Comment by AnishPandita** [comment]
Hi @eduhorta the functionality works as intended. The freezing problem seems to be solved.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/6846bdae-51ac-4b49-b0d8-5e0bd659334a

**Review by iTvX — APPROVED** [review]
Following a series of operations, which included initiating several distinct projects, navigating to user profiles and the like, the page held up admirably with zero instances of crashes through out the process of Tested Reports > Reports > Projects > Project. Good job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/2a305da2-691a-4927-9a69-4768ebbbac67

**Review by xaanders — APPROVED** [review]
Hi Eduardo! 
I've tested your changes. Everything works as intended. 
No freezes at all. 
Good job! 
[pr999.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/b4fa6d51-10bc-40f5-8fc1-ef85298c966d)

**Review by NidaZaki — APPROVED** [review]
Works great!

**Review by ramyaram2092 — COMMENTED** [review]
Hello @eduhorta  
I locally  wanted to reproduce the bug in development branch before I tested the  fix . However I couldn't reproduce  the issue it in the development branch. Could you help me understand the fix ?

**Comment by Jiangwei-shi** [comment]
I've tested it. Everything works as intended. No crash during  Reports > Reports > Projects > Project
image

**Comment by eduhorta** [comment]
> Hello @eduhorta I locally wanted to reproduce the bug in development branch before I tested the fix . However I couldn't reproduce the issue it in the development branch. Could you help me understand the fix ?

Hey @ramyaram2092!
You have to go to "Development Branch", then Reports -> Reports -> Projects -> Pick Any and the browser will freeze.

If that is not happening to you, please try to access it on an anonymous or clear your cache. 
So you won't have anything on your cache regarding the Project Report's page.

**Review by vemanamadhu — APPROVED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13665284/99ac7e83-d6ba-4682-9eed-7cd89195de8a


It looks good to me. The code is fine too. Good job Eduardo

**Pull request merged**
