### PR TITLE
Changhao - Unit tests for DeleteUserPopup.jsx

### PR DESCRIPTION
**Pull request by lichanghaogit**
# Description
Unit tests for DeleteUserPopup.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm test DeleteUserPopup.test.js` to run this PR locally
3. verify all 20 tests are passed.
## Screenshot:
Screenshot 2023-12-13 at 10 10 07 PM

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 
Screenshot 2024-01-15 at 4 20 03 PM

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed as expected. Please watch the overview video for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/705d3894-445d-40fa-a50a-9a14d829015e

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 21 - PR6

**Comment by Lin1404** [comment]
@Changhao3220K I tested your PR and all the test cases passed!

image

**Review by Lin1404 — DISMISSED** [review]

**Review by ShengjieMao — DISMISSED** [review]
All tests passed. Great work!
PR_1832

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Changhao,

All tests passed. Nice work! 

Screenshot 2024-01-29 at 17 33 53

**Review by peterson337 — DISMISSED** [review]
All tests passed

a

**Review by 666saofeng — APPROVED** [review]
All tests passed and everything worked as intended.
image

**Review by Pandani07 — DISMISSED** [review]
All test cases passed and the app works as it should!
Screenshot 2024-02-08 at 6 03 07 PM

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
file location

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and worked as expected.

imagem1

**Pull request merged**
