### PR TITLE
Jiadong - Replace Badges Section on Dashboard 

### PR DESCRIPTION
**Pull request by yunshan111**
# Description
image
image

## Related PRS (if any):
This frontend PR is related to the #https://github.com/OneCommunityGlobal/HGNRest/pull/1053
…

## Main changes explained:
replace badge section on the dash board to Timlog component
add number indicator
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
4. log as admin user
5. go to dashboard -> Other Links -> Badge Management -> assign a new badge to another user.
6. log out
7. Log in as the user who was recently assigned the badge.
8. Check the number indicator on the dashboard.
9. Click on the "Badge" tab to view the assigned badge.
10. Check if the number indicator reset to 0.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/476243f0-9309-4d25-8df2-4062e0e72453

### CODE REVIEW

**Comment by arunsrao9** [comment]
I have tested the PR by assigning 3 badges to my volunteer profile, looks good:
Screenshot 2024-08-02 at 11 13 00 PM

But when i check on my volunteer profile, next to the badge it says 0, but if i click it i can see the badges:
Screenshot 2024-08-02 at 11 18 57 PM

Screenshot 2024-08-02 at 11 19 00 PM

**Review by manikittu810 — APPROVED** [review]
Hello @yunshan111 
Reviewed the PR.  Followed the above steps and everything is working as mentioned. Find the recording below.

https://github.com/user-attachments/assets/e9eaa11a-bda6-4f17-ba78-1824aa2c780d


Thankyou.

**Review by Gauravmg6 — APPROVED** [review]
I assigned badges to my volunteer account from my admin account. Everything is working as expected.
Screenshot 2024-08-03 192224

**Review by varunreddy03 — DISMISSED** [review]
I have tested this PR by checking into frontend and backend branches. And I have assigned multiple badges from the admin user to my Volunteer user and the badges were assigned successfully and then the badges number notification was accurate and it got reset to zero after opening.

PR 2529_1
PR 2529_2

**Comment by souravwalke** [comment]
I tested the PR and found an issue. The number of badges in the dashboard resets to zero even though the user has four badges assigned to his name. The problem is only found in the dashboard section, "view profile" works as expected.

https://www.loom.com/share/1f2abb8d63f340e48d2dc226e6f71abf?sid=cfb65b71-9ec9-47b7-bcb6-8a94ba5df847

**Review by jinxyou — DISMISSED** [review]
The badge number seems to be fine, after I assigned a badge to the member. Great work! 
Screenshot 2024-08-03 221056
Screenshot 2024-08-03 221107
Screenshot 2024-08-03 221355
Screenshot 2024-08-04 012942

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR successfully and it works as expected . I assigned badge to my volunteer account from my owner account . For reference i have attached screenshot here. 

Screenshot 2024-08-06 152654
Screenshot 2024-08-06 152708
Screenshot 2024-08-06 152838

**Review by Parth-tech — DISMISSED** [review]
Hey Jiadong,
The PR meets it required functionality and the codebase looks good too. 
When new badges are assigned the counter correctly indicates the number of badges assigned. Once the badges are visited then the counter resets itself to 0.

Image References:
Screenshot 2024-08-06 at 5 40 15 PM
Screenshot 2024-08-06 at 5 40 25 PM

**Review by Aishwarya0898 — DISMISSED** [review]
Hello Jiadong, 
I have tested this PR and it is successfully working as mentioned. I assigned badge to my volunteer test account from my owner account . Here are the screenshots for reference.
Thank you.
PRReview1_1
PRReview1_2
PRReview1_3
PRReview1_4

**Review by DiyaWadhwani — DISMISSED** [review]
Hi,
Reviewed your changes and they work as expected.
Attached a video of testing below.
Thank you

https://github.com/user-attachments/assets/9042866e-6f0a-4831-a627-2ca864f3ee1e

**Pull request merged**
