### PR TITLE
Anand_BadgeManagement_Unit_Test

### PR DESCRIPTION
**Pull request by anandsesha**
# Description
Tested badge validation and assignment logic - including Redux actions, API calls, error handling, and success messaging.

Test case file: `src\components\Badge\__tests__\BadgeManagement.test.js`
Reference: `src\actions\badgeManagement.js`

## Related PRS (if any):
none

## Main changes explained:
`validateBadges` function:
- Tested validation logic for missing first and last names, ensuring appropriate error messages are shown when necessary.
- Verified that no actions are triggered if both names are provided.

`assignBadges` function:
- Checked error handling when no badges are selected, ensuring the appropriate error message is displayed.
- Verified API call to fetch the user profile by name and handled the case where the user is not found.
- Tested successful badge assignment by confirming that a PUT request is made to the server and appropriate success messages are displayed.
- Ensured proper error handling and messaging when server issues occur during the badge assignment process.

## How to test:
1.Check into current branch
2. Do npm install
3. Do npm test -- BadgeManagement.test.js to run the test
4. Verify that all test cases pass successfully

## Screenshots or videos of changes:

BadgeManagement unit tests
validateBadges:
validateBadge
assignBadges:
assignBadge

### CODE REVIEW

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture2740

**Review by ziyanw52 — APPROVED** [review]
Hi, I have test this and all test cases passed successfully!
WeChat548304d418c3a992c75616985be15a7d

**Review by Dk-21 — APPROVED** [review]
PR 2740
@anandsesha 
Tested the unit test file and all test cases passed.
Screenshot 2024-09-30 at 8 23 24 PM

**Review by RishithaMamidala — APPROVED** [review]
@anandsesha 
All unit tests for the validateBadges and assignBadges functions passed. The validateBadges function correctly handled missing names with appropriate error messages, and proceeded when both names were present. The assignBadges function handled errors for missing badges, fetched user profiles by name, successfully assigned badges, and managed server-side errors gracefully. No issues were encountered.
PR 2740

**Review by anirudhsk2107 — APPROVED** [review]
All tests have passed 

PR_2740

**Review by slidracoon72 — APPROVED** [review]
#2740
@[anandsesha](https://github.com/anandsesha)
Verified the unit test file, and all test cases successfully passed.

PR 2740

**Comment by tharunaa-1** [comment]
For this PR all the Test cases has been Passed!

image

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR and all test cases passed successfully.

**Review by Vincent-space — DISMISSED** [review]
I've tested them, all of the test cases passed.
image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (214)

**Comment by geetamatkar** [comment]
Hi @anandsesha ,
Tested this PR and all test cases have passed.

PR2740

**Comment by pallavithorat** [comment]
This PR has cleared all test cases! Screenshot attached for confirmation.
PR #2740

**Review by nikhilgiri0226 — APPROVED** [review]
All test cases passed
Screenshot_2740

**Review by AshishNags — APPROVED** [review]
Tested BadgeManagement.test.js file, all test cases passed successfully

PR 2740

**Review by jinxyou — APPROVED** [review]
All test cases have passed. Great work!
Screenshot 2024-10-04 164932

**Comment by SatyashanthiT** [comment]
I have reviewed this PR, gone through the code changes related to badge validation and assignment logic, and tested the unit tests. All test cases ran successfully, confirming that the logic is working as expected.
image

**Review by Abi-Liu — APPROVED** [review]
Looks good! Everything passes as expected
Screenshot 2024-10-04 at 9 24 46 PM

**Comment by navya9989** [comment]
I have tested 1 unit from this PR and the test cases passed Successfully
2740# PR

**Comment by beblicarl** [comment]
all tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
