### PR TITLE
Chetan Fixed email validation and location of success message

### PR DESCRIPTION
**Pull request by Chetan0606**
# Description
Fixed the email validation part and the placement of success message
image
Fixes # (bug list priority medium)

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Added the email validation part to index.jsx
- Made the success message position changes in sendEmails.js
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ Other Links→ Send Emails → Enter the email list separated by comma → Click send email to specific user
6. verify if you are getting an invalid email message in the top right corner if you have entered an invalid email and a success message when it's a valid one.
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/c7ab1669-b23e-4edd-b764-e7ce0e92ea71

### CODE REVIEW

**Review by SrikanthChowdary495 — APPROVED** [review]
Everything working as expected. Also, I have gone through the code it looks great. verified if you are getting an invalid email message in the top right corner if you have entered an invalid email and a success message when it's a valid one. Great work!

https://github.com/user-attachments/assets/c8d47e16-ca1e-426e-993f-8c32c658a937

**Review by varunreddy03 — APPROVED** [review]
I have tested this PR and it works as expected in both light and dark mode, it is taking valid input for one or more emails and also testing the validity of email using regular expressions and it is working for all the test cases. And the success and error messages are aligned to the right side of the page.

Screenshot 2024-08-10 193710
Screenshot 2024-08-10 193727
Screenshot 2024-08-10 193801
Screenshot 2024-08-10 193920
Screenshot 2024-08-10 193957

**Review by Gauravmg6 — APPROVED** [review]

**Review by Gauravmg6 — APPROVED** [review]
Everything works as expected.

Screenshot 2024-08-11 005809
Screenshot 2024-08-11 005837

**Review by manikittu810 — APPROVED** [review]
Hello @Chetan0606 
The email string validation pattern using regex looks good.

Screenshot 2024-08-11 at 4 16 31 PM

Thank you.

**Review by Aishwarya0898 — APPROVED** [review]
Hi @Chetan0606 

This PR is working as expected. Here is the reference, Great Job!


https://github.com/user-attachments/assets/c7cfc550-f9e3-441a-ad1b-0311bbd6ac70

**Review by Pranay-ai — COMMENTED** [review]
The PR is working as expected please find the screenshots for reference.
image

image
image

Thank You

**Review by Pranay-ai — APPROVED** [review]

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and it works good as expected.


https://github.com/user-attachments/assets/3468a098-ee2d-4b76-b3d9-829a8bc9af84

**Review by vijay10pk — APPROVED** [review]
Changes are working as expected.
Screenshot 2024-08-13 at 10 52 22 PM
Screenshot 2024-08-13 at 10 52 03 PM

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

image

image

image

**Review by beblicarl — APPROVED** [review]

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/2cf7903d-7bcf-4c88-8c58-d419812229a6

**Review by preethamdnr — APPROVED** [review]
Hello Chetan,
I have checked this PR and working as expected in both the modes.
image
image
image

**Review by abdel-lall — APPROVED** [review]
LGTM, Good job!
Screenshot 2024-08-17 213941

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
