### PR TITLE
Masasa - Fixed Scrolling issue 

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
# Description
This PR aims at fixing the horizontal scroll issue that was in the teams page. As described in the image below, the when the page was shrunk the buttons would be inaccessible.
Screenshot 2024-01-10 at 8 27 01 PM

## Related PRS (if any):
This frontend PR is not related to any backend, so please use the development branch for the back end
…

## Main changes explained:
- Added a css file for the Teams component so that even future formatting can be added there
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ other links→ Teams→…
6. verify function that upon shrinking the window you can scroll to have access to the buttons

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/d899a97b-51ec-483f-84bb-a9356605bed5

### CODE REVIEW

**Review by bajajtushar094 — APPROVED** [review]
Hi @ThapeloMasasa, I reviewed your PR and it is working as described. Thanks 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/841b6863-c69d-450d-850e-f99ade55492e

**Review by bienzguoa — APPROVED** [review]
Works as described. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/32ec0461-5321-4ea2-9496-f26e821e7aad

**Review by scoopstroop92 — APPROVED** [review]
Works as expected . Good job @ThapeloMasasa 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/87726eda-b1d1-4eab-9767-cbf4bf2c1a6e

**Review by n0vay — APPROVED** [review]
LGTM
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
