### PR TITLE
Jingyi-Interact with Task "Ready for Review" button

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
Give the user permission to interact with any "Ready for Review" task button to either mark it as complete or reset it with "More work needed, reset this button" 

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- use dispatch to check the permission for conditional rendering in React

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to "Other Links" -> "Permission Management" -> "Manage User Permissions"
6. In the permission management section, grant a volunteer account without the permission "interact with any 'Ready for Review'" permission.
7. log in to this volunteer account and in the dashboard -> tasks. Check if this volunteer can interact with the "Ready for Review" task button.

## Screenshots or videos of changes:
Screenshot 2024-05-11 001835

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/b63d7713-57b3-4e93-9fe2-fa4c27c31ab0

### CODE REVIEW

**Review by hbodgal — APPROVED** [review]
image

it works well. I was able to interact with "Ready for Review".

**Review by peter6866 — APPROVED** [review]
Changes work as expected!
image
image

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and it works as intended. Great Work! Below is a video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/738ae3ae-8765-41f7-b38c-d363df66c19f

**Review by Pranay-ai — APPROVED** [review]
Hey @Jingyii800 
I have just reviewed the functionality it's working as expected.
image

Thank You.

**Pull request merged**
