### PR TITLE
Ajay - fix verified the user data and fixed the UI/UX issues of the user list.

### PR DESCRIPTION
**Pull request by AJAYINAVOLU**
# Description
This pull request fixes the issue where the Team Locations search results did not display all columns properly by widening the search list box to show all three columns (Name, Email, Location). It also adds sorting functionality to the "User List," allowing users to sort by Name or Location in ascending and descending order. These changes address previously reported usability issues and enhance the overall user experience. Related problems are from previous [PR2276](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2276) and reported search issues on the Team Locations page.

Fixes # (PRIORITY HIGH)  Tatyana → Fix TeamLoc option Search

## Related PRS (if any):
This frontend PR is related to the development backend branch.

## Main changes explained:
- Updated ListUsersPopUp.jsx: Added sorting functionality and state management to allow sorting user profiles by Name/Location.
- Updated TeamLocations.css: Adjusted the table width to auto to ensure all columns are displayed properly.
- Updated TeamLocations.jsx: Removed unnecessary class that was affecting the layout.

## How to test:
1. Check into the current frontend branch and the development backend branch.
2. Do npm install and npm run start:local to run this PR locally.
3. Clear site data/cache.
4. Log in as an owner-user.
5. Go to dashboard→ Reports → Team Locations.
6. Verify that the search bar is working fine by typing a name, and the user list suggestions are rendered properly with the correct width.
7. 
image
9. Next, verify that the User List is working fine by clicking on the User List button beside the search bar and the users' location list is rendered properly.
10. 
image
12. Finally, verify the sorting function is working on the users' location list for name and location by clicking on Name/ Location.
13. 
image

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/be301c86-cc5b-4133-8a2b-d073d62fdffd

**Review by abdel-lall — APPROVED** [review]
LGTM. nice job!
Screenshot 2024-10-06 012929
Screenshot 2024-10-06 012909

**Comment by pallavithorat** [comment]
Hi, I reviewed the PR and verified that the search bar is functioning correctly. When typing a name, the user list suggestions are rendered properly with the appropriate width.
PR#2746
PR2#2746

**Review by lucy-xfl — COMMENTED** [review]
image
I use the Incognito window for it. There is no report button. It seems not work well on my side and I wish I knew why.

**Review by khushijain03 — COMMENTED** [review]
Hi @AJAYINAVOLU , I followed the instructions as mentioned, I don't see the search bar or the user list or the edit button. I tested it both in normal and incognito modes. Attaching the error showing up on my console.

Screenshot 2024-10-11 at 8 48 06 PM

**Review by slidracoon72 — APPROVED** [review]
#2746 
@AJAYINAVOLU 
I have reviewed the PR and confirmed that the search bar is working as expected. As names are typed, the user list suggestions are displayed correctly with the appropriate width. The User List is displayed on clicking the button and the sorting functionality works as expected.

Screenshot 2024-10-11 at 9 49 37 PM
Screenshot 2024-10-11 at 9 50 04 PM

**Review by Jingyii800 — APPROVED** [review]
I have tested this function and it worked as expected. The search bar is working fine by typing a name, and the user list suggestions are rendered properly with the correct width, also the sorting function looks good.

https://github.com/user-attachments/assets/6de57037-300f-43d3-972b-44ba53fcb618

**Comment by lng2020** [comment]
For those reviewers who didn't see the report button, it's an `Owner` feature and It requires an owner permission account.

**Comment by VMD281** [comment]
I reviewed the PR and the location feature looks good! I have attached the screenshots below:
PR#2746_1
PR#2746_2
PR#2746_3

**Review by javid679 — APPROVED** [review]
Hey, I have reviewed this PR and search function is working absolutely fine and the rendering of the results is good too but somehow i couldn't be able to see user's list, may be an issue from my end.
Screenshot (57)

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by NazaninHashemian** [comment]
I tested everything as follows:
- Checked into the current frontend branch and the development backend branch.
- Ran `npm install` and `npm run start:local` to test locally.
- Cleared site data/cache.
- Logged in as an owner-user and navigated to Dashboard → Reports → Team Locations.
- Verified the search bar functionality, user list suggestions, and proper rendering.
- Checked the sorting function on the users' location list for name and location.
Everything works as expected. Approving this PR.

**Pull request merged**
