### PR TITLE
Changhao - added more unit tests for activeinactiveconfirmationpopup.jsx

### PR DESCRIPTION
**Pull request by Changhao3220K**
# Description
more unit tests for activeinactiveconfirmationpopup.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm test ActiveInactiveConfirmationPopup.test.js` to run this PR locally
3. verify all 12 tests passed

## Screenshots:
Screenshot 2024-02-22 at 11 43 07 AM

### CODE REVIEW

**Review by this-journey — APPROVED** [review]
Hello! I have reviewed your PR and all tests have passed.  Great job!

PR 1698

**Review by ilyaflaks — APPROVED** [review]
PR1698
All of the tests are passing as described. Well done!

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 16 - PR1

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Great job on the tests that you've already got here. However, I'd like to see test coverage regarding the "isOpen" props and confirmation that ModalHeader is rendering. 
 
Screenshot 2023-12-15 at 2 25 17 PM

in addition, your test file location is incorrect per the file convention standard HGN uses. Please refer to <a>https://docs.google.com/document/d/1-iWj_1XJ_hFE0lRAAWvOfKtrkacT5HIvfWUu-6shQ08/edit </a> to correct it


All of your tests so far pass though

Screenshot 2023-12-15 at 2 26 27 PM

**Comment by DragonSlayer2401** [comment]
I tested your PR and all tests passed as expected. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/06aa59c9-b1a6-4f32-a01b-f728d751192c

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-16 at 9 12 29 PM
All the test cases were successful. Excellent job!

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-17 at 1 48 14 AM

**Review by ljrirene — DISMISSED** [review]
All 11 tests passed. Great work!

**Comment by KurtisIvey** [comment]
Hey [Changhao3220K](https://github.com/Changhao3220K) , once those changes are implemented, I'll rally some more reviewers and move this to final review since it does look really good

**Review by bienzguoa — DISMISSED** [review]
Screenshot 2023-12-29 at 4 43 07 PM
It looks good for all these test cases. Code is clear and correctly rendered. As Kurtis mentioned, it's better to have a test case for "isOpen" prop.

**Review by 666saofeng — APPROVED** [review]
All tests passed. Great job!
image

**Comment by dhairya-mehta** [comment]
Hi, all test cases passed. Good work!
image

**Review by XiaohanMeng — APPROVED** [review]
Hi, all 12 test cases passed! Well Done!
1698_result

**Comment by KaushikMreddy** [comment]
Hi, 
all the test cases have passed
image
Good work!

**Review by dkn6 — APPROVED** [review]
Thank you for your great work! LGTM

test

**Review by Sandhya1236 — DISMISSED** [review]
I have successfully tested the additional unit tests for ActiveInactiveConfirmationPopup.jsx. After checking into the current branch, running npm install, and executing npm test ActiveInactiveConfirmationPopup.test.js, I verified that all 12 test cases passed successfully. This confirms that the unit tests for the ActiveInactiveConfirmationPopup component are functioning as expected and correctly cover the intended scenarios.

image

**Review by Saniya98 — APPROVED** [review]
All test cases have passed successfully 
image

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture1698

**Review by Abhinav-Ankur786 — APPROVED** [review]
All the 12 test cases are passing
PR #1698

**Comment by beblicarl** [comment]
@Changhao3220K , can you please work on all merge conflicts for this and all other PRs that are meant to be reviewed?

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
