### PR TITLE
Mohan - hotfix Visibility toggle Alignment In Teams

### PR DESCRIPTION
**Pull request by mohangadde1**
# Description
PR will Fix the  Visibility toggle Alignment In Teams

## Related PRS (if any):
No Related PR

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ View Profile→ Teams 
6. verify function in both dark and light mode

## Before
image
## After
image

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/92df2496-ebc0-4605-a68c-569892b5d600

**Review by jinxyou — DISMISSED** [review]
Looks good to me and it works in both mode. 
Screenshot 2024-11-30 004134
Screenshot 2024-11-30 004148

**Comment by one-community** [comment]
Please fix it so thee are aligned with the ones below too: 
image

**Review by one-community — CHANGES_REQUESTED** [review]
Please fix is so these are aligned with the ones below too: 
image

**Review by RashmiKY98 — CHANGES_REQUESTED** [review]
When changing the size of the screen, the visibility toggle appears below Visibility header.  Request you to look into the issue.
image

**Review by NazaninHashemian — APPROVED** [review]
I've reviewed the changes in this PR, which addresses the visibility toggle alignment in the Teams section. The functionality works as expected, and I verified it in both dark and light modes. The UI changes seem to be functioning correctly.

However, during my testing, I encountered an issue with the developer account not being able to log in locally. I was able to log in successfully on the live version of the site, so this issue seems to be related to my local environment or backend configuration rather than the changes in this PR.

Since the PR does not affect authentication or backend functionality, I believe it is ready to be merged. Please note that the login issue appears to be a separate concern that I will address locally.




notworkingDeveloperAccount

**Comment by pallavithorat** [comment]
I have tested the PR by verifying the functionality of the 'Teams' section under both dark and light modes. Everything works as expected.
Screenshot 2024-12-03 at 2 51 06 PM
Screenshot 2024-12-03 at 2 51 28 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
