### PR TITLE
Olga - design project details page

### PR DESCRIPTION
**Pull request by cvtqx**
# Description
This is the design of the project details page from Phase II. It was created based off the prototype below:

Figma prototype

## How to test:

1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. go to  http://localhost:3000/bmdashboard/12345 
4. check the design against the prototype, check for responsiveness in different screen sizes

### CODE REVIEW

**Review by Jiyuanxia — APPROVED** [review]
Hi @cvtqx , I have reviewed your pull request and tested it. It looks the same with the prototype and fits different screen sizes. Good job!
Screenshot 2023-09-21 172212
Screenshot 2023-09-21 172202

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
All the font sizes for the Members working on site today is just defaulted to 1rem. Might suggest lowering that for smaller resolutions, or either reducing padding inside and outside that box in order to allow the full table to show on tablets. 
Screenshot 2023-09-21 at 4 11 14 PM


Daily logging,Add a new item, & Team should not be represented as paragraph elements but instead heading elements. The buttons should be contained within `<li>` tags inside a parent `<ul>`. Not sure why the Materials with quantity less than 20% left, Card title, and Rented Tools or equipment to be returned in 3 days is represented as an h6 if there aren't prior heading elements of h4, h5 inside this component.

this fix can be ignored if this is an already declared css variable throughout the app and you guys are just altering its styling inside this new feature:
inside ProjectDetails.css lines 162, class styling should not be camelCased. It's an incorrect convention that has permeated too much of the app. it should be single-card or something along those lines.

Might be a good idea to throw this in chat gpt for some optimizations and corrections since there are probably more issues. These are just what I've noticed. I haven't deep dived into the css since that would take a lot longer.


My own person opinion on the "Log issue" button alignment is that it looks weird on desktop res being slightly offset like that. You 100% nailed it off the design, so my criticism lies within the design itself. The lack of symmetry makes it look bad. My criticism on this is for whoever did the mock up lol. room for improvement there for sure.

Screenshot 2023-09-21 at 4 11 39 PM

**Comment by DavidC0126** [comment]
Hi @cvtqx I tested your PR and the page works as described. Also, I agree with the suggestions from @KurtisIvey!

web1
web2

**Comment by luisarevalo21** [comment]
Hello @cvtqx 
I tested your PR and works as intended great work!

You nailed the design and works smoothly on all screen sizes. 
I think @KurtisIvey nailed all the suggestions as it pertains to semantic issues. 

Correctly using html tags where its needed and fixes those that need to be changed. Using h1 -h6 instead of a regular p tag. I would also agree on the log issue button it seems off butting having the extra space.
But overall great work on nailing the design. 
Screenshot 2023-09-21 at 8 20 34 PM

**Review by Haoj1 — COMMENTED** [review]
@cvtqx Your prototype looks good on my end

**Review by Chuehleo — APPROVED** [review]
Your prototype looks great and so does the responsiveness, great job!
Screenshot 2023-09-21 235645
Screenshot 2023-09-21 235605

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and the page works as intended in different sizes! Great job!

Week4 - PR8 (1)
Week4 - PR8 (2)

**Review by JeffLi117 — APPROVED** [review]
Hi @cvtqx , your design project details page does work at multiple screen sizes!

image

image

image

Besides the recommendations listed by others, I also suggest changing the "Members working on site today" table background colors/borders - for example, you might be give the whole table a slight gray border (like how each row is separated). This might make it more visually appealing, as the very light gray background color of the table is hard to distinguish in relation to the overall white background.

**Comment by cvtqx** [comment]
@KurtisIvey @luisarevalo21 @DavidC0126  thanks for your reviews and I appreciate your expertise! I've made the requested changes and also updated all classNames to follow the convention. I'll leave the log issue button as is for now.

**Comment by veronicacheng2** [comment]
Hi @cvtqx, I tested on my end. The page looks good and is responsive.

[screen-capture (5).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/911f2b83-3857-46f2-bde1-89cbd61e4346)

**Comment by beblicarl** [comment]
This UI implementation is well done. Great work!

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.09.24-12_00_46.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/cfb7b0c4-6545-47ad-bd3e-2715ea116dbc)

**Review by beblicarl — APPROVED** [review]

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Semantics look good. No complaints whatsoever there. These are the issues that I received alerts to in vs code:

unnecessary curly braces:
pr1330 curly braces unnecessary and needs to be cleaned up

button labels key linting error. You might be better off just making a button component for this or creating the buttons themselves instead of mapping over them. I totally get the desire to not repeat yourself too much in code though. LogBar.jsx's length wouldn't be too bad if it was 80-100 lines in comparison to some of these components that are 700+ lol
pr1330 button labels key error

no nested ternary:
pr1330 no nested ternary expressions
try using a switch statement instead, and you can avoid the linting error and improve readability:
Screenshot 2023-09-25 at 11 24 37 AM
I know people don't use them much in JS, but this would be a perfect use case for it

don't use index as keys:
pr1330 don't use index as key

ToolCards.jsx needs to be a function declaration linting error.
pr1330 toolCards jsx needs to be linted and turned into function declaration

**Comment by Sssky-18** [comment]
Hi @cvtqx, the UI is so good and it works for different size of the the window. All the pictures and buttons are shown as expected. However, as @KurtisIvey stated, there are some warning inside the BMDashboard code. The code works, but hope you can check the warnings again.

PR#1330_1

PR#1330_2

PR#1330_3

**Comment by Shubhu0** [comment]
Hi @cvtqx I reviewed the PR and compared the Prototype with it. The UI looks and works great, tried it with different sizes and versions and the text and font adapted great! Good work!

269710535-398184e1-213a-4cb6-a540-9fb2be04fc8b

image

**Review by yangfan2001 — DISMISSED** [review]
Hi I have tested your PR. It looks as same as the prototype. And It works great in different screen size. Great Job! 
image
image
image

**Comment by Vishala09** [comment]
The UI looks awesome and exactly same as in the wireframe. Great Job!

**Here the UI looks great and the hover on Card title enhances the card with a shadow which is awesome. Similary, Can we do a color change or something else on hover for buttons such as Team , Material , etc .. ?**
image
image


**The table looks good. Although in the prototype, the alternate rows are shaded. Can we do the same ?**
**There is an unnecessary scrollbar for horizontal scrolling at the bottom. I am not sure , if it's only for me. If it cannot be replicated , please ignore.**
image

**Looks good in different screen sizes!**
image
**It is very responsive. Great job!**
[Untitled_ Oct 02,2023 5_47 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/04b81c4b-7c00-451a-a846-569c1601859c)

**Comment by cvtqx** [comment]
@KurtisIvey and @Sssky-18 lint errors fixed and I've added uuid  to be used instead of index. Thanks for your suggestion on the switch statement @KurtisIvey . This was a great case for it.

**Comment by cvtqx** [comment]
@JeffLi117 thanks for the suggestion on improving the table design. I've changed it a bit, please take a look.

**Comment by cvtqx** [comment]
@Vishala09 excellent catch on the buttons! I've added a hover effect, please take a look. Also updated the table. As for the scrollbar that you see, this is intended and it only appears on certain screen sizes when the table does not fit.

**Review by Vishala09 — CHANGES_REQUESTED** [review]
Please check my previous comment for reviews and Can you consider doing the the alternate shading of rows in the table?

**Review by JeffLi117 — DISMISSED** [review]
@cvtqx The changes in the table look great!

image

**Comment by cvtqx** [comment]
> Please check my previous comment for reviews and Can you consider doing the the alternate shading of rows in the table?

@Vishala09 all has been done. You might need to do git pull on this branch.

**Comment by Vishala09** [comment]
Rested the PR! Great Job!

Hover on button looks good!
image

Table looks great!
image

**Review by Vishala09 — APPROVED** [review]

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR. It works as expected. I tried to resize and check if it was responsive and it worked well.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/50b34c8c-4c5f-4837-994b-09e9575ce24c

**Review by KurtisIvey — APPROVED** [review]
Fantastic Job! Zero issues whatsoever with it.

**Comment by RheaWu1212** [comment]
Hi it works as expected, only at the last part, I'm not able to scroll left to right:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/91df40cd-bdaa-437a-8b18-d9d221077b8d

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/1b23e8d2-8a86-4d5d-b29e-fde85dd577a1

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
