### PR TITLE
Nahiyan_Dark Mode Modals on Projects/WBS page

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Implemented dark mode on all modals that can be found in the Projects page and the WBS page.

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Dark mode for all modals on the Projects page
- Dark mode for all modals on the WBS page

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links → Projects → WBS
6. verify that all modals on the Projects page are working properly
7. verify that all modals on the WBS page are working properly.
8. ### **NOTE: Add task modal, edit task modal and more info modal are not working. This is being fixed by another developer so just please test the UI only. Hit refresh when you are unable to interact with these modals**

## Screenshots or videos of changes:
Screenshot 2024-05-16 115039
Screenshot 2024-05-16 115114

### CODE REVIEW

**Comment by beblicarl** [comment]
This functionality is working as intended as seen in the screenshots below

image

image

image

**Review by beblicarl — DISMISSED** [review]

**Review by Ramaruva — CHANGES_REQUESTED** [review]
Hi I verified all modals in projects and wbs can you check this two issues which I noticed
while navigating from particular wbs the page is turning from dark mode to light mode and also when I am trying to remove an particular wbs the modal for it is not in dark mode 
image

**Review by jayyy-s — DISMISSED** [review]
All the modals look good to me. I ran into the same issue as @Ramaruva ran into (navigating to a WBS tasks page did not keep dark mode). I'm assuming this is not in the scope of this PR. If it is in scope, the first place I would probably investigate is how props for darkMode are implemented in ./components/Projects/WBS/WBSDetail/WBSTasks.jsx
wbs modal
welcome modal
add task modal

**Review by MinSun0814 — DISMISSED** [review]
image
image

I can see the modals in dark mode with no issue. Nice work!

**Review by sucheta90 — CHANGES_REQUESTED** [review]
Hello @Nahiyan-16,

I reviewed this PR and noticed an issue: the changes are not persistent between pages. Each time I visit a different page or refresh the current one, the dark mode reverts back to light mode. You can clearly see the problem in the attached video. Constantly switching between dark and light modes could lead to a poor user experience. I'm not sure if this is the intended behavior. Other than that, the modals look great.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/127ee06e-8b0b-4fef-8061-84b62dd2fa52

**Review by hbodgal — DISMISSED** [review]
image

I have checked all the functionalities. It works as expected. But i do face the issues which already are listed.

**Comment by Nahiyan-16** [comment]
> Hello @Nahiyan-16,
> 
> I reviewed this PR and noticed an issue: the changes are not persistent between pages. Each time I visit a different page or refresh the current one, the dark mode reverts back to light mode. You can clearly see the problem in the attached video. Constantly switching between dark and light modes could lead to a poor user experience. I'm not sure if this is the intended behavior. Other than that, the modals look great.
> 
>  Screen.Recording.2024-05-18.at.12.08.10.PM.mov

Yes, I am aware of this and I will publish another PR to fix this issue. This PR should only handle modals on projects and wbs page.

**Review by Sandhya1236 — APPROVED** [review]
Everything works great as expected. Dark mode is properly implemented on all of the functionalities.
image
image
image

**Comment by cecilia-uu** [comment]
It works as expected when clicking the dark mode button, but it is not consistent after clicking the 'wbs' icon. It means that it become the light mode again. Also, I cannot edit the wbs information.
截屏2024-05-23 下午12 44 48
截屏2024-05-23 下午12 46 58

**Review by tianyangL11 — APPROVED** [review]
Everything works perfectly.  The dark mode implement this functionality successfully
a457d81ae4da474ba51e1e5a672f82e
5136e3ee1928521a93b57956240d540

**Review by Wenboooooo — APPROVED** [review]
Functions look good to me.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
