### PR TITLE
TuanDinh_TeamsReportLogs_UnitTest

### PR DESCRIPTION
**Pull request by TuanDinh140194**
Add Unit test for TeamsReportLog component

# Description
Create the unit test for TeamsReportLogs component

## Main changes explained:
- Add new file TeamsReportLogs.test.js
- In TeamsReportLogs.test.js, i added 7 test case to test the TeamsReportLogs.jsx component.
- In the begin, test if the component renders without crashing, next test if the component displays the correct title, displays the correct number of members, displays the correct total team blue squares, displays the correct total Weekly Committed Hours, and displays the correct total Teams Work Hours. Finally, test if the component still display empty blocks when no team data is provided
…

## How to test:
1. check into current branch
2. do `npm install`
3. do `npm test TeamsReportLogs.test.js` to run the test
4. Verify that all 7 tests have passed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/db28eb5e-d25e-4266-b1f8-32ba05edcf7e

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by Bali2Mohit** [comment]
Hi @TuanDinh140194 , I have tested your PR. all tests are passing. Well done
Screenshot 2023-11-18 at 16 04 29

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-11-18 at 2 07 37 PM

**Review by Hemsharavanan — APPROVED** [review]
- The PR covers comprehensive unit tests covering rendering, display of various metrics, and handling scenarios with different data inputs. 
- All tests pass successfully, ensuring accurate rendering of information and component stability.
Following 7 tests passed successfully.
1. renders without crashing
2. displays the correct title 
3. displays the correct number of members
4. displays the correct total team blue squares
5. displays the correct total Weekly Committed Hours
6. displays the correct total Teams Work Hours
7. component still display empty blocks when no team data is provided
PR #1560 TuanDinh_TeamsReportLogs_UnitTest

**Review by pika-chu11 — APPROVED** [review]
Hi @TuanDinh140194 , the test passed on my end! Great job! 
PR 1560

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 12 - PR 4

**Review by Alforoan — DISMISSED** [review]
All 7 passed, nice!

image

**Review by ChengyanOo — APPROVED** [review]
Hi @TuanDinh140194,

Excellent work on implementing the tests! I'm happy to report that all tests have passed. Attached is a screenshot for your reference.

Screenshot 2024-01-10 at 14 31 09

**Review by 666saofeng — APPROVED** [review]
All tests passed. Good job!
image

**Review by XiaohanMeng — DISMISSED** [review]
PR1560 UnitTest result

All 7 cases passed on my end! Great Job!

**Review by ChengyanOo — DISMISSED** [review]
I've reviewed your code and am impressed by the thoroughness of your test coverage for the component. Excellent work!
Screenshot 2024-02-27 at 11 35 04

**Review by scoopstroop92 — CHANGES_REQUESTED** [review]
Hello Tuan Good job on the test cases. I have two suggestions though !
1.  Kindly move the unit test case to the right path
2.  There is no verification in Test case 1, you are just rendering the component !

**Review by scoopstroop92 — APPROVED** [review]
Made the changes!. Can be merged

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
