### PR TITLE
Sneha - Info modal for admin permission management

### PR DESCRIPTION
**Pull request by Sneha1b**
# Description
Implement Info Modal for permissions (Bug priority High)

## Main changes explained:
- Updated the `rolePermissions` file to add info button with pop up modal to give more information about the permission

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. Goto Other Links → Permissions Management
5. Select any role
6. Verify that there is a info modal besides the delete button
7. Verify onClick behaviour for the modal

## Screenshots or videos of changes:
After:
Screen Shot 2023-06-09 at 6 57 42 PM

Screen Shot 2023-06-09 at 6 57 36 PM

### CODE REVIEW

**Comment by yufeiStella** [comment]
Clicking on most info modals and everything works well.
Screen Shot 2023-06-09 at 23 20 05
Screen Shot 2023-06-09 at 23 20 31
Screen Shot 2023-06-09 at 23 20 44

**Review by stevenpaalz — APPROVED** [review]
Changes appear to be working as intended.
Screenshot 2023-06-10 at 8 42 56 AM

**Review by EdwinLauM — APPROVED** [review]
Works as intended! info modals for every permission. 

Screen Shot 2023-06-10 at 6 52 15 PM

**Review by Chuehleo — APPROVED** [review]
Everything working as intended
Screenshot 2023-06-12 021330
Screenshot 2023-06-12 021355

**Comment by oreoluwadnd** [comment]
Screenshot from 2023-06-12 18-40-42
Screenshot from 2023-06-12 18-41-20

 Info Modal for permissions  working well

**Review by oreoluwadnd — COMMENTED** [review]
Screenshot from 2023-06-12 18-40-42
Info modal for admin permission came up

**Review by oreoluwadnd — COMMENTED** [review]
Screenshot from 2023-06-12 18-41-20
Info modal came up

**Review by oreoluwadnd — APPROVED** [review]
Screenshot from 2023-06-12 18-41-20
Info modal came up

**Comment by AnishPandita** [comment]
Hi @Sneha1b, I tested your changes and it works as intended. Clean code, well structured.
Screenshot 2023-06-12 at 7 16 27 PM

**Review by NidaZaki — APPROVED** [review]
Works as intended!

**Review by eduhorta — APPROVED** [review]
It is working as intended!
Great job! 👍

Screenshot 2023-06-13 10-40-59

**Comment by Lucas-E** [comment]
Thank you everyone! Moving to final review!

**Comment by juneluo** [comment]
It works as intended. Good job!
Just a few suggestions before merging:
1. line75, a typo "GIves" should be "Gives".
2. the code inside <i></i> in line232 to 241 and line 253 to 263 seems duplicate, is it possible to move this part out of the condition like the following?
<div><i>...</i>{condition?(<Button>...</Button>):(...)}</div>

**Comment by cvtqx** [comment]
Looks good!

Screen Shot 2023-06-16 at 1 58 50 PM

**Pull request merged**
