### PR TITLE
Anny_fix_alginment_of_text_in_Permission_Management_buttons

### PR DESCRIPTION
**Pull request by astrjc0326**
# Description
Screen Shot 2023-11-08 at 8 50 42 PM

## Related PRS (if any):
No

## Main changes explained:
- Delete the styling of info-button to prevent the alignment issue on the deployed code

## How to test:
1. check into current branch
2. do npm install and npm run start:local to run this PR locally
3. log as owner user
4. go to Other Links → Permissions Management → Manage User Permissions 
5. check if both "Add" and "Delete" button is aligned

## Screenshots or vide
Screen Shot 2023-11-08 at 2 05 21 PM
os of changes:

## Note:
The code is the same however it displays differently on local devices and when deployed.

### CODE REVIEW

**Review by Jiyuanxia — APPROVED** [review]
Hi @astrjc0326 , I have reviewed your pull request and tested it. It works as you intended, both "Add" and "Remove" button is aligned. Good job!
Screenshot 2023-11-09 111013

**Review by tsunami776 — APPROVED** [review]
Hi @astrjc0326, I tested your PR locally and it works as intended. 'Add' and 'Remove' Text in buttons are aligned in user permission management. Nice work!

CleanShot 2023-11-09 at 10 45 54

**Review by Shubhu0 — APPROVED** [review]
Hi @astrjc0326 Reviewed your PR and it is working as intended. The buttons are aligned correctly. I did notice that there is a scroll feature that gets imposed on the browser's original scroll, as you can see in the picture i have shared. 

image

**Review by Sssky-18 — APPROVED** [review]
Hi @astrjc0326 , I tested this PR, and after checking the correct route, I can clearly see that all the Add and Delete buttons are aligned. Thank you for your great work! 
PR#1505

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
