### PR TITLE
Assign badge

### PR DESCRIPTION
**Pull request by zhangwen829**

### CODE REVIEW

**Comment by zhangwen829** [comment]
Please log in as a user with the Administrator role (You may use this email "devadmin@hgn.net", credentials included in the Instructions for Running HGN React App locally) Find the "Badge Management" link in the header under other links, and go to the badge assignment tab.

**Comment by daoquangvy** [comment]
Can you also create a PR for the HGNRest badge branch? 

The current HGNRest in the development branch is not working with this. The "badgeController.js " in the current HGNRest is outdated. 

Otherwise, everything is working perfectly when I try to run this branch with the "badgeController.js" in the badge branch in HGNRest. I don't think I should approve this before the HGNRest is updated first.

**Comment by zhangwen829** [comment]
https://github.com/OneCommunityGlobal/HGNRest/pull/41/

**Review by daoquangvy — APPROVED** [review]
Thank you for the PR on HGNRest. I will approve this/

**Pull request merged**
