### PR TITLE
Xiao F update teams page sorting part c

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-12-29 at 16 36 28

## Related PRS (if any):
To test this frontend PR you need to checkout the [#671](https://github.com/OneCommunityGlobal/HGNRest/pull/671) backend PR.

## Main changes explained:
- Update file `src/components/Teams/TeamTableHeader.jsx` for including new icons and getting onclick methods from child component
- Update file `src/components/Teams/Teams.jsx` for including new sorting methods and states for managing different sortings

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user (Right now, you need an owner account to toggle 'Active' status for a team)
5. go to Other Links-> Teams->  Click 'Team Names' to cycle through sorting methods: default(by modified date), ascending, descending
6. go to Other Links-> Teams->  Click 'Active' to cycle through sorting methods: default(by modified date), ascending(inactive teams on top), descending
7. When 'Team Names' is not in default sorting, clicking on 'Active' will reset 'Team Names' icon to default

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/d73825cf-6fe0-4861-83f5-98768729fdb0

### CODE REVIEW

**Review by abdel-lall — APPROVED** [review]
Works as described. Nice job!

Screenshot 2023-12-30 012050

**Review by Alforoan — APPROVED** [review]
Everything works as intended. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/41a2aad2-354a-4f36-8ca3-8f967d71caf0

**Review by yangfan2001 — APPROVED** [review]
Hi, I have read your code and tested your PR, everything works as expected, great job!
image

**Review by Haoj1 — APPROVED** [review]
@tsunami776. Everything looks good! It is able to sort the team by active and modifying date

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/a5169de0-f07b-49d5-a8b9-b8b0c2e567da

**Review by bienzguoa — APPROVED** [review]
Work as intended! Code looks clear. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/458971a1-5c20-47cc-8a54-cf5955e406ce

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
