### PR TITLE
Vishala Phase 2 Update Materials Single and Bulk

### PR DESCRIPTION
**Pull request by Vishala09**
# Description
This PR is about **updating single material** from material list page and **updating materials in bulk** from update materials page.
Or Implements # (WBS) 3.3.5

## Related PRS (if any):
Related Backend PR : https://github.com/OneCommunityGlobal/HGNRest/pull/606

## Main changes explained:
- Added Update Material Folder with multiple files

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. on the backend , do `npm run build` and `npm start`
4. log as admin user
5. Test **Materials List page** : http://localhost:3000/bmdashboard/materials
6. Please test for list view , project based listing of materials and open/close functionality of edit/view modals
7. **Test Update Material one at a time**  : http://localhost:3000/bmdashboard/materials
8. Click the update icon under updates to open the pop up window
9. Play with input values and units to test validations. 
10. Any value entered on Qty used/wasted should be added to used/wasted values and subtracted from available
11. Click submit to check if the values have been updated correctly in materials list page.
12. Open `view` near the update icon to view the history of the update made.
13. To test Bulk Material Update , go to http://localhost:3000/bmdashboard/updateMaterials
14. Test Select projects and Select date fields
15. Play with input values and units to test validations
16. Any value entered on Qty used/wasted should be added to used/wasted values and subtracted from available
17.Cancel should cancel the entered values and Submit should submit the data and you can view the update changes in materials list page.

Note : As it is a fresh implementation, I constructed it based on phase 2 documentation, wireframes, input gathered from fellow team members, and incorporating some of my own insights. Hence , Do conduct a thorough testing to ensure optimal user-friendliness.

## Screenshots or videos of changes:
[Untitled_ Nov 15,2023 5_04 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/f1176a2c-b7b0-4ca2-800c-923e15fbe0f8)

### CODE REVIEW

**Review by Haoj1 — COMMENTED** [review]
@Vishala09 entering material inputs looks good! Both  http://localhost:3000/bmdashboard/materials and http://localhost:3000/bmdashboard/updateMaterials are good

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/bfd74b55-7216-443e-8cbd-4c456b10006f

**Comment by palakgosalia** [comment]
Hey, I reviewed and tested your PR. Great work. I was able to update the material individually as well as in bulk. I also played around with the input to cover edge cases. Great work with that. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/4f3368cb-d630-4711-8f2b-3e24e68606e9

**Comment by Cavein254** [comment]
Hi @Vishala09, I have tested both pages and the update functionality works as expected. 

- [x] Bulk update works as intended
- [x] open/close functionality of edit/view modals
- [x] Any value entered on Qty used/wasted should be added to used/wasted values and subtracted from available

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/b13a9266-ba13-40b5-a1fc-0e13bf4c11ab

**Review by tdkent — CHANGES_REQUESTED** [review]
- Can you make the route to the bulk update page "/bmdashboard/materials/update"?
- On the bulk update page it would be clearer to have a Project column instead of an Id column.
- It might be clearer to move project-related actions and reducers into their own files (ie actions/bmdashboard/projectActions.js)

**Comment by Vishala09** [comment]
@tdkent 

I made the requested changes. Please find them here in the video.

[Untitled_ Nov 30,2023 1_14 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/915d6e7f-b6d2-4009-9086-2d06afbd2380)

**Review by tdkent — DISMISSED** [review]
Awesome work, thanks for making those changes. One other minor change would be to place all materials-related reducers into the same file, **materialsReducer.js**

**Review by tdkent — DISMISSED** [review]

**Review by tdkent — APPROVED** [review]

**Pull request merged**
