### PR TITLE
Edwin - Make total valid weekly summaries editable by owner/admin

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-07-04 at 1 53 10 AM

## Main changes explained:
- Created a new component that has a clickable up arrow and down arrow to edit the valid weekly summaries
- Made changes to the code to send a PATCH request every time the weeklySummariesCount property is changed with the up/down arrows

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to Reports -> Weekly Summaries Report -> "Total Valid Weekly Summaries"
5. Use the up arrow and down arrow to change the count. Refresh the page to make sure the latest count is saved

## Screenshots or videos of changes:

Admin/Owner Account:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/3769d2da-92f6-45ef-bcc8-00bd515b7b64

### CODE REVIEW

**Comment by AaronPersaud** [comment]
Hi Edwin, I have tested it and it looks good!

<b> Testing up and down arrow functionality and saving on refresh </b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/68f63e37-4a7d-4537-bb87-67c9cdf58be8

- tested cannot decrement at 0, text turns blue at 8 summaries



- PATCH request is made successfully on increment/decrement

973_no_arrows

However, I noticed that the up/down arrows only appear on the "Last Week" tab and do not appear in any of the other tabs. Is this the intended behaviour?

**Review by beblicarl — APPROVED** [review]

**Review by BaileyM96 — APPROVED** [review]
Good afternoon Edwin,

I reviewed your pull request and all changes work as intended! Great work!

[Total Weekly Summaries.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/f177baed-f170-4d38-ab2a-8c004fac6ac1)

**Review by tdkent — CHANGES_REQUESTED** [review]
Local testing of the updated functionality of  **Reports > Weekly Summaries Reports > Last Week**, which allows updating of the **Total Valid Weekly Summaries** field, confirms that a successful `PATCH` request is sent after each button click. The updated data persists after page refresh.

However, the following issues may be worth consideration before merging:
- Is a fresh `PATCH` request in response to _each button click_ desirable rather than a confirmation button to send a single request after the user has made the desired update? (this button might appear on screen only if the user's new value is different from the current value)
- The current styling of the arrow icons is not very intuitive and could be improved to make them look more like buttons. I would recommend a background and/or border around each arrow, with a hover effect.
- The buttons are quite small and the spacing potentially too tight (particularly for touch screen users). Horizontal alignment would allow increased size and spacing.
- Because the buttons are positioned relative to the summary value, they move slightly every time the value changes and the width of the value container changes. This is particularly noticeable when the value is decremented from `1` to `No valid submissions yet!`. The result is the user having to slightly adjust their pointer after each click and, potentially, missed clicks. A possible improvement would be to have the buttons container positioning independent of the value.
- **Total Valid Weekly Summaries** text turns blue when value = 8.
- As pointed out by @AaronPersaud the **Weekly Summaries** value is only editable in the **Last Week** tab.
- One of the `<div>` containers wrapping the arrows is (apparently, could just be a rogue hover style) a selectable element. Clicking the element does not send a request (see below). 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/1a9f92b2-b39e-4594-8d9e-f0dbbc36ab28

Testing demos:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/0f0a324b-3441-4288-a435-001f87264cd9

973-patch

**Review by ramyaram2092 — COMMENTED** [review]
Hello @EdwinLauM  I locally tested the new component . It works as expected and I do not see errors on the console as well. Well written clean code.
I just have one doubt before merging , is there a requirement to change the font of the  "valid weekly summaries" to blue when the value is set to 8?. I couldn't see that in the bug document 
**Issue Link** :  [Weekly Summary Component](https://docs.google.com/document/d/1n5NIb3dbiSrIRuOG1ZCwt34pEP1poqddCv1guaQml88/edit)

image


Apart from that everything looks good to me. Good work


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/60442397-dd18-4338-a0b3-7bfeb488e369

**Comment by EdwinLauM** [comment]
> Hello @EdwinLauM I locally tested the new component . It works as expected and I do not see errors on the console as well. Well written clean code. I just have one doubt before merging , is there a requirement to change the font of the "valid weekly summaries" to blue when the value is set to 8?. I couldn't see that in the bug document 

Hey @ramyaram2092. when I pushed the commit I was getting merge conflicts. The merge conflict was because I was missing the piece of code that makes it blue when the value is 8. If you pull the most recent dev branch the code for that logic is also there. I am not too sure where is the requirement but the logic is already implemented in the dev. In the case of my PR, I just adjusted the already existing logic with my new code.

**Comment by AnishPandita** [comment]
Hi @EdwinLauM, the PR works according to the specified functionality. Total Weekly summary is editable via admin account.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/4c2e7f9c-0eb1-4993-aba2-8f4372880de9

**Review by mahamakhan — APPROVED** [review]
Everything works as intended.

**Comment by ramyaram2092** [comment]
> > Hello @EdwinLauM I locally tested the new component . It works as expected and I do not see errors on the console as well. Well written clean code. I just have one doubt before merging , is there a requirement to change the font of the "valid weekly summaries" to blue when the value is set to 8?. I couldn't see that in the bug document
> 
> Hey @ramyaram2092. when I pushed the commit I was getting merge conflicts. The merge conflict was because I was missing the piece of code that makes it blue when the value is 8. If you pull the most recent dev branch the code for that logic is also there. I am not too sure where is the requirement but the logic is already implemented in the dev. In the case of my PR, I just adjusted the already existing logic with my new code.

Makes sense. Approving the PR on the same account

**Review by ramyaram2092 — APPROVED** [review]
It looks good to me. Approving the changes from my end

**Comment by Jiangwei-shi** [comment]
Hi Edwin, I have tested it, and it looks good! I tested that it cannot decrement at 0. The text turns blue at 8 summaries and turns black for more than 8.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/a36282df-2369-48cd-902e-fc81e4491ed5

**Review by HectorAgudelo — APPROVED** [review]
The changes to the code and addition of elements performs as expected. although, the arrow design should be more visible to the user and less ambiguous. Also, when clicking the arrows i ended up highlighting the text.  Make the arrows into buttons, that may help. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/2fc4f893-4954-42a3-99da-674a01df06c2

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello [EdwinLauM](https://github.com/EdwinLauM), 

Everything works as intended.

However, I would have to concur with [tdkent](https://github.com/tdkent).

The styling seems a bit out of place compared to the rest of the application. 
Also, as noted when the hours equals "8" the text and number become blue. 
Next, when the number reaches "0" the component and text move in according to the space needed for the text. Which should be fine tuned.
Lastly, you can click across the entire component even though the number isn't increasing. 

I think adjusting those styling errors would make the feature complete. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/bce530db-3ef4-40b2-9560-eea37672c70a

Screenshot 2023-07-07 at 7 35 19 PM

**Comment by one-community** [comment]
Yes, please make the style match this from the Profile --> Volunteering Times tab: 
image

**Comment by AaronPersaud** [comment]
> Hi Edwin, I have tested it and it looks good!
> 
> Testing up and down arrow functionality and saving on refresh
> 
>  973.mp4 
> * tested cannot decrement at 0, text turns blue at 8 summaries
> 
> 
> 
> * PATCH request is made successfully on increment/decrement
> 
> 973_no_arrows
> 
> However, I noticed that the up/down arrows only appear on the "Last Week" tab and do not appear in any of the other tabs. Is this the intended behaviour?

**Review by AaronPersaud — CHANGES_REQUESTED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/973#issuecomment-1620890457

see the above comment

**Comment by ramyaram2092** [comment]
@one-community  This PR has 5 approvals

**Comment by one-community** [comment]
> @one-community This PR has 5 approvals

Thank you. Still has requested changes from me and 3 other people though, so won't move to final review. Feel free to still review any like this too.

**Comment by one-community** [comment]
Thank you all, moved this to final review!

**Review by cvtqx — APPROVED** [review]
The functionality works as described and the styling has been adjusted to match the rest of the app. I can change the summaries count up and down but not below 0 and the new value is saved upon refreshing the page. Great work!

Screen Shot 2023-08-09 at 2 05 43 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
