### PR TITLE
Nahiyan dark mode on projects and teams page

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
THIS IS A FOLLOW-UP PR TO [PR#2105](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2105)
This PR makes dark mode available for the following pages:

1. Projects page
-  Inventory page
- Members page
- WBS pages
2. Teams Page
3. Send Emails Page

## Related PRS (if any):
This frontend PR is related to the dev backend PR.

## Main changes explained:
- Implemented dark mode for Inventory page, Members page, WBS pages, and Projects page
- Implemented dark mode for Teams page
- Implemented dark mode for Send Emails Page

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
4. Clear site data/cache
5. log as owner user
6. go to dashboard→ Other Links→ Projects | Teams | Send Emails
7. verify that dark mode is working properly

## Screenshots or videos of changes:
Screenshot 2024-04-11 192816
Screenshot 2024-04-11 192842
Screenshot 2024-04-11 192953
Screenshot 2024-04-11 193012

### CODE REVIEW

**Review by hbodgal — DISMISSED** [review]
Everything works fine. Looks great.

image

**Review by linkhanthtel — DISMISSED** [review]
I reviewed your PR and dark mode work properly. One thing, it would be better if the color of the team tables in teams page changed to light color when we flip back to light theme.

#2147 (Projects)
#2147 (Send Emails)

#2147 (Teams)

**Comment by alla0810** [comment]
thumbs up!  I like color matches of projects/team/email pages when logged as an admin
But when I logged in as a volunteer, the background color looked a little too dark, and a little distractive compared with light mode.

projects
team
email

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account. All the mentioned pages are capable of toggling between dark and light mode. _Note that the pop up modals are still in white background even with dark mode. Good job!_


Screenshot 2024-04-12 at 4 23 07 PM
Screenshot 2024-04-12 at 4 22 41 PM
Screenshot 2024-04-12 at 4 22 12 PM
Screenshot 2024-04-12 at 4 24 40 PM

**Review by aaryaneil — DISMISSED** [review]
All the changes work as expected and the dark mode works well. Good work.
Screenshot 2024-04-12 at 5 26 06 PM
Screenshot 2024-04-12 at 5 26 24 PM
Screenshot 2024-04-12 at 5 26 39 PM
Screenshot 2024-04-12 at 5 26 59 PM
Screenshot 2024-04-12 at 5 27 11 PM

**Review by SushmithaPrathap — DISMISSED** [review]
I've tested this PR and everything works well, except for one issue. When transitioning from the light theme to the teams page, then switching to dark theme and back to light theme, the table remains in the dark theme. Thats the only issue, everything else works fine.

Here are the screen recordings:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/21feb031-66cc-4ae8-b7fa-a65fd840e0a2


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/fc494c30-3ff6-4bf0-abd1-4cb0e8364ad3

**Review by metaphor987 — DISMISSED** [review]
Hi Nahiyan, I've tested the changes using the admin account, and the three pages can switch to dark mode. Good work! Just one thing, the pop-up windows (after clicking the icon beside "Projects" and "WBS") on the project page stay white when switched to dark mode. I feel that it would be better to make them dark as well.
Screenshot 2024-04-12 at 6 56 50 PM
Screenshot 2024-04-12 at 8 40 30 PM

**Review by Parth-tech — DISMISSED** [review]
Hey Nahiyan,
Everything works great. When I had first logged in to Owner Account and while I was on teams page when I switched to dark mode and back to light mode, the table was still reflecting the dark mode changes. This problem was resolved automatically once I logged out of the Owner Account and I logged back in.

`Also highlighted by Sucheta here:` https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2147#pullrequestreview-1998589212

Issue Reference:

Screenshot 2024-04-13 at 2 19 28 AM
Screenshot 2024-04-13 at 2 19 42 AM

Correctly working functionality:
Screenshot 2024-04-13 at 2 29 16 AM
Screenshot 2024-04-13 at 2 28 51 AM

**Comment by hiralsonip** [comment]
I have reviewed the changes and everything is working as expected. 

PR2147_project

PR2147_send_email

PR2147_teams

**Review by Tiantian-C — COMMENTED** [review]
I reviewed your PR. Everything works fine!
Screenshot 2024-04-13 at 3 37 28 PM
Screenshot 2024-04-13 at 3 37 42 PM
Screenshot 2024-04-13 at 3 37 52 PM

**Review by sucheta90 — DISMISSED** [review]
Hello @Nahiyan-16, I have reviewed this PR and it works as intended. As I logged in as an owner, I was able to see the toggle button that turns changes to light and dark mode which specifically works for the Dashboard, Projects, Teams and Send-email page. Please refer to the attach video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/caa35f0d-03dd-403c-afbc-e466a987c247

**Review by SRamen1999 — COMMENTED** [review]
Everything works as intended. Dark mode works for all the Projects, Teams, and Send Emails pages.

Screen Shot 2024-04-19 at 9 11 03 AM

Screen Shot 2024-04-19 at 9 09 02 AM

Screen Shot 2024-04-19 at 9 09 49 AM

Screen Shot 2024-04-19 at 9 08 26 AM

**Comment by Nahiyan-16** [comment]
@SushmithaPrathap I fixed that issue. Can you please take another look?

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
