### PR TITLE
Sriram - fix projects archive functionality and Set Inactive button crashing UI

### PR DESCRIPTION
**Pull request by sri0606**
# Description
Screenshot 2024-09-12 235632

## Related PRS (if any):
This frontend PR is related to the development backend PR.
…

## Main changes explained:
- Updated Projects file to refactor all the relevant code to Project component.
- Created a modal within Project.js itself for better state re-rendering. Before the projects page had to be refreshed to see new changes, but now only the modified project re-renders. 
- Updated Projects.test.js and Project.test.js test files accordingly.
- Modified "Update Project" action in reducers/allProjectReducer,js to only update project if its found in database to not create duplicates/empty projects..
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links→ Projects→ Archive
6. verify if clicking on "Set Inactive" crashes UI and sets the project inactive.
7. verify that after clicking "Confirm" button, the project is archived either by querying the database (MongoDB compass) or by refreshing the page, the project shouldn't be there anymore.
8. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
archiveModal
dbUpdatedForArchive

### CODE REVIEW

**Review by ArtemisNyx3 — DISMISSED** [review]
[PR#2673 Test Nikita.webm](https://github.com/user-attachments/assets/6c93b0cb-9dbb-46d2-b3e8-13cf493898f2)

Functionality is working as expected

**Review by RishithaMamidala — CHANGES_REQUESTED** [review]
@sri0606 
The inactive status works correctly. But when archived, the button disables but the project is still visible until the page is refreshed. See, below video for details.

https://github.com/user-attachments/assets/3106577d-186e-4e44-bdef-1efa436cf64f

**Review by SnelPatare — COMMENTED** [review]
I have tested the changes. Selecting "Set inactive" will inactivate the project. Selecting "Confirm" will also inactivate the project but the project name is still displayed.
image

**Review by ddshah878 — APPROVED** [review]
Tested the changes, and everything is working as expected. Great job!


https://github.com/user-attachments/assets/b8003a4c-31c9-4c41-a1f3-d2cad6841b5b

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.
Screenshot 2024-09-16 150848
Screenshot 2024-09-16 150956

**Review by crystallow1168 — APPROVED** [review]
Hi @sri0606,

Changes are working as expected. Here are my findings:

https://github.com/user-attachments/assets/520d0f6c-a3ac-465c-9ff0-74c5b0365643

✅ Set project inactive without crashing the UI
✅ Changes worked both on dark and light mode

image

✅ Project is successfully archived 

---

Other observations:
❗️Project list does not update after archiving a project

**Comment by sri0606** [comment]
> Hi @sri0606,
> 
> Changes are working as expected. Here are my findings:
> 
>  PR.2673.mp4 
> ✅ Set project inactive without crashing the UI ✅ Changes worked both on dark and light mode
> 
> image
> ✅ Project is successfully archived
> 
> Other observations: ❗️Project list does not update after archiving a project

Hey @crystallow1168 , please make sure you have pulled the latest commits. In the recent commit, I made it so that the project is removed from project list once archived without any need for refreshing the page.

**Comment by crystallow1168** [comment]
@sri0606,
I have pulled the latest commit and the project list is now updated after archiving a project! Great job!

https://github.com/user-attachments/assets/39a8a64f-1f28-4c25-bf02-3b25ef2646c3

**Review by RishithaMamidala — CHANGES_REQUESTED** [review]
@sri0606 
I've reviewed the PR again, and there's an issue with archiving. The project doesn't get archived the first time I attempt it, but it works on the second try. Please refer to the video below for more details.

https://github.com/user-attachments/assets/4364c18c-821e-45b5-aef1-7f2d440f9fa5

**Comment by sri0606** [comment]
> @sri0606 I've reviewed the PR again, and there's an issue with archiving. The project doesn't get archived the first time I attempt it, but it works on the second try. Please refer to the video below for more details.
> 
>  video1191325365.mp4

That's odd. Please share the console logs using "Inspect"  and check if there any errors. Also re-try after clearing cache and rebuilding.

**Comment by tharunaa-1** [comment]
After clicking on "Set Inactive" the UI doesn't crash and sets the project inactive. And after clicking "Confirm" button, the project is archived by refreshing the page. The project doesn't show up anymore.

https://github.com/user-attachments/assets/e26404ae-d9b1-4f5f-b494-c2a2f5d4eaaf

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/f5a88311-d83f-4f2c-8329-fa7e1e832307

**Review by RishithaMamidala — APPROVED** [review]

**Review by mrinalini-raghavendran19 — DISMISSED** [review]
Looks good to me!

Changes are working for me. The steps followed by me to test this PR were - 

1) Logged in as an admin user

2) Had previously created a project for this purpose - `project-test-mrin`

3) Click on the `Archive` button on project page for the project that needs to be archived

Screenshot 2024-09-30 at 5 17 48 PM

4) Had to click again on `Archive` again to confirm archiving the project. Table updates to show the project is no longer displayed

5) Verified on MongoDB using the query - `{"projectName": "project-test-mrin"}` 

Screenshot 2024-09-30 at 5 44 27 PM

Works in dark mode as well with the same steps! 

Good job!

**Comment by pallavithorat** [comment]
I've tested the PR, and it's working fine. Clicking 'Set Inactive' correctly marks the project as inactive without any UI issues. The 'Confirm' button successfully archives the project and refreshes the page.
PR #2673

**Comment by javid679** [comment]
I have tested this, and everything is working fine as intended, but somehow the functionality is not quickly intended and taking a bit of time, see the below video for reference:


https://github.com/user-attachments/assets/af8c96c5-1d8d-43de-8da1-e440205a635c

**Review by AshishNags — DISMISSED** [review]
Approving the PR, every functionality is working as expected.
created the project
Screenshot 2024-10-09 170834

After clicking "Set Inactive" button
Screenshot 2024-10-09 170848

After clicking "Confirm" button.
Screenshot 2024-10-09 170914

**Comment by VMD281** [comment]
Hi I tested this issue and found that the set inactive feature works perfectly but when the project is confirmed to be archived it is not archived in one time.
PR#2673_2
e35b03">

**Review by zhiminV — APPROVED** [review]
I have checked that everything work as expected:

1.  "Set Inactive" will set the project inactive.
2.  "Confirm" button, the project disappeared.
3. work in dark mode

https://github.com/user-attachments/assets/ed40afb9-c17e-4a04-ac27-eecf6b07c967

**Review by SupriyaSudini — APPROVED** [review]
I have tested this, and everything is functioning correctly. Approved.
image

image

image

**Review by Rupa2400 — APPROVED** [review]
Tested PR #2673 and confirmed everything works as expected. Clicking "Set Inactive" doesn’t crash the UI, and the project is archived correctly after confirmation, both in the database and on refresh. The feature also functions well in dark mode. Great job!

https://github.com/user-attachments/assets/ca203c7e-1980-4444-9e73-98e016ab1516

**Review by Rui-Liu-github — CHANGES_REQUESTED** [review]
Hi, I reviewed PR#2673 by pulling the latest version. 
1) I tested and  clicked "Set Inactive" and sets the project inactive. I can see the the project is not inactive.
2) I tested that after clicking "Confirm" button, the project is not archived, instead, it just moves to the top of the project list. When I refresh the website, the project disappears. I think this might be an issue.

https://github.com/user-attachments/assets/f4f95380-1b5f-4878-9df3-db38aae1cd21

tested second case below, show the project moves to the top of the project list after I confirm:
review#2673_2
review#2673_3
PR_review#2673
review#2673_5_refreh
64fd4)

**Review by humera314 — COMMENTED** [review]
image
After clicking confirm project ids archied

**Comment by sri0606** [comment]
> Hi, I reviewed PR#2673 by pulling the latest version.
> 
> 1. I tested and  clicked "Set Inactive" and sets the project inactive. I can see the the project is not inactive.
> 2. I tested that after clicking "Confirm" button, the project is not archived, instead, it just moves to the top of the project list. When I refresh the website, the project disappears. I think this might be an issue.

Hey @Rui-Liu-github , can you review it again? I'm not sure why the project was not being auto-removed from table, but it should be fixed now. **Make sure to pull the latest changes.**

**Review by SnelPatare — APPROVED** [review]
The changes are working as expected. The Project is archived with Direct confirm button and after getting inactive as well. 
image

**Review by NazaninHashemian — COMMENTED** [review]
Verified that "Set Inactive" works without crashing the UI and archives the project successfully.
Confirmed the project is removed from the archive after confirming and reflected correctly in the database.
Tested functionality in both light and dark modes—no issues found.
Refactor to Project component and the new modal works well for targeted re-renders without page refreshes.
Tests (Projects.test.js, Project.test.js) updated appropriately.
Followed setup steps (branch checkout, npm install, clear cache, login as admin) and everything worked as expected.
All changes look good! 🎉

**Pull request merged**
