### PR TITLE
Olena Lesson Card Functionality

### PR DESCRIPTION
**Pull request by olenadanykh**
**Description**
Lesson list component for Phase II
lessonlistpage

**Related PRs (if any):**
This frontend PR is related to thehttps://github.com/OneCommunityGlobal/HGNRest/pull/716 backend PR (ONLY to test LIKE functionality)
&&
https://github.com/OneCommunityGlobal/HGNRest/pull/715 backend PR (Other functionality like EDIT, DELITE Card, FILTER, SORT)
…

**Main changes explained:**
Implemented functionality for the Edit & Delete buttons on the Lesson Card (visible and operable only for the author of the card).
Users can click on the Edit button to modify the lesson summary, with added validation to ensure the summary is not empty.
Users can click on the Delete button to remove the entire card.

**How to test:**

1. Checkout to the current branch.
2. Run npm install and ... to run this PR locally.
3. Log in as any user.
4. Go to http://localhost:3000/bmdashboard/lessonlist.
5. localStorage.clear() in the console
6. Verify the design, tag input functionality, and expand/collapse card functionality.
7. Test the Edit & Delete buttons, Like button functionality and Sort/Tag filter functionality and overall page design. To test, please change the authorId to your userID in backend file db.js.

**## Note:**
Please note that the Figma navigation bar and the current design differ. I've made adjustments based on Jae's request, and he has also verified the design.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/e2d6ca0e-8420-4a48-aaa8-1aba58030c0e

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/f27754cd-e4bf-4739-a348-a59c13861e6b

### CODE REVIEW

**Review by pshereen — CHANGES_REQUESTED** [review]
Editing the Review:
Tested the PR again with backend from https://github.com/OneCommunityGlobal/HGNRest/pull/715.
The Likes functionality is working as per the requirement.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/fa98b6dc-8a21-4012-ab55-b01e26682d89


However, I was not able to test other functionalities like EDIT, DELITE Card, FILTER, SORT as the db.js file did not have the option to change authorid in both the 715 and 716 backend PR branches.

**Review by Renanluizssx — COMMENTED** [review]
Hi @olenadanykh, i don't know what wrong i did, but when i log in http://localhost:3000/bmdashboard/lessonlist, the screen get empty, i put localstorage.clear() in the console and i cleaned on the localstorage but nothing happened

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/65ba58e2-ba1e-42b7-b550-d4f0d0ebb0b8

**Review by Nahiyan-16 — COMMENTED** [review]
## Tested Like Functionality
Using backend from PR (https://github.com/OneCommunityGlobal/HGNRest/pull/716),  tested "like" functionality as an admin and a volunteer. 
Likes were saved when switching accounts and worked as expected. 
Great job Olena!

Screenshot 2024-01-23 125703

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Olena, 

I've tested your PR with BE [#716](https://github.com/OneCommunityGlobal/HGNRest/pull/716). All functionalities worked as intended. Please refer to the attached video. Congrats! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/d3b0a8af-32bf-4dd3-b0fd-03bb262966b2

**Review by pshereen — DISMISSED** [review]

**Review by lacnoskillz — APPROVED** [review]
Olena! nice work! with that minor typo change the filter is now working and all the other functionality still works (edit/delete/like)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/bbfba79b-2240-40f0-aa05-61db1d853d17

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by xmyoot** [comment]
Hello Olena, awesome work! Everything worked on my end, please reference my video: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/00d66c7c-b70f-46cb-ae48-fa45e953d0a3

**Pull request merged**
