### PR TITLE
Nahiyan_Add view password eye

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Screenshot 2024-03-15 152018

## Related PRS (if any):
This frontend PR is related to the DEVELOPMENT backend.

## Main changes explained:
- Just added a an eye icon to any password inputs

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. Clear site data/cache
4. Log out to login screen
5. Observe the eye icon
6. Type in password and click on eye icon
7. Should be able to toggle visibility
8. Log in as owner
9.  Go to user profile -> Update password
10.  Verify the eye icon is on the right side of the input
11.  Go to Other Links -> User Management
12.  Click on reset password on any user
13. Verify the eye icon is on the right

## Screenshots or videos of changes:

# Before:
Screenshot 2024-03-18 174734
Screenshot 2024-03-18 174814

# After:
Screenshot 2024-03-18 174525
Screenshot 2024-03-18 174620

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/7c07b4f0-45fc-4505-bd10-e6a9657ef0c7

### CODE REVIEW

**Review by Abi-Liu — DISMISSED** [review]
Changes work as expected! Went to the login page and clicking on the eye icon toggled the input from type password to text.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/382b25df-5943-4ba1-9268-2bfba61b932c

**Review by sameersdeshpande — DISMISSED** [review]
Changes work as expected! I went to the login page and clicking on the eye icon toggled the input from type password to text. I could find no problems in seeing passwords.
Screenshot 2024-03-16 at 12 20 14 AM
Screenshot 2024-03-16 at 12 20 07 AM

**Review by linkhanthtel — DISMISSED** [review]
It is working! Clicking on the eye icon toggled the input from type password to text.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/b485d7bf-7624-4e36-8706-d237ae7ba53e

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
