### PR TITLE
EduardoV - fix tests of TeamMembersPopup that displayed errors in the dev branch

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Fix tests of TeamMembersPopup that displayed errors in the dev branch.

image

## Main changes explained:
- Removed "Add" and "Delete" buttons permissions tests that were bugged
- Simplified code
- Added render test of "Close" button

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install`  to run this PR locally
4. open file src → tests → Teams → TeamMembersPopup.test.js
5. run `npm run test src/__tests__/Teams/TeamMembersPopup.test.js`

## Screenshots or videos of changes:
This is the result it's supposed to get:

Screenshot_2

If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by JeffLi117 — APPROVED** [review]
Tests passed, code LGTM. Good job!

image

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR. It works as expected.

Screenshot 2023-10-06 at 6 14 34 PM

**Review by luisarevalo21 — APPROVED** [review]
Hello @eduvarjaor,

I tested your PR and works as intended. Great work!
Running the test yields no warning, and shows all tests pass.
Screenshot 2023-10-06 at 7 19 23 PM

**Review by yangfan2001 — APPROVED** [review]
Hi, I have run your unit tests in local and they were are passed. Great Job!
image

**Review by wantingxu7 — APPROVED** [review]
Hi, I tested and the PR works well. Good work!

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works as intended.
Screenshot 2023-10-07 at 12 53 52 AM

**Comment by Shreyj14** [comment]
test cases passed.
Screenshot 2023-10-07 at 11 12 49 AM

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions. All tests passed! And the code looks amazing. Great work!
Screenshot 2023-10-07 at 3 02 21 PM

**Review by TuanDinh140194 — APPROVED** [review]
I have check the file in src/test/Teams/TeamMembersPopup.test.js and run npm run test src/__tests__/Teams/TeamMembersPopup.test.js. I look like everything have passed. 
Screenshot 2023-10-07 123143

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended! 

week6 - PR4 (#1386)

**Review by Shubhu0 — APPROVED** [review]
Hi @eduvarjaor I Tested and reviewed your PR. Working as intended

image

**Review by beblicarl — APPROVED** [review]

**Review by lacnoskillz — APPROVED** [review]
Nice work Eduardo
After pulling your changes I see the new TeamStatusPopup test
And after running the test they all passed!
image

**Review by DavidC0126 — APPROVED** [review]
Hi @eduvarjaor I tested your PR and it works as intended.
Screenshot 2023-10-10 at 2 54 22 AM

**Review by eduhorta — APPROVED** [review]
All tests passed and the code looks good.
Great job! 👍 

image

**Review by KurtisIvey — APPROVED** [review]
pr1386 tests pass


Tests pass and function as intended

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
