### PR TITLE
Induja Add more specific link validation to Google Doc and Media file

### PR DESCRIPTION
**Pull request by Indujaks**
# Description
Add more specific link validation to Media File and GDoc links
This bug was noticed from my after reviewing pull request 980 on the front end. 
Custom Regex validator function specifically for the “Google Doc” & “Media Folder(dropbox)” needs to be created and implemented in the google doc and media folder input field. Currently, the “isValidUrl” is validating that, but only verifies that is starts with https:// etc. We need one that validates more specifically since the fields themselves are specific. This validator should be accessible in a central location such as the “utils” folder as it needs to be implemented both on the userprofile>links>edit & the otherlinks>userManagement>createNewUser modal. Images have been provided below of the target locations and the only validator function currently:

Other links > usermanagement > create new user modal
Screenshot 2023-08-23 at 12 35 25 PM

User profile > links > edit modal
Screenshot 2023-08-23 at 12 35 35 PM

Current isValidUrl function, but not specific enough for specific use cases
Screenshot 2023-08-23 at 12 35 40 PM

## Main changes explained:
1. Add specific validation regex pattern for google docs and drop box in new file under utils folder
2. Added specific validation check in editmodal instead of using a generic prototype.
3.  Included an extra step of validation while creating a new user, added a form error incase of invalid links.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. Navigate to: Dashboard → Other Links → User Management → Create New User.
5. Fill in user details as per instructions.
6. Verify Admin Document and Media Folder accept valid links.
7.  Access the user profile page for the newly created user.
8. Edit User's Links:
              Navigate to the user's profile page.
9. Verify Google Doc and Media Folder Links:
              Test if only valid links are accepted for Google Doc and Media Folder fields.

## Screenshots or videos of changes:

Before: 
Earlier while creating a user profile/Editing a profile, it was accepting any valid link irrespective of it being a google doc or drop box.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/23998d87-c1b4-45a0-a9c9-230c9e00a0d3

After: 
While creating a user profile/editing a profile, it accepts only specific valid links for google doc and drop box

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/df6f7525-bb37-415f-a7de-61fcfd271cf4

### CODE REVIEW

**Review by tsunami776 — APPROVED** [review]
Tested both userprofile>links>edit & the otherlinks>userManagement>createNewUser modal with an Owner account. Now both Google Docs and DropBox links are validated during creation and editing. Validations work as described in the PR.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/b7e77d26-9bb3-421a-9b40-8ef363e22763

**Review by DavidC0126 — COMMENTED** [review]
Hi @Indujaks I tested your PR and it works as intended. However, I noticed that if I did not put anything in the edit link and close the window on profile page, when I press the edit button again, it would show empty box. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/10dc61e9-dcfc-4aff-9142-471ea369f16e

**Review by Haoj1 — DISMISSED** [review]
@Indujaks Validation works both in creating new user and editing profile. Great work! There is a small suggestion that, on the 'edit profile' link page, if an invalid link is entered, even though it cannot be submitted, after clicking 'cancel' and then re-entering this page, the invalid link still remains in the input field. Refreshing the page resolves the issue. It would be beneficial to retrieve the correct data from the backend again when clicking 'edit'. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/0828333b-73e7-4070-92f7-aaf79f1431a4

**Review by iTvX — CHANGES_REQUESTED** [review]
I tested your pull request. In most cases, it worked as expected. However, it still allows the input 'http://www.google.com/sdfsdfsdf'.

I also tested 'http://www.dropbox.com/home', but it passed validation even though it is not a valid address.

We know that valid Google Docs URLs begin with 'https://docs.google.com/document/'. Therefore, the link 'http://www.google.com/sdfsdfsdf' should not be accepted. And also http://www.dropbox.com/home is home address of dropbox. 

You can check my video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/5dafdb44-a4f7-4718-93ef-0b4f82c0e3df

**Comment by Indujaks** [comment]
> I tested your pull request. In most cases, it worked as expected. However, it still allows the input 'http://www.google.com/sdfsdfsdf'.
> 
> I also tested 'http://www.dropbox.com/home', but it passed validation even though it is not a valid address.
> 
> We know that valid Google Docs URLs begin with 'https://docs.google.com/document/'. Therefore, the link 'http://www.google.com/sdfsdfsdf' should not be accepted. And also http://www.dropbox.com/home is home address of dropbox.
> 
> Also, even if you have a valid address without "www", it won't allow you to save. I don't think "www" is necessary.
> 
> You can check my video below:
> 
>  MyRecord_20230824112620.mp4

Updated the regex pattern for both google doc and drop box, Please review!

**Review by Jiyuanxia — APPROVED** [review]
Hi @Indujaks, I have reviewed your pull request and tested it. It works as you intended. Well done.
Screenshot 2023-08-24 165709
Screenshot 2023-08-24 165726
Screenshot 2023-08-24 170018
Screenshot 2023-08-24 170108

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Drop box link validation is failing on both the "create new user page" and "user profile link edit modal". I'm pasting the link from the folder share as well which would 100% be the link that would be here.

Google doc link validation seems to be working whenever I make a new user. Unable to tell whenever I edit links on a user's profile.

The error message on the user modal is also not descriptive at all, so if I didn't know what was occurring behind the scenes, I'd be clueless as to what was happening.

pr1167 drop box link validation failing no matter what
pr1167 doc link validation failing

**Comment by Indujaks** [comment]
> Drop box link validation is failing on both the "create new user page" and "user profile link edit modal". I'm pasting the link from the folder share as well which would 100% be the link that would be here.
> 
> Google doc link validation seems to be working whenever I make a new user. Unable to tell whenever I edit links on a user's profile.
> 
> The error message on the user modal is also not descriptive at all, so if I didn't know what was occurring behind the scenes, I'd be clueless as to what was happening.
> 
> pr1167 drop box link validation failing no matter what pr1167 doc link validation failing

Updated regex!

**Comment by n0vay** [comment]
Unable to test dues to missing dashboard icons error.

**Review by liaoyufu-leo — CHANGES_REQUESTED** [review]
Hi, this change not work on my device, I used the share link on my google doc, it's still invalid.

the link are below 
https://docs.google.com/document/d/11Fb7mS_BvSErASFvgNPOi_wwU2jpUtyqHAWzq1-_m3k/edit?usp=sharing 
image

**Comment by Indujaks** [comment]
> Hi, this change not work on my device, I used the share link on my google doc, it's still invalid.
> 
> the link are below https://docs.google.com/document/d/11Fb7mS_BvSErASFvgNPOi_wwU2jpUtyqHAWzq1-_m3k/edit?usp=sharing image

Update the regex to accept any characters after document!

**Comment by AuroraLovesWhales** [comment]
Hi @Indujaks. I tested your PR and also faced the same issue as @liaoyufu-leo. I used my own Google Doc link and it is not being accepted. The media link works as expected.

**Comment by Indujaks** [comment]
> Hi @Indujaks. I tested your PR and also faced the same issue as @liaoyufu-leo. I used my own Google Doc link and it is not being accepted. The media link works as expected.

Please test on the latest update!

**Review by arcan9 — APPROVED** [review]
Works just fine. Great work on the PR!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102492480/021344c1-0ae7-483a-a25e-065500039262

**Comment by Arsamat** [comment]
Tested the functionality and seems to be working as expected. 


Снимок экрана (262)
Снимок экрана (264)
Снимок экрана (261)

**Review by KurtisIvey — APPROVED** [review]
Functions perfectly now on my comp! Great Job 😁

No issues on usermanagement page or through the editLinks modal

**Review by navneeeth — COMMENTED** [review]
Hi @Indujaks! Tested your PR and the check for the Google Docs link works as expected. Good job! The Dropbox link check works as expected too. However, when I tested with the proper Dropbox link, the invalid link error persists. Am I doing something wrong in the test? Please let me know.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/9cce033a-cf8b-41f4-98a3-8cf048a0e57f

**Review by tsunami776 — APPROVED** [review]
I've tested your PR with an admin account the link validation works on both editing profiles and creating new users. However, maybe it is not related to this PR, I tested with an owner account and the 'other links' are missing.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/579e57a7-a8b3-4c2c-877a-22bd4bd13067

**Review by tsunami776 — APPROVED** [review]
I read @jerryren527's PR #1199 suggestions and created a new owner account. The old owner account is indeed problematic. The new owner account has 'Other links' button, and I tested validation functionalities again. The validation function still works as described in the PR.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/47d7adec-3b82-40e0-9bee-2b21f54796af

**Review by ss23046 — COMMENTED** [review]
Hi @Indujaks 
Tested your PR. Logged in as an admin user and followed the steps mentioned. The google doc and dropbox link check works as expected for invalid links. However, it's not accepting valid links for both of them. 
Screen Shot 2023-08-29 at 10 14 30 PM
Screen Shot 2023-08-29 at 10 16 37 PM

**Comment by Indujaks** [comment]
> Hi @Indujaks Tested your PR. Logged in as an admin user and followed the steps mentioned. The google doc and dropbox link check works as expected for invalid links. However, it's not accepting valid links for both of them. Screen Shot 2023-08-29 at 10 14 30 PM Screen Shot 2023-08-29 at 10 16 37 PM

The error doesn't seem to be related to this bug fix!

**Review by eduhorta — APPROVED** [review]
Everything is working as intended!
Didn't find any issue during my testing.

Great job! 👍 

image

**Review by liaoyufu-leo — APPROVED** [review]

**Review by iTvX — APPROVED** [review]
I have retested your PR, I didn't find any issue. Great job. Now, I approved you request.

**Review by navneeeth — APPROVED** [review]
Tested the latest changes and it LGTM! Good implementation. Even the Dropbox check works as expected. Also tested the Edit Links section in the profile and it works as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/c584866e-8e2f-4b4d-a0c5-c2c1312a0515

**Review by ramyaram2092 — COMMENTED** [review]
Hello @Indujaks  good job on the regex pattern 
I did give a valid URL to google docx as well as drop box but it isnt accepting it. Could you take a look at it 
This is via View Profile->Edit 
image

**Comment by Shreyj14** [comment]
Hi @Indujaks 
The PR is working as intended. 
Screenshot 2023-09-02 at 2 50 59 PM
Screenshot 2023-09-02 at 2 50 59 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/12b54979-7214-4fa8-bc5d-eeee4641af61

**Comment by GKD890** [comment]
Hi @Indujaks , I tested this PR and it works as intended. I was working on #1001 , and I think it's good idea to put test method into `src/utils/` . 
Other than that, I'm a bit disagree on that the `media folder `link need  to bind with dropbox link. And I was having such concern when working on #1001 . Because we're choosing using dropbox link as the `media folder` link at this stage. However, it could be other links than dropbox. 

Let me know what you think.

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great!

[screencast-localhost_3000-2023.09.04-11_36_16.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/828ade69-ad48-4a6c-852b-2660e3ef6609)

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
