### PR TITLE
Jerry - Track Who Changes Permissions On Permissions Management Page

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
description

**Edit (Sep 21, 2023)**: Added a table on the Permissions Management page that fetches the permissionsChangeLogs from the dev database. Only Owner accounts can view see the table. Admin accounts are unable to see the table.

## Related PRS (if any):
* BE PR [#530](https://github.com/OneCommunityGlobal/HGNRest/pull/530)

## Main changes explained:

- Added `state.userProfile` to the request body of PATCH `/roles/:roleId` requests.

 **Edit (Sep 21, 2023)**:
- Table added to Permissions Management Page, only visible to Owner accounts.
- Table has pagination (20 rows per page), with pagination buttons. The page currently fetches ALL logs from permissionChangeLogs collection. If collection contains a really large number of logs, fetching logs may take a long time.

## How to test:

1. check into current branch. 
2. do `npm install` and `...` to run this PR locally
3. Go to BE PR and follow “How to test” instructions there to start the backend.
4. Log into a Owner account
5. From Dashboard, go to Other Links→ Permissions Management→ Jerry Test Role
    - Note: I advise you to test this branch only using “Jerry Test Role”, because it was created solely for testing purposes and will not interfere with the other roles needed for HGN app to run correctly. If you do insist on testing one of the other roles, I recommend testing the “Volunteer” role. 
    2. DO NOT test the “Owner” or “Admin" roles, as that will cause unwanted permissions changes to those vital roles.
6. Add/Delete permissions, then click Save.
7. In MongoDB dev database, check the `permissionChangeLogs` collection to see a log containing information about your latest permission change.
8. You may also check the `rolesMergedPermissions` collection to see that the changed role’s permissions field has also changed accordingly.

## Screenshots or videos of changes:

**Edit (Sep 21, 2023)**: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/c587ba15-49d5-4292-9a4a-c2b5aa3ab0e6

**Edit (Sep 21, 2023)**: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/0602b8e0-5837-4bf4-841e-d8b1d5b7e5a5

https://github.com/OneCommunityGlobal/HGNRest/assets/55968519/8fa9c22e-0fc3-46a4-a38c-955b9044201b

## Note:

It would be ideal for the `permissionChangeLogs` collection to be read-only and for the logs to have an expiration date (i.e., be automatically deleted after some set amount of time). From my understanding, these configurations can be made to the database by Jae or any trusted developer. If there it is possible/preferable to set these configurations in a Node.js environment, please let me know!

### CODE REVIEW

**Review by EdwinLauM — DISMISSED** [review]
Hey @jerryren527! Functionality works as intended! Good job! Changed permissions and it correctly logged a new entry in the 'permissionChangeLogs' model in the db.

Might be out of the scope of this PR but I was wondering if it would also be useful to store exactly which permissions were changed for a certain role aside from the current 'permissions' property which currently contains all the permissions that role has after any changes. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/fc0b057b-321f-44bf-b028-df86179dae9e

**Review by DavidC0126 — DISMISSED** [review]
Hi @jerryren527 I tested the PR and it works as described. Good job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/14c07f04-52fb-45dc-b9d2-42949830938f

**Review by winghojackyli — DISMISSED** [review]
Hi @jerryren527 , I've tested the PR and it worked as intended. 

[screen-capture.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/01e111ba-f6e7-4fdb-b470-26a7c291b04d)

**Review by GaryB93 — DISMISSED** [review]
Tested with BE PR#530. Further testing might be needed to verify permissionChangeLogs are logged every time the permissions for a role are changed.

**Review by Shiwani99 — DISMISSED** [review]
Hi @jerryren527,

I tested your PR and it works as expected. I'm attaching a screen recording of what I tested.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/834af641-c5b3-4211-8d8f-5f381b6a1413

**Review by wantingxu7 — DISMISSED** [review]
Hi @jerryren527, the code works as expected in my local. Great work!
FE#1277
DBlog_FE#1277

**Review by robertoooc — DISMISSED** [review]
Hi @jerryren527, I tested your pr and it does work well. The new database schema you entered is being registered in MongoDb Compass and is tracking the users that make changes to the permissions. Nice job on the schema. 



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/d72088b5-cfa7-4c9f-a6b8-24047941e07f

**Review by Shiwani99 — DISMISSED** [review]
Hi,
I tested your PR again. It works as Intended. I checked if the permissions added or removed were able to be seen in MongoDB collection. It was removed from MongoDB collections when the permissions were removed and added to MongoDB when the permissions were added from owner account.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/172f9e1f-f02c-4d65-b49f-9d6b713b0016

**Comment by emunkh404** [comment]
image
Why i dont have an update even after npm install

**Comment by jerryren527** [comment]
> image Why i dont have an update even after npm install

Please try the following:
1. check into this branch, `git checkout jerry_track_who_changes_permissions`
2. pull in the latest commits, `git pull origin jerry_track_who_changes_permissions`
3. Repeat steps 1 and 2 for the backend branch (https://github.com/OneCommunityGlobal/HGNRest/pull/530)
4. Run the backend server.
5. Run the frontend server.

**Comment by emunkh404** [comment]
> > image Why i dont have an update even after npm install
> 
> Please try the following:
> 
> 1. check into this branch, `git checkout jerry_track_who_changes_permissions`
> 2. pull in the latest commits, `git pull origin jerry_track_who_changes_permissions`
> 3. Repeat steps 1 and 2 for the backend branch ([Jerry - Track Who Changes Permissions On Permissions Management Page HGNRest#530](https://github.com/OneCommunityGlobal/HGNRest/pull/530))
> 4. Run the backend server.
> 5. Run the frontend server.

image
okay, thanks. But this what is loading ... ?

**Comment by jerryren527** [comment]
> > > image Why i dont have an update even after npm install
> > 
> > 
> > Please try the following:
> > 
> > 1. check into this branch, `git checkout jerry_track_who_changes_permissions`
> > 2. pull in the latest commits, `git pull origin jerry_track_who_changes_permissions`
> > 3. Repeat steps 1 and 2 for the backend branch ([Jerry - Track Who Changes Permissions On Permissions Management Page HGNRest#530](https://github.com/OneCommunityGlobal/HGNRest/pull/530))
> > 4. Run the backend server.
> > 5. Run the frontend server.
> 
> image okay, thanks. But this what is loading ... ?

That's just a loading message that should disappear and either show a table (if logged in as Owner account) or nothing (if logged in as Admin account)

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Hi @jerryren527, I reviewed your latest updates.

Not really a big fan of how the table is looking. Do we really need to include the Role ID and the Editor ID? I feel like this is unnecessary information and we could just have the Role name and Editor name. Also, I don't know if this app needs to be mobile friendly and this might be more of a question for Jae. But I was thinking we could just have the date/time, role name, and editor name and then be able to click a See Details button for that row/changeLog that would display all the other information in a modal. If it's just for display this should be easy to implement.

Also, when I removed some permissions from Jerry test role 5 I noticed in the change log in MongoDB it says I added 4 permissions and didn't remove any according to the permissionsAdded array and the permissionsRemoved array. This doesn't seem right.

Lastly, I just wanted to point out the amount of console.logs being sent. I would like to see those removed before this branch is merged.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/644064d2-9fda-4221-af03-f0b082524ef5

**Comment by jerryren527** [comment]
> Hi @jerryren527, I reviewed your latest updates.
> 
> Not really a big fan of how the table is looking. Do we really need to include the Role ID and the Editor ID? I feel like this is unnecessary information and we could just have the Role name and Editor name. Also, I don't know if this app needs to be mobile friendly and this might be more of a question for Jae. But I was thinking we could just have the date/time, role name, and editor name and then be able to click a See Details button for that row/changeLog that would display all the other information in a modal. If it's just for display this should be easy to implement.
> 
> Also, when I removed some permissions from Jerry test role 5 I noticed in the change log in MongoDB it says I added 4 permissions and didn't remove any according to the permissionsAdded array and the permissionsRemoved array. This doesn't seem right.
> 
> Lastly, I just wanted to point out the amount of console.logs being sent. I would like to see those removed before this branch is merged.
> Screen.Recording.2023-10-02.at.1.29.37.PM.mov

Hi @GaryB93, thank you for your detailed review! You brought up some great points.

1. Jae had approved the appearance of the table. You bring up a good point that the table should be mobile friendly -- currently it is not. This is a great bug/feature to add to the Bugs+Features doc.
2. I noticed that `Jerry test role 5` had no logs in the database prior to the permissions change you made in your screen recording. I actually did not create that particular role, someone else did. And they likely created it and added those 6 initial permissions manually. Or they manually deleted logs related to `Jerry test role 5` from the database. But in any case, because there were no logs related to `Jerry test role 5` in the database prior to you clicking 'Save', it seems like you had added 4 new permissions. So with that said, this is the intended behavior. It is just strange that there is a role called `Jerry test role 5` with 6 initial permissions and no logs related to it in the database.
3. You are absolutely right about the comments. Thank you so much for catching that!

**Comment by one-community** [comment]
> Hi @jerryren527, I reviewed your latest updates.
> 
> Not really a big fan of how the table is looking. Do we really need to include the Role ID and the Editor ID? I feel like this is unnecessary information and we could just have the Role name and Editor name. Also, I don't know if this app needs to be mobile friendly and this might be more of a question for Jae. But I was thinking we could just have the date/time, role name, and editor name and then be able to click a See Details button for that row/changeLog that would display all the other information in a modal. If it's just for display this should be easy to implement.
> 
> Also, when I removed some permissions from Jerry test role 5 I noticed in the change log in MongoDB it says I added 4 permissions and didn't remove any according to the permissionsAdded array and the permissionsRemoved array. This doesn't seem right.
> 
> Lastly, I just wanted to point out the amount of console.logs being sent. I would like to see those removed before this branch is merged.
> 
>  Screen.Recording.2023-10-02.at.1.29.37.PM.mov

Looking at how this is turning out, I agree with all of Gary's suggestions here. Let's drop those extra IDs and make this more compact and looking better. I agree that making this look good for a mobile is a good job for a followup PR. Jerry, please add this action item as bullet under this PR on the Bugs Doc.

**Review by GaryB93 — DISMISSED** [review]
Hi @jerryren527, I tested your changes. The id's have been removed from the Permission Change Log table and the console.logs have been removed. Great work!

Screenshot 2023-10-10 at 12 58 55 PM

**Review by malikjahanzaib — APPROVED** [review]
Hi @jerryren527, I have reviewed this PR and the "permissionChangeLogs" table gets populated as intended when adding or removing permissions from a role. Also the updated permissions are reflected correctly in "rolesMergedPermissions" table. Great work!

Test rec(s):


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/f2d6a8af-5054-4f00-8b4f-6e617a877d8e


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/26925e7b-e6f6-4c4c-a4cf-6e10a68eb504

**Review by StrawberryCalpico — APPROVED** [review]
Hi I tested your PR and it worked as expected. Great Job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/8bff3eb8-1ac6-4f88-87c3-fed08b94a133

**Comment by Lin1404** [comment]
Hi @jerryren527 , I have tested your PR and it works as intended.
image
image

**Review by Lin1404 — DISMISSED** [review]

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Comment by beblicarl** [comment]
this functionality works as intended and the code is great as well

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.01.18-08_13_29.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/af101d35-622d-47aa-9633-7bfcafc68f9e)

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
