### PR TITLE
Alex- Add Copy Email Icon to User Management Table 

### PR DESCRIPTION
**Pull request by alexander-huerta**
# Description
- Having to drag across a user's email to select and then copy it is inefficient
- With the proposed changes, an admin can use the Copy Icon to the right of the email to quickly copy a user's email address. 
- After a successful copy, the admin will be notified via a pop up.

tast_copy_email

## Main changes explained:

1. Added Copy Icon next to each email
2. Clicking the Copy Icon will copy the users email to your clipboard
3. A success message will display after copying email

## How to test:

1. check into current branch 
2. run `npm run start:local` 
3. log as admin user
4. Navigate to user management (Other links -> User Management)
5. Click on the copy icon next to the email you would like to copy
6. Paste the email to make sure it was properly copied
7. You should receive an success window pop up

## Screenshots or videos of changes:

BEFORE SCREENSHOT
COPY_BTN_USER_MANAGEMENT

AFTER SCREENSHOT
COPT_BTN_USER_MAN COMPLETE

AFTER VIDEO
[COPY_EMAIL_COMPLETE.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59572783/505ab46e-5338-49dc-a675-c64eac8354b5)

### CODE REVIEW

**Review by eduhorta — APPROVED** [review]
Working as intended 👍
Nice job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/ffd11f4d-5c3c-4859-a2ea-fc5a522e8329

**Review by GKD890 — APPROVED** [review]
Hi, I've tested the function, it works great. Code also looks great to me. 

Besides, maybe just me, but I think using a `toast` to remind a success copy may be a bit distraction. I personally prefer a small button or something shows besides the content I just clicked.  But a `toast` align with other notifications like `saved successful`, so this one still looks good to me.

Frontend_PR#833

**Comment by alexander-huerta** [comment]
I was thinking of that trade off as well. Open to change based on other opinions.

**Review by yoyoweiii — APPROVED** [review]
Hi @alexander-huerta it works as intended! great work! It is now convenient to copy email.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60588210/ee73b4ce-c80f-4261-8e31-b7ad5d68482a

**Review by EdwinLauM — APPROVED** [review]
Works as intended! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/420df6b9-f387-42af-96a6-d658b8faf269

**Comment by yufeiStella** [comment]
It works as expected! The green success window pop up and the email is also copied to my clipboard.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/d68a10ac-520a-4df1-836d-88ad263b3c75

**Review by yufeiStella — APPROVED** [review]
It works as expected! The green success window pop up and the email is also copied to my clipboard.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/7af6574f-0153-4a84-b54e-9804c669c9f3

**Comment by AnishPandita** [comment]
Hi @alexander-huerta I tested your code and its working as intended. The copy email option is working well.
Screenshot 2023-05-17 at 4 11 35 PM

**Review by Cirakuze — APPROVED** [review]
Confirming the changes behave as expected.

**Review by stevenpaalz — APPROVED** [review]
Confirming changes work as intended. 

One minor visual consideration: The copy icon is displaced in the cell when the email string is long. May want to consider floating icon to top of cell above email text for consistency.

Screenshot 2023-05-18 at 5 09 59 PM
Screenshot 2023-05-18 at 5 14 17 PM

**Comment by OAkinbode** [comment]
The changes work as expected. 

Screenshot 2023-05-18 at 5 27 17 PM

**Review by OAkinbode — APPROVED** [review]
The changes work as intended.

Screenshot 2023-05-18 at 5 27 17 PM

**Comment by one-community** [comment]
Thank you everyone, merging! Yes, Alex please do implement Steven's suggestion though with a quick followup PR.

**Pull request merged**
