### PR TITLE
Refactored UserProfile and added new functionality

### PR DESCRIPTION
**Pull request by CameronWhiteCS**
Overhaul and refactor of the user profile:

    * Refactored UserProfile component
    * Converted component from the old React class system to the newer React hooks system
    * Fixed bug preventing phone numbers from displaying accurately after being modified
    * Changing a user's teams or assignments will no longer result in their profile being auto saved.
        - Editing the main tab didn't result in auto saving, but changing teams or projects did. This change is intended to resolve inconsistencies.
        - Editing blue squares is the only action that still results in auto saving
    * Fixed bug that prevented manual saving after modfiying a user's projects
    * Fixed bug resulting in changes to blue squares not being properly saved in all circumstances
    * Added ability to see a person's tangible hours broken down by category when viewing their profile

### CODE REVIEW

**Review by YueruZhao — APPROVED** [review]
Looks good, please merge

**Comment by CameronWhiteCS** [comment]
The first profile you viewed determined the state of this component until a page refresh. This has been fixed but required some fairly substantial changes.

**Review by YueruZhao — COMMENTED** [review]
Looks good, please merge

**Comment by CameronWhiteCS** [comment]
Unable to merge due to conflicts that then broke the tests, need a third approval.

**Review by one-community — APPROVED** [review]
Approved without review, as per Cameron's request

**Pull request merged**
