### PR TITLE
Added logout modal

### PR DESCRIPTION
**Pull request by migfernandes01**
Welcome, Dev (dropdown menu) > Logout 
Clicking cancel in the dialog leaves the user on a blank page instead of the page they were on when they attempted to log out.
This dialog should be changed from window.confirm() to a reactstrap Modal.  Use the confirmation from:  view profile > select featured (badges) > delete (any badge), as a template.

### CODE REVIEW

**Comment by EvianTan** [comment]
I checked the change in this PR, local build succussed, and I verified the behavior of "click the logout button", it worked well. However, there is a build failure on `UnAuthenticated Header page` I think you need to fix...

**Comment by migfernandes01** [comment]
@EvianTan Thanks for the comment, I will try to solve that problem.

**Review by chrisweilacker — APPROVED** [review]
lgtm, but get others to look at it too

**Comment by ronBP95** [comment]
Taking a look at this to provide a second set of eyes for confirmation

**Comment by ronBP95** [comment]
The logout modal looks fantastic and all of the buttons and redirects work as intended.
- Clicking the "X" button closes the modal
- Clicking the Cancel button closes the modal and the issue with a blank page redirect has been resolved
- Clicking logout redirects the user to the login page

**Comment by ronBP95** [comment]
This appears to be unrelated but for some reason in this branch, there is an error that is coming up that is related to team member tasks.

×
Unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'data')
/HighestGoodNetworkApp/src/components/TeamMemberTasks/TeamMemberTasks.jsx:150

**Pull request merged**
