### PR TITLE
Yi DiffedText Unit Test

### PR DESCRIPTION
**Pull request by yi-lin-1234**
# Description
Unite test for `DiffedText.jsx`

## Main changes explained:
- Add the unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test DiffedText.test.js` to run the test
4. Verify that all 3 tests have passed

## Screenshots or videos of changes:

Screenshot 2023-12-05 at 9 06 36 PM

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-06 at 7 47 40 PM

**Review by pika-chu11 — APPROVED** [review]
Hi @yi-lin-1234 , the test passed! Great Job!
PR 1642

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!
image

**Review by vikrambadhan — APPROVED** [review]
Hi, I teste your PR and all the test cases passed!

Week 15 - PR4

**Review by Hemsharavanan — APPROVED** [review]
- Your test suite effectively verifies the rendering of the DiffedText component, ensuring it renders without crashing when provided with different sets of text.
- The tests validate the correct display of text differences by applying different styles based on changes. 
- Overall the tests validate the basic rendering, diff output, and text removal handling of the DiffedText component.
- Nice job!
PR #1642 Yi DiffedText Unit Test

**Comment by DragonSlayer2401** [comment]
All tests passed as intended. Please watch my overview video for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/3a9f8126-0926-496c-9ff5-5b00f517426a

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-09 at 2 58 24 PM
Good job! @yi-lin-1234 , all the cases passed!

**Comment by beblicarl** [comment]
All tests passed successfully 

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
