### PR TITLE
EduardoV - fix tests of TeamMembersPopup that displayed errors in the dev branch

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Fix tests of TeamMembersPopup that displayed errors in the dev branch.

image

## Main changes explained:
- Removed "Add" and "Delete" buttons permissions tests that were bugged
- Simplified code
- Added render test of "Close" button

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install`  to run this PR locally
4. open file src → tests → Teams → TeamMembersPopup.test.js
5. run `npm run test src/__tests__/Teams/TeamMembersPopup.test.js`

## Screenshots or videos of changes:
This is the result it's supposed to get:

Screenshot_1

If all tests passed, everything worked as intended.

### CODE REVIEW

**Comment by emunkh404** [comment]
Hi @eduvarjaor,

I followed the steps you provided and ran the test cases. I'm pleased to report that there were no failures in the tests. Great work!

image

**Comment by one-community** [comment]
Moving this to final review so you can wrap up Eduardo. Please resolve the branch conflicts.

**Comment by one-community** [comment]
Not labeling it so other can still review it too.

**Review by AaronPersaud — APPROVED** [review]
Hi @eduvarjaor, nice job on the fix!

Everything passes. 

<b>Result of `npm run test`</b>

image

<b>Result of running the TeamMembersPopup suite</b>

image

**Review by yangfan2001 — APPROVED** [review]
Hi, I ran the unit tests in my local env and all tests were passed. Nice Fix!
image

**Review by DavidC0126 — APPROVED** [review]
LGTM. Good Job!

**Comment by beblicarl** [comment]
All tests passed 

image

**Review by beblicarl — APPROVED** [review]

**Review by cvtqx — APPROVED** [review]
All tests pass.
Screen Shot 2023-10-05 at 3 36 37 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended!

Week6 - PR3

**Comment by AriaYu927** [comment]
Hi @eduvarjaor, I tested your PR and every test pass.
Screenshot 2023-10-06 at 09 28 51

**Review by eduhorta — APPROVED** [review]
Hey @eduvarjaor!
I have tested your PR and every test is passing ✅ 

image

Please, resolve this branch conflicts 👍 

Also, for some reason there is some space between the header and the effort/summary bar
Screenshot 2023-10-06 at 14 06 23

**Review by lacnoskillz — APPROVED** [review]
Hello!
After pulling your changes locally and running the test I found that they all passed!
nice work
 image

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works as intended.
Screenshot 2023-10-06 at 4 31 40 PM

**Pull request closed without merging**
