### PR TITLE
Harshida - Change button color and alignment of Timer component.

### PR DESCRIPTION
**Pull request by harshidad**
# Description
This PR for the button color of timer on dashboard. Changed the blue color. Also when resize the browser, buttons (Start / Pause / Stop ) overlap with clear and timer. so fixed the alignment as well.  

## Related PRS (if any):
This PR is not related with any PR.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. logged In as any user 
4. go to dashboard
5. Verify the below changes on timer:
      - Click on the Start button. Verify the color of Pause button (Blue) and mouse hover color(Just dark blue)
      - Now resize the browser. Verify the buttons alignments.
      
## Screenshots or videos of changes:
Before Changes: 
Before_Changes

After Changes:
After_Changes

### CODE REVIEW

**Review by Sssky-18 — DISMISSED** [review]
Hi @harshidad, I tested this PR, and the fix worked as expected. The color on the Pause button showed correctly.  

before,
PR#1317

after,
PR#1317_2

**Review by DavidC0126 — APPROVED** [review]
Hi @harshidad I tested your PR and it works as intended.

Uploading UI_button.mov…

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-09-20 014106

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and everything works as intended.

week4 - PR1

**Comment by beblicarl** [comment]
This functionality works as intended

image

**Review by beblicarl — DISMISSED** [review]

**Review by iTvX — DISMISSED** [review]
I tested your pr, it worked as intended, good job!
CleanShot 2023-09-20 at 12 18 48@2x

**Review by Bhagyashree444 — APPROVED** [review]
Works as expected. Good job.

PR #1317

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Since this is a CSS based pull request that isn't urgent, I'm going to go against the grain and request changes because the boxes aren't aligned and of equal length(Pause and Stop aren't aligned with the top row of Clear and the timer). Timer doesn't have to be of equal length since it actually has more content. You should probably use something like a min container width to accomplish this, but you've got total freedom since it's your PR. 

Lets shoot for the moon and get this thing looking good. 

Bonus points for removing the inline styling for the z-index on the parent div

Screenshot 2023-09-20 at 3 55 50 PM

I've included the pixel widths of the containers I have issues with below:
edit

**Review by dah00 — APPROVED** [review]
Hey, PR works as expected
PR1317_check

**Comment by AnishPandita** [comment]
Hey, the tested the PR and the spacing and color look good. Although as suggested by @KurtisIvey, the buttons are slightly off the mark with width. It would be great to make them constant. 

Screenshot 2023-09-21 at 1 20 15 PM

**Comment by Jiyuanxia** [comment]
Hi @harshidad , I have reviewed your pull request and tested it. The alignment issue is fixed but the button color is the same as before.

Before:
Screenshot 2023-09-21 190218
Hovering the button:
Screenshot 2023-09-21 190223

After:
Screenshot 2023-09-21 190338
Hovering the button:
Screenshot 2023-09-21 190343

**Comment by astrjc0326** [comment]
I tried the PR and it displayed as description. 
Screen Shot 2023-09-21 at 8 08 34 PM
Screen Shot 2023-09-21 at 8 08 44 PM

**Comment by wantingxu7** [comment]
Hi, i tested and the overlapping issue was resolved but the color remains unchanged.

Before:
before

After:
after

**Review by TuanDinh140194 — CHANGES_REQUESTED** [review]
The overlap issue is fixed but the alignment between the button is still not equal. The height is good but the length of the start button is shorter than the clear button, and the pause button is longer than the clear button. It should be fixed length for the button. So that, the alignment between the buttons will equal. Moreover, the button color is not change when I hover.
Screenshot 2023-09-22 124927
Screenshot 2023-09-22 124944

**Review by JeffLi117 — APPROVED** [review]
The color changes work as intended, as well as there not being any overlap between the buttons. 

image

However, as others have stated, this could look markedly more aesthetically pleasing with a little change (perhaps changing the display into a grid format once it breaks from a straight horizontal line display - you may need to create 3 columns to allow for the timer overflow). This is only a suggestion.

**Review by JeffLi117 — CHANGES_REQUESTED** [review]
The color changes work as intended, as well as there not being any overlap between the buttons. 

image

However, as others have stated, this could look markedly more aesthetically pleasing with a little change (perhaps changing the display into a grid format once it breaks from a straight horizontal line display - you may need to create 3 columns to allow for the timer overflow). This is only a suggestion.

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions. 

1. The alignment is working as expected. I tested by resizing the browser and the alignment looks perfect.
2. However, the pause button does not change to dark blue as mouse hovering on it. Please check on this. You may check the details below in the recording.



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/fbfb5774-60ca-43c5-94f4-2fd96dc7ad03

**Review by Haoj1 — COMMENTED** [review]
Hi @harshidad. I have tested your PR. The alignments look good but the color of pause button is still same.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/34bd3a32-ba47-47c5-9120-95e165988d3d

**Comment by luisarevalo21** [comment]
Hello @harshidad
I tested your PR and works as intended great work!
However, as others stated the color is still a dark blue for mean instead of the lighter blue shown in your photo.
The alignment/sizing issue looks to be solved. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/3445ec5a-3c0f-4db0-be91-7fad269b15c0

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Alignment and button sizing looks great! As others have stated, the pause button doesn't have the hover color integrated into it. Once that's implemented, I'll approve it.

pr1317 no hover on pause

**Comment by Vishala09** [comment]
Tested your PR. It works as expected! Looks neat, Great job!!

**Before :** 

image

**After:**
image

image

**Review by Vishala09 — APPROVED** [review]

**Comment by harshidad** [comment]
> Alignment and button sizing looks great! As others have stated, the pause button doesn't have the hover color integrated into it. Once that's implemented, I'll approve it.

@KurtisIvey -   I go through with your comment mentioned above "Alignment and button sizing looks great! As others have stated, the pause button doesn't have the hover color integrated into it. Once that's implemented, I'll approve it."  
               - Here the hover color is the default behavior of the reactstrap component and it is working as expected (a little darker) See the attached video. Can you please verify it once again?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/e43bd01c-e3bc-480b-a6f1-1b976ff070e3

**Review by Shiwani99 — CHANGES_REQUESTED** [review]
Hi,
I tested your PR. The alignment looks really good for the timer. I also tried resizing the window and it was aligned well, but as mentioned before, the pause button does not have a hover color or the hover color is too dark to be differentiated.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/5ffe1736-cf7e-4c97-b5da-70aeda25ad14

**Comment by Shubhu0** [comment]
Hi @harshidad The alignment for the timer button looks good! I much prefer the current alignment. Noticed one thing, the hover feature for the PAUSE button sometimes slowed the website for 1-2 seconds, and then it was back to normal

image

I had one opinion that when testing for a smaller format such as a mobile the buttons are pushed below the timer and the timer is longer and above it. I think it would be better to have the START and STOP buttons below the timer.

image

**Comment by KurtisIvey** [comment]
audio included in the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/41cafd59-a309-4263-aecc-1ac700a8cd50

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
audio included in the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/41cafd59-a309-4263-aecc-1ac700a8cd50

once the hover issue is fixed, you'll have my approval since everything looks fantastic and the code looks good too

**Review by yi-lin-1234 — COMMENTED** [review]
Hello, I tested your PR and works as intended. Great work!
before change:
Screenshot 2023-10-14 at 1 56 12 PM
after change:
Screenshot 2023-10-14 at 1 57 41 PM

**Review by Cloid — CHANGES_REQUESTED** [review]
Hi there.

In terms of color and alignment, I tested for the base cases of pushing and hovering. Most of the functionality works already and looking at the code, this was a CSS adjustment. 

Attached is the pictures of me testing and comparing to live:
Screenshot 2023-10-20 204030

Screenshot 2023-10-20 204052

As others said, I had trouble seeing the new blue color when hovering or being pushed/neutral state. Maybe make it a more distinct blue color.

There is also a slight alignment issue with the Clear Button and Timer elapsed button that I would like to get fixed:
image

**Review by StrawberryCalpico — DISMISSED** [review]
Hi I tested your PR, it worked as intended! Great Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/d85bccf5-923e-4a29-89c0-0fabcbe7aaad

**Comment by palakgosalia** [comment]
Hey, I tested and reviewed your PR. It works as expected. Thank you

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/9c8f41bb-3a67-40fb-aab4-045403cf62dd

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Pull request closed without merging**
