### PR TITLE
Change the UI of the dropdown on clicking the ‘Edit’ button next to a task 

### PR DESCRIPTION
**Pull request by Lemonnycodes**
# Description
Screenshot 2024-09-17 181633

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:

- Update file ControllerRow.jsx: Adjusted button styles to improve margins and spacing for dropdown options (Add Task, Remove, Move, Copy).
- Update styles.css: Added necessary CSS rules for consistent padding and spacing between buttons.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links>Projects>Click WBS Icon>Choose WBS>Edit
6. Click Edit next to the task.
7. verify this new feature works in dark mode

## Screenshots or videos of changes:
Before Changes: 
image

After Changes:

https://github.com/user-attachments/assets/436977e6-2eb9-445e-a930-7e63ec2f8788

### CODE REVIEW

**Review by RishithaMamidala — APPROVED** [review]
@Lemonnycodes 
The layout is correct on clicking edit in WBS and UI changes are perfect.
PR 2689

**Review by manikittu810 — APPROVED** [review]
Hello @Lemonnycodes 
Everything is working as mentioned.
Screenshot 2024-09-18 at 6 27 42 PM

Thank you.

**Review by Lexie5212 — APPROVED** [review]
I test this PR, and the added UI changes work both in the light and dark mode

https://github.com/user-attachments/assets/44b8386e-6cc0-42ee-a90a-f3f8fd9067e6

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and it works as expected in both light and dark mode. 


https://github.com/user-attachments/assets/9ed47100-4490-427a-ab8b-61d0a7b79f00

**Review by chu-ziyu — APPROVED** [review]
I tested this PR and everything worked as expected in both light mode and dark mode.
Screenshot 2024-09-19 at 4 36 05 PM
Screenshot 2024-09-19 at 4 36 15 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/1f6f44e6-2e81-44a4-b1bf-5ced82632c85

**Comment by beblicarl** [comment]
this feature works as intended and the code is great

[screencast-localhost_3000-2024_09_20-08_59_52.webm](https://github.com/user-attachments/assets/81397d26-e324-4e53-9ff6-72a67d35f489)

**Review by beblicarl — APPROVED** [review]

**Review by anirudhsk2107 — APPROVED** [review]
The changes for this PR are working properly in both light and dark modes

Screen Shot 2024-09-20 at 9 27 30 PM
Screen Shot 2024-09-20 at 9 27 38 PM

**Review by ashmita123 — APPROVED** [review]
The UI changes to the dropdown when clicking the 'Edit' button works as mentioned. Tested both in light and dark modes, and everything functions as expected.

https://github.com/user-attachments/assets/de032fae-eb93-4fa1-989f-c98fd29bdacd

**Review by mohangadde1 — APPROVED** [review]
image
image
Tested the PR both light and dark mode, works fine.

**Review by ArtemisNyx3 — APPROVED** [review]
image
Ui fixed 👍🏽

**Review by sam19981 — APPROVED** [review]
Changes are working as expected.

Screenshot 2024-09-21 at 10 09 31 PM

**Review by Gauravmg6 — APPROVED** [review]
It was working as expected.
Screenshot 2024-09-22 181720

**Review by anandsesha — APPROVED** [review]
Reviewed this PR and the UI changes look great. The buttons added to Edit Task row have consistent styling and spacing and are responsive. The changes work in both dark and light modes. The codebase looks clean. Great job!

Screenshot (1078)
Screenshot (1076)

**Comment by one-community** [comment]
Thank you all, merging!  So much nicer!

**Pull request merged**
