### PR TITLE
Rahul Fix Reports Team Page On Small Screens

### PR DESCRIPTION
**Pull request by slidracoon72**
Screenshot 2024-10-16 at 11 03 09 AM

# Description
Updated the layout and styling in the Reports component to improve the Reports Teams page's usability on smaller screens. Enhanced the table under "Breakdown of Weekly Hours So Far This Week" for better responsiveness and a cleaner appearance. Prioritized readability and user experience across various screen sizes.

## Related PRS (if any):
No related PRS

## Main changes explained:
- Updated styling and layout of the ReportHeader component
- Updated the table alignment in the ReportChart component
- Updated other components to adjust the layout and improve the styling
- Now, when selecting a team member’s name, the next page that pops up is improved for better appeal and usability on smaller screens.

## How to test:
1. check into current branch: `git checkout Rahul-Fix-Reports-Team-Page-Layout-On-Small-Screens`
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→Reports→Reports→Teams→Click any team name…
6. Verify that the team header is responsive and looks better for smaller screens
7. Verify the table below "Breakdown of Weekly Hours So Far This Week" is aligned properly
8. Check both the changes in light and dark modes

## Screenshots or videos of changes:

Before:
https://www.loom.com/share/6e7fcf48833848409af47e7d2a2a6c9e?sid=f56fba71-bcf4-4263-b2e5-ac7a7485386b

After:
https://www.loom.com/share/2607637381ae40e683e575699dbf2039?sid=5aee3c87-8c97-4fd6-8462-071c5f4bed67

### CODE REVIEW

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/b25c82f6-b142-45b9-ab02-07431160b0d7

**Review by manikittu810 — DISMISSED** [review]
Hello @slidracoon72 
Everything is working as mentioned.


https://github.com/user-attachments/assets/adabb378-dc80-476d-ab80-25e2141f5548


Thank you.

**Review by NK3101 — DISMISSED** [review]
Tested the PR in both light and dark modes, and everything works as expected.

https://github.com/user-attachments/assets/faaee779-2953-489c-8cb7-a6060431744b

**Review by shashankhv — CHANGES_REQUESTED** [review]
I have tested the PR, and the components you mentioned are working as expected. However, the last component with the calendar and table is still not optimized for smaller screens. Since the PR is titled ‘Fixing the reports page,’ I wanted to bring this up for further improvement.

[Rahul-PR.webm](https://github.com/user-attachments/assets/2bc6be6e-e978-467a-b869-3ba944fe3cfd)

**Comment by slidracoon72** [comment]
> I have tested the PR, and the components you mentioned are working as expected. However, the last component with the calendar and table is still not optimized for smaller screens. Since the PR is titled ‘Fixing the reports page,’ I wanted to bring this up for further improvement.

@shashankhv The update you mentioned is not included in this pull request because it is not a requested bug fix. A separate pull request will be needed for this change.

**Review by shashankhv — APPROVED** [review]

**Comment by shashankhv** [comment]
@slidracoon72 Thanks for the clarification. I have approved it now.

**Comment by geetamatkar** [comment]
Hi @slidracoon72 ,
Tested this PR and 'Breakdown of Weekly Hours So Far This Week' table is alligned properly in different resolutions.

Screenshot 2024-10-19 at 3 35 12 PM
Screenshot 2024-10-19 at 3 35 34 PM
Screenshot 2024-10-19 at 3 35 57 PM

**Review by lng2020 — APPROVED** [review]
LGTM about the style change. However, I think the change in code format is unnecessary but not a blocker for this PR.

https://github.com/user-attachments/assets/9cbdf40c-fd37-45d7-8a74-8b616954f86f

**Review by CodewithKoushica — DISMISSED** [review]
The updates to the Reports component greatly improve the user experience on smaller screens, especially with the enhanced table layout under "Breakdown of Weekly Hours So Far This Week." The overall responsiveness and readability are much better now. Tested in both light and dark modes, and everything functions smoothly.

Approving this PR.
Screenshot 2024-10-23 at 5 17 40 PM

**Review by nikhilgiri0226 — DISMISSED** [review]
I have tested the PR. Everything looks good and the components you mentioned were responsive in the small and large screens.


https://github.com/user-attachments/assets/a04ac2ac-9cae-4982-a4c5-0dadf6f9ea10

**Review by anji-annavarapu — APPROVED** [review]

**Review by hqzhu0913 — DISMISSED** [review]
header is responsive and works well in light and dark mode.
Screenshot 2024-10-30 at 11 43 31 PM
Screenshot 2024-10-30 at 11 44 32 PM

**Review by samarth9201 — DISMISSED** [review]
Verified the Changes, page is responsive to all sizes.

Screenshot 2024-10-31 020616
Screenshot 2024-10-31 020623
Screenshot 2024-10-31 020632
Screenshot 2024-10-31 020641

**Review by hqzhu0913 — DISMISSED** [review]
UI responsive layout work as expected.
https://www.loom.com/share/085342c971ae414a8b59ed3f7f7e94af?sid=4921e62d-8426-4d50-bf0b-2c80200d0bd7

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
