### PR TITLE
Akshay Fix Weekly Summary Tab Dates

### PR DESCRIPTION
**Pull request by agujjar2206**
# Description
This PR fixes the date calculation issue in the WeeklySummary component that caused an 8-day gap between the 'Last Week' and 'Week Before Last' tabs. The issue was due to incorrect date calculations in the moment.js library, caused by Daylight Savings Time (DST).
Fixes Weekly Summaries Component (Priority High) bug

## Mainly changes explained:
Update date calculation logic in WeeklySummary.jsx to correctly calculate the due dates for the 'Last Week', 'Week Before Last', and 'Three Weeks Ago' tabs.
Add comments to the code to explain the date calculation logic.

## How to test:
1. Check out the current branch.
2. Run npm install to ensure all dependencies are installed.
3. Log in as an admin user.
4. Go to the Weekly Summary component by clicking on Summary in the Dashboard.
5. Verify that the dates on the 'Last Week', 'Week Before Last', and 'Three Weeks Ago' tabs are calculated correctly and there is no 8-day gap between them.

## Screenshots or videos of changes:
Before Fix:
screenshot4
After Fix:
screenshot3

Note:
This PR includes only the changes related to fixing the date calculation issue in the WeeklySummary component. The code has been tested locally, and the issue has been resolved.

### CODE REVIEW

**Comment by one-community** [comment]
Excellent, thank you!

**Comment by AnishPandita** [comment]
Hi @agujjar2206 I testes the PR and the date calculation seems to work correctly.
Screenshot 2023-03-28 at 3 38 37 PM
Screenshot 2023-03-28 at 3 38 09 PM

**Comment by vitorsaa2k** [comment]
Hello @agujjar2206! I've tested and the label shows as intended. But I agree with @ypan710 suggestion to change the label of "Week Before Last" to "Two Weeks Ago"

image

**Review by vitorsaa2k — COMMENTED** [review]
Hello @agujjar2206! I've tested and the label shows as intended. But I agree with @ypan710 suggestion to change the label of "Week Before Last" to "Two Weeks Ago"

image

**Comment by one-community** [comment]
I'd like to keep it as "Week Before Last" please.

**Comment by Jorge-Nerd** [comment]
Hi @agujjar2206  I tested and it work fine I just suggest to change the names to " nº of weeks before "

After fix 
image

**Comment by one-community** [comment]
Again: I'd like to keep it as "Week Before Last" please.

**Comment by one-community** [comment]
Thank you everyone. Moving this one to final review...

**Comment by agujjar2206** [comment]
> Hi @agujjar2206 I testes the PR and the date calculation seems to work correctly.
> Screenshot 2023-03-28 at 3 38 37 PM
> Screenshot 2023-03-28 at 3 38 09 PM

Hello @AnishPandita, the changes made are in the Weekly Summaries component, not Tasks and Timelogs. Please read the description carefully, and test the PR again.

**Comment by agujjar2206** [comment]
> Suggest changing variable name "dueDateBeforeLast" to "TwoWeeksAgo" and label for "Week Before Last" to "Two Weeks Ago". Besides that, I've reviewed the PR and the date calculations are displayed correctly.
> 
> Screen Shot 2023-03-30 at 11 33 14 AM
> 
> Screen Shot 2023-03-30 at 11 33 18 AM
> 
> Screen Shot 2023-03-30 at 11 33 22 AM

Hello @ypan710, thank you for the suggestion. Please check the dates in the Weekly Summaries Component, not Tasks and Timelogs. Thank you.

**Comment by ypan710** [comment]
Hi @agujjar2206 I've retested the PR and result is as expected. Thanks.

Screen Shot 2023-04-04 at 9 58 37 PM

**Comment by one-community** [comment]
Works for the 3 I can see. 4th tab seems to have vanished if you'd like to take this new bug I just logged: "Add missing “Two Weeks Ago” tab to the Weekly Summaries Reports Page"

**Pull request merged**
