### PR TITLE
Lawrence - Fix back to top covering numbers on User Management page

### PR DESCRIPTION
**Pull request by lchua2314**
# Description
Screenshot (2898)

## Main changes explained:
- Update file UserManagement.jsx to add extra margins below the pagination menu so there's room for the "Back to Top" button

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. log as admin user
4. go to dashboard→ other links → user management
5. verify that you can see now see the clickable numbers at the bottom of the screen

## Screenshots or videos of changes:
Before:
Capture 1

After:
Capture 8

## Note:
My screen size is smaller than average so I can't view the whole button and page numbers, but it'll probably be visible for your screen.

### CODE REVIEW

**Review by sxiong5 — DISMISSED** [review]
Worked as expected!

Screenshot 2023-08-01 at 14 11 29 (2)

**Review by winghojackyli — DISMISSED** [review]
Hi @lchua2314 , I've tested your PR and it workd as intended. The numbers are shown and I can navigate through tose numbers.

**Review by Indujaks — APPROVED** [review]
Tested your changes, works as expected! 
Just one suggestion: is there anyway we could place the button not overlaying any details?
Screenshot 2023-08-01 at 11 23 46 AM

**Review by veronicacheng2 — APPROVED** [review]
Hi @lchua2314, I tested the changes and the new layout is not covering the page number

image

**Review by joyceiphone — DISMISSED** [review]
LGTM. Working as expected. 
Screen Shot 2023-08-01 at 6 44 31 PM

**Review by TheDescendant39 — CHANGES_REQUESTED** [review]
@lchua2314 I tested your changes by changing window sizes across multiple browsers. It works as intended in all cases **except one**. 

**Issue:** 
- When I have "Automatically hide menu bar" enabled, the button gets over the page numbers. 
- It works when the menu bar is on the screen but not when it is hidden. Please refer to the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/aabad3af-0019-48bf-a0c9-0f579be5f0ee

**Note:** This maybe is a minor issue because many people don't hide their menu bar. I just wanted to point it out so it doesn't come up again sometime in the future. A very good and needed change otherwise. Thanks.

My Screen:
Liquid Retina Display: 13.6-inch (2560 × 1664)

**Review by DavidC0126 — COMMENTED** [review]
Hi @lchua2314,

I have tested your PR and it  works perfectly.
page_number_shown

**Comment by AnishPandita** [comment]
Hi @lchua2314, it works well.
Screenshot 2023-08-02 at 12 55 35 AM

**Review by AnishPandita — APPROVED** [review]

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

issue #1078

**Review by yurisokolovicz — DISMISSED** [review]
Hi @lchua2314,
The new functionality is working fine. Please see the video below using both 1-25 and 1-50 options. Utilizing a margin bottom of 50px was sufficient to prevent the previous behavior.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/c8ca2fe2-aeb7-4be5-ab75-8397093d9e26

**Review by eduvarjaor — DISMISSED** [review]
Hi @lchua2314 

You made a great job doing this PR. Worked perfectly.
Screenshot_1

**Comment by iTvX** [comment]
I have tested your PR, it worked good, great job!
CleanShot 2023-08-02 at 10 05 08@2x

**Review by TheDescendant39 — APPROVED** [review]
Great job with the changes @lchua2314. It works well now. Thanks

**Review by n0vay — APPROVED** [review]
Good Job! Works as intended.
image

**Review by eduhorta — APPROVED** [review]
Working as intended 👍

image

**Review by Abiddy — APPROVED** [review]
Looks good! Great job.


Screenshot from 2023-08-05 11-36-08

**Review by ramyaram2092 — DISMISSED** [review]
Looks good. Good job @lchua2314 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/5bb72cc3-a22c-4d79-9ca8-8446e603239d

**Review by BaileyM96 — DISMISSED** [review]
Good evening @lchua2314 I tested your changes and everything works great and the code looks great, good job!

## Video Walkthrough

[PR #1078 Fix back to top covering numbers on User Management page.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/cf3b6a32-f353-415a-989e-be86a21194ea)

**Comment by BaileyM96** [comment]
@one-community  this PR has 9 approvals and can be merged.

**Review by EdwinLauM — APPROVED** [review]
Hey @lchua2314. Changed work as expected! Good job! :)

Screen Shot 2023-08-05 at 6 57 18 PM

**Review by yaow62023 — DISMISSED** [review]
I have test all the changes, the clickable numbers are work. Also it can jump to different page. check the video below for details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/a58641ef-45f3-4980-808a-f8f4e72769f2

**Comment by luisarevalo21** [comment]
Hello @lchua2314 
I reviewed your PR and works as intended. Great work.

### Some notes

1. As you pointed out the button is cut off on smaller screens as noted in my screenshot. 

2. When selecting more users, i.e 25 or 50 the button is also cutoff and selecting the next page is also cutoff 
Screenshot 2023-08-06 at 9 57 54 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/51f94162-8e19-4b70-a2af-5ff4c8bcebdd

Screenshot 2023-08-06 at 9 55 03 PM


3. The first page works as intended, however, when viewing some pages the button is cutoff and hidden 
4. 
Screenshot 2023-08-06 at 9 59 55 PM
Screenshot 2023-08-06 at 10 00 04 PM
Screenshot 2023-08-06 at 10 00 14 PM

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this one to final review!

**Review by yunshan111 — DISMISSED** [review]
LGTM!

image

**Review by cvtqx — APPROVED** [review]
Button looks good, it is not covering numbers. 

Screen Shot 2023-08-09 at 12 26 45 PM

**Review by iTvX — APPROVED** [review]
I approve your request, as I checked, it worked as intended. Great job!
QQ截图20230809125747

**Review by EdwinLauM — APPROVED** [review]
Hey @lchua2314. Works as expected! Tried with different filters as well to see if the button remained the same

50 user filter:
Screen Shot 2023-08-09 at 1 22 15 PM

25 user filter:

Screen Shot 2023-08-09 at 1 22 22 PM

10 user filter:

Screen Shot 2023-08-09 at 1 22 33 PM

**Review by navneeeth — APPROVED** [review]
LGTM! The 'Back To Top' button does not overlap the page numbers. Tested with an admin account and good implementation with the margin-bottom insertion for the footer. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/6f96efe9-0b6d-42c7-9f54-331bbfee301d

**Review by Jiyuanxia — APPROVED** [review]
Hello, @lchua2314! I have completed the review of your pull request and conducted testing. The implementation appears to be functioning as intended. The "Back to Top" button behaves as expected and does not obstruct the numbers on the user management page under any circumstances. Well done!

When there are 10 items displayed on the 'User Management' page, the 'Back to Top' button does not appear at the top of the page:
Screenshot 2023-08-10 153009

The 'Back to Top' button becomes visible when scrolling down to the bottom of the page:
Screenshot 2023-08-10 153018

When there are 25 items displayed on the 'User Management' page, the 'Back to Top' button does not appear at the top of the page:
Screenshot 2023-08-10 153036

When scrolling down slightly, the 'Back to Top' button becomes visible:
Screenshot 2023-08-10 153102

The back to top button appears when scrolling down to the buttom of the page:
Screenshot 2023-08-10 153108

When there are 50 items displayed on the 'User Management' page, the 'Back to Top' button does not appear at the top of the page:
Screenshot 2023-08-10 153118

When scrolling down slightly, the 'Back to Top' button becomes visible:
Screenshot 2023-08-10 153127

The 'Back to Top' button becomes visible when scrolling down to the bottom of the page:
Screenshot 2023-08-10 153134

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works good on my device.

image

**Review by ThapeloMasasa — APPROVED** [review]
The back to the top is no longer ontop of the numbers.. it appears below it.. good Job!!

Screenshot 2023-08-11 at 7 11 49 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
