### PR TITLE
Sorting feature to sort QSTs

### PR DESCRIPTION
**Pull request by ReinaT5678**
# Description
Added a sort feature for QSTs by team code after clicking the Edit button.

## Related PRS (if any):
This frontend PR is related to the development backend.
…

## Main changes explained:
- Added styling changes to add more space between buttons.
- Added a sorting function for the QSTs after clicking the edit button.
- The sorting feature is by team codes.
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ profile → view profile → edit button under QSTs and by the save button
6. click on the Edit button. Verify that the QSTs are accurately sorted under the correct team codes.
7. verify this new feature works in [dark mode]

## Screenshots or videos of changes:

Screenshot 2024-09-19 at 5 36 35 PM
Screenshot 2024-09-19 at 5 36 47 PM

### CODE REVIEW

**Comment by geetamatkar** [comment]
Hi @ReinaT5678 ,
I tested this PR and it is working as expected.

PR2696

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as described for light and dark mode.
Screenshot 2024-09-21 at 7 47 49 AM
Screenshot 2024-09-21 at 7 48 30 AM

**Review by Dk-21 — APPROVED** [review]
Hi @ReinaT5678 
I reviewed and tested the changes and It is working as expected.

Screenshot 2024-09-21 at 7 33 00 PM

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.

**Review by khushijain03 — DISMISSED** [review]
Hi @ReinaT5678, 

The PR works as expected.

Screenshot 2024-10-06 at 1 04 23 AM

**Comment by pallavithorat** [comment]
I tested the PR, and the changes works as expected in both light and dark modes.
PR #2696
PR2#2696

**Review by mrinalini-raghavendran19 — APPROVED** [review]
Looks good to me!

The changes work as expected by the requirement. I can now see the buttons filtered according to the team code when we click on the `Edit` option.

I do have some suggestions though, the sorting looks scattered and not aligned in the page. Maybe this is a potential enhancement to the filtering feature.

Light mode:

Screenshot 2024-10-07 at 4 57 21 PM

Dark mode:

Screenshot 2024-10-07 at 4 58 14 PM

**Review by Jingyii800 — APPROVED** [review]
Hi, I have tested this function and it works well. Great job!
https://github.com/user-attachments/assets/55b9ee4c-920e-4d47-8da5-5176ffbda877

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected. Below are the screenshots for reference:
Capture2696

**Comment by VMD281** [comment]
Hi, I reviewed the PR  and the buttons work perfectly even in dark mode.
PR#2696_1
PR#2696_2

**Comment by sheetalmangate** [comment]
I have reviewed changes but at my local its showing  "Add new QST" option instead of  "Add A new Title".

PR2696_testing

**Review by SupriyaSudini — COMMENTED** [review]
I have reviewed this PR and encountered an issue. When I clicked on "edit," it did not sort the QSTs as expected. 

image


https://github.com/user-attachments/assets/1b298107-3a9e-4387-8328-a52ef9822de9

**Review by Rui-Liu-github — APPROVED** [review]
I reviewed PR #2696, tested the profile site feature after I the Edit button feature. The QSTs are accurately sorted under the correct team codes on light and dark mode.

image
image

**Review by one-community — CHANGES_REQUESTED** [review]
It isn't a filter that I want here, I need a way to manually change the order they are presented in. 

Right now they are listed in the order they were created. I want to be able to reorder them however I like, so the ones that are similar can be kept/moved together. 

No need to show the codes like that either.

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (248)

**Comment by SatyashanthiT** [comment]
Tested the sorting feature for QSTs. Verified that after clicking the Edit button, QSTs are accurately sorted by team codes, with appropriate spacing adjustments between buttons.

image

**Review by ShraddhaShahari — COMMENTED** [review]
I have tested this PR and all the changes are working as expected. Tested this scenario on both the modes, they are working fine. Below are the screenshots attached for the reference.
Screenshot1-PR-2696

Screenshot2-PR-2696

Screenshot3-PR-2696

Screenshot4-PR-2696

**Pull request closed without merging**
