### PR TITLE
Nahiyan dark mode for all dashboard modals

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Implemented dark mode for all dashboard modals. 

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
-Dark mode on modals: **header, timelog, leaderboard, badge, and weekly summary**
-Updated loading skeletons to be in dark mode

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard
6. verify that modals are working properly across all components (**header, timelog, leaderboard, badge, and weekly summary**)

## Screenshots or videos of changes:
Screenshot 2024-05-01 203647
Screenshot 2024-05-01 203717

## Note:
Please request changes if you find any modal that is not working in dark mode

### CODE REVIEW

**Review by jennZhang93 — CHANGES_REQUESTED** [review]
Tested with owner account, but the page showed up for a few seconds and then went blank with the following console errors.

image

**Review by MinSun0814 — COMMENTED** [review]
image
image
Seems working as intended (timer, time entry, message, badge).

**Comment by Nahiyan-16** [comment]
> Tested with owner account, but the page showed up for a few seconds and then went blank with the following console errors.
> 
> image

Hey @jennZhang93, thanks for bringing this to my attention, but I can't seem to replicate it and neither can the other reviewer. Can you please list the steps taken to recreate this bug?

**Comment by jennZhang93** [comment]
> > Tested with owner account, but the page showed up for a few seconds and then went blank with the following console errors.
> > image
> 
> Hey @jennZhang93, thanks for bringing this to my attention, but I can't seem to replicate it and neither can the other reviewer. Can you please list the steps taken to recreate this bug?

Yes, so I `git pull` your branch and backend dev branch, `npm install` for both, `npm start` for backend, `npm run start:local` for frontend. Then I go to my localhost to see the webpage and then it shows a blank page after trying to load for a few sec.

**Review by linkhanthtel — DISMISSED** [review]
I reviewed your PR and all modals work properly! Nice work!

**Review by aaryaneil — APPROVED** [review]
Tested the PR and I am also getting a blank screen, I've attached a video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/8ff80f7d-6d69-4aa7-b0d1-b453ef53ade4

**Review by aaryaneil — CHANGES_REQUESTED** [review]
Tested the PR and I am also getting a blank screen, I've attached a video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/c7ec80c0-0ff9-4443-b843-b7577c649209

**Comment by beblicarl** [comment]
This functionality is working as intended and the code is great

image

image

image

**Review by beblicarl — DISMISSED** [review]

**Review by hbodgal — DISMISSED** [review]
Everything works well. I have checked info boxes, pop-ups. They all works well with Dark mode.

image

**Review by tdkent — DISMISSED** [review]
Nice work, the dark mode color scheme applies to the Dashboard modals.

Screenshot 2024-05-04 at 11 49 01 PM
Screenshot 2024-05-04 at 11 49 30 PM

**Review by jennZhang93 — DISMISSED** [review]
Tested again with owner account and everything worked as expected. The only difference was the updates on the dev backend branch. Good work!

Screenshot 2024-05-10 at 12 46 47 PM
Screenshot 2024-05-10 at 12 46 03 PM
Screenshot 2024-05-10 at 12 46 10 PM
Screenshot 2024-05-10 at 12 46 27 PM

**Review by nathcarnevalli — COMMENTED** [review]
Everything is working as expected, but how can I access the Create message modal?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/a9f87530-f6b6-4cf1-b129-2397cb67913e

**Comment by ZhangPeizhou** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/6c15ccba-3eeb-4a5d-bea7-6be79f4f8aec

Everything switched to the dark mode as expected.

**Review by jayyy-s — APPROVED** [review]
Looks good to me. Checked information, badge report, and add time entry modals and they were all dark mode. Nothing missing as far as I can see so approving.
add tang modal
badge report modal
info modal

**Pull request merged**
