### PR TITLE
Satya fix teams UI

### PR DESCRIPTION
**Pull request by SatyashanthiT**
Description
This PR addresses the UI issues on the Teams page in the admin/owner profile. These issues are primarily related to table and card layout at various screen sizes:

At 768px and below, the table is not centered and the top two cards lack padding.
At 575px and below, the table starts side-scrolling.
At 479px and below, the cards stack vertically.
Around 400px and below, the members modal’s table cuts off and starts side-scrolling.

Related PRS (if any):
This PR is related to the PR2416 front-end PR.

Main changes explained:
Updated Teams.css to reduce font size at 575px and below.
Adjusted padding for cards at 768px and below.
Reduced card size at 479px to prevent vertical stacking.
Implemented overflow-x adjustments for members modal at 400px and below.

How to test:
Check into the current branch.
Run npm install to update dependencies.
Clear site data/cache.
Log in as an admin user.
Navigate to Dashboard → Teams page.
Verify table alignment, card layout, and responsiveness across 768px, 575px, 479px, and 400px screen sizes.
Ensure that the changes function properly in dark mode.

Screenshots or videos of changes:

center table
Has padding - 756
has padding 594
reduced side scrolling
no vertical stacking 414px
reduced font

### CODE REVIEW

**Review by Muzammil603 — CHANGES_REQUESTED** [review]
image
image
image
image
image
image
not working as expected

**Review by ziyanw52 — CHANGES_REQUESTED** [review]
Hi, I have test this PR, and when if it's 427px and below, the cards stack vertically. Please see screenshot as reference.
701727849597_ pic_hd

**Review by nikhilgiri0226 — DISMISSED** [review]
I have reviewed the PR and all the below issues seems to be fixed but there is a slight misalignment in the position of button "Active teams" when the screen size was 400 px or below. I am not sure if this is the expected behavior or needs to be fixed, So, I am not requesting a change.

At 768px and below, the table is not centered and the top two cards lack padding.
At 575px and below, the table starts side-scrolling.
At 479px and below, the cards stack vertically.
Around 400px and below, the members modal’s table cuts off and starts side-scrolling.

Screenshot_2736_400px
Screenshot_2736_479px
Screenshot_2736_575px
Screenshot_2736_768px

**Review by Jingyii800 — DISMISSED** [review]
I have tested this function and under the 756 px width, the teams list and members list looks as expected.

https://github.com/user-attachments/assets/5e4754b0-d84e-4014-91aa-1a01bbb60e49

**Comment by ShreyaLaheri** [comment]
I have tested this PR - functionality wise everything looks okay. However, there seems to be a little misalignment in elements as we change screen sizes.
image
image

**Review by SharadhaS24 — CHANGES_REQUESTED** [review]
The PR is working as expected in 700px but the edit delete button of the website is getting cropped in 300px,400px and 500px screen in Safari and is not working as expected.

image
image
image
image

**Review by SharadhaS24 — DISMISSED** [review]
The PR is working as expected in 700px 300px,400px and 500px perfectly . Tested the PR in Safari with both light and dark mode.

image
image
image
image

**Review by NK3101 — APPROVED** [review]
The PR is working as expected in 700px, 400px and 500px. Tested the PR in both light and dark mode.

Screenshot 2024-10-24 at 11 10 04 PM
Screenshot 2024-10-24 at 11 09 31 PM
Screenshot 2024-10-24 at 11 05 46 PM

**Review by Muhideenthegreat — APPROVED** [review]
Verification:

The UI is much responsive with the various paddings added and works as expected:

Screenshot 2024-10-26 at 5 56 18 PM
Screenshot 2024-10-26 at 5 56 57 PM
Screenshot 2024-10-26 at 5 57 39 PM

**Comment by SatyashanthiT** [comment]
All requested changes have been addressed, and the failing tests are resolved. This PR is ready for review.

**Review by ziyanw52 — APPROVED** [review]
Hi, I've checked this and the UI looks good!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
