### PR TITLE
Add curruserId into data

### PR DESCRIPTION
**Pull request by yunshan111**
# Description
 Improve efficiency of time log page - esp converting intangible time to tangible and vice versa  

1. Leaderboard → Click a person’s time bar → Create intangible time entry for that person → save → refresh → click the “tangible” box to make that time entry tangible and you’ll see the process takes way longer than it should. It should instantly make it tangible
2. Refresh and confirm it saved 

## Related PRS (if any):
N/A

## Main changes explained:
- Fix bug in timeEntries.js

## How to test:
1. check into current branch
4. do **npm run install** and then **npm run start** run this PR locally
5. log as admin user
6. go to dashboard→ Leaderboard → Click a person’s time bar → Create intangible time entry for that person → save
7. repeat step 6 for multiple users. Open 5-10 tabs for each person's time entry.
8. click on the checkbox of tangible for each tab and test if they function correctly and evaluate the component's efficiency.

## Screenshots or videos of changes:
Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/5f8f2007-aa40-4698-8f3f-62a4e273e1ee

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/53397a3b-97aa-4586-9471-73c79aa92f4e

### CODE REVIEW

**Review by Bali2Mohit — COMMENTED** [review]
Hi @yunshan111 , tested your PR changes. Can see a difference in time before and after the changes. Works perfectly. well done.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94716419/0253b76c-5f67-4b2e-a3cf-6e046351aeac

**Review by pika-chu11 — APPROVED** [review]
Hi @yunshan111 , I have tested the code, and the code did improve the efficiency of switching status of a event, tangible or intangible. Good job!

Before:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/62b760be-2356-4030-8323-2f94f5c2c9d0

After:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/b98faf5d-9306-44f3-be85-b2c12fc05f17

**Review by sahilpatel18 — APPROVED** [review]
@yunshan111! The quick change that occurs after clicking on the tangible checkbox is noticeably more efficient than before. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/9b15779d-3a97-4299-b895-38c3e07ad48d

**Review by Bali2Mohit — APPROVED** [review]

**Review by Sssky-18 — APPROVED** [review]
Hi @yunshan111 , I have tested this PR, and the tangible button worked great. After assigning the intangible time, clicking the tangible button can successfully change the time to tangible. Great work. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/bd4b0e32-66d2-4d3a-807e-3cb878cfb190

**Review by wantingxu7 — APPROVED** [review]
Hi @yunshan111 
the function works well and after clicking and unclicking the checkbox, the time bar changes shortly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/e2e16a51-86bf-4e25-8eeb-4febd8b9240c

**Review by Jiyuanxia — APPROVED** [review]
Hi @yunshan111 , I have reviewed your pull request and tested it. It works as you intended. Good job!
Screenshot 2023-11-16 191156
Screenshot 2023-11-16 191234

Screenshot 2023-11-16 191228
Screenshot 2023-11-16 191203

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by navneeeth — APPROVED** [review]
The PR works as expected in improving the efficiency of the time log page in converting intangible time to tangible time and vice-versa. 

The changes are quite noticeable and everything looks good.

### Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/cb9b5175-4d4e-4f0c-93c3-24f530bfd4f6


### After:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/a7aeb1f7-8e9b-4045-bb7c-7b08e3213e8a

**Review by BaileyM96 — APPROVED** [review]
Good evening @yunshan111 I have tested your PR and everything works as described great work!

## Videos

[PR 1521 Add cursor data.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/367c06d5-03d6-47da-842d-8fd0a122d9ce)

[Checking speed of click event for tangible time.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/e1d173b4-cc62-42b9-bbbe-8663c13f60a1)

## Screenshot

Screenshot 2023-11-18 at 6 08 08 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
