### PR TITLE
Restore ability to make active/inactive using dot by person’s name

### PR DESCRIPTION
**Pull request by mounica-dingari-by**
# Description
Restore ability to make active/inactive using dot by person’s name

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to Other Links → User Management → Click Dot

## Screenshots or videos of changes:
Screenshot from 2023-08-26 09-47-42

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by AuroraLovesWhales** [comment]
Hi @mounica-dingari-by. I have tested your PR and it is working as expected. I logged in as admin and was able to set user status to active/inactive by clicking on the dot (except for the Owner role). It does take a refresh for the change in status to be updated (change of the dot color from green to grey or vise versa if I go to the user's profile page and come back, but I don't think it's an issue. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/73724af3-0db7-468e-b3ce-17711917489e

**Review by AuroraLovesWhales — APPROVED** [review]

**Review by yunshan111 — APPROVED** [review]
Tested this PR, LGTM.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/d7ef0a1c-e53d-437c-b42f-d8c17b67e5be

**Comment by Shreyj14** [comment]
Hi @mounica-dingari-by I was able to replicate the changes. Great job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/1ca4739f-1e44-4f54-84a9-d9e40e984255

**Review by Shreyj14 — APPROVED** [review]

**Review by veronicacheng2 — APPROVED** [review]
Hi @mounica-dingari-by, I have tested the PR and everything works great. I am able to toggle the active state by clicking the dot next to the name of the user on user management page.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/90b7aaed-9540-4c2e-a7c1-65eec46a3b57

**Review by ramyaram2092 — APPROVED** [review]
The functionality works as expected 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/d344174c-75f1-48d2-955b-564656c87227

**Comment by n0vay** [comment]
I am not able to get other link Icon for some reason even after clear cache and hard resrt.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/ee47193c-0f29-4601-be6e-95eff4a8a409

**Review by arcan9 — APPROVED** [review]
It worked great, although I did notice that clicking the back button on the browser, you're unable to see the change in active/inactive dot unless I refresh the page. Nice job restoring the function nonetheless!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102492480/ac805c8c-df22-4f69-b9ab-3b3aeb95de7a

**Review by yaow62023 — APPROVED** [review]
I tested your pull request within the admin account. Clicking the green dot allows for deactivating the account, and clicking the gray dot reactivates it. The functionality of the "OK" and "Close" buttons in the popup dialog also works correctly. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/26bbd8b9-de29-4b56-95d4-c986be25f09e

**Review by winghojackyli — APPROVED** [review]
Hi @mounica-dingari-by , I've tested your PR and it works as intended. I am able to set user status to active and inactive by clicking on the dot as admin. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/b6c0c0a2-6e55-4f39-b2c2-2a2c94e11188

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
