### PR TITLE
Zijie lint fix updatepassword2

### PR DESCRIPTION
**Pull request by iTvX**
# Description
This is the update version of https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1451

## How to test:

1. checkout to this branch, then `npm install`, `npm run start:local`
2. **Record a video to verify that the password update function is working normally.**

~~1. `rm .eslintignore`
3. `npx eslint src/components/UpdatePassword/UpdatePassword.jsx`
4. `npx eslint src/components/UpdatePassword/index.js`~~

### CODE REVIEW

**Review by this-journey — CHANGES_REQUESTED** [review]
Hello @iTvX !  I reviewed your PR and unfortunately it isn't working.  After logging in I cannot even access my profile or any of the other items on the NavBar.  They become available very briefly upon reload, but then become unusable.  I cleared site data and cache prior to logging in.  See my video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/20ada02f-9a0d-4025-8674-d8ea1caaee97

**Review by Alforoan — CHANGES_REQUESTED** [review]
I cleared cache and tried multiple times, but it seems that I am unable to change the password.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/2efae2bf-50f9-4ce2-8f26-b00e1def4dee

**Review by Pandani07 — CHANGES_REQUESTED** [review]
I tested this PR and i encountered an error on the backend. I could not save my changed password.
Screenshot 2024-02-08 at 8 42 44 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/90dcc6f5-1be7-4969-9dc8-f69ccd6ed458

**Review by XiaohanMeng — CHANGES_REQUESTED** [review]
Hi, I tested this PR using accounts with manager, admin, owner, and volunteer roles. All functionalities performed well. The owner can view everyone's dashboard, admins can view dashboards except for the owner's, managers cannot see the dashboards of admins and owners, and volunteers are unable to access dashboards of administrators, owners, and managers. Please refer to the video for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/c1444702-83b6-4cba-9674-5346f8f34964

**Comment by EvianTan** [comment]
Going to close this PR because #2293 is doing the same thing.

**Pull request closed without merging**
