### PR TITLE
Ilya remove task modal from reports

### PR DESCRIPTION
**Pull request by ilyaflaks**
# Description
view-all-bug

Other than converting a modal to an expanded box (see above), some bugs were noticed: 
- Total Hours were inconsistent between the minimized chart and the expanded chart
- On screens smaller than 670px the Pie Chart legend overflows and is hidden
- Console errors related to mapping arrays of data to components (no key property was provided)

# Priority: High

## Related PRS (if any):
None
…

## Main changes explained:
- Removed the modal, made the full Pie Chart expand down without covering the table under it 
- Added logic for the minimized Pie Chart to account for the tasks not being displayed if there are more than 4 total tasks. The last item on the legend will say "x other tasks" and the total hours will be consistent
- Special case: when the number of tasks is 5, all 5 will be displayed on the chart
- Added media queries to render the legend underneath the Pie Chart for screens narrower than 670px and reduced the padding for screens narrower than 435px
- fixed existing bugs related to array mapping and prop destructuring

## How to test:
1. check into current branch on the front end and "development" branch on the backend
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. [Follow these instructions](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa?sid=b05f5604-87cb-4ca1-80b8-49bd823893ee) to add a user account you want to test to a project and assign at least 6 tasks to that user
6. The tasks with no hours logged will not be displayed on the Pie Chart. To add hours logged, connect to **hgnproddb** using Mongo Compass, select the "tasks" collection, search for the task you need by **taskName** and add some number (not zero) to the "hoursLogged" field
  
task-compass

Also feel free to use the tasks from the video below

7. Go to the Home Page -> Reports dropdown -> Reports -> People -> Search to find the user account you assigned tasks to and click on it -> test the functionality by clicking "View all"
8. Test the same feature on screen sizes 435px to 670px wide and 350-435px wide

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/7258181b-dd19-45bb-b206-8c6423a51fd7

## Notes:
- Feel free to test by viewing my accounts "Ilya Manager" (30+ tasks), "Ilya Volunteer" (11 tasks) and "Ilya Newman" (5 tasks - special case)
- The console is going to have some errors not related to this PR. These can be disregarded because the code changed by this PR will not introduce these errors to the "development" branch when it gets merged

### CODE REVIEW

**Review by Nahiyan-16 — COMMENTED** [review]
## Couple of notes
Hey Ilya, first of all, great job on making the modal very responsive using media queries. 
The view all button works fine and displays the correct number of tasks.

I did however notice that the colors didn't seem to match from the pie chart to the list. For example, as you can see in the image below, the three largest tasks on the list (in terms of hours) are in two shades of purple and red but on the pie chart the three largest sections are different colors. 
Screenshot 2024-01-24 104611

Also, something else that I noticed is that the hours are not matching from the "Tasks contributed" table. I am not sure if the estimated hours are supposed to match the hours from the pie chart. Other than that great work on this!

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Ilya,

I test your pr with owner user, and everything work as intended. One small issue, as @Nahiyan-16 said, two pie charts should be constructed in such a way that the segments in each chart, ranked from the largest to the smallest, share the same colors. 
Screenshot 2024-01-24 at 13 45 28


Also, I think the estimated hours in the table are indeed supposed to be different from the hours represented in the pie chart. This is because the estimated hours are input by the user when creating the task. On the other hand, the actual time it takes to complete a task is variable and depends on the user who undertakes the task. Therefore, it's expected that these values will differ.

**Review by KevHnh — DISMISSED** [review]
Tested using an owner account and the expand feature works as intended. I understand the comments regarding the color of each segment of the pie chart made by previous reviewers, but I think it's still intuitive and comprehensive. 

image

**Review by pshereen — DISMISSED** [review]
Tested the PR as an owner user.

The modal is removed from the reports as per the requirement.

Screenshot 2024-01-24 181618

It is working as expected in responsive mode also.

Screenshot 2024-01-24 181457

However as other reviewers mentioned the color in the pie chart is not matching with the color in the table for the same task. Pls refer the task 'Bake a Pie 4' in the below screenshot. Table and pie chart are having a different shade of brown for same task.
PR-PieColorDifference

Also, a suggestion: It will be good if a small text is displayed showing particular task name and its hours once we hover mouse over each section of the pie chart.

**Review by ClemarNunes — DISMISSED** [review]
I tested the PR as an owner user. Disregarding the problems already reported in other comments, it is working as expected and the expansion feature is ok.

task

**Review by 666saofeng — APPROVED** [review]
Hi, I tested with the admin account. It worked as expected on admin side.
pr1867

**Review by SRamen1999 — DISMISSED** [review]
I tested using an owner account everything works as expected but there are some things I noticed. 

Some of the colors on the pie chart don't match with the hours listed.

Screen Shot 2024-01-29 at 1 07 19 PM


One improvement I would recommend is to sort the hours from largest to smallest or vice versa so it is easier to read.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/d5f8178b-2171-4c49-b588-7f03628dfbad

**Comment by ilyaflaks** [comment]
> ## Couple of notes
> Hey Ilya, first of all, great job on making the modal very responsive using media queries. The view all button works fine and displays the correct number of tasks.
> 
> I did however notice that the colors didn't seem to match from the pie chart to the list. For example, as you can see in the image below, the three largest tasks on the list (in terms of hours) are in two shades of purple and red but on the pie chart the three largest sections are different colors. Screenshot 2024-01-24 104611
> 
> Also, something else that I noticed is that the hours are not matching from the "Tasks contributed" table. I am not sure if the estimated hours are supposed to match the hours from the pie chart. Other than that great work on this!

@Nahiyan-16 Thank you for catching that. Even though this falls outside of the scope of this PR, I attempted to investigate why this is happening. It looks like the PieChart component accepts an object and JavaScript objects can not be sorted. I can see the chart data and the legend are in the same (random) order before being passed to the chart, but I don't know anything about the D3 library to know what goes wrong after that. 

I made a small change to this PR: sorted the projects by hoursLogged instead of by most recent. That seemed to have improved the behavior for the first 8 items, after that the chart and the legend diverge again. I'll bring this up to Jae and if he thinks this needs to be addressed, I'll add a new bug to the list so someone with knowledge of D3 can work on it.

**Comment by ilyaflaks** [comment]
> Hi Ilya,
> 
> I test your pr with owner user, and everything work as intended. One small issue, as @Nahiyan-16 said, two pie charts should be constructed in such a way that the segments in each chart, ranked from the largest to the smallest, share the same colors. Screenshot 2024-01-24 at 13 45 28
> 


@X1aoZhang99 Thanks for reviewing this PR. I did a small change and now the colors on the chart and the legend are sorted  based on the most hours logged. As for colors being different, that's a larger bug that should have it's own PR. My most recent change only remedies it to an extent. Still, I'd appreciate it if you tested the change if you have time. 

@pshereen My latest change should sort the top 8 or so tasks more accurately. However, it is not a perfect solution. Please retest if you have time. As for hover effects on the Pie Chart, that should be a different PR for someone well versed in D3 library

@SRamen1999 Good suggestion on sorting by hours in the descending order, my latest change implements that. Please retest if you have time.

**Review by Sophie-lei — APPROVED** [review]
Hey! I tested this PR and I think the pie chart works perfectly on my end. it is intuitive. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/a25563ab-3c40-4be3-afdf-db4a68ae934f

One small recommendation would be that it will look better to sort the test order by their hours.
Screenshot 2024-02-01 at 11 02 29

**Review by Pandani07 — APPROVED** [review]
I tested this PR and it works as intended. Great job with the modal, it looks great. The hours are sorted in descending order as you have mentioned.  The colors and chart legend are sorted based on the most hours logged.

Each segment's size In the pie chart corresponds to the number of hours (i.e. larger size = more hours). The UI is responsive and smooth.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/7f90126f-da04-4f05-8c70-5eaf1b797cf6

**Review by XiaohanMeng — APPROVED** [review]
Hi Ilya,

Great work on the pie chart functionality! It operates seamlessly and the chronological ordering of data is both logical and intuitive. Additionally, the color palette you've selected is beautiful and significantly enhances the chart's readability and aesthetic appeal. Fantastic job on all fronts!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/065f40c3-e139-439a-a91b-ff00187ea476

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by navneeeth — APPROVED** [review]
Hello, @ilyaflaks! Reviewed your pull request and the implementation to remove a modal from appearing when 'View All' is clicked in the Reports page under People and it works as expected!

## Testing Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/c8d90861-bddb-4cff-9467-f92d57491dc8


The implementation to expand the current box with the option to collapse the window is well-designed. 

## Responsiveness


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/b63a159a-cf0e-4d77-93ac-b42c326e60e8

The feature works great on widths in the ranges between 435-670 px and 350-435 px.  Great use of a flexbox for the `.pie-chart-wrapper` class and the media query to add padding to the `.report-page-content` and `.report-page-wrapper` classes for smaller widths.

LGTM! Approving!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
