### PR TITLE
Ramya Lint Fix: Userprofile -> TabToolTip  

### PR DESCRIPTION
**Pull request by scoopstroop92**
200w

# Description

- Lint fix for the TabToolTip (sub module) of the UserProfile Component

## Main changes explained:

- Enforced a function type for function components
- Enforced a convention in module import order
- Reordered the function definitions order

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3.  Verify if the application works as expected with respect to TabToolTip in UserProfile 

## Note:
- Thoroughly test the functionality  , ensure it  works as before . Report any error you see so that I can go ahead make similar changes in the  other modules of UserProfile component 
-  A kind request to focus on testing the frontend over the eslint test .

### CODE REVIEW

**Review by Alforoan — APPROVED** [review]
Everything seems to work normally. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/4fe4dade-ba75-4eb3-a71d-292175a8c890

**Comment by Lin1404** [comment]
Hi @ramyaram2092 , I have tested your PR. Everything looks good!
Screenshot 2023-12-06 at 9 48 22 AM
Screenshot 2023-12-06 at 9 48 44 AM
Screenshot 2023-12-06 at 9 49 00 AM
Screenshot 2023-12-06 at 9 49 14 AM

**Review by Lin1404 — APPROVED** [review]

**Comment by DragonSlayer2401** [comment]
I tested your PR all of the tooltips seem to work as expected:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/f9ca6e2c-fd50-4091-a3f3-75879195d6fd

**Review by Renanluizssx — APPROVED** [review]
Hi @ramyaram2092, i tested your application and it´s running corretly, see my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/f9746fa2-c7b9-4d7f-bcf0-2d88fe8fbc86

**Review by ShengjieMao — APPROVED** [review]
Great work. All tabs worked as expected and showed the corresponding tips properly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/ee0fc078-9d83-419a-b635-be4277c9da64

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/2cc1adfe-4995-44f0-87e1-49757996792e

**Comment by EvianTan** [comment]
Work as expected and no errors were introduced by this PR.
image

**Review by shashankm9 — COMMENTED** [review]
I have tested frontend related PR #3848. Number of People Hired vs. Total Applications page says Loading... and i dont see any graph.
PR 3848

**Pull request merged**
