### PR TITLE
Yongjian add to projects report copy functionalities

### PR DESCRIPTION
**Pull request by ypan710**
# Description
Screenshot 2023-09-19 at 5 08 15 PM

## Main changes explained:
Aligned green dots under "Active" label and made ID numbers able to be copied to clipboard upon hovering cursor over them. Made WBS names clickable and take users to their corresponding task list.

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. log as admin user
4. go to Dashboard→ Reports -> Reports -> Projects -> "AAA USE THIS PROJECT" -> click on the WBS to take to task list
5. verify green dots under "Active" label are aligned and ID numbers are able to be copied to clipboard.

## Screenshots or videos of changes:
Screenshot 2023-09-19 at 5 05 40 PM
Screenshot 2023-09-19 at 5 05 46 PM
Screenshot 2023-09-19 at 5 06 16 PM

Screenshot 2023-09-19 at 5 06 20 PM
Screenshot 2023-09-19 at 5 06 26 PM

### CODE REVIEW

**Review by Chuehleo — DISMISSED** [review]
Everything works as expected, great job!
Screenshot 2023-09-20 013436
Screenshot 2023-09-20 013153

**Comment by beblicarl** [comment]
The WBS isn't in alignment at my end however the copy feature works

straight-1

[screencast-hgnapplication_react_beta.surge.sh-2023.09.20-16_04_13.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/fd527bf1-f214-4c9a-a57e-45abc2a82e2c)

**Review by sxiong5 — CHANGES_REQUESTED** [review]
Hey @ypan710, I've tested the PR, and I found the alignment issue is still not solved. I checked the DOM; please consider using `table`; it may help. (Just a suggestion)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/bf33c898-7050-4191-ac67-1d856f2d3660

**Review by iTvX — DISMISSED** [review]
As I checked, this issue has not been fixed.

CleanShot 2023-09-20 at 12 15 03@2x

**Review by wantingxu7 — CHANGES_REQUESTED** [review]
Hi, I've tested the PR and the 'click to copy' function works perfectly, good Job!

However the green dots are not aligned perfectly according to window shrinking and expanding. And there is another issue which I didn't see in others' comments, the paging overlaps with the list (see picture)


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/c9c60e7d-1bbb-4d84-86ba-7c0e1391a461

**Review by dah00 — CHANGES_REQUESTED** [review]
Hey @ypan710, I tested your PR, the WBS names are clickable, which takes to task lists as intended. Also, the copy functionality works fine. However, the alignment of the labels is off and the ID number is duplicated
PR1318_taks_list
PR1318_WBS_not_aligned
PR1318_copy

**Review by Bhagyashree444 — CHANGES_REQUESTED** [review]
Good job on copy functionality and WBS names are clickable and directs on WBS task list page. However the WBS Active  labels are not aligned on my end.

PR #1318

**Comment by DavidC0126** [comment]
Copy function works as described, but encountered active labels not aligned on the page same as other people mentioned on this PR.

copied
not_aligned

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and the alignment issue is still not fixed. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/ed8b43d4-2c92-426e-9a97-54cba74b9c3e

**Comment by Jiyuanxia** [comment]
Hi @ypan710 , I have reviewed your pull request and tested it. It works as you intended for me. Good job!
Screenshot 2023-09-21 184908
Screenshot 2023-09-21 185139

**Review by Sssky-18 — DISMISSED** [review]
Hi @ypan710, I tested this PR, and I observed that all the problems mentioned by other people had been fixed. The names were clickable, and active dots were aligned. The ID can be copied, and the WBS form worked as expected. 

PR#1318

PR#1318_2

**Review by tsunami776 — DISMISSED** [review]
Hi @ypan710, I tested your PR and it works as described. Now WBS names are aligned and the copy function works as intended. Clicking on the WBS name will navigate user to the correct page.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/e808b67c-ca5f-44db-af02-239233dcc913

**Review by JeffLi117 — DISMISSED** [review]
Changes work as intended (vertically aligned green dots, IDs, and clickable WBS names) and are visually acceptable at most screen sizes. 

Initial view: 
image

When the screen size is ~1355 pixels wide, it becomes more difficult to discern where one ID ends and the other begins; once the screen width goes past that, it overlaps significantly (but the copying works well, so this is only a visual concern).
image

On mobile, alignment and copying works well (besides the overlap stated above):
image

You might be able to amend this visual issue by using a media query breakpoint within their respective table's CSS stylesheets - perhaps font could be altered to scale with a decreasing width. 
I'm unsure of if this is intended/important, but one semi-confusing aspect for me is when the user (if not using a very wide screen) needs to drag the horizontal scrollbar to get to the second ID string, the top column categories  (#, Name, Active, ID) do not move with the scrollbar but rather stay fixed at the top. Maybe it's worth looking into, later down the line.
These are only suggestions from a visual standpoint. Great work!

**Review by dah00 — DISMISSED** [review]
I tested your PR again after your changes and everything works well now. Everything under the WBS section is now vertically aligned. The copy functionality works still and the WBS names are clickable. Great job!
PR1318_copied
PR1318_aligned
PR1318_taks_list

**Review by Haoj1 — DISMISSED** [review]
@ypan710 The wbs is clickable and the user is displayed correctly

**Review by sxiong5 — DISMISSED** [review]
Hey @ypan710, the PR LGTM! Great job! The alignment issue has been fixed.

Screenshot 2023-09-26 at 14 09 21 (2)

**Review by Bhagyashree444 — DISMISSED** [review]
The alignment and copy functionality works as expected. Great Job!
PR #1318

**Comment by Shubhu0** [comment]
Hi @ypan710 Reviewed the PR and it was working as intended for me. The copy feature works correctly and copies the text, and the green icons are aligned. Good work!

image
image

**Comment by astrjc0326** [comment]
Hi, I tested the PR and the copy feature and the align issue of the bullet points are fixed as expected. Great Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/7a275166-f677-47aa-8e4b-9d18ec821078

Responsive web design improvement: Bullet points overlap names at certain window sizes with longer lengths.
 Screen Shot 2023-10-01 at 9 09 49 PM

**Review by wantingxu7 — DISMISSED** [review]

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
<h1>My suggested revisions:</h1>

Inconsistent CSS naming conventions. You've got 3 different naming conventions going on in this example. This could lead to others accidentally creating a similar class such as "scroll_x" and breaking the app stylistically. Would suggest just following BEM standards since that was the standard in the CSS files before you started making new classes. There's way too much CSS issues going on throughout the app already, so just trying to prevent it from getting worse in the future. You're also borrowing classes between ProjectMemberTable.jsx & WbsTable.jsx which is going to be really weird in the future if someone has to modify these components. 

For the class "scroll_x", if you want that reusability it should be relocated into App.css under the class name scroll-x-overflow as it would become self documenting in the class name and located in a central location.

for example:
   instead of: projectProfile ~ you'd use project-profile
   instead of: projects__active--input ~ you'd use projects-active-input
pr1318 inconsistent naming convention as theres 3 dif types here

Your break point should be adjusted as there's overlap when sizing down.
pr1318 breakpoints need to be adjusted along with font-size


There's an issue with this section right here as the numbers aren't centered and the green dots aren't aligned vertically:
pr1318 bad css
The width being added doesn't serve any real purpose in the css. The number itself is also not centered.

pr1318 fix project-id styling

There's no reason for the # to be inside another div when that div isn't directly styled and we can just omit it entirely.
pr1318 fix projectMemberTable syntax

Because of styling somewhere else in the app that I have no idea of the location of, this is the solution I'd use for centering the green dot in the right hand section. We're enhancing specificity with y margin by adding this new class project-active-indicator. (Note: do not add !important willy nilly unless the target is very specific otherwise it'll cause nightmares for other people lol, that's why we use BEM convention)
pr1318 fix dot centering in projectMemberTable

You're also reusing the exact css and jsx structuring in the screenshot below. You might be better off making a new component so you can reuse it in both of these applications and have isolated css for that new component since you're reusing CSS form another section that is named in a way to be specific for that very section. WbsTable.jsx also has the same issue of the green dot not being vertically aligned(use solution above):
pr1318 code identical structure better off in own component possibly since reusing css

There's a stylesheet specifically for WbsTable.css, so you shouldn't be using inline styling:
pr1318 theres a style sheet so no need for inline styling

This one wasn't you, but it'd be great if you could remove them since you're working in the file WbsTable.jsx:
pr1318 old console logs from someone else that we should clean up

There's also 3 errors present in the console on this page:
pr1318 errors in the console after removing all the console logs


Task list for approval:
 - fix things noted above
 - fix all css naming conventions that were modified in non BEM format
 - remove console.logs
 - fix console errors
 
There were several issues in this pull request. Once these issues are corrected, I'll take a deeper dive back into it. This process took a considerable amount of time, and it's possible that I missed a few things.

**Comment by ypan710** [comment]
> # My suggested revisions:
> Inconsistent CSS naming conventions. You've got 3 different naming conventions going on in this example. This could lead to others accidentally creating a similar class such as "scroll_x" and breaking the app stylistically. Would suggest just following BEM standards since that was the standard in the CSS files before you started making new classes. There's way too much CSS issues going on throughout the app already, so just trying to prevent it from getting worse in the future. You're also borrowing classes between ProjectMemberTable.jsx & WbsTable.jsx which is going to be really weird in the future if someone has to modify these components.
> 
> For the class "scroll_x", if you want that reusability it should be relocated into App.css under the class name scroll-x-overflow as it would become self documenting in the class name and located in a central location.
> 
> for example: instead of: projectProfile ~ you'd use project-profile instead of: projects__active--input ~ you'd use projects-active-input pr1318 inconsistent naming convention as theres 3 dif types here
> 
> Your break point should be adjusted as there's overlap when sizing down. pr1318 breakpoints need to be adjusted along with font-size
> 
> There's an issue with this section right here as the numbers aren't centered and the green dots aren't aligned vertically: pr1318 bad css The width being added doesn't serve any real purpose in the css. The number itself is also not centered.
> 
> pr1318 fix project-id styling
> 
> There's no reason for the # to be inside another div when that div isn't directly styled and we can just omit it entirely. pr1318 fix projectMemberTable syntax
> 
> Because of styling somewhere else in the app that I have no idea of the location of, this is the solution I'd use for centering the green dot in the right hand section. We're enhancing specificity with y margin by adding this new class project-active-indicator. (Note: do not add !important willy nilly unless the target is very specific otherwise it'll cause nightmares for other people lol, that's why we use BEM convention) pr1318 fix dot centering in projectMemberTable
> 
> You're also reusing the exact css and jsx structuring in the screenshot below. You might be better off making a new component so you can reuse it in both of these applications and have isolated css for that new component since you're reusing CSS form another section that is named in a way to be specific for that very section. WbsTable.jsx also has the same issue of the green dot not being vertically aligned(use solution above): pr1318 code identical structure better off in own component possibly since reusing css
> 
> There's a stylesheet specifically for WbsTable.css, so you shouldn't be using inline styling: pr1318 theres a style sheet so no need for inline styling
> 
> This one wasn't you, but it'd be great if you could remove them since you're working in the file WbsTable.jsx: pr1318 old console logs from someone else that we should clean up
> 
> There's also 3 errors present in the console on this page: pr1318 errors in the console after removing all the console logs
> 
> Task list for approval:
> 
> * fix things noted above
> * fix all css naming conventions that were modified in non BEM format
> * remove console.logs
> * fix console errors
> 
> There were several issues in this pull request. Once these issues are corrected, I'll take a deeper dive back into it. This process took a considerable amount of time, and it's possible that I missed a few things.

@KurtisIvey For the inconsistent CSS naming conventions, although there exists 3 different naming conventions, I've merely selected the classes that were originally in HTML files in the project. I've never named the CSS classes in different conventions. 

For the ids and green dots, I've inspected and aligned them again and pushed my latest changes on 10/6. I've also deleted the CSS you mentioned that didn't serve any purposes from my task. I've removed the extra console logs. 

Lastly, I don't think the console warnings were due to my code changes because I doubled checked the files changed for my commits and I didn't find causes that led to the warnings.

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
If you're able to, I'd correct the naming conventions just for prevention of issues in the future and since it's best practice. Even if it wasn't you since you're working in the file. 

pr1318 dots still not aligned vertically and tasks element error
Green dots are still not vertically aligned. Refer to my previous solution.

If we ignore the other console errors, the one most easily fixable that is actually within the files you're working in would be the <tasks> related one. If you can swap out the <tasks> elements since they don't technically exist with a div in ProjectMemberTable.jsx & WbsTable.jsx, that should remedy that issue. At least it did so on my local environment when checking it out. 


Good job on the breakpoint adjustment.

**Review by yi-lin-1234 — COMMENTED** [review]
Hello, I tested your PR and works as intended. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/39d6cbed-5844-4e67-9bac-e4515606740b

**Comment by ypan710** [comment]
> If you're able to, I'd correct the naming conventions just for prevention of issues in the future and since it's best practice. Even if it wasn't you since you're working in the file.
> 
> pr1318 dots still not aligned vertically and tasks element error Green dots are still not vertically aligned. Refer to my previous solution.
> 
> If we ignore the other console errors, the one most easily fixable that is actually within the files you're working in would be the related one. If you can swap out the elements since they don't technically exist with a div in ProjectMemberTable.jsx & WbsTable.jsx, that should remedy that issue. At least it did so on my local environment when checking it out.
> 
> Good job on the breakpoint adjustment.

@KurtisIvey I've made the changes you requested, could you please re-review? Thanks.

**Review by X1aoZhang99 — COMMENTED** [review]
Hi Yongjian, 

The green dots are now vertically aligned; it is still aligned when the window gets smaller. The copy feature also works as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/84805b6f-999d-47ae-970a-39ae9f660ac1


But there are still some errors that show up in the console. 
Screenshot 2024-01-16 at 21 35 50

**Review by 666saofeng — APPROVED** [review]
It worked as intended.
image
image
image

**Comment by KurtisIvey** [comment]
Hey Yongjan, sorry for the delay. app seems to be crashing most likely due to backend incompatibilities. If you could clear up the merge conflicts, I'll get this reviewed again asap.

**Comment by one-community** [comment]
Yongjian has said he can't figure out how to solve these merge conflicts. Can someone else take this over to complete it?

**Comment by kylepham** [comment]
Close this PR. Please refer to https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2163.

**Pull request closed without merging**
