### PR TITLE
Gowtham fix team location search error

### PR DESCRIPTION
**Pull request by curiousfancier**
# Description
when you log in as an Owner Account and in the team location page’s search box when we input in the search for any accounts it shows a white screen the error is fixed and we can see the results.

## Related PRS (if any):
This frontend PR is not related to any backend PR

## Main changes explained:
- Fixed Team Location Search error

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log in as owner user
5. go to reports→ Team Location→ Search
6. verify if you can search for a team member's Location

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/27274513/e34eac86-8b2d-46a1-9a8e-fb8c31ba6ea6

### CODE REVIEW

**Review by peter6866 — DISMISSED** [review]
Changes work as expected.
image

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested your PR and it works as intended. Please refer the screenshot attached.

PR 2276

**Review by hbodgal — DISMISSED** [review]
image

its working fine. I was able to search user's location.

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi, 

image

There seems be an error here, I got 3 search results, but 4 locations on the map. Please check this.

**Review by MinSun0814 — DISMISSED** [review]
The crash no longer happens. Nice work!
image

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works perfectly. Great Job! Below is a video for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/160a5743-0016-49aa-9ce0-665b42a52504

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected. Good work.
Screenshot 2024-05-25 at 8 03 35 PM
Screenshot 2024-05-25 at 8 04 12 PM

**Review by Sandhya1236 — DISMISSED** [review]
I have tested the changes successfully by checking out the current branch, running npm install, and npm run start:local to set up the PR locally. After clearing site data and cache, I logged in as an owner user and navigated to Reports -> Team Location -> Search. I verified that I could search for a team member's location successfully. All functionalities worked as expected, and the feature appears stable. The PR is ready for merging.

image

**Review by suaniii — APPROVED** [review]
I have tested the PR, and the changes work as expected. Logged in as an owner user, and verified that I could successfully search for a team member's location. All functionalities worked well, and the feature appears stable. Good work.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/016e763b-9c97-43dc-9016-5ca730071bc7

**Review by Jingyii800 — APPROVED** [review]
It works well. As an owner account, I am able to see the specific user location from reports->team locations by typing in search bar.
Please see my video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/5e1e80dd-da27-4b10-b1c0-78bfcfd943c3

**Review by vishavk1992 — APPROVED** [review]
I am able to search for the location of  person, and it works great.

PR-2276

**Review by DiyaWadhwani — APPROVED** [review]
Hi Gowtham,
Logged in as owner and I can see the location of a user as shown in the screenshot below.
Great work. Thank you

Screenshot 2024-06-28 at 1 34 08 AM

**Review by Parth-tech — APPROVED** [review]
Hey Gowtham,
The functionality highlighted is working correctly. 
Great Job.

Screenshot 2024-07-03 at 12 42 42 AM

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/288a4327-ba1c-4191-9fdd-d5799b747414

 and I am able to find team member location. Attached below is the video.

**Review by Rishitha1309 — APPROVED** [review]
PR working as expected.!

**Review by vijay10pk — APPROVED** [review]
Able to search the location of the team.
Suggestion: If possible try to make the edit and remove button centered so that it will look centered irrespective of the row height.
Screenshot 2024-07-12 at 11 05 40 PM

**Review by AnujVakil — APPROVED** [review]
I have tested this PR and working as expected.
PR #2276_1

**Review by Shadhrush5 — APPROVED** [review]
Hi, I reviewd PR #2276 by following the steps below.
running npm install
npm run start:local to set up the PR locally. 
Cleared site data and cache
Logged in as an owner user
Navigated to Reports -> Team Location -> Search.
I verified that I could search for a team member's location successfully. All functionalities worked as expected, and the feature appears stable except for slight delay. I am approving this. Thank you for your efforts, great work.

https://github.com/user-attachments/assets/9b4de561-10d3-4744-874a-ea904833cb2a

**Comment by nikethaanand** [comment]
The change are working as expected, able to search and view users locations on typing name in the search bar.

Uploading Screen Recording 2024-07-17 at 4.24.17 PM.mov…

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested the changes successfully.  
I logged in as an owner user and navigated to Reports -> Team Location -> Search. I verified that I could search for a team member's location successfully. 

I have searched for AI User. They are showing as expected in the map. 
location

**Review by ishan-miglani — APPROVED** [review]
I have tested the changes in this PR and the functionality works well. I verified that I could search for a team member's location successfully. Good work!

https://github.com/user-attachments/assets/3db1d22c-7ffd-4067-9ae6-6d2cd7fb57f1

**Review by angelalalacheng — APPROVED** [review]
Hi, 
I use your branch `Gowtham-Fix-TeamLocation-Search-Error` to test and it all shows the correct result.

Screenshot 2024-07-21 at 5 38 33 PM
Screenshot 2024-07-21 at 5 41 15 PM

**Comment by souravwalke** [comment]
Hi, I tested your PR and it works as intended. Please refer to the screenshot attached.

PR#2276

**Review by ReinaT5678 — APPROVED** [review]
I tested the map functionality and everything shows up as written! I attached a video below of the testing:

https://github.com/user-attachments/assets/79e88c22-37d1-4ab7-bdce-6cae8102557b

**Comment by arunsrao9** [comment]
I tested the PR and everything seems to be working great!
Screenshot 2024-08-04 at 12 09 33 PM
Screenshot 2024-08-04 at 12 08 51 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
