### PR TITLE
Papia create suggestion icon

### PR DESCRIPTION
**Pull request by papiasharmin**
# Description
(PRIORITY HIGH) Jae: Add “Suggestions” Icon to Dashboard icons section
It should function just like the Report App Bug icon (see below) but have the option to be submitted anonymously. 
Should have a dropdown that includes these options:
Suggestion Category: 
To identify and remedy poor client and/or user service experiences
To identify bright spots and enhance positive service experiences
To make fundamental changes to our programs and/or operations
To inform the development of new programs/projects
To identify where we are less inclusive or equitable across demographic groups
To strengthen relationships with the people we serve
To understand people's needs and how we can help them achieve their goals
Other
Would you like a followup/reply regarding this feedback? 
Should include an edit button for an Owner to add to the above “Suggestion Category:” dropdown
Should include an edit button for an Owner to add an additional information collection field if needed

## Related PRS (if any):
This frontend PR is related to the #440 backend PR.

## Main changes explained:
Added a form to take user suggestion, with one suggestion dropdown and radio field for feedback confirmation. For owner class added two edit buttons to add new suggestion category to the dropdown option, and adding extra text field. 

## How to test:
1. please follow backend PR 440 first to test this PR
2. check into current branch frontend and backend
3. do `npm run start:local` to run this PR locally
4. log as owner
5. go to dashboard→ click suggestion icon, as a owner try adding new suggestion category and new field, refresh the page to check if changes stays. 
6. fill up the required fields and submit, if you have configured the backend for sending email to your gmail address correctly, you will receive a suggestion email.

## Screenshots or videos of changes:
#Adding field and submitting form:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/73595da8-f551-4a79-a849-c531456c66fd

#Received suggestion email:
suggestionemail

### CODE REVIEW

**Comment by beblicarl** [comment]
I can confirm that this functionality works as intended and the code is cool

issue #998

[screencast-hgnapplication_react_beta.surge.sh-2023.07.12-14_36_01.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/3e8a2dbb-3ea5-4b1b-88a1-12ae681534df)

**Review by beblicarl — DISMISSED** [review]

**Review by freecode23 — COMMENTED** [review]
Hi I am getting: "404 not found error" when I click the suggestion button . Can you help me fill in what Im missing here. 
I attach picture of the error.
My steps:
1. backend on development branch
2. front end on papia_create_suggestion_icon branch.
3. backend: npm run build --> npm start
4. frontend: npm i --> npm run start:local
5. logged in as owner. Click on suggestion button
Screenshot 2023-07-12 at 12 42 33 PM


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/11370d70-9f3a-4997-bc0a-11194b96bff4

**Comment by papiasharmin** [comment]
> Hi I am getting: "404 not found error" when I click the suggestion button . Can you help me fill in what Im missing here. I attach picture of the error. My steps:
> 
> 1. backend on development branch
> 2. front end on papia_create_suggestion_icon branch.
> 3. backend: npm run build --> npm start
> 4. frontend: npm i --> npm run start:local
> 5. logged in as owner. Click on suggestion button
> 
> Screenshot 2023-07-12 at 12 42 33 PM
>  Screen.Recording.2023-07-12.at.12.53.08.PM.mov

Hello, @freecode23 , you also have to checkout to  papia creates suggestions icon branch on backend.

**Review by siddharthmohite — COMMENTED** [review]
I checked out into the branch both on frontend and backend, did npm install  and then npm run start: local. As soon as I click on the suggestion icons, the page becomes unresponsive. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37925823/c001e92a-c28d-4321-aa2a-8e0ed360c1a3
Screenshot 2023-07-12 at 7 32 08 PM
Screenshot 2023-07-12 at 7 46 14 PM

**Review by luisarevalo21 — APPROVED** [review]
Hello @papiasharmin,

I reviewed your PR and works as intended great job! 
one suggestion I have is after the user submits a suggestion maybe provide a notification saying it was successfully sent. 
While testing other PR I noticed some pop ups appear within the app, when I perform certain functions. Adding a pop up will help the user know their suggestion was sent. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/b83fb734-334a-4d98-a077-18e3c73d400b

**Comment by papiasharmin** [comment]
> I checked out into the branch both on frontend and backend, did npm install and then npm run start: local. As soon as I click on the suggestion icons, the page becomes unresponsive.
> 
> https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37925823/c001e92a-c28d-4321-aa2a-8e0ed360c1a3 Screenshot 2023-07-12 at 7 32 08 PM Screenshot 2023-07-12 at 7 46 14 PM

Hello, @siddharthmohite , please follow PR #440 backend to test this PR. My bad should have make this obvious.

**Comment by papiasharmin** [comment]
> Hello @papiasharmin,
> 
> I reviewed your PR and works as intended great job! one suggestion I have is after the user submits a suggestion maybe provide a notification saying it was successfully sent. While testing other PR I noticed some pop ups appear within the app, when I perform certain functions. Adding a pop up will help the user know their suggestion was sent.
> 
>  Screen.Recording.2023-07-12.at.8.12.47.PM.mov

Hello @luisarevalo21. Good suggestions, Thank you I will add that.

**Comment by AuroraLovesWhales** [comment]
Hi @papiasharmin. I have tested your PR and have found an issue. When I add a new category, there is no way to delete it. Is it an intended functionality? Please refer the video below for reference:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/c54a6c78-882c-41db-bfe3-8488c7c35083

**Review by freecode23 — DISMISSED** [review]
Everything works perfect.
All the features works using owner, admin, and user role 
- in all cases, the email I hardcoded in backend received emails successfully
- cancel button works correctly in all roles
- admin and user can see the new field created by owner

Sample email received is below.
Just a minor suggestion to make the email more readable: maybe have the title "Suggestion:", "Suggestion Category:", and the fields like "Field M" in bold or underline them

Screenshot 2023-07-13 at 7 23 51 PM

**Review by ramyaram2092 — COMMENTED** [review]
Hello @papiasharmin 
When I click on the suggestion Icon the application freezes and I am seeing the following error on the console and the application freezes
PR-998
 
I see that PR #440  has been merged with the development branch. I have the latest development branch running for the backend . Could you help me understand if I am missing any step here ? 

**Steps to Reproduce :** 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/7a6f8306-b26c-41c1-a6be-c302a2c50a66

**Front end branch :** 
image

**Back end branch** : 
image

**Comment by papiasharmin** [comment]
> Hello @papiasharmin When I click on the suggestion Icon the application freezes and I am seeing the following error on the console PR-998
> 
> I see that PR #440 has been merged with the development branch. I have the latest development branch running for the backend . Could you help me understand if I am missing any step here ?
> 
> **Steps to Reproduce :**
> 
>  PR-998.mp4 
> **Front end branch :** image
> 
> **Back end branch** : image

Hello, @ramyaram2092 , the api route is not created in development branch it is in papia_create_suggestion_icon branch, that is way you are getting 404 status, some people are seeing this branch, and some having same problem as you, I will try to fix it, and let you know. thank you for your review.

**Review by xaanders — DISMISSED** [review]
Hi Papia! You did a great job! 
Everything's working as inteded! 
[998.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/ce44cdd5-b426-4366-b90c-8429d471e959)

And I got an email as well:

**Review by NidaZaki — DISMISSED** [review]

**Review by cvtqx — DISMISSED** [review]
The front end works well and the form looks great! I was able to add a new suggestion and a new field as well:

Added suggestion

But can you capitalize this 'cancel'?

Capitalize

**Review by ramyaram2092 — DISMISSED** [review]
Hello @papiasharmin .. I think the the link to the back end PR in the description points to a different PR which is already merged in the development branch . Got confused  because of that. My bad. Kindly update the hyperlink in the PR description.  

I retested the end to end flow . Everything works as expected functionality wise .  Nice work 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/436983cf-740b-42d0-bb19-66aa617c5ca8

**Suggestion** : 
My only suggestion is improvements in the look and feel of the UI. However since the PR is for a working functionality for the user  suggestion we could ignore that for now  and address it in a different PR

Approving the PR on the same note from my end

**Review by BaileyM96 — COMMENTED** [review]
Hello @papiasharmin I tested this branch and I am sure you are now aware/testing that when clicking on the suggestion icon, the application freezes and the developer log has a list of errors.

**Review by shiva2096 — DISMISSED** [review]
Hi @papiasharmin 

Changes are working as descriped in the requirements.
The correct backend PR to checkout is [ HGNRest - 440](https://github.com/OneCommunityGlobal/HGNRest/pull/440)


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/71603cd9-2495-4012-b617-53dac979f012

**Comment by igorrochadasilva** [comment]
Hi @papiasharmin !
The front end works well and the form looks great! 
Great work : )

New category
998_01_add-category
Add new field
998_02_add-new-field
Submit suggestion
998_03_submit-suggestion
Refresh page and see if exists the field added
998_04_reflesh-page

**Review by joyceiphone — APPROVED** [review]
Good work! Tested the front end and backend part simultaneously. Everything worked as expected.

**Comment by beblicarl** [comment]
This functionality works as intended. The only issue I got is I didn't receive the email sent. However, this could be just me so let's take this with a pinch of salt

1. I clicked on the edit category
2. Added a category
3. I was able to delete the category as well

4. I clicked on the edit field
5. Added a field name
6. I was able to delete the field name

[screencast-localhost_3000-2023.07.18-16_20_56.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/9c2b7c04-99c5-45fa-ae5d-ca095e4ced1f)

**Comment by beblicarl** [comment]
> > This functionality works as intended. The only issue I got is I didn't receive the email sent. However, this could be just me so let's take this with a pinch of salt. Also, there are errors in the browser console
> > 
> > 1. I clicked on the edit category
> > 2. Added a category
> > 3. I was able to delete the category as well
> > 4. I clicked on the edit field
> > 5. Added a field name
> > 6. I was able to delete the field name
> > 
> > screencast-localhost_3000-2023.07.18-16_20_56.webm
> > ### Error
> > issue #998-errors
> 
> May be because, I also changed the back end. My bad. Forgot to tell that.

I did as you said and it works perfectly now 

issue #998-email

**Review by cvtqx — COMMENTED** [review]
Tested this on BE and FE and everything works as described! Well done!

WATCH OUT FOR TYPOS:

Typo

REVIEW:

New category can be added:

New category added

A category can be deleted:
New category deleting

Remaining categories after a category has been deleted are arranged with numbers in chronological order:

After one category was deleted

New fields can be added:

New fields added

Fields can be removed:

A field deleted

View after a field has been deleted:

One field was deleted

**Review by xaanders — DISMISSED** [review]
Hi Papia. I have re-tested your PR due to changes. Main functionality works good but some changes required. 
I could create new categories and they remain after refreshes: 
categories
And I could remove them by writing their list-number: 
removing-cat
Adding fields works: 
adding-fields
Removing: 
removing-field1
removing-fields

However I could send suggestions without any information typed or category chosen:
( I don't render the page dashboard for faster performance )
[scrnli_7_19_2023_12-33-40 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/9b53765a-0b22-4644-8fb4-008909c893f0)

Got the email like this: 
em

**Review by ramyaram2092 — COMMENTED** [review]
Hello @papiasharmin  retested the PR  for the updated changes
**Observations** :
1. End to End functionality works as expected 👍 
2. Only the owner account has the ability to add/ delete fields and suggestion category 
3. I see a warning message when i click on the Suggestion icon via all class logins

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/4e05f6a8-05ef-4af4-8815-612a2886f192


**Suggestions**  : 
For delete functionality I think a dropdown would be more suitable over a text box for the following two reasons  : 
1. There is always a possibility of user typing in the wrong field name 
2.  In the following video you can see there are no fields to delete yet the application prompts the user to type the field name to delete 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/caa53335-21f7-43a8-8ee7-3e4736420b0f

**Comment by mounica-dingari-by** [comment]
Hi @papiasharmin , the application freezes after clicking the suggestion icon. In the frontend, I can't see the field staying intact after refresh. 
Screenshot from 2023-07-19 16-04-07

**Comment by papiasharmin** [comment]
> Hello @papiasharmin retested the PR for the updated changes **Observations** :
> 
> 1. End to End functionality works as expected 👍
> 2. Only the owner account has the ability to add/ delete fields and suggestion category
> 3. I see a warning message when i click on the Suggestion icon via all class logins
> 
>  RETEST-PR-998-Warning-Message.mp4 
> **Suggestions** : For delete functionality I think a dropdown would be more suitable over a text box for the following two reasons :
> 
> 1. There is always a possibility of user typing in the wrong field name
> 2. In the following video you can see there are no fields to delete yet the application prompts the user to type the field name to delete
> 
>  RETEST-PR-998-Delete-Functionality.mp4

Hello @ramyaram2092, thank you for the review and suggestions. I have added the delete option like this, to keep the function in one place, instead of writing different function. user can copy the field name to delete it, I will add that as instruction. and I will also fix the problem pointed in suggestion 2.

**Review by xaanders — COMMENTED** [review]
Hi @papiasharmin! 
It works as intended. There is no warning and I can't send an email fully empty. 
photo_2023-07-22_10-57-04
But I suggest to add extra validation to the text area checking if there are words. Now I can type just one space and it can be sent with just empty string.

**Review by winghojackyli — APPROVED** [review]
Hi @papiasharmin , I tested the PR and it works great. 

### Adding Category and Field & Suggestion Submission


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/c06d366d-2fa0-4766-9ad8-12fdd421d8dc

### Email Sent

email

**Review by beblicarl — APPROVED** [review]

**Comment by veronicacheng2** [comment]
Hi @papiasharmin, I tried clicking the suggestion icon but there was nothing popped up. Please advise if I have missed anything. Thank you!

image

**Pull request merged**
