### PR TITLE
Ramakrishna edit all team code at Once

### PR DESCRIPTION
**Pull request by Ramaruva**
# Description
image

## Related PRS (if any):
This frontend PR is related to the [#1034](https://github.com/OneCommunityGlobal/HGNRest/pull/1034) backend PR.

…

## Main changes explained:
- Implemented new method to replace all teamcode at once in weeeklysummaryreport.jsx
- Added neccessary buttons to replace all teamcode in weeklysummaryreport.jsx
- Modified the single teamcode change api inorder to tackle 500 api call issue
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner  user or whoever has permission to edit the teamcode
5. go to dashboard→ Reports-> Weeklysummaryreports
6.  Try to select any teamcode from dropdown menu 
7. After that you will prompted to see an input box and replace button now try to enter any new teamcode(here teamcode must be length between 5 to 7 and can have any char,numbers and spl chars).
8. Now ensure that after entering the replace button the new teamcode is replaced with old one in selectbox and also following user profile
9. after this try change any teamcode indiviually for any users also to ensure that we are not getting any issues here.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/69ac9ba4-dae0-4322-be83-cb13b56b83df

### CODE REVIEW

**Review by SrikanthChowdary495 — COMMENTED** [review]
I am unable to add the input in replace button. Please find video for Reference.

https://github.com/user-attachments/assets/4385e869-b753-4fb2-8f88-33eb0e96caba

**Comment by Ramaruva** [comment]
> I am unable to add the input in replace button. Please find video for Reference.
> 
>  weeklysummaries.mp4

Hi,

Thank you for taking the time to test this PR. I attempted to replicate your steps and was unable to reproduce the issues you encountered. However, please note that the team code must be between 5-7 characters in length. If this requirement is not met, it will trigger the error message mentioned in the PR.

I have attached the latest video demonstrating the expected functionality. If you continue to face the same issue, please let me know if you are seeing any console log errors and mention them here, along with any network issues.

https://github.com/user-attachments/assets/f547f003-e3b6-4b43-a480-cb6d9567573a

**Review by kdaga81 — DISMISSED** [review]
image
image
I have tested the team code replacement functionality and confirmed it works as expected. After entering a new team code (5 to 7 characters, including any chars, numbers, and special chars) and clicking the replace button, the new code successfully replaced the old one in the select box and user profile. Additionally, I verified that changing the team code individually for various users did not cause any issues. Everything is functioning correctly.

**Comment by angelalalacheng** [comment]
Hi, 
I use `Ramakrishna_EditAll_TeamCode ` for the frontend and `Ramakrishna_Editall_TeamCode_Backend` for backend and it seems like even I input 5 - 7 characters it shows me "NOT SAVED".

https://www.loom.com/share/4fd2f05a1ab44f67a63fde873bc5583e?sid=30a27448-8279-4a70-8d87-32bfa110777e

**Comment by souravwalke** [comment]
Tested the changes of the PR and all the features work as expected.
Screenshot 2024-07-20 at 1 08 05 PM
Screenshot 2024-07-20 at 1 08 20 PM
Screenshot 2024-07-20 at 1 07 14 PM

**Review by Chetan0606 — DISMISSED** [review]
I have followed as per the provided guidelines and it's working as per the expectations.
Screenshot (317)
Screenshot (316)
Screenshot (315)

**Review by jinxyou — APPROVED** [review]
I tested changing teamcode to any 5-7 characters and it seems to work fine. I also tried to select multiple team and replace. It also works fine. Great work!
Screenshot 2024-07-20 185410
Screenshot 2024-07-20 185454
Screenshot 2024-07-20 185525

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and its working as expected. Logged in as admin and navigated to weekly summaries reports page and selected a random team code and replaced with a new one. Below video has the details.

https://github.com/user-attachments/assets/7fd5252b-9224-47ce-905d-8fcd28d246ae

**Review by pavanswaroopl — APPROVED** [review]
Great work,

Tested and everything works fine.


https://github.com/user-attachments/assets/a64f7881-65ea-48be-ac78-ebb6ee943034

**Comment by cecilia-uu** [comment]
截屏2024-07-21 下午2 51 38
Tests work as expected.

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as described and I was able to replace the team code.

https://github.com/user-attachments/assets/f14d3c7f-dac4-430b-9862-ada1fc8ea73f

**Review by gowthamdongari — APPROVED** [review]
Works as expected keep up the good work!
350742381-3c8c7d6f-3bf1-43d5-b3ce-8b1b40d60d3f

**Review by kabraambika — CHANGES_REQUESTED** [review]
In dark mode, Selected team code name is not visible.

Text is not visible in dark mode as shown below:
image

Text is visible in light mode as shown below:
image

**Review by Shadhrush5 — APPROVED** [review]
Hi, I have reviewed PR #2469 along with the backend PR #1034. I followed the steps as mentioned in the PR and everything works fine. I notice a slight lag the first time, but I didn't see it again later. I also tested the cases where the length does not confer with the requirements. I have attached a Video below. Thank you for the great work.


https://github.com/user-attachments/assets/100606e8-cd2d-456e-9338-add5fdcc0b49

**Review by ishan-miglani — CHANGES_REQUESTED** [review]
Hi, the replace team code functionality works well. I am able to replace the team code and it is reflected in user profile as well. 
The selected team code is not visible in dark mode. Please address this. Thanks!

https://github.com/user-attachments/assets/7ed1f034-41d0-46db-8dcc-4c0e814e23d2

**Review by SaiLavanya1 — DISMISSED** [review]
I have tested PR #2469. The functionality of editing all team codes works as expected. The input box and replace button are functioning correctly, and the updates are accurately reflected in the user profiles. The UI responsiveness is good, and the validation for team code length and characters is working properly. No issues were encountered during the testing.
Screenshot 2024-07-22 at 5 07 30 PM
Screenshot 2024-07-22 at 5 07 43 PM
Screenshot 2024-07-22 at 5 09 40 PM

**Comment by ReinaT5678** [comment]
I'm experiencing an issue with the replace functionality (see video attached). I noticed SrikanthChowdary495 also was experiencing the same error. I included some network errors that popped up in my console. 

https://github.com/user-attachments/assets/069410dc-547c-42f8-abf8-40c0ac10cb15

Screenshot 2024-07-23 at 9 14 04 PM

**Comment by SrikanthChowdary495** [comment]
> > I am unable to add the input in replace button. Please find video for Reference.
> > weeklysummaries.mp4
> 
> Hi,
> 
> Thank you for taking the time to test this PR. I attempted to replicate your steps and was unable to reproduce the issues you encountered. However, please note that the team code must be between 5-7 characters in length. If this requirement is not met, it will trigger the error message mentioned in the PR.
> 
> I have attached the latest video demonstrating the expected functionality. If you continue to face the same issue, please let me know if you are seeing any console log errors and mention them here, along with any network issues.
> 
>  teamcodeissuecheck.mp4

I was unable to replace even I have followed this steps. I am attaching a reference video. 

https://github.com/user-attachments/assets/f82c6002-e263-4d76-999b-367473dfea69

**Comment by Ramaruva** [comment]
Hi all,

Thank you for taking the time to test my PR.

Regarding the dark mode issue, I have addressed it and also added a proper error message to be displayed on the frontend. This should prevent the misunderstanding caused by the previous generic error message.

For those experiencing the 404 issue, I was unable to replicate it on my end. However, I did notice that if the API route is missing in the backend, it results in a 404 error. Therefore, if you are encountering a 404 error, please check if the API route is present in the backend code.

Thanks again for your help.
image
image

image

**Review by kabraambika — APPROVED** [review]
I have reviewed the changes for the frontend PR. Now feature is working in dark mode as well, refer screenshot below:

image
image

**Review by JatinAgrawal94 — APPROVED** [review]
Changs work as expected. Good work.

https://github.com/user-attachments/assets/c3aed53c-39b8-4eda-b3b5-d726d75aba32

**Review by ishan-miglani — APPROVED** [review]
I have verified the changes. The functionality works well and is now visible in dark mode as well. Great work!

https://github.com/user-attachments/assets/53987e2d-4c30-48a7-bb70-7f8e90feaa39

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/a4d98953-3d58-49f3-ac08-5ac4ac9e3136

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
