### PR TITLE
Meet BadgeReport unit tests

### PR DESCRIPTION
**Pull request by meetpadhiar4**
# Description
Unit test for src/components/Badge/BadgeReport.jsx 

## Main changes explained:
- Added 6 test cases for the component
 1. renders component without any errors
 2. renders all the core static fields properly
 3. renders all mobile view specific fields properly
 4. renders correct message if no badges are present
 5. renders all the badge information correctly
 6. test for multiple badges

## How to test:
1. check into current branch
2. do `npm test BadgeReport.test.js`
3. check if all test cases pass without any errors

## Screenshots or videos of changes:
test cases passed

### CODE REVIEW

**Review by KyreneAF — APPROVED** [review]
- All the tests pass 
- All the tests fail when return is commented out besides the first test which should always pass.
Screenshot 2024-05-23 at 3 50 58 PM
Screenshot 2024-05-23 at 3 17 05 PM

**Review by hbodgal — APPROVED** [review]
image

All test passed!

**Review by curiousfancier — APPROVED** [review]
All test cases are working succesfully
image

**Review by peter6866 — APPROVED** [review]
All test cases passed.
image

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected! Nice work!

**Review by Ramaruva — APPROVED** [review]
Hi, I have run the test cases and all are working well 
image

**Review by MinSun0814 — APPROVED** [review]
image

**Review by aaryaneil — APPROVED** [review]
All the test cases passed.
Good work!!
Screenshot 2024-05-24 at 10 35 34 PM

**Comment by KaushikMreddy** [comment]
Hi, 

All your test cases have passed
image

**Review by dikshitakejriwal — APPROVED** [review]
All the test cases passed as shown in the screenshot. The tests are through and well implemented. Great Work!

Screenshot 2024-05-28 at 5 45 37 PM

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
