### PR TITLE
Shrada Fix missing form validation in user profile page

### PR DESCRIPTION
**Pull request by shradac**
# Description
Screenshot 2024-07-26 at 1 24 30 AM

## Related PRS (if any):
This frontend PR is related to development backend PR.
…
## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. go to dashboard→ Profile
6. verify lastName field cannot have less than 2 characters.

## Screenshots or videos of changes:
Screenshot 2024-07-26 at 1 10 18 AM

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (152)

**Review by kdaga81 — APPROVED** [review]
image

Giving Error if Lastname length is less than size 2

**Comment by nikethaanand** [comment]
The change works as expected, while updating the last name. The save changes option is also disabled when the error shows up.
image
image

**Review by KurtisIvey — APPROVED** [review]
Nice and simple fix. Well done. Works exactly as intended

**Review by Gauravmg6 — APPROVED** [review]
An alert is displayed as expected for the last name being less than 2 characters.

Screenshot 2024-07-28 004403

**Review by Chetan0606 — APPROVED** [review]
Followed the instructions provided and verified accordingly. Everything looks good and here's my observation.

image

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested this PR. If lastname have less than 2 char it is throwing an error. 
everything working as expected. 
profileee

**Review by manikittu810 — APPROVED** [review]
Hello @shradac 
Length of the String (LastName) is working as mentioned above.
Screenshot 2024-08-01 at 4 09 46 PM

Thank you.

**Review by Pranay-ai — APPROVED** [review]
Hey @shradac 
I have tested the PR and its  as expected
image

Thank You

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and it's working as expected.
Screenshot 2024-08-03 213016

**Review by jinxyou — APPROVED** [review]
The function works as expected. Great work!
Screenshot 2024-08-03 230047

**Comment by Gmon-k** [comment]
I have tested from my side and it it throwing an warning, when the last name is a single letter. Below is screenshot for it

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the form validation works as expected.
Screenshot 2024-08-01 at 8 29 57 PM
Screenshot 2024-08-01 at 8 30 04 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
