### PR TITLE
show save reminder after the first save

### PR DESCRIPTION
**Pull request by juneluo**
### Description
Fix USER PROFILE COMPONENT bug 2 (PRIORITY MEDIUM)
When making changes on a user’s profile, the reminder to click the save button has stopped showing AFTER 1 SAVE. It works the first time I make an edit, but not after that/after the auto-refresh when I “save”. It should show for everything that requires that button, ever time. 
img

### Mainly changes explained:
Delete the changes made to the state `showSaveWarning` from the function `handleSubmit` and `toggleInfoModal`.
In the code before, the flag/state will be changed to false when the user clicks 'save' or more information icon once. Therefore, no save reminder will be shown even the state `Changed` is updated as true again (new changes made after first save). This `showSaveWarning` should only be set to False when we don't want to show the reminder no matter what value the Changed is. It can be used in the future design but it is not necessary in the current design.

### How to test:
check into current branch
do npm install and ... to run this PR locally
User profile → change any value of the profile → click save → second time change any value of the profile → click save

### CODE REVIEW

**Review by LeeSingChanYau — APPROVED** [review]
Good job! Changed many fields and saved multiples times in the user profile page and it showed the save reminder everytime.

**Comment by RafaelCastilhoCastro** [comment]
Hi @juneluo,
I tested the feature and it worked as intended.
I have a question though. When the user make any changes the save warning appears. But if the user undo the changes the save warning remains. Ideally shouldn't disappear? Since useEffect is already been used in the code I think it could be used to update the `showSaveWarning` in case the changes are undone if I'm not mistaken.
I'm not sure if this is supposed to be a feature. In case it isn't I'll leave it as a suggestion.
Thanks.

**Comment by AnishPandita** [comment]
Hello @juneluo I tested your bug and it seems to work perfectly and displays the save prompt even after multiple saves. However whenever I change the profile name the name gets rendered on the main page but the profile name on top right does not get updated. It updates when I refresh the page. 

https://user-images.githubusercontent.com/111321945/214972933-ff403633-1f4c-4cc6-8673-6c5c2c9e7021.mov

**Comment by one-community** [comment]
Good catch on a new bug Anish. The name updates if we refresh. Logging this on the Bugs doc as a new bug.

**Comment by Gukal7** [comment]
Hi @juneluo, I tested the code and the save button/reminder works fine and the changes could also been seen on the dashboard. But there is one issue, I couldn't see my name on top right alongside Welcome. I am testing on the new user that I made myself. My name doesn't even show when I log in for the first time and don't make any changes.

Screenshot 2023-01-28 at 11 58 16 AM
Screenshot 2023-01-28 at 11 58 33 AM

**Comment by one-community** [comment]
Good catch. What you describe is a different bug though Gurkanwal. Cali has her name by it on the Bugs Doc.

**Comment by Filipe-Oliv** [comment]
Hi @juneluo.  I changed several fields and saved several times on the user's profile page and it showed the save reminder each time.

[week 03 - 02-07-23 (8).webm](https://user-images.githubusercontent.com/114119668/217380596-035dad43-49fe-491a-9346-e7c1facc5366.webm)

**Comment by RafaelCastilhoCastro** [comment]
Hi @juneluo,
This PR is tested and approved. Can you please check the conflicts so it can be moved?
Thanks.

**Review by tingedudu8 — APPROVED** [review]
Hi @juneluo, I tested this PR and it works perfectly. The reminder to save appears each time I make an adjustment. But I saw a redundant "/" in the edit link box.
PR652

**Comment by one-community** [comment]
Get rid of that redundant / and I'll move this to the Management team for final review

**Comment by one-community** [comment]
Thank you, moving to final review

**Review by Filipe-Oliv — APPROVED** [review]
Works as intended. I'm going to approve it.

**Comment by one-community** [comment]
Moving to final review

**Comment by KaixiangGU** [comment]
Works well, thank you! @juneluo

**Pull request merged**
