### PR TITLE
Shiwani old badges unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for old badges component

## Main changes explained:
- Added 3 test cases:   renders without crashing, check tool tip of Badges Earned Before Last Week, check Badges Earned Before Last Week heading

## How to test:
1. check into current branch
2. do `npm test src/components/Badge/__tests__/OldBadges.test.js` 
3. check if all the test cases pass without any warnings or errors

## Screenshots or videos of changes:
Screenshot 2024-01-29 at 3 26 27 PM

### CODE REVIEW

**Review by ShengjieMao — DISMISSED** [review]
Followed the instructions. All tests passed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/21b55f84-4cf2-4e99-9edc-e03fd75a8f5e

**Review by iTvX — DISMISSED** [review]
As I checked, everything works perfectly.

CleanShot 2024-01-25 at 12 49 02@2x

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work! 

Screenshot 2024-01-25 at 6 38 34 PM

**Comment by Cavein254** [comment]
@Shiwani99 ran the tests as suggested in this pr and all the tests passed.
Screenshot 2024-01-26 165212

**Comment by beblicarl** [comment]
all tests passed successfully

image

**Review by beblicarl — DISMISSED** [review]

**Comment by Lin1404** [comment]
All test cases passed successfully. Great work!
image

**Review by Lin1404 — DISMISSED** [review]

**Review by peterson337 — DISMISSED** [review]
All tests passed.

a

one comunnity

**Review by 666saofeng — APPROVED** [review]
All tests passed.
image

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 22 -PR2

**Review by navneeeth — CHANGES_REQUESTED** [review]
Hey there, @Shiwani99! Good implementation of the tests! They are all passing:

test cases result

---
tool tip

 I inspected the Badges component as shown above where the OldBadges component renders within it and I believe you've covered the correct tests to: 
1) Check the text in the tool tip of Badges Earned Before Last Week (on and before hover)
2) Check the heading text of Badges Earned Before Last Week
 
 However, I believe that the check you've added to see if the image src is correct is redundant as it is already being covered in the `BadgeImage.test.js` test file (as shown below) in the same parent directory of tests and thus can be removed: 
image source is being checked in BadgeImage test js

I will approve the PR once you remove the redundant test titled `check if image src is correct`. Thank you!

**Review by X1aoZhang99 — CHANGES_REQUESTED** [review]
Hi Shiwani,

Apart from the issue @navneeeth said above, everything looks good and all tests passed. 

Screenshot 2024-01-28 at 18 51 20

**Review by Renanluizssx — DISMISSED** [review]
Hi @Shiwani99, i tested your unit tests and it's running every ok
PR#1875

**Comment by Shiwani99** [comment]
> Hey there, @Shiwani99! Good implementation of the tests! They are all passing:
> 
> test cases result
> 
> tool tip
> 
> I inspected the Badges component as shown above where the OldBadges component renders within it and I believe you've covered the correct tests to:
> 
> 1. Check the text in the tool tip of Badges Earned Before Last Week (on and before hover)
> 2. Check the heading text of Badges Earned Before Last Week
> 
> However, I believe that the check you've added to see if the image src is correct is redundant as it is already being covered in the `BadgeImage.test.js` test file (as shown below) in the same parent directory of tests and thus can be removed: image source is being checked in BadgeImage test js
> 
> I will approve the PR once you remove the redundant test titled `check if image src is correct`. Thank you!

Hi, Thank you for your review. I have removed the test case as requested by you.

**Comment by Shiwani99** [comment]
> Hi Shiwani,
> 
> Apart from the issue @navneeeth said above, everything looks good and all tests passed.
> 
> Screenshot 2024-01-28 at 18 51 20

Hi,
Thank you for your review. I have removed the test case as requested.

**Pull request merged**
