### PR TITLE
Ilya fix blue square hover box on phones

### PR DESCRIPTION
**Pull request by ilyaflaks**
blue-sq-hover-tooltip

# Description
The hover box (aka Tooltip) appears when the blue square is hovered over and displays the date the blue square was assigned and the reasoning behind it. On screens sized 1420px wide and larger it occupies the white space to the left of the blue square. On smaller screens it gets cut off.   

Fixes # 21 (UserProfile component)

## Related PRS (if any):
This frontend PR is related to the [#1751 ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1751)frontend PR.
To test this PR checkout the current branch on the front end and the "development" branch on the backend
…

## Main changes explained:
- Added a media query in BlueSquares.css to match screens narrower than 1420px
- Added min-height to the "summary" for edge cases when the summary is really short and appears too far removed from the square itself.  
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Other Links → User Management → search → select any user with at least one blue square assigned
6. Open the Developer Tools on your browser (cmd + option + i on Mac) and expand the side panel so that the main page is narrower than 1420px. Alternatively you can exit the full screen mode on your browser and drag one of the vertical borders to make the window narrower. 
7. Note that using the "device toolbar" feature of your dev tools will not help one test the PR because smart phones don't have cursors and do not need hover effects.
8. Verify that the hover box is covering the less crucial information above the blue squares. 
9. Reduce the browser window to about 350-450px to simulate a smart phone and test again

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/c49b4e0c-d979-42ac-9c53-890684e95aa2

## Note:
I'm open to any suggestions on how this UI could be improved.

### CODE REVIEW

**Review by pshereen — DISMISSED** [review]
I tested the PR.
It works as per the requirements.

Screenshot 2024-01-17 192756

**Comment by Vishala09** [comment]
Works as intended! Great work!
Before : 
image
After : 
image
image

**Review by Vishala09 — DISMISSED** [review]

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Ilya, 

I've just tested your PR. I logged in as the admin user, and all functionalities worked just as intended. Congrats! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/958bb161-fe6a-4c25-ab09-249cb53479c0

**Comment by Cavein254** [comment]
Hi @ilyaflaks,
Tested the pr and everything works as intended. 

- [x] Verify that the hover box is covering the less crucial information above the blue squares.
- [x] Reduce the browser window to about 350-450px to simulate a smart phone and test again


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/3d5af285-c07b-4fd5-903f-503ba7eb7055

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Works as intended, but I think some vertical alignment is in order as well since it's cut off there depending on the position of your scroll window. We also want to be sure that we're keeping in mind how people interact on phones and tablets since mouses likely won't be used on them. They will instead click with their finger rather than hover with a mouse cursor(we can omit tablets with trackpad accessories since we're not trying for perfection).

(not requesting changes for horizontal alignment, but there is room for improvement)
   If you did want to try another approach, you could have the popup positioned in the middle of the screen when its on screen sizes where a mouse would not be hovering anymore. This way it's position would be centered no matter what device you used and no longer be offset. 

For the vertical alignment, you could reference the position of the blue square itself to ensure it's not too far above it(what's currently happening). I'd play around with absolute positioning to accomplish this since there will be a lot of blue squares potentially.

Overall, I think you did a good job on improving it since it wasn't done that well in the first place CSS wise. 

task list:
   Fix vertical alignment, so it's not cutoff

**Review by peterson337 — DISMISSED** [review]
I tested it and it worked as advertised.

one comunnity

**Comment by ilyaflaks** [comment]
@KurtisIvey first of all, thank you for the constructive feedback and taking the time to come up with improvements for my PR. 

_>We also want to be sure that we're keeping in mind how people interact on phones and tablets since mouses likely won't be used on them. They will instead click with their finger rather than hover with a mouse cursor_

I think the only thing we can do for phones and other touch screen devices is to have the tooltip with details show up when the user presses and holds the blue square. I don't know if it's the best user experience in this case because we still want the user to be able to click on the square and open a modal. 

_>If you did want to try another approach, you could have the popup positioned in the middle of the screen when its on screen sizes where a mouse would not be hovering anymore. This way it's position would be centered no matter what device you used and no longer be offset._

Good idea, I added a media query for screens narrower than 768px to address this

_>For the vertical alignment, you could reference the position of the blue square itself to ensure it's not too far above it(what's currently happening). I'd play around with absolute positioning to accomplish this since there will be a lot of blue squares potentially._

I was only able to replicate the component cutting off bug on a screen with height under 842px. That's a pretty extreme case for non-mobile devices. I added another media query to just position the component as fixed closer to the top. It will cover some blue squares, but there's no other room to go. 

I have considered positioning the tooltip relative to the square itself from the start and decided against it. Firstly, i'd have to set "overflow" to "visible" for blueSquareContainer class, and that would make it overlap the button underneath it. Second, the tooltips for the squares on the right would overflow the screen and would be cut off. 
absolute

[There's a solution](https://stackoverflow.com/questions/50970336/prevent-css-tooltip-from-going-out-of-page-window) that would require quite a bit of JavaScript, at which point it would be more sensible to just install another package for React tooltips. I tried the one built into reactstrap and it's very buggy.

**Review by Renanluizssx — CHANGES_REQUESTED** [review]
Hi @ilyaflaks, i review your application and some devices don't appear the blue square message, look my review:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/56932048-63de-42a6-81a5-ee810d0e0842

**Comment by ilyaflaks** [comment]
> Hi @ilyaflaks, i review your application and some devices don't appear the blue square message, look my review:
> 
>  2024-01-31.12-48-50.mov

@Renanluizssx I believe that is a behavior of Chrome Dev Tools. Toggling the device toolbar not only adjusts the screen size but changes the cursor to a circle, which represents the user's finger. Mobile devices are not supposed to have hover events because most of them don't come with a mouse, and therefore don't have a cursor. As mentioned before, this PR is targeted more for computer browsers that are not in full screen mode. 

I'm surprised any of the devices you selected had the hover effect. My DevTools didn't have them in "Responsive" mode or any of the devices I had added.

**Review by Nahiyan-16 — APPROVED** [review]
## Looks great
Hi Ilya, I was reviewing your PR by first analyzing what was going on in the development version and I discovered that my profile page seems to go blank when I reduce the width to about 1025px or below. The only way it can return to normal is when I increase the width and refresh the page. I should also mention that I am using a Windows device and on Chrome. Here is a video demonstration of what is happening on the dev version below: 
[Dev-version.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/80b3a391-21e2-4011-adb6-10a16a06694d)

Using your PR, I was able to get exceptional results as the page would not go blank when I resized the page.  I also do not see any glaring UI changes that need to be made for the Blue Squares section. Here is a video of me resizing using your PR:
[PR-video.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/f5e4864d-abc7-4c5c-a231-8624f86429d1)

**Comment by ilyaflaks** [comment]
> ## Looks great
> Hi Ilya, I was reviewing your PR by first analyzing what was going on in the development version and I discovered that my profile page seems to go blank when I reduce the width to about 1025px or below. The only way it can return to normal is when I increase the width and refresh the page. I should also mention that I am using a Windows device and on Chrome. Here is a video demonstration of what is happening on the dev version below: [Dev-version.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/80b3a391-21e2-4011-adb6-10a16a06694d)
> 
> Using your PR, I was able to get exceptional results as the page would not go blank when I resized the page. I also do not see any glaring UI changes that need to be made for the Blue Squares section. Here is a video of me resizing using your PR: [PR-video.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/f5e4864d-abc7-4c5c-a231-8624f86429d1)

That's very interesting since my changes only deal with the blue square component! This branch is definitely not up to date, so I think some of the later merges to the "development" branch were detrimental to this page. I suggest you bring it up to Jae and submit a new bug to the **HGN Phase I bugs** list

**Review by peterson337 — APPROVED** [review]
I tested it and it worked as advertised.

one comunnity

**Review by Pandani07 — APPROVED** [review]
Hello, I tested this PR and the functionality works as intended, good job! The UI is responsive and smooth

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/355b9e0e-895f-4ee5-a641-1a1d4b689e3a

**Review by Renanluizssx — APPROVED** [review]

**Review by KurtisIvey — APPROVED** [review]
Everything works great! Vertical alignment is fixed and everything is functioning perfectly 😁 

I would definitely say this is ready for merge 👍

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
