### PR TITLE
Nahiyan_Dark mode on User Profile Modals

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Implemented dark mode on all user profile modals.

## Related PRS (if any):
This frontend PR is related to the dev backend.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ User Profile
6. verify that all modals are working properly in dark mode

## Screenshots or videos of changes:
Screenshot 2024-05-28 130533
Screenshot 2024-05-28 130548
Screenshot 2024-05-28 130601

### CODE REVIEW

**Review by Kavil-Jain-514 — DISMISSED** [review]
The dark mode changes are perfect.
image
image

image
image
image
image

**Review by KyreneAF — DISMISSED** [review]
- Modals seem to be working I believe there were only 4.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/322b2049-e525-4eed-bc00-663083334a71

**Review by Sandhya1236 — CHANGES_REQUESTED** [review]
Upon reviewing the PR, I observed that dark mode is not functioning correctly for various modals and popups, including those depicted in the provided screenshots. I followed the steps to check out the branch, install dependencies, run the application, and verify the modals in dark mode. During this process, I found that several modals are not displaying correctly, with missing or incorrect styling that significantly affects readability and user experience. Additionally, I encountered an issue where I could not add a new title. These issues need to be addressed to ensure a consistent and functional dark mode across all components of the application.

image

image

image

image

image

**Comment by Nahiyan-16** [comment]
@Sandhya1236 What type of account did you test with? Can you attempt to test this again as all the other reviewers are getting different results?

**Comment by Sandhya1236** [comment]
Upon reviewing the PR again, I tested the dark mode functionality and verified it from the owner account. I checked out the branch, installed dependencies, ran the application, and thoroughly tested the modals in dark mode. This time, I ensured to verify all components, and I am pleased to report that everything tested successfully. The previous issues with missing or incorrect styling and the inability to add a new title have been resolved. I apologize for any inconvenience caused by the earlier review.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/03eafc34-dbf1-4dbe-9f52-bf720f5dfaab

**Review by Sandhya1236 — DISMISSED** [review]
Upon reviewing the PR again, I tested the dark mode functionality and verified it from the owner account. I checked out the branch, installed dependencies, ran the application, and thoroughly tested the modals in dark mode. This time, I ensured to verify all components, and I am pleased to report that everything tested successfully. The previous issues with missing or incorrect styling and the inability to add a new title have been resolved. I apologize for any inconvenience caused by the earlier review.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/30011ac5-3029-4362-b55e-965cf6ad9cd7

**Review by KaushikMreddy — DISMISSED** [review]
Hi, 

I've tested your changes, after switching to night and day modes. All the desired changes are in order.
image
image


Good work.

**Comment by Vijeth-V** [comment]
I have tested the changes, and after switching between night and day modes, I can confirm that all the desired adjustments have been successfully implemented.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/7a0cc6f6-c5e7-4170-8210-f00c2a6d96a1

**Review by nathcarnevalli — DISMISSED** [review]
Hi Nahiyan, worked as expected to me :) 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/14a14f3d-98af-439c-954a-0a2aad9bf4e0

**Review by JatinAgrawal94 — DISMISSED** [review]
All Modals look great with the dark theme.
Suggestion: Shouldn't dropdown having "Team weekly summaries" too have a dark theme?
Rest else seems good.
PR#2295

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/30641244-9e72-4b77-b1d4-3a319243a051

**Review by jinxyou — DISMISSED** [review]
I have tested the pull request. And the function of dark mode seems working in a proper way. Most of the backgrounds are turning into blacks. No apparent problem have been seen.
Screenshot 2024-05-31 002811
Screenshot 2024-05-31 002834

**Comment by CloudyZ524** [comment]
Hi Nahiyan, 
After reviewing the dark mode, I noticed the style of buttons in the profile page are not unified. 
For example, this blue button for "Add a new title" has no shadow while other buttons have shadows. 
Screenshot 2024-05-31 at 16 02 36

Also, the buttons "Pause", "Set Final Day" and "Cancel" has no filling colors, which style looks slightly different from other buttons. 
Screenshot 2024-05-31 at 16 02 55

**Review by CloudyZ524 — APPROVED** [review]
Hi Nahiyan, 
After reviewing the dark mode, I noticed the style of buttons in the profile page are not unified. 
For example, this blue button for "Add a new title" has no shadow while other buttons have shadows. 
Screenshot 2024-05-31 at 16 02 36

Also, the buttons "Pause", "Set Final Day" and "Cancel" has no filling colors, which style looks slightly different from other buttons. 
Screenshot 2024-05-31 at 16 02 55

**Review by cecilia-uu — DISMISSED** [review]
It works as described. Great!
截屏2024-06-01 下午4 27 33

**Review by KurtisIvey — DISMISSED** [review]
Great job, all of the modals are functioning as intended with dark mode. Did notice that user links weren't visible due to a lack of contrast, but that's not related to anything you've touched. I'll just submit a bug report for that.

Fantastic job as always with all the dark mode modal integration!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/640e5a1b-3d6a-4012-8149-5b33f68f26de

**Review by cvtqx — DISMISSED** [review]
Hello,
all the modals look great in dark mode. Great job!

Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/7fcce2ff-80c1-4228-b755-75ea07bacba3

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected.
Screenshot 2024-06-02 at 1 01 47 AM
Screenshot 2024-06-02 at 1 01 51 AM
Screenshot 2024-06-02 at 1 02 26 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
