### PR TITLE
Yubo- unit test for Edit Link Modal

### PR DESCRIPTION
**Pull request by GKD890**
# Description
This is a unit test for Edit Link Modal
Or Implements # (WBS) 

## Main changes explained:
- add some `id` and `data-testid` in `EditLinkModal.jsx` for better testing experience.
- test some logic when editing EditLInkModal, especially **Media Folder LInk** (some times it's used **media Url**)

## How to test:
1. check into current branch
2. do `npm install` and `npm test src/components/UserProfile/UserProfileModal/EditLinkModal.test.js`
3. verify that all tests pass.

## Screenshots or videos of changes:
Screenshot 2023-11-12 at 00 50 00

### CODE REVIEW

**Comment by wanglu1207** [comment]
@GKD890  Good job! All the test cases passed!

**Review by Bali2Mohit — COMMENTED** [review]
Hi @GKD890, the unit tests are passing. Well done
Screenshot 2023-11-11 at 23 15 40

**Comment by kavya151** [comment]
Hi @GKD890, All the test cases passed. Good work!
Screenshot 2023-11-11 at 8 03 10 PM

**Review by DavidC0126 — DISMISSED** [review]
Hi @GKD890 I tested the PR and it works as described.

Screenshot 2023-11-13 at 12 55 40 AM

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

week12 - PR1

**Review by Bali2Mohit — APPROVED** [review]

**Comment by GKD890** [comment]
Due to the file is placed in the wrong folder, please don't' review it now

**Comment by GKD890** [comment]
Hi everyone, thanks for testing it again, I didn't make any differences to the files, but only to relocate it to the component folders as suggested in the channel.
**I've changed the directory for you:**
- simply run `npm test src/components/UserProfile/UserProfileModal/EditLinkModal.test.js` 

Thank you in advance.

**Review by Alforoan — APPROVED** [review]
They all passed. Nice!

image

**Pull request merged**
