### PR TITLE
Aditya-Added-Tests-For-Badges

### PR DESCRIPTION
**Pull request by adityasure9**
# Description
This PR introduces unit tests for the `Badges` component to verify the correct display of badge-related messages. These tests ensure that both the number of badges and the context (whether the user is viewing their own profile or another user's profile) are handled accurately.

## Main changes explained:
- **Created** `Badges.test.jsx` to introduce unit tests for the `Badges` component.
- **Mock** Redux store to simulate authentication, user profile, and role states.
- **Implemented** tests for badge display logic, ensuring the component correctly displays:
  - No badges,
  - One badge,
  - Multiple badges,
  - Contextual messages depending on whether the user is viewing their own or another user's profile.

## How to test:
1. Check into the current branch.
2. Run `npm install` to install dependencies.
3. Run `npm test Badges.test.jsx` to execute the unit tests.
4. Verify that all tests pass, and the text for badge displays matches the expected values for each scenario.

## Screenshots or videos of changes:
image

## Note:
Ensure that the badge display logic behaves correctly under different user contexts and badge collection states. Also, check for edge cases like an empty badge collection or large numbers of badges.

### CODE REVIEW

**Review by Lexie5212 — APPROVED** [review]
I tested the PR, all tests passed as expected.
Screenshot 2024-09-27 at 21 08 25

**Review by jinxyou — APPROVED** [review]
image
All test cases have passed!

**Review by ziyanw52 — APPROVED** [review]
I have test this, and all the test cases passes!
591727502652_ pic_hd

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture2733

**Review by Watchdog00 — COMMENTED** [review]
I have completed the testing and got the expected results. Good job!

**Review by aaryaneil — COMMENTED** [review]
I am not sure what this PR intends to do as it isn't adding any new test cases to the pre existing ones.

**Comment by mianmiantea2019** [comment]
All test cases are passing but one console error

image

**Review by Dk-21 — APPROVED** [review]
PR 2733
@adityasure9 
All the test cases Passed.

Screenshot 2024-09-30 at 8 41 38 PM

**Review by slidracoon72 — APPROVED** [review]
#2733
@[adityasure9](https://github.com/adityasure9) 
Verified the unit test file, and all test cases successfully passed.

**Comment by tharunaa-1** [comment]
All the test cases passed as expected. 
image

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and all test cases passed.

Screenshot 2024-10-02 235750

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the testcases have passed.
Screenshot (219)

**Comment by geetamatkar** [comment]
Hi,
I tested this PR and all test cases have passed.

PR2733

**Comment by mianmiantea2019** [comment]
all test cases have passed.

image

**Review by j-corp-25 — APPROVED** [review]
All tests are passing great work

Screenshot 2024-10-06 at 2 31 06 AM

**Comment by SatyashanthiT** [comment]
I have reviewed this PR, ran the unit tests for the Badges component using Badges.test.jsx, and confirmed that the badge display logic functions correctly across various scenarios. The tests passed successfully, ensuring accurate messaging for different badge counts and context conditions.
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
