### PR TITLE
Eduardo add skeleton loading feature to all components

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
image

## Main Change
Created a new `SkeletonLoading` component to replace the old `Loading` component.

## Main Changes Explained
- Implemented the `SkeletonLoading` component, which accepts a `template` prop.
- The component uses switch/case logic to determine which Skeleton Loading mock should be rendered based on the provided template.
- The `template` prop is a string that specifies the name of the component being addressed.
  - Example: `<SkeletonLoading template="TeamMemberTasks" />`, `<SkeletonLoading template="UserProfile" />`, etc.

## How to Test
1. Checkout the branch: `git checkout Eduardo_add_skeleton_loading_feature_to_all_components`
2. Run `npm install` and `npm run start:local` to locally run this PR.
3. Log in as an admin to gain access to all pages.
4. Go to the Dashboard and ensure the page fully loads.
5. Navigate to Reports -> Weekly Summaries Reports and wait for the page to fully load.
6. Visit Other Links -> User Management and wait for the page to fully load.
7. Access the View Profile page and wait for the page to fully load.
8. Verify if the Skeleton Loading mock is being rendered correctly.

### Old Loading Component
image

### New SkeletonLoading Component
Screenshot 2023-06-27 12-30-23
Screenshot 2023-06-27 12-30-30
Screenshot 2023-06-27 12-30-07
Screenshot 2023-06-30 12-00-07
Screenshot 2023-06-30 12-00-28

### CODE REVIEW

**Comment by beblicarl** [comment]
This functionality works as intended. Great work!!

[skeleton-loader_3000-2023.06.30-17_43_59.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/872b1217-ada3-4dd5-bd82-5d7d3ac63542)

**Review by beblicarl — DISMISSED** [review]

**Comment by AuroraLovesWhales** [comment]
Hi @eduhorta. I have tested your PR. The new loading feature works as intended, except for one thing: the time filter takes forever to load for me. Please refer to the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/31675706-ace3-4274-a622-907b35965c3c

**Review by mahamakhan — APPROVED** [review]
All pages mentioned work as intended. 

image

**Comment by eduhorta** [comment]
> Hi @eduhorta. I have tested your PR. The new loading feature works as intended, except for one thing: the time filter takes forever to load for me. Please refer to the video below.
> 
>  Screen.Recording.2023-06-30.at.3.34.43.PM.mov

Hey @AuroraLovesWhales, thank you for testing my PR! 😁

About your video:
I also have the same problem with long loading times for the filter you just pointed.
But that was already happening even with the old `Loading` component

image

While developping the SkeletonLoading I realized that the loading time has something to do with the number of items are being rendered on the Team Member Tasks. So, using an Admin account the list was long and it did take some time to finish it.
I think it has something to do with our hardware (correct me if I am wrong)

Can you try to run the test on a volunteer/mentor account?
I got a smoothier behaviour by doing that. Check this video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/d667c26d-dd36-4756-94c3-a64823737a9a

I also noticed that the live version of the app we are using has a faster loading time than when I'm running things locally. So I'm expecting the Skeleton Loading to perform better on the live app.

**Comment by Jiangwei-shi** [comment]
work as intended! good work!
image

**Review by HectorAgudelo — DISMISSED** [review]
The changes work as intended although the loading time is a bit slow. specially for the time buttons.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/0451204f-f1ef-4d27-b5d6-aa76cf8cccf6

**Comment by AuroraLovesWhales** [comment]
> > Hi @eduhorta. I have tested your PR. The new loading feature works as intended, except for one thing: the time filter takes forever to load for me. Please refer to the video below.
> > Screen.Recording.2023-06-30.at.3.34.43.PM.mov
> 
> Hey @AuroraLovesWhales, thank you for testing my PR! 😁
> 
> About your video: I also have the same problem with long loading times for the filter you just pointed. But that was already happening even with the old `Loading` component
> 
> image
> 
> While developping the SkeletonLoading I realized that the loading time has something to do with the number of items are being rendered on the Team Member Tasks. So, using an Admin account the list was long and it did take some time to finish it. I think it has something to do with our hardware (correct me if I am wrong)
> 
> Can you try to run the test on a volunteer/mentor account? I got a smoothier behaviour by doing that. Check this video:
> 
>  2023-07-01.09-39-45.mp4 
> I also noticed that the live version of the app we are using has a faster loading time than when I'm running things locally. So I'm expecting the Skeleton Loading to perform better on the live app.

Hi @eduhorta. Thank you so much for your detailed response! I have tested with a volunteer account but am still experiencing the same behavior. Maybe it is due to hardware issue since others are not experiencing the same problem. Everything else is working as intended. I will go ahead and approve this PR. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/3b1d937c-3060-424b-abe5-bdd74f94cf25

**Review by AuroraLovesWhales — APPROVED** [review]

**Review by tdkent — APPROVED** [review]
Local tests confirm this PR is function as intended. `SkeletonLoading` component replaces `Loading` component on the following pages:
- `/dashboard`
- `/weeklysummariesreport`
- `/usermanagement`
- `/userprofile/:id`

The skeleton gives a visual preview of the incoming page and prevents page elements from being pushed during loading.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/09c6f0f4-8c0d-4375-8fce-c3928098c61a

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Comment by xaanders** [comment]
Tested this PR and all changes work as expected. SkeletonLoading component has replaced Loading component on these pages:
-dashboard
-weekly summaries report
-user managment 
-profile page 
As a suggestion on pages like dashboard to render just some of the list items in the first render, and a button to expand it if needed. Otherwise it can cause a delay showing the page content with full list. 

Everything works as intendend. Good job!
[scrnli_05-07-2023_11-49-19.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/34bca42d-0b02-48ca-8161-57d8c226e839)

**Review by xaanders — APPROVED** [review]

**Review by NidaZaki — APPROVED** [review]

**Review by juneluo — APPROVED** [review]
The PR has replaced the loading component with the skeleton loading component successfully.
Test result: following pages have the new loading component:
Dashboard (timelog)
Weekly Summaries Reports page
User Management page
User profile page

**Pull request merged**
