### PR TITLE
Shrey add unit test cases for user table header

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for UserManagement component UserTableHeader.jsx

## How to test:
1. check into current branch
2. do `npm install` 
3. npm run test UserTableHeader.test.js
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-12-08 at 11 42 50 PM

### CODE REVIEW

**Comment by DragonSlayer2401** [comment]
I tested your PR it appears to be working as intended. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/3af9bc15-862e-40a1-aecd-96f6842477b9

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-09 at 12 18 02 AM

**Review by Hemsharavanan — APPROVED** [review]
- Your suite correctly verifies the rendering of table headers in the UserTableHeader component, ensuring all expected headers are present. 
- Good approach in writing test cases covering the permission-based rendering.
- Overall the tests provides thorough coverage for the UserTableHeader component, validating header rendering and conditional column display based on permission levels effectively.
- Good work!
PR #1653 Shrey add unit test cases for user table header

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 16 - PR7

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
