### PR TITLE
Yubo - feature- warning popup in editing media links

### PR DESCRIPTION
**Pull request by GKD890**
# Description
This is a 

## Main changes explained:
- Add a popup to if the `Media Folder` link is changed to remind and confirm such operation
- Add a **Cancel** button to withdraw the changing operation.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user -> go to other user's profile page -> click link **Edit** under picture.
4. Try to change the `Media Folder` link and see if the popup works.
5. Click **Cancel** will withdraw the changes; Click **Confirm** will continue editing.

## Screenshots or videos of changes:
Screenshot 2023-09-03 at 2 41 39 AM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/5b168205-d5ab-482a-a9c1-7747d72f5dc0

## Note:
You need **Admin** account to change other user's `Media Folder` link

### CODE REVIEW

**Comment by luisarevalo21** [comment]
Hello @GKD890,

I tested your PR and works as intended. Great work! 
When attempting to change the media link or google doc a modal warning appears. 
Canceling and attempting to change it again makes the modal appear again. 

When continuting user can change the link.


One thing I noticed is if user's do attempt to change the link and try again the modal doesn't appear. I'm unsure if that is intended or it should appear every time a user' tries to attempt to change it. 

The video displays it.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/c8df438f-242e-44cc-a385-8d2cc40053e1

**Review by belagaam — CHANGES_REQUESTED** [review]
I tested the PR as per the instructions. 

One thing I observed is that when I try to change the link for the first time it gives a pop-up warning. After that, I can edit the link any number of times until the page is refreshed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/5142543c-f52d-4401-ac0b-8ecb7a813fb5

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Great work! A warning pops up to notify the user that they are trying to edit the Dropbox link which they might not want to do.

The only suggestion I want to make is to make it where if you confirm you want to change the Dropbox Link but then you change your mind and close the Edit Link modal, if you open the Edit Link modal and try editing the Dropbox link again, the warning should pop up again. Currently, the Edit Link modal seems to be saving the state of the user confirming they want to change the Dropbox Link in between renders.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/90614d90-3fcb-4598-a3e6-986a6b3f31b2

**Comment by Sssky-18** [comment]
Great job! I tested out this feature on two different account levels, and it performed as expected. Congratulations!

When an admin account attempts to modify the Media Folder link, they'll encounter a pop-up cautioning them to proceed with care. If they choose "Cancel," the warning will reappear the next time they attempt to alter the link. However, if they select "Confirm," the warning will not reappear, enabling them to make the change. So, I find this feature to be quite efficient.

One question I'd like to raise, which Gary also mentioned earlier, is that the warning does not reappear when this admin, after changing the link for one individual, returns to that person's profile at a later time and wishes to make another adjustment. Is this how the feature is intentionally designed to function? It might be a good idea to have the warning pop up each time the admin opens the individual's profile and wants to modify the link.

Thank you for your contribution! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/b4f26273-e693-4d70-a43b-8c9c63107906

**Comment by DavidC0126** [comment]
Hi @GKD890 I tested your PR and it performs as described. My observation is the same with others' comment on this PR earlier that if a user attempts to change the link and try again, the modal doesn't appear.
warning

**Review by Haoj1 — COMMENTED** [review]
@GKD890 Good job! The popup displays correctly after trying to change the content in media box. And I am wondering if it is able to display the popup again when try to edit again as others mentioned above.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/a4c5581e-7073-4158-aee7-b6e97a7a7caf

**Review by harshidad — COMMENTED** [review]
I tested the PR as per the instructions.

 I observed  below: 
 1. when I try to change the link for the first time it gives a pop-up warning. After that, I can edit the link any number of times .
 2. After doing changes, even I click the Cancel button, instead of withdraw the changes it save the changes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/302abb99-fb7a-4916-993a-cc032e1d8c2a


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/750f6250-b248-443d-a625-635f0380e47f

**Review by robertoooc — DISMISSED** [review]
Hi @GKD890, I tested your newest implementation and it does provide a warning popup when trying to edit the media links. 

I saw what everyone else mentioned and can also confirm that once you hit the confirm button then exit the modal it will no longer show up if you try to edit the links again, it only will reappear after a full page refresh. It's probably just a matter of resetting your state booleans after the modal closes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/13346b43-70d0-4889-869a-de2eedbdbbf1

**Review by gabi-lima — COMMENTED** [review]
It works the first time, but after that it no longer appears.
image

**Comment by dah00** [comment]
Hey @GKD890, I have tested your PR and the popup warning shows up as expected when I try to make a change to the media folder. However, I am not sure if it is normal that the warning pops up the first time only. After clicking on the confirm button, it no longer shows up. I have to refresh the page before the warning pops up again

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/37416ca1-9364-4d4d-9758-77de362d9e0e

**Review by Jiyuanxia — APPROVED** [review]
Hi @GKD890 , I have reviewed your pull request and tested it. It works as you intended. Well done.
Screenshot 2023-09-15 135042

**Review by Shiwani99 — DISMISSED** [review]
Hi,
I tested your PR. It works as Intended. I am getting a pop up when I try to change it and when I give confirm I am able to move forward with editing it.

**Review by Bhagyashree444 — CHANGES_REQUESTED** [review]
Great job, and it functions perfectly the first time I attempt to update the links. When I choose to cancel the update, it behaves as expected. However, if I confirm and make changes, then on the second attempt to update the link, the popup doesn't appear.

An image for the popup when updating for the first time.
PR #1236

**Comment by astrjc0326** [comment]
I tested the PR, and it worked as described.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/478e33c3-414a-44ed-a92a-24cc55a2be05

**Review by vikrambadhan — CHANGES_REQUESTED** [review]
Hi, I evaluated the PR in accordance with the instructions.

One thing I noticed is that a pop-up warning appears the first time I try to modify a link.  The link can then be changed as many times as necessary until the page is refreshed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/a9b7a42f-aab9-4c2c-b567-d8fcb89e888e

**Comment by Chuehleo** [comment]
The warning popped up successfully but as others mentioned, the modal only pop up for the first time.
Screenshot 2023-09-23 171820
Screenshot 2023-09-23 171927

**Review by EdwinLauM — APPROVED** [review]
Hi @GKD890! Works as expected, trying to modify the linked makes the modal popup, running into the same problem the other members have mentioned

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/e264da9e-f1b6-42f7-87f4-445276185bb0

**Comment by RheaWu1212** [comment]
I tested PR, admin dashboard --> go to user --> edit media link --> none was there, so I added it --> NO POPUP --> changed link agagin --> NO POPUP AGAIN

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/47fb8528-f081-4b0b-acaa-3cdac7f25b93

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions. This pop up functionality works as expected the first time. However when I change it afterwards, the warning is gone and does not popup later on.
Screenshot 2023-09-30 at 11 24 18 PM
Screenshot 2023-09-30 at 11 25 40 PM

**Review by JeffLi117 — APPROVED** [review]
Your changes work as intended, but only once (until the page is refreshed). As others have mentioned, it might be more reasonable to ensure that each time the LINKS Edit is clicked necessitates a new warning. However, I can see the other side of the argument in ensuring there are as little (but still necessary) warnings.

image

**Comment by GKD890** [comment]
Thanks for the feedback, I've updated the popup confirmation, now it will show again if you **Cancel** the edit modal and open it again, and here's the most recent [commit](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1236/commits/bb6631439444768d8623fdc209a1b5834d045724) for those who have approved the code.

My initial thought is to leave more flexible to admin who's doing this operation, but seems it's more intuitive to have multiple confirmation (and that's more safe). Please review it again and let me know if you have any concerns. Thank you.

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Hi @GKD890, I was originally going to approve this request but stumbled onto an interesting edge case.

Starting with a refreshed page on the user's profile page with an empty Media Link and I try adding a Dropbox link which does prompt me with the popup warning as intended. I update the newly added link and it gets saved to the user's profile.

However, if you open up the Edit Links Modal again right after and delete the link you just added you are not prompted with a warning. And after doing that, if you close the modal and reopen it, it seems to have saved the state of you deleting the link without you updating it. See video for clarification.

After further testing I've found this issue might only exist if you click the Update button and not the Cancel button.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/95accc96-554c-4829-9fec-4c2c96d374ff

**Comment by GKD890** [comment]
> Hi @GKD890, I was originally going to approve this request but stumbled onto an interesting edge case.
> 
> Starting with a refreshed page on the user's profile page with an empty Media Link and I try adding a Dropbox link which does prompt me with the popup warning as intended. I update the newly added link and it gets saved to the user's profile.
> 
> However, if you open up the Edit Links Modal again right after and delete the link you just added you are not prompted with a warning. And after doing that, if you close the modal and reopen it, it seems to have saved the state of you deleting the link without you updating it. See video for clarification.
> 
> After further testing I've found this issue might only exist if you click the Update button and not the Cancel button.
> 
>  Screen.Recording.2023-10-04.at.3.16.01.PM.mov

Thank you for pointed that out. Since when I noticed the comment, it was already been merged. But I do solved it now in PR #1416 , just let you know that. Really appreciate your testing on edge cases.

**Pull request merged**
