### PR TITLE
Ivy-Send Emails, gives a successful message when email list is empty

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
Screenshot 2024-07-31 at 3 39 22 PM

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. go to dashboard→ Other Links→ Send Emails→…

https://github.com/user-attachments/assets/d9b8834f-09ad-4fa7-a0b9-a8bf2d461f85

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Pranay-ai — APPROVED** [review]
Hey @20chen-7 
I Reviewed the PR Working as Expected here is the screenshot
image

Thank You

**Review by manikittu810 — CHANGES_REQUESTED** [review]
Hello @20chen-7 
I have reviewed the code and these are my observations :
1)Working : Empty textbox gives error message to the user.
2)But, when the user gives an input string without '@gmail.com'(which is a normal string like a,b,c) it is displaying 'Email successfully sent'. Is this the intended behavior of code? Because the given string is not getting validated as an email and still displaying as mentioned above.

https://github.com/user-attachments/assets/f45ac04f-2c1a-498c-855c-2ed13ecd7d3e


https://github.com/user-attachments/assets/69b8f6cd-418f-4b41-ab2e-f9d69177decf

**Comment by 20chen-7** [comment]
> Hello @20chen-7 I have reviewed the code and these are my observations : 1)Working : Empty textbox gives error message to the user. 2)But, when the user gives an input string without '@gmail.com'(which is a normal string like a,b,c) it is displaying 'Email successfully sent'. Is this the intended behavior of code? Because the given string is not getting validated as an email and still displaying as mentioned above.
> 
>  Screen.Recording.2024-08-01.at.11.31.34.AM.mov 
>  Screen.Recording.2024-08-01.at.11.32.44.AM.mov

That's another bug here, out of scope based on the bug description. You can post in the bug doc as a new bug.

**Review by manikittu810 — APPROVED** [review]
Everything working good
Thanks.

**Review by Jingyii800 — APPROVED** [review]
I tested this feature and it worked as expected, I can not send the email when the email list is empty.

https://github.com/user-attachments/assets/bef19a2b-ec19-454f-a2c2-ff9096bde171

**Review by JatinAgrawal94 — APPROVED** [review]
1)Even when I enter an invalid email, the page still shows me that "Email was sent". 
2)when the field is empty it shows me error, which it should be.
Considering 1st one is not in scope. Everything works fine.
Good work.

https://github.com/user-attachments/assets/cfc7e7a2-705a-414d-b06c-35e2b507981b

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and it's working as expected.

https://github.com/user-attachments/assets/80af5b1d-ebeb-4ac9-ad70-dc71da1df010

**Review by kdaga81 — APPROVED** [review]
image
image

Working as expected!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
