### PR TITLE
XiaoW Improve loading speed of new tasks resources

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
Fixes bug list PROJECTS/TASKS/WBS COMPONENT 6 (priority high) :

Improve loading speed of New Tasks resources
- Other Links -> Projects -> WBS -> Pick any -> Add Task -> Choose Resource
- When adding “resources” to a new task, the resources list of people often doesn’t include everyone until I refresh.

## Main changes explained:
- Delete obsolete codes in AddTaskModal component for finding members, they are not being used since PR [#694](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/694#issue-1609123908)
- Update the way AddTaskModal component handles members, make it update in time
- optimize logic of handleFilter function in TagsSearch component

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. open incognito browser with no cached data
4. log as admin user
5. go to dashboard → Other Links → Projects → Pick your project → Pick your WBS → Click Add Task → type member name in Resource input
6. verify a list of members will show up soon as you type the first letter of member name without refreshing

## Note:
The members must be in the same project

### CODE REVIEW

**Review by bienzguoa — COMMENTED** [review]
It works as described! When typing a letter, all names include this letter will show in the list and they are sorted from A-Z(a-z), one suggestion is : we can sort the list so that the names with inputted first letter will be on the top.

Screenshot 2023-06-17 at 7 19 55 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/e83cd360-5cc4-4501-a095-2ef69066566e

**Review by stevenpaalz — DISMISSED** [review]
This optimization appears to be working as intended. Resource lookup is now very fast.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/38872726-aa29-428f-9b29-938febbe7821

**Comment by wang9hu** [comment]
> It works as described! When typing a letter, all names include this letter will show in the list and they are sorted from A-Z(a-z), one suggestion is : we can sort the list so that the names with inputted first letter will be on the top.

Hi @bienzguo, thank you for reviewing my PR! In regarding to what you suggested, although I believe it is a great idea, it falls outside the scope of this PR.

**Comment by one-community** [comment]
> > It works as described! When typing a letter, all names include this letter will show in the list and they are sorted from A-Z(a-z), one suggestion is : we can sort the list so that the names with inputted first letter will be on the top.
> 
> Hi @bienzguo, thank you for reviewing my PR! In regarding to what you suggested, although I believe it is a great idea, it falls outside the scope of this PR.

I agree... Zubing, please add this as a new request though on the bugs doc. We should do this with ALL lists where it would be helpful.

**Review by EdwinLauM — COMMENTED** [review]
Works as intended! I agree with @bienzguoa suggestion. Will approve when those changes are made. Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/a6d4f1b3-dee8-46af-8f10-f88bff6334e0

**Review by yufeiStella — APPROVED** [review]
Hi @wang9hu, I added all members to my projects, and your function works very well!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/537d3e83-4dbe-4669-8ae6-074fbbe8e24a

**Review by bienzguoa — APPROVED** [review]

**Review by NidaZaki — APPROVED** [review]
Great work! It works as intended! And I agree with @bienzguoa suggestion, should be interesting to develop.

**Review by Chuehleo — DISMISSED** [review]
Everthing work as intended, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/79b5b036-e8f2-423c-8215-12bb9f0f5af4

**Comment by Lucas-E** [comment]
Thank you everyone! Moving to final review!

**Comment by cvtqx** [comment]
The new filter works as intended and matching resources are displayed immediately upon typing in the input field. 

Screen Shot 2023-06-20 at 3 57 15 PM

**Comment by juneluo** [comment]
The resources list of people shows as intended. Good job. 
I like the change of deleting obsolete function to keep the code clean.
I notice that the same obsolete function appears in the `EditTaskModal.jsx `and it seems to have very similar way to handle members as the previous `AddTaskModal.jsx.` Will it be a good idea to apply similar improvement to that file? I think they are highly related and can be made in the same PR, but for sure you can raise another PR for it if you prefer.

**Review by juneluo — APPROVED** [review]

**Pull request merged**
