### PR TITLE
Ramakrishna Fix 5-Digit Search Function Breaks After Edits

### PR DESCRIPTION
**Pull request by Ramaruva**
# Description
Bug Fix -  
image

## Related PRS (if any):
Please use latest backend development branch for this
…

## Main changes explained:
- Update file weeklysummaryreports.jsx to update the handleteamcode change

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. Dashboard→ Reports →Weekly Summaries Report
6. Try too search  in SELECT TEAMCODE
7. And Try to change any change any TEAMCODE 
8. Now verify that you are able to search in SELECT TEAMCODE 

## Screenshots or videos of changes:
Before Changes:
https://www.loom.com/share/3893c617bcaf4cd998c0cfffb55b7bd9?sid=28904b8a-062c-4e39-ac30-29e229dd13ed

After Changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/879b14f3-1194-42f1-8128-977432c17b39

## Note:
Sometimes for somecodes if we try too change any teamcode we are getting an userprofile api call error alert(500status) that is not related to this changes so please ignore it.
Sometimes in selectdropdown box the selection event his not notifying immediately (like button responses are slow sometimes ) those slowness is didn't caused due to these changes.

### CODE REVIEW

**Review by Wenboooooo — APPROVED** [review]
I followed the instruction and logged in as admin, input the team code A-AAW and a-abc for the first try, the page successfully rendered the result. Then I changed the search content to A-BCD and A-KKK and the functionality works too. In the end I cleared the search content and the page displayed all the team by default. To me it works good.

**Review by jinxyou — APPROVED** [review]
I have tested this pull request. I have tested the function of searching for team codes, and add it to the filter. The results returned by the filter of team codes are correct. After several tries, the function is working properly. Excellent work!

Screenshot 2024-05-31 001253

**Review by Kavil-Jain-514 — APPROVED** [review]
I successfully searched the team code after making changes to it. The code is excellent, and I encountered no issues. 

image

image

**Review by sucheta90 — APPROVED** [review]
Hello @Ramaruva , I have followed the steps mentioned to test this PR, and would like to confirm that the feature works as intended for both Admin and Owner's role. Well done.
Screenshot 2024-05-31 at 3 51 29 PM

**Review by KyreneAF — APPROVED** [review]
- when name is updated you are able to search for it in the search bar above without refreshing the page.
- You are also able to change back to the original name and search for it without refreshing the page.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/6dfcd196-f780-4da6-a548-5c74616a2233

**Comment by CloudyZ524** [comment]
I've tested the teamcode search function which works as expected! Nicely Done.

Screenshot 2024-05-31 at 16 28 29

**Review by CloudyZ524 — APPROVED** [review]
I've tested the teamcode search function which works as expected! Nicely Done.

Screenshot 2024-05-31 at 16 28 29

**Review by peter6866 — APPROVED** [review]
Great work on updating the Weekly Summaries Reports component to fix the search functionality and handle team code changes! Here's the review based on the provided testing steps:

✅ Updated handleTeamCodeChange:
   - Reviewed the changes made to the `weeklysummaryreports.jsx` file, specifically the updates to the `handleTeamCodeChange` function.
   - Confirmed that the modifications are implemented correctly and align with the intended functionality.

✅ Search Functionality in SELECT TEAMCODE:
   - Logged in as an admin/owner user and navigated to the Weekly Summaries Report page (Dashboard → Reports → Weekly Summaries Report).
   - Tested the search functionality in the SELECT TEAMCODE dropdown.
   - Verified that the search works as expected, allowing users to find specific team codes easily.

✅ Changing TEAMCODE:
   - While on the Weekly Summaries Report page, attempted to change the selected team code.
   - Confirmed that the team code can be successfully changed without any issues.
   - Verified that the reports and data displayed on the page update correctly based on the newly selected team code.

✅ Ability to Search Again:
   - After changing the team code, tested the search functionality in the SELECT TEAMCODE dropdown again.
   - Ensured that the search feature remains functional and allows users to search for team codes even after making changes.

https://www.loom.com/share/8c31655ce58e4b8698684f514d0e225c?sid=421955fb-86f0-43b2-a77a-dec84a8e218a

**Review by Sandhya1236 — APPROVED** [review]
I have successfully tested the changes on the latest backend development branch. The update to the WeeklySummaryReports.jsx file, specifically modifying the handleTeamCode function, was implemented. After running npm install and clearing the site data and cache, I logged in as an admin user and navigated to the Weekly Summaries Report. I verified that searching in the "SELECT TEAMCODE" dropdown and changing any "TEAMCODE" worked correctly. The functionality performed as expected, allowing seamless searching and updating of team codes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/14b2574d-35eb-48ef-8ea7-b92ebe39adf7

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and it works perfectly as intended. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/1ec1327d-1581-4f0d-9f7b-e016aefc9de4

**Review by cecilia-uu — APPROVED** [review]
I tested your PR and it works perfectly as intended. Good job!
截屏2024-06-01 下午4 14 23

**Comment by nishithaShetty** [comment]
Hi, Nice work! The functionality works as expected. I tried multiple searches, and it worked as expected without refreshing the page. I was also able to change the name successfully.
PR#2301_1

**Review by cgomezhub — APPROVED** [review]
the functionality is working as required, is correctly updated in the search bar when is changed in the list. good job!
https://www.loom.com/share/bc70b928a72c4c26bc6271b14767976f?sid=d2b2b888-a32c-47fe-a3fd-bd36d2918f27

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
