### PR TITLE
WBS #4.3 - Changes to project page and WBS

### PR DESCRIPTION
**Pull request by VC444**
- Added popup that shows instructions about projects on the projects page
- Added edit button by task number in WBS
- Inside the edit modal, the classification is changed to a dropdown list

### CODE REVIEW

**Comment by daoquangvy** [comment]
@VC444 
Hi Vignesh,

In OneCommunityGlobal, we normally work and update our code on a future branch inside this repo rather than creating a fork and merger them with the development branch. The reason we have this workflow is that:

1. It allows us to keeps all of the branches and testing them in one place by using "git checkout"
2. We only have to deal with one git remote, rather than dealing with multiple remotes.
3. Merging all the branch to  the development branch is also easier

Since you are forking the repo, If I want to pull your branch and test them, I can't just simply using "git checkout" to change branches. I need to do some "git remote", and also make sure the merger later will not conflict with the development branch.

I wonder if you can take a look at our current branch inside this repo. Feel free to create a new branch in this repo and update your code there if you can't find a branch that covers what you are working on.

Please let me know if you have any questions.

**Comment by VC444** [comment]
I understand. I tried pushing my changes directly using a branch, but I get an error stating that I don't have write access to the HighestGoodNetworkApp repo. Do you have any recommendations on what I can do?

**Comment by one-community** [comment]
Try now. I'm not sure why, but you weren't added with editing access to our repos. I normally do all that at once, so somehow I made an error and must have missed it during your setup process.

**Comment by one-community** [comment]
Maybe my invite to you was missed or declined... just checked the other areas I add you and you still have in invite pending for Sentry. Just invited you again to the HGN group that gives you the write access you need.

**Comment by VC444** [comment]
Great! I have pushed my changes now.

**Comment by daoquangvy** [comment]
Can you create a PR from it? I will review it as soon as I'm available again.

**Comment by VC444** [comment]
> Can you create a PR from it? I will review it as soon as I'm available again.

done

**Pull request closed without merging**
