### PR TITLE
yixiao_taskreducer_unit

### PR DESCRIPTION
**Pull request by JYXiao-2021**
# Description
Create the unit test for the reducer component to confirm whether it working as intended.

## Main changes explained:
-Create file reducer.test.js to do the unit test.

## How to test:
1. check into current branch
2. do npm install to run this PR locally
3. run npm test src/components/TaskEditSuggestions/`__tests__`/reducer.test.js
image

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by ShengjieMao — CHANGES_REQUESTED** [review]
Hi, not sure if I met some problems on my end, but after running the commands as you described in the pr, there seems to be no tests found for your file. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/c6867855-76bf-4272-8552-5be992e37bcc

**Comment by Cavein254** [comment]
Hi @JYXiao-2021, I have tested this pr and have similar conclusions to @ShengjieMao. There is not test file as the one you have stated in the pr.

Screenshot 2024-01-26 151053

**Comment by JYXiao-2021** [comment]
The __tests__ not shown good in my first comment. I changed now and also show an image to show the correct command.

**Review by sahilpatel18 — COMMENTED** [review]
I am getting an unexpected output

Screenshot 2024-01-26 at 11 00 24 PM

**Review by ShengjieMao — APPROVED** [review]
All tests passed
PR_1881(2)

**Review by 666saofeng — APPROVED** [review]
All Tests passed.
image

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 22 -PR2

**Review by bienzguoa — APPROVED** [review]
The test looks throughly and correctly rendered, and all tests passed!
Screenshot 2024-01-28 at 12 28 39 AM

**Comment by xmyoot** [comment]
Hello, 

I tried testing this PR but ran into some issues, can't checkout into this branch: please see photo: 
image

**Review by X1aoZhang99 — APPROVED** [review]
Hi Yixiao,

All tests passed, nice work! 

Screenshot 2024-01-28 at 18 46 46

**Review by Renanluizssx — APPROVED** [review]
Hi @JYXiao-2021, i tested your unit test and it passed all 
Screenshot 2024-01-30 220320

**Review by yvonnep165 — APPROVED** [review]
Hi @JYXiao-2021 ,
I tested your PR and all the test cases passed. Nice Work!

1881TEST

**Review by Nahiyan-16 — APPROVED** [review]
## All tests have passed
Hi Yixiao, I have tested your PR and all tests have passed successfully. 
However, I do have a few suggestions: 
- For consistency,  'FETCH_TASK_EDIT_SUGGESTIONS_SUCESS'  should be updated to 'FETCH_TASK_EDIT_SUGGESTIONS_SUCCESS' as there seems to be a typo.
- For the 'FETCH_TASK_EDIT_SUGGESTIONS_ERROR' action, you might want to consider adding a comment explaining why the payload is not provided (as it's usually an error action).
- Consider adding comments explaining assumptions or decisions, especially in cases where you assume specific payload structures or when certain values are hardcoded.

Screenshot 2024-02-01 120720

**Review by Pandani07 — APPROVED** [review]
Ran this PR and all the tests passed. 

Screenshot 2024-02-02 at 7 58 26 PM

**Comment by galgalinidhi** [comment]
Hello @JYXiao-2021, I tested the PR and all the test cases passed!

Screenshot 2024-02-03 at 2 20 39 AM

**Review by Sophie-lei — APPROVED** [review]
Hey, I just tested this PR and all tests have been passed.
Screenshot 2024-02-03 at 21 44 38

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed as expected. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/a447490e-c8e4-4695-801d-5c51f16c9c63

**Review by navneeeth — APPROVED** [review]
Hello, @JYXiao-2021! Great job on writing these tests! I believe that they cover all of the aspects involved in the `src/components/TaskEditSuggestions/reducer.js` implementation. 

The tests cover all of the action cases in the reducer: 
```javascript
FETCH_TASK_EDIT_SUGGESTIONS_BEGIN
FETCH_TASK_EDIT_SUGGESTIONS_SUCESS
FETCH_TASK_EDIT_SUGGESTIONS_ERROR
REJECT_TASK_EDIT_SUGGESTION_SUCCESS
FETCH_TASK_EDIT_SUGGESTIONS_COUNT_SUCESS
TOGGLE_DATE_SUGGESTED_SORT_DIRECTION 
TOGGLE_USER_SORT_DIRECTION
```

Good job on maintaining the action names consistently in the tests despite the typos in the action cases in the reducer.js implementation. Perhaps the typos can be corrected by replacing the case names across all files in a future PR.

### Test Cases Result

test_cases_passing

The implementation of the test cases are all passing.

Approving! LGTM!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
