### PR TITLE
Jay unit test for InfoModal component

### PR DESCRIPTION
**Pull request by jayyy-s**
# Description
Implements unit test for the `src/components/Teams/InfoModal.jsx`

## Related PRS (if any):
This is not related to any backend PR

## Main changes explained:
- Create file `src/components/Teams/__tests__/InfoModal.test.js` which implements the following unit tests:
  - Tests that the InfoModal component renders with the correct text
  - Tests that the InfoModal component is not in the document after toggling it closed

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm test -- src/components/Teams/__tests__/InfoModal.test.js` and verify that it achieves complete code coverage

## Screenshots or videos of changes:
image

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested this PR. all test cases passed successfully. 
testcasesss

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (146)

**Review by kdaga81 — APPROVED** [review]
image

All test cases passed

**Review by vijay10pk — APPROVED** [review]
All the test cases passed.
image

**Comment by nikethaanand** [comment]
All the test cases are passed and working as expected.
image

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-07-27 at 5 18 19 AM

**Review by jinxyou — APPROVED** [review]
All test cases passed! Great work!
image

**Comment by mianmiantea2019** [comment]
All test cases passed! Great work!

image

**Review by Gauravmg6 — APPROVED** [review]
All test cases passed

Screenshot 2024-07-27 231652

**Review by ramyaram2092 — APPROVED** [review]
Looks good ! Good job 
image

**Review by gowthamdongari — APPROVED** [review]
All test cases working well
image

**Review by KurtisIvey — APPROVED** [review]
Functions as it should. There's really not a lot to test here, so you nailed everything that did need testing perfectly. Fantastic job. 

Screenshot 2024-08-03 at 3 33 37 PM

**Comment by iTvX** [comment]
Good job

2024-08-04 at 00 37 46@2x

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
