### PR TITLE
Logeshwari - Fix for Newly Created Role not displayed in Permission Management

### PR DESCRIPTION
**Pull request by Logeshwari-Renu**
# Description
issue

## Related PRS (if any):
This backend PR is related to the development backend PR.

## Main changes explained:
- Updated role.js to successfully call Api and create new role for addNewRole function.
- Updated PermissionsManagement.jsx by passing getAllRoles as a prop to CreateNewRolePopup in the ModalBody.
- Updated NewRolePopUp.jsx by adding getAllRoles to the mapDispatchToProps. Also Called getAllRoles after a successful role creation in handleSubmit.

## How to test:
1. check into current branch
2. do `npm install`, `npm run build`, `npm run start` to run this PR locally
3. Clear site data/cache
4. Log as Owner user or user having access to Permissions Management page.
5. Go to dashboard → Other Links → Permissions Management → click Add New Role
6. Create New role by giving Role name and enabling Permissions
6. Verify the success toast message "Role created successfully.
7. Verify the newly role name listed under the User roles by scrolling, without refreshing the page.

## Screenshots or videos of changes:

Before Changes:
https://drive.google.com/file/d/1vFXL7RJjUd_jIxyUtjqflKeGN-IqnnyE/view?usp=sharing

After Changes:
https://github.com/user-attachments/assets/1031d8fa-3982-4e1e-b238-9f90cfd4a538

### CODE REVIEW

**Review by kdaga81 — APPROVED** [review]
Screenshot 2024-07-19 at 6 36 49 PM
Changes working as expected! Role added without refreshing the page

**Review by Chetan0606 — APPROVED** [review]
Verified as per the instructions provided. Everything looks fine. Below are the screenshots attached as per my observation.
Screenshot (313)
Screenshot (312)

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected. Good work.
Screenshot 2024-07-20 at 5 56 22 AM
Screenshot 2024-07-20 at 5 56 41 AM
Screenshot 2024-07-20 at 5 56 56 AM

**Review by Pranay-ai — COMMENTED** [review]
Hey @Logeshwari-Renu 
I was trying to review the PR with backend set to development but i had some issues with the api fetching.

**Review by preethamdnr — APPROVED** [review]
Hello Logeshwari,
This PR is working as expected.
image
image
image

**Review by Lemonnycodes — APPROVED** [review]
Hi Logeshwari,

I have tested the changes introduced in this PR and verified the following:

- created a new role with the specified permissions.
- Confirmed that the success message "Role created successfully" appears after role creation.
- Verified that the newly created role appears in the User roles list without needing to refresh the page.

**Image References:**
PR 2471 (1)
PR 2471 (2)

**Comment by AllenYixuan** [comment]
Hi, I test this part. But when I login the http://localhost:3000/login; it shows 
image
Could you please tell me how to solve it? Thanks

**Review by SnelPatare — APPROVED** [review]
Changes working as expected. Please find below images. 
image

**Review by sriramsme — APPROVED** [review]
Hey @Logeshwari-Renu , I have reviewed the changes and everything works as expected. Although, it worked the same with or without refreshing the page. Please refer to the video:


https://github.com/user-attachments/assets/1e89a348-8565-4260-8755-c812ec9b00d9

**Review by vedantg24 — APPROVED** [review]
Tested the PR, and the changes are working as expected. Added a new role with some permissions, toast is successfully created and can be seen in the list without refreshing

Screenshot 2024-09-04
Screenshot 2024-09-04_1
Screenshot 2024-09-04_2

**Comment by sud306** [comment]
Hello,
I reviewed this PR and it's working as expected.
10  PR2471_1
10  PR2471_2
10  PR2471_3

**Review by yashwanth170 — APPROVED** [review]
I have tested before and after changes, everything is working as expected. 
Add_new_permission_role_1

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
