### PR TITLE
Nahiyan dark mode for user badge and permissions management 

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
THIS IS A FOLLOW UP PR TO https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2105
This PR makes dark mode available for the following pages:
- User Management
- Badge Management
- Permissions Management

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Implemented dark mode for the User Management page
- Implemented dark mode for the Badge Management page
- Implemented dark mode for the Permissions Management page

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links→ User, Badge, Permissions management pages
6. verify that dark mode is working properly on all pages by toggling dark mode on and off
7. go to dashboard→ Other Links→ Permissions management page -> Click on a user role (Ex: Owner) 
8. verify that dark mode is working there too

## Screenshots or videos of changes:
Screenshot 2024-04-08 141949
Screenshot 2024-04-08 175640
Screenshot 2024-04-08 175659
Screenshot 2024-04-08 175715

### CODE REVIEW

**Review by hbodgal — DISMISSED** [review]
It works well and It looks great.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/d633a182-9fac-4fbb-943c-25c29bbbcdab

**Review by linkhanthtel — DISMISSED** [review]
The dark mode looks good on all pages.

#2128 (Badge Management)
#2128 (Permission Management Role)
#2128 (Permission Management)
#2128 (User Management)

**Review by SushmithaPrathap — DISMISSED** [review]
Hey, I've gone through the implementation as per the instructions provided, tested it thoroughly, and everything works as expected. Attached are the screenshots and recording that document my testing process. Great work on this!

Screenshot 2024-04-10 at 10 41 25 PM
Screenshot 2024-04-10 at 10 41 36 PM
Screenshot 2024-04-10 at 10 41 25 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/788dd1fe-3e84-4fda-b4c0-80a91b57d8bf

**Review by SRamen1999 — DISMISSED** [review]
The dark mode for the User Management, Badge Management and Permissions Management page works as expected. One thing I noticed is that when creating something on those pages the modals are not dark mode. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/4a9b9c2f-e77d-497e-8c05-924952864616

**Comment by MQChen211** [comment]
Hi, I tested your PR with User, Badge and Permissions managements, and all works well.
截屏2024-04-11 15 48 37
截屏2024-04-11 15 48 55
截屏2024-04-11 15 49 07
截屏2024-04-11 15 49 34

**Review by MQChen211 — DISMISSED** [review]

**Comment by hiralsonip** [comment]
Hi... I have checked this PR and everything is working as expected. 

PR2128_Badge

PR2128_Permission

PR2128_User_Management

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi, I check you PR and the night mode is working fine in all the pages as you mentioned.
Here attaching the images for reference.
Screenshot 2024-04-11 at 6 55 49 PM
Screenshot 2024-04-11 at 6 55 27 PM
Screenshot 2024-04-11 at 6 55 20 PM

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account. All the mentioned pages can toggle between dark and light mode. Good job! 

**Note**: Pop up modal seems to always be in light mode as shown below:
Screenshot 2024-04-11 at 7 45 35 PM

Other pages are great:
Screenshot 2024-04-11 at 7 45 00 PM
Screenshot 2024-04-11 at 7 43 09 PM
Screenshot 2024-04-11 at 7 44 25 PM
Screenshot 2024-04-11 at 7 44 05 PM

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes look good. Great work.
Screenshot 2024-04-12 at 12 51 09 AM
Screenshot 2024-04-12 at 12 51 21 AM
Screenshot 2024-04-12 at 12 51 31 AM

**Review by MohdShahzil29 — APPROVED** [review]
This is working exceptionally well, just as I envisioned it would, meeting all my expectations flawlessly

**Review by anandsesha — CHANGES_REQUESTED** [review]
Hi Nahiyan, I have tested the dark modes on User, Badge, Permission management pages and for each user role.

**Just one small issue**: 
The Badge management page (dark mode) → Badge Development → Hover on any row and the text is not visible because of the hover color (#F7F9FA) being very similar to the text color. Kindly choose a darker color for the text. Screenshot below. 

Note: Badge management page (dark mode) → Badge Development → Assign Badge when clicked gives a light color popup. Refer second Screenshot below.

Everything else looks great!
Hover color issue

Note - Popup not dark

Screenshot (798)
Screenshot (800)
Screenshot (801)
Screenshot (803)

**Comment by metaphor987** [comment]
Hi Nahiyan,

The testing instructions were very clear. I tested the dark mode for the User, Badge, and Permission Management pages using an admin account. Everything looks great except for a small issue, which is shown in the recording and screenshots below.

When navigating to Badge Management -> Badge Development and then hovering over the badge list, the background turns white, making the text hard to read due to the similar color. It would be great if the text color could be changed in this situation.

Screenshot 2024-04-13 at 1 19 35 PM


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/b5eea7e6-d4c9-41c9-a263-f9fcacde59f2

**Review by Tiantian-C — COMMENTED** [review]
Hi,
It works very well!
Screenshot 2024-04-13 at 4 01 06 PM
Screenshot 2024-04-13 at 4 01 12 PM
Screenshot 2024-04-13 at 4 01 34 PM
Screenshot 2024-04-13 at 4 02 04 PM

**Comment by Nahiyan-16** [comment]
@anandsesha Fixed light mode remaining while hovering over a row. Also, this dark mode PR is not meant to update any modals. Thats for future PRs

**Review by anandsesha — APPROVED** [review]
Hi, following up my previous review, the hover issue on Badge Development row is now fixed. Screenshots attached. Noted - Assign Badge and other Models are not covered in this PR.

PR 2128 Hover issue fixed
Screenshot (872)

**Comment by one-community** [comment]
Thank you all, merging!  We'll get that modal darkmode issue fixed next

**Pull request merged**
