### PR TITLE
Ishan -- > Tapan - fix timelogs tab reverting to user instead of staying on person you are viewing 

### PR DESCRIPTION
**Pull request by TapanPathak**
# Description
Screenshot 2024-08-01 at 11 22 11 PM

https://www.loom.com/share/f650f6233040480b9b2931736fa1dde8?sid=5b7a0f00-50c8-4a48-9863-d7b77932eec8

## Related PRS (if any):
N/A
…

## Main changes explained:
-  Fix timelogs tab reverting to user instead of staying on person you are viewing
- Fixed Code in Timelog to get the url from the link
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. Go to Leaderboard ->  Click on Progress Bar of Any Volunteer
6. Go to Leaderboard -> Click on Any Volunteer -> Click the timelog button on their dashboard
7. Observe time log doesn't revert back to logged in user timelog even after waiting a few seconds
8. Try step 5, 6 and 7 back to back for multiple volunteers and see bug doesn't appear

## Screenshots or videos of changes:
Before - 
https://www.loom.com/share/f650f6233040480b9b2931736fa1dde8?sid=5b7a0f00-50c8-4a48-9863-d7b77932eec8

After - 

https://github.com/user-attachments/assets/b37cca46-0da2-42cc-a75c-62bf7e87695b

### CODE REVIEW

**Review by Ramaruva — APPROVED** [review]
Hi, I have test the changes in my local env and working as expected 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/aaadda48-ffa1-47aa-adae-e46a382012af

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/2966506f-1804-4e08-9e78-acc7805e1179

**Review by peter6866 — DISMISSED** [review]
Changes work as expected.
[PR.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58479595/d4c90671-4004-42b3-93f5-66461dc81986)

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it seems to be working it's just that there is an error of the data not loading apparently but your PR has no issues. Great Job! Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/898e9183-ed65-401f-86fd-a96d5ba5e449

**Review by Sandhya1236 — APPROVED** [review]
I have successfully tested the fixes for the timelogs tab issue, which previously reverted to the logged-in user instead of staying on the selected person. The changes involved updating the code in the Leaderboard and Timelog to correctly fetch the URL from the link. After checking into the current branch, running npm install, and starting the application locally, I cleared the site data and cache. Logging in as an admin or owner user, I navigated to the Leaderboard, clicked on the progress bar of a volunteer, and then accessed their timelog via the timelog button on their dashboard. The timelog consistently displayed the selected volunteer's data without reverting to the logged-in user. Repeating these steps back-to-back confirmed that the bug was resolved and the functionality worked as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/9907ab01-5201-432b-82ae-8e3af777bf0b

**Review by JatinAgrawal94 — APPROVED** [review]
1)check into current branch
2)do npm install and ... to run this PR locally
3)Clear site data/cache
4)log as admin/owner user
5) Leaderboard ->Progress Bar of Any Volunteer  ( Works fine)
6)Leaderboard -> Any Volunteer ->  timelog button on dashboard (Works fine)
Time log doesn't revert back to logged in user Timelog.
Greatwork!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/d57a6453-8df3-4ac0-86a8-342596e13bd7

**Comment by one-community** [comment]
Xiao W said "the logic changes seem legit and I don't think it will break anything", so thank you all, merging!

**Pull request merged**
