### PR TITLE
Shengjie unit test codes for TagSent in WBS

### PR DESCRIPTION
**Pull request by ShengjieMao**
# Description
Created unit tests for the TagSent component in WBS. Checked for functionalities and edge cases.

## Related PRS (if any):
None

## Main changes explained:
- Created tests for check props
- Tested components rendering
- Checked for input types

## How to test:
1. check into current branch
2. do `npm install` and `npm test TagSent.WBS.test.js` to run this PR locally

## Screenshots or videos of changes:
screenshot

## Note:
Tried to test the case of missing inputs, but the original function may lack the checks on inputs validities. Kept the codes in the comments still in case of future needs.

### CODE REVIEW

**Review by AaronPersaud — DISMISSED** [review]
Hi @ShengjieMao, I've tested and everything works! Good job.

image

**Review by sameersdeshpande — DISMISSED** [review]
Hello!
I checked and could see that all tests have passed .
Screenshot 2024-03-23 at 9 19 14 PM

**Review by linkhanthtel — DISMISSED** [review]
I have tested and everything looks good!

**Review by meetpadhiar4 — DISMISSED** [review]
hi, i reviewed your PR and it passed all the test cases. please refer the screenshot attached.
Screenshot 2024-03-25 at 12 00 57 PM

**Review by ImzIssa — DISMISSED** [review]
Hey, I've tested your PR and all your test cases pass. Nice work!

PR#2086

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 20 - PR1

**Review by SanketKaware — DISMISSED** [review]
All the tests have successfully passed and everything looks good!

Here is the screenshot for reference.
image

**Review by m-khalaf — DISMISSED** [review]
test everything and looks good to me as well :)
image

**Comment by aaryaneil** [comment]
Tested this request, and everything looks good.
Screenshot 2024-03-28 at 11 08 28 PM

**Review by aaryaneil — DISMISSED** [review]
All test cases passed, looks good to me.
Screenshot 2024-03-29 at 6 53 14 PM

**Review by navneeeth — APPROVED** [review]
Hey there, @ShengjieMao!

The test cases are all passing:

test cases passing

All of the 6 tests to:
- check the `removeResource` function call with correct argument after `onClick` is triggered
- test the render of an FontAwesomeIcon known by `faTimesCircle`
- test an edge case to not pass `removeResource` function as a prop
- test the render of a `<li>` element with the correct className when the `name` and `userID` properties are in the wrong format
- test the render of a `<li>` element with the correct text in the `<small>` element 
are all well-thought about and efficiently written. They extensively cover the implementation under `src/components/Projects/WBS/WBSDetail/components/TagSent.jsx`. Good use of the `shallow` import to simulate clicks, find elements & className, and play with the properties. LGTM! Approving!

**Comment by rajnada** [comment]
Hii,

It looks good to me! all the test cases pass successfully. Great !

image

**Review by scoopstroop92 — CHANGES_REQUESTED** [review]
Good job on the test cases @ShengjieMao .  Could you help me understand why there are changes in  .prettierignore , package.json and package-lock.json  and included in this PR.

**Comment by ShengjieMao** [comment]
Didn't notice the changes in dependencies when pushed, might be caused by my other working directories I suppose. Now withdraw all the changes in those files and the tests all passed after executing. @ramyaram2092 can you please check again to see if the codes work as expected?

**Review by scoopstroop92 — APPROVED** [review]
Looks good to me !

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
