### PR TITLE
Jiangwei-Apply Tasks Tab time log format to the individual timelogs tabs

### PR DESCRIPTION
**Pull request by Jiangwei-shi**
# Description
(PRIORITY MEDIUM) Jae: Apply Tasks Tab time log format to the individual timelogs tabs (WIP - Jiangwei)
When using the sort function on the Tasks Tab a manager can see which times are logged to tasks vs projects and if the log was 24, 48, or 72 hours ago → 
I’d like this same format applied to the Time Log page and tabs. 
This is needed so that anyone viewing this information can more easily see when work was completed and what it was logged to (Project or Task)

## Related PRS (if any):
N/A

## Main changes explained:
- Create a 72+ button so Adm/own can check  timelogs tabs before 72h
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ timelog→Tasks…

## Screenshots or videos of changes:
image
image
image

This page will have an additional '72+' button. When clicked, it will display tasks from others that were set more than 72 hours ago, and the display bar on the left of tasks from more than 72 hours ago should be gray. The background colors for Tangible and Intangible should be different. At the same time, the left bar of the Project/Task should be hollow, and the bar without a Project/Task should be solid.

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by GKD890 — COMMENTED** [review]
Using admin account, and older tasks can be filtered by **72+** Button.
Frontend_PR#1072_Admin_1

**Comment by beblicarl** [comment]
This functionality works as intended. As you can see from the video below, I logged in as a Volunteer and the 72+ hours option was unavailable however they were available when I logged in on both my Admin and Owner accounts. Great Work!

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.07.30-14_55_31.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/23fc32b5-5e69-42d0-b344-676df5ccf8aa)

**Review by beblicarl — APPROVED** [review]

**Comment by veronicacheng2** [comment]
Hi @Jiangwei-shi, I have tested the PR. The 72+ button appears and is functioning when I am logged in as Owner
Logged in as owner



But when I am logged in as Volunteer and try to access the Tasks tab, the app will crash. I am not sure if this happens to everyone or just me:
Logged in as volunteer

**Review by winghojackyli — APPROVED** [review]
The PR works great! I can use the 72+ filter as an owner. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/eeb4ce53-1ab3-430f-b9a9-6a8d5215b097

**Comment by one-community** [comment]
Looking good!

**Review by eduardocodes — APPROVED** [review]
Hi @Jiangwei-shi 

I tested this PR and everything works well. Nice job!
Screenshot_1

**Review by DavidC0126 — APPROVED** [review]
Hi @Jiangwei-shi 
I have tested the PR and it works as intended.
Screenshot 2023-07-31 at 11 39 48 PM

Screenshot 2023-07-31 at 11 40 11 PM

**Review by xaanders — CHANGES_REQUESTED** [review]
Hi @Jiangwei-shi! I've tested your PR and for owner and admin it works as intended! 

[1.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/0e7d9ea7-7895-45b7-83d7-e96b848c48b8)

But page crashes for volunteer and manager: 

[error.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/5879fb20-0271-413e-b432-82796aba8d0f)

**Comment by sxiong5** [comment]
> Hi @Jiangwei-shi! I've tested your PR and for owner and admin it works as intended!
> 
>  1.webm 
> But page crashes for volunteer and manager:
> 
>  error.webm



> Hi @Jiangwei-shi, I have tested the PR. The 72+ button appears and is functioning when I am logged in as Owner Logged in as owner
> 
> But when I am logged in as Volunteer and try to access the Tasks tab, the app will crash. I am not sure if this happens to everyone or just me: Logged in as volunteer

Hey @xaanders, @veronicacheng2, the page crashed because of the Infinite Scroll, and it does not relate to this PR.

**Review by sxiong5 — APPROVED** [review]
The PR looks good.

Screenshot 2023-08-01 at 15 16 40 (2)

**Review by yurisokolovicz — CHANGES_REQUESTED** [review]
Dear @Jiangwei-shi,

I have noticed some errors in the console when I click the 72h+ button in an owner account. Please see the video below regarding owner and adm acc. This issue seems to be caused by a 400 (Bad Request) status code.


Owner Account:



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/0d9da1f4-afce-49a5-b6f6-a7a1765b625d


Adm Account:



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/5c8cb686-9ee0-49d3-8c1b-e97566e8773f

**Comment by one-community** [comment]
Please confirm the 72 hrs button works for all classes, not just Owner. "This is needed so that anyone viewing this information can more easily see when work was completed and what it was logged to (Project or Task)"

If visible to all, just address the 2 changes requested and it's ready for final review!

**Comment by Lin1404** [comment]
Hi @Jiangwei-shi, I have tested your PR, it works well for Admin and Core Team class, but page crashes for Volunteer and Mentor.

Admin Account:
image

Core Team:
image

Mentor & Volunteer:
image



> Please confirm the 72 hrs button works for all classes, not just Owner. "This is needed so that anyone viewing this information can more easily see when work was completed and what it was logged to (Project or Task)"
> 
> If visible to all, just address the 2 changes requested and it's ready for final review!

**Review by zuhang2000 — CHANGES_REQUESTED** [review]
Hi Jiangwei! I've tested your PR following your instructions. The functionality works great for Admin role. 
Screen Shot 2023-08-05 at 2 13 02 PM

However, when I tried with Volunteer role, it reports error. Please check the recording here. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/642e7229-1265-472d-8294-cabbcb359fee

**Review by yunshan111 — APPROVED** [review]
Tested 72+ button, looks good to me.

image

**Review by ThapeloMasasa — APPROVED** [review]
The 72 hour button does perform the filtering and the tangible and intangible time is displayed as expected
Screenshot 2023-08-09 at 5 18 12 PM

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @Jiangwei-shi 
I tested your PR and Admin works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/039b158b-48af-4f76-826a-a4583c5deeec

However, as others pointed out when I log into a volunteer account the app crashes. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/c77134a0-58dd-430f-8426-2b737198afb8

**Comment by Jiyuanxia** [comment]
Hello, @Jiangwei-shi! I have completed the review of your pull request. The implementation appears to be functional when using the admin role, but it crashes when accessed with the volunteer role.

Admin
Screenshot 2023-08-10 164342

Volunteer
Screenshot 2023-08-10 164845

**Review by scoopstroop92 — APPROVED** [review]
Hello @Jiangwei-shi . Good job . It works well for admin/owner login. However volunteer user crashes

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/189cb1bb-9695-4038-b505-a77692495c4d

image

**Review by LunaticLeo — APPROVED** [review]
Hi, this change works good on my device. @Jiangwei-shi 

image

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, the "72+" button works as intended. Great job. Check the video below. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/fda52734-aa4d-4c52-99e5-a91f073eb729

**Review by belagaam — APPROVED** [review]
I have tested the PR according to the instructions given. The 72+ hr function button works when I log in as an
Screenshot 2023-08-15 at 3 47 34 PM
Screenshot 2023-08-15 at 3 52 15 PM
 Owner/Admin. Great work!

**Review by navneeeth — CHANGES_REQUESTED** [review]
Tested the changes and it works as expected for an Admin/Owner user:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/d2950ae8-d4e8-4f62-b6b4-ef8e278a973a

However, as many have pointed out, there are a bunch of errors observed in the Console when the Tasks tab is loaded when logged in as a Volunteer:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/33d6fa9d-df82-4357-8606-42287cdd4ed5

**Review by belagaam — APPROVED** [review]
I tested the changes as per the instructions. Everything works as expected. Good work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/9af1e2db-b184-4e0b-a040-3a34e0c2641f

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-08-18 125813

**Review by one-community — COMMENTED** [review]
Just waiting on bugs to be fixed here so I can send this to final review...

**Comment by Jiangwei-shi** [comment]
> Just waiting on bugs to be fixed here so I can send this to final review...

**Comment by Jiangwei-shi** [comment]
please check gh pr checkout 1183

**Comment by Jiangwei-shi** [comment]
since the development branch is updated. I created a new branch and fixed the bug. this branch can be closed and deleted. New PR is related to #1183

**Pull request closed without merging**
