### PR TITLE
Shiqing fix weekly summaries submission page formatting

### PR DESCRIPTION
**Pull request by yvonnep165**
# Description
Screenshot 2024-03-22 at 1 56 55 PM
Fix some formatting issues for the weekly summaries submission page

## Related PRS (if any):
This frontend PR is related to the latest backend.

## Main changes explained:
- The weekly summary lines up with the row below
- There's no extra line between the text 'total submitted' and the form below
- The text 'Enter...' aligns vertically with the buttons to the right
- The icon gets removed

## How to test:
1. check into current branch
2. do npm run start:local to run this PR locally
3. Clear site data/cache
4. log in as any user
5. go to dashboard→ Summary
6. verify the formatting is the same as the screenshot below

## Screenshots or videos of changes:
Screenshot 2024-03-22 at 2 30 38 PM

## Note:
n/a

### CODE REVIEW

**Review by Abi-Liu — DISMISSED** [review]
Looks good! Everything seems to be aligned properly.

Screenshot 2024-03-22 at 4 17 22 PM

**Review by abdel-lall — DISMISSED** [review]
LGTM!
Screenshot 2024-03-22 203007

**Comment by dhairya-mehta** [comment]
Hey Verified the PR ,everything works as expected!
image

**Review by linkhanthtel — DISMISSED** [review]
Looks good! Everything aligned properly!

Screenshot 2024-03-23 at 1 21 20 PM

**Review by sameersdeshpande — CHANGES_REQUESTED** [review]
Hello @yvonnep165 
I reviewed this PR and its looking as you have fixed. I have small recommendation that the letter P which is displaying can also be removed. Let me know if we need it there. Also I have marked one more box which I feel the box is overlapping. Let me know if these can be considered.

Screenshot 2024-03-23 at 9 10 33 PM

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and it is working as intended. Please refer the screenshot attached.

PR 2084

**Review by ImzIssa — DISMISSED** [review]
Hey, I have tested your PR and the changes you mentioned look good.
PR#2084

**Review by m-khalaf — DISMISSED** [review]
Looks good to me as well, I was able to verify all the changes you made :)
image

**Review by hbodgal — DISMISSED** [review]
looks great to me. Just remove the later P as others suggested.

image

**Review by lacnoskillz — COMMENTED** [review]
Hi @yvonnep165 
I pulled your changes and it looks as described however I noticed development seems to already have the summaries submission page formatted and only see the issue on the live app. Maybe another PR fixed the alignment or maybe I am doing something wrong. 

This is development

development

And this is your changes/branch

pr 2084 after

As you can see they are practically the same.


below is on the live app.

image

**Comment by MQChen211** [comment]
Hi, I tested your PR and it works as expected.

**Review by cvtqx — APPROVED** [review]
All the requested fixes have been implemented and the component looks neat. Great job!

Screen Shot 2024-04-12 at 5 49 27 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
