### PR TITLE
Vijay Anand -  Added unit test for  projectMembershipReducer file

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description
Added unit tests for the projectMembershipReducer. 

## Related PRS (if any):
No related PRs.

## Main changes explained:

- Added a new test file projectMembershipReducer.test.js under the tests directory.
- Test cases include:
- Returns the initial state when no state is provided.
  - Handles FETCH_MEMBERS_START by setting fetching to true and clearing the error.
  - Handles FETCH_MEMBERS_ERROR by updating the error field and setting fetched to true.
  - Handles RECEIVE_MEMBERS by populating the members array and stopping the fetching state.
  - Handles FIND_USERS_START, FIND_USERS_ERROR, and FOUND_USERS for searching users functionality.
  - Handles ADD_NEW_MEMBER by adding a new member to the members array.
  - Handles DELETE_MEMBER by removing the specified member from the members array.
  - Handles REMOVE_FOUND_USER by removing a user from the foundUsers array.

## How to test:

1. Check out the current branch.
2. Run npm install if necessary.
3. Execute npm test projectMembershipReducer.test.js.
4. Verify that all test cases pass without any errors.

## Screenshots or videos of changes:
Screenshot 2024-11-28 at 8 01 12 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by RashmiKY98 — APPROVED** [review]
No issues found. Verified the 7 scenarios. All test cases passed.
image

**Review by mianmiantea2019 — APPROVED** [review]
good work, all tests passed. 

image

**Review by NazaninHashemian — APPROVED** [review]
All the unit tests related to projectMembershipReducer were successful, indicating that the reducer behaves as expected for the various actions tested (like adding/removing members, handling errors, etc.).
The code changes from the pull request seem to be functioning correctly, and the tests are well-covered for this reducer.

**Comment by pallavithorat** [comment]
I have reviewed the PR and tested the changes locally , All test cases passed successfully without any errors.
Screenshot 2024-12-04 at 12 21 07 PM

**Review by anirudhsk2107 — APPROVED** [review]
All tests passed 

Screenshot 2024-12-05 122730

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (258)

**Comment by beblicarl** [comment]
All tests passed successfully and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
