### PR TITLE
Johny fix bug same folder task

### PR DESCRIPTION
**Pull request by johny4437**
# Description
In Tab Task in Dashboard, select a task. It was not possible to delete a task and it was also not possible to see the tasks that were in the same folder.

## Mainly changes explained:
Added an delete button in the `singleTask.js` file, now it is possible to delete a task.
in The` sameFolderTask.js` now is able to see all the tasks in the same folder.

When the Task is not in a folder( it means this task is the mother task) this screen shows:
Captura de Tela (258)

## How to test:
check into current branch
do `npm install` and `...` to run this PR locally
log as admin user
go to dashboard→ Tasks→ select a task that is in a folder

##Watch the video and see how to test:

https://user-images.githubusercontent.com/39320057/224459016-369aec71-38fe-4a15-8c64-b8c620788de0.mp4

### CODE REVIEW

**Review by crystalsong2021 — APPROVED** [review]
Nicely done. Have a good weekend.

**Comment by crystalsong2021** [comment]
@johny4437 , Great job implementing the logic for the sub task and deleting and updating. I tested on the UI and it works as intended for this PR.
https://user-images.githubusercontent.com/18197013/224463800-17a8125f-a3ae-4b85-be6a-b6efa862997e.mp4

**Review by Lucas-E — APPROVED** [review]
Hey Johny, just tested your PR and it works as intended, very good job! Have a great weekend!

https://user-images.githubusercontent.com/92558269/224495214-1ca63e07-80c3-4459-b3f9-b6f7f1c2c382.mp4

**Comment by nicollext** [comment]
Hey @johny4437! Tested and works as expected. 

https://user-images.githubusercontent.com/101591708/224515586-2831639a-1ff2-4434-81ec-d215401d78eb.MP4

**Review by nicollext — APPROVED** [review]

**Review by kangjay88 — APPROVED** [review]
Hi @johny4437, I have tested this PR and it works as expected. Code implementation looks good, great work!

https://user-images.githubusercontent.com/108297706/224526749-79ee1839-c017-497e-aff2-c1bac89f2e9c.mp4

**Comment by one-community** [comment]
Moving to final review, thank you all

**Review by rauleffting — APPROVED** [review]
Hi @johny4437! Your PR worked as intended.

https://user-images.githubusercontent.com/29555732/224751778-2cbd01c1-8b58-4c37-85b3-2853414ac3c2.mp4

Good job! The code is ok as well!

**Pull request merged**
