### PR TITLE
Anirudh user team project container unit test

### PR DESCRIPTION
**Pull request by belagaam**
# Description
Unit test case for UserTeamProjectContainer

## How to test:
1. check into current branch
2. do `npm install`
3. npm test UserTeamProjectContainer.test.js
4. verify that all test cases pass.

## Screenshots or videos of changes:

Screenshot 2024-03-09 at 12 57 49 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by mianmiantea2019** [comment]
All tests pass. 

image

**Comment by nnamdixobi** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/5d1f2226-e629-47d9-98f7-9f3311669856
Screenshot 2024-03-09 163810
Tests passed successfully and no errors were generated

**Review by YHX6 — APPROVED** [review]
All test cases passed!
Screenshot 2024-03-09 at 6 30 04 PM

**Review by dhairya-mehta — APPROVED** [review]
Hey Anirudh, tested and verified all test cases, good job!
image

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.

PR 2040

**Review by Abi-Liu — APPROVED** [review]
Looks good! All tests are passing.
Screenshot 2024-03-18 at 8 07 51 PM

**Review by ImzIssa — APPROVED** [review]
Hey, I've test your PR and all the test cases pass.

PR#2040

**Review by vikrambadhan — APPROVED** [review]
Hi, i tested your PR and all the test cases passed!

Week 30 - PR7

**Comment by aaryaneil** [comment]
Looks good to me, passed all the tests.
Screenshot 2024-03-29 at 6 05 58 PM

**Pull request closed without merging**
