### PR TITLE
Miguel - Changing Feature Count To Zero Deletes Badge

### PR DESCRIPTION
**Pull request by Cloid**
# Description
Fixes a bug when setting the badge count to 0 (either manually or using arrows) and not deleting it afterward.
Now when a badge count reaches 0, a delete modal automatically pops up.  
Clicking on "Yes, Delete" will delete the badge "locally" but the "Save Changes" button needs to be pressed in the main badge modal to save the changes on the deleted badge in the server. 
If a user clicks on the "Cancel" button on the delete modal or if the user presses the "X" button on the main badge modal (without saving), the badges will revert back to the last saved badge counts.

Original Bug:
Login as administrator > ‘Welcome, Username’ > View Profile > Featured Badges > Assign Badges → Assign any quantity of  Badges to the user, then go to ‘Selected Featured’ and change the count to zero. The Badges should disappear when the ‘count’ is set to zero, but they don’t.

## Related PRS (if any):
n/a

## Main changes explained:
- Updated deletion logic for badges to account for both having a badge count of 0 and pressing the "Delete" button on a badge.
- Fixed sortBadges to not use a "shallow copy" of the server object causing server-sided changes badges to be updated "locally" without going through the proper methods.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. Go to your own profile or a separate profile (volunteer, manager, etc.)
5. Assign badges if none exist
6. Select Featured > set badge count to 0 (either manually typing it to 0 or using arrow keys)
7. Press Yes, Delete on Modal and Save Changes
8. verify the functionality of badge deletion by pressing "Select Featured" button and ensuring the deleted badges are not there.

Test with the featured checkbox being checked on the badge as well.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/3566f375-69f6-4748-a962-c347845c9e52

## Note:
You need to click "Save Changes" on the badge modal to save deletion, otherwise, it will revert back to the original server-saved badge count.
Save_Changes_Button

### CODE REVIEW

**Comment by Bali2Mohit** [comment]
Hi @Cloid,
I have tested your PR, and it works perfectly.
Well done.

**Review by sahilpatel18 — APPROVED** [review]
Feature works as intended—good work! Attached is a screen recording showcasing the successful test.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/b7c35b1a-bff4-4126-a0e3-0ed424fad956

**Comment by palakgosalia** [comment]
Hey, I have tested your PR and everything works as intended. Great Work
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/955ac128-f8c7-465c-8f87-a56a8f21551b

**Review by luisarevalo21 — APPROVED** [review]
Hello @Cloid ,

I tested your PR and works as intended. Great work!
Attempting to delete a badge and setting the count to 0 a popup appears asking to confirm. 
If i say yes to delete and do not save changes the badge is still there. If i click save changes the badge is no longer there. 
Works for typing 0 and reducing the count using the arrow. 
Great work 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/c2846f2d-f436-4c8a-9d38-7c284e53eb82

**Review by Shuhua-L — APPROVED** [review]
Hi @Cloid, I’ve tested that the desired badge deletion flow works as intended for these scenarios:

- an admin deleting his/her badges
- an admin deleting a volunteer user’s badges
- an owner deleting his/her badges
- an owner deleting an admin user’s badges

Nice work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/b48bef4b-4197-4f5b-aa71-af127cfaa870


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/740968e8-d849-437c-a829-3f3cd8010af3

**Review by Sssky-18 — APPROVED** [review]
Hi @Cloid , I tested this PR using my own test account. I firstly assigned several badges to it, and use the arrow to change the count to 0. The warning text works as expected, and the corresponding badge is deleted successfully. After clearing all the badges, the text about no badge is displayed properly. So I approved this PR, and thank you for your great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/0a70a0c9-8343-4fd0-8546-42be402ff8c0

**Review by Shubhu0 — DISMISSED** [review]
Hi @Cloid tested your PR and it is working as intended. Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/484479b2-c8be-4c3c-ba7e-29a14056d025

**Review by sxiong5 — APPROVED** [review]
Hey @Cloid, the PR works perfectly! Nice job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/890cebfc-d551-456a-b0dc-da6de33e49b5

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by DavidC0126 — DISMISSED** [review]
Hi @Cloid I tested the PR and it works as described. Good job!


Uploading delete.mov…

**Review by KurtisIvey — APPROVED** [review]
Everything functions like it could and great implementation of the splice method to solve this issue. Your code is clean and self documenting. I like how you cleared up the plurality of variables as well in BadgeReport.jsx to accurately self document. Fantastic job!

Badges originally had
first badges


Set to 0 per instruction which gave delete notification modal:
set to 0


Badges reflected after setting to 0 and clicking delete from modal:
after setting to 0


Badge number reflected on user profile without refresh accurately:
reflects on user profile


Badges reflected properly once again on user profile with refresh:
persists refresh

**Pull request merged**
