### PR TITLE
Olga design projects summary view

### PR DESCRIPTION
**Pull request by cvtqx**
# Description
Design of BM dashboard displaying projects view page and its basic functionality. Here is the Figma prototype:

Screen Shot 2023-10-06 at 2 52 53 PM

## Main changes explained:
Created new components in BMDashboard/Projects, updated BMDashboard.jsx design and populated it with dummy data.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. go to localhost:3000 and login with any user
4. go to localhost:3000/bmdashboard and log in again with the same user
5. verify that you are taken to the building and inventory management view below:

Screen Shot 2023-10-06 at 2 57 38 PM

6. verify that:
 - projects in the select dropdown are the same as the projects displayed in the blue rectangles. 
 - when selecting a project from the dropdown menu and clicking on the button you are redirected to  a new page (localhost:3000/bmdashboard/projects/:projectId) (that page is blank for now except for a project id and a welcome message)
 - page is responsive to different screens

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. The page looks really good. I tested if the projects displayed are in the dropdown as well, visited the dashboard of the specific project, checked if the page was responsive.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/e49300ac-2161-449d-a223-4cb35c964536

**Review by JeffLi117 — APPROVED** [review]
Changes work as intended, as well as at different screen sizes. Great job!

The dropdown selection matches what I see on the screen:
image
image
image

When I select a project and then click the "Go to Project Dashboard" button, this is what I see (the URL at the top is as you intended as well):
image

Mobile view:
image

**Comment by wantingxu7** [comment]
Hi @cvtqx 
I followed your instruction, but when doing step 4, I cannot see any projects. Just like the follow screenshot:

**Review by yangfan2001 — DISMISSED** [review]
Hi, I have tested your PR, and it worked well. When I select a project and click the **Go To Project Dashboard** button, it redirects to the correct URL. Additionally, the web page functions properly across different screen sizes. Great job!
image
image
Display well in different screen size:
image

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works great to follow the steps.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/be051119-aa51-4e6c-85da-b6c9870b12f4

**Comment by cvtqx** [comment]
> Hi @cvtqx I followed your instruction, but when doing step 4, I cannot see any projects. Just like the follow screenshot: 

Hi @wantingxu7 ! have you tried clearing cache or hard refreshing the page? let me know if that solves the issue.

**Comment by Shreyj14** [comment]
Hi I tested the PR and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/a2fe1e30-2a69-4b31-8aa7-9d6879e047a8

**Review by Shreyj14 — DISMISSED** [review]

**Review by Sssky-18 — DISMISSED** [review]
Hi @cvtqx, I tested this PR, and it worked as expected! The project summary page was displayed properly with correct drop-down bar. Besides, when I select the items in the drop-down bar, the redirection to the corresponding page worked as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/dc7e6437-1c6e-4521-aeff-105578009c90

**Comment by Lin1404** [comment]
Hi @cvtqx  
I have tested your PR, and it worked great. It redirects to the correct URL for different project.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/f981c003-7b6d-423f-bed8-2955dbdbfe0a

**Review by Lin1404 — DISMISSED** [review]

**Review by TuanDinh140194 — APPROVED** [review]
The PR work as describe. After login to localhost:3000/bmdashboard. It shown 4 projects and project in the drop down have the same with project in the blue rectangular. After I click on the drop down menu project. The page has the project id in the url and the page also show the welcome message. I also test the responsive with other device. Everything work great !

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/62e0d046-ae91-419d-be87-f4be1bc12687

**Review by Shubhu0 — APPROVED** [review]
Hi @cvtqx reviewed the PR. Working as intended.

image

**Review by beblicarl — DISMISSED** [review]

**Review by lacnoskillz — APPROVED** [review]
Hello!
I pulled your changes and tested it on my end! Great work!
It seems all the dropdowns match and functions like you described
I tested on multiple view ports and they all seem to work well!
Galaxy fold view port dropdown is a little off center but thats just me being nit picky I have yet to meet a person with that phone

image

PR 1384
Also note you are still loggin to the console on line 103
image

**Review by DavidC0126 — APPROVED** [review]
Hi @cvtqx I tested your PR and it works as intended.

Uploading 1384.mov…

**Comment by Katherin4u** [comment]
Hello! I also ran into the same Issue when testing your PR, I cleared the cache and hard refreshed and it keeps showing me the same thing.

image

**Comment by cvtqx** [comment]
@lacnoskillz I've fixed the centering issue. and thanks for pointing out those console.logs. all have been removed.

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
noted changes through direct slack message

**Review by yi-lin-1234 — DISMISSED** [review]
Hello, I tested your PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/9214e207-a9a2-46ee-9ebf-ece3e6987790

**Review by KurtisIvey — APPROVED** [review]
Fantastic job. Everything is fully responsive and will set the foundation for any future alterations as this area of the app is expanded upon.

horizontal scrollbar removed successfully:
pr1384 horizontal scroll removed

abundance of text now properly expands the container that it's in without overflow & heading and bottom of paragraph element have equal margin/padding inside the container from top to bottom:
pr1384 handles overflow well

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
