### PR TITLE
Swathy - Hover effect on checkbox and radio

### PR DESCRIPTION
**Pull request by swathyjayaseelan**
# Description
When you hover over checkbox or radio it should show a pointer

## Related PRS (if any):
This is a front-end only change
…

## Main changes explained:
- Have added css to give the hover effect on checkbox and radio
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as any user
5. Go to Weekly Summary and hover over the checkbox and you should be able to see the pointer. This should work in any checkbox and radio button throughout the app. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/18b0e308-f6c9-47ae-9d98-85cc3280c3fb

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by linkhanthtel — CHANGES_REQUESTED** [review]
Nice work! I can see the pointer when I hover checkbox and radio button throughout the app. But, one thing, when I go to add intangible time entry, I can't see the pointer when I hover the tangible input field.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/51d9543a-ca9b-4c97-808c-f34a1fffe861

**Review by hbodgal — DISMISSED** [review]
Its working as needed.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/5f537472-c085-445c-ba9f-f7c2ac43e1f0

**Comment by swathyjayaseelan** [comment]
> Nice work! I can see the pointer when I hover checkbox and radio button throughout the app. But, one thing, when I go to add intangible time entry, I can't see the pointer when I hover the tangible input field.
> 
>  Screen.Recording.2024-03-30.at.8.23.56.PM.mov



> Nice work! I can see the pointer when I hover checkbox and radio button throughout the app. But, one thing, when I go to add intangible time entry, I can't see the pointer when I hover the tangible input field.
> 
>  Screen.Recording.2024-03-30.at.8.23.56.PM.mov

@linkhanthtel  Thank you for pointing it out. I have fixed it. Please check the changes. Please note that the cursor pointer will appear only when the checkbox is enabled and shows default cursor when it is disabled.

**Review by tdkent — APPROVED** [review]
Tested the checkboxes and hover effects on the Weekly Summary and Report pages and works as intended.

**Review by aaryaneil — APPROVED** [review]
The changes work as expected and the pointer appears when hovering on checkbox.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/0db51a95-bc29-4320-a0e4-9439a7424bbb

**Pull request merged**
