### PR TITLE
Shihao - Lint Fix Logout

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Lint Fix `src/component/Logout/**`

## Main changes explained:
- Change the code style according to ESLint and Prettier

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. go to dashboard and tried to logout
4. check the app works as normal and be able to logout
5. set up ESLint and Prettier in VSCode
6. check all files in `src/component/Logout/**` doesn't have errors

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/1f1c65be-9367-43a7-bfc3-bc3794bd1bc6

### CODE REVIEW

**Review by gabi-lima — APPROVED** [review]
Working as expected, no errors in my vscode. Well done!

image

**Review by Indujaks — APPROVED** [review]
No Errors seen while logging out, Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/50550a2e-ff61-4383-8c6d-9543980e619d

**Comment by iTvX** [comment]
Checked on my vocode, no error found. Great job!

image

**Review by GaryB93 — APPROVED** [review]
Logout functionality tested and no lint errors in code.

Screenshot 2023-08-31 at 4 20 42 PM

Screenshot 2023-08-31 at 4 21 40 PM

**Review by vinaykumarh — APPROVED** [review]
Reviewed the PR. Checked on edge and chrome for different user. Works as expected and no error on VSCode as well.

Review:
 
image

image

image

**Review by DavidC0126 — APPROVED** [review]
Hi @sxiong5 I tested this PR and it looks good to me.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/c07821de-8eee-4bd8-bfff-516cd2c99c4a

**Review by ss23046 — APPROVED** [review]
Hi @sxiong5 
Reviewed the PR, good job, no errors while logging out

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99052235/5c1a4bdb-f15c-4df7-a614-804bf3566571

**Review by ramyaram2092 — APPROVED** [review]
No issues with functionality and the code looks clean as well 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/839b580f-6488-45b9-bf90-ba6e028c497d


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/bcf0e748-c563-447f-b44b-67d76c6c1b31

**Review by EdwinLauM — APPROVED** [review]
Hey @sxiong5! Checked your code changes and also tested the changes! Logout works as expected and no errors!

Screen Shot 2023-09-01 at 12 05 47 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
