### PR TITLE
Kurtis - Fix default cursor appearing on timeEntryForm in the Notes section

### PR DESCRIPTION
**Pull request by KurtisIvey**
# Description
Cursor showed default when hovering over placeholder text within notes when the intangible/tangible time entry modal was open. Thought it was more intuitive and natural if the cursor showed default to indicate the notes entry could be typed within. It would show cursor:text once text was entered prior, but would be default if no text was entered at all.
Fixes # PRIORITY MEDIUM

## Related PRS (if any):
This frontend PR is related to the #886 frontend PR.
…

## Main changes explained:
When adding tangible or intangible time I noticed that when I hovered the cursor over the default placeholder text, the cursor was default. In order to have the box seem more active and accessible from the get go, I implemented a fix that would default the cursor type to "text" which would indicate the textbox in the "Notes" section would be accessible right away one you hovered over the placeholder text since that would be the natural pointer position to interact with it. 

through examining the tinyMCE docs, I saw that I could directly manipulate this through adding                     content_style: 'body { cursor: text !important; }' 
to the init section. Because of the !important, it maintains the highest specificity possible and overrides the default cursor styling that was being imposed by an unknown source. 

…

## How to test:
-I'm still new to Pull requests, so I wasn't sure on the process here. Because of that, you'll need to navigate to the repo that I forked. 
- clone the repo that I forked onto your local environment by using git clone
- do `npm install to update the node_modules
- afterwards, run npm run build 
- followed by npm run start to launch the app on local host to begin testing the modified development client
- log as admin user or volunteer user
- go to dashboard→ add intangible time entry →hover over placeholder text within notes section
- verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/825cba9c-07bf-4c81-8d61-ba2aad7f6f15

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/fb1a096e-e0f1-4431-9578-51650a4b2350

### CODE REVIEW

**Review by 20chen-7 — COMMENTED** [review]
This is another issue, which may be out of the scope when we click the 'More' options, like this
Screenshot 2023-06-06 at 3 54 55 PM
This will not exit properly.
Screenshot 2023-06-06 at 3 53 43 PM
Details like showed in the video.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/34aad36f-9b3c-4bde-92a5-58cf3e91f259

**Comment by KurtisIvey** [comment]
I believe you just click the 3 horizontal dots again to close that. They have a little grey background when its enabled. That seems to be a built into the actual app. Not sure how to bypass that in tinyMCE since I can't embed a useRef into that built in advanced text options modal to detect when it's being clicked/hovered outside of its area.

**Comment by 20chen-7** [comment]
> I believe you just click the 3 horizontal dots again to close that. They have a little grey background when its enabled. That seems to be a built into the actual app. Not sure how to bypass that in tinyMCE since I can't embed a useRef into that built in advanced text options modal to detect when it's being clicked/hovered outside of its area.

You are correct!

**Review by 20chen-7 — DISMISSED** [review]
Everything is great!
Screenshot 2023-06-06 at 4 13 56 PM

**Comment by AnishPandita** [comment]
Hi @KurtisIvey I tested your PR and it seems to be working as intended. The cursor transforms on hovering over the placeholder text. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/78909633-915b-409d-abb8-b4fc6681e822

**Review by OAkinbode — APPROVED** [review]
Hello Kurtis, The PR works fine. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/688a8b65-4669-49a9-9a67-9fe1767c6950

**Review by leonzh2k — CHANGES_REQUESTED** [review]
Everything looks good: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/2ec7cfd4-40f3-4359-a941-004adfa20fdf

I noticed the cursor only turns into a text cursor when hovering over the placeholder text, and remains a default cursor everywhere else in the textbox. I think it would be even better if the cursor would change to a text cursor anywhere in the textbox (Not sure if TinyMCE allows this though).

Also, I noticed you created a fork to make these changes. This caused me some confusion when trying to pull your changes to my local (I assumed you were working on a branch on the main repository so I did `git checkout -b kurtisivey_fix_cursor_bug_on_tangible_time origin/kurtisivey_fix_cursor_bug_on_tangible_time` which obviously doesn't work since it's on a separate repository entirely. 

From looking at previous PRs, it looks like most people's workflow is just creating a branch on the main repository. This way of working would certainly simplify the process of testing out the new changes for reviewers. Although, if you prefer to work on a fork I don't think anybody would be opposed to that, but the process of pulling these changes would be different, so I think clarifying that and explaining the process in the "How to test" section would be ideal.

**Comment by KurtisIvey** [comment]
@leonzh2k 

I did notice that as well. There's some underlying styling that is interferring with tinyMCE's built in styling. As it does exhibit all the behavior you're wanting under normal conditions as displayed on the tinyMCE website. I'm not sure what could be causing it either since I've tested the Editor without the form-control className applied to it and the same issue is still present. This fix only improves it slightly by forcing a cursor:text over the placeholder text than nothing at all.

Honestly, I was just scared of messing up the main branch which is why I forked it lol. I'll do that in the future though as it seems like that's the common practice. Thanks for letting me know, I'm still learning the pull request process. This is like my 3rd pull request ever

**Review by nathanah — APPROVED** [review]
Appears to work as intended.

**Comment by leonzh2k** [comment]
@KurtisIvey Interesting, I suppose that could be added as a bug. I'd still recommend adding instructions for fetching the changes in the fork for new reviewers. After that, I'm good to approve.

**Review by leonzh2k — APPROVED** [review]

**Comment by cvtqx** [comment]
Hi @KurtisIvey , there are instructions on how to create a PR in this doc: https://docs.google.com/document/d/1d-ZzDnb_OOXXUN49V-wExHpAgOFMYpe2se1SaziA7Xw/edit on page 11, perhaps this will help!  (I haven't created any yet, but I will be as cautious as you when I start :) )

**Comment by KurtisIvey** [comment]
@cvtqx I read that, but was still very cautious about possibly harming something. I figured with a fork there would be no way I'd screw anything up. Going to just branch and send in a pull request next time since that seems to be the norm

**Comment by Lucas-E** [comment]
Great job everyone! @KurtisIvey Please, resolve the conflicting files so I can move it to final review!

**Comment by KurtisIvey** [comment]
@Lucas-E 

I've resolved them. It's my first github resolve, so please let me know if I did anything incorrectly

**Comment by yufeiStella** [comment]
Hi Kurtis, it has an error when compiling.
Screen Shot 2023-06-09 at 22 40 51

**Comment by KurtisIvey** [comment]
> Hi Kurtis, it has an error when compiling. Screen Shot 2023-06-09 at 22 40 51

seems like I goofed it in clearing the merge conflicts. I'm waiting for assistance in slack, so I can ungoof it.

**Comment by yufeiStella** [comment]
@KurtisIvey Everything works fine now!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/a62804c2-f8aa-4fbf-ac0e-bce565e2751f

**Review by Chuehleo — APPROVED** [review]
Everything works as intended, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/f16da489-3e5c-461a-9449-61ff0f2b6936

**Review by 20chen-7 — APPROVED** [review]
I approved it, well done!

**Comment by rachnapandya** [comment]
Works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/9db1d3d9-fe95-4376-8c8f-fc2fcc720409

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this to final review!

**Review by leonzh2k — APPROVED** [review]

**Review by NidaZaki — APPROVED** [review]
The cursor looks good!

**Review by nathanah — APPROVED** [review]

**Comment by one-community** [comment]
I'd like to merge this but I'm not familiar with this: 
image

Can anyone help me understand that and then resolve it?

**Comment by one-community** [comment]
Nevermind, I figured it out... Kurtis was somehow not added to the repositories yet. Merging!

**Pull request merged**
