### PR TITLE
Ramya unit test: Userprofile/UserLinks

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit tests for src/components/UserProfile/UserLinks

## Main changes explained:
-  New file
      - **UserLinks.test.js** : unit test cases 
-  Existing file
      - **UserLinks**  : Added  test id to the objects for unit testing 
####  Test cases 
image

## How to test:
1. check into current branch
2. do npm test UserLinks.test.jsx
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Comment by Cavein254** [comment]
@ramyaram2092 ran test for `UserLinks.test.js` and all the test pass
Screenshot from 2024-01-12 09-57-05

**Review by bajajtushar094 — APPROVED** [review]
@ramyaram2092 all the test cases passed. Thanks 
Screenshot 2024-01-12 at 21 48 36

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Review by bienzguoa — APPROVED** [review]
Very comprehensive test! It covers a variety of scenarios and all rendered correctly. All test cases passed!
Screenshot 2024-01-12 at 8 45 48 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2024-01-12 at 9 52 18 PM

**Comment by belagaam** [comment]
All test Case passed Successfully.

Ramya Unit test - UserProfile

**Pull request merged**
