### PR TITLE
Chris_teamMemberTask_taskButton_unittest

### PR DESCRIPTION
**Pull request by chrischenlixing**
# Description
This is a unit test for the src/components/TeamMemberTasks/TaskButton.jsx

## Main changes explained:
- Ensuring that the TaskButton component appears correctly on the screen when provided with a task object.
- Verifying that clicking the button triggers a series of actions to update the task status to 'Complete', delete the task, and fetch necessary date.
- Checking that the button is only rendered when the task status is not 'Complete', ensuring that completed tasks do not show the button.

## How to test:
1. check into current branch
2. do `npm test src/components/TeamMemberTasks/__tests__/TaskButton.test.js`
3. check if all the test cases pass as expected without any warnings or errors

## Screenshots or videos of changes:
Screenshot 2024-05-21 at 5 32 50 PM

### CODE REVIEW

**Review by peter6866 — APPROVED** [review]
All test cases passed!
image

**Review by cecilia-uu — APPROVED** [review]
All tests have passed.
截屏2024-05-22 上午9 30 09

**Review by Sandhya1236 — APPROVED** [review]
All test cases passed. Good Job!
image

**Review by KyreneAF — APPROVED** [review]
- The Tests all pass!
Screenshot 2024-05-22 at 2 22 58 PM

**Comment by beblicarl** [comment]
The code is great and all test cases were catered for

image

**Review by beblicarl — APPROVED** [review]

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected! Nice work!

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.

PR 2273

**Review by hbodgal — APPROVED** [review]
image

All test passed!

**Review by curiousfancier — APPROVED** [review]
All test cases working as expected!
image

**Review by Wenboooooo — APPROVED** [review]
Looks good to me all tests have passed!

**Pull request merged**
