### PR TITLE
Vijayanand UI fix on report when searching projects/people/teams table on narrow screen

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description
Screenshot 2024-07-17 at 12 10 44 PMFixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch.
…

## Main changes explained:
When the user click on Projects/People/Teams button the page will automatically scroll to the respective table component on narrow screens(<900)
When user start typing in the search input box after few seconds it will automatically scroll to the search result on narrow screens(<900)
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ Reports → Reports
6. verify if the screen automatically scrolls and displays the respective tables when Projects/People/Teams button is clicked on narrow screens(less than 900px)
7. verify if the screen automatically scrolls and displays the search result after a few seconds once the user stops typing in the search input box on narrow screens(less than 900px)

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/76ca1b03-1104-4b64-8410-2fc75e6f5921

## Note:
This change will not have any effect on larger screens(greater than 900px)

### CODE REVIEW

**Review by kdaga81 — CHANGES_REQUESTED** [review]
https://github.com/user-attachments/assets/36b0c4d0-babd-4bc1-b43e-c47a90b5a219


I have verified all the expected changes and everything is working as intended. However, I have a suggestion regarding the search field functionality. It would be more user-friendly to have a search button that, when clicked, scrolls directly to the table. In the current setup, if a user makes a typo or a pause, they have to scroll back up to the search field, which can be inconvenient.

**Comment by nikethaanand** [comment]
All the changes are working as epxecte, able to scroll and search. Sometimes the top navbar is not showing up on my screen, can you check that once.
https://github.com/user-attachments/assets/6598573a-06ff-4e36-9e7f-f5ac5d9fc5b4

**Review by Chetan0606 — DISMISSED** [review]
Checked a

https://github.com/user-attachments/assets/ac5d1540-782e-4c40-a41f-980de72d0aa9

s per given instructions and everything seems good.

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and it scrolls automatically in both the scenarios.

https://github.com/user-attachments/assets/f3ce095d-c752-4e86-b1a6-6b7e77109f5e

**Comment by vijay10pk** [comment]
> Screen.Recording.2024-07-19.at.8.30.21.PM.mov 
> I have verified all the expected changes and everything is working as intended. However, I have a suggestion regarding the search field functionality. It would be more user-friendly to have a search button that, when clicked, scrolls directly to the table. In the current setup, if a user makes a typo or a pause, they have to scroll back up to the search field, which can be inconvenient.

@kdaga81 Thank you for your suggestion. Even I thought the same, but as per the requirement it is a UI change not a functional change. Your suggestion is out of scope for this requirement.

**Review by Gauravmg6 — APPROVED** [review]
https://github.com/user-attachments/assets/86cc7a20-5822-4599-b23c-e61baa60bc7f
Everything works as intended. One suggestion would be that the search results are displayed involuntarily after each pause. It would be better if there was an option to wait for a button click to scroll to the results.

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey Vijay,
I have just reviewed your PR. Your code is working as expected, but I would like to suggest an improvement. As of now, the scroll functionality is invoked on every keystroke change, which might not provide a good user experience. It would be better if the scroll functionality is performed only when clicking the search button or by implementing a timeout for every few seconds.
Thank you,
Pranay

**Comment by vijay10pk** [comment]
> Hey Vijay, I have just reviewed your PR. Your code is working as expected, but I would like to suggest an improvement. As of now, the scroll functionality is invoked on every keystroke change, which might not provide a good user experience. It would be better if the scroll functionality is performed only when clicking the search button or by implementing a timeout for every few seconds. Thank you, Pranay

@Pranay-ai Thank you for your suggestion. As you can see in the requirement screenshot above I can't change the functionality of this component. So, I made it scroll down to search results after a 5-second gap when the user stops typing.

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/c8b6f8e8-1739-4099-a32a-a4b8391b64c5

**Comment by one-community** [comment]
> Hey Vijay, I have just reviewed your PR. Your code is working as expected, but I would like to suggest an improvement. As of now, the scroll functionality is invoked on every keystroke change, which might not provide a good user experience. It would be better if the scroll functionality is performed only when clicking the search button or by implementing a timeout for every few seconds. Thank you, Pranay

I'd like to keep it every keystroke because this will mostly be used on computers.

**Review by preethamdnr — APPROVED** [review]
Hello Vijay,
This PR is working as expected.

https://github.com/user-attachments/assets/d1a660cc-1517-4212-8a6f-5afbbbd8afa5

**Review by Lemonnycodes — DISMISSED** [review]
Hi,
I have tested the changes introduced in this PR. 

- The screen scrolls automatically to the respective tables when clicking the Projects, People, or Teams buttons.
- After typing in the search box, the screen correctly scrolls to display the results.
- The feature works , with no issues encountered during testing. 

Screenshots:
PR 2473
PR 2473 (2)

**Comment by FayeLV** [comment]
Hi,
Good job!
- On narrow screens (less than 900px), I checked that the screen scrolls to show the correct tables when the Projects/People/Teams button is clicked and scrolls to show search results a few seconds after typing stops.

Snipaste_2024-08-29_21-27-47
Snipaste_2024-08-29_21-30-16
Snipaste_2024-08-29_21-30-38
Snipaste_2024-08-29_21-33-48
Snipaste_2024-08-29_21-34-15

**Review by FayeLV — APPROVED** [review]

**Review by vedantg24 — DISMISSED** [review]
Tested the PR, and the changes are working as expected. The screen automatically scrolls and displays the respective tables when Projects/People/Teams button is clicked. Also, the screen automatically scrolls and displays the search results after the user stops typing in the search input box.

https://github.com/user-attachments/assets/a64a9393-15ea-46be-aa85-b8828185858b

**Review by ashayk9 — APPROVED** [review]

**Review by ashayk9 — DISMISSED** [review]
I have tested the changes introduced in this PR and confirmed that the screen automatically scrolls to the respective sections when clicking the Projects, People, or Teams buttons. Additionally, after typing in the search box, the screen correctly scrolls to display the search results.


https://github.com/user-attachments/assets/1235bf42-f28c-4ba8-8bbc-60224d40c514




Uploading Screen Recording 2024-09-04 at 10.06.44 AM.mov…

**Comment by vijay10pk** [comment]
> Screen.Recording.2024-07-19.at.8.30.21.PM.mov 
> I have verified all the expected changes and everything is working as intended. However, I have a suggestion regarding the search field functionality. It would be more user-friendly to have a search button that, when clicked, scrolls directly to the table. In the current setup, if a user makes a typo or a pause, they have to scroll back up to the search field, which can be inconvenient.

@kdaga81 adding a search button will change the functionality on other larger screens. As mentioned in the requirement I made sure to keep the functionality in larger screens. I have increased the scroll timeout. Kindly please re-review the PR.

**Review by Shreyav2000 — APPROVED** [review]
Hi,

I tested this PR and can confirm that everything works as intended. The page correctly scrolls to the respective table components when clicking on the Projects/People/Teams buttons, and the automatic scroll to search results also functions well on narrow screens (<900px). Great Work!

Thanks!


https://github.com/user-attachments/assets/878bb41c-8f18-4085-9469-c159dfc5ef16

**Review by swaroop-2007 — APPROVED** [review]
@vijay10pk 
I reviewed your changes and checked the code! Everything is working as expected. Great job. 

https://github.com/user-attachments/assets/f53415c4-55af-4523-af1b-ebec00a253b9

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.

image

Thank You

**Review by crystallow1168 — CHANGES_REQUESTED** [review]
Hello @vijay10pk 

The changes are working as expected and here are my findings:
✅ verify if the screen automatically scrolls and displays the respective tables when Projects/People/Teams button is clicked on narrow screens(less than 900px)
✅ verify if the screen automatically scrolls and displays the search result after a few seconds once the user stops typing in the search input box on narrow screens(less than 900px)

https://github.com/user-attachments/assets/d15b3b24-a5ba-448a-82c4-46d61609613c


---
Observations:
❗️When navigating from Dashboard to the Reports page, the view doesn't start on the top of the page

https://github.com/user-attachments/assets/ba060d6d-7693-4255-8980-f673a2dd136d



❗️ After clicking on either Projects/People/Teams button, the top navigation bar disappears

https://github.com/user-attachments/assets/84a48b79-7b12-4c31-bec4-4ebf9e67d44c

**Review by SnelPatare — APPROVED** [review]
The changes are working as expected. 
image

**Review by SFA23SCM35V — DISMISSED** [review]
I tested that when the user clicks on the Projects, People, or Teams button, the page automatically scrolls to the respective table component on narrow screens (less than 900px). Additionally, when the user starts typing in the search input box, the page automatically scrolls to the search result after a few seconds on narrow screens.

**Review by neeharikakoniki — APPROVED** [review]
The functionality for the Projects, People, and Teams buttons on narrow screens (less than 900px) worked flawlessly. When clicked, the screen automatically scrolled to the respective tables.
The search functionality also performed  well. After typing in the search input box, the results displayed automatically after a brief pause, reflecting relevant information promptly.
https://github.com/user-attachments/assets/42edd9b8-4241-4f9b-95dc-f0290fd45ae2

**Review by nevatiarishabh — APPROVED** [review]
I have tested the PR. Everything works as expected. The scroll feature is working automatically and properly as per the description.

https://github.com/user-attachments/assets/4dbb1487-7b2a-4ef7-9cd6-9965a0b07572

**Review by lcohen730 — APPROVED** [review]
Screen automatically scrolls and displays respective tables when Projects/People/Teams buttons are clicked on narrow screens(less than 900px) and a few seconds after typing stops in input


https://github.com/user-attachments/assets/f7b429af-2ea3-4876-b256-d0d68f6944e0

**Review by mrinalini-raghavendran19 — APPROVED** [review]
Looks good to me! The PR works as expected in a narrow screen and automatically scrolls to the table and filters appropriately according to user action.

Find the recording below to verify:

Uploading Screen Recording 2024-09-25 at 4.48.22 PM.mov…

**Review by khushijain03 — DISMISSED** [review]
Hi @vijay10pk,

I tested this PR and can confirm that it works as expected. Upon clicking the Projects/People/Teams buttons, the page appropriately scrolls to the corresponding table components. Additionally, the automatic scroll to search results works effectively on narrow screens as well!



https://github.com/user-attachments/assets/c03cfde3-4a26-4717-a4ea-b69483ce711e

**Review by Muzammil603 — APPROVED** [review]
image
image
working as expected

**Comment by vijay10pk** [comment]
> Hello @vijay10pk
> 
> The changes are working as expected and here are my findings: ✅ verify if the screen automatically scrolls and displays the respective tables when Projects/People/Teams button is clicked on narrow screens(less than 900px) ✅ verify if the screen automatically scrolls and displays the search result after a few seconds once the user stops typing in the search input box on narrow screens(less than 900px)
> 
>  PR.2473.mp4 
> Observations: ❗️When navigating from Dashboard to the Reports page, the view doesn't start on the top of the page
> 
>  HGN.APP.mp4 
> ❗️ After clicking on either Projects/People/Teams button, the top navigation bar disappears
> 
>  Top.nav.bar.missing.mp4

Hello @crystallow1168, Thank you for your observation. Addressing your observation#1, which was the existing behaviour as per the requirement the existing behaviour shouldn't be affecting desktop screens. So by default when the page load input box becomes active.
Observation#2: This out of the task scope. Kindly add it as a separate bug in the bug docs.

**Review by zhiminV — APPROVED** [review]
I login as admin user, and tested the following function work

1. screen automatically scrolls and displays the respective tables 
2. the screen automatically scrolls and displays the search result after stops typing in the search input box 



https://github.com/user-attachments/assets/97e719e6-7db5-489e-b246-55f8927bfd2e

**Review by SupriyaSudini — APPROVED** [review]
I have tested the PR and confirmed that everything is working as expected, even on smaller screens.


https://github.com/user-attachments/assets/8d6a7f2f-02dc-461b-bc8b-beca66e26ce6

**Pull request merged**
