### PR TITLE
Vijay anand replace badge assignment search function

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description

Screenshot 2024-07-31 at 1 06 35 PM

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch in backend.
…

## Main changes explained:
- Replaced the search functionality in the badge assignment and displayed the search result in a table with radio button for selecting the name the user wants to assign a badge.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Other Links→ Badge Management
6. verify search functionality is working if the user enters the name(either first or last name)
7. verify the user is able to select a name by clicking on the radio button and proceed to assigning badge.
8. Verify that the assign button is enabled only when a name is typed in the input field.
9. verify the responsiveness of the search box and table for different screen size.
10. verify all the above changes in dark mode.

## Screenshots or videos of changes:
[Demo Video Link](https://www.loom.com/share/4cc106a0f46b4685a79a3b37520003b1?sid=cdc56187-81c7-4454-b3e3-e19a90aed3c1)

## Note:
only the search and table are related to this requirement.

### CODE REVIEW

**Review by Pranay-ai — DISMISSED** [review]
Hey @vijay10pk The PR is Working as expected Please find the screenshots for reference.
Thank You

**Review by Aishwarya0898 — APPROVED** [review]
Hey Vijay, 
The PR is working as expected, checked in Dark Mode as well. Here are the references.
PRReview2_1
PRReview2_2
PRReview2_3

**Review by DiyaWadhwani — DISMISSED** [review]
Hi Vijay,
Went over your changes and the search functionality works expected.
Thank you for your work. I have dropped a screenshot of the visible UI below.

ss

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and verified the search functionality for first and last name. The result displayed in table with radio button user selection. The functionality works in dark mode as well. Great Work!
#PR2539
#PR2539_2

**Review by manikittu810 — APPROVED** [review]
Hello @vijay10pk 
I have verified the mentioned steps and everything is working as mentioned . Responsiveness is also good with different screen sizes.Below are the attached screenshots.



Screenshot 2024-08-08 at 3 59 27 PM
Screenshot 2024-08-08 at 3 59 58 PM
Screenshot 2024-08-08 at 4 00 51 PM

Thank you.

**Review by vishavk1992 — DISMISSED** [review]
i have tested this PR successfully and everything is working as mentioned. 

Screenshot 2024-08-09 162058
Screenshot 2024-08-09 162120

**Review by jinxyou — DISMISSED** [review]
The changes seems good. The radio works fine, and the selection of dropdown list works fine, in both light mode and dark mode. 
Screenshot 2024-08-09 172440
Screenshot 2024-08-09 172446
Screenshot 2024-08-09 172456
Screenshot 2024-08-09 172512

**Review by SatyashanthiT — DISMISSED** [review]
I verified that the search functionality in badge assignment works correctly, allowing users to search by first or last name and select a name using a radio button. The table and search box are responsive across different screen sizes, and the changes also function well in dark mode. I observed the video provided for additional reference, and everything appears to be working as expected. 


https://github.com/user-attachments/assets/5a2ce4d4-e811-405f-ba67-0920687a963f

**Review by Gauravmg6 — APPROVED** [review]
I checked the functionality for different screen widths and it all works fine. 

Screenshot 2024-08-11 014837

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected. Great work!

https://github.com/user-attachments/assets/4cc458ec-37f4-4c42-bc20-e7effd12d201

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and I was able to search for user and assign badge. Tested for light and dark mode both.
Screenshot 2024-08-11 at 8 33 12 PM
Screenshot 2024-08-11 at 8 33 27 PM
Screenshot 2024-08-11 at 8 33 31 PM
Screenshot 2024-08-11 at 8 34 34 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/88f7cabd-fc4f-4814-a928-7b12b3e3ce84

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
