### PR TITLE
Shubhankar added missing box shadow style to buttons

### PR DESCRIPTION
**Pull request by shubhankarval**
# Description
(PRIORITY LOW) Jae: Add Profile Page missing box Shadow Style in User Profile Component

## Related PRS (if any):
…

## Main changes explained:
- Update UserProfile.jsx with box styles.
- Update BadgeReport.jsx with box styles.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner user
4. go to User Profile. 
5. Verify the following:
    - View the profile in mobile view and check if the modal buttons (below the badge section) have box shadow. 
    - Go to a user's profile who has an assigned badge, click on `Select Featured` to view Full Badge History View and check if the Delete button has a box shadow.
    -  Go to a user's profile and check whether the `Generate Summary Intro` button has a box shadow. 
## Screenshots or videos of changes:
Screenshot 2023-11-11 114037
Screenshot 2023-11-11 115639
Screenshot 2023-11-11 115817

## Note:
Please check other buttons in User Profile page which may require box shadow.
Disregard the change in Image.test.jsx.

### CODE REVIEW

**Review by Bali2Mohit — COMMENTED** [review]
Hi @shubhankarval , I am trying to fetch the changes in local, but getting issue in pulling the changes. It gives error for image.test.jsx. 
Can you provide a solution to that.
Screenshot 2023-11-11 at 23 15 01

**Comment by shubhankarval** [comment]
Hey @Bali2Mohit, I was able to remove the Image.test.jsx file from this PR which was accidentally modified by my editor. Please check now.

**Review by sahilpatel18 — APPROVED** [review]
In the mobile view, the modal buttons have a box shadow, and on the standard desktop view, the delete buttons also feature a box shadow as specified. Great work!

Mobile view:
Screenshot 2023-11-11 at 8 34 56 PM

Desktop View delete buttons: 
Screenshot 2023-11-11 at 8 35 09 PM

**Review by wantingxu7 — APPROVED** [review]
I've checked the buttons in description, the shadow LGTM. Good work.

**Comment by Bali2Mohit** [comment]
> Hey @Bali2Mohit, I was able to remove the Image.test.jsx file from this PR which was accidentally modified by my editor. Please check now.

Hi @shubhankarval , I have tested the PR again. This works perfectly now. Thanks for updating. Great work
Screenshot 2023-11-14 at 17 41 39
Screenshot 2023-11-14 at 17 45 13

**Review by Bali2Mohit — APPROVED** [review]

**Review by Jiyuanxia — APPROVED** [review]
Hi @shubhankarval , I have reviewed your pull request and tested it. It works as you intended. Boxes have proper shadow now. Great work!
Screenshot 2023-11-16 191845
Screenshot 2023-11-16 192028
Screenshot 2023-11-16 192148

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions.
The testing details as below:
1. Check if the modal buttons have box shadow.
2. In the Full Badge History View, check if the Delete button has a box shadow.
3. Check if the Generate Summary Intro button has a box shadow.
During my testing, all of them have box shadow. 
Screenshot 2023-11-18 at 11 21 16 PM
Screenshot 2023-11-18 at 11 21 39 PM
Screenshot 2023-11-18 at 11 22 03 PM

**Review by nathanah — APPROVED** [review]
LGTM

**Comment by beblicarl** [comment]
This functionality works as intended

image

image

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by AnishPandita** [comment]
Hey, I checked the Pr and all the UI changes look good.
1. The modal button shadows look good in the mobile view.
Screenshot 2023-12-02 at 2 06 27 AM

2. The delete button in the full badge history view has a shadow too.
Screenshot 2023-12-02 at 2 07 42 AM

3.  The generate summary info button has shadow as well.
Screenshot 2023-12-02 at 2 07 02 AM

**Pull request merged**
