### PR TITLE
Logeshwari  - fix for team management page struck on team edit

### PR DESCRIPTION
**Pull request by Logeshwari-Renu**
# Description
Page struck Task

## Related PRS (if any):
This frontend PR is related to the backend [#PR1087](https://github.com/OneCommunityGlobal/HGNRest/pull/1087#issue-2492617032).

## Main changes explained:
- Handled the error for Unauthorized error message in the Team update API and edited Toaster message for user to display the message. 

## How to test:
1. check into current branch
2. do `npm install`, `npm run start:local` to run this PR locally
3. Clear site data/cache
4. Log as Any user.
5. Go to Other Links -> Teams.
6. Select the "Edit" option and edit the Name of the Team and click "Ok".
7. "Team Updated successfully" toaster message should be displayed.
8. Verify the team names can be edited and the page is not struck anytime during editing and saving.
 Note: If the user is not having permission to edit, then "You are not authorized to edit team code." will be displayed. 
 Go to "Other Links" -> "Permission Management" -> "Manage User Permission" to provide Team Edit Permission for specific user .

## Screenshots or videos of changes:

Before Changes:
https://github.com/user-attachments/assets/c82b9427-2570-45de-aa46-1f56633db845

After Changes:
https://github.com/user-attachments/assets/3df2eaa6-2dc8-43c7-8826-16f564d32782

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Hello @Logeshwari-Renu 
Followed the mentioned steps and everything is working as mentioned.


https://github.com/user-attachments/assets/9f2f016d-7f63-49f0-9aa0-b502f06c1604


Thank you.

**Review by RishithaMamidala — CHANGES_REQUESTED** [review]
@Logeshwari-Renu 
While editing the team name, the page no longer freezes, but the table does not automatically update after the edit. A refresh is required to see the changes.
Can the table update immediately after the team name is edited.

https://github.com/user-attachments/assets/e61eb02f-f719-4bb1-aec8-593c96e45e37

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected. While editing the team name, the page no longer freezes. However, the table does not automatically update, a refresh is required to see the updates.


https://github.com/user-attachments/assets/8131639d-dbab-49f0-935c-6da273796302

Thank You

**Review by Jingyii800 — APPROVED** [review]
I have tested this feature and verified the team names can be edited and the page is not struck anytime during editing and saving.

https://github.com/user-attachments/assets/bf35784b-260d-4f37-8ade-7bd370845182

**Review by SnelPatare — APPROVED** [review]
I have tested the changes and it is working as expected I was able to edit team names using owner profile. 
Please find screenshots below. 
image

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.

https://github.com/user-attachments/assets/1d3c6358-606a-4dcb-a094-9e429ca6f89e

**Review by Pranay-ai — APPROVED** [review]
Hey @Logeshwari-Renu 
The PR is working as expected, here is the screenshot for reference
image

**Comment by sri0606** [comment]
hello @Logeshwari-Renu , I tried to test the changes you made but ran into some issues:

* I got "You are not authorized to edit team code". (i'm using admin account)
* I checked to see if I have necessary permissions which I did, in fact I have all permissions.
* I made sure I'm on right brach for both frontend and backend.

most likely the issue is on my end as it seemed to work for others but not sure what it is. Any help would be appreciated!

https://github.com/user-attachments/assets/af8ade5c-6c40-478d-81ef-13ce1347478a


Branches:

image
image

**Review by SMitta11 — APPROVED** [review]
Tested this PR and it is working as expected, message  getting displayed on changing the team.
Screenshot:

**Review by yashwanth170 — APPROVED** [review]
The page needs to be reloaded to view the updated details, but aside from that, everything is working as expected.
edit_team_1
edit_team_2

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected and the changes are being saved prompt is showing and then disappearing. This could be a unrelated issue but the team name is not changing on its own after editing. Below are the screenshots for reference:
PR _Review_2627

**Review by CillianRen — APPROVED** [review]
image

It works well now, but I still need to refresh the page to see the changes.

**Review by ddshah878 — APPROVED** [review]
The page no longer freezes when editing the team name, but the table doesn't update automatically. A refresh is required to see the changes.


https://github.com/user-attachments/assets/cbfd0cfa-5f40-4b3a-97f7-b085b3cf6daf

**Comment by panchalvatneu** [comment]
Tested this PR and I have the following observations -
1. Once the new team name is changed nothing happens, however the page does not get stuck anymore and you get a green notification saying the name is changed.
2. But a refresh is needed to see the name change and the team edited jumps up to the top of the table.

Is there a way we can update the table automatically? and also maintain the order of the table?

**Review by Sudershhh — APPROVED** [review]
The above changes work as expected. I can see the toast notification and there seems to be no lag while that happens. 

PR

**Review by mohangadde1 — APPROVED** [review]
https://github.com/user-attachments/assets/1c82c899-7b29-4d1e-a2ae-352549654a15
working fine but changes are not appearing until I refresh the page.

**Review by mohangadde1 — APPROVED** [review]

**Review by sam19981 — CHANGES_REQUESTED** [review]
Hi @Logeshwari-Renu ,
Screenshot 2024-09-07 at 2 57 56 PM

I tried testing the changes, but I’m unable to make any edits to the team, even though I’m an administrator. I’ve attached a video for reference. Please take a look. Thank you!

https://github.com/user-attachments/assets/3ef953fc-86bb-4be6-b4c2-ae4b81cbb2c1

**Comment by one-community** [comment]
Thank you all, merging!  Listed requested change as a new bug

**Pull request merged**
