### PR TITLE
Nahiyan_Fix Basic Information tab UI (Tablet View)

### PR DESCRIPTION
**Pull request by Nahiyan-16**
[](url)# Description
The Basic Information tab UI seems to break from the viewport of (768px - 1024px)
Screenshot 2024-03-19 141434

## Related PRS (if any):
This frontend PR is related to the DEV backend

## Main changes explained:
- Added conditions to the column props so width changes for the desktop view

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as Owner and Volunteer user
5. go to dashboard→ User Profile → Basic Information Tab
6. verify that when making the viewport smaller than 1024px, the UI appears to be normal
7. verify the mobile and desktop view as well by adjusting the viewport width
8. Use both an owner account and a volunteer account to test this as there are edit and non edit versions of these fields

## Screenshots or videos of changes:
Before: 
Screenshot 2024-03-21 132017

After:
Screenshot 2024-03-21 131956

### CODE REVIEW

**Review by Abi-Liu — APPROVED** [review]
Changes look great! The inputs now span across the width of the modal and the toggle inputs are now no longer spilling out of the modal as well.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/17269e2d-7484-4ffa-806e-a533d20e2f2a

**Review by linkhanthtel — CHANGES_REQUESTED** [review]
When making the viewport smaller than 1024px, the UI break as the screenshot attached.

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and it works as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/5ed64c29-4808-4d85-8bb3-c81019f471aa

**Comment by Nahiyan-16** [comment]
> When making the viewport smaller than 1024px, the UI break as the screenshot attached.
> 
> 

Hi @linkhanthtel, can you check again please? It seems to be fixed for other people.

**Review by linkhanthtel — APPROVED** [review]
I checked again! It look good! Kindly see the attached screenshot!

#2079re

**Review by SanketKaware — APPROVED** [review]
This change looks good to me.  

I have tested this change for Administrator, Volunteer, and Owner type accounts. Didn't face any issues.

Please see my video review for reference -
**Administrator**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/924e25db-4a39-46c8-89e2-5f80b1600efd


**Owner**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/fb17eff7-bed7-40b2-8c17-30bea193d07f



**Volunteer**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/f2caaea2-0264-4fe7-99f7-700a07194521

**Review by ImzIssa — APPROVED** [review]
Hey, I've reviewed your work and your changes look great. Nice Work.
PR 2079
PR 2079 (2)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
