### PR TITLE
Roberto fix removing user from profile

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
When trying to remove a user from a team within's the user's profile page it doesn't update the database only state. Additionally when you go to a team's member list and either add or remove a user from there then visit that user's profile to see the update it will have a very delayed response.

Screenshot 2023-09-28 at 5 14 05 PM
Screenshot 2023-09-28 at 5 13 57 PM

## Related PRS (if any):
This frontend PR is related to the [#550](https://github.com/OneCommunityGlobal/HGNRest/pull/550) backend PR.
…

## Main changes explained:
- Imported and used deleteTeamMember function to TeamsTab.jsx to ping the backend and update the database.
- Added a boolean variable to UserProfile.jsx to indicate when the save button is clicked to execute the function
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ Other Links→ Teams→ Select A Team→ Members→ Add a User to Team→ Visit that user's profile
5. verify that the user's profile is updated immediately after a refresh
6. User's profile→ Teams section→ Remove from Team→ Save Changes→ Visit that Team
7. verify that removing the user from a team from within a user's profile actually updates the team member list
8. repeat step 4 and 5 + also remove a user from team member list and make sure it updates user profile immediately

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/7f044ee4-62ed-434d-bea0-46801f1565de

## Note:
Adding user to a Team from user's profile page won't actually update the Team's member list

### CODE REVIEW

**Review by Bhagyashree444 — CHANGES_REQUESTED** [review]
Excellent job, Roberto! The 'add/delete user from a team' feature functions smoothly, seamlessly updating user profiles and team lists for Manager and volunteer roles. 

However, I've noticed that these changes don't update immediately for users with the Admin role. 
Additionally, users aren't visible on the Team Members list for those with the Mentor and Tester roles.

**Review by Shiwani99 — CHANGES_REQUESTED** [review]
Hi,
I tested your PR. As mentioned before, there is a delayed response in the add team members tab when adding and deleting team members. I tried to check in user profile too and it does get added to the team and deleted from it when the user adds or deletes a team member in teams tab, but there is a delayed response in the team tab when adding or deleting users.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/784e8808-457f-43d1-a10e-3e7f47165a51

**Review by JeffLi117 — CHANGES_REQUESTED** [review]
Most changes work as intended (when testing on Admin account) - however, the biggest "issue" I ran into when testing this PR was being unable to see a new member being added to a team until I closed that pop-out window and then re-opened it. 

About to select Jefftest Litest user: 
image

Immediately after selecting said user and clicking "Add": 
image

After closing the pop-up window, and then re-opening it: 
image

Checking the user's profile after having added them (using a different user, JeffreyVol): 
image

The resulting message when I remove the user from the team (on the user profile page):
image

I can also remove the user from the team within the pop-up window and confirm it so:
image

This seems very similar to a recent PR (#1347 which was resolved when switched to new branch #1352). I'm unsure how simple/complex it was to fix the issue, but perhaps you can ask @Shreyj14 ?
Overall, good job on making the functionality for adding/removing team members!

**Review by TuanDinh140194 — CHANGES_REQUESTED** [review]
Hi! I have followed your and instruction and test your PR. First, after I add member to the team, it didn't add immediately, but after I close the pop-up and reopen it, it added member to the team. And, I noticed it didn't show team name  in the profile team. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/18a78e08-a472-4335-9e6e-4022b33c2a42

**Review by Haoj1 — CHANGES_REQUESTED** [review]
@robertoooc When I add a member to the team, it correctly display in profile, but when I try to remove the member, the team is still in the profile

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/10316e1b-b8b2-4f46-8971-21b7a88fb562

**Comment by emunkh404** [comment]
Great job, Roberto! The 'add/delete user from a team' feature works smoothly, updating user profiles and team lists for Manager and volunteer roles. I tested your PR and found a slight delay in the add team members tab. However, it successfully adds and deletes team members from the user profile when making changes in the teams tab. Overall, most changes function as intended, especially when testing on the Admin account.
image

**Comment by RheaWu1212** [comment]
Everything works as expected! great work! I deleted existing member from team and it updated right away. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/c48f11a7-8c71-46cc-a9b9-c8bec76b2ee7

**Comment by robertoooc** [comment]
@Shiwani99, @JeffLi117, that issue of the member's list not being updated until you reopen the window has already been fixed and merged into development so it was not the main intention of this pr and when merged it shouldn't have any major merge conflicts.

**Comment by robertoooc** [comment]
@TuanDinh140194 and @Haoj1, Can you confirm that you tested this pr with the assigned backend [550](https://github.com/OneCommunityGlobal/HGNRest/pull/550) and ran `npm run build`. The backend pr was meant to fix this issue.

**Comment by JeffLi117** [comment]
> @Shiwani99, @JeffLi117, I noticed this issue as well but that issue of the member's list not being updated until you reopen the window has already been fixed and merged into development. So it was not the main intention of this pr and when merged it shouldn't have any major merge conflicts.

@robertoooc Understood. Please feel free to dismiss my "requested changes" comment -- or if there is another course of action more suitable, please let me know!

**Comment by astrjc0326** [comment]
Hi Robert, I tested the PR and it works as expected.
It works smooth to remove user at the team side.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/69b011b7-4f3a-4df8-8f3b-49c97422ef23

It works the other way, but it took a long delay for the delete to happen.

Uploading Screen Recording 2023-09-30 at 10.27.36 PM.mov…

**Comment by beblicarl** [comment]
I tested this functionality. I noticed that sometimes when you delete a team from the user's profile it does not reflect in the team member page.

[screencast-localhost_3000-2023.10.01-17_07_08.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/68fb82a2-8621-4607-9cda-7c568cd38f24)

**Comment by robertoooc** [comment]
> I tested this functionality. I noticed that sometimes when you delete a team from the user's profile it does not reflect in the team member page.
> 
>  screencast-localhost_3000-2023.10.01-17_07_08.webm

Hi @beblicarl, if you're referring to the action performed in your video at 3:44. The user isn't removed from the team's member list due to not clicking the save changes. If there are any other instances please let me know!

**Review by Sssky-18 — DISMISSED** [review]
Hi @robertoooc, I tested this PR using my Admin account, and the add and delete actions worked as expected. First of all, I added my account into my team, and it worked great, and the team correctly showed in my Admin profile. Then I removed the account from the team in the profile page, after saving the changes, my Admin account was successfully removed from my team. So I think this PR worked as intended, great work! 
PR#1350_2

PR#1350

PR#1350_3

**Review by Vishala09 — CHANGES_REQUESTED** [review]
I tested your PR. Great Job!

I tried to add an user to the team in teams page. After a delay / open&close of dialog , I can see the user being added to the team. This is also reflected in the corresponding user's page under teams tab. When I delete the user from team from the user's profile page , user gets deleted and this gets reflected in teams page as well.
But , when I try to add the same user again for the second time to the same team , for some reason it is displayed in teams page , but not in user's profile page. I have a video testing for the same scenario. Please look into it. 

[Untitled_ Oct 04,2023 4_06 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/0a035d8b-ca2a-4949-8a5c-5662126982dd)

**Comment by robertoooc** [comment]
> I tested your PR. Great Job!
> 
> I tried to add an user to the team in teams page. After a delay / open&close of dialog , I can see the user being added to the team. This is also reflected in the corresponding user's page under teams tab. When I delete the user from team from the user's profile page , user gets deleted and this gets reflected in teams page as well. But , when I try to add the same user again for the second time to the same team , for some reason it is displayed in teams page , but not in user's profile page. I have a video testing for the same scenario. Please look into it.
> 
>  Untitled_.Oct.04.2023.4_06.PM.webm

Hey @Vishala09, I noticed you didn't run `npm run build` before running `npm start` on your backend. That's the cause of that last functionality not working.

**Comment by Vishala09** [comment]
Hi @robertoooc! Thank you! I just figured that out. Retested it again! Everything seems to work fine. Great Job!!

- Adding user to a team on teams page works fine
- Reflected immediately on user's profile
- Deleting user from a team from user's profile reflects on teams page
- Deleting user from a team from teams page reflects on user's profile

**_Please find my video testing here:_**
[Untitled_ Oct 04,2023 6_48 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/563135c4-bf3d-4a35-affe-d89fbfbd038c)

**Review by Vishala09 — DISMISSED** [review]

**Comment by Shreyj14** [comment]
Hi @robertoooc 
I tested the PR and the functionality works as intended for all but the one where the team list needs to be updated instantly. You can see in my recording that once I close the team members list and reopen then only the name is being reflected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/53e27262-1278-4c30-9961-d5ac5beadef1

**Review by Shiwani99 — APPROVED** [review]

**Review by Shubhu0 — CHANGES_REQUESTED** [review]
Hi @robertoooc I tested and reviewed the PR. The member can be added and deleted easily and works as intended. However, I did notice that it does not reflect the change or addition of a member till you close down the pop-up and reopen it, only upon reopening is the change reflected correctly


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/c3b3b1d7-cb9b-46c4-bfed-acb56aa32dc0

**Review by malikjahanzaib — APPROVED** [review]
Hello @robertoooc, I've evaluated this pull request using my Admin account and found that the add and delete actions performed as anticipated. Initially, I added my account to my 2 different teams, and it functioned seamlessly, with the team correctly displaying in my Admin profile. Subsequently, I removed my account from the team on the profile page, and upon saving the changes, my Admin account was effectively removed from the team. Therefore, I believe this pull request has successfully achieved its intended functionality. Excellent job!

Test Rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/b23ba7e1-f42b-4553-b4aa-572238e0373a

**Review by StrawberryCalpico — APPROVED** [review]
Hi! I just test your PR, it worked perfectly, Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/ce518d37-bdd2-4dd7-8a02-1176bc15bea8

**Review by KurtisIvey — APPROVED** [review]
Your code is clean and functions exactly as intended. Fantastic job!

member added:
pr1350 member added to team successfully

member removed in user profile from team:
pr1350 removed successfully

member readded:
pr1350 readded kurtis-admin to team

member removed successfully from teams popup modal:
pr1350 removed successfully from modal

member stayed removed when logging out and back in:
pr1350 removed user stayed removed upon relogging in

**Review by KurtisIvey — APPROVED** [review]
Functions perfectly fine still. Good job on clearing up the merge conflict.

**Pull request merged**
