### PR TITLE
Nahiyan_Dark mode on BMDashboard

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
This PR includes dark mode on all available/working pages of the BMDashboard. 

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Dark mode on the following:
- BMDashboard
- Project details page
- Equipment page

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to `localhost:3000/bmdashboard/` -> select a project and go to Project Dashboard 
6. go to `localhost:3000/bmdashboard/equipment/list` 
7. verify all pages are working properly both in dark and light mode.

## Screenshots or videos of changes:
Screenshot 2024-06-06 183040
Screenshot 2024-06-06 183353

### CODE REVIEW

**Comment by Vijeth-V** [comment]
Everything works well, both in light mode and dark mode. Good job!
Screenshot 2024-06-06 at 9 46 48 PM
Screenshot 2024-06-06 at 9 46 56 PM

**Review by tianyangL11 — CHANGES_REQUESTED** [review]
My Project details page is perfect, but the input fields in the Equipment page are not displaying properly.
d321adbdba6ea85f8a9ba374aec9125
3175b6832708560f8e344dec23dee85

**Review by aaryaneil — APPROVED** [review]
The changes work as expected and all the pages work properly in dark mode.
Screenshot 2024-06-15 at 12 08 25 AM
Screenshot 2024-06-14 at 11 09 52 PM
Screenshot 2024-06-14 at 11 13 02 PM

**Review by kdaga81 — CHANGES_REQUESTED** [review]
1. Uneven margin between the buttons
image

2. Text in yellow box too small to read, We can increase the size of the box to make it more visible
image
3. We can have 2 columns for label and textfield which will make it more uniform.
image
4. Should it be a pre-populated value or drop-down?
image

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey @Nahiyan-16 
The Changes Are Working at expected
image
In the second page, consider adding a min width to t he input fields.
image
Thank you.

**Review by manikittu810 — APPROVED** [review]
Hello @Nahiyan-16 
Everything works as mentioned.

https://github.com/user-attachments/assets/37bc811a-f560-46ae-83af-5968ed1646c2

Screenshot 2024-08-01 at 5 44 54 PM

Thank you.

**Comment by Gmon-k** [comment]
All the pages are working fine in the dark mode. Below are the screenshot for it.

**Pull request closed without merging**
