### PR TITLE
Shefali unit test pie chart

### PR DESCRIPTION
**Pull request by SMitta11**
# Description
Unit test for src/components/common/PieChart/PieChart.jsx

## Main changes explained:
Added test cases to check for the following
-  applies dark mode class correctly
- renders the SVG pie chart
- generates the correct number of unique colors
- -removes SVG on unmount
- 
## How to test:
1. check into current branch
2. do `npm install`
3. do `npm test PieChart.test.js`

##Screenshot after running:
Screen Shot 2024-09-13 at 12 21 35 PM

### CODE REVIEW

**Review by RishithaMamidala — APPROVED** [review]
@SMitta11 
Reviewed the PR, Passes all test cases.
PR 2672

**Review by ArtemisNyx3 — APPROVED** [review]
image

test cases passed

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (199)

**Review by Saniya98 — APPROVED** [review]
All test cases are passing 
image

**Review by jinxyou — APPROVED** [review]
All test cases have passed. 
Screenshot 2024-09-13 234600

**Review by Abhinav-Ankur786 — APPROVED** [review]
Test cases are passing 

image

**Comment by mianmiantea2019** [comment]
Test cases are passing!

image

**Review by Gauravmg6 — APPROVED** [review]
All the test cases are passing.

Screenshot 2024-09-16 150101

**Review by ddshah878 — APPROVED** [review]
I have tested the PR and all the test cases have passed. Good job!

image

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and all test cases passed successfully

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture2672

**Review by Watchdog00 — COMMENTED** [review]
Verified the changes, and everything aligns with the PR specifications. Tests are passing.

**Review by neeharikakoniki — APPROVED** [review]
The unit tests thoroughly cover the core functionality of the PieChart.jsx component. The dark mode class, SVG rendering, color generation, and unmounting behavior are all well-tested.

image

**Comment by geetamatkar** [comment]
Hi @SMitta11 ,
Tested this PR and it is working as expected.

PR2672

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
