### PR TITLE
show user name in header when first log in

### PR DESCRIPTION
**Pull request by juneluo**
### Description
Fixes bug 3 of HIGH-PRIORITY BUGS/FUNCTIONS (IN ORDER):
 When you log in your account, the user name is not showing up until you refresh the page.
img

### Mainly changes explained:
In previous version, the `props.auth` won't have the value of `firstName` and `ProfilePic` and the hook to get header data will only run once (before is authenticated) at the very beginning. Now that it will be able to check the change of the status and get the header data when the user first sign in.

A small correction not related to this task:
The warning information of the input on the forgot password page has been corrected.

### How to test:
check into current branch
do npm install and ... to run this PR locally
Log in
PR

### CODE REVIEW

**Comment by Jorge-Nerd** [comment]
Hello @juneluo Compared to logging into the development branch 

login_develop
seems to fix this little bug
image

**Comment by NyahJ** [comment]
Hi @juneluo,

The change works well on my side. I believe you have fixed the bug, thanks :)

**Review by tingedudu8 — APPROVED** [review]
Hi @juneluo, I tested different roles and they all worked well, as well as the warning information in the forgot password page.
PR681

**Review by suigunfjc — APPROVED** [review]
Hi @juneluo , I tested on the dev branch and your branch. The header is displayed correctly now. I checked your code and they look good to me. I will approve your PR. Good job!
Screenshot 2023-02-20 204850
Screenshot 2023-02-20 204914

**Comment by AnishPandita** [comment]
Hi, I tested you PR # 681 and its working as intended. I tested with multiple user logins and the profile name shows up correctly. The warning info on forgot password looks okay too.
Screenshot 2023-02-21 at 5 55 27 PM

**Comment by agujjar2206** [comment]
Hello @juneluo, I have tested the PR and it works as expected.



Thank you.

**Review by agujjar2206 — APPROVED** [review]

**Comment by Lunaliar** [comment]
Working on my end as well! Great job using a minimal-change solution! 
Screenshot from 2023-02-22 10-45-05
Screenshot from 2023-02-22 10-46-15

**Review by Lucas-E — COMMENTED** [review]
Hey, Juneluo, how are you doing? I've tested your changes on my end, and everything works fine, great job!
JunePr681First

**Comment by anant2047** [comment]
The functionality works as expected. The code looks good too. Bravo!
Screen Shot 2023-02-22 at 6 08 31 PM

**Review by anant2047 — APPROVED** [review]

**Review by vanelnw — APPROVED** [review]
Hi @juneluo 
Great job fixing this bug. I've tested it and it's works as expected

https://user-images.githubusercontent.com/38879488/220813067-ba86b402-9cd3-42b8-a29a-b951694b9209.mp4

**Comment by kamtoeddy** [comment]
Hi @juneluo,

Your fix works as intended
Thank you

Screenshot (508)

**Comment by harlleybastos** [comment]
Hi @juneluo, I just checked here and your fix works !

Here before and after changes:

Before:
PR_#681_BEFORE_CHANGES

After:
PR_#681_AFTER_CHANGES

**Comment by one-community** [comment]
Great job everyone, moved this one to the PR Management Review Team

**Review by rauleffting — APPROVED** [review]
Hi @juneluo. Your PR is working perfectly. And the code is clean.

https://user-images.githubusercontent.com/29555732/221203368-ce3c6985-052d-4f76-86ca-3f7f4147347c.mp4

Thank you very much!

**Review by kamtoeddy — APPROVED** [review]

**Pull request merged**
