### PR TITLE
Xiaohan fix profile assign badge

### PR DESCRIPTION
**Pull request by XiaohanMeng**
# Description
bug

## Related PRS (if any):
To test this frontend PR you need to checkout the [#911](https://github.com/OneCommunityGlobal/HGNRest/pull/911) backend PR.

## Main changes explained:
- Update the assigning badge permission
- Fix the bug of assigning badge on other user profile

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as Owner user
5. go to dashboard→ Permissions Management -> Manage User Permissions ->  Choose a user without badge management permissions of 'assign badges' -> add the permission for this user -> Scroll down then submit
6. log into the account that was just granted permission and go to Leaderboard -> click one profile -> click 'assign badge' -> assign badge -> click 'confirm'
7. You will see the changes on the page.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/7522be9c-36d1-4bb2-bf70-3d160c971e2e

## Note:
- If you cannot see other users in the leaderboard, you can use the Owner account to add them to the team.
- If the displayed badges have reached their limit, click "Selected Feature" to check for new badges.
- One possible reason for the badge list not displaying is due to cache. If this occurs, please clear the cache and try again.

### CODE REVIEW

**Review by SanketKaware — DISMISSED** [review]
I have tested the functionality and it works as expected. 

For the "Volunteer" role account, after adding the permission, I was able to see the "Assign Badge" button.

Adding "Edit Badge" permission was necessary to view the list of available badges.

Change looks good. 

For reference, please take a look at my video review.

**Before**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/cb641df0-55a0-403a-8d04-1613442779c3


**After adding "Assign Badge"**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/0547092f-24b0-4068-9856-31d8c3704bd3


**After adding "Edit Badge"**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/8a3faf9f-4238-42e9-affe-8800a8ecb5e9

**Review by iven-yao — DISMISSED** [review]
I just reviewed this pull request, and following is before and after granted "assign badge" on a volunteer role. The role that has permission will see the Assign Badges button on other's user profile page, and able to assign a new badge correctly. Great job.

image
image
image
image

**Comment by hbodgal** [comment]
I reviewed this pull request and it works fine. Now New User who got permission to Assign Badges can use the functionality well and without any issue. here is the video recorded while testing:

link : https://drive.google.com/file/d/1-M7-YWankLA02Lyreohmr_Wf9aGQOmKQ/view?usp=sharing

**Review by Renanluizssx — COMMENTED** [review]
Hello Xiaohan, i tested your application and in my case, when i added assigned badge button, it isn't enough to assign the badges, but when i added badge management button, i got to assigned the badges, please see my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/0138cdcf-09da-4781-a04e-60817373b43a

**Review by SRamen1999 — DISMISSED** [review]
After checking this PR, Everything works as expected. Before giving permission user cannot assign badges. But after granted permission you are able to assign a new badge.

Before

Screen Shot 2024-03-29 at 12 24 05 PM

After 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/c81c4696-6736-4dd9-afa5-c577c9d7a89e

**Review by kylepham — DISMISSED** [review]
PR worked as expected. I tested on Volunteer account and confirmed that the user can assign badges to other users.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/fd0a94f4-962f-4baa-859f-c161a577dea6

**Review by hbodgal — DISMISSED** [review]
I reviewed this pull request and it works fine. Now New User who got permission to Assign Badges can use the functionality well and without any issue. here is the video recorded while testing:
https://drive.google.com/file/d/1-M7-YWankLA02Lyreohmr_Wf9aGQOmKQ/view?usp=sharing

**Comment by anandsesha** [comment]
Hi, I have reviewed this PR and the functionality works as expected.

Logged in as an Owner user, and chose volunteer user without badge management permissions.

- Added permission of volunteer user
Volunteer user - permission
Vol user permission added
Volunteer user - toggle add

- logged into the volunteer account that was just granted permission and assigned badges to admin user
logged in as Vol
Assign badges
badges added

- Tested adding additional badges, editing badges, and selecting Featured; changes reflect as expected.
added additional badges
changes updated dashboard
edit badges
updated badges

**Review by Sarthak32 — DISMISSED** [review]
Hello, I have tested your PR , after giving permission it works as expected.
Screenshot 2024-03-30 114816
Screenshot 2024-03-30 115652
Screenshot 2024-03-30 120352

**Review by Renanluizssx — DISMISSED** [review]
Hi @XiaohanMeng, i reviewed your application again and it was about my cache in my browser, it's running well

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/2be7ddbe-ccb8-4b9c-8845-bc556bb3be99

**Review by hetvi11110 — DISMISSED** [review]
I have reviewed PR as mentioned and, it is working as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/b02e2aa1-d8fc-48f2-adda-309de5786dc8

**Review by Parth-tech — DISMISSED** [review]
Hey Xiaohan,
I have review the PR and it worked correctly. 

`Before` Assigning permission to the volunteer account:

- [x] The Volunteer/User must not be able to Assign Badges

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/de31baa8-a43f-4cb7-912f-d58904ebba67

`After` giving Assign Badge Permission to the Volunteer:

- [x] The Volunteer/User must be able to Assign Badges

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/ffa10ef2-5215-477b-ba42-f1550fd57bbd

**Review by Tiantian-C — COMMENTED** [review]
Hi,
When I tried to add badge, I can't find any badge to select.
Screenshot 2024-04-03 at 4 16 25 PM

**Review by SushmithaPrathap — DISMISSED** [review]
Hey,
I reviewed this PR for adding the assign badge permissions. Everything works as expected.
- The owner gave permission to the mentor and the mentor assigned badges to volunteer. The badges were assigned successfully.
- The volunteer has no permission to assign badges and the assign badges button does not appear on the volunteer's screen

Here is a screen recording and screenshots:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/359ceb99-5438-4921-b153-ccc39adac1ac

Screenshot 2024-04-04 at 11 22 36 AM

**Comment by MQChen211** [comment]
Hi, I tested your PR and it works as expected. I signed in with the Owner account to give a Volunteer account permission to assign badges, then logged in as the Volunteer to assign badges to another account. It works out well.
截屏2024-04-04 12 30 10
截屏2024-04-04 12 30 16
截屏2024-04-04 12 30 24
截屏2024-04-04 12 31 39
截屏2024-04-04 12 32 15
截屏2024-04-04 12 32 37

**Review by MQChen211 — DISMISSED** [review]

**Review by anandsesha — DISMISSED** [review]

**Review by aaryaneil — DISMISSED** [review]
All the changes work as expected. Good work.

Screenshot 2024-04-06 at 11 54 20 AM
Screenshot 2024-04-06 at 11 54 56 AM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/fc636e60-d93b-4e65-9621-f6fc3e455189

**Comment by hiralsonip** [comment]
Hello...I logged in as owner and gave "assign badge" permission to volunteer. After that I logged in as a volunteer, it is now showing me the assign badge button but on clicking that button it does not show the badge list and in console displays the error shown in the below screenshot. 

PR2089_volunteer_permission

**Review by hiralsonip — DISMISSED** [review]
Hello...I logged in as owner and gave "assign badge" permission to volunteer. After that I logged in as a volunteer, it is now showing me the assign badge button but on clicking that button it does not show the badge list and in console displays the error shown in the below screenshot.

PR2089_volunteer_permission

**Review by X1aoZhang99 — DISMISSED** [review]
Hi @XiaohanMeng ,

I have tested this pull request and also the BE pull request [#911](https://github.com/OneCommunityGlobal/HGNRest/pull/911). All features work as intended. Please refer to the video. Nice work! 

### Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/68f3892b-fb55-430a-84ad-9b8877679571

**Pull request merged**
