### PR TITLE
Pratima - Fixed Multiple calls to userprofile/ and team/ endpoints on Teams.jsx

### PR DESCRIPTION
**Pull request by PratimaSingh02**
# Description
image

This frontend PR is related to the dev backend.

## Main changes explained:
- Updated componentDidUpdate() in Teams.jsx …
- Made changes in the logic to compare previous and current props in Teams.jsx …

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links → Teams
6. Check the number of api calls (userprofile and team) being made from Network tab in Chrome DevTools (It shouldn't be recurring)
7. No new api calls should be made while typing into searchbar but you should be able to see the search results

## Screenshots or videos of changes:
Before the change:
Teams Page Before

After the change:
Pratima--2

### CODE REVIEW

**Review by linkhanthtel — DISMISSED** [review]
I reviewed your PR and no new api call is made when I type in the search bar. Nice work!

**Comment by ptrpengdev** [comment]
Great job on this. LGTM. This code fixed redundant API calls within the team page. Please resolve the conflicts before merging. 

One thing to point out: this fix is related to improper implementation within the React lifecycle hook, not an optimization with debouncing.

**Review by Ramaruva — DISMISSED** [review]
verified changes in my local env and api calls are making one time
image

**Comment by PratimaSingh02** [comment]
> Great job on this. LGTM. This code fixed redundant API calls within the team page. Please resolve the conflicts before merging.
> 
> One thing to point out: this fix is related to improper implementation within the React lifecycle hook, not an optimization with debouncing.

@ptrpengdev I have transpired about the debouncing to Jae

**Pull request merged**
