### PR TITLE
Sucheta - Filter Projects by User's First Name and Last Name

### PR DESCRIPTION
**Pull request by sucheta90**
# Description
(PRIORITY HIGH) Jae: New Function Request: Search Projects By Person 
- Other Links>Projects
- Need a way to search project by person so I know which ones they belong to and can easily add tasks for them
- [Video of what’s needed](https://www.loom.com/share/3c95e9c100f44bcd8cab922bcff8e8e1)

## Related PRS (if any):
This frontend PR is related to the [#919](https://github.com/OneCommunityGlobal/HGNRest/pull/919) backend PR.

…

## Main changes explained:
- Adds a new component `SearchProjectByPerson.jsx` to `Projects.jsx`. This component returns a form that takes user input to execute the search function.
- Creates a new Reducer function - `userProjectsByUserNameReducer.js` that holds the initial state of the `userProjects` and `userError`

…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/ owner user (any account that has access to the project's page)
5. go to dashboard→ Other Links→ Projects
6. User should see a form that takes user first and last name and executes a search and then a filter function and renders the list of projects.
7. User should see an error if a user is unavailable in the database.

...
## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/1fc52bcc-908c-469e-ae0a-f20e38a152af

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Ramaruva — CHANGES_REQUESTED** [review]
Hi, I am getting error while navigating to projects page I am attaching an video of this recordings 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/49155974-a175-4cf0-bcea-95f37ee679eb

**Review by MinSun0814 — CHANGES_REQUESTED** [review]
Hello Sucheta,  I am not able to open up the page. Please refer to the image
image

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi @sucheta90 , 

I've reviewed your changes and tested them, adding onto the previous reviews, the current code leads to an error on clicking Other Links -> Projects. The following image shows the error.

### I got this at first
image

### Changes I made and request for:

I've tried to fix this error. I added this code in file `Projects.jsx` in `HighestGoodNetworkApp\src\components\Projects\Projects.jsx`.
Please look at the following Image to see the change I made.

image

I have added a `?` to _line 440_ 

previously:
image

Now:
image

### Error Faced Previously:

Projects can be undefined in case there are no projects to show at the start, adding the "?", takes that case into consideration. Once I made this change, the page started working. See below for the expected working look.

### Your Changes are working here: 
image

I am searching for projects I created for myself
image

Resulting search:
image

Take a look at the error that I got at first and the errors the other 2 reviewers faced. 
Your Filter is working as expected. Good work!

**Review by linkhanthtel — CHANGES_REQUESTED** [review]
When I go to dashboard→ Other Links→ Projects. I see error like this.

Screenshot 2024-05-09 at 11 55 28 PM
Hello @linkhanthtel , I just made a change to this PR, can you check if it works ok now?

**Comment by sucheta90** [comment]
> Hi, I am getting error while navigating to projects page I am attaching an video of this recordings
> 
>  sucheta.mp4

Hello @Ramaruva , thank you for reviewing this PR and suggesting the solution to the problem. I have made the suggested change. Can you please verify if this PR works now?

**Review by Ramaruva — DISMISSED** [review]
Hi after latest changes code changes are working fine good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/f6659de7-2f16-4a7f-a694-b81e7bea238a

**Comment by sucheta90** [comment]
Closed due to too many merge conflicts, please refer to [PR2241](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2241)

**Pull request closed without merging**
