### PR TITLE
Howie Clear Insert field when used

### PR DESCRIPTION
**Pull request by HowieMiao**
# Description
Owner login: Other Links -> Send Emails>Insert
After clicking on the insert button under the insert header or image link section, the input should be cleared out.

## Related PRS (if any):
N/A

## Main changes explained:
Updated announcements so that when the insert image/link field is used, it will clear the field after use

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Other Links → Send Emails → Insert
6. verify when an image link is put into the insert field, that it is cleared after use
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/1cb37065-5506-4a01-aae2-9b2c43d1fce7

### CODE REVIEW

**Review by Pranay-ai — DISMISSED** [review]
Hey @HowieMiao 
The PR is working as expected please find the attached screenshot for reference.

https://github.com/user-attachments/assets/b84a680b-6377-4ecf-904b-da40672d072a

Thank You.

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and it works as expected. Great Work 
Screenshot 2024-08-16 164011

**Review by JatinAgrawal94 — DISMISSED** [review]
Image is inserted using link in both dark and light mode.
Suggestion: When I switch from dark to light mode or vice versa the inserted image disappears. Is that supposed to happen? Rest everything works fine.

https://github.com/user-attachments/assets/75d6ba74-f7f1-4d86-8a24-b69994df7b8e

**Review by Aishwarya0898 — DISMISSED** [review]
Hello @HowieMiao 
The Pr is working as expected, tested in both the modes.

https://github.com/user-attachments/assets/65f58c53-e9f7-4203-baf7-9854d03973e9

**Review by Gauravmg6 — APPROVED** [review]
Everything works as expected.

https://github.com/user-attachments/assets/57e4f035-ae38-4910-bf63-351519a30156

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR and its working as expected.


https://github.com/user-attachments/assets/ddcc5ce1-d868-4467-8cf3-f287d5f33c4d

**Comment by beblicarl** [comment]
This feature works as intended and the code is great

[screencast-localhost_3000-2024.08.21-08_56_02.webm](https://github.com/user-attachments/assets/43371235-b21d-4030-9f7f-c6c395c3f765)

**Review by beblicarl — DISMISSED** [review]

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.



Thank You

**Review by sri0606 — APPROVED** [review]
Hey, Good job! The insert field works as expected. I have tested it in both light and dark modes. Please refer to the video below:


https://github.com/user-attachments/assets/cdf18476-3865-40f2-b2c2-f09ea361ae1f

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
