### PR TITLE
Edwin - Fix making intangible to tangible doesn't add progress

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-07-17 at 9 50 37 PM

## Main changes explained:
- When intangible/tangible checkbox is clicked, update the `hoursLogged` property of the userProfile model to update the progress task bar. 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. login with Admin/Owner
4. Dashboard -> Current Week Timelog -> Click the intangible/tangible checkbox 
5. Refresh the page and the progress task bar should change accordingly

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/3309fb8f-a589-4fc9-9dc4-0d97ae039ec2

## Notes:

Currently, when logging time for new task, the progress task bar does not update without refreshing. You will see this behavior as well when clicking the tangible/intangible checkbox and the progress task bar will only update after a refresh.  Thus, making the progress task bar update without refresh is out of the scope of this PR.

### CODE REVIEW

**Review by joyceiphone — APPROVED** [review]
I have tested this ticket by changing one of the intangible time logs to tangible. The changes are reflected after I refreshed the page. Good work!

**Review by xaanders — CHANGES_REQUESTED** [review]
Hi @EdwinLauM ! I've tested your PR and functionality works as explained but:

```
 if (!data.projectName) {
    const url = ENDPOINTS.GET_TASK(data.projectId)
    axios.get(url)
    .then(resp => setTaskData(resp.data))
  }
```

This part of code must be inside of useEffect hook. 
It creates infinite requests:

**Review by HectorAgudelo — APPROVED** [review]
I tested this PR and it works as expected. even though it says that the page had to be refresh to be able to see the changes, my changes were reflected without it.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/dac9ab42-e3d9-4270-b4e6-9ecf45ebd957

**Comment by EdwinLauM** [comment]
> Hi @EdwinLauM ! 
> 
> However I found a problem.

Hi @xaanders, I have updated the code with your feedback!

**Pull request closed without merging**
