### PR TITLE
Ishan fix profile page formatting

### PR DESCRIPTION
**Pull request by ishan-miglani**
# Description
Screenshot 2024-08-22 at 6 45 30 PM

## Related PRS (if any):

To test this PR you need to checkout the development backend branch.

## Main changes explained:
- added css class to keep labels inline with icons in BasicInformationTab.css
- applied css class to labels in BasicInformationTab.jsx

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ View Profile→ Basic Information→…
6. Verify the 4 info icons next to Name, Title, Email and Phone are in the same line as the labels.
7. Verify the Pause button is now in the same line as the Active label.
8. Verify these new features work in dark mode.

## Screenshots or videos of changes:
Before:

https://github.com/user-attachments/assets/9652873d-4bab-45cb-b533-bd35cffd8d74

After:

https://github.com/user-attachments/assets/5ff7d734-9a72-482b-b23e-cef6050f181e

### CODE REVIEW

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

https://github.com/user-attachments/assets/7d95433a-acd9-4712-ac99-096345a20817

Thank You

**Review by SnelPatare — APPROVED** [review]
Working as expected!!

image

**Review by jinxyou — APPROVED** [review]
I have tested it. The fix looks great. 
Screenshot 2024-08-23 161525

**Review by kdaga81 — APPROVED** [review]
image

Changes working as expected!

**Review by SMitta11 — APPROVED** [review]
It works well in both light and dark mode.
Screenshots:
Screen Shot 2024-08-23 at 11 30 39 PM
Screen Shot 2024-08-23 at 11 30 53 PM

**Review by Pranay-ai — APPROVED** [review]
Hey @ishan-miglani 
The PR is Working as expected please find the screenshot for reference.
Thank You.
image

**Review by oliviahyw — APPROVED** [review]
I have tested this PR and the styling is working as expected in either mode.
PR2601

**Review by Gauravmg6 — APPROVED** [review]
Works as expected.
Screenshot 2024-08-25 022003

**Review by preethamdnr — APPROVED** [review]
Hello Ishan,
I have reviewed this PR and changes are working great.
image
image

**Pull request merged**
