### PR TITLE
yixiao_taskeditservice_unit

### PR DESCRIPTION
**Pull request by JYXiao-2021**
# Description
Create the unit test for the service component to confirm whether it working as intended.

## Main changes explained:
- Create file service.test.js to do the unit test.

## How to test:
1. check into current branch
2. do npm install to run this PR locally
3. install the module: npm install axios-mock-adapter
4. run npm test src/components/TaskEditSuggestions/`__tests__`/service.test.js

## Screenshots or videos of changes:
this is changed result
image

### CODE REVIEW

**Comment by Lin1404** [comment]
Hi @JYXiao-2021 , I have tested your PR and all cases passed.

image

**Review by Lin1404 — DISMISSED** [review]

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2024-01-26 at 10 58 45 PM

**Review by ShengjieMao — DISMISSED** [review]
All tests passed. 
PR_1883

**Comment by Cavein254** [comment]
@JYXiao-2021  ran the tests in the pr and everything works as expected.
Screenshot 2024-01-27 132522

**Review by peterson337 — DISMISSED** [review]
All tests passed.

a


one comunnity

**Review by 666saofeng — APPROVED** [review]
All tests passed. Congrats!
image

**Review by vikrambadhan — CHANGES_REQUESTED** [review]
Hi, I tested your PR and the test case failed. Please check the attached screenshot for more info.

Week 22 - PR5

**Comment by bienzguoa** [comment]
> Hi, I tested your PR and the test case failed. Please check the attached screenshot for more info.
> 
> Week 22 - PR5

Hi, I think maybe you didn't do npm install. Please do that and try test again.

**Review by bienzguoa — DISMISSED** [review]
All test cases passed, the test looks good!
Screenshot 2024-01-28 at 12 24 53 AM

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Yixiao,

All tests have passed, nice work! 

Screenshot 2024-01-28 at 18 43 52

**Review by Renanluizssx — COMMENTED** [review]
Hi @JYXiao-2021, i got an error in unit test
PR#1883

**Review by yvonnep165 — DISMISSED** [review]
Hi @JYXiao-2021 ,
All tests passed as below.  Nice Work!

PR 1883

**Review by Nahiyan-16 — DISMISSED** [review]
## All tests pass!
Hi Yixiao, after installing the `axios-mock-adapter`, I was able to run the test and everything seems to be working as intended. 
However, I do have a few suggestions:
- Check assertions based on the response from your service functions. If a function is expected to return data from the server, consider checking the data received.
- Instead of using `axios-mock-adapter`, you can leverage Jest's own mocking capabilities for `Axios`. This can make your tests more consistent with the rest of your Jest test suite.
```
jest.mock('axios');
const axiosMock = require('axios');
const mock = new axiosMock.MockAdapter(axios);
```
- Consider adding more descriptive comments or test suite names to provide context and make it easier for developers to understand the purpose of each test suite and test case.
- Test for edge cases and unexpected scenarios. For instance, what happens if the server responds with a 500 error? Ensure your service functions handle error responses appropriately.

Screenshot 2024-02-01 115318

**Review by Pandani07 — DISMISSED** [review]
I ran the test and everything worked as it was supposed to. Tests and test suits passed.

I also thoroughly checked the functionality of the app on this front-end for any bugs and everything worked as intended. The responsiveness of the app with different screen sizes was checked as well.

Screenshot 2024-02-02 at 7 54 48 PM

**Comment by JYXiao-2021** [comment]
> Hi, I tested your PR and the test case failed. Please check the attached screenshot for more info.
> 
> Week 22 - PR5

can you try after install the axios-mock-adapter module ：npm install axios-mock-adapter

**Comment by JYXiao-2021** [comment]
> Hi @JYXiao-2021, i got an error in unit test PR#1883

It seems that you did not check this branch because the word on the image says no tests matched.

**Comment by galgalinidhi** [comment]
Hi @JYXiao-2021, I tested the PR and all the test cases passed!

Screenshot 2024-02-03 at 2 16 40 AM

**Review by Sophie-lei — DISMISSED** [review]
hey, I just checked this PR and all tests have passed.
Screenshot 2024-02-03 at 21 39 59

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed as expected. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/6fead236-4ffe-4688-b487-e75bf89c93cf

**Review by navneeeth — CHANGES_REQUESTED** [review]
Hello, @JYXiao-2021! I tested your unit test file implementation and I believe there are **more tests required**.

### Test Cases Result
test cases passing

The implementation of the current set of 4 unit tests are working as expected.

### Understanding the `src/components/TaskEditSuggestions/service.js` implementation

Here, we have 4 exports of functions that make GET, POST, and DELETE requests with axios and have the following common structure of a try and catch block:
getTaskEditSuggestionsHTTP

### Reviewing your `src/components/TaskEditSuggestions/__tests__/service.test.js` implementation

In your implementation, it's a great choice to use a **MockAdapter** to simulate responses from a server for testing these axios requests.
However, within the following code, you are only mocking a 404 response to each of the calls:
```javascript
 beforeEach(()=>{
    // Mock all requests with a 404 error 
    mock.onAny().reply(404);  
  });
```

The above implementation only tests the **catch** parts of the `.../service.js` file where each of the functions respond with a `console.log` that prints the error. Whereas a valid response from the **try** parts of the `.../service.js` file is not being tested. 

You can include these for example in your `beforeEach();` to simulate a successful response:
```javascript
 mock.onGet(ENDPOINTS.TASK_EDIT_SUGGESTION()).reply(200, { data: 'mock data' });
 mock.onPost(ENDPOINTS.TASK_EDIT_SUGGESTION()).reply(200);
 mock.onDelete(/\/taskeditsuggestion\/\d+/).reply(200);
 mock.onGet(`${ENDPOINTS.TASK_EDIT_SUGGESTION()}?count=true`).reply(200, { count: 5 });
```
And, write tests like these for example to simulate a successful response and observe if these functions are returning the expected data:

```javascript
it('should fetch task edit suggestions', async () => {
    const result = await getTaskEditSuggestionsHTTP();
    expect(result).toEqual({ data: 'mock data' });
  });

it('should fetch task edit suggestion count', async () => {
    const result = await getTaskEditSuggestionCountHTTP();
    expect(result).toEqual({ count: 5 });
  });

```

This test file will be incomplete without including tests that simulate successful responses from the server. 
Please include **4 more tests** that test a simulated success response (one for each of the exports). Thank you.

Note: Since you are testing ONLY the axios implementation response here and not the response format, it is fine if the MockAdapter response that you are creating/simulating is different from the actual expected response format of each of these HTTP requests.

**Review by vikrambadhan — COMMENTED** [review]
Hi, I tested your PR and all the test cases failed!

Week 25 - PR4

**Comment by JYXiao-2021** [comment]
> Hello, @JYXiao-2021! I tested your unit test file implementation and I believe there are **more tests required**.
> 
> ### Test Cases Result
> test cases passing
> 
> The implementation of the current set of 4 unit tests are working as expected.
> 
> ### Understanding the `src/components/TaskEditSuggestions/service.js` implementation
> Here, we have 4 exports of functions that make GET, POST, and DELETE requests with axios and have the following common structure of a try and catch block: getTaskEditSuggestionsHTTP
> 
> ### Reviewing your `src/components/TaskEditSuggestions/__tests__/service.test.js` implementation
> In your implementation, it's a great choice to use a **MockAdapter** to simulate responses from a server for testing these axios requests. However, within the following code, you are only mocking a 404 response to each of the calls:
> 
> ```js
>  beforeEach(()=>{
>     // Mock all requests with a 404 error 
>     mock.onAny().reply(404);  
>   });
> ```
> 
> The above implementation only tests the **catch** parts of the `.../service.js` file where each of the functions respond with a `console.log` that prints the error. Whereas a valid response from the **try** parts of the `.../service.js` file is not being tested.
> 
> You can include these for example in your `beforeEach();` to simulate a successful response:
> 
> ```js
>  mock.onGet(ENDPOINTS.TASK_EDIT_SUGGESTION()).reply(200, { data: 'mock data' });
>  mock.onPost(ENDPOINTS.TASK_EDIT_SUGGESTION()).reply(200);
>  mock.onDelete(/\/taskeditsuggestion\/\d+/).reply(200);
>  mock.onGet(`${ENDPOINTS.TASK_EDIT_SUGGESTION()}?count=true`).reply(200, { count: 5 });
> ```
> 
> And, write tests like these for example to simulate a successful response and observe if these functions are returning the expected data:
> 
> ```js
> it('should fetch task edit suggestions', async () => {
>     const result = await getTaskEditSuggestionsHTTP();
>     expect(result).toEqual({ data: 'mock data' });
>   });
> 
> it('should fetch task edit suggestion count', async () => {
>     const result = await getTaskEditSuggestionCountHTTP();
>     expect(result).toEqual({ count: 5 });
>   });
> ```
> 
> This test file will be incomplete without including tests that simulate successful responses from the server. Please include **4 more tests** that test a simulated success response (one for each of the exports). Thank you.
> 
> Note: Since you are testing ONLY the axios implementation response here and not the response format, it is fine if the MockAdapter response that you are creating/simulating is different from the actual expected response format of each of these HTTP requests.

Thanks for suggestions. I already changed the test and please review it.

**Comment by JYXiao-2021** [comment]
> Hi, I tested your PR and all the test cases failed!
> 
> Week 25 - PR4

Can you try npm install axios-mock-adapter to test the pass? Thanks.

**Review by navneeeth — APPROVED** [review]
Hello again! Thanks for addressing my pull request review. I think the PR now works as expected! Great job on adding the required **4 more tests**. 

## Test Cases Result
test cases passing
The implementation with the total set of 8 unit tests are working as expected.

Good idea of separating the tests as `HTTP other Service Functions` so that you can clearly define the behavior of the `MockAdapter` in the `beforeEach();` implementation for the simulated success response and for the simulated failure response. The `try` blocks of the relevant implementation in the `service.js` file are now being satisfactorily tested too.
Good implementation! Approving!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
