### PR TITLE
Jerry - Combined changes 1199+1281

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
The main motivation of this PR is to combine FE PRs 1199 and 1281, which happen to make changes to many of the same files and lines of code. To avoid a merge conflict when PRs 1199 and 1281 get merged into development branch, this PR was created.

## Related PRS (if any):
Backend: BE PR #[539](https://github.com/OneCommunityGlobal/HGNRest/pull/539)
Frontend: #1199 and #1281 

## Main changes explained:
- Employing consistent naming of permissions in `src/utils/routePermissions.js`
- Deciding that when a volunteer account has both `See User Management Tab (Full Functionality)` AND `See User Management Tab (ONLY create Users)`, then the `See User Management Tab (Full Functionality)` permission will have priority. I.e., the volunteer account will be able delete, edit, and create users. 

## How to test:
1. In backend (BE PR #[539](https://github.com/OneCommunityGlobal/HGNRest/pull/539)) check into `jerry_user_management_permissions` branch and run the branch locally.
2. In frontend, check into current branch.
3. do `npm install` and `...` to run this PR locally
4. Log in as Owner -> Other LInks -> Permissions Management -> Manage User Permissions
5. Enter the username of an account that does not have the “See User Management Tab (Full Functionality)” permission by default (i.e., a Volunteer account). 
6. Next to “See User Management Tab (Full Functionality)” or “See User Management Tab (ONLY create Users)”, click on Add. Then scroll down and click on Submit.
7. Log in as the volunteer account (if already logged in, make sure to log out and log back in). The “Reports” button should appear with ONLY the “User Management” option visible/accessible.
8. The volunteer account can create, delete, and update users in the User Management page if "See User Management Tab (Full Functionality" permission was added. If only the "See User Management Tab (ONLY create Users)" permission was added, then the volunteer can only create users.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/f3d46882-81c5-4932-b8e3-079823196667

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/350578ce-a743-48df-9ef4-8e3e427e3f6e

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Hey,
Great work. I tested by creating, deleting, updating users in volunteer and it works as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/9d221a56-4f3d-457a-9eb6-d2162b7457f6

**Review by GaryB93 — APPROVED** [review]
Hey @jerryren527, I tested your combined changes and everything seems to work well. I was able to give the User Management Tab permission to a volunteer role and was then able to access the User Management Page. When giving the user the permission to only create users, the delete and reset passwords are disabled as intended. I also went ahead and checked the routing for a user that doesn't have access to User Management and was unable to navigate to that page via URL. Great work!

Screenshot 2023-09-20 at 4 14 03 PM
Screenshot 2023-09-20 at 4 14 55 PM

**Review by wantingxu7 — APPROVED** [review]
Good work. The function works as intended. In the recording, I first grant a volunteer to 'create user' and the buttons are unclickable. Then i grant the volunteer to full permission and 'create user' function and buttons are clickable.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/bc8f426e-e155-40c2-b5f0-d5c98a4a28c2

**Review by JYXiao-2021 — APPROVED** [review]
Hi, Great job. I tested this PR and  It works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/ace8fe44-0bbc-490c-9dd3-98c79ee31c2f

**Review by navneeeth — APPROVED** [review]
Hello, @jerryren527! Tested your PR and the changes work as intended. 

Performed the following tests after checking into the BE PR 539 and this frontend PR:

### See User Management Tab (ONLY create Users)
1. Logged in as Owner and went to `Other Links -> Permissions Management -> Manage User Permissions`
2. Granted the `See User Management Tab (ONLY create Users)` permission to a Volunteer account that I have access to.
3. Logged out of the Owner account and logged in as the Volunteer account with the above permission and first verified that the `Other Links-> User Management` is visible in the Dashboard Header.
4. I was successful in creating an user and as intended, prevented from updating or deleting the user.
Testing video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/06d72a8f-694e-41ec-b16c-f64bacc5b578


### See User Management Tab (Full Functionality)
1. Logged in as Owner and went to `Other Links -> Permissions Management -> Manage User Permissions`
2. Granted the `See User Management Tab (Full Functionality)` permission to a Volunteer account that I have access to.
3. Logged out of the Owner account and logged in as the Volunteer account with the above permission and first verified that the `Other Links-> User Management` is visible in the Dashboard Header.
4. I was successful in creating an user and as intended, I was also allowed the rest of the functionality in the User Management page.
Testing video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/8f0634b2-56b9-4296-b654-c0f8f4fed925


Good implementation!

**Review by Bhagyashree444 — APPROVED** [review]
Both work as expected - See User Management Tab (Full Functionality)” or “See User Management Tab (ONLY create Users).

Screenshot (156)
Screenshot (157)

**Review by malikjahanzaib — APPROVED** [review]
Hi @jerryren527, I tested this PR locally along with BE PR #539 and everything seems to work as intended. See User Management Tab (Full Functionality) and See User Management Tab (ONLY create Users) works perfectly when I assigned these permissions to a volunteer account from an owner account. Also the volunteer with full functionality was able to delete the account it created using create users only functionality. That confirms the changes work as described. 

Only thing I noticed is when the volunteer account changed the user details(it previously created) they weren't reflected in the user management tab immediately but changes persisted in the user profile when clicked. I believe this bug is not related to this PR rather has been addressed in other PR. Great Job!!!

Test rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/4fbee7af-930c-47fb-9b54-0ea0d6cacdd9

**Review by StrawberryCalpico — APPROVED** [review]
Hi, I tested your PR, it works as expected. The functionality works well. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/65c9ff8f-6ae7-4170-ae61-00a0e86b05c1

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Hey @jerryren527, I don't see an option here called Manage User Permissions. Is this because of some error?
pr

**Comment by palakgosalia** [comment]
Hey, I have reviewed and tested the changes and it works as intended. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/8c1f77f7-ded2-4c3a-81c7-20a9a96b740a

**Review by shubhankarval — APPROVED** [review]
Hey @jerryren527, the PR works as intended, great job!

Reports button is available with only User management option:
Screenshot 2023-11-04 161212

User has ability to create and delete users and reset passwords:
Screenshot 2023-11-04 161310
Screenshot 2023-11-04 161523
Screenshot 2023-11-04 161606

**Review by Alforoan — APPROVED** [review]
Everything works as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/85ce8413-50bd-4564-acf3-13c70e0f7b9a

**Review by skaush21 — CHANGES_REQUESTED** [review]
* logged in as owner -> other links -> permission management -> manage user permissions
1. owner account is unable to modify/add user permissions
2. owner account cannot see the search query for users shown in the video.
* logged in as volunteer user with no permission changes, volunteer cannot see other links -> user management.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/740709dc-3807-43fb-bb0e-e5e5c6702550

issues found:
In PermissionsManagement.jsx on line 17 isUserPermissionsOpen is set to ‘false’ after setting this to true and saving the changes the pop-up window for the search query appears. I am able to search for a user and add permission roles. 
PR1312

However, the submit button does not work. I get a notification stating that its been saved but when I log out and log in as volunteer user, I am unable to see ‘’other link’ -> ‘user-management’.

**Comment by jerryren527** [comment]
Thank you all. I’m closing this PR as another developer has already addressed the changes it aimed to make. Please see refer to this [google sheet](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit?usp=sharing).

**Pull request closed without merging**
