### PR TITLE
Swathy - Added unit tests for People Table

### PR DESCRIPTION
**Pull request by swathyjayaseelan**
# Description
Unit testing of People Table component under Reports

## Main changes explained:
- Create a unit test file for People Table Component under Reports --> __tests__

## How to test:
1. check into current branch
2. run ```"npm test src/components/Reports/__tests__/PeopleTable.test.js"```

## Screenshots or videos of changes:
You should be able to see 6 successful tests
## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by nnamdixobi** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/eb4242f8-8f15-4a72-a3d0-2ee077ae82e4

Screenshot 2024-03-08 184704
Tested and I got these errors please attend to them

**Review by nnamdixobi — CHANGES_REQUESTED** [review]
I tested as specified and got errors which should be addressed

**Comment by swathyjayaseelan** [comment]
@nnamdixobi  I apologize for providing the wrong path. Please test with this path 
npm test src/components/Reports/__tests__/PeopleTable.test.js

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 30 - PR8

**Review by aaryaneil — APPROVED** [review]
Looks good to me, all the test cases were passed.
Screenshot 2024-03-30 at 8 28 03 PM

**Review by scoopstroop92 — COMMENTED** [review]
Looks good @swathyjayaseelan . Good job on the test cases
image

**Review by yvonnep165 — APPROVED** [review]
Hi, I have reviewed the tests you wrote and ran the tests. They all passed. Nice work!
PR 2035

**Review by bhuvaneswarignanasekar — APPROVED** [review]
I have reviewed your PR. All test passed. Great Job. 

Screenshot 2024-04-09 at 8 36 44 PM

**Pull request merged**
