### PR TITLE
Xiaoyu - Revise "Save" and add a Close Button

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
image

## Related PRS (if any):
This frontend PR is related to the #951 .
…

## Main changes explained:
- separate save function into handle close, handlesavesuccess, handlesaveerror, updateuserdata,mainsavehandler
- add close button
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user

## Note:
Include the information the reviewers need to know.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/c7e9daed-c300-42c3-b75e-55b5f610950e

### CODE REVIEW

**Review by BaileyM96 — APPROVED** [review]
Good evening I merged your branch and tested the save and close button and ran into no issues. The buttons and functionality work as intended and I looked at the differences in the original PR , great work!

## Video

[PR#975 save & close button.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/b5eab83c-8c95-4e98-a8ac-76efc0afca8c)

**Review by AaronPersaud — APPROVED** [review]
Everything looks good!

<b> Testing move summary and close button</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/7089472a-486a-48e3-b623-5a6ba47a21ab

- moving summary successfully
- close button works after moving
- close button works without submitting weekly summary



- summary is moved to the correct tab

I have approved the pull request.

**Comment by AnishPandita** [comment]
Hi @20chen-7 I tested the PR and everything works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/e89160bf-5ab3-49c4-9655-4f4584d132e4

**Review by tdkent — APPROVED** [review]
Local testing confirms that weekly summary inputs can be transferred between tab groups. The **Close this window** button also works as intended. Nice work!

I encountered a couple of potential issues (granted they are likely outside the scope of this PR) during testing:

- Clicking `Save` to submit the form causes simultaneous and contradictory responses: a modal form to confirm / cancel form submission **and** a toast proclaiming the form is already submitted. The modal cancels as soon as the toast timer runs out, regardless of whether the user has interacted with the form.

- It is not entirely clear whether the `Move This Summary` action is transferring the data to the selected tab only, or if the data is being transferred _and_ submitted. (It appears the data is submitted because after using the `Move This Summary` and reloading the page, the Weekly Summaries section is updated, without having used the `Save` button).

- Users can submit what appear to be empty summary forms, as long as there is a valid entry in one of the other tabs:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/6a94f7de-f86a-48d4-bc96-816f3f87733e


Main Test Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/beaf38e4-87e9-4fe7-b613-b0c5d3dc5b86

**Comment by beblicarl** [comment]
This functionality works as intended. Great work!

[issue #975.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/3a18ab02-2528-44dc-a3b7-7dc48f801d0b)

**Review by beblicarl — APPROVED** [review]

**Review by NidaZaki — APPROVED** [review]

**Review by yaow62023 — APPROVED** [review]
Two functions tested. Move weekly summary and button auto close. Both function are worked. For detail check the video below. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/b0c6ad5d-171c-4603-8f88-0afdc2239360

**Review by shiva2096 — APPROVED** [review]
Changes works as described
- successfully move summary across tabs
- close button works



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/ab2ac5fd-488a-4d38-99c6-f275bb565f24

**Pull request merged**
