### PR TITLE
Akshit finished for Sarthak project and team overview UI fixed

### PR DESCRIPTION
**Pull request by Sarthak32**
# Description
Restores Gradient gradient coloring for the overview boxes in Teams and Projects. 

## Related PRS (if any):
It is not related to any.
…

## Main changes explained:
- Implements Gradient gradient coloring for overview boxes in Teams and Projects to improve UI aesthetics.
…

## How to test:
1. check into the current branch.
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ Other Links>Teams and dashboard→ Other Links>Projects
6. You should be able to see those gradient colors and proper alignment like this :
 ## Screenshots or videos of changes:

https://github.com/user-attachments/assets/45526f43-0c03-4e4a-825d-31e0d7d7af7f

## Note:
N/A

### CODE REVIEW

**Review by hbodgal — DISMISSED** [review]
It works as mentioned. Teams page and Projects page both have gradients visible.

image

**Review by linkhanthtel — DISMISSED** [review]
Those gradient colors in both Teams and Projects Pages look good. Nice work!

#2123 (Projects)

#2123 (Teams)

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account. The gradient looks good!

**Note:** I noticed a thin outline on the gradient outside. Not sure if this is expected.

Although there are console errors, I think it is a problem from other branches. Those two errors always show up.

Screenshot 2024-04-17 at 9 23 44 PM (2)

**Review by MohdShahzil29 — APPROVED** [review]
working fine
Screenshot from 2024-04-18 13-45-32

**Review by SRamen1999 — COMMENTED** [review]
I am able to see the new gradient coloring for the overview boxes in Teams and Projects pages. 

Screen Shot 2024-04-19 at 9 36 25 AM

Screen Shot 2024-04-19 at 9 37 31 AM

**Review by aaryaneil — DISMISSED** [review]
The UI changes work as expected and the gradient looks good. Great work.
Screenshot 2024-04-20 at 5 56 44 AM
Screenshot 2024-04-20 at 5 56 53 AM

**Review by Tiantian-C — DISMISSED** [review]
It looks nice!
Screenshot 2024-04-20 at 4 01 16 PM
Screenshot 2024-04-20 at 4 01 47 PM

**Review by dkt6 — APPROVED** [review]
LGTM
Thank you for the great work!

**Review by Sandhya1236 — DISMISSED** [review]
I have tested the changes successfully by checking out the current branch, running npm install, and npm run start:local to set up the PR locally. After clearing site data and cache, I logged in as an owner user and navigated to dashboard → Other Links → Teams and dashboard → Other Links → Projects. I verified that the gradient colors and proper alignment are displayed as expected. All functionalities worked as intended, and the feature appears stable. The PR is ready for merging.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
