### PR TITLE
Ramya teams limit see all

### PR DESCRIPTION
**Pull request by scoopstroop92**
## Note: 
Taking a look at the recent reviews. Kindly do not review the PR unless you see a different kind of bug to report

# Description of the feature

- A “Limit See-All” option for teams 

-  Other Links ->Teams

- When this option is turned on for a team member,  the team member  shouldn't  be able to see  other members of the team in their dashboard 

- The member however should be able to see team members of other teams  they are part of 

## Related PRS (if any):
This frontend PR is related to the [731](https://github.com/OneCommunityGlobal/HGNRest/pull/731) backend PR.

## Main changes explained:
-  Added a column ‘See all’ in the "Team Member " popup
-  A tool tip beside See All
-  Added a Toggle Switch in Add/Edit Teams pop-up beside every row 
-  Rendered the toggle switch with appropriate choice.
-  When the user makes the choice,  make a call to   action function 
-  The  action function  makes a post call to the backend 
-  Make a dispatch call to the reducer to update the redux store. 

## How to test:
1.  check into current branch
2.  do `npm install` and `...` to run this PR locally
3.  log as admin user
4.  Go to Other Links ->Teams
5.  Create two Teams , lets say Team A and Team B (you can use any existing Team as well)
6.  Add  the a **_testuser_1_** as team member to **_Team A_** **_and Team B_**
7.  Set the toggle switch to off  in Team A for **_testuser_1_**
8.  Login to the **_testuser_1_**'s  profile and verify if the user is only able  to see  the members of the  Team B and not Team A

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/2eaaf5a2-9f80-442c-9ace-20fddc997f35

## Note:

- Kindly mention any  bugs , errors you see in the console. 
- Try breaking the functionality , any suggestion is helpful

### CODE REVIEW

**Review by SaiDeepak-NEU — COMMENTED** [review]
Checked into the backend branch mentioned in PR 731 and the frontend branch and tested the feature.

Logged in as an admin and created two teams.
Added a volunteer user to both the teams and 2 different users to distinguish while testing
Switched on the 'see all' toggle for a user in team A
logged out and logged in as volunteer user and could see only the team members for team A and not team B as expected.
The tooltip also seemed to work fine.

Screenshot (47)
Screenshot (45)
Screenshot (44)

However, one bug which I noticed is that, the toggle status is changing on opening the members modal again. When I first add a user, the toggle is off and when I open the modal again the toggle is on without me changing the status.

Take a look at this picture and compare it with picture above, you will notice toggle is on for owner user even when i did not switch it on.
Screenshot (46)

Rest everything worked fine and good job!

**Review by Sophie-lei — CHANGES_REQUESTED** [review]
I tested this PR with PR#718 backend. I found that the see all button limit works as expected. Like the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/e6e192ba-4366-4558-926e-876eda53ce7b

However, just like SaiDeepak mentioned above, the toggle status changes every time the team button is reopened. After changing the see-all status, The toggle status does not change after I reopen it. Please view the video for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/16962427-5ec0-4661-8606-984340dc392a

**Review by KevHnh — CHANGES_REQUESTED** [review]
I followed the steps closely and was able to replicate the expected results. Only comment has already been reported by previous reviewers, the "See All" setting gets toggled when opening the members modal. Otherwise, the changes works as expected.

Team A
image

Team B
image

User's Dashboard with Limited See All
image

See All toggled off after opening modal
image

**Review by Pandani07 — CHANGES_REQUESTED** [review]
Other than the issues that the previous reviewer's have mentioned before, everything works as expected.
I logged in as an admin and created two teams A, B. I added the same user to both teams and one different user for each team. I turned the see all toggle for the common user in team A off. I verified if the common user could see only the members of team B on their account and it works as expected. The tool tip works as well.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/8249a73b-c999-42eb-8f9c-9c2a7089acad


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/38397b5c-ace7-4f34-9e21-469497494d7a

**Review by Renanluizssx — CHANGES_REQUESTED** [review]
Hi @ramyaram2092, all aspects you said is correct:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/a7c12337-7e14-4ba6-8f4e-0a4a7761f13c



 but i noticed an error when i opened the modal, see my review:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/c87b825b-6da0-4edb-ad21-1444f2cde1c9

**Comment by galgalinidhi** [comment]
Hi @ramyaram2092, I tested the PR and it works as expected. However, I observed that the toggle switch is deactivated for certain users, even though I haven't made any changes to it.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/de3d9d45-a891-45e0-bfd2-9b85c254e4bf

**Review by 666saofeng — APPROVED** [review]
Hi, I tested with the admin account and a volunteer account and it worked as intended.


Uploading HGN APP - Google Chrome 2024-02-03 15-20-48.mp4…

**Comment by 666saofeng** [comment]
> Hi, I tested with the admin account and a volunteer account and it worked as intended.
> 
> Uploading HGN APP - Google Chrome 2024-02-03 15-20-48.mp4…



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/ad411396-0710-47d1-a0ae-1f86ff24746f

**Comment by TareqMia** [comment]
Hi, I tested this by following the steps and with the related backend PR, and I am getting the same issues as others have mentioned. When the 'See All' toggle is switched, it does not stay to what was selected. See below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/40886e42-ef4e-4c3e-a7e3-62168723df92

**Comment by mohabbasd** [comment]
Hello, I tested the PR and everything works well and as for me the toggle switch is also working properly when I log in and log out the toggle switch stays the same.
Screenshot 2024-02-03 at 10 16 31 PM
Screenshot 2024-02-03 at 10 17 32 PM

**Review by mohabbasd — DISMISSED** [review]

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Ramya,

I have tested the PR with BE #731. All functionalities worked as intended, also the toggle switch works well for me. It stays what was selected. Please refer to the video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/9baf4009-12d0-451b-b483-5b8f15231238

**Review by SRamen1999 — CHANGES_REQUESTED** [review]
After testing this PR I noticed a bug. 

When you look at a teams toggle box then exit it and look at another team it shows the previous teams toggles not the current. After you exit and click the same team again, then it will show the correct toggle info.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/68a9e61f-8839-4e98-86ae-daba71aa4956

Other than this bug all functionalities worked as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/70075bc6-be1a-43b2-bdb4-8118f3b3dc1e

**Comment by Weiyao-Li** [comment]
please see my frontend review

**Review by brandta-1 — CHANGES_REQUESTED** [review]
# Review
As others have pointed out, when a new team mate is added, the switch state for the previous users will reset. The team visibility function is working correctly, per the video and pictures below.

# Videos


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/5aeda2b5-3c15-4393-b549-cd84a5acf346

00_team_visibility

01_limited_dashboard

**Comment by ramyaram2092** [comment]
> # Review
> 
> As others have pointed out, when a new team mate is added, the switch state for the previous users will reset. The team visibility function is working correctly, per the video and pictures below.
> 
> 
> 
> # Videos
> 
> 
> 
> 
> 
> https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/5aeda2b5-3c15-4393-b549-cd84a5acf346
> 
> 
> 
> 00_team_visibility
> 
> 
> 
> 01_limited_dashboard
> 
> 
> 
> 

Hello thank you for the feedback ! I want to re-confirm if you tested with the latest code ? Can you confirm if you did git pull before you tested ?

**Comment by ramyaram2092** [comment]
> please see my frontend review

Hello ! Could you confirm if you did git pull before you tested the PR ?

**Review by XiaohanMeng — CHANGES_REQUESTED** [review]
Hi, I tested this PR and it works generally as intended, but there's a toggle issue. As shown in the video, after adding a user to a team, Team A's 'see all' toggle turns on by itself, allowing my volunteer account to automatically see all Team A members. Also, the toggle doesn't reset properly upon re-entry. Please see the attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/9d70d53a-6dc2-4bb0-a4c9-716542c4984c

**Review by SanketKaware — CHANGES_REQUESTED** [review]
The toggle switch does not work as expected. When I turn it off in TeamA, it automatically turns off in TeamB and vice versa.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/b97b4ade-d64d-4fff-8952-ec3416e45ca0

**Comment by ramyaram2092** [comment]
@SanketKaware  I did fix  this issue . Let me check from my end . Could you confirm if you did a git pull before you tested this ?

**Comment by SanketKaware** [comment]
> @SanketKaware I did fix this issue . Let me check from my end . Could you confirm if you did a git pull before you tested this ?

@ramyaram2092 Yes, I confirmed that.

image

**Review by sameersdeshpande — APPROVED** [review]
Checkedout from the current branch.
Logged in as an admin and created two teams.
Added a test user to both the teams and 2 different users to distinguished while testing
Switched on the 'see all' toggle for a user in team A
logged out and logged in as test user and could see only the team members for team sam samtest and not samtest3 as expected. But seems to have an issue with toggle. As I toggle user in one team, it reflects for all despite change.
Screenshot 2024-03-15 at 8 52 03 PM
Screenshot 2024-03-15 at 8 51 42 PM
Screenshot 2024-03-15 at 8 52 45 PM

**Review by sameersdeshpande — CHANGES_REQUESTED** [review]
Hi, I tested this PR and it works generally as intended, but there's a toggle issue.After adding a user to a team, Team A's 'see all' toggle turns on by itself, allowing my test account to automatically see all Team A members. Also, the toggle doesn't reset properly upon re-entry. 
Screenshot 2024-03-15 at 8 51 42 PM

**Comment by ramyaram2092** [comment]
Thank you @SanketKaware  for catching it. it was specifically happening only for new team member .
I have fixed the issue. Adding the testing video from my end  with this comment !

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/bd6a3bf2-715f-465c-9080-02b354c6f90f


@sameersdeshpande @SanketKaware @XiaohanMeng  @brandta-1  Kindly re-test and let me know

**Review by iven-yao — CHANGES_REQUESTED** [review]
Hi, I just tested this pull request and found some issue, 

1. logged in as an admin role
2. created two new teams `teamIvenA` and `teamIvenB`
3. added a few members into teams, when I added new members it showed the toggle switch to off as default sometimes, however when I reopen the member modal, they became toggle switch to on.
4. when I tried to set toggle off for one role, for example `Iven Volunteer` in `teamIvenA`, it will also reflect to be off in `teamIvenB`.

let me know if I misunderstood the feature. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25358966/51beca0b-363b-4438-849f-05fadcb24851

**Comment by Gayathr-2012** [comment]
I tested the current branch and added two teams along with their members. In team_a, I toggled it off. However, when I opened the team members section, the toggle switched off and then on automatically. After visiting the profile of a user from team_a, I was able to see members from team B.
image

image

image

**Comment by Gayathr-2012** [comment]
Hello,

I tested the current branch and added two teams along with their members. In team a, I toggled it off. However, when I opened the team members section, the toggle switched off and then on automatically. After visiting the profile of a user from team a, I was able to see members from team B.
image
image
image

**Review by ImzIssa — CHANGES_REQUESTED** [review]
Hello, I've tested your PR and I've noticed what others have, The the toggle switch did not work as expected.

**Comment by ramyaram2092** [comment]
Taking a look at the recent  reviews. Kindly do not review the PR unless you see a different kind of bug to report

**Pull request merged**
