### PR TITLE
Wanting unit test for `AddWBS.jsx`

### PR DESCRIPTION
**Pull request by wantingxu7**
# Description
Unit test for `AddWBS.jsx`

## Main changes explained:
- Created file `AddWBS.test.jsx`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm test AddWBS.test.js`
4. verify that all tests pass with no error

## Screenshots or videos of changes:
AddWBS_unittest

### CODE REVIEW

**Comment by DragonSlayer2401** [comment]
I tested this PR and all tests passed as expected. Please watch the overview video below:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/087f2325-cdfa-4904-9de0-7d83f4624e1a

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-17 at 1 20 20 AM

**Review by bienzguoa — APPROVED** [review]
Good job! Unit test code looks so good, everything is very clear. All test cases passed.

Screenshot 2023-12-17 at 12 21 51 AM

**Review by ljrirene — APPROVED** [review]
Thank you! All tests passed on my side.

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-18 at 10 18 22 PM
All tests have passed successfully. Excellent job!

**Comment by beblicarl** [comment]
all tests passed

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Review by sxiong5 — COMMENTED** [review]
Hey @wantingxu7, all the tests were passed! Thanks!

Screenshot 2023-12-20 at 20 22 44

**Pull request merged**
