### PR TITLE
Showing three summaries instead of just one.

### PR DESCRIPTION
**Pull request by LeeSingChanYau**
Now we can see the last three summaries instead of just one. Implemented a way for people on the same team (especially managers of a team) to access the weekly summaries of their fellow team members. They shouldn’t have access to the entire summaries report, just the summaries of people on their team. Created a dropdown select input form to select from all the team members of the current user.

### CODE REVIEW

**Comment by guiwustro** [comment]
I tested here, and all is working. I have just one question, the Volunteers should be able to see the weekly summaries of their teammates also? (See picture below ). If yes, all is working as should be. 

Image showing that I'm in a volunteer account and can see the weekly summaries of my teammates
image

**Review by guiwustro — APPROVED** [review]
I tested here, and all is working. I have just one question, the Volunteers should be able to see the weekly summaries of their teammates also? (See picture below ). If yes, all is working as should be. 

Image showing that I'm in a volunteer account and can see the weekly summaries of my teammates
image

**Comment by LeeSingChanYau** [comment]
Hello Guilherme, yes that's what I think. Volunteers should be able to see the summaries of their teammates.

**Review by guiwustro — APPROVED** [review]

**Comment by EvianTan** [comment]
Hey @LeeSingChanYau 

I know you already included a bug/feature description as above, could you also give the info like the bug number you're working on? Also, could you please use this Markdown file from [here](https://docs.google.com/document/d/1d-ZzDnb_OOXXUN49V-wExHpAgOFMYpe2se1SaziA7Xw/edit#heading=h.7d9qvgfixytg) to create your PR description? That would give us more info needed. image

**Comment by one-community** [comment]
Even better, please put "Fixed PR #XXX" and link it by your name on the bugs doc. Then we can just use the Find function to locate it. This is better because the numbers change as I add and remove bugs from the doc.

**Comment by EvianTan** [comment]
Hey @LeeSingChanYau . 
I couldn't approve this PR since the behaviors of this PR is not as expected:
Click the button of a admin/owner user's profile page, will get the whole list of all users' summaries instead of current person. Click on the manager/mentor user's profile page, will get the whole team users of current person. Which is definitely not what we want, see the the bug description. 
image
image

**Comment by one-community** [comment]
What Yiyun says is correct. Since this is now showing the whole team's summaries and not just the summaries of the person we are clicking on, I’m thinking this would make more sense and save time to have as an additional tab at the end of the Tasks and Timelogs section on the main Dashboard page too. If that's not super easy, we can do that in a new PR though.

**Comment by LeeSingChanYau** [comment]
I think it may be misleading because of the name I gave to the button. Maybe I should name **View Teammates Summaries**? Yes, I can update the positioning of the button.

**Comment by one-community** [comment]
Good idea, let's make that update too please! With it being a tab in the new location, I think we can get away with the shorter version too: Teammates' Summaries

**Comment by one-community** [comment]
Clarifying Yiyun's comment here: "I couldn't approve this PR since the behaviors of this PR is not as expected. Click the button of a admin/owner user's profile page, will get the whole list of all users' summaries instead of current person. Click on the manager/mentor user's profile page, will get the whole team users of current person. Which is definitely not what we want, see the the bug description."

A person should be able to see the summary of anyone on their OWN team only, not the team of the person they are looking at. Original bug said a person should be able to see the summary of only the person they are looking at, but you've improved on this Alan by allowing a person to choose anyone from their team. We just need to limit it to only anyone from THEIR TEAM, not the team of whomever they are looking at because a person they are looking at may have multiple teams.

**Comment by LeeSingChanYau** [comment]
Hello, I pushed a new commit with changes to satisfy the requests above. Please let me know if should change anything.

**Review by rauleffting — CHANGES_REQUESTED** [review]
Seeing only team members summary is working, but I found something else. Now, it's not possible to see the blue squares anymore.

For example:

This is the development branch:

Screen Shot 2023-01-05 at 12 14 01

It's possible to see the blue squares.

Below is the PRs branch:

Screen Shot 2023-01-05 at 12 15 28

The blue squares can't be seen anymore. And this happens on both the admin and volunteer same team account.

I think this is not supposed to happen, right? 
The error might be inside UserProfile.jsx.

Please, if I'm wrong, feel free to correct me.

**Comment by rauleffting** [comment]
Hi, @LeeSingChanYau! Please update me when this PR is finished.

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau 

It seems to be working correctly. It's showing the blue squares as well. 

@EvianTan, @one-community, check out the video below if this is what you were hoping for, please.

[week 03 - 02-10-23 (#620).webm](https://user-images.githubusercontent.com/114119668/218174065-4426c58e-164b-49b9-aa21-e9026e28b2fa.webm)

**Comment by tingedudu8** [comment]
Hi @LeeSingChanYau, I tested this PR and found that part of the users in the same team display three summaries, but some of them still display one summary, which you can see from below. Also, like PR #593, the summaries should be cleared after the box being collapsed and reopened.

https://user-images.githubusercontent.com/70128933/219810906-26fd4b5f-48f0-444b-bc2a-30d93a259cab.mov

**Comment by PrabhjotSembhi** [comment]
@LeeSingChanYau Please resolve conflicts and also please let Raul Know if changes are made that he wants.

**Comment by NyahJ** [comment]
Hi @@LeeSingChanYau,

After going though the comments above and test from my end, I believe it makes more sense to change the name of this button to "Teammates' Summaries". What's more, there is no missing blue squares issue for my side.
However, I do meet one of the issues mentioned above: there is only one summary for some users instead of three, as shown  in this screenshot, could you pls take a look at this? Thanks!

截屏2023-03-01 下午5 02 06

**Comment by one-community** [comment]
I agree with that button name change, we've got the room, so please call it "View Teammates' Summaries"

**Pull request closed without merging**
