### PR TITLE
pause,start,stop,and cler

### PR DESCRIPTION
**Pull request by ivany9**
The Timer component start, stop, and pause the timer  at the same time  in differents tabs,  also when the user press stop button the timer is on pause.

### CODE REVIEW

**Comment by one-community** [comment]
This PR appears to be fixing this from the Bugs Doc:
"Currently a person can start a timer, pause it, then open a new tab with a timer and it will show the same time on the 2nd one (this is correct). If they start the second timer and leave the first paused though, they can then click “stop” and log their time on the paused one and keep the 2nd one going. To eliminate this, the timer needs to sync all timers when the “Submit” button is clicked. "

Correct me if I'm wrong Jorge. Please copy/paste the source descriptions in your PRs like this from here on out too.

**Comment by ivany9** [comment]
It is correct, now the timers are sync, no matter if you press start, pause, stop or clear all the buttons are working together.
if you open differents tabs you can see the functionality working  for each tab.

Opening two timers and clicking “pause” on one pauses both. But then a person can just start one of the two and the 2nd paused timer will stay at its paused time. You can then click “stop” on that timer and log that time while the other timer continues on ticking forward from the previous time. 
mockup1

**Comment by migfernandes01** [comment]
Hey Jorge, it looks good to me and works. Just have 2 things I am not sure:
1) There are some changes on the `.eslintrc.js` file. Did you mean to overwrite it with your configs?
2) I am getting some errors when running the tests:
failed test jorge PR timer

Other than that it looks good to me. Let me know about those 2 things so I can approve when all is good!

**Comment by ivany9** [comment]
Hi Miguel, Thanks, I already dissmised the changes in .eslintrc.js, now the test looks good

thanks.

**Review by stevenwang213 — APPROVED** [review]
The following tests were tested:
1. Open multiple pages, page1 and page2. Start on page1, page2 starts too.
2. Pause/stop on page1, page2 pauses/stops.
3. Pause/stop on page2, page1 pauses/stops.
4. When the timer is running, create another page. The timer on the new page displays correctly.
5. When the timer is running, create another page and pause/stop on any page. All pages pause/stop.
6. After pausing on any page and logging/clearing the time, all timers are set to zero.

The code works as expected. Great Job!

**Comment by migfernandes01** [comment]
Great job correcting those things @ivany9 ! I still see 1 failed test when I run `npm start` in the testing part. I am not sure what it is:
1 error PR 415

**Comment by ivany9** [comment]
Hi @migfernandes01  just  ran the test and this is what  I got 
mockup4

**Comment by one-community** [comment]
I'm running into all kinds of problems testing this on the Dev. 

1. Clear button cleared timer but refreshing brings back old time
2. Got it to clear but then couldn't get the start button to work 
3. Pause button didn't work when two timers were open

Video:
https://user-images.githubusercontent.com/18335122/169738461-a0545c9e-b46a-4f84-86b7-4e85bbc8e698.mov

**Pull request merged**
