### PR TITLE
Peterson make people report tasks contributed section invisible if no tasks

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request has been opened to fix the bug that displays the Tasks table named Tasks contributed when the user does not have tasks.

## Related PRS (if any):
None.

## Main changes explained:
The component  PeopleReport has been modified to fix the bug.

## How to test:
1. check into current branch
2. do `npm install` , `git pull`  and `...` to run this PR locally
4. Log in as an administrator or owner.
5. Go to Reports→ Reports →  People → Click on any username.
6. Check if the table named Tasks contributed is displayed because the user will have tasks.

## Screenshots or videos of changes:
Peterson_Make_People_Report_Tasks_Contributed_section_invisible_if_no_tasks

## Note:
The console is going to have some errors not related to this PR. These can be disregarded because the code changed by this PR will not introduce these errors to the "development" branch when it gets merged.

### CODE REVIEW

**Comment by AJAYINAVOLU** [comment]
Changes are working as expected!




Thank You

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and it works as expected. 
Screenshot 2024-08-20 175031
Screenshot 2024-08-20 175107

**Review by preethamdnr — CHANGES_REQUESTED** [review]
Hello Peterson,

I've reviewed your PR and here are my observations:

For users who do not have tasks, I did not see the text "No tasks have been found" displayed.

The feature is functioning correctly for users who have tasks, as the "Tasks contributed" table is displayed appropriately.
Please refer to the attached video for further details.


https://github.com/user-attachments/assets/7ed30991-a64c-4a51-b845-65c417a7ff99

**Review by manikittu810 — APPROVED** [review]
Hello @peterson337 
The PR is working as mentioned.


https://github.com/user-attachments/assets/e7f7e480-2d00-4161-b265-062dc59b683c

Thank you.

**Review by SMitta11 — APPROVED** [review]
I login as owner and navigated to reports->people and changes are working as mentioned in PR.
Below are the screenshots:
Screen Shot 2024-08-22 at 5 56 41 PM
Screen Shot 2024-08-22 at 5 54 22 PM

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected. Good work.
Screenshot 2024-08-23 at 10 11 15 AM

**Review by Pranay-ai — COMMENTED** [review]
Hey @peterson337 

The Pr is Working as expected 



Thank You

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
Tested this PR but I am unable to see the text for the users who don't have tasks assigned.

https://github.com/user-attachments/assets/b9afa43f-dce0-4771-af38-885f31c055d9

**Review by Gauravmg6 — APPROVED** [review]
Everything is working well.
Screenshot 2024-08-25 014021

**Review by Saniya98 — APPROVED** [review]
Everything is working as expected
image

**Comment by peterson337** [comment]
> Hello Peterson,
> 
> I've reviewed your PR and here are my observations:
> 
> For users who do not have tasks, I did not see the text "No tasks have been found" displayed.
> 
> The feature is functioning correctly for users who have tasks, as the "Tasks contributed" table is displayed appropriately. Please refer to the attached video for further details.
> 
>  video1786919028.mp4

Hello [@preethamdnr](https://github.com/preethamdnr), I saw your request change and I think that your environment is outdated. Try using git pull in your terminal.

**Comment by peterson337** [comment]
> Tested this PR but I am unable to see the text for the users who don't have tasks assigned.
> 
>  Screen.Recording.2024-08-24.203001.mp4



Hello [@Vigneshwar-Muriki](https://github.com/Vigneshwar-Muriki), I saw your request change and I think that your environment is outdated. Try using git pull in your terminal.

**Review by preethamdnr — APPROVED** [review]
Hello Peterson,
Thank you for the suggestion. I followed your steps by pulling the latest changes using 'git pull' and running the PR locally. After doing so, everything is working as expected.
image

**Review by Vigneshwar-Muriki — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
