### PR TITLE
Jiayu fix bug manual add lost volunteer time

### PR DESCRIPTION
**Pull request by peter6866**
# Description
image

## Related PRS (if any):
This frontend PR is related to backend [PR# 977](https://github.com/OneCommunityGlobal/HGNRest/pull/977).

## Main changes explained:
- Updated `src/actions/timeEntries.js` to return the status code for deleting time entries.
- Updated `AddLostTime.jsx` to fix the boolean checking logic and modify request body.
- Updated `EditHistoryModal.jsx` to fix the boolean checking logic and update the request body. 

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as **owner** user
5. go to dashboard→ Reports→ Reports→ Add Lost time
6. verify owner can successfully add lost time for Project, Person, and Team.
7. verify owner can successfully edit and delete lost time for Project, Person, and Team.

### Before Changes
image
image

### After Changes
https://www.loom.com/share/df6c6c8043ad405088c3766672dec080?sid=e4b769b9-4c1a-4245-9f1e-735f2f9c4342

### CODE REVIEW

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR as owner and able to add the lost time for Project, Person and Team. 
The owner can also edit and delete the lost time for Project, Person and Team.
The issue fix for manual add lost volunteer time is fixed for owner!.

Suggestion: Toaster message can be added to show user the success of add/ edit/ delete lost time.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/ab578111-21ac-4d04-8a5d-ffd8d01fe15f

**Comment by akshit0211** [comment]
I am able to add, edit, and delete "add lost time" for projects, person, and team. Good job!

project add
project
projectedit
person add
person
person edit

**Review by akshit0211 — APPROVED** [review]

**Review by Kavil-Jain-514 — APPROVED** [review]
I have reviewed the PR, and the functionality works perfectly fine; I can add lost time for the project, people, and team.
image
image

However, sometimes the screen goes all white when I log in as owner.
image

**Review by tianyangL11 — APPROVED** [review]
I can successfully add and delete lost time for team, project and user.  Great job!
8a9f3bc6152950c2c49212a2aeee2d9
9305220a30642a6840422aeba7caf55
3f4c193b732bc8c9d706dfcaa2e38ea

**Review by DiyaWadhwani — APPROVED** [review]
Hey Jiayu,
Thank you for the clear instructions. This works as expected. Attached a video implementation of the feature working successfully.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/25978ded-ec9e-48f4-9247-1c7e0296c6bd

**Review by pavanswaroopl — CHANGES_REQUESTED** [review]
Hello,

Great work, but I have observed while adding lost time for team, steps to reproduce:

Add lost time -> select team -> and type a new team name -> it will ask for create new team with the name you have given, while it doesn't make sense to add lost time for a team that has not been created, I'm not sure that option might be at a wrong place, correct me if I'm wrong. As this might not be related to the current PR, I'm approving this, but this should be addressed elsewhere. Thanks

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/5ae52f3b-7804-4883-95fc-8c9f4bea631c


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/09e7cc84-4f6c-46eb-ab04-b847a731bfd7


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/eb523a98-a8ac-4533-8f01-993dc6207709

Screenshot 2024-06-29 at 5 03 03 PM

**Comment by peter6866** [comment]
> Hello,
> 
> Great work, but I have observed while adding lost time for team, steps to reproduce:
> 
> Add lost time -> select team -> and type a new team name -> it will ask for create new team with the name you have given, while it doesn't make sense to add lost time for a team that has not been created, I'm not sure that option might be at a wrong place, correct me if I'm wrong.
> 
>  Screen.Recording.2024-06-29.at.4.56.32.PM.mov 
>  Screen.Recording.2024-06-29.at.4.58.04.PM.mov 
>  Screen.Recording.2024-06-29.at.5.03.15.PM.mov 
> Screenshot 2024-06-29 at 5 03 03 PM

Hi @pavanswaroopl , I believe this is not related to this PR.

**Review by pavanswaroopl — APPROVED** [review]
Found an issue that might not be related to this PR, hence approving it.

**Review by nyelmela — APPROVED** [review]
I reviewed the PR as owner and I can successfully add,delete,update lost time for project, person and team.Here is the video implementation of the related functionality

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/06477488-6cf9-427c-9daf-4333ba755972

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR with backend PR 977. i followed the instructions as given and successfully tested this PR . It working as expected and i was able to add, edit and delete the lost time for project, person and Team. 

Suggestion :Toaster messages can be added to notify the user of successful additions, edits, or deletions of lost time.

PR-2319+977
PR-2319-1
PR-2319-2

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
