### PR TITLE
Kaikanes badge key error

### PR DESCRIPTION
**Pull request by lacnoskillz**
# Description
When loading the app there is a key prop warning and duplicate key warnings.
I noticed in the BadgeSummaryViz component we are assigning them keys but still causing errors
Also the hover was bugged out because of them having the same keys

[Untitled_ Oct 26, 2023 2_51 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/3db0fc63-eed2-4e7c-b5ad-fd9aa28f0ad3)

(bug list priority /low )
Gave the keys unique values by accessing the correct object ._id parameter instead of .id

## Related PRS (if any):
Front end only
…

## Main changes explained:
- Changed .id to ._id on multiple lines
- Updated the key attribute for the list of DropdownItem components inside the DropdownMenu on line 119. Instead of just using the date as the key, I have created a composite key that incorporates the value._id and an index. This change ensures that each DropdownItem component has a unique key,
- key changes also  fixes the bugged out badges
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as Admin who has badges 
4. go to dashboard check key warning is gone.  
5. /Reports/search a user/people/ click on user/ show badges 
6. Verify badges work properly when hovering/clicking on them in multiple view ports
7. verify key prop warning for BadgeSummaryViz Component is gone.

## Screenshots or videos of changes:
[Untitled_ Oct 26, 2023 4_03 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/9c2a0fc0-9ee0-458e-a98c-b9b036e84578)

This error should be gone

Badge key warning

## Note:
That when viewing someones profile you only see your stats (whoever your logged in as).
There are still warnings for BadgeSummaryPreview component that will be a separate PR

### CODE REVIEW

**Review by emunkh404 — APPROVED** [review]

**Comment by emunkh404** [comment]
Hi Kai, I reviewed PR #1461. Your update is working perfectly as expected. Great job!
image
image

**Review by Chuehleo — DISMISSED** [review]
Everything works as expected, great job!
Screenshot 2023-10-26 161916
Screenshot 2023-10-26 161937

**Review by ChirayuRai — COMMENTED** [review]
I checked out your PR and it works as intended!

Screenshot 2023-10-26 at 6 42 47 PM (2)

**Review by sxiong5 — DISMISSED** [review]
Hey @lacnoskillz, the PR worked as intended. 

Screenshot 2023-10-27 at 13 45 28

**Comment by wantingxu7** [comment]
Hi, I just tested and the function works well, and here is what I got in inspect:
截屏2023-10-27 下午2 45 09

**Review by Iris-Song — DISMISSED** [review]
Hi I have tested locally,  the PR worked as intended.
Screenshot 2023-10-28 at 10 16 40

**Review by Bali2Mohit — DISMISSED** [review]
Hi @lacnoskillz, Great work. I tested your changes. All looks good. the error is gone.
Before: Screenshot 2023-10-28 at 21 30 06

After: 
Screenshot 2023-10-28 at 21 36 38

Approving

**Review by yaow62023 — DISMISSED** [review]
I have tested your pr, no error pops out on your pr. Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/a437d8f9-f850-47d6-809a-5197b945c7c6

**Review by sahilpatel18 — DISMISSED** [review]
Hovering over and clicking the badges results in the expected behavior, and the key prop warning for the BadgeSummaryViz Component is no longer present. Good job.
Screenshot 2023-10-28 at 9 08 19 PM

**Review by yangfan2001 — DISMISSED** [review]
Hi, I have tested your PR and it works as intended.
image

**Review by Shubhu0 — APPROVED** [review]
Hi @lacnoskillz Tested your PR and it is working as intended.

image

image

**Comment by palakgosalia** [comment]
Hey, I have reviewed and tested your PR. It works as intended. 
Thank you

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/219faa12-ba19-4c7e-a39e-7dd7524c79bf

**Review by zuhang2000 — DISMISSED** [review]
Hi, I've tested your PR following your instructions. The hover functionality works as expected on all places. 
The error you mentioned also does not exist anymore.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/21b89d4b-1fcb-41c6-94ef-8db7f2d46c1e

**Review by savio-henrique — APPROVED** [review]
Hi @lacnoskillz , I've tested your PR, great work! It didn't show any errors other than the errors mentioned about the 'BadgeSummaryPreview', as the video and the screenshot shows!

# Video and screenshots

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/c1eea3f8-b385-49db-a289-d7d2c827ed5b

screenshot

**Review by KurtisIvey — APPROVED** [review]
Fantastic job. Whoever made this component before really did so haphazardly to just use the index from the .map.

I didn't encounter the hover issue on the main dev branch as I went to double check whether the issues were present. Regardless, you've improved the code 👍🏻

<h3>old lazy code:</h3>

pr1461 lazy code
pr1461 lazy code pt 2

<br>
<br>

<br>
<h3>Good code that follows standard practices from your PR:</h3>

Screenshot 2023-10-31 at 1 53 32 PM
Screenshot 2023-10-31 at 1 53 01 PM



If you could clear up the merge conflicts, this should be able to be merged without issue

**Review by yi-lin-1234 — DISMISSED** [review]
Hello, I have verified that the badges function correctly when hovered over or clicked, and I can confirm that the key prop warning for the BadgeSummary Component has been resolved. Great work!



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/b08b6dd8-840c-4959-a011-ccf99a0599a2

**Comment by lacnoskillz** [comment]
Cleared up merge conflicts
I also pulled from development again
So it shows a bunch of files that were changed that are unrelated to mine
My changes are on src/components/Reports/BadgeSummaryViz.jsx

**Comment by lacnoskillz** [comment]
Cleared up merge conflicts and fixed tablet view key ids (lines after 142)
I also pulled from development again so it shows a bunch of files that were changed that are unrelated to mine
My changes are on src/components/Reports/BadgeSummaryViz.jsx

**Pull request closed without merging**
