### PR TITLE
yihan create editable four-letter team code option

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
This frontend PR is related to the [#480](https://github.com/OneCommunityGlobal/HGNRest/pull/480) backend PR.

## Main changes explained:
- Update file TeamsTab.jsx and UserProfile.jsx for adding Team Code section under teams tab.
- Update file WeeklySummariesReport.jsx and FormattedReport.jsx for adding Team Code Input field and code and color filters on weekly summaries report page. 
- Create file BioFunction.jsx and TotalValidSummaries.jsx for spliting bioFunction and getTotalValidWeeklySummaries (which cause `rendered fewer hooks than expected` error ) from FormattedReport. 

## How to test:
1. check into current branch on both front and back end.
2. do `npm run start:local` to run this PR locally
3. log as Admin/Owner user
4. test "Need the code to be editable from the Weekly Summary Reports page"
a. go to Reports → Weekly Summaries Report → edit team code field (on the far right of Name) → click outside the input field
b. refresh page or go to user's profile page to see if the code is saved successfully.
6. test "Need the code to be editable from a person’s Profile Page"
a. go to any user's profile page → Teams Tab → edit Team Code section → click on "save changes" button
b. verify the team code is saved successfully.
8. test "Need the page to be easily filterable by multiple codes and/or colors" and "See how many people are already assigned to each existing code AND color"
a. go to Reports → Weekly Summaries Report → filter weekly summaries by two filters.
b. verify the page changes and displays correct summaries. Besides, see if the number of "Total Team Members" is correct.

## Screenshots or videos of changes:
1. Edit team code on user profile page and weekly summaries page.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/ce11719c-430a-43bd-bbae-5841aa1e565a

2. Test team code and color filters.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/028b6133-cc54-4bbc-9234-916a8d230538

## Note:
If you edit Team code/Bio announcement/Total Valid Weekly Summaries on weekly summaries page, then use filters, you'll see the corresponding data doesn't update. But it acctually has been saved successfully, and will update if you refresh the page. At first, I was thinking load the weekly summaries from database everytime we use the filter. But after did some tests, I found that load summaries repeatedly slows the system performance and brings really bad user experience.

### CODE REVIEW

**Comment by Haoj1** [comment]
Hi, @AriaYu927, editing team code in profile page looks good to me! But the weekly summary pages are sometimes frozen and cannot be edited. Perhaps it's due to loading too many records on a single page at the same time or my network being slow? I will keep trying weekly summary pages in a better network
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/7fdf9563-8c3e-4ee4-a4dd-8620fdaac9ba

**Review by DavidC0126 — APPROVED** [review]
Hi @AriaYu927 I tested your PR with BE [PR#480](https://github.com/OneCommunityGlobal/HGNRest/pull/480), and they all work as described. Good job! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/172fd29d-2b09-4f56-9a74-073f5c2e0ee0

**Comment by tsunami776** [comment]
I got the same error in the console as @AriaYu927 if the lines 116~126 of /src/components/WeeklySummariesReport/WeeklySummariesReport.jsx are not commented out. 
CleanShot 2023-08-23 at 10 45 39
After commenting out those lines, there is no more freeze issue for me. I tested the Team code and the filters worked as described in the PR.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/c44adbb2-1bf4-48fd-a96a-0ef4f341b271

**Review by eduvarjaor — COMMENTED** [review]
I got the same error in the console too and then followed the recommendation to comment on the lines above. 

Did it and worked well. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/d1728ec4-5846-4412-8d1c-e0627916aae3

**Review by GaryB93 — CHANGES_REQUESTED** [review]
I ran into the same issue as above with the Weekly Summaries Report page freezing and unable to click on any link or update any input fields. After commenting out lines 116-126 I was able to filter through the different team codes and click on links. However, doing so seems to result in a memory leak.

I did also notice if you clicked on a team code input field and then clicked outside of it without changing the team code, you would get a message that you did indeed change the team code.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/28f98b34-6d86-4668-9088-1658df007736

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/e1f47164-8e8f-41e3-af5f-aea842bdb11f

**Comment by AriaYu927** [comment]
I've updated my branch. The freeze issue is solved on my end.

**Review by Haoj1 — DISMISSED** [review]
Nice work @AriaYu927! The freeze issuses are fixed after comment the line 116~126. And the new commit also runs with no problem.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/14870d4b-0640-4f0c-906a-a7bbdcbff62f


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/92f200a2-0cc2-494a-a436-babe2578d876

**Comment by AriaYu927** [comment]
Hi @GaryB93 , thanks for testing! I've updated this PR. The freeze and save issue that you mentioned is solved, please check.

**Review by Haoj1 — APPROVED** [review]
The new commit looks good to me! Good work @AriaYu927 !

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/a57e81ba-24be-45a8-a108-8bfa6d87d8e8

**Review by gabi-lima — APPROVED** [review]
Working as intended, great job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74115277/82c24af0-962b-4622-bfbd-77caa4a7286d

**Review by GaryB93 — APPROVED** [review]

**Review by Jiyuanxia — APPROVED** [review]
Hi @AriaYu927, I have reviewed your pull request and tested it. It works as intended. Good job!
Screenshot 2023-08-24 180439
Screenshot 2023-08-24 180331
Screenshot 2023-08-24 180615
Screenshot 2023-08-24 180636
Screenshot 2023-08-24 180833

**Review by EdwinLauM — APPROVED** [review]
Hey @AriaYu927! Changes work as expected!

Changing Team Code through Weekly Summaries Report Tab:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/27e7e223-71f4-4e5a-a352-d3c5ae6e6d59

Changing Team Code through User Profile:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/aaadb396-ef30-4641-9393-aef09f429976

Weekly Summary Report Tab filters:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/67003bfa-ecaa-4935-b457-93e38253bf90

**Review by liaoyufu-leo — DISMISSED** [review]
Hi everything work well on my device, nice job! @AriaYu927 
image
image
image
image

**Review by yaow62023 — APPROVED** [review]
I've tested your pull request, and all the features are functioning properly. Excellent job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/9f77cf0b-d1fa-4fec-9ee1-91bc9c0bd9a8

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/58ff451a-54b2-420f-8ffd-065b99859a76

However, I've also noticed an issue that might need some improvement. When entering the team code, if it's not following the specified format like "a-aaa," and instead entered as "aaaa," or if five letters are entered, or even other characters, they are all accepted upon saving. Therefore, I recommend adding an input validation feature to ensure that the entered team code adheres to the specified format.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/0d934a6a-64dc-4e24-bdc2-d6b457588b46

**Comment by n0vay** [comment]
Tested the following changes:
Changed the Team code sucessfuly.
Changed the code from User Profile page. Worked for a single user, but didn't change it for the whole team.
While using Filters, the team code filter is working perfectly, I was able to filter the members I assighned code to. 
But it is taking a very long time to select something using select color, the website lags for 8-10 sec for me.



image
image
image


Got the following errors while opening Weekly Summaries Report Page I dont know if this is because of this PR:
image

**Review by winghojackyli — APPROVED** [review]
Hi @AriaYu927 , I've tested the PR and it works as intended. 

### Feature 1: Need the code to be editable from the Weekly Summary Reports page


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/293114ae-733f-4efd-93d1-1a15c8f736d0

### Feature 2: Need the code to be editable from a person’s Profile Page


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/64f33f6a-eede-48f6-9def-04c86381dfdb

### Feature 3: Need the page to be easily filterable by multiple codes and/or colors" and "See how many people are already assigned to each existing code AND color


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/6f455b75-f1cf-4e96-be5a-a33c0e9c827f

**Comment by AriaYu927** [comment]
> Tested the following changes: Changed the Team code sucessfuly. Changed the code from User Profile page. Worked for a single user, but didn't change it for the whole team. While using Filters, the team code filter is working perfectly, I was able to filter the members I assighned code to. But it is taking a very long time to select something using select color, the website lags for 8-10 sec for me.
> 
> image image image
> 
> Got the following errors while opening Weekly Summaries Report Page I dont know if this is because of this PR: image

The details below the error on your screenshot says the error is caused by Timelog.jsx. So, I think it is out of the scope of this PR.

**Comment by one-community** [comment]
Looking good! 

The current position of these labels is going to conflict with a new function that shows badges in that area. Please move the code to the left of the Media URL text and make the box only big enough for the letters allowed there.

**Comment by AriaYu927** [comment]
> enough

I've solved conflicts and moved code fields to the position you suggested, please check. Thank you!

截屏2023-08-28 19 10 56
截屏2023-08-28 19 16 29

**Review by robertoooc — DISMISSED** [review]
Hi @AriaYu927, nice job I tested your branch and was able to perform all stated actions. Didn't seem to encounter any issues. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/85fbde16-8570-46bd-880b-8db2bf1aee3f

**Comment by Arsamat** [comment]
Tested and worked as expected

**Comment by Shubhu0** [comment]
Tested and it is working as expected

**Review by yaow62023 — APPROVED** [review]
I have tested your PR again, work as intended. Great work!

**Comment by one-community** [comment]
> I've solved conflicts and moved code fields to the position you suggested, please check. Thank you!

Please move the code field to the left of the words "Media URL"

**Comment by AriaYu927** [comment]
> > I've solved conflicts and moved code fields to the position you suggested, please check. Thank you!
> 
> Please move the code field to the left of the words "Media URL"

Fixed, please check.

**Review by GaryB93 — CHANGES_REQUESTED** [review]
I encountered many issues with this pull request logged in as an Owner. Firstly, I was unable to save a team code to a user when changing the team code through the user profile page.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/cc5bf2fa-2f90-408f-b9d8-663984de858b

Secondly, when visiting the Weekly Summaries Reports page, I noticed none of the team codes are being displayed properly. Every team code displays 'X-XXX'. Upon reviewing an error in the console when changing the team code on the Weekly Summaries Page it seems maybe that the input fields aren't reading state/team code value. I was also unable to save Team code changes made in the Weekly Summaries Reports page.

Screenshot 2023-09-04 at 1 58 49 PM

**Comment by AriaYu927** [comment]
> I encountered many issues with this pull request logged in as an Owner. Firstly, I was unable to save a team code to a user when changing the team code through the user profile page.
> 
>  Screen.Recording.2023-09-04.at.2.01.03.PM.mov 
> Secondly, when visiting the Weekly Summaries Reports page, I noticed none of the team codes are being displayed properly. Every team code displays 'X-XXX'. Upon reviewing an error in the console when changing the team code on the Weekly Summaries Page it seems maybe that the input fields aren't reading state/team code value. I was also unable to save Team code changes made in the Weekly Summaries Reports page.
> 
> Screenshot 2023-09-04 at 1 58 49 PM

Thanks for your testing. I've updated this PR and applied your suggestion of adding regex test to this PR, please re-review when you get a chance. Thank you!

**Review by GaryB93 — DISMISSED** [review]
Great work on implementing the regex to enforce the team code format. With this PR, you can now effectively change and save a team code for a user via the User Profile page or the Weekly Summaries Report page. You can also filter by team code or color. Not a fan of having to refresh the page to see the changes on the Weekly Summaries Report page but for performance reasons it makes sense. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/13f19bb2-15fc-45f6-b841-4f852fe6db88

**Comment by GaryB93** [comment]
I did see there seems to be a color missing from the color filter. See below.

Screenshot 2023-09-05 at 2 05 36 PM

**Comment by AriaYu927** [comment]
> I did see there seems to be a color missing from the color filter. See below.
> 
> Screenshot 2023-09-05 at 2 05 36 PM

Hi, thanks for your testing. For this problem, it does has an option names "Team" in db. Here is my screenshot:
image

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR and it works as expected. I tried editing the team code in profile page and weekly summary report page, and the update was visible in both the pages. I also tried to check the number of users with the same team code and it showed the correct number of users who have the same team code.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/ba118517-47c3-4cf5-8244-5fbbb6f61e39

**Comment by AnishPandita** [comment]
Hey, I tested the PR and it seems to function well. I was able to edit team code from profile as well as summary page and it reflected correctly. Also the filter according to code and color seemed to work correctly. Didn't encounter any console errors as well. The Regex idea was a nice addition too. Approving the PR.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/a9fb2860-7c44-4c60-b06b-156f67ccd9e7


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/f1f5cb9e-504d-4d2e-a23c-cde35c48b78a

**Review by AnishPandita — APPROVED** [review]

**Pull request merged**
