### PR TITLE
yihan hotfix for filter dropdown list and team code regex check

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
Screenshot 2023-10-03 at 17 50 35
Screenshot 2023-10-03 at 17 50 46
Screenshot 2023-10-05 at 16 29 41

## Related PRS (if any):
To test this frontend PR you need to checkout the [#561](https://github.com/OneCommunityGlobal/HGNRest/pull/561).

## Main changes explained:
- Update file UserTeamsTable.jsx and FormattedReport.jsx for allowing non-caps letters.
- Update WeeklySummariesReport.css and WeeklySummariesReport.jsx for improving filter dropdown style (height, margin between each item, scroll bar visibility)

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. log as Admin/Owner user
4. go to Reports -> Weekly Summaries Report -> Select Team Code
5. verify if 
a. the list is 3x long. (Previously shows 5 items, now shows 15 items)
b.  the space between each item is decreased.
c. the list is alphabetical. 
d. the scroll bar always visible if the code list is overflowed.
e. each team code in the list is followed by a parenthesis with the number of team members in it. 
f. there is a “Select All With NO Code” option at the bottom. 
g. non-caps letter is allowed.
h. now, the allowed team code format are X-XXX and XXXXX.
 
## Screenshots or videos of changes:
Before:
Screenshot 2023-10-03 at 17 28 57

After:
Screenshot 2023-10-03 at 18 26 55

### CODE REVIEW

**Comment by olenadanykh** [comment]
Hi @AriaYu927 .
I tested your PR, and everything works as intended. I was able to verify:
The list is now shows 15 items.
The list is in alphabetical order.
The scroll bar is always visible if the code list overflows.
Each team code in the list is followed by a parenthesis with the number of team members in it.

Great job!
PR1371

There is a 'Select All With NO Code' option at the bottom.
PR1371-2

**Comment by wantingxu7** [comment]
Hi yihan, I just tested the PR, everything works as intended except for one thing, the dropdown list shows 11 items rather than 15 as described.

**Review by navneeeth — DISMISSED** [review]
Hello, @AriaYu927! Tested your changes and they LGTM!

The hotfix works as expected and I verifed the following:
a. The list is 3x long. (Previously shows 5 items, now shows 15 items)
b. The space between each item is decreased.
c. The list is alphabetical.
d. The scroll bar always visible if the code list is overflowed.
e. Each team code in the list is followed by a parenthesis with the number of team members in it.
f. There is a “Select All With NO Code” option at the bottom.
g. Non-caps letter is allowed.

Good implementation!

### Testing video for before the changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/8c0c00bc-cdeb-486d-a03b-3e997c4d4c3f

### Testing video for after the changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/efe332e5-695a-4083-84d5-eba3cf40724e

**Comment by emunkh404** [comment]
Hi @AriaYu927 .It seems that it's not implemented for me. I've tried updating it multiple times, but no changes have occurred. Do you have any suggestions?
image

**Comment by AriaYu927** [comment]
> Hi @AriaYu927 .It seems that it's not implemented for me. I've tried updating it multiple times, but no changes have occurred. Do you have any suggestions? image

Hi @emunkh404 , to get the updated branch, did you try `git branch -D yihan-four-letter-code` to delete the local branch, then checkout to `development` and run `git fetch --all` then `git checkout yihan-four-letter-code`?

**Review by eduhorta — APPROVED** [review]
- List is displaying 15 items
- Alphabetical order
- Scrollbar displaying
- Non-Caps letter allowed

image

Select all with no code:
image

Great job with the implementation! 👍

**Comment by beblicarl** [comment]
a. the list is 3x long. (Previously shows 5 items, now shows 15 items)
b. the space between each item is decreased.
c. the list is alphabetical.
d. the scroll bar always visible if the code list is overflowed.
e. each team code in the list is followed by a parenthesis with the number of team members in it.
f. there is a “Select All With NO Code” option at the bottom.
g. non-caps letter is allowed.

[screencast-localhost_3000-2023.10.05-18_04_25.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/8ca6acf5-9732-4419-9d5f-7e5dc0c13856)

**Comment by Shreyj14** [comment]
Hi @AriaYu927 all these features work as intended.
a. the list is 3x long. (Previously shows 5 items, now shows 15 items)
b. the space between each item is decreased.
c. the list is alphabetical.
d. the scroll bar always visible if the code list is overflowed.
e. each team code in the list is followed by a parenthesis with the number of team members in it.
f. there is a “Select All With NO Code” option at the bottom.
g. non-caps letter is allowed.
h. now, the allowed team code format are X-XXX and XXXXX.

great job!!

**Review by Shreyj14 — APPROVED** [review]

**Pull request merged**
