### PR TITLE
Ajay - Add title and sort functions to Projects WBS Pages Other 

### PR DESCRIPTION
**Pull request by AJAYINAVOLU**
# Description
This PR fixes the centered WBS and Project titles, set default sorting to most recent edits, and added a "Name" sort button (alphabetical/reverse/default). Improved spacing and vertical centering between "Projects" and the back arrow, and applied these formatting changes to subsequent pages.

Fixes # (PRIORITY MEDIUM) Jae: Add title and sort functions to Projects WBS Pages Other

## Related PRS (if any):
This frontend PR is related to the development branch of the [backend](https://github.com/OneCommunityGlobal/HGNRest) repository.

## Main changes explained:
- Update **WBSTasks.jsx**: Added "Project Name" to show return to WBS list.
- Update **WBSTasks.test.js**: Adjusted test case to reflect title change to "WBS Name: wbs name 1."
- Update **wbs.jsx**: Added sorting logic (ascending, descending, default by recent edits).
- Update **index.js** (reducer): Added reducer for fetching project name by project ID.

## How to test:
1. Check into the current frontend branch and the development backend branch.
2. Do npm install and npm run start:local to run this PR locally.
3. Clear site data/cache.
4. Log in as an owner-user.
5. Go to Dashboard→ Other Links→ Projects→ WBS Icon of any project→ WBS List Page.
6. Verify the Back button and the "Return to Project List" is rendered properly and when clicked returns to the project list.
7. Verify the "Project Name: " title is rendered properly.
8. Verify the sort function is working properly for Default sort [Most recently edited -- indicated with minus sign beside the Name], Ascending Order [Ascending order with respect to Name -- indicated with upward arrow], Descending Order [Descending order with respect to Name -- indicated with downward arrow].
9. Click on the any of the WBS and go to the Tasks page.
10. Verify the "WBS Name: " title is rendered properly.
11. Verify the Back button and the "Return to WBS List: Project Name" is rendered properly and when clicked returns to the WBS list.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/666fa18b-115f-4817-be5d-8b96109d4f52

Screenshots:

### CODE REVIEW

**Review by Muhideenthegreat — APPROVED** [review]
Verification:

- The project name sort works as expected (both in ascending & descending order)
- Title is properly rendered in WBS pages
- Return button works as expected as well
Screenshot 2024-11-08 at 5 45 34 PM
Screenshot 2024-11-08 at 5 45 46 PM
Screenshot 2024-11-08 at 5 46 02 PM

Suggestion:
- The sort buttons can be merged into a single multiarrow button with slightly faded colors.

**Comment by geetamatkar** [comment]
Tested this PR and everything is working as expected.

Screenshot 2024-11-08 at 6 19 14 PM
Screenshot 2024-11-08 at 6 19 30 PM

**Review by manikittu810 — DISMISSED** [review]
Hello @AJAYINAVOLU 
Everything is working as mentioned.
Thank you.
Screenshot 2024-11-08 at 4 52 03 PM

**Review by nikhilgiri0226 — APPROVED** [review]
I have reviewed this PR and everything works as expected.
The project title is properly rendered and the sorting functionality is working as expected as well. The return button is also working as expected.


https://github.com/user-attachments/assets/96dfefe8-df09-41a2-98db-5a89c6e94f55

**Review by aaryaneil — DISMISSED** [review]
Tested all the functionalities mentioned in the PR and all work as expected. Just a suggestion that the '-' next to the "Name" in the project WBS should be a little different because it will be hard for a new user to differentiate as I myself was wondering what it was for if not for your instructions.

https://github.com/user-attachments/assets/7c84754c-6c67-4a04-a661-82bce72090d8

**Review by audreydieuanh — CHANGES_REQUESTED** [review]
I verified that
1. The Back button and the "Return to Project List" is rendered properly and when clicked returns to the project list.
2. The "Project Name: " title is rendered properly.
3. Sort function is working properly. The only difference was that the Default Sort icon was not a '-' icon.
4. "WBS Name: " title is rendered properly.
5. The Back button and the "Return to WBS List: Project Name" is rendered properly and when clicked returns to the WBS list.

test18

**Comment by audreydieuanh** [comment]
> I verified that
> 
> 1. The Back button and the "Return to Project List" is rendered properly and when clicked returns to the project list.
> 2. The "Project Name: " title is rendered properly.
> 3. Sort function is working properly. The only difference was that the Default Sort icon was not a '-' icon.
> 4. "WBS Name: " title is rendered properly.
> 5. The Back button and the "Return to WBS List: Project Name" is rendered properly and when clicked returns to the WBS list.
> 
> test18 [ test18 ](https://private-user-images.githubusercontent.com/127930337/386919554-b8451f60-a73f-4e03-aca9-5bd4ce31e982.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTc3NjAsIm5iZiI6MTczMTgxNzQ2MCwicGF0aCI6Ii8xMjc5MzAzMzcvMzg2OTE5NTU0LWI4NDUxZjYwLWE3M2YtNGUwMy1hY2E5LTViZDRjZTMxZTk4Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNDI0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjc1ZjNkOTQzMjc5YjM4N2IyODQ4YzMxMTZlMmY1ZGYyYmRkNzQyZTYxYjFhODIzODU4ZTM2ZWQ0MDk1NjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wA8X4fEd0YPvnqFK17hy8c7JCWibrl6WrrgKeGy-05U) [ ](https://private-user-images.githubusercontent.com/127930337/386919554-b8451f60-a73f-4e03-aca9-5bd4ce31e982.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MTc3NjAsIm5iZiI6MTczMTgxNzQ2MCwicGF0aCI6Ii8xMjc5MzAzMzcvMzg2OTE5NTU0LWI4NDUxZjYwLWE3M2YtNGUwMy1hY2E5LTViZDRjZTMxZTk4Mi5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExN1QwNDI0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMjc1ZjNkOTQzMjc5YjM4N2IyODQ4YzMxMTZlMmY1ZGYyYmRkNzQyZTYxYjFhODIzODU4ZTM2ZWQ0MDk1NjYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wA8X4fEd0YPvnqFK17hy8c7JCWibrl6WrrgKeGy-05U)

Please dismiss this review. I clicked request changes instead of approve.

**Review by audreydieuanh — APPROVED** [review]
I verified that
1. The Back button and the "Return to Project List" is rendered properly and when clicked returns to the project list.
2. The "Project Name: " title is rendered properly.
3. Sort function is working properly. The only difference was that the Default Sort icon was not a '-' icon.
4. "WBS Name: " title is rendered properly.
5. The Back button and the "Return to WBS List: Project Name" is rendered properly and when clicked returns to the WBS list.

test18

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
