### PR TITLE
Changhao - added unit tests for weeklysummary.jsx

### PR DESCRIPTION
**Pull request by lichanghaogit**
# Description
added new unit tests for weeklysummary.jsx to cover edge cases for url input entry

## How to test:
1. check into current branch
2. do `npm install` and `npm test WeeklySummary.test.jsx` to run this PR locally
3. verify all 25 unit tests are passed

## Screenshot:
Screenshot 2024-01-24 at 1 26 04 PM

### CODE REVIEW

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 22 - PR1

**Review by ShengjieMao — APPROVED** [review]
Run the commands according to the instructions, all tests passed successfully.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/766aaa92-3350-40fa-acbe-fc06b1ddc59e

**Comment by iTvX** [comment]
All tests pass, great work!


CleanShot 2024-01-25 at 12 51 22@2x

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2024-01-25 at 6 37 11 PM

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by Lin1404** [comment]
@Changhao3220K All tests passed. Good job!

image

**Review by Lin1404 — APPROVED** [review]

**Review by bienzguoa — APPROVED** [review]
Good job! all test cases passed and renderings are correct.
Screenshot 2024-01-28 at 12 43 56 AM

**Review by AaronPersaud — APPROVED** [review]
Hi @Changhao3220K, I've tested and all the tests passed! Nice work.

image

**Review by 666saofeng — APPROVED** [review]
All tests passed.
image

**Review by X1aoZhang99 — APPROVED** [review]
Hi Changhao,

All tests passed, nice work! 

Screenshot 2024-01-28 at 18 49 31

**Review by Renanluizssx — APPROVED** [review]
Hi @Changhao3220K, All tests passed, very good
Screenshot 2024-01-30 200802

**Review by yvonnep165 — APPROVED** [review]
Hi @Changhao3220K , 
I tested your PR and all the test cases passed! Nice work!

1876TEST

**Review by Nahiyan-16 — APPROVED** [review]
## All tests passed
Hi Changhao, I have tested your PR and all 25 tests have successfully passed. 
Screenshot 2024-02-01 121310

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
