### PR TITLE
Yongjian - Remove horizontal scroll bar on dev and main

### PR DESCRIPTION
**Pull request by ypan710**
# Description
(PRIORITY LOW) Kaixiang:  Remove the horizontal scroll bar on Dev and Main 
Confirmed by at least 2 people but Jae can’t see it on either site using his computer. 
Screen Shot 2023-04-17 at 10 29 41 PM

## Mainly changes explained:
Added "overflow-x: hidden" CSS property to rid of horizontal scroll bar on dev and main.

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. inspect dashboard and other pages in the application to verify that the horizontal scroll bar has been removed

## Screenshots

Screen Shot 2023-04-17 at 10 25 18 PM

Screen Shot 2023-04-17 at 10 25 35 PM

Screen Shot 2023-04-17 at 10 25 58 PM

### CODE REVIEW

**Comment by NataliaCavicchioli** [comment]
Hey @ypan710 I tested you PR and it is looking good. 

It solved the problem with the scroll bar, but the real problem is that the user modal (the one that has view profile, update password, etc) is overflowing, that's why the scroll bar is showing in first place.

I believe that your PR works as intended, as it solves the scroll bar problem, but we should create another PR to solve this, and once this is solved, maybe the overflow: hidden in the whole page won't be necessary.

Before: 
https://user-images.githubusercontent.com/103126226/232815415-bd54822e-6920-493a-a444-8ebd3af72108.png

After: 
https://user-images.githubusercontent.com/103126226/232814640-592dbff5-dbff-4233-b114-64789ccd70c4.png

**Comment by one-community** [comment]
Good catch Natalia. Yongian, please create and raise that PR first. Then decide if this one is even needed.

**Comment by one-community** [comment]
Changing status on this one to "do not review" until this is done.

**Comment by ypan710** [comment]
> Good catch Natalia. Yongian, please create and raise that PR first. Then decide if this one is even needed.

Ok.

**Pull request closed without merging**
