### PR TITLE
Peizhou_Improve the Red/Grreen dot on LeaderBoard

### PR DESCRIPTION
**Pull request by ZhangPeizhou**
# Description
C1
C2

## Related PRS (if any):
This frontend PR is not related to any backend PR, please just check in to the development branch.

## Main changes explained:
- Improve the red/grreen dot on LeaderBoard

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ LeaderBoard
6. move the mouse over a red/green dot, and see if the text is improved like this: 
"Weekly Committed: 10 hours
Click to view their Dashboard"

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Hello @ZhangPeizhou 
Changes are working as mentioned. Below is the screenshot attached.

Screenshot 2024-08-02 at 6 59 13 AM


Thankyou.

**Review by Pranay-ai — APPROVED** [review]
Hey @ZhangPeizhou 
The PR is working as expected here is the Screenshot for reference 
image
Thank You

**Review by kdaga81 — DISMISSED** [review]
image

The hover message is popping as expected.

However, there are 2 issues:
1. It takes some time for message to pop-up upon hovering. However, it should be pop-up directly upon hovering.
2. When we go to any user's dashboard after clicking on red/green dot, there's no option of going back to current user's dashboard. Please let me know if I'm missing on this.

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/ef3ccf78-fea5-435f-8ae5-9ed4ab353c1c

**Comment by ZhangPeizhou** [comment]
> 1. message to pop-up upon hovering. However, it should be pop-up directly

Hello, thank you very much for your review. For the location of the message, I will work on to fix it. However, going back to the original dashboard is another bug. You can report it in the document. Thank you!

**Review by Gauravmg6 — APPROVED** [review]
Changes are working as expected. 
Screenshot 2024-08-03 183042

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and it's working as expected. When the mouse is hovered over the red dot, it displays the weekly commitment.
Screenshot 2024-08-03 214136

**Review by Annezhang673 — APPROVED** [review]
Works as expected. I can see the updated description when hovering my mouse to the red dot on the leaderboard.
Screen Shot 2024-08-04 at 12 03 46 PM

**Comment by ZhangPeizhou** [comment]
> 5

Hello, I double-checked the code, and I think the location of where the text pops out is related to the size of the browser and the dot location on the web page. It should be fine, as long as the function works properly.

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as described.
Screenshot 2024-08-04 at 6 36 57 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
