### PR TITLE
Sam lint fix summary bar

### PR DESCRIPTION
**Pull request by samarth9201**
# Description
Fixed Linting errors in **src/component/Header/**** and **src/component/SummaryBar/****

## Related PRS (if any):
This frontend PR is not related to backend PR.

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. Clear site data/cache
4. log as any user
5. The App should work as normal
6. Run npm run test to make sure all tests are passing.
7. Run `npm run lint`, you should not see any errors.
8. Verify that everything work as expected. Especially focus on the Summary bar on dashboard, everything should look and function as normal.

### CODE REVIEW

**Review by jinxyou — APPROVED** [review]
All test cases have passed. Flint doesn't return any error. Great job!
Screenshot 2024-11-08 235400
Screenshot 2024-11-08 235700

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the summary component works as expected and no issues.
All the test cases passed.
Screenshot 2024-11-09 at 5 25 09 AM
Screenshot 2024-11-09 at 5 28 04 AM

**Comment by EvianTan** [comment]
lint fix with no errors, however local running unit tests did have failures.
image

**Review by audreydieuanh — CHANGES_REQUESTED** [review]
There are no errors when running npm run lint. However, there are a lot of local test errors when running npm run test.

test8

**Comment by anji-annavarapu** [comment]
There are no errors when running npm run lint. However, there are a lot of local test errors when running npm run test.

Screenshot 2024-11-09 230153

**Review by anirudhsk2107 — APPROVED** [review]
The app is working properly 

Screen Shot 2024-11-13 at 1 59 23 PM
Screen Shot 2024-11-13 at 2 01 03 PM

Screen Shot 2024-11-13 at 1 52 58 PM

**Comment by SatyashanthiT** [comment]
I tested this PR and confirmed that the lint fixes are working as expected. The Summary Bar on the dashboard displays correctly, with no errors in functionality. All tests and lint checks passed successfully, ensuring stable performance.

image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (242)

**Comment by EvianTan** [comment]
Run lint check and the test, no issue. Going to approve and merge this PR.
image

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
