### PR TITLE
Aaron new scripts for lint and lint:fix

### PR DESCRIPTION
**Pull request by AaronPersaud**
# Description
Currently our linting command `npm run lint` does not check all of the files. I have added some flags that make sure all necessary files are checked so any files with linting errors will not pass the checks to merge.

## Related PRS (if any):
N/A

## Main changes explained:
- added flags that make sure eslint checks both `.js` and `.jsx` files
- also added these flags to lint:fix command

## How to test:
1. check into current branch
2. do `npm install` 
3. run `npm run lint` and make sure it passes (nothing should happen)
4. remove one of the component folders from `.eslintignore` (ex. `src/components/SetupProfile/**`)
5. run `npm run lint` again and verify the lint errors show up
6. run `npm run lint:fix` and make sure the number of lint errors go down
7. revert the changes (can be done manually or using `git reset --hard`)

## Screenshots or videos of changes:

Running `npm run lint`

image

Running `npm run lint:fix`

image

### CODE REVIEW

**Review by iTvX — APPROVED** [review]
I approved your pull request

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/69b0ae51-3fe3-42d1-acf2-3694ff0111a5

**Comment by Shreyj14** [comment]
Hi @AaronPersaud I tested the PR and it works as intended. The number of errors go down once i run lint fix. 
Screenshot 2023-09-15 at 5 05 38 PM
Screenshot 2023-09-15 at 5 05 18 PM
Screenshot 2023-09-15 at 5 04 43 PM

**Review by Shreyj14 — APPROVED** [review]

**Review by DavidC0126 — APPROVED** [review]
Hi @AaronPersaud I tested the PR and it works as intended.
before_fix
after_fix

**Review by robertoooc — APPROVED** [review]
Hi @AaronPersaud, I tested your changes to the new run lint script and it indeed does lint all the files within a folder, both jsx and js files. The lint:fix command also does run across multiple files within a given folder. 
Screenshot 2023-09-15 at 6 45 36 PM
Screenshot 2023-09-15 at 6 46 17 PM

**Review by ramyaram2092 — APPROVED** [review]
Nice Work Aaron. This will be very useful for us . I checked this with a  component that had both *.jsx and *.js file
**your branch :**
image

**Development branch :**
image

**Review by zuhang2000 — APPROVED** [review]
This PR works as expected! I approved it.
1. npm run lint
Screen Shot 2023-09-16 at 4 02 42 PM


2. npm run lint:fix
The number of errors indeed goes down.
Screen Shot 2023-09-16 at 4 03 13 PM

**Review by gabi-lima — APPROVED** [review]
Working as expected! Well done. 
image

**Review by Haoj1 — APPROVED** [review]
@AaronPersaud The errors go down after running link fix. The changes look good to me

**Review by Chris33871 — APPROVED** [review]
Hi @AaronPersaud ,

I've reviewed the changes and it works well on my end 👍 

PR1306-1
PR1306-2
PR1306-3

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR and it works as expected.

npm run lint

Screenshot 2023-09-18 at 6 46 34 PM

npm run lint:fix

Screenshot 2023-09-18 at 6 46 56 PM

**Review by EvianTan — APPROVED** [review]

**Review by navneeeth — APPROVED** [review]
Hey @AaronPersaud! Tested your PR and it works as expected!

1. Running `npm run lint` before removing `src/components/App.jsx` from `.eslintignore` and observing no errors:
npm run lint before

2.  Running `npm run lint` after removing `src/components/App.jsx` from `.eslintignore` and observing 9 errors:
npm run lint after removing src components App dot jsx

3.  Running `npm run lint:fix` and observing 3 errors:
npm run lint fix

**Pull request merged**
