### PR TITLE
Nandini finishing for Nathalia fix project report UI issues

### PR DESCRIPTION
**Pull request by nathcarnevalli**
# Description
Fix PROJECT REPORT PAGE UI issues for 375px and up:
- When WBS is empty, the stub/placeholder does not function in dark mode.
- When 850px and below the title appears in the second row, we want it in the first.'
- Tasks table is out of view when 769px and below.
- The WBS and Members table don't have any side spacing when 415px and below.
- Tasks table header items overlap when between 851px and 1000px.

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Changed the following css files: ProjectReport.css, TasksDetails.css, TasksTable.css and ReportPage.css.
- Changed the following components: ProjectReport.jsx, TasksDetails.jsx, TasksTable.jsx, WbsTable.jsx, ReportPage.jsx and ReportBlock.jsx.

## How to test:
1. Check into current branch
2. Do `npm install` and `npm  run start:local` to run this PR locally
3. Clear site data/cache
4. Log as admin/owner user
5. Go to Dashboard→ Reports → Projects → Select a project → Follow the steps below
6. Verify if the stub/placeholder works in dark mode
7. Verify if when 850px and below the title appears in the first row
8. Verify if when 769px and below tasks table isn't out of view
9. Verify if WBS and Members table have side spacing when 415px and below
10. Verify if Tasks table header items don't overlap when between 851px and 1000px

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/282e9627-67f8-42e3-819b-7c9ddef75c7c

## Note:
...

### CODE REVIEW

**Review by Nahiyan-16 — APPROVED** [review]
Hi @nathcarnevalli, awesome work on this. I went through the checklist and everything seems to be in order. The code is neat and clean. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/b2c607da-0f2a-4b9f-adeb-9b9a6ee0a272

**Review by vijay10pk — CHANGES_REQUESTED** [review]
Table headers are not responsive around 750px and also it's not scrollable. Please check the styling and update it. Please refer the below video for better understanding. But the other changes work as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/30d02164-e9a9-4712-89e1-992b4e2309c4

**Comment by nathcarnevalli** [comment]
Hi @vijay10pk thank you for your review, but your suggestion is out of the scope of this task.

**Comment by vijay10pk** [comment]
> Hi @vijay10pk thank you for your review, but your suggestion is out of the scope of this task.

Then I will approve the PR now. Thanks.

**Review by vijay10pk — APPROVED** [review]

**Comment by nikethaanand** [comment]
All  changes are working as expected. All the styling and modes are working correctly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47215795/1678fad2-3a85-4823-8ce7-a5f4b36565f4

**Review by sahithidhulipala9 — APPROVED** [review]
Did all the above mentioned steps. Working perfect.
Video Link: https://www.loom.com/share/a3deff98e3c5411c993fb30447bca791

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good Work.

https://github.com/user-attachments/assets/ad897dcd-3c9e-4a23-a945-8f8071cf83c4

**Review by kdaga81 — APPROVED** [review]
image

I verified the expected behavior for all styling and dark/light mode. Everything working as expected!

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work for all the different screen sizes.

https://github.com/user-attachments/assets/9d4351e1-80c2-4592-aaa1-5789ba0ecec8

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi, 

I've tested your changes, please check point #3, the rest of them are working as expected

1. 850 px and below, the title appears the desired place
image
2. Plcaeholder looks good in WBS table
image
3. under 750px, the tasks table starts to get cut off, please recheck this.
image
4. The side spacing on WBS and Members table looks good under 415px
image
5. The task table items do not overlap, but the table gets cutoff
image

**Review by MinSun0814 — APPROVED** [review]
image

Works as intended

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.
PR 2441
PR 2441-1

Thank You

**Comment by nikhilgiri0226** [comment]
The changes were added in the new PR NandiniYelmela__fix_project_report_UI_issues #2480. So, after discussing with Jae, closing this PR.

**Pull request closed without merging**
