### PR TITLE
completed copy button for weekly summaries and user profile

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description
Created a copy button on the user's weekly summary and the weekly summary branch. 
Recreated this PR as the original one, won't load the weekly summaries, and had several changes, which came from the navbar disappearing. 

Screenshot 2023-10-12 at 8 35 43 PM

Please reviewing the original PR to test this one. 

Added a copy icon to user's profile component. When viewing weekly summaries admins can quickly copy and paste their team members summaries to speed up their managerial tasks.
Jae also suggested to add the icon to the weekly reports summary to view everyone's weekly summaries to counter-act the current bug. This way admins can copy weekly summaries there as well.

## Related PRS (if any):

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1166

## How to test:
check into current branch
do npm install and ... to run this PR locally
log as admin user or owner.
go to dashboard→ view profile → show weekly summary → select a team member.
View their weekly summaries and click on the copy button to copy their summary to your clipboard.
Verify clipboard has the exact text copied to your clipboard.
Repeat from steps 3 but navigate to dashboard→ reports → weekly summary reports → select a team member.
View their weekly summaries and click on the copy button to copy their summary to your clipboard.

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Iris-Song — DISMISSED** [review]
Hi, I have tested your PR, all things run well as expect. Both test cases can copy correct weekly summary. Good job!
Screenshot 2023-10-13 at 08 33 00

Screenshot 2023-10-13 at 08 33 50

Screenshot 2023-10-13 at 08 37 57

**Review by JeffLi117 — DISMISSED** [review]
Your changes work as expected - when navigating with either A) dashboard→ view profile → show weekly summary → select a team member or B) dashboard→ reports → weekly summary reports → select a team member, I am able to view the member's weekly summaries, use the copy button, then paste from my clipboard.

Route A:
image
image

Route B:
image
image

*(Probably?) outside of the scope of this PR, but might be important to address - if a paragraph of a user's weekly summary ends in a white space, that white space is preserved and displayed on the user's weekly summary (when viewing when the two routes mentioned above) as a "&nbsp;" (see image below - within the <p> tags). While I doubt this will happen often, it's still a tad unpleasant to see. It might be solved by trimming summaries before they are entered into the database, or when the data is fetched but before it is rendered.

image

Great job!

**Review by shubhankarval — DISMISSED** [review]
Hey @luisarevalo21, I have checked out all the given functionality of your PR locally, and it works perfectly. All the text is getting copied  in both test cases properly. Just a suggestion for the future, It would've been better told in the instructions that we had to create a new weekly summary, if one wasn't available to test. 
</br>
pr1
pr3
pr2

**Review by yi-lin-1234 — DISMISSED** [review]
Hello, I tested your PR and works as intended. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/27a8d44c-0992-4681-90df-39c8e39353b8

**Review by wantingxu7 — DISMISSED** [review]
Hi, I tested the PR, the functions work well as described. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/c440865b-697f-4743-8a54-f606456268f4

**Review by yangfan2001 — DISMISSED** [review]
Hi, I have reviewed and tested your PR. Everything works as expected, and the copy button functions well. Great job!
image
image

**Comment by mounica-dingari-by** [comment]
Hi @luisarevalo21 , your works as intended. Good work!

Screenshot from 2023-10-13 20-06-08
-d3954a182ff6)

**Review by vikrambadhan — COMMENTED** [review]
Hi, I tested your PR according to the instructions given, however, I wasn't able to view any summary to copy on  the 'Weekly Summaries Report" page

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/9877beba-cf24-493a-85ff-be9cfa7e3771

**Review by Sssky-18 — DISMISSED** [review]
Hi @luisarevalo21, I tested this PR, and it worked as intended. For both ways, the summary can be displayed properly, and the copy button is clickable. The summary can be copied and pasted correctly. Thank you for your hard work! 
PR#1408
PR#1408_2

**Review by JYXiao-2021 — DISMISSED** [review]
Hi, I test this pr and it works as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/9dee0f26-0499-493b-9a6f-fd451d95e642

**Review by StrawberryCalpico — DISMISSED** [review]
Hi I tested your PR, it worked as expected.
Screenshot 2023-10-14 at 4 07 20 PM
Screenshot 2023-10-14 at 4 07 33 PM

**Review by Cloid — DISMISSED** [review]
Hi there.

I tested the following cases;
- Admin submitting weekly summary, navigating to the same profile, using copy button and pasting in a separate file
- Volunteer profile same steps as above
-  Viewing a separate user (Admin -> Volunteer or Volunteer -> Admin) profile, viewing their weekly summary and copy/pasting it.

It passed all these cases and works fine. Good job.

Attached is video of me testing the first case:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/e0bb77a2-a7c8-45bd-87e8-1c6aa1248663

**Review by TuanDinh140194 — APPROVED** [review]
Hi! The PR works as expected. After go to view profile and show weekly summary, I click the copy button and paste it to google translate. It work as expected. For the other cases, I go to weekly summary report page, the page get slow loadings, but after wait around 15 seconds, I can reach the copy button and it works as describe.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/39382c83-e961-446f-9202-5615e84fa0e0

**Comment by John-Flavian** [comment]
Great work @luisarevalo21 .

**Comment by emunkh404** [comment]
I tested the branch copy button for weekly summaries and user profile #1408, and your changes work as expected. When navigating with either A) dashboard → view profile → show weekly summary → select a team member or B) dashboard → reports → weekly summary reports → select a team member, I am able to view the member's weekly summaries, use the copy button, and then paste from my clipboard

image
image

**Review by lacnoskillz — DISMISSED** [review]
Hey @luisarevalo21 !
I pulled your code and tested it locally and can see that the changes you made work as intended. I can now copy weekly summary's! Nice work!
image

this is the pasted code after copying!
TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY TEST SUMMARY

**Comment by luisarevalo21** [comment]
> Your changes work as expected - when navigating with either A) dashboard→ view profile → show weekly summary → select a team member or B) dashboard→ reports → weekly summary reports → select a team member, I am able to view the member's weekly summaries, use the copy button, then paste from my clipboard.
> 
> Route A: image image
> 
> Route B: image image
> 
> *(Probably?) outside of the scope of this PR, but might be important to address - if a paragraph of a user's weekly summary ends in a white space, that white space is preserved and displayed on the user's weekly summary (when viewing when the two routes mentioned above) as a " " (see image below - within the
> 
> tags). While I doubt this will happen often, it's still a tad unpleasant to see. It might be solved by trimming summaries before they are entered into the database, or when the data is fetched but before it is rendered.
> 
> image
> 
> Great job!

Hello @JeffLi117  great catch! 
I adjusted the regex expression to remove the new line as well. 

Thanks!

**Comment by luisarevalo21** [comment]
> Hi! The PR works as expected. After go to view profile and show weekly summary, I click the copy button and paste it to google translate. It work as expected. For the other cases, I go to weekly summary report page, the page get slow loadings, but after wait around 15 seconds, I can reach the copy button and it works as describe.
> 
>  HGN.APP.-.Google.Chrome.2023-10-14.17-21-33.mp4

Hello make sure the user' you are testing has a weekly summary submitted and if so, make sure you are selecting this week instead of last week. Or whenever the weekly summary was submitted. 
As for the slow loading, I didn't touch that component and does take a while to load. Please be patient for it to load. 

Thanks. Feel free to reach out with any questions.

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-10-20 212916
Screenshot 2023-10-20 212954
Screenshot 2023-10-20 213240

**Review by Shubhu0 — DISMISSED** [review]
Hi @luisarevalo21 tested the PR and it is working as intended. Was able to copy anyone summary and the contents did not change when pasted onto MS Word. Great work

image
image

**Comment by RheaWu1212** [comment]
Everything works as expected, great job!
Screen Shot 2023-10-21 at 10 58 50

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions. The copy icon is shown correctly next to the weekly summary report.
I also test the copy functionality and paste it. It seems to me that everything is pasted good.
Screenshot 2023-10-22 at 1 02 16 AM
Screenshot 2023-10-22 at 1 01 05 AM
Screenshot 2023-10-22 at 1 03 42 AM
Screenshot 2023-10-22 at 1 04 03 AM

**Review by JeffLi117 — APPROVED** [review]
Here I have screenshots of when I copied the summary with the first method (dashboard→ view profile → show weekly summary → select a team member):
image

And the second method (dashboard→ reports → weekly summary reports → select a team member): 
image

Both methods yielded the same result, shown below:
image

Great job - no issues with white spaces!

**Comment by AnishPandita** [comment]
Hey tested the Pr and it seems to work perfectly as intended. The Placement of copy icon and its functionality looks good. Was able to copy correctly.
Screenshot 2023-11-11 at 12 17 28 PM
Screenshot 2023-11-11 at 12 18 42 PM

**Pull request merged**
