### PR TITLE
Anirudh unittest teamstab

### PR DESCRIPTION
**Pull request by belagaam**
# Description

Unit test case for TeamsTab component

## How to test:
1. check into the current branch
2. do `npm install`
3. run npm test TeamsTab.test.js
4. verify that all test cases pass.

## Screenshots or videos of changes:

Unit Test - TeamsTab

## Note:

Kindly take a look at the test cases and suggest if more validations can be added

### CODE REVIEW

**Review by curiousfancier — DISMISSED** [review]
test suite passed with all the test cases
image

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-04-27 at 9 38 57 PM

**Review by MinSun0814 — DISMISSED** [review]
Tested PR and all tests passed.
image

**Review by iTvX — CHANGES_REQUESTED** [review]
Your unit test part is good, but why do you also change the css while you don't even mention it. Also, please resolve the git conflicts. Thank you.

2024-04-30 at 08 36 30@2x

**Comment by beblicarl** [comment]
All test cases are great and all tests passed successfully

image

**Review by beblicarl — DISMISSED** [review]

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and it passed all the test cases. Please refer the screenshot attached.
PR 2202

**Review by dkt6 — APPROVED** [review]
All test cases are working as expected.
Thank you for the great work!

**Review by Ramaruva — APPROVED** [review]
I have run the given test cases in my local env and all test case have been passed
image

**Comment by belagaam** [comment]
> Your unit test part is good, but why do you also change the css while you don't even mention it. Also, please resolve the git conflicts. Thank you.
> 
> 2024-04-30 at 08 36 30@2x

**Comment by KaushikMreddy** [comment]
Hi, 
The test cases are all working
image

**Comment by belagaam** [comment]
> Your unit test part is good, but why do you also change the css while you don't even mention it. Also, please resolve the git conflicts. Thank you.
> 
> 2024-04-30 at 08 36 30@2x

The change was done by mistake, didn't now how that happened. I have fixed the issue now. Can you check it again?

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and it is working as intended. Please refer the screenshot attached.

PR 2202

**Review by peter6866 — APPROVED** [review]
All tests passed as expected.

image

**Review by JatinAgrawal94 — APPROVED** [review]
Tested the PR and all test cases have passed successfully.

**Review by shradac — APPROVED** [review]
All tests passed. The tests cover all specified scenarios. Good Work!

week1-17

**Review by deepthikannan — APPROVED** [review]
image
Reviewed your PR. All unit test cases passed.

**Review by shradac — APPROVED** [review]
All tests passed. The tests cover all specified scenarios. Good Work!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
