### PR TITLE
Kaushik - Finished Cheng-Yun Project.jsx Unit Test

### PR DESCRIPTION
**Pull request by DavidC0126**
# Description
Provide the unit test functions for Project.jsx

## Related PRS (if any):
N/A

## Main changes explained:
- Update Project.jsx for inserting data-test id
- Create Project.test.jsx

## How to test:

1. check into current branch
2. do `npm install`
3. `npm run test src/components/Projects/Project/Project.test.jsx`
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-11-29 at 10 39 12 PM

## Note:

### CODE REVIEW

**Review by sahilpatel18 — DISMISSED** [review]
Although I am encountering a console error, all test cases have passed successfully. Great work!

**Review by ZichanYang324 — DISMISSED** [review]
I have verified that all the test cases passed, and here is the test result
PR1610

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-01 at 10 30 10 PM
Good job @DavidC0126 ! All the test cases passed!

**Comment by belagaam** [comment]
All test cases passed

Cheng-Yun Project jsx Unit Test

**Review by scoopstroop92 — CHANGES_REQUESTED** [review]
Hello @DavidC0126  good job on the test cases. I still see the console error though 
image
image

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed! 

Week 15 - PR5

**Review by 666saofeng — APPROVED** [review]
Hi, all tests passed and it worked as intended.
image

**Comment by DragonSlayer2401** [comment]
All tests passed I don't see any issues please watch the video for more details

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/d8a475ea-a530-4740-8ce5-e7694df04c59

**Review by XiaohanMeng — APPROVED** [review]
All cases passed! Great Job!
PR1610 UnitTest result

**Review by KaushikMreddy — COMMENTED** [review]
Hi David, 

Ran your changes, no errors faced with running the test cases or the code. Simple and concise code as well.
image

**Review by Sandhya1236 — COMMENTED** [review]
All the test cases have passed. But has taken too long to execute.

image

**Review by peter6866 — DISMISSED** [review]
Great job on adding unit tests for Project.jsx! The PR looks solid and covers the necessary test cases. Here are the highlights:

✅ Project.jsx has been updated with data-test IDs, enabling effective testing of the component.

✅ Project.test.jsx has been created to house the unit test functions for Project.jsx.

Testing:
- I followed the provided testing steps and ran the command `npm run test src/components/Projects/Project/Project.test.jsx`.
- All tests passed successfully, indicating that the Project component functions as expected.
image

**Comment by ZhangPeizhou** [comment]
Passes all tests
PR#1610

**Review by Kavil-Jain-514 — DISMISSED** [review]
Passed all the test cases !!
image

**Review by JatinAgrawal94 — DISMISSED** [review]
All tests cases have passed as expected. Consider the screenshot attached.
Great work!
Screenshot 2024-06-06 at 6 19 56 PM

**Comment by akshit0211** [comment]
All test cases passed. Good job!

all test cases passed

**Review by akshit0211 — DISMISSED** [review]

**Review by deepthikannan — DISMISSED** [review]
image
All test cases passed.

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Ran the test cases and all have passed.
Screenshot 2024-07-06 190209

**Review by scoopstroop92 — DISMISSED** [review]
The error is gone. Good job . Approving on the same note 
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
