### PR TITLE
Zijie fix Fix team page formatting of Active and Members

### PR DESCRIPTION
**Pull request by iTvX**
# Description
CleanShot 2023-09-05 at 12 23 39@2x

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin or owner user
4. go to Other Links>Teams
5. check: Stuff below Active should be centered with no shadow. Stuff below Members should be centered with shadow.

Before:
CleanShot 2023-09-05 at 12 26 50@2x

After:
CleanShot 2023-09-05 at 12 33 17@2x

## Update
Shadow small box instead of the big box.

image

### CODE REVIEW

**Review by Haoj1 — APPROVED** [review]
@iTvX Good job! The active icon is centered
before

after

**Comment by Sssky-18** [comment]
Hi Zijie, I checked your code and compare the icons before and after. Your contribution works well, congrats!

I checked this through 3 ways: the first is to check the improved CSS on the active and member icons centered them and added the correct shadow. Then I compared the position of inactive icons, and your code worked well for them, too. Finally, I add a new team to see the format, and they are correctly centered. Therefore, I think your contribution on the format is efficient. Thank you!  

PRreview_#1265_before
PRreview_#1265_after

**Review by AriaYu927 — APPROVED** [review]
Hi @iTvX , I've tested this PR and it works as expected. Thank you!

截屏2023-09-06 10 32 30

**Review by luisarevalo21 — DISMISSED** [review]
Hello @iTvX,

I tested your PR and works as intended. Great work! 
I logged in as an owner and viewed the teams component. 
The active icon is centered and has no box shadow. 
the members icon is centered an has a box shadow around it. 

Screenshot 2023-09-05 at 8 02 10 PM

**Review by robertoooc — DISMISSED** [review]
Hi @iTvX, I tested your branch and it seems to have completed the required assignment. Everything seems to be centered well along with the shadow being fixed.
Your branch:
Screenshot 2023-09-05 at 8 36 39 PM

Development Branch:
Screenshot 2023-09-05 at 8 37 49 PM

**Review by harshidad — APPROVED** [review]
I tested your PR and changes looks good. 
PR#1265_After
PR#1265_Before

**Review by tsunami776 — APPROVED** [review]
I tested using an admin account, and it functioned as described in the PR. Now, the 'Members' column is centered and has shadows, while the 'Active' column is correctly centered without any shadows.

Before:

#1265before

After:

#1265after

**Review by navneeeth — APPROVED** [review]
Hello, @iTvX! I tested your changes and it LGTM! Good work! The items placed below the 'Active' column header are centered with no shadow. And as intended, the items placed below the 'Members' column header are centered with shadow.

Before the fix:
before

After the fix:
after

**Comment by one-community** [comment]
Thank you everyone, merging!!

**Pull request merged**
