### PR TITLE
Luis edit warning description

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description
Allow owners to edit a current warning description. 
Only owners are able to edit a warning description. 
Upon editing a warning the remaining warnings become uneditable until save is triggered.

## Related PRS (if any):
This frontend PR is related to the #[806](https://github.com/OneCommunityGlobal/HGNRest/pull/806) backend PR.

## Main changes explained:
- Inside of `WarningTrackerModal.jsx` I changed the p tag to input passing the styles and added the functionality needed.
- The functionality allows owners to edit by changing the same.
- Next a save button was added to trigger the actual save and put action sending the data to the backend.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log in as an owner account
4. Upon loading, click the "+/-" button to load all the current warnings. 
5. Upon loading, create a test, warning and submit it. 
6. Click the newly created warning, and edit it. 
7. Once edited, click the 'save' button to send the updated warning. 
8. View the user's warnings and should display the newly edited warning. Also, the `WarningTrackerModal.jsx`will have the updated list as well. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/fbbfc65f-10ca-492f-8a3c-52b4393cd3e5

## Note:
Include the information the reviewers need to know.
There is a bug, which when creating a new warning, it doesn't allow you to add spaces, I'll fix the issue in this PR #2037

### CODE REVIEW

**Review by Abi-Liu — CHANGES_REQUESTED** [review]
EDIT: You also linked the wrong related PR. the link points to PR 806 in the Frontend repo rather than the Backend.

Hey Luis! Overall the changes work as expected. When editing a warning it correctly updates the info in the database and is reflected in the list of warnings. However, I did notice you were trying to implement drag and drop functionality with the packages you installed, but it doesn't quite seem to be working.

This isn't a huge deal to be honest and it would be fine without it, but if you wanted to get it to work that would be a nice little feature too. If you end up not wanting to do it maybe we can just remove the packages.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/d0053b7e-8feb-4ee5-81ed-1338b09bf6bc

**Review by meetpadhiar4 — CHANGES_REQUESTED** [review]
Hi, I tested your PR and while editing the warning it is giving a request failed error. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/6bde272a-f69b-4c26-998a-339eb2ad9fe8

**Comment by luisarevalo21** [comment]
> EDIT: You also linked the wrong related PR. the link points to PR 806 in the Frontend repo rather than the Backend.
> 
> Hey Luis! Overall the changes work as expected. When editing a warning it correctly updates the info in the database and is reflected in the list of warnings. However, I did notice you were trying to implement drag and drop functionality with the packages you installed, but it doesn't quite seem to be working.
> 
> This isn't a huge deal to be honest and it would be fine without it, but if you wanted to get it to work that would be a nice little feature too. If you end up not wanting to do it maybe we can just remove the packages.
> 
>  video1232010502.mp4

Hello @Abi-Liu 
Thanks for your review and feedback. 
I fixed the link to correct backend. 
Next, I removed the packages which involved dragging the components. 
I was working on it, but realized it should be its own PR. I'll be working on it this upcoming week. 
Thanks again!

**Comment by luisarevalo21** [comment]
> Hi, I tested your PR and while editing the warning it is giving a request failed error. Please refer the video attached.
> 
>  Screen.Recording.2024-03-21.at.1.22.28.PM.mov

Hello @meetpadhiar4 
I replicated your steps and didn't see the 401 error. 
Please ensure you've checked into the correct backend and followed the steps. 
And followed the steps for this branch, by installing then running the frontend. 
Also, show your console so I can see the error that occurs. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/bfa50414-7286-4166-8b3d-86f974f00bdc

**Review by Pandani07 — DISMISSED** [review]
Tested! This PR works as intended, tested the backend as well. Please refer the video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/b68c9655-1cb0-4431-812f-8f5371714bd2

**Comment by Abi-Liu** [comment]
Hey @luisarevalo21. Just to make sure, did you do ```npm uninstall (package name)```? Because I still see the packages in the `package-lock.json`

**Comment by luisarevalo21** [comment]
> Hey @luisarevalo21. Just to make sure, did you do `npm uninstall (package name)`? Because I still see the packages in the `package-lock.json`

Hello @Abi-Liu 
I did now, before I just removed it from the package.json file. I was unaware you had to run npm uninstall. However, now it should be removed. Thanks for the suggestion.

**Review by Abi-Liu — DISMISSED** [review]
Gotcha. Looks good now!

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested you PR and it works as expected. Below is a video for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/f5bd64bd-5376-47a6-afd5-aa596703f482

**Review by aaryaneil — DISMISSED** [review]
The changes work as mentioned. Good work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/6d2a876f-f732-4b15-ab64-0214ff572cfb

**Review by SRamen1999 — COMMENTED** [review]
Everything works as expected. You can add, edit and delete warning trackers. However I encountered an error when clicking on a warning.

here is the error

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/07e378a5-b3a9-4230-8e68-4c416a1ed9fa


edit deleting and adding new warning

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/595f6bfc-5261-4a94-9076-8f287aa242b9

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account. Add, edit, delete and hide a newly created warning all worked. Good job!

**Note**: I see that deletion will show a Delete Successful confirmation notice. It may be better to have the same confirmation for Edit a warning. Currently after editing is done, the Save button appear. After clicking the Save button, nothing else would happen. So a line of confirmation may help.
This is the confirmation message I mentioned:
Screenshot 2024-04-11 at 8 26 33 PM

Other testing all went well:
Screenshot 2024-04-11 at 8 27 25 PM

**Review by metaphor987 — CHANGES_REQUESTED** [review]
Hi Luis,

I've tested the changes using an owner account. I can successfully add, edit and delete warnings. There's only one issue: When I "Add New Warning Tracker", I could not add space in the warning name. And when I'm trying to edit the existing ones' names, space can be added. Everything else looks great.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/223889a3-97fc-46e0-8293-45d93c5452d2



Note: A small suggestion: It may be better to keep the "Current Warning Descriptions" tab opening after clicking "Cancel" in the "Add New Warning Tracker" mode, instead of closing the whole tab. Because sometimes users may decide to not continue to add warning but still hope to edit other ones. 

Screenshot 2024-04-14 at 12 07 09 AM

Thank you!

**Review by Parth-tech — CHANGES_REQUESTED** [review]
Hey Luis,
The PR works as intended but there is one problem. For the warning name you `cannot type whitespace`.
Example:
- We cannot do this: `Need Space In Between`
- Instead we have to do this: 
   - Type: `NeedSpaceInBetween` --> Move cursor behind & add whitespace.

`What's causing the problem?`
- In file `src/components/Warnings/modals/WarningTrackerModal.jsx`, on `line 328` you are using `onChange` and on every change you are calling `handleChange`, in this function on `line 133` are using `.trim()` due to which `WhiteSpace is removed`. 

`Solution:`
- Call `handleChange` when user clicks on `Add Button`. But then you will have to add validation check; to ensure that user cannot submit a string comprising of only White Spaces.

Video Reference:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/9f67ecc2-aa7a-4cb8-9de8-9e8e99fa471c

**Review by Tiantian-C — COMMENTED** [review]
Most of the functions work well, but when I try to edit the warning, an error occured.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/6021e9fa-51fa-433b-8e10-6ff2056f2293

**Review by cgomezhub — CHANGES_REQUESTED** [review]
I think you're doing a good job!  The backend is responding well to the requests. However, there are a couple of things to consider before approving it:

When you deactivate an existing warning, it allows you to create another one with the same name. Then, you can activate the first existing warning name, resulting in two or more warnings with the same name. (look Carlos-Warning)

When an existing warning is active, it does not allow you to create another one with the same name (which is correct!). It would just be nice to have an alert or popup to show the user this error.

Screenshot 2024-05-07 053703
Screenshot 2024-05-07 060610

**Comment by KaushikMreddy** [comment]
Hi, verified edit warning title changes. The edit is working as expected and change is reflected immediately.

image
image
image

Checked for duplicates after edit, Warning is shown in console. 
image

Works perfectly!

**Review by nathcarnevalli — COMMENTED** [review]
It worked as expected, nice job :). I suggest adding a success message when a warning is edited. Additionally, the background color of the message could be green when a warning is edited or deleted to indicate success.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/aee01dc4-8aab-4edf-b9db-c42bfaa4c9a9

**Comment by luisarevalo21** [comment]
Hello All 

I've addressed issues that were brought up. 
Duplicates cannot be added, and case sensitivity is handled by storing all entries in lowercase. For example, "Test" and "test" will be treated the same in the database. The stored entries are then capitalized via CSS for display purposes. 
Also, I added a success message upon adding editing a warning. 
Lastly, I addressed the trimming issue and you can edit and add a warning with a space. 
If you can re-review that would be great 


@nathcarnevalli 
@cgomezhub
@Tiantian-C 
@Parth-tech 
@metaphor987 
@jennZhang93 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/fd525965-3b43-47d6-9284-7ef6c5d298cd

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by nathcarnevalli — CHANGES_REQUESTED** [review]
The success message when editing doesn't appear for me. Please see the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/bb39b8b6-5a32-4aae-8193-a569997e7e74

**Review by cvtqx — CHANGES_REQUESTED** [review]
I've tested this PR and the warning can be added, deleted and edited successfully. Duplicate title is not allowed and a toast is shown in case a title already exists.
I did not see a success toast after editing a warning. Other than that works great. 

See the screen recording:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/b1270545-286b-4422-9943-106d6904f8e1

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
