### PR TITLE
Anand_Implemented Task Deadline Count Update in Dashboard

### PR DESCRIPTION
**Pull request by anandsesha**
# Description
This PR updates the dashboard to accurately reflect task deadline counts when a task's hours suggestion is approved, ensuring that the red notification circle shows the correct count.
PR Description

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- `TaskEditSuggestionModal.jsx`: Checked the user role during the task edit suggestion approval process, ensuring only non-volunteer users can approve suggestions.
- `dashboardAction.js`: Dispatched the incrementDashboardTaskCount action to update the task count upon approval.
- `dashboardReducer.js`: Handled INCREMENT_DASHBOARD_TASK_COUNT action to update the task count in the Redux state.
- `TeamMemberTask.jsx`: Accessed the updated task count from the Redux state and rendered the incremented count in the red circle.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. Add a task and assign it to different accounts to test
6. Go to dashboard→ Tasks→ Select that task→ Click Suggest and Update
7. After Updating  the suggestion can be viewed on the Task Edit Suggestion page (click on the red circle in the header)
8. On this page, click View Suggestion and Approve the changes.
9. Navigate back to the Dashboard and check if that task has the count incremented, which is the number displayed inside the red circle next to it.
10. Test the same with a Volunteer user and you should be able to suggest but no option to approve or see the count next to the task.

Follow the video below.

## Screenshots or videos of changes:
[https://www.loom.com/share/b5bb1a550ade42b7b30dafd37fd9b75c?sid=a88eb981-a215-45c4-a480-8c62137c82cd](https://www.loom.com/share/b5bb1a550ade42b7b30dafd37fd9b75c?sid=a88eb981-a215-45c4-a480-8c62137c82cd)

## Note:
Please note these warnings/errors are not related to this PR
Screenshot (1013)

### CODE REVIEW

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected.

https://github.com/user-attachments/assets/6f061c0e-3ed4-466a-a149-f7bc1d28b38d

**Review by Pranay-ai — COMMENTED** [review]
Hey @anandsesha 
I have reviewed the PR it's working as expected, please find the video below

https://github.com/user-attachments/assets/d265282a-427a-4578-89e4-7449b6b3ab78

Thank You

**Review by Pranay-ai — DISMISSED** [review]

**Review by preethamdnr — DISMISSED** [review]
Hello Anand,

I have reviewed  this PR and it working as expected and mentioned in the description.

image
image
image

**Review by SnelPatare — APPROVED** [review]
Working as expected.. Nice work!!
image
image

image

**Review by Lemonnycodes — DISMISSED** [review]
Hi,

I have tested the PR and it works as expected 

- Added and assigned tasks to multiple accounts.
- The "Suggest and Update" functionality works as expected; the suggestion is viewable on the Task Edit Suggestion page.
- The ability to view and approve suggestions is correctly limited to the admin/owner user role.
- The task count increment functionality is accurate upon suggestion approval.
- Verified that a Volunteer user can suggest changes but cannot approve or see the task count.

Screenshots:
PR 2547 (1)
PR 2547 (2)
PR 2547 (3)
PR 2547

**Review by Parth-tech — DISMISSED** [review]
Hi Anand,
The PR works well and the codebase looks great too.

Scenarios covered:
The owner account is able to offer suggestions and also approve/reject them. 
The volunteer account is able to see the approved changes. 
The volunteer can simply offer suggestions but cannot approve/reject them.

`Image References:`
Screenshot 2024-08-22 at 11 28 06 PM
Screenshot 2024-08-22 at 11 28 55 PM
Screenshot 2024-08-22 at 11 29 05 PM
Screenshot 2024-08-22 at 11 29 32 PM
Screenshot 2024-08-22 at 11 30 04 PM
Screenshot 2024-08-22 at 11 32 19 PM
Screenshot 2024-08-22 at 11 32 54 PM

**Comment by FayeLV** [comment]
Hi,

The PR is functioning as expected, and the codebase appears to be in excellent shape.
The owner account can both suggest changes and approve or reject them.
The volunteer account can view the approved suggestions.
Volunteers can make suggestions but do not have the authority to approve or reject them.
References:
Snipaste_2024-08-28_18-02-42
Snipaste_2024-08-28_18-06-39
Snipaste_2024-08-28_18-20-04
Snipaste_2024-08-28_18-20-53
Snipaste_2024-08-28_18-23-14
Snipaste_2024-08-28_18-23-39
Snipaste_2024-08-28_18-25-42

**Review by FayeLV — DISMISSED** [review]

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and everything working as expected. 

Screenshot 2024-09-05 170622

https://github.com/user-attachments/assets/0f34ddb2-13c4-4e07-b101-2543856151ea

**Review by vedantg24 — DISMISSED** [review]
Tested the PR, and the changes are working as expected. When the suggestion is accepted, the task has the count incremented successfully. Also, tested with volunteer, and there is no option to approve as well as no count next to the task 

Screenshot 2024-09-05 at 1 22 24 PM
Screenshot 2024-09-05 at 1 23 09 PM
Screenshot 2024-09-05 at 1 23 31 PM
Screenshot 2024-09-05 at 1 24 09 PM

**Review by ashayk9 — APPROVED** [review]
I have reviewed the PR it's working as expected.
Screenshot 2024-09-05 at 12 31 59 PM
Screenshot 2024-09-05 at 12 32 51 PM
Screenshot 2024-09-05 at 12 35 22 PM

**Review by swaroop-2007 — APPROVED** [review]

**Comment by swaroop-2007** [comment]
@anandsesha 
I checked the changes you have made to the code. I checked all the features, and everything is working as expected. 
Screenshot (352)
Screenshot (353)
Screenshot (354)


This is the dashboard of the Volunteer Account after editing the task:
Screenshot (355)

**Comment by sud306** [comment]
Hello,
I reviewed this PR and it's working as expected.


7  PR2547_1
7  PR2547_2
7  PR2547_3
7  PR2547_4

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

PR 2547
PR 2547-1

Thank You

**Review by yashwanth170 — APPROVED** [review]
Hello Anand,

Everything is working as expected.
Task_edit1
task_edit2

**Comment by saurabhshetty29** [comment]
Tested the PR, and everything is working as expected.
Screenshot 2024-09-11 at 12 00 43 AM

**Comment by SFA23SCM35V** [comment]
Testing the branch and working fine

PR1
pr2
pr3
pr4
pr5

**Review by crystallow1168 — DISMISSED** [review]
Hi @anandsesha,

The changes are working as expected (refer to the clip below):
User with volunteer role:
✅ Volunteer user can only suggest changes and have no other options to approve the suggested changes
✅ Volunteer user does not have red circle when there's a new suggestion
✅ Volunteer user can view the approved suggested changes when clicked on the red bell

User with Admin role:
✅ Admin user can view the suggestions and approve the changes
✅ Admin user has the number increment with red circle (left of Dashboard) when there is a new suggestion on a task
image
✅ Admin user can view the approved suggested changes when clicked on the red bell


https://github.com/user-attachments/assets/09addda1-d842-4cd8-8f1f-af9c296668b7

---

Observation: It may not be in current fix scope, I found that the end date displayed on the suggesting a change on the  task pop up form is not correct. (refer to image below)
image

**Review by SFA23SCM35V — APPROVED** [review]
PR2

**Review by Shreyav2000 — DISMISSED** [review]
I was testing this PR but couldn’t see the View Suggestions option, which led to encountering errors. I made sure to check out the dev branch on the backend and pulled the latest changes, but the functionality didn’t work as expected.

I’ve attached a screenshot for reference to help identify the issue.

Screenshot 2024-09-13 at 9 35 10 PM

**Review by sam19981 — APPROVED** [review]
Changes are working as expected but need to refresh the screen to view the notifications and suggestion updates.

Screenshot 2024-09-15 at 12 59 49 AM
Screenshot 2024-09-15 at 1 01 16 AM
Screenshot 2024-09-15 at 1 04 07 AM
Screenshot 2024-09-15 at 1 04 37 AM
Screenshot 2024-09-15 at 1 05 50 AM

**Review by nishitag5 — APPROVED** [review]
I reviewed this PR and it's working as expected.

https://github.com/user-attachments/assets/11075ec9-126d-4a86-a314-5c43284502bf

**Review by nevatiarishabh — COMMENTED** [review]
Everything is working as expected. I have checked the changes.

Screenshot 2024-09-25 at 3 46 12 PM
Screenshot 2024-09-25 at 4 04 31 PM
Screenshot 2024-09-25 at 4 07 15 PM

**Review by mrinalini-raghavendran19 — APPROVED** [review]
Looks good to me!

The changes work as expected. I have tested the PR using the following steps - 

1. Added tasks to an existing project and delegating resources to the same
2. Logged in from an admin account and ensured I could suggest, update and approve/ reject changes suggested to the tasks either by self or volunteer accounts
3. Logged in from a volunteer account and suggested changes but cannot approve/ reject those changes
4. Verified those changes have been reflected from volunteer accounts on admin account 
5. Verified the notification circle appears on updates to task

https://github.com/user-attachments/assets/324cf910-06a0-4334-b2bc-5ea1d71f200f

Great work!

**Review by khushijain03 — APPROVED** [review]
Hi @anandsesha , 
The PR works as expected, tested for both owner/admin account , volunteer account.


https://github.com/user-attachments/assets/a6cb8a16-5a9b-4de9-9d60-68b77cec6748

https://github.com/user-attachments/assets/d32acc71-3ae2-4640-93cf-8fc6ece155b8

**Review by AshritaCherlapally — COMMENTED** [review]
I have checked in to the current branch, but for some reason the "suggest" button is not showing it up for me.

PR#2547

PR#2547 copy

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
