### PR TITLE
Nathan separate edit time entry permissions

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR divides the `editTimeEntry` permission into several subpermissions controlling each part which can be edited (date, isTangible, time, and description).

## Related PRS (if any):
This frontend PR is related to the #[924](https://github.com/OneCommunityGlobal/HGNRest/pull/924) backend PR.

## Main changes explained:
- Added permissions to `PermissionsConst.js`
- Replaced `editTimeEntry` with `editTimeEntryTime`, `editTimeEntryDescription`, `editTimeEntryDate`, `editTimeEntryToggleTangible` (change tangibility for other users' time entries), and `toggleTangibleTime` (change tangibility for own time entries)

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links→ Permissions Management → Manage User Permissions
6. grant a volunteer account one of the listed permissions individually (`editTimeEntryTime`, `editTimeEntryDescription`, `editTimeEntryDate`, `editTimeEntryToggleTangible`, and `toggleTangibleTime`)
7. login to your volunteer account in an incognito window (so you can stay logged in with your owner account)
8. test the granted permission with volunteer
10. logout as volunteer
11. repeat steps 6-10 for each permission

## Notes
Check the Permissions Management spreadsheet or the descriptions in the Permissions Management Page for desired behaviors of permissions
https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit#gid=0

### CODE REVIEW

**Comment by Ramaruva** [comment]
Hi @nathanah  can you please explain more about how to test the give permissions for volunteer account I mean in volunteer account profile specifically where should I need to look those changes as I am new to the team so can you please specifically mention what changes can I expect in volunteer account Thank you!

**Comment by nathanah** [comment]
> Hi @nathanah can you please explain more about how to test the give permissions for volunteer account I mean in volunteer account profile specifically where should I need to look those changes as I am new to the team so can you please specifically mention what changes can I expect in volunteer account Thank you!

On the dashboard under Tasks and Timelogs, the Tasks tab can be used to view other people's time entries on your team when you click the 1-7 days button filters (showing time entries within the last 1-7 days). Under the Current Week Timelog tab, you can see all of your own time entries for this week. 
image

**Review by nathcarnevalli — COMMENTED** [review]
I'm not sure if it's realated to the task, so correct me if I'm wrong.

1- I need to clear the form manually every time, so it looks like that the 'Clear Form' button is not working right.

2- I can change the project/task field even if I don't have permissions to change my tasks because the edit button still appears on the page.

Screenshot 2024-05-10 090830

Screenshot 2024-05-10 091745

Screenshot 2024-05-10 091804

3- I edited the time, but my Total Tangible Hours was not updated on the view profile > volunteering times.

Screenshot 2024-05-09 160448

**Comment by nathanah** [comment]
> I'm not sure if it's realated to the task, so correct me if I'm wrong.
> 
> 1- I need to clear the form manually every time, so it looks like that the 'Clear Form' button is not working right.
> 
> 2- I can change the project/task field even if I don't have permissions to change my tasks because the edit button still appears on the page.
> 
> Screenshot 2024-05-10 090830
> 
> Screenshot 2024-05-10 091745
> 
> Screenshot 2024-05-10 091804
> 
> 3- I edited the time, but my Total Tangible Hours was not updated on the view profile > volunteering times.
> 
> Screenshot 2024-05-09 160448

1. Unrelated issue I think.
2. You're also able to edit the description and project within a day of the time entry's date so people can correct their own minor errors. After a day, the permissions are required. You can edit the date to be earlier to test this.
3. Also unrelated I think. This is probably related to @wang9hu's refactor?

**Comment by nathanah** [comment]
> > > Hi @nathanah can you please explain more about how to test the give permissions for volunteer account I mean in volunteer account profile specifically where should I need to look those changes as I am new to the team so can you please specifically mention what changes can I expect in volunteer account Thank you!
> > 
> > 
> > On the dashboard under Tasks and Timelogs, the Tasks tab can be used to view other people's time entries on your team when you click the 1-7 days button filters (showing time entries within the last 1-7 days). Under the Current Week Timelog tab, you can see all of your own time entries for this week. image
> 
> Hey just to clarify that I understand properly image
> 
> in given sc according to the permission given user can edit his time log is that correct can please clarify me and sorry for asking you again and again

Yes, that is the relevant button to open the edit modal. Read lines 61-70 in the linked spreadsheet for information on which fields each individual permission should be able to edit.

**Review by nathcarnevalli — DISMISSED** [review]

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi @nathanah , 

I've tested all the permissions, I found some issues with some of them.

1. `editTimeEntryTime, editTimeEntryDescription`, These 2 permissions do not have any effect at all. Adding them to a volunteer account and removing them did not change anything. I was still able to edit the time and description of the time entry
2.  `editTimeEntryDate, toggleTangibleTime`, These 2 permissions are working. I checked them before and after adding the permissions. These action are disabled before having permission and are enabled once given the permission.
3. `editTimeEntryToggleTangible `, This permission I believe, is set on a higher level than a Volunteer account only, can you please check whether this permission can be given to a volunteer account? I believe that a Volunteer account should not be able to validate the time entries of others at all. So this option would not be given to some account on a account type level itself. 

Here are some images of point 1 and 2

Before Permissions:
image
image


After permissions:
image

image

As you can see, In both the Before and After images, Edting the Time and Description is possible, regardless of permissions.

I've used my Owner account and Volunteer Account to test these changes.

**Review by Sandhya1236 — DISMISSED** [review]
I checked out the current branch, ran npm install and necessary commands to set up the PR locally, and cleared the site data/cache. As the owner user, I navigated to Dashboard → Other Links → Permissions Management → Manage User Permissions. I granted a volunteer account each of the listed permissions (editTimeEntryTime, editTimeEntryDescription, editTimeEntryDate, editTimeEntryToggleTangible, and toggleTangibleTime) individually. I logged into the volunteer account in an incognito window and tested each granted permission successfully. After logging out of the volunteer account, I repeated this process for each permission. All tests were successful, confirming that the permission management functionality works as intended.


image
image

**Comment by nathanah** [comment]
> Hi @nathanah ,
> 
> I've tested all the permissions, I found some issues with some of them.
> 
> 1. `editTimeEntryTime, editTimeEntryDescription`, These 2 permissions do not have any effect at all. Adding them to a volunteer account and removing them did not change anything. I was still able to edit the time and description of the time entry
> 2. `editTimeEntryDate, toggleTangibleTime`, These 2 permissions are working. I checked them before and after adding the permissions. These action are disabled before having permission and are enabled once given the permission.
> 3. `editTimeEntryToggleTangible `, This permission I believe, is set on a higher level than a Volunteer account only, can you please check whether this permission can be given to a volunteer account? I believe that a Volunteer account should not be able to validate the time entries of others at all. So this option would not be given to some account on a account type level itself.
> 
> Here are some images of point 1 and 2
> 
> Before Permissions: image image
> 
> After permissions: image
> 
> image
> 
> As you can see, In both the Before and After images, Edting the Time and Description is possible, regardless of permissions.
> 
> I've used my Owner account and Volunteer Account to test these changes.

1. Can you recheck this? You should still be able to edit the description within the same day and the time for intangible entries.
3. The logic needs to be completely implemented using permissions with no references to specific roles such that new roles can be created or modified in the future and the permission can be granted to individual accounts.

**Review by KaushikMreddy — DISMISSED** [review]
I tested #1, the changes are working as you've mentioned. My test account is a little slow, but it works.

**Review by Kavil-Jain-514 — DISMISSED** [review]
Everything worked great. The review is given in the backend PR 
https://github.com/OneCommunityGlobal/HGNRest/pull/924#pullrequestreview-2086924849

**Review by Parth-tech — DISMISSED** [review]
Hey Nathan,
The PR works as intended. The volunteer account is able to edit field as per the permission assigned. Upon removal of the permission the volunteer looses rights to edit the corresponding data fields. Great job!

I will attach a few screenshots for reference:

- Tangibility:
Screenshot 2024-05-31 at 3 50 29 PM
Screenshot 2024-05-31 at 3 50 38 PM

- Work Hours:
Screenshot 2024-05-31 at 3 53 34 PM
Screenshot 2024-05-31 at 3 53 52 PM

**Review by peter6866 — CHANGES_REQUESTED** [review]
Great work on refactoring and splitting the `editTimeEntry` permission into more granular subpermissions! 

✅ **PermissionsConst.js:**
    - Verified the successful addition of the new permissions: `editTimeEntryTime`, `editTimeEntryDescription`, `editTimeEntryDate`, `editTimeEntryToggleTangible`, and `toggleTangibleTime`.

✅ **Permission Replacement:**
    - Confirmed that the broad `editTimeEntry` permission has been correctly replaced with the new subpermissions.

✅ **Functionality (Partial):**
    - Tested and verified the functionality of four permissions:
        - ✅ `editTimeEntryTime`
        - ✅ `editTimeEntryDescription`
        - ✅ `editTimeEntryDate`
        - ✅ `toggleTangibleTime`
    - Confirmed that volunteer accounts can successfully modify time entries according to the granted subpermissions.

❌ **Functionality (Partial):**
    - Identified an issue where the `editTimeEntryToggleTangible` permission is not applied to volunteer accounts as intended because the volunteer account cannot view others time logs.

✅ **Testing Instructions:**
    - Followed the clear and comprehensive instructions to successfully test the changes locally.

https://www.loom.com/share/c0b768e785aa45f580cee5953039ad07?sid=4e799fc7-a8ff-4829-aead-f184e3364ebc

**Comment by nathanah** [comment]
> Great work on refactoring and splitting the `editTimeEntry` permission into more granular subpermissions!
> 
> ✅ **PermissionsConst.js:** - Verified the successful addition of the new permissions: `editTimeEntryTime`, `editTimeEntryDescription`, `editTimeEntryDate`, `editTimeEntryToggleTangible`, and `toggleTangibleTime`.
> 
> ✅ **Permission Replacement:** - Confirmed that the broad `editTimeEntry` permission has been correctly replaced with the new subpermissions.
> 
> ✅ **Functionality (Partial):** - Tested and verified the functionality of four permissions: - ✅ `editTimeEntryTime` - ✅ `editTimeEntryDescription` - ✅ `editTimeEntryDate` - ✅ `toggleTangibleTime` - Confirmed that volunteer accounts can successfully modify time entries according to the granted subpermissions.
> 
> ❌ **Functionality (Partial):** - Identified an issue where the `editTimeEntryToggleTangible` permission is not applied to volunteer accounts as intended because the volunteer account cannot view others time logs.
> 
> ✅ **Testing Instructions:** - Followed the clear and comprehensive instructions to successfully test the changes locally.
> 
> https://www.loom.com/share/c0b768e785aa45f580cee5953039ad07?sid=4e799fc7-a8ff-4829-aead-f184e3364ebc

Volunteers can see timelogs from people on their team just like other roles can. You click the little checkbox next to Tangible: and it should work fine.
image
image

**Review by peter6866 — DISMISSED** [review]
Changes work as expected.

**Review by JatinAgrawal94 — DISMISSED** [review]
1) Checked out current branch
2) Cleared Site data/cache
3) Logged in as owner user
4) Go to dashboard→ Other Links→ Permissions Management → Manage User Permissions
5) Granted a volunteer account one of the listed permissions individually (editTimeEntryTime, editTimeEntryDescription, editTimeEntryDate, editTimeEntryToggleTangible, and toggleTangibleTime)
6) Logged Into a Volunteer Account and tested the functionalities.

Everything works good.Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/04e7d69b-10c1-4fa0-9400-726c6f247f83

**Review by CloudyZ524 — APPROVED** [review]
Hi Nathan,
I've followed along your instructions to test the functionalities of this pull request. 
Firstly, I added permission of editTimeEntryTime, editTimeEntryDescription, editTimeEntryDate, editTimeEntryToggleTangible and toggleTangibleTime to a volunteer user. Then login to volunteer account to try all function about edit timelog which all worked well. 

My volunteer account seems start at today's date so I cannot change to any other date earlier or later. Except for this, everything works as expected. Great job!

Screenshot 2024-06-07 at 13 26 10
Screenshot 2024-06-07 at 13 27 53

**Review by ImzIssa — DISMISSED** [review]
I reviewed your PR and everything looks great.

**User can edit the date**
Screenshot (418)

**User can edit the time log**
Screenshot (416)

**User can edit the description**
Screenshot (417)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
