### PR TITLE
Shengjie unittest tinyce

### PR DESCRIPTION
**Pull request by ShengjieMao**
# Description
Created more unit test based on the previous unit test file for TinymceEditor component. Checked for the testing results.

## Related PRS (if any):
None

## Main changes explained:
- added test to check for unusual input length
- created test to see if the component can render properly when edge cases met

## How to test:
1. check into current branch
2. do `npm install` and `npm test TinymceEditor.test.jsx` to run this PR locally
3. Check if the tests passed or if anything else needed for the test

## Screenshots or videos of changes:
output

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by alla0810** [comment]
All tests passed.  Nice work!

image

**Review by linkhanthtel — APPROVED** [review]
I reviewed your PR and all tests passed! Nice work!

**Review by jennZhang93 — APPROVED** [review]
All tests passed. Good work!
Screenshot 2024-04-18 at 7 16 47 PM

**Review by SRamen1999 — APPROVED** [review]
All tests passed.
Screen Shot 2024-04-18 at 10 52 52 PM

**Review by metaphor987 — APPROVED** [review]
Hi Shengjie, the instructions are very clear, and all tests passed on my side. Nice work!
Screenshot 2024-04-19 at 12 54 08 AM

**Review by curiousfancier — APPROVED** [review]
All test cases working well 
image

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-04-19 at 10 23 37 PM

**Review by Tiantian-C — COMMENTED** [review]
All tests passed.
Screenshot 2024-04-20 at 3 27 41 PM

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by curiousfancier — APPROVED** [review]
I have run through all tests and they have passed

image

**Review by cvtqx — APPROVED** [review]
All the tests pass and test coverage report shows 100%. great job!

Tests:

Screen Shot 2024-04-26 at 5 51 13 PM

Coverage report:

Screen Shot 2024-04-26 at 5 58 56 PM

**Comment by beblicarl** [comment]
All test cases passed successfully

image

**Pull request merged**
