### PR TITLE
Peteson fix the saving functionality so that the reason doesn’t disappear after switching dates

### PR DESCRIPTION
**Pull request by peterson337**
# Description
In the user profile section, there is a blue button labeled 'Schedule Blue Square Reason,' which opens a modal containing one input field and one text area field. The input field is used to specify the date of the next Sunday when the developer will return to work, while the text area field is for specifying the reason for the leave request. The identified bug pertains to the text area field not retrieving the last entered text when the modal is reopened or when the date input is changed or the page is reloaded.

## Related PRS (if any):
None
…

## Main changes explained:
The text area will recover the last thing that was written or saved after the date is changed, the modal is reopened, or the page is reloaded.

After the message "Reason Scheduling Saved!" appears, the date will be saved to local storage and will be used to recover the last entry in the text area labeled "What is your reason for requesting this time off?".
…

## How to test:
1 check into current branch.
2. do `npm install` and `npm run start` to run this PR locally.
3. log as any user.
4. Go to view profile.
5. Click on the "Schedule Blue Square Reason" button.
6. Write in the text area field, "What is your reason for requesting this time off?"
7. After clicking the "Save" button, a second modal will open. Click on the "Confirm" button. 
8. After the message "Reason Scheduling Saved" appears, check if the date is saved in your local storage. Reopen the modal or change the date input or reload the page and check if the text area recovers the last reason that was saved 

## Screenshots or videos of changes:

Before my fix: https://www.dropbox.com/scl/fi/5qcycgx7j9lf80gj1z8dw/Blue-Square-Scheduler-Bug-Summary.mov?rlkey=97rh2g94krrr6c6uyoj5o9mx4&e=2&dl=0

After my fix: Peterson fix the saving functionality so that the reason doesn’t disappear after switching dates

## Note:
The console is going to have some errors not related to this PR. These can be disregarded because the code changed by this PR will not introduce these errors to the "development" branch when it gets merged.

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested your PR and it is working correctly. The date and message are stored in local storage and does not change after reopening the modal or reloading the page. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/b8f2b1c8-13e1-4c8a-999b-783844d45448

**Review by ShengjieMao — APPROVED** [review]
The function worked as expected. And data is also saved for the date chosen. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/bd22d4a1-bb18-40cb-a1a5-c1493c1fa1c3

**Review by XiaohanMeng — COMMENTED** [review]
Hi, I tested this PR and encountered the same issue that meetpadhiar4 mentioned above. The changes to the date and text are stored locally, so the information from the previous entry automatically displays the next time. Please refer the attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/c5bb6239-4b74-4889-90d2-fd7c9b33765e

**Comment by one-community** [comment]
Closing this, fixed by another PR.

**Pull request closed without merging**
