### PR TITLE
Added color bar for time logs

### PR DESCRIPTION
**Pull request by KaixiangGU**
### Description:
Added color bar for time log when filtering time logs on team member tasks tab. The bar color keeps consistency with the button color.
Red bar: past 24 hrs 
Blue bar: past 48 hrs
Green bar: past 72 hrs
Color_bar2
Color_bar1

### How to test:
Click any hours filter button (24/48/72) see if the color bar can be displayed correctly on the left side of time log.

### CODE REVIEW

**Review by Cirakuze — COMMENTED** [review]
Confirming the behavior as expected:

| | BEFORE | AFTER |
|--|--|--|
|24 hr | BEFORE - MAY 15 | AFTER - MAY 15 |
| 48 hr | BEFORE - MAY 14 | AFTER - MAY 14 |
| 72 hr | BEFORE - MAY 13 | AFTER - MAY 13 |

**Comment by AnishPandita** [comment]
Hi @KaixiangGU I tested your PR and the colour pattern behaviour seems to work correctly when filtering according to 24h, 48h and 72h. Also I agree with @Cirakuze its better to maintain consistency by importing the colour file into the others.
Screenshot 2023-05-16 at 5 29 15 PM
Screenshot 2023-05-16 at 5 29 28 PM

**Comment by papiasharmin** [comment]
functionality working as intended. good job. 
taskboxcolor1
taskboxcolor2

**Review by EdwinLauM — COMMENTED** [review]
Good job! Filter coloring is working as intended! I agree with @Cirakuze to export these colors are constants. 

Also I agree with @Cirakuze its better to maintain consistency by importing the colour file into the others.

Screen Shot 2023-05-16 at 6 38 07 PM

**Review by papiasharmin — COMMENTED** [review]
Hello @KaixiangGU. Your code looks great. agreed to @Cirakuze. One more thing is the moment function you are using for for time formatting, it has been used in several places, on teamMemberTasks.jsx file four time on line 151, 156, 171, 176 and in FilteredTimeEntries.jsx two time, it will be better to put it in a separate reusable function.  I have a question, today is 17th May for me, but i am looking at work report for 15,14,and 13 May, while i should see 16,15,14, because you are  using this line "tz('America/Los_Angeles')".  is it meant to be always this time zone?

**Review by eduhorta — COMMENTED** [review]
Everything is working as intended.

24h:
image
48h:
image
72h:
image

I agree with @Cirakuze. Having those colors as constants in a file will bring consistency.

**Review by yoyoweiii — COMMENTED** [review]
Hi @KaixiangGU Your PR works as intended that the color labels change when it comes to to 24h, 48h and 72h. 
I agree @Cirakuze mentioned that its better to maintain by importing the color into the other files. 
24 hrs

HGN APP and 22 more pages - Personal - Microsoft​ Edge 5_17_2023 2_35_49 PM

48 hrs

HGN APP and 22 more pages - Personal - Microsoft​ Edge 5_17_2023 2_36_09 PM

72 hrs

HGN APP and 22 more pages - Personal - Microsoft​ Edge 5_17_2023 2_37_23 PM
6)

**Review by abdel-lall — COMMENTED** [review]
the functionality works as intended.
PR830

**Review by yufeiStella — APPROVED** [review]
works as intended:

**Review by drewlong314 — APPROVED** [review]
Works as intended
Screen Shot 2023-05-20 at 3 03 55 PM
Screen Shot 2023-05-20 at 3 04 15 PM
Screen Shot 2023-05-20 at 3 04 26 PM

**Review by wang9hu — DISMISSED** [review]
Works as intended! Good job!
Screenshot 2023-05-20 162508

**Review by GKD890 — APPROVED** [review]
Hi, I've tested the colour bar, it's rendered properly. Also agree with @Cirakuze maybe it's better to put those colours as constants. But I think it can be considered in next PR if any that still need to use these colours.

Frontend_PR#830

**Review by 20chen-7 — DISMISSED** [review]
The function is intended and code looks great!
Screenshot 2023-05-22 at 12 56 55 PM
 
Screenshot 2023-05-22 at 12 57 26 PM
.
Screenshot 2023-05-22 at 12 57 46 PM

**Comment by KaixiangGU** [comment]
Thanks for all reviews. Already addressed @Cirakuze comment.

@one-community Please move it to final.

**Comment by one-community** [comment]
Excellent, thank you everyone. Moving it to final review!

**Review by Cirakuze — APPROVED** [review]

**Pull request merged**
