### PR TITLE
Ramakrishna Teamcode Regex change and select All with No Team code option fix

### PR DESCRIPTION
**Pull request by Ramaruva**
## Related PRS (if any):
This frontend PR is related to the [#1010](https://github.com/OneCommunityGlobal/HGNRest/pull/1010) backend PR.

…

## Main changes explained:
- Updated the Teamcode regex to match latest Teamcode requirementes i.e teamcode can have numbers,any special characters, and length of only 5-7 
- Modified the handleTeamcode function inorder to fix an select all team code option
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner  user or any user who can edit teamcode
5. go to dashboard→ weeklysummaryreport 
6. try to change Teamcode of any user and teamcode should able to have special characters,numbers,alphabet and it should be length 5-7 only please this are you able to give teamocode in this pattern or not.
7. After checking teamcode please try check whether you are able too select the "Select Team Code" and check whether you are able to See option select All with no Team code. 

## Screenshots or videos of changes:
image
image

## Note:
Please note that while changing teamcode for some users we are getting 500 api status error this is not related to this changes that is another issue.
image

### CODE REVIEW

**Review by kdaga81 — CHANGES_REQUESTED** [review]
image

Working fine for "a-a1B@#" but not for "a1B@#Z4" on same field. Getting above error!

**Comment by Ramaruva** [comment]
> image
> Working fine for "a-a1B@#" but not for "a1B@#Z4" on same field. Getting above error!

can you give the username which you wanted to change the team code

**Review by jinxyou — APPROVED** [review]
I tried to change the teamcode including special characters. Except for the status 500 error, there's no other problem. Also I'm able to select the ALL WITH NO CODE. Great work!
Screenshot 2024-06-29 185333
Screenshot 2024-06-29 185347

**Review by nyelmela — APPROVED** [review]
I have successfully tested the PR as owner. This PR updates the Teamcode regex to allow numbers, special characters, and a length of 5-7 characters, and modifies the `handleTeamcode` function to fix the "Select All" option. To test, I checked out the current branch, ran `npm install`, started the backend from the dev branch, cleared site data/cache, and logged in as an admin/owner user. I navigated to the dashboard → weekly summary report, changed a user's Teamcode to ensure it followed the new pattern, and verified that the "Select All" option with no Teamcode worked correctly. All functionalities worked as expected, so I approve this PR.

image
image

**Review by HowieMiao — APPROVED** [review]
After testing PR, can ensure that team code Regex update now allows for all special characters. Disregarding status code 500 error when inputting, everything else seems to be in order with being able to select section with no team codes as well.

image

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and able to change Team code using special characters, numbers, and alphabet of 5-7. Any other combination is captured under validation error. Also "Select All with no Team code" option is available in the dropdown.! Except for the 500 API error every thing works fine!

**Review by sahithidhulipala9 — APPROVED** [review]
Reviewed the PR, Able to see "Select All with Node Code" option in the select team code dropdown. Able to change the team and add the team based on the special characters, numbers and alphabets of length 5-7 and except for the error, everything is working perfectly.
Screenshot (99)
Screenshot (100)

**Comment by vijay10pk** [comment]
I have tested this PR with an admin credential. I am able to edit the team code the input field accepts special characters and number and length validation is also working fine and able to select the "select all with NO Code(XXXX)". Getting 500 error popup when I tried to edit team code for a few users.
Screenshot 2024-07-02 at 7 56 01 PM
Screenshot 2024-07-02 at 7 56 01 PM
Screenshot 2024-07-02 at 7 55 34 PM
Screenshot 2024-07-02 at 7 55 34 PM
Screenshot 2024-07-02 at 7 54 03 PM
Screenshot 2024-07-02 at 7 54 03 PM

**Comment by vijay10pk** [comment]
Tested the changes in this PR and regex is working fine as expected, apart from getting 500 error codes while editing a few team codes for users. refer front-end PR for more test screenshots[https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2401#issuecomment-2204740623](url)

**Review by vijay10pk — APPROVED** [review]

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR with my admin account and i was able to change Team code using special characters, numbers, and alphabet of 5-7 and Also  "Select All with Node Code" option available to select in  team code dropdown. Except 500 Api error , everything working correctly. 

PR-2401+1010
PR-2401+1010-1

**Review by Trip2310 — APPROVED** [review]
Successfully tested this PR as owner. It is accepting the updated regex and tried testing with all special character,and  more than 7 input not accepting that is good. Able to select team with nocode.
PR_2401
PR_2401a

**Review by nikhilpittala16 — APPROVED** [review]
I tested the PR and everything works fine except for the status 500 error. I have tried changing the team code and it works. I am able to see and select "Select All With NO Code (1304)" .
Screenshot (15)

Screenshot (16)

Screenshot (18)

Screenshot (19)

Screenshot (20)

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and I was able to select the checkbox "Select All with no code " and was able to add team code to them with 5-7 characters long which includes numbers and special characters. I got an error message but this was specified in the instructions that this is some other issue. So, it works fine
Screenshot 2024-07-05 150412

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
