### PR TITLE
Nahiyan_Dark mode for team locations and Weekly Summaries Report Modals

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Implemented dark mode on all modals within the Team Locations and Weekly Summaries Report page. 

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Updated all modals on team location page
- Updated all modals on Weekly Summaries Report Page

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links -> Weekly Summaries Report/Team Locations
6. verify all modals can switch to dark mode

## Screenshots or videos of changes:
Screenshot 2024-05-07 111249
Screenshot 2024-05-07 111309
Screenshot 2024-05-07 111343

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and it is working as intended. Please refer the screenshot attached.

PR 2236 1
PR 2236 2

**Comment by Ramaruva** [comment]
Hi I am new.., I don't have an owner account to test this entirely so can you please provide an owner account if possible Thank you!

**Review by linkhanthtel — DISMISSED** [review]
I reviewed your PR and all modals look good! Nice work!

**Comment by Nahiyan-16** [comment]
> Hi I am new.., I don't have an owner account to test this entirely so can you please provide an owner account if possible Thank you!

Please see Jae with this request. He can provide you with an owner account.

**Review by MinSun0814 — DISMISSED** [review]
Works as intended. Nice work!
image
image

**Review by jayyy-s — CHANGES_REQUESTED** [review]
Dark mode for team locations and Weekly Summaries Report modals look good. Code changes make sense and are simple to understand.
2336 1st toggle
2336 dark user modal
add user modal

Only problem I found is this logout modal. Requesting that this gets changed to dark mode as well if the user has selected it.
2336 logout (not dark moded)

**Review by Ramaruva — DISMISSED** [review]
Verified dark mode in weekly summary and team location pages modal and they are working as expected 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/bc6fc13d-96f7-47f2-a619-93fda1301a63

**Comment by Nahiyan-16** [comment]
> Dark mode for team locations and Weekly Summaries Report modals look good. Code changes make sense and are simple to understand. 2336 1st toggle 2336 dark user modal add user modal
> 
> Only problem I found is this logout modal. Requesting that this gets changed to dark mode as well if the user has selected it. 2336 logout (not dark moded)

This is being implemented in another PR. This PR only focuses on team locations and Weekly Summaries Report Modals

**Comment by ZhangPeizhou** [comment]
Hi, I cannot see the "Search" role under "Team Locations", I wonder why that happens?
image

**Review by dkt6 — DISMISSED** [review]
Thank you for the great work!
These updates meet the expectations in my environment as well.

**Comment by Nahiyan-16** [comment]
> Hi, I cannot see the "Search" under "Team Locations", I wonder why is that? image I did checkout to the current branch, it still does not work. image

I believe you need to login with a owner account

**Review by jayyy-s — DISMISSED** [review]
Modals looked good, previously requested changes not necessary for this PR.

**Review by nathcarnevalli — DISMISSED** [review]
Everything worked as expected for me :)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/c275bd2c-ff12-4b63-ab23-4400313c0c6b

**Review by hbodgal — DISMISSED** [review]
image

Dark mode works fine in Weekly Summaries Report Modals. 
But Dark Mode is not applied on this one Dilog Box (check img)

**Review by KurtisIvey — DISMISSED** [review]
Everything works as described. All modals are running dark mode without issue and the code looks great too. Fantastic job!
Screenshot 2024-05-11 at 4 20 11 PM
Screenshot 2024-05-11 at 4 20 29 PM
Screenshot 2024-05-11 at 4 21 07 PM
Screenshot 2024-05-11 at 4 21 15 PM

**Review by TareqMia — DISMISSED** [review]
Everything worked as expected and the modals look good in dark mode 👍 

Screenshot 2024-05-11 at 6 04 20 PM
Screenshot 2024-05-11 at 6 04 26 PM
Screenshot 2024-05-11 at 6 05 31 PM

**Comment by KaushikMreddy** [comment]
Hi @Nahiyan-16,

I've reviewed your changes, These changes look good.
image
image


### Requesting a change on this part:
- In the add new user location table, the hover color is white, the text needs to be darkened or it's not seen.
image


-  The info icon displays this pop-up on the reports page, please make the color of the background same as the the pop-ups for uniformity. In case the way it's been done now is correct, ignore this.
image

Good work!

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi @Nahiyan-16,

I've reviewed your changes, These changes look good.
image
image


### Requesting a change on this part:
- In the add new user location table, the hover color is white, the text needs to be darkened or it's not seen.
image


-  The info icon displays this pop-up on the reports page, please make the color of the background same as the the pop-ups for uniformity. In case the way it's been done now is correct, ignore this.
image

Good work!

**Pull request merged**
