### PR TITLE
Shantanu unit test cases NewModal File

### PR DESCRIPTION
**Pull request by n0vay**
# Description
Unit test for common New Modal component

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run on terminal: "npm test Image.test.jsx"
4. verify that all tests pass

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Review by wantingxu7 — APPROVED** [review]
I ran the test and all tests passed. Good work!

**Review by keyunhuangg — APPROVED** [review]
I checkout this branch and follow the instruction to run the tests. It seems like all tests have passed!
Screenshot 2023-11-17 at 8 02 36 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

PR 1541

**Review by StrawberryCalpico — APPROVED** [review]
Screen Shot 2023-11-18 at 4 44 33 PM
Hi, tested your PR, great job!

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-18 at 11 58 25 PM

**Pull request merged**
