### PR TITLE
ambika fix core team unique additions in leaderboard

### PR DESCRIPTION
**Pull request by kabraambika**
# Description
image

This PR addresses the following issues:

- Leaderboard Issue: The leaderboard wasn't updating correctly when additional hours were needed due to missed hours in a unique Core Team role. It was incorrectly showing a green dot based on weekly hours instead of accounting for the special case when hours were missed. 

- Timelog Display: The timelog was not reflecting the accurate hours a person needed to complete for a unique Core Team role. It was failing to include the extra hours required due to the presence of more than five blue squares.

- Blue Square Mouseover: When hovering over the blue square in a user's profile, if the number of blue squares exceeds five, additional unique hours should be assigned to the Core Team user. The calculation now correctly updates the required hours as follows: committed hours + (additional makeup hours from last week) + (if the number of blue squares is greater than 5, then (number of blue squares - 5) hours).

- Additional Makeup Hours Calculation: The "additional makeup hours" field in the user's profile now correctly includes hours added when the number of blue squares exceeds five.

Fixes # (bug list priority medium)

## Related PRS (if any):
This frontend PR is related to the [1083](https://github.com/OneCommunityGlobal/HGNRest/pull/1083) backend PR.

## Main changes explained:
- Update [Leaderboard.jsx](src/components/LeaderBoard/Leaderboard.jsx) for showing the Additional make up hours for this week for Core team role 

## How to test:
1. check into current branch, `git checkout ambika-fix-core-team-unique-hours-additions`, `git pull`
3. do `npm install` and `npm run start:local` to run this PR locally
4. Clear site data/cache
5. log as user with core team role

**This PR needs API testing using Postman, please first set up the Postman environment.**
1. If this is your first time using Postman, just start HGNRest and post to http://localhost:4500/api/login with the email and password in the body. You will get a token as a result if your setup is successful.
image

2. Make the following adjustments to HGNRest then rebuild and restart the HGNRest:
  - **userProfileController.js**: Add test function in userProfileController
   image
  
  - **userProfileRouter.js**: Add a new route to call the test function 
  image
   
  - Get core team user's id from user profile and copy id from the url as shown below
  image

  - **userHelper.js**: Add role: 'Core Team' and id of core team user to let assignBlueSquareForTimeNotMet just apply for Core Team member.
  image

 
3. Use Postman and send a GET request to http://localhost:4500/api/userProfiletest. Make sure you input the correct address and method set to GET. Set the authorization value to the token you get at step 1 in the header. The request will return finished (this will take a few seconds.) 
image

4. Change system's date to future date by gap of one week. [For first week, blue square is not assigned], Open a 'Core Team' userProfile page and check the value of Additional Make-up Hours This Week. Also, check the blue square to see if the blue square assignment is correct.

**If you get unauthorized token, then follow the step 1 again and update token in step 3** 

6. Verify that if additional makeup hours are assigned for this week, the leaderboard will display a red status if those hours are not completed. On mouseover, the additional makeup hours should also be visible, as demonstrated below:
image
7. Verify that if there are no additional makeup hours for this week, the green and red statuses on the leaderboard will function based on the weekly committed hours for the Core Team user. On mouseover, the tooltip will not display any information regarding additional makeup hours for this week.
8. Verify that in userprofile, on mouseover for bluesquare, hours added when the number of blue squares exceeds five
9. Verify that in userprofile, the additional make up hours for this week field includes the hours added when the number of blue squares exceeds five as well.
10. Verify that in timelog, the total hours includes hours added when the number of blue squares exceeds five.
11. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
https://www.loom.com/share/3d7f4b2f024b4cb7a30437b0d969ac47?sid=71e8e8ab-b668-48bf-b18b-d5ad1a9c00ce
## Note:
- To test this PR, create a new user with the Core Team role.

- To fix an existing core team user's additional makeup hours, first, log in as the owner. Then, manually edit the makeup hours for this week in the user's profile. Login in back as existing core team's user, moving forward, the hours will be calculated correctly on a weekly basis.

### CODE REVIEW

**Review by AJAYINAVOLU — DISMISSED** [review]
In the leaderboard, on mouseover, the additional makeup hours are not visible.
I have manually added the additional hours using the owner account.

Before assigning additional hours using owner account:
Screenshot (1738)

After assigning additional hours:
Screenshot (1739)
Screenshot 2024-09-03 151422

I was unable to replicate the same by manually adding hours. Should I add the blue squares using the owner account or wait for the blue squares to add and then review this to replicate the issue?

**Comment by kabraambika** [comment]
> In the leaderboard, on mouseover, the additional makeup hours are not visible. I have manually added the additional hours using the owner account.
> 
> Before assigning additional hours using owner account: Screenshot (1738)
> 
> After assigning additional hours: Screenshot (1739) Screenshot 2024-09-03 151422
> 
> I was unable to replicate the same by manually adding hours. Should I add the blue squares using the owner account or wait for the blue squares to add and then review this to replicate the issue?

Hello @AJAYINAVOLU,
Firstly, regarding the leaderboard, when a user profile is updated, the leaderboard will not automatically refresh. You'll need to click the refresh button next to the Leaderboard title after saving the user profile.

I reviewed the leaderboard and noticed that the additional makeup hours were added manually but still visible on mouseover for your profile, as shown below:
image

**Now, regarding the blue square condition for core team users' additional hours:** For the core team user, the blue square condition applies if no summary is provided or if the committed hours are not met by the end of the week. To test this, set your system's date to a future date by week's monday. The blue square will be automatically assigned, and any additional make-up hours will also be assigned automatically.

**Comment by crystallow1168** [comment]
> **Now, regarding the blue square condition for core team users' additional hours:** For the core team user, the blue square condition applies if no summary is provided or if the committed hours are not met by the end of the week. To test this, set your system's date to a future date by week's monday. The blue square will be automatically assigned, and any additional make-up hours will also be assigned automatically.

Hello @kabraambika,
I wasn't able to populate the blue squares by setting my Mac's system to a future date.
My steps were:
1. Create a user and assigning the role to Core Team. (Start date for this account is 09/03/2024)
2. On my Mac -> System settings -> Date & Time -> Set date to 10/03/2024
3. Logged in using the user with Core Team role

The blue squares are not populated, and I'm not sure if I am missing any other steps?

**Comment by kabraambika** [comment]
> Hello @kabraambika, I wasn't able to populate the blue squares by setting my Mac's system to a future date. My steps were:
> 
> 1. Create a user and assigning the role to Core Team. (Start date for this account is 09/03/2024)
> 2. On my Mac -> System settings -> Date & Time -> Set date to 10/03/2024
> 3. Logged in using the user with Core Team role
> 
> The blue squares are not populated, and I'm not sure if I am missing any other steps?

Hello @crystallow1168 ,
Could you please create a Loom video or attach some images so I can verify your core team's user profile on my end?

**Comment by crystallow1168** [comment]
Hi @kabraambika,


https://github.com/user-attachments/assets/e9e5e071-2e6b-4f08-9075-fbd1f3a1f6b9

The screenshot video app ends abruptly after changing the time setting. Below is the screenshot of the profile when date is set to 10/17/2024.

image

**Comment by kabraambika** [comment]
Hello @crystallow1168 ,
I've detailed the updated instructions for testing. Please follow the temporary changes needed to obtain the blueSquare and account for additional makeup hours in the core team member case.

**Review by AJAYINAVOLU — COMMENTED** [review]
Hi @kabraambika , I am still unable to replicate the hovering to display the additional makeup hours. I have tried it on both Chrome and Firefox browsers after refreshing the leaderboard as well. 

https://drive.google.com/file/d/1EcO98O6yjzC9oTYABZc16D_Y_3POhFws/view?usp=sharing

**Comment by sri0606** [comment]
@kabraambika I have tried to test this PR and facing same issue as @AJAYINAVOLU . These are steps I followed:

* Created a user with core team role.
* Logged in as owner and manually added "Additional make-up hours" and some blue squares (more than 5) for that user.
* Logged back in with core team user account and I still don't see any change in tooltip info when mouseover. Refreshed the leaderboard too.

Also isn't there an alternative to changing systems date to obtain a blue square? Manually adding doesn't work?

Screenshot 2024-09-03 224525
WhatsApp Image 2024-09-03 at 22 45 05_e00c8bf7

**Comment by kabraambika** [comment]
Hello @sri0606 and @AJAYINAVOLU , I created a Loom video for the mouseover tooltip based on your instructions, Created a new user, added manual make up hours for core team, checked leaderboard from core team member user and owner user as well, everything is working fine. Could you please follow it and let me know if you're doing anything differently?
https://www.loom.com/share/0076503d5c134064a6583f0fcd3440c3?sid=a7b981a3-cf84-4222-a0f1-9bbf092d6d64

**Comment by sri0606** [comment]
> Hello @sri0606 and @AJAYINAVOLU , I created a Loom video for the mouseover tooltip based on your instructions, Created a new user, added manual make up hours for core team, checked leaderboard from core team member user and owner user as well, everything is working fine. Could you please follow it and let me know if you're doing anything differently? https://www.loom.com/share/0076503d5c134064a6583f0fcd3440c3?sid=a7b981a3-cf84-4222-a0f1-9bbf092d6d64
> 
> A core team member is a unique user who receives additional hours if the weekly committed hours are not met or if the summary is not submitted. Based on this feature, I’ve provided an alternative method [and temporary code in files which will trigger functions] in the "How to Test" section on how to apply a blue square to the core team member along with the additional hours.

Thats exactly what I did. Here's a video walkthrough:

https://www.loom.com/share/e8e5c0fe6ada408294fada1d69e179e5

**Comment by kabraambika** [comment]
> Thats exactly what I did. Below is a video walkthrough. I tried to check again after refreshing leaderboard too but no luck. Let me know if I'm doing anything incorrectly.
> 
> https://www.loom.com/share/e8e5c0fe6ada408294fada1d69e179e5

Hello @sri0606 , I reviewed the user you created, and it’s working fine on my end. Just to confirm, are you testing in the correct frontend and backend branches as specified in the PR instructions? This PR hasn't been merged yet, so please make sure you’re testing in the following branches:

Frontend: git checkout ambika-fix-core-team-unique-hours-additions
Backend: git checkout ambika-fix-core-team-unique-hours-additions
Could you share screenshots of the branches you’re testing in ?

**Comment by sri0606** [comment]
> > Thats exactly what I did. Below is a video walkthrough. I tried to check again after refreshing leaderboard too but no luck. Let me know if I'm doing anything incorrectly.
> > https://www.loom.com/share/e8e5c0fe6ada408294fada1d69e179e5
> 
> Hello @sri0606 , I reviewed the user you created, and it’s working fine on my end. Just to confirm, are you testing in the correct frontend and backend branches as specified in the PR instructions? This PR hasn't been merged yet, so please make sure you’re testing in the following branches:
> 
> Frontend: git checkout ambika-fix-core-team-unique-hours-additions Backend: git checkout ambika-fix-core-team-unique-hours-additions Could you share screenshots of the branches you’re testing in ?

Yes, I'm using the correct branches.

image
image

**Comment by kabraambika** [comment]
> Yes, I'm using the correct branches.
> 
> image image

Hello @sri0606 , Can you run command `npm i && npm run build && npm start` for backend repo ?

**Review by sri0606 — DISMISSED** [review]
Hello @kabraambika , thanks for quick responses. I was able to get it to work after clearing cache and rebuidling. I went ahead and tested the other changes and everything worked as expected.

* I got the authorization token from posting to http://localhost:4500/api/login.
* I made below code changes as mentioned:
  Screenshot 2024-09-04 113506
  Screenshot 2024-09-04 113520
  Screenshot 2024-09-04 113530
 
* Then I sent a get request to http://localhost:4500/api/userProfiletest with that token.
 
  Screenshot 2024-09-04 113453

image

**Review by crystallow1168 — COMMENTED** [review]
Hi @kabraambika,

Thank you for the detailed instructions on testing! These are my findings:

- ✅ Verify that if additional makeup hours are assigned for this week, the leaderboard will display a red status if those hours are not completed. (refer to image below)

image

- ❗️ Verify that if there are no additional makeup hours for this week, the green and red statuses on the leaderboard will function based on the weekly committed hours for the Core Team user. On mouseover, the tooltip will not display any information regarding additional makeup hours for this week.
**Comment: @kabraambika I'm not sure how to test this. I have added intangible time to the core user's account, but it doesn't seem like it counts towards the committed hours. Please let me know if there's a way to satisfy the committed hours for the core user**

- ✅ Verify that in userprofile, on mouseover for bluesquare, hours added when the number of blue squares exceeds five (refer to image below)
- ✅ Verify that in userprofile, the additional make up hours for this week field includes the hours added when the number of blue squares exceeds five as well. (refer to image below)
- ✅ Verify that in timelog, the total hours includes hours added when the number of blue squares exceeds five. (refer to image below)
image


- ✅ verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

**Comment by kabraambika** [comment]
Hello @crystallow1168 , Thank you for verifying all the conditions. There's a way to convert an intangible time log for a core user into a tangible one. First, log the intangible time under the core team role. Then, log in using the owner profile, search for the core team user on the leaderboard, and click on their green or red status dot. This will display the core team user's dashboard. From there, navigate to the current week's time log and click the checkbox, which will convert the intangible time log into a tangible one. Feel free to ping me on slack if unable to do so.

**Review by vishnupriyaatheti — CHANGES_REQUESTED** [review]
Hi @kabraambika,

I have tested your PR with various scenarios, and overall, everything works as expected. Here are the details of the scenarios I tested:

**New Core Team User**: I created a new Core team user and manually added makeup time from the owner account. I verified that the tooltip displayed the correct data as described, and the timelog was updated accordingly. Everything worked as expected.

**Bluesquares Addition**: For the new user, I followed the test case you provided. By changing the system date further ahead, the blue squares were added as expected. However, according to the instructions, blue squares should not be added for the first week, and there should be no makeup time added for that period. I observed that markup time was added directly to 60 hours for the first week, but no blue squares were added. Please verify if this is a valid scenario. In this case, the user was created on 09/04/2024, and the system date was set to 09/09/2024. According to the functionality, there should be no markup time for the first week. The subsequent weeks worked perfectly, and I was able to test up to the addition of two blue stars.

Due to some system issues affecting time changes, I was unable to complete the remaining verification. I will finish this tomorrow and let you know the results. Meanwhile, could you please clarify the above issue? Additionally, could you guide me on how to filter existing Core team members from the UI?

Thank you!

I am attaching a single screenshot to avoid any confusion. Please focus on the highlighted sections.
PR 2600 markup time added by chnaging system date to one week ahead

**Review by vishnupriyaatheti — APPROVED** [review]
I have verified the other changes and are working as expected.

**Review by Shreyav2000 — DISMISSED** [review]
I was able to test the Leaderboard Issue and Timelog Display features without problems. However, when it came to testing Blue Square Mouseover and Additional Makeup Hours Calculation, the blue squares did not update as expected, even after moving the system date forward. You can also verify the change of date in the second screenshot. This issue seems to be specific to macOS users. I will attach screenshots below for your reference:
red dot is being showed when there is additional makeup time added with details after hover
no blue square assigned even after changing system's date
additional makeup time displayed correctly after manually updating it from an owner account

**Comment by kabraambika** [comment]
Hello @Shreyav2000 , Thank you for reviewing the PR! I'm also using a Mac. For simulating the automatic assignment of bluesquare and the carryover of makeup hours from last week to this week, are you following the code screenshots provided in the "How to Test" section? Additionally, just updating the system date won't be enough to trigger the bluesquare assignment.

**Review by crystallow1168 — DISMISSED** [review]
@kabraambika 

> Hello @crystallow1168 , Thank you for verifying all the conditions. There's a way to convert an intangible time log for a core user into a tangible one. First, log the intangible time under the core team role. Then, log in using the owner profile, search for the core team user on the leaderboard, and click on their green or red status dot. This will display the core team user's dashboard. From there, navigate to the current week's time log and click the checkbox, which will convert the intangible time log into a tangible one. Feel free to ping me on slack if unable to do so.

Verified the last condition and everything looks good!
✅ Verify that if there are no additional makeup hours for this week, the green and red statuses on the leaderboard will function based on the weekly committed hours for the Core Team user. On mouseover, the tooltip will not display any information regarding additional makeup hours for this week.

image

**Comment by geetamatkar** [comment]
Hi @kabraambika ,
I have reviewed the PR and conducted the following verifications:

Leaderboard Makeup Hours:
Confirmed that additional makeup hours assigned for this week are accurately reflected by a red status if incomplete. The additional makeup hours are correctly displayed on mouseover. ✅

Leaderboard without Additional Makeup Hours:
Verified that when there are no additional makeup hours, the green and red statuses function based on the weekly committed hours. The tooltip does not display makeup hours when there are none, as expected. ✅

User Profile - Additional Makeup Hours:
Verified that the additional makeup hours field includes hours added due to exceeding five blue squares. ✅

Timelog - Total Hours:
Ensured that total hours in the timelog now reflect the hours added when more than five blue squares are accumulated. ✅

Dark Mode:
Verified that the new feature works as expected in dark mode without any visual issues. ✅

Blue hours

Screenshot 2024-09-07 at 5 39 14 PM

**Comment by Shreyav2000** [comment]
> Hello @Shreyav2000 , Thank you for reviewing the PR! I'm also using a Mac. For simulating the automatic assignment of bluesquare and the carryover of makeup hours from last week to this week, are you following the code screenshots provided in the "How to Test" section? Additionally, just updating the system date won't be enough to trigger the bluesquare assignment.

**Comment by Shreyav2000** [comment]
Hello!

Yes, I made the temporary code changes as suggested, but it still did not work for me. I followed the steps in the "How to Test" section thoroughly, including updating the system date, but it didn’t trigger the bluesquare assignment.

Let me know if there are any additional steps I should try!

**Review by Shreyav2000 — COMMENTED** [review]
Hello!

Yes, I made the temporary code changes as suggested, but it still did not work for me. I followed the steps in the "How to Test" section thoroughly, including updating the system date, but it didn’t trigger the bluesquare assignment.

Let me know if there are any additional steps I should try!

**Review by Shreyav2000 — DISMISSED** [review]
Changes work as expected.

**Pull request merged**
