### PR TITLE
Hiral cleanup dashboard console logs

### PR DESCRIPTION
**Pull request by hiralsonip**
# Description
(Priority High) Jae: Clean up dashboard console log violations to improve the loading speed

## Related PRS (if any):
This frontend PR is related to the Development backend PR.

## Main changes explained:
- Changed the function in the `store.js` file. Remove extra keys from the state which are undefined. 

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin user
5. go to the dashboard and check the console. 

### Before
Before

### After
After

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66827672/2f7dece9-1d0d-4c60-a8c3-86d52e6a1b4c

Private_Window

### CODE REVIEW

**Review by hbodgal — DISMISSED** [review]
image

There are no console errors on load.

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and there were no errors.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/9434fb04-8220-478b-a6f7-e2d3f5b816c8

**Review by linkhanthtel — DISMISSED** [review]
I reviewed your PR and there are no console errors. Nice work!

**Review by Ramaruva — DISMISSED** [review]
Verified this changes in local env and logs are cleared now
image

**Review by peter6866 — DISMISSED** [review]
Changes work as expected. There are no other errors after login.
image

**Review by JatinAgrawal94 — DISMISSED** [review]
No Console errors can be seen on when dashboard page loads.

**Review by KurtisIvey — DISMISSED** [review]
No errors and functionality still remains. Definitely cleaned up the dashboard. Haven't seen it that error free in a while. Fantastic job!


Screenshot 2024-06-15 at 3 44 37 PM



However, there does appear to be a merge conflict

**Comment by one-community** [comment]
Thank you! Will merge once conflicts are resolved

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by VaishnaviK23** [comment]
I was testing this change on Dev. I am not getting the 'unexpected keys' error shown in the 'before' screenshot so that seems to be fixed. However, the console is not clean and I'm getting certain other errors when the dashboard loads:
PR 2199

**Pull request merged**
