### PR TITLE
Raul make user profile page responsive

### PR DESCRIPTION
**Pull request by rauleffting**
# Description
(USER PROFILE COMPONENT - PRIORITY LOW) 

> 1. (PRIORITY LOW) Jae: Optimize user profiles for phones and tablets.
>     a. A lot has been added to this page. What can we do to make it work better on phones and tablets? Please submit your suggestions to Jae before putting a lot of work into this. 

## Mainly changes explained:
The user profile page was edited to be responsive. The blue square section was adjusted and the tabs were replaced by a menu list. Every item on the list opens a modal with the respective functions.

## How to test:
1. git checkout raul_make_userprofile_responsive
2. npm install
3. npm run start:local
4. log in as an admin or any other role
5. click on Welcome -> View Profile, as below:
Screen Shot 2023-01-31 at 22 29 49
6. Verify if the page is responsive and working on small screens (you can test it by changing the resolutions with the inspection resource on Chrome). The proper resolutions to test are **between 425px and 1024 px**.
7. Also, **focus on the functionalities**. **This PR is not supposed to style the page** but make it fit on phone screens.

### Here are two videos to help you:

1. User profile page behavior on the development branch (BEFORE):

https://user-images.githubusercontent.com/29555732/215923563-4a7ab796-7551-483c-85c9-4ec4e8c07216.mov

2. User profile page behavior on this branch (AFTER):

https://user-images.githubusercontent.com/29555732/215923131-b6c64241-4fbf-4963-8023-781d19b2458c.mov

### CODE REVIEW

**Comment by tingedudu8** [comment]
https://user-images.githubusercontent.com/70128933/216133530-56b9a70b-c967-44b1-a14b-3d55fcb7a1a4.mov

Hi @rauleffting, I test the function on different resolutions and they all work very well. The blue square section was adjusted and the menu list makes it easier to use on the phone. Thank you!

**Comment by RafaelCastilhoCastro** [comment]
Hi @rauleffting,
Thank you for the thorough PR instructions.
I tested the PR and found some issues I'd like to point out.

1. When clicking the "hamburger menu button", the menu slides but it is behind others page's elements.


2. On the Projects tab the Assign Project button is left aligned. IMO it should be centered. Also, in case a project's name is long, the Delete button could also be horizontal and vertical center aligned.
2(projects)

3. On the basic info tab the Status and End Date are left aligned. I'd sugest the positioning as in the image to the right.
3(basic info)

4. On Teams tab, I think that's exactly like Item 2.
4(teams)

5. On Badge History tab, the content need some rearrangement. The name field could be center aligned, the Modified and Count fields could use some more space, the section is leaking to the right and the buttons could be center aligned.
5(badgeHistory)

6. The Assign Badge tab loads the huge list of possible badges leaving the Confirm button way down below them. I'd suggest a "window box" to contain the badges. The user may scroll throught the badges but the confirm button will be visible at all times.
6(assign badge long list)

7. The field that displays the earned badges is small and the scroll is not working in case the user has more badges. I noticed that this functionality isn't working on desktop visualization too, so I'm not sure if this will be in this PR scope.
7(badges scroll)

Thanks.

**Comment by tingedudu8** [comment]
Hi @rauleffting, refering to what @RafaelCastilhoCastro pointed out, I tested some other functions besides the responsive characteristic. I am not sure whether these also should be solved in this PR. I found out some other problems. Thanks!

https://user-images.githubusercontent.com/70128933/216161266-bbb9ca27-3cd8-4f33-a688-6a3d4710f74f.mov

**Comment by AnishPandita** [comment]
Hi @rauleffting I tested your PR and most of the things seem perfectly responsive for different screen sizes. Although as suggested above on clicking the menu button on top right the popup overlay overshadows the menu options. Also on navigating to select featured button the next screen has some overflow of data on smaller screen. Also as suggested by @RafaelCastilhoCastro the positioning of UX of some DOM elements could be rethought to make it more intuitive to user.

https://user-images.githubusercontent.com/111321945/216164903-edd5ea1d-a45e-48ae-878d-60eb0cf3a1c4.mov

**Comment by Gukal7** [comment]
Hi @rauleffting, I've also tested the code and most of the things are working just fine, scrolling at all the places is also working as expected. As I change screen size all the elements adjusts well. But like @RafaelCastilhoCastro mentioned there are certain elements whose positioning and alignment could be fixed. But like @tingedudu8 said we are not sure if those changes are required to be done in this PR.
But I think the issue with the menu bar overlaying should be fixed in this one.
Screenshot 2023-02-01 at 4 09 48 PM

**Comment by one-community** [comment]
Great job team. Raul, please log any other bugs uncovered here that you won't include in this PR on the Bugs doc and comment so I can approve them.

**Comment by rauleffting** [comment]
You are right, @RafaelCastilhoCastro! The changes that you suggested will be developed. I'll let all of you know when I'm done with the new improvements.

**Comment by rauleffting** [comment]
Please, guys! Take a look again. Thank you!

**Comment by Filipe-Oliv** [comment]
Hi @rauleffting.

Following are some notes:

1.1. The organization of the clock in relation to the “hamburger” menu button;
1.2. The “hamburger” menu is below the profile picture;
1.3. Can't click menu items because profile picture is above;
1.4. The Assign badges button is going over the edge;
week 02 - 02-01-23 (1)


2.1. The checkbox is above the info icon;
2.2. The screen needs to be scrolled up and down to see the close button and confirm button.
week 02 - 02-01-23 (2)


3.1. The section below the text “Bravo '' is off-screen.
week 02 - 02-01-23 (5)


4.1. It has opened two popups with the same content when it is clicked in the blue square.
week 02 - 02-01-23 (6)


5.1. The form for adding a personal link is off-screen.
week 02 - 02-01-23 (7)


6.1. Suggestion: rearrange the buttons at the bottom of the Basic Info box.
week 02 - 02-01-23 (8)


7.1. The form for adding phone numbers in the basic info box is off
week 02 - 02-01-23 (9)
-screen.


8.1. Suggestion: A better way to rearrange basic info form is following the organization of the image 7.1.
week 02 - 02-01-23 (10)

9.1. (video) Note:When the screen resolution changed during the video, it was because it was switched to landscape mode. 
9.2. The page is a bit larger than the screen.
[week 02 - 02-01-23 (1).webm](https://user-images.githubusercontent.com/114119668/216471126-cc624066-755f-47eb-b712-8c601fdfd516.webm)

**Comment by rauleffting** [comment]
Hi @Filipe-Oliv.  The header component is not related to this PR. Also, the changes must be tested between 425px and 768 px. Thank you!

**Comment by Gukal7** [comment]
Hi @rauleffting I have tested the new code and checked all the bugs that @RafaelCastilhoCastro mentioned earlier. As you can see in the screenshots everything is looking fine now. Good job!
Screenshot 2023-02-02 at 10 39 10 PM
Screenshot 2023-02-02 at 10 38 41 PM
Screenshot 2023-02-02 at 10 38 03 PM
Screenshot 2023-02-02 at 10 36 17 PM
Screenshot 2023-02-02 at 10 35 52 PM
Screenshot 2023-02-02 at 10 35 35 PM

**Review by PrabhjotSembhi — COMMENTED** [review]
Hey @rauleffting , I have checked this. Mostly it's working fine.
Here are some suggestions and minor changes:

1. Profile image and Button Overlapping Menu. I have checked by giving z-index to the ".bg-dark" class. It fixed it 
PR 670 1

2. Change photo button needs some top margin. it touches the Profile photo
PR 670 2

3. Assign Project and Team button is getting cropped while reducing screen size.
PR 670 4

4. Phone field and get time zone is not responsive
PR 670 5

5. Design style  of tabs is not consistent on a large screen and small screen 
PR 670 7
PR 670 8


Please check the video  for more details
https://user-images.githubusercontent.com/82662768/216625585-01c7b9ab-d535-4b60-a8a1-f259f68e6626.mp4

**Comment by RafaelCastilhoCastro** [comment]
Hi @rauleffting,

The changes are working as intended. I found just a few points that require your attention.

1. Badge history could be smaller as to fit the screen horizontally. The badges checkbox is overlapping the blue header.
error1

2. On Assign badge modal the badge checkbox is overlapping blue header.
error2

3. On Edit links modal the link fields are leaking to the right and there's a "/" floating on the bottom left.
error3

Thanks.

**Comment by rauleffting** [comment]
@RafaelCastilhoCastro I've fixed all items that you appointed and extended the responsive improvements to 1024px. Thank you!

**Comment by RafaelCastilhoCastro** [comment]
Hi @rauleffting,
The changes are working fine! I noticed two points though.
1. I still see the floating "/" on Edit links modal though.

error1

2. The Badge history is horizontally bigger than the screen requiring horizontal scrolling. If it is possible to set a new design for mobile responsivity, I'd suggest something like the image below.

idea

Thank you.

**Comment by rauleffting** [comment]
Hi @RafaelCastilhoCastro. I deleted the floating "/" and added a Dropdown button to the badges table. Take a look again! Thank you very much!

**Comment by Filipe-Oliv** [comment]
HI @rauleffting 

Considering the aspects you ask us to pay atention for now.

Here are two things I caught

1 . In the basic information, the 'role' field is overtaking the screen
week 02 - 02-04-23 (1)

2. In the basic information, the 'Time Zone' field is overtaking the screen.
3week 02 - 02-04-23 (2)

Please let me know if I need to revise something.

**Review by Theophileaseh — CHANGES_REQUESTED** [review]
Hi @rauleffting 

## CHANGES REQUESTED ♻️ 

- 
- Greate work on implementing the project requirements ✔️ 
- Linter is failing ❌ 

Can you please ensure the linter is passing
Cheers and happy coding 💻

**Comment by rauleffting** [comment]
> Hi @rauleffting
> 
> ## CHANGES REQUESTED ♻️
> * Great work on implementing the project requirements ✔️
> * Linter is failing ❌
> 
> Can you please ensure the linter is passing Cheers and happy coding 💻

Hi, @Theophileaseh! We don't use the eslint on the front end. It's not working - just the prettier. Eslint works only on the backend. Thank you very much!

**Comment by RafaelCastilhoCastro** [comment]
Hi @rauleffting,
I'll test this PR again as soon as you can check the issues pointed out by @Filipe-Oliv.
Thank you.

**Comment by PrabhjotSembhi** [comment]
Hi @rauleffting, Just checking the status of this. Are all comments addressed and when I can rereview this?

**Comment by suigunfjc** [comment]
Hi @rauleffting.

I tested your features and they are awesome. I just got a few questions.

I saw that you have addressed the 'role' field overtaking situation mentioned by @Filipe-Oliv. I think you also fixed the 'time zone' field with a similar method but it still overtaking the screen a little bit when I set the screen width to 420px. Don't think it's a big deal though. 

Another thing I noticed is that the width of the 'phone' field is hard coded to 300px, not sure if it needs to be responsive.

The last question is that I don't see the difference between the red 'X' button (cancel button in PC view) and the reset button. They seem to do the same thing. 


https://user-images.githubusercontent.com/94319381/219844363-adb71680-cb4a-4e7c-820c-e7b31f748eb2.mp4

All other features look good to me, great job!

**Comment by rauleffting** [comment]
Hi guys. This PR is ready. The field overtaking situation is a bug of the chrome inspector. It doesn't get well with React. About the phone input size, it cannot be changed, because it's a library with a pattern, and I didn't choose it. Thank you all!

**Comment by Jorge-Nerd** [comment]
Hello @rauleffting  I like the modifications you made, but I noticed that you need some padding for the letters in these dimensions 1024 * 600

image

**Comment by Filipe-Oliv** [comment]
Hi @rauleffting 

I tested your PR in Edge and Chrome. Both went well.

I'm gonna approve your PR. 

[02-20-2023 (1).webm](https://user-images.githubusercontent.com/114119668/220099659-f5f6a194-c292-4e78-9088-45dc7abe635a.webm)

**Review by Filipe-Oliv — DISMISSED** [review]

**Comment by rauleffting** [comment]
> Hello @rauleffting I like the modifications you made, but I noticed that you need some padding for the letters in these dimensions 1024 * 600
> 
> image

Hi Jorge. That page is not related to this PR. Thank you!

**Comment by Jorge-Nerd** [comment]
> > Hello @rauleffting I like the modifications you made, but I noticed that you need some padding for the letters in these dimensions 1024 * 600
> > image
> 
> Hi Jorge. That page is not related to this PR. Thank you!

@rauleffting Ohh ok sorry for the mistake, overall good job then

**Comment by NyahJ** [comment]
Hello @rauleffting,

Thanks for updating this PR, I followed your 2 videos attached to test, other than the overlapping to be addressed by another PR, every change worked so well for different sizes of the screen.
However, I met another issue about "Full View of Badge History" shown as below in the vidoe, which I am not sure if this should be fixed by this PR. 
I tesed to change the amounts of the badges:
1. some numbers could not be changed; 
2. For the numbers could be changed, we can only use the increase/decrease button instead of manually typing directly;
3. The small modal would disapear after every change, which is not user-friendly.
https://user-images.githubusercontent.com/77643813/221712947-1194c224-7843-46ed-a6c2-065f18f539d0.mp4

**Comment by rauleffting** [comment]
Please, guys, approve this PR again. I disabled jest to avoid conflicts because we are not using this yet.

**Comment by rauleffting** [comment]
Hi @NyahJ. I saw your review just now. I'm going to check it. Thank you!

**Comment by rauleffting** [comment]
Hi @NyahJ. Already fixed! Please, approve if everything works well. Thank you!

**Review by NyahJ — APPROVED** [review]
Hi @rauleffting,

Tested and reviewed the update. Awesome, they all got fixed and worked perfectly! 
Thanks for your efforts!

截屏2023-03-01 下午1 14 21

**Comment by RafaelCastilhoCastro** [comment]
Thanks @NyahJ and @rauleffting.
Moving this PR to be reviewed by the leadership team.

**Comment by anant2047** [comment]
Gave some minor comments on the code. Tested the responsiveness and it works well for most of the devices. Amazing effort!
Here is the responsiveness on most of the devices - 

https://user-images.githubusercontent.com/97596031/222317807-bcfa99f6-c353-4130-b8ea-1ec162b9a85c.mov

Found a few issues. The menu is not visible in few devices - 


https://user-images.githubusercontent.com/97596031/222317974-08fc8b27-734d-4c36-b0b0-54d731eaca5c.mov


Responsive issue in galaxy fold - 

https://user-images.githubusercontent.com/97596031/222318031-6d17b563-0bb6-45b6-82e9-735a837ba79b.mov

**Review by Lucas-E — COMMENTED** [review]
Hey Raul, I've tested your PR and it looks really good. From devices with width equal or higher than 412 it's fully responsive, as you've specified.
Captura de tela de 2023-03-02 00-21-27
Captura de tela de 2023-03-02 00-19-32

**Comment by Lunaliar** [comment]
Hey @rauleffting, I tested out the responsiveness of the profile page, I think it's a good idea to have the different items in a concise column like you have set up, good job! I do have a few suggestions that maybe improve the UX on this page:
1. If a screen can fit all of the content it doesn't need to scroll as it does in this video at an iPad size.
[Ipad air res.webm](https://user-images.githubusercontent.com/98275089/222626411-98c16214-98e5-4ac3-bb9d-e4e0df2a0510.webm)
2. While I was testing this at resolutions 425 and 1024 I noticed some weird breakpoints around 470 px as you can see in the video below
[Landscape response.webm](https://user-images.githubusercontent.com/98275089/222626467-adb23934-551b-49f3-9130-00db93aa3cd9.webm)
3. I found the landscape orientation to be a bit hard to use with certain elements of the page being a bit too close to the sides of the screen. Ideally, the user has access to their whole screen but people that have otter box or other heavy-duty protection cases with raised edges may have a hard time clicking on elements that don't have quite enough padding.

**Comment by dkamghem** [comment]
The profile is responsive as shown below:
IMG_2380

**Comment by mpavithr** [comment]
Hi, I tested the responsiveness and it seems to work well for me! If I have to make suggestions, I notice that the spacing in the volunteering times of the profile page isn't consistent.  Sometimes there is a space between the categories, and sometimes there isn't.
pr670_3
pr670_2
pr670_1

**Review by RafaelCastilhoCastro — APPROVED** [review]
Hi @rauleffting,
I tested your PR and the screens are working of small screens as intended. Thanks.

**Comment by one-community** [comment]
Finally fully tested this on my phone. Looks good, thank you everyone!

**Pull request merged**
