### PR TITLE
Shengwei fix icon formatting issue in dashboard and user profile component

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
image

## Related PRS (if any):
I took over the task from PR1561. This frontend PR is related to the #[1561](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1561).
…

## Main changes explained:
- Change the information tooltip position to the center of the dashboard page.
- Adjust icon alignment time-log component on the dashboard page.
- Update phone input field length to match with other fields when the page resizes.
- Adjust icon alignment in the user profile page
- Update the Location button length to match with other input fields in the user profile page.
- Adjust placement of the information icon after the role input field in the user profile page.

The following are updated from PR1561
- Align certain items to be on the same line at the top of the page, correcting a bump-down issue.
- In individual profiles, fix a spacing issue to ensure uniformity.
- Adjust the spacing so each element has the same amount of space.
- Make phone input width 100% so they match other input length.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. verify information tooltip on center
5. verify information tooltip, active icon, and use icon on same line
6. verify information tooltip on user profile page spacing fixed
7. verify phone input on user profile page have same width as other input

## Note:
Before:
[Video link for details](https://www.loom.com/share/3eb48d69e36249ef945a709197713ced?sid=1571d129-fd39-4c72-a5cb-ad870b7bbc7d)

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/10f1d80d-3854-47f3-8776-f630bf6d7017

### CODE REVIEW

**Review by chrischenlixing — APPROVED** [review]
image
All changes on the main page looks good
image
All Changes on the user profile page looks good even when extending the display.
Correct me if I am wrong, in the "How to test" instructions, it's asked to log in as an admin, but I believe logging in as a "volunteer" would also work?

**Review by ShengjieMao — APPROVED** [review]
THe format looked good and worked as expected. Great work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/90d3356b-4006-44e5-8834-cda5d8ec6c49

**Review by TareqMia — APPROVED** [review]
Hi @ptrpengdev, tested out this PR and everything looks good and nicely formatted 👍 
Screenshot 2024-02-17 at 9 49 44 AM
Screenshot 2024-02-17 at 9 50 25 AM

Screenshot 2024-02-17 at 9 50 33 AM

**Review by n0vay — APPROVED** [review]
Looks Good to Me
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
