### PR TITLE
Dhrumil - Added tests cases for Teams.

### PR DESCRIPTION
**Pull request by ddshah878**
Description
Unit test for src/components/Teams/Teams.jsx

Main changes explained:
•	Added a new file under __tests__ called Teams.test.js
•	The list of test cases for `Teams`
- renders `Teams` component without errors
- calls `getAllUserTeams` and `getAllUserProfile` on `componentDidMount`
- updates state when `onWildCardSearch` is called
- calls `deleteTeam` and shows success toast message when `onDeleteUser` is called
- renders `Loading` component when `fetching` is set to true
- toggles `sortTeamNameState` when `toggleTeamNameSort` is called
- toggles `sortTeamActiveState` when `toggleTeamActiveSort` is called
- calls `getTeamMembers` and opens team members popup when `onTeamMembersPopupShow` is called
- closes team members popup when `onTeamMembersPopupClose` is called
- calls `deleteTeamMember` when `onDeleteTeamMember` is called

How to test:
1.	check into current branch
2.	do npm install and npm test Teams.test.js
3.	check if all test cases pass without any error.

## Screenshots or videos of changes:
image

## Note:
Ignore error Teams is not an array.

### CODE REVIEW

**Review by lucy-xfl — APPROVED** [review]
Every test pasted on my side.
image

**Comment by pallavithorat** [comment]
All test cases have passed successfully without any errors, indicating that the Teams component's functionality is working as expected.

Screenshot 2024-10-16 at 3 49 49 PM

**Comment by SatyashanthiT** [comment]
I have tested the PR for Teams unit tests, verified all the test cases, including the rendering and various state update functions, and confirmed that they pass successfully without any issues
image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (229)

**Review by manikittu810 — APPROVED** [review]
Hello @ddshah878 
Everything is running as mentioned.
Screenshot 2024-10-18 at 9 12 09 AM

Thank you.

**Review by SharadhaS24 — APPROVED** [review]
All the 11 test cases have passed without any issues indicating the proper functionality of teams.

image

**Comment by geetamatkar** [comment]
Tested this PR and all test cases have passed.

**Comment by mianmiantea2019** [comment]
All tests passed

image

**Review by vishavk1992 — APPROVED** [review]
All test cases passed successfully !!!
Screenshot 2024-10-21 201820

**Review by slidracoon72 — APPROVED** [review]
#2788 
@ddshah878 
I have reviewed and tested the PR, and all test cases have passed successfully.

Screenshot 2024-10-23 at 12 54 46 PM

**Review by beblicarl — CHANGES_REQUESTED** [review]
All tests passed successfully however there are a lot of errors in the console

image

**Review by anirudhsk2107 — APPROVED** [review]
The tests have passed
Screen Shot 2024-10-25 at 8 19 05 PM

**Review by Anoushka21 — APPROVED** [review]
All tests are passing!
image

**Review by bhavya17prakash — APPROVED** [review]
All test cases are passing
PR 2788

**Review by RachanaZha — APPROVED** [review]
All test cases related to this PR have passed successfully. Please find below the screenshot of test result:
zha_rachana_PR#2788

**Review by CodewithKoushica — CHANGES_REQUESTED** [review]
All the test cases passed.
Please consider:
The Teams.test.js file throws an error: Teams is not an array: undefined. It seems teams may be undefined during testing. Adding a default empty array or a check to ensure teams is defined before this check could resolve this.

Thanks!

Screenshot 2024-10-30 at 9 31 17 AM

**Review by samarth9201 — APPROVED** [review]
All tests passed. 
Screenshot 2024-10-31 021036

**Review by vijay10pk — APPROVED** [review]
All the test cases passed bu there are errors in the console. Please fix it if it's in the test file.
image

**Review by anirudhsk2107 — APPROVED** [review]
All test cases have passed 
Screenshot 2024-12-12 143656

**Pull request merged**
