### PR TITLE
Yongjian - Create back to top button on index page (NEW)

### PR DESCRIPTION
**Pull request by ypan710**
# Description
Screen Shot 2023-05-04 at 11 23 45 PM

## Mainly changes explained:
Added a link styled as a button that appears as an user starts to scroll down the index (dashboard) page and navigate the user to the top of the dashboard page upon clicking. (Note: I created this PR to reflect the changes for PR#801 as it hasn't been reflected through merge for PR#801).

## How to test:
1. check into current branch
2. do `npm run start:local`
4. login as any role to the dashboard page and as an user starts to scroll to the bottom of the page, the "Back to Top!" button on the right hand side will appear and upon clicking, the user should be navigated to the top of the dashboard page.

## Screenshots

Screen Shot 2023-05-06 at 1 55 29 PM

Screen Shot 2023-05-06 at 1 55 53 PM

Screen Shot 2023-05-06 at 1 56 00 PM

Screen Shot 2023-05-06 at 1 56 32 PM

### CODE REVIEW

**Review by stevenpaalz — DISMISSED** [review]
This change works as intended across all pages.

One thought: It may make sense for this button to exist as its own React component that we can opt to include within certain routes. Otherwise this will appear on all pages. But if that is our intention then this is fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/e68646fe-ef72-46c9-b659-55ebcebb6e4a

**Review by mahamakhan — DISMISSED** [review]
back to the top button works fine.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/106139234/78d30b54-794f-4f53-b2d0-ea1af8073cc3

**Review by OAkinbode — COMMENTED** [review]
Hello Yongjian, 

The button works as intended. I do have a suggestion. Can we style the button to fit more with the general theme of the site? An example is box-shadows. I included that in my local code to see how it looks:
PR 909 look

The code:
PR 909 code suggestion
I believe there is an existing CSS file you can call to apply this.

**Comment by Lucas-E** [comment]
Hey @ypan710, great job! Please resolve the conflicts and DM me so I can move this PR to final review!

**Comment by AnishPandita** [comment]
Hi @ypan710, I tested the PR and was able to replicate the desired result.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/1d3c1ed6-cbf5-43a7-8b17-b3d93a15bc36

**Review by eduhorta — COMMENTED** [review]
Hi, @ypan710!
The feature is working on all pages as intended. Nice job! 👍
Please, resolve the conflict on this branch so we can approve.
Screenshot 2023-06-14 09-29-29

**Review by Chuehleo — DISMISSED** [review]
Everything work as intended, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/0cdc23cf-fdff-4619-b71b-ce4eb04e70f3

One thought:  consider keeping the words white with just an underline effect when hovering on the button for better clarity.
螢幕擷取畫面 (14)

**Review by cvtqx — APPROVED** [review]
The button works as described! 

Screen Shot 2023-06-14 at 3 08 46 PM

**Review by KurtisIvey — APPROVED** [review]
Works as intended. When back to top is pressed, it does just that. 

pr909 back to top works

**Comment by rachnapandya** [comment]
The feature is working as intended. Appreciated @ypan710 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/47ac6462-727c-4a95-a77c-4006d55732fb

**Review by bienzguoa — DISMISSED** [review]
Works as intended! Agree with the comment adjusting the style to fit the theme.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/33b0b856-a9d4-46a4-a3a2-1206e88498b0

**Review by NidaZaki — APPROVED** [review]
The button works as intended!

**Review by leonzh2k — APPROVED** [review]
Works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/737ea4e9-919e-4861-92b2-7a6c9af0bcd7

A potential UI change you could make: currently the text on the button turns blue on hover to indicate you can interact with it, but against the black background it makes for bad contrast. Consider changing the colors.

**Review by yufeiStella — DISMISSED** [review]
Great job! The button works as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/6056d8ac-a0fa-4486-9d15-a4a60c5538f6

**Review by EdwinLauM — COMMENTED** [review]
Works as intended! Like other members have mentioned, please resolve the conflict and will approve! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/98c8a21d-ec54-446e-805b-902e3b824a95

**Comment by one-community** [comment]
Thank you everyone! Merging!

**Pull request merged**
