### PR TITLE
John Add new total row to Leaderboard

### PR DESCRIPTION
**Pull request by Cavein254**
# Description

Screenshot 2024-02-02 100112

## Related PRS (if any):
This frontend PR is not related to any backend PR
…

## Main changes explained:
Added a new row below the `HGN Totals`
Added `BLUE` color to the row text
…

## How to test:
Check into current branch
Do `npm install` and `...` to run this PR locally
Clear site data/cache
Log as admin user
Go to the Dashboard → Leaderboard
Check if a row is added
Check if the text is blue

## Before
Screenshot 2024-02-02 142211
## After
Screenshot 2024-03-02 224116

### CODE REVIEW

**Review by Sophie-lei — DISMISSED** [review]
Hey, I tested this PR as the owner role and admin role. the CSS style has been changed successfully.
Screenshot 2024-02-03 at 15 17 04
Screenshot 2024-02-03 at 15 17 44

**Comment by galgalinidhi** [comment]
Hi @Cavein254, I tested the PR for Admin, Owner and Core Team accounts and I see the row added for all.

Screenshot 2024-02-03 at 1 46 37 AM

Screenshot 2024-02-03 at 1 48 52 AM

Screenshot 2024-02-03 at 1 45 59 AM

**Review by peterson337 — DISMISSED** [review]
HI [Cavein254](https://github.com/Cavein254), tested your application, and everything worked as expected. Good job!

a

**Review by ShengjieMao — DISMISSED** [review]
The row is in the right position and font color is blue as mentioned in the instruction.
PR_1908

**Comment by swathyjayaseelan** [comment]
The new added row is visible to all roles. I logged in as Volunteer and I was able to see the row. According to the requirement, shouldn't it only be visible for Admin, Core and Owner roles. Please check with Jae on the requirement. 
Also, the total member count 'XXX' is hard coded now. Though the backend is not coded yet and the API is not returning the data, in the front-end we can add hard code the value in the org data in LeaderBoard.Container.jsx so that it can be easily hooked up to the API when it is ready.
![Screenshot 2024-02-02 at 11 26 49 PM]

**Review by 666saofeng — APPROVED** [review]
Hi, I tested with the admin account. It worked as expected. 
image

**Review by Nahiyan-16 — COMMENTED** [review]
## Displays correctly
Hi John, I tested this feature by checking responsiveness when resizing and everything seems to be fine. 
One quick note, **is this feature supposed to be available for all roles or just Admin/Owner?**

Screenshot 2024-02-03 152640

**Comment by xmyoot** [comment]
Hello, I tested this and it worked great from the admin account reference the photo please: 
PR#1908

**Review by X1aoZhang99 — DISMISSED** [review]
Hi John,

I've tested the PR with the admin user. I notice that a new row has been added, and the text in this row is colored blue. Please refer to the video. Nice work! 

Screenshot 2024-02-04 at 20 47 17

**Review by prnvjn — DISMISSED** [review]
Works as per requirement, can see the row with 0 hrs Totals: xxx in blue color
Screenshot 2024-02-08 at 7 57 15 PM

**Comment by nnamdixobi** [comment]
Looks good but I believe it will help and make it look better if you were to add the loading bar beside it for the total members too

**Review by TapanPathak — DISMISSED** [review]
Hi, tested your PR, and everything worked as expected!

Screenshot 2024-02-14 at 12 19 52 PM

**Comment by one-community** [comment]
Please make this change: https://www.loom.com/share/dc5211e6306041ad8e3be7d1d43b24f6?sid=70377f94-a07b-4161-b8e3-ed95a302720f

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and all features worked as expected.

novoPRprint

**Review by chrischenlixing — COMMENTED** [review]
image
Hello John, I logged in as an admin and it's working properly as it's showing the actual number for the 0 hours members and the position of it is correct. However, is there suppose to be more 0 hours members than the actual total numbers for the members?
image
I also logged in as a volunteer, from my perspective, it's shouldn't be shown for a volunteer maybe?

**Comment by Cavein254** [comment]
@chrischenlixing, Added the requested changes. Kindly re-review.

**Comment by dhairya-mehta** [comment]
Hey, I reviewed your code and approve the changes!
image

**Review by XiaohanMeng — DISMISSED** [review]
Hi, I tested this PR using both the owner and admin accounts. Both accounts were able to view the added row—well done!
1908_result1

1908_result2

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Requesting changes due to inline styling right here. We use Bootstrap classes and also have dedicated stylesheets. It's considered bad practice and should be avoided whenever possible, unless complex logic necessitates it. 

Screenshot 2024-02-24 at 4 33 12 PM

Other than that, everything else looks fine, and you seem to have modified it to reach the visual Jae wanted as shown in his video. 

Screenshot 2024-02-24 at 4 27 49 PM

**Review by skaush21 — APPROVED** [review]
Total hours row appears directly below 'HGN Totals', features looked good!

Screen Shot 2024-02-29 at 10 49 35 PM

**Review by MALAV1308 — DISMISSED** [review]
Hello John, I reviewed your PR and it is working fine. Great Job! 
image

**Review by YHX6 — DISMISSED** [review]
The new line is added. Here is an overview
Screenshot 2024-03-02 at 17 15 33

**Comment by DiegoSalas27** [comment]
Hi John. Great work. I have tested your PR and it's working as expected. Attached to this comment is an image displaying the functionality you implemented:

image

**Review by PratimaSingh02 — DISMISSED** [review]
- The blue row is visible
zero hours

**Review by psharma1984 — DISMISSED** [review]
Hi @Cavein254 I tested with owner and admin account and saw the row added for both.
a
b

**Review by hetvi11110 — DISMISSED** [review]
I tested this code on my local server and it is working as described. Here is the screenshot:
Screenshot 2024-03-04 211415

**Review by Gugor99 — DISMISSED** [review]
### Report
Hi John, 
I checked your implementation and it works as expected. As you can see from the screenshots, I logged in both with an admin and a volunteer account. I was able to see the new row only with the admin's account. Also changes are responsive and everything seems to work properly, well done!
### Screenshots
Cattura1
Cattura2

**Review by Tiantian-C — COMMENTED** [review]
It looks right! But I wonder whether the total hours is 0 ?
Screenshot 2024-03-06 at 1 21 20 PM

**Review by Weiyao-Li — DISMISSED** [review]
Hi, great work here. I logged in as an admin. It works as expected. Well done
image

**Review by SRamen1999 — DISMISSED** [review]
Tested this PR, and everything worked as expected. I logged in as Admin user and can see the new row changes.

Screen Shot 2024-03-07 at 7 12 38 PM

**Review by Coops023 — APPROVED** [review]
Hi John i have reviewed this PR and it is functioning as intended, well done!

Screenshot 2024-03-08 at 19 42 19

**Review by bhuvan-dv — DISMISSED** [review]
Changes are working as expected
PR-1908

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Requesting changes due to camelCasing of css class and bad css class naming. Though you may see camelcasing of css classnames in various stylesheets, those are mistakes leftover from previous devs. Use hyphens for css and camelcasing for variables. We at the very least don't want the problem to grow larger.
Screenshot 2024-03-16 at 1 16 01 PM

In addition, naming the class "orgName" would have me assume this is some sort of large title saying HGN. Where as in actual use, it's a flexbox container. The div is also unnecessary as this class could just be applied to the tableheader the div resides in

Action list:
   1. rename .orgName to leaderboard-totals-container or something along the lines of that. It's really up to you, but just make sure the name describes what it's doing at the very least. We should be able to identify where it's being applied by the naming down the line incase someone else has to modify it.
   2. Remove the div entirely since it's doing nothing by being there. Apply the new css class name to the tableheader the totals are within.

**Comment by Cavein254** [comment]
> Requesting changes due to camelCasing of css class and bad css class naming. Though you may see camelcasing of css classnames in various stylesheets, those are mistakes leftover from previous devs. Use hyphens for css and camelcasing for variables. We at the very least don't want the problem to grow larger. Screenshot 2024-03-16 at 1 16 01 PM
> 
> In addition, naming the class "orgName" would have me assume this is some sort of large title saying HGN. Where as in actual use, it's a flexbox container. The div is also unnecessary as this class could just be applied to the tableheader the div resides in
> 
> Action list:
> 
>     1. rename .orgName to leaderboard-totals-container or something along the lines of that. It's really up to you, but just make sure the name describes what it's doing at the very least. We should be able to identify where it's being applied by the naming down the line incase someone else has to modify it.
> 
>     2. Remove the div entirely since it's doing nothing by being there. Apply the new css class name to the tableheader the totals are within.

Added requested changes rega
PR 1908 Code
rding the css and the div

**Comment by Cavein254** [comment]
> Requesting changes due to camelCasing of css class and bad css class naming. Though you may see camelcasing of css classnames in various stylesheets, those are mistakes leftover from previous devs. Use hyphens for css and camelcasing for variables. We at the very least don't want the problem to grow larger. Screenshot 2024-03-16 at 1 16 01 PM
> 
> In addition, naming the class "orgName" would have me assume this is some sort of large title saying HGN. Where as in actual use, it's a flexbox container. The div is also unnecessary as this class could just be applied to the tableheader the div resides in
> 
> Action list:
> 
>     1. rename .orgName to leaderboard-totals-container or something along the lines of that. It's really up to you, but just make sure the name describes what it's doing at the very least. We should be able to identify where it's being applied by the naming down the line incase someone else has to modify it.
> 
>     2. Remove the div entirely since it's doing nothing by being there. Apply the new css class name to the tableheader the totals are within.

@KurtisIvey , Added the requested changes

Screenshot 2024-03-16 230106

**Review by KurtisIvey — APPROVED** [review]
Looks and functions well. Great job on cleaning up the css naming. Will make it extremely easy for the next maintainer should they need to revisit this area.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
