### PR TITLE
Kaikanes lessonform draganddrop

### PR DESCRIPTION
**Pull request by lacnoskillz**
# Description
Added Drag and Drop feature to my lesson from design

## Related PRS (if any):
Added feature to Front end PR
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1477

## Main changes explained:
- added the ability to drag and drop

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as anyone
4. go to  http://localhost:3000/bmdashboard/lessonform
5. verify drag and drop functionality works in various view ports and scenarios

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/009342a7-9157-466f-9d28-0b1bfba1ca0f

## Note:
Still no backend functionality

### CODE REVIEW

**Review by tsunami776 — APPROVED** [review]
Hi @lacnoskillz, I tested your PR locally and it works as described. The Default placeholder image looks good to me. Drag and drop feature works for different files. No error was thrown in the browser console. Nice work!

Test video:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/fdc0f350-9e30-4ce6-8ee3-126498d9ecf6

**Review by Sssky-18 — APPROVED** [review]
Hi @lacnoskillz , I just tested this PR, and the drag and drop functionality worked well in various view ports and scenarios. I tested drag into both pics and video, and it worked as expected. Thank you for your great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/61b3e53b-f08a-4738-a3b9-f55da45ba50f

**Review by Jiyuanxia — APPROVED** [review]
Hi @lacnoskillz , I have reviewed your pull request and tested it. It works as you intended. Good job!
Screenshot 2023-11-09 104958
Screenshot 2023-11-09 105014

**Review by sxiong5 — APPROVED** [review]
Hey @lacnoskillz, I have tested the PR and it worked as intended. Nice job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/4d8f6abd-8e83-4e59-b0e6-1a4decc927ce

**Review by pika-chu11 — APPROVED** [review]
Hi @lacnoskillz, you did a great job! The function works perfectly fine when I drag and drop my imag

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/43d5e683-dcbc-4624-a81e-28942876120b

es into the Upload area.

**Review by Shubhu0 — APPROVED** [review]
Hi @lacnoskillz reviewed your PR and the select-by-drop feature is working as intended

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/39087100-e0e4-42c2-b811-dc7995d42206

**Review by sahilpatel18 — APPROVED** [review]
Hi @lacnoskillz, I've checked the drag and drop feature across different viewports and situations, and it's functioning perfectly. Great work!

Uploading Screen Recording 2023-11-10 at 1.57.31 AM.mov…

**Review by Iris-Song — CHANGES_REQUESTED** [review]
Hi @lacnoskillz reviewed your PR and the select-by-drop feature is working as intended. But I think you have accidentally changed logo.png. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/018d522e-fdc5-465d-a8c4-03757919df39

**Comment by lacnoskillz** [comment]
@Iris-Song 
Hey I don't know why I got all those changes.
I didn't touch logo and a bunch of those other files
If you look it says the logo was deleted then added.
If anyone has suggestions for an easy fix let me know.
Other wise I could re clone development and make another branch

**Comment by AriaYu927** [comment]
Hi @lacnoskillz , I've tested your PR, the drag and drop functionalities works great. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/1496ff8e-68ea-4778-a277-03477e911e52

**Comment by palakgosalia** [comment]
Hey, I reviewed and tested your PR and it works as intended. I was able to drop images as well as videos. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/d9431ebe-6b13-45eb-871c-557feb7413ff

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and drag and drop functionality works as intended. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/505694b5-b672-4f15-8c22-a4b4ab6b9e65

**Comment by mounica-dingari-by** [comment]
Hi @lacnoskillz , I've tested your PR and the drag and drop works well !

Screenshot from 2023-11-11 11-11-33

Screenshot from 2023-11-11 11-12-48

Screenshot from 2023-11-11 11-11-28

**Review by zuhang2000 — APPROVED** [review]
Hey, I have tested your PR and it works as expected. 

I test dropping images and also videos. The feature works perfectly. The following recording is the test details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/f13d521b-e485-475b-8f5a-f913740d4533

**Comment by one-community** [comment]
For this, the app will (currently) most commonly be used with an tablet. Please be sure it’s on the action list to add a “take photo” option to your function too, so people can just take a picture with the device they are on. This will be much more streamlined and probably get way more use than drag and drop. We definitely want both though!

**Comment by lacnoskillz** [comment]
Remade branch 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1577

**Pull request closed without merging**
