### PR TITLE
Masasa - Rearranged permissions and indented sub_permissions

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
# Description
This pull request implements the requirements as specified by the screenshot below:
Screenshot 2023-08-15 at 3 10 24 PM
Screenshot 2023-08-21 at 12 51 55 PM

The goal is to rearrange the permissions such that they are ordered according to how they are organized in this [spreadsheet](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit#gid=0)

Then after ordering the should be formatted to have the permissions in white being the main ones while the ones in blue become indented to show that they are subordinate to the ones in the white row.

## Related PRS (if any):
it is not related to any back end PR
…

## Main changes explained:
- rearranged the order of permissions in UserRoleTab
- added new logic and formatting in rolePermissions …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner user
4. go to otherlinks→ Permission Management→ choose any Role→…
5. verify that it looks like the screenshot

## Screenshots or videos of changes:

Screenshot 2023-08-17 at 5 22 16 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by luisarevalo21 — APPROVED** [review]
Hello @ThapeloMasasa 

I tested your PR and works as intended. Great work!
When I logged in as an owner account I visited permissions management  selected mentor and admin and the permission list is organized as you showed in your screenshot. 

No issues occurred.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/d0f6eeac-d7bc-4ab4-ab26-de85d3eb38d6

Screenshot 2023-08-17 at 7 38 49 PM

**Review by n0vay — DISMISSED** [review]
Works perfectly
image

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this one to final review!

**Comment by beblicarl** [comment]
This works as intended.

screenshot-localhost_3000-2023 08 18-10_09_12

**Review by beblicarl — DISMISSED** [review]

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change work perfectly on my device
image

**Review by veronicacheng2 — APPROVED** [review]
Hi @ThapeloMasasa, I have checked on my end. Everything looks good and neat.

### Mentor Permission
image

### Owner Permission
image

### Admin Permission
image

**Comment by AnishPandita** [comment]
Hi, the rearrangement looks perfect. No issues found.
Screenshot 2023-08-18 at 3 13 46 PM

**Review by TheDescendant39 — COMMENTED** [review]
Hi @ThapeloMasasa, PR changes work as intended.
Screen Shot 2023-08-18 at 4 26 22 PM

**Review by yaow62023 — APPROVED** [review]
Works as intended. Good Job!

**Comment by one-community** [comment]
Excellent job everyone, thank you. Looks great and I see Carl's approval on this already, so I'll merge it as soon as the merge conflicts are addressed.

**Pull request merged**
