### PR TITLE
Pallavi improve user management page search

### PR DESCRIPTION
**Pull request by pallavithorat**
# Description

This pull request resolves two issues in the User Management page:

1) Improved Search Functionality: This pull request resolves an issue in the User Management search functionality, where adding a space after a search term (e.g., "Li ") was intended to limit the search to exact matches for that term, rather than partial matches. Previously, the system returned all names containing the search term, even if an exact match with a trailing space was entered (e.g., entering "test " would incorrectly return names like "testuser" instead of just "test").

2) Dark Mode Bug Fix: Fixes a bug where switching from the dashboard in dark mode to the User Management page and then back to light mode caused the table format to remain in dark mode. Now, the table correctly updates to reflect the selected theme.

Fixes #2197 
Task1

## Main changes explained:

Updated the User Management component to improve search functionality by supporting exact matches for firstName and lastName when a trailing space is added (e.g., "test " returns only "test" and not "testuser"). Additionally, enhanced dark mode handling to ensure seamless theme transitions, with the table format correctly switching between dark and light modes.

## How to test:
1. check into current branch

2. do npm start to run this PR locally

3. Clear site data/cache

4. log as admin user

5. go to dashboard→ Other Links -> User Management

6.Verify that the functionality behaves as expected with the new exact-match search in the First Name and Last Name columns. Ensure that entering a name with a trailing space (e.g., "test ") returns only exact matches. Additionally, test the dark mode transition to confirm that the table format switches correctly between dark and light themes. Please see the attached screenshot for confirmation

## Screenshots or videos of changes:
# Before Picture:
Before 1
Before_

# After Resolving Bug:

https://github.com/user-attachments/assets/264d4391-6c1d-4be0-bbba-ea94b687bda0

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/4873a94b-79e7-45cc-819b-83cdad3321b7

**Review by vijay10pk — APPROVED** [review]
Changes works as expected.
Screenshot 2024-11-15 at 11 20 23 PM
Screenshot 2024-11-15 at 11 20 11 PM

**Review by nikhilgiri0226 — APPROVED** [review]
I have reviewed the PR and everything works as expected. With a trailing space while searching ("test ") returns the exact match and also it works fine in both light and dark mode.


https://github.com/user-attachments/assets/91db1ecf-8bfa-47a6-9457-9493e59f8d65

**Review by RashmiKY98 — APPROVED** [review]
Tested the feature in dark and light mode. Reviewed the code changes. No issues found.
Screenshot 2024-11-17 012455
Screenshot 2024-11-17 012346

**Comment by SatyashanthiT** [comment]
Verified that the updated search functionality correctly returns exact matches when a trailing space is added, and the dark mode bug fix ensures seamless theme transitions between light and dark modes. Everything works as intended. Approved the changes.

image

**Pull request merged**
