### PR TITLE
Lucile_T_make_cursor_start_in_fields

### PR DESCRIPTION
**Pull request by LucileTech**
# Description 
(PRIORITY LOW) Make cursor start in fields on Teams, Projects, and other pages 
Other Links → Projects or Teams → click icons/edit/etc.
I’d like to have the cursor start in the available fields so it is more efficient when using these pages. Modals with individual empty fields automatically put the cursor in the empty field, so I can immediately start typing rather than having to manually put the cursor in the field and then do my typing. 
For instance, in the image below, right now I have to click the “members” icon, then click in the field to type. There’s no other reason to click that icon though, so the typing cursor should automatically go into the typing field to save clicks and time. 
Please check all other pages and apply this wherever it makes sense there too

## Main changes explained:
- Autofocus was added on inputs so when you go on projects, members, teams pages, there is now a focus on the input so you can start typing without clicking in the input first

## How to test:
1. git checkout Lucile_T_make_cursor_start_in_fields
2. git pull
3. `npm install` and `npm run start:local` to run this PR locally
4. log as admin user
5. go to dashboard→ Other Links → Projects or Teams → click icons/edit/etc.

## Video of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111132148/2ddf5fce-21b6-438b-bdd4-aba4f0e3288f

## Screenshots :
You should have autofocus on those pages : 

Members on projects : 
autofocus

User Management : 
autofocus 2

Teams : 
autofocus 3

Reports : 
autofocus 4

### CODE REVIEW

**Review by jonathancarpena — DISMISSED** [review]
Works perfectly. On Members, Reports, Teams, and User Management pages, the autofocus field works as expected! Good job! 👍


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/125dad64-63b1-4f6b-8663-5ca60d62e4ba

**Review by EdwinLauM — DISMISSED** [review]
Works as intended! Auto focuses on the input fields! Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/ace0768f-8761-4493-8280-69c9ff19169a

**Review by mahamakhan — APPROVED** [review]
Checked user management, teams and projects. Everything works as mentioned.

**Review by Chuehleo — APPROVED** [review]
Everything work as intended, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/20f582eb-0653-43b0-807a-eea94099aeac

**Comment by AnishPandita** [comment]
Hi @LucileTech I tested the PR and everything works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/08262c5c-2152-455a-89fa-fc9969170c14

**Review by eduhorta — DISMISSED** [review]
Auto focus is working properly on the input fields! 
Great job! 👍

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/b2ba8cde-c031-468a-a472-333ba549c9bd

**Review by KurtisIvey — DISMISSED** [review]
functions perfectly. Nice little ui feature that I had forgotten about. Will have to implement this into some of my own stuff.
pr928 works with autofocus

**Comment by one-community** [comment]
Fix the merge conflicts on this one and I’ll move it to final review!

**Review by cvtqx — COMMENTED** [review]
Autofocus works on all the mentioned input fields:

User management:
Screen Shot 2023-06-22 at 3 48 46 PM

Projects->members:
Screen Shot 2023-06-22 at 3 48 59 PM

Teams:
Screen Shot 2023-06-22 at 3 49 06 PM

**Comment by yufeiStella** [comment]
Checked the pages, and the auto-focus works well!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/73f0bc78-e466-4128-8704-3ba254191865

**Comment by rachnapandya** [comment]
Auto-focus works well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/d8abad09-c6ed-4f3f-9f06-3c33b3ed5702

**Comment by one-community** [comment]
Thank you everyone, moving to final review. Reminder if everything is good to "approve" these rather than just comment.

**Review by juneluo — APPROVED** [review]
Autofocus works as intended in the four page mentioned in the description. good job.

**Review by EdwinLauM — APPROVED** [review]

**Pull request merged**
