### PR TITLE
Nahiyan_Dark mode on dropdown items

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Dark mode is implemented on all dropdown items on the header

## Related PRS (if any):
This frontend PR is related to the dev backend

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner
5. go to any page besides the dashboard or timelog page (They seem to be broken in development)
6. Once you can see the header, select on reports, other links and welcome dropdowns.
7. verify dark mode is working properly both in light mode and dark

## Screenshots or videos of changes:
Screenshot 2024-06-06 211226
Screenshot 2024-06-06 211243

### CODE REVIEW

**Comment by Vijeth-V** [comment]
Good job Nahiyan, this works perfectly well.

Screenshot 2024-06-08 at 2 37 22 PM

**Review by cvtqx — DISMISSED** [review]
All the drop down elements look dark in dark mode and light in light mode, just as expected. 

Video:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/25803993-6515-4d18-8ba2-961fcd13fcc6

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and the dark mode works on the Reports, Other links and User dropdowns available in the header. 
When switched back to Light mode the dropdown changes to light colour.
The Functionality for dark mode on dropdown in headers works fine!

PR2328_1
PR2328_2
PR2328_3

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected. Added screenshots for light and dark mode drop down menus.
Screenshot 2024-06-14 at 8 49 28 PM
Screenshot 2024-06-14 at 8 49 31 PM
Screenshot 2024-06-14 at 8 49 34 PM
Screenshot 2024-06-14 at 8 49 42 PM
Screenshot 2024-06-14 at 8 49 44 PM
Screenshot 2024-06-14 at 8 49 46 PM

**Review by tianyangL11 — DISMISSED** [review]
Great！  It work as expected
607abc08bd3aa19a4787968be3f2f92
09280ee6d8e5212cb1663fd57a1c1fc
a348e0b5b67ced805b4cc5fa4fa1720

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
I might come across as a stickler for this one, but i'm requesting changes for two reasons.

1. the "hello username" is in the same font color as the actual drop down selector links. It should be lighter or modified to a less intuitively interactive color as it is in light mode.
Screenshot 2024-06-15 at 4 13 28 PM


2. There's no reason to lighten the text as the hover color activates. Normally, text lightens in color when in dark mode and hovered upon. Just leave the text color as white, so the contrast ratio doesn't get worse at the very least.
Screenshot 2024-06-15 at 4 14 26 PM

**Comment by KurtisIvey** [comment]
Changes look great. If you can clear up the merge conflict please and then shoot me a slack message once it's done, so I can review it again when I get off work.

**Review by KurtisIvey — APPROVED** [review]
Everything checks out after clearing up the merge conflict. Great Job!
image
image

**Pull request merged**
