### PR TITLE
Iven add teams team code colors filters on dashboard

### PR DESCRIPTION
**Pull request by iven-yao**
# Description
image
implemented filters features on Dashboards for tasks tab, 

## Related PRS (if any):
This frontend PR is related to the [#926](https://github.com/OneCommunityGlobal/HGNRest/pull/926) backend PR.

## Main changes explained:
- Implemented filters features on Dashboards for tasks tab, visible to Manager, Mentor, Admin, and Owner roles.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner/mentor/manager user
5. go to dashboard→ Tasks, check there are three multi-select filters for Team Names, Team Codes, and Color (WeeklySummaryOptions)
6. verify filter works as expected
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
Screenshot 2024-05-08 113733
Screenshot 2024-05-08 113820
Screenshot 2024-05-08 113846
Screenshot 2024-05-08 113908

## Note:
Include the information the reviewers need to know.

1. How to set Color group?

- login as admin
- go to other user's profile -> Volunteering times -> Weekly Summary Options
- Save Changes
image

2. How to set Team Code?

 - login as admin
 - go to other user's profile -> Teams -> Team Code
 - Save Changes
image

### CODE REVIEW

**Review by aaryaneil — DISMISSED** [review]
The changes work as expected but the backend logic for filters should be AND and not OR. What I am trying to say is if we apply multiple filters then the results should be more finely grained.
Screenshot 2024-05-04 at 4 10 25 AM
Screenshot 2024-05-04 at 4 10 32 AM
Screenshot 2024-05-04 at 4 11 09 AM

**Review by MinSun0814 — DISMISSED** [review]
If you apply an additional filter to a dataset that has already been filtered, the result should be a further reduction of the data, not an increase in the number of items. The new filter should narrow down the existing filtered results rather than adding more items to the list.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/36617c6b-490d-42f7-9f87-06a70fb2fbaf

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

image

image


image

**Review by beblicarl — DISMISSED** [review]

**Review by MinSun0814 — DISMISSED** [review]
The new filter functionality works as intented. It now correctly narrows down the results upon adding additional filters. Nice work!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/b7b1f090-ea98-4ea1-b965-ea5b77d328f4

**Review by nathcarnevalli — COMMENTED** [review]
The labels cannot be seen on the dark mode. However, the filter worked as expected for every type of account. 

Screenshot 2024-05-10 235134

**Comment by iven-yao** [comment]
@nathcarnevalli Thank you for pointing that out, just fixed the style in darkmode.
Screenshot 2024-05-10 205104

**Review by hbodgal — CHANGES_REQUESTED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/7a5d7205-4e18-474c-ba42-184ba9844ebc

The filters looks fine but I get a white screen after some time. If that is a seperate issue, let me know on slack ill approve.

**Comment by iven-yao** [comment]
> HGN.APP.-.Google.Chrome.2024-05-11.10-45-38.mp4 
> The filters looks fine but I get a white screen after some time. If that is a seperate issue, let me know on slack ill approve.

My guess is you didn't use the corresponding backend for this test, please make sure you checkout https://github.com/OneCommunityGlobal/HGNRest/pull/926, build and start the server, then try again, thank you

**Review by curiousfancier — APPROVED** [review]
Works as expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/27274513/a034755d-d719-4d4b-9569-8b022fac52ca

**Comment by ZhangPeizhou** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/3422e73b-8a38-46ec-aea5-edf08d847a98

Everything works as expected, works well under dark mode as well.

**Comment by nishithaShetty** [comment]
Good work, everything works as expected, in light mode as well as dark mode.
The labels looks good in dark mode and the filter narrows down the values correctly based on team code, color and team name
PR#2244_filter
PR2244_darkMode

**Review by peter6866 — APPROVED** [review]
Changes work as expected to filter from team name/code/colors. Works fine in both light and dark mode. 
image
image
image

**Review by hbodgal — APPROVED** [review]

**Review by Kavil-Jain-514 — COMMENTED** [review]
I wonder if that's me or if it is happening with everyone. The application is crashing for this branch.
image

image

**Review by Sandhya1236 — APPROVED** [review]
I checked out the current branch, ran npm install and npm run start:local to set up the PR locally, and cleared the site data/cache. I logged in as an admin/owner/mentor/manager user and navigated to the dashboard → Tasks. I verified that the three multi-select filters for Team Names, Team Codes, and Color (WeeklySummaryOptions) functioned correctly. Additionally, I confirmed that this new feature worked as expected in dark mode. All tests were successful, confirming the proper functionality of the filters and their compatibility with dark mode.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/9d342140-966b-4443-b843-8f04bd33101a

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/0fba4738-2edb-4fa6-89f6-ac62717611f1

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
