### PR TITLE
akshit_fixed new people not showing up as resources

### PR DESCRIPTION
**Pull request by akshit0211**
# Description
Screenshot 2024-07-04 at 4 24 35 PM

[Issue Video](https://www.loom.com/share/a143ee931bcd4efe98418ddb76d7785a?sid=9f7d70d9-9aea-4c1d-973a-96b8967b7bd1)

## Related PRS (if any):
This frontend PR is related to the development backend.

## Main changes explained:
Made changes in the src/components/UserProfile/TeamsAndProjects/UserProjectsTable.jsx file.

## How to test:
1. Check into the current branch.
2. Do `npm install` and `...` to run this PR locally.
3. Clear site data/cache
4. Log in as an Owner user.
5. Go to Other Links→ User Management→ Click on any user→ Profile page→ Projects→ Assign Project.
6. Other Links→ Projects→ Project Assigned WBS→ Add Task.
7.  Verify that the person is showing up as a resource immediately without refresh.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/205c9dff-0526-4eb3-b429-fe166d256ea0

### CODE REVIEW

**Review by nyelmela — APPROVED** [review]
The PR 2418 has been tested and works perfectly. Checked into the current branch, ran npm install, cleared site data/cache, and logged in as an Owner user. Verified user management by assigning a project and confirmed that the person shows up as a resource immediately without refresh. Everything works as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/a87c68e2-4cd8-45da-bd1d-4a9df729c175

**Review by vijay10pk — APPROVED** [review]
All the requirements work as expected. Looks good to me.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/51cfbff8-5869-43f5-82ee-c9c72b6ca3bd

**Comment by IchinnorovTuguldur** [comment]
Tested the assign project feature. I was able to assign project to any member.

**Review by sahithidhulipala9 — APPROVED** [review]
Able to solve the assign project to user perfectly. Can able to see the resource name without reloading.
Screenshot (103)
Screenshot (102)

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good Work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/6c29b34d-650a-4c93-be69-1b08933b92eb

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected.

Uploading Screen Recording 2024-07-14 at 4.25.09 AM.mov…

**Review by Chetan0606 — APPROVED** [review]
Everything works as expected


https://github.com/user-attachments/assets/dd46ba60-68a3-495e-b7e1-744025b93acf

**Comment by jayyy-s** [comment]
Hi, I tested the PR and it works as stated in the instructions. No errors/issues found.

https://github.com/user-attachments/assets/3773606a-e03e-4284-9adf-9d877932d11d

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
