### PR TITLE
Shihao fix update task time button

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Fix the issue of Editing Task Details.
For more information, check the [video](https://highest-good.slack.com/files/UE2QSE3K9/F05MTQHUF5W/screen_recording_2023-08-09_at_1.16.12_pm.mov).

## Main changes explained:
- Remove unassigned function call which caused the errors
- Implement the task refreshing after update

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ Tasks→ task→ Edit
5. edit the task details and update to check whether the function worked, also check if the details are refreshed and keep up to date after that.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/dbcc8fb7-dd70-4602-99eb-21ffd64f8e36

### CODE REVIEW

**Review by iTvX — APPROVED** [review]
I have followed your instructions, and everything looks good. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/b52f348f-046b-4aae-aec0-c7dd542f564e

**Review by TheDescendant39 — APPROVED** [review]
Hi @sxiong5, I performed the test as you states and your changes work well. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/ee72b292-a879-491d-be5c-c6fab6445723

**Review by eduhorta — APPROVED** [review]
Great job!
The feature is working as intended! 👍


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/244ae4d1-226f-4086-b1ce-2b3bdaba1bef

**Review by Jiyuanxia — APPROVED** [review]
Hello, @sxiong5! I have tested your pull request, and it is working as expected. When I log in with the admin role and proceed to edit the details of a task, the functionality functions correctly, and the updated information is displayed. Great job!

Before updating:
Screenshot 2023-08-10 151249

After updating:
Screenshot 2023-08-10 151344

**Review by robertoooc — APPROVED** [review]
Hit @sxiong5, I tested your branch and it performed as expected. Tried changing many parameters and found no issues in updating the tasks.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/8cf39cad-6fb0-44ec-af0f-f09cbd7360c2

**Review by winghojackyli — APPROVED** [review]
Hi @sxiong5 , I've tested the PR and it works as intended. 
The task details can be edited and changes are reflected on dashboard. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/864fea07-0888-4245-a9bd-8532ea25bfad

**Review by yunshan111 — APPROVED** [review]
Tested the edit function, LGTM.

41d67c4c8fe6d63a7758fe90dcf2ac8
after:
3387ad89377aa86f56f79832236a3d8

**Review by ramyaram2092 — APPROVED** [review]
Works as expected. Good work 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/ffaa36a3-ab8a-40e3-8c15-031c9b81fe2e

**Comment by AnishPandita** [comment]
Hi, the PR works well. Editing task works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/094b6ae2-bbbe-4cb3-95e7-e6f6777f8544

**Review by luisarevalo21 — APPROVED** [review]
Hello @sxiong5 
I reviewed your PR and works as intended great job!
When reviewing a task, I am able to update it. Once updated the task reflects the update when I select "edit" again. 


Uploading Screen Recording 2023-08-10 at 8.19.56 PM.mov…


Screenshot 2023-08-10 at 8 20 45 PM

**Review by n0vay — APPROVED** [review]
I  was able to edit the tasks. Good Job!
image

**Review by ThapeloMasasa — APPROVED** [review]
The changes work as intended.. the task does get updated

Screenshot 2023-08-10 at 10 52 10 PM

**Comment by beblicarl** [comment]
Tested this functionality and it works as intended. Great work

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.08.11-12_30_15.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/bbf0b0cb-35ac-4208-b1e2-a3ab3e2eb494)

**Review by beblicarl — APPROVED** [review]

**Review by xaanders — CHANGES_REQUESTED** [review]
Hi @sxiong5! 
I've tested your PR and it works from the dashboard. Could save updated task info from the project page as well but had an issue doing that. 

[scrnli_8_11_2023_12-24-41 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/c8f505c2-eb10-4140-94b8-a2268cb7e31b)

**Review by yaow62023 — APPROVED** [review]
I have test your PR, the update task feature works are intended. Check the video below. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/ab31c9f4-794e-41d3-bd5b-024fb29c4103

**Review by eduvarjaor — APPROVED** [review]
Hi @sxiong5 

I tested this PR and worked perfectly. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/b788fffb-19e6-4559-8fee-67cd0b4f3bf9

**Review by jerryren527 — COMMENTED** [review]
Hi @sxiong5!

I was able to test your changes and confirm your changes work as intended when following your instructions! Editing a task from Dashboard -> Tasks -> task works, as demonstrated in the screen recording:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/2c4ed5f5-34ad-445f-8a40-dace058278f4

However, I encounter the same issue as @xaanders when attempting to edit a task from the Projects -> WBS page. An error is caught, as demonstrated in the screen recording below. After refreshing the page, the task is successfully modified with the new edits.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/be550043-4b09-4828-b3ad-80f8dce03446

Thank you for considering this issue!

**Review by veronicacheng2 — APPROVED** [review]
Hi @sxiong5, I have tested the PR according to instructions and everything works as intended


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/6e3808be-ba44-4205-af1f-4ec8d1a218fe

**Comment by Shreyj14** [comment]
Work as expected , nice job!
Screenshot 2023-08-11 at 3 56 46 PM

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works good on my device. @sxiong5 
image

**Comment by igorrochadasilva** [comment]
Hi @sxiong5 !
I hope you are well =D

Work as expected , nice job!

1109_01_before-task
 
1109_02_edit-task

1109_03_edit-after-task

1109_04_updated-task

**Comment by one-community** [comment]
This a hotfix, so I'm merging it with all these approvals. Thank you everyone!

**Comment by sxiong5** [comment]
> Hi @sxiong5! I've tested your PR and it works from the dashboard. Could save updated task info from the project page as well but had an issue doing that.
> 
>  scrnli_8_11_2023_12-24-41.PM.webm



> Hi @sxiong5!
> 
> I was able to test your changes and confirm your changes work as intended when following your instructions! Editing a task from Dashboard -> Tasks -> task works, as demonstrated in the screen recording:
> 
>  successful.editing.of.task.from.Dashboard.-.Tasks.-.task.mp4 
> However, I encounter the same issue as @xaanders when attempting to edit a task from the Projects -> WBS page. An error is caught, as demonstrated in the screen recording below. After refreshing the page, the task is successfully modified with the new edits.
> 
>  error.when.editing.task.from.Projects.-.WBS.page.mp4 
> Thank you for considering this issue!

Hey, @xaanders, @jerryren527, Thanks for letting me know! I will raise the other RP to fix this problem!

**Pull request merged**
