### PR TITLE
Vijay Anand - Unit test total org summary reducer

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description
Added unit tests for the totalOrgSummaryReducer.

## Related PRS (if any):
No related PRs.

## Main changes explained:
- Created a new test file totalOrgSummaryReducer.test.js under the tests directory.
- Covered the following scenarios:
  - Returns the initial state when no state is provided.
  - Handles FETCH_TOTAL_ORG_SUMMARY_BEGIN by setting loading to true and clearing errors.
  - Handles FETCH_TOTAL_ORG_SUMMARY_SUCCESS by updating the volunteerstats array and stopping the loading state.
  - Handles FETCH_TOTAL_ORG_SUMMARY_ERROR by setting error with the provided error message and stopping the loading state.
  - Handles FETCH_TOTAL_ORG_SUMMARY_DATA_SUCCESS by updating the volunteerOverview array and stopping the loading state.
  - Handles FETCH_TOTAL_ORG_SUMMARY_DATA_ERROR by setting fetchingError with the provided error message and stopping the loading state.

## How to test:
1. Check out the current branch.
2. Run npm install if necessary.
3. Execute npm test totalOrgSummaryReducer.test.js.
4. Verify that all test cases pass successfully without any errors.

## Screenshots or videos of changes:
image

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (263)

**Review by jinxyou — APPROVED** [review]
All test cases passed. Good job!
Screenshot 2024-12-13 212255

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected! Nice work!

**Review by anirudhsk2107 — COMMENTED** [review]
All tests have passed 

Screenshot 2024-12-14 104747

**Review by Nahiyan-16 — APPROVED** [review]
Hey Vijay,

I've reviewed the unit tests for the `totalOrgSummaryReducer`. They effectively cover the initial state and handle various actions, including `FETCH_TOTAL_ORG_SUMMARY_BEGIN`, `FETCH_TOTAL_ORG_SUMMARY_SUCCESS`, `FETCH_TOTAL_ORG_SUMMARY_ERROR`, `FETCH_TOTAL_ORG_SUMMARY_DATA_SUCCESS`, and `FETCH_TOTAL_ORG_SUMMARY_DATA_ERROR`. The tests ensure the reducer updates the state correctly for loading, success, and error scenarios.

Screenshot 2024-12-15 at 8 19 19 AM

**Review by KurtisIvey — APPROVED** [review]
Approved! Another great reducer test file from you. Thanks for the excellent work:


The tests do a great job checking that the reducer works properly for all the main actions, like starting, succeeding, or failing to fetch data, and updates the state correctly. They also make sure the reducer handles the starting state and unknown actions in a predictable way.

Screenshot 2024-12-14 at 9 04 17 PM

**Review by RashmiKY98 — APPROVED** [review]
Executed the unit test cases. Reviewed the code to ensure it covers boundary edge cases. No issues found.
image

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Review by ddshah878 — APPROVED** [review]
All test cases passed.

image

**Review by ShraddhaShahari — COMMENTED** [review]
I have tested this PR and all the test cases have passed.
Screenshot-PR2949

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
