### PR TITLE
Peterson fix when adding team to profile save changes becomes disabled for other tabs

### PR DESCRIPTION
**Pull request by peterson337**
# Description
In the user profile page and the teams tab, when the button named 'Assign Team' is pressed, a modal opens containing an input to select or create a new team, and two buttons: one to close the modal and another to add the user to a team. When the user's own account is added to a team, it causes the 'Save Changes' button to be disabled in all other tabs, even when the user makes changes to fields like first name, last name, and others. This pull request has been opened to fix the bug.

## Related PRS (if any):
None
…

## Main changes explained:
The component TeamsTab.jsx has been modified to fix the bug.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4.Log in as an administrator or owner
5. go to view profile→ teams
6. Click the button named 'Assign Team' and a modal will open.
7. Select a team to add your user.
8. Check if the button 'Save Changes' is enabled in all the tabs.

## Screenshots or videos of changes:
Before my fix
After my fix

## Note:
None

### CODE REVIEW

**Review by hbodgal — APPROVED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/43563110-ff35-4833-9bb5-a439a483fa82

Looks good. I was able to edit other sections of profile before saving changes on Teams section,

**Review by KyreneAF — COMMENTED** [review]
- Save Changes is active after making changes works as expected :)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/8b575f2b-4363-47f7-9094-60ef8d89b31c

**Review by peter6866 — APPROVED** [review]
Changes work as expected. 
image
image

**Review by cecilia-uu — APPROVED** [review]
Looks good.
截屏2024-05-28 上午7 16 52
截屏2024-05-28 上午7 19 08

**Review by Sandhya1236 — APPROVED** [review]
I have successfully tested the fix for the bug on the user profile page in the Teams tab. The issue was that when the 'Assign Team' button was pressed and the user's own account was added to a team, the 'Save Changes' button became disabled in all other tabs, even when changes were made to fields like first name, last name, and others. The main changes involved modifying the TeamsTab.jsx component to resolve this issue. After checking into the current branch, running npm install, and starting the application locally, I cleared the site data and cache. Logging in as an administrator or owner, I navigated to the user profile, went to the Teams tab, clicked the 'Assign Team' button to open the modal, and selected a team to add the user. I verified that the 'Save Changes' button remained enabled in all tabs after making changes. All tests confirmed that the bug was fixed and the functionality worked as expected.

image

image

image

**Comment by one-community** [comment]
Low risk, merging!  Thank you all!

**Review by TXMO-dev — COMMENTED** [review]
After adding user to the team, the save changes is now enabled, Approved! Great Job Peterson!!

**Pull request merged**
