### PR TITLE
Roberto - enhances save changes modal to notify request is still processing

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
When making changes to a users's profile and clicking on save changes the success modal immediately pops up even though the put request isn't fully complete processing. If you make a change to the user and click save changes, then refresh your page immediately it would lead to the frontend sending out the put request, but not completely finishing due to the page refresh which would lead to a get request while the put is still being carried out. This would lead to the get request sending old information rather than the newly updated information from the put request.

## Related PRS (if any):
Use latest backend dev branch

## Main changes explained:
- In UserProfile.jsx changed the handleSubmit props of the SaveButton component to be async.
- In SaveButton.jsx added a still waiting message and updated the handleSave function to be async and trigger a change in modal message when the request is done.
- In EditConfirmModal.jsx added a boolean disabled props to make the exit button disabled in the short period that the changes are fully saved.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to any user profile page→ edit any basic information → click on save changes
5. verify you see the still waiting message then it turns into the success message 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/708a059b-edb4-4359-90dc-ba34a817adbb

## Note
The message is just to prevent people from refreshing the page before the request is fully executed

### CODE REVIEW

**Comment by palakgosalia** [comment]
Hey, I reviewed and tested your code. It works as intended. Details in the video. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/27f6f73b-c9cc-49c3-80cd-5dc54871ad36

**Comment by ptrpengdev** [comment]
Hi @robertoooc , I tested the PR and had no issues. Great work!

image

image

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-02 at 3 00 20 PM
Good job, @robertoooc ! The function looks great!

**Review by Alforoan — DISMISSED** [review]
I changed name and title and it worked as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/20c3d868-cef7-4a83-940d-20103f019372

**Review by keyunhuangg — APPROVED** [review]
Verified that the waiting message pops up before success upon changes  on name, title, time-zone, email, and phone number. Below screenshot shows one of them.
Screenshot 2023-12-15 at 1 33 45 PM
Screenshot 2023-12-15 at 1 33 50 PM

**Review by Renanluizssx — DISMISSED** [review]
Hi @robertoooc, i tested your application and it´s correct, nice.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/90f8e1e2-c235-4d5f-98c3-d5a81408d20b

**Review by Sophie-lei — DISMISSED** [review]
Hey, I just tested this PR. The function working as expected. The timezone is mortified automatically and it can be saved. However, there is a UI problem with the telephone number box. Please view the video for more details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/43a12370-6be4-49c0-b521-81ab4042b192

**Review by 666saofeng — APPROVED** [review]
Hi, I tested with admin account and it worked as expected. Cong

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/209ff82e-19bd-4c01-b485-0cf957b8b9dc

rats!

**Review by KevHnh — COMMENTED** [review]
Hi, I tested the PR with the latest backend version but things are not working as expected. I logged in using an admin account, made an edit to my profile, and clicked save but I can only see the success message.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/37b72ffc-9077-4feb-9d67-68fe1979494d

**Comment by galgalinidhi** [comment]
Hi @robertoooc, I tested the PR and it works as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/7e58e98a-8bf8-44f9-b234-e83c892ba5a9

**Review by SRamen1999 — DISMISSED** [review]
I tested the PR and had no issues. I used an admin account and was able to edit any profile and got a success message.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/e8275b13-5a7c-4b74-bf38-b568dfef6b57

**Review by Pandani07 — DISMISSED** [review]
Tested this PR and the save changes modal works as intended! Whenever I edited the profile, I got a  success message


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/bf832b59-a447-4df6-89da-64316ee8bbdc

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and everything is working.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/3ab8ddcd-13ee-4387-b138-a46083217d72

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by navneeeth — CHANGES_REQUESTED** [review]
Hey there! Reviewed this PR and the enhancement to the Save Changes feature works great and nearly as expected!

## Testing Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/a68abfee-f245-44b3-9091-d4369d3021b4

Good switch from handling the submit with an `async` and `await`. The new `stillSavingMessage` introduced to the `modalMessage` looks great!
Great job on introducing a `disabled` flag to disable the `Close` Button's style until the changes are saved succcessfully.

## Error

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/50ef8c03-880a-4317-abcb-e03cc6c82ecb


However, when the modal encounters an error, for example when I manually tested the implementation when the server is shut down, despite showcasing the error, it shows me the modal with the 'Success' message as shown in the above video.

This needs to be worked on as it is quite critical and I'll then approve this PR. Great job, overall!

**Comment by robertoooc** [comment]
@navneeeth, 
I just added some error handling to take into account this instance. If requests fail or disconnect the modal message and title should now differ accordingly.

**Review by navneeeth — APPROVED** [review]
Hello, @robertoooc! Apologies for the delayed re-review. The new changes look great! I see the error message on error. Great job! Approving!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
