### PR TITLE
Harshida added sorting on material list 

### PR DESCRIPTION
**Pull request by harshidad**
# Description
Added the sorting option for project and name column in bmdashboard -  material list. 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to bmdashboard/materials-list
5. verify sorting apply on column name and project columns.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/7d92e139-c4fe-44e9-bfae-c61344363082

### CODE REVIEW

**Comment by Cavein254** [comment]
Hi @harshidad, tested the changes you made and the components work as expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/6ae3bbcb-4112-45c2-b196-f7952095a4b3

**Review by lichanghaogit — APPROVED** [review]
Hi @harshidad 
I tested this PR on my local environment and the sorting function works as expected, nice work!
Screenshot 2023-11-23 at 10 07 22 AM
Screenshot 2023-11-23 at 10 07 30 AM
Screenshot 2023-11-23 at 10 07 40 AM
Screenshot 2023-11-23 at 10 07 46 AM
Screenshot 2023-11-23 at 10 08 17 AM
Screenshot 2023-11-23 at 10 08 27 AM

**Review by shalabhtayal — APPROVED** [review]
code tested. It works as intended


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10181678/5fd1fb6d-424f-45f9-81fa-918dd0f4d1d3

**Review by lacnoskillz — APPROVED** [review]
Hey @harshidad 
Nice job!
I pulled your changes and tested your code and it works great!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/42f99935-6620-4d26-b417-518d8c8011e4

Note I did notice a minor issue when clearing cache and trying to go the the materiallist and no data rendering unless hard refreshed. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/80b9c2cf-1314-4e50-aca4-3a9aa7a796b4

**Review by scoopstroop92 — COMMENTED** [review]
Hello @harshidad good job on the functionality. 
I have a question with respect to the  sorting functionality .  on clicking the column names I see three states in total . Correct me if I am wrong 
1.  Ascending
2.  Descending
3.  No sorting 
Is the  "No sorting" state  needed ? 

**Testing Video** 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/b48f025f-d45e-45a7-a20a-c761fcbad33a

**Comment by harshidad** [comment]
> Hello @harshidad good job on the functionality. I have a question with respect to the sorting functionality . on clicking the column names I see three states in total . Correct me if I am wrong
> 
> 1. Ascending
> 2. Descending
> 3. No sorting
>    Is the  "No sorting" state  needed ?
> 
> **Testing Video** https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/b48f025f-d45e-45a7-a20a-c761fcbad33a

@ramyaram2092 . You are correct! Here 3 state for sorting implemented. When user click on the column then Ascending & Descending. Default sorting is also required to show the data without sort , which is default to display records pulled from API  by default.

**Comment by ramyaram2092** [comment]
> > Hello @harshidad good job on the functionality. I have a question with respect to the sorting functionality . on clicking the column names I see three states in total . Correct me if I am wrong
> > 
> > 1. Ascending
> > 2. Descending
> > 3. No sorting
> >    Is the  "No sorting" state  needed ?
> > 
> > **Testing Video** https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/b48f025f-d45e-45a7-a20a-c761fcbad33a
> 
> @ramyaram2092 . You are correct! Here 3 state for sorting implemented. When user click on the column then Ascending & Descending. Default sorting is also required to show the data without sort , which is default to display records pulled from API by default.

Got it. Approving the PR on the same note

**Review by scoopstroop92 — APPROVED** [review]

**Comment by ptrpengdev** [comment]
Hello @harshidad, I tested the sorting feature in the bmdashboard/materials-list and verified sorting applied on column name and project columns is functional. Just to confirm before approval, the ordering icons for both columns change when clicking on either one (Project Or Name). Is that the expected behavior? Thank you and great work!

image

image

**Comment by palakgosalia** [comment]
Hey, I tested your code and it works as intended. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/9cdcc4e4-f0b2-4b51-a063-8851a2e7129d

**Review by Alforoan — APPROVED** [review]
It works as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/36d05a79-6a31-437e-a5cf-a7b58822e97a

**Review by tdkent — APPROVED** [review]

**Pull request merged**
