### PR TITLE
show badges in weekly report

### PR DESCRIPTION
**Pull request by juneluo**
# Description
Jae: Make most difficult to earn badges show up by a person’s name on Reports Page
There are certain badges that are very hard to earn. When a person earns these, I’d like them to post to the right of the person’s other details on the Reports → Weekly Summaries Reports page. This is so that Management can see these badges were earned by that person and acknowledge them for it
- Make visible to anyone who has access to the page
- Make it remain on whatever weekly tab it is awarded on, just like a weekly summary stays on that tab and can be referenced up to two weeks past.
- Make it so multiple badges can be shown on this page if they happen to be earned in the same week
- Integrate this into the Other Links → Badge Management → Badge Development page. Add a column for “Reports Page Notification”. Checking a box here makes that badge one that shows up on the Weekly Summaries Reports page tab for that week when earned

## Related PRS (if any):
This frontend PR is related to the [#470 backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/470).

## Main changes explained:
- The weekly summary report page will show the badges earned within the week
- Add an attribute 'showReport' to the badges, If its value is false (the report notification of a badge is not checked), it will not show in the report.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally (after update the backend PR)
3. log as owner/admin user
4. go to the profile page of a user, assign a badge A.
5. Other Links → Badge Management → Badge Development: click the checkbox to make the badge A appears on the report page.
6. Reports → Weekly Summaries Reports --> This Week, search the user and see the badge A appears under the username.

### CODE REVIEW

**Review by Abiddy — COMMENTED** [review]
Hey I'm getitng a bunch of failed tests when I try to run this.

`Summary of all failing tests
FAIL src/components/WeeklySummariesReport/WeeklySummariesReport.test.jsx
  ● WeeklySummariesReport page › On page load › displays an error message if there is an error on data fetch

    expect(received).toBeInTheDocument()

    received value must be an HTMLElement or an SVGElement.
    Received has value: null

      25 |       //waitFor(() => screen.queryByTestId('loading') === null);
      26 |       const error = await waitFor(() => screen.queryByTestId('error'));
    > 27 |       expect(error).toBeInTheDocument();
         |                     ^
      28 |
      29 |       //expect(screen.getByTestId('error')).toBeInTheDocument();
      30 |     });

      at __EXTERNAL_MATCHER_TRAP__ (node_modules/expect/build/index.js:342:30)
      at Object.toBeInTheDocument (node_modules/expect/build/index.js:343:15)
      at Object.<anonymous> (src/components/WeeklySummariesReport/WeeklySummariesReport.test.jsx:27:21)

  ● WeeklySummariesReport page › On page load › displays an error message if there is an error on data fetch

    Network Error

      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:99:14)
      at XMLHttpRequest.invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:18:28)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:338:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:131:3)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:60:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)`

**Comment by veronicacheng2** [comment]
Hi @juneluo, I have tried testing the PR, but some error occurs when I am accessing the weekly summaries report page:

image

**Review by veronicacheng2 — DISMISSED** [review]
Hi @juneluo, I have tested the PR and everything works as intended. The badge will be shown on the weekly summaries report after I added the badges in badge development.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/a0220e75-323c-4c6a-a1af-9a9412ef8699

**Review by TheDescendant39 — DISMISSED** [review]
Hi @juneluo, I followed the test steps and the changes work as intended. Good Job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/4f0b3c73-e0de-4216-8ddd-89c7174559e6

**Review by winghojackyli — APPROVED** [review]
Hi @juneluo , I've tested the PR and it works as intended. 
But when I first visited the badge management -> badge assignment page, it seems unresponsive upon the first render. I need to refresh the page to make components responsive again. For the content of this PR, it works. 



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/5578bbfa-36d9-4dde-956d-a494ae8b5779

**Review by n0vay — DISMISSED** [review]
Tested functionality, works as intended. Good Job!
image

**Comment by n0vay** [comment]
But I am also able to assign badges as admin account.

**Review by robertoooc — DISMISSED** [review]
Hi @juneluo, I tested your branch along with the new pr in the backend and received the expected results. Nice Job.

Assigning badge:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/f54c1485-db35-4de6-ad28-663191079e37

Weekly Summary Report: 

Screenshot 2023-08-13 at 5 54 44 AM

**Review by jerryren527 — APPROVED** [review]
Hi @juneluo!

Thank you for the clear instructions for testing your code! I tested your branch and am happy to confirm that an Owner can assign badges to a user on the user's profile. An owner can also manage which badges appear in the weekly summary reports by checking or unchecking check boxes in the Badge Management Page. And the correct badges appear under a user’s name in this week’s weekly summary report:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/901549a2-6aae-47f7-af1b-b98333c586b6


Checking and unchecking badges in the Badge Management Page successfully adds and removes the badges that appear in this week’s weekly summary report:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/37aadaa4-227c-47e0-b351-8f8e492f8eee

Excellent job!

**Review by yurisokolovicz — COMMENTED** [review]
Dear @juneluo 

I followed all the steps, ensuring the correct branches in both the front-end and back-end, and running ''npm i'', also including building the app on the front-end using ''npm run build'' and ''serve -s build''. However, the page crashed on the weeklysummariesreport page regarding a file that you made modifications (FormattedReport.jsx). I've attached the video, along with the error message from the console. The marker to display the badge is also not being filled. Please check the videos below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/ba859e6d-15ef-4769-b059-561ee165ed5a


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/09a74d10-056d-437e-947e-56c25c9aa540

**Comment by Lin1404** [comment]
> Dear @juneluo
> 
> I followed all the steps, ensuring the correct branches in both the front-end and back-end, and running ''npm i'', also including building the app on the front-end using ''npm run build'' and ''serve -s build''. However, the page crashed on the weeklysummariesreport page regarding a file that you made modifications (FormattedReport.jsx). I've attached the video, along with the error message from the console. The marker to display the badge is also not being filled. Please check the videos below:
> 
>  simplescreenrecorder-2023-08-14_11.07.07.mp4 
>  simplescreenrecorder-2023-08-14_11.27.39.mp4

I met the same problem with the checkbox in Badge Development, also the page crashed on Weekly Summaries Reports page. Login as owner user.

image

**Comment by Jiyuanxia** [comment]
Hello @juneluo, I've thoroughly reviewed your pull request and conducted testing on it. However, it appears that there might be an issue present. Although I was able to successfully add a badge to an individual and access the badge management page to select the checkbox, I encountered a problem afterward. While an alert indicated a successful badge update, the checkbox itself does not remain selected. Additionally, attempting to access the weekly summaries report page resulted in a crash.

Successfully adding a badge
Screenshot 2023-08-14 171531

Alert indicating a successful badge update
Screenshot 2023-08-14 171549

Error message and the checkbox remaining unselected
Screenshot 2023-08-14 171754

Error message and the blank weekly summaries report page
Screenshot 2023-08-14 171703

**Comment by juneluo** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/9314962/6260b263-b35c-48ec-a880-897ef3598d4e

Hi @Jiyuanxia @Lin1404 @yurisokolovicz  thank you for the review! Unfortunately I cannot reproduce the problem you mentioned. The video above shows how it works when I test them locally.

My guess is that the back end update is not running properly in your test. For the error `TypeError: Cannot read properties of undefined (reading 'length')`, `summary.badgeCollection` will not be undefined since the update made in `reporthelper.js` guarantees it will be an empty array if no data selected. Also the checkbox problem requires to save boolean value introduced in the update. The warning `Uncaught SyntaxError SyntaxError: Unexpected token '<'` is caused by a merged branch two weeks ago and not related to this one.
Here is the script I used when test locally:
(In the back end repository)$`npm run build $npm start`
(In the front end repository)$`npm run start:local`

Please let me know how you test if it still doesn't work so that I can locate the problem.

**Comment by juneluo** [comment]
> Hi @juneluo , I've tested the PR and it works as intended. But when I first visited the badge management -> badge assignment page, it seems unresponsive upon the first render. I need to refresh the page to make components responsive again. For the content of this PR, it works.
> 
>  HGN.APP.-.Google.Chrome.2023-08-12.19-03-58.mp4

Thanks for recording this bug but it didn't occur in my test. I checked the code and for now I think it is not caused by the update in this branch. However, I will keep an eye on it. 
Please feel free to register it to the bug doc if it happens again or someone else also find the same problem.

**Comment by Jiyuanxia** [comment]
Hello @juneluo, I apologize for the previous misunderstanding I had. I've retested both the backend and frontend components using the method you provided, and I'm pleased to report that this pull request is now functioning as intended. Well done on addressing the issues.

**Comment by one-community** [comment]
Thank you everyone, moving this to final review!

**Review by cvtqx — DISMISSED** [review]
I've tested this PR and the functionality works as described. The assigned badge appears under the username in Weekly Summaries Reports --> This Week:

Screen Shot 2023-08-16 at 11 45 23 AM

If I uncheck a badge in Other Links → Badge Management → Badge Development, the badge is not visible in this week report:

Screen Shot 2023-08-16 at 11 47 03 AM

Great job!

**Comment by Lin1404** [comment]
> 

Thank you @juneluo , the problem has been solved.

**Review by Lin1404 — DISMISSED** [review]

**Review by yunshan111 — DISMISSED** [review]
LGTM, I've reviewed your pull request and conducted some testing. One issue I encountered is that the weekly summary page consistently exhibits slow loading times. Unfortunately, I'm uncertain about the underlying cause of this delay. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/2beb72b1-49b6-4074-a7fe-43a5589f1e8d

**Review by liaoyufu-leo — DISMISSED** [review]
hi ,this change work well on my device！
image

**Comment by juneluo** [comment]
Conflicts fixed but this branch shall be merged after the fix of the current Dev branch.

**Comment by juneluo** [comment]
Update:
1. place all the badges to the top right of the summary card so they don’t add to the vertical space needs.
2. remove the badge titles since the badges being on this page are just for admins to see and acknowledge people.
3. Show the complete badge image instead of cropping them with a circle.

**Comment by wantingxu7** [comment]
Hi, I've tested the PR and it looks good to me. I assigned a badge to volunteer and it shows up accordingly.

截屏2023-09-19 下午3 01 31
截屏2023-09-19 下午3 04 05

**Pull request merged**
