### PR TITLE
Yongjian - Create button to save visibility edits for manager

### PR DESCRIPTION
**Pull request by ypan710**
# Description
Screen Shot 2023-04-20 at 4 35 02 PM

## Mainly changes explained:
Under manager role, created "Save Changes" button to save the changes of visible/invisible toggle button.

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. login as manager role, under "Welcome, XXX" -> View Profile -> Teams, inspect presence of "Save Changes" button and toggle "visible/invisible" and click on "Save Changes" button to verify ability to save the changes.

## Screenshots
Screen Shot 2023-04-20 at 4 29 55 PM

Screen Shot 2023-04-20 at 4 30 48 PM
Screen Shot 2023-04-20 at 4.30.05 PM

Screen Shot 2023-04-20 at 4 30 05 PM

Screen Shot 2023-04-20 at 4 30 32 PM

### CODE REVIEW

**Review by johny4437 — APPROVED** [review]

**Comment by johny4437** [comment]
Working as intended! Greate Job.

**Review by abdel-lall — COMMENTED** [review]
The Changes work fine. One small issue that I've noticed is that the "Basic Information" tab is now have two "Save Changes" buttons.

PR785(1)

**Comment by one-community** [comment]
That's new... please remove that extra save button and make sure the remaining one works as it should.

**Review by AuroraLovesWhales — COMMENTED** [review]
Hi yongjian, I have tested your PR. Other than the extra "save changes" button as mentioned above, it works as expected. I logged in as a manager, set teams to invisible, and saved the changes. After I logged out and logged back in again, the visibility was still set as invisible. 
https://user-images.githubusercontent.com/44281916/233752948-e17ff7d2-f593-4aec-9448-e026ed7939dc.mov

**Comment by AnishPandita** [comment]
Hi @ypan710 I tested your PR and it sees to be working as intended. 
Screenshot 2023-04-21 at 8 34 23 PM
Screenshot 2023-04-21 at 8 34 38 PM

**Comment by Vishvesh-Sheoran** [comment]
Upon approval of these changed by 'johny4437' github shows that the branch has a conflict:

https://ibb.co/DQz9jv0

Upon opening the src of UserProfile I saw the overlapping code, and thought that we should consider evaluating whether the 'Refresh' button is necessary for the specific use case of the code. If it's not necessary, removing it can simplify the code and reduce potential confusion for future developers who may work on the code. Here:

<Button outline onClick={loadUserProfile}>
  Refresh
</Button>

<SaveButton
  className="mr-1 btn-bottom"
  handleSubmit={handleSubmit}
  disabled={!isFormValid() || areProfileTasksTeamsProjectsEqual()}
  userProfile={userProfile}
/>

function isFormValid() {
  return formValid.firstName && formValid.lastName && formValid.email;
}

function areProfileTasksTeamsProjectsEqual() {
  return isProfileEqual && isTasksEqual && isTeamsEqual && isProjectsEqual;
}

**Comment by alexander-huerta** [comment]
Hi Yongian, Nice job on the functionality! 

After following your testing instructions, I can verify that "Save Changes" button now renders and working as intended. It allows me to save the state of the visible/invisible toggle. The state remained after login in and out.

However, I will note the same bug mentioned above- there are now  two "Save Changes" buttons in the "Basic Information" tab.

**Comment by one-community** [comment]
Why is there this PR about this too: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/792

**Comment by ypan710** [comment]
Close due to similar PR (#792) tackling the same task and avoiding confusion.

**Pull request closed without merging**
