### PR TITLE
Jatin make columns editable by owner

### PR DESCRIPTION
**Pull request by JatinAgrawal94**
# Description
Screenshot 2024-07-19 at 7 15 15 PM

## Related PRS (if any):
This frontend PR is related to the [#1085](https://github.com/OneCommunityGlobal/HGNRest/pull/1085) backend PR.

## Main changes explained:
- Edit icon added to allow owner user to edit information from user management page itself.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links -> User Management
6. Check if the edit icon is visible beside the headers in the table.
7. Clicking the edit icon the respective column fields turn into input tags, allowing the user to edit user data.
8. Make Changes to the user data and check if the data is updated or not.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/588efe23-0f5f-47aa-b86b-67f97c37059c

### CODE REVIEW

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.




Thank You

**Review by Jingyii800 — CHANGES_REQUESTED** [review]
I tested the function, and it mostly worked well. After saving changes, the updated field initially appears correctly, but the changes disappear after refreshing the page. It often requires refreshing the page several times or clicking the edit icon again to display the changes properly. Please check my video for more details.

**Comment by JatinAgrawal94** [comment]
> I tested the function, and it mostly worked well. After saving changes, the updated field initially appears correctly, but the changes disappear after refreshing the page. It often requires refreshing the page several times or clicking the edit icon again to display the changes properly. Please check my video for more details.
> 
>  8.29.mp4

**Comment by JatinAgrawal94** [comment]
> I tested the function, and it mostly worked well. After saving changes, the updated field initially appears correctly, but the changes disappear after refreshing the page. It often requires refreshing the page several times or clicking the edit icon again to display the changes properly. Please check my video for more details.
> 
>  8.29.mp4

It is because everytime we make an update the page reloads and fetches all the user's information and stores it in localstorage. Due to large volume of user accounts, this process take some time, which is why it takes a couple seconds for the update to actually show on the frontend. 
But I am still figuring out how to resolve this problem.

**Review by Pranay-ai — APPROVED** [review]
Hey @JatinAgrawal94 
The PR is Working as expected Please find the Screenshot for reference 
image

**Review by SMitta11 — APPROVED** [review]
I followed the instructions given in PR and I clicked on edit beside header and it gives me option to edit for any user but it is taking forever to change that, maybe it is due to VPN I am using as US data center has issues right now, not sure.
But it shows functionality is as expected so approving the PR.
Screen Shot 2024-08-31 at 7 13 57 PM

**Review by sri0606 — CHANGES_REQUESTED** [review]
Hey @JatinAgrawal94 , I have reviewed the changes and some features are not working as expected.
* Editing the columns doesn't always work. When I refresh I don't see the updates.
* The data is being updated for each character entered into input field. This is not user friendly as screen is being flooded with toaster messages. Maybe adding a save button could be a better option.


https://github.com/user-attachments/assets/862cfa73-bd4d-46e2-9178-eeb6d7fe2e08

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are not visible. Unable to see the edit icons next to column headers. Below are the screenshots for reference:
Capture2620

**Review by Jingyii800 — DISMISSED** [review]
I have tested this funftion again and this time it worked as expected, no latency in the frontend, the changes display immediately. Great job!

https://github.com/user-attachments/assets/2d42c50a-8d57-4291-aaa6-d0745a137884

**Review by sri0606 — CHANGES_REQUESTED** [review]
@JatinAgrawal94 , I tried to test the recent updates you made and everything seems to work as expected. But the issue about data being updated for each add/delete of a character still persists. 

https://github.com/user-attachments/assets/71b4f662-7589-408d-b6ee-186c019e66c6

**Review by Saniya98 — APPROVED** [review]
Changes are working as expected
image

**Review by sri0606 — CHANGES_REQUESTED** [review]
Hey @JatinAgrawal94 , The toaster messages doesn't appear for each character update. But now the data is not being updated and whenever I click save, i get an error.

I have pulled latest commits and did `npm install` too.


https://github.com/user-attachments/assets/040e89db-6f33-4ddc-868c-f61541a545fa

**Review by sri0606 — APPROVED** [review]

**Comment by navya9989** [comment]
Hi, I reviewed this PR but i'm unable to edit the hours and the edit option is not available. 
PR 2620

**Comment by JatinAgrawal94** [comment]
> Hi, I reviewed this PR but i'm unable to edit the hours and the edit option is not available. PR 2620

Please login with an owner account and try again.

**Pull request merged**
