### PR TITLE
Yubo fix no popup warning for empty media url

### PR DESCRIPTION
**Pull request by GKD890**
# Description
A small fix in `EditLinkModal` 

## Related PRS (if any):
It's a small fix in PR #1236 

## Main changes explained:
- Add a condition to determine if the input of **Media Folder Link** was empty
- Add an update to the `ref` that stores the original **Media Folder Link** after link submitted. Now, it always compare the link you are typing with the updated link with no need to refresh the page. (Thanks to @GaryB93 pointed out in PR #1236 ) 

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user -> go to other user's profile page -> click link **Edit** under picture.
### For 'no popup warning'
- Try to change the `Media Folder` link and see the popup won't show up if current user has empty **Media Folder Link** (you can delete to empty to test)
### For 'comparing updated link'
- Update one user's **Media Folder Link**  (this case, you should find a user that has **Media Folder Link**, you can also add one before testing). After you click 'update' button, it should close automatically.
- click the `Edit` button again and make some changes to the input of ** Media Folder Link** and see the warning is indicating the updated link you made. Because before the changes, the warning will show the link before you updated.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/24707ab9-a111-4183-8460-439f51494020

### CODE REVIEW

**Review by yangfan2001 — APPROVED** [review]
Hi I have tested your PR and it work as expected. Great Job!
When empty, pop up don't show up.
image
After the update, when I try to change the URL, a warning will pop up, and I can see the warning message.
image

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions! Everything works as expected. I tested editing several times and the pop up message is working correctly. Good job! You may check the testing details in the below recording.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/75cfa7fd-6ce0-44aa-b069-659d67d70424

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and works as intended. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/e83f4c9a-5449-4aeb-8036-9bf2a69d1d72

**Comment by emunkh404** [comment]
Hello, I tested your PR and works as intended. Great work!
image

image

image

**Review by Sssky-18 — APPROVED** [review]
Hi @GKD890, I have tested your PR, and the popup worked as expected. Firstly, if this account has the media link, each time I change it the popup will display. Secondly, if it is empty, the popup will not show until I save one to the account. Lastly, after the account has the link, the popup starts to work normally. Therefore, I think your work is perfect. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/ff0f84e9-b02f-47f6-85be-5a3e1bda3ad2

**Comment by Vishala09** [comment]
Working as expected. 

- When the media link is initially empty and if we try to edit , it doesn't display the pop up
- When the media link is empty , media link navigator is also not visible
- When the media link is edited and saved for the first time , it saves properly. 
- Click of update button automatically closes the pop up
- Now media link navigator is visible
- If we edit it for next time , now the warning shows as we make the change immediately
- The warning also is displayed properly with the previous link
image

Please find my video testing here!
[Untitled_ Oct 17,2023 2_53 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/021b39f3-ab3f-4e62-94c1-aa67145fc810)

**Review by Vishala09 — APPROVED** [review]

**Review by lacnoskillz — APPROVED** [review]
Hello @GKD890 
I pulled your changes and it appears to work as expected!
Nice work!

[Untitled_ Oct 17, 2023 7_37 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/840e61e4-7006-457b-9be3-74ef9b9c6539)

**Review by navneeeth — APPROVED** [review]
Hello, @GKD890! I tested your changes and they LGTM! Good implementation!

Logged in as admin user and navigated to an user's profile page and clicked Edit under their picture. Experimented with the Media Folder link when there is a link and the popup warning appears as expected. And if there is an empty link, there is no popup warning.

## Testing video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/182400da-d53a-427a-8afa-7a0cd76a5c11

**Review by StrawberryCalpico — APPROVED** [review]
I tested your PR. The PR works as expected. The warning shows up when I make changes. If empty, no warning. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/b1793f25-cdbd-4f74-8afc-851a1121cbde

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
