### PR TITLE
Changhao - added new unit tests for usertablesearchheader

### PR DESCRIPTION
**Pull request by lichanghaogit**
# Description
added more unti tests for usertablesearchheader.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm test UserTableSearchHeader.test.js` to run this PR locally
3. verify all 13 unit tests are passed

## Screenshot:
Screenshot 2024-01-16 at 11 43 10 PM

### CODE REVIEW

**Review by KevHnh — APPROVED** [review]
All test cases passed

image

**Review by pshereen — APPROVED** [review]
Tested the PR.
All the tests are passed.

Screenshot 2024-01-17 194010

**Review by bajajtushar094 — APPROVED** [review]
@Changhao3220K All test cases passed. Thanks
Screenshot 2024-01-18 at 23 11 32

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by DragonSlayer2401** [comment]
I tested the PR and all tests passed as expected. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/7fe1f49d-0794-4628-b1d7-d7d500e75cbb

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 21 - PR2

**Review by bienzguoa — APPROVED** [review]
Good job! very conprehensive test and all test passed.
Screenshot 2024-01-21 at 12 29 39 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by Lin1404** [comment]
@Changhao3220K All test cases passed. 

image

**Review by Lin1404 — APPROVED** [review]

**Comment by xmyoot** [comment]
Awesome work, all tests cases passed 
PR#1843

**Review by X1aoZhang99 — APPROVED** [review]
Hi Changhao, 

All tests passed, nice work! 

Screenshot 2024-01-28 at 19 20 26

**Review by peterson337 — APPROVED** [review]
I tested it, and everything worked as expected.

a

**Review by Renanluizssx — APPROVED** [review]
Hi @Changhao3220K, i tested your unit test and it's correct:
Screenshot 2024-02-01 080427

**Review by 666saofeng — APPROVED** [review]
All tests passed. Congrats!
image

**Review by Pandani07 — APPROVED** [review]
All test cases have passed, checked the app for additional bugs and defects, all working as expected

Screenshot 2024-02-05 at 11 17 25 AM

**Review by scoopstroop92 — APPROVED** [review]
Looks good. Good job on the test cases

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and all tests passed.

Purple-and-Pink-Modern-Work-From-Home-Simple-Presentation-2

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
