### PR TITLE
fix volunteering times

### PR DESCRIPTION
**Pull request by KaixiangGU**
Thi PR fix volunteering times comprehensively.
google docs

Fixed:
1. Page break when manually edit hours on user profile page.
2. Hours are logged correctly when you select a task in time entry.
3. Hours will be updated correctly when you check/uncheck tangible or ingngible in time entry.
4. Hours will be updated correctly when you select a different project/task.

👀 How to test this PR:
You can try the following below actions to see if the hours on user profile page is updated correctly:
1. Submit a new time entry.
2. Manually edit hours and save changes on user profile page.
3. Edit an old time entry and turn a intangible to tangible and vice versa.
4. Edit an old time entry and select a different project/task.
5. Edit an old time entry and change hours.

### CODE REVIEW

**Review by ShaunSully88 — APPROVED** [review]

**Comment by EvianTan** [comment]
Hi @KaixiangGU , you did a great job on making this frontend tangible hours logic working! I tested with edit the classification tangible hours on user profile pages, they worked well!

There are a few things I need to confirm with you:
1. When I edit the tangible hours on user profile page and click the "save" button, it gave the errors on below image. We should get rid of those warnings. Did you see that before?
image
2. Log tangible time on a specific task won't update the classification tangible hours of this task on user profile page. (Example: if I log 2 min tangible time on task which classification is food, so my profile page tangible food hours will increase by 0.03 hours) So I cannot verified your above fixed 2,3,4. Please correct me if I'm wrong.

**Comment by KaixiangGU** [comment]
Hi @EvianTan 

1. I didn't see that error when I was working on this PR, it was probably caused by another PR.

2. I will double-check this, thank you!

**Comment by EvianTan** [comment]
Hi @KaixiangGU ,

Thanks for the replay.
1. Yes, we've confirmed this bug is not caused by your PR/changes, already filed it as urgent bug 10. Don' worry about this one.
2. Yes this PR is supposed to handle situation including log tangible time to tasks and also projects. If the implementation would take you much more time, consider split this bug/feature into two parts:
a. make the classification hours can be edited and updated correctly on user profile (which has been verified in this PR)
b. make log/edit/delete tangible time entries also affects correctly the classification tangible hours on user's profile (which can be filed and implemented later)

How does the above sound like to you?

**Comment by one-community** [comment]
Excellent job on this!

1. Working now except for hours logged to Tasks. If I create a new Task (Admin Login → Other Links → Projects → Click WBS Icon by project chosen → Choose WBS → Add Task) and then log time to that task, the logged time shows up under “Unassigned Category Hours”. To further test this, I then manually switched the category for that new task, saved it, and logged time again to the new task… the new time still showed up under “Unassigned Category Hours” instead of the proper category.

2. Please also make “intangible hours” editable just like the other ones.

**Comment by KaixiangGU** [comment]
@one-community Hi Jae, could you please give me the task name that you tested? I'm trying to debug this with the same task that you and Yiyun used.

**Comment by one-community** [comment]
See "Task Wont Add Hours FOOD" under my Jae Sabol account. 

If you create a new Task (Admin Login → Other Links → Projects → Click WBS Icon by project chosen (note: you be a part of the Project you are adding a task to) → Choose WBS → Add Task) and then log time to that task, the logged time shows up under “Unassigned Category Hours”. 

NEW/I SEE WHY THIS IS CONFUSING: I started with the task called "Task Wont Add Hours" and got the expected result. Then, to further test this, I manually switched the category THAT WAS DEFAULT "HG FOOD" TO "HG HOUSING", saved it (took multiple tries to get the save to stick), and logged time again to the new task… and it worked as it should to log time to housing! 

Tried repeatedly to change the category to test something other than Housing and it wouldn't save... so I created an additional task called "Task Wont Add Hours ENERGY" (TOOK FOUR TIMES TO GET THIS TO SAVE from the default "food" to energy) and added time again and it worked again... 

Then to be sure I could get the original result and create a task for you to debug, I created "Task Wont Add Hours FOOD", logged hours, and they showed up under “Unassigned Category Hours” instead of the proper category.

**Comment by KaixiangGU** [comment]
Thanks for your information! Going to take a closer look at this.

**Comment by KaixiangGU** [comment]
@EvianTan @one-community 
Hi Yiyun and Jae, I used the same tasks that you tested to debug tasks hours not logged, here is what I found.

1. The tasks that you used are **"database hoursLogged field test"** and **"Task Wont Add Hours FOOD"**. I console.log the information about these tasks when I logged hours to it. It showed that the **classification** for both tasks is actually an empty string, so it will logged to **"unassigned"** category.



2. And then I manually changed the classification of both tasks and it correctly logged hours this time.
task_after_change_classification
edit task wont add hours Food to education

**I think the hour logged to the task is actually work already (maybe?)** I created tasks for all categories and it works well on my end. I think the reason why it's logged to **unassigned** category is that **classification** is not assigned correctly when creating a new task. 

If you check create new task modal, there's a text field for classification, you have to manually type **classification name** in the text field, otherwise, an empty string will be assigned to the classification which will cause tasks logged to **unassigned** category. 

On the other hand, if you check the edit task modal, it's a dropdown menu for classification instead of the text field. It will make you think that my task classification is "Food" which is the first value in the dropdown menu, but actually it's just an empty string in the database.

Please let me know if anything wrong! Thank you!

**Comment by one-community** [comment]
Yes, this makes sense and I think you are right! Your code works, but the issue is new tasks being created are choosing "Food" by default and not recording this or edits to this in the database. I'll add a link to this PR by that bug and we can consider this one done.

**Comment by one-community** [comment]
Whoops: Still need this though: "Please also make “intangible hours” editable just like the other ones. "

**Comment by KaixiangGU** [comment]
Yes, I think the solution for this issue is to make a dropdown menu for classification field in **create new task popup**. If the user doesn't make any changes on the classification, it will use "FOOD" as default category, so that a default value will assign to new task but not an empty string!

Sure, I will continue to work on intangible hours.

**Comment by one-community** [comment]
Sounds good, thank you. Adding some of your notes here to the new bug too.

**Pull request merged**
