### PR TITLE
NEEDS NEW DEVELOPER - Create the ability to approve suggestions

### PR DESCRIPTION
**Pull request by tingedudu8**
# Description
Fix MANAGEMENT DASHBOARD COMPONENT
(PRIORITY HIGH) Yiyun: Create the ability for admin/owner users to approve and apply “suggested” changes on a task.

## Mainly changes explained:
Add some functions to make the Suggest button work. Also, the suggested changes list should be removed from the dashboard.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as mentor/manager role
4. go to dashboard→ Tasks→ click on the tasks near the red bell→ click on "Suggest" and make some changes.
5. log out the current user
6. log in as admin/owner role
7. click on the red circle(notification) near "Dashboard"
Screen Shot 2023-03-18 at 3 32 43 PM
→ click on the task suggestion you made using the former role→ Approve→ Go back to the former user and click on the red bells to see whether the changes have been made already.

## Note:
There are many log in log out in this PR, try to use different browsers for different role, and refresh the page often.
If you do not have team member tasks, login in as admin, go to dashboard→ Other Links→ Teams→ create your own team to test.

### CODE REVIEW

**Comment by Jorge-Nerd** [comment]
Hello @tingedudu8  I tried to test the PR, but it was not clear to me how to do the test

**Comment by one-community** [comment]
You have to create a Mentor or Manager role account to test this.

**Comment by one-community** [comment]
See the detailed "how to test" instructions and follow them exactly.

**Comment by calexander3108** [comment]
Hi @tingedudu8, I am trying to test this PR but I can't seem to find the "Suggest" button or modal, am I missing something?

https://user-images.githubusercontent.com/127106980/226151777-572ac472-9583-459d-8718-15662e7b617a.mp4

**Comment by NyahJ** [comment]
Hi @tingedudu8,

I followed your test steps and tried to test your changes. Unfortunately, I cannot find the "Suggest" button, could you pls upload a guidance video for us to refer to?

截屏2023-03-18 下午9 58 09

**Comment by tingedudu8** [comment]
I will take a look at the problem @NyahJ pointed out, please do not review before the problem is resolved.

**Review by 20chen-7 — CHANGES_REQUESTED** [review]
The suggest button I could see and try to edit it, but the changes would not be saved.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/921c010f-0ce5-4637-9899-20a69bd702af

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/36e803fa-38eb-407d-88cb-a50473f9e62b

**Pull request closed without merging**
