### PR TITLE
Shihao - FeaturedBadges Unit Test

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Unite test for `FeaturedBadges.jsx`

## Main changes explained:
- Add the unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test FeaturedBadges.test.js` to run the test
4. Verify that all 2 tests have passed

## Screenshots or videos of changes:
Screenshot 2023-12-07 at 15 28 30

### CODE REVIEW

**Review by sucheta90 — APPROVED** [review]
@sxiong5 Ran test in local branch and the test passed.
PR1650_test_passed

**Review by pika-chu11 — APPROVED** [review]
Hi @sxiong5 , the test passed on the end! Great Job!
PR 1650

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Comment by DragonSlayer2401** [comment]
I ran the test and all 3 passed as expected. Please watch the overview video below:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/88cb6d17-8baa-4756-b54f-55681ba6d512

**Review by vikrambadhan — APPROVED** [review]
Hi, Great job! All the test cases passed!

Week 15 - PR 2(#1650)

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 
Screenshot 2023-12-09 at 12 19 22 AM

**Review by Hemsharavanan — APPROVED** [review]
- Your tests effectively validate the rendering of the FeaturedBadges component, ensuring that the component renders correctly with the provided badge data.
- The test for sorting badge images verifies the correct sorting based on the badge count. 
- Overall, the tests effectively validate the rendering and sorting behavior of the FeaturedBadges component.
- Nice work!
PR #1650 Shihao - FeaturedBadges Unit Test

**Review by ZichanYang324 — APPROVED** [review]
Hi @sxiong5, I have run the test and all the test cases passed, well done!
Screenshot 2023-12-09 at 16 59 24

**Review by cvtqx — APPROVED** [review]
Tests pass, great job!
Screen Shot 2023-12-15 at 12 30 14 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
