### PR TITLE
Ivy-permission-btn-functionality-update

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
Screenshot 2024-07-09 at 3 50 23 PM

Or Implements # (WBS) 
…

## Main changes explained:
- Update PermissionListItem.jsx
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links→ Permission management → Add New Role
6. verify function “A” (feel free to include screenshot here)
7. verify this new feature
## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/24d894a6-0e20-4133-8e6a-4abc06d35e3e

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected. the add button does get disabled if some permission is already added under it and the add button next to Reports, etc works as expected.
Screenshot (48)
Screenshot (49)
Screenshot (50)
Screenshot (51)

**Review by vijay10pk — CHANGES_REQUESTED** [review]
Please review the logic for the "delete all" function. When I try to add "all" for two different categories and then attempt to delete "all" for one of the categories, it ends up deleting items from the category I didn't intend to delete. Please refer the screen recording for better understanding.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/197f5d30-6a1b-43e7-8506-2385b6aa76f2

**Review by kdaga81 — DISMISSED** [review]
image
image
image

The functionality is working as expected!

**Review by kdaga81 — COMMENTED** [review]
image
We can change the color gradient in dark mode as it's very hard to read.

**Comment by 20chen-7** [comment]
> Please review the logic for the "delete all" function. When I try to add "all" for two different categories and then attempt to delete "all" for one of the categories, it ends up deleting items from the category I didn't intend to delete. Please refer the screen recording for better understanding.
> 
>  Screen.Recording.2024-07-09.at.7.27.28.PM.mov

Fixed that, plz check it agin.

**Review by vijay10pk — APPROVED** [review]
Requested changes are fixed and all the changes are working as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/086929ca-7077-4ac1-b6be-6d195663a80a

**Review by nyelmela — APPROVED** [review]
I have tested the PR 2444 and verified that the functionality works as expected. After checking into the current branch, running `npm install`, and executing the PR locally, I cleared the site data and cache, logged in as an admin user, and navigated to `Dashboard` → `Other Links` → `Permission Management` → `Add New Role`. The "Add" button correctly disables if a permission is already added, and the "Add" buttons next to Reports and other sections function as intended. Please see the attached screenshot for verification.

image

**Review by sahithidhulipala9 — APPROVED** [review]
PR Working as expected!
PR 2444 1
PR 2444

**Comment by nikethaanand** [comment]
The add and delete permissions functionality works correctly. On clicking the add and delete buttons correct selections are made. The color of the buttons is also correctly assigned.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47215795/0804f80a-eb44-4287-9c43-bd042cd14a7d

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good Work!

https://github.com/user-attachments/assets/f482dfe6-7b00-47dd-a46e-b712a3030265

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected.

https://github.com/user-attachments/assets/e5baae05-5de9-4bb5-9a32-58bbd594ee75

**Review by jinxyou — APPROVED** [review]
The toggle button for all functionality works fine. Great work!

https://github.com/user-attachments/assets/cce7f56e-5803-4b49-a59e-affd6c618e22

**Review by Rishitha1309 — APPROVED** [review]
everything worked as expected.!

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
Tested this PR as mentioned in the instructions. If I select a category and add all permissions, and later try to delete all those permissions with just one click, it doesn't work for all categories. The video below has all the details.

https://github.com/user-attachments/assets/fa243209-f43a-4563-b21a-077ce2cc63d3

**Comment by 20chen-7** [comment]
> Tested this PR as mentioned in the instructions. If I select a category and add all permissions, and later try to delete all those permissions with just one click, it doesn't work for all categories. The video below has all the details.
> 
>  Screen.Recording.2024-07-13.182238.mp4

fixed, please check again.

**Review by Pranay-ai — DISMISSED** [review]
The PR is working as expected 

https://github.com/user-attachments/assets/ea294c33-ed42-42da-a803-0fd609d74cce
Thank You

**Review by nathanah — CHANGES_REQUESTED** [review]
This whole thing can be accomplished by adding `permission` as an input parameter for `togglePermission` on line 39. This is how it initially was, but was broken by linting. Can rename `permission` to something like `permissionKey` to remove the linting error.

**Comment by 20chen-7** [comment]
> This whole thing can be accomplished by adding `permission` as an input parameter for `togglePermission` on line 39. This is how it initially was, but was broken by a [linting fix](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/d1c7f88ed79cfdce8554102250b9f13a5a7ec88b). You can rename `permission` to something like `permissionKey` to remove the linting error.

Well, I will rename this one, but I did pass the lint style check before this pr.

**Comment by nathanah** [comment]
> > This whole thing can be accomplished by adding `permission` as an input parameter for `togglePermission` on line 39. This is how it initially was, but was broken by a [linting fix](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/d1c7f88ed79cfdce8554102250b9f13a5a7ec88b). You can rename `permission` to something like `permissionKey` to remove the linting error.
> 
> Well, I did pass the lint style check and rename will change a lot, changing the whole jsx not just this single function. Plz check all occurence of 'permission'([458b9df](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/458b9df082dd067668e653cc1e055fccdbcda51e))

I made a PR to show what I mean. This seems like a simpler way to fix it.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2512/files

**Comment by 20chen-7** [comment]
> > > This whole thing can be accomplished by adding `permission` as an input parameter for `togglePermission` on line 39. This is how it initially was, but was broken by a [linting fix](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/d1c7f88ed79cfdce8554102250b9f13a5a7ec88b). You can rename `permission` to something like `permissionKey` to remove the linting error.
> > 
> > 
> > Well, I did pass the lint style check and rename will change a lot, changing the whole jsx not just this single function. Plz check all occurence of 'permission'([458b9df](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/458b9df082dd067668e653cc1e055fccdbcda51e))
> 
> I made a PR to show what I mean. This seems like a simpler way to fix it. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2512/files

**Comment by 20chen-7** [comment]
> > > > This whole thing can be accomplished by adding `permission` as an input parameter for `togglePermission` on line 39. This is how it initially was, but was broken by a [linting fix](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/d1c7f88ed79cfdce8554102250b9f13a5a7ec88b). You can rename `permission` to something like `permissionKey` to remove the linting error.
> > > 
> > > 
> > > Well, I did pass the lint style check and rename will change a lot, changing the whole jsx not just this single function. Plz check all occurence of 'permission'([458b9df](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/458b9df082dd067668e653cc1e055fccdbcda51e))
> > 
> > 
> > I made a PR to show what I mean. This seems like a simpler way to fix it. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2512/files

You can pull another PR and report the permissionKey lint error to the bug doc, that is totally fine. I do not want to change the original dev branch a lot. plz do not add duplicate label here, as it is not a duplicate one.

**Comment by 20chen-7** [comment]
You can pull another PR and report the permissionKey lint error to the bug doc, that is totally fine. I do not want to change the original dev branch a lot. plz do not add duplicate label here, as it is not a duplicate one.

**Comment by 20chen-7** [comment]
> > > This whole thing can be accomplished by adding `permission` as an input parameter for `togglePermission` on line 39. This is how it initially was, but was broken by a [linting fix](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/d1c7f88ed79cfdce8554102250b9f13a5a7ec88b). You can rename `permission` to something like `permissionKey` to remove the linting error.
> > 
> > 
> > Well, I did pass the lint style check and rename will change a lot, changing the whole jsx not just this single function. Plz check all occurence of 'permission'([458b9df](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/458b9df082dd067668e653cc1e055fccdbcda51e))
> 
> I made a PR to show what I mean. This seems like a simpler way to fix it. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2512/files

You can pull another PR and report the permissionKey lint error to the bug doc, that is totally fine. I do not want to change the original dev branch a lot. plz do not add duplicate label here, as it is not a duplicate one.

**Comment by nathanah** [comment]
> > > > This whole thing can be accomplished by adding `permission` as an input parameter for `togglePermission` on line 39. This is how it initially was, but was broken by a [linting fix](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/d1c7f88ed79cfdce8554102250b9f13a5a7ec88b). You can rename `permission` to something like `permissionKey` to remove the linting error.
> > > 
> > > 
> > > Well, I did pass the lint style check and rename will change a lot, changing the whole jsx not just this single function. Plz check all occurence of 'permission'([458b9df](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/458b9df082dd067668e653cc1e055fccdbcda51e))
> > 
> > 
> > I made a PR to show what I mean. This seems like a simpler way to fix it. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2512/files
> 
> You can pull another PR and report the permissionKey lint error to the bug doc, that is totally fine. I do not want to change the original dev branch a lot. plz do not add duplicate label here, as it is not a duplicate one. The most important thing here is My pr did not show any lint error.

I'm not claiming your code had a lint error. The bug you are claiming to fix was created by someone's linting PR which is why I'm bringing up linting at all.

**Comment by 20chen-7** [comment]
> > > > > This whole thing can be accomplished by adding `permission` as an input parameter for `togglePermission` on line 39. This is how it initially was, but was broken by a [linting fix](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/d1c7f88ed79cfdce8554102250b9f13a5a7ec88b). You can rename `permission` to something like `permissionKey` to remove the linting error.
> > > > 
> > > > 
> > > > Well, I did pass the lint style check and rename will change a lot, changing the whole jsx not just this single function. Plz check all occurence of 'permission'([458b9df](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/458b9df082dd067668e653cc1e055fccdbcda51e))
> > > 
> > > 
> > > I made a PR to show what I mean. This seems like a simpler way to fix it. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2512/files
> > 
> > 
> > You can pull another PR and report the permissionKey lint error to the bug doc, that is totally fine. I do not want to change the original dev branch a lot. plz do not add duplicate label here, as it is not a duplicate one. The most important thing here is My pr did not show any lint error.
> 
> I'm not claiming your code had a lint error. The bug you are claiming to fix was created by someone's linting PR which is why I'm bringing up linting at all.

Gotcha, I will close this PR

**Pull request closed without merging**
