### PR TITLE
Angela - MailChimp Replacement

### PR DESCRIPTION
**Pull request by angelalalacheng**
# Description
- We currently use MailChimp to send out our weekly progress updates. It is not user friendly and the price keeps going up. I’d like a replacement that an Admin can use via the app.
- Take over the work of previous people: [FE PR 1315](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1315) [BE PR 540](https://github.com/OneCommunityGlobal/HGNRest/pull/540) led to [1784](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1784)
- [Video of what’s needed](https://www.loom.com/share/ce0ff3e66f3e40e19703ad9f4206cad1?sid=775e17db-d792-4a1c-a6d6-26379ccfe48c)

ORIGINAL REQUEST

1. We currently use MailChimp to send out our weekly progress updates. It is not user friendly and the price keeps going up. I’d like a replacement that an Admin can use via the app:
2. “Create Announcement” option for Owners
3. Addition of this to Permissions Page
4. Ability for those with access to input emails to add them to list
5. Ability for those with access to import spreadsheet too add them to the list
6. Unsubscribe function so people can automatically remove themselves from the list
7. Integration with self-setup page so people can choose to subscribe as part of setting themselves up
8. Template for easily inputting the image, YouTube link, and other details we share every week so anyone can easily produce what you see below
9. Test send option to “test send” the blog to a designated email before sending
10. Section/field input for anything else we’d like to say at the end
11. Google also only allows limited sending, so we need this to send in batches of less than 100 (so 90) at a time and timed so that we don't get blocked as spam. Please build this into the email system too.
12. If any auto-posting integration with social media is possible, I’d love to include that too… and anything else that would make this weekly process easier/fasterAdd feature that allows users to schedule their own blue square vacations/emergencies

## Related PRS (if any):
This frontend PR is related to the [#1080 backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/1080).

## Main changes explained:
- Update `src/components/Announcements/index.jsx` for image upload plugins and remove useless functions.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as **Owner** user
5. See backend how to setup the email sending account
6. go to Dashboard→ Other Links→ Send Emails
7. verify two functions: `Broadcast Weekly Update` and `Send Email to specific user` and remember to test sending the email with image.

## Screenshots or videos of changes:
https://www.loom.com/share/1f66a2dd69fa4be4921370bae2a4c69b?sid=bf0393aa-cd39-44ba-ab9b-c37f6ddaf033

## Note:
If your account want to receive email, you need to set the email subscription in the profile page.
Screenshot 2024-08-20 at 9 01 21 PM
**Google also only allows limited sending, so we need this to send in batches of less than 100 (so 90) at a time and timed so that we don’t get blocked as spam.**

### CODE REVIEW

**Review by panchalvatneu — CHANGES_REQUESTED** [review]
It's unclear if this service sends emails in bulk. If we keep the recipient box empty does the email auto-send to everyone? but apparently gmail has a 100 emails limit? also where is the test send option? If we keep the email body empty the broadcast weekly update is still successful?
Screenshot 2024-09-07 162009

**Comment by angelalalacheng** [comment]
> Hello @angelalalacheng
> 
> I have noticed a small needed fix in the code, when a user is inputting nothing, and , when clicked weekly on the button "Broadcast Weekly update " and is still working without an error popup message.
> 
>  Screen.Recording.2024-08-22.at.9.25.25.AM.mov 
> Screenshot 2024-08-22 at 10 02 49 AM
> Thank you.

@manikittu810 Thank you for your review. I added the error popup message when a user is inputting nothing. It is helpful if you can try again.
Screenshot 2024-09-22 at 3 32 36 PM

**Comment by angelalalacheng** [comment]
> It's unclear if this service sends emails in bulk. If we keep the recipient box empty does the email auto-send to everyone? but apparently gmail has a 100 emails limit? also where is the test send option? If we keep the email body empty the broadcast weekly update is still successful?

Hi, @panchalvatneu 
Thank you for suggestions. For the first and second question, I believe you could look into backend code which will be more clear. I implemented the that function in the backend and if still has any concerns, I' m happy with any feedback. About the third question, I think test send option can be done by "Send Email to specific user". You can input one email to see if the content is correct. As for the last question, I have done that error popup and it is helpful you could try again.

**Review by SFA23SCM35V — COMMENTED** [review]
Tested the PR by verifying the Broadcast Weekly Update and Send Email to specific user functions. However, the email sending functionality, including sending emails with images, is not working as expected.

**Review by manikittu810 — CHANGES_REQUESTED** [review]
Hello @angelalalacheng 
Functions are not working as mentioned.

https://github.com/user-attachments/assets/06222890-bc84-45f5-ac45-d9bb764adac9



Thank you.

**Review by Ankuriboh — CHANGES_REQUESTED** [review]
Code works great, all functionalities worked as described. It is worth noting that I added my own TinyMCE editor API code that was reverted in #2232 (specifically, [this line](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/6bf511b72a208f3a79d5d2fe60347baef774283b#diff-10288012838ff74e80d2d9b7f1d6c3056c7426399e4da9ac08ea5273187f4a6dR79) caused the editor to not load since we don't bundle the editor anymore).

**Pull request merged**
