### PR TITLE
Ramya Lint Fix: Userprofile -> TeamWeeklySummaries

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description

- Lint fix for the TeamWeeklySummaries  (sub module) of the UserProfile Component

## Main changes explained:

-Removed unused imports

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3.  Verify if the application works as expected with respect to TeamWeeklySummaries in UserProfile 

## Note:
- Thoroughly test the functionality  , ensure it  works as before . Report any error you see so that I can go ahead make similar changes in the  other modules of UserProfile component 
-  A kind request to focus on testing the frontend over the eslint test .

### CODE REVIEW

**Comment by this-journey** [comment]
Hello, I am new to the team and would love to be able to test this PR, however, I am not sure of how the functionality should work since I don't have much experience with the application.  Is there a specific user account I should use or steps I should take that would allow me to test this?  As of now, when I select "Show Team Weekly Summaries" in my volunteer account user profile it just says "Loading" and nothing else displays.  Please let me know if I am doing something wrong or going about this incorrectly.
Screenshot 2023-12-05 at 2 08 29 PM (2)

**Review by Alforoan — CHANGES_REQUESTED** [review]
It just says "Loading" indefinitely.
image

**Comment by DragonSlayer2401** [comment]
As previously mentioned it loads indefinitely there was a status 400 Bad Request in the console which may be the issue. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/deefb1bb-2e15-4a82-b894-5f5d58eb9cad

**Review by Renanluizssx — APPROVED** [review]
Hi @ramyaram2092, i tested your application and when i click on the Hide Team Weekly Summaries button, it show me the user's summary, good

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/75c3195e-8939-49cc-9606-e08665f090eb

**Review by 666saofeng — APPROVED** [review]
Hi, I tested with admin account and it worked as intended on my side. Please refer to the video for the details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/aa837c97-269c-4e06-83ef-203aa1abb192

**Comment by EvianTan** [comment]
Work as expected and no error introduced by this PR.
image

**Pull request merged**
