### PR TITLE
Abdel make reports buttons obvious when clicked

### PR DESCRIPTION
**Pull request by abdel-lall**
# Description

 (PRIORITY LOW) Yiyun/Jae: Make reports buttons obvious they are "click to show/click to hide"
    1. When you click on “Projects”, “People” or “Teams”, the right table will disappear after an even number of clicks. We need an outline or shadow or other clear indicator which button is clicked so that it’s also clear that clicking it again will hide the related content.

## Mainly changes explained:
    1. dynamically adding the “selected” class to the report buttons when they’re clicked.
    2. Adjusted the size of the table container to prevent the report buttons from overlapping or stacking on top of each other. 
## How to test:
    1. check into current branch
    2. do `npm run start:local` to run this PR locally
    3. go to Reports > Reports
    4. Click on the report buttons (Projects/People/Teams) to see the style changes.

### Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/efe02938-43d5-4e66-9dcc-212a2fbad1c4

### After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/43457ed0-8e76-40ee-b549-02998be0e064

### CODE REVIEW

**Review by eduhorta — DISMISSED** [review]
It works as intended.

Before:
Screenshot 2023-05-22 10-46-14

After:
Screenshot 2023-05-22 10-46-18

I also noticed that the Navbar got a mb-3 leaving a blank space between these two sections.

Before: 
image

After:
image

This margin was related to PR #829
image

**Review by 20chen-7 — APPROVED** [review]
The code looks more organized after removing extra space. The function is intended

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/7f974075-d343-4b3e-8fe3-a2e7dc821f9b

.

**Review by NidaZaki — COMMENTED** [review]
The changes look good. The buttons don't overlap when clicking on the "Projects" button. Also, the buttons get highlighted when selected.
Before:
PR#846-1

After:
PR#846

Although I noticed a margin on the ReportsPage which was related to PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/829 

PR#846-3

**Review by stevenpaalz — DISMISSED** [review]
Change is working as intended.

Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/dd2e311a-6219-4d87-a4d2-4738d99bcffd



After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121642083/2a8177df-d6bb-4892-8028-a49cea1915df

**Comment by one-community** [comment]
I think I like the list closer to the buttons... less distance to travel to click a name, which is the purpose of the list. To make it look better though, can we just center everything rather than having the buttons all on the left?

**Review by lchua2314 — DISMISSED** [review]
Looks good. 

Before:
PR 846 Before

After:
PR 846 After

**Comment by AnishPandita** [comment]
Hi @abdel-lall I tested your PR and its working as intended. Clicking on the report button makes it clear that they are clicked to avoid confusion.
Screenshot 2023-05-23 at 2 33 29 AM
Screenshot 2023-05-23 at 2 33 40 AM

**Review by EdwinLauM — APPROVED** [review]
Works as intended! Good job! 

Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/c3d832a2-6d4f-45cf-805c-069b9f78672e

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/b1fd25b3-ef96-43f2-b91e-b62292b40451

**Review by NidaZaki — DISMISSED** [review]

**Comment by one-community** [comment]
Thank you all, moving to final review!

**Review by suigunfjc — COMMENTED** [review]
Hi @abdel-lall , I tested your branch and it works as intended. Great Job.
image

image
image

However, after reviewing your changes, I noticed that there are several format modifications unrelated to this function.(App.css, PeopleTable.js, ProjectTable,jsx, TeamTable.jsx, etc). @nicollext and @EvianTan are currently working on re-enabling ESLint and Prettier for automatic code formatting. To avoid any conflicts, I suggest pausing the format changes until the code formatting tools are fully operational.

**Pull request merged**
