### PR TITLE
Move App from Surge to Netlify

### PR DESCRIPTION
**Pull request by agryash**
# Description
Since we're facing a lot of issues with Surge, it's better to move to Netlify with much less downtime. Upon research, it was found that Netlify has a Open Source Plan Policy. This PR addresses the changes that make us align to the requirements of their Policy. The policy can be found [here](https://www.netlify.com/legal/open-source-policy/). 

## Related PRS (if any):
No Related PRs

## Main changes explained:
- Added Code of Conduct for One Community Global
- Added Link to Netlify's homepage on our homepage.

## How to test:
1. check into current branch
2. check for changed Code of Conduct in README.md
3. npm start on frontend
4. should be able to see footer which links to Netlify's home page

## Screenshots or videos of changes:
image

### CODE REVIEW

**Comment by one-community** [comment]
Help by triple checking we meet the criteria and any suggestions you may have for adding to the Code of Conduct.

**Review by AJAYINAVOLU — DISMISSED** [review]
License Compliance: We’ve included GPL v2 in our documentation, meeting the Open Source Initiative standards required by Netlify’s Open Source Plan.

Code of Conduct: Our Code of Conduct is visible in the repository readme file, supporting Netlify’s requirements for community engagement.

Netlify Link Integration: The "This site is powered by Netlify" link is active on our site, supporting Netlify’s visibility expectations.

Non-Commercial Assurance: Our project remains non-commercial in compliance with Netlify’s guidelines.

image

I think we are good to go with Netlify since we're following all the guidelines they've set.

**Review by AJAYINAVOLU — DISMISSED** [review]
License Compliance: We’ve included GPL v2 in our documentation, meeting the Open Source Initiative standards required by Netlify’s Open Source Plan.

Code of Conduct: Our Code of Conduct is visible in the repository readme file, supporting Netlify’s requirements for community engagement.

Netlify Link Integration: The "This site is powered by Netlify" link is active on our site, supporting Netlify’s visibility expectations.

Non-Commercial Assurance: Our project remains non-commercial in compliance with Netlify’s guidelines.

image


I think we are good to go with Netlify since we're following all the guidelines they've set.

I have reviewed the new changes for formatting and the updated code of conduct.

**Comment by strallia** [comment]
Suggested Changes for Code of Conduct:
- Under the Prohibited Behaviors section, I suggest listing the items with bullet points for readability and clarity, since it lacks proper punctuation at the moment.
- For the Reporting Concerns section, I suggest adding hyperlinks to the Contact Us and Software Suggestions/Development pages for easy redirection. 

Suggested UI Changes for Netlify footer:
- I recommend moving the footer text to the bottom edge of the page. Right now, it floats in the center of my page.

Compliance with Netlify’s Open Source Plan Policy:
- For the criteria “Includes a license listed on the Open Source Initiative approved license list or a Creative Commons license that includes 'attribution' or places the work in the public domain.” It looks like two licenses are referenced in the README: a Creative Commons Attribution 3.0 Unported License and the GPL v2. I’m not sure if both are needed, but either one satisfies this criteria. Whichever license is used, I suggest [adding a License file to the repo](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) containing the full details of the license.  
- For the criteria “Features a Code of Conduct at the top level directory of the project repository or prominently in the documentation (with a link in the navigation, footer, or homepage).” I recommend updating the README's Table of Contents to include a link to the Code of Conduct section.
- All other criteria are satisfied.

Screenshot 2024-08-30 at 4 55 15 PM

**Review by strallia — CHANGES_REQUESTED** [review]
I've requested changes in my [previous comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2623#issuecomment-2322628442)

**Pull request merged**
