### PR TITLE
Yili fix permissions management info icon

### PR DESCRIPTION
**Pull request by suaniii**
# Description
image

## Related PRS (if any):
For backend use development branch

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links→ Permissions Management → Any role
6. Click on the info icons on the right side of the `save` button and the `delete` button
7. Verify the information displayed in the pop-ups is correct.
8. Verify the page does not crash.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/19c647ee-65d3-46ed-99e8-0ca9c64276c8

save
dele

### CODE REVIEW

**Review by vijay10pk — APPROVED** [review]
All the changes works as per the requirement.

Screenshot 2024-07-06 at 1 32 06 PM
Screenshot 2024-07-06 at 1 32 41 PM

**Review by vijay10pk — DISMISSED** [review]
The pop-ups are not closing when the 'X' icon is clicked for both save and delete info pop-up. For save pop-up it is opening the delete pop-up when i try to close by clicking on x icon. Please re-check the logic for closing the pop-ups. Refer the video clip for better understanding.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/5028dde0-3411-438d-8352-a062366340e1

**Review by nyelmela — COMMENTED** [review]
I have tested PR 2421 the changes on the current branch by following the steps provided: performed `npm install` and ran the PR locally, cleared site data/cache, logged in as an owner user, navigated to the dashboard, accessed Other Links, then Permissions Management, and selected any role. I clicked on the info icons on the right side of the save button and the delete button, verified the information displayed in the pop-ups is correct, and confirmed that the page does not crash. However, I encountered an issue where clicking the cross button to close the pop-up sometimes triggers the delete pop-up if I click the cross on the save pop-up and vice versa. Other than this, everything works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/5ac210a2-64d3-4961-a9c3-b893ac0b8618

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
When I try to exit the popup "delete the role" popup comes up instead of closing that popup.  Please fix this.

https://github.com/user-attachments/assets/1cce5a02-54c0-475a-850f-18ed368a4ac6

**Review by ishan-miglani — CHANGES_REQUESTED** [review]
I have tested the changes here. When the 'save' popup is closed the 'delete role' popup comes up. Also when you click on the close icon for the 'delete' popup, nothing happens. Please address this

https://github.com/user-attachments/assets/10449edb-542c-4521-80c3-9326d9701d16

**Review by nikhilpittala16 — CHANGES_REQUESTED** [review]
When the 'X' symbol is clicked on the save or delete info pop-ups, the pop-ups do not close. When I click the x symbol to close the save pop-up, it opens the delete pop-up instead. Kindly review the reasoning behind the pop-ups' closure. See the video clip for a clearer explanation.

https://github.com/user-attachments/assets/42fc1a40-ce23-46eb-a483-00814e2986db

**Review by SrikanthChowdary495 — COMMENTED** [review]
The 'X' icon isn't working to close the save and delete pop-ups. When I try to close the save pop-up, it opens the delete pop-up instead. Please review the code for closing these pop-ups. I've included a video clip for clarity.

https://github.com/user-attachments/assets/2ae02311-0cd1-4d26-8e08-c151e4cc2370

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected.
Screenshot 2024-07-20 at 4 40 46 AM
Screenshot 2024-07-20 at 4 40 51 AM

**Comment by suaniii** [comment]
Fixed the issue mentioned above. Please check it again. Thanks all!

**Comment by angelalalacheng** [comment]
Hi,
I use `yili_fix_permissions_management_info_icon` for frontend and the latest development branch for backend. The popup works good but the text is not apparent in the dark mode.

Light mode:
Screenshot 2024-07-20 at 11 16 15 AM
Screenshot 2024-07-20 at 11 16 24 AM

Dark mode:
Screenshot 2024-07-20 at 11 16 49 AM
Screenshot 2024-07-20 at 11 16 58 AM

**Review by pavanswaroopl — DISMISSED** [review]
Excellent work,

Didn't get any errors as stated by others, worked fine

https://github.com/user-attachments/assets/81342f38-9f70-49ff-b9f1-4b1dfb8b3e7d

Screenshot 2024-07-20 at 8 26 12 PM

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR and its working as expected. Closing a pop up doesn't open another.

https://github.com/user-attachments/assets/fe6c679c-fd75-4aff-a4ae-9c54bb79261e

**Review by Chetan0606 — APPROVED** [review]
Everything looks good. Here's an attached video of my observation

https://github.com/user-attachments/assets/bfc25066-9aea-40b0-b54f-11ac83500c81

**Comment by cecilia-uu** [comment]
截屏2024-07-21 下午2 53 56
截屏2024-07-21 下午2 54 22
Work as expected!

**Review by ishan-miglani — APPROVED** [review]
Everything works well now. Great work!
Please fix the CI build for the branch and should be good. Thanks!

https://github.com/user-attachments/assets/15b20c5c-bbda-4c68-bb63-41b664dd444a

**Comment by souravwalke** [comment]
I tested this PR and it is working as expected.

https://www.loom.com/share/8de94a092c8547a8a7d7aa35529fba0e?sid=951228ac-7564-4d3b-88d2-9c656b192fac

**Review by kabraambika — DISMISSED** [review]
I have reviewed the functionality on the frontend branch `yili_fix_permissions_management_info_icon` and the backend `development` branch.

Both the save and delete modals are working as intended in both light and dark modes, displaying the correct text as shown below:

image

image

**Comment by suaniii** [comment]
Hi folks, the pipeline issue was fixed. Please take a look and approve, thanks.

**Review by ishan-miglani — APPROVED** [review]
Verified the changes after rebase. Works as intended. Thanks!

https://github.com/user-attachments/assets/7bd67cde-17a4-46c4-8490-71bc738cde54

**Comment by arunsrao9** [comment]
I tested this PR and it is working as expected.
Screenshot 2024-07-26 at 10 40 43 AM
Screenshot 2024-07-26 at 10 40 40 AM
Screenshot 2024-07-26 at 10 40 34 AM
Screenshot 2024-07-26 at 10 40 30 AM

**Review by kabraambika — APPROVED** [review]
Good work! I have reviewed the features for the Frontend PR after the pipeline issue was fixed. The feature is working as intended in both dark and light mode, as shown below:
image

image

**Review by ReinaT5678 — APPROVED** [review]
I made sure to test both the "ok" and "x" buttons for the popups and they all work correctly!

https://github.com/user-attachments/assets/5e1767d8-03df-4669-b620-888cf90569fc

**Review by varunreddy03 — APPROVED** [review]
I have verified this PR and both the info button descriptions of Save and Delete are working as intended in both Light and Dark mode.

PR 2421_1
PR 2421_2

**Review by Parth-tech — APPROVED** [review]
Hi Yili,
The PR works as intended and the codebase looks great as well. 


`Image reference:`

Screenshot 2024-08-01 at 9 22 49 PM
Screenshot 2024-08-01 at 9 23 11 PM

**Review by Pranay-ai — APPROVED** [review]
Hey @suaniii 
The PR is working as expected here is the screenshots for reference
image
image
image
image

Thank You.

**Review by AnkitLall — APPROVED** [review]
Hi @suaniii,

I have tested the feature, following the instructions in the PR, and it works as expected. Please refer the attached video recording of the testing.

https://github.com/user-attachments/assets/0b8cf135-4b9b-4818-93e6-1a0ba58932f4

**Review by adityasure9 — APPROVED** [review]
Hi @suaniii,

I tested the PR, and the info icons now work as expected. The pop-ups display the correct information and close properly when the "X" button is clicked, without triggering any other pop-ups or causing the UI to freeze. Everything works well in both light and dark modes.

I also tested for rapid clicks on the info icons, and the functionality remained stable. Great job on fixing this issue!

**Review by preethamdnr — APPROVED** [review]
Hello Yili,
Both save and delete icon working fine. 
image
image

**Pull request merged**
