### PR TITLE
Jinchao apply missed hours to Core Team member

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
Front end update for: a&b
image

## Mainly changes explained:
Add new attribution for Core Team members under the volunteering time tab: Additional Make-up Hours This Week. 

Weekly committed time for Core Team members in the summary bar, leaderboard, and tasks board is now the sum of weekly committed hours and their last week's missed hours(Additional Make-up Hours This Week).

## How to test:
Please test with back-end [PR313](https://github.com/OneCommunityGlobal/HGNRest/pull/313)

Frontend functionality:
1. Log in as an admin user and see userProfile pages of users in different roles 
(Other links->user management->click on user's name -> volunteer). 
Make sure that **ONLY THE CORE TEAM** members have the 'Additional Make-up Hours This Week' in their volunteering times tab. 
image

2. Try if the new field can be edited and saved like other number value fields.
3. Log in as other non-admin roles and check if the field is read-only
image

4. Log in as a core team member, and check if the weekly committed time in the dashboard is now the sum of weekly committed hours and additional make-up hours. (Summary Bar, Leaderboard, team member tasks)
image
image
image

5. Log some time logs and see if the progress bar in the summary bar and the red/green dot in the leaderboard work as indeed. You can first log 1 min of tangible time using the clock and edit the time length of it at the current week timelog tab. The red dot should turn to green when the user has met the required hours. In my example, the weekly committed hour for the user is 30 hours while it has 12 hours of make-up time.
image

6. Create a new user of the Core Team role or set a user's role to Core Team. Check if the make-up time is set to 0 as default.
## Note:
**Please also read the test instructions in the backend [PR313](https://github.com/OneCommunityGlobal/HGNRest/pull/313): This function needs to be thoroughly tested at both the frontend and backend.**

### CODE REVIEW

**Review by LucileTech — APPROVED** [review]
Hi @suigunfjc, I reviewed your PR and everything is working as intended : 

- no make-up hours for volunteer

1 no make up hours for volunteer

- Make up hours for volunteer

2 make up hours for volunteer

- With admin rights the new field can be edited and saved like other number value fields


https://user-images.githubusercontent.com/111132148/231612575-c54fe277-4c7e-4861-9542-91cdf8602f16.mp4

- As other non-admin roles the field is read-only
4 as other non-admin roles the field is read-only

- As a core team member the weekly committed time in the dashboard is the sum of weekly committed hours and additional make-up hours
5 as a core team member the weekly committed time in the dashboard is the sum of weekly committed hours and additional make-up hours


- The progress bar in the summary bar and the red/green dot in the leaderboard work as indeed






6 1 the progress bar in the summary bar and the red:green dot in the leaderboard work as indeed
6 2 the progress bar in the summary bar and the red:green dot in the leaderboard work as indeed


- For a new core team user the make-up time is set to 0 as default
7 for a new core team user the make-up time is set to 0 as default

**Comment by agujjar2206** [comment]
Hello @suigunfjc, great work on the PR! All the features work as expected.

Screenshots:







Thank you.

**Review by vitorsaa2k — APPROVED** [review]
The profile used for test has a 10 hours week committed hours and 10 Additional Make-up Hours.
image

- With 17 hours committed.

image

- With the full 20 hours committed.

image

The changes works as intended.

**Comment by one-community** [comment]
Thank you everyone, moving this one to final review!

**Review by PrabhjotSembhi — COMMENTED** [review]
Here is one issue. 
When I add time with clock the amount of time logged is also add to total hours. 
Example: 
10 hours committed 
5 hours Make-up Hours 

total 15 hours 

if I log 10 mins with clock it will become
Screenshot 2023-04-15 172734
Screenshot 2023-04-15 175352


logged time 0.10 / 15.10

**Comment by suigunfjc** [comment]
Hi @PrabhjotSembhi, the issue exists on the dev host. I think the current logic for total hours is tangible hours + intangible hours. The weekly committed hour which equals weekly committed hours + make-up hours will show when your mouse is over the green/red dot.

**Comment by one-community** [comment]
Yes, this logic is correct. Total time includes tangible plus intangible. That means though that you should only have a larger number on the right if you log intangible time. Is that what's happening for you Prabh?

**Comment by PrabhjotSembhi** [comment]
> , the issue exists on the dev host

Ok got it

**Review by PrabhjotSembhi — APPROVED** [review]

**Pull request merged**
