### PR TITLE
Olena_edit_delete_functionality_for_lesson_card

### PR DESCRIPTION
**Pull request by olenadanykh**
**Description**
Lesson list component for Phase II
lessonlistpage

**Related PRs (if any):**
#1479
…

**Main changes explained:**
Implemented functionality for the Edit & Delete buttons on the Lesson Card (visible and operable only for the author of the card).
Users can click on the Edit button to modify the lesson summary, with added validation to ensure the summary is not empty.
Users can click on the Delete button to remove the entire card.

**How to test:**

1. Checkout to the current branch.
2. Run npm install and ... to run this PR locally.
3. Log in as any user.
4. Go to http://localhost:3000/bmdashboard/lessonlist.
5. Verify the design, tag input functionality, and expand/collapse card functionality (PR1479).
6. Test the Edit & Delete buttons. To test, please change the userId to your userID in DummyData (src -> components -> BMDashboard -> LessonList -> Lessons.jsx -> DummyData -> userid).

**## Note:**
Please note that the Figma navigation bar and the current design differ. I've made adjustments based on Jae's request, and he has also verified the design.
Currently, I am using dummy data, and the frontend is not connected to the backend. LocalStorage is not utilized to store data, so the functionality is not persistent after page refresh. I'll connect all these features to the backend and will load data from DB later, as the schema, routers and controllers are still in progress.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/fe50da50-953d-47ce-bdaf-77187d05b9e7

### CODE REVIEW

**Review by lacnoskillz — DISMISSED** [review]
@olenadanykh 
Nice work! the lesson list page looks so good and you added a lot of awesome functionality
I was able to pull your changes and it functions as described
great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/38d1fd9a-15b6-4d37-8800-e6acff1c88ad

Note
for anyone having trouble getting their id you can console log it and grab it here
image

**Comment by ptrpengdev** [comment]
Hi @olenadanykh , I tested the PR, and all the mentioned features work as expected. However, I found a minor issue with the tags display when the browser window is narrowed. The scroll bar appears, covering most of the tag content. I have attached the screenshot below.

- Verify the design, tag input functionality, and expand/collapse card functionality
image

- Tested the Edit & Delete buttons. (**You can see the scroll bar covered the tags**)
image
image

**Comment by Cavein254** [comment]
Hi, @olenadanykh , your component is working as expected after adding data to the component DummyData (src -> components -> BMDashboard -> LessonList -> Lessons.jsx -> DummyData -> userid).

- [x] The edit and delete buttons showing
- [x] Component editing functionality
- [x] Component delete functionality

Screenshot from 2023-12-07 14-14-56


Screenshot from 2023-12-07 14-09-00

Screenshot from 2023-12-07 14-09-21

Screenshot from 2023-12-07 14-09-36

**Comment by olenadanykh** [comment]
> Hi @olenadanykh , I tested the PR, and all the mentioned features work as expected. However, I found a minor issue with the tags display when the browser window is narrowed. The scroll bar appears, covering most of the tag content. I have attached the screenshot below.
> 
> * Verify the design, tag input functionality, and expand/collapse card functionality
>   image
> * Tested the Edit & Delete buttons. (**You can see the scroll bar covered the tags**)
>   image
>   image


Hi @ptrpengdev, thank you for bringing that to my attention. I've made some adjustments to the styling, and now the horizontal scrollbar should appear thicker and not cover the text. Could you please confirm if it looks better on your end when you have a chance? Appreciate your feedback. Thanks!

scrollbar

**Pull request closed without merging**
