### PR TITLE
Strallia: Hotfix for the visibility of i icon modal and taking-time-off overlay on tasks list

### PR DESCRIPTION
**Pull request by strallia**
# Description
This PR is a hotfix for [PR2725](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2725) and [PR2660](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2660). Changes from the first PR disabled the fixes from the second, which this hotfix resolves.

## Main changes explained:
- Revert changes from PR2725
- Update TeamMemberTask.jsx to fix visibility of i icon modal and positioning of the taking-time-off overlay on Safari
- Update FollowUpInfoModal.css to decrease the height of the modal to view all its contents
- Update style.css to fix overlapping table data, positioning of buttons, borders, etc. to make it as close to the original design

## How to test:
1. check into current branch
2. do `npm install` and `npm start` to run this PR locally
3. Clear site data/cache
4. log as owner or admin user
5. go to dashboard→ Tasks and Timelogs→ Team Member Tasks table
6. at least one team member must have a blue square to test the taking-time-off overlay
7. verify the taking-time-off overlay covers a single row in Safari and Chrome. It should work like this:

https://github.com/user-attachments/assets/032d2844-88bf-44ed-89fc-64064c9225e6

8. verify the content of the i icon modal is fully visible or scrollable

https://github.com/user-attachments/assets/c97579f1-0a52-433a-bc8d-e76ba3dde57b

10. verify both features work in darkmode
12. verify both features are responsive on mobile, tablet, desktop

## Note:
n/a

### CODE REVIEW

**Review by shivansh-nathani — APPROVED** [review]
I have tested the changes and things are working as expected.

https://github.com/user-attachments/assets/6076e60d-37e0-4d43-a26c-5de9c6bc2206

https://github.com/user-attachments/assets/67aa28c4-386a-4f83-a094-52991e84c63b

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/c3b63a2a-1a20-405a-bb11-24dcbde4e788

**Review by manikittu810 — APPROVED** [review]
Hello @strallia 
Everything is working as mentioned.
Screenshot 2024-10-18 at 7 57 18 AM
Screenshot 2024-10-18 at 7 57 31 AM
Screenshot 2024-10-18 at 7 57 59 AM
Screenshot 2024-10-18 at 7 58 19 AM

Thank you.

**Review by Jingyii800 — APPROVED** [review]
I have tested this feature an it works as expected. The time-off looks in one row and it's responsive for different sc

https://github.com/user-attachments/assets/2abb0efc-f269-4733-bdd9-61a777e96df6

reen size.

**Review by NK3101 — APPROVED** [review]
Tested the PR, interface works as expected in both light and dark modes.

https://github.com/user-attachments/assets/6439db9b-00d4-4345-8c6f-8aeadce61214

**Comment by geetamatkar** [comment]
Tested this PR and it is working as expected.

Screenshot 2024-10-19 at 3 18 50 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
