### PR TITLE
Anirudh - Leaderboard a way to see how many days until a person’s last day.

### PR DESCRIPTION
**Pull request by Pandani07**
# Description
Add to Leaderboard a way to see how many days until a person’s last day. A scheduled last day can be set in 3 places:

1. User Management>Set Final Day
2. Profile>Basic>Set Final Day Information
3. Profile>Volunteer Times tab>End Date
image

## Related PRS (if any):
This frontend PR is related to the backend PR [#927](https://github.com/OneCommunityGlobal/HGNRest/pull/927)
This is an updated PR for https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2011. I have used the latest development branches.
…

## Main changes explained:
After this Date has been set, you can see the count of the remaining days on the leaderboard, under the days left column.

## How to test:

1. check into the current branch
2. do npm install and npm run start:local to run this PR locally
3. Clear site data/cache
4. log as an OWNER user
5. go to dashboard→ view Profile→ Set a final day at the bottom. You should see a red countdown indicator on the leaderboard. If it does not show up immediately, reload the page. Only Owners/ admins can set the final dates.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/5234be92-a958-4d37-8a23-58d8d782485f
image

## Note:
This only works If you're an owner user. The setting of the final day was not my task, my task was to just _display_ the set final day on the leaderboard.

### CODE REVIEW

**Review by hbodgal — CHANGES_REQUESTED** [review]
I tried to test this PR but got white screen whenI open "View Profile" page. I have logged in using Owner Account.

image

**Review by linkhanthtel — CHANGES_REQUESTED** [review]
I run with the owner account. When I go to 'View Profile', I only see the white screen.

**Comment by Pandani07** [comment]
> I tried to test this PR but got white screen whenI open "View Profile" page. I have logged in using Owner Account.
> 
> image

I have asked people not to review this PR in the description

**Comment by Pandani07** [comment]
> I run with the owner account. When I go to 'View Profile', I only see the white screen.
> 
> 

Please dont review this PR as the backend is not ready

**Review by Sandhya1236 — APPROVED** [review]
I have tested the changes successfully by checking out the current branch, running npm install, and npm run start:local to set up the PR locally. After clearing site data and cache, I logged in as an OWNER user and navigated to the dashboard to view the profile. I set a final day at the bottom of the profile page and observed a red countdown indicator on the leaderboard. If the indicator did not appear immediately, a page reload resolved the issue. Only Owners and Admins can set the final dates. All functionalities worked as expected, and the feature appears stable. The PR is ready for merging.

image

**Review by peter6866 — APPROVED** [review]
Great work on implementing the countdown indicator for a person's last day on the Leaderboard!

Here's my review based on the provided testing steps:

✅ **Countdown Indicator Implementation:**
- Checked out the current branch and ran `npm install` and `npm run start:local`.
- Cleared site data/cache and logged in as an owner user.
- Navigated to the user's profile and set a final day.
- Verified that a red countdown indicator appeared on the Leaderboard under the "Days Left" column as expected.

✅ **Functionality:**
- Confirmed that the countdown indicator accurately displays the number of days remaining until the set final day.
- Verified that the indicator updates dynamically as the final day approaches.

✅ **User Permissions:**
- Confirmed that only owners and admins can set final dates for users, as per the requirements.

https://www.loom.com/share/7765f35c13ea4406b07191171052c167?sid=0118b632-d291-4be8-bea0-49fc8878241d

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
When I try to set a final day through View Profile-> Basic Information -> Set final day.
The final date being set is one day before the date I selected. 
The other 2 approaches are working just fine.
Please fix this.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/081f88ac-4b0c-4c49-955e-4187e018c397

**Review by KaushikMreddy — APPROVED** [review]
Hi Anirudh, 

I've tested your changes. I changed it in the user management tab,  user profile basic information tab, and volunteering times tab, all have reflected the changes.
image
The -49 is visible on the leaderboard.
image

**Comment by akshit0211** [comment]
Hi Anirudh, the changes are working as expected. Good Job!

profile page
owner
volunteer

**Review by akshit0211 — APPROVED** [review]

**Review by Kavil-Jain-514 — APPROVED** [review]
I have reviewed the PR and the red countdown indicator is displayed on the leaderboard.

image

**Review by Sudershhh — APPROVED** [review]
Hi Anirudh,

I set the final day date and able to see the day counter text to the right of the name. Good Job!

PR 2220 + 927

**Review by suaniii — APPROVED** [review]
I reviewed the PR, and all functionalities worked as expected. I logged in as an admin user, navigated to the dashboard, and viewed the profile. After setting a final day at the bottom of the profile page, I observed a red countdown indicator on the leaderboard. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/468bec0c-7e94-4192-889e-5b1d39721a50

**Pull request merged**
