### PR TITLE
Shengjie new badges unit test cont

### PR DESCRIPTION
**Pull request by ShengjieMao**
# Description
Unit test for NewBadges component based on pr#1783's reviews. 

## Related PRS (if any):
This frontend PR is related to the #1783 frontend PR 

## Main changes explained:
- Moved test file to the new designed location
- Added more tests on filtering, sorting, and other features
- Rewrote some old tests to include more conditions
…

## How to test:
1. check into current branch
2. do `npm test NewBadges.test.js`
3. Check if all test cases passed

## Screenshots or videos of changes:
testNB

### CODE REVIEW

**Review by PratimaSingh02 — APPROVED** [review]
All the test cases have passed. Great work!
image

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.

PR 2068

**Review by Abi-Liu — APPROVED** [review]
Looks good! All tests are passing as expected.
Screenshot 2024-03-16 at 3 51 33 PM

**Review by AaronPersaud — APPROVED** [review]
Hi @ShengjieMao, I've tested and all the tests have passed! Good job.

image

**Comment by dhairya-mehta** [comment]
Hey, I tested out your code, good job!
image

**Review by ImzIssa — APPROVED** [review]
Hello, all the test cases pass. Nice Work!

PR#2068

**Review by Pandani07 — APPROVED** [review]
All test cases passed, PR works as intended
Screenshot 2024-03-20 at 7 49 44 PM

**Review by KurtisIvey — APPROVED** [review]
Looks good. Everything was addressed in this new pull request from 1783. Great job

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
