### PR TITLE
Shrey_unit_test_cases_Stub

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for Stub component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test Stub.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-11-25 at 12 36 21 PM

### CODE REVIEW

**Review by scoopstroop92 — COMMENTED** [review]
Hello @Shreyj14 good job on the unit tests

I see you have the test file under projects/components/ whereas other unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?

**Review by Hemsharavanan — APPROVED** [review]
- Your tests cover fundamental aspects like rendering, contained icon, text presence, icon size, and class name.
- Majority of assertions use appropriate methods like screen.getByText and direct queries, ensuring basic functionality validation.
- Overall the tests provide coverage for essential functionalities of the Stub component, ensuring the presence of text, correct icon size.
PR #1581 Shrey_unit_test_cases_Stub

**Comment by palakgosalia** [comment]
Hey, I reviewed your code and ran the test. All 5 out of 5 test cases passed. 

image

**Review by Alforoan — APPROVED** [review]
All passed. Nice!

image

**Comment by Shreyj14** [comment]
> Hello @Shreyj14 good job on the unit tests
> 
> I see you have the test file under projects/components/ whereas other unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?
> 
> 

Hi @ramyaram2092 the tests needs to be in the component folder, as mentioned in 
https://docs.google.com/document/d/1-iWj_1XJ_hFE0lRAAWvOfKtrkacT5HIvfWUu-6shQ08/edit?pli=1#heading=h.lz7htr6nv182.

**Comment by one-community** [comment]
> > Hello @Shreyj14 good job on the unit tests
> > I see you have the test file under projects/components/ whereas other unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?
> > 
> 
> Hi @ramyaram2092 the tests needs to be in the component folder, as mentioned in https://docs.google.com/document/d/1-iWj_1XJ_hFE0lRAAWvOfKtrkacT5HIvfWUu-6shQ08/edit?pli=1#heading=h.lz7htr6nv182.

This is what is correct, do we need to update the documentation? 
image

**Comment by ramyaram2092** [comment]
@shrey  Currently your test file is under this path . src/components/common/Stub/Stub.test.jsx
If you observe the screenshot of the slack as provided by Jae   the test files should go under  a  folder called __tests__  with thin the component. i.e. **_src/components/common/Stub/__tests__/Stub.test.jsx_**

**Comment by ramyaram2092** [comment]
> > > Hello @Shreyj14 good job on the unit tests
> > > I see you have the test file under projects/components/ whereas other unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?
> > > 
> > 
> > 
> > Hi @ramyaram2092 the tests needs to be in the component folder, as mentioned in https://docs.google.com/document/d/1-iWj_1XJ_hFE0lRAAWvOfKtrkacT5HIvfWUu-6shQ08/edit?pli=1#heading=h.lz7htr6nv182.
> 
> This is what is correct, do we need to update the documentation? image

Yes it needs to be updated

**Comment by one-community** [comment]
> > > > Hello @Shreyj14 good job on the unit tests
> > > > I see you have the test file under projects/components/ whereas other unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?
> > > > 
> > > 
> > > 
> > > Hi @ramyaram2092 the tests needs to be in the component folder, as mentioned in https://docs.google.com/document/d/1-iWj_1XJ_hFE0lRAAWvOfKtrkacT5HIvfWUu-6shQ08/edit?pli=1#heading=h.lz7htr6nv182.
> > 
> > 
> > This is what is correct, do we need to update the documentation? image
> 
> Yes it needs to be updated

Please use the suggest function on the doc so I can approve the change

**Pull request closed without merging**
