### PR TITLE
Shihao - Lint Fix WeeklySummariesReport

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Lint Fix `src/component/WeeklySummariesReport/**`

## Main changes explained:
- Change the code style according to ESLint and Prettier

## How to test:

1. check into current branch
2. do npm install and ... to run this PR locally
3. log as any user
4. go to dashboard→ summary
5. check the app works as normal
6. set up ESLint and Prettier in VSCode
7. check all files in `src/component/WeeklySummariesReport/**` doesn't have errors
8. Follow the instructions in the video to run the command

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/b1c7c2c9-8212-4a7e-a4b3-71c09ee1c961

### CODE REVIEW

**Review by Changhao3220K — APPROVED** [review]
Hi @sxiong5 I tested the app on admin locally and it works fine, for the eslint it shows one warning.
Screenshot 2023-11-17 at 8 50 26 PM
Screenshot 2023-11-17 at 8 54 44 PM

**Comment by AnishPandita** [comment]
Hey I tested the PR according to your guidelines and didn't get any lint errors. Everything worked fine as well.
Screenshot 2023-11-17 at 7 17 53 PM

**Review by sahilpatel18 — APPROVED** [review]
After testing, I found that everything works exactly as intended. Additionally, there were no lint errors. Great work!

PR 1557

**Review by Bali2Mohit — APPROVED** [review]
Hi @sxiong5, I have tested your PR. Works perfectly
Screenshot 2023-11-18 at 16 07 27
Screenshot 2023-11-18 at 16 12 04

**Comment by ptrpengdev** [comment]
Hi @sxiong5, I tested the PR with the Admin account. The UI  and the App work without any issues. 

image

**Review by Hemsharavanan — DISMISSED** [review]
The code successfully lints without any errors, and the application functions properly post linting changes. Good work!
PR #1557 Shihao - Lint Fix WeeklySummariesReport

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
