### PR TITLE
Added test file for LoginPrivileges

### PR DESCRIPTION
**Pull request by aaryaneil**
# Description
Added unit tests to check for LoginPrivileges functionality.

## Main changes explained:

Added test cases to check the following:

1. Test Render Radio Buttons
2. Test Selected Input Checked
3. Test Handle Input Change Called
4. Test Default Selected Input
5. Test Radio Buttons Interact
6. Test No Role Selected
7. Test Multiple Renders

## How to test:
1. check into current branch
2. do `npm install` and `npm test LoginPrivileges.test.js`

## Screenshots or videos of changes:
Screenshot 2024-06-30 at 1 20 52 AM

### CODE REVIEW

**Review by kdaga81 — APPROVED** [review]
image

All testcases passed successfully

**Review by Logeshwari-Renu — APPROVED** [review]
All the test cases have been passed.

**Comment by sahithidhulipala9** [comment]
All test cases passed successfully!
PR 2406

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by vijay10pk — APPROVED** [review]
All the test cases pass.

Screenshot 2024-07-03 at 12 31 17 PM

**Review by HowieMiao — APPROVED** [review]
All tests passed, looks good 

image

**Review by Rishitha1309 — APPROVED** [review]
All test cases passed
PR2406

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Review by jinxyou — APPROVED** [review]
All test cases have passed. Great work!
Screenshot 2024-07-06 175858

**Review by JatinAgrawal94 — APPROVED** [review]
All test cases passed.
Screenshot 2024-07-12 at 6 03 56 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
