### PR TITLE
EduardoV - create unit tests for the TeamMembersPopup component

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the TeamMembersPopup component to confirm whether it working as intended.

Screenshot_1

## Main changes explained:
- Export file TeamMembersPopup .jsx for the test component
- Create file TeamMembersPopup .test.js to do the unit tests

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install` to run this PR locally
4. open file src → tests → Teams → TeamMembersPopup .test.js
5. run `npm run test src/__tests__/Teams/TeamMembersPopup.test.js`

## Screenshots or videos of changes:
This is the result it's supposed to get:

Screenshot_2

If all tests passed, everything worked as intended.

### CODE REVIEW

**Comment by AnishPandita** [comment]
Hey I tested the PR and all the test cases passed and there was no error.
Screenshot 2023-09-13 at 5 13 47 PM

**Review by AnishPandita — APPROVED** [review]

**Review by vikrambadhan — DISMISSED** [review]
Hi, i tested your PR and it works as intended!

week3 - PR10

**Review by Haoj1 — APPROVED** [review]
@eduvarjaor All tests passed, good job!

**Review by DavidC0126 — DISMISSED** [review]
Hi @eduvarjaor I tested this PR and it works as described.

test1

**Review by robertoooc — APPROVED** [review]
Hi @eduvarjaor, I tested your new unit test implementation for the team members popup component and it passed all tests. The test itself looks well written as well. 
Screenshot 2023-09-13 at 6 40 58 PM

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Hey @eduvarjaor, good work! I just have a couple of suggestions. First with checking if the component is rendering without crashing, do we need to check if the "Add" button is rendering or could we just see if rendering the component returns null?

Secondly, you're testing if the "Add" button is rendering when the user has that permission but not testing to make sure the "Add" button is NOT rendering if the user doesn't have permission. Just to be more thorough I would add a test making sure the "Add" button doesn't render if this is the case.

I'd also like to add that we can test to make sure the team name is being displayed in the modal since it's being given within props.

Lastly, since the function that gets called with the "Delete" button seems to be in props, we can test to see if that function gets called when the "Delete" button is clicked.

Any objections to these suggestions?

Screenshot 2023-09-14 at 2 47 16 PM

**Review by yunshan111 — APPROVED** [review]
Reviewed the PR, and ran the tests. LGTM

image

**Review by Jiyuanxia — APPROVED** [review]
Hi @eduvarjaor , I have reviewed your pull request and tested it. It works as intended. Good job!

Screenshot 2023-09-14 215458

**Review by iTvX — APPROVED** [review]
I have tested your pr, it looks good,

CleanShot 2023-09-15 at 13 19 42@2x

**Comment by Sssky-18** [comment]
Tested this PR, and the test code works as expected. 
PR#1297

**Review by liaoyufu-leo — APPROVED** [review]
Hi @eduvarjaor, this change works well in my device, nice job.
image

**Review by Chuehleo — APPROVED** [review]
Everything works as intended, great job!
Screenshot 2023-09-15 231832

**Review by dah00 — APPROVED** [review]
Hey, I have tested your PR and all tests passed. 
PR1297

**Review by gabi-lima — APPROVED** [review]
Great job!
image

**Review by Bhagyashree444 — APPROVED** [review]
Works as expected. Great work!
PR#1297_VS_code
lobal/HighestGoodNetworkApp/assets/41186831/f9f1fb01-3358-41de-9c20-3d549d43c0d2)
bal/HighestGoodNetworkApp/assets/41186831/97b36d3a-c02f-4ada-83c4-3f01e5768078)

**Review by EdwinLauM — APPROVED** [review]
Hey @eduvarjaor! Works as expected and code changes look good!

Screen Shot 2023-09-16 at 8 29 37 PM

**Comment by beblicarl** [comment]
This passed

image

**Review by beblicarl — DISMISSED** [review]

**Review by Shiwani99 — DISMISSED** [review]
Hi,
I tested your PR. It works as intended.
Screenshot 2023-09-18 at 7 57 21 PM

**Comment by eduvarjaor** [comment]
> Hey @eduvarjaor, good work! I just have a couple of suggestions. First with checking if the component is rendering without crashing, do we need to check if the "Add" button is rendering or could we just see if rendering the component returns null?
> 
> Secondly, you're testing if the "Add" button is rendering when the user has that permission but not testing to make sure the "Add" button is NOT rendering if the user doesn't have permission. Just to be more thorough I would add a test making sure the "Add" button doesn't render if this is the case.
> 
> I'd also like to add that we can test to make sure the team name is being displayed in the modal since it's being given within props.
> 
> Lastly, since the function that gets called with the "Delete" button seems to be in props, we can test to see if that function gets called when the "Delete" button is clicked.
> 
> Any objections to these suggestions?
> 
> Screenshot 2023-09-14 at 2 47 16 PM

Hi Gary,

1) On "renders without crashing" we are testing if the button Add is in the document. If the component crashes or fails to render, the Add button will not be rendered, and this test can catch those issues.

2) That's a good point. I added it. Nice job.

3) Nice suggestion Gary. I added it.

Thanks for all the suggestions.

**Review by GaryB93 — APPROVED** [review]
Thanks for adding these tests @eduvarjaor! Great work!

**Review by sxiong5 — APPROVED** [review]
The test LGTM!

Screenshot 2023-09-21 at 12 57 30

**Comment by astrjc0326** [comment]
I tested the PR. It works! 
Screen Shot 2023-09-21 at 2 35 22 PM

**Review by harshidad — DISMISSED** [review]
All the test passed.
PR#1297

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this PR and it works after changed as shown in pic.
Screenshot 2023-09-22 at 7 50 06 PM

**Review by JeffLi117 — CHANGES_REQUESTED** [review]
Tests ran and all passed as expected.

image

One thing I noticed while reading the code for the tests 'displays "Add" button if user has "assignTeamToUsers" permission' and 'display "Delete" button if user has permission to delete members' - while both are testing to see if a button is rendered when the user has permissions, the former tests by using the syntax of `expect(addButton).toBeInTheDocument();` while the latter uses `expect(addButton).toBeNull;`. My experience in testing is limited but I was expecting the syntax of the tests to be similar since they're both testing for items to be in the document. 

The one using `toBeInTheDocument()`
image

The one using `toBeNull`
image

If I am wrong in this matter, please dismiss this review.

**Comment by eduvarjaor** [comment]
> Tests ran and all passed as expected.
> 
> image
> 
> One thing I noticed while reading the code for the tests 'displays "Add" button if user has "assignTeamToUsers" permission' and 'display "Delete" button if user has permission to delete members' - while both are testing to see if a button is rendered when the user has permissions, the former tests by using the syntax of `expect(addButton).toBeInTheDocument();` while the latter uses `expect(addButton).toBeNull;`. My experience in testing is limited but I was expecting the syntax of the tests to be similar since they're both testing for items to be in the document.
> 
> The one using `toBeInTheDocument()` image
> 
> The one using `toBeNull` image
> 
> If I am wrong in this matter, please dismiss this review.

Good point @JeffLi117, I fixed it now. Please, recheck to ensure that everything is fine.

Thanks for the feedback!

**Review by JeffLi117 — APPROVED** [review]
Your new changes look good! Thanks for the quick response and revision.

**Review by yangfan2001 — APPROVED** [review]
Hi, I have read your PR and all tests are passed 👍
image

**Pull request merged**
