### PR TITLE
Shihao - Team member sort function

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Screenshot 2023-08-18 at 13 52 18

## Related PRS:
This frontend PR is related to the [#474](https://github.com/OneCommunityGlobal/HGNRest/pull/474) backend PR.

## Main changes explained:
- Sort members by alphabet by default
- Create a column `Date Added`
- Create a way to sort members by date

## How to test:
1. check into current branch
2. do `npm install` and `npm start` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ Teams→ Members
5. check whether the member is sorted by alphabet
6. click the 'Date Added' to check if the user is sorted by both date and alphabet

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/72c9f985-a44b-419e-9d79-d474dbb73c44

### CODE REVIEW

**Review by winghojackyli — DISMISSED** [review]
Hi @sxiong5 , I've tested this frontend PR along with the backend PR #474. They work great together. 
Initial state: members are sorted alphbetically
Click date tab once: members are sorted in chronological order
Click twice: members are sorted in reverse chronological order
Click three times: members are sorted alphbetically


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/c61a253b-3183-48fc-948f-90b64450b87b

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works well on my device. @sxiong5

image

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-08-18 122226
Screenshot 2023-08-18 122201
Screenshot 2023-08-18 122246

**Review by navneeeth — APPROVED** [review]
LGTM!

The PR works as expected. Good implementation!
Tests:
Logged in as admin user, navigated to Dashboard->Other Links->Teams->Members and checked if the members are sorted alphabetically. Experimented with the 'Date Added' button to check if the user is sorted by both date and alphabet. Also checked by adding a new user and the PR works fine.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/8ab9847a-9bb3-4233-bb0e-af1859c1e4d2

**Review by iTvX — DISMISSED** [review]
I approved your pull request, everything looks good. Good job!
CleanShot 2023-08-18 at 12 38 43@2x

**Review by belagaam — APPROVED** [review]
Tested the pr as per the instructions. The team members' names are sorted in chronological order and the date can be sorted by clicking on the date added. Everything works as expected. Great work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/431f7897-2cf4-4824-aa01-cc002f49cd02

**Review by eduvarjaor — APPROVED** [review]
Everything is working as intended. Good job @sxiong5 !

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/26114c88-72db-4798-9bd8-baa6281f7f2f

**Review by veronicacheng2 — DISMISSED** [review]
Hi @sxiong5, I have tested the sorting function and everything works as intended. 

image

image

**Comment by KurtisIvey** [comment]
Well done! Functions perfectly. No errors on the backend either. 

descending:
pr1136 descending
alphabetical:
pr1136 alphabetical
ascending:
pr1136 ascending

**Review by TheDescendant39 — APPROVED** [review]
Hi @sxiong5, PR changes work as intended. Great Job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/a9e0d025-e4aa-4e56-8bf9-16f9e4faa6c3

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @sxiong5. I have tested your PR and everything is working as intended. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/232e3fb8-a8ac-4565-8a5a-eef1592507cb

**Review by luisarevalo21 — APPROVED** [review]
Hello @sxiong5 

I tested your PR and works as intended great job!

Following your steps, I logged in as an owner, viewed the teams and I am able to toggle the order. 
Clicking the date once, members are sorted by date. 
Clicking the date again sorts the members in reverse order. 
Clicking once more the members are sorted by their names. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/5099b4ce-fc8c-4676-9db1-177df124df16


I then tested for an admin and works as intended too. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/b3244e42-e2b8-4d16-97bf-45b6c44d98dd

**Review by yunshan111 — DISMISSED** [review]
LGTM, tested both frontend and backend.

**Review by harshidad — COMMENTED** [review]
Somehow for all records, I can see "Date added" as current date. 
Can you pls let me know If I follow different steps here. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/5f28feda-251d-46f4-80cd-c3b81daf4ded

**Review by yaow62023 — DISMISSED** [review]
I have test your PR, all the features works as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/e3eeb4ab-fea7-48da-8083-a5fdf23939d3

**Review by ss23046 — APPROVED** [review]
Hi @sxiong5 ,
Tested the PR, works as intended. Good implementation!

Logged in as an admin, navigated to Other Links-->Teams-->Members
1. Members are sorted alphbetically, initially
2. Members are sorted in chronological order after clicking the date tab once
3. Members are sorted in reverse chronological order after clicking the date tab twice: 
4. Members are sorted alphbetically after clicking again

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99052235/f8ace29e-bc20-4391-8d5f-80c307e5f7d2

**Review by n0vay — APPROVED** [review]
Good Job! working as intended.
image

**Review by EdwinLauM — APPROVED** [review]
Hey @sxiong5! Code changes work as expected! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/0fb0bfc9-a507-434f-829d-211f0e7e2455

**Review by arcan9 — APPROVED** [review]
Checked out the PR and tested. Functionality is added. Nice job!

Screenshot 2023-08-19 at 10 49 26 PM

**Comment by one-community** [comment]
Thank you all! Fix the merge conflicts and I'll merge this.

**Review by tsunami776 — APPROVED** [review]
The sorting feature functions seamlessly. Clicking on the sort button effectively cycles through alphabetical, descending, and ascending orders. Excellent implementation!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/04767355-92d9-45a6-8095-c48bd46096e7

**Review by winghojackyli — APPROVED** [review]
Hi @sxiong5 , I've tested the PR and it works as intended after merging development branch into this branch. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/f100835a-7898-4dc9-8a09-5c8e2b66f1af

**Review by Haoj1 — APPROVED** [review]

**Review by Haoj1 — APPROVED** [review]
Hi @sxiong5, The new date column and sort by date and alphabet work successfully!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/d2bd977f-825a-4c9d-952d-686114abe17d

**Pull request merged**
