### PR TITLE
Timezone API UI fix-updating timezone state when using GetTimeZone button, minor linter changes

### PR DESCRIPTION
**Pull request by rutvij2811**
Issue: Updating the profile with the new timezone is not reflected in the UI or the database.

Root cause: Not updating the state value of TimeZone, when the "Get Time Zone" button is clicked. Hence it stored only the default value at the backend.

Fix: Whenever the button "Get Time Zone" is clicked, it should change the state for "timezone" also along with the "timezoneFilter" (Part of the dropdown component).

saveTImeZoneFixUI

### CODE REVIEW

**Comment by Programmingrelated1999** [comment]
It looks good.

**Comment by Programmingrelated1999** [comment]
My Bad. I could not get the result from the snip video on my computer. I am not sure if this is the problem with the API. 
PR_review

**Comment by rutvij2811** [comment]
You will have to add the timezone api key in the local env first before it works.

**Comment by Programmingrelated1999** [comment]
Got it working! Everything looks good. I will go ahead and approve it.

**Review by Programmingrelated1999 — APPROVED** [review]
Everything looks good. I was able to update the time zone based on location.

**Comment by one-community** [comment]
Get Timezone button is no longer working for me on the Dev after merging this PR.

**Pull request merged**
