### PR TITLE
Shiwani UserPermissionsPopup unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for src/components/PermissionsManagement/UserPermissionsPopUp.jsx

## Main changes explained:
- Added 7 test cases to UserPermissionsPopup.test.js: check if user name is present, check if input box displays only the active users, check if permissions is present, check if submit button works as expected when the button is clicked, check if toast message gets displayed when the button is not clicked, check if toast error message gets displayed when the button is clicked, check if Reset to Default button works as expected.
- Added data-testid in PermissionListItem.jsx to check for a specific permission in Reset to Default button test case.

## How to test:
1. check into current branch
2. do `npm test src/components/PermissionsManagement/__tests__/UserPermissionsPopup.test.js` 
3. check if the test cases pass without any errors or warnings

## Screenshots or videos of changes:
Screenshot 2024-03-11 at 7 51 14 PM

## Note:
- console.log of error message called 'server error' is not a warning or error

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and it passed all the test cases. All the related components are rendered without any errors. Please refer the screenshot attached.

PR 2048

**Comment by dhairya-mehta** [comment]
Hey, I tested the cases , 1 of them failed
image

**Comment by Shiwani99** [comment]
> Hey, I tested the cases , 1 of them failed image

Hi,
Thank you for your review. I have made changes to the test case that is failing. Can you please check again to see if the test cases are passing now?

**Review by 20chen-7 — DISMISSED** [review]
I have run the command you provided, every tests passed and the unit test code looks clear and good.
Screenshot 2024-03-13 at 10 34 24 PM

**Review by Nahiyan-16 — CHANGES_REQUESTED** [review]
Great work on the tests in this PR! The test suite is thorough and well-structured.

I did however notice multiple occurrences of `await waitFor(() => {});` without a specific condition or assertion inside the callback. 

Could you provide some clarification on why there are multiple instances of this?

Also the `act` and `wait` here `import { render, screen, fireEvent, waitFor, act, wait } from '@testing-library/react';` are unused imports.

Overall, great work on these tests!
Screenshot 2024-03-13 144923

**Review by Pandani07 — DISMISSED** [review]
All the test cases passed!
Screenshot 2024-03-13 at 9 22 02 PM

**Review by Abi-Liu — DISMISSED** [review]
Looks good! All tests are passing.

Screenshot 2024-03-19 at 9 39 17 PM

**Comment by Shiwani99** [comment]
> Great work on the tests in this PR! The test suite is thorough and well-structured.
> 
> I did however notice multiple occurrences of `await waitFor(() => {});` without a specific condition or assertion inside the callback.
> 
> Could you provide some clarification on why there are multiple instances of this?
> 
> Also the `act` and `wait` here `import { render, screen, fireEvent, waitFor, act, wait } from '@testing-library/react';` are unused imports.
> 
> Overall, great work on these tests! Screenshot 2024-03-13 144923

Thank you for your review. There are 2 test cases where I have done this, so in the sixth test case 'check if toast message gets displayed when the button is not clicked' I should have added the assertion inside await waitFor which I didn't notice and I will do the change for this test case. For the last test case, 'check if reset to default button works as expected' I didn't add any assertions because there were multiple state updates taking place. State updates take place after clicking on the user name, after clicking on add permission button, after clicking on reset to default button, and also, since the test case wasn't checking for anything related to add or delete permission since it belonged to another component I didn't add any assertions for this and just left it empty so that the asynchronous updates would take place for testing further on reset to default button. I have made the necessary changes now. Thank you for notifying about this.

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 30 - PR4

**Comment by aaryaneil** [comment]
Looks good and passed all the tests.
Screenshot 2024-03-29 at 2 26 44 PM

**Review by aaryaneil — DISMISSED** [review]
All test cases passed, looks good to me.
Screenshot 2024-03-29 at 6 59 54 PM

**Review by iven-yao — DISMISSED** [review]
I just tested this pull request, and unit test passed all the cases as expected. 
image

**Review by scoopstroop92 — DISMISSED** [review]
Good job on the test cases shiwani 
image

**Review by Nahiyan-16 — DISMISSED** [review]
Great job!

**Review by bhuvaneswarignanasekar — DISMISSED** [review]
I have reviewed your PR. All test cases passed.

Screenshot 2024-04-09 at 8 27 19 PM

**Review by yvonnep165 — DISMISSED** [review]
Hi @Shiwani99 I checked all the test cases and ran the tests. All tests passed. Nice work! Please refer to the screenshot below:
Screenshot 2024-04-26 at 4 52 30 PM

**Review by KurtisIvey — DISMISSED** [review]
Test coverage is great and also handles networking request testing as well. Fantastic job as usual. No complaints from me at all on this test file.

once the merge conflict is resolved, please request a re-review from me, so we can move forward with merging this

image

**Review by KurtisIvey — APPROVED** [review]
Everything is still good to go. Fantastic job and thanks for clearing up the merge conflict. 

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
