### PR TITLE
Yiyun add one more tab for weekly summaries

### PR DESCRIPTION
**Pull request by EvianTan**
# Description
image
This PR is for URGENT bug #1 
This PR is **ONLY** for adding one more tab on weekly summaries dashboard, to show the weekly summary of "three weeks ago".
**This PR doesn't have any contribution on fixing the "total submitted".** 

## Related PRS (if any):
#622 Alan worked on this before but didn't get it completed. I'm going to close it since I'll raise new ones.

## Mainly changes explained:
`src/components/WeeklySummary/WeeklySummary.jsx`: update the UI and properties to make the weekly summaries dashboard show 4 tabs instead of 3, add `dueDateThreeWeeksAgo`, `summaryThreeWeeksAgo`, etc.
`src/components/WeeklySummary/WeeklySummary.test.jsx`: update test suites to pass the `run npm test` command.

## How to test:
check into current branch
do `npm install` and `...` to run this PR locally
log as any role user or a new created user
go to dashboard→ weekly summaries
verify adding summaries on the 4 tabs can work

## Screenshots or videos of changes:
image

## Note:
1. I made some changes on the Dev database for testing this PR
Before my change, weeklySummaries in Dev database somehow showed the three dates identical, both of them are the current week's due date. This [link](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/622#issuecomment-1383054737) shows how the identical due dates problem found.
I used below commands to update the due dates to be correct. **Since the due dates in our Beta database are correct, I didn't make any changes there.**
image

2. From the below discussion, we decide to improve the current logic of counting "total submitted", I'll try to fix this part next week, in my next PR.
image

### CODE REVIEW

**Comment by crystalsong2021** [comment]
@EvianTan I tested and confirmed the additonal tab on weekly summaries. Nicely done!
Untitled design (2)

**Comment by johny4437** [comment]
HI @EvianTan I tested the PR, I have one questions and one  observation. 
1 -Will a "three weeks ago" tab be added to the Weekly Summary Report page in the future?
Captura de Tela (256)

2 - I am getting an error in  the console. Can this be fixed?
Captura de Tela (255)

**Review by crystalsong2021 — APPROVED** [review]
Thank you for working hard on this PR with adding tab to the  weekly summaries.

**Comment by mpavithr** [comment]
Hi, I tested the PR and I do see the additional tab. However, if I add a paragraph to the three weeks ago summary and click save, I'm not able to click anything again on the page until I refresh the page.

pr707_2

**Comment by crystalsong2021** [comment]
> HI @EvianTan I tested the PR, I have one questions and one observation. 1 -Will a "three weeks ago" tab be added to the Weekly Summary Report page in the future? Captura de Tela (256)
> 
> 2 - I am getting an error in the console. Can this be fixed? Captura de Tela (255)

I am also getting the error in the console.

**Review by Lucas-E — COMMENTED** [review]
I hope this message finds you well. I wanted to inform you that I have tested your Pull Request and found the code to be working very well. However, I did encounter an error in the console after submitting. Nevertheless, 
Captura de tela de 2023-03-11 12-50-48
excellent job!

**Review by kangjay88 — APPROVED** [review]
Hi @EvianTan, I have tested this PR and the '3 Weeks Ago Summary' does save and show. However, I am also not able to click anything else after submitting. This is also the case when I created a summary for 'last week's summary' and 2 weeks ago summary, unless I reload the page - maybe in a separate PR, code should implement a reload after saving? 

https://user-images.githubusercontent.com/108297706/224502537-14b327c3-b0b7-40f8-b2cd-38b176220f3a.mp4

**Comment by nicollext** [comment]
Hey @EvianTan! I tested and it is working as expected. I also was not able to click the page after submitting the summary, but I tested the development branch and the error and the click behavior were already present. Maybe we could open a PR to solve this problem. 

**Before**  

https://user-images.githubusercontent.com/101591708/224517111-ea377866-8a05-4f80-8f2c-4271ff45b14d.MP4


**After**

https://user-images.githubusercontent.com/101591708/224517116-45b499fc-48b0-4028-a87c-09fe461414e9.MP4

**Comment by vitorsaa2k** [comment]
The new tab is appearing and working normally but im getting the same arror as everyone else.

image

**Comment by NyahJ** [comment]
Hi @EvianTan,
Thanks for your hard work on this PR, I have tested your change, there are four tabs: shows the summaries from current week to last 3 weeks. However, the names were incorrect, shown like the following image, could you pls take a look at this?

截屏2023-03-17 下午3 35 05

**Pull request merged**
