### PR TITLE
Tim - Add badge summary modal to People Reports page

### PR DESCRIPTION
**Pull request by tdkent**
# Description

This PR integrates a non-editable badge summary modal into the People Reports page. The modal is activated with a **Show Badges** button that is grouped with the other buttons on the People Reports page.

pr-badgesummary-1
pr-badgesummary-2

## Related PRS (if any):
N/A

## Main changes explained:
- Adds a **Show Badges** button next to the current buttons
- Clicking the **Show Badges** button activates a static version of the **Badge Summary** modal found in **View Profile > Featured Badges > Select Featured**
- Editable fields and PDF options have been removed
- Adds a **Close** button to the modal
- Styling added/updated for desktop and tablet versions of the modal
- Adds new files to FE codebase: **BadgeSummaryVIz.jsx** and **BadgeSummaryViz.css**

## How to test:
1. `git checkout Tim_impl_badge_summary_on_peoples_report` to check into current branch
2. run `npm install` to ensure your modules are up to date (no new modules are added in this PR) 
3. `npm run start:local` to run this PR locally
4. log in as an admin user
5. go to **Reports → Reports → People Reports → Choose Person**
6. Select different users to test the modal with varying badge counts. To test a user with many badges use "Tim Volunteer". To test a user with zero badges use "Tim Mentor". Note also that as an admin you can assign new badges to users.
7. Test desktop ( > 1024 px) and tablet (<= 1024px) modal styling.
8. Verify the **Badge Summary** button and modal are working as intended

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/273cc258-0ce3-4ad4-91db-e3181b5c59cb

## Notes/Known Issues:
- Only Admin and Owner accounts should be able access the People Reports section of the app.
- There is a slight shift in the background screen when the modal is activated. This is also noticeable when activated the user profile version of the modal.
- There are various key prop and html errors on the People Reports page that are unrelated to this PR.
- Due to existing styling of the People Reports buttons, the **Show Badges** button wraps to a new line at width <= 787 px.

### CODE REVIEW

**Review by sxiong5 — APPROVED** [review]
Hi @tdkent, I've gone ahead and tested the PR and everything seems to be working as expected. The button and modal both functioned properly across various screen sizes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/ce5df7e3-eea5-4504-841f-5914a753f4ea

# Needs to optimize
The styling may not related to this PR. The background of this page is not complete; consider adjusting the CSS.

Screenshot 2023-08-07 at 14 11 26 (2)

**Review by winghojackyli — APPROVED** [review]
The modal works as intended in desktop ( > 1024 px) and tablet (<= 1024px). 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/13569790-2a46-49c6-9701-f3d91e8746fd

**Review by TheDescendant39 — COMMENTED** [review]
Hi @tdkent, I tested your changes and they work well. Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/311bd382-f9a8-41ea-a577-0309df0f98d1

**Note:** Just a suggestion, do you think that it will be better to show a message like "No badges to show" instead of showing an empty modal? I think showing an empty modal would confuse users about whether the badges loading or there are no badges at all.

**Comment by jerryren527** [comment]
Everything works as intended, great job!

**Comment by AnishPandita** [comment]
Hi @tdkent I was able to replicate the results of the PR. Works as intended.
Screenshot 2023-08-07 at 5 15 55 PM
Screenshot 2023-08-07 at 5 16 59 PM

**Comment by robertoooc** [comment]
Hi @tdkent, I tested your changes and overall the functionality works as intended. 

- I did notice that the Dates dropdown doesn't show for any media sizes under 1025px. BadgeSummaryIpadSize

- Another thing I noticed is that sometimes you can't scroll down and see all the dates within the Dates dropdown select. 
- The video I provide shows that I am not able to scroll all the way, the select option seems to lock at a certain point when there are many dates for the given badge.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/971211f4-c6d5-484f-8e13-201c6c07035c

**Comment by robertoooc** [comment]
> # Description
> This PR integrates a non-editable badge summary modal into the People Reports page. The modal is activated with a **Show Badges** button that is grouped with the other buttons on the People Reports page.
> 
> pr-badgesummary-1 pr-badgesummary-2
> ## Related PRS (if any):
> N/A
> 
> ## Main changes explained:
> * Adds a **Show Badges** button next to the current buttons
> * Clicking the **Show Badges** button activates a static version of the **Badge Summary** modal found in **View Profile > Featured Badges > Select Featured**
> * Editable fields and PDF options have been removed
> * Adds a **Close** button to the modal
> * Styling added/updated for desktop and tablet versions of the modal
> * Adds new files to FE codebase: **BadgeSummaryVIz.jsx** and **BadgeSummaryViz.css**
> 
> ## How to test:
> 1. `git checkout Tim_impl_badge_summary_on_peoples_report` to check into current branch
> 2. run `npm install` to ensure your modules are up to date (no new modules are added in this PR)
> 3. `npm run start:local` to run this PR locally
> 4. log in as an admin user
> 5. go to **Reports → Reports → People Reports → Choose Person**
> 6. Select different users to test the modal with varying badge counts. To test a user with many badges use "Tim Volunteer". To test a user with zero badges use "Tim Mentor". Note also that as an admin you can assign new badges to users.
> 7. Test desktop ( > 1024 px) and tablet (<= 1024px) modal styling.
> 8. Verify the **Badge Summary** button and modal are working as intended
> 
> ## Screenshots or videos of changes:
>  tim-badgesummary-pr.mov 
> ## Notes/Known Issues:
> * Only Admin and Owner accounts should be able access the People Reports section of the app.
> * There is a slight shift in the background screen when the modal is activated. This is also noticeable when activated the user profile version of the modal.
> * There are various key prop and html errors on the People Reports page that are unrelated to this PR.
> * Due to existing styling of the People Reports buttons, the **Show Badges** button wraps to a new line at width <= 787 px.

**Review by luisarevalo21 — APPROVED** [review]
Hello @tdkent 
I tested your PR and works intended great job!
The modal adapts to different size screens. For larger screens and smaller ones.

I enjoyed your level of detail which made it much easier to test your PR.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/818688ea-c706-452e-b32e-22dd5273e5f6

Screenshot 2023-08-07 at 8 40 21 PM
Screenshot 2023-08-07 at 8 40 32 PM

**Review by yurisokolovicz — APPROVED** [review]
Hi @tdkent 
I have tested the new modal on the report page for badge summary. It works as intended. The responsiveness of the modal is fine in my opinion. Please check the video below for Owner and Admin accounts for different users. Good job!


Owner Account:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/60bf11dc-82c0-4927-941a-4eb19a363dce

Admin Account and responsivity testing:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/b890a8f8-649e-4813-ac14-1f9268bf9c93

**Comment by tdkent** [comment]
> Hi @tdkent, I tested your changes and they work well. Good Job!
> 
>  Screen.Recording.2023-08-07.at.3.07.25.PM.mov 
> **Note:** Just a suggestion, do you think that it will be better to show a message like "No badges to show" instead of showing an empty modal? I think showing an empty modal would confuse users about whether the badges loading or there are no badges at all.

Good suggestion! I agree that would be a nice addition, however since the current Show Badges modal on the User Profile page does not have that I did not add it here.

**Comment by tdkent** [comment]
> Hi @tdkent, I tested your changes and overall the functionality works as intended.
> 
> * I did notice that the Dates dropdown doesn't show for any media sizes under 1025px. 
> * Another thing I noticed is that sometimes you can't scroll down and see all the dates within the Dates dropdown select.
> * The video I provide shows that I am not able to scroll all the way, the select option seems to lock at a certain point when there are many dates for the given badge.

Great catches on the Dates select. Note that the User Profile version of the Badges Summary modal also removes the option to view Earned Dates at tablet size, so I did not add it here. The other issue you point out is certainly an edge case applying to both versions the modal, probably worth fixing at some point.

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great! Good work

[Uploading screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.08.08-18_51_18.webm…]()

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great as well

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.08.08-18_51_18.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/7ec6eb25-722a-488b-bcc7-1d53cc2ea767)

**Review by beblicarl — APPROVED** [review]

**Comment by Lin1404** [comment]
Hi @tdkent , I tested your changes with my account and it works prefect.
image

I have also tested your account, and it display the same as our expected.
image

**Review by Lin1404 — APPROVED** [review]

**Review by yunshan111 — APPROVED** [review]
The badge summary works as intended. LGTM.

image

**Comment by one-community** [comment]
Excellent! I see Carl reviewed this already and he's on the PR Review Leadership team, so merging it. Great work everyone!

**Pull request merged**
