### PR TITLE
Shrey unit test cases for Dropdown component

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for Dropdown component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test Dropdown.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-10-30 at 11 33 40 PM

The screenshot below shows the coverage report for Dropdown.jsx

Screenshot 2023-10-30 at 2 54 29 AM

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed. Great work

image

**Review by beblicarl — APPROVED** [review]

**Review by wantingxu7 — APPROVED** [review]
All tests passed. Great work!

**Review by navneeeth — APPROVED** [review]
Hello, @Shreyj14! All the tests are passing. Great work!
unit_tests_passed

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I run the `npm test Dropdown.test.jsx` and all the test cases are passed. Great work!

Screenshot 2023-10-31 at 4 27 05 PM

**Review by vikrambadhan — APPROVED** [review]
All the test cases ! Great Job!

week 10 - PR2

**Review by tsunami776 — APPROVED** [review]
Hi @Shreyj14, your unit test makes sense and covers the aspects I can think of. I ran the  unit test locally and all tests passed. Great work!
CleanShot 2023-10-31 at 20 22 16

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great job! 

Screenshot 2023-10-31 at 11 47 55 PM

**Review by DavidC0126 — APPROVED** [review]
Hi @Shreyj14 I tested the PR and it works as intended.

Screenshot 2023-10-31 at 10 26 19 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
