### PR TITLE
Jacob - Fix the project members search issue

### PR DESCRIPTION
**Pull request by DragonSlayer2401**
image

## Related PRS (if any):
N/A
…

## Main changes explained:
- Fix filtering in projectMembers.js
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as Owner user
5. go to Dashboard → Other Links → Projects
6. verify you can create a new project
7. verify you can search for members and the results don't disappear
8. verify you can add members

## Screenshots or videos of changes:
Before:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/44338759-dd28-4ce8-9591-5c263332b196

After:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/46568d01-15af-490d-a908-8a3f49aac83e

## Note:
The filtering is very inefficient and will be optimized in a separate pull request. Please be patient during your review.

### CODE REVIEW

**Review by Sophie-lei — COMMENTED** [review]
Hey, I tested this PR as an owner role. it can add new projects successfully. and I tried to add a number by search. The search function is actually working, just takes an extremely long time., which I think it shouldn't be.  The suggestion would be a more effective way to search the user. Looks like the search member result it is not trigger by user input but something else.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/d78fb0f9-f7b9-4c94-a14d-4373425dc803

**Comment by galgalinidhi** [comment]
Hi @DragonSlayer2401 , I tested the PR and I'm able to create a new project and add members to it. However, I see that the search results disappear after a while. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/271b797e-20c3-48e3-829a-82044d2be532

**Review by Nahiyan-16 — APPROVED** [review]
## Working
Hi Jacob, I tested your PR by creating a new project and searching up a name and pressing `Enter`. Previously, the results would disappear but in this patch, you have fixed that problem. Also, this search bar needs to be optimized but I believe that you mentioned in your video that you'll work on that on another PR. Below I have a before and after video:

Before (Development as of 2/3/24):
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/a67a3944-b2e9-4c56-a69a-83c1ad9783bc

After: 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/2f44a124-add5-45fc-8da6-599eb531bf57

**Comment by DragonSlayer2401** [comment]
> Hey, I tested this PR as an owner role. it can add new projects successfully. and I tried to add a number by search. The search function is actually working, just takes an extremely long time., which I think it shouldn't be. The suggestion would be a more effective way to search the user. Looks like the search member result it is not trigger by user input but something else.
> 
>  screen-recording-2024-02-03-at-150101_JUjcwvml.mov

So I did mention this in the notes of the PR but the optimizations will be in a separate PR. This is because the inefficiencies are somewhat related to the logic that existed before making this PR. It is because after every new character entered it fetches an array of all users from the database and then has to filter through every single one. In a separate PR I will be changing this logic to use backend querying and debounce the search on the frontend to limit the number of requests.

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Jacob,

I've tested the PR with owner user. All functionalities are working well. It's capable of adding new projects successfully. Additionally, when attempting to add a number through search, the search functionality is operational but experiences significant delays. Please refer to the video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/2024565b-68be-4c50-9d4f-2e622fb464e4

**Comment by DragonSlayer2401** [comment]
> Hi Jacob,
> 
> 
> 
> I've tested the PR with owner user. All functionalities are working well. It's capable of adding new projects successfully. Additionally, when attempting to add a number through search, the search functionality is operational but experiences significant delays. Please refer to the video. 
> 
> 
> 
> https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/2024565b-68be-4c50-9d4f-2e622fb464e4
> 
> 
> 
> 

I'm addressing performance issues in a separate PR, as mentioned in the notes of this PR. Since the objective of this PR was to fix the members disappearing. The performance issues are due to the frontend filtering, which existed before. It's just that new additions may have made it worse, which is, again, why it's being addressed in a different PR.

**Review by Pandani07 — APPROVED** [review]
Tested this PR and the functionality works as expected. Apart from the search being delayed (which you have said you will fix), no issues at all. I could create projects, add members to it and everything is saved. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/93dfccc2-880e-4bbb-a772-de2b9ba54aa6

**Review by ClemarNunes — COMMENTED** [review]
.

**Pull request closed without merging**
