### PR TITLE
Shrey unit test cases Modal file

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for Modal component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test Modal.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-11-06 at 8 01 23 PM

Screenshot 2023-11-06 at 8 01 31 PM

## Note
The console.log message is the expected behavior as that is part of the actual code.

### CODE REVIEW

**Review by luisarevalo21 — APPROVED** [review]
Hello @Shreyj14,
I tested your PR and works as intended. Great work! 
Running the test suite, shows all tests pass. 
console.log appears but is as expected.

**Review by malikjahanzaib — APPROVED** [review]
Hi @Shreyj14, all unit tests passing. Nice job!!!

Screenshot:

image

**Review by wantingxu7 — APPROVED** [review]
I ran the test and got "PASS". Good work!

**Review by Shuhua-L — APPROVED** [review]
I've successfully tested the PR. Tests are passing with flying colors. There are no errors specific to this PR, other than the expected console.logs. 

Great job with the test implementation!

PR1501

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great Work! 

Screenshot 2023-11-08 at 12 53 15 AM

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!

Screenshot 2023-11-08 at 4 50 30 PM

**Review by sxiong5 — APPROVED** [review]
Hey @Shreyj14, all the tests are passed, nice work!

Screenshot 2023-11-09 at 13 32 46

**Review by pika-chu11 — APPROVED** [review]
Hi @Shreyj14 , I have ran your test and it passed on my end! Good job!
PR 1501

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!!

Week 11 - PR2

Week 11 - PR2 (2)

**Review by Shubhu0 — CHANGES_REQUESTED** [review]
Hi @Shreyj14 I tested your PR and faced the following error

image

**Comment by beblicarl** [comment]
All tests passed. Great work

image

**Comment by wanglu1207** [comment]
Shrey_UnitTest_Modal
Hi @Shreyj14, I tested you PR. It works great! Good job!

**Review by Iris-Song — APPROVED** [review]
Hi I have tested your PR, it works as intended. Good job!
Screenshot 2023-11-10 at 21 54 36

**Comment by palakgosalia** [comment]
Hey, I have reviewed and tested your PR. All the test cases passed. Thank you

image

**Comment by kavya151** [comment]
Hi @Shreyj14 I have reviewed your PR. All the test cases passes. Good job!
PR 1501

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR and everything works as expected. All tests passed!
Screenshot 2023-11-11 at 10 39 09 PM

**Review by DavidC0126 — APPROVED** [review]
I tested the PR and it works as intended.
Screenshot 2023-11-12 at 10 58 56 PM

**Comment by beblicarl** [comment]
All tests passed. Great work

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
