### PR TITLE
added and removed margin from some component to fix the style

### PR DESCRIPTION
**Pull request by papiasharmin**
This PR is related to PR #809
  On previous PR, the header height was fixed so that there are no overlapping  and a gap between the header and the component below it. but some component do not require the gap on original design, so in this PR the styling is changed accordingly.
Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/4f3de264-8d72-44ad-8fc7-26c03d03d26a

after:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/b0374768-884f-45de-9d06-3ca840a0fcfb

How to test:
 1.  checkout to this branch
 2.  npm run start:local
 3.  sign in to any account preferably admin, and the pages should look like as shown in after video. also check the responsiveness.

### CODE REVIEW

**Review by eduhorta — APPROVED** [review]
Hi papia!

I could not replicate the overlap as posted on the video "before". But that was related to  PR #809, right?

For PR #829 the margin of some components were changed and nothing was overlapping.
Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/86563840-dc0d-4992-a80d-8660ab972a76

**Comment by papiasharmin** [comment]
The overlapping was there before PR #809. I have accidentally changed some original style at PR #809, so this PR is overall style change. Thank you.

**Review by EdwinLauM — APPROVED** [review]
Looks good. Works as intended! Good job!

Before:
PR #829 Before

After:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/225ffe2c-3012-4cfb-8eb4-a86c2cfe9159

**Comment by wang9hu** [comment]
I tested your branch and it worked as intended. 
Before:
Screenshot 2023-05-16 231751
After:
Screenshot 2023-05-16 230658

**Review by yoyoweiii — APPROVED** [review]
Works as intended, @papiasharmin , good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60588210/c6382ad5-a33d-4540-bb19-fb64443703ee

**Review by GKD890 — APPROVED** [review]
Hi, I also didn't experience the overlap in the `development` branch, but seems the margins were added to each component other than the `navbar`. Overall works no problem to me.

Frontend_PR#829

**Review by abdel-lall — APPROVED** [review]
Works as intended. Good job!
PR829

**Review by NidaZaki — APPROVED** [review]
**Before:**
Before

**After:**
After

Tested this branch out, changes look good to me.

**Review by yufeiStella — APPROVED** [review]
Works good for me.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/2e779609-531a-4b59-8e7f-2e4799fe27a3

**Comment by one-community** [comment]
Thank you all! Merging...

**Review by lchua2314 — APPROVED** [review]
Hi, papia. I couldn't replicate the bug, but I noticed this gap has been closed. Everything works as intended.

Before:
Before

After:
After

**Pull request merged**
