### PR TITLE
Yi fix minor formatting and styling issues

### PR DESCRIPTION
**Pull request by yi-lin-1234**
# Description
Screenshot 2023-11-18 at 3 26 57 AM

https://www.loom.com/share/3eb48d69e36249ef945a709197713ced?sid=1571d129-fd39-4c72-a5cb-ad870b7bbc7d

## Related PRS (if any):
none

## Main changes explained:
- Change the information tooltip position to the center of the page.
- Align certain items to be on the same line at the top of the page, correcting a bump-down issue.
- In individual profiles, fix a spacing issue to ensure uniformity.
- Adjust the spacing so each element has the same amount of space.
- Make phone input width 100% so they match other input length.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. verify information tooltip on center
5. verify information tooltip, active icon, and use icon on same line
6. verify information tooltip on user profile page spacing fixed
7. verify phone input on user profile page have same width as other input

## Note:
Before change:
https://www.loom.com/share/3eb48d69e36249ef945a709197713ced?sid=1571d129-fd39-4c72-a5cb-ad870b7bbc7d
After change:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/ad000f8f-2291-462c-b727-66cf742d957a

### CODE REVIEW

**Comment by ptrpengdev** [comment]
Hi @yi-lin-1234 , I checked out your code and tested the functionalities; everything works as expected. However, please pull the latest code from the development branch with `git pull origin development` before merging.

**Review by Hemsharavanan — APPROVED** [review]
- The position of the information icon is adjusted, now centered on the dashboard.
- Furthermore, the information, green circle, and person icons aligned on a single line next to "Task and Timelogs."
- Additionally, adequate spacing is provided for the information, green circle, and clock icons on the user profile page. Similar spacing adjustments are made for the information icon adjacent to "Featured Badges" and "You have no badges."
- Furthermore, the Basic Information form fields are now appropriately aligned, catering to both enlarged and resized screens.
Refer below screenshots.
PR #1561 Yi fix minor formatting and styling issues ss1
PR #1561 Yi fix minor formatting and styling issues ss2
PR #1561 Yi fix minor formatting and styling issues ss3
PR #1561 Yi fix minor formatting and styling issues ss4

**Comment by kavya151** [comment]
Hi @yi-lin-1234 , I have run this PR locally and everything is as expected. Good job!!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/fa917d6d-e74c-4749-be92-0a8f293b3e35

**Review by lichanghaogit — APPROVED** [review]
Hi @yi-lin-1234 
I tested this PR on my local environment and all the function work as expected. Nice work!

information tooltip on center
Screenshot 2023-11-22 at 10 41 34 AM
information tooltip, active icon, and use icon on same line
Screenshot 2023-11-22 at 10 42 03 AM

phone input on user profile page
Screenshot 2023-11-22 at 10 42 26 AM

**Review by Alforoan — CHANGES_REQUESTED** [review]
On profile page, the items don't seem to be perfectly aligned.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/f44a17c0-0caf-471f-b7fc-6615076d6553

**Review by swathyjayaseelan — COMMENTED** [review]
All changes look good except the icons here are spaced properly but not vertically aligned.
 
Screenshot 2024-02-17 at 11 03 36 AM

**Pull request merged**
