### PR TITLE
akshit_improve_loading_resources_list

### PR DESCRIPTION
**Pull request by akshit0211**
# Description
Screenshot 2024-06-28 at 9 27 20 PM

## Related PRS (if any):
This frontend PR is related to the development backend.

## Main changes explained:
Made changes in these files to improve resource loading:
- src/components/Projects/WBS/WBSDetail/components/TagsSearch.jsx
- src/components/Projects/WBS/WBSDetail/components/TagsSearch.css

## How to test:
1. Check into the current branch.
2. Do `npm install` and `...` to run this PR locally.
3. Clear site data/cache.
4. Login as an Owner user.
5. Go to Other Links→Projects→select WBS-click on the name of a WBS→Add Task→Click on resources field.
6. Verify that you can view and add team members and that the list updates immediately without needing to refresh the browser.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/dcc2d221-5d80-4a10-80a9-704e275426c4

### CODE REVIEW

**Review by kdaga81 — CHANGES_REQUESTED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/086b8c6a-ddd2-4142-993d-71a57c2bab8c

When we type a resource and click outside the text field, it shows the entire list instead of just the filtered list based on the input provided. Is this the expected behavior, or does it need to be fixed?
I'll approve if this is the ideal behavior.

**Comment by akshit0211** [comment]
> Screen.Recording.2024-06-28.at.11.33.29.PM.mov 
> When we type a resource and click outside the text field, it shows the entire list instead of just the filtered list based on the input provided. Is this the expected behavior, or does it need to be fixed? I'll approve if this is the ideal behavior.

@kdaga81 thanks for reviewing this. I have fixed the issue. Please review it again.

**Review by jinxyou — APPROVED** [review]
I tested that resources field are able to add by clicking the dropdown list item and no refreshing needed. Also, the filter and search function works well. It's a bit bizarre to be based on searching for any existing letters instead of first letters. Still, great work!
Screenshot 2024-06-29 194237
Screenshot 2024-06-29 194245

**Review by aaryaneil — APPROVED** [review]
The changes work as expected and the list updates without needing to refresh the browser.
Screenshot 2024-06-30 at 12 40 39 AM

**Review by sahithidhulipala9 — APPROVED** [review]
Working as expected. List is automatically updating without even refreshing!
Screenshot (101)

**Review by KaushikMreddy — APPROVED** [review]
Hi Akshit,

Your changes are working as expected. I tested this in the development branch to understand the bug and tested your changes after that.

Case 1: Without typing anything, if I click in the resources box, all names pop up

image

Case 2: If I type a few letters, click outside, and return, the same names are visible again.
image

Good work!

**Review by nyelmela — APPROVED** [review]
I tested this PR 2397 the changes by checking out the branch, running `npm install`, and starting the app locally. After clearing the site data/cache, I logged in as an Owner user and navigated to `Other Links → Projects → selected WBS → Add Task → clicked on the resources field`. I verified that I could view and add team members, and the list updated immediately without needing to refresh the browser. Everything worked as expected, and I encountered no issues.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/6b4ee6a3-5a31-4629-8e35-d08e2404585f

**Review by vijay10pk — APPROVED** [review]
Changes works as expected.
Screenshot 2024-07-05 at 11 25 19 PM

**Review by Rishitha1309 — APPROVED** [review]
changes worked as expected and also the list updated without refreshing the browser.
PR2397

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by kdaga81 — CHANGES_REQUESTED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60085629/ff404fe8-b4ad-46ba-aadf-67df91228c08

I'm only able to add a few resources (shown in video). Please let me know if we can add permitted users only.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
