### PR TITLE
TuanDinh_TeamsReportCharts_Unit_Test

### PR DESCRIPTION
**Pull request by TuanDinh140194**
Add Unit Test for TeamsReportCharts.jsx component

# Description
Create the unit test for TeamsReportCharts component

## Main changes explained:
- Add new file TeamsReportCharts.test.js
- In TeamsReportCharts.test.js, i added 7 test case to test the TeamsReportCharts.jsx component.
- First, test if the component renders without crashing, test if it renders the correct number of PieChartInfoDetail components, test if renders a message when no team is selected, renders the correct title, it does not render PieChartInfoDetail when selectedTeamsData is empty. Add test for renders PieChartInfoDetail components with correct values and colors. Finally, test if the component calls useEffect with the correct dependencies.
…

## How to test:
1. check into current branch
2. do `npm install` 
3. do `npm test TeamsReportCharts.test.js to run the test
4. Verify that all 7 tests have passed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/7f749c1e-177a-4517-8fb6-5eabf98c0a1d

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-11-18 at 2 06 11 PM

**Review by Hemsharavanan — APPROVED** [review]
- The PR covers unit tests for the TeamsReportCharts component. 
- It checks the rendering, title, message display when no team is selected, and proper rendering of PieChartInfoDetail components with correct values and colors. 
- The tests also validate the correct dependencies for useEffect hook within the component.

Following 7 test have passed successfully.
1. renders without crashing
2. renders the correct number of PieChartInfoDetail components
3. renders a message when no team is selected
4. renders the correct title
5. does not render PieChartInfoDetail when selectedTeamsData is empty
6. renders PieChartInfoDetail components with correct values and colors
7. calls useEffect with the correct dependencies
PR #1558 TuanDinh_TeamsReportCharts_Unit_Test

**Review by pika-chu11 — APPROVED** [review]
Hi @TuanDinh140194 , I have tested the test and it passed on my end! Great job!
PR 1558

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-18 at 11 42 45 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week12 - PR6

**Review by BaileyM96 — APPROVED** [review]
Hello @TuanDinh140194 I tested everything as described and all 7 of the tests have passed great work!



## Screenshot

Screenshot 2023-11-21 at 4 46 31 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
