### PR TITLE
akshit_add_loading_spinning_circle

### PR DESCRIPTION
**Pull request by akshit0211**
# Description
Added a loading spinning circle when members don't load in the projects.
Screenshot

## Related PRS (if any):
This frontend PR is related to the development backend.

## Main changes explained:
1. Added loading spinning circle logic in src/components/Projects/Members/Members.jsx.
2. Updated fetchAllMembers logic in src/actions/projectMembers.js.

## How to test:
1. Check into the current branch.
3. Do `npm install` and `...` to run this PR locally
4. Clear site data/cache
5. Login as admin or any other user.
6. Go to dashboard→ Other Links→ Projects→…
7. Verify that you can see the loading circle before members load.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/8918dc35-6976-4021-89a9-fa85f5912f8d

### CODE REVIEW

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works as expected. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/1bf20cc5-d0ec-4e03-b182-7348518cf0ec

**Comment by agryash** [comment]
Works well for me.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/38642926/bcba4076-9953-4007-a7f2-5b3b64302022

**Review by agryash — DISMISSED** [review]

**Review by jinxyou — DISMISSED** [review]
The loading circle works well. Great work!
Screenshot 2024-06-22 191108

**Review by deepthikannan — DISMISSED** [review]
image
Tested your PR and is working as expected.

**Comment by kdaga81** [comment]
image

I have a suggestion: could we position the loader at the center of the screen?

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and the loading spinning circle added to the table component works fine.!

PR2382

**Comment by sahithidhulipala9** [comment]
Reviewed the PR, Working as Expected
Screenshot (76)

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi Akshit, 

I tested your changes, your loading circle works well, please try to position it to the center of the page. 
image

I noticed a smaller loading circle when I reloaded the page, see the image below. please remove it if it is being replaced by the bigger loading circle.
image

**Review by nathcarnevalli — APPROVED** [review]
Works as expected.

Screenshot 2024-06-28 113058

Screenshot 2024-06-28 113104

**Review by tianyangL11 — APPROVED** [review]
It can show the loading circle successfully.  Great job!
image

**Review by vijay10pk — DISMISSED** [review]
Able to see a loading circle before it load the table. Works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/5b6b2c34-b26d-4ba4-934f-e92686cad991

**Comment by akshit0211** [comment]
> Hi Akshit,
> 
> I tested your changes, your loading circle works well, please try to position it to the center of the page. image
> 
> I noticed a smaller loading circle when I reloaded the page, see the image below. please remove it if it is being replaced by the bigger loading circle. image

Hi Kaushik, I have repositioned the loading circle to the center. Additionally, the smaller loading circle appears on every page, so removing it is beyond the scope of this PR.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
