### PR TITLE
Jianjun - fix the permission of editing or deleting time entry from other users

### PR DESCRIPTION
**Pull request by juneluo**
# Description
**Fix the following two permission:**
 '**Edit Timelog Information**' : 'Gives the user permission to edit any time log entry.'
'**Delete Time Entry (Others)**' : 'Gives the user permission to Delete time entry from others users "Dashboard" -> "Leaderboard" -> "Dot By the side of user\'s name" -> "Current Time Log" -> "Trash button on bottom right"',

**Original problem description:**
7. (PRIORITY MEDIUM) Jae: (WIP Jianjun)Fix the “Edit Timelog Information” permission from the Manage User Permissions Component on Permission Management Page. Even after adding the permission, the user it’s not able to modify the information of the time entry from another user.
Admin/Owner login → Other Links → Permissions Management → Manage User’s Permissions → Choose User (must be a class other than Admin/Owner) → Edit Timelog Information → Add
Go log in as chosen user and test they have the new ability 
8. (PRIORITY MEDIUM) Jae: (WIP Jianjun)Fix the “Delete Time Entry (Others)” permission from the Manage User Permissions Component on Permission Management Page. Even after adding the permission, the user it’s not able to delete the time entry of another user.
Admin/Owner login → Other Links → Permissions Management → Manage User’s timer
Permissions → Choose User (must be a class other than Admin/Owner) → Delete Time Entry (Others) → Add
Go log in as chosen user and test they have the new ability 

## Main changes explained:
- The user with (front end) permission 'editTimelogInfo' is able to edit other user's time entry from that user's dashboard timelog tab.
- The user with (front end) permission 'deleteTimeEntryOthers' is able to delete other user's time entry from that user's dashboard timelog tab.
- Remove the unnecessary 'edit' button from the time log information(description/explanation) card.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as **user that is not Admin/Owner** --> "Leaderboard" -> "Dot By the side of other user\'s name" -> "Current Time Log" -> CANNOT see "Trash button on bottom right" or "Pen button on bottom right"
4. log as **Owner** --> Permissions Management → Manage User’s Permissions → Choose User (must be a class other than Admin/Owner)  → Delete Time Entry (Others) / Edit Timelog Information→ Add
5. log as **the user whose permission has been changed in step4**, repeat step 3, CAN SEE and CLICK the "Trash button" or "Pen button".

## Screenshots or videos of changes:
User without permission:

Owner give permission to a certain user:

After getting the permission:

## Note:
The permission 'editTimelogInfo' was not used as it designed in the previous code, and the "Edit" button of the info card has no action linked, so it is removed to avoid confusion.

### CODE REVIEW

**Review by bienzguoa — DISMISSED** [review]
It works as intended! Good job!
Screenshot 2023-06-17 at 2 11 52 AM
Screenshot 2023-06-17 at 2 14 53 AM
Screenshot 2023-06-17 at 2 16 39 AM

**Review by KurtisIvey — APPROVED** [review]
Functions as intended and clear instructions. Good job

pr916

**Comment by AriaYu927** [comment]
Hi @juneluo , I've tested your PR and it works as expected. Thank you!
core-other-after
core-other-before

**Review by AriaYu927 — APPROVED** [review]

**Review by leonzh2k — DISMISSED** [review]
Tested with a volunteer account.

Before permissions granted:
image

After permissions granted: 
image

And confirmed that I can actually edit and delete time entries: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49804462/fe6f35bd-3383-493d-b7bf-292e70fd9dbb

**Review by EdwinLauM — COMMENTED** [review]
Works as intended! Good job! Please resolve conflicts and I will approve

Before giving permissions:

Screen Shot 2023-06-17 at 7 18 38 PM

After giving permissions:

Screen Shot 2023-06-17 at 7 17 41 PM

**Comment by yufeiStella** [comment]
Hi @juneluo, it works well!
Screen Shot 2023-06-18 at 00 00 13

**Comment by Lucas-E** [comment]
Hey @juneluo, awesome job! Please resolve the conflicts and DM me on Slack with the link of this PR so I can move it to final review!

**Review by Lucas-E — APPROVED** [review]

**Comment by Lucas-E** [comment]
Thank you everyone! Sending this one to final review!

**Review by NidaZaki — APPROVED** [review]
Looks good! Nice work!

**Review by Chuehleo — APPROVED** [review]
Everything work as intended, great job!
Before permissions granted:
Screenshot 2023-06-22 062806
After permissions granted:
Screenshot 2023-06-22 062943

**Pull request merged**
