### PR TITLE
Alex- Weekly Summary| update placeholder text and add check boxes

### PR DESCRIPTION
**Pull request by alexander-huerta**
# Description

chatGPT and other AI text completion tools are changing the way we create and submit our weekly summary reports. This PR aims to update the Weekly Summary component to evolve at the same time. This is part of a series of small changes to come.

## Main changes explained:

1. Updated the placeholder text inside of the form
2. Revised the wording above the required Media File box
3. Create 2 new check boxes below the summary Form 
4. Removed redundant logic from the function that displays the Save button conditionally 

## How to test:
1. Start backed-(HGNRest repository) from the development branch by running  `npm run build`  then  `npm  start`  
2. From this repository, check into current branch and run `npm run start local`  
3. Log as any user (more than one ideally)
4. From the dashboard click the Summary exclamation to enter the Weekly Summary Component 
5. Enter a weekly summary as you normally would and attempt to savem 
6. Ensure all 3 check boxes must be clicked before Save button appears. 
7. Check for spelling errors or grammatical errors throughout. 

## Screenshots or videos of changes:

weekly_summary_fe_pr_1

### CODE REVIEW

**Review by OAkinbode — COMMENTED** [review]
Hello Alex, 

The feature seems to work as intended. 

1. The button does not become active until all the boxes are checked. 
PR868 first screen
It becomes active when all are checked.
PR868 second screen
When you click it, it works. 

Nice work.

**Review by cvtqx — COMMENTED** [review]
Great job, @alexander-huerta ! 

The form looks great  and the changes have been implemented nicely. There are a few things I've noticed:


1. Placeholder text - when I open the form there is no placeholder text showing, only a blank textarea. I've checked in Chrome and Firefox and both show blank textarea. Is this meant to be that way? In the current version the placeholder is showing.

PR#868_placeholderTextMissing

 2. 3 check boxes must be clicked before Save button appears  - this works as intended.

3. Check for spelling errors or grammatical errors throughout - 
I suggest capitalizing (Required) since it comes after a full stop: 

PR#868_functionality_and_UI


One more thing I've noticed (although it is probably beyond the scope of this PR): I was able to save the form despite entering only 45 word text, when the required minimum is 50. the form throws alert when I type less than 45 words:

PR#868_minimumWordCountNotWorking
.

**Comment by alexander-huerta** [comment]
@cvtqx Thank you for the quick and thorough review. A few follow ups 

For point 1. The placeholder text should appear when the page loads, however if you click into the form- as if you were going to type a summary, the placeholder is meant to disappear. Do you see the placeholder text at all? If not, this could be a bug. Can you also confirm if you see the placeholder text in the live site? This PR merely changes the text so I am not sure why the functionality is changing. I will wait for your response and then look into it. 

Regarding the 49 word summary being accepted- that is a bug that I just documented in the sheet and wrote your name next to. I was able to recreate this in the main site and also this branch- only when the summary first exceeded 50 words and then words were deleted. The Regex on line 169 likely needs a small tweak which I can look into. My next ticket is within this same component so it works out.

**Review by EdwinLauM — APPROVED** [review]
Hey @alexander-huerta, changes work as intended! Good job! 

1. I do see the placeholder text that @cvtqx mentioned was missing.

Screen Shot 2023-06-02 at 7 28 38 PM

2. Save button is not clickable until all the new checkboxes are selected

Screen Shot 2023-06-02 at 7 29 18 PM

3. Like @cvtqx mentioned, I am also able to submit my weekly summary when there are 49 words. 

Screen Shot 2023-06-02 at 7 30 28 PM

Approving this PR, since it looks like you are going to address the word count in another PR.

**Review by NidaZaki — COMMENTED** [review]
I came across this issue where it does not let me click the "Save" button because there seems to be some inconsistency with the minimum number of words required for the summary and the number of words in the textbox. Please refer the image.
PR#868

**Review by yufeiStella — APPROVED** [review]
Great! It worked very well that all 3 check boxes must be clicked before the save button appears.
Screen Shot 2023-06-03 at 02 41 23
Screen Shot 2023-06-03 at 02 42 15

**Comment by AnishPandita** [comment]
hi @alexander-huerta I tested your PR and its working as intended. The button is disabled till all the boxes are checked and text summary is filled.
Screenshot 2023-06-03 at 2 41 58 AM
Screenshot 2023-06-03 at 2 42 12 AM

**Review by Lucas-E — CHANGES_REQUESTED** [review]
Impressive job on the pull request (PR) for the weekly summary feature! The functionality is flawless, with the necessary conditions in place: minimum 50 words, a provided Dropbox link, and all checkboxes checked as shown in the images. Well done!

There are, however, some errors originating from the test file. please, solve those errors so that the PR can be approved. The test script is pointing that 3 tests failed.
Captura de tela de 2023-06-03 14-58-18
Captura de tela de 2023-06-03 14-58-15
Captura de tela de 2023-06-03 14-58-10
Captura de tela de 2023-06-03 14-57-43
Captura de tela de 2023-06-03 14-57-06

**Comment by alexander-huerta** [comment]
Thank you all for the feedback. @EdwinLauM I addressed the failing tests- they are now passing. I also added a few additional tests for more coverage of the new checkboxes. Can you please review and approve

**Review by eduhorta — DISMISSED** [review]
Hi, @alexander-huerta!
Everything is working as intended. Nice job! 👍

Testing min of 50 words:
Screenshot 2023-06-05 10-14-44
Not providing media URL:
Screenshot 2023-06-05 10-15-09
Not checking all the boxes:
Screenshot 2023-06-05 10-15-30
Screenshot 2023-06-05 10-15-38

**Comment by cvtqx** [comment]
> @cvtqx Thank you for the quick and thorough review. A few follow ups
> 
> For point 1. The placeholder text should appear when the page loads, however if you click into the form- as if you were going to type a summary, the placeholder is meant to disappear. Do you see the placeholder text at all? If not, this could be a bug. Can you also confirm if you see the placeholder text in the live site? This PR merely changes the text so I am not sure why the functionality is changing. I will wait for your response and then look into it.
> 
> Regarding the 49 word summary being accepted- that is a bug that I just documented in the sheet and wrote your name next to. I was able to recreate this in the main site and also this branch- only when the summary first exceeded 50 words and then words were deleted. The Regex on line 169 likely needs a small tweak which I can look into. My next ticket is within this same component so it works out.

@alexander-huerta I do see the placeholder text in the live site. I have tested your branch again and did not see the placeholder  in the textarea, HOWEVER, I do see it when I test it in an incognito window! I am not sure why that happens, but I guess the issue is with me not the code.  Also since noone else has reported this issue, we can probably disregard it. 

Otherwise, all the functionality works as intended, so I am approving this PR.

**Review by cvtqx — APPROVED** [review]
All the added functionality works as intended, great job!

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Everything seems to be working except the word requirement on the Editor. I can submit it with just the placeholder text alone and not any inputted text on my part so long as the checkboxes are all ticked. As you can see in the video below, the save button is enabled once I have ticked all the boxes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/d93e46c3-c190-446d-aec0-6f3da24adbc2

 I love the additional implementations for the check boxes as it makes it more dummy proof for new people like myself. Once the word requirement is enforced on the front end it should be good to go. 
 
 Additional suggestion since you're already in that file:
 I would recommend adding the following key value pair to the Editor's "init" object present on line 438 since the default cursor over the text body in the editor isn't cursor:text , but instead cursor:default. 
 
content_style: 'body { cursor: text !important; }'
 
 
 However, I am also wondering why it's not refused on the back end and sending an error in the front end dev tools console. That sort of validation shouldn't be only on the front end as it could be considered bad practice. The regex to detect words on the front end could also be a express-validator custom validation on the backend. Perhaps a new pull request in the future for this feature and the proper testing file to confirm full functionality for all invalid form submissions?

**Comment by alexander-huerta** [comment]
Thank you for the thorough review @KurtisIvey Made the edit to the Editors init property. 

The back end validation certainly seems like tech debt and a ticket for a separate PR. Great suggestion 

More immediately, i'm interested in trying to figure out how my proposed edits affected the front end validation and are causing this bug. Any ideas? I think it must have to do with the disabled field in the save button online 519. 

The regex on 169, and the different validate functions below seem fine to me

**Review by 20chen-7 — APPROVED** [review]
The code and function are good.
Default placeholder txt:
Screenshot 2023-06-07 at 1 14 10 PM
Test for each condition:
Screenshot 2023-06-07 at 1 15 02 PM
Screenshot 2023-06-07 at 1 15 34 PM
Screenshot 2023-06-07 at 1 15 14 PM
Screenshot 2023-06-07 at 1 15 20 PM
Screenshot 2023-06-07 at 1 15 25 PM

**Comment by KurtisIvey** [comment]
@alexander-huerta 

I believe this to be related to the validation done by Joi.

It's on line 176 of WeeklySummary.jsx. It actually states in a comment that it allows an empty string or the minimum word count of 50. By removing the .allow('') in summary present on line 177, I was able to enforce the required minimum word count of 50 and the save button remained in a disabled state until it met or exceeded 50 words.

line.176-178 would be as follows
summary: Joi.string()
      .regex(this.regexPattern)
      .label('Minimum 50 words'),

This did cause the test "should save the form data when "Save" button is pressed" to fail in WeeklySummary.test.jsx . However, from examination of the test, it seems to be incomplete since there is no summary "Weekly Summary" text being typed into that element. Perhaps this test could be rephrased into "should NOT save the form data when "Save" button is pressed if no summary". 

line.260 
expect(saveButton).toBeDisabled();

A new test would need to be made that would test for all form fields filled

**Comment by rachnapandya** [comment]
Works as intended.
The placeholder text is working fine. 
placeholdertext
Word limit!
max50
green checked box
unchecked

**Review by bienzguoa — DISMISSED** [review]
All of these work as intended! I tested using admin and volunteer.

Screenshot 2023-06-17 at 3 10 08 AM
Screenshot 2023-06-17 at 3 10 30 AM
Screenshot 2023-06-17 at 3 13 32 AM
Screenshot 2023-06-17 at 3 13 38 AM
Screenshot 2023-06-17 at 3 13 44 AM

**Review by Chuehleo — APPROVED** [review]
Everything work as intended, great job!
Screenshot 2023-06-20 024321
Screenshot 2023-06-20 024218

**Comment by beblicarl** [comment]
This PR works as intended. Great !!
Weekly-Summary 2023-06-29 111215

**Comment by xaanders** [comment]
Tested this PR. 

- Placeholder is shown

placeholder

- Checkboxes are validated as well:
c1
c2
c3

However(and probably not related to this PR) form is validated(and submit button is true) when:
- text area 0 or  >= 50 words(as it was mentioned before)
- url link contains "https://"

**Comment by Jiangwei-shi** [comment]
1. Placeholder works
2. Checkboxes work as well
3. this PR is working as intended
image
image

**Review by xaanders — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, moving this to final review

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @alexander-huerta! I have tested your PR and everything is working perfectly! Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/ddaf8212-e289-4866-93a3-679acd701c48

**Review by siddharthmohite — COMMENTED** [review]
The Changes work as intended amazing!.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37925823/2eea6c1a-e1f9-4488-8fe2-11890b45f89b

**Pull request merged**
