### PR TITLE
Nathalia fix discrepancies in the total hours for the project on the project report page

### PR DESCRIPTION
**Pull request by nathcarnevalli**
# Description
- Reports → Reports → Projects→ select project→ look at the information panel on the right side for project details.
- The total number of hours for the same project shows different hours for different accounts. 
- See recorded video https://drive.google.com/file/d/1rMGP777UKCnfTu_9K2mhdei6ncsqwITI/view?usp=sharing

## Related PRS (if any):
- This frontend PR is associated with the dev backend PR.

## Main changes explained:
- Added missing dependencies to useEffect hooks to ensure correct data fetching and state updates.
- Reset state variables (memberCount, activeMemberCount, nonActiveMemberCount, hoursCommitted) when project ID changes.
- Included validation to reset hoursCommitted to 0 if there are no WBS items.
- Updated task fetching logic for correct WBS items.
- Recalculated member counts correctly when project members change.

## How to test:
1. Switch to the current branch.
2. Execute npm install and npm run start:local to run this PR locally.
3. Clear site data/cache.
4. Log in as an Admin user.
5. Navigate to Dashboard → Reports → Projects → Select a project 
6. Verify if the project hours update correctly when switching between the following projects: HGN Software Development, HGN handover and JIAYU TEST NEW.
7. Log in as an Owner user.
8. Confirm if the project hours match those in the Admin account.

## Screenshots or videos of changes:
Admin:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/bc6fecca-e02c-4bcb-88fd-b68fb80fc69e

Owner:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/933d8dbc-bd6d-41ac-86bd-350c7e7d8999

## Notes
Feel free to select other projects for testing.

### CODE REVIEW

**Comment by Vijeth-V** [comment]
Everything works perfectly well


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/7c400f57-b998-4fee-8b4d-867cfc975594

**Review by Sandhya1236 — DISMISSED** [review]
I have tested the new frontend pull request successfully. The main changes include adding missing dependencies to the useEffect hooks to ensure correct data fetching and state updates, resetting state variables (memberCount, activeMemberCount, nonActiveMemberCount, hoursCommitted) when the project ID changes, including validation to reset hoursCommitted to 0 if there are no WBS items, updating task fetching logic for correct WBS items, and recalculating member counts correctly when project members change. To test, I switched to the current branch, executed npm install and npm run start:local to run the PR locally, cleared the site data/cache, and logged in as an Admin user. I navigated to Dashboard → Reports → Projects → selected a project, and verified that the project hours update correctly when switching between projects such as HGN Software Development, HGN handover, and JIAYU TEST NEW. I also logged in as an Owner user and confirmed that the project hours matched those in the Admin account. All functionalities worked as expected, and the feature is ready for check-in to the development branch. This frontend PR is associated with the dev backend PR.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/0469821a-d0fd-490b-8fbb-a91d432d21b8

**Comment by beblicarl** [comment]
i have tested this functionality successfully and I can confirm that it works as intended

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.06.05-15_39_56.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/07db7a2c-f6fa-471b-9055-e5f9e766e8e0)

**Review by beblicarl — DISMISSED** [review]

**Review by JatinAgrawal94 — DISMISSED** [review]
Verified that the project hours update correctly for the projects JIAYU TEST NEW, HGN SOFTWARE DEVELOPMENT, HGN HANDOVER for owner and admin user.
Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/33e56a6e-b21c-4f69-afb6-e4f2acbf301e

**Comment by cecilia-uu** [comment]
截屏2024-06-08 下午10 17 42
I tested it and it works as mentioned.

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR using Admin and Owner account. The Project hours update are matching correctly for both the accounts. Great Work!

PR2315_HFNsoft
PR2315_HGNhandover
PR2315_Jiyu

**Review by shradac — DISMISSED** [review]
As an Owner user, I navigated to the Projects report under Dashboard → Reports and selected HGN Software Development, HGN handover, and JIAYU TEST NEW. I confirmed that the displayed project hours updated correctly when switching between these projects. I then compared the project hour totals shown in the Owner account to those visible in an Admin account, verifying that the hours matched across the two user roles as expected. The project hours tracking and reporting functionality appears to be working properly.

week1-6
week1-7
week1-8

**Review by Kavil-Jain-514 — DISMISSED** [review]
To test the changes, I followed these steps:
Switched to the current branch.
Executed npm install and npm run start:local to run the PR locally.
Cleared the site data/cache.
Logged in as an Admin user.
Navigated to Dashboard → Reports → Projects, selected a project, and verified that the project hours updated correctly when switching between projects such as HGN Software Development, HGN handover, and JIAYU TEST NEW.
image
image
image

Logged in as an Owner user and confirmed that the project hours matched those in the Admin account.
image
image
image

All functionalities worked as expected, and the feature is ready for check-in to the development branch.

**Review by Jingyii800 — DISMISSED** [review]
Hi Nathalia,

The feature works well, whether I logged in as admin or owner, I can see the same hours on the project report page.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/9c85225c-9e7f-4316-a9e0-500e07c8b13e

**Review by Parth-tech — DISMISSED** [review]
Hi Nathalia,
Everything works as expected. The count for both the owner and the admin account was the same. Great job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/22750a96-7feb-4007-876c-893be31bfc27

**Comment by akshit0211** [comment]
Hi, it is working as expected. Hours are the same in both accounts. Good job!

admin sd
admin handover
admin j

owner sd
owner handover
owner j

**Review by akshit0211 — DISMISSED** [review]

**Review by TXMO-dev — APPROVED** [review]
Discrepancies in the total hours for the project, work as expected. Approved!

**Review by ImzIssa — DISMISSED** [review]
Hey, everything works as expected. Great work.

Screenshot (427)

Screenshot (428)

Screenshot (429)

**Review by vishavk1992 — DISMISSED** [review]
`I have tested this functionality and can confirm that it works as intended.`

PR-2315
PR-2315-1

**Review by Sarath-3119 — DISMISSED** [review]
The changes in the pr are reflected as expected and the time is changing for each of the projects 

image

image

**Review by AnujVakil — APPROVED** [review]
I have tested this PR and it is working as expected.
PR #2315_1
PR #2315_2
PR #2315_3

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
