### PR TITLE
Shrey_unit_test_DuplicateNamePopup

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for DuplicateNamePopup component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test DuplicateNamePopup.test.js
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-12-02 at 10 55 48 PM

### CODE REVIEW

**Review by pika-chu11 — APPROVED** [review]
Hi @Shreyj14 , test passed on my end! Great job!

PR 1627

**Review by vikrambadhan — APPROVED** [review]
Hi, Great Job! I tested your PR and everything works as intended!

Week 14 - PR2

**Comment by ptrpengdev** [comment]
I tested your PR and everything works as intended.

image

**Review by scoopstroop92 — APPROVED** [review]
Hello @Shreyj14  good job on the test cases 
image

**Comment by DragonSlayer2401** [comment]
I tested your PR all of the tests passed as expected and there were no errors or warnings. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/1224ebb4-2612-424b-ae57-fd994b6b5be5

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
