### PR TITLE
Tianjue fix red bell broken

### PR DESCRIPTION
**Pull request by tingedudu8**
# Description
Fix PROJECTS/TASKS/WBS COMPONENT
(PRIORITY LOW) Kaixiang/Jae: On team member tasks tab, when you click red bell icon, some task will break the page, some of them opened modal but no content, some of them did work well.

## Related Problem:
Screen Shot 2023-03-08 at 4 12 29 PM
The date format has been modified on the "Task Info Changes" modal.

## Mainly changes explained:
Add one condition to make sure when the old task is empty will not break the page.
Prevent reload the page before the `taskNotification` has been created.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. login in as any role
4. go to dashboard→ Tasks→ Click on those red bells to see whether they all work properly and whether the "Task Info Changes" modal shows info correctly.

## Note:
If you do not see red bells, login in as admin, go to dashboard→ Other Links→ Projects→ AAA USE THIS PROJECT→ WBS→ Jae's WBS - USE THIS, add and edit tasks and assigned them to anyone to test.

### CODE REVIEW

**Comment by mpavithr** [comment]
Hi, it seems to be working fine for me. When I click on the red bell, the Task Info Changes is shown as seen below
pr703_1
pr703_2

**Review by Lucas-E — COMMENTED** [review]
Hey, how are you doing? Just test the PR and it works fine to me. I tested some tasks, mine and not mine to assure everything is okay.
Captura de tela de 2023-03-09 00-26-53

**Comment by crystalsong2021** [comment]
@tingedudu8 , I checked the functionality of the red bell icon and upon clicking, the modal pop up to show more information. It closed when I click `mark as read` or click outside the modal. Nice job!
Screenshot 2023-03-08 at 10 12 47 PM

https://user-images.githubusercontent.com/18197013/223936889-65ebcc46-2155-4807-943f-34eb61e5505e.mov

**Review by crystalsong2021 — APPROVED** [review]
Nice job.

**Comment by vitorsaa2k** [comment]
Working as intended on both my tasks, and tasks for other users.

image

Also could you please remove some lines which makes nosense? It's not related to this PR but are on the file this PR is changing. 

The file is `AddTaskModal.jsx` and the lines are:

- 653 
image
- 677 
image
- 701 
image
- On this one you dont need to remove the line, just remove the onClick prop that is calling the "toggle" function, the one that is marked on this image: 
image
 
Those lines have duplicated props being passed to the component and should be removed for better behavior of the app.

**Comment by nicollext** [comment]
Tested. Working well. 

**BEFORE** 
Page broke due to TypeError. 

https://user-images.githubusercontent.com/101591708/224356797-cf6e30f2-50c7-46d6-a6a5-4538cb71c699.MP4




**AFTER** 
Working as expected. 

https://user-images.githubusercontent.com/101591708/224357277-e49282f8-7718-4788-8487-170f3246ffbb.MP4


https://user-images.githubusercontent.com/101591708/224357300-b13c8554-8c43-41c0-b7b4-6d30ed74072d.MP4

**Comment by NyahJ** [comment]
Hi @tingedudu8,

I use different accounts to test yout changes in this PR, every red bell can bring me a "Task Info Changes" page as expected, great job! Thank you.

截屏2023-03-10 下午10 05 59

**Review by kangjay88 — APPROVED** [review]
Hi @tingedudu8, I have tested this PR review and can confirm it is working correctly. Code logic looks good as well. Thank you!

https://user-images.githubusercontent.com/108297706/224495701-95e75353-0c68-44c9-a5ad-fbdb2192561f.mp4

**Comment by Jorge-Nerd** [comment]
Hi @tingedudu8 the task work as expected
image

**Comment by AriaYu927** [comment]
Hi @tingedudu8 , I tested the code and everything looks great. Good job, thank you!
PR#703

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by calexander3108 — COMMENTED** [review]
Everything seems good testing on red bells on various tasks. Clicking on the red bell shows expected modal pop ups and displaying the correct contents.

image
image

**Review by NataliaCavicchioli — APPROVED** [review]
I tested your PR and it is working well! 

I opened many modals and none of them broke. Well done!

image

**Review by nicollext — APPROVED** [review]
Great job!

**Comment by ayush0904** [comment]
I have tested the PR. It is working perfectly

image

**Comment by AnishPandita** [comment]
Hi, I tested your PR and its working as required. Code looks clean as well.

https://user-images.githubusercontent.com/111321945/228736867-a65f6495-6ccf-4c2d-839b-f9eea6032726.mov

**Pull request merged**
