### PR TITLE
Yi - Add permission control for wbs related pages

### PR DESCRIPTION
**Pull request by FyisFe**
# Description
image

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Add permission control for accessing wbs related pages

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links -> Project -> WBS -> Access it
6. verify you could view it since admin user has permission
7. log as user without permission
8. verify if you are redirected to the dashboard

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/575bc618-b583-4821-9555-02b0cb197f96

### CODE REVIEW

**Comment by nnamdixobi** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/ddc7f4bc-f316-4bcf-b781-f9c96b4ed001

Everything seems to be working as expected

**Review by Abi-Liu — DISMISSED** [review]
Tested with development server build. Worked as expected. Great job!

When logged in as a user with the `Volunteer` role, trying to visit the WBS page through this link: `http://localhost:3000/wbs/tasks/65e2419373590a2134027a98/65e1f37b20001c275486cab1/Test` results in me being redirected back to the dashboard page as expected. When using the DevAdmin account, I can view all the WBS Action Items.

Screenshot 2024-03-11 at 4 31 40 PM

Screenshot 2024-03-11 at 4 32 08 PM

**Comment by dhairya-mehta** [comment]
Hey, I verified the functionality, checking the redirection as expected
image

**Review by hetvi11110 — DISMISSED** [review]
I have reviewed PR as explained, and it is working as expected. I've attached the reference video for to review.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/d924597f-4c2e-4d24-9bad-160f183abd9c

**Review by iven-yao — DISMISSED** [review]
I just reviewed this pull request, and the route guard works as expected, admin is able to view the page, while other role without permission will be redirected to dashboard.

image
image

**Review by SRamen1999 — DISMISSED** [review]
After reviewing this pull request, the route guard works as expected, admin is able to view the page, while other role without permission will be redirected to dashboard. Also giving WBS permission works as expected. 

video showing the route guard

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/f8dc4e12-9e88-4b86-91cc-0dca2ed3f62e


video showing the WBS permission on a volunteer account

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/c4c72b52-3319-4dc5-a5a2-2938b6dff38f

**Review by kylepham — DISMISSED** [review]
Changes work as expected. Users without WBS permission didn't have access to specific WBS when entering the URL directly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/e8934bed-3b36-47e3-9842-30715affb15f

**Review by Sarthak32 — DISMISSED** [review]
Hi! I have tested your PR and it works as expected it redirects user(without permission) to dashboard 
Screenshot 2024-03-30 155728
Screenshot 2024-03-30 160305

**Comment by MQChen211** [comment]
Hi I tested the functionality, it worked out as expected.

**Review by Renanluizssx — DISMISSED** [review]
Hello @FyisFe,, i reviewed your branch and it's working very well, please access my curriculum below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/191409d8-c14a-4b80-98f4-e81178fd1e92

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works as expected. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/8954a217-b5c8-4a4e-8598-b6cd56018e9d

**Review by j-corp-25 — DISMISSED** [review]
Hi Yi,

I have followed the directions as instructed. 

Redirection is working when navigating to WSB url.

I Tested this route with `Mentor` , `Volunteer`, and `CoreTeam`. 

Working as expected. Video is showing below with the test cases.



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/bba199ef-eee3-40f3-ae72-e263326260a8

**Comment by Gayathr-2012** [comment]
Hi,
logged as admin user
Went to dashboard→ Other Links -> Project -> WBS -> Access it
verified I could view it since admin user has permission
logged as user without permission
verified redirection when navigating.
Good job it works as expected.


image

image

image


image

**Review by bhuvaneswarignanasekar — DISMISSED** [review]
I reviewed the PR, It works as intented. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59138503/f159e0b5-1f22-4d8f-b886-7f8c233c26e4


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59138503/4626e79d-c82e-4cc5-8b0f-47a2cbfd25e9

**Review by Tiantian-C — COMMENTED** [review]
I will be redirected when I logged in as a volunteer and could view it when I logged in as an admin since admin user has permission.
Screenshot 2024-04-03 at 4 35 14 PM

**Review by SushmithaPrathap — DISMISSED** [review]
Hey,

I've reviewed your PR as per the instructions and everything checks out. When logged in as a Volunteer, accessing the WBS page through the provided link redirects me back to the dashboard, just as intended. Using an admin account, I can see all the WBS Action Items without any issues. Looks good to me!

Here is a screen recording:
Screenshot 2024-04-04 at 9 16 32 PM

**Comment by hiralsonip** [comment]
I've confirmed the updates, and they're all functioning correctly. When I attempted to access the WBS page with a Volunteer account, it directed me to the dashboard as expected. However, with an admin account, I was able to access the page without any issues.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66827672/3ef472e0-610d-4bc3-aafb-8d19eeb51c0b

**Review by MohdShahzil29 — APPROVED** [review]
i have checked the PRs everything working as expected. Droping video for refrence.

https://www.loom.com/share/a97ceef780c946ab8a98353bb3dbc3ae

**Review by anandsesha — DISMISSED** [review]
Hi, I reviewed this feature and it works as expected. Admin user able to access WBS and then tested with volunteer user who doesn't have permission to access, with the WBS url and it redirects to dashboard page as expected. 

Screenshot (817)
Screenshot (818)
Screenshot (819)
Screenshot (820)
Screenshot (822)
Screenshot (823)

**Pull request merged**
