### PR TITLE
Ramakrishna _Allowing the numbers in teamcode

### PR DESCRIPTION
**Pull request by Ramaruva**
# Description
image

## Related PRS (if any):
This frontend PR is related to the [#979](https://github.com/OneCommunityGlobal/HGNRest/pull/979) backend PR.

…

## Main changes explained:
-updated the regex the for teamcode changes in formatted.jsx, teamtable.jsx,userProfile.jsx,userTeamsTable.jsx,SaveButton.jsx
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user or any user who can edit teamcodes 
5. Go Reports->weekly Summaries Report 
6. In this page Try to edit the teamcode and check whether you're able to add numbers in teamcode and also check whether the teamcode pass this conditions : length of team code is between 5 to 7 
                                                         A-AAAAA or AAAAAA or A-1AAAA or A12AAAA
7. Now check the same thing in profile page where teamcode can be added 
video explainations:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/0748ab94-7baf-4880-89db-da2b92d139da

##Note:
In weeklysummarie report page for some users while editing the teamcode we are getting 500 userprofile api error and that error is not related to this PR changes, so can you kindly change the teamcode which are able to change Thank you!

### CODE REVIEW

**Comment by Parth-tech** [comment]
Hi Ram,

So before testing your code I verified that we cannot add numbers in the development branch. 

Post this I pull your work and tried editing the team code as per your steps:
1. Reports -> Weekly Summaries
2. Edit Team Code

But on trying any number or only character combination led to a 500, interval server error for me.
I also tried going to the user profile and edit the code but no luck with that either. 

It worked for `Jordy Volunteer` Account as follows:
Screenshot 2024-06-07 at 2 44 33 PM
Screenshot 2024-06-07 at 2 45 10 PM

But it did not work in the below cases:
Screenshot 2024-06-07 at 2 46 32 PM
Screenshot 2024-06-07 at 2 45 59 PM

Just to avoid any confusion while testing can you provide a video recording on how to correctly test the code?

**Comment by Ramaruva** [comment]
> Hi Ram,
> 
> So before testing your code I verified that we cannot add numbers in the development branch.
> 
> Post this I pull your work and tried editing the team code as per your steps:
> 
> 1. Reports -> Weekly Summaries
> 2. Edit Team Code
> 
> But on trying any number or only character combination led to a 500, interval server error for me. I also tried going to the user profile and edit the code but no luck with that either.
> 
> It worked for `Jordy Volunteer` Account as follows: Screenshot 2024-06-07 at 2 44 33 PM Screenshot 2024-06-07 at 2 45 10 PM
> 
> But it did not work in the below cases: Screenshot 2024-06-07 at 2 46 32 PM Screenshot 2024-06-07 at 2 45 59 PM
> 
> Just to avoid any confusion while testing can you provide a video recording on how to correctly test the code?

Hi @Parth-tech , I am sorry for the inconvenience due to some checking for some test users it is not allowing to edit the teamcode actually I forget to put it in note in pr message will add it asap and also video, in meanwhile can you check to change another team where you can change the teamcode

**Comment by Parth-tech** [comment]
> > Hi Ram,
> > So before testing your code I verified that we cannot add numbers in the development branch.
> > Post this I pull your work and tried editing the team code as per your steps:
> > 
> > 1. Reports -> Weekly Summaries
> > 2. Edit Team Code
> > 
> > But on trying any number or only character combination led to a 500, interval server error for me. I also tried going to the user profile and edit the code but no luck with that either.
> > It worked for `Jordy Volunteer` Account as follows: Screenshot 2024-06-07 at 2 44 33 PM Screenshot 2024-06-07 at 2 45 10 PM
> > But it did not work in the below cases: Screenshot 2024-06-07 at 2 46 32 PM Screenshot 2024-06-07 at 2 45 59 PM
> > Just to avoid any confusion while testing can you provide a video recording on how to correctly test the code?
> 
> Hi @Parth-tech , I am sorry for the inconvenience due to some checking for some test users it is not allowing to edit the teamcode actually I forget to put it in note in pr message will add it asap and also video, in meanwhile can you check to change another team where you can change the teamcode

Thanks Ram! I will look into it again soon.

**Comment by nishithaShetty** [comment]
Hi Ram,
Good Work! 
The functionality works as expected. The team codes take only between 5-7 characters, and I was able to add numbers to the team code as well.
Tested this in the profile page and reports.

Added the screenshot below of the validations
PR#2330_1
PR#2330_2
PR#2330_3
PR#2330_4
PR#2330_5

**Comment by cecilia-uu** [comment]
It works! Good job.
截屏2024-06-08 下午10 25 49
截屏2024-06-08 下午10 25 27

**Review by Wenboooooo — CHANGES_REQUESTED** [review]
Hello, I followed the instructions and tried to change the teamcode according to the hint. But some 500 errors occurred.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114895283/8d4f9b46-084d-4bfb-b9f1-ca9d75f38a6e

**Review by jinxyou — CHANGES_REQUESTED** [review]
Hi So I have tested this PR according to the instructions. I am able to edit the team code. And the limitation of code length works well. However, whenever I posted a legal team code, the status 500 error will pop up. It seems unavoidable under any circumstances. Please look through it! Thank you.
Screenshot 2024-06-01 211302

Screenshot 2024-06-08 155348

**Comment by akshit0211** [comment]
The team code takes 5-7 characters. The functionality works as expected. Good job!

reports page1
reports page2
profile page
save

**Review by akshit0211 — APPROVED** [review]

**Comment by Ramaruva** [comment]
> Hi So I have tested this PR according to the instructions. I am able to edit the team code. And the limitation of code length works well. However, whenever I posted a legal team code, the status 500 error will pop up. It seems unavoidable under any circumstances. Please look through it! Thank you. Screenshot 2024-06-01 211302
> 
> Screenshot 2024-06-08 155348

Hi as in my early summary note it was expected due to some validation checking in backend we are getting 500 api status and which not caused due to this changes thank you!

**Comment by Ramaruva** [comment]
> Hello, I followed the instructions and tried to change the teamcode according to the hint. But some 500 errors occurred.
> 
>  2330.mp4

Hi Thanks for taking time out testing as per my instructions note in intial pr that due some backend validations for someusers we are getting 500 api status and those 500 api error status is not related to this PR changes so can you kindly check to change the teamcode with another users where it not throwing 500 api error thank you!

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR for the Weekly summary Reports and Profile page as admin user
-- Able to add numbers to the team code
-- Allows only 5 to 7 characters 
-- Saves only if the team code is in specified formats (A-AAAAA or AAAAAA or A-1AAAA or A12AAAA)
-- No other special characters is allowed

Note: I was able to test for only very few users in report as most of them are throwing 500 server error.

The functionality change  works fine wherever I was able to change the teamcode.

PR2330
PR2330_2
PR2330_3

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
I am running into 500 internal server error on entering any new team code for a user.
Have a look at the video attached for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/68ab40d7-6c0d-461a-86e7-6b734f856173

**Comment by Ramaruva** [comment]
> I am running into 500 internal server error on entering any new team code for a user. Have a look at the video attached for reference.
> 
>  PR.2330.mp4

HI @JatinAgrawal94  Thank you for testing this pull request. The 500 API error is not caused by the changes in this PR. The issue arises because, in the backend, when saving the team code in the user table, the entire table is saved, leading to a MongoDB exception. This exception is not related to any specific team code, as noted in my initial PR message. Please try with different users, as the 500 API error occurs for some users. Check with other users where the team code can be changed easily.

**Review by Jingyii800 — APPROVED** [review]
Hi Ram,

I tested this feature, it works well. I can edit team code in the weekly summary report page and also this change can be reflected immediately in the user profile page. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/740cc8b9-68a3-4bcf-a1b8-8201a7007c9e

**Review by KaushikMreddy — APPROVED** [review]
Hi Ramakrishna, 

I tested your changes, the length being under 5 shows an error as expected and the length is not allowed to be above 7. Numbers are allowed as well. The changes expected for the task are working well. 
image
image

**Review by Parth-tech — APPROVED** [review]
Hi Ram,
Everything works as expected. I have left a detailed review on the backend repo [link.](https://github.com/OneCommunityGlobal/HGNRest/pull/979#pullrequestreview-2114270054)

Great job done!

**Review by TXMO-dev — APPROVED** [review]
I checked out this branch, installed the dependencies, and ran the application. Everything works perfectly. Great job on this implementation. Approved!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
