### PR TITLE
update infringement spelling

### PR DESCRIPTION
**Pull request by juneluo**
### Description
Fixes bug DASHBOARD COMPONENT(PRIORITY MEDIUM) 1.
RJ: Bluesquare record value incorrect on dashboard on main. Infringement change missing for this item on Main. 
image

### Mainly changes explained:
Update all the spelling of infringment to infringement, and two of the file name.
Note: function `Infringments` in PeopleReport.jsx is renamed as `updateInfringements` in development branch. In case the function is called somewhere else I didn't find, I didn't touch its name for the main and just change its spelling from Infringment to Infringement.

### How to test:
check into current branch
do npm install and ... to run this PR locally
go to dashboard→ summary bar
img

### CODE REVIEW

**Review by LeeSingChanYau — COMMENTED** [review]
I do not see any errors so far from testing. Please let me know test cases I should do to make sure everything is working well.

**Comment by PrabhjotSembhi** [comment]
Hey, I have searched for "infringments" it's replaced everywhere is with "infringements".

image


Blue square record count is also shows.

image

**Review by navyasrim — APPROVED** [review]
Code looks good to me and no blockers.. checked for blue squares and count is showing properly.

**Review by RafaelCastilhoCastro — COMMENTED** [review]
It looks the code is good. The blue squares count is working properly too.
Thanks.
image

**Review by PrabhjotSembhi — COMMENTED** [review]
I have also checked this. everything seems fine. the blue square count is also shown.

**Comment by AnishPandita** [comment]
I checked for the misspelling and couldn’t find any instance of infringments. Also the verified that the blue square count is being correctly displayed.
Screenshot 2023-02-18 at 1 24 28 AM
Screenshot 2023-02-18 at 1 24 36 AM
Screenshot 2023-02-18 at 1 24 57 AM
Screenshot 2023-02-18 at 1 25 08 AM

**Pull request merged**
