### PR TITLE
Changhao - More Unit tests for DeleteUserPopup.jsx

### PR DESCRIPTION
**Pull request by lichanghaogit**
# Description
Unit tests for DeleteUserPopup.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm test DeleteUserPopup.test.js` to run this PR locally
3. verify all 20 tests are passed.
## Screenshot:
Screenshot 2023-12-13 at 10 10 07 PM

### CODE REVIEW

**Review by this-journey — APPROVED** [review]
Hello!! I have reviewed your PR and all 20 tests passed.  Great job.

Screenshot 2023-12-14 at 12 33 31 PM (2)

**Review by ilyaflaks — APPROVED** [review]
I have reviewed the changes on this PR and all of the tests are passing! Good work @Changhao3220K !
PR1697

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 16 - Pr2

**Comment by Lin1404** [comment]
Hi! I have reviewed your PR and all 20 tests passed. Great job.

Screenshot 2023-12-15 at 8 01 32 AM

**Review by Lin1404 — APPROVED** [review]

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Great job on this one as it's very robust. Would just like to see some tests utilizing the "isOpen" props to ensure proper functionality depending on the state of that boolean. If you're feeling extra adventurous, you could add test coverage for cases where the username might be null/undefined/empty

Screenshot 2023-12-15 at 2 45 14 PM

All of your tests pass though 👍🏻

The test file is also in the incorrect location. Please refer to the following link for the correct location <a>https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit</a> This will have to be resolved before merge can occur.

Screenshot 2023-12-15 at 2 40 40 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 
Screenshot 2023-12-16 at 12 31 28 AM

**Comment by KurtisIvey** [comment]
Hey [Changhao3220K](https://github.com/Changhao3220K) , once those changes are implemented, I'll rally some more reviewers and move this to final review since it does look really good

**Review by n0vay — APPROVED** [review]
LGTM
image

**Review by Alforoan — COMMENTED** [review]
All tests passed. Nice! 
image

**Review by bienzguoa — COMMENTED** [review]
All test passed! Code looks good and clear, most cases are covered. Could you add additional test for isOpen prop? 
Screenshot 2023-12-30 at 11 08 32 PM

**Review by 666saofeng — APPROVED** [review]
All tests passed. Everything worked as expected.
image

**Review by peterson337 — APPROVED** [review]
Hi Changhao3220K, All Tests passed. Good job!

a

**Comment by DragonSlayer2401** [comment]
All tests passed as intended. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/2fe3dbb3-6d00-487b-804b-e769ba37f56a

**Review by XiaohanMeng — APPROVED** [review]
All cases passed. Great Work!
PR1697 UnitTest result

**Pull request merged**
