### PR TITLE
Shrey - Unit test cases for FileUpload common component

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for FileUpload component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test FileUpload.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-11-01 at 2 24 33 PM

### CODE REVIEW

**Review by DavidC0126 — APPROVED** [review]
Hi @Shreyj14 I tested the PR and it works as described.

fileupload

**Review by navneeeth — APPROVED** [review]
Hello, @Shreyj14! All the tests are passing. Good implementation!
test_cases_passing

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great jo
Screenshot 2023-11-02 030659
b!

**Comment by beblicarl** [comment]
All tests passed! Great work

image

**Review by sxiong5 — APPROVED** [review]
Hey @Shreyj14, all the tests were passed.

Screenshot 2023-11-02 at 13 17 02

**Review by Jiyuanxia — APPROVED** [review]
All tests pass, well done!
Screenshot 2023-11-02 134339

**Review by tsunami776 — APPROVED** [review]
Hi @Shreyj14, your unit test for FileUpload as a common component makes sense to me. I ran the test locally and all tests passed as shown in the screenshot below. Great work!
CleanShot 2023-11-02 at 15 54 01

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed! Great Job!

Week10 -Pr4

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Good work

Screenshot 2023-11-03 at 1 58 47 AM

**Review by malikjahanzaib — APPROVED** [review]
Hi @Shreyj14, All tests passing. Great job!!!

Screenshot:
image

**Comment by kavya151** [comment]
Hi @Shreyj14 . All testcases passed!
pr#1476

**Review by pika-chu11 — APPROVED** [review]
Hi @Shreyj14, all tests are verfied passed on my end! Great job!
 
Screenshot 2023-11-04-FE#1476

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR and it works as expected. 
Screenshot 2023-11-04 at 11 46 12 PM

**Review by savio-henrique — APPROVED** [review]
Hi @Shreyj14 , I've tested this PR and the tests are passing as expected! Great job! :+1: 

# Screenshot

terminal

**Comment by Shreyj14** [comment]
@one-community it has 12 reviews

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
