### PR TITLE
Lucas create blue square reason scheduler

### PR DESCRIPTION
**Pull request by Lucas-E**
# Description
Implementation of functionality to schedule the reason to the week's blue square.

## Related PRS (if any):

This PR is related to backend's [#468](https://github.com/OneCommunityGlobal/HGNRest/pull/468) PR

## Main changes explained:
Now it's possible to schedule a reason for the week's blue square. Only owners and administrators should be able to schedule a reason. Only sundays can be used as date to schedule the reason for a blue square.

## How to test:

Follow the videos:

### PART 1

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92558269/67aea1da-e495-4882-aa34-a6e515da7547

### PART 2

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92558269/a7eab51c-48eb-4955-b107-1c78ca72b7b9

### CODE REVIEW

**Review by TheDescendant39 — CHANGES_REQUESTED** [review]
Hello @Lucas-E, I tested Part1 of your PR and here are my results:

**Tests:**
1. Check if the day on the calendar is next Sunday. (Correct)
2. Check if only the Sunday date can be stored. (Correct)

**Issues:**
1. I cannot save the blue square's reason. I get the "The reason must be unique to the date" error. In your video there already was a reason when you clicked the schedule button so it could be an issue with my setup. Please let me know if that's the case.
5. When I selected a day other than Sunday and tried to save the text -> Got the correct error -> Closed the window -> Clicked on "Schedule Blue Square Reason" again, it showed the previously selected date and did not go back to being the default "next Sunday". Do you think it would be better to revert to "next Sunday" every time a user clicks the button?

*Please refer to the video to reproduce my tests:*

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/825b3761-72de-4c75-ab0f-821986900188

**Comment by Lucas-E** [comment]
> Hello @Lucas-E, I tested Part1 of your PR and here are my results:
> 
> **Tests:**
> 
> 1. Check if the day on the calendar is next Sunday. (Correct)
> 2. Check if only the Sunday date can be stored. (Correct)
> 
> **Issues:**
> 
> 1. I cannot save the blue square's reason. I get the "The reason must be unique to the date" error. In your video there already was a reason when you clicked the schedule button so it could be an issue with my setup. Please let me know if that's the case.
> 2. When I selected a day other than Sunday and tried to save the text -> Got the correct error -> Closed the window -> Clicked on "Schedule Blue Square Reason" again, it showed the previously selected date and did not go back to being the default "next Sunday". Do you think it would be better to revert to "next Sunday" every time a user clicks the button?
> 
> _Please refer to the video to reproduce my tests:_
> 
>  Screen.Recording.2023-08-02.at.3.27.58.PM.mov

Youa re absolutely right! I've forgotten to put a limitation for the user. I'll change it right now! Please review it again after I change it!

**Review by DavidC0126 — COMMENTED** [review]
I tested the PR along with [PR#468](https://github.com/OneCommunityGlobal/HGNRest/pull/468), and it works as described. I checked only Sundays can be used as date to schedule the reason for a blue square and only admin/owner can save the reason for a blue square. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/9ca3638c-52f0-42a9-9009-61c7ef674a54


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/1bd9d38a-0edb-4d42-bab4-7e3f4857479c

**Review by winghojackyli — APPROVED** [review]
Hi @Lucas-E ,I've tested both frontend and backend PR together and everything works as intended. 

### Part 1
Only owner or admin can schedule a reason for the weekly blue square. The request can only be done on Sunday. 

Capture


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/b222220a-0f83-40e9-b3cb-120fe58f543d


### Part 2
I commented the part which only allows request on Sunday. This enables me to request on Aug 3 Wed and log the details of the schedule at the backend. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/2fe75677-5922-43eb-b28c-6584905acca9

**Review by eduvarjaor — COMMENTED** [review]
Hi @Lucas-E 

While I was testing, I faced up the same bug that @jerryren527 found. It only happens when the day is Sunday and the user doesn't write the blue square reason on the textarea.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/e359b16c-19c7-46d1-987f-b7d7e7e45bb8

**Review by TheDescendant39 — APPROVED** [review]
Hi @Lucas-E, I tested your changes and now I am able to save the reason as well.  
Screen Shot 2023-08-04 at 3 42 55 PM

**Comment by Lucas-E** [comment]
@TheDescendant39 

> Hello @Lucas-E,
> 
> I've come across an issue while testing the "Schedule Blue Square Reason" feature on my Administrator account. When I clicked the button for the first time and submitted nothing for the blue square's reason, I expected to see an error message, but nothing was displayed (just a red box with no text was displayed).
> 
> Could you please review this behavior and consider adding an appropriate error message to handle this case? Thank you!
> 
>  missing_error_message.mp4

Just solved it! Please review it again and let me know if everything is fine!

**Comment by Lucas-E** [comment]
> Hi @Lucas-E
> 
> While I was testing, I faced up the same bug that @jerryren527 found. It only happens when the day is Sunday and the user doesn't write the blue square reason on the textarea.
> 
>  blue_square.mp4

Just solved it!

**Review by Abiddy — COMMENTED** [review]
I'm not able to see the error message or submit a blue-square request. Is it because I need to have the backend on  a certain branch too?

[Screencast from 08-05-2023 09:45:41 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77697776/8759ec9f-1ddd-4f42-acd6-15eb47460bc7)

****UPDATE****

I checked through the backend branch and the errors display fine now but why do we get this message "The reason must be unique to the date" ?

Screenshot from 2023-08-05 10-26-12

**Comment by n0vay** [comment]
Tested basic functionality, works as intended.
image

**Review by ThapeloMasasa — APPROVED** [review]
The functionality to create and save a blue square a head of time works as intended.
Screenshot 2023-08-05 at 1 33 30 PM

**Comment by jerryren527** [comment]
> @TheDescendant39
> 
> > Hello @Lucas-E,
> > I've come across an issue while testing the "Schedule Blue Square Reason" feature on my Administrator account. When I clicked the button for the first time and submitted nothing for the blue square's reason, I expected to see an error message, but nothing was displayed (just a red box with no text was displayed).
> > Could you please review this behavior and consider adding an appropriate error message to handle this case? Thank you!
> > missing_error_message.mp4
> 
> Just solved it! Please review it again and let me know if everything is fine!

Hi @Lucas-E,
I tested out your new changes and I am happy to report that an error message is successfully displayed when an Administrator account clicks on the "Schedule Blue Square Reason" button for the first time and submits nothing for the blue square's reason! Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/88db26dd-4ffe-4756-85fa-2b1c45db5271

**Comment by jerryren527** [comment]
> I'm not able to see the error message or submit a blue-square request. Is it because I need to have the backend on a certain branch too?
> Screencast.from.08-05-2023.09.45.41.AM.webm
> 
> **UPDATE**
> 
> I checked through the backend branch and the errors display fine now but why do we get this message "The reason must be unique to the date" ?
> 
> Screenshot from 2023-08-05 10-26-12

Hello @Abiddy !

It seems like you might be encountering the error message "The reason must be unique to the date" due to testing outdated commits. Here are the steps I followed to ensure I pulled the most recent changes from the remote `lucas_create_blue_square_reason_scheduler` branch into my local working directory:

## Backend:

1. Before getting started, I made sure my local working directory was using node version 14 by running:
   ```
   nvm use 14.17.5
   ```
* Note: I have Node version 14.17.5 installed on my computer. Modify this command according to the version of Node installed on your computer.

2. Then, I switched to the `lucas_create_blue_square_reason_scheduler` branch and pulled the latest changes from the remote using:
   ```
   git checkout lucas_create_blue_square_reason_scheduler
   git pull origin lucas_create_blue_square_reason_scheduler
   ```

3. To confirm that the latest changes were successfully pulled in, I checked the updated commit history with:
   ```
   git log
   ```

4. Finally, I ran the necessary commands for the backend:
   ```
   npm i && npm run build && npm start
   ```

## Frontend:

1. Similar to the backend, I ensured my local working directory used node version 14 by executing:
   ```
   nvm use 14.17.5
   ```

2. I changed to the `lucas_create_blue_square_reason_scheduler` branch using:
   ```
   git checkout lucas_create_blue_square_reason_scheduler
   ```

3. Next, I pulled the latest changes from the remote `lucas_create_blue_square_reason_scheduler` branch with:
   ```
   git pull origin lucas_create_blue_square_reason_scheduler
   ```

4. To confirm the successful update, I checked the commit history once again using:
   ```
   git log
   ```

5. Lastly, I ran the following commands for the frontend:
   ```
   npm i
   npm start:local
   ```

I hope these steps are helpful in pulling the latest changes to your local working directory. If you have any further questions or need more assistance, don't hesitate to ask!

**Review by ramyaram2092 — DISMISSED** [review]
Hello @Lucas-E  appreciate the detailed video. The overall functionality looks great. 
The system allows me to schedule reason for a blue square for an already past  date . For example I am able to schedule one for Last Sunday (July 30). is that an expected behavior? 
The testing video is a as follows :

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/fbd19ad3-a92b-4fdb-9d0c-73c38ac4e344

**Review by yaow62023 — COMMENTED** [review]
I tested your changes, and the schedule blue square function can be used normally. But I have the same question: the blue square before the current date can be stored, and the function can be changed by pressing the plus button. So is it necessary to add a function to disable the previous date in the option of the schedule for blue square.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/433573ef-c00e-481f-bc7b-b3ce6d8d2ffd

**Comment by Lucas-E** [comment]
> I tested your changes, and the schedule blue square function can be used normally. But I have the same question: the blue square before the current date can be stored, and the function can be changed by pressing the plus button. So is it necessary to add a function to disable the previous date in the option of the schedule for blue square.
> 
>  2023-08-06.12-27-41.mp4

Solved it, please re-review!

**Review by luisarevalo21 — APPROVED** [review]
Hello @Lucas-E 

I tested your PR and works as intended great job!

I can add a blue square for the future and the app provides me feedback saying it was successfully scheduled.

One feedback I can think of is, when a user selects a date, you should check if that date can be used. If the user selects a Monday the error message should pop up. Just so they don't have to type a message then click "submit" to get the error. Let me know your thoughts. 

Screenshot 2023-08-07 at 9 39 57 PM


If i select a date in the past the code displays an error message. 
Screenshot 2023-08-07 at 9 38 47 PM
Screenshot 2023-08-07 at 9 39 45 PM



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/def7f839-d7b5-409e-9c5e-d204ee5c26e3

**Review by navneeeth — APPROVED** [review]
LGTM! Tested both parts and the scheudling as well as the check for only issuing blue squares on Sundays works well. Great implementation!

**Part 1:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/f9aeab6c-a812-46b1-87bc-2198a107bb50

**Part 2 with the IF condition commenting for scheduling on non-Sundays:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/5fdeeeb5-6187-4119-83ad-9cf3ac40546b

**Part 2 with the Cron Job Scheduling:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/85e479a0-ccc9-4d65-835c-a49924cea961

**Review by veronicacheng2 — APPROVED** [review]
Hi @Lucas-E, I have tested the PR and it works as intended

Test Result:
1. Cannot schedule blue square reason other than Sunday
2. Only admin/owner can schedule blue square 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/0becf780-9562-4ae4-8565-b0168f120e34

**Review by zuhang2000 — APPROVED** [review]
Great I've tested your PR following your instructions. The functionality is working as expected! First I test on Admin account and everything work as expected. I can only schedule a reason on Sunday and not on other week days. I also could not provide a blank message to the input. It's good that you have covered all the edge cases. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/35e462bd-2b0a-4220-b318-cb14e6a7378c

I also did test on Volunteer. And it displayed the message that I must be Admin or Owner in order to schedule a blue square reason, which is as expected. And it does not allow to save any changes as a volunteer. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/3359d39b-8c3a-43cb-9344-fcc40d5cb607

**Comment by Jiyuanxia** [comment]
Hello @Lucas-E, I've completed the review of your pull request and conducted testing in conjunction with backend pull request.  Unfortunately, I encountered the same issues that others have faced previously. Specifically, while I was able to see a red alert square, the associated error message did not display within it. I've taken care to ensure that I tested the latest version of your code for both the frontend and backend.
Screenshot 2023-08-14 183916
Screenshot 2023-08-14 183934

**Comment by Lucas-E** [comment]
> Hello @Lucas-E, I've completed the review of your pull request and conducted testing in conjunction with backend pull request.  Unfortunately, I encountered the same issues that others have faced previously. Specifically, while I was able to see a red alert square, the associated error message did not display within it. I've taken care to ensure that I tested the latest version of your code for both the frontend and backend.
> Screenshot 2023-08-14 183916
> Screenshot 2023-08-14 183934
> 

Did you perform a git pull for this branch?

**Comment by iTvX** [comment]
I tested your PR, and everything looks fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/7e027b40-cd4d-4c08-bb05-0e3afb9187b2

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change work well on my device, and I find the blue square after I created it.

image
image
image

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change work well on my device, and I find the blue square after I created it.

image

image

image

**Review by eduvarjaor — APPROVED** [review]
Working as intended with the new changes. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/00ea1bea-e8db-4caf-9037-eb84a62e5e96

**Comment by AuroraLovesWhales** [comment]
Hi @Lucas-E. I have tested this PR along with the backend and both Part 1 and Part 2 are working as expected. Great job!!!

Part 1:
1. Check if only Sunday date can be stored
2. Check if reason is edited if it already exists

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/33f092a6-3680-49ae-8e4a-473425e02cbc

Part 2:
1. Comment part so days other than Sunday can be used to schedule reason
2. Schedule reason to the day you are reviewing the code

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/d9dd1f8a-4737-4c2e-a287-5bcdd0b34c9c

4. Change the cron job to attend your time, but on America/Los_Angeles timezone
5. Check if blue square is issued

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/7b200844-690d-4d94-8b0f-e88e31688f3a

**Review by AuroraLovesWhales — APPROVED** [review]

**Pull request merged**
