### PR TITLE
Yaohong create Quick Setup Modal for new team members

### PR DESCRIPTION
**Pull request by YHX6**
# Description
image
This is a continuation of [#PR 1673](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1673)  and [#PR  644](https://github.com/OneCommunityGlobal/HGNRest/pull/644)

## Related PRS (if any):
his frontend PR is related to the [#821 backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/821).
…

## Main changes explained:
 - Created title schema
 - Created controller for interacting with database
 - Created route from title
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin or ownder user
5. go to dashboard→ user management→ click a user → user profile page
6. Task 1: Click a QSC to open a modal to enter information and then save changes
7. Task 2: Click another QSC to overwrite user profile information
8. Task 3: Click "Add a new title" button to create a title/QSC (make sure your team code exists); Click a QSC to delete it

## Screenshots or videos of changes:
Task 1: Click a QSC to open a modal to enter information and then save changes

https://github.com/OneCommunityGlobal/HGNRest/assets/113729159/2ec65fcf-1010-40a8-af39-42645cde53c5

Task 2: Click another QSC to overwrite user profile information

https://github.com/OneCommunityGlobal/HGNRest/assets/113729159/6ddc5093-7d51-4ad0-bb1d-1931b55d8fda

Task 3:  Click "Add a new title" button to create a title/QSC (make sure your team code exists); Click a QSC to delete it

https://github.com/OneCommunityGlobal/HGNRest/assets/113729159/cf95d36b-6d31-4f2a-9f72-99d02986604c

### CODE REVIEW

**Review by abdel-lall — COMMENTED** [review]
Hi @YHX6. Could we please address the validation of inputs on the 'Add A New Title' modal? It appears that there's a need for validation to ensure their validity. Additionally, implementing error handling and error messages would greatly enhance the user experience, especially if something isn't functioning correctly. Currently, when attempting to add a new title, I've noticed that it doesn't save, and there's no indicator to alert me of any issues. Thank you!
Screenshot 2024-03-30 154507

**Review by jennZhang93 — CHANGES_REQUESTED** [review]
Not sure why this would happen, but when I logged in with admin account, and if I tried to open an user profile page, they are all blank for some reason. This won't happen with Core Team and Volunteer role. Below are the screenshots showing the error message.

Screenshot 2024-04-06 at 11 27 44 PM
Screenshot 2024-04-06 at 11 27 52 PM
Screenshot 2024-04-06 at 11 28 02 PM

**Review by MohdShahzil29 — CHANGES_REQUESTED** [review]
not working
review

**Comment by YHX6** [comment]
The above issues of not showing the page occur because some of the titles created have problems. I have deleted all those titles and added validations in both the frontend and backend files. It works on my side right now

**Comment by YHX6** [comment]
As for the issue of unexpected keys, I am not sure where that comes from. However, the error seemed to exist before I worked on this PR. Maybe it is originated from other parts of code

**Review by Parth-tech — CHANGES_REQUESTED** [review]
Hey Yaohong,
The PR does work as intended, so great job there. There are a few minor issues as well. 

`Firstly I will share the video of what is working correctly:`

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/d6f43900-74cc-4ae8-9b0d-5d1c590cc499




https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/411ab93d-8250-4b3c-b9bd-12f6a5bcc43f

`Next I want to highlight the issues:`
- The `Media Folder input` in modal has an `*` which kind of implies that it is a required field. But even when I don't type anything in it, I am allowed to create a custom QSC. If this is how it should be please ignore this.
- The `Project Assignment` is also required. So when I choose a value and then I clear the field, then too it allows me to submit custom QSC. The problem is that, when I submitted I thought no project will be assigned as the field was empty. But it uses the last select value. So if such behavior is intended please ignore this as well.
- There is no validation check of GoogleDoc field. Should it have any validation? If yes then that is missing.

Reference videos:
- `Media Folder:`


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/31e5c01c-b310-4bd3-a35e-76bccd8ffdd2


- `Project Assignement Issue:`

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/aa3aee1a-6d95-49f8-aea3-8a08d92f23b5

Thanks!

**Review by SushmithaPrathap — CHANGES_REQUESTED** [review]
Hey!

I've tested this PR and it functions well overall. However, there are some issues with form validations not working as expected:

When the "project assignment" field (required) is left empty, it incorrectly displays "project not found". After adding a new title, the change doesn't reflect as expected. The "save changes" button behavior is confusing. 
Delete QSC works fine and the modals are working well

Here is a screen recording:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/100743d8-035b-48de-9fdf-17259b381c03


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/7edf28db-a8b3-45b1-adec-b709938d8efe

**Review by metaphor987 — COMMENTED** [review]
Hi Yaohong,

I've tested the Quick Setup Modal using an admin account. The main functionalities, such as assigning a title to the user and updating the title for the user, all work well. However, there are some small issues with "Team Assignment" while creating new titles, as shown below:

- When leaving the "Team Assignment" blank, we can successfully create the new title. However, an error message appears if we click "Save Changes" after assigning this new title to users, and the new user title is not saved in the user's profile after refreshing the page.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/8103d5bd-7745-4e38-bc16-22d7fa3238a8

- When choosing to create a new team while doing the "Team Assignment," sometimes the web page becomes unresponsive. In the cases where it does respond, we encounter the same issue while saving the new user title described in the above case.
Screenshot 2024-04-13 at 5 15 02 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/9089a057-eb37-4681-9cee-522b021b7e95

Thank you!

**Review by Tiantian-C — COMMENTED** [review]
I have tested it. It works fine!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/72f0aa18-29a8-433d-bf60-06dd02dc13ad

**Review by p-suram — COMMENTED** [review]
Hey, Great Work. I don't see any errors in console too. Delete works well.
I see same issues mentioned by others. Along with that I have other comment that, When media URL is not valid, API is failing, but still I see the `Success` popup. We might want to show `Error` or `Unsuccessful` popup if API fails (Please see at 5:00 in below attached video). 
Please find attached video below

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/e68ffe12-3e1b-437d-8db0-a2b21402f171

**Review by aaryaneil — CHANGES_REQUESTED** [review]
I tested the changes but I am getting a TypeError when creating a new modal.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/ce62e851-4751-4e0a-a76a-e6affae68377

Screenshot 2024-04-13 at 11 22 35 PM

**Comment by YHX6** [comment]
> Hey Yaohong, The PR does work as intended, so great job there. There are a few minor issues as well.
> 
> `Firstly I will share the video of what is working correctly:`
> 
>  Custom_QSC.mp4 
>  QSC_overwrite.modal_check.mp4 
> `Next I want to highlight the issues:`
> 
> * The `Media Folder input` in modal has an `*` which kind of implies that it is a required field. But even when I don't type anything in it, I am allowed to create a custom QSC. If this is how it should be please ignore this.
> * The `Project Assignment` is also required. So when I choose a value and then I clear the field, then too it allows me to submit custom QSC. The problem is that, when I submitted I thought no project will be assigned as the field was empty. But it uses the last select value. So if such behavior is intended please ignore this as well.
> * There is no validation check of GoogleDoc field. Should it have any validation? If yes then that is missing.
> 
> Reference videos:
> 
> * `Media Folder:`
> 
>  Media.Folder.Issue.mp4 
> * `Project Assignement Issue:`
> 
>  Project.Assignment.mp4 
> Thanks!



> Hey Yaohong, The PR does work as intended, so great job there. There are a few minor issues as well.
> 
> `Firstly I will share the video of what is working correctly:`
> 
>  Custom_QSC.mp4 
>  QSC_overwrite.modal_check.mp4 
> `Next I want to highlight the issues:`
> 
> * The `Media Folder input` in modal has an `*` which kind of implies that it is a required field. But even when I don't type anything in it, I am allowed to create a custom QSC. If this is how it should be please ignore this.
> * The `Project Assignment` is also required. So when I choose a value and then I clear the field, then too it allows me to submit custom QSC. The problem is that, when I submitted I thought no project will be assigned as the field was empty. But it uses the last select value. So if such behavior is intended please ignore this as well.
> * There is no validation check of GoogleDoc field. Should it have any validation? If yes then that is missing.
> 
> Reference videos:
> 
> * `Media Folder:`
> 
>  Media.Folder.Issue.mp4 
> * `Project Assignement Issue:`
> 
>  Project.Assignment.mp4 
> Thanks!

Thank you so much for identifying the issues. I have fixed the problem of Media Folder input. 

As for the Google doc, I did not implement validation because simply checking the format does not guarantee the link exists and it refers to the correct documentation. So I left this part for manual validation.

For the Project Assignment issue, this input field is actually a component provided by others. I checked it and saw that it has been used for many pages and I am not sure if changing it will cause issues for other pages. I will create a new component to solve this problem.

**Comment by YHX6** [comment]
Thank you all for identifying the issues. 

Here are some issues that I solved:
 - Media Folder input no validation
 - Returns warning message of "project" not found when Project Assignment input is empty  (replace it with "project is empty")
 - Showing error and success simultaneously when media folder in empty

Here is the part that I think should be it for manual validation
 - Google doc: I did not implement validation because simply checking the format does not guarantee the link exists and it refers to the correct documentation. So I left this part for manual validation.

The rest of the issues all originated from the input field of "Team Assignment" and "Team Assignment". The part of code is from others's components and it has been used for many other features. I am not sure if changing it will cause issues for other pages. I will check it and implement a new component is needed.

**Review by p-suram — CHANGES_REQUESTED** [review]
Following up on my previous review:
 When media URL is not valid, API is failing, but still I see the `Success` popup. We might want to show `Error` or `Unsuccessful` popup if API fails (Please see at 5:00 in below attached video). 
Please find attached video below

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/e68ffe12-3e1b-437d-8db0-a2b21402f171

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account and described features worked. Good work

I noticed there's a warning message asking users to save changes even after the user clicked "Save". May be good to remove the warning message after user hit Saved.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/f7489f2b-1d49-4559-9cc5-a365cf73a67f

**Review by aaryaneil — COMMENTED** [review]
I tested your PR and I received a 400 error on saving the changes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/ece01928-f6e7-4b04-87c7-4b8f26cbee05

**Comment by YHX6** [comment]
> I tested your PR and I received a 400 error on saving the changes.
> 
>  Screen.Recording.2024-04-25.at.11.03.43.PM.mov

Hi, the code "T" is a debugging one and is not removed. I have just deleted. Please try to create a new title  and then assign it. i test on my side and did not found this error

**Review by p-suram — CHANGES_REQUESTED** [review]
Hey Yaohong, Good Work. I am not seeing issue that I have mentioned in my previous review. I would request couple of changes for below:
1. Please remove  `console.log` from `src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx` file line 31
2. There's `console.log` in `src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx` file line 150. Please fix the functionality 
3. When adding a new title, if I just enter one word as title, it is appending `Undefined` to the title. Ex: If i just give `Dev`, it is displaying `DUndefined`. Please check at `1:25` in my review video 
Please find my review video below. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/be987b96-9ddd-4e93-8602-d54246c82684

**Review by SushmithaPrathap — DISMISSED** [review]
Hey, I tested this PR, on saving the changes there was a crash. 400 error.

I tried with another profile. Editing the title works, deleting is working well and adding a new title also works. Only one issue after adding a new title, the modal doesn't close

Here is a screen recording:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/dabcb7d9-e957-44ed-ba19-917a44673fcf

Crash:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/7cd7de69-7670-4b6c-8868-2db349090948

**Comment by YHX6** [comment]
> Hey Yaohong, Good Work. I am not seeing issue that I have mentioned in my previous review. I would request couple of changes for below:
> 
> 1. Please remove  `console.log` from `src/components/UserProfile/QuickSetupModal/QuickSetupModal.jsx` file line 31
> 2. There's `console.log` in `src/components/UserProfile/QuickSetupModal/AddNewTitleModal.jsx` file line 150. Please fix the functionality
> 3. When adding a new title, if I just enter one word as title, it is appending `Undefined` to the title. Ex: If i just give `Dev`, it is displaying `DUndefined`. Please check at `1:25` in my review video
>    Please find my review video below.
> 
>  2024-04-26.08-09-12.mp4

Thank you so much! Just fixed it.

**Review by cvtqx — APPROVED** [review]
Hi, I've tested this PR and it works as described. Below are videos of testing:

1. Click a QSC to open a modal to enter information and then save changes 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/b5392fd2-ce06-41c3-afbe-f5d0f0b34ab8

2. Task 2: Click another QSC to overwrite user profile information

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/1bd1c94a-4319-418b-b4e4-ef42e2014711

3. Task 3: Click "Add a new title" button to create a title/QSC (make sure your team code exists); Click a QSC to delete it

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/badfad0f-33c0-4f99-9ffb-87f2743724aa

Validation in input fields works well and i can't submit the form without the required fields:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/e8c5cfcb-4887-44fa-aa79-d15196460cf7

**Pull request merged**
