### PR TITLE
Zuhang_fix_blue_circle_for_three_digit_numbers

### PR DESCRIPTION
**Pull request by zuhang2000**
# Description
- The Badges Section at the bottom of the Dashboard page. 
- Currently badges with 3-digit numbers are having a displaying issue. The 3-digit number is exceeding the blue circle.
- Centering number may be all that’s needed, or blue circle make need to be enlarged.
- Badges should look like they do on the Profile Page.
- Check  fringe case that the Person Maximum Badge doesn’t get broken or over-enlarged.

Before Change:
Screenshot 2024-02-10 at 6 22 20 PM

After Change:
Screenshot 2024-02-10 at 6 21 12 PM

## Main changes explained:
- Fix issues in Badge.css of the Badge component
- Fix the .badge_count_3_digit

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Profile→ Assign Badges
6. After you assign badges, click the "Select Featured" and increase the badge count to be a 3-digit number.
7. Go back to the Badge section of the Dashboard page.
8. Make sure that the 3-digit number within the blue circle is displaying correctly.
9. Check edge case that the Person Maximum Badge doesn’t get broken or over-enlarged.

## Screenshots or videos of changes:
Screenshot 2024-02-10 at 6 21 12 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and the 3 digit numbers are displayed properly. I tested this feature with various badges, and different values, and it works well. Please refer the screenshots attached.

PR 1940 1
PR 1940 2

**Review by peterson337 — APPROVED** [review]
HI Zuhang, I tested your application, and everything worked as expected. Good job!

one comunnity

**Review by XiaohanMeng — COMMENTED** [review]
Hi, I tested this PR and found that every badge with three digits works as intended. Additionally, I examined the edges of the badges and found no issues with breakage or excessive enlargement. Well done! Please see the reference video.
1940_result

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/2122d1c7-bcc0-44ea-a07b-c49548789453

**Review by XiaohanMeng — APPROVED** [review]

**Review by swathyjayaseelan — APPROVED** [review]
The changes look good.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/e7e72b49-f8d3-49cd-a141-b5809ce46dae

**Review by FyisFe — APPROVED** [review]
It looks great! 

image
image

**Comment by dhairya-mehta** [comment]
Hi, I tested your PR and the 3 digit numbers are displayed properly, good job!

**Review by yvonnep165 — APPROVED** [review]
Hi, I tested the PR with owner account and the 3 digit numbers are displayed properly. Please refer the video as below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/ef238fa9-dd13-420a-bf2e-c66d0bfb4dc0

**Comment by rajnada** [comment]
Hii,

I have checked the design. Now It looks better.

Dashboard view in Desktop :

image


Profile view in Dashbaord :

image


Dashboard View in small device :

It looks Nice Just the headers are more aligned to the left! check here...

image

Profile view in Small Device :

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
