### PR TITLE
Sucheta - Filter project by User's First Name / Last Name / Search by Alphabet (updated)

### PR DESCRIPTION
**Pull request by sucheta90**
# Description
(PRIORITY HIGH) Jae: New Function Request: Search Projects By Person 
- Other Links>Projects
- Need a way to search project by person so I know which ones they belong to and can easily add tasks for them
- [Video of what’s needed](https://www.loom.com/share/3c95e9c100f44bcd8cab922bcff8e8e1)

## Related PRS (if any):
This frontend PR is related to the [#919](https://github.com/OneCommunityGlobal/HGNRest/pull/919) backend PR.

…

## Main changes explained:
- Adds a new component `SearchProjectByPerson.jsx` to `Projects.jsx`. This component returns a form that takes user input and shows suggested users in a dropdown list to choose from. Once a user has been selected, the search function is executed.
- Creates a new Reducer function - `userProjectsByUserNameReducer.js` that holds the initial state of the `userProjects` and `userError`
- Users can now be searched by `First Name`, and `Last Name` as well as allows alphabetic search.
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/ owner user (any account that has access to the project's page)
5. go to dashboard→ Other Links→ Projects
6. User should see a form that takes user first and last name or an expression to match a user. User will be given list of users to choose from in a dropdown. Once user has been selected, the search function is executed and then a filter function and renders the list of projects.
7. User should see an error if project/projects related to a particular user are unavailable in the database.

...
## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/8a6979e2-4f4c-471e-a2e2-0a25389251b7

## Note:
The search is case insensitive.

### CODE REVIEW

**Review by Sandhya1236 — DISMISSED** [review]
I have successfully tested the implementation of the new functionality to search projects by person. This update, related to backend PR #919, adds a new component SearchProjectByPerson.jsx to Projects.jsx. The component provides a form for user input and displays suggested users in a dropdown list. Once a user is selected, the search function is executed. Additionally, a new reducer function userProjectsByUserNameReducer.js was created to manage the state of userProjects and userError. Users can now be searched by first name, last name, or through alphabetic search. After checking into the current branch, running npm install, and starting the application locally, I cleared the site data and cache. Logging in as an admin or owner user, I navigated to dashboard → Other Links → Projects. The form for searching users appeared as expected, allowing me to select a user from the dropdown and view their related projects. The functionality worked correctly, displaying an error message if no projects were found for the selected user.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/4aa99d68-2f1e-4e53-89b2-aa0465f31010

**Review by mohabbasd — CHANGES_REQUESTED** [review]
Hello, I tested your PR everything looks great but the search functions was not working properly. Below is a video for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/b516c8ce-a123-41bd-b166-be14f92297a1

**Comment by sucheta90** [comment]
> Hello, I tested your PR everything looks great but the search functions was not working properly. Below is a video for your reference.
> 
>  Screen.Recording.2024-06-01.at.7.41.08.PM.mov

Hello @mohabbasd , thank you so much for taking the time to review this PR. Can you please check if the [backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/919) was properly installed? I was unable to recreate the bug. Please make sure to run the `npm install` for for both PR's.

**Comment by Vijeth-V** [comment]
I am unable to perform search. I am getting 404 status for the API call. I am attaching a video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/8e012417-427f-44af-8f5e-324ddb3164bf

**Review by Wenboooooo — CHANGES_REQUESTED** [review]
Hello, I followed the instruction and logged in to the project page, but it seems like the function of searching by alphabet was not working. I typed in some project names in the search bar but no results displayed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114895283/64e44560-e1e3-4c37-8fd4-2edc5e5d9771

**Comment by sucheta90** [comment]
> Hello, I followed the instruction and logged in to the project page, but it seems like the function of searching by alphabet was not working. I typed in some project names in the search bar but no results displayed.
> 
>  2312.mp4

Hello @Wenboooooo , the feature requires a user name that will provide you a list of users matching the input . In this feature the Current account user has the ability to search Project , using a user's First or Last name Or an Alphabet that matches with the first or last name of the user. Let me know if you have any questions related to this PR.

**Review by Logeshwari-Renu — CHANGES_REQUESTED** [review]
I have followed the instructions and performed the search, following are the observations. 

1) Able to search by username "Logeshwari Admin" when pasting the complete name in the text box.

2) While searching for the username "Logeshwari Admin" by a few characters of the first name, the suggested users dropdown is not listing any users for me. (The empty dropdown for "Suggested users" is not getting displayed in the video, please check the screenshot).

3) Can you rename the button label as "Search Project by Person" instead of "Search Project", so users will understand they are searching for a person belonging to projects and not the projects themselves.

4) The search text box is cleared after the search is complete. The "Back" button can be renamed to "Clear Search" so users can understand they have completed the search, or retain the name in the search box to understand which person is searched.

PR2312_No_suggested_users

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/e9985690-ec3d-4b73-b1be-ee38f9bbd7ba

**Review by Kavil-Jain-514 — DISMISSED** [review]
Hello Sucheta, 
The functionality is working, and the code implementation is good. The search functionality works with random capitalization of characters as well.
image
![image]
It also gives an error when the name is absent from the list.
(https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/45e022a7-ebd5-4e84-bf43-7a2a8a5a9372)

However, I have a suggestion. After the user types in the Name, the search project button should also work by pressing the enter key. This is good practice in UI that the button works on the enter key.

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
I followed the necessary steps as mentioned. Search for projects with first and last name works fine but when I switch to dark mode, I see a white background. I am attaching a video for reference.
Rest everything works fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/5065c52f-12bc-4057-9c54-10e1fca8e4f6

**Comment by Vijeth-V** [comment]
Hello, I am not aware why this is not working on my machine, I have pulled the latest code on both the backend server and the front end as well. But still it fails to make the API request, it gives 403 error. I have attached a screen recording for reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/dd327855-dfe5-4a5c-a1eb-969c864202f9

**Review by Trip2310 — DISMISSED** [review]
PR#2312

The changes add new functionality for searching and displaying projects by a user's name. The code is generally well-structured.
Add comments to describe complex logic and do function and variable names are self-explanatory.

**Comment by sucheta90** [comment]
> The changes add new functionality for searching and displaying projects by a user's name. The code is generally well-structured. Add comments to describe complex logic and do function and variable names are self-explanatory.

Thank you @Trip2310 for taking the time to review this PR. I will work on the suggestions.

**Comment by cecilia-uu** [comment]
截屏2024-06-08 下午10 21 09
It's weird. I cannot open it..

**Pull request closed without merging**
