### PR TITLE
Shiwani TeamMemberTask unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for TeamMemberTask.jsx

## Main changes explained:
- Added a new file called TeamMemberTask.test.js
- Added 5 test cases: check status icon, team member name and link, check if time beside the tasks are right, check if task names and its associated links are working properly and added tests to check whether icons are functioning as expected, progress bar showing correct logged time and estimated time.
- Added test ids for testing specific tags in TeamMemberTask.jsx

## How to test:
1. check into current branch
2. do `npm test src/__tests__/TeamMemberTask.test.js` 
3. check if all the test cases pass

## Screenshots or videos of changes:
Screenshot 2023-11-01 at 7 49 24 PM

## Note:
This is my first PR on unit tests so feel free add any comments or suggestions

### CODE REVIEW

**Review by navneeeth — APPROVED** [review]
Hi, @Shiwani99! The test cases are all passing. Great implementation!

test_cases_passing

**Review by DavidC0126 — COMMENTED** [review]
Hi @Shiwani99 I tested the PR and it works as intended.


Uploading UI.mov…

**Review by Chuehleo — COMMENTED** [review]
Everything works as expected, great job!
Screenshot 2023-11-02 024032

**Comment by beblicarl** [comment]
All tests passed. Great work

image

**Review by beblicarl — APPROVED** [review]

**Review by sxiong5 — APPROVED** [review]
Hey @Shiwani99, all the tests were passed. Nice work.

Screenshot 2023-11-02 at 12 24 59

**Review by Jiyuanxia — APPROVED** [review]
Hi @Shiwani99 , I have reviewed your pull request and tested it. It works as you intended, all tests passed. Well done!
Screenshot 2023-11-02 134614

**Review by tsunami776 — APPROVED** [review]
Hi @Shiwani99, your implementation of unit test for TeamMemberTask looks good to me. I ran the test locally and all tests passed. Nice work!
CleanShot 2023-11-02 at 15 44 42

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and the all the test cases passed! Good Job!

Week 10 - PR3

**Review by Shuhua-L — APPROVED** [review]
All tests passed as intended. Great implementation!
Screenshot 2023-11-02 at 6 06 28 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
