### PR TITLE
Jinchao fixed project/task field of timeEntry component

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
Currently the project/task field in timeEntry can only show project correctly. For those time logged under a task, the project/task is blank.
image
image

## Related PRS (if any):
This frontend PR is related to the [#403](https://github.com/OneCommunityGlobal/HGNRest/pull/403) backend PR.

## Main changes explained:
- Remove redundant states and axios requests in TimeEntry component. Now the component will get those data directly from the `data` parameter.

## How to test:
1. check into current branch on both FE and [BE](https://github.com/OneCommunityGlobal/HGNRest/pull/403)
2. do `npm run build` and `npm start` at BE
3. log as admin users->go to Timelog and log some time under both projects and tasks.
4. check if the project/task works for all timeEntries and this PR doesn't break anything relative to timeEntry component.
image
5. open the browser console to check if these bad request error are fixed(these errors are occured when we have a timeEntry logged under a task)
Screenshot 2023-06-10 193315edit

## Note:

- Currently there is a bug preventing you change the project/task for a timeEntry:

Screenshot 2023-06-10 200700
Please pass this feature when testing, I will fix this bug in another PR.

- This PR will improve the efficency of the timeEntry component since it remove two axios requests which are time cosuming:
Screenshot 2023-06-10 193315edit2 
You can test the time on your loacalhost following these codes in TimeEntry.jsx on dev branch:
Screenshot 2023-06-10 193350

### CODE REVIEW

**Review by bienzguoa — COMMENTED** [review]
Hi,
When I added time entry, there was no update and it didn't show anything I logged, but the time showing on the Leaderboard changed. I can't figure out the issue I encountered...
Screenshot 2023-06-11 at 1 13 59 AM
Screenshot 2023-06-11 at 1 18 26 AM

**Comment by suigunfjc** [comment]
Hi @bienzguoa , I tried add timeEntries under both project and task and I couldn't reproduce your situation. Could you record a video of your operations? Thanks.

**Comment by KurtisIvey** [comment]
Tried to review, but every time I try to add a task entry, it doesn't allow me to select or enter anything. I'm using an admin account with all permissions enabled

image

**Review by cvtqx — APPROVED** [review]
The fix seems to work as described. I was able to successfully add both project and task  into Timeentry form and nothing broke. 

Screen Shot 2023-06-13 at 11 38 01 AM

The console did not show any GET errors: 

Screen Shot 2023-06-13 at 11 37 06 AM

**Review by Chuehleo — APPROVED** [review]
Changes working as intended and console did not show any GET errors.
Screenshot 2023-06-13 103950

**Review by KurtisIvey — APPROVED** [review]
Figured out how to navigate assigning tasks and was able to successfully review this. Looks great, functions exactly as intended without the errors that were previously listed. Great job

pr906 and pr403

**Comment by Lucas-E** [comment]
Thank you everybody! Moving to final review!

**Comment by bienzguoa** [comment]
> Hi @bienzguoa , I tried add timeEntries under both project and task and I couldn't reproduce your situation. Could you record a video of your operations? Thanks.

Hi,
The problem has been resolved. now it works as intended! Good job!
Screenshot 2023-06-14 at 1 00 05 AM

**Review by bienzguoa — APPROVED** [review]

**Review by NidaZaki — APPROVED** [review]
Works as intended!

**Review by Lucas-E — APPROVED** [review]

**Comment by KaixiangGU** [comment]
Work as intended.
Capture

**Pull request merged**
