### PR TITLE
Jingyi-User Profile: Rehireable / Notrehireable Check Box

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
When logging as Owner/Admin, going to one user's user profile, besides the user's time log icon, there is a checkbox to change the rehireable status of this user.
Also, when viewing people by Reports>Reports>People>Choose person>,  the rehireable/Not rehireable checkbox is on the right.
image
image

## Related PRS (if any):
This frontend PR is related to the[ #789 ](https://github.com/OneCommunityGlobal/HGNRest/pull/789#issue-2175170890)backend PR.

## Main changes explained:
- In the user profile, create a new frontend UI and API and server function to change the status of rehireable/Not rehireable
- In people report page, link this endpoint to current checkbox, too

## How to test:
1. check into the current branch and backend #xxx backend branch
2. do `npm install` and `npm run start：local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Leaderboard→ select one user→ User profile
6. verify there's a check box besides the "clock" icon to change rehireable status. When clicking on it, a popup window will ask you to confirm the change.
7. Refresh the page to make sure this change is saved.
8. go to Reports>Reports>People>Choose person>, see there is a checkbox under the "title". When clicking on it, a info window will pop up and show the result. 
9. Refresh the page to make sure this change is saved.
10. Log in as a Volunteer Role; make sure you cannot see this checkbox on the User Profile Page.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/a6ffd80e-8d56-4fcd-bc7f-ae69b19c1dd9

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/0fd97655-66ee-4e82-b2cf-edec03837dbc

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and I was able to change the rehire status of the users with the admin account. The rehire checkbox was not visible with volunteer account. Please refer the videos attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/df9cb89a-d11b-45f8-89aa-6ceb180d92b7


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/613c6195-57e0-42b0-b578-ea971533be5e

**Review by navyasrim — APPROVED** [review]
Hi, I reviewed your PR and I was able to change the rehire status of the users with the admin account, also when I login with volunteer account ,the rehire checkbox was not visible, refer the Pictures 
PR-2032-2
PR-2032-3
PR-2032-1
attached.

**Comment by nnamdixobi** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/30c2e68a-b096-44b2-829d-4983350c908f

Tested and works as expected, however whenever I refresh the box unchecks

**Comment by 20chen-7** [comment]
Left review at the [backend](https://github.com/OneCommunityGlobal/HGNRest/pull/789#pullrequestreview-1935785945)

**Review by yaow62023 — DISMISSED** [review]
Hi Jingyi, I have test your PR, all the functions work as intended. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/afab74d6-e92c-4061-8e4e-ca2af5fa5a92

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works perfectly. Below is a video for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/d90724f6-2154-411a-8769-39b43b0de600

**Review by yvonnep165 — DISMISSED** [review]
Hi @Jingyii800 , I reviewed your PR and I was able to change the rehire status of the users with the admin and owner account. I also tested it with the volunteer account. The rehire checkbox for the account itself and other's account were not visible with volunteer account. Nice work!
Please refer the videos attached:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/64f42bbd-33bf-4b28-82b5-5ea6876e81f4

**Review by aaryaneil — COMMENTED** [review]
Tested the PR the changes work as mentioned. The only thing is that from the volunteer account, I could change the rehireable from the reports section, I don't know whether it's supposed to do that or not.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/7267652a-98f6-4243-bfbb-bce3536ce7a3

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
