### PR TITLE
Leo - Make Teams list only suggest active members

### PR DESCRIPTION
**Pull request by Chuehleo**
# Description
Screenshot 2023-08-25 201238

## Related PRS (if any):
…

## Main changes explained:
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to Other Links -> Teams -> Choose Team → Members → Add
5. check if the list shows only active team members

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/7f6fe9e9-d1a5-425a-842b-d8e71aad8590
## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by AuroraLovesWhales** [comment]
Hi @Chuehleo. I have tested your PR and it is working as expected. Great job!

I paused three of my own test accounts and they are not showing up when I try to add new members to a team.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/1de36a1a-a97a-46db-b025-2f3b84b7a716

**Review by AuroraLovesWhales — APPROVED** [review]

**Review by harshidad — APPROVED** [review]
Working Good!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/a24471ba-4b2e-4d0d-bb18-3b0d86b4efa0

**Review by ramyaram2092 — APPROVED** [review]
Works as intended. Good job 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/cc06e522-f876-4ad3-a48d-13f4cc1f0b78

**Review by belagaam — APPROVED** [review]
I tested the PR as per the instructions. I paused some of my test user and they were not visible when adding to a team. Resuming the user makes them visible again.
Everything works as expected. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/a206f1e7-a2ec-47bb-b7c1-06611b25673c

**Comment by Shreyj14** [comment]
hi @Chuehleo the PR works as intended.Great Job!
[New Recording - 8_26_2023, 3_34_52 PM (1).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/c5f680f1-37a1-49b9-a1e0-34063a907c68)

**Review by Shreyj14 — APPROVED** [review]

**Review by arcan9 — APPROVED** [review]
The change worked as it should. I deactivated these certain users and checked if they show up in the dropdown when adding team members, which they don't. Previously they would've shown up if they're active. Nice job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102492480/cd2d808c-6045-4da7-8f8a-3e072ab46f2b

**Comment by one-community** [comment]
FANTASTIC! I see a Leadership Team review in here too, so merging!

**Pull request merged**
