### PR TITLE
EduardoV - create a unit test for the CreateNewTeamPopup component

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the CreateNewTeamPopup component to confirm whether it working as intended.

Screenshot_1
Screenshot_2

## Main changes explained:
- Export file CreateNewTeamPopup.jsx for test component
- Create file CreateNewTeamPopup.test.js to do the unit test

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install` to run this PR locally
4. open file src → tests → Teams → CreateNewTeamPopup.test.js
5. run `npm run test src/__tests__/Teams/CreateNewTeamPopup.test.js`

## Screenshots or videos of changes:
This is the result it's supposed to get:

Screenshot_3

If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by harshidad — APPROVED** [review]
Testcase Passed.
PR#1269

**Review by DavidC0126 — APPROVED** [review]
Hi it works as expected!
create

**Comment by iTvX** [comment]
Hi, I tested your PR and your code, and everything looks fine. Good job. 

CleanShot 2023-09-06 at 23 52 31@2x

**Review by vinaykumarh — APPROVED** [review]
Reviewed the PR and tested it as per instruction. It works as expected.
image

**Comment by Sssky-18** [comment]
Just tested the code, and it worked well on my console. All tests were passed. Great work! 

PRreview_#1269

**Comment by AnishPandita** [comment]
Hey, I ran the tests according to the guidelines provided and everything worked perfectly. There were no errors discovered.
Screenshot 2023-09-07 at 1 54 11 PM

**Review by ss23046 — APPROVED** [review]
Hi @eduvarjaor ,
Works fine, no issues occurred. LGTM

Screen Shot 2023-09-07 at 8 46 02 PM

**Review by GaryB93 — APPROVED** [review]
Ran tests on CreateNewTeamPopup.jsx and reviewed code in test file. All tests passed. Good work!

Screenshot 2023-09-08 at 2 52 04 PM

**Review by EdwinLauM — APPROVED** [review]
Hey @eduvarjaor! Unit tests passed and code looks good! Good job! 

Screen Shot 2023-09-09 at 7 25 28 PM

**Review by gabi-lima — APPROVED** [review]
Great job Edu!
image

**Comment by beblicarl** [comment]
This test passed and the code seems great!

issue #1269

**Review by beblicarl — APPROVED** [review]

**Review by vikrambadhan — APPROVED** [review]
Hi, i tested your PR and it works as intended

Week3 - PR13

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
