### PR TITLE
Nathan - removed <p> and linted

### PR DESCRIPTION
**Pull request by nathanah**
# Description
Removes validateDOMNesting warning: \<div\> cannot appear as a descendant of \<p\>.

## Main changes explained:
- Removed a \<p\> wrapper
- Linting changes on the rest of the file

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard
5. verify that warning does not appear in the dev tools console

## Screenshots or videos of changes:
Before:
image
After:
image

### CODE REVIEW

**Review by jonathancarpena — DISMISSED** [review]
@nathanah Received no errors in the console when going on the Dashboard page. Nice job! 👍

**Review by KurtisIvey — DISMISSED** [review]
Functions as intended. Very happy to have that thing finally gone from the console lol.

pr944 works

**Comment by Jiangwei-shi** [comment]
I logged in to Admin and my account. Both work as described. the console doesn't have a validateDOMNesting warning.
image
image

**Comment by AnishPandita** [comment]
Hi @nathanah I tested your PR and its working as intended. The validateDOMTesting warning is not there anymore.
Screenshot 2023-06-27 at 12 20 21 AM

**Comment by beblicarl** [comment]
This PR works as intended. Great !!

Screenshot from 2023-06-27 14-59-27

**Review by beblicarl — DISMISSED** [review]

**Comment by one-community** [comment]
We reverted some changes that may have caused this problem. Is it still a problem, does this still need to be merged?

**Comment by nathanah** [comment]
> We reverted some changes that may have caused this problem. Is it still a problem, does this still need to be merged?

It is still present on the development branch.

**Comment by one-community** [comment]
Thank you everyone, moving this to final review!

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @nathanah. I have reviewed your PR and the warning is gone now. Great job!

image

**Review by HectorAgudelo — DISMISSED** [review]
The update works as expected.
PR#944

**Review by KurtisIvey — APPROVED** [review]
re-reviewed and everything seems to still be working as intended. Functions on volunteer, admin, and owner without issues. Good job

**Review by xaanders — APPROVED** [review]

**Comment by xaanders** [comment]
Logged as an admin. Console is clean. 
doc_2023-07-04_14-04-39

**Pull request merged**
