### PR TITLE
Peterson impl make profile team code field show existing codes

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This feature is designed to assist the administrator or owner in assigning a team code to a specific user by providing suggestions for codes in use.

## Related PRS (if any):
None
…

## Main changes explained:
The user profile file has been updated to retrieve the team codes from the database.

The Auto Complete Team Code component is designed to provide automatic suggestions in the input field.
…

## How to test:
1. check into current branch
2. do `npm install` and `npm start` to run this PR locally
4. Log in as an administrator or owner
5. go to View Profile→ Teams
6. Click on the input field, and a dropdown menu will appear with a spinning spinner. Once the team codes are loaded, the spinner will disappear, and the codes will be displayed. You can close the dropdown menu by clicking outside of it.
7. Once the dropdown menu is open, click on the code or type in the input to find a specific code.
8.After adding a new code for the user, click the "Save changes" button to assign the team code to the new user.

## Screenshots or videos of changes:
a

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by linkhanthtel — DISMISSED** [review]
I reviewed your PR and everything worked as expected! Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/8e98fbe7-c629-408f-8e4f-9767422ba764

**Review by hbodgal — DISMISSED** [review]
image

I was able to see loading spinner and a dropdown with all codes. And even search and filter options. Everything works as required.

**Review by MinSun0814 — DISMISSED** [review]
There is now a dropdown with suggested input. Works as intended.
image
image

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and it is working as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/a8556943-52a3-48fb-a7f1-015250e66564

**Review by peter6866 — DISMISSED** [review]
Great work on this team code suggestion feature! I followed your testing instructions and was able to successfully:

Test input field:
- The dropdown appeared with a spinner as expected.
- Team codes loaded correctly and the spinner disappeared.
- Closing the dropdown by clicking outside worked as intended.

Select and search:
- Clicking on a code in the dropdown successfully added it.
- Typing in the input filtered the suggestions effectively.
Save changes: 
- After adding a new code, clicking "Save Changes" correctly assigned it to the user.

image

**Review by JatinAgrawal94 — DISMISSED** [review]
1) check into current branch
2) Do npm install and npm start to run this PR locally
3) Log in as an administrator or owner
4) Go to View Profile→ Teams
5) Assign and changed team codes.
This works good. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/e3ae5bec-a8f0-472b-a97f-f1796bda9e98

**Comment by nishithaShetty** [comment]
Hi, Nice work!
The functionality works as expected. When we click the dropdown, a list is suggested. We can select from the list or add an user input. If the input is correct, we can save the changes; otherwise, an error is prompted.

PR#2191_1
PR#2191_2
PR#2191_3

**Comment by akshit0211** [comment]
This feature is working properly. Good work!

img1
img2
img3
img4

**Review by akshit0211 — DISMISSED** [review]

**Review by Sudershhh — CHANGES_REQUESTED** [review]
The functionality is working as expected, however the design does not seem to be consistent. Having a substantial gap between the table headers and the input dropdown field OR the dropdown options can have a higher z index to keep it on top, would be good.

PR 2191

**Review by Sarath-3119 — DISMISSED** [review]
Tested this PR, on clicking the input, searched for a team code from the dropdown, when the right format is entered the drop down filtered based on the search result . ABle to save changes as expected. 




image
image

**Comment by one-community** [comment]
> The functionality is working as expected, however the design does not seem to be consistent. Having a substantial gap between the table headers and the input dropdown field OR the dropdown options can have a higher z index to keep it on top, would be good.
> 
> PR 2191

Yes, I agree. I'd like this to suggest/show as many as possible so I rarely have to scroll.

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR using an admin account. The dropdown spinner works as expected. After selecting a team code, the spinner disappears. I was able to assign a team code by selecting a team and a message popped up. After clicking the save changes button, another message popped which said the update was saved. Below is the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/4ce9a6be-82b9-4969-bd62-d13ca2a38694

**Review by Shadhrush5 — DISMISSED** [review]
Hi, I have reviewed PR 2191 using the following steps:
Checkout branch "Peterson_Impl_Make_Profile_Team_Code_Field_Show_Existing_Codes"
npm install
npm run start:local
Logged in as admin
View Profile -> Teams
Used the scroll bar to select a team code
Saved changes as well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/119898772/49042417-975a-4148-8605-9878746a39ee


The functionality described works as expected. Great work. Thank you.

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and it works as expected and i was able to assign team code. 


https://github.com/user-attachments/assets/5fbadf8a-79a3-4a53-b9b1-f6c5e2f627a3

**Comment by ZhangPeizhou** [comment]
works as expected, well done!

https://github.com/user-attachments/assets/d1c6b8b2-e956-493d-a5bd-164701b02a7b

**Review by AnujVakil — DISMISSED** [review]
I have tested this PR and working as expected.
PR #2191_1
PR #2191_2

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.
Screenshot (109)
Screenshot (112)
Screenshot (110)
Screenshot (111)

**Review by SaiLavanya1 — DISMISSED** [review]
I've tested the PR #2191, and it worked as expected.
https://www.loom.com/share/25be1f844e6a4bea87c3cb92401b0933

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
