### PR TITLE
added start date to user management table

### PR DESCRIPTION
**Pull request by mounica-dingari-by**
# Description
Add start date column to User Management Table

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to Other Links→ User Management

## Screenshots or videos of chan
Screenshot from 2023-09-07 12-56-03
ges:

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by EdwinLauM — COMMENTED** [review]
Hey @mounica-dingari-by! I have tested your PR and the start date column does appear in the user management table. However, I am not too sure why it is not displaying the correct start date. Attached is a video of my current saved start date in an owner account but it is not being displayed correctly in the user management tab 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/6c56f6a3-9e09-414b-ab0b-99daf455c3f7

**Review by DavidC0126 — COMMENTED** [review]
Hi the functionality works as described.
startDate

**Review by luisarevalo21 — APPROVED** [review]
Hello @mounica-dingari-by 

I tested your PR and works as intended. Great work! 
When viewing the dashboard, I can see a start date and an end date. 

Screenshot 2023-09-07 at 8 33 13 PM

**Review by Sssky-18 — APPROVED** [review]

**Comment by Sssky-18** [comment]
Hi, I just tested this feature and it worked! The start date was shown as an added column on the User Management page. However, all of them showed "N/A", not the actual date. So I checked your code, and the "N/A" was your setting for current tests. Therefore, I think the test for this feature passed as expected. Congrats! 


PR#1278

**Review by harshidad — COMMENTED** [review]
@mounica-dingari-by 
 I tested  PR and the start date column does appear, but  it is not displaying the correct start date value. Please see the attached video, where start date display in view profile but 
still value not display in User management . It display N/A for all records.

Is it intended value? 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/33f20972-de9e-4073-8f5e-81e640a73666

**Review by Haoj1 — COMMENTED** [review]
@mounica-dingari-by Good job. There is a new column for start date. Hope there is more updates

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/d07f4b82-be5a-408d-a2ad-04f1d2825c88

**Review by zuhang2000 — CHANGES_REQUESTED** [review]
Hi I've tested your PR following your instructions! There is a start date column adding to the user management table. However, all inputs in "start date" and "end date" column are "N/A", which should not be case. They should display the correct start date/end date for that user. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/c0c99da9-6f7f-4678-b378-642c5a24c93d

**Review by vikrambadhan — COMMENTED** [review]
Hi, 
I tested your PR and the start date is not appearing in the user management tab. It shows "N/A" as the start date for all records. I have attached a video addressing this issue.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/c42d90f9-e9c8-4506-adcf-942bcebb4dc8

**Review by robertoooc — CHANGES_REQUESTED** [review]
Hi @mounica-dingari-by, I tested your pr and noticed that no information actually shows up in the start date section. I added a few console logs in the user table data file and realized that in UserTableData.jsx file your line 101 has the startDate variable. The props.user does not have the startDate attribute it's actually just supposed to be createdDate as shown below.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/8870f5dd-91b0-4f03-b269-786590d099f3

**Review by veronicacheng2 — APPROVED** [review]
Hi @mounica-dingari-by, I have tested the PR and it works great! 

image

**Review by gabi-lima — APPROVED** [review]
Great job!

**Review by winghojackyli — COMMENTED** [review]
Hi @mounica-dingari-by , I've tested the PR and it shows the start date column, but there is no valid data of start date shown. 

startDate

**Review by GaryB93 — CHANGES_REQUESTED** [review]
The user management table now has a Start Date column but is not display start dates for any of the users.

Screenshot 2023-09-10 at 1 03 35 PM
Screenshot 2023-09-10 at 1 12 30 PM

**Comment by AnishPandita** [comment]
Hey, I tested the PR and the start date column looks good. 
Screenshot 2023-09-11 at 9 25 51 PM

**Review by dah00 — APPROVED** [review]
Hey @mounica-dingari-by , I test your PR and I can see the Start Date as expected. Great work!
PR1278_start_date_display

**Comment by Jiyuanxia** [comment]
Hi @mounica-dingari-by , I have reviewed your pull request and tested it. The "Start Date" colunm does appear but after I pause one of my account, the start date does not change accordingly.
Screenshot 2023-09-15 131755

**Comment by tsunami776** [comment]
> Hi @mounica-dingari-by, I tested your pr and noticed that no information actually shows up in the start date section. I added a few console logs in the user table data file and realized that in UserTableData.jsx file your line 101 has the startDate variable. The props.user does not have the startDate attribute it's actually just supposed to be createdDate as shown below.
> 
>  Start.date.pr.mov

The start date column now appears in the table, but they are 'N/A'. I did a similar test as above and tried to print out props.user in the browser console. No startDate attribute was found and an attribute somewhat close is createdDate.

**Review by Shiwani99 — CHANGES_REQUESTED** [review]
Hi,
I tested your PR. User Management page does display a start date column, but does not display the actual start date even if the start date is changed.

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Just as the others have said, user management fails to properly reflect the start date of users. 

I've included photos below of my own test accounts verifying this.
pr1278 fails to show start dates for users in user manag tab
Screenshot 2023-09-19 at 4 55 22 PM
Screenshot 2023-09-19 at 4 55 37 PM


You may want to ensure the props are properly being passed since they're showing N/A

**Comment by KurtisIvey** [comment]
Here's the fix:
change line 101 with the following code as startDate doesn't exist
      `      <td>{props.user.createdDate ? formatDate(props.user.createdDate) : 'N/A'}</td>
`
Screenshot 2023-09-19 at 5 02 45 PM
Screenshot 2023-09-19 at 5 02 11 PM

**Comment by iTvX** [comment]
I have tested your pr, it looks good. Thank you!

CleanShot 2023-09-20 at 13 50 16@2x

**Comment by astrjc0326** [comment]
I tested the PR. The start date was shown in the user page but not displayed in the User Management page as others' mentioned.
I tried to fix with the way KurtisIvey advised and it worked.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/cbcf9dee-fae2-4663-8be5-d73c64bb17b5

**Comment by Chuehleo** [comment]
The start date column was showing as expected but it shows N/A for all of the columns. I replaced line 101 in UserTableData.jsx which @KurtisIvey suggested and the start date showed correctly.
Screenshot 2023-09-23 032842
After the replacement of line 101:
Screenshot 2023-09-23 033209

**Review by JeffLi117 — CHANGES_REQUESTED** [review]
Your intended change of creating a start date column to the user management table is indeed present -- however, as others have stated, there is an issue on line 101 within UserTableData.jsx that keeps the data only displayed as "N/A". Please see the image below and implement the change suggested by @KurtisIvey .

image

**Review by belagaam — COMMENTED** [review]
I tested the PR as per the instructions. I am able to see the start date but the values for each user are showing up as N/A

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/7a840623-1603-47d0-b30f-f9487a546ccf

**Comment by Shubhu0** [comment]
Hi @mounica-dingari-by I tested and reviwed the PR. The start data and end date is displayed. However shouldn't the start dates and end dates show the correct date instead of 'N/A' ?

image

**Comment by RheaWu1212** [comment]
Hi there, no expected start date displayed: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/d951da6e-2fab-40e8-9d44-a28f861765d4

**Review by Bhagyashree444 — CHANGES_REQUESTED** [review]
I was able to add/update the start date for a user but the changes didn't reflect on the start date column of user management page.
Screenshot (191)

Screenshot (192)

**Pull request closed without merging**
