### PR TITLE
EduardoV - create unit tests for the TeamTableHeader component

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the TeamTableHeader component to confirm whether it working as intended.

Screenshot_1

## Main changes explained:
- Export file TeamTableHeader.jsx for the test component
- Create file TeamTableHeader.test.js to do the unit tests

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install` to run this PR locally
4. open file src → tests → Teams → TeamTableHeader.test.js
5. run `npm run test src/__tests__/Teams/TeamTableHeader.test.js`

## Screenshots or videos of changes:
This is the result it's supposed to get:

Screenshot_2

If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by vikrambadhan — APPROVED** [review]
Hi, i tested your PR and it works as intended!

Week3 - PR11 (#1299)

**Review by Haoj1 — APPROVED** [review]
@eduvarjaor All tests passed. Good job!

**Review by DavidC0126 — APPROVED** [review]
Hi @eduvarjaor I tested your PR and it works as intended.
test_teamTable

**Review by robertoooc — APPROVED** [review]
Hi @eduvarjaor, your new unit test for the team table header component looks well written. It also does pass all your cases.
Screenshot 2023-09-13 at 9 44 31 PM

**Review by EdwinLauM — APPROVED** [review]
Hi @eduvarjaor! Works as expected and code looks good! Good job! 

Screen Shot 2023-09-14 at 1 21 28 AM

**Review by dah00 — APPROVED** [review]
Hey @eduvarjaor, Tested your PR and all tests passed as expected. Great work 
PR1299

**Review by yunshan111 — APPROVED** [review]
Reviewed your PR, and ran the tests. LGTM

image

**Review by tsunami776 — APPROVED** [review]
All tests passed and the TeamTableHeader works as described. Nice work!
CleanShot 2023-09-14 at 17 01 33
CleanShot 2023-09-14 at 16 59 09

**Comment by one-community** [comment]
Thank you everyone, merging.

**Review by Bhagyashree444 — COMMENTED** [review]
Works as expected.
PR #1299

**Pull request merged**
