### PR TITLE
Changhao - fixing the build issue

### PR DESCRIPTION
**Pull request by lichanghaogit**
# Description
fixing build issue caused by unit tests
## How to test:
1. check into current branch
2. do `npm install` and `npm test UserTableData.test.js` to run this PR locally
3. verify all 30 tests are passed

## Screenshot:
Screenshot 2024-02-15 at 10 43 14 PM

### CODE REVIEW

**Review by ShengjieMao — APPROVED** [review]
All tests passed after the revision. great work
PR_1954

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR. It passed all the test cases and all the related components are being rendered properly and are displayed without any errors. Please refer the screenshot attached. 

PR 1954

**Review by TareqMia — APPROVED** [review]
Hi @Changhao3220K, I tested this PR and the unit tests passed all the test cases. All the components rendered without any issues and everything is working as intended 
Screenshot 2024-02-16 at 6 31 13 PM

**Review by TapanPathak — APPROVED** [review]
Hi, All test cases passed! 

Screenshot 2024-02-16 at 7 03 03 PM

**Review by chrischenlixing — APPROVED** [review]
image
It's confirmed all tests are passed!

**Review by n0vay — APPROVED** [review]
Looks good to me
image

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and worked as expected.

Captura de tela 2024-02-17 224127

**Review by prnvjn — APPROVED** [review]
All the 30 tests passed!

image

**Review by KurtisIvey — APPROVED** [review]
I think the coverage is really good on this. I don't see any improvements to be made. Your tests cover a wide range of scenarios including different user roles and permissions that should ensure proper component functionality.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
