### PR TITLE
yihan make task summary refresh after edit and save

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Main changes explained:
- Update file EditTaskModal.jsx for executing reload function after clicking on "update" button.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to Tasks Tab → Click Task → edit Hours/Estimated → Update
5. verify if page auto-refresh and shows the correct data.

### CODE REVIEW

**Review by tdkent — APPROVED** [review]
Local testing confirmed that editing fields (specifically Task Name and Estimated Hours) in the Edit Task Modal and clicking the Save button executed a page refresh.

Updated task data now displays on the Task Details page after this refresh. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/13f3532a-9fbb-415d-8b72-1f816402e2b8

**Review by AuroraLovesWhales — APPROVED** [review]
I have tested this PR and everything is working as intended. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/29a0e46e-b353-4c91-bee2-1956dbf3613c

**Review by HectorAgudelo — APPROVED** [review]
The changes to the code work as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/a3c81bd1-c836-424e-959b-926193291dda

**Review by mahamakhan — APPROVED** [review]
Function works as intended.

**Comment by AnishPandita** [comment]
Hi @AriaYu927, I tested the PR and it works as intended. Was able to replicate the functionality.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/c9039bec-3634-4a91-9f1b-01ef47da2239

**Comment by beblicarl** [comment]
I can confirm that this functionality works as intended. Great work!

[task-modal-reload_3000-2023.07.01-09_16_43.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/67775a5b-2573-4224-9954-66318a71bfca)

**Review by beblicarl — APPROVED** [review]

**Review by KurtisIvey — APPROVED** [review]
functions as intended

before editing:
pr963 before

after editing and the page auto refreshing
pr963 after

**Review by NidaZaki — APPROVED** [review]

**Pull request merged**
