### PR TITLE
Aaryaneil VolunteerTimeTab unit test

### PR DESCRIPTION
**Pull request by aaryaneil**
# Description
Unit test for `src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx`

## Main changes explained:
- StartDate component should correctly validate and display a success style if the start date is before the end date
- StartDate component should handle the case when the start date is null or undefined
- StartDate component should correctly validate and display an error style if the start date is after the end date
- WeeklyCommittedHours component should handle the case when the entered value is equal to the defined maximum
- WeeklyCommittedHours component should prevent users from entering hours beyond the defined maximum or below the minimum
- MissedHours component should handle the case when userProfile.missedHours is null or undefined
- MissedHours component should display the missed hours if the user cannot edit
- MissedHours component should only allow non-negative values for additional make-up hours

## How to test:
1. check into current branch
2. do `npm test VolunteeringTimeTab.test.js ` 

## Screenshots or videos of changes:
Screenshot 2024-05-24 at 10 22 17 PM

### CODE REVIEW

**Comment by KaushikMreddy** [comment]
Hi, 

Your test cases are working with one console error, please look into that
image
image

**Review by MinSun0814 — COMMENTED** [review]
All tests passed but there is erro in the console.
image

**Review by KurtisIvey — APPROVED** [review]
.

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
I like where you're going with your unit tests. However, I do have a few things I'd like to see integrated into this unit test.

1. test to make sure the viewtab component and all of its child components are rendering. As there is a dark mode, it would be beneficial to check that it works in dark mode as well.
2. testing of <StartDate/> when canEdit is false to confirm proper desired functionality
3. testing of <EndDate/> when canEdit is false to confirm proper desired functionality
4. Given the less desirable writing of VolunteeringTimeTab.jsx and it containing multiple components(not your fault), I would like to see the tests of these components seperated into their own blocks to keep things more organized.

**Review by deepthikannan — DISMISSED** [review]
image
All test cases passed with one console error. Kindly make the required changes.

**Review by jennZhang93 — DISMISSED** [review]
Tested locally and all tests passed. Good work!
Screenshot 2024-05-25 at 10 00 34 PM

**Comment by aaryaneil** [comment]
> I like where you're going with your unit tests. However, I do have a few things I'd like to see integrated into this unit test.
> 
> 1. test to make sure the viewtab component and all of its child components are rendering. As there is a dark mode, it would be beneficial to check that it works in dark mode as well.
> 2. testing of  when canEdit is false to confirm proper desired functionality
> 3. testing of  when canEdit is false to confirm proper desired functionality
> 4. Given the less desirable writing of VolunteeringTimeTab.jsx and it containing multiple components(not your fault), I would like to see the tests of these components seperated into their own blocks to keep things more organized.

Thank you for your input. I will add those test cases.

**Comment by iTvX** [comment]
Please solve the conflict, test all pass.

2024-05-25 at 23 32 57@2x

**Review by cecilia-uu — DISMISSED** [review]
All tests passed.
截屏2024-05-27 下午11 14 51

**Review by Sandhya1236 — DISMISSED** [review]
Upon reviewing the PR and performing the required tests, I checked into the current branch and executed npm test VolunteeringTimeTab.test.js. The tests verified the functionality of the StartDate, WeeklyCommittedHours, and MissedHours components. Specifically, the StartDate component was validated for correct success and error styles based on date inputs and handled null or undefined values properly. The WeeklyCommittedHours component successfully managed input constraints within defined maximum and minimum values. Additionally, the MissedHours component correctly displayed missed hours and ensured only non-negative values for make-up hours. All tests were executed successfully, confirming the robustness of the changes.

image

**Review by beblicarl — CHANGES_REQUESTED** [review]
There are these errors in the console

image

**Pull request closed without merging**
