### PR TITLE
Jiayu add teams limit see all

### PR DESCRIPTION
**Pull request by peter6866**
# Description
image

## Related PRS:
This frontend PR is based on PR #1905 
To test this frontend PR you need to checkout [backend PR 1017](https://github.com/OneCommunityGlobal/HGNRest/pull/1017).

## Main changes explained:
image

- Added a loading state for team members between clicking different teams

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3.  log as admin user
4.  Go to Other Links ->Teams
5.  Create two Teams , lets say Team A and Team B (you can use any existing Team as well)
6.  Add  the a **_testuser_1_** as team member to **_Team A_** **_and Team B_**
7.  Set the toggle switch to off  in Team A for **_testuser_1_**
8.  Login to the **_testuser_1_**'s  profile and verify if the user is only able  to see  the members of the  Team B and not Team A

## Screenshots or videos of changes:
https://www.loom.com/share/80d08159a46f40c8ab9871d27d729044?sid=1537e57a-a323-4124-84e8-37773be5d1b9

### CODE REVIEW

**Review by DiyaWadhwani — DISMISSED** [review]
Hi Jiayu,
Everything works as expected. Thank you for your clear instructions. I have attached a video where I have tested your changes below.
Thank you

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/ff374f84-1674-4d41-9456-99df5e61418a

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR with backend PR 1017. Everything is working perfectly. I followed your given steps and ran this PR successfully. I have attached a video for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/1c509a6a-46ba-48c7-a4a7-6308f5c079be

**Review by vijay10pk — DISMISSED** [review]
Everything works well as expected. Looks good to me.
Screenshot 2024-07-05 at 1 00 34 PM

Screenshot 2024-07-05 at 1 01 48 PM

Screenshot 2024-07-05 at 1 18 58 PM

Screenshot 2024-07-05 at 1 20 19 PM

**Comment by VaishnaviK23** [comment]
Hi Jiayu,
Everything works as expected. The instructions were clear and easy to follow, thanks. I have tested this with backend PR 1017. Attaching screenshots of the testing.
Thanks.
Screenshot 2024-07-05 at 1 16 12 PM
Screenshot 2024-07-05 at 1 17 24 PM
Screenshot 2024-07-05 at 1 17 49 PM
Screenshot 2024-07-05 at 1 18 12 PM
Screenshot 2024-07-05 at 1 18 47 PM

**Review by VaishnaviK23 — DISMISSED** [review]
Hi Jiayu,
Everything works as expected. The instructions were clear and easy to follow, thanks. I have tested this with backend PR 1017. Attaching screenshots of the testing.
Thanks.
Screenshot 2024-07-05 at 1 16 12 PM
Screenshot 2024-07-05 at 1 17 24 PM
Screenshot 2024-07-05 at 1 17 49 PM
Screenshot 2024-07-05 at 1 18 12 PM
Screenshot 2024-07-05 at 1 18 47 PM

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR. I have followed the given instructions and all the features work as stated.
Adding Nikhil Pittala to Team A and Team B with toggle switch off in A and not in B.
Screenshot (24)
Screenshot (26)
As you can see only teammates from TeamB can be seen.
Screenshot (27)

**Review by sahithidhulipala9 — APPROVED** [review]
PR worked perfectly!
Screenshot 2024-07-05 205049
Screenshot 2024-07-05 205130
Screenshot (106)

**Review by jinxyou — DISMISSED** [review]
Hi I tested all the functions of toggling the members of a team and I can verify that the toggle is working. Great work!
Screenshot 2024-07-05 203536
Screenshot 2024-07-05 203839
Screenshot 2024-07-05 203903

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR and it works as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/c54bee2c-e132-4ba3-a861-accc3931e312

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
On Adding a new team member the toggle button for permission is off, but on refresh the button is set to ON. Please fix that.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/c6e34a91-81b2-4993-97f3-36d546c80d51

**Comment by peter6866** [comment]
> On Adding a new team member the toggle button for permission is off, but on refresh the button is set to ON. Please fix that.
> 
>  PR-2412.mp4

The bug is fixed. Please review again.

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/c58f848b-c6e6-4fab-82c3-ca2650d9e5da

**Review by Shadhrush5 — APPROVED** [review]
Hi Jiayu,
I have completed the review of this PR #2412 along with the backend PR #1017. I followed the steps as mentioned:
Checked out with the branch "jiayu-limit-see-all" from both the frontend and backend project.
Logged in as an Admin
Created two teams Team A - Test PR#2412 and Team B - Test PR#2412
Screenshot 2024-07-08 at 9 19 19 AM

Added my volunteer test account in both teams along with a few more test accounts.
Disabled the "see all" toggle for my volunteer account in Team A .
Screenshot 2024-07-08 at 9 36 07 AM
Screenshot 2024-07-08 at 9 36 17 AM

Logged into my Volunteer account and saw that only team members from 'B' were visible in the dashboard.
Screenshot 2024-07-08 at 9 40 36 AM

Your changes are working as expected. Great work and thank you.

**Comment by one-community** [comment]
Thank you all, merging!

**Review by Sarath-3119 — COMMENTED** [review]
Working as expected in dev site.
https://www.loom.com/share/f91f3ee424074ae0a26bb0af36803789

**Pull request merged**
