### PR TITLE
Changhao - added unit tests for resetpasswordbutton

### PR DESCRIPTION
**Pull request by Changhao3220K**
# Description
added new unit tests cover edge cases for resetpasswordbutton.jsx

## How to test:
1. check into current branch
2. do `npm install` and ` npm test ResetPasswordButton.test.js` to run this PR locally
3. Verify all 9 tests are passed

## Screenshot:
Screenshot 2024-01-04 at 1 25 26 PM

### CODE REVIEW

**Review by ChengyanOo — APPROVED** [review]
Hi @Changhao3220K,

Outstanding work on your unit tests! They are impressively thorough, showcasing meticulous attention to detail. Additionally, your code is clean and well-organized, which is a significant accomplishment. Great job!

Attached is a screenshot highlighting the successful execution of these tests. Keep up the excellent work!

Screenshot 2024-01-04 at 17 20 02

**Review by beblicarl — CHANGES_REQUESTED** [review]
Hello @Changhao3220K Good job on the unit test cases
However can you move the test cases to the path as suggested in the unit-testing channel in slack for the PR to get approved/merged

**Review by bienzguoa — APPROVED** [review]
All tests passed as showing below! One suggestion: Consider using a modal or inline error message if possible but not using 'window.alert'.
Screenshot 2024-01-06 at 12 06 33 AM

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
As mentioned by Carl


The test file is also in the incorrect location. Please refer to the following link for the correct location <a>https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit</a> This will have to be resolved before merge can occur. 

All of your other tests are in the same boat with the improper test location. Would advise getting these resolved, so you don't keep making new test files in the wrong location.

**Comment by Changhao3220K** [comment]
> As mentioned by Carl
> 
> The test file is also in the incorrect location. Please refer to the following link for the correct location https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit This will have to be resolved before merge can occur.
> 
> All of your other tests are in the same boat with the improper test location. Would advise getting these resolved, so you don't keep making new test files in the wrong location.

Hi @KurtisIvey The file has been moved to the correct location, Thank you very much for your suggestions!

**Comment by Changhao3220K** [comment]
> Hello @Changhao3220K Good job on the unit test cases However can you move the test cases to the path as suggested in the unit-testing channel in slack for the PR to get approved/merged

Hi @beblicarl The file has been moved to the correct location, Thank you again for reminding me this!

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by sahilpatel18 — COMMENTED** [review]
Screenshot 2024-01-12 at 10 03 01 PM

**Pull request merged**
