### PR TITLE
Bug Fix: Timelog form clears on Submit

### PR DESCRIPTION
**Pull request by chrisweilacker**
Timelog form utilizing the timer was not clearing after a submit, so that if you used the timer again the timelog form would show your last entry.  This has been fixed.

### CODE REVIEW

**Comment by daoquangvy** [comment]
I keep getting this bug when I tried to submit the time from the timer. I wonder if this happens because I used the wrong Back-End branch? I'm currently using the development branch for the Back-End.

`Error: [Exception... "Unexpected error" nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)" location: "JS frame :: https://cdn.tiny.cloud/1/1rsz7lmakcvzg8trwjy91zht48pj4oubz8jrdyqxbbr63pvs/tinymce/5.7.0-107/themes/silver/theme.min.js :: render/< :: line 4" data: no]`

image

**Comment by chrisweilacker** [comment]
> I keep getting this bug when I tried to submit the time from the timer. I wonder if this happens because I used the wrong Back-End branch? I'm currently using the development branch for the Back-End.
> 
> `Error: [Exception... "Unexpected error" nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)" location: "JS frame :: https://cdn.tiny.cloud/1/1rsz7lmakcvzg8trwjy91zht48pj4oubz8jrdyqxbbr63pvs/tinymce/5.7.0-107/themes/silver/theme.min.js :: render/< :: line 4" data: no]`
> 
> image
> 
> However, If I refresh the page again, the time is still being submitted into the database correctly.

I am not sure at this is. I don't see it on my computer at all.  I don't think this is a backend issue as all the changes here didnt require any changes to the backend...maybe try getting the latest backend and rebuilding...

The error seems to be coming from TinyMCE

**Comment by daoquangvy** [comment]
I just tried it again and everything seems to work perfectly! Thank you for the update.

I will approve this.

**Review by daoquangvy — APPROVED** [review]
I just tried it again and everything seems to work perfectly! Thank you for the update.

I will approve this.

**Pull request merged**
