### PR TITLE
Jiadong improve efficiency of time log convert intangible time

### PR DESCRIPTION
**Pull request by yunshan111**
# Description
 Improve efficiency of time log page - esp converting intangible time to tangible and vice versa  

1. Leaderboard → Click a person’s time bar → Create intangible time entry for that person → save → refresh → click the “tangible” box to make that time entry tangible and you’ll see the process takes way longer than it should. It should instantly make it tangible
2. Refresh and confirm it saved 

## Related PRS (if any):
N/A

## Main changes explained:
- Fix bug in timeEntries.js

## How to test:
1. check into current branch
4. do **npm run install** and then **npm run start** run this PR locally
5. log as admin user
6. go to dashboard→ Leaderboard → Click a person’s time bar → Create intangible time entry for that person → save
7. repeat step 6 for multiple users. Open 5-10 tabs for each person's time entry.
8. click on the checkbox of tangible for each tab and test if they function correctly and evaluate the component's efficiency.

## Screenshots or videos of changes:
Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/5f8f2007-aa40-4698-8f3f-62a4e273e1ee

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/53397a3b-97aa-4586-9471-73c79aa92f4e

### CODE REVIEW

**Review by Shiwani99 — COMMENTED** [review]
Hi,
I tested your PR. It does work as expected, but I noticed a slight problem in the code. You have added dispatch(getTimeEntriesForWeek(timeEntry.personId, offset)); to timeEntries.js file under actions so the problem is that I worked on a PR related to timelog details getting updated with other user details when a user records timelog in someone else's timelog page. This is the PR I'm talking about https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1412. I made that change in actions by adding timeEntry.curruserId instead of timeEntry.personId as that would get the time entries of logged in user in any user's timelog page instead of their time entries. curruserId refers to the user id of the user whose timelog page is currently being viewed, so when you change that to personId you will basically get the time entries of the logged in user in other user's timelog page too when you record your timelog.

this is before your change in timeEntries.js under actions

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/e77aa79a-5fd7-48be-b306-7a55691e037f


This is after your change in timeEntries.js under actions

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/44b3e58b-ad1b-4a1b-9b90-c025e77c715c

I have noticed this change in your code related to timeEntries which actually is reversing the PR I had mentioned before. Overall, you have done a great work in fixing the bug and I am able to tick and untick tangible time without any delay. Please do confirm with someone on your change in /actions/timeEntries.js since that might bring up the bug that was previously reported and fixed.

**Review by navneeeth — COMMENTED** [review]
Hello, @yunshan111! I tested your implementation and the function to click on the 'Tangible' checkbox works as expected and also for multiple users in different tabs. However, as @Shiwani99 mentioned, please review the code to make changes such that it does not undo/reverse a previous fix and I will then approve the PR.

### Testing Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/c0a8d80a-951d-4853-b709-8d0af5916f1e

**Review by pika-chu11 — APPROVED** [review]
Hi @yunshan111 , I have tested the function and works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/34ee5e94-1293-417d-a4ca-bb7e6ab7be8d

**Review by Shiwani99 — APPROVED** [review]
Hi,
I tested your PR and it works as expected. There is no issue in the timer and I am able to tick and untick from intangible to tangible now without any delay.

**Pull request merged**
