### PR TITLE
Ivy-Create a visualization section for the 5-letter codes

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
Needs new developer to finish and debug: [1678](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1678)→[2329](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2329))
Other Links → Reports → Weekly Summaries Reports
When codes and/or Colors are selected from the “Select Team Code” and “Select Color” sections of the Weekly Summaries Reports page, I’d like a series of useful visualizations to come up between those selection rows and the people’s info below
Pie chart showing selected teams and # of people in each oe, plus the total for all selected teams in the middle. 
This is so I can easily see how many people are in combinations of teams for things like balancing the Admin’s duties overseeing them
Summary of people and their roles in each team - it’d be super cool if clicking a person in this summary would bring you to their info on the page too
This is so I can easily see who the various roles are in a team without having to go to the Teams page
Any others that would fit and you might think would looks cool and be beneficial once I’ve got 300+ people in this list
Make sure the Open PDF, Load Badges, and Load Trophies buttons can still be used with these views too
## Related PRS (if any):
This frontend PR is related to the `backend's development branch`.

…
## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/4aeb09ed-85a3-45f4-800b-a769f772cd47
Screenshot 2024-09-06 at 3 10 47 PM

Screenshot 2024-09-06 at 3 05 32 PM
And please not 
## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/be0b03d4-5143-437c-bef1-f0ded740f186

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.

**Review by Saniya98 — APPROVED** [review]
Everything works as expected

**Review by oliviahyw — APPROVED** [review]
I have tested this PR and everything is working as expected.
PR2599

**Review by vishnupriyaatheti — CHANGES_REQUESTED** [review]
@20chen-7 I have reviewed your changes 
Below are the few observations & issues.
issue 1 : the text is not displaying properly. highlighted in the attached images.
issue 2: When selected all teams/all colors the display of pie chart is not user friendly
FE PR 2599 text is being cut
FE PR 2599 all team   color selected by biostatus
FE PR 2599 all teams selected
FE PR 2599 text not diaplayed properly parathesis missing

**Comment by sri0606** [comment]
Hello @20chen-7 , I've reviewed your PR, and everything runs without any errors.

But below are some issues I found,

* **Percentages Not Adding Up to 100%**: The percentages sometimes add up to slightly less or more than 100%, likely due to rounding errors. You can add or subtract the difference to ensure that the total adds up to 100%. For example, if percentages add up to 99.8%, adjust the largest slice by 0.2% to make the total 100%. 

* **Frequency Count Not Updating**: When selecting new checkboxes, only the percentages are updated. The frequency count does not reflect these changes.

* **Visibility and Zooming of Names**: As previously mentioned, the names are not visible. Additionally, there's no option to zoom in. It would be helpful to implement a popup dialog box for the pie chart that allows zooming and better visibility of names.

* **Table View UI/UX**: When selecting "Select All" or a large number of checkboxes, the table on the right becomes excessively long. You should probably consider implementing vertical scrolling for the table and ensuring its size is relative to the pie chart on the left. This adjustment will help avoid excessive empty space below the pie chart.


https://github.com/user-attachments/assets/3bf1fb9b-b398-4a95-b3bf-43363eb569b1

PR2599

**Comment by FayeLV** [comment]
Hi, 
everything works great overall, but I found a few small issues that might need your attention:
Arrow Position Adjustment: The up and down arrows are too close to the text. It is recommended to add padding or margin to increase the space between them for better readability and visual appeal.
Text Display Optimization: The text does not display fully on different screen sizes. It is advised to adjust the text layout to ensure it appears correctly across all screen dimensions.
Text Color Contrast Issue: The white text is difficult to read against certain background colors. Consider adjusting the text or background color to improve visibility.
Snipaste_2024-08-31_12-55-43
Snipaste_2024-08-31_12-59-47
Snipaste_2024-08-31_13-01-10

**Review by Parth-tech — CHANGES_REQUESTED** [review]
Hey Xiaoyu (Ivy),
The chart and the table are working nicely but there are a few issues due to which hamper the visual appeal:

1. When one slice of the pie is extremely large the others get crushed and their text would overlap.
2. The text helps us identify a pie is clipped at times.
3. Selecting a team code which has many member leads to a very long table and hence huge vertical scrolling.

If these issues could be addressed then the visualization would be extremely useful and robust.

`Image References:`
`1. Overlapping text in pie chart`
Screenshot 2024-08-31 at 12 23 23 PM
`2. Extremely large table hence the vertical scrolling bar is very big`
Screenshot 2024-08-31 at 12 23 41 PM
`3. Text for each pie is being clipped`
Screenshot 2024-08-31 at 12 24 30 PM

**Review by crystallow1168 — CHANGES_REQUESTED** [review]
Hi @20chen-7 ,

The pie and the table looks good, and here are my observations:

- ✅ Pie chart showing selected teams and # of people in each oe, plus the total for all selected teams in the middle.
    - ❗️ Issue A (refer to image): The text is cut off when the screen on smaller screen
    - ❗️ Issue B (refer to image): The text is overlapping when the pie sections are too close to each other
- ✅ Summary of people and their roles in each team is shown
    - ✅ Clicking a person in summary table would direct user to the selected person's profile page
    - ❗️ Length of the table may get too long when there are many members on the table, which may lead to infinite scrolling
- ✅  Open PDF is working
- ❗️ Load Badges button: I'm not too sure how to test the functionality of this but when the button is clicked, button's text changed to 'Hide Badges'
- ❗️ Load Trophies button: Not sure how to test this functionality either, and button text stays the same after clicking the button
    
image
image

**Review by strallia — CHANGES_REQUESTED** [review]
| Key |
| --- |
| ✅ = Tested and works |
| ❌ = Issues that need fixing |

✅ Pie chart and table displays when codes and/or Colors are selected from the “Select Team Code” and “Select Color” sections of the Weekly Summaries Reports page.

✅ Pie chart shows selected teams and # of people in each, plus the total for all selected teams in the middle.

✅ Can view user's profile page via hyperlink in table.
- ❌ In the table, the hyperlinks for each row redirect to the same profile page which seems redundant. Also from a user experience perspective, I expected the hyperlinks in the Role column to redirect to more info about the role and not the user's profile. If only redirection to a user’s profile is needed, I suggest removing the hyperlinks in the Role column.

✅ Open PDF works.

❌ I'm not sure how to test the Load Badges button. It does toggle between Load Badges and Hide Badges, but I don’t see a difference on the page. I also don’t see any changes clicking Load Trophies.

❌ In dark mode, the background color of the table rows are inconsistent. Some have a light gray background while others are dark navy. For visual consistency with the rest of the page’s background, I think all the rows should have a dark navy background.
Screenshot 2024-09-03 at 8 28 29 PM

❌ In dark mode, the color of the header text in the table is hard to see—it is white text on light gray background. More color contrast is needed for readability.
Screenshot 2024-09-03 at 8 34 26 PM

❌ When I put the page in dark mode and then open a user profile page by clicking their name in the table, the user’s profile page is in light mode. I expected the user profile page to also be in dark mode.
https://github.com/user-attachments/assets/ab99954d-112b-449f-b33d-7bde647e4502

**Review by ddshah878 — COMMENTED** [review]
The chart, table, and open PDF feature are functioning well, but there are a few issues.

- The text gets cut off on the pie chart.
- When the pie sections are too close, the text overlaps.
- In dark mode, the table header text is difficult to read.
Dark(1)

- The yellow background makes the text hard to read in both light and dark modes.
- In dark mode, the background color of the table rows is inconsistent, some rows have a white background while others have a dark navy background.

Dark(2)

- The yellow background makes the text hard to read in both light and dark modes.
White

- The "Open PDF" function works.

- However, I’m unsure how to test the "Load Badges" button. It toggles between "Load Badges" and "Hide Badges," but I don't see any visible change. Clicking "Load Trophies" also doesn't seem to do anything.

**Review by Jingyii800 — DISMISSED** [review]
I have tested this feature, and it works as expected. The chart visualized the team summary.

https://github.com/user-attachments/assets/ab118fce-3a40-43ce-ab6e-edd7ca0b7ceb

**Comment by sud306** [comment]
Hello,
Overall the changes are working as expected.
1. Here, I have selected few Team Codes.


PR2599_1

2. When Total comes to 1, there is a white line coming on right radius of the circle which can be avoided for better look. Other than that, everything looks great!

 
PR2599_3

3. The 'Open PDF button' works fine.

**Review by yashwanth170 — COMMENTED** [review]
1. When I select all teams the pie chart is not clear
2. The table may become excessively long when there are many members, leading to infinite scrolling. This issue can be resolved by implementing pagination or something
show_charts

**Review by strallia — DISMISSED** [review]
### These issues from my first comment are still present:

> In the table, the hyperlinks for each row redirect to the same profile page which seems redundant. Also from a user experience perspective, I expected the hyperlinks in the Role column to redirect to more info about the role and not the user's profile. If only redirection to a user’s profile is needed, I suggest removing the hyperlinks in the Role column.

> I'm not sure how to test the Load Badges button. It does toggle between Load Badges and Hide Badges, but I don’t see a difference on the page. I also don’t see any changes clicking Load Trophies.

I'm still unsure how to test this and what changes I should see.

> In dark mode, the background color of the table rows are inconsistent. Some have a light gray background while others are dark navy. For visual consistency with the rest of the page’s background, I think all the rows should have a dark navy background.

(Please let me know if these changes are not relevant to this PR so I can approve it)

### These issues have been fixed. Great work!:

> In dark mode, the color of the header text in the table is hard to see—it is white text on light gray background. More color contrast is needed for readability.

Screenshot 2024-09-06 at 5 06 06 PM

> When I put the page in dark mode and then open a user profile page by clicking their name in the table, the user’s profile page is in light mode. I expected the user profile page to also be in dark mode.

https://github.com/user-attachments/assets/fff70329-3f25-44ca-a5af-f88bad921c36

**Comment by 20chen-7** [comment]
> ### These issues from my first comment are still present:
> > In the table, the hyperlinks for each row redirect to the same profile page which seems redundant. Also from a user experience perspective, I expected the hyperlinks in the Role column to redirect to more info about the role and not the user's profile. If only redirection to a user’s profile is needed, I suggest removing the hyperlinks in the Role column.
> 
> > I'm not sure how to test the Load Badges button. It does toggle between Load Badges and Hide Badges, but I don’t see a difference on the page. I also don’t see any changes clicking Load Trophies.
> 
> I'm still unsure how to test this and what changes I should see.
> 
> > In dark mode, the background color of the table rows are inconsistent. Some have a light gray background while others are dark navy. For visual consistency with the rest of the page’s background, I think all the rows should have a dark navy background.
> 
> (Please let me know if these changes are not relevant to this PR so I can approve it)
> 
> ### These issues have been fixed. Great work!:
> > In dark mode, the color of the header text in the table is hard to see—it is white text on light gray background. More color contrast is needed for readability.
> 
> Screenshot 2024-09-06 at 5 06 06 PM
> > When I put the page in dark mode and then open a user profile page by clicking their name in the table, the user’s profile page is in light mode. I expected the user profile page to also be in dark mode.
> 
>  Screen.Recording.2024-09-06.at.4.56.10.PM.mov

For the profile, waiting for Jae's comments, and for 'Load Badges' those btns, not necessary for this PR.

**Comment by strallia** [comment]
I tested and confirm the following issue is fixed. Nice work!

> In dark mode, the background color of the table rows are inconsistent. Some have a light gray background while others are dark navy. For visual consistency with the rest of the page’s background, I think all the rows should have a dark navy background.
Screenshot 2024-09-07 at 11 03 08 AM

I will follow up on the profile-related issue when Jae gets back to you about it.

**Review by swaroop-2007 — CHANGES_REQUESTED** [review]
@20chen-7 
I’ve reviewed the PR, and everything works well except for two issues:

1. After clicking "Load Badges," there’s no visible change aside from the button text changing to "Hide Badges."

2. With the "Load Trophies" button, there’s no visible change, and the button text stays the same.
Screenshot (378)
3. In the mobile view, I am unable to see the text on the charts. Please refer to the screenshot below. 
Screenshot (379)

Other than that, nice work on this!

**Comment by 20chen-7** [comment]
> Hello, Overall the changes are working as expected.
> 
> 1. Here, I have selected few Team Codes.
> 
> PR2599_1
> 
> 2. When Total comes to 1, there is a white line coming on right radius of the circle which can be avoided for better look. Other than that, everything looks great!
> 
> PR2599_3
> 
> 3. The 'Open PDF button' works fine.
> 4. I could not find visible difference when clicking 'Load Badges' and 'Load Trophies'.

for your 

> I tested and confirm the following issue is fixed. Nice work!
> 
> > In dark mode, the background color of the table rows are inconsistent. Some have a light gray background while others are dark navy. For visual consistency with the rest of the page’s background, I think all the rows should have a dark navy background.
> 
> Screenshot 2024-09-07 at 11 03 08 AM
> I will follow up on the profile-related issue when Jae gets back to you about it.

Not sure why your mode is inconsistent, mines looks consistent.
https://github.com/user-attachments/assets/98c9bde0-c4fa-4587-ba11-24c71695531f

**Comment by 20chen-7** [comment]
> @20chen-7 I’ve reviewed the PR, and everything works well except for two issues:
> 
> 1. After clicking "Load Badges," there’s no visible change aside from the button text changing to "Hide Badges."
> 2. With the "Load Trophies" button, there’s no visible change, and the button text stays the same.
>    Screenshot (378)
> 3. In the mobile view, I am unable to see the text on the charts. Please refer to the screenshot below.
>    Screenshot (379)
> 
> Other than that, nice work on this!

For the first and second, plz check the description, this is a fix for previous developer, and I am not responsible for these. For the third, plz check again.Screenshot 2024-09-10 at 5 11 41 PM

**Comment by strallia** [comment]
@20chen-7 To clarify, the dark mode row colors are consistent and working for me now. Although, when I apply the recent commits you made on 9/10/2024, I cannot run the app locally because it’s failing a test. See pic for reference:

> Screenshot 2024-09-11 at 2 24 21 PM

The only issue remaining before I can approve this PR is the first one raised in [this comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2599#pullrequestreview-2287286133) about removing redundant hyperlinks in the Role column. From your previous replies, it sounded like you were waiting on comments from Jae. Can I get a follow-up on what he said?

**Comment by 20chen-7** [comment]
> @20chen-7 To clarify, the dark mode row colors are consistent and working for me now. Although, when I apply the recent commits you made on 9/10/2024, I cannot run the app locally because it’s failing a test. See pic for reference:
> 
> > Screenshot 2024-09-11 at 2 24 21 PM
> 
> The only issue remaining before I can approve this PR is the first one raised in [this comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2599#pullrequestreview-2287286133) about removing redundant hyperlinks in the Role column. From your previous replies, it sounded like you were waiting on comments from Jae. Can I get a follow-up on what he said?

If you check the latest dev, you will find that unit test also failed, not related to my PR. Moreover, I will leave in this week.

**Comment by SFA23SCM35V** [comment]
I have tested this PR and everything is working as expected.
PR #2599
PR#2559

**Review by SFA23SCM35V — APPROVED** [review]
Screenshot 2024-09-12 003039

**Review by swaroop-2007 — DISMISSED** [review]

**Review by neeharikakoniki — APPROVED** [review]
When codes and/or Colors are selected from the “Select Team Code” and “Select Color” sections of the Weekly Summaries Reports page, the visualizations come up between those selection rows and the people’s info below.
image
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
