### PR TITLE
Nahiyan_New header UI functionality

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Nav items on the right of header now collapse into two rows when viewport gets smaller

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner/volunteer account
5. ensure header UI is working properly

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/5be51647-a587-4215-ba29-f3b393741e4a

### CODE REVIEW

**Review by KyreneAF — APPROVED** [review]
- Header dynamically changes as screen size changes and message disappears at 1050px
- Header behaves normally even with drop-downs open and buttons still work! Looks great! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/b3cadd5c-1ee3-4738-8da4-fea6e810fb25

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/77253385-76b8-4ced-a396-16f8d36a1f72

**Review by hbodgal — APPROVED** [review]
image

I have tested on multiple screen sizes. It works well.

**Review by curiousfancier — APPROVED** [review]
Works as expected it is changing dynamically with screen size.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/27274513/7cecf49e-46ac-4d24-9994-39485f1c6d2e

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
