### PR TITLE
Ajay - fix tab preview names v2

### PR DESCRIPTION
**Pull request by AJAYINAVOLU**
# Description
This PR adds a feature that allows users to see a preview name for each tab in the application without needing to click and view the content. By utilizing useLocation and dynamically updating document.title, improves navigation and user experience across the entire project.
This PR is an update to [PR 2815](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2815) and refactors tab title handling by consolidating it into app.jsx, reducing file changes from 67 to 1. Future updates are simplified with route-based titles set in one location, improving maintainability and performance.

Fixes # (PRIORITY MEDIUM) Jae: Add tab preview names 

## Related PRS (if any):
This frontend PR is related to the development branch of the [backend](https://github.com/OneCommunityGlobal/HGNRest) repository.

## Main changes explained:
- Updated App.jsx to handle all document titles in a single UpdateDocumentTitle component using a route-pattern array, reducing file changes from 67 to 1.

## How to test:
1. Check into the current frontend branch and the development backend branch.
2.  Do npm install and npm run start:local to run this PR locally.
3. Clear site data/cache.
4. Log in as an owner-user.
5. For each endpoint, please: -> Navigate to the URL.
6. Check that the browser tab displays a relevant preview name based on the current page content.
7. The list of endpoints are:

1. **Dashboard:**
   - `/dashboard` 
   - `/dashboard/:userId`

2. **Profile Setup:**
   - `/ProfileInitialSetup/:token`

3. **Timelog:**
   - `/timelog/` → **Title**: `Timelog` 
   - `/timelog/:userId`

4. **Members:**
   - `/project/members/:projectId`

5. **People Report:**
   - `/peoplereport/:userId`

6. **Project Report:**
   - `/projectreport/:projectId`

7. **Team Report:**
   - `/teamreport/:teamId`

8. **Task Edit Suggestions:**
   - `/taskeditsuggestions`

9. **Inventory:**
   - `/inventory/:projectId`
   - `/inventory/:projectId/wbs/:wbsId`

10. **Weekly Summaries Report:**
    - `/weeklysummariesreport`

11. **Reports:**
    - `/reports`

12. **Team Locations:**
    - `/teamlocations`

13. **Projects:**
    - `/projects`
    - `/wbs/tasks/:wbsId/:projectId/:wbsName`

14. **WBS:**
    - `/project/wbs/:projectId`
    - `/wbs/tasks/:taskId`
    - `/wbs/samefoldertasks/:taskId`

15. **User Management:**
    - `/usermanagement`

16. **Badge Management:**
    - `/badgemanagement`

17. **Permissions Management:**
    - `/permissionsmanagement`
    - `/permissionsmanagement/:userRole`

18. **Teams:**
    - `/teams`

19. **Announcements:**
    - `/announcements`

20. **Total Organization Summary:**
    - `/totalorgsummary`

### BM Dashboard Routes:

21. **BM Dashboard:**
    - `/bmdashboard`
    - `/bmdashboard/login`

22. **BM Purchase Routes:**
    - `/bmdashboard/materials/purchase`
    - `/bmdashboard/reusables/purchase`
    - `/bmdashboard/equipment/purchase`
    - `/bmdashboard/tools/purchase`

23. **BM Projects:**
    - `/bmdashboard/projects/:projectId`

24. **BM Lesson List:**
    - `/bmdashboard/lessonlist/`

25. **BM Material and Reusable Updates:**
    - `/bmdashboard/materials/update`
    - `/bmdashboard/reusables/update`

26. **BM Materials and Consumables Add:**
    - `/bmdashboard/materials/add`
    - `/bmdashboard/consumables/add`

27. **BM Equipment and Tools:**
    - `/bmdashboard/equipment/add`
    - `/bmdashboard/equipment/:equipmentId`
    - `/bmdashboard/tools`
    - `/bmdashboard/tools/add`
    - `/bmdashboard/tools/log`
    - `/bmdashboard/tools/:toolId`
    - `/bmdashboard/tools/:equipmentId/update`

28. **BM Lesson Form:**
    - `/bmdashboard/lessonform/:projectId`
    - `/bmdashboard/lessonform/`

29. **BM Inventory Types:**
    - `/bmdashboard/inventorytypes`

### Other Routes:

30. **Login:**
    - `/login`
    - `/logout`
    - `/forgotpassword`

31. **Email Subscription:**
    - `/email-subscribe`
    - `/email-unsubscribe`

32. **Profile and Password Update:**
    - `/userprofile/:userId`
    - `/userprofileedit/:userId`
    - `/updatepassword/:userId`
    - `/forcePasswordUpdate/:userId`

33. **Other Pages:**
    - `/infoCollections`
    - `/` (default route)

## Screenshots or videos of changes:
image
image
image
image
image

### CODE REVIEW

**Review by CodewithKoushica — DISMISSED** [review]
Nicely done! The centralized approach to document title updates is now streamlined and easy to maintain. I appreciate how this refactor simplifies future additions and edits. The implementation is clean, efficient, and performs well across the app.

Great job on the changes—approving this PR!

Screenshot 2024-10-31 at 2 33 53 PM
Screenshot 2024-10-31 at 2 41 15 PM
Screenshot 2024-10-31 at 2 41 22 PM
Screenshot 2024-10-31 at 2 41 30 PM

**Review by samarth9201 — APPROVED** [review]
Verified changes. Can verify that the preview name are correct and relevant.

Screenshot 2024-11-01 003548
Screenshot 2024-11-01 003724
Screenshot 2024-11-01 003815
Screenshot 2024-11-01 003917
Screenshot 2024-11-01 003940
Screenshot 2024-11-01 003954
Screenshot 2024-11-01 004012
Screenshot 2024-11-01 004035
Screenshot 2024-11-01 004054
Screenshot 2024-11-01 004109

**Review by anirudhsk2107 — APPROVED** [review]
The tab preview name changes are working in all the pages mentioned.
Attached a few screenshots as example -
Screen Shot 2024-11-01 at 1 28 17 PM
Screen Shot 2024-11-01 at 1 28 11 PM
Screen Shot 2024-11-01 at 1 27 47 PM
Screen Shot 2024-11-01 at 1 27 40 PM
Screen Shot 2024-11-01 at 1 27 08 PM
Screen Shot 2024-11-01 at 1 25 36 PM
Screen Shot 2024-11-01 at 1 25 28 PM
Screen Shot 2024-11-01 at 1 25 15 PM
Screen Shot 2024-11-01 at 1 25 07 PM
Screen Shot 2024-11-01 at 1 24 54 PM
Screen Shot 2024-11-01 at 1 24 43 PM
Screen Shot 2024-11-01 at 1 24 17 PM
Screen Shot 2024-11-01 at 1 24 04 PM
Screen Shot 2024-11-01 at 1 20 38 PM
Screen Shot 2024-11-01 at 1 20 26 PM
Screen Shot 2024-11-01 at 1 19 51 PM
Screen Shot 2024-11-01 at 1 19 44 PM
Screen Shot 2024-11-01 at 1 19 14 PM

**Review by hqzhu0913 — APPROVED** [review]
Verify most links work. Just some of the links's pages have not implemented yet. 
Screenshot 2024-11-01 at 4 18 12 PM
Screenshot 2024-11-01 at 4 18 06 PM
Screenshot 2024-11-01 at 4 16 19 PM

**Review by Jingyii800 — DISMISSED** [review]
I have tested the feature. All the tab preview looks good and match the page content. Very clear and user friendly improvement.
Great job!!
Screenshot 2024-11-01 215929
Screenshot 2024-11-01 220306
Screenshot 2024-11-01 220255
Screenshot 2024-11-01 220245
Screenshot 2024-11-01 220239
Screenshot 2024-11-01 220218
Screenshot 2024-11-01 220206
Screenshot 2024-11-01 220145
Screenshot 2024-11-01 220138
Screenshot 2024-11-01 220114

**Review by nikhilgiri0226 — DISMISSED** [review]
I have reviewed the PR and the tab names are visible across the Application. Most of them were accessible and in few of the routes there was a white screen but the route was working fine.
Kindly find the screenshots below.

Dashboard
image
image

Profile
image

Project
image
image

People report
image

Team report
image

Task Edit Suggestion
image

Weekly Summary project report
image

Reports
image

Team locations
image

Projects
image
image

WBS
image
image
image

User Management
image

Badge Management
image

Permission management
image
image

Teams
image

Announcements
image

Total Organization Summary
image

BM Dashboard routes
image
image
image
image
image
Not working - BM Dashboard projects routes but project/:project id was working fine.
image
image

BM Lesson list
image

BM Material and Reusable Updates
image
image

BM Materials and Consumables Add
image
image

BM Equipment and Tools
image
White screen on /tools and /tools/log but /tools/add is working fine
image
image
image

BM Lesson Form
image
image

BM Inventory types
image

Login
image

Forget PW
image

Email subscribe and unsubscribe
image
image

Profile and Password Update
image
image
image
image

Info collections - The route was working fine but there was a white screen.
image

**Review by aaryaneil — DISMISSED** [review]
Tab preview name changes correctly based on the endpoint visited.
This is a really nice addition to the application. Great work.
Screenshot 2024-11-02 at 9 29 36 PM
Screenshot 2024-11-02 at 9 30 02 PM
Screenshot 2024-11-02 at 9 30 30 PM
Screenshot 2024-11-02 at 9 31 30 PM
Screenshot 2024-11-02 at 9 31 57 PM
Screenshot 2024-11-02 at 9 32 09 PM
Screenshot 2024-11-02 at 9 32 20 PM
Screenshot 2024-11-02 at 9 32 31 PM
Screenshot 2024-11-02 at 9 32 39 PM
Screenshot 2024-11-02 at 9 33 04 PM
Screenshot 2024-11-02 at 9 33 13 PM
Screenshot 2024-11-02 at 9 33 17 PM
Screenshot 2024-11-02 at 9 33 26 PM
Screenshot 2024-11-02 at 9 33 35 PM
Screenshot 2024-11-02 at 9 33 48 PM
Screenshot 2024-11-02 at 9 34 00 PM
Screenshot 2024-11-02 at 9 34 05 PM
Screenshot 2024-11-02 at 9 34 15 PM
Screenshot 2024-11-02 at 9 34 40 PM

**Pull request merged**
