### PR TITLE
Shiwani Fix Log time entry for other users at other user’s timelog page

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Screenshot 2023-10-12 at 3 52 24 PM

## Main changes explained:
- Created two separate user ids called LoggedInUserId and currUserId where in LoggedInUserId will have the user id of the logged in user and currUserId will have the user whose time log page is being visited. Added these two user ids in TimeEntry.jsx, Timer.jsx, TimeEntryForm.jsx.
- Added a new user profile variable called curruserProfile in TimeEntryForm.jsx which will have the user profile details of the logged in user which is present in redux store payload. This is required to avoid mixing up of details in mongoDB as initially userProfile was used but it contains the user profile details of the user whose time log page is being viewed which leads to mongo db update for the logged in user with the other user details.
- Added getUserProfile action with current user id instead of logged in user id, and getTimeEntriesForWeek action to update the redux store for the 0th week since redux store is updated with logged in user's 0th week details for TimeEntries state variable.
- Added curruserId to TimeEntry object under handleSubmit in TimeEntryForm.jsx
- Updated TimeEntries.js under actions for updateTimeEntriesForWeek action which in turn calls GetTimeEntriesForWeek by changing timeEntry.personId with timeEntry.curruserId so that the time entries are updated with user whose time log page is being viewed so that the frontend displays the time entries accordingly.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as any user
4. go to dashboard→Leaderboard->click the progress bar for any of the users listed under leaderboard
5. Record time in the chosen user's time log page
6. Verify that after recording time log, user profile details of logged in user does not change. Check if the time log details of logged in user does not display in other user's time log page.
7. Additionally, test by recording in own time log page by clicking on the progress bar adjacent to your name, and test by recording time in dashboard. The time log details will change for logged in user's time log page and dashboard in this case.
8. Feel free to leave any comments and screen recordings of your test.

## Screenshots or videos of changes:

before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/91ae9679-78d0-40c2-94eb-022e77c86b9b

after:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/4ef9b068-21d9-4e66-809b-ee18b3deb3ed

## Note:
- Time log will get updated for logged in user's time log page and when user records time log in dashboard.
- Time log details of logged in user should not appear if you are viewing someone else's time log page.

### CODE REVIEW

**Review by yangfan2001 — DISMISSED** [review]
Hi, I have read and tested your PR. It looks great. After I viewed others profile and log my time in others time log page, the dashboard and others time log page displayed as expected. Great Job!
before add time
image
after add time
image
image

**Review by TuanDinh140194 — COMMENTED** [review]
Hi! I have tested your PR. I have logged in as Owner account. Next, I record the time and click on the progress bar of the other users. Next, I added the time on the other users and notice that the time didn't update for other users. After come back to my dashboard, I notice it updated on the logged in users.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/0ddfd97f-fdc0-42c1-91b4-f45fcffc263c

**Review by JYXiao-2021 — DISMISSED** [review]
Hi, I test this pr and it works as intended.  it shows in the video. I log in as owner account and to log time in the volunteer account. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/dca0db0a-8c9f-41d1-9829-8a238ebfa6f8

**Comment by Cloid** [comment]
Hi there.

I tested the base case by using two separate Volunteer profiles. I submitted a timer entry within a different volunteer's profile and the bug-fix works. I also tested manually submitting a volunteer time entry (as Admin) for a volunteer profile and then submitting the Admin's time entry and it works as expected. Good job! 

Attached is a video of me testing both these cases.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/4d1897a3-ed42-4f61-93bf-dc3e89c81ad0

**Review by Cloid — APPROVED** [review]

**Review by eduhorta — APPROVED** [review]
Hey @Shiwani99!

I've tested your PR and here is a video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/1eca6a0d-8b58-4f30-ae02-27f2134582e9

The logged time is not being added to the profile you are currently accessing.
Great job! 👍

**Review by DavidC0126 — DISMISSED** [review]
Hi @Shiwani99 I tested the PR and it works as described, good job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/06f314eb-f43e-4154-b7e9-6d8caa0cb1f7

**Review by lacnoskillz — DISMISSED** [review]
Hello @Shiwani99
I confirmed the bug while testing in development. 
I pulled your code and it seems to be working as intended as I don't see the logged in users time log being displayed when saving while viewing another users time log.
Nice work

[Untitled_ Oct 17, 2023 2_14 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/f279bc91-4a14-45a8-9553-14661fc7d56e)

**Review by tsunami776 — APPROVED** [review]
Hi @Shiwani99, I tested your PR locally and it works as described. I verified that user profile detail of logged in user will not change after recording time log. Also clicking on progress bar then record time will change logged in user's time. Great work!

Test video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/fa39f20a-735d-4d97-b8b0-85a9d6b768cf

**Review by StrawberryCalpico — DISMISSED** [review]
Hi, I tested your PR, and it works as expected! Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/767f1dad-181c-4d76-8bf2-76f914391f56

**Review by belagaam — DISMISSED** [review]
tested the PR as per the instructions. Everything works as expected. 

Screenshot 2023-10-21 at 4 26 27 PM
Screenshot 2023-10-21 at 4 26 44 PM

**Review by Iris-Song — APPROVED** [review]
Hi, I have tested and it works as intended. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/39618dfd-1b97-41e7-89ee-3960f0425d4b

**Review by Shubhu0 — APPROVED** [review]
Hi @Shiwani99 Tested and Reviewed your PR. It is working as intended. Great work on it as everything is working as it should and looks good!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/f0811351-ad33-42b5-af89-fbb70c2e0520

**Comment by RheaWu1212** [comment]
Hi I tested your PR, here's video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/bdeef0a7-653b-46c8-b68c-fb533209a63e

logged in as Admin account and adding time on volunteer account, no time has added, great wotk!

**Comment by one-community** [comment]
Thank you all, moving to final review!

**Review by KurtisIvey — DISMISSED** [review]
Functions as intended. While I did not experience the issue you originally noted while on different versions of the current dev branch, I did experience an issue where when I'd submit time under similar conditions, it would switch to my own user's timelog. This fix in pr1412 enhanced the user experience by no longer allowing that unintentional switch to occur.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/516da40c-5ebb-4a0c-b067-80dcedcebeb1


pr1412 improves user experience

Good job 👍🏻

**Pull request merged**
