### PR TITLE
Zijie lint fix for reports component Second to Last Phase

### PR DESCRIPTION
**Pull request by iTvX**
# Description
Lint fix for Reports component, this is phase 13 （Second to Last Phase）.

## Files changed
src/components/Reports/PeopleReport/PeopleReport.jsx

eslint test:
CleanShot 2023-10-05 at 02 56 22@2x

# How to Test

To test this pull request:

- Check out the current branch
- Run `npm install` and `npm run start:local` to run this PR locally  
- Log in as an admin user
- Check all the functionality of the report is the same as before, and see if any bugs have appeared. (Please record a video)

(Optional)
- Set up ESLint in VSCode/ IntelliJ IDEA, I personally use IntelliJ IDEA
- Delete .eslintignore file in the root: `rm .eslintignore`
- `npx eslint src/components/Reports/PeopleReport/PeopleReport.jsx`
- `git restore .`

I have complete confidence that **the code will pass the ESLint tests.** Therefore, I kindly request that you **focus on testing the frontend**. Specifically, please ensure that the **report functionality remains consistent** with how it operated previously. Thank you for your time and effort!

### CODE REVIEW

**Review by Iris-Song — APPROVED** [review]
Loading total project report/ total team report/ total team report are slow. Other parts looks well.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/20955ec8-9181-4033-8e17-24b0b30c2085

**Review by luisarevalo21 — APPROVED** [review]
Hello @iTvX, 

I tested your PR and works as intended. Great work!
Running the scripts returns no error and the application runs as normal. 

I did notice a log to the console, but didn't see any in your code. So, I think its unrelated tot his PR. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/e4098ac1-9dba-44d3-adc4-69790e02a735

Screenshot 2023-10-05 at 8 37 49 PM

**Review by DavidC0126 — APPROVED** [review]
Hi @iTvX I tested your PR and there is no error when testing. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/c2035bfc-4e2d-4929-9657-b26f4db83028

**Comment by olenadanykh** [comment]
Hi @iTvX. I've tested your PR locally, and I didn't notice any ESLint errors. The functionality for REPORTS is working as expected. Compared to previous tests, this time all reports for the total project report, total team report, and total team report loaded extremely quickly. Great work!

PR1381


2F0F8386-983D-4243-9A04-FB88EBFCDBF7_1_206_a

**Comment by emunkh404** [comment]
Hi @iTvX,

I have thoroughly tested and reviewed your branch 'Zijie_Fix_Report_Lint_Phase13' (PR #1381), and it appears that everything is working as expected. Great job! I couldn't find any significant issues, except for a few frontend key-value and HTML element rule warnings.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/21adf6ac-9e12-45cb-9551-192a8085dbce

**Comment by beblicarl** [comment]
The report functionality works as intended and there are no errors as well

[screencast-hgnapplication_react_beta.surge.sh-2023.10.06-18_07_43.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/413f6958-0827-4923-8a7b-539e519a5366)

**Review by beblicarl — APPROVED** [review]

**Review by lacnoskillz — APPROVED** [review]
Hello again Zijie
It looks like the functionality is still the same with these changes.
Note it still takes a long time for Show Total Team Report to load on my end but as someone said above it loaded fast so maybe its a me issue

[Untitled_ Oct 6, 2023 1_26 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/d6259e20-8b9a-40b4-87b7-4df2e97d01c2)

**Review by malikjahanzaib — APPROVED** [review]
Hi @iTvX , I have tested the code changes locally and everything seems to work as expected. There are no ESLint errors as well. Nice job!

Screenshot 2023-10-06 111421

Test Rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/1ed47ff7-2dc6-4814-af00-7b84949555fd

**Review by tsunami776 — APPROVED** [review]
Hi @iTvX, I did the optional test first and there was no error shown. Then I tested your PR locally and the report page works as expected. Nice work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/9fca1dd2-536f-4c21-89bf-bd85bd6d8556

**Comment by RheaWu1212** [comment]
HI I tested the code locally and everything work as expected:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/649c05b9-5cf0-462a-81f1-0b904a8c2788

**Review by Shubhu0 — APPROVED** [review]
Hi @iTvX Reviewed the PR and it is working as intended. Found no console errors on the reports page and it was working smoothly. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/4712eee9-52c9-420a-bfd1-52a0510704c6



image

**Review by KurtisIvey — APPROVED** [review]
Functions as intended.
pr1381 no errors
All tests still passing on the frontend
pr1381 all tests still pass


What does "1" mean in reference to this pull request to indicate what you're committing? 
Screenshot 2023-10-12 at 10 50 51 AM
I'd check out this [commit guide](https://gist.github.com/robertpainsi/b632364184e70900af4ab688decf6f53) so you can improve the clarity of what's going on in your commits. The commits don't have to be perfectly worded, but surely they can be better than "1" or "3"

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
