### PR TITLE
Anne Fixed spacing between task rows and within task rows in WBS

### PR DESCRIPTION
**Pull request by Annezhang673**
# Description
Screen Shot 2024-09-21 at 7 24 23 PM

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- Update HighestGoodNetworkApp/src/components/Projects/WBS/WBSDetail/wbs.css to increase the spacing betwwen sub-sub task and the spacing between line spacing of txt in WBS.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links>Projects>[Click WBS Icon](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa)
Please refer to the above link on how to create WBS task and sub tasks. There are minor differences.
7. Add task A with two lines of name, then proceed to add sub task B, then proceed to add sub task C. Verify that the line spacing of task A is increased and the sub-sub task is spaced out, compared to the screenshot in the description. Watch the video below if you need an example of the tasks and sub tasks for testing. 

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/ccc746f1-4c97-43dd-8b69-665d66cd3484

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Nahiyan-16 — APPROVED** [review]
This works great and visibly looks awesome.
Before: 
Screenshot 2024-09-21 205134
After:
Screenshot 2024-09-21 205155

**Review by ArtemisNyx3 — APPROVED** [review]
**Before**
image


**After**
image

code is working as expected and there is a big improvement in readability, it doesn't look congested anymore.

**Review by sam19981 — APPROVED** [review]
Changes are working as expected there is a neat space between the task and sub task.

Screenshot 2024-09-21 at 10 45 21 PM

**Comment by mianmiantea2019** [comment]
This works great!

image

**Review by abdel-lall — APPROVED** [review]
LGTM. Nice job!
Screenshot 2024-09-22 005206

**Review by ashmita123 — APPROVED** [review]
Tested PR #2709. The updated task spacing in the WBS table works as expected, improving readability.

Screenshot 2024-09-23 at 1 41 17 PM

**Review by Lexie5212 — APPROVED** [review]
I tested the PR and the code changes worked as expected. With lines and spaces, the interface view became nice.
Screenshot 2024-09-23 at 18 08 35

**Review by RishithaMamidala — APPROVED** [review]
@Annezhang673 
Changes are working, there is a space between the task and sub task.
PR 2709

**Review by anirudhsk2107 — APPROVED** [review]
I tried it in both light and dark mode, and they worked perfectly
PR_ 2709
Screen Shot 2024-09-23 at 11 20 56 PM

**Review by nikhilgiri0226 — APPROVED** [review]
image

Changes are visible as expected.

**Review by chu-ziyu — APPROVED** [review]
I have tested this PR and everything worked as expected.

https://github.com/user-attachments/assets/f7e2390b-2518-4cb2-b6f6-7eedfc5c39b3

**Review by mrinalini-raghavendran19 — APPROVED** [review]
Looks good to me:

Tested it by adding subtasks to task:

Before:
[
Screenshot 2024-09-24 at 4 30 36 PM
](url)

After:
Screenshot 2024-09-24 at 4 31 09 PM

**Comment by saurabhshetty29** [comment]
Tested by adding sub tasks, looks good!
Screenshot 2024-09-24 at 10 14 45 PM

**Review by SFA23SCM35V — APPROVED** [review]
Working as expected approving the PR
PR 2709

**Review by nevatiarishabh — APPROVED** [review]
I have tested the PR. Everything is working as expected. Looks good to me. The spacing has been effectively changed.

Screenshot 2024-09-25 at 1 10 15 PM

**Comment by khushijain03** [comment]
Tested by adding tasks and sub-tasks, changes are working as expected.
Screenshot 2024-09-25 at 9 08 46 PM

**Review by khushijain03 — APPROVED** [review]
Tested by adding tasks and sub-tasks, changes are working as expected.
Screenshot 2024-09-25 at 9 13 19 PM

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and everything works great!!

Screenshot 2024-09-26 151700

**Review by nishitag5 — APPROVED** [review]
The changes are working as expected
Before:
Screenshot 2024-09-27 002431

After:
image

**Review by neeharikakoniki — APPROVED** [review]
This PR successfully improves the readability of the WBS by increasing the line spacing for tasks and properly spacing sub-sub tasks. The changes are well-implemented, making the task hierarchy visually clearer and easier to navigate.

image

**Review by Vincent-space — APPROVED** [review]
Hi @Annezhang673 , the WPS of #2709 looks great when I tried to add task.
image

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as described.
Screenshot 2024-09-28 at 10 10 35 AM

**Review by jinxyou — APPROVED** [review]
The spacing seems working well. Great work! 
Screenshot 2024-09-28 164515

**Review by Muzammil603 — APPROVED** [review]
image
workinga as expected

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
