### PR TITLE
Nahiyan_Added a confirm password input

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Screenshot 2024-03-18 160626

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Cleaned up unused imports
- Added functionality to confirm password

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→Other Links→User Management→Create New User
6. Select Admin/Owner role
7. Observe the confirm password input
8. Make sure passwords have to match before creating the user profile

## Screenshots or videos of changes:
Screenshot 2024-03-18 161226

### CODE REVIEW

**Review by Abi-Liu — DISMISSED** [review]
Looks good! The confirm password input works as expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/f3dfb2e2-5cc9-4f14-a326-7f5a811ba5ff

**Review by linkhanthtel — DISMISSED** [review]
It looks good! Confirm password input field work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/fd9d1d2c-40e7-4d73-9eb7-18e4f523ecd3

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and it works as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/9b995853-f423-4693-b871-968f0e5fc0e5

**Review by iven-yao — DISMISSED** [review]
Hi, I just reviewed this pr, and everything looks good.
- [x] confirm actual password input
- [x] form validation as expected
 
image
image
image

**Review by hetvi11110 — DISMISSED** [review]
I have looked over and tested this PR as it was mentioned. It is working perfectly on my local server. Here is a reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/81bc8500-fb6c-4ab0-af21-32c767d109ab

**Review by ImzIssa — DISMISSED** [review]
hello, I've tested this PR and your changes work fine. 

PR#2073
PR#2073 (2)

**Review by SRamen1999 — COMMENTED** [review]
After testing this PR everything works as expected. If you don't match the password or give the proper email it gives an error message.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/7d254461-316f-4366-a4cb-c40e7630b6df

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested you PR and it works perfectly. Amazing Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/4c6ad452-522f-47dc-8812-4ef365c022fb

**Comment by rajnada** [comment]
Hi,

I have reviewed the PR and validation working fine as you mentioned. Great Job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/25640436/7d33da20-af53-46c2-b016-7cfef2c23afb

**Review by Coops023 — DISMISSED** [review]
Hi, i reviewed this PR i checked that if the passwords do not match, i would get an error and if they did match i could create the user. well done!

keep

keep2

**Comment by Gayathr-2012** [comment]
Hi,
 I tested current branch  and it works perfectly. nice job.
 Selected  Admin Owner role
Observed the confirm password input
Make sure passwords have to match before creating the user profile -> works perfect.
image

**Review by tdkent — DISMISSED** [review]
Confirmed through testing that non-matching passwords blocks form submission and prompts an error toast, and that matching passwords in both fields allows proper execution of new user creation.

Minor nit: it might be worth changing the toast text to "Your passwords do not match" so the error context is completely clear to the user.

Screenshot 2024-03-23 at 9 41 52 AM

**Review by psharma1984 — DISMISSED** [review]
hi @Nahiyan-16 Password input field works as expected. 

[screen-capture (2).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/5e19868d-db1d-4b79-8c83-53d15e597161)

**Review by sameersdeshpande — DISMISSED** [review]
Hello @Nahiyan-16 
I checked this PR and this is working fine.I am able to see the confirm password and its working as expected. Approving
Screenshot 2024-03-23 at 6 16 12 PM
tworkApp/assets/87390339/522a4f55-4ccc-4807-9f53-cc36c676132a">

**Review by Sarthak32 — DISMISSED** [review]
Hello, I tested this PR and it works well code is also clean.
Screenshot 2024-03-24 104759
Screenshot 2024-03-24 105528

**Review by Tiantian-C — COMMENTED** [review]
Hello,
I have tested this function. It works as described!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122494725/792405e8-6007-43e9-bc9d-6879674de97b

**Review by kylepham — DISMISSED** [review]
Everything works as expected. The validation message displays correctly when the passwords are mismatched. Great work.
Screenshot 2024-03-25 at 10 53 40 AM
Screenshot 2024-03-25 at 10 56 58 AM

**Review by one-community — CHANGES_REQUESTED** [review]
> Confirmed through testing that non-matching passwords blocks form submission and prompts an error toast, and that matching passwords in both fields allows proper execution of new user creation.
> 
> Minor nit: it might be worth changing the toast text to "Your passwords do not match" so the error context is completely clear to the user.
> 
> Screenshot 2024-03-23 at 9 41 52 AM

Yes, please add this and also an "eye" icon for revealing the passwords if a person wants to. Add these two things and I'll merge this!

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi, I just reviewed you PR and it works fine.

PR 2073
PR #2073

**Review by hbodgal — DISMISSED** [review]
Functionality works fine. 
image

**Review by KurtisIvey — APPROVED** [review]
No complaints from me. Everything works as it should and there's active form validation per the request of the bug. In addition, the recent feature requests from Jae were addressed too. You even had the toast actually explain the error too. Almost brings a tear to my eye after seeing all the non descriptive toasts lol 🥲 

Fantastic job!

Screenshot 2024-03-30 at 4 20 32 PM

My only suggestion would be in a later bug fix  to have this password confirmation verified in the backend as well.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
