### PR TITLE
Jinchao update weeklysummaryrequired

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
image
Frontend update for [#316](https://github.com/OneCommunityGlobal/HGNRest/pull/316).
## Mainly changes explained:
Replace Weekly Summary Required switch on volunteerTimeTab with Weekly Summary Options selection input. Update the showing logic of weekly summaries in Weekly Summaries Reports page and generated PDF.
## How to test:
Please test this PR with the backend [#316](https://github.com/OneCommunityGlobal/HGNRest/pull/316) update.
Please open both the dev host https://hgnapplication_react_dev.surge.sh/ branch and your localhost since this PR will replace the previous 'Weekly Summary Required' with the new 'Weekly Summary Option', without directly modifying the database. The database will only be updated when a user clicks the save changes button.

1. Log in to both dev host and localhost as an admin user, go to other links -> user management -> open any user's profile page -> volunteering times tab. Check if the **weekly summary options** in localhost synchronize with **Weekly Summary Required** in dev (Avoid using any accounts that have a name like jinchaoxxx, I made my own test on these accounts lol)
image
image
2. Change the **Weekly Summary Required** in dev. Restart the local HGNRest and go to userProfile page, check if the **weekly summary options** changed as well (This ensures that if an account doesn't have a weekly summary option set in the database, the system will use the old information. Currently, there is a bug preventing changing from "Not Required" to "Required", so just check by changing from "Required" to "Not Required")
3. Log in as a non-admin user and check the synchronization in read-only view:
image
image

4. Change the **weekly summary options** in localhost to 'Team' and save changes. Check if the save changes button work as intended.
5. Go to Reports->weekly summary reports to check if the color for different options(required, team, not required) is correct
image
6. Click Open PDF at the top of the weekly summary reports page to check if the pdf report is correct.
image
7. Repeat step 5 and 6 with the different weekly summary options, and check if the reports are correct based on color pattern table in Note.
## Note:
Color pattern: 
image

### CODE REVIEW

**Review by ypan710 — COMMENTED** [review]
Hi @suigunfjc, I've tested your PR until Step 2 when you instructed "Change the Weekly Summary Required in dev and refresh the localhost page, check if the weekly summary options changed as well (This ensures that if an account doesn't have a weekly summary option set in the database, the system will use the old information. Currently, there is a bug preventing changing from "Not Required" to "Required", so just check by changing from "Required" to "Not Required")". For this step, I've checked that the localhost did not synchronize the information (Changing from "Required" to "Not required") with that of the dev version. Should I continue reviewing?

Screen Shot 2023-04-13 at 11 50 16 PM

Screen Shot 2023-04-13 at 11 50 20 PM

**Comment by suigunfjc** [comment]
Hi @ypan710 , thank you for testing my PR, I open the account in my chrome and the requirement state seems not changed. Maybe you forget to click the save change button after your make changes.
image

**Review by ToobaJamal — COMMENTED** [review]
Hi Jinchao, I tested the PR and all the steps you mentioned are working as intended. Good work!

**Review by ToobaJamal — APPROVED** [review]

**Comment by ypan710** [comment]
> Hi @ypan710 , thank you for testing my PR, I open the account in my chrome and the requirement state seems not changed. Maybe you forget to click the save change button after your make changes. image

I've tested again and ensure I saved the changes on the dev version but this time the Weekly Summary Option on the dev version defaulted to "Not Required" since login and after I tried to toggle it to "Required" and clicked "Save Changes", the Weekly Summary Option reverted back to "Not Required", which I think is strange.

Screen Shot 2023-04-14 at 7 57 36 AM

Screen Shot 2023-04-14 at 7 57 49 AM

**Review by abdel-lall — APPROVED** [review]
worked as expected.
PR764

**Comment by suigunfjc** [comment]
Hi @ypan710, as I mentioned in the instruction, there is a bug in the current dev that prevents the user from changing the status from 'Not Required' to 'Required'. 
Here is an explanation of why we need step1 & 2, hope this will help you.
image
This is userProfile data in the database and below is another userProfile data after your saving change from localhost.
image
You can see that after you make any change and click the save change button from localhost, the data in the database will have a new attribute **weeklySummaryOption**. Then the value of Weekly Summary Options at localhost will follow this attribute rather than the previous **weeklySummaryNotReq** attribute. 
This PR will not add the **weeklySummaryOption** attribute to existing user profiles. In cases where the attribute is not present, the system will rely on the value of the **weeklySummaryNotReq** attribute. This ensures that the application will continue to function properly with current data. However, if a user profile is updated, the new **weeklySummaryOption** attribute will be added, overriding the effect of the old 'weeklySummaryNotReq' attribute.

**Review by LucileTech — APPROVED** [review]
I tested your PR and every steps are working fine: 
When I refreshed the localhost page, the weekly summary options changed as well:
PR 7 refresh the localhost page, check if the weekly summary options changed as well

The save changes button is working as intended:


PR 7 the save changes button work as intended


The colors are correct on the summary page and the pdf on 3 options: 

PR 7 the color or the summary is black on required
PR 7 the color or the summary is green on not required
PR 7 the color or the summary is pink on team

**Comment by one-community** [comment]
Thank you all, moving to final review. @ypan710 still please confirm your concerns were addressed.

**Comment by ypan710** [comment]
> Thank you all, moving to final review. @ypan710 still please confirm your concerns were addressed.

I've read the author's response above, but for some reason it's still not working for me in step 2. You can move it to final review if you want.

**Comment by KaixiangGU** [comment]
Tested, everything works fine except step 2. Changed required to not required on DEV but failed sync changes on local.
@one-community Should have more people review this in final review team.
Capture3
Capture2

**Comment by suigunfjc** [comment]
@KaixiangGU @ypan710 Sorry guys, I just noticed that changing the **Weekly Summary Required** on dev won't update the cache at localhost, so the **Weekly Summary Options** won't get updated immediately. Please restart the HGNRest after you change the **Weekly Summary Required** and the **Weekly Summary Options** should be 'Not required' as expected. Also please use a new account to do this test since any update on localhost will create the WeeklySummaryOption attribute.

**Comment by one-community** [comment]
Ok, thank you Kevin, will do.

**Review by vitorsaa2k — APPROVED** [review]
Tested following the steps provided on the description, and all situations worked well.

**Comment by one-community** [comment]
Excellent, thank you everyone. Merging!

**Pull request merged**
