### PR TITLE
Shereen_Bulk Reusables Update component

### PR DESCRIPTION
**Pull request by pshereen**
Added Bulk Reusable Update component.
Added reducer function.
Added action fyunction.
Added URL

# Description
Update Reusable - Bulk
Implements WBS # 10.2.5

## Related PRS (if any):
This frontend PR is related to the https://github.com/OneCommunityGlobal/HGNRest/pull/1005 backend PR.

…

## How to test:
1. check into current branch
3. do npm install and npm run start:local to run this PR locally
4. Clear site data/cache
5. Login as any user
6. Go to /bmdashboard (http://localhost:3000/bmdashboard) and log in again.
7. Navigate to [/bmdashboard/reusables/update] (http://localhost:3000/bmdashboard/reusables/update)
8.  Increment values in Used and Wasted columns and click Submit button. Check if the success message is coming after the submit button is clicked and New available column is updated accordingly.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/d6e4ebd6-6d5f-472f-8e1c-3c3d55a000df

### CODE REVIEW

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and able to increase the Used and Wasted columns and submit the changes. The New available column is updates correctly. The validations for Used and Wasted columns work when user exceeds the available Quantity. Great Work!

**Review by kdaga81 — CHANGES_REQUESTED** [review]
image


Few Changes:
1. The text field also accepts 'e' as input.
2.  When I submitted for 'e', New Available was updated to '0' from '10'.

**Review by kdaga81 — CHANGES_REQUESTED** [review]
image

When we enter delete key on the textfield it's displaying 'Used' and 'Wasted'. Ideally, it should be '0'

**Review by nyelmela — DISMISSED** [review]
I have tested this successfully
image

**Comment by sahithidhulipala9** [comment]
Tested PR, working perfectly!
Screenshot (93)

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by jinxyou — DISMISSED** [review]
I tried to increment the amount on items that's has 0 quantity, and it reported "Quantity Used exceeds the available stock". And increment those are in stock would be successful. Great work!
Screenshot 2024-06-29 191147
Screenshot 2024-06-29 191156

**Review by pavanswaroopl — CHANGES_REQUESTED** [review]
Hello,

Great work, but I found two potential issues with this functionality, below are the steps to reproduce:

1. If we place alphabet like e in used and wasted it is still getting accepted and success dialog is displayed on submit.
2. The form still allows to edit the fields even if available units are 0, and still be able to submit, I feel there should be some validation not to allow users edit if there are 0 available units, this might be an improvement, correct me if I'm wrong 




https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/1af8b07a-c40e-439e-94ba-68afa3899488


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/455ae671-712b-4428-b47a-d1ba2c629042

Screenshot 2024-06-29 at 9 36 27 PM

**Comment by pshereen** [comment]
> 1. accepts 'e' as input

Thank you for the feedback.
Fixed issues related to accepting 'e' as input.
Please pull again and test.
Make sure to delete cache before testing.

**Comment by pshereen** [comment]
> Hello,
> 
> Great work, but I found two potential issues with this functionality, below are the steps to reproduce:
> 
> 1. If we place alphabet like e in used and wasted it is still getting accepted and success dialog is displayed on submit.
> 2. The form still allows to edit the fields even if available units are 0, and still be able to submit, I feel there should be some validation not to allow users edit if there are 0 available units, this might be an improvement, correct me if I'm wrong
> 
>  Screen.Recording.2024-06-29.at.9.29.54.PM.mov 
>  Screen.Recording.2024-06-29.at.9.37.20.PM.mov 
> Screenshot 2024-06-29 at 9 36 27 PM

Thank you for the feedback.
Fixed issues related to accepting 'e' as input.
Please pull again and test.
Make sure to delete cache before testing.

And regarding the submission of form even after no changes are made: Since the message indicates logged for 0 Reusable Records, it is not an issue.
Might be in future we can consider adding that check also.

**Review by HowieMiao — CHANGES_REQUESTED** [review]
Test PR, increment functions and input no longer accepts 'e', seem to be running into problems with POST after submitting. On back-end PR 1005 and this current branch

image

**Comment by pshereen** [comment]
> 6\. http://localhost:3000/bmdashboard/reusables/update

It looks like you are in a different branch.
Pull frontend from https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2389

**Comment by pshereen** [comment]
> Test PR, increment functions and input no longer accepts 'e', seem to be running into problems with POST after submitting. On back-end PR 1005 and this current branch
> 
> image

It looks like you are on a different branch.
In the image you shared it is printing in detectStoreNew to the console.
But this branch will not print that.
Make sure to pull front end from: 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2389
Backend from: https://github.com/OneCommunityGlobal/HGNRest/pull/1005
Clear cache before testing.
Attaching a video, I tested now after clearing cache. 
As you can see in the video, it is not printing any message to the console. And the updates are successfully logged.

Uploading HGN APP and 1 more page - Personal - Microsoft​ Edge 2024-07-01 14-33-22.mp4…

**Review by HowieMiao — DISMISSED** [review]
Client sided back end problems with npm, previous change requests can be ignored. PR is functional

image

**Comment by pshereen** [comment]
> image
> 
> When we enter delete key on the textfield it's displaying 'Used' and 'Wasted'. Ideally, it should be '0'

Fixed.
Please pull both frontend and back end again.
Make sure to clear cache before testing.

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR with backend PR-1005. Initially, I encountered an API-related error. Then, I ran npm run build for the backend PR followed by npm start.
 After following these steps, I was able to test this PR successfully.
for frontend > checkout PR 2389 > Npm start 
for backedn > checkout PR > npm run build > npm start 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/5909860d-0ad9-4ad2-b4d2-2bed03f2b3ae

PR-2389

**Comment by Vigneshwar-Muriki** [comment]
Tested this PR with instructions as mentioned and it's working good. Entered different values for used and wasted column and new value is updated accordingly and got a pop up after updating the values. Screenshots are attached below.
Screenshot 2024-07-04 150153
Screenshot 2024-07-04 150202
Good work!

**Review by Vigneshwar-Muriki — DISMISSED** [review]

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected. Good Work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/60431d9c-bf32-400c-95e0-f252dc946adc

**Comment by pshereen** [comment]
> image
> 
> Few Changes:
> 
> 1. The text field also accepts 'e' as input.
> 2. When I submitted for 'e', New Available was updated to '0' from '10'.

Addressed

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
