### PR TITLE
Wanting unit test for `ProjectTableHeader.jsx`

### PR DESCRIPTION
**Pull request by wantingxu7**
# Description
unit test for `ProjectTableHeader.jsx`

## Related PRS (if any):
…

## Main changes explained:
Add file `ProjectTableHeader.test.jsx`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. do `npm test ProjectTableHeader.test.js`
4. verify that all tests pass with no error

## Screenshots or videos of changes:
unittest_ProjectTableHeader

### CODE REVIEW

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-16 at 12 26 33 AM

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-15 at 10 16 52 PM
All the test cases were successful. Excellent job!

**Comment by DragonSlayer2401** [comment]
I tested your PR and all tests passed as expected. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/0e237baf-79a7-48e5-86ab-64edbe04b7ac

**Review by ljrirene — DISMISSED** [review]
All tests PASSed!

**Review by Alforoan — CHANGES_REQUESTED** [review]
All tests passed, but I have a couple suggestions.
1. Maybe a more descriptive test description, such as instead of "renders without crashing," you can try "should render the ProjectTableHeader component without errors."
2. An edge case for when hasPermission returns false instead of true.


image

**Review by sxiong5 — DISMISSED** [review]
Hey @wantingxu7, the test cases were passed! Nice job.

Screenshot 2023-12-20 at 20 29 03

BTW, I don't understand what @Alforoan said about "the `hasPermission` returned false in one of the edge cases".

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 17 - PR5

**Review by Alforoan — DISMISSED** [review]
Upon closer inspection, they're concise and descriptive.

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by navneeeth — CHANGES_REQUESTED** [review]
Hello, @wantingxu7! After observing the implementation of ProjectTableHeader.jsx, this is a great design of the test cases for rendering, showing 'Delete' for users with delete permission, and hiding for those without. The test cases are passing for the implementation. 


However, the latest comment on the HGN Unit Testing Guide document suggests placing tests in a `__tests__` folder within the Component for better file structure. Please move the test within a folder called `__tests__`. See screenshot below. Thank you!

folder structure

**Comment by beblicarl** [comment]
All test cases passed successfully

image

**Review by beblicarl — DISMISSED** [review]

**Review by navneeeth — APPROVED** [review]
Updated file structure looks good! Approving the PR.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
