### PR TITLE
Fan - Add unit tests for BadgeTableHeader component

### PR DESCRIPTION
**Pull request by yangfan2001**
# Description
Unit Test For BadgeTableHeader.jsx

## Related PRS (if any):
None

## Main changes explained:
- Add Unit Test For BadgeTableHeader.jsx

## How to test:
1. check into current branch
2. do `npm install`
3. RUN `npm test src/__tests__/Badge/BadgeTableHeader.test.js` to see if all test cases are passed

## Screenshots or videos of changes:

image

### CODE REVIEW

**Review by Bali2Mohit — COMMENTED** [review]
Tested your PR. All tests pass. Well done

Screenshot 2023-11-04 at 16 06 51

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great work
Screenshot 2023-11-04 at 2 14 30 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, All test cases passed! Great Job!

Week 10 - PR6

**Review by kavya151 — APPROVED** [review]
Hi @yangfan2001 , I have run the test cases and all of them have passed. Good job!
Screenshot 2023-11-04 at 4 58 37 PM

**Review by savio-henrique — APPROVED** [review]
Hi @yangfan2001 , I've tested the test cases, all passed as expected! Great job! :+1: 

# Screenshot
terminal

**Comment by palakgosalia** [comment]
Hey, I have tested your PR and all test cases passed.

image

**Comment by AnishPandita** [comment]
Hey I tested the PR and the test cases ran perfectly without any issues. Checked the BadgeTableHeader.jsx for any errors but found none.
Screenshot 2023-11-05 at 12 39 27 AM

**Comment by wantingxu7** [comment]
I ran the test and got the same message as others.  Good work.

**Review by Sssky-18 — APPROVED** [review]
Hi @yangfan2001 , I just tested your PR, and all tests are passed as expected. Thank you for your great work! 

PR#1487_1

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-08 at 7 33 15 PM

**Comment by wanglu1207** [comment]
Good job! All the test cases passed!

**Review by Bali2Mohit — APPROVED** [review]

**Review by BaileyM96 — APPROVED** [review]
Hello @yangfan2001 I reviewed your changes  and all your tests have successfully passed. Great work!

## Screenshot

PR #1487 Fan Add unit tests for BadgeTableHeader component

**Comment by BaileyM96** [comment]
@one-community

**Review by AaronPersaud — APPROVED** [review]
Hi @yangfan2001, I've tested it and all the tests passed! Great work!

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
