### PR TITLE
Shengjie - created projectstab's test file

### PR DESCRIPTION
**Pull request by ShengjieMao**
# Description
Created unit tests for the ProjectsTab component in TeamsAndProjects. 

## Related PRS (if any):
None

## Main changes explained:
- Created test units for checking props rendering
- Checked for components functionalities and stats
- Made sure edge cases are considered 
…

## How to test:
1. check into current branch
2. do `npm install` and `npm test ProjectsTab.test.js` to run this PR locally
3. Check if all 11 tests passed

## Screenshots or videos of changes:
Output

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
I reviewed your PR and all 11 tests passed!

**Review by aaryaneil — APPROVED** [review]
All test cases passed, looks good to me.
Screenshot 2024-03-30 at 1 13 27 PM

**Review by j-corp-25 — APPROVED** [review]
## Hi, Shengjie!

I've followed the instructions provided:

1. Switched to the branch `shengjie_ProjectsTab_Test`.
2. Executed `npm install` via terminal.
3. Initiated `npm test ProjectsTab.test.js`.

**Result: Success! All 11 test cases have passed flawlessly.**

For a detailed walkthrough, I've prepared a video demonstration that meticulously follows the steps outlined. You can access it here:

[Video Demonstration](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/a43e85ca-ac39-4b16-932b-82fd6302989c)

**Review by yvonnep165 — APPROVED** [review]
Hi @ShengjieMao , I have reviewed and run you tests. All test cases passed. Nice work!
Screenshot 2024-04-05 at 10 41 18 PM

**Review by ImzIssa — APPROVED** [review]
Hey, I've reviewed your PR. All test cases passed.

PR 2100

**Review by vikrambadhan — APPROVED** [review]
Hi, Great Job! I tested your PR and all the test cases passed!

Week 31 - Pr3

**Review by bhuvaneswarignanasekar — APPROVED** [review]
I have reviewed your PR. All test passed. Attaching the screenshot.
Screenshot 2024-04-09 at 8 11 40 PM

**Review by KurtisIvey — APPROVED** [review]
The coverage is there and you're following testing best practices. No complaints for me on this one. There are a lot of props in this component, and you made sure to handle them well. Fantastic job!

Screenshot 2024-04-12 at 11 07 46 PM

**Review by scoopstroop92 — APPROVED** [review]
Good job on the test cases !
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
