### PR TITLE
Yubo-fix_adding_professional_links

### PR DESCRIPTION
**Pull request by GKD890**
# Description

Frontend_PR#1101_Description-1

Fixes **User Management Component** # 21 **Urgent**

## Related PRS (if any):
This frontend PR is related to frontend PR #980:

1. It adds fixed **Google Doc** link and **Dropbox** link.

## Main changes explained:
- Rewrite the `EditLinkModal.jsx` file as the previous one has unfunctional and unnecessary `dispatch` functions.
- Add the style to 'help context' to tell user why certain links can't be added.
- Integrate PR #980.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to 'Other links'→ choose any user→ Edit their links below their Profile Picture.
5. verify if all the valid links can be added and removed. `Google Doc` and 'Dropbox link' are special **admin links** that need to be fixed, and invalid URLs can't be added
6. remember to click `Save Changes` after the `Modal` is closed.

## Screenshots or videos of changes:
Frontend_PR#1101_Description-2

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/e9c7ccc5-8ae3-41ee-922a-d1aed97efc78

## Note:
You may find if it can be saved by only clicking `update` button, it may be in a new PR once it's solved. Thank you for reviewing.

### CODE REVIEW

**Review by yaow62023 — APPROVED** [review]
All functions are tested. In the two videos below, I tested the admin and user links. Both links add a new link if the correct URL pattern is entered. And the google and media folders can only be saved when the correct URL format is entered.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/8be22406-390c-4213-96dd-a8da006ac6f5

**Review by yaow62023 — DISMISSED** [review]
The new changes in the code have been reviewed. The functionality is working perfectly, and we have also tested the case sensitivity for ".com" part, which is functioning as expected. The newly modified code is more concise.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/4449f2ef-8370-410a-8995-a76ae5b5c981

**Review by eduvarjaor — APPROVED** [review]
The new changes working as intended. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/5b1cff20-304d-4755-9236-683e95088e97

**Review by DavidC0126 — APPROVED** [review]
Hi @GKD890,
I tested your PR and all functions work as described.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/c1262fd4-bc12-43e7-b468-cf8e6b8a335a

**Review by BaileyM96 — APPROVED** [review]
Good evening I tested the changes and everything works as described and ran into no issues, the links also dont work if they are not the right format so good work on that.

## Videos

[PR #1001 adding professional links.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/69d37189-407b-4139-be6f-9eedfec2ebf6)

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-hgnapplication_react_beta.surge.sh-2023.07.27-15_44_49.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/9eb8e9de-4550-4d70-be11-0edd7fd535c1)

**Comment by Shreyj14** [comment]
Hi @GKD890 Great Job! the PR functions as described. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/8416da12-edde-4f7c-b8f7-3c087baec920

**Review by Shreyj14 — DISMISSED** [review]

**Review by zuhang2000 — CHANGES_REQUESTED** [review]
I did test about adding new links, both Admin Links and Personal Links. I did several test on adding Admin Links such as checking whether it can handle the incorrect link format. It works as expected.

However, when I try to add personal links. It could fail sometimes. After I click update, it does not allow me to click "Save Changes" below. The "Save Changes" button is not responding. The program is not detecting any changes I just made. I need to add another personal link and delete the previous one to let it detect changes. Please see the video I attached below. If this is a problem on my end, please let me know so that I can test it further. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/bf5ff3c9-020e-4465-b12c-4d8afcd8d7ce

**Comment by iTvX** [comment]
I tested your PR, and it worked just as you described. Great job!

However, I don't like that I have to click 'Save Changes.' It should automatically save the changes.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/076d9ff9-ac97-42a5-a45b-f3ebe1d11fa2

**Review by Indujaks — APPROVED** [review]
Tested the changes, added two personal links and verified the input for valid/invalid test cases.
Functionality seems to work as expected!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/8d8721cd-474b-4deb-b1ed-ceaf94d840d8

**Comment by Lin1404** [comment]
Hi @GKD890 ! I have tested your PR, added links and verified the input for valid/invalid test cases, and if I remove the added url, it will automatically remove after update.

image

**Comment by GKD890** [comment]
> I did test about adding new links, both Admin Links and Personal Links. I did several test on adding Admin Links such as checking whether it can handle the incorrect link format. It works as expected.
> 
> However, when I try to add personal links. It could fail sometimes. After I click update, it does not allow me to click "Save Changes" below. The "Save Changes" button is not responding. The program is not detecting any changes I just made. I need to add another personal link and delete the previous one to let it detect changes. Please see the video I attached below. If this is a problem on my end, please let me know so that I can test it further.
> 
>  Test.1001.mov

Hi @zuhang2000 , I think the reason why you can't see the `save changes` is clickable is because you didn't click the '+' button so that the personal link you typed isn't being added properly to trigger 'changes'. I think it can be solved by remembering to click '+' button at the right side of the input. 

Hope that helps, let me know if that still doesn't work.

**Comment by GKD890** [comment]
> I tested your PR, and it worked just as you described. Great job!
> 
> However, I don't like that I have to click 'Save Changes.' It should automatically save the changes.
> 
>  MyRecord_20230803155310.mp4

Hi @iTvX , You are right. I was also trying to removing the additional savings. But it's more than I expected, so I put into lower priority list. As this is the core features that's urgently needed, I just open this PR so it can be used ASAP. 
If possible, can you review and approve this PR again? Thank you.

**Comment by GKD890** [comment]
Hi @Shreyj14 @beblicarl @DavidC0126 @yaow62023 @BaileyM96 @eduvarjaor , if possible, can you re-approve this PR again as this one is a relatively urgent one. I resolved some conflicts since you approved the last time. You can see one of the recent commits here: [1. merged from dev](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1001/commits/6ef18b62da32d794ee49902cd2b65c7a91c299d3),  [3. changed variable's name](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1001/commits/96504fedc1e45fb8e40db40d224726f994d759f7 )
And you may click to see other several commit to see what I've made, mostly the names of variables. Thank you in advance for taking time.

**Review by Abiddy — APPROVED** [review]
Works great! Great job!

Screenshot from 2023-08-05 23-46-44

**Comment by one-community** [comment]
Thank you all, merging!

**Review by yaow62023 — COMMENTED** [review]
I have tested your change, add link feature work as intended. Also so the warning message also works great. Check the video below for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/aa215858-25b3-4c6a-8690-1bf4a1017877

**Pull request merged**
