### PR TITLE
UP1: Jae: Clicking people’s time log loads my timelog data before theirs

### PR DESCRIPTION
**Pull request by RJBornToWin**
What is handled here and things to test:
1. Display of summary bar in timelog page : a) For self : normal just like dashboard summary bar b) other user: disabled summary bar to avoid incorrect summary/error submission
2. Loading to be shown till timelog and summary bar are loaded when navigated to timelog page
3. Effort shown in timelog page - summary bar is calculated from weekly summary data. Not the same logic as in dashboard page which uses leaderboard data to calculate effort. Effort shown in summary bar is just the tangible entries for the current week.
4. Filter Entries by Project and Task and its associated dropdown is displayed in 2 separate lines to avoid overflow of dropdown out of container when task name is too long. (UI changes already confirmed with Jae)
UP_1_project_dropdown_error

5. Update timelog - summary bar effort - on toggle of tangible entries (tangible -> intangible and vice versa). 
6. No change in timelog - summary bar effort on change in timelog tabs.
7. ESLint corrections

What is not covered: 
a. Cali is working on the authentication token missing in the API calls on first hit (which resolves on page refresh). This is not handled in this PR.
b. Improving the performance of the page

Output screenshots:
Dropdown correction:
UP_1_dashboard_project_list

Other user:
UP_1_timelog_other_user

Same user:
Screen Shot 2023-01-24 at 9 54 00 PM

### CODE REVIEW

**Comment by rauleffting** [comment]
Hi @RJBornToWin. Thank you very much! 
About the UX experience, I tested your changes and all worked perfectly, as you can see below:

Item 1:

ITEM 1

Items 2, 3, and 5:

https://user-images.githubusercontent.com/29555732/214611901-1f2813db-0102-414e-8f76-9fc624ad1145.mov

Item 6:

https://user-images.githubusercontent.com/29555732/214612228-a524b2eb-4257-4472-ba96-d9d9a1012fd6.mov

**Review by rauleffting — APPROVED** [review]
I have nothing to say about the code as well. It's very clean and understandable. So, I'm going to approve it.

**Comment by RafaelCastilhoCastro** [comment]
Hi @RJBornToWin,
I tested and here's what I found.

1. About the summary bar in timelog page of others users: Although the bar is faded as it is disabled the summary submit link (text link) is active and clickable, still been possible to submit an incorrect summary. (Image 1)

2. Loading animation working as intended. Although if I may I would suggest the implementation of a skeleton loading page instead. @one-community

All else seems to be working properly. Thanks.

**Review by rauleffting — CHANGES_REQUESTED** [review]
@RafaelCastilhoCastro is right about item 1. I missed it. We need to disable this function.

About item 2, it's a very good idea!

**Comment by AnishPandita** [comment]
Hi @RJBornToWin 
I went over the changes you implemented and tested them. Here is my review:
1) The summary of self and other user dashboard is working fine but as suggested by @RafaelCastilhoCastro incorrect summary can still be submitted by clicking the text link.

https://user-images.githubusercontent.com/111321945/214685099-f89c179e-7bad-4f7f-bb83-3d868e5bdc66.mov

2) Loading shown till time log and summary loaded are working fine. But when we navigate to time log page there is still 'Loading' written on top left corner of the screen after everything is rendered.

https://user-images.githubusercontent.com/111321945/214687064-b18439f6-b190-48c3-bda8-1cff308de163.mov






3) Rest everything looks okay. The UI changes are working correctly and the Tangible-Intangible toggle update working fine too.

https://user-images.githubusercontent.com/111321945/214687124-b2d003b3-e295-480e-9cb3-bb908e59fffb.mov





4) When I navigate to dashboard after going to time log page of other user from their dashboard it does not load any thing.

https://user-images.githubusercontent.com/111321945/214685935-9dcc6b25-5e0a-4527-beaf-27856544bbbb.mov

**Comment by AnishPandita** [comment]
I also went over the code and everything seems okay. Clean and extremely legible code.

**Comment by RJBornToWin** [comment]
Hello All, Thanks for everyone for reviewing it.

The scope of this PR is just the "**timelog**". I see the link is clickable as part of other users "**dashboard**".
If you see in the URL : it says dashboard/userid. But the PR is for timelog/userid.

If raul can log that as a bug (may be after confirming with Jae), I can handle it as a separate PR to keep functional isolation.
But I would leave this PR to "TIMELOG". @rauleffting

**Comment by RafaelCastilhoCastro** [comment]
Hi @RJBornToWin,
I performed new tests:

1. The summary link shows as inactive, thanks.
2. I tested @AnishPandita's item 2. The word 'Loading' doesn't appear to me.
3. I reproduced the flow of @AnishPandita's item 4 but the loading occured normally.

All seems to be working as intended. Thanks.

About the Skeleton Loading Page, I will message you directly about this matter so I don't clutter the PR.

**Comment by one-community** [comment]
Yes, please log that as a new bug

**Comment by RJBornToWin** [comment]
Have disabled summary submission link for other user dashboard.
Adjusted forgot password link (for bug: LOGIN COMPONENT : Low priority 1)
Changed LINK to div for "bluesquare" in disabled summary bar as it was making page go irresponsive on click when disabled.

**Comment by PrabhjotSembhi** [comment]
Hey @RJBornToWin, I have checked this. 
Could you give me some clarity? I am unsure how to check for other users, just so you know, your first screenshot. 

I was not able to navigate to that. can you please give some more instructions? 


These things are working fine:
Loading animation working well
The summary bar is calculated from weekly summary data.

**Comment by RJBornToWin** [comment]
From the leaderboard on your dashboard: Clicking on the user’s progress bar
- timelog , user’s status icon - dashboard.

**Review by rauleffting — APPROVED** [review]
I tested your changes. Everything worked quite well.

https://user-images.githubusercontent.com/29555732/215284571-16837f1f-4b97-4410-850b-ad4d861cfd29.mov

**Comment by Gukal7** [comment]
Hey @RJBornToWin, I have tested your changes and everything works great!
Screenshot 2023-01-28 at 5 37 44 PM

**Comment by PrabhjotSembhi** [comment]
I have checked it is working fine. I am facing performance issues and that's hampering testing also.
Sometimes it keeps loading for a minute or 2 and in some cases even more.  ( but you mentioned performance is not covered in this PR )

You can see dashboard components are not even loading
image

It keeps loading and I have tried restart/ relaunching it several times.


another thing I am not able to add an entry for the person whose profile I am currently watching

I clicked the Yellow "Add time entry for user" button
image

But the form is not getting submitted
image


https://www.loom.com/share/c499cd861df64dcbb6ecedceabb209fc

**Pull request merged**
