### PR TITLE
Vijay Anand - confirm button enable/disable in badge popup component based on selection

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description
Confirm button in AssignBadgePopup was causing error when user try to click confirm button and restart again from user selection step in badge assingment.

Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 
Made confirm button to get enabled only when the user selects at least one badge.

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch for backend.

## Main changes explained:
- Improved Redux state management in the badgeReducer, ensuring immutability when adding or removing selected badges.
- Updated AssignBadgePopup to use Redux state directly via useSelector, and implemented a proper check for enabling the Confirm button.
- Modified AssignTableRow to dispatch Redux actions directly using useDispatch, ensuring consistent state updates.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links→ Badge Management→ Badge Assignment
6. Search for a user and select a user and then click Assign Badge button.
7. verify if the "Confirm" Button is disabled when no badge is selected and gets enabled only when at least one badge is selected.
8. verify if it gets disabled again if no badges are selected.

## Screenshots or videos of changes:
**Before**
https://drive.google.com/file/d/1tzsavAocJK-0v-H1i5fB3jJkvlVYcOjp/view?usp=sharing

**After/How to test**
https://www.loom.com/share/08c369d54beb420e9bb210f61bf73790?sid=ea1c5473-6ebc-4ad2-95fd-6bc41e6dffb7

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nikhilgiri0226 — DISMISSED** [review]
image

I can see the button disabled when I don't select the badge. It works as expected.

**Review by chu-ziyu — APPROVED** [review]
I have tested this PR and everything worked as expected in both light and dark mode.
Screenshot 2024-09-24 at 2 51 34 PM
Screenshot 2024-09-24 at 2 51 38 PM
Screenshot 2024-09-24 at 2 51 51 PM
Screenshot 2024-09-24 at 2 51 55 PM

**Review by RishithaMamidala — APPROVED** [review]
@vijay10pk 
PR works correctly, Confirm Button is disabled when no badge is selected and is enabled when a badge is selected.
PR 2717

**Review by Lexie5212 — APPROVED** [review]
I tested the PR both in the light and dark mode. Changes worked as expected. 

https://github.com/user-attachments/assets/cd6e07bb-adca-457b-abf0-c2d722a18482

**Comment by tharunaa-1** [comment]
Works perfect, Tried adding a badge and it has been added to the profile badge.

image

image

**Review by slidracoon72 — APPROVED** [review]
#2717
@vijay10pk
The PR functions as intended: the Confirm Button is disabled when no badge is selected and becomes enabled once a badge is chosen.

**Review by ashmita123 — APPROVED** [review]
Tested PR #2717. The Confirm button is disabled when no badge is selected and becomes enabled once a badge is chosen. Everything works as expected. 

https://github.com/user-attachments/assets/88aabc54-d91d-438a-aa10-64a40969a211

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and verified that "Confirm" Button is disabled when no badge is selected and gets enabled only when at least one badge is selected.

Screenshot 2024-09-26 150811
Screenshot 2024-09-26 150822

**Review by Dk-21 — APPROVED** [review]
### PR 2717
@vijay10pk 
Tested The Changes and Working as specified.
PR-2717(2)
PR-2717(1)

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/b37c3340-ada3-49ba-883a-6ebbc7469d56

**Review by anirudhsk2107 — COMMENTED** [review]
The changes are working properly. 
When no one is selected the "Assign Badge" button is disabled -
Screen Shot 2024-09-26 at 11 30 24 AM

Badge assigning is only allowed when someone is selected and the badge reflects in their user profile. 
Screen Shot 2024-09-26 at 11 30 04 AM

**Review by anirudhsk2107 — APPROVED** [review]

**Review by ziyanw52 — COMMENTED** [review]
I have test this, and it works when no I select a person, no badge were assigned and the 'confirm' bottom is disabled as default.
After select one badge, the 'confirm' bottom can be clicked. But if unselect, the 'confirm' bottom is disabled again.
361727473934_ pic_hd
371727473963_ pic_hd

**Review by aaryaneil — APPROVED** [review]
The functionality works as described in the PR, the confirm button gets disabled when no badge is selected and enabled when at least one is selected.
Screenshot 2024-09-28 at 8 45 35 AM
Screenshot 2024-09-28 at 8 45 37 AM

**Review by jinxyou — APPROVED** [review]
The button enable and disable is working properly. Great work!
Screenshot 2024-09-28 161219
Screenshot 2024-09-28 161206

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.
Screenshot 2024-09-29 142833

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
