### PR TITLE
Shihao - Improve Summary Loading Performance

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Screenshot 2023-08-24 at 17 51 20

## Related PRS (if any):
This frontend PR is related to the [#484](https://github.com/OneCommunityGlobal/HGNRest/pull/484) backend PR.

## Main changes explained:
- Refactor `FormattedReport` component
- Adjust query to reduce HTTP request
- Add an observer to check if the dom is visible

## How to test:
1. check into `development` first
2. log as owner user
3. go to dashboard→ Reports→ Weekly Summaries Report
4. wait for page fully loaded

1. then check into current branch
6. log as owner user
7. go to dashboard→ Reports→ Weekly Summaries Report
8. check if the page load faster than dev branch

## Screenshots or videos of changes:
**Dev branch**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/422d6e50-7070-4294-a1c3-692c0960f6a9

**After changes**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/0e6aca47-9f33-4ca9-a12f-27e541f825ab

### CODE REVIEW

**Review by yunshan111 — APPROVED** [review]
Tested this PR, LGTM. Good job!!

Before: 10 sec

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/a8155552-8d90-4bb4-a9b5-363eb4ac2d84

After: 4 sec

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/ccd74313-72f2-41bd-a6db-92c2796a18cf

**Review by DavidC0126 — APPROVED** [review]
Hi @sxiong5 I tested your PR and it works as described. Good job! There is a huge enhancement on the weekly report page performance.

DEV
dev_load

Your branch
curr_load

**Review by vinaykumarh — APPROVED** [review]
Reviewed the PR and the result is as expected from the requirement.
Below are snaps of review.

Dev:

image

image

PR:

image

image

There is significant improvement in weekly summary report load time. Based on the metrics provided in Screen shots above and also by general observation as a user.

Good Work!

**Review by Jiyuanxia — DISMISSED** [review]
Hi @sxiong5 , I have reviewed your pull request and tested its performance. It works as you intended, and the loading speed of the weekly summaries report page has significantly improved. Previously, it took about **14 seconds** to load the page, whereas now it takes only **5 seconds**. Well done on this achievement!

**Review by n0vay — DISMISSED** [review]
Good Job. 
Saved half the time loading page.
image

**Review by iTvX — APPROVED** [review]
I have reviewed your code and tested your pull request. The speed is much quicker than the development branch. I approve your request – good job!

CleanShot 2023-08-24 at 22 06 02@2x

**Review by veronicacheng2 — DISMISSED** [review]
Hi @sxiong5, I have tested the PR. The speed of loading the summary page improved significantly. Good job!

Current branch
image

Dev branch:
image

**Comment by beblicarl** [comment]
This functionality works as intended and the refactoring you did is fantastic! Great work

### Dev Branch

We were making over 1700 requests according to the developer tools and this explains why it slowed down the application

[screencast-localhost_3000-2023.08.25-11_42_04.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/e3ede72f-1de0-49a5-9b3b-1032ea6e9400)

### Current Branch

The number of requests made was brought down to just 72. That is remarkable

[screencast-localhost_3000-2023.08.25-11_56_29.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/d5fb131e-38e3-481e-8d9b-bd1f2cf64dca)

**Review by beblicarl — APPROVED** [review]

**Review by GaryB93 — APPROVED** [review]
The Weekly Summaries Report page now has a faster load time. Great work on cleaning up the codebase as well!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/6e3e9d59-7848-4292-ae0d-7339005fedcf

**Review by Haoj1 — APPROVED** [review]
@sxiong5 Good job! Weekly summary page is loading more faster than before

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/1c9aae7a-6cc8-43eb-98ce-4bc9124324ce

**Review by liaoyufu-leo — APPROVED** [review]
Hi, I have test the changes and it become toooooo much quicker! @sxiong5

**Review by EdwinLauM — APPROVED** [review]
Hey @sxiong5! Changes work as expected! Loading time has improved

Screen Shot 2023-08-25 at 4 25 00 PM

**Review by BaileyM96 — APPROVED** [review]
Hello @sxiong5 I tested your changes and you have succesfully reduced the loading time for the weekly summaries, great work! The loading time for the summaries went from 70 seconds on my end to 4.5 seconds.

##Screenshots

Before
Weekly Summary speed BEFORE

After(sorry the image kept blowing out)
Weekly Summary speed AFTER

**Comment by AuroraLovesWhales** [comment]
Hi @sxiong5. I have tested your PR and the loading speed has indeed improved for me. Great work!

Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/9e41d50d-8c37-45b7-a0c2-de1631aac45a

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/2f6c1f35-bf90-400f-9020-864b2a3f2aa7

**Review by AuroraLovesWhales — APPROVED** [review]

**Comment by Shreyj14** [comment]
Hi @sxiong5 
Great work on making the page load significantly faster!

**Development branch**
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/dee5d685-28be-4d7d-86cc-00863be2181e

**Current Branch**
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/d9699dd5-4207-4631-b62e-eda74c7cae6c

**Review by ramyaram2092 — DISMISSED** [review]
Hello @sxiong5  Its definitely lot faster than it used to be  Good job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/5cc592bd-c38b-46bf-b61d-6f34489ce461

**Review by zuhang2000 — APPROVED** [review]
I reviewed your PR following your instructions. Work as expected! Good job! The performance now increase by a lot. The code also looks good to me. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/5123b0cc-bf94-4bf3-9ed3-f069e2697939

**Review by yaow62023 — APPROVED** [review]
I have tested you pull request, the loading speed is faster then old version. Check the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/97760009-1acd-4504-a977-b235a01b4fb2

**Review by belagaam — APPROVED** [review]
Tested the PR as per the instructions. The weekly summary page does seem to open faster. Good work.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/19234e47-de76-4f66-8405-2caaa884c999

**Review by winghojackyli — APPROVED** [review]
Hi @sxiong5 , I've tested this PR and it works great. Thank you for your work! 

### Before

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/ae62cf14-7a51-4253-a3e9-1026e1ddc476

### After


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/3e3b7be4-d79f-4d48-878f-25febc49667f

**Comment by one-community** [comment]
Thank you everyone! Resolve the merge conflicts here and I'll merge this!

**Pull request merged**
