### PR TITLE
Shihao - hotfix group member add time issue

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Screenshot 2023-10-24 at 15 34 01
Screenshot 2023-10-24 at 15 34 28

## Related PRS (if any):
This PR fixed the issue of group member added time and optimized the sorting logic in #1342.

## Main changes explained:
- Corrected the issue of group members added time
- Optimized the sorting logic

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ Other Links → Teams 
5. Check if the "addDateTime" is correct. (Hint. You can change your system date and add the member to the team to simulate adding the user at a different time)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/336a1c32-6637-4904-9bd6-b4a0794410af

### CODE REVIEW

**Review by DavidC0126 — APPROVED** [review]
Hi @sxiong5 I tested the PR and the Date added are all looking good to me. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/acbd67a5-bb06-426e-ab48-865fd958caa9

**Review by navneeeth — APPROVED** [review]
Hello, @sxiong5! Tested your changes and they work as expected. Good implementation! The value for the `Date Added` column reflects the system's date and time during the addition. And as seen in the teams list, the members are sorted by permission at top and then alphabetical below that.

### Member added on Oct 25th:
Oct 25

### Member added on Oct 17th:
Oct 17

**Review by Shubhu0 — APPROVED** [review]
Hi @sxiong5 tested and reviewed your PR and it is working as intended. Great Work!
The hotfix for changing dates was fun!

image

**Comment by palakgosalia** [comment]
Hey, I tested out your changes by changing the system date as well. It works as intended. Good work. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/c909343f-284b-4f17-9fc3-89ae165de0e1

**Comment by beblicarl** [comment]
This functionality works and the code is cool

image

**Review by beblicarl — APPROVED** [review]

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I have verified your updates, and they are functioning as anticipated. The "Date Added" column accurately displays the date and time of the system when the addition is made. Additionally, in the list of team members, those with higher permissions are listed first, followed by the rest of the members in alphabetical order.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/358e0b5c-d28a-4fb6-86f4-5d2715c45597

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
