### PR TITLE
Changhao - added new test cases for UserTableData

### PR DESCRIPTION
**Pull request by Changhao3220K**
# Description
New unit tests cover the edge cases for UserTableData.jsx 

## How to test:
1. check into current branch
2. do `npm install` and `npm test UserTableData.test.js` to run this PR locally
3. verify all 21 tests are passed

## Screenshot:
Screenshot 2024-01-11 at 5 39 43 PM

### CODE REVIEW

**Review by pshereen — APPROVED** [review]
Checked into the usertabledata_unit_test. 
Ran the following local: 
npm install
npm test UserTableData.test.js

All 21 test cases are passed.

image


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/851637dd-ab87-4390-a96e-eba234319b53


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/845d5fa2-ecea-483c-95b0-4c833bb6e567

**Review by bajajtushar094 — APPROVED** [review]
@Changhao3220K all your test cases passed as stated. Thanks
Screenshot 2024-01-12 at 21 52 50

**Review by bienzguoa — APPROVED** [review]
All test passed! The code looks clear for added edge cases and rendered correctly.
Screenshot 2024-01-12 at 8 50 53 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2024-01-12 at 9 56 45 PM

**Comment by iTvX** [comment]
All testes passed, good job!

CleanShot 2024-01-13 at 11 19 19@2x

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 20 - PR1

**Review by n0vay — APPROVED** [review]
LGTM
image

**Review by peterson337 — CHANGES_REQUESTED** [review]
I ran 'npm test UserTableData.test.js' in the terminal and only 17 tests passed.                           

Print 1

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73541319/b6b090c9-8186-45ac-8c8d-c4490306271a

**Review by 666saofeng — APPROVED** [review]
All tests passed!
image

**Review by X1aoZhang99 — APPROVED** [review]
Hi Changhao,

All tests passed. Nice work! 

Screenshot 2024-01-31 at 10 30 49

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed as expected. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/b167f019-4a86-45d3-9e1b-b5968828192b

**Comment by xmyoot** [comment]
Hello, 
all tests passed successfully 
PR#1814

**Review by Pandani07 — APPROVED** [review]
All the test cases passed. Also explored the app for any bugs and could not find any, all components rendered as expected
Screenshot 2024-02-10 at 1 05 35 PM

**Review by ramyaram2092 — COMMENTED** [review]
Good job on the Test cases 
image

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and all the test cases have been successfully passed.
Screenshot 2024-02-13 at 12 59 53 AM

**Review by ShengjieMao — APPROVED** [review]
All tests passed. The cases are comprehensive and the components are all tested 
PR_1814

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
