### PR TITLE
Ramya Unit Test :UsersProfile/ ToolTips/TabToolTips 

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit test for src/components/UserProfile/ToolTips/TabToolTips

## Main changes explained:
-  New files
      - **_TabtoolTips.test.jsx_** : unit test cases 
      -  _**MockNavLink**_ :  Mock component for the test cases   
- Existing file 
      - **_TabtoolTips_**  : Added  data-attribute to the objects 

## How to test:
1. check into current branch
2. do npm test TabToolTips.test.jsx
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed as intended. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/521ddfe8-c839-4000-a097-44ea8a0deac0

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work! 
Screenshot 2023-12-17 at 1 16 32 AM

**Review by ljrirene — DISMISSED** [review]
Goog job! All tests passed on my side.
WX20231217-024206@2x

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-18 at 10 19 42 PM
All tests have passed successfully. Excellent job!

**Comment by beblicarl** [comment]
all tests passed

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
