### PR TITLE
Yihan send review email

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
截屏2023-07-25 19 15 37

## Related PRS (if any):
This frontend PR is related to the [#482 ](https://github.com/OneCommunityGlobal/HGNRest/pull/482)backend PR.
This PR is based on [PR#1013](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1013). I recommand to test #1013 before review this one.

## Main changes explained:
- Update file ReviewButton.jsx for executing send email function after click on "submit" button.

## How to test:

Before moving to testing, firstly you need to set up your own test email id to send the mail notification.
This is only for test purposes. Once tested you can revert these changes. These changes are not required on the main.

To send email using Gmail API using OAuth2 and nodemailer, kindly follow the below video and setup up a test mail id.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

Fill below variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE

(resource: #964 )

============================================================================================

1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any user
4. go to dashboard→ Tasks → "Submit for review" → "Submit"
5. verify you, other Amin/Mentor/Manager users on the same team and highestgoodnetwork@gmail.com receive the review request email.

## Screenshots or videos of changes:

Submit test 2 for review: 
截屏2023-07-26 15 34 40

Then receive the email:
截屏2023-07-26 15 30 28

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hi @AriaYu927 , I tested your PR and it works great. 

I submitted the review for "1.3.2.1 Create sheep barn assembly instructions" and I received email. 




Screenshot (5)

**Review by xaanders — DISMISSED** [review]
Hi @AriaYu927 ! I have tested your PR and it works good!

**Review by ramyaram2092 — COMMENTED** [review]
Hello @AriaYu927 
As part of testing this functionality I tried to log into volunteer  or mentor  to "Submit for review"
But the app keeps crashing for volunteer mentor and manager class. This issue doesnt happen for owner and admin
Console :
image

**Testing video**
 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/8a654787-8e0f-458d-8b93-4da1bf2c4b7a

**Comment by n0vay** [comment]
Still getting error in Backend.
image

**Comment by n0vay** [comment]
The other error where I cant see other accounts from mentor is fixed, Good Job on that!

**Comment by AriaYu927** [comment]
> The other error where I cant see other accounts from mentor is fixed, Good Job on that! image

Hi @n0vay , I just would like to confirm if this one and the above comment is for this PR?

**Review by zuhang2000 — CHANGES_REQUESTED** [review]
Hi Yihan! I have tested your PR following the instructions. I follow through the youtube tutorial and successfully configure the .env. However whenever I log in with Volunteer account, the dashboard is redirected to a blank page. The same thing also happens to Manager account but not with the Admin account. You may check my recording here.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/89716109-7647-4a22-97c6-e3a5d0ea63f5

**Comment by veronicacheng2** [comment]
Hi @AriaYu927, I face the same issue as @zuhang2000 and have difficulties accessing the dashboard page when I am logged in as Volunteer. 

image

**Comment by AuroraLovesWhales** [comment]
Hi @AriaYu927. I tested your PR and I'm also facing the same issue as @veronicacheng2, @zuhang2000, and @ramyaram2092. Below is a recording when I logged in as a volunteer.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/365d73c3-af1f-4410-9813-c3d2dc9d087e

**Comment by AriaYu927** [comment]
Hi @zuhang2000 @veronicacheng2 @AuroraLovesWhales , I went through all the errors and warnings and I thought they are caused by InfiniteScroll, which is out of the scope. So, I updated this branch with the development branch. Now, the dashboard can be load successfully on my end. Please check this PR again and let me know if there's still any issue.

**Review by DavidC0126 — COMMENTED** [review]
Hi @AriaYu927 I tested your PR and it works as intended. I was able to receive an request review email as an admin in the same team.

email
request

**Comment by Lin1404** [comment]
Hi @AriaYu927 I tested your PR and it works as intended. Good Job！

image

image

**Review by Lin1404 — DISMISSED** [review]

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR. It works as Intended. I'm getting a mail after I submit for review.

Screenshot 2023-09-20 at 4 47 25 PM

Screenshot 2023-09-20 at 4 51 43 PM

**Review by StrawberryCalpico — DISMISSED** [review]
Hi I tested your PR, there is some bug that user cannot created a WBS, and user can't submit the task for review. 

Screenshot 2023-10-14 at 1 02 43 PM

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hi @AriaYu927, I have reviewed this PR and the email functionality seems to work as described (good job on that!). The issue I am facing is that I have 2 volunteers, a manager, a mentor, an admin and an owner on a project/wbs/task, but when a review request is submitted by a volunteer or the owner, only the admin receives the "Review Request" email. Is that how its supposed to work or is there anything I am missing?

Screenshots:

Screenshot 2023-10-17 202318

Screenshot 2023-10-17 202335

Screenshot 2023-10-17 202345

Screenshot 2023-10-17 202519

**Comment by AriaYu927** [comment]
> Hi @AriaYu927, I have reviewed this PR and the email functionality seems to work as described (good job on that!). The issue I am facing is that I have 2 volunteers, a manager, a mentor, an admin and an owner on a project/wbs/task, but when a review request is submitted by a volunteer or the owner, only the admin receives the "Review Request" email. Is that how its supposed to work or is there anything I am missing?
> 
> Screenshots:
> 
> Screenshot 2023-10-17 202318 Screenshot 2023-10-17 202335 Screenshot 2023-10-17 202345 Screenshot 2023-10-17 202519 Screenshot 2023-10-17 203524

Hi @malikjahanzaib , thanks for your testing. 
Let's say A sends a review request. Then, the email can only be sent to the Admin, Manager and Mentor user who is in A's team. So, you need to assign team for your Mentor and Manager user first.
image

**Comment by AriaYu927** [comment]
> Hi I tested your PR, there is some bug that user cannot created a WBS, and user can't submit the task for review.
> 
> Screenshot 2023-10-14 at 1 02 43 PM

Hi, thanks for your testing. I've updated this PR, could you please check it again when you get a chance?

**Review by cvtqx — APPROVED** [review]
I've tested this PR from volunteer's and manager's account. Functionality works as described in both, I received emails and all manager/admin/mentor roles from the team were cc'ed as well as highestgoodnetwork@gmail.com.

Volunteer:

Screen Shot 2023-10-20 at 2 12 53 PM


Volunteer's team:

Screen Shot 2023-10-20 at 2 14 35 PM

Manager:

from manager

I've verified that all those emails are admin/manager/mentor roles.

I would advocate for including a more detailed guidance on how to test such complex PRs, for example include link to this document for emailing set up: https://docs.google.com/document/d/1HJJTDtWykjGb4IfiIFlHXDfp_IABvmwKxsMPqqF6rG8/edit, then instruct on how to assign a task, and that a person must be a part of a project and a team etc... There are many new people testing PRs and without clear instructions it takes a long time to figure things out. 

Other than that great job!

**Comment by malikjahanzaib** [comment]
> > Hi @AriaYu927, I have reviewed this PR and the email functionality seems to work as described (good job on that!). The issue I am facing is that I have 2 volunteers, a manager, a mentor, an admin and an owner on a project/wbs/task, but when a review request is submitted by a volunteer or the owner, only the admin receives the "Review Request" email. Is that how its supposed to work or is there anything I am missing?
> > Screenshots:
> > Screenshot 2023-10-17 202318 Screenshot 2023-10-17 202335 Screenshot 2023-10-17 202345 Screenshot 2023-10-17 202519 Screenshot 2023-10-17 203524
> 
> Hi @malikjahanzaib , thanks for your testing. Let's say A sends a review request. Then, the email can only be sent to the Admin, Manager and Mentor user who is in A's team. So, you need to assign team for your Mentor and Manager user first. image

That worked, guess I missed the point where they have to be in the same team. I apologize for not reading the description carefully. Thank you so much for the help. Once again, Great Work!!!

Approving changes.

Screenshot:

Screenshot 2023-10-20 232608

**Review by malikjahanzaib — APPROVED** [review]

**Pull request merged**
