### PR TITLE
EduardoV - create a unit test for the Team component

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the Team component to confirm whether it working as intended.

Screenshot_1

## Main changes explained:
- Update file Team.jsx file by adding 'data-testid' to active-input and member-button to get these elements in the test
- Create file Team.test.js to do the unit test

## How to test:
1. check into current branch
2. do `npm install` to run this PR locally
3. cd HighestGoodNetworkApp
4. open file src → __tests__ → Teams → Team.test.js
5. run `npm run test /src/__tests__/Teams/Team.test.js`

## Screenshots or videos of changes:
This the result it's suppose to get:

Screenshot_2

If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by vinaykumarh — APPROVED** [review]
Reviewed the PR, apart from few warning it is working as expected.
Good work!

Review:
image

**Review by iTvX — APPROVED** [review]
Tested with my WSL 2, worked as intended. Great job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/51843091-cf8c-4a44-822c-f8f14c604395

**Review by gabi-lima — APPROVED** [review]
Working as expected. Well done!

image

**Review by Haoj1 — APPROVED** [review]
@eduvarjaor Tests all passed. Good work

**Review by ss23046 — APPROVED** [review]
Hi @eduvarjaor 
Tested your PR, it works
Screen Shot 2023-08-31 at 3 52 45 PM

**Review by DavidC0126 — APPROVED** [review]
LGTM. Good work!
test

**Review by robertoooc — APPROVED** [review]
Hi @eduvarjaor, I tested your unit test and it worked well as expected. Nice Job.
Screenshot 2023-08-31 at 5 23 34 PM

**Review by luisarevalo21 — APPROVED** [review]
Hello @eduvarjaor 

I tested your PR and works as intented great job!
CD into the root director of HighestGoodNetworkApp, then  running the test script yielded 1 test suite and 6 pass and no errors. 
Screenshot 2023-08-31 at 8 08 34 PM

**Review by EdwinLauM — APPROVED** [review]
Hey @eduvarjaor! Tested your PR and works as expected! 

Screen Shot 2023-09-01 at 12 01 21 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Review by harshidad — COMMENTED** [review]
I tested your PR and works as intented great job!
Team component #1212

**Review by winghojackyli — COMMENTED** [review]
I've tested the PR and all tests passed. 

image

**Pull request merged**
