### PR TITLE
Luis error message on admin page

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description
(PRIORITY Low)  Jae/Joyce: Error message should disappear when search for a popupEditor item (WIP Luis) 
If a person goes to the admin page, enters “123”, and hits the search icon. The error message will appear in the consol when one clicks on the inspector.
Screenshot 2023-08-14 at 10 15 57 PM

## Main changes explained:
Was asked to fix the error message. When searching into the search bar. 
Figured out the error was because useState was setting data to null, so when searching it would throw an error. 
After speaking with Jae, he concluded it wasn't necessary since we can search via the browsers built in search function. 
See comments for details. 

Screenshot 2023-08-14 at 8 35 15 PM

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as an admin user
4. go to dashboard→ other links → popup management.  
5. Search bar was removed and the error message is no longer there. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/c97bc5b5-cc32-41e4-baba-0fedd04d28c8

### CODE REVIEW

**Review by TheDescendant39 — COMMENTED** [review]
Hi @luisarevalo21, I was able to reproduce the issue on the development branch and then confirmed that the search bar was removed, as required. Good Job. 

Before:

After:

**Review by robertoooc — APPROVED** [review]
Hi @luisarevalo21, I tested your branch and found no issues with it. The search bar was removed along with it's console logged error.

Before: 
Screenshot 2023-08-15 at 9 09 59 AM

After: 
Screenshot 2023-08-15 at 9 11 53 AM

**Comment by Jiyuanxia** [comment]
Hello @luisarevalo21, I've reviewed your pull request and conducted testing on it. I'm pleased to inform you that everything is functioning as you intended. Great work!

Before
Screenshot 2023-08-15 144134

After
Screenshot 2023-08-15 144009

**Review by winghojackyli — DISMISSED** [review]
Hi @luisarevalo21 , I've tested this PR and everything works as intended. 

#### Before

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/297163af-bcee-4702-877d-2bd71e6f0623

#### After

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/4dc8f9d4-7dda-4557-87b1-5f1452908e18

**Pull request merged**
