### PR TITLE
kaushik_fix_usermanagement_delete_finalday_button

### PR DESCRIPTION
**Pull request by KaushikMreddy**
# Description
image

## Related PRS (if any):
This frontend PR is related to the dev backend.

…

## Main changes explained:
- Updated UsertableData.jsx 
- Set delete final day button to be set according to existence of end data value
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/Owner user
5. go to dashboard→ other links→ user management
6. Set a user's final day
7. If the user's final day is set, the `Set Final Day` button should change to `Delete Final Day`
8. Check if the change reflected in that user's profile ( click on their name )

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/144624017/decb61e2-316c-4099-8ec4-aaa20dfa4f92
## Note:

Include the information the reviewers need to know.

### CODE REVIEW

**Review by kdaga81 — COMMENTED** [review]
image
The changes are not reflected in my instance

**Comment by KaushikMreddy** [comment]
> image The changes are not reflected in my instance

Hi, its reflecting for me
image

try to reload your application, clear your terminal, run npm install and npm run start:local again

**Comment by Vijeth-V** [comment]
The changes are reflected, and I was able to set a final date for the user.
I have shared a video of the working.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/c99ae196-e53c-4985-80b6-02e2e604698b

**Review by Jingyii800 — DISMISSED** [review]
Well done! As an owner role, now I can set final day in user management for specific user. This will immediately reflect on the user's profile page. After deleting final day, the final day will also become N/A on user profile page. Works well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/39494100-4241-4e2a-8182-738c61569cbc

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR as admin & owner and the "Set Final Date" functionality works fine. Able to add and delete the final date easily! The date validation is provided for wrong selection of past date. Great Work!
Suggestion:
1. The final date displayed in the profile page is one day previous to the date selected in the user management page. Is that the logic ?
2. The Logged in user like admin / owner is having the option to set their own "Set Final Date". This can be disabled for the logged in users.

**Comment by sahithidhulipala9** [comment]
Able to verify the function in both admin and owner accounts, great work!

https://www.loom.com/share/2544d92a2f6745d6a0149b5163813d73

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by suaniii — DISMISSED** [review]
Hi, the change worked well. I've tested on both admin and owner account. Set a user's final day in the `user management` page, and the `Set Final Day` button did change to `Delete Final Day`. This `Delete Final Day` button and the date also reflected in that user's profile.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/c882df6d-7d9d-4fef-bda0-f7058a54914a

**Comment by KaushikMreddy** [comment]
> I have tested the PR as admin & owner and the "Set Final Date" functionality works fine. Able to add and delete the final date easily! The date validation is provided for wrong selection of past date. Great Work! Suggestion:
> 
> 1. The final date displayed in the profile page is one day previous to the date selected in the user management page. Is that the logic ?
> 2. The Logged in user like admin / owner is having the option to set their own "Set Final Date". This can be disabled for the logged in users.
>    
>    
>    
>    

Hi Logesh, 

My work with this bug is limited to fixing the button change as per the end date being set. But your suggestions are good, raise a bug in the document, and see if Jae approves it. We can move forward from there.

**Review by Sudershhh — DISMISSED** [review]
After I set the Final Day, the button is changed to "Delete Final Day" and the change is also reflected in the user profile. The same is true after I delete the final day.

Good Job!

PR 2366

**Review by aaryaneil — COMMENTED** [review]
The changes work as expected and the final day which is set is also visible in the user's profile with the delete final day button. But when I click the delete final day button on the user's profile the button changes but on refreshing the page the changes do not persist.
Screenshot 2024-06-21 at 3 04 56 PM
Screenshot 2024-06-21 at 3 05 07 PM
Screenshot 2024-06-21 at 3 05 36 PM

**Review by ImzIssa — DISMISSED** [review]
I've tested your PR and your changes work as expected.

Screenshot (402)

**Review by shradac — DISMISSED** [review]
I have tested this PR. I set a user's final day. The "Set Final Day" button changed to "Delete Final Day". I then checked to see if the change was reflected in that user's profile by clicking on their name. Good job!

Screenshot 2024-06-22 at 4 28 18 PM
Screenshot 2024-06-22 at 4 28 28 PM
Screenshot 2024-06-22 at 4 28 38 PM

**Comment by KurtisIvey** [comment]
Merge conflict :( 

Would you be able to clear it up please when you have a chance, so we can get this pushed to final review

**Review by vishavk1992 — DISMISSED** [review]
From my owner account, I am able to set the final day for a user, and it reflects on the user's profile. I can also delete the final day from my owner account.

PR-2366-2
PR-2366

**Review by jinxyou — DISMISSED** [review]
I set the final date for a user, and the button toggles as expected, as well as the profile of the user will change correspondently. Great work!
Screenshot 2024-06-22 174622
Screenshot 2024-06-22 174632
Screenshot 2024-06-22 174647

**Review by deepthikannan — DISMISSED** [review]
image
From owner account I'm able to set the final date, the changes are reflected in the user profile as well.

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected. I was able to delete the final day with the new button.
Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/ebc19fd5-2693-46a2-8f4e-390761ad09cf

**Comment by beblicarl** [comment]
this functionality works as intended, great work!

image

**Review by beblicarl — DISMISSED** [review]

**Review by nathcarnevalli — DISMISSED** [review]
The changes are reflecting for me. Nice work :)

Screenshot 2024-06-28 111132

**Review by anandsesha — DISMISSED** [review]
Tested this feature and both Set and Delete Final Day works fine. I was able to see the changes in the End date field and the user's page.

Please make sure to address if this was the intended implementation - The final date displayed in the profile page is one day previous to the date selected in the user management page.
Screenshot (954)
Screenshot (956)
Screenshot (957)
Screenshot (958)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
