### PR TITLE
Jiayu add standard time entry and description to "add lost time"

### PR DESCRIPTION
**Pull request by peter6866**
# Description
image

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch of backend.

## Main changes explained:
- Update `AddLostTime.jsx` to include the note entry for adding lost time of person.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Reports -> Reports
6. click **Add Lost Time** and click person type
7. verify that there is a entry for note
8. enter a note and submit
9. in the database, verify that the note is in the TimeEntries collection with person type. (Follow the video below to check)
11. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
https://www.loom.com/share/9918f66af118487fa20ce80b41c8c8ab?sid=15f0f042-e4c9-414f-bfda-4ae57b7fa534

### CODE REVIEW

**Review by aaryaneil — COMMENTED** [review]
Tested the PR and while adding a time entry I received a 500 error code.
Screenshot 2024-07-14 at 12 20 32 AM
Screenshot 2024-07-14 at 12 20 51 AM

**Review by JatinAgrawal94 — DISMISSED** [review]
On Submitting the time for a project, page shows 500 internal server error.

https://github.com/user-attachments/assets/bc474c50-2ace-4765-b847-12aaacabec92

**Review by SrikanthChowdary495 — CHANGES_REQUESTED** [review]
ICheck into the current branch, run npm install, and then npm run start:local to run this PR locally. Clear the site data/cache, log in as an owner user, and go to Dashboard → Reports → Reports. Click "Add Lost Time" and select a person type. Ensure there's a field for a note, enter a note, and submit it. 

Everything works as expected. Please find the below video.

https://github.com/user-attachments/assets/0b97785e-678c-404a-83d2-5ca334e3919f

**Review by kabraambika — APPROVED** [review]
I have reviewed the PR and able to add lost time for person type as shown below. Hence, Approving this PR. Thanks!

https://github.com/user-attachments/assets/bdcd5880-e9d5-4b20-bd0c-5142cffa393a

**Review by ishan-miglani — APPROVED** [review]
I have tested the changes. I am able to log Person lost time with notes. It works in dark mode as well.

https://github.com/user-attachments/assets/586b2620-8afa-4ab6-abdc-6fc026374b1d

**Comment by Parth-tech** [comment]
Hey Jiayu,

The PR works as intended. The codebase looks good too.
Screenshot 2024-07-18 at 8 07 49 PM
Screenshot 2024-07-18 at 8 08 18 PM
Screenshot 2024-07-18 at 8 09 19 PM
Screenshot 2024-07-18 at 8 09 29 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (136)
Screenshot (137)

**Review by Chetan0606 — APPROVED** [review]
Tested the code as per the given instructions and working as expected. But when trying to edit lost time I am unable to edit the notes. Please correct me if I am wrong
Screenshot (304)
Screenshot (306)
Screenshot (307)

**Review by SrikanthChowdary495 — APPROVED** [review]
Check into the current branch, run npm install, and then npm run start:local to run this PR locally. Clear the site data/cache, log in as an owner user, and go to Dashboard → Reports → Reports. Click "Add Lost Time" and select a person type. Ensure there's a field for a note, enter a note, and submit it.

Everything works as expected. Please find the below video.

**Review by angelalalacheng — APPROVED** [review]
Hi, 
I use `jiayu_lost_time_note` for the frontend and the latest development branch as backend. Both light and dark mode works good! But, there seemed like a minor bug when the popup shows, the components in the background will move to left.

Light mode:
https://www.loom.com/share/e3309b4c7b494bc2abe85a44cf169ee9?sid=124e1f13-cc70-4db5-b6f1-30f6789d8dd9

Dark mode:
https://www.loom.com/share/0c00762254594f2296ace44318a2e2f4?sid=0db03597-c1f6-414a-9edd-d6b06491c276

**Review by pavanswaroopl — APPROVED** [review]
Excellent Work,

Tested in both frontend and backend, changes working as expected

https://github.com/user-attachments/assets/67a3d26f-d9ee-4862-b5f4-974b6dce5c88

Screenshot 2024-07-20 at 8 52 51 PM

**Comment by souravwalke** [comment]
Tested the contents of the PR and everything is working as expected.

https://www.loom.com/share/68f3be904cf4445cbcbbde5c3d5b5abd?sid=67198b31-0b08-4457-b972-75dd1a10ea29

**Review by Jingyii800 — APPROVED** [review]
I have tested this PR. Logging in as Owner account, I am able to add lost time for a user with notes both in light mode and dark mode. Great work.

https://github.com/user-attachments/assets/fb5e5dec-9f5d-47f9-925f-3c8ee9ce33e5

**Review by ReinaT5678 — APPROVED** [review]
Hi! I tested the files and everything seems to be showing up! Good job!

https://github.com/user-attachments/assets/4aea7807-fa1a-4e19-bb72-c8380e1ec6bd

**Comment by arunsrao9** [comment]
I have tested the changes. I am able to log Person lost time with notes. It works in dark mode as well:
Screenshot 2024-08-05 at 12 21 31 PM
Screenshot 2024-08-05 at 12 20 34 PM
Screenshot 2024-08-05 at 12 21 49 PM
Screenshot 2024-08-05 at 12 21 38 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
