### PR TITLE
Shuhua - Add toaster to Permissions Management

### PR DESCRIPTION
**Pull request by Shuhua-L**
# Description
description

## Related PRS (if any):
N/A

## Main changes explained:
- Updated files `src/components/PermissionsManagement/Preset.jsx`, `src/components/PermissionsManagement/Preset.jsx` for adding toast notifications 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log in as Owner -> Other Links -> Permissions Management -> choose a role
5. Verify successful notifications for the following actions:
    a. To apply a preset, click "**Load Presets**," pick one, and "**Apply**"
    b. To delete a preset, click "**Load Presets**," pick one, and "**Delete**"
    c. To create a new preset, click "**Create New Preset**"
6. Verify error notifications for these actions:

    Option 1: Manually change the code to cause server errors
             a. Comment out line 43 in file `src/components/PermissionsManagement/Preset.jsx`, save, refresh the page; applying presets will cause 400 errors
            b. Change the preset id at line 58 in file `src/components/PermissionsManagement/Preset.jsx`, save, refresh the page; deleting presets will cause 400 errors
            c. Comment out line 70 in file `src/components/PermissionsManagement/RolePermissions.jsx`, save, refresh the page; creating presets will cause 400 errors

    Option 2: Stop the server to cause network errors

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/732721f1-d969-4fb1-a18c-40f974409b95

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/e68684b3-e8ae-4c27-8080-a3ce575b9685

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/917a79ac-0a8b-4d63-873e-3f8a0a06b163

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/073d5318-f1a7-46fb-aed8-4105ae9f91a9

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/dedab374-0ff7-441d-87f9-458c1422ce02

## Note:
- The app will crash if you click on these two info icons. This is a known issue and unrelated. Just refresh the page if it happens.
issue-info-icons

### CODE REVIEW

**Comment by bajajtushar094** [comment]
Hi @Shuhua-L, I have reviewed your changes. They are working fine. I have checked them for success toast of create, delete, and apply preset functionality, and error toast  for create, delete, and apply preset. I have recordings of the same.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/218957ce-b80a-4bc0-823b-0e46c0785c6b 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/2b7e3dcc-441a-442e-adb0-30afe0eff417


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/fa7ec840-049a-423a-812d-f9c399fb1551


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/7892fb3b-75b4-43f7-9636-fcf67c14f6c1

**Review by bajajtushar094 — APPROVED** [review]
Hi @Shuhua-L, I tested your code for success and error toast for create, apply and delete preset. It seems to be working fine and code looks good too. I am attaching videos of the same. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/23c7d26e-8880-48a2-afc3-a75106a2023f


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/f5c16c5e-9939-446d-b902-f32842f4c0f0


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/56ed3ac6-b1f5-49fe-8681-b52815aacba2


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/226936e4-f9a6-45a7-b9bb-4acb6fd38f2c

**Review by BaileyM96 — APPROVED** [review]
Good morning @Shuhua-L, I went ahead and approved your PR.

I was able to create a new preset, delete presets, and load presets and see the new toaster notifications pop up on my screen. I also tested the error messages as you mentioned and all of those worked as well. Great work!

## Screenshots

Error Messages:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/e2d6c693-53ac-432a-887a-5753c7ea2500


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/e6a7378b-7636-4849-83e9-899af2df461b


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/42895ef3-4ded-47a5-8ba8-5771dff1fc25


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/febda98d-bc90-4855-a47c-7d5c83566567

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
