### PR TITLE
Nathan permission categories

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR turns category permissions into multi-checkboxes instead of their own permissions to prevent overlap. To do this, it creates a component to display permissions wherever needed

## Related PRS (if any):
[Back-end PR 585 fixes the `Cannot read property 'permissions' of null` BE error which will make testing this easier](https://github.com/OneCommunityGlobal/HGNRest/pull/585)

## Main changes explained:
- Created `PermissionsConst` to restructure permissions to account for categories and consolidate `mainPermisisons`, `modalInfo`, and `permissionLabel`.
- Created `PermissionList` and `PermissionListItem` components to be reused wherever needed
- Added multi-checkbox functionality to categories in `PermissionListItem`
- Moved info point modal logic into `PermissionListItem` to reduce redundancy
- Implemented `PermissionList` for updating role permissions, role presets, new roles, and user permissions

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. login as owner user
4. go to dashboard→ Other Links→ Permissions Management
5. go to each of: "Manage User Permissions", "Add New Role", any actual role, and "Load Presets" in any role
6. verify info points work in every location
7. verify adding and removing permissions work in every location (except presets which should not be editable)
8. verify changes save and persist after reload

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/23086054/04e1e1d3-27ad-4e9a-901b-8d20a2468f56

### CODE REVIEW

**Review by beblicarl — DISMISSED** [review]

**Review by JeffLi117 — DISMISSED** [review]
Initially, the code works great! At some point or another, though, I think there gets to be too many errors on the back-end, which (for lack of a better term/knowledge on my part) seems to "stick" up some of the intended functionality, whether that's adding new roles or deleting recently added ones. 

I'm unsure how this is all happening directly, but I seem to get the error on the back-end when I 1) create a new role and then 2) immediately click on said role after its creation. The error I see is shown below:

image

Perhaps due to incorrect modification on the front-end to reflect the similar changes in the back-end/database?

This is the video showing what I experienced when I created some roles, clicked around, but then became unable to create another role.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112568110/2466943e-532f-4c24-bda2-0c3a30bd4b17

**Review by Bali2Mohit — COMMENTED** [review]
Hi @nathanah , I tried testing the PR, but I am unable to view the Management button. I tried with my account as Admin as well as the generic DevAdmin account. But i didn't work for both.
Can you suggest what might be wrong here
Screenshot 2023-11-18 at 16 19 37

**Comment by nathanah** [comment]
> Initially, the code works great! At some point or another, though, I think there gets to be too many errors on the back-end, which (for lack of a better term/knowledge on my part) seems to "stick" up some of the intended functionality, whether that's adding new roles or deleting recently added ones.
> 
> I'm unsure how this is all happening directly, but I seem to get the error on the back-end when I 1) create a new role and then 2) immediately click on said role after its creation. The error I see is shown below:
> 
> image
> 
> Perhaps due to incorrect modification on the front-end to reflect the similar changes in the back-end/database?
> 
> This is the video showing what I experienced when I created some roles, clicked around, but then became unable to create another role.
> 
>  HGN.APP.-.Google.Chrome.2023-11-17.08-47-53.mp4

This error is not caused by this PR (should be fixed by this PR https://github.com/OneCommunityGlobal/HGNRest/pull/585).

**Comment by GKD890** [comment]
It works as intend, and also fix the 'giving the permission to edit admin links' while using frontend and backend. Will be back approve the code.
A small thing: for managing the **Owner**'s role, do you think we should disable the **Delete Role** for **Owner** itself?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/236be198-f7c8-4926-99c5-29f69e7e3b5b

**Review by Alforoan — DISMISSED** [review]
Functionality works as intended, but there's some issue with it on the backend. 
image


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/bd4ca8fa-c80d-4bbc-8973-70fa9a7b3875

**Review by ljrirene — DISMISSED** [review]
Hi Nathan,
I logged in as an owner. It looks well when I try to edit the permissions. However there are still some problems here:
1. It has several backend problems here when I tried to add a new role:
image
2. I can't delete this role after I create it. Not sure if this is not related to the task.

Here is my test recording:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/33f6b3b7-8d4a-42eb-92a3-3f6fc29605cc

**Comment by this-journey** [comment]
Code seems to be working properly and when using BE 585 I received no errors in my back end terminal.  Here's a small sample of all the user roles/permissions I tried.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/8f90303a-2821-46e4-99dc-ec7a8f608114

**Review by navneeeth — CHANGES_REQUESTED** [review]
Hello, @nathanah. Great effort on redesigning the structure of the permissions list! I really liked the non-overlapping nature of the list design. 

Logged in as an Owner user and in each of "Manage User Permissions", "Add New Role", any actual role, and "Load Presets" in any role, the info points work, adding and removing permissions works, and the saved changes persist on reload.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/8ce47b1f-4397-4106-870c-8e5f924072ec

## Issue
wbs

However, I observed that in the implementation, you have referred to the above permission as 'Work **Balance** Structures' instead of 'Work **Breakdown** Structures'. I believe an update is required in `src/components/PermissionsManagement/PermissionsConst.js` to reflect the correct permission name. Thank you!

**Review by navneeeth — APPROVED** [review]
Thank you for addressing the issue, @nathanah! The fix LGTM in the Permissions list as well as in the info point.
issue_fixed

**Pull request merged**
