### PR TITLE
Yubo fix manage 'adminLinks in user profile' permission

### PR DESCRIPTION
**Pull request by GKD890**
# Description
Frontend_PR_Description

Fixes # 4 in PERMISSIONS MANAGEMENT COMPONENT (medium)

## Related PRS (if any):
It's related to PR #1001, which hasn't been merged into dev yet.
…

## Main changes explained:
- Fix the `canEdit` permission in `UserLinkLayout.jsx` by importing `hasPermission()`.
- Remove some unused props from parent component `UserLinkLayout` to its children components.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as **Owner** user first (it's higher than **admin**, thus you need to ask to upgrade your dev account to **Owner**)
4. go to dashboard→ Other Links→ Permissions Management→ Manage User Permissions (a button on the right side) -> choose a user (let's call it **User B**) you want to grant the permission (need to search the user in the input area) -> choose **Manage Admin Links in User Profile** and submit
5. log as **User B** choose any other users to go to their **User Profile** page -> verify you can edit the Links under their Picture.
6. click `update` function so, but notice you can't **save** as so far you don't have that permission.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/bdbbb8fb-e3c4-40b4-818b-f46e8e77bcc5

## Note:
# !!At this moment, you can't **Save**!

### CODE REVIEW

**Review by xaanders — APPROVED** [review]
Hi @GKD890! I've tested your PR. Works good! 
I've tested it with different users. I could update but not to save due to other permissions. 

[scrnli_7_25_2023_1-16-29 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/cf519390-bb7f-4b69-b76b-0e41d0ec4b56)

Good job!

**Review by winghojackyli — DISMISSED** [review]
Hi @GKD890 , I tested your PR and it works great. The "ADD LINK" part can be edited but cannot be saved as mentioned. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/35cb3228-aac2-4169-aa95-69bd6651de95

**Review by eduvarjaor — DISMISSED** [review]
Hi @GKD890 

You made a good job! Everything working perfectly.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/1ce973a5-3d0a-4153-b0ea-9b97dc4c4148

**Review by veronicacheng2 — APPROVED** [review]
Hi @GKD890 , I tested according to instructions and it works perfectly

Logged in as Volunteer before adding permission to manage admin links in user profile:
Before adding permission

Logged in as Owner to add permission to manage admin links in user profile:
Adding Permission to manage admin links in user profile

Logged in again as Volunteer and now admin links can be edited in user profile:
Logged in as Volunteer again to check Edit Link

**Review by BaileyM96 — COMMENTED** [review]
Hello @GKD890  I reviewed your changes and everything seems to work fine, and I am able to grant permissions to a user and edit the links with that permission

I do have one question. In your PR you said you are not able to save your changes but when I edited my changes and created the links  I was able to save the changes and refresh the page. But say when I want to edit the links it does not allow me to save the changes. Is that the scope of the PR? I could use some clarification for that please.

## Video Walkthrough

Manage user permissions as Owner

[PR # 1035 manage user permissions as owner.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/29aa2c79-b364-4032-a8a9-190a33c5d599)

adding links/editing links as a volunteer 

[PR #1035 manage admin links in user profile _Volunteer_.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/bff171ef-c9d0-4ce3-95ae-669328d5dfe0)

**Comment by GKD890** [comment]
> Hello @GKD890 I reviewed your changes and everything seems to work fine, and I am able to grant permissions to a user and edit the links with that permission
> 
> I do have one question. In your PR you said you are not able to save your changes but when I edited my changes and created the links I was able to save the changes and refresh the page. But say when I want to edit the links it does not allow me to save the changes. Is that the scope of the PR? I could use some clarification for that please.
> 
> ## Video Walkthrough
> Manage user permissions as Owner
> 
>  PR.1035.manage.user.permissions.as.owner.webm 
> adding links/editing links as a volunteer
> 
>  PR.1035.manage.admin.links.in.user.profile._Volunteer_.webm

Hi @BaileyM96 , thank you for reviewing my code. I've noticed in your 2nd video, you are editing the links for yourself. After you've got the permission, you should test if you can edit other users' admin links. I guess it's because your volunteer account isn't in any team or projects, so that you can't go to other's user profile page just by clicking. 

If so, I suggest you add your volunteer account to a project and a team so you see others on the right side of Dashboard page. 

Or, let's say **UserB** is given permission and you are login as **User B**, you could simply copy another user **User C**'s url of their user profile page, and paste to the window that **User B** is login. then you are using editing a different person's admin links. 

Let me know if I'm not clear in some place.

**Comment by Shreyj14** [comment]
Hi @GKD890 I tested this PR and I was able to save it for my user profile, but for a different user profile, it did not have save button. It is working as described in the description. Great Work!

**Review by EdwinLauM — COMMENTED** [review]
Hey @GKD890! It works as intended! Good job! Please resolve the branch conflicts and request a review again and I will approve it :) 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/f53e32a5-55f8-4da2-ba70-fa1712f87f4b

**Review by BaileyM96 — DISMISSED** [review]
Hello @GKD890 I went back through and re-tested the Volunteer side like you explained to me in my last comment. The functionality works and I am not able to save changes of other users admin Links. Great work.

## Video

[PR #1035 admin links update.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/f5a777f0-6be1-409f-9ee2-41f52f402dab)

**Comment by mounica-dingari-by** [comment]
Hi @GKD890 , I've tested this PR and everything works great. Good work!!!

Screenshot from 2023-07-27 23-19-31
Screenshot from 2023-07-27 23-19-37
Screenshot from 2023-07-27 23-27-43
Screenshot from 2023-07-27 23-28-21

**Review by shiva2096 — DISMISSED** [review]
Hi @GKD890 

Great work, functionality is working as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/aaeb3589-5b5e-4906-959c-4eac6444425c

**Comment by GKD890** [comment]
> Hi @EdwinLauM , I wonder if you know how to solve the case that all approved code to a file that I didn't made changes has been dismissed. After I resolved the conflicts, it happened. Do I need to wait for others members to review it again?

Thank you

**Comment by n0vay** [comment]
I was able to edit permission for owner account, but when I change permission for a mentor account i am getting this error and the page is going blank after a few seconds.
image

**Comment by GKD890** [comment]
> I was able to edit permission for owner account, but when I change permission for a mentor account i am getting this error and the page is going blank after a few seconds. image

Hi, I believe this is caused by merging the dev branch. If you check the # coding-problem channel in slack, it's caused by a component in dashboard. the component is in `src/components/TeamMemberTasks/TeamMemberTasks.jsx` file. Is it possible you can test users by copy and paste their userProfile's url?

**Review by sxiong5 — APPROVED** [review]
The PR worked as expected! Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/bf0abc9a-a739-4a68-b91e-092b51a46be1

**Review by iTvX — APPROVED** [review]
I use my owner account and give the permission to another account. Then login that account, after I test it, everything looks good. I approve your request.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/0ca3a50a-8434-424e-8832-806e408d7a73

**Review by ThapeloMasasa — APPROVED** [review]
I have tested the PR and it works as intended and the code is well written as well. Here are images for the testing:
Screenshot 2023-08-09 at 1 12 47 PM
Screenshot 2023-08-09 at 1 13 07 PM


Screenshot 2023-08-09 at 1 12 09 PM

**Review by ramyaram2092 — APPROVED** [review]
works as expected based on the privileges given to a user via manage permissions

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/c5f81ac7-780e-4027-8ae4-7e09c3298619

**Comment by Lin1404** [comment]
I have tested the PR and it works as intended. Good Job!

image

User B before add link:
image

User B after add link:
image

**Comment by Jiyuanxia** [comment]
Hi @GKD890 , I have reviewed your pull request and tested it. It works as you intended. Good job!
Screenshot 2023-08-15 153628
Screenshot 2023-08-15 154943

**Review by yunshan111 — DISMISSED** [review]
I tested your PR, it works as intended. LGTM!

**Comment by AnishPandita** [comment]
The PR works well ,LGTM.
Screenshot 2023-08-25 at 4 28 17 PM
Screenshot 2023-08-25 at 4 33 37 PM

**Comment by Shubhu0** [comment]
Reviewed the PR, works as expected.

**Pull request closed without merging**
