### PR TITLE
Shrey add unit test cases for Input

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for Input component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test Input.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-11-06 at 2 53 44 AM

### CODE REVIEW

**Review by wantingxu7 — APPROVED** [review]
Hi @Shreyj14 , I ran the test and got "PASS". Good work!

**Review by navneeeth — APPROVED** [review]
Hello, @Shreyj14! The tests are all passing! Good implementation with the test cases!

unit test cases passing

**Review by luisarevalo21 — APPROVED** [review]
Hello @Shreyj14 ,

I tested your PR and works as intended. Great work! 
Upon running the tests, all tests run correctly. 
Screenshot 2023-11-06 at 5 15 57 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great work! 

Screenshot 2023-11-08 at 1 05 53 AM

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!

Screenshot 2023-11-08 at 4 55 51 PM

**Review by tsunami776 — APPROVED** [review]
Hi @Shreyj14, I ran the unit test and all tests passed. Your unit test is well-commented and comprehensive. Great work!

**Review by Shubhu0 — APPROVED** [review]
Hi @Shreyj14 Reviewed your PR and all tests were passed

image

**Review by Iris-Song — APPROVED** [review]
Hi, I have tested and it looks well. Good job.
Screenshot 2023-11-10 at 22 12 25

**Comment by wanglu1207** [comment]
@Shreyj14 good job! All the test cases passed!
Shrey_UnitTest_Input

**Review by kavya151 — APPROVED** [review]
Hi @Shreyj14 , I have reviewed your PR and all the test cases passed. Good job!!
Screenshot 2023-11-11 at 1 29 35 PM

**Review by pika-chu11 — APPROVED** [review]
Hi @Shreyj14, all tests passed on my end! Great job! 
PR 1497

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
