### PR TITLE
Shereen Unit Test UserProfileAdd

### PR DESCRIPTION
**Pull request by pshereen**
# Description
Unit test for UserProfileAdd component.

## How to test:
1. check into current branch
2. do `npm install` and `npm test UserProfileAdd.test.js` to run this PR locally
3. Verify all the 8 tests are passed. 

## Screenshots or videos of changes:
Screenshot 2024-04-19 170202

### CODE REVIEW

**Review by aaryaneil — DISMISSED** [review]
Tested your PR and all the test cases were passed.
Screenshot 2024-04-19 at 9 49 35 PM

**Review by linkhanthtel — DISMISSED** [review]
All 8 tests passed as expected! Nice work!

**Review by curiousfancier — DISMISSED** [review]
al test cases working well 
image

**Review by AaronPersaud — DISMISSED** [review]
Hi Shereen, I've tested and everything works! Great job.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
