### PR TITLE
Youyou_fix_new_roles_not_show_in_permission_page

### PR DESCRIPTION
**Pull request by jennZhang93**
# Description
Screenshot 2024-06-24 at 11 00 15 PM

## Related PRS (if any):
This frontend pr is not related to any backend pr, please just check in to the development branch.

## Main changes explained:
- Updated `/actions/role.js` to properly make api calls to create new role for function `addNewRole`
- Updated `/components/PermissionsManagement/PermissionsManagement.jsx` to include an async function that calls the `addNewRole`
- Updated `/components/PermissionsManagement/NewRolePopUp.jsx` to properly handle onClick event response and to display the correct toast message. Also added useEffect hook to call `getAllRoles` so that the role list is updated to include the new role.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user or other users that has access to Permissions Management page
5. go to Dashboard→ Other Links→ Permissions Management → click Add New Role
6. Enter a role name. Randomly select a few permissions to add. 
7. Scroll to the bottom and click Create
8. Check for a toast message saying: Role created successfully
9. The User Roles list should now include your newly created role.

## Screenshots or videos of changes:
newPR-ezgif com-video-to-gif-converter (1)

## Note:
N/A

### CODE REVIEW

**Review by DiyaWadhwani — DISMISSED** [review]
Hey Youyou,
Followed your instructions and successfully created a new role while assigning permissions at random. Selecting the role shows me the permissions I had assigned at creation.
I have attached a video recording of the implementation below.
Thank you. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/c035b619-10de-469a-b48a-0e4a55133310

**Review by kdaga81 — DISMISSED** [review]
image
image

The changes as working as expected. Created a new role "Tester" to review the changes.

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and i added new role in my owner account  and gave permission  to the role . permission successfully added to new role. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/78777b49-e0e5-4fb9-b0f4-ba40a8da7530

**Review by Jingyii800 — DISMISSED** [review]
I have tested this PR,  adding a new role in the admin account. After clicking on "create", I can see the popup window showed "successfully" and checked my new role in the role lists.
Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/5251d103-db47-47a1-83ff-f44e9fe539c8

**Review by Logeshwari-Renu — CHANGES_REQUESTED** [review]
I have tested the PR and able to create new Roles. Great Work. However, I was able to add role name "RoleTest" and "RoleTest ". The validation for same role name can be checked with trim() function to avoid duplicates.

**Review by Trip2310 — APPROVED** [review]
Hi Y,
I have tested this PR and followed all instructions, login as admin and -->Permisssion Management--> created a new role as"Newrole Manager" successfully.
http://localhost:3000/permissionsmanagement/newrole-manager
Good work,
PR_2386

**Review by HowieMiao — DISMISSED** [review]
Tested this PR with role name "NewRole" was able to add role specific permissions and upon clicking create role, was shown Role Created successfully prompt and shown NewRole in the permission list, looks good.

image

**Review by KaushikMreddy — DISMISSED** [review]
Hi, 
I've reviewed your changes. I was able to add a role and it showed up in the list.
image

I tried adding another role with the same name and was blocked from doing so as expected. 
image
Good work!

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes works as expected. I was able to create a new role and it was visible in the list after that.
Good Work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/c781c715-3fb2-403f-84ab-1fec407abca9

**Comment by beblicarl** [comment]
Changes work as intended and the code is great

[screencast-localhost_3000-2024.06.28-07_11_48.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/1c0bf3e1-5741-4af6-9618-339e04ecc534)

**Review by beblicarl — DISMISSED** [review]

**Review by nyelmela — CHANGES_REQUESTED** [review]
I encountered an error while trying to create a new role in the Permissions Management section.I followed the exact same steps as listed. Please review the attached video for details: Could you please address this issue?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/31b1ed35-3c03-448b-95ab-3e4a17092e82

**Review by pavanswaroopl — DISMISSED** [review]
Hello,

I have tested and everything works as per the requirement, great work.

Thanks

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/75e7baf3-fecd-434b-9fda-56e7d57c419a

**Review by jinxyou — DISMISSED** [review]
The role creating function works great! I was able to create and add random permission and see my added role.
Screenshot 2024-06-29 200627
Screenshot 2024-06-29 200645
Screenshot 2024-06-29 200818

**Comment by Shadhrush5** [comment]
Hi Jen Zhang, I checked out to the branch mentioned, ran npm install, npm run build and finally when I run start, I see this issue. Not sure why.
Screenshot 2024-07-09 at 9 43 27 AM

**Review by Shadhrush5 — CHANGES_REQUESTED** [review]
Hi, I reviewed PR #2386 with the following steps.
Checked out to the branch "Youyou_fix_new_roles_not_show_in_permission_page"
npm install
npm run start:local
I logged in with an admin account
Other Links -> Permission Management -> Add New Role
Gave a unique name and added a few permissions
When I hit create, I see a toast "Error 403"

Please have a look at the video attached. Do let me know if I'm doing something wrong.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/119898772/9032ee71-9b6b-493e-96e2-f1b00bd5019f

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
Followed the instructions but ran into an error when creating a new role. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/85e14568-81f9-464e-87ec-c2541fb4f0de

**Review by AnujVakil — APPROVED** [review]
I have tested this and PR and functionality is working as expected.

PR #2386_1

PR #2386_2

**Review by Shadhrush5 — APPROVED** [review]
Hi, I reviewed PR #2386 with the following steps.
Checked out to the branch "Youyou_fix_new_roles_not_show_in_permission_page"
npm install
npm run start:local
I logged in with an owner account
Other Links -> Permission Management -> Add New Role
Gave a unique name and added a few permissions
When I hit create, I see a success toast
I can also find the newly created role in the list.

Please have a look at the video attached. Great job. Thank you.


https://github.com/user-attachments/assets/c63fff91-aa5e-4d3e-b6c1-882ad2397a16

**Review by nyelmela — APPROVED** [review]
I have tested this PR and now it works perfectly fine.I have tested this PR by checking into the current branch and running npm install and npm run start:local to run it locally. After clearing site data/cache, I logged in as an admin user or another user with access to the Permissions Management page. I navigated to Dashboard → Other Links → Permissions Management, clicked Add New Role, entered a role name, randomly selected a few permissions to add, and clicked Create at the bottom. A toast message confirmed: "Role created successfully." The User Roles list now includes the newly created role. Everything works perfectly fine.

https://github.com/user-attachments/assets/31903953-ccfc-44d5-bf0b-5473c222dc6a

**Review by Logeshwari-Renu — APPROVED** [review]

**Review by ishan-miglani — APPROVED** [review]
I have reviewed the changes. Once I log in as owner account I am able to create a new role with permissions and get the role created successfully toast. I am able to see the role I created in the roles list. Thanks! 

https://github.com/user-attachments/assets/8966eb2e-6c7b-4cd6-8375-38dacfba9066

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested this PR,. After clicking on "create", I can see the popup window showed "successfully" and checked my new role in the role lists. I have checked on User Roles. 

I have attached the video for reference.

https://github.com/user-attachments/assets/89bc6c60-0ebd-49e8-9f6c-21834b7fdd6f

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by one-community** [comment]
Reverted because it looks like this merged PR created problems with merges: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/actions/runs/10024633067

image

**Pull request merged**
