### PR TITLE
Shrey unit test cases paging.jsx

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for Dropdown component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test Dropdown.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-11-18 at 12 23 14 PM

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-11-18 at 2 04 46 PM

**Review by StrawberryCalpico — APPROVED** [review]
Screen Shot 2023-11-18 at 4 37 58 PM
Tested your PR, great work!

**Review by pika-chu11 — APPROVED** [review]
Hi @Shreyj14 , I have tested your test and it passed on my end! Great job!
PR 1559

**Comment by wanglu1207** [comment]
Hi @Shreyj14 , good job! All the cases passed!
Shrey_unit_test_paging

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-18 at 11 46 36 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed! Great Work!

Week 12 - PR5

**Review by BaileyM96 — APPROVED** [review]
Hello @Shreyj14 I ran your test and have successfully passed all the tests great work!

## Screenshot

Screenshot 2023-11-21 at 4 34 33 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
