### PR TITLE
Shiwani BMLogin Unit Test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/BMDashboard/Login/BMLogin.jsx`

## Main changes explained:
- Added 13 test cases: renders without crashing, check if login elements get displayed when isAuthenticated is true, check if login elements does not get displayed when isAuthenticated is false, check if Enter your current user credentials to access the Building Management Dashboard header displays as expected, check if email label is displaying as expected, check if password label is displaying as expected, check if submit button is disabled when either email or password is not entered, check if validation for invalid email id works as expected, check if validation for password works as expected, check if entering the right email and password logs in as expected, check if statusText in response is not 'OK' and status is 422 and displays validation error, check if statusText in response is not 'OK' and status is not 422 and does not display any validation error, check failed post request does not display any validation error 

## How to test:
1. check into current branch
2. do `npm test src/components/BMDashboard/Login/__tests__/BMLogin.test.js` 
3. check if all the test cases are passing without any warnings or error.

## Screenshots or videos of changes:
Screenshot 2024-05-22 at 2 14 04 PM

### CODE REVIEW

**Review by KyreneAF — APPROVED** [review]
All Tests passed as expected.
first image is with BMLogin as is and second is after the return is commented out and fails as expected. 
Screenshot 2024-05-22 at 3 08 33 PM
Screenshot 2024-05-22 at 3 15 56 PM

**Review by peter6866 — APPROVED** [review]
All test cases passed.
image

**Review by n0vay — APPROVED** [review]
Looks good to me

**Review by beblicarl — APPROVED** [review]

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected! Nice work!

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.
PR 2297

**Review by hbodgal — APPROVED** [review]
image

All tests passed!

**Review by curiousfancier — APPROVED** [review]
All test cases working as expected
image

**Review by MinSun0814 — APPROVED** [review]
image

**Review by aaryaneil — APPROVED** [review]
All the test cases passed, good work.

Screenshot 2024-05-24 at 10 38 54 PM

**Comment by KaushikMreddy** [comment]
Hi, 

All your test cases have passed
image

**Review by scoopstroop92 — APPROVED** [review]
Looks good . Good job on the test cases shiwani !

**Comment by Vijeth-V** [comment]
All the test cases have passed.
Screenshot 2024-05-30 at 10 52 11 PM

**Review by dikshitakejriwal — APPROVED** [review]
All the test cases passed as expected. Couldn't think of any other edge cases. Good Work!
Screenshot 2024-06-01 at 3 14 40 PM

**Review by JatinAgrawal94 — COMMENTED** [review]
All test cases passed as expected.

**Comment by Changhao3220K** [comment]
Hi @Shiwani99 ,
All tests passed as expected, nice work!
testBMLogin

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
