### PR TITLE
Ivy-Update-AI-prompt-UI

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
Screenshot 2024-07-05 at 3 51 16 PM

## Main changes explained:
- Update CurrentPromptModel.jsx …
…

## How to test:
using a owner account, if you copied the AI prompt before, you can edit the prompt, then test it.
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. verify this new feature works:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/d1c11de3-432b-442c-8444-4e6885bce68f

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by IchinnorovTuguldur** [comment]
Hello, I tested the new feature and was able to see new icon on the button but I don't see any edit option once I click on it. Can you confirm if it is there? Attached is the screen shot of what I see
Screenshot 2024-07-05 at 4 15 23 PM

**Review by vijay10pk — CHANGES_REQUESTED** [review]
The requirement is working as expected but I guess the button is not responsive. Can you please check it once? refer the screenshot for issue.
Screenshot 2024-07-05 at 10 13 56 PM

But the functionality is working as expected and I was able to edit the prompt.
Screenshot 2024-07-05 at 10 14 14 PM

**Review by nyelmela — DISMISSED** [review]
I tested PR 2419 the AI feature using an owner account by checking out the current branch, running `npm install`, and starting the app locally. I verified that the new AI feature works perfectly fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/5211e0dc-f746-45f0-ae27-7831e62ef62a

**Review by MinSun0814 — DISMISSED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/dd307a6e-d58a-4d5e-826a-818a7916a431


I have tested the bug fix. Upon using it once, the new icon disappears, which aligns with the task requirements. Nice work.

**Review by KaushikMreddy — DISMISSED** [review]
Hi, 
I've tested your changes, 
Before:
image
After:
image

**Review by jinxyou — DISMISSED** [review]
All functions work as expected. Great work!
Screenshot 2024-07-06 174049
Screenshot 2024-07-06 174055
Screenshot 2024-07-06 174103

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/8796031e-1914-4609-8519-34380ecffdf5

**Comment by 20chen-7** [comment]
> The requirement is working as expected but I guess the button is not responsive. Can you please check it once? refer the screenshot for issue. Screenshot 2024-07-05 at 10 13 56 PM
> 
> But the functionality is working as expected and I was able to edit the prompt. Screenshot 2024-07-05 at 10 14 14 PM

fixed it, plz check it again

**Review by Gauravmg6 — CHANGES_REQUESTED** [review]
I was able to copy the prompt but the edit option was available to me. Probably some authentication issue with mine. 
The button stayed responsive. 

Screenshot 2024-07-22 170354
Screenshot 2024-07-22 170514

**Comment by 20chen-7** [comment]
> I was able to copy the prompt but the edit option was available to me. Probably some authentication issue with mine. The button stayed responsive.
> 
> Screenshot 2024-07-22 170354 Screenshot 2024-07-22 170514

You can check the permission page and update the edit the ai prompt function, then you can edit the button. This is out of the scope of this PR.

**Review by Pranay-ai — COMMENTED** [review]
Hey @20chen-7 
The Functionality of New is Working Fine

image
But "i" icon is not on the same line as shown in the image above

**Comment by Gmon-k** [comment]
I have tested the PR and it works succesfully
1) I am able to access the AI prompt
2)I am able to edit it too
3)I can copy the prompt too
Below is the screenshot for it

**Review by SatyashanthiT — APPROVED** [review]
I have tested this PR by checking out the current branch, installing dependencies, and running the application locally. I verified that the updated AI prompt UI functions correctly, allowing users to edit prompts as intended. The new feature works smoothly, and the UI updates enhance usability. Everything works fine, and I recommend approving this PR.

https://github.com/user-attachments/assets/0daf5ef8-d798-424b-b983-02df59002cac

**Pull request closed without merging**
