### PR TITLE
ruike_add_active_indicator

### PR DESCRIPTION
**Pull request by StrawberryCalpico**
# Description
Screen Shot 2023-11-18 at 11 32 21 AM

## Related PRS (if any):
N/A

## Main changes explained:
In the Teams->Members
Add green/grey dot to indicate if user is active or not

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner
4. go to Other Links -> Teams -> Members
5. check all users have a corresponding dot to indicate if they are active or not
6. go to Other Links -> User Management
7. click one user's green dot to switch it to inactive
8. go to Other Links -> Teams -> Members
9. check that user's dot became grey

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/8bedbbe5-d9bb-4210-8441-e2388f18aca5

### CODE REVIEW

**Review by ptrpengdev — APPROVED** [review]
Hi @StrawberryCalpico, I have tested your code and all functionalities work as expected with the Admin role. Great work!

**Team Status:**

Active indicatior
activeStatus

Inactive indicatior
inactiveStatus

User status: 

User Management <hr/>
acitveUser

inactiveUserUserMgmt

User Profile<hr/>

activeUserMgmt

inactiveUser

**Comment by palakgosalia** [comment]
Hey, I tested and reviewed your PR. I was able to make the user inactive and see the changes in the teams and members tab. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/09e66dc1-a15c-4772-84bf-a183ae8029c1

**Review by Hemsharavanan — APPROVED** [review]
- Reviewed the active/inactive indicators for team members in the team section's members modal table. 
- Successfully toggled a user's status from active to inactive in User Management, reflecting the change in their profile. 
- Reversed the status back to active, confirming the reactivation. The functionality appears to be working as intended. 

Please refer to the attached video for further details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/28252459/18449316-887b-461e-9a6a-15ab671eed1b

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/28252459/8b521d65-4598-4e8e-b379-4162e7da3100

**Review by KavyaAlla — APPROVED** [review]
Hi @StrawberryCalpico , I have tested this PR locally. I was successfully able to set players inactive at User management and it is getting reflected in the teams properly. Everything is working as expected. Good job!!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/d210ad4f-52ad-47cd-9fd0-523759cc4b40

**Review by Shuhua-L — COMMENTED** [review]
Hi @StrawberryCalpico, Great job! 

When I toggle the status of a Volunteer and Mentor, the indicators within the Teams -> Members tab update correctly upon reopening the tab. 

I also noticed that when a member is added to a team, the default dot appears grey initially, even though the user is active. It takes another reopening of the tab to display the accurate color. Not sure if this is something that needs attention though.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/619006cd-02b9-4ddf-b607-5d6b136cd265


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/ac236564-87d6-4235-a14d-e838a971449a

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
