### PR TITLE
Alex - Create a Pull Request Template

### PR DESCRIPTION
**Pull request by alexander-huerta**
Following the GitHub Docs, I am creating a pull request template in order to save time and create consistency in the teams PR formatting. 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

### CODE REVIEW

**Comment by one-community** [comment]
Please add a screenshot of the template people will see when they go to publish, so everyone can easily look at it and give feedback/suggestions via comments here.

**Comment by one-community** [comment]
I'm going to move this directly to feedback from the complete PR Leadership Team too.

**Comment by Aishwaryak01** [comment]
@alexander-huerta : Can we also maintain the semantic versioning of files while we create a PR? I think this could help a lot in maintaining files specifically when more than one person is working on a file simultaneously.
It would be great if we add it to the PR template itself.

**Comment by one-community** [comment]
Here's the source image for this template, from the linked Google Doc: 
image

**Comment by one-community** [comment]
Yes, that sounds like it would be very helpful. How do we do that Aishwarya? Does anyone disagree?

**Comment by alexander-huerta** [comment]
Hi @Aishwaryak01 I am not sure what you mean by semantic version. Can you provide me an example please? 



[This tutorial](https://www.youtube.com/watch?v=MjsS4ujX3nU) provides a great overview of how templates work and the goal of this PR. You can start the video at 3:42 to see it in action.


### This is a preview of the proposed  template
pr_template_preview

### And this is the markdown code 
pr_template_md_code

**Comment by Cirakuze** [comment]
@alexander-huerta You can add the instructions and suggestions in this template as comments that will not show up when the PR is opened.

| Write | Preview |
| -- | -- |
| Screenshot 2023-05-19 at 20 48 38 | Screenshot 2023-05-19 at 20 48 47 |

**Comment by alexander-huerta** [comment]
Great suggestion @Cirakuze. I will look into this now! Does anyone else have a preference? 

I just want to confirm that this is just a style preference. Whether it comes commented out or not, the template is still completely editable until the request is published, is that correct?

**Comment by rauleffting** [comment]
> Hi @Aishwaryak01 I am not sure what you mean by semantic version. Can you provide me an example please?
> 
> [This tutorial](https://www.youtube.com/watch?v=MjsS4ujX3nU) provides a great overview of how templates work and the goal of this PR. You can start the video at 3:42 to see it in action.
> 
> ### This is a preview of the proposed template
> pr_template_preview
> 
> ### And this is the markdown code
> pr_template_md_code

I think this is ok! Very similar to the version I'm using.

**Comment by Cirakuze** [comment]
> Great suggestion @Cirakuze. I will look into this now! Does anyone else have a preference?
> 
> I just want to confirm that this is just a style preference. Whether it comes commented out or not, the template is still completely editable until the request is published, is that correct?

Yes, that's correct. But you can still add/edit/remove comments in the PR description even after they're opened.

**Comment by suigunfjc** [comment]
Hi @alexander-huerta , your code in the template file looks good to me. Could you tell me how to test this change? I suppose we can make a pull request on your `alex_create_pr_template_fe` branch?

**Comment by alexander-huerta** [comment]
I don't know of a way of testing this without going live on development and submitting another pull request to use the template.

**Review by Cirakuze — APPROVED** [review]
This is a no-risk PR.

**Pull request merged**
