### PR TITLE
Yubo-Warning of Editing Media Folder link & Autosave

### PR DESCRIPTION
**Pull request by GKD890**
# Description
This a feature that may not in the bug list.

## Main changes explained:
- Add a warning will show up if the input in `Media Folder` link is different from `mediaUrl` that is related to your weekly summary.
- Remove additional save that's mentioned in #1001 , now only click `update`, the links will be saved automatically.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user -> go to other user's profile page -> click link **Edit** under picture.
4. Try to change the `Media Folder` link and see if the warning shows up.
5. Click `update` to save the changed `Media Folder` link to the profile and refresh to check if autosave works properly.

## Screenshots or videos of changes:
Screenshot 2023-08-26 at 4 27 32 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/cb3f08ce-2d52-47ae-b445-feb4b0e7beb1

### CODE REVIEW

**Review by ramyaram2092 — CHANGES_REQUESTED** [review]
Hello @GKD890  firstly good job on the changes. Works as expected. However if there media URl is blank and have to be updated the first time. It still shows the error message . I think it shouldnt 

**Testing video :** 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/0d3dc983-2a33-4e65-9639-d6a83c8df119

**The Bug I am referring to :** 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/86985cd5-a05b-4c42-a80e-a0db0d07478b

**Review by Haoj1 — APPROVED** [review]
@GKD890 Admin upated correctly and displayed warning when changed. Nice work 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/d6c7ca8d-d231-4abb-ae3b-51ad9454e23e

**Review by yaow62023 — CHANGES_REQUESTED** [review]
I've tested your pull request, and the warning message is indeed displaying. However, ramyaram2092 and I have both encountered the same issue. In my second video, I refreshed the page and cleared the cache, but the warning message continues to appear for empty media links. This issue needs to be addressed. Apart from this, everything else looks great. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/58fb6e81-4d4f-4aac-a0bb-c7a0e52edca6


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/435510b9-95fc-49e8-a23d-db6aae357603

**Review by winghojackyli — DISMISSED** [review]
Hi @GKD890 , the PR works as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/13b0a8c2-0ba0-4dff-92ac-4be00c7914fc

**Comment by GKD890** [comment]
Need to look into the issues mentioned by other reviewers, will re-open and @ them when it's done.

**Comment by GKD890** [comment]
Hi @ramyaram2092 and @yaow62023 . Thank you for providing the video for the issue, and I've reviewed them. I believe that was I tended to do so as I don't want such thing happened: making `Media Folder` link empty also leaves an empty `mediaUrl` . That's also true for a broken link. 
As the difference between two links triggers the warning, such warning's exisitance keeps reminding the **admin** that the `Media Folder` link is empty. 

If that makes sense, please re-review this when you are available or let me know your concerns. Thank you all.

**Review by tsunami776 — COMMENTED** [review]
I tested with an admin account, and the PR works as stated. A warning appears when the input URL doesn't match the saved one. If the URL is different, clicking 'Update' will directly save the Media Folder link.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/b5809a1c-750d-42b2-9a50-91c259756fbc

**Pull request merged**
