### PR TITLE
XiaoW_Time entry on tasks tab refactor and restructure redux store

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
The main changes of this PR is the restructure of redux store (reducers). Currently, reducers are all saved in localStorage via redux-persist and part of the reducers, such as userProfile, userTask, userProjects ..., are for storing data that is for displaying dashboard or timelog pages, and when a logged in user checks on another user's page (Dashboard, Timelog, Userprofile, etc), those state are of the displaying user. But if the logged in user keeps his own page open, and open the same page of another user on a new tab, those states will be refreshed, and the page for logged in user would not behave normally. This is also part of the reason why new bugs constantly show up after fixing old bugs when it comes to non logged in user's pages.

The fix for this is to use SessionStorage for part of the reducers, and because SessionStorage is only created when open new tab and clear itself upon close, it is perfect for storing data that is solely for current page/displaying user. 

This PR also refactors the TeamMemberTasks tab, the time entry inside, and simply part of the logic within some other components.

## Related PRS (if any):
This frontend PR is related to the [#699](https://github.com/OneCommunityGlobal/HGNRest/pull/699/#issue-2078135101) backend PR.
…

## Main changes explained:
- Restructure redux store
- Replace FilterTimeEntry with TimeEntry component in TeamMemberTasks
- add essential action creator and reducer case handlers for states for TeamMemberTasks
- Modify TimeEntry to make it work on both weekly time entry tab and TeamMemberTasks tab
…

## How to test:
1. check into current branch and  [#699](https://github.com/OneCommunityGlobal/HGNRest/pull/699/#issue-2078135101) on the backend
1. do `npm install` and `npm run start:local` to run this PR locally
1. Clear site data/cache (go to devtool -> Application tab -> Open Local Storage (on left panel) -> right click url -> click clear (see pic below)
1. log as admin user
1. go to dashboard → Tasks tab
1. verify users and tasks are displayed normally
2. click 24h/48h/72h, verify time entry are displayed normally
3. open another user's dashboard/Timelog page on a new tab, and refresh the old tab see if there are any issues
4. If you are comfortable checking with the LocalStorage and SessionStorage, right click on the field you want to check and select "store string as global variable", it will save it to a variable (temp1, temp2, ....). Then in console tab, use `JSON.parse(temp1)` to get the JS object. (see pic below)

## Screenshots or videos of changes:
How to clear cache:
image

How to check redux-persist state:
image
image

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great job! It worked as expected when I checked tasks tab, timelog page. Redux state also persisted after clearing the cache. There are no errors in backend as well.

Screenshot 2024-01-12 at 8 20 33 PM

Screenshot 2024-01-12 at 8 20 44 PM

Screenshot 2024-01-12 at 8 28 00 PM

**Review by robertoooc — APPROVED** [review]
Hey @wang9hu, I took a thorough look at your pr. Nice job with the team member task file refactor, it's so much easier to look through it now since it's much smaller. 

I think utilizing the session and local storage the way you did was quite clever. I realized that some of those variables you placed in the session storage are some that are less frequently used, which is awesome because in instances where we need to work on different tabs. It clears them and it helps with state management and not exceeding the Mb limit.

I'm very impressed, and the full functionality seems to operate just well. Even when viewing other user's dashboards there are no conflicts in state management.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/7c8378de-767b-4501-a166-6b7d01940699

**Review by sucheta90 — APPROVED** [review]
Hello @wang9hu, I have been able to test this PR as an Administrator. I followed the steps in the PR and it works as intended. Well done. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/4b224dfb-ccd4-4e6d-8811-2d41e7122f40

**Comment by mianmiantea2019** [comment]
Hi @wang9hu, I tested this PR as an Administrator. Tasks tab, Redux state works as intended and no errors in backend. Well done.

image

image

image

**Review by bienzguoa — APPROVED** [review]
Everything works as described and no issues. Good job!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/873c97eb-939f-4026-b703-11e600771a58

**Pull request merged**
