### PR TITLE
Nahiyan dark mode for weekly summaries reports page

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
THIS IS A FOLLOW UP PR TO [2105](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2105)
This PR makes dark mode available for the following pages:
- Weekly Summaries Report page
- Team locations page

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Implemented dark mode for the Weekly Summaries Report page
- Implemented dark mode for the Team Locations page

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Reports → Weekly Summaries Report page and Team Locations page
6. verify that dark mode is working properly on both these pages.

## Screenshots or videos of changes:
Screenshot 2024-04-07 175105
Screenshot 2024-04-07 175129

### CODE REVIEW

**Review by hbodgal — DISMISSED** [review]
Dark mode works well for both the pages.

image


image

**Review by linkhanthtel — DISMISSED** [review]
Nice work! Dark mode looks good on both pages. 

#2127 (Weekly Summary Reports)


#2127 (Team Locations)

**Review by SushmithaPrathap — DISMISSED** [review]
Hey, Tried and tested this PR. Works as described, Good work!
Dark mode works as expected on both the screens.

Here are the screenshots:
Screenshot 2024-04-10 at 11 02 44 PM
Screenshot 2024-04-10 at 11 00 34 PM

**Review by SRamen1999 — DISMISSED** [review]
Dark mode works as expected for team locations and weekly summary reports.
Screen Shot 2024-04-11 at 4 26 14 PM

Screen Shot 2024-04-11 at 4 22 42 PM

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi, I just checked your PR and is working fine as expected.

Screenshot 2024-04-11 at 7 37 23 PM
Screenshot 2024-04-11 at 7 27 35 PM

**Review by jennZhang93 — DISMISSED** [review]
I've tested with an owner account. The dark mode feature work as expected. Good job!

**Note**: Not sure if it's my laptop problem, just wanted to note that switching between modes take about 2 seconds for me.

Screenshot 2024-04-11 at 7 08 13 PM

Screenshot 2024-04-11 at 7 08 43 PM

**Review by anandsesha — DISMISSED** [review]
Hi, I tested the dark mode in the Team Locations page and the Weekly Summary Reports page and the feature works as expected. Looks great!

Note:
This is perhaps an unrelated issue, but when I click on Reports - Team Locations - search box and type something, the page goes blank and  error seen in console. Not sure if that issue is reported already. Screenshot attached in the end. 

Screenshot (787)

Screenshot (789)
(https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78548214/dd9539ad-dc82-4009-9b1e-1a73490fbcc2)

Team locations search box error on typing any text:
Screenshot (788)

**Review by aaryaneil — DISMISSED** [review]
Tested the PR the changes look good for the mentioned pages.
Screenshot 2024-04-12 at 12 59 09 AM
Screenshot 2024-04-12 at 12 59 34 AM

**Comment by MQChen211** [comment]
Hi, I tested your PR, the dark mode in the Weekly Summaries Report page and Team Locations page work as expected.

截屏2024-04-12 14 27 49

截屏2024-04-12 14 28 29

**Review by MQChen211 — DISMISSED** [review]

**Comment by hiralsonip** [comment]
Hi...I checked this PR and everything is working as expected. 

**Team Location Page**
PR2127_team_location

**Weekly Summary Page**
PR2127_weekly_summary

**Review by hiralsonip — DISMISSED** [review]

**Review by lacnoskillz — DISMISSED** [review]
Hello again @Nahiyan-16 
I successfully pulled your changes and the dark mode feature works on these pages as well. 
Nice work.
However, like I noted in your other PR the mobile view icon is a little off but that's just me being nitpicky.
Great job all around and look forward to seeing dark mode come to all the other pages
below are images with your changes


Summaries report page
summaries reports page dark mode

Team locations
team locations dark mode

Mobile view Drop down
Here is where the light/dark mode icon looks a little off center compared to the other items
dark mode mobile 2127

Happy coding!

**Pull request merged**
