### PR TITLE
Vijay Anand - Added search by name functionality feature to Leaderboard Component

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description
Screenshot 2024-08-14 at 10 14 45 PM

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch in backend.
…

## Main changes explained:
- Added debounced search functionality to search users by name in the leaderboard component table for better user experience.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to the dashboard
6. verify whether you could search user from the leaderboard component table by name.
7. verify this new feature works in [dark mode].
8. verify the responsiveness of this new feature.
9. verify other functionalities of the leaderboard components are unaffected by the new change - like viewing the user dashboard by clicking on the status and viewing the user profile by clicking the user name.

## Screenshots or videos of changes:
**Testing the new feature**
https://www.loom.com/share/2264d26b08994dfd9e0b8ef5f2414c15?sid=b416506a-873e-49d4-bfba-e49bb6217c80

## Note:
- Start testing the functionality only after the entire dashboard is loaded.
- Search input will be cleared every time the admin/owner user performs view user dashboard or view user profile because the component gets unmounted.
- Any other existing dashboard UI issues are not related to the leaderboard component.

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
I have gone through steps mentioned and everything is working as mentioned.


https://github.com/user-attachments/assets/254b9419-5188-4034-919a-d6e70ec148d9


Thank you.

**Review by manikittu810 — APPROVED** [review]
I have gone through steps mentioned and everything is working as mentioned.


https://github.com/user-attachments/assets/254b9419-5188-4034-919a-d6e70ec148d9


Thank you.

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.


https://github.com/user-attachments/assets/6168ba90-0479-4d68-8f4c-b8f518a9c77f


Thank You

**Review by kdaga81 — APPROVED** [review]
image

I verified the changes in dark/light mode and all the scenarios mentioned. Everything working as expected

**Review by Gauravmg6 — APPROVED** [review]
Everything works well.
Screenshot 2024-08-25 021437

**Review by RishithaMamidala — APPROVED** [review]
@vijay10pk 
The code works as described.
PR 2597

**Review by preethamdnr — APPROVED** [review]
Hello Vijay,
I have reviewed this PR and it is working as expected.

https://github.com/user-attachments/assets/b743c43c-45a8-4b5a-883a-20ec876fde27

**Review by gowthamdongari — APPROVED** [review]
Hello Vijay,
I have reviewed this PR and working as expected.

https://github.com/user-attachments/assets/64f08853-a6ff-4a7c-8345-fc259797b6ad

**Review by Pranay-ai — APPROVED** [review]
Hey @vijay10pk 
The PR is working as expected please find the reference for the screenshot
image

**Review by sri0606 — APPROVED** [review]
Hey @vijay10pk , I have tested your PR and everything works as expected. The performance is decent too and worked fine in dark mode.

Please refer to the video below:

https://github.com/user-attachments/assets/22b38d22-915d-4b83-856a-308804191a7c

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
