### PR TITLE
Shantanu - Unit test case for Image common component

### PR DESCRIPTION
**Pull request by n0vay**
# Description
Unit test for coomon Image.jsx component

## How to test:
1. check into current branch
2. do npm install
3 run on terminal: "npm test Image.test.jsx"
4. verify that all tests pass

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-11-04 at 10 47 09 PM

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR. Everything works as expected. Good job!
Screenshot 2023-11-04 at 11 04 06 PM

**Review by pika-chu11 — APPROVED** [review]
Hi! I've tested with all testes passed. Great work!
Screenshot 2023-11-04-HGNapp-#1490

**Review by kavya151 — APPROVED** [review]
Hi @n0vay , I have reviewed the PR and all the tests passed. Good Job!
Screenshot 2023-11-04 at 8 53 43 PM

**Review by yangfan2001 — APPROVED** [review]
Hi, I have tested you PR and all tests were passed. Great Job!
image

**Review by savio-henrique — APPROVED** [review]
Hi @n0vay , I've tested as you requested, all tests passed as expected!

Great work! :+1: 

# Screenshot

terminal

**Comment by palakgosalia** [comment]
Hey, All the test cases passed successfully. Good work

image

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
