### PR TITLE
Cheng-Yun Project/Overview.jsx unit test 

### PR DESCRIPTION
**Pull request by DavidC0126**
# Description
Create a unit test for the project Overview component.

## Related PRS (if any):
No
…

## Main changes explained:
- Create file Overview.test.jsx for unit test Overview components.

## How to test:
1.check into the current branch
2.do npm install and run this PR locally
3.open file src → components → Projects → Overview
4.run `npm run test Overview.test.jsx`

## Screenshots or videos of changes:

Screenshot 2023-11-19 at 3 55 19 PM

## Note:
If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by Changhao3220K — DISMISSED** [review]
Hi @DavidC0126 
All the test passed, nice work!
Screenshot 2023-11-22 at 8 36 51 PM

**Comment by beblicarl** [comment]
All tests paased. Great

image

**Review by beblicarl — APPROVED** [review]

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-11-23 at 12 38 23 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, Great Job! I tested this PR and all test cases passed!

Week 13 - PR3

**Review by ramyaram2092 — CHANGES_REQUESTED** [review]
Hello @DavidC0126  good job on the Unit test.
1. I see you have the test  file in projects/components/ whereas other  unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?
2.  You could  remove unused imports

**Review by Hemsharavanan — APPROVED** [review]
- Your tests are clear, focusing on verifying the presence and correctness of rendered numerical values.
- Overall the tests effectively confirm the component's rendering with props and the accurate display of the number of projects and active projects. 
PR #1574 Cheng-Yun Project Overview jsx unit test

**Comment by DavidC0126** [comment]
> Hello @DavidC0126 good job on the Unit test.
> 
> 1. I see you have the test  file in projects/components/ whereas other  unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?
> 2. You could  remove unused imports
>    

Hi @ramyaram2092,

After asking Olga, I think our consensus is to put the test just under the component folder. Thank you for asking.

**Comment by DavidC0126** [comment]
> Hello @DavidC0126 good job on the Unit test.
> 
> 1. I see you have the test  file in projects/components/ whereas other  unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?
> 2. You could  remove unused imports
>    

Hi I removed the unnecessary imports. Thanks.

**Review by ramyaram2092 — APPROVED** [review]

**Comment by ramyaram2092** [comment]
> > Hello @DavidC0126 good job on the Unit test.
> > 
> > 1. I see you have the test  file in projects/components/ whereas other  unit test PR's I have reviewed so far , the test files were under src / test folder. Could you check with other and confirm this ?
> > 2. You could  remove unused imports
> >    
> 
> Hi I removed the unnecessary imports. Thanks.

Approving the PR on the same note. Good job

**Review by Alforoan — APPROVED** [review]
They both passed. Nice!

image

**Review by ChengyanOo — APPROVED** [review]
@DavidC0126,

I have reviewed and run your tests, and I'm pleased to inform you that they have all passed successfully. For your records and further reference, I've attached a screenshot of the test results. Great job on the testing!
Screenshot 2024-01-09 at 15 19 54

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
