### PR TITLE
Mohan - Made Changes For add or delete teams without saving

### PR DESCRIPTION
**Pull request by mohangadde1**
# Description
image

## Related PRS (if any):
This frontend PR is related to the previous PR https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2607

## How to test:
1. check into current branch
2. do npm install and npm run start:local to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Open a User Profile-> Teams->Assign Teams
6. Now Perform Delete Teams The Functionality Should Work without saving the changes.
7. Verify If the Changes are working for both the Desktop and Mobile Version

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/3baca2c7-e810-4350-b7d0-dc08c3f6eea6

### CODE REVIEW

**Review by vijay10pk — APPROVED** [review]
The changes are working as expected in both desktop and mobile screens.
Screenshot 2024-10-19 at 8 12 10 PM
Screenshot 2024-10-19 at 8 13 08 PM

**Comment by navya9989** [comment]
HI @mohangadde1, I have tested this PR locally and the teams are added and deleted without saving which is working as expected. Here are the Screenshots for Reference. Great Work!
PR 2806
PR# 2806

**Review by navya9989 — DISMISSED** [review]
Works Good

**Comment by RashmiKY98** [comment]
Followed the below tests to test the PR:

- Added the user to two teams and then pressed on delete. 

- Refreshed the button without hitting Save Changes.

- The User was added to the team/ deleted from the team automatically.

- Tested on Microsoft Edge and Firefox browsers.
Screenshot 2024-10-20 011158

**Review by CodewithKoushica — CHANGES_REQUESTED** [review]
I reviewed the Code and tested it in local setup.
- Verified that teams can be deleted and assigned without needing to save manually. The auto-save feature is working as expected, streamlining the user experience.
- Tested the feature on both desktop and mobile. The UI is responsive and functions properly on different screen sizes. Conducted tests on multiple browsers (chrome, Firefox, Safari), and the feature works consistently without any issues.
- No issues encountered in either light mode. 
- **A slight UI/UX issue in dark mode. The team name is not visible while hovering. Please fix that.**

Overall, the code looks neat, the functionality works well, and the feature enhances the overall workflow for managing teams efficiently. No major issues found.

Good work!

https://github.com/user-attachments/assets/da401069-9dbb-4fde-84e7-75bab1c45283

**Review by samarth9201 — APPROVED** [review]
Code looks good and can validate that it works as expected.

Screenshot (93)
Screenshot (94)
Screenshot (95)

**Review by NK3101 — DISMISSED** [review]
Tested the PR, addition and deletion of teams without saving are working as expected.
Screenshot 2024-10-21 at 11 05 05 PM
Screenshot 2024-10-21 at 11 05 16 PM
Screenshot 2024-10-21 at 11 07 10 PM

**Review by slidracoon72 — DISMISSED** [review]
#2806 
@mohangadde1 
I have reviewed this PR and confirmed that the add and delete functionality works as expected when assigning teams. The changes are effective without needing to save, and I verified that everything works smoothly on both desktop and mobile versions.
Screenshot 2024-10-23 at 12 18 15 PM
Screenshot 2024-10-23 at 12 18 22 PM
Screenshot 2024-10-23 at 12 17 56 PM
Screenshot 2024-10-23 at 12 19 56 PM

**Review by nikhilgiri0226 — APPROVED** [review]
I reviewed the PR and tested locally.

The auto save feature works fine and we can add/delete teams without manually have to save them. Tested the feature in dark/light mode and both mobile and desktop version. 

There was one slight UI issue I faced. In dark mode, when we hover over the row in the table, the whole row turns white, making it hard to differentiate anything in that row. I have attached the screenshot below.

image
image
image
Highlighted row in table in dark mode below
Screenshot (40)

**Review by Anoushka21 — DISMISSED** [review]
The assign and delete team doesn't need save changes and its auto saved. Works in both light and dark mode.!

https://github.com/user-attachments/assets/dd486f39-fcbf-4487-b4f6-12bca4e34905

**Comment by ShreyaLaheri** [comment]
I couldn't see the assign team button
image

**Review by anji-annavarapu — APPROVED** [review]

**Review by anji-annavarapu — APPROVED** [review]

**Review by CodewithKoushica — DISMISSED** [review]
Thank you for the UI fix. Works great now.
Approving the changes.
Screenshot 2024-10-28 at 10 58 33 AM

**Review by hqzhu0913 — DISMISSED** [review]
The assign and delete functions work for both desktop and mobile. In the desktop mode these operations can be auto saved and results are shown immediately. But in the mobile mode, it needs press refresh to see the results.
Screenshot 2024-10-28 at 11 13 04 PM
Screenshot 2024-10-28 at 11 13 09 PM
Screenshot 2024-10-28 at 11 29 08 PM
Screenshot 2024-10-28 at 11 29 37 PM

**Review by anirudhsk2107 — APPROVED** [review]
the changes are working 
Screen Shot 2024-10-30 at 2 24 28 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Review by NazaninHashemian — COMMENTED** [review]
Everything works great! I tested the functionality in both dark and light modes, and it looks fantastic on both desktop and mobile sizes. The design and layout are responsive, and everything seems to be functioning as expected. However, there is one minor issue: the buttons on smaller mobile phones are a bit too large, which affects the overall user experience. The sizing of these buttons could be adjusted for a more streamlined look and feel on smaller screens. Other than that, everything is perfect!

**Review by SammanBaidya — COMMENTED** [review]
Tested and reviewed the changes which works as intended. Tested by adding and deleting the team and it works as the author showed in their video. Please check my video below for test reference. Well implemented. 

[Review5 #2806.webm](https://github.com/user-attachments/assets/65145f70-8490-4727-850c-3f8c5cb28741)

**Pull request merged**
