### PR TITLE
huijie role distribution pie chart for TotalOrgSummary

### PR DESCRIPTION
**Pull request by metaphor987**
# Description
Implements the role distribution pie chart in the totalOrgSummary as in the design document: 
Screenshot 2024-08-17 at 9 28 22 AM
https://www.figma.com/design/qkRC9ivsIE2uG2M7WOPTg0/Weekly-Volunteer-Summary-Mockup-%26-social-architecture-tracking-and-management-system
The pie chart only display the label text when a role exceeds the percentage of 1%

## Related PRS (if any):
This frontend PR is related to the ##1062 backend PR(https://github.com/OneCommunityGlobal/HGNRest/pull/1062)

## Main changes explained:
- Create the pie chart for role distribution of users

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Total Org Summary → open the "Volunteer Roles and Team Dynamics" tab, and the pie chart is on the right
7. verify that the pie chart is displaying the role distribution as expected. 
Notes: currently there are several roles with very small angles, this is due to test roles in Dev environment. There will not be so many roles in Production environment.

## Screenshots or videos of changes:
Screenshot 2024-08-17 at 9 36 48 AM

## Update 11/29:
This branch now includes both the role distribution pie chart and the work distribution bar chart.

### CODE REVIEW

**Review by manikittu810 — DISMISSED** [review]
Hello @metaphor987 
Displaying role distribution pie chart as expected.
Screenshot 2024-08-17 at 7 10 52 AM

Thank you.

**Review by kdaga81 — CHANGES_REQUESTED** [review]
image

Pie chart is not visible in my instance. Also, I can see multiple tabs of "Volunteer Roles and Team Dynamics"

**Review by Pranay-ai — APPROVED** [review]
Hey @metaphor987 
I have reviewed the PR, its working as expected.
image

Thank you

**Review by AnkitLall — APPROVED** [review]
I have tested the feature, following the instructions in the PR, and it works as expected. Please refer the screenshots attached below.

huijie role distribution pie chart for TotalOrgSummary #2584

**Review by Gauravmg6 — APPROVED** [review]
Working as expected.
Screenshot 2024-08-18 014659

**Review by beblicarl — CHANGES_REQUESTED** [review]
though the pie chart appears as intended, we have the Volunteer Roles and Team Dynamics tab appearing twice on the screen like we do in the image below

image

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.



Thank You

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
The Pie chart is not visible.
Screenshot 2024-08-23 at 11 21 08 AM (2)

**Review by Saniya98 — APPROVED** [review]
All working fine

**Review by sri0606 — APPROVED** [review]
Hey @metaphor987 , I have reviewed the PR and I can indeed see a pie chart in "Volunteer Roles and Team Dynamics" section.

image

**Review by sam19981 — CHANGES_REQUESTED** [review]
The pie chart is visible, but there are two entries for "Volunteer Roles" and "Team Dynamics." Please check the screenshot below.
Screenshot 2024-09-14 at 11 16 02 PM

**Review by Watchdog00 — COMMENTED** [review]
I tested this feature, and the pie chart is displaying correctly.

**Review by ziyanw52 — DISMISSED** [review]
I have tested this feature and the pie is shown after click the Volunteer Roles and Teams Dynamics tab. Also, the role distribution is displaying as expected.
1071728192856_ pic_hd

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
