### PR TITLE
Fix Badges Select Featured and Edit Personal Max Functions

### PR DESCRIPTION
**Pull request by angelalalacheng**
# Description
https://www.loom.com/share/737001d350ca4b79ab9950a158df7b3d?sid=177c042d-ba44-4cf1-8daa-a9b712537181
1. In "Select Featured", select the featured badges (at most five) and save changes.The web will crash.
2. In "Assign Badges", the checkbox does not check the badges which user already have.
3. For "New Max - Personal Record Award" badge, it cannot be modified in "Select Featured".

## Related PRS (if any):
This frontend PR is related to backend development branch.
…

## Main changes explained:
- Update returnUpdatedBadgesCollection function in `badgeManagement.js` and `AssignBadgePopup.jsx` to make sure the functionality of checkbox can add / reassign the badges in selectedBadges.
- Update useEffect in `BadgeReport.jsx` to avoid memory leak after Save Changes in Select Featured.
- Update ` BadgeImage.jsx` to adjust the value for "New Max - Personal Record Award" badge.
- Update ` AssignBadgePopup.jsx` to rename selectedBadges to existBadges to avoid use same as Redux one and simulate the hook again and again
- Update related test cases to adopt to new logic

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
5. Log as owner / admin user
6. Go to Profile Page>Select Featured / Assign Badges
7. Verify
        (a.) When open the "Assign Badges" popup, see the checkbox check the existing badges.
        (b.) Test the functionality: Select the existing badge then its amount will +1. Select the new badge will show 1 except the "New Max - Personal Record Award" badge.
        (c.) When select "New Max - Personal Record Award" badge, it will first show the "personalBestMaxHrs" in userProfile from backend(you can check that in MongoDB). And, if you adjust the Count value in "Select Featured" and larger than "personalBestMaxHrs", it will show the Count value.
        (d.) Select the featured badges (at most five) and save changes and see whether the web will crash or not.

## Screenshots or videos of changes:
https://www.loom.com/share/e7ab95c9c2e44191847f441cd3c5622e?sid=546d9147-e6b7-4fef-a7f5-f694da367ddc

### CODE REVIEW

**Comment by strallia** [comment]
### These Features Are Working As Expected
a) Existing badges are prechecked.
Screenshot 2024-09-02 at 8 17 10 PM

b) Adding more of the same badge increments its total except for the "New Max - Personal Record Award" badge.
image

c) Changing the Count value in "Select Featured" for the "New Max - Personal Record Award" badge does the selected number in the profile.
image

**Review by strallia — APPROVED** [review]

**Review by sri0606 — APPROVED** [review]
Hey @angelalalacheng , I reviewed and tested the changes you made, everything works as expected. 
* On selecting the same, the badges count are being updated (+1) and the count is visible.
* Updating the count on "Personal badge" to a greater number works correctly.
* Featuring 5 badges or less does not break the app.


https://github.com/user-attachments/assets/36e00823-7cb4-49b3-9919-4a51e882ca96

**Review by vedantg24 — DISMISSED** [review]
Tested the PR and it’s working as expected. In "Assign Badges", existing badges are already checked. Adding more badges of same type, increments the number by 1 except the "New Max - Personal Record Award”. Also, changing the count value in "Select Featured" for the "New Max - Personal Record Award" badge increments the selected number.

https://github.com/user-attachments/assets/3d389cf7-97e7-4b73-9d61-3fcf51da5187

**Comment by FayeLV** [comment]
Hi,
Great job! Below are the test results:
a) Selecting up to five featured badges in "Select Featured" and saving changes no longer causes the web to crash.

b) In "Assign Badges", the checkboxes now correctly reflect the badges the user already owns.

c) The "New Max - Personal Record Award" badge can now be successfully modified in "Select Featured".
https://www.loom.com/share/518e3236040b48ef8c0d090ff4a8012f?sid=50404ff0-b9c6-4034-99f3-fd3224ed9d93

**Review by FayeLV — APPROVED** [review]

**Review by sam19981 — CHANGES_REQUESTED** [review]
Hi @angelalalacheng,

I have a quick question about updating the New Max - Personal Record Award. Does this represent the maximum number of hours and not the badge count? Also, should the admin be able to update it, like with the rest of the badges?

Please take a look at the video below—when my Max - Personal Record in the backend is set to 8, and I try to update it to a lower number, it doesn’t work. Could you please check?

Screenshot 2024-09-06 at 7 37 38 PM

https://github.com/user-attachments/assets/ec18003a-e35b-42b0-bd47-3ee74e18ccef

**Review by ashayk9 — APPROVED** [review]
I tested the PR, and it is working as expected. In "Assign Badges," existing badges are already selected. Adding more badges of the same type increases the count by 1, except for the "New Max - Personal Record Award." Additionally, changing the count value in "Select Featured" for the "New Max - Personal Record Award" badge increments the selected number.

https://github.com/user-attachments/assets/655b0858-e051-4b0f-8e93-d7c6dfec0313

**Comment by sud306** [comment]
Hi,
I tested this PR and it works as expeceted.
The counters are getting updated as it should.
8  PR2525_1
8  PR2525_2
8  PR2525_3
8  PR2525_4
8  PR2525_5
8  PR2525_6

**Review by Parth-tech — DISMISSED** [review]
Hi Angela,
The badge assignment and the count of the badge works as intended. The webpage does not crashes on selecting featured badges. One cannot select more than 5 badges. The badge count also updates correctly.

`Image References:`
Screenshot 2024-09-07 at 3 38 21 AM
Screenshot 2024-09-07 at 3 38 52 AM
Screenshot 2024-09-07 at 3 39 17 AM

**Review by swaroop-2007 — APPROVED** [review]

**Comment by swaroop-2007** [comment]
@angelalalacheng 
Great work! The modifications work as expected.
a) There is no crash when choosing up to five highlighted badges in "Select Featured" and saving modifications.
b) The user's existing badges are correctly reflected in the "Assign Badges" checkboxes.
c) It is possible to successfully update the "New Max - Personal Record Award" badge under "Select Featured".

Screenshot (356)
Screenshot (357)
Screenshot (358)
Screenshot (359)
Screenshot (360)

**Review by crystallow1168 — DISMISSED** [review]
Hi @angelalalacheng,

Everything is working as expected. These are my findings:
(a.) ✅ When open the "Assign Badges" popup, see the checkbox check the existing badges.
image

(b.) ✅ Test the functionality: Select the existing badge then its amount will +1. Select the new badge will show 1 except the "New Max - Personal Record Award" badge.
image
image

(c.) ✅ When select "New Max - Personal Record Award" badge, it will first show the "personalBestMaxHrs" in userProfile from backend(you can check that in MongoDB). And, if you adjust the Count value in "Select Featured" and larger than "personalBestMaxHrs", it will show the Count value.
image
image

(d.) ✅ Select the featured badges (at most five) and save changes. Webpage does not crash.

Observation under Assign Badges popup: If the checkbox shows existing badges on "Assign Badges" popup, wouldn't it be troublesome for the admin to uncheck all the boxes if the admin only wanted to add just one badge when the user has a list of existing badges?

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

PR 2525-2

PR 2525
PR 2525-1

Thank You

**Review by vishnupriyaatheti — APPROVED** [review]
@angelalalacheng changes are working as expected. 
Count value updating in click and confirm of new badges. Featured the updated as selected in the profile and also the webpage is not crashing when we select 5 featured badges and saving.
FE PR 2525 change of featured badges

**Review by SnelPatare — DISMISSED** [review]
The changes are working as expected. 
image

**Comment by KurtisIvey** [comment]
Would love to get this moved to final review asap once the merge conflict is cleared up

**Comment by saurabhshetty29** [comment]
The badge assignment and count function as expected, with no crashes when selecting featured badges. Users can't select more badges than allowed, and the badge count updates correctly. Everything works smoothly in both light and dark modes.
Screenshot 2024-09-14 at 12 21 39 PM
Screenshot 2024-09-14 at 12 22 09 PM
Screenshot 2024-09-14 at 12 22 42 PM

**Review by nishitag5 — DISMISSED** [review]
- Verified that the "Assign Badges" popup correctly checks the boxes for existing badges.
- Selecting an existing badge increments its count by +1, and new badges start at 1 (except "New Max - Personal Record Award").
- "New Max - Personal Record Award" correctly displays personalBestMaxHrs from the backend, and adjusts when the count exceeds this value.
- Successfully selected up to five featured badges, saved without crashes, and changes were applied correctly.

https://github.com/user-attachments/assets/cff3f748-c407-4d70-ba81-db49f8c4bffa

**Comment by geetamatkar** [comment]
Hi @angelalalacheng ,
Tested this PR and it is working as expected.

1. After opening the "Assign Badges" popup, checkbox checks the existing badges.
2.  After selecting the existing badge , amount will +1. S
3.  Web didn't crash after selecting 5 feature badges.

PR2525-3
PR2525-2
PR2525-1

**Review by nevatiarishabh — APPROVED** [review]
Everything is working as expected. Selecting the existing badge makes the amount +1.
"New Max - Personal Record Award" badge shows "personalBestMaxHrs"  in userProfile.
The web does not crash when five featured badges are selected and saved.

Screenshot 2024-09-20 at 6 48 02 PM

Screenshot 2024-09-20 at 6 59 39 PM

**Comment by angelalalacheng** [comment]
> Would love to get this moved to final review asap once the merge conflict is cleared up

@KurtisIvey
Hi, merge conflict is cleared up!
Thank you.

**Review by mrinalini-raghavendran19 — DISMISSED** [review]
LGTM!

The changes work as expected - I have verified the following in the recording below:

- When opening the "Assign Badges" popup, checkboxes show existing badges.
- Selecting an existing badge adds 1. A new badge shows 1, except for "New Max - Personal Record Award."
- Selecting "New Max - Personal Record Award" shows "personalBestMaxHrs" from the backend. If you increase Count beyond that, it shows the new Count.
- Saving changes, after choosing 5 featured badges doesn't crash the app

https://github.com/user-attachments/assets/4882af93-be55-40ab-aad6-f598de6eceb0

Great work!

**Comment by pallavithorat** [comment]
I have tested this pull request and everything is functioning correctly.

When opening the "Assign Badges" popup, the checkboxes correctly reflect the assigned badges. Selecting an existing badge increases its count by one. Additionally, the web application remained stable after selecting five feature badges, with no crashes encountered.

PR1#2525
PR2#2525

**Review by AshishNags — DISMISSED** [review]
Approving this PR, every functionality is working as expected.
Screenshot 2024-10-09 182934
Screenshot 2024-10-09 183002
Screenshot 2024-10-09 183114
Screenshot 2024-10-09 183126

**Review by Anoushka21 — DISMISSED** [review]
Tested the PR with admin role.
Working as expected. Counter for badges are being updated as well as featured badges counters!

https://github.com/user-attachments/assets/d3a962a0-a1db-4593-9db3-c9af9c2585ba

**Review by bhavya17prakash — APPROVED** [review]
**Features Verified as Working:**

1. Pre-selected badges: Existing badges are correctly pre-checked.
2. Badge count increment: Adding more instances of the same badge correctly increments its total, except the "New Max - Personal Record Award" badge.
3. Count update for "New Max - Personal Record Award": Changing the count for the "New Max - Personal Record Award" in the "Select Featured" section accurately reflects the selected number on the profile.
4. App stability: No crashes occur when selecting up to 5 badges to feature.

Please find the screen recording of testing attached

https://github.com/user-attachments/assets/abd8f903-3986-44c7-91e1-42e6994e26be

**Pull request merged**
