### PR TITLE
Obeda radio unit test

### PR DESCRIPTION
**Pull request by dah00**
# Description
Unit test for Radio component 

## Main changes explained:
- Added test file Radio.test.jsx

## How to test:
1. check into current branch
2. do `npm install` 
3. do `npm test src/components/common/Radio/Radio.test.jsx`
4. Make sure all tests pass

## Screenshots or videos of changes:
pass with no warning

## Note:
- replaced `checked `attribute with `defaultChecked` attribute because of this warning:
all tests pass with warning

### CODE REVIEW

**Review by pika-chu11 — APPROVED** [review]
Hi @dah00 , I have tested your unit test and it passed on my end. Great Job!
PR 1546

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great work! 

PR 1546

**Comment by wanglu1207** [comment]
Obeda_Radio_unit_test
Hi @dah00, good job! All the test cases are passed!

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-18 at 11 59 54 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 13 - PR5

**Review by ZichanYang324 — APPROVED** [review]
Hi @dah00 I have tested all the cases and they were all passed. It is perfect. And the screenshot for the test is also attached.
Screenshot 2023-11-25 at 3 09 24 AM

**Review by Hemsharavanan — APPROVED** [review]
- Your tests ensure thorough coverage, validating rendering, label display, checked states, selection behavior, default value handling, and error message display.
- The tests are clear and well-structured, focusing on specific functionalities and scenarios related to the Radio component.
- Well done!
PR #1546 Obeda radio unit test

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
