### PR TITLE
Shrey_test_Members_Member_Component

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for Member component

## How to test:
1. check into current branch
2. do `npm install` 
3. npm test Member.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-10-27 at 5 10 32 PM

## Note:
Added prop types, and conditional rendering in Member.jsx file to handle NaN console.error warning.

Screenshot 2023-10-27 at 5 11 38 PM

### CODE REVIEW

**Review by ChirayuRai — APPROVED** [review]
It passes the tests on my end. Good job!

Screenshot 2023-10-27 at 4 16 19 PM

**Review by JYXiao-2021 — APPROVED** [review]
Hi, It all passed, good job.
Screenshot 2023-10-27 at 7 25 28 PM

**Comment by sahilpatel18** [comment]
**Testing Summary:**
I have successfully tested the PR and everything is working as expected. All unit tests for the Member component passed.

**Test Evidence:**
Screenshot 2023-10-27 at 8 15 46 PM

**Review by sahilpatel18 — APPROVED** [review]
**Testing Summary:**
I have successfully tested and everything is working as expected. All unit tests for the Member component passed.

**Test Evidence:**
Screenshot 2023-10-27 at 8 15 46 PM

**Review by Iris-Song — APPROVED** [review]
I have tested, and the result is as intended. Good job!
Screenshot 2023-10-27 at 23 08 53

**Review by yangfan2001 — APPROVED** [review]
Hi, I have read and tested your PR. Looks like all test cases are passed, Great Job!
image

**Review by malikjahanzaib — APPROVED** [review]
Hi @Shreyj14, All tests passing. Great job!!!

Screenshot:

Screenshot 2023-10-27 235448

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-10-28 003425

**Comment by kavya151** [comment]
Hi @Shreyj14 All the tests passed.
Screenshot 2023-10-28 at 11 19 54 AM

**Review by BaileyM96 — APPROVED** [review]
Good morning @Shreyj14 I ran your test and everything passed as expected great work.

## Screenshots

Screen Shot 2023-10-28 at 12 38 51 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
