### PR TITLE
Nahiyan_Dark mode on all modals on Badge Management page

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Implemented dark mode for all modals on the badge management page. 

## Related PRS (if any):
This frontend PR is related to the dev backend 

## Main changes explained:
- All modals that can be found on Badge Management page can now be toggled to dark mode

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other links -> Badge Management
6. verify that all modals are working in dark mode on this page

## Screenshots or videos of changes:
Screenshot 2024-05-10 115907
Screenshot 2024-05-10 115932

### CODE REVIEW

**Review by MinSun0814 — DISMISSED** [review]
All things working as intended. Nice work!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/f70b449b-77d2-4972-9824-5e4ed262a40f

**Review by tdkent — DISMISSED** [review]
Tested the various badge management modals, and they all have the correct dark mode color scheme:

Screenshot 2024-05-10 at 2 42 40 PM
Screenshot 2024-05-10 at 2 42 51 PM
Screenshot 2024-05-10 at 2 42 59 PM

**Review by hbodgal — DISMISSED** [review]
image

i checked the popups and dilogue boxes as well. Everything displays well in dark mode.

**Review by linkhanthtel — CHANGES_REQUESTED** [review]
All modals look good in dark mode but one thing, font color in light theme need to be changed in 'Assign Badge' component.

**Review by TareqMia — CHANGES_REQUESTED** [review]
Tested the changes and there were 2 issues that I found: 

- as mentioned already, the Assign Badge Modal's font does not look right in light mode 
- after assigning a badge, there is an issue with the confirmation modal's font. 

### Working properly
Screenshot 2024-05-11 at 5 09 49 PM
Screenshot 2024-05-11 at 5 16 38 PM
Screenshot 2024-05-11 at 5 16 50 PM

### Needs change 
Screenshot 2024-05-11 at 5 10 03 PM
Screenshot 2024-05-11 at 5 13 04 PM

**Review by lacnoskillz — DISMISSED** [review]
Hello @Nahiyan-16 
I have pulled your code and verified the dark mode works on bade management modals
Nice work!
See below image
dark mode badge



edit badge dark mode

**Review by abdel-lall — CHANGES_REQUESTED** [review]
The text is not visible in light mode.

Screenshot 2024-05-11 221652

**Review by nathcarnevalli — COMMENTED** [review]
I've encountered the same bug in the Badge Assignment feature. When switching to bright mode again, the letters doesn't change, as shown below

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/2085bb3b-a6f4-4699-84dc-62fbaaeb8556

**Review by nathcarnevalli — APPROVED** [review]
Everything working well :)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/2a17cb1d-9fe4-49d8-b1e5-d986a02067c2

**Review by linkhanthtel — APPROVED** [review]
I reviewed your PR again and all looks good. Nice work!

**Review by DaveB4r — APPROVED** [review]
Everything looks perfect.
Excellent work!
PR #2243 Review 1
PR #2243 Review 2
PR #2243 Review 3
I'm not sure if this font color is readable.
PR #2243 Review 4

**Review by peter6866 — APPROVED** [review]
All modals look good in Dark mode after changes and the assign badge modal is good in light mode. 
image
image
image
image
image
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
