### PR TITLE
Nahiyan_Fixed header UI for mobile

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Fixed spacing for mobile display (767px to 375px)
Fixed header appearing on the login page.

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Fixed spacing for mobile display (767px to 375px)
- Fixed header appearing on the login page.

## How to test:
1. check into current branch
2. do `npm install` and `npm start run:local` to run this PR locally
3. Clear site data/cache
4. log as owner/volunteer/admin user
5. go to the login page
6. verify header does not appear in any width size
7. go to the dashboard
8. verify the header items are spaced properly when 767px to 375px

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/4399412d-1ced-473d-80de-11d6c887eaaf

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Hello @Nahiyan-16 
The changes are working as mentioned.

https://github.com/user-attachments/assets/35dbabdd-a01c-4a70-a92b-99cceb146ddc


Thank you.

**Review by ddshah878 — APPROVED** [review]
Everything is working as expected. Good job!
https://github.com/user-attachments/assets/1e974d3a-dc9f-434c-8ff7-5fa5ce9325a8

**Review by ArtemisNyx3 — APPROVED** [review]
working as expected
[screen-capture.webm](https://github.com/user-attachments/assets/e6c387d7-832c-4453-b9cc-05515d46a7a4)

**Review by nikhilpittala16 — COMMENTED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/ceb4ffe3-d4ab-4884-b301-78dccb5a872b

**Pull request merged**
