### PR TITLE
Vijay Anand assign badge popup ui fix

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description

Screenshot 2024-08-06 at 10 06 07 PM

## Related PRS (if any):
To test this frontend PR you need to checkout the development branch in the backend.

## Main changes explained:
- Added UI fix to display the badges with a scrollable list inside the popup instead of scrolling the entire page to click the confirm for better user experience.

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→Other Links→ Badge Management
6. Search and select a name from the search result and click on assign badge a popup with a list of badges.
7. verify if the popup has an internal scrollable list of badges and it fits the browser's viewport.
8. verify the responsiveness and also in dark mode.

## Screenshots or videos of changes:
**Before Change**
https://www.loom.com/share/7a04336ed0b747fb8808a24cc91af8e8?sid=e98f0534-8298-4b88-a52b-6df33ab1c834

**After Change**
https://www.loom.com/share/d12be2f3c90046c08f86b2026bd504c1?sid=7af373c4-7cc6-487d-9bd9-f4f4b1c3bf0d

## Note:
These changes are related only to the assign badge popup.

### CODE REVIEW

**Review by DiyaWadhwani — COMMENTED** [review]
Hi Vijay,
Reviewed your changes and they're working as expected.
Thank you for your work. Attached a video implementation of the testing below.

https://github.com/user-attachments/assets/ba7143e7-b304-4560-bb22-45683dc0642d

**Review by Pranay-ai — APPROVED** [review]
Hey @vijay10pk 
The PR is Working as expected please find the attached screenshot for the same.
image
Thank You

**Review by vishavk1992 — APPROVED** [review]
Screenshot 2024-08-08 174616
I have tested this PR and it works as expected. I have attached video and screenshot for your reference.

https://github.com/user-attachments/assets/52847b14-a4e0-4991-9e8b-ca32a639f036

**Review by SatyashanthiT — APPROVED** [review]
I have tested this PR by checking out the current branch, installing dependencies, and running the PR locally. I verified that the badge assignment popup now displays a scrollable list of badges, fitting within the browser's viewport.
image

**Review by manikittu810 — DISMISSED** [review]
Hello @vijay10pk 
Followed the mentioned steps and verified the list of badges to assign and everything is working fine.
Screenshot 2024-08-08 at 5 20 02 PM


Thank you.

**Review by varunreddy03 — APPROVED** [review]
I have verified this PR and the assign badge popup UI is fixed and it is fitting perfectly to all the screen sizes and is working perfectly in both dark and light modes. I even checked the padding and layout and it is even across all the screens.

PR 2542_1
PR 2542_2
PR 2542_3

I don't know if this comes under the scope of this PR or not but I have observed an incomplete filling of color in dark mode for screen widths 425px and less. when the screen is below 425 when you scroll the screen to the right then you can observe that it is still white. I am attaching the screenshot for it below.

PR 2542_4

**Review by Aishwarya0898 — DISMISSED** [review]
Hi Vijay,
The PR is working as expected. Here is the reference.


https://github.com/user-attachments/assets/f674a41c-900c-41c0-b3b8-d54ca7c31d5e

**Review by beblicarl — APPROVED** [review]

**Review by ishan-miglani — DISMISSED** [review]
Hi, I have verified the changes in this PR. The assign badge popup UI is fixed and now scrollable and it is fitting to all the screen sizes and is working in both dark and light modes. Thanks!

https://github.com/user-attachments/assets/f3d44dc3-1fd1-4774-8be4-6112b26de490

**Review by jinxyou — COMMENTED** [review]
The fix seems working fine. Great work!
Screenshot 2024-08-09 171557
Screenshot 2024-08-09 171622

**Review by jinxyou — APPROVED** [review]

**Comment by arunsrao9** [comment]
I have tested the PR and everything seems to be working fine. Here are the screenshots:
In light mode:
Screenshot 2024-08-09 at 6 27 15 PM

In dark mode:
Screenshot 2024-08-09 at 6 27 53 PM
Great work!

**Review by adityasure9 — APPROVED** [review]
Hi @vijay10pk,

The UI fix looks great! The scrollable badge list works perfectly across different screen sizes and modes. Everything functions as expected. Thanks for the improvement!
PR2542After
PR2542Before
PR2542Mobile

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Requesting changes for inline styling. Both for the new inline styling added and the old inline styling that was integrated into your change. Make a custom style sheet specifically for this component or use bootstrap. 

However, I do like the improvement. 

Screenshot 2024-08-10 at 12 39 00 PM

**Review by abdel-lall — APPROVED** [review]
LGTM, Nice Job!

Screenshot 2024-08-10 235225

**Review by Gauravmg6 — APPROVED** [review]
It's working well.

Screenshot 2024-08-11 014348

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.

https://github.com/user-attachments/assets/e8a2c1d2-d149-4e27-afc4-5ddd19fac8eb

**Review by Parth-tech — APPROVED** [review]
Hi Vijay,
The PR works as intended and meets the requirements. The modal is responsive and usable at all screen sizes.

`Image References:`

Screenshot 2024-08-11 at 11 25 13 PM
Screenshot 2024-08-11 at 11 25 25 PM
Screenshot 2024-08-11 at 11 25 33 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/04c5d93e-2c3d-4552-9bef-da3b8e164797

**Comment by Lemonnycodes** [comment]
Hi,

 I tested the PR fix for displaying badges in a scrollable list within the popup.

-  The scroll functionality works as expected
- . The popup is responsive, fits well within the viewport, and works correctly in both light and dark modes. 

PR 2542 (2)
PR 2542

**Review by SMitta11 — DISMISSED** [review]
I login as admin and checked badge management as given in PR.I selected a user and it has scrollable list of badges for user both in light and dark mode.
Screenshots:
Screen Shot 2024-08-17 at 7 38 25 PM
Screen Shot 2024-08-17 at 7 38 51 PM

**Comment by vijay10pk** [comment]
> Requesting changes for inline styling. Both for the new inline styling added and the old inline styling that was integrated into your change. Make a custom style sheet specifically for this component or use bootstrap.
> 
> However, I do like the improvement.
> 
> Screenshot 2024-08-10 at 12 39 00 PM

Hello, @KurtisIvey I have made the changes you requested. Let me know if you want to change anything further.

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
We were so close :( 

2 out of the 4 inline styles were fixed, but there's one remaining. Once the last one is resolved, I'll re-review and approve. 


Screenshot 2024-08-24 at 4 21 45 PM

Screenshot 2024-08-24 at 4 21 52 PM


Last task for approval:
make a custom utility CSS class or use one of the bootstrap max height implementations. Utilize the built in colors in bootstrap for the background color & text or create a custom utility CSS class for that as well. 
If you go the stylesheet route, title it accordingly, so people know it's directly associated with this file.

**Review by KurtisIvey — APPROVED** [review]
Inline styling has been fixed and ui is functional. Thank you and great work!

Screenshot 2024-08-31 at 4 32 23 PM

**Pull request merged**
