### PR TITLE
Nandini Fixes Hours Status

### PR DESCRIPTION
**Pull request by nyelmela**
# Description
The display indicates 10/10 hours but includes an exclamation mark (!) in the HOURS status.
image

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:

- Updated file `EffortBar.jsx`: Fixed the time calculation logic to ensure correct display of total hours.
- Updated file `Timelog.jsx`: Ensured consistency in time calculation and display across components.

## How to test:

1. check into current branch
2. do npm install and npm run start:local to run this PR locally
3. Clear site data/cache
4. log as any volunteer
5. go to dashboard→ Clock in 10 hours
6. ensure that the exclamation mark (!) does not appear erroneously
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by Aishwarya0898 — APPROVED** [review]
Hello @nyelmela 
The PR works as expected, Here is the screenshot for reference.

Before:
PR #2535 Image1
After:
PR #2535 Image2
Dark Mode:
PR #2535 Image3
PR #2535 Image4

**Review by Pranay-ai — APPROVED** [review]
Hey @nyelmela 
The PR is Working as expected , please find the screenshot for reference thank you.

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.

image

Thank You

**Review by vishavk1992 — DISMISSED** [review]
I have tested This PR and it works as expected. 

Screenshot 2024-09-12 160828

**Review by RishithaMamidala — APPROVED** [review]
@nyelmela 
The hours status in this PR works correctly.
PR 2535

**Review by Parth-tech — APPROVED** [review]
Hi Nandini,
The PR works well and the codebase looks great as well.

Image References:
Screenshot 2024-09-14 at 12 43 37 AM
Screenshot 2024-09-14 at 12 43 46 AM
Screenshot 2024-09-14 at 12 46 35 AM
Screenshot 2024-09-14 at 12 46 47 AM

**Review by crystallow1168 — APPROVED** [review]
Hi @nyelmela,

Changes are working as expected! Great job!

image

✅ ! turns to checkmark when expected hours are fulfilled

**Comment by saurabhshetty29** [comment]
The content works seamlessly in both light and dark modes
Screenshot 2024-09-14 at 12 12 18 PM

**Review by Shreyav2000 — DISMISSED** [review]
I tested the changes with my test volunteer account by clocking in for 1 hour, and everything worked as expected.

The time calculation logic accurately reflects the hours without the exclamation mark (!) appearing unnecessarily.
Verified that the feature works smoothly in dark mode as well.
Great work on the fix!
PR 2535

**Review by nishitag5 — DISMISSED** [review]
The functionality is working as expected.
before:
Screenshot 2024-09-14 211229

after:
image

**Review by SFA23SCM35V — APPROVED** [review]
checked into current branch, ensured that the exclamation mark (!) does not appear erroneously

**Review by neeharikakoniki — APPROVED** [review]
Clocked in 10 hours
Ensured that the exclamation mark (!) does not appear erroneously
Verified that this feature works in dark mode
Everything works as expected
image
image
image
image

**Review by anirudhsk2107 — APPROVED** [review]
This PR is working as expected. Following are the screenshots for reference:-
Screen Shot 2024-09-20 at 1 51 20 PM
Screen Shot 2024-09-20 at 1 51 04 PM

**Review by mrinalini-raghavendran19 — APPROVED** [review]
Looks good to me!

The changes work as expected. Find below, attached screenshot.

Screenshot 2024-09-25 at 4 34 46 PM

**Review by nevatiarishabh — DISMISSED** [review]
I have tested the PR. Everything is working as expected.

Initial:
Screenshot 2024-09-26 at 7 17 39 PM
Screenshot 2024-09-26 at 7 18 10 PM

Final:
Screenshot 2024-09-26 at 9 40 16 PM
Screenshot 2024-09-26 at 9 39 57 PM

**Review by khushijain03 — DISMISSED** [review]
Hi @nyelmela , 
The PR works as expected.
Before: 
Screenshot 2024-10-04 at 8 21 16 PM

After: 
Screenshot 2024-10-04 at 8 27 24 PM

**Review by AshishNags — APPROVED** [review]
Approving this PR, working as expected.
Screenshot 2024-10-10 122725

**Comment by navya9989** [comment]
HI , I have tested this PR and is working as Expected! Great Work!
PR #2535

**Review by navya9989 — APPROVED** [review]
This PR works good!

**Review by javid679 — APPROVED** [review]
Hey I have checked the code and PR is working as intended.

Before: 

Screenshot (78)


After: 
image

**Review by bhavya17prakash — APPROVED** [review]
Changes are working as expected.
PR 2535

**Comment by VMD281** [comment]
Hi, I reviewed this PR and tested the functionality. It works perfectly fine!
PR#2535_1
PR#2535_2

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
