### PR TITLE
Papia added myteam filter and update user team

### PR DESCRIPTION
**Pull request by papiasharmin**
# Description
(PRIORITY High) Jae: Create “My Team” filter for Tasks Tab and Leaderboard (WIP Papia)
On the Dashboard, we need a “My Team” button and filter. Clicking this button should filter both the Tasks Tab and Leaderboard to show only the people on that person’s team. Then they should be able to use the 24h, 48h, etc. buttons and only see their team members. 
Make it the Default option for Core Team members
This is for Owner, Admin and Core Team classes to have a way to only see teams they are on in both the Leaderboard and Tasks Tab views (see below)
This is needed because these classes see ALL users and that makes useless all the tools for easily reviewing the work of just their team 

##Related PR:
 This PR is updated version of frontend PR #913.

## Main changes explained:
Updated the assign team and delete team function in the team page and profile page, so that the user teams state got updated. Added 'My Team' toggle button. Added a toggleTeamView function and getMyTeam helper function to get data for logged in user's team members. Remove fetching leaderBoardData from mapStateToProps to leaderboard component, as it is fetching the wrong state.

## How to test:
1. check into current branch
2. npm run start:local to run this PR locally
3. Log as admin, go to other links -> teams page, assign yourself on  team or delete from team, do the same on view profile-> team tab.
4. Go to dashboard, user will show team toggler button and their team members by default if they are assigned to any team, on leadderboard and task tab. If they are not assigned to any team, will not see the button and will see all members.
toggele the button to see if it shows all members and the person's team members alternatively. And also able to ftech correct data for clicking 24hr,48hr,72hr buttons. Also check the responsivenes.
4.Log in as volunteer or manager to see they can't see the filter button, and correct data of members are fetched on task and leaderboard 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/d4548ef6-7621-423f-867e-412540bdf214

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86232710/9b0135b4-5567-4b28-8839-413cb95313f6

### CODE REVIEW

**Review by winghojackyli — DISMISSED** [review]
Hi @papiasharmin , I've tested the PR and it works as expected. 

### As Admin
I can use the filter "View All" and "View Team" with the time filter. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/3e93255c-7b1b-4f3f-93db-f70ded4619d1

### As Volunteer

I cannot see the "View All" and "View Team" filter, but I can use the time filter. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/b19ed2df-7cce-45e1-bb20-cd1a3ffadbec

**Review by sxiong5 — APPROVED** [review]
Hey @papiasharmin, the changes are working well!

Screenshot 2023-07-28 at 15 12 40
Screenshot 2023-07-28 at 15 29 00
Screenshot 2023-07-28 at 15 29 47

**Comment by veronicacheng2** [comment]
Hi @papiasharmin, I have tested the PR and am able to apply filters using 'view all' button and 'my teams' button after assigning the team member. 

**Logged in as Owner**
Assigning Team Member:
Adding team members

Applying my team filter:
Applying my team filter

Applying view all filter with time filter:
Applying View All Filter

**Logged in as Volunteer**
No view all filter or my team filter:
Logged in as volunteer


**Exception on user profile page**
All pages are working fine, except that I can not access the user profile page, I am not sure if this happens to everyone or just me:
User Profile Page Error

**Comment by papiasharmin** [comment]
> Hi @papiasharmin, I have tested the PR and am able to apply filters using 'view all' button and 'my teams' button after assigning the team member.
> 
> **Logged in as Owner** Assigning Team Member: Adding team members
> 
> Applying my team filter: Applying my team filter
> 
> Applying view all filter with time filter: Applying View All Filter
> 
> **Logged in as Volunteer** No view all filter or my team filter: Logged in as volunteer
> 
> **Exception on user profile page** All pages are working fine, except that I can not access the user profile page, I am not sure if this happens to everyone or just me: User Profile Page Error

Thank you @ve

> Hi @papiasharmin, I have tested the PR and am able to apply filters using 'view all' button and 'my teams' button after assigning the team member.
> 
> **Logged in as Owner** Assigning Team Member: Adding team members
> 
> Applying my team filter: Applying my team filter
> 
> Applying view all filter with time filter: Applying View All Filter
> 
> **Logged in as Volunteer** No view all filter or my team filter: Logged in as volunteer
> 
> **Exception on user profile page** All pages are working fine, except that I can not access the user profile page, I am not sure if this happens to everyone or just me: User Profile Page Error

Thank you @veronicacheng2 , for pointing out this. This must have happened after solving resolving conflicts.

**Review by ramyaram2092 — COMMENTED** [review]
Hello @papiasharmin 
**Logged in as Admin :** 
I just assigned myself to a team. I am unable to see the View all/ my team button in my admin dashboard
image
2. I tried to see if the newly added team is visible in the prfile. Like @veronicacheng2  said the page crashes
image
**Note**: _I verified if the crashing happens because of adding a new team so i logged in as owner and tried viewing the profile page . It still crashes so i dont think adding team was the issue_ 








[4:41](https://highest-good.slack.com/archives/D05HD8PCH2R/p1690587678252199)
Is that expected ?  In 913 you said you were working on it

**Review by yaow62023 — COMMENTED** [review]
I tested all the relevant features, and most of them are functioning correctly. I was able to access the profile pages of each team member using both the admin and volunteer accounts. However, the badges' images are not displaying on the individual profile page. This issue may require fixing. For more details, please refer to the second video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/303f2a27-6c3b-459d-8683-86c4c8043bc9


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/680ad9fd-9f0d-4e41-aac8-35cad1ce7845

**Review by joyceiphone — COMMENTED** [review]
Need resolve conflicts.

**Comment by mounica-dingari-by** [comment]
Hi @papiasharmin , I've tested this PR and it works great, but there's a firebase error that I've encountered. It is somehow slowing down the page and taking a while to load. Other than that, the functionality works as intended.
Screenshot from 2023-07-29 11-44-13
Screenshot from 2023-07-29 11-44-36

This is the firebase error that I got

Screenshot from 2023-07-29 11-46-20

Checked, by logging in as Volunteer and the filters don't show up. Good work!
Screenshot from 2023-07-29 11-48-30

**Comment by n0vay** [comment]
Some of the functionality works for Admin Users, but as a mentor I can see only me on the team and as a volunteer nothing shows up.
image

**Comment by TheDescendant39** [comment]
Hi, @papiasharmin I tested your PR changes and everything looks good. 

*Test Sequence:*
1. Logged in as admin with no teams assigned. (Confirmed that the toggle button was not shown on the dashboard)
2. Assigned admin to two teams. (Confirmed that it was reflected in the profile->teams section).
3. Opened Dashboard. (Confirmed that the toggle button appeared)
4. Clicked on the toggle button multiple times. (Confirmed that the button filters between team members and all members)
5. Checked the same for the leaderboard.
6. Deleted the assigned teams and opened Dashboard again. (Confirmed that the toggle button disappears as the admin is not in any team).

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/2c57781e-380c-4f2c-ac8d-15fc13cb3513

**Review by shiva2096 — DISMISSED** [review]
Hi @papiasharmin 

Great work! Functionality is working as expected. However it is a bit slow when I use the toggle switch.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/6782d7b3-f28f-4d03-9b06-cc825bc29cf8

**Review by eduvarjaor — COMMENTED** [review]
Hi @papiasharmin 

I tested this PR and these are the results:

1) As an owner and admin, I was able to get myself in and out of the team, but I couldn't see my teams in the dashboard due to a localhost

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/5a785677-8d3b-45ab-a92a-4591a29efaa7


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/72e8c608-9f87-4c67-8037-4330f83c84f1

2) As a volunteer, I was unable to get myself into a team.
Screenshot_1

**Comment by AnishPandita** [comment]
Hi @papiasharmin, on testing the PR the result was as intended. I tested all possible scenarios including no assigned team to admin, then assigning and testing the toggle button, and checking that volunteer/manager don't see that button. However as pointed by some other members the toggling did seem bit slow.

Screenshot 2023-08-01 at 12 37 38 AM

Screenshot 2023-08-01 at 12 38 59 AM


Screenshot 2023-08-01 at 12 39 28 AM

**Comment by papiasharmin** [comment]
> Hi @papiasharmin, on testing the PR the result was as intended. I tested all possible scenarios including no assigned team to admin, then assigning and testing the toggle button, and checking that volunteer/manager don't see that button. However as pointed by some other members the toggling did seem bit slow.
> 
> Screenshot 2023-08-01 at 12 37 38 AM Screenshot 2023-08-01 at 12 38 59 AM Screenshot 2023-08-01 at 12 39 28 AM

Hello @AnishPandita, thank you for your review. it is slow because, there are almost 700 member, and collecting timeentries for all those users can and setting the state gets slow.

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions. The functionality is working as expected! I test on different roles. The Admin account is correctly displaying all members on the team and their corresponding tasks. The volunteer account only displays his own information. The button is also working correctly on Admin account and not shown on the volunteer account. Good job!

The only thing I'm wondering is that Admin is hard to figure out which team that member belongs to. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/ec96c2f1-ffde-4140-b606-9dc9736a451b

**Comment by luisarevalo21** [comment]
Hello @papiasharmin 

I reviewed your PR and works as intended. Great job!

As an admin, I added my accounts to my specific team. I can remove and view all them inside of the dashboard and my profile. 

Screenshot 2023-08-08 at 3 29 46 PM


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/0ac3a0b9-890f-48f0-912c-26437458af55

As a volunteer I can view only the hour details for volutneers. Using the hour buttons, but I cannot see the admins. 
I can also view what team I am on, via my profile page.

Screenshot 2023-08-08 at 3 29 29 PM

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works good on my device. @papiasharmin 

image

**Review by ThapeloMasasa — DISMISSED** [review]
The filter works as expected:

When I am not part of a team it doesnt show up
Screenshot 2023-08-11 at 6 37 05 PM

Once I am part of a team I can view all or select my team and the CSS works well for the button
Screenshot 2023-08-11 at 6 37 44 PM
Screenshot 2023-08-11 at 6 39 00 PM

**Comment by Jiyuanxia** [comment]
Hello @papiasharmin, I've thoroughly reviewed your pull request and performed testing on it. I'm delighted to confirm that it's working precisely as you intended. Excellent work!

Login on a owner role with a team
Screenshot 2023-08-15 150908

After clicking view all
Screenshot 2023-08-15 150944

Login on a owner role without a team
Screenshot 2023-08-15 151054

Login on a volunteer role with a team
Screenshot 2023-08-15 151229

**Comment by Lin1404** [comment]
Hi @papiasharmin ! I've tested this PR. Functionality works well! 

Login on a admin role with a team
image

After remove from a team
image

Login on a volunteer role with a team
image

**Review by belagaam — DISMISSED** [review]
I tested the PR as per the instructions and it works as expected. Good work.

As an admin

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/1b5e2c85-a72b-4832-b9f3-33be7bf77bbc

As a Volunteer

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/0351eec8-b83a-44f6-953b-6399bb9880b2

**Comment by Shubhu0** [comment]
PR works as intended. Good job!

**Comment by Shubhu0** [comment]
Hi @papiasharmin 

Tried to review and test your PR but the page just crashes and ends up as a blank output.

image

**Comment by kavya151** [comment]
Hi @papiasharmin . I have tested this PR locally and everything works as intended. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/164a7498-2d63-4190-b0d6-d40a6ce58fa4

**Comment by ptrpengdev** [comment]
Hi @papiasharmin, it appears that there are code conflicts with the latest code in the development branch. Could you please take a moment to resolve these conflicts? Thank you!

**Review by Changhao3220K — COMMENTED** [review]
hi @papiasharmin 
the adding team function works well for admin and volunteers,
but when checking the team for admin there is a bug, I will attach a screenshot below
Screenshot 2023-11-17 at 2 33 28 PM
Screenshot 2023-11-17 at 2 55 36 PM

**Comment by ptrpengdev** [comment]
Hi @papiasharmin, I have tested the app with the Admin account. Some features failed locally, possibly due to latest code change in the back end . Could you please specify the specific backend branch I should checkout to test with this frontend PR code?

Env Setup: 
1. Frontend branch: papia_added_myteam_filter_and_update_user_team
2. Backend branch: development (latest code base)

Test functionalities:
1. Search/Add member for team (**Sucess**)
2. Delete member for team (**Sucess**)
3. New team creation (**Failed**) 
   -  rendered blank page. **API error message**: "team validation failed: teamCode: Please enter a code in the format of A-AAA or AAAAA"; http://localhost:4500/api/team
5. Dashboard task data displaying (**failed**)
   - **API error message**: QueryExceededMemoryLimitNoDiskUseAllowed. http://localhost:4500/api/user/655621d546f10d58d8d9b581/teams/tasks


I have attached the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/66b2e880-dfe2-4115-9346-3c6c21abc96f

Screenshot:
taskDisplayErrorWithDevBranchBackend

**Review by ptrpengdev — APPROVED** [review]
Hi @papiasharmin, I have tested the app with the Admin account. Some features failed locally, possibly due to latest code change in the back end . Could you please specify the specific backend branch I should checkout to test with this frontend PR code?

Env Setup: 
1. Frontend branch: papia_added_myteam_filter_and_update_user_team
2. Backend branch: development (latest code base)

Test functionalities:
1. Search/Add member for team (**Sucess**)
   - For the search feature, I believe we could enhance the user search in the future by displaying the user name along with an additional unique identifier, such as email. Currently, the search result shows only the user name. However, since user names in the application are not unique, the search results could return multiple records of the same name (e.g., "Peter Peng") without additional information. This enhancement would provide better clarity. 
2. Delete member for team (**Sucess**)
3. New team creation (**Failed**) 
   -  rendered blank page. **API error message**: "team validation failed: teamCode: Please enter a code in the format of A-AAA or AAAAA"; http://localhost:4500/api/team
5. Dashboard task data displaying (**failed**)
   - **API error message**: QueryExceededMemoryLimitNoDiskUseAllowed. http://localhost:4500/api/user/655621d546f10d58d8d9b581/teams/tasks


I have attached the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/66b2e880-dfe2-4115-9346-3c6c21abc96f

Screenshot:
taskDisplayErrorWithDevBranchBackend

**Review by ptrpengdev — CHANGES_REQUESTED** [review]
Reference: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1061#pullrequestreview-1738194806

**Comment by palakgosalia** [comment]
Hey, I tested your code. I was able to add myself in a new team and delete as well. I faced one issue at the dashboard page. The team member tasks section won't load. On checking the network logs I saw that the tasks API call fails and has error code 400 and the error shown is QueryExceededMemoryLimitNoDiskUseAllowed. Attaching the video below



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/635f00d3-de5e-4f84-b240-9f2e90d0a98f

**Review by Shuhua-L — COMMENTED** [review]
Update: I ran into the same issue on the dev branch. So, it may not be related to this PR but to the dev branch or API. I'll come back to this when it's resolved.

---

I tried to test your branch with the latest dev backend, but I'm having issues loading Team Member Tasks. Please check the error message in the screenshots.

PR1061-1
PR1061-2

**Comment by ZichanYang324** [comment]
Hi @papiasharmin , I was facing the same error when I tried to go back to the dashboard, the team member tasks sections were unable to illustrate, so I cannot test the 24/48/72 hours feature. But these functions work very well for other parts, including adding myself to a team and deleting myself from a team. 

Screenshot 2023-11-24 at 10 51 47 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86720318/528052a6-9183-4340-81ea-d04fc4ae3d17

**Review by sucheta90 — CHANGES_REQUESTED** [review]
@papiasharmin I tried to run this branch locally as - Admin and as a Team Member, both the times a got error. Hence, couldn't test the feature.
**As ADMIN**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/97db485c-7372-47d5-bf43-1f5b683757da

**As Team Member**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/d1d4449d-d11e-40b8-ab6a-414c8c9fcfc8

**Comment by DragonSlayer2401** [comment]
I logged in as an Admin user and after a few seconds, the whole app became unresponsive. Refreshing the page did fix it but only for a few seconds. I tried restarting the frontend and clearing my browser data with no success. Please see the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/2bb1c447-98e9-45b3-9157-cce3cfb0ded5

**Review by Alforoan — CHANGES_REQUESTED** [review]
As a few other people have pointed out, the page becomes unresponsive. Fix is needed. Thank you.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/77bcee58-8d69-4a7e-bffd-049e6dbe4b21

**Pull request closed without merging**
