### PR TITLE
Shiwani unit test for BadgeTableFilter component

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for BadgeTableFilter component 

## Main changes explained:
- Added a new file called BadgeTableFilter.test.js
- Added 6 test cases: renders without crashing, check name box, Check description box, Check type dropdown, Check ranking dropdown, Check if reset filter button works properly

## How to test:
1. check into current branch
2. do `npm test src/__tests__/BadgeTableFilter.test.js` 
3. check if all the test cases pass

## Screenshots or videos of changes:
Screenshot 2023-11-09 at 1 22 01 PM

### CODE REVIEW

**Review by tsunami776 — APPROVED** [review]
Hi @Shiwani99, your unit test looks good to me. Your test covers TextSearchBox, DropDownSearchBox and reset button components in BadgeTableFilter. I checked the mock data with the description filter and it works as described. I also ran your unit test and all tests passed. Great work!

CleanShot 2023-11-09 at 13 04 01


CleanShot 2023-11-09 at 12 51 13

**Review by navneeeth — APPROVED** [review]
Hello, @Shiwani99! Good implementation of the tests!
All the test cases are passing:
test cases passing

**Review by Sssky-18 — APPROVED** [review]
Hi @Shiwani99 , I tested your new unit test for BadgeTableFilter, and it worked as expected. All the tests are passed well. Great work!
PR#1507

**Review by pika-chu11 — APPROVED** [review]
Hi @Shiwani99 , I have tried your test and it passed on my end! Great job!
PR 1507

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed! 

Week 11 - PR1

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-09 at 11 56 27 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-11-10 at 1 11 04 AM

**Comment by beblicarl** [comment]
All tests passed. Great work

image

**Review by wantingxu7 — APPROVED** [review]
I ran the test and got "PASS". Good work!

**Review by Bali2Mohit — COMMENTED** [review]
Hi @Shiwani99, I have tested your PR. All tests passed. Good work.

Screenshot 2023-11-10 at 19 54 54

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
