### PR TITLE
Edwin - Make save changes button visible for admin links

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-08-24 at 9 55 57 PM

## Main changes explained:

- Made code changes for save button to be visible when updating admin links when having the 'Manage Admin Links' permission
- Made code changes for save button to be visible when updating admin links when having 'Edit User Profile' permission

## How to test:

1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as Owner user
4.  Other Links -> Permissions Management -> Manage User Permissions -> Give "Manage Admin Links" permission to a non Admin/Owner user
5. Log into that user -> Click into any user -> Change the Edit button besides links in the bottom left -> Change admin links -> Update -> Save Changes button should appear and you should be able to click, refresh and changes should remain
6. Other Links -> Permissions Management -> Manage User Permissions -> Remove "Manage Admin Links" Permission and give "Edit User Profile" permissions to a non Admin/Owner user and repeat step 5. 

## Videos/Screenshots of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/e4b88f01-9c72-468c-98bf-2e2c515ad2de

### CODE REVIEW

**Review by iTvX — CHANGES_REQUESTED** [review]
Hi,

First, I logged into my owner account and made sure that my vol account had no permissions. However, when I logged into the vol account, I was surprised to find that I could modify the links of other people's accounts and successfully save them.

Then, following your instructions, I granted the account the appropriate permissions and tried to make changes. However, I didn't notice any difference.

I'm wondering if I made a mistake somewhere. If I did, please let me know as soon as possible. Thank you.

You can check the video below：

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/6f02352c-638b-4206-8b29-f93c25fda11c

**Review by Haoj1 — COMMENTED** [review]
Hi @EdwinLauM, I use admin to add a permission to my vol user, but it seems that the vol user still has no permission to edit admin link. Did I make a mistake in any step?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/205b80a3-4ec1-48ac-a76e-a18735f2ab09

**Comment by liaoyufu-leo** [comment]
Hi, I signed in as a admin user, but I can't see the user permission button. Is it normal? @EdwinLauM

**Review by harshidad — COMMENTED** [review]
Hi @EdwinLauM,

I signed in as a admin user, but "User Permission" button not visible.  Do I need different permission. 
Make save changes button visible for admin links #1174

**Comment by AuroraLovesWhales** [comment]
Hi @EdwinLauM. I have tested your PR and found the following issue: I granted the permission for my manager account, but when I logged in as manager and try to update the admin link for my volunteer account, I could not find the Admin Link field. Only Personal Link field is available. Please refer to the video recording below for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/9bb6338e-5913-4188-8583-808c504ced8d

**Review by ramyaram2092 — APPROVED** [review]
Hello @EdwinLauM  I am able to update another user profile from a non-admin/non owner profile with appropriate user permissions



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/6160d989-92e8-4c5f-9cb5-83e702f7d72d

**Comment by arcan9** [comment]
> Hi @EdwinLauM,
> 
> I signed in as a admin user, but "User Permission" button not visible. Do I need different permission. Make save changes button visible for admin links #1174

I'm the same as you. Have you found a solution? I pulled the PR but I don't see the changes. @harshidad

**Review by tsunami776 — COMMENTED** [review]
I tested with a newly created owner account and a volunteer account. I granted volunteer access to 'Manage Admin Links in User Profile', but when I logged back into my volunteer account I still couldn't edit admin links.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/2856a567-2ced-4784-9905-2cda160332ba

**Comment by Jiyuanxia** [comment]
Hi @EdwinLauM , I have reviewed your pull request and tested it. I can not see the tab for other links when I log in with owner role. And when I log in with admin role, User Permission does not show up.

Owner homepage
Screenshot 2023-08-30 162452

Admin Permissions Management
Screenshot 2023-08-30 162424

**Review by gabi-lima — CHANGES_REQUESTED** [review]
At first, an error appears when saving, and then the saving warning appears. However, when updating the profile, the link disappears.
![Captura de tela 2023-09-01 161750
imagem_2023-09-01_161821190](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74115277/1cd493c3-961e-4b77-b9c1-65e3045cfae4)

**Pull request closed without merging**
