### PR TITLE
Shiwani AssignBadgePopup component Unit Test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for AssignBadgePopup component unit test

## Main changes explained:
- Added a new file called AssignBadgePopup.test.js
- Added 6 test cases: Renders without crashing, Check if search box for badges rendering correct results, Verify Badge and Name column is present, Check if tool tip renders the text when hovered, Check filtered badges, Check if confirm button works as expected.

## How to test:
1. check into current branch
2. do `npm test src/__tests__/AssignBadgePopup.test.js`
3. check if all the test cases pass

## Screenshots or videos of changes:
Screenshot 2023-11-06 at 5 54 09 PM

### CODE REVIEW

**Review by luisarevalo21 — APPROVED** [review]
Hello @Shiwani99,
I tested your PR and works as intended. Great work!
Upon running the test suite all tests pass and no issues arise.
Screenshot 2023-11-06 at 5 25 26 PM

**Review by malikjahanzaib — APPROVED** [review]
Hi @Shiwani99, all tests passing. Great job!!!

Screenshot:

image

**Review by wantingxu7 — APPROVED** [review]
I've ran the test and all tests passed. See the following screenshot. Good work!

**Review by Shuhua-L — COMMENTED** [review]
All tests have passed as expected. Great job!

PR1499

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great work! 

Screenshot 2023-11-08 at 1 02 17 AM

**Review by Shuhua-L — APPROVED** [review]

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-08 at 4 59 11 PM

**Review by Jiyuanxia — APPROVED** [review]
Hi @Shiwani99 , I have reviewed your pull request and tested it. All tests passed. Well done!
Screenshot 2023-11-09 103027

**Review by sxiong5 — APPROVED** [review]
Hey @Shiwani99, all the tests are passed! Great job!

Screenshot 2023-11-09 at 13 45 42

**Review by pika-chu11 — APPROVED** [review]
Hi @Shiwani99 , all the tests passed on my end! Great work!
PR 1499

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all test cases passed!

Week 11 - PR 3

**Review by Shubhu0 — APPROVED** [review]
Hi @Shiwani99 tested your PR and all tests were passed

image

**Comment by wanglu1207** [comment]
shiwani_AssignBadgePopup_Unit_Test
@Shiwani99 Good job! It works as intended!

**Review by Iris-Song — APPROVED** [review]
Hi, I have tested locally and it works as intended. Good job!
Screenshot 2023-11-10 at 22 08 00

**Comment by palakgosalia** [comment]
Hey, I have reviewed and tested your PR locally and all test cases have passed. Thank you.

image

**Review by Hemsharavanan — APPROVED** [review]
All tests passed. Good work!

Shiwani AssignBadgePopup component Unit Test

**Review by DavidC0126 — APPROVED** [review]
Tested the PR and looked good to me!
Screenshot 2023-11-12 at 10 54 52 PM

**Review by ZichanYang324 — APPROVED** [review]
I have run the test and all the tests passed, well done!

the screenshot for this test is also attached.
Screenshot 2023-11-25 at 2 52 12 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
