### PR TITLE
Yixiao_form_unittest

### PR DESCRIPTION
**Pull request by JYXiao-2021**
# Description
Create the unit test for the Form component to confirm whether it working as intended.

## Main changes explained:
- Create file Form.test.js to do the unit test.
- Update file Form 

## How to test:
1. check into current branch
2. do npm install to run this PR locally
3. run npm  test src/components/common/Form/`__tests__`/Form.test.js

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by prnvjn — DISMISSED** [review]
Hi, All the 15 test were passed, quick side note it's 
`npm test src/components/common/Form/Form.test.js `

Screenshot 2024-02-10 at 4 10 16 PM

**Review by TareqMia — DISMISSED** [review]
Hi @JYXiao-2021, all tests passed after using the proper path 👍 
Screenshot 2024-02-10 at 7 09 30 PM

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 24 - PR4

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and all tests passed.

Captura de tela 2024-02-11 055343

**Review by 666saofeng — APPROVED** [review]
All tests passed!
image

**Review by ShengjieMao — DISMISSED** [review]
all tests passed. Can see all components properly rendered and tested. 
PR_1935

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and it passed all the test cases. Please refer the screenshot attached.

PR 1935

**Review by peterson337 — DISMISSED** [review]
Hi Yixiao, all Tests passed. Good job!

a

**Comment by mianmiantea2019** [comment]
Hi [JYXiao-2021](https://github.com/JYXiao-2021), all Tests passed and well structured. Good job!

image

**Review by chappdev2019 — DISMISSED** [review]

**Review by TapanPathak — DISMISSED** [review]
Hi, All test cases passed. 
Screenshot 2024-02-13 at 4 15 09 PM

**Review by peterson337 — DISMISSED** [review]
Hi Yixiao, all Tests passed. Good job!

a

**Comment by dhairya-mehta** [comment]
Hi All the 15 test cases passed! code was well written!
image

**Review by X1aoZhang99 — DISMISSED** [review]
Hi, all tests passed. Nice work! 
Screenshot 2024-02-17 at 21 43 54

**Review by XiaohanMeng — DISMISSED** [review]
Hi, all cases passed! Well done! 
PR1935-result

**Review by iTvX — CHANGES_REQUESTED** [review]
The unit test should be placed in the folder named "__tests__." Please create a "__test__" folder and place the unit test under this folder.

CleanShot 2024-02-26 at 20 15 56@2x

**Review by scoopstroop92 — CHANGES_REQUESTED** [review]
Hello @JYXiao-2021 ! good job on the test cases.  Kindly move the unit test case  it to the correct path 
image

**Comment by YHX6** [comment]
All tests passed for this unit test on my side.

**Review by YHX6 — DISMISSED** [review]
All cases passed, here is a overview

**Review by PratimaSingh02 — DISMISSED** [review]
Hey all the test cases have passed 👍 
1935 Yixiao_form_unittest

**Review by iTvX — APPROVED** [review]

**Review by Tiantian-C — COMMENTED** [review]
All the tests passed successfully!
Screenshot 2024-03-12 at 11 40 52 PM

**Comment by JYXiao-2021** [comment]
> Hello @JYXiao-2021 ! good job on the test cases. Kindly move the unit test case it to the correct path image

already update, please review again.

**Review by scoopstroop92 — APPROVED** [review]
Approving the PR as the path has been updated

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
