### PR TITLE
Ramakrishna fix openingteams newtab

### PR DESCRIPTION
**Pull request by Ramaruva**
# Description
image

## Related PRS (if any):
Please use latest  backend development branch to test this changes
…

## Main changes explained:
- Updated the TeamReport.jsx with an api call to get teamdetails 
- Updated the loader spinner in TeamReportLogs.jsx
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5.  Go to  Reports -> Teams
6.  Click an one of the team Name and navigate their component  and navigate back to page and try to navigate to another team and check if each time you navigate to another team respective team details are rendered or not.
7. Now instead of clicking on team name now try to open the team name in new tab like for different team with different team and check each time the respective  team get rendered 
8. For reference please watch uploaded video.
## video reference for testing

https://github.com/user-attachments/assets/2f51dbce-0d8e-47a7-a445-a09980bd5baa

## Note:
When I was about to raise the pull request, I received some new updates from the development branch. These updates resulted in differences in the team report, particularly affecting the rendering of team members. I'm uncertain whether this behavior is an issue or expected. However, it's important to note that the team members not rendering is unrelated to this specific pull request.
image

### CODE REVIEW

**Comment by AJAYINAVOLU** [comment]
Changes are working as expected.





Thank You

**Review by vishavk1992 — CHANGES_REQUESTED** [review]
I tried to review this PR but encountered an issue. I’ve attached a screenshot of the error. The error prevents the localhost from starting, so I wasn’t able to proceed

Screenshot 2024-08-20 174305
Screenshot 2024-08-20 174326

**Comment by Ramaruva** [comment]
> I tried to review this PR but encountered an issue. I’ve attached a screenshot of the error. The error prevents the localhost from starting, so I wasn’t able to proceed
> 
> Screenshot 2024-08-20 174305 Screenshot 2024-08-20 174326

Hi @vishavk1992,

Thank you for taking the time to review the pull request. I have re-tested the branch locally and was able to run it successfully without encountering any errors. Could you please try running it again on your end? If you continue to experience the same issue, kindly provide more detailed steps to reproduce the problem. I appreciate your assistance.

Thank you!
image

**Review by JatinAgrawal94 — APPROVED** [review]
Team pages are opening properly in a new Tab. Good Work.

https://github.com/user-attachments/assets/e6c1151a-d4e2-49c8-a572-ecf174c770c2

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.

https://github.com/user-attachments/assets/ff8e6c13-6d39-418d-ab5a-aab94c5a5608

**Review by Saniya98 — APPROVED** [review]
Everything is working as expected
image

**Review by SnelPatare — COMMENTED** [review]
Changes are working as expected. I have 2 suggestions for easy navigation. 
1. Adding a back button on team's detail page. 
2. When we select team -> navigate to team detail. when we hit back it shows me reports with no team listing. 
 I have a suggestion that when we hit back button from team's detail page it should show us team list instead of report page

Please find attached screenshot of testing. 
image
image

**Review by Jingyii800 — APPROVED** [review]
I have tested this function and it worked as described. I opened several teams as new tabs at the same time, and it displays the correct team name and content.

https://github.com/user-attachments/assets/c068245c-5fba-47dd-9bf1-e654ce050c38

**Review by sri0606 — COMMENTED** [review]
Hello @Ramaruva ,

I have reviewed the changes you made. Some notes:

* Although everything works as intended, it's taking a long time to load (maybe its just on my end).
* As mentioned earlier, a back button to teams page to easily view team list would be better. 


https://github.com/user-attachments/assets/838a28f0-fb29-44fd-8ab4-a8cad9853b21

**Review by RishithaMamidala — APPROVED** [review]
@Ramaruva ,

I have reviewed the PR. Everyting works as you described in new tab and also in the same tab.

But as mentioned in the previous comments:
1) It takes a lot of time to load the new team details when we go back and open the new team.
2) A back button to view team list would be better.


PR 2589-1
PR 2589

**Review by ddshah878 — APPROVED** [review]
The changes are functioning as expected. Great job!

However, as mentioned before, it takes a while to load the new team details when going back and reopening the team.

https://github.com/user-attachments/assets/45eb5526-6453-44cf-bd92-3e98b5bf23a4

**Comment by Ramaruva** [comment]
> Changes are working as expected. I have 2 suggestions for easy navigation.
> 
> 1. Adding a back button on team's detail page.
> 2. When we select team -> navigate to team detail. when we hit back it shows me reports with no team listing.
>    I have a suggestion that when we hit back button from team's detail page it should show us team list instead of report page
> 
> Please find attached screenshot of testing. image image

Hi @SnelPatare  thanks for taking time and testing my PR, I like you'r new suggestion, but let's jae decide on this @OneCommunityGlobal/highest-good-network-team and however I would like to introduce this feature separately like in another PR however thanks for suggestion

**Review by sam19981 — CHANGES_REQUESTED** [review]
Hi @Ramaruva,

I tested the changes, and while the navigation and initial loading work, I can’t see any team members even after waiting. Is this part of your task, or should this be a new bug? If it’s a bug, should I add it to the documentation?

Screenshot 2024-09-14 at 9 39 07 PM

Screenshot 2024-09-14 at 9 40 14 PM

**Comment by navya9989** [comment]
I Reviewed this PR and Everything is fine as Expected.

**Review by ziyanw52 — APPROVED** [review]
I test this PR and when click the team name, it can successfully navigate to their component and  team details are rendered. But as mentioned above, if go back and to the teams page and click another, it takes some time to load.
When open multiple teams in different tabs, it looks good.
801727979840_ pic_hd
811727979871_ pic_hd
821727980319_ pic_hd

**Comment by ShreyaLaheri** [comment]
Everything works well overall. However, I noticed a small issue: after selecting a team, the details displayed correctly. But when I went back and chose another team, the old details still showed for a moment before updating to the new team’s details. This delay might need to be looked into for a smoother experience.

https://github.com/user-attachments/assets/74dfec16-e37a-4e15-ac66-6d7cc4b6ec11

**Review by AshishNags — DISMISSED** [review]
Approving this PR, functionality working as expected.
Screenshot 2024-10-16 170526
Screenshot 2024-10-16 170552

**Comment by navya9989** [comment]
HI , I have tested this PR and changes are working as expected and I have seen that it is taking time to update team members while navigation but it is updating as expected. Great Work!
PR#2589

**Review by navya9989 — APPROVED** [review]

**Comment by Ramaruva** [comment]
> Hello @Ramaruva ,
> 
> I have reviewed the changes you made. Some notes:
> 
> * Although everything works as intended, it's taking a long time to load (maybe its just on my end).
> * As mentioned earlier, a back button to teams page to easily view team list would be better.
> 
>  PR.2589.mp4

Hi @sri0606 , Thanks for taking time and reviewing my PR , regarding load, it is because in this component they are taking all data at once this is causing the load time, at first I thought of fixing this load issue along with this issue but I realized it would take of lot of code refactoring and lots on impact on testing

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
