### PR TITLE
Raul implement opening a new tab by ctrl-clicking on the name in the user management

### PR DESCRIPTION
**Pull request by rauleffting**
# Description
(USER MANAGEMENT COMPONENT - PRIORITY LOW) 

> Jae: Make Names Command(Mac)/Control(PC) Clickable :
> a. Admin Login → Other Links → User Management
> b. The clickable names in the Team Management page won’t allow me to Command(Mac)/Control(PC) click to open them in a new tab

## Mainly changes explained:
The old opening function was deleted and a new one was created. Now, besides the opening at the same tab by clicking, if the user clicks pressing the ctrl/command, the profile opens in a new tab.

## How to test:
1. git checkout raul_impl_opennewtab_ctrlclicking_name
2. npm install
3. npm run start:local
4. log as an admin user
5. go to Other Links -> User Management
6. click any name by pressing the ctrl and make sure that the name's profile will open in a new tab.

Here is a video of my testing below:

https://user-images.githubusercontent.com/29555732/213498874-02996a6c-dc7c-433c-9f12-0c187afbd287.mov

### CODE REVIEW

**Review by RafaelCastilhoCastro — COMMENTED** [review]
Hi Raul,
I tested the feature and it is working. When clicking while holding Ctrl btn the browser opens the link in a new tab and when holding shift it opens the link in a new window. But I experienced some problems when doing that. After opening a new tab or a new window this way, the main window stoped responding completly. I could not click on any other link on the main screen. Only after refreshing the page it worked again. I'm using Chrome. If this is a different bug to be addressed in another PR, please let me know. Please check the attached video. [Video](https://user-images.githubusercontent.com/65736872/213517721-59c788e0-d455-4b61-bb84-d88839511b79.mp4)

Thanks.

**Comment by rauleffting** [comment]
Perfect, @RafaelCastilhoCastro! I did some changes. Please, try again! Thank you very much!

**Comment by PrabhjotSembhi** [comment]
Hey, I checked it out. It only opens a new tab once after the screen becomes unresponsive.

https://user-images.githubusercontent.com/82662768/213541752-015360cf-de2e-43a9-b811-6d01076fe043.mp4

**Comment by rauleffting** [comment]
Thank you @PrabhjotSembhi. I've already fixed it. Please, pull the new commit.

**Review by navyasrim — APPROVED** [review]
Looks good to me ,tested and working as expected.. on control click new tabl is opening and no blockers..

**Comment by RafaelCastilhoCastro** [comment]
@rauleffting I tested again and it works as intended and no more frozen screen.

**Comment by AnishPandita** [comment]
Hi, I tested this PR and its functioning properly. The profile opens up on a new tab using command + click on mac. 

https://user-images.githubusercontent.com/111321945/219853411-9e4ceb63-fd37-491c-83d4-d82df81adea7.mov

**Pull request merged**
