### PR TITLE
Sucheta - Update Projects Page sorting (by Project Name) and Filters Project List by Category Name and Active/ Inactive

### PR DESCRIPTION
**Pull request by sucheta90**
# Description

(PRIORITY HIGH) Jae: Update Projects Page sorting (WIP Sucheta)
Other Links>Projects
I’d like the default filter/sorting of this page to show the Projects that have most recently had additions to their WBSs at the top.
2ND PR: I’d also like sort buttons added by Project Name, Category, and Active so I can 1-click and sort by these instead if needed
3RD PR: Add a sort button to the Members and Inventory heading so I can 1-click and sort by whichever of these have had edits most recently.

## Related PRS (if any):
This frontend PR is related to the [PR#693](https://github.com/OneCommunityGlobal/HGNRest/pull/693) backend PR.
This PR is an updated version of [PR#1738](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1738)
…

## Main changes explained:
- Adds a `DropdownButton` component using ReactBootstrap to `ProjectTableHeader.jsx` - `Category ` and `Active `.
- Project Name can be sorted alphabetically.
- Projects can be filtered by category.
- Projects can be filtered by Active or Inactive status.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Projects
6. The table header should have sorting buttons by the Projects Name. The `downArrow ` sorts the project list (A-Z) and `upArrow ` sorts (Z-A).
7. The `Category ` has a dropDown to choose between categories. To reset the selected category, simple select `Unspecified` from the dropdown.
8. The `Active` has a dropdown to choose between active and inactive projects. To reset simply choose "Choose status".

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/77120566-f9c1-4a4d-9203-7515655ea299

## Tutorial to add WBS and import tasks

https://www.loom.com/share/65f71dcdbf834191bdb81fd5c40db8e8?sid=9700014d-3218-4b18-a39c-7a01e163e57f

## Note:
By default, the project page is sorted based on the most recently modified project. This includes adding a new Work Breakdown Structure (WBS) or adding/updating a task within the WBS. Please review the backend code to confirm the intended functionality.

### CODE REVIEW

**Comment by Haoxiang310** [comment]
I've tested your PR with admin and owner role and everything works as expect. Nice work!
For admin role:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/1450b801-2267-4a19-beca-a5793ad83808

For owner role:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/a38a9064-e49a-4584-af6b-39681e511223

There are 2 things I found which might can be improved. The first thing is when I click the down arrow, the order is from A to Z, and when I click the up arrow, the order is from Z to A, which is somehow counter-intuitive for me. The second thing is after I click on the up/down button, I cannot cancel choosing it thus cannot get back to the default order.

**Comment by yuhuimin1996** [comment]
Hi I've tested this frontend PR (also backend PR #693) with admin user and owner user. All the features worked well as you described, good job!
Admin user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/f840eaa6-8764-42de-abae-87ccef745e43

Owner user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/ec9f4952-20bf-4fe5-bd81-b8fd420918c6

**Comment by Cavein254** [comment]
@sucheta90 tested the pr #1872 together with the corresponding back-end [#693](https://github.com/OneCommunityGlobal/HGNRest/pull/693) and everything works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/bca750f9-8bf4-4f92-a24e-1ff9e37d9122

**Comment by mianmiantea2019** [comment]
Hi @sucheta90  I've tested the pr #1872 together with the corresponding back-end #693  with admin user and owner user. Everything works as intended. Good job!

Admin user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/df36879b-aa08-46de-8f95-7c80f308ea2d


Owner user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/ca690af2-6d14-4721-95d1-63729b061c56

**Review by bienzguoa — APPROVED** [review]
Tested using both admin and owner account, work as intended!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/d76e84ed-3088-4009-b908-298b95a3eaae

**Review by Renanluizssx — APPROVED** [review]
hi @sucheta90, i tested your application and it's correct, i logged in as an admin, i navigated to the dashboard, and i clicked on Projects, then i clicked the down arrow and up arrow, and the category and active functions are also functioning properly, congratulations.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/ebb9761f-57aa-4bea-bf4f-36eb3f449c31

**Review by 666saofeng — APPROVED** [review]
for details on PR https://github.com/OneCommunityGlobal/HGNRest/pull/693#pullrequestreview-1831490302

**Review by KevHnh — APPROVED** [review]
UI looks great and everything functions as expected.

Only suggestion I have is having one button that toggles sorting alphabetically and reversing it is probably more intuitive. Especially since when the sorting button is unselected, you can't see which sorting mode is active (unless you manually check yourself).

And by one button, I mean using the same arrow icon but just rotating it 180deg for its respective mode.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/e75f9fe5-8ecb-4ce6-b7e1-c1ec0eb09bdf

**Review by pshereen — APPROVED** [review]
Tested the PR and all the features are working as per the requirements. 
Well done!

1. The table header has sorting buttons by the Projects Name. The downArrow  sorts the project list (A-Z) and upArrow  sorts (Z-A). - Working

2. The Category has a dropDown to choose between categories. To reset the selected category, simple select Unspecified from the dropdown. - Working

3. The Active has a dropdown to choose between active and inactive projects. To reset simply choose "Choose status". - Working

Below video is attached to show all implemented features.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/f6f0c759-34f9-4e5d-a902-e061d34ac0fc

**Review by X1aoZhang99 — APPROVED** [review]
Hi Sucheta, 

I test your PR with BE [#693](https://github.com/OneCommunityGlobal/HGNRest/pull/693#pullrequestreview-1842066139). All functionalities work as intended. Congrats! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/40d45c1d-31f5-4808-8f75-4a0b826c836b

**Comment by xmyoot** [comment]
Hi Sucheta amazing work,

I test your PR. Everything works as intended please reference my video: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/e6401e62-18c1-4238-9bd0-d6cb283664cb

**Comment by galgalinidhi** [comment]
Hi @sucheta90, the functionality works as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/5d983d8e-2613-49ac-8cb4-b17c1c2bf473

**Review by peterson337 — APPROVED** [review]
I tested this PR along with the corresponding back-end PR, and it worked. Please review the test results on the back-end PR
https://github.com/OneCommunityGlobal/HGNRest/pull/693

**Review by Pandani07 — APPROVED** [review]
Tested this PR and the features work as intended. I could sort the projects alphabetically. I could also filter the category and the sorting applies to the filtered projects as well. Well done


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/9bb47ffb-13b5-480d-bff6-5476fe05daa0

**Review by SaiDeepak-NEU — APPROVED** [review]
Logged in as an admin and navigated to projects and tested the changes
1. The project name sorting worked well. I was able to verify the up arrow and down arrow sorting projects correctly alphabetically.
Screenshot (53)
Screenshot (52)
2. The category sorting also worked fine, was able to sort from the dropdown without any issues. selecting unspecified resetted the list as expected.
Screenshot (54)
3. The active status and inavtive status sorting also worked well.

Overall a very good and clean job on these changes.

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and everything is working perfectly.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/19ecfa5c-e7dc-47c6-90e6-f4eb1842c3b6

**Comment by one-community** [comment]
Shoot... didn't check the backend first. Needs fixes there.

**Pull request merged**
