### PR TITLE
Anirudh add edit button to each summary

### PR DESCRIPTION
**Pull request by belagaam**
### Description

BUG DESCRIPTION

### Main changes explained:

    Update file Timelog/WeeklySummaries.jsx. Added the functionalities of editing an already submitted summary
     Update file Timelog.css to add style to the buttons

### How to test:

    check into current branch
    do npm run start:local to run this PR locally
    log as owner/admin/core/mentor/manager/volunteer user
    accounts that can submit summary for other users (owner/admin/manager/mentor) can also edit summary for them  hence when switched to different user profile they could access the edit button. Core/Volunteer account can only edit their own summary.
    edited summary will only be saved if it has more than 50 words.       

**Added Functionalities**

User Able to edit its own Summary

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/7132a057-711b-46ad-80b3-256106b38d23

Admin User able to edit summary for different User 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/83bd474e-a0bf-4c2c-bd19-797dd679e3f0

### CODE REVIEW

**Comment by ptrpengdev** [comment]
Hi @belagaam, this feature works as expected. Great work! 

Verified:
- The edit button is displayed. The user is able to edit previous summaries.

image
image

- The Admin/Owner is **able** to edit a summary for other users.
- 
image

**Review by sucheta90 — DISMISSED** [review]
Hey! @belagaam , test the local branch as Admin and the **Edit** button works as expected. Well done.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/f937a8ca-fceb-4df2-a9fa-5c248124d83a

**Review by Alforoan — DISMISSED** [review]
I tested as an admin with editing and trying to save with less than 50 words and both worked as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/11c23d47-3734-4f15-84a6-bd04224457b7

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-02 at 2 02 11 PM
Screen Shot 2023-12-02 at 2 02 02 PM
Hi @belagaam , the button works as expected! Good job!

**Review by Lin1404 — DISMISSED** [review]

**Review by keyunhuangg — DISMISSED** [review]
1) Logged in as admin and did not have a weekly summary, no 'edit' button for this week, last week and the week before last's summary. 
2) Added a a weekly summary
3) Verified that the 'edit' button is visible in dashboard->weekly summaries for this week
Screenshot 2023-12-15 at 6 42 15 PM

**Review by bajajtushar094 — DISMISSED** [review]
Hi @belagaam, I reviewed your PR and it is working fine. Thanks 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/8feb4348-f35b-42e5-a31a-2d879f4a246a

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by scoopstroop92 — COMMENTED** [review]
@belagaam The functionality works great ! Can be merged once the merge conflict is resolved 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/fb3cf955-0e8d-4345-8a3d-9a486d8c0a9b

**Pull request merged**
