### PR TITLE
Vishala phase2 log materials bm dashboard

### PR DESCRIPTION
**Pull request by Vishala09**
# Description
This feature is a part of Building Management Dashboard (bmdashboard). This feature is to log the materials used by the housing projects.
Implements # Phase 2 WBS : 3.3.3
Documents and Figma wireframes referred : https://docs.google.com/document/d/1WONWQW_56pXlyZpdQFibddFuT3iMxFjho-wfGwbHFV8/edit
https://www.figma.com/file/kpwXZP2pLtOJ1Fn2u7Sivn/HGN-PII?type=design&node-id=430-5449&mode=design&t=Br43OtYXP9erhdFF-0

## Related PRS (if any):
This frontend PR is related to the backend PR#583 (Vishala phase2 logmaterials)  (https://github.com/OneCommunityGlobal/HGNRest/pull/583)

## Main changes explained:
- Created new files to maintain the log materials feature
- Added urls , actions , constants , reducers to integrate with the log materials components

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. on the related backend pr , do `npm run build` and `npm start`
4. log as admin user
5. go to http://localhost:3000/bmdashboard/logMaterials
6. The date is set to today's date initially
7. Select a project to load materials (At the moment , Tim and Vishala projects has some test data)
8. The projects loaded belong to Housing category only
9. If one user selects “project 1” and “Check Out”, this table will only show the rows representing the materials that belong to project 1 and the Available value is larger than 0. If the user selects “Check In”, the rows rendered from the database will be the materials whose Used value is larger than 0. 
10. Validations - Date : Date is less than or equal to current date. 
11. Validations - Log Entry : If Check In is selected , the entered value must be less than or equal to Using and if Check out is selected , the entered value must be less than or equal to Available
12. Cancel button : Clears the entered log values
13. Submit button : Posts the log entries to database.
14. Please test for the available functionalities. As it is a phase 2 task , I have implemented this with some inputs from the docs and based on my own ideas. So , please test this completely on multiple aspects.

## Screenshots or videos of changes:

image

[Untitled_ Oct 24,2023 10_27 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/ba522212-51a6-4886-9c6d-a1587d8d3780)

### CODE REVIEW

**Review by DavidC0126 — COMMENTED** [review]
Hi @Vishala09 I tested it and I encountered a problem. I pull dev backend and when I tried to load the data I got 404 every time. I used Tim's test data and yours. If PR#583 has merged into dev then can you tell me how to fix this problem? Thank you!

**Comment by Vishala09** [comment]
> > Hi @Vishala09 I tested it and I encountered a problem. I pull dev backend and when I tried to load the data I got 404 every time. I used Tim's test data and yours. If PR#583 has merged into dev then can you tell me how to fix this problem? Thank you!
> > 
> 
> Hi @DavidC0126 ! Thank you for testing. I mentioned this Backend PR [OneCommunityGlobal/HGNRest#583](https://github.com/OneCommunityGlobal/HGNRest/pull/583) I am sorry for the confusion , the 583 got linked automatically to one the available front end PRs
Please use this backend PR to test this functionality

**Comment by Vishala09** [comment]
> > > Hi @Vishala09 I tested it and I encountered a problem. I pull dev backend and when I tried to load the data I got 404 every time. I used Tim's test data and yours. If PR#583 has merged into dev then can you tell me how to fix this problem? Thank you!
> > > 
> > 
> > 
> > Hi @DavidC0126 ! Thank you for testing. I mentioned this Backend PR [OneCommunityGlobal/HGNRest#583](https://github.com/OneCommunityGlobal/HGNRest/pull/583)
> > I am sorry for the confusion , the 583 got linked automatically to one the available front end PRs
> > Please use this backend PR to test this functionality

**Review by navneeeth — CHANGES_REQUESTED** [review]
Hello, @Vishala09! I tested your implementation and you've done an excellent job! Here are my observations:

- The Date validation works as intended and does not allow selection of a date after the current date.
- The loading of the projects work as expected and the displayed projects belong only to the Housing category.
- The Check In or Out dropdown works as expected and the values displayed are based on the intended logic for Available value larger than 0 for Check Out and Used value larger than 0 for Check In.
- The Log Entry checks do not work as given in the description for the entered value since the description mentions `less than` but the implementation allows `less than or equal to` in the checks and in the error message displayed: `Please enter a value less than or equal to Stock Available`. Also, I was wondering if the implementation should instead check if the entered value is less than Available for Check In and less than Using for Check Out. This is since you'd usually Check In with Available item(s) and you'd check out item(s) that are in Using.
- The Cancel button works as expected. Perhaps a better placeholder for this button would be `Clear All`. 
- The Submit button works as expected but does not alter any Available/Using values after submitting the entered values successfully.
- The Log Material fields for entering the values allow negative values.
- The Success message looks good with the `Successfully posted log for $x materials` and the correct value of $x is displayed.

### Testing video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/63e8ec4b-b3e5-4830-b090-961061022185

**Review by cvtqx — CHANGES_REQUESTED** [review]
Hi @Vishala09, I've tested this PR for the functionality that you described. Great work! Everything seems to work as described:

1. The projects loaded belong to Housing category only - YES
2. If one user selects “project 1” and “Check Out”, this table will only show the rows representing the materials that belong to project 1 and the Available value is larger than 0. If the user selects “Check In”, the rows rendered from the database will be the materials whose Used value is larger than 0. - YES
3. Validations - Date : Date is less than or equal to current date. -YES
4. Validations - Log Entry : If Check In is selected , the entered value must be less than Using and if Check out is selected , the entered value must be less than Available - YES
5. Cancel button : Clears the entered log values - YES
6. Submit button : Posts the log entries to database. -YES

However, I think it would make sense if the data (available and using) was updating in the db and the relevant table cells after the post request is sent.

Screen Shot 2023-10-26 at 3 38 03 PM

Video of testing:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/bf168cf4-4a86-404e-8c4a-3fe738788d06

**Comment by Vishala09** [comment]
> Hi @Vishala09, I've tested this PR for the functionality that you described. Great work! Everything seems to work as described:

Hi @cvtqx , Thank you for testing. Your concern was discussed earlier during development and we have an update form to update the stock values accordingly in the db. These log records are going to be used for analytics purpose and hence they are not intended to make real value changes.

**Comment by Vishala09** [comment]
> Hello, @Vishala09! I tested your implementation and you've done an excellent job! Here are my observations:
> 
> * The Date validation works as intended and does not allow selection of a date after the current date.
> * The loading of the projects work as expected and the displayed projects belong only to the Housing category.
> * The Check In or Out dropdown works as expected and the values displayed are based on the intended logic for Available value larger than 0 for Check Out and Used value larger than 0 for Check In.
> * The Log Entry checks do not work as given in the description for the entered value since the description mentions `less than` but the implementation allows `less than or equal to` in the checks and in the error message displayed: `Please enter a value less than or equal to Stock Available`. Also, I was wondering if the implementation should instead check if the entered value is less than Available for Check In and less than Using for Check Out. This is since you'd usually Check In with Available item(s) and you'd check out item(s) that are in Using.
> * The Cancel button works as expected. Perhaps a better placeholder for this button would be `Clear All`.
> * The Submit button works as expected but does not alter any Available/Using values after submitting the entered values successfully.
> * The Log Material fields for entering the values allow negative values and decimal values which I assume must not be allowed.
> * The Success message looks good with the `Successfully posted log for $x materials` and the correct value of $x is displayed.
> 
> ### Testing video:
>  1447.+.583.mp4

Hi @navneeeth 
I am sorry for not mentioning it clearly in the description. It is less than or equal to. 
According to the document,  you Check out with available items (to use them , probably at the beginning of the day) and you Check In the items that were used (after using them , probably by EOD/W/M)

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hi @Vishala09, I have tested this PR locally and all the features that you implemented work as described. One bug I encountered is that I was able to post log entries as negative values to the database (as already pointed out by @navneeeth [here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1447#pullrequestreview-1700500883)). Functionality wise everything else looks good. Checkout my test recording below. Great job!!!

Test rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/7f0d6d58-ea39-4e47-a8b8-d98c55211c63

**Pull request closed without merging**
