### PR TITLE
Changhao - added unit test cases for resetpasswordpopup.jsx

### PR DESCRIPTION
**Pull request by Changhao3220K**
# Description
new unit tests cover edge cases for restpasswordpopup.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm test ResetPasswordPopup.test.js` to run this PR locally
3. verify all 12 unit tests are passed

## Screenshot:
Screenshot 2024-01-04 at 6 59 41 PM

### CODE REVIEW

**Review by beblicarl — CHANGES_REQUESTED** [review]
Hello @Changhao3220K Good job on the unit test cases
However, can you move the test cases to the path as suggested in the unit-testing channel in slack for the PR to get approved/merged

**Review by bienzguoa — COMMENTED** [review]
Good job! All tests passed. Could we consider more edge cases and add tests for them? Like passwords with spaces or leading/trailing spaces, passwords with allowed/disallowed symbols. 
Screenshot 2024-01-05 at 11 23 46 PM

**Comment by one-community** [comment]
> Good job! All tests passed. Could we consider more edge cases and add tests for them? Like passwords with spaces or leading/trailing spaces, passwords with allowed/disallowed symbols.

Please make things like this a requested change so they are sure to get integrated

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 19 - PR3

**Comment by Changhao3220K** [comment]
> Hello @Changhao3220K Good job on the unit test cases However, can you move the test cases to the path as suggested in the unit-testing channel in slack for the PR to get approved/merged

Hi @beblicarl Thank you very much for reminding me that! The file has been moved to the correct directory now. Please check.

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Review by bajajtushar094 — APPROVED** [review]
All test cases passed. Thanks 
Screenshot 2024-01-10 at 22 59 18

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the test cases passed please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/2b724f42-f9d6-47b6-ba29-a27a8a7f6425

**Review by sahilpatel18 — COMMENTED** [review]
All test cases passed successfully. Great work!

Screenshot 2024-01-12 at 10 01 09 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
