### PR TITLE
Kyrene - fix project details Page

### PR DESCRIPTION
**Pull request by KyreneAF**
# Description
Screenshot 2024-11-03 at 2 14 02 PM

## Related PRS (if any):
…

## Main changes explained:
- Changed Project name to show the name instead of id #
- Fixed over-lapping in media queries
- Added the Routes of component currently created to the buttons when clicked
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Enter this URL and sign in: http://localhost:3000/bmdashboard/65419e61105441587e2dec9
6. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/97932b6e-60f1-40e9-85c6-deed39cbdb90

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working properly
Screen Shot 2024-11-06 at 1 43 53 PM
Screen Shot 2024-11-06 at 1 44 04 PM
Screen Shot 2024-11-06 at 1 43 42 PM

**Review by Muhideenthegreat — CHANGES_REQUESTED** [review]
Verification:

- Project title/name is now displayed instead of ID. 

Screenshot 2024-11-06 at 11 04 13 PM
Screenshot 2024-11-06 at 11 04 36 PM

Minor Issues & Bugs:

- All buttons route to the appropriate functionality except the "Log Issues" & "Tool/Equipment" buttons. 
- Page toggle to dark mode doesn't reflect changes as the page still remains in light mode

Screenshot 2024-11-06 at 11 08 19 PM

**Review by nikhilgiri0226 — APPROVED** [review]
I have reviewed the PR. The project name is visible instead of project id. Also, the routing is working fine except log issues. Not sure if that is covered in this PR. So, I am approving the PR.


https://github.com/user-attachments/assets/473b3122-dcf1-4b4b-a3b6-63b556aaa872

**Comment by RashmiKY98** [comment]
Project name/title is displayed correctly. However, below issues where found.
1. When clicked on Tool/Equipment button, a blank page is displayed. Clicking back button of the browser does not work, it still displays a blank page. After clicking back button of the browser, I had to refresh for the page to load.
Screenshot 2024-11-09 232045

2. Unable to enable the dark mode in the browser. 
Screenshot 2024-11-09 230852

**Pull request merged**
