### PR TITLE
Jerry - email verification admin accounts

### PR DESCRIPTION
**Pull request by jerryren527**
# Description

Screenshot 2023-09-28 at 8 53 11 AM

The main motivation of this PR is to require an actual email and password associated with a real volunteer in the Main HGN app whenever creating an Administrator or Owner account in the Dev environment.  This is a security measure to provide an identity, in the form of a real email address, to otherwise anonymous Administrator and Owner accounts in the Dev environment.

## Related PRS (if any):
- Back end PR#582 (https://github.com/OneCommunityGlobal/HGNRest/pull/582)

## Main changes explained:
- Conditionally render input fields for Actual Email and Actual Password whenever role value equals ‘Administrator’ or ‘Owner’
- Added Error messages and Form Error messages that direct user’s attention to the Actual Email and Actual Password fields whenever invalid credentials are provided.

## How to test:
1. Check into back end branch. Follow the instructions to run the back end branch locally.
2. check into current branch
3. do `npm install` and `...` to run this PR locally
4. log as admin user
5. Other Links -> User Management -> Create New User
6. Select 'Administrator' Role, and provide the actual email address and actual password for your account on the Main HGN app.
7. Note that currently, there is no way to create 'Owner' role. However, if 'Owner' option were available, the above steps would still apply to it.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/a63ae70c-d650-427a-a0f9-3a16519a63ab

## Note:

Please try creating users of other roles as well to see if that breaks the app. Thanks!

### CODE REVIEW

**Review by navneeeth — APPROVED** [review]
Hello, @jerryren527! I tested your PR along with the related BE and it works as expected! Great implementation! 

- Checked into the current branches, logged in as Owner, navigated to `Other Links -> User Management` and tested the `Create New User` functionality by attempting to create an user with an Administrator user role. 

- The actual email and actual password fields validate the input properly and do not allow me to create an user with an Administrator user role if either the actual email or the actual password is incorrect. 
- The error messages displayed are as expected. 
- Verified in the database if the actual email field is reflected for the newly created user with the Administrator user role.

### Testing Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/ddea72af-ffc6-49d5-b709-ec58640fa4cc

**Review by malikjahanzaib — APPROVED** [review]
Hi @jerryren527, everything looks good to me in this PR. I was only able to create an admin account when correct actual HGN main credentials were provided. Confirmed in the DB as well. Loved the implementation. Great job!


Test rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/215c38fe-9e9e-42f3-bb67-05a89ad56ce9

**Review by Shuhua-L — APPROVED** [review]
Hey @jerryren527  I've tested both of your PRs, and they worked as expected. Nice work!

After logging in as an admin, I tested the 'Create New User' feature, and here are the results:

- Successfully created a new Volunteer user without providing actual HGN account credentials
- Creating an Admin user with correct credentials will succeed; otherwise, error messages will appear in the top-right corner


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/069ead9b-2710-4a18-b8ac-c61220b9d160

**Review by Alforoan — APPROVED** [review]
It worked as intended. Nice! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/5ee4b58c-b40a-4333-a458-c73718ea0b5e

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by ramyaram2092 — APPROVED** [review]
Good job on the functionality @jerryren527 ! The code looks good 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/e029536f-a857-4ed9-b3fb-4e5bf7bc24ed

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
