### PR TITLE
Ramya Unit Test :UsersProfile/ TeamsAndProject/AddProjectPopup

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit test for src/components/UsersProfile/ TeamsAndProject/AddProjectPopup

## Main changes explained:
-  New files
      - **_AddProjectPopup.test.js_** : unit test cases 

## How to test:
1. check into current branch
2. do npm test AddProjectPopup.test.js
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
1. Kindly take a look at the test cases and  suggest if more validations can be added 
2.  Validating the error message "**_Great idea, but they already have that one! Pick another!_**" cannot be effectively achieved through a unit test due to the close coupling between the parent and child components. Mocking the child component would essentially replicate the component logic, which defeats the purpose of isolating the unit under test. Instead, it would be more appropriate to verify this behavior in an integration test

### CODE REVIEW

**Review by prnvjn — APPROVED** [review]
Hey all tests passed, another test you can implement is if the project doesn't exist in the list it show's an error
image

**Review by TareqMia — APPROVED** [review]
Hello, I reviewed the PR and all the tests passed 👍 

Screenshot 2024-02-10 at 9 29 29 PM

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and all tests passed.

Captura de tela 2024-02-11 054806

**Review by 666saofeng — APPROVED** [review]
All tests passed on my side.
image

**Review by ShengjieMao — APPROVED** [review]
all tests passed. Testing data are well designed and comprehensive. all components and functions are tested. 
PR_1936

**Review by peterson337 — APPROVED** [review]
Hi ramyaram2092, all Tests passed. Good job!

a

**Comment by mianmiantea2019** [comment]
Hi ramyaram2092, all Tests passed. Good job!

image

**Review by TapanPathak — APPROVED** [review]
Hi, All test cases passed!

Screenshot 2024-02-16 at 7 08 57 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 25 - PR3

**Review by n0vay — APPROVED** [review]
Looks good to me
image

**Comment by dhairya-mehta** [comment]
Hi, I verified all the testcases and they passed!
image

**Review by ChengyanOo — APPROVED** [review]
All tests passed!
Screenshot 2024-02-22 at 18 29 06

**Comment by beblicarl** [comment]
All tests passed successfully. Great work!!

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
