### PR TITLE
Olena - LessonList Component (route, figmaDesign)

### PR DESCRIPTION
**Pull request by olenadanykh**
# Description
Lesson list component for Phase II
lessonlistpage

## Related PRS (if any):
none
…

## Main changes explained:
-created route
-created the design for the Lesson List component based on the Figma specifications
-made the changes to the card nav bar due to Jae request

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any user
4. go to http://localhost:3000/bmdashboard/lessonlist
5. verify design & tag input functionality and expand/collapse card functionality

## Note:
At the moment, only the tag functionality is operational. 
Please note that the Figma navigation bar and the current design differ. I've made adjustments based on Jae's request, and he has also verified the design.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/3bb09c8e-1aca-4164-818a-c9f915446282

### CODE REVIEW

**Comment by mounica-dingari-by** [comment]
Hi @olenadanykh , I can see that the route works as intended. 

Screenshot from 2023-11-04 21-36-03

**Comment by wanglu1207** [comment]
Good job! The route works!

**Review by lacnoskillz — COMMENTED** [review]
Hey @olenadanykh !
I pulled your changes and your design look great! I like the way you implemented the tags 
As far as responsiveness and design matching the figma it looks super good.
I did notice a bug with the tags though.
when you create tags with the same value or name and try to delete them out of order. It bugs out. Probably just a key issue
Note I'm assuming they probably don't want users to add multiple duplicate tags. I'm in the works of changing mine as mine allows duplicates. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/6237fad1-07b6-43b3-aa2c-482ae55a3c27


Also Note there is the double scroll bar issue that I also ran into on my page but with the global app.css change I made in my lessonform pr it fixes yours too.

```
#root {
  height: 100%;
  overflow-x: auto;
  overflow: hidden;
}
```

**Comment by olenadanykh** [comment]
> Also Note there is the double scroll bar issue that I also ran into on my page but with the global app.css change I made in my lessonform pr it fixes yours too.

Thank you for bringing this to my attention. However, I currently don't observe the double scroll bar problem on my end. It might be a browser-specific issue or related to different screen sizes, but 'll keep an eye on it.

**Comment by olenadanykh** [comment]
> I did notice a bug with the tags though.
> when you create tags with the same value or name and try to delete them out of order. It bugs out. Probably just a key issue
> Note I'm assuming they probably don't want users to add multiple duplicate tags. I'm in the works of changing mine as mine allows duplicates.

Thank you @lacnoskillz  for catching that issue with the tags, and you're absolutely right; it's likely a key-related problem. I encountered some limitations in combining the index with the tag name due to ESLint restrictions. Currently, I'm using the tag name as the key, but I am going to change it to ensure it's unique. Also, I think you're right that there's no need for duplicate tags, so it would be better to change the functionality.

**Review by lacnoskillz — COMMENTED** [review]
Hey @olenadanykh 
Nice work with the new tags functionality!
I verified that users can no longer make duplicate tags even with spaces
I did notice another small bug if a user enters a large tag it sticks outside the div
adding this line did the trick for my tag div and seems to work for yours also `word-break: break-all;`


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/69bb446a-e1d8-4b8d-bdbf-db4098627c38

**Review by Alforoan — APPROVED** [review]
All seems to work as it should. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/40cce638-fbac-40c7-a118-879b744dbf56

**Review by bajajtushar094 — APPROVED** [review]
Hi @olenadanykh, I reviewed your PR and it worked fine. Thanks 

Uploading Screen Recording 2024-01-11 at 23.47.42.mov…

**Pull request closed without merging**
