### PR TITLE
Fix Lint /src/utils/**

### PR DESCRIPTION
**Pull request by samarth9201**
# Description
Fixed Linting errors in /src/utils/**

## Related PRS (if any):
This frontend PR is not related to any backend PR.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user
5. The App should work as normal
6. Run `npm run test` to make sure all tests are passing.

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by anirudhsk2107 — APPROVED** [review]
Ran the app and navigated to a few pages, no problems there. 
All the test cases passed as well. 
Screen Shot 2024-11-08 at 11 01 34 AM
Screen Shot 2024-11-08 at 10 47 30 AM

**Comment by geetamatkar** [comment]
Tested this PR and app is working normally.

Screenshot 2024-11-08 at 3 46 12 PM

**Review by Muhideenthegreat — APPROVED** [review]
Verification: 
- All testcases passed and app is still functioning as expected as well

Screenshot 2024-11-08 at 6 14 52 PM

**Comment by RashmiKY98** [comment]
All the test cases ran successfully. Looks good! Thanks!
image

**Review by aaryaneil — APPROVED** [review]
All the pages in the webapp work as expected and the tests passed.
Screenshot 2024-11-09 at 4 45 35 AM
Screenshot 2024-11-09 at 4 48 47 AM

**Comment by EvianTan** [comment]
No issue on unit tests or lint. I'll approve and merge it now.
image

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
