### PR TITLE
Hiral Fix edit button on narrow screens

### PR DESCRIPTION
**Pull request by hiralsonip**
# Description
Fixed the edit button on the narrow screen of the project - add task page

## Related PRS (if any):
This frontend PR is related to the dev backend PR.

## Main changes explained:
- Updated the CSS for the edit button, specially for the narrow screen

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin user
5. go to dashboard→Links→Projects→Choose project WBS→Add Task→Edit button

## Screenshots or videos of changes:
Edit_button_narrow_screen

Edit_button_regular_screen

### CODE REVIEW

**Review by KaushikMreddy — DISMISSED** [review]
Hi Hiral, 
The button spacing looks good!

image

**Review by vijay10pk — CHANGES_REQUESTED** [review]
Styling fix for edit button looks good. But when I narrow the screen down the edit option are disappearing when I narrow it down further or in mobile view. I am not sure if that is the expected behaviour.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/e2bc427b-d376-44e0-96c9-766850f1e9c8

**Review by nyelmela — DISMISSED** [review]
I have tested PR 2422 the changes on the current branch by following the steps provided: performed `npm install` and ran the PR locally, cleared site data/cache, logged in as an admin user, navigated to the dashboard, accessed Links, then Projects, chose a project WBS, added a task, and verified the functionality of the edit button on narrow screens. The CSS updates for the edit button work correctly, and everything functions as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/176f48f1-6f7d-4364-b728-de147c18820c

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
The edit button doesn't work after a certain page size.
Please watch the video to get a better Idea.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/607d982a-1ff6-4d71-9995-440c1276a0d2

**Review by cvtqx — DISMISSED** [review]
I've tested  this PR and the edit button looks good on smaller screen sizes. 
One comment: It would be helpful to include a 'before' picture into your description to better understand what the issue with the button was previously. 
I looked at the current version of the site to compare and the updated styling looks good. Good job!

Here is the before picture:

Screenshot 2024-07-06 at 9 45 21 PM

Here is a picture of the new look:

Screenshot 2024-07-06 at 9 37 25 PM

**Review by sahithidhulipala9 — APPROVED** [review]
spacing of button is good!
PR 2422 1
PR 2422

**Review by Kavil-Jain-514 — DISMISSED** [review]
The spacing looks good.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/69308f0c-daab-4154-bef2-81159a80e8c8

**Review by Shadhrush5 — DISMISSED** [review]
I have tested PR 2422 with the following steps:
Took the changes on the current branch, performed npm install and ran the PR locally, cleared site data/cache, logged in as an admin user, navigated to the dashboard, accessed Links, then Projects, chose a project WBS, added a task, and verified the edit button styling for various sizes. The CSS updates for the edit button work correctly, and everything functions as expected. I have attached before and after screenshots for reference.
Before:
Screenshot 2024-07-07 at 8 20 07 AM

After:
Screenshot 2024-07-07 at 8 51 56 AM

One suggestion for future bug fixes and file modifications, please try to avoid the addition of spaces or deletion of existing spaces (unless this time it was done to match formatting on other files, please disregard). It would be easier to see the actual modification made to the file. Great work. Thank you for your time.

**Review by kdaga81 — DISMISSED** [review]
image

The orientation of edit button is working fine with narrow screen

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and it works as expected 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/9f9df6de-0cb7-41e0-9f5d-726748ce1b1a

**Comment by AnujVakil** [comment]
It looks fine for normal as well as narrow screen!
Screen Shot 2024-07-09 at 7 23 22 PM

Screen Shot 2024-07-09 at 7 22 16 PM

**Review by AnujVakil — DISMISSED** [review]
It looks good for normal as well as narrow screen!
PR#2422_1

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
Tested this PR as mentioned in the instructions. The styling of EDIT button is good but when I switch to mobile display, the options under the button disappear. Apart from this, everything looks good.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/64720954-878b-4f5d-94a7-741142516745

**Review by rmcgummadi — DISMISSED** [review]
I have tested PR 2422. The edit button spacing looks good with the narrow dimensions as well. 

Regular Dimensions:
Screenshot 2024-07-11 at 12 31 56 PM

Narrow Dimensions:
Screenshot 2024-07-11 at 12 32 25 PM

**Review by angelalalacheng — DISMISSED** [review]
I test the PR and it performs good in different view. Nice!
Screenshot 2024-07-11 at 9 59 25 PM
Screenshot 2024-07-11 at 9 59 46 PM
Screenshot 2024-07-11 at 10 00 08 PM
Screenshot 2024-07-11 at 10 00 21 PM

**Review by jinxyou — APPROVED** [review]
The button style on narrow screen seems fine, it keeps a consistent style on every size of screen. 
Screenshot 2024-07-13 140433

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected.

https://github.com/user-attachments/assets/1526ff97-f88e-4a51-94f7-7c9518287a24

**Review by DiyaWadhwani — APPROVED** [review]
Hi Hiral,
Great work. I have tested your changes. The buttons are visible on narrowing down the screen. I have attached a video below. 
Thank you

https://github.com/user-attachments/assets/b64f3ac5-88ec-43e3-9833-3e59391473ac

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
