### PR TITLE
Jonathan impl weekly summary color options

### PR DESCRIPTION
**Pull request by jonathancarpena**
# Description
PR #1 (1)
PR #1 (2)

## Main changes explained:
- Added 6 new summary options for the Weekly Summary Options dropdown inside of the Volunteering Tab and Create New User Form (E.g. Required, Not Required, Team Fabulous, Team Marigold, .etc)
- Changed the color of the summaries based on the user's Weekly Summary Option on the Weekly Summaries Reports page.

## How to test:
1. check into `jonathan_impl_weekly_summary_color_options`
2. do `npm install` and `npm run start:local` to run this PR locally

For Current User:
1. log as admin user
2. go to Profile page → Volunteer Times tab → Weekly Summary Options → Change Team
3. logged in as an Admin → Reports → Weekly Summary Reports
4. verify if summary text has changed color to the corresponding Weekly Summary Option

For New User:
1. log as admin user
2. go to Other Links → User Management → Create New User → Weekly Summary Options → Choose a Team
3. go to the _user you created_ Profile page → Volunteer Times tab
4. verify if Weekly Summary Option is the one you selected
5. log in as new user and submit a weekly summary
6. logged in as an Admin → Reports → Weekly Summary Reports
7. verify if summary text has changed color to the corresponding Weekly Summary Option

## Videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/561dc708-e42b-4684-a45c-e4cb3bd9701f

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/c5d25db7-45b0-4401-a714-e353473dd237

### CODE REVIEW

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @jonathancarpena. I have tested your PR and everything is working as intended. Great job!

For current user:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/118b8639-8096-4432-a457-4583896ef533

For new user:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/96ed8608-0563-468d-a044-0cc0c3ce3f4d

**Comment by Jiangwei-shi** [comment]
I have tested it, and everything works as intended.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/66c4d52a-7506-473f-bee1-5f188d60232a

**Comment by one-community** [comment]
This is looking excellent! Please be sure your PR includes these changes applied to the original "Team" option too: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/965 All your colors should do this same thing.

**Comment by one-community** [comment]
Please confirm these options show up here on the New Member setup page too: 
image

**Comment by beblicarl** [comment]
This PR works as intended when you check as a current user and also as a new user. Great work

[summary-color-current-user.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/09e01dbe-d8df-428c-8fa1-4c720f2bfa7b)


[screencast-localhost_3000-2023.07.03-13_10_52.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/c094f8d7-ae0a-4434-b7fa-445e8aa62e5f)

**Comment by jonathancarpena** [comment]
> This PR works for a new user. However, I noticed the weekly summary didn't always change colour for the current user. I am not sure why
> 
>  summary-color-current-user.webm 
>  screencast-localhost_3000-2023.07.03-13_33_59.webm

There was a typo with the Team Luminous so that's why it wasn't updating with that team specifically, but I all the other teams worked. I fixed those changes. Please let me know if everything works now. 😅

**Comment by jonathancarpena** [comment]
> This is looking excellent! Please be sure your PR includes these changes applied to the original "Team" option too: #965 All your colors should do this same thing.

No problem. Just committed new changes with Team option

**Review by tdkent — DISMISSED** [review]
After running local tests I can confirm the PR works as intended. 

Demo of admin account changing weekly summary options from Required to Team Marigold:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/a3b1dd14-853e-47af-84b5-e0856dc0fb77

Demo of admin creating new user account with Weekly Summary Options set to Team Lush. New user then logs in, creates a new summary. Admin account then confirms the correct team color text is displaying.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/9d3ced31-ffdb-4e11-80c0-349082e79faf

Lastly, I also confirmed that Weekly Summary Options were editable for existing users, in addition to new users.

**Comment by Lucas-E** [comment]
Hey @jonathancarpena, great Job! Solve the conflicts so I can move it to final review!

**Review by AaronPersaud — DISMISSED** [review]
Tested it and everything looks good to me!

<b>Test for current user</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/27b20810-bc1a-4b92-81c0-473e74956977

<b> Test for new user </b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/a51b5654-8462-47d7-aa8c-d032cdad37dd

**Review by BaileyM96 — DISMISSED** [review]
Great job on getting the summary colors implemented Jonathan!

I have performed tests through both the admin profile and user profiles, everything functioned as expected and ran into no problems testing this feature. I was able to confirm that all color variations are displaying correctly on both interfaces.


[Weekly Summary color options test.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/ed503884-b05a-4d52-b720-50b3a999b2ec)

**Review by yaow62023 — DISMISSED** [review]
The first feature I tested, is change the team color. The weekly summary color change with the team color. For more detail, see the video below. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/d9761c11-8f6b-4b14-8804-7ceb7a7297a6

The second the feature is for create a new user and assign a team color for the new user. At admin site, the color of weekly summary match with the team color. For more detail see the video below. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/ca372fa5-c8c7-4e0c-9986-86099fee2093

**Comment by AnishPandita** [comment]
Hi @jonathancarpena I tested the PR and it works great.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/031103cd-3e1b-4c09-b7b4-9642c021657f

**Comment by luisarevalo21** [comment]
Hello onathancarpena,

I tested the PR and every works as intended. Great job!

### Changing the team color for the admin, changed to different colors works as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/68bfd876-1d24-4c2e-b30f-565e0f89222a

### creating new user's weekly summary report
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/45a6eabf-3309-4f84-9791-8392ec575d8b

### confirmed user's weekly summary changed color
set the color of the new user to violet and confirmed it.

Screenshot 2023-07-06 at 9 21 51 PM

**Review by luisarevalo21 — APPROVED** [review]

**Review by ramyaram2092 — CHANGES_REQUESTED** [review]
@jonathancarpena  I am unable to view the newly added weekly summary  for any  newly created user in Reports-> Weekly Summaries Report  screen

**Existing Users :**
I tried changing the summary color for users whose summary report is  already present  .  The  functionality works as expected for existing users

**New Users:**
 However I couldn't do the same for newly created admin/ volunteer users 
**Name of the new users:**
**Administrator**: ramya testadmin
**Volunteer**: test 970

 Could you check the latest from this branch and confirm ?

**Review by NidaZaki — COMMENTED** [review]
Works as intended!

**Comment by one-community** [comment]
> The weekly summary color change with the team color. For more detail, see the video below.

I don't see this as successful in your video:

image

**Comment by jonathancarpena** [comment]
> @jonathancarpena I am unable to view the newly added weekly summary for any newly created user in Reports-> Weekly Summaries Report screen
> 
> **Existing Users :** I tried changing the summary color for users whose summary report is already present . The functionality works as expected for existing users
> 
> **New Users:** However I couldn't do the same for newly created admin/ volunteer users **Name of the new users:** **Administrator**: ramya testadmin **Volunteer**: test 970
> 
> Could you check the latest from this branch and confirm ?

I checked both users **ramya testadmin** and **test 970**  and neither of them even had a weekly summary submitted so it will always appear as Not Provided in red. Can you verify it after you have completed the steps of submitting the weekly summaries?

I retested the branch and recorded the whole process of creating a new volunteer, submitting a weekly summary report, and changing the weekly summary option as an Admin user

This video: 
Create User -> Change Weekly Summary Option -> Submit Weekly Summary -> Check if color has changed

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/5ae28411-eeb3-4026-9fca-864842f9e141


This video:
Change Week Summary Option Again -> Check if color has changed

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/35af470c-f606-4d48-95c9-b4ff2b342864

**Comment by jonathancarpena** [comment]
> > The weekly summary color change with the team color. For more detail, see the video below.
> 
> I don't see this as successful in your video:
> 
> image

I believe the users are not loading fast enough that's why it appeared white. The user fetching function definitely needs some optimizing. 😅

**Comment by ramyaram2092** [comment]
> 

Correct @jonathancarpena.  I  type and submit the  weeekly summary for  ramya testadmin. It shows in the profile that I have submitted my weekly summary. It doesnt come up in the  Summary report.  I am not sure if I am missing any step .

I just did the above in the dev environment 

**Screenshot of the weekly summary showing up in the profile** 
image

**Screenshot from the Weekly summary report** 
image

**Review by xaanders — APPROVED** [review]
Hi Jonathan! I've tested your PR and everything works as intended! 
The video of testing with existing user: 
[existing-user.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/d27e2926-ccd9-4da5-88b6-f254ceee075c)

And a new user, I poused a video couple times to make it shorter a little, but everything good from admin account and newly created one: 

[new-user.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/a9337c93-9f87-4f92-b430-0fb3e8507ae7)

**Comment by jonathancarpena** [comment]
> Correct @jonathancarpena. I type and submit the weeekly summary for ramya testadmin. It shows in the profile that I have submitted my weekly summary. It doesnt come up in the Summary report. I am not sure if I am missing any step .
> 
> I just did the above in the dev environment
> 
> **Screenshot of the weekly summary showing up in the profile** image
> 
> **Screenshot from the Weekly summary report** image

@ramyaram2092 I believe those are different weeks.

**Comment by AriaYu927** [comment]
Hi Jonathan, I've tested this PR and it works as expected.

Existing user:
current_user_color
current_user_summary

new added user:
new_user_color
new_user_summary

**Comment by AriaYu927** [comment]
> > 
> 
> Correct @jonathancarpena. I type and submit the weeekly summary for ramya testadmin. It shows in the profile that I have submitted my weekly summary. It doesnt come up in the Summary report. I am not sure if I am missing any step .
> 
> I just did the above in the dev environment
> 
> **Screenshot of the weekly summary showing up in the profile** image
> 
> **Screenshot from the Weekly summary report** image

Hi @ramyaram2092 , I can see your weekly summary shown in yellow color in the report page. It looks like you submitted This Week summary but took a screenshot of Last Week summary.
截屏2023-07-12 13 44 54
截屏2023-07-12 13 45 36

**Comment by one-community** [comment]
> This is looking excellent! Please be sure your PR includes these changes applied to the original "Team" option too: #965 All your colors should do this same thing.

image

**Comment by jonathancarpena** [comment]
> > This is looking excellent! Please be sure your PR includes these changes applied to the original "Team" option too: #965 All your colors should do this same thing.
> 
> image

@one-community Updated with the color change. 👍

PR #970 - Changes (2)

PR #970 - Changes (1)

**Review by ramyaram2092 — APPROVED** [review]
Hello @jonathancarpena 
My bad that was an error from my side. Just to be sure I retested  the PR today. The functionality works as expected. Approving the PR on the same note

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/8893c931-79b7-4f53-a291-d1a0846f16ef

**Comment by one-community** [comment]
Merging this one because it is Urgent and already has two approvals from two members of the PR Review Leadership Team

**Comment by one-community** [comment]
Great job everyone, thank you!

**Pull request merged**
