### PR TITLE
Hoang fix page reload on wbs item click

### PR DESCRIPTION
**Pull request by kylepham**
# Description

Screenshot 2024-04-21 at 2 43 24 PM

## Video showing this issue
[Video link](https://drive.google.com/file/d/1Rf4kWrPiOyfP6velJV5tdsb4QRJVyCzN/view?usp=sharing)

## Related PRS (if any):
Latest backend dev branch

## Main changes explained:
- Change from `<a>` tag to `<Link>` tag to prevent page reload

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. Start the timer if it stops
6. Go to Other Links → Projects
7. Choose any project and click on WBS
8. Choose any WBS item in the list
9. Verify that the timer doesn't stop like in the video above
10. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/43fcc324-606a-4c76-9642-f57eda390ac4

## Note:
None

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
Timer doesn't stop and I no longer see "Timer has paused" alert. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/eca54e59-dadc-4f04-81b0-05aff90e6797

**Review by MinSun0814 — APPROVED** [review]
I was able to replicate the bug.
Old:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/e6f68b22-ba28-464b-a773-a524034c9370

New:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/54ca01ed-d5d1-43a5-8d3a-6f70fdb32b9d

Timer no longer pauses when clicking on WBS. Works as intended.

**Review by dkt6 — APPROVED** [review]
LGTM
The 'Timer has paused' issue no longer occurs when navigating pages. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/168319518/4a0155fd-559f-4660-a4ff-df3ff3154632

**Review by peter6866 — APPROVED** [review]
Changes work as expected! 
[Screen cast](https://www.loom.com/share/a525c3878e604a6b853475023d32cfa8?sid=d792cf1b-e426-4a68-9bff-c0fac56fe9f6)

**Comment by kylepham** [comment]
@one-community This issue has been fixed on the `development` branch. Please see the video below and consider closing this PR. Thank you.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/efd78b07-8f08-4e6e-b446-80ae30a04ef8

**Comment by one-community** [comment]
> @one-community This issue has been fixed on the `development` branch. Please see the video below and consider closing this PR. Thank you.
> 
>  Screen.Recording.2024-06-03.at.1.52.30.PM.mov

It was hard to reproduce for some people. So I think we still need this.

**Comment by kylepham** [comment]
@one-community the code changes that I have made overlapped with existing code, so I believe the issue has been fixed.

**Pull request closed without merging**
