### PR TITLE
Fix the CountDownTimer component layout

### PR DESCRIPTION
**Pull request by nicollext**
# Description

image

## Mainly changes explained:

At the BadgeReport component, a span tag was mistakenly applied globally instead of being intended for another component (UserProfile) where it was meant to be applied.
I deleted this global span tag and will open another PR to fix the bug that it was intend to fix at UserProfile component.

## How to test:
check into current branch
do `npm install` and `...` to run this PR locally
log as any user
go to dashboard

## Screenshots or videos of changes:
 
**Before** 

https://user-images.githubusercontent.com/101591708/229664566-329eb1fa-471b-4c36-992d-d8b4771ebd9d.MP4

**After**

https://user-images.githubusercontent.com/101591708/229664579-488139fb-d319-469c-8718-1f86e88d97a1.MP4

### CODE REVIEW

**Review by ToobaJamal — DISMISSED** [review]
Hi Nicolle, I have tested the changes you made and these are working as expected. 

Before
#750_before

After
#750_after

**Review by vitorsaa2k — APPROVED** [review]
Works completely fine!
Before:
image

After: 
image

just remember to not add the package-lock.json file on your commits.

**Comment by LucileTech** [comment]
Hi @nicollext, It works well good catch 

before
Screenshot 2023-04-04 at 17 42 14

after
Screenshot 2023-04-04 at 17 40 53

**Review by LucileTech — APPROVED** [review]
I tested it and it works as explain.

**Comment by one-community** [comment]
Thank you all, moving to final review...

**Comment by one-community** [comment]
Branch conflicts need to be fixed here

**Pull request merged**
