### PR TITLE
Akshit fix map remove option for users

### PR DESCRIPTION
**Pull request by akshit0211**
# Description

Screenshot 2024-07-30 at 10 26 19 PM

Screenshot 2024-07-30 at 10 26 55 PM

## Related PRS (if any):
This frontend PR is related to the development backend.

## Main changes explained:
Made changes in these files:
src/components/TeamLocations/ListUsersPopUp.jsx
src/components/TeamLocations/MarkerPopup.jsx

## How to test:
1. Check into the current branch.
2. Do `npm install` and `...` to run this PR locally.
3. Clear site data/cache.
4. Login as owner user.
5. Go to Reports→ Team Locations
6. Click on individual points and verify that you can see the remove option for all users. Also, verify the same for the user list.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/b415549b-36f8-4fb9-9e2d-9d1bfc8b50f8

### CODE REVIEW

**Comment by Gmon-k** [comment]
I have tested from my side, it is working correctly, below are the screenshot for it

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected.

https://github.com/user-attachments/assets/ca8a2d93-4377-49fd-971c-34767fbf2e4a

**Review by kdaga81 — APPROVED** [review]
image
image

Remove option available in both user and user list

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

**Review by Pranay-ai — APPROVED** [review]
Hey @akshit0211 
i have reviewed the PR , The functionality is working as expected and the delete options is available
image
image

Thank You.

**Review by manikittu810 — APPROVED** [review]
Hello @akshit0211 
Followed the above mentioned steps, everything works fine and as mentioned . Below iis the screenshot.

Screenshot 2024-08-03 at 5 05 48 PM


Thank you.

**Review by Annezhang673 — COMMENTED** [review]
I logged in as Admin but I could not see the remove option for users. Could be an issue on my end. Below are the screenshots. 
Screen Shot 2024-08-04 at 12 09 49 PM
PR2519

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and it works as expected. 

Screenshot 2024-08-06 165031
Screenshot 2024-08-06 165113

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
