### PR TITLE
XiaoW_new timer refactor

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
This is the refactored new timer frontend, and the related components were based on PR [#1021](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1021#issue-1811282749). 
The new timer is based on Websocket connection communication and it is a count down timer instead of stop watch timer like the old timer.

## Related PRS (if any):
This frontend PR is related to the [#575](https://github.com/OneCommunityGlobal/HGNRest/pull/575#issue-1948845268) backend PR.
To test this frontend PR you need to checkout the  [#575](https://github.com/OneCommunityGlobal/HGNRest/pull/575#issue-1948845268) backend PR.

## How to test:
1. check into current branch
2. check into backend branch
3. do `npm install` and `npm run start:local` to run this PR locally
4. log as any role
5. go to dashboard
6. verify function the new timer is working as intended (set/add/remove goal, start, pause, stop and log time...), try to break it.

## Note:
1. The time range it can be set is between 15mins and 10 hours. 
2. Refresh will cause the Websocket connection to close, which would lead to a forced pause action
3. Be aware of browser memory saver (may kick in after 2 hours of inactive for chrome), the timer is designed to pause and keep the elapsed time when Websocket connection is lost.

## Updates:
1. After discussing with Jae, the time range now is 1 min to 5 hours;
2. the alignment issue is fixed.
3. the gong audio now stops after TimeIsOverModal is closed
4. Part of the UI changes.

### CODE REVIEW

**Review by navneeeth — DISMISSED** [review]
Hello, @wang9hu! I tested the new timer you have implemented and found no issues. Great work!
Tried setting, adding, and removing a goal and start, pause, stop, and log time. Even the popup after the timer completes to either log the time or to add more time works as expected. The responsiveness for other screens is good. The check for minimum time set as 15 minutes works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/c15fe7da-7a6e-4812-953a-1f588cf5eaa6

Also tested the functionality on page refresh and as mentioned in the Note in the Description, the forced pause action works as expected. The check for the max time range to be 10 hours works as intended too.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/e3434d41-c7d2-4533-8816-fbb750e9aacb

No issues that I could see from my testing. Great job!

**Review by StrawberryCalpico — APPROVED** [review]
I tested your PR. The timer works as intended!( add, stop, reset, time range...)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/e527ad49-6361-4ceb-a1a4-aa405e81a6cb

**Review by lacnoskillz — DISMISSED** [review]
Hello @wang9hu !
I pulled both front and back end codes and tested the new timer.
It seems to work fine! I tried to break it with no luck. Nice work
NOTE ## I would just work on making it more responsive in mobile viewports as we CANT access the drop down menu

Vid test:

[Untitled_ Oct 18, 2023 5_34 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/e37f4266-3047-4d76-914d-476cf41a2b16)

also refresh seems to work too!
image

**Review by malikjahanzaib — APPROVED** [review]
Hi @wang9hu, I have reviewed this PR and all the functionalities of the new timer seem to work perfectly and is responsive too. Below is my test recording. Great work!!!

Test rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/4d864264-873d-4044-904a-0c85dec9b21f

**Review by dah00 — APPROVED** [review]
Hey, I tested your PR and the new timer is working as expected. The timer is paused when page is refreshed, all the buttons work fine. I played around with it and tried to break it, but everything is functioning properly. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/3632782d-b4e5-4a5c-8136-3ff439af0366

**Review by cvtqx — CHANGES_REQUESTED** [review]
The new timer looks fantastic and works as described!

Checking functionality: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/cc5124d5-1663-439e-9297-58c8d8828de6

Checking responsiveness:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/12ad5c9b-6a44-4f18-9388-2a3a382ad177

There is a little vertical misalignment with the clock and hours-minutes-seconds. But its not a big deal. See picture below:

alignment


And I loved the gong sound when time is complete. However, when I clicked on add more time in the modal, the time was added but the gong sound continued and no way to stop it other than refresh the page.

Screen Shot 2023-10-18 at 9 47 38 PM

**Comment by wang9hu** [comment]
>  NOTE ## I would just work on making it more responsive in mobile viewports as we CANT access the drop down menu

 @lacnoskillz Noted, I will see what I can do, thanks for the review!

**Comment by wang9hu** [comment]
@cvtqx Thanks for reviewing my PR!


> There is a little vertical misalignment with the clock and hours-minutes-seconds. But its not a big deal. 

Those two icons are imported from react-icons, and the icons have the same width and height, but the position of what is inside of the image might be out of our control.


> And I loved the gong sound when time is complete. However, when I clicked on add more time in the modal, the time was added but the gong sound continued and no way to stop it other than refresh the page.

Great catch! I will fix that in the next commit.

**Review by Shubhu0 — DISMISSED** [review]
Hi, @wang9hu Tested the PR and it is working as intended. The new clock is excellent, and all its features, adding time, resetting it, and setting daily goals all work as required! Great job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/494a5d92-8e7d-433f-a80e-df127e180385

**Review by eduhorta — COMMENTED** [review]
Hey @wang9hu!

The new timer looks really good! Great job! 👍 

I have dome some testing and everything seems to be working.

Here is a video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/a43a7953-0230-4122-a059-42752c47fed0

There is some horizontal misalignment (blue line) between the buttons and the gap between them also needs some adjustment (green line)

Screenshot 2023-10-19 at 14 15 44

Last thing as mentioned by @cvtqx 

When you add time after the clock runs out the gong sound continues.

Congratulations on implementing this feature!

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Just as everyone else stated, the gong keeps once I've let the timer finish and try to add more time. Afterwards, even after stopping the timer to log the time, the gong still continues.

I also notice the alignment issue in the timer
pr1282 minus button not vertically aligned

Other than that, all the web socket communications check out:
pr1282 web socket comm handles add and remove time
pr1282 web socket communication works and submits time properly

Time is detected properly when finished:
pr1282 detects time done


Love the look of the new timer with the green/blue loading feature. Looks super slick. I know this thing has been a real beast, so great job on everything. I'm usually pretty good at breaking things or finding ways to fail a PR functionality wise, but this new timer seems to be quite bulletproof. 

Task list:
 - fix the gong so it resets properly
 - fix the alignment issues on the buttons ( if you don't feel like doing it yourself, just shoot me a message and I'll do it. I know you're probably burnt out on this thing).
 
p.s. since nobody has mentioned it yet, the old timer is still there 🤨

**Review by jerryren527 — CHANGES_REQUESTED** [review]
Hello @wang9hu !

This was a fun PR to test. Your code changes achieve the following:

✅ Page refresh while timer is running causes timer to pause, and Timer Paused modal appears. Elapsed time remains the same. 
✅ Page refresh while timer is paused, timer remains paused, no Timer Paused modal.  Elapsed time remains the same.
✅ ‘Goal time cannot be set over 10 hours!’ warning message appears whenever user attempts to set goal to over 10 hours.
✅ ‘Remaining time is already less than 15 minutes!’ Warning message appears whenever user attempts to set goal less than 15 minutes.
✅ Timer modal’s add/subtract time buttons are correctly disabled and enabled according to current goal.
✅ Reset Time button accurately resets time to last known goal.
✅ ‘You need at least 1 minute to log time!’ Modal appears when elapsed time is under 1 minute.
✅ When elapsed time is at least 1 minute, ‘Add Tangible Time Entry’ modal appears.

However, I came across a potential bug. Please try to reproduce the following and consider addressing it if necessary:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/fd4f6aa6-e23e-46e6-94df-90d986471128

- When adding a tangible time entry, the time entry is successfully added, but it freezes the app in localhost and I must refresh the page. I get this uncaught error in my browser’s console:

Screenshot 2023-10-19 at 3 33 38 PM

And this error in my backend console:

Screenshot 2023-10-19 at 3 35 06 PM

Please let me know if this bug is reproducible and needs fixing! Great job!

**Review by tsunami776 — COMMENTED** [review]
Hi @wang9hu, the new timer looks awesome! I like the circular and horizontal progress bar that clearly shows what percentage of planned work has been done. Adding and subtracting time from the timer works as intended. Time won't be added and Toast will pop up when time is below zero and above 10 hours. 

Pause and stop buttons work as intended. Pause will save the working time and refresh the page will not reset the timer. Stop button also works as the old timer, which pops up modal that prompts user to put a description to save the work.

Minor things could be improved:
1. As suggested above reviewers, the sound will continue to play if user wants to add more time after the time is up
2. As others pointed out, the subtracting button is not aligned with other buttons
3. There could be a reset button to reset the timer

Alignment:
CleanShot 2023-10-19 at 14 00 08

Add and subtracting work as intended:
CleanShot 2023-10-19 at 13 59 49
CleanShot 2023-10-19 at 13 58 59


Test video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/f0af2d32-42e0-4e63-a258-5e50ccb3deaf

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Left a comment on BE [#575](https://github.com/OneCommunityGlobal/HGNRest/pull/575).

**Review by vikrambadhan — CHANGES_REQUESTED** [review]
Hi, I tested your PR and I am getting an error while running the FE and BE. 

week 8 - PR1 (1)

Week8 - PR 1

**Review by LucileTech — DISMISSED** [review]
Nice work, this new timer is looking good!

It started at 15min as default. The countdown is working as intended. (I would have liked a clear button)


Screenshot 2023-10-20 at 08 29 20
Screenshot 2023-10-20 at 08 32 12

If 'add more time' is clicked, and time is added, the sound continues anyway. It stops when the page is refreshed.

Screenshot 2023-10-20 at 08 47 55



If 'log time' is clicked, it is working well and logging time.


Screenshot 2023-10-20 at 09 16 46



When back on the home page, the timer is set up as the last count-down-time.

Screenshot 2023-10-20 at 09 18 09


When the page is refreshed during the count down, I receive this alert:

Screenshot 2023-10-20 at 08 50 50

**Comment by wang9hu** [comment]
> Hi, I tested your PR and I am getting an error while running the FE and BE.

@vikrambadhan Thanks for your review, you need to run `npm install` before starting the app on both front and back ends.

**Review by BaileyM96 — DISMISSED** [review]
Good morning @wang9hu I went ahead tested the new timer feature and I am ready to approve these changes. The new timer works as described in the directions and I feel is ready to be used.

## Video Walkthroughs

Add time, decrement time, showed elapsed time, pause, reset and start time.

[PR #1282 Add time, decrement time, showed elapsed time, pause, reset, start time_.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/38eeeadb-c6b3-43e7-a092-8039863485f3)

Set goal, start timer, pause timer, refresh page message.

[PR #1282 new timer refactor_ set goal, start timer, pause timer, refresh page message_.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/ce9b101e-2ed0-4262-a846-1a2a5f2312ee)

Stop timer and log time for account.

[PR #1282 Stop time in and out of menu, log time for the profile_.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/0ba4ae94-ec53-4ba3-80cb-5a7fa26018a2)

## Final Thoughts

There is quite  a few UI features that can improved or changed for the time clock, but I didn't feel like that was a reason to not approve this feature since it works as intended. I will include some screenshots to show what I think can be improved for it in the future.

## Screenshots

When timer is active I see that the UI is updated to say working, I was confused for a little thinking that something was supposed to be loading there but it just seems to be text. I think we should remove it since its not really providing anything to the timer or the user and if we remove it, it would allow more space and not be so cramped.

Working text is confusing

I saw that another developer commented on this but I will include it as well, but the minutes and seconds do not align with each other. Maybe put some padding on the words Minutes and seconds but im not sure if that would help.
 
Minutes, Seconds does not align with text and numbers

**Review by Bhagyashree444 — COMMENTED** [review]
Excellent work! The timer functions seamlessly. However, there's a minor issue with the sound persisting after the goal completion, even when additional time is added.

In the new timer, I can successfully set, add, remove goals, and perform standard actions like start, pause, stop, and log time. The time range is thoughtfully restricted to 15 minutes to 10 hours, with alerts to prevent exceeding this range. Additionally, hitting the refresh button initiates a forced pause action, ensuring a smooth user experience.

Furthermore, the app's responsiveness across various screens is highly commendable.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/41186831/08782a44-29e2-4b03-bd7f-ca1a48e7203e

**Review by savio-henrique — CHANGES_REQUESTED** [review]
Hi @wang9hu , I've tested your PR's, FE and BE, great work on the new timer! Seems to be working as intended only for some bugs and little details that others have mentioned and I'm mentioning them here too.

---
### About the timer

The timer itself looks great! The aesthetics and looks are great, only afeccted by the little misalignment on those buttons:
image

The max and min goal restraints are working as intended, as the pausing, forced pause by reloading and the responsiveness are working out too!
Here's the testing of those:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/e34c1959-7d9c-4ac8-855d-ca9b4b875595

forced_pause

---
Seems that when the timer can't connect to the timer service this message appears, if it is to be intended, is working well!
timer-service-failed

---
## Changes needed

* When the time is finished, a gong sound plays (great feature!), but it doesn't stop if you add more time or log the time, only by reloading the page.
* The timer doesn't pause or stop when logging the hours after pressing the stop button, going on while logging the time, it only stops when the form is submitted.

---

Other than those little tweaks, I think that the new timer is pretty great! Good work on this PR! Congrats!

**Comment by emunkh404** [comment]
Tested the new timer feature, ready to approve. It works as described and looks great. PR tested and working as intended. The new clock is excellent, all features are functional. Great job!
image
image

**Review by ChirayuRai — DISMISSED** [review]
I tested your frontend and backend PRs, and everything seems to be working as intended! All the functionality for adding and subtracting time is working, as well as pausing and ending time. Reloading the page also works, meaning potential interruptions won't mess with things! Now I just wonder if pushing an update to the live site would reset the timer progress as it did before...

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/805cd923-f4ca-463f-9b92-d9b26e4f5a07

**Comment by RheaWu1212** [comment]
Hi it works as expected:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/6640ef37-d1eb-49ae-8966-16797d305c45

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, no error append at this branch. Check the video below for details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/0058c2b8-2e1e-4330-9bc2-c6e33c7f459a

**Comment by palakgosalia** [comment]
Hey, I have reviewed and tested the PR and it worked fine for me. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/1762c092-7531-49e9-835d-e14f95379f47

**Comment by wang9hu** [comment]
> * The timer doesn't pause or stop when logging the hours after pressing the stop button, going on while logging the time, it only stops when the form is submitted.


Thank you @savio-henrique for your detailed review! 

Regarding your second requested change, after checking with Jae, it is intentional to let the timer keep running before the form is submitted. 

Other changes will reflect in the next commit.

**Pull request merged**
