### PR TITLE
Lawrence - Hide sensitive data

### PR DESCRIPTION
**Pull request by lchua2314**
# Description

Task desc

## Main changes explained:
- Hide hardcoded login credentials using the .env file for creating a new user.

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. log as admin user
4. go to Other Links→ User Management
5. press Create New User button and create a new user
6. verify that the user is created successfully which means the environment variable was used successfully.

## Screenshots or videos of changes:
Screenshot (2828)

## Note:
Your .env should already have the environment variable "REACT_APP_DEF_PWD" so there's nothing in the .env file that's needed to be changed for this PR.

### CODE REVIEW

**Review by joyceiphone — APPROVED** [review]
LGTM.

**Review by luisarevalo21 — APPROVED** [review]
Hello @lchua2314,

I tested your PR and works as intended great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/133d9250-f1d3-4fb8-a132-a18b49d9cf3b

**Review by mahamakhan — APPROVED** [review]
The user gets created successfully as mentioned. 
image

**Review by igorrochadasilva — APPROVED** [review]
Hi @lchua2314 !
I hope you are well =D

I tested your PR and works as intended great job!
1020_01_create-user

1020_02_created-user

**Review by xaanders — APPROVED** [review]
Hi! Works good. I could create and login in new account.

**Comment by eduvarjaor** [comment]
There are 4  approvals here.

@OneCommunityGlobal

**Comment by iTvX** [comment]
I have tested your PR, and it looks good. I can create a new user.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/83ab5cd7-6a80-456c-82b5-03271f446657

**Review by BaileyM96 — APPROVED** [review]
Everything works great good job!

## Video

[PR #1020 Sensitive Data.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/46367a6a-650a-4ea0-b973-92260546fc2a)

**Review by freecode23 — APPROVED** [review]
1. Logged in as admin, created new user SherlyPR1020 
2. Logged in as the new user with new password
Screenshot 2023-07-19 at 8 04 54 PM

**Review by ramyaram2092 — APPROVED** [review]
Create user functionality works as expected . No issues

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/6f6a11ff-c2b5-401c-8ffe-a91f7c1204aa

**Comment by AnishPandita** [comment]
Hey @lchua2314 I tested the PR and it works as described. I was able to create a new user and log in.
Screenshot 2023-07-19 at 7 30 08 PM
Screenshot 2023-07-19 at 7 31 48 PM

**Review by AaronPersaud — APPROVED** [review]
Hi, I've tested it and it works perfectly!

<b>Creating new user and logging in with default password</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/5730dee6-c4f1-41d0-b4fb-d8d0d7cec8fb

(my laptop was lagging, so the vid is a bit long)

- new user created successfully
- logging in with default password successfully
- changing password 
- logging in with new password successfully

Nice job!

**Review by HectorAgudelo — APPROVED** [review]
This PR works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/39d2c9d9-9b19-49c5-b8df-3488beb66366

**Review by n0vay — APPROVED** [review]
Great Job, works as intended.

**Comment by Shreyj14** [comment]
Great! Works as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/c7830f47-ba79-418b-8561-70fa52568800

**Review by eduvarjaor — APPROVED** [review]
Hi @lchua2314  

I tested this PR and everything it's OK! Nice job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/fcc98bf0-f3dc-405d-bf8d-d0704f9dc422

**Review by shiva2096 — APPROVED** [review]
Hi @lchua2314 

Great work! The functionality is working as expected without any issues.

Screenshot 2023-07-21 at 8 04 10 PM

Screenshot 2023-07-21 at 8 04 38 PM

**Review by yurisokolovicz — APPROVED** [review]
The modifications appear to be working fine. Good job! Check the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/da20652c-2306-479e-b0f8-dda35548e31a

**Comment by winghojackyli** [comment]
The PR works perfectly. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/39914b37-655a-468d-b8ae-c7a6e4fe9d38

**Review by winghojackyli — APPROVED** [review]
The PR works perfectly. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/39914b37-655a-468d-b8ae-c7a6e4fe9d38

**Review by yaow62023 — APPROVED** [review]
All functions are tested. I can create new users and log in.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/8f7832c7-a8df-4572-a401-021f45ab3efa

**Pull request merged**
