### PR TITLE
Shiwani Unit Test for CurrentPromptModal

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/WeeklySummary/CurrentPromptModal` 

## Main changes explained:
- Added new file CurrentPromptModal.test.js
- Added 6 test cases: render component without crashing, check view and copy current AI prompt button, check tooltip associated with the button, check current AI prompt modal content, check close modal button, check copy button inside the modal 

## How to test:
1. check into current branch
2. do `npm test src/__tests__/CurrentPromptModal.test.js`
3. check if all the test cases pass

## Screenshots or videos of changes:
Screenshot 2023-11-27 at 7 04 37 PM

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed and the test cases are good. Great work

image

**Review by beblicarl — APPROVED** [review]

**Review by sucheta90 — APPROVED** [review]
All test cases passed in the local environment. 
pr#1595_test_passed

**Review by ZichanYang324 — APPROVED** [review]
I did the test and all the test cases have passed as the resulting pic shows below. 
PR1595

**Review by ChengyanOo — APPROVED** [review]
@Shiwani99,

I'm happy to report that all the tests have successfully passed. This is a great achievement and reflects well on the quality of the work. Keep up the excellent effort!

Screenshot 2024-01-09 at 15 38 10

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by bajajtushar094 — APPROVED** [review]
All test cases passed. Thanks. 
Screenshot 2024-01-10 at 23 02 21

**Review by ramyaram2092 — COMMENTED** [review]
Hello Shiwani great job on the test cases !
Kindly  update the test case path ! Other than that everything looks good

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 23 - PR6

**Review by 666saofeng — APPROVED** [review]
Hi, All tests passed and it worked as intended.
image

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and worked as expected.

Captura de tela 2024-02-18 042617

**Review by YHX6 — APPROVED** [review]
All tests passed.
Screenshot 2024-03-09 at 5 56 43 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
