### PR TITLE
Dhrumil-White-Screen_Fix-Featured-Badge_Save-Issue

### PR DESCRIPTION
**Pull request by ddshah878**
# Description
image

## Related PRS (if any):
Related PR: [PR #2569](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2569)
…

## Main changes explained:
Selecting any badge as featured and saving changes works without issues, the white screen error is fixed, and all changes are successfully saved.

## How to test:
1. Check into the current branch
2. Do npm install and ... to run this PR locally
3. Clear site data/cache
4. log as admin/owner
5. Go to View Profile → Select Featured
6. Check save changes button is working

## Screenshots or videos of changes:
Before: - https://www.loom.com/share/2c402e5468904cfbbd2c9fa8d971674b?sid=f44b0535-96c0-4e54-a370-3ae8495d0e81
After: -
https://github.com/user-attachments/assets/4066b899-5afc-4b80-a04c-991fec138ad1

Note:
If you don't have badges, please add them using the Assign Badges button next to the Select Featured button.

### CODE REVIEW

**Review by CodewithKoushica — CHANGES_REQUESTED** [review]
The feature works smoothly, and the white screen issue is resolved effectively.

One small improvement: consider adding a success message after saving. This would confirm to users that their featured badge selection has been saved, enhancing the overall user experience.


https://github.com/user-attachments/assets/1d476306-8740-437a-b747-d08f879db0be

**Review by CodewithKoushica — APPROVED** [review]

**Review by samarth9201 — DISMISSED** [review]
Verified that the changes work as expected.

Screenshot (183)
Screenshot (184)

**Review by anirudhsk2107 — APPROVED** [review]
the changes are working 
Screen Shot 2024-10-29 at 11 19 49 PM
Screen Shot 2024-10-29 at 11 18 54 PM
Screen Shot 2024-10-29 at 11 19 27 PM

**Review by hqzhu0913 — CHANGES_REQUESTED** [review]
The selected feature works as explained. But I find in the dark mode, the column names are not visible when not hovering. And the second thing is that if the comment is not an explaination, please remove them. Improve code cleanness and readability.
Screenshot 2024-10-29 at 10 56 59 PM
Screenshot 2024-10-29 at 10 57 19 PM

**Review by nikhilgiri0226 — COMMENTED** [review]
I have reviewed the PR and everything is working fine. When we select any badge as featured and save changes. No white screen glitch was there.

Kindly refer the video below.


https://github.com/user-attachments/assets/299a01f4-f096-4407-976f-3805e08fb13e

**Review by Jingyii800 — DISMISSED** [review]
I have tested this feature. There's no glitch when featuring the badges. But the column name are invisible in dark mode and only can be seen when hovering on it.
image

**Review by varun-elango — APPROVED** [review]
The changes look good and the white screen issue is resolved. I did observe that column names are not visible in dark mode but that is not in the scope of this PR.
PR 2825_1
PR2825_2

**Comment by RashmiKY98** [comment]
Checked the functionality and is working fine. Tested the same with different web page dimensions and different browser. Tested in dark mode as well. The column names are visible in the dark mode. No issues found. 

Screenshot 2024-11-03 003503
Screenshot 2024-11-03 003311
Screenshot 2024-11-03 003001

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and didn't encounter the white screen issue. Good work.

https://github.com/user-attachments/assets/90d0d86d-9241-48fb-98dc-16e24e726496

**Review by Muhideenthegreat — DISMISSED** [review]
Verifications:

- Export button is disabled when no badges are featured
- When badges are selected as featured, it saves without going to a white screen. Bug fixed!
Screenshot 2024-11-07 at 12 12 25 PM
Screenshot 2024-11-07 at 12 11 28 PM
Screenshot 2024-11-07 at 12 11 44 PM

Suggestions:
- When changes are made, a message could be displayed to show if the task is successful / unsuccessful / not authorized

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/a50b88c3-c16a-463a-86a2-93b3f2970aac

**Review by vijay10pk — APPROVED** [review]
All the changes are working as expected.
Screenshot 2024-11-07 at 10 09 42 PM
Screenshot 2024-11-07 at 10 09 30 PM
Screenshot 2024-11-07 at 10 09 13 PM

**Review by AshritaCherlapally — APPROVED** [review]
Changes are working as expected, able to select and assign badges, after selecting the page does shows a alert message. Code changes are working perfectly fine.


https://github.com/user-attachments/assets/6585e038-3888-4f93-804d-d6f70302a971

**Pull request merged**
