### PR TITLE
Fixing all button to expand all tasks

### PR DESCRIPTION
**Pull request by crystalsong2021**
### **Description**
--------------------------------------------------------------

This PR is regarding issue # 7  - "All" button doesn't open all folders in the WBS. This issues are listed below what the user encounter.

- Dashboard→ Other Links → Projects → AAA USE THIS PROJECT → WBS Icon → Jae's WBS - USE THIS → click the “All” button → then click and reclick some of the top open folders and you’ll see they aren’t actually opening to show their full contents

- I’m also having issues on the Main where I can’t open a folder without using the “all” button. Can’t reproduce on the Dev though… so hoping fixing “a” above will fix this too. 

### **Related PRS (if any):**
--------------------------------------------------------------
None

### **Mainly changes explained:**
--------------------------------------------------------------

1. update the open folder state to reflect the changes using useEffect hooks
2. split the fetching of tasks into 2 states. (fetch only the parent task to reduce the latency and the second is to load all tasks which takes longer)
3. adding loading spinner to improve the UI while loading

### How to test:
--------------------------------------------------------------
Check into the current branch
Do npm install and ... to run this PR locally
Log in as an admin user
Dashboard→ Other Links → Projects → AAA USE THIS PROJECT → WBS Icon → Jae's WBS - USE THIS → click the “Expand All” button 
check all the tasks are being displayed correctly
click "collapse All" button to see the parent tasks are being display

### Screenshots or videos of changes:
-----------------------------------------------------------------

https://user-images.githubusercontent.com/18197013/227554825-7e54def6-9351-4801-89a7-9f22c798e822.mov

### CODE REVIEW

**Review by nicollext — COMMENTED** [review]
Hi @crystalsong2021, the "Expand All" and "collapse All" buttons are working great. The loading spinner algo improved the UI/UX. Great work!

https://user-images.githubusercontent.com/101591708/227675439-38c28019-2731-4a99-b26a-63ce6f0b715b.MP4

However, during my testing, I noticed that the requests for the tasks are only being made after clicking the "Expand All" button. It's not currently possible to open a folder before clicking the "Expand All" button.

https://user-images.githubusercontent.com/101591708/227676028-856872cd-43cc-4980-984c-e74df856a94c.MP4

**Comment by calexander3108** [comment]
The "Expand All" & "Collapse All" Button works as expected. However if I open "Jae's WBS-USE THIS" project first time or after refresh, there are some tasks number (e.g. task# 2) that does not show an openable folder logo, but shows a subfolder then I click "Expand All". This subfolders (only for task# 2 and might be some other task# ) can only be seen after I clicked "Expand All" and not refreshing the project.

https://user-images.githubusercontent.com/127106980/227705310-5eb9c650-b2b7-4adf-b6a4-588f93b669ec.mp4

**Comment by Jorge-Nerd** [comment]
Hi @crystalsong2021  I tested and really like the changes that you did, good work

Before
PULL#735_1
After

PULL#735_2

**Comment by one-community** [comment]
Please fix the merge conflict on this PR

**Comment by AnishPandita** [comment]
Hi @crystalsong2021 I tested your Pr and Expand and Collapse is working as expected. However as pointed by others the data for folders is loaded only after we click expand button once otherwise its showing nothing in the folder hierarchy.

https://user-images.githubusercontent.com/111321945/229263510-c7028c91-7ac5-4894-893b-25e9a646794c.mov

**Comment by crystalsong2021** [comment]
> Hi @crystalsong2021 I tested your Pr and Expand and Collapse is working as expected. However as pointed by others the data for folders is loaded only after we click expand button once otherwise its showing nothing in the folder hierarchy.

Thanks for the input. I tried to reduce the latency on the first initial load by only loading the main task.

**Comment by crystalsong2021** [comment]
> Hi @crystalsong2021, the "Expand All" and "collapse All" buttons are working great. The loading spinner algo improved the UI/UX. Great work!
> 
> However, during my testing, I noticed that the requests for the tasks are only being made after clicking the "Expand All" button. It's not currently possible to open a folder before clicking the "Expand All" button.

@nicollext Thank you for the review. It was done on purpose due tot he increase loading time. I am trying to think of the better way to reduce the latency of the loading time. Maybe in the new PR.

**Comment by crystalsong2021** [comment]
revision to show all tasks at initial loading
https://user-images.githubusercontent.com/18197013/230587035-3f5b6fce-67dd-415d-8479-baf1e77b16f6.mp4

**Comment by crystalsong2021** [comment]
> Please fix the merge conflict on this PR

@one-community , the merge conflict is fixed.

**Comment by one-community** [comment]
Thank you. If you've fixed the other concerns here, please request a re-review by those people. There should be at least 3 approvals on this before it goes to final review/Raul.

**Comment by calexander3108** [comment]
> The "Expand All" & "Collapse All" Button works as expected. However if I open "Jae's WBS-USE THIS" project first time or after refresh, there are some tasks number (e.g. task# 2) that does not show an openable folder logo, but shows a subfolder then I click "Expand All". This subfolders (only for task# 2 and might be some other task# ) can only be seen after I clicked "Expand All" and not refreshing the project.

This issue has been resolved!

**Review by calexander3108 — DISMISSED** [review]

**Comment by one-community** [comment]
Reminder to reviewers to please approve the PR if your issues have been resolved and/or no issues exist.

**Review by PrabhjotSembhi — COMMENTED** [review]
image
it's working and there few things I am not seeing the same tasks as you It's behaving correctly but I am not seeing Loading animation. maybe my internet is fast or something
I am only seeing this many tasks 
image

**Review by ToobaJamal — COMMENTED** [review]
Hi Crystal,

I tested the PR and the **Expand all** and **Collapse all** buttons are working fine. However, here are a few issues I encountered:
1- I have different tasks than you
2- It is not possible to expand a task by just clicking on it before the **Expand All** button is clicked
3- The sub-tasks are not shown correctly every time. For example: If a task has a subtask named subtask-1, on expanding the tasks the correct subtask will sometimes be shown otherwise, some strange subtasks are shown. 

Notice the **Robo task four** and **Another Johny Task** in the attached video.

https://user-images.githubusercontent.com/52610124/230867442-86d0f963-91a2-4030-b3d5-d0d6ff10984f.mp4

**Review by nicollext — DISMISSED** [review]
Working as intended. Great job, thank you @crystalsong2021 

https://user-images.githubusercontent.com/101591708/230963490-1c6a8129-7a2a-4d26-9bb3-7d69ae3b3ddc.MP4

**Review by ypan710 — COMMENTED** [review]
Hi @crystalsong2021, I've tested your PR and the "Expand All" and "Collapse All" button worked as expected.

Screen Shot 2023-04-10 at 4 12 57 PM

Screen Shot 2023-04-10 at 4 13 02 PM

**Comment by LucileTech** [comment]
I tested the PR and it is working as expected! "Expand All" is showing  full content of files, and "Collapse All" shows just the files. When you click and re-click the files, it hides and shows the content. It is also working with the subfiles 
Here is a recording:

https://user-images.githubusercontent.com/111132148/231019875-d991d560-4dfd-4f08-8297-61e01341cb33.mp4

**Review by LucileTech — DISMISSED** [review]

**Comment by one-community** [comment]
Thank you everyone, moving to final review. Crystal also just let me know she's got Covid, so final reviewer please also fix these merge conflicts.

**Review by rauleffting — APPROVED** [review]
Hi, @crystalsong2021. Your PR worked quite well and the code is very clean.

https://user-images.githubusercontent.com/29555732/231215062-304cd07b-6913-42d4-bbe6-697143744dd8.mp4

Thank you!

**Pull request closed without merging**
