### PR TITLE
Sriram - add a button to create new projects

### PR DESCRIPTION
**Pull request by sri0606**
# Description
image

## Related PRS (if any):
This frontend PR is related to the backend development branch.
…

## Main changes explained:
- Removed the input text (above search bar) on Projects page to create a project and added a button that opens a modal.
- WBS and members can be assigned directly while creating the project.
- Updated the tests according to the new AddProject component.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links→ Projects
6. verify that there is no input text section above search bar and you can see a button `Add New Project`.
7. verify that after creating a project,  WBS are created and members are assigned correctly.
8. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
newAddProjectBtn
addProjectModal

## Note:
Make sure to go the project's WBS and members page to verify they have actually been assigned.

### CODE REVIEW

**Review by ArtemisNyx3 — APPROVED** [review]
image
Amazing work 🙌🏽

**Comment by tharunaa-1** [comment]
There is no input text section above search bar, there is only Add New Project button.
image


WBS are created and members are assigned correctly
image

**Review by chu-ziyu — DISMISSED** [review]
I tested this PR and everything worked as expected in both light mode and dark mode
1. Green button on the right for adding new project instead of input area
2. New modal can create WEBs and add team members
https://github.com/user-attachments/assets/178049e4-a3ec-4a37-85f5-d4dabe5a4a0b
sriram-add-button-to-create-new-project

**Review by Jingyii800 — APPROVED** [review]
Great work! There is no input bar on the top but " add a new project" button. 

https://github.com/user-attachments/assets/58ec7190-8683-4d52-8158-ea86b0ff7c29

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/3e74f158-a720-4f36-a51e-5b66a9e7999f

**Review by RishithaMamidala — CHANGES_REQUESTED** [review]
@sri0606 
The add project button works as expected and opens a modal. 
There is a suggession, when clicking on add project button in modal, the page freezes and requires a reload for the project to be added. Am not sure if this is in the scope of this PR. Please let me know if it is out of scope.

https://github.com/user-attachments/assets/bc33553b-8fa5-49ef-822a-5e77206537b6

**Comment by sri0606** [comment]
> @sri0606 The add project button works as expected and opens a modal. There is a suggession, when clicking on add project button in modal, the page freezes and requires a reload for the project to be added. Am not sure if this is in the scope of this PR. Please let me know if it is out of scope.
> 
>  PR.2694.mp4

Hey @RishithaMamidala , That issue is out of scope for this PR. It has been there for a while now. I believe this is being fixed in another PR.

**Review by ashmita123 — DISMISSED** [review]
I've tested this PR, and everything is working as expected. I verified that there is no input text section above the search bar, and the 'Add New Project' button is now visible. After creating a project, WBS are created and members are assigned correctly. I also confirmed that this new feature works in dark mode. Overall, great work!


https://github.com/user-attachments/assets/43add521-4041-4427-852f-97cb7739f9d5


https://github.com/user-attachments/assets/964ccc60-fe04-459f-a35e-0c461749e51f

**Review by RishithaMamidala — DISMISSED** [review]

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and it works as expected and i am able to create new Project

Screenshot 2024-09-20 155746
Screenshot 2024-09-20 155819

**Review by manikittu810 — DISMISSED** [review]
Hello @sri0606 
Changes are working as mentioned. Good work.
Screenshot 2024-09-20 at 4 54 16 PM

Thank you.

**Review by jinxyou — APPROVED** [review]
The project adding feature is working well. Great work!
Screenshot 2024-09-20 222329
Screenshot 2024-09-20 222348
Screenshot 2024-09-20 222423

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes mentioned in the PR work as expected, just after creating the project the loading animation keeps on going and no updates are made, I am not sure if that's supposed to happen but thought I'd mention it.
Screenshot 2024-09-21 at 9 07 36 AM
Screenshot 2024-09-21 at 9 08 44 AM
Screenshot 2024-09-21 at 9 11 18 AM

**Review by mohangadde1 — APPROVED** [review]
image
image
everything works as expected.

**Comment by mianmiantea2019** [comment]
Tested the PR and the changes mentioned in the PR work as expected

image

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.

Screenshot 2024-09-22 184056

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
