### PR TITLE
Alan click dot persons name

### PR DESCRIPTION
**Pull request by LeeSingChanYau**
This PR fixes the problem where "the “Filter Entries by Project” box is still sometimes loading the data for the viewer rather than the person being viewed. Sometimes it will fix itself and show the right list, but not always. I also made the PopUpBar be fixed to the top".

How to test:
- View tasks and time in the current account you are logged in.
- Open the dashboard of another user by clicking on the dot next to their name.
- Check if the right tasks and time entries are displaying.
- Check if the popup bar is fixed to the top even if we scroll.
- Do the steps above in multiple accounts.

### CODE REVIEW

**Comment by rauleffting** [comment]
Hi @LeeSingChanYau! I tested and, as you can see below, all worked well:

https://user-images.githubusercontent.com/29555732/212720788-acb94983-f53c-4bea-a900-b23805af5d2d.mov

**Comment by RafaelCastilhoCastro** [comment]
Hi @LeeSingChanYau,

I tested and I experienced a few issues. Please check video 1 for issues 1 and 2, and video 2 for issue 3.

1. Just after clicking the dot and the new window renders the items inside the "Filter Entries by Project and Task" box change in order as if the loading is taking a long time.

2. Just as the page is rendered the loaded tasks are from the last viewed profile and they are switched by the tasks of the actual profile after a few seconds. Also as if the loading is taking a long time.

3. Often when clicking on the itens inside the "Filter Entries by Project and Task" box the selection automatically jumps back to the last selected item. This issue is not observed when navigating the itens using the arrow keys.

4. The yellow floating bar is fixed but its size is off on the left side compared to its right side.(Please check image)


https://user-images.githubusercontent.com/65736872/214391910-9a0e9cab-0011-4f81-9e61-8836b838c31e.mp4



https://user-images.githubusercontent.com/65736872/214391932-836973fe-9691-4634-a450-848bfceb73f6.mp4

**Comment by AnishPandita** [comment]
Hi @LeeSingChanYau I tested the issues and the it seems to be working well.
1) Tasks for the current user are being displayed correctly.
2) The yellow floating bar is fixed and behaves perfectly even if we scroll.
https://user-images.githubusercontent.com/111321945/214417060-ba6b6a59-11c1-41d6-becf-a8322d9c4961.mov

**Comment by AnishPandita** [comment]
Hi @LeeSingChanYau I tested the issues and the it seems to be working well.

Tasks for the current user are being displayed correctly.
The yellow floating bar is fixed and behaves perfectly even if we scroll.

https://user-images.githubusercontent.com/111321945/214418403-8e79efdd-6642-4127-bfde-0a1195a2b837.mov

**Comment by rauleffting** [comment]
Hi @LeeSingChanYau! Please, verify @RafaelCastilhoCastro 's feedback. After that, I'm going to approve it! Thank you very much!

**Comment by PrabhjotSembhi** [comment]
I was checking this. it showed my data when i everytime click the dot of another user

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau, I have tested and checked for some issues. Please check the items and video below.

1. Sometimes the dashboard doesn't load after I refresh the page or when I'm trying to go back.

2. Whenever I click a second time on the dot next to the user the leaderboard only shows the user I clicked on previously. As soon as I come back to the page it shows all users again and after clicking on a second user the leaderboard only shows that user again.

Also, I only noticed the same problems as Rafael:

*The yellow popup exceeding the right side of the page

*Yellow popup is below notification numbers

[screen-capture (1).webm](https://user-images.githubusercontent.com/114119668/215614152-eb9b5f81-237f-4127-a5d2-ae55a66ab544.webm)

**Comment by rauleffting** [comment]
Following up on this.

**Comment by NyahJ** [comment]
Hi  @LeeSingChanYau,

I have tested your PR with every steps you suggested with different accounts.
Everything works well except for the popup bar, it is fixed to the top even if we scroll indeed, however, it is fixed in the middle of the page when scrolling, is it better to fix the bar in the border?

https://user-images.githubusercontent.com/77643813/217683430-36e753f4-569b-4352-ae21-316755f41094.mp4

**Comment by one-community** [comment]
Yes, should be fixed at the border when scrolling, so always visible at the top of a person's screen

**Comment by RafaelCastilhoCastro** [comment]
As mentioned by @NyahJ, there's another PR by @LeeSingChanYau related to this same issues.
[PR#595](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/595)
I'm confused about which PR is fixing which issue.

**Comment by Lunaliar** [comment]
Hey @LeeSingChanYau,
I ran through the tests you mentioned above. I didn't have any instances of swapped tasks or time but I did run into a little issue while trying to select different tasks and it immediately switched to the previously selected task. 

Breakpoints over 1550px cause other layout issues with the navbar and timer controls. The yellow pop-up bar was always detached from the navbar. It seems set to a height on the current window so it hangs out no matter where we scroll.

The videos below have examples of what I've found (Sorry I had trouble showing my cursor in videos, Linux can be tricky at times) 

https://user-images.githubusercontent.com/98275089/219060574-76ec83d9-9af6-4aac-9162-01717ae5e8cc.mp4


https://user-images.githubusercontent.com/98275089/219060669-8c64105d-1d34-4add-a972-e5ac630acca4.mp4

**Comment by angelinatr15** [comment]
Hello @LeeSingChanYau,

I clicked on the dot that is next to the member name. That sends me to a new window that displays their Tasks and Timelogs. I did this to a few others as well and the data that is suppose to render for each account is correct. 

As for the yellow pop-up bar, I think it would look nicer if it stays at the very top while scrolling down. Right now it has a small gap from the top while we are scrolling that gaps stays at the top, see image below. It looks like this design is being worked on in PR #595. 

Screenshot 2023-02-16 at 12 02 30 PM

**Comment by one-community** [comment]
I think it is more noticeable when it isn't at the top... Let's keep it as it is

**Comment by PrabhjotSembhi** [comment]
Hi @LeeSingChanYau, It still shows Entries of the previous user after 3-4 seconds it gets updated, to the one we clicked on
Suppose I am A
I am check-in B 
It will show A's entries for a few seconds before loading B's

Now B's entries are loaded last time. 

Now if A checks for C -> shows B's entries for a few seconds before loading C's.

Now C's entries are loaded last time. 

Now if A checks for any other person shows the last loaded entries for a few seconds before loading the correct ones. 

check video 


https://user-images.githubusercontent.com/82662768/219619633-1dddf790-c167-4f0b-b479-b4b899898ba3.mp4

**Comment by agujjar2206** [comment]
I have reviewed this PR and it looks good. The fix for the "Filter Entries by Project" box not always showing the correct data and the addition of a fixed PopUpBar to the top both work as intended.

I have also tested the changes by viewing tasks and time in multiple user accounts and the correct data is displayed. Additionally, the popup bar stays fixed to the top even when scrolling.

**Review by agujjar2206 — DISMISSED** [review]

**Comment by vanelnw** [comment]
Hi @LeeSingChanYau,
I have test changes by clicking on the dot that is next to the member name and tasks for the current user are being displayed correctly.
however as @angelinatr15  mentioned, it would be better if the yellow pop-up bar is fixed to top when scrolling


https://user-images.githubusercontent.com/38879488/219849923-8c9074fe-b7ef-444e-aa8a-fd6e5cb28101.mp4

**Comment by suigunfjc** [comment]
Hi @LeeSingChanYau,
I tested your features and the tasks for the current user are displayed correctly, well done! Though I noticed that after deployed your branch, all status dot turned to red as below:

Screenshot 2023-02-18 173501

and the timelog page is not working either:
Screenshot 2023-02-18 173527

**Comment by ayush0904** [comment]
Hi @LeeSingChanYau,

Thank you for the steps provided for reviewing the process, it was very helpful.
I also faced some of the issues that are addressed above:

1 - As stated by @RafaelCastilhoCastro , when I am clicking the colored dots next to the name. The page loads first with the old data and then the new data comes. 

2 - When the “Filter Entries by Project and Task” options are changed. All the data comes immediately, however the Project/Tasks take some time to load

3 - The Yellow Bar above is floating. The left margin and right margin for the bar is not the same.  Moreover, the color combination of white over yellow is not readable properly. Is it possible to change it to black over yellow to increase the readability

**Comment by tingedudu8** [comment]
Hi @LeeSingChanYau, I tested your PR and all the features work well. The dot color looks good to me. But I thought the yellow pop-up bar should be extend to the very left, just as the right side. Also, the loading time to jump to the next person takes a bit long. Thanks!

https://user-images.githubusercontent.com/70128933/221017849-81d640fb-f0b8-491a-b8ba-993b73ee8766.mov

**Comment by dkamghem** [comment]
It seems to work. I can view dashboard of different users. However the pop bar remain fix without moving when scrolling down or up. 
Screen Shot 2023-02-28 at 1 10 49 PM (2)

**Comment by RafaelCastilhoCastro** [comment]
Hi guys,
Since many of you are reporting different and inconsistent results compared to other reviews please make sure you have both repos properly updated and installed (`git pull` & `npm i`) and double check your results.
Also I think this PR changes are not related the color from the dots beside the user names since it's a different component (@LeeSingChanYau correct me if I'm wrong please). If you guys continue to experience such problem after updating/installing your repos, check if this issue is/should be added on the bugs Doc.

@LeeSingChanYau the reviews report a few seconds to load the correct user data once accessing it's profile after clicking the dot. Will you addess this loading time on this PR?

**Review by Lucas-E — COMMENTED** [review]
Hey Lee! I've tested your PR and it's working well. I can see the other person's dashboard, the taskts and times seems to be right.
When i enter one person dashboard, close and then enter another person's dashboard, the tasks glitch a little, and a little time after, they load as they should.
Captura de tela de 2023-03-01 17-33-20
Captura de tela de 2023-03-01 17-33-15

**Comment by angelinatr15** [comment]
Hi @LeeSingChanYau, 

I retested this branch and see the same problem as @RafaelCastilhoCastro reported. The drop down data inside of the "Filter Entries by Project and Task:" flickers between the original and new user. When I checked my console I noticed that the UI is re-rendering numerous times. However I am not sure what is specifically causing this and if that is the reason that is causing the "Filter Entries by Project and Task:" to flicker like that.  Although after the drop down data flickers for a bit the correct data does render for that user that is being viewed.

**Review by kamtoeddy — COMMENTED** [review]
Hi @LeeSingChanYau,

Just tested your PR and I could see a user's details upon clicking on the red circle but I also noticed the that the data inside of the "Filter Entries by Project and Task:" flickers between the original and new user just like @RafaelCastilhoCastro and @angelinatr15 have already reported

Screenshot (557)

**Comment by Lunaliar** [comment]
Looking great! I do not see the same issues I was before with the filer entries list on the other user's dashboard I'm viewing:
[clickpersondot.webm](https://user-images.githubusercontent.com/98275089/222598910-ee3edafd-72be-4cd7-88ba-a4c893ebc6ac.webm)
but I am seeing the same switching behavior on the user Im logged in as. 
[dotpersonadmin.webm](https://user-images.githubusercontent.com/98275089/222599469-4f5e75d0-35ec-4811-bdb7-90b68db20775.webm)
I've triple-checked my branch, status and ensured the node packages are current. I couldn't find any particular reason in the code as to why this behavior keeps recurring.

**Review by kangjay88 — COMMENTED** [review]
Hi @LeeSingChanYau,

After making sure npm and most recent branch was pulled, I noticed similar things consistent to other people's findings: 
-Yellow bar remains floating instead of fixed to top
-The tasks do take a while to load in the "Filter Entries Section", or the "total effort" box
-I noticed that the text box for "Filter Entries Section" was not fully responsive on my local server, not sure if other people are experiencing this as well

https://user-images.githubusercontent.com/108297706/222808279-a67c1923-9fc8-416f-bd2e-4d275c371fcf.mp4

**Comment by mpavithr** [comment]
Hi i tested this by following steps you gave, im able to view the tasks and time in the current account i am logged in.
Im able to open another user's dashboard by clicking on the dot next to their name.
The right tasks and time entries are displayed.
However as others have mentioned  as well the popup bar is fixed but not right at the top even if we scroll.
rb4rb4rb4

**Comment by LeeSingChanYau** [comment]
@kangjay88 @mpavithr @rauleffting Conflicts resolved, please review when you can.

https://user-images.githubusercontent.com/67836976/226084998-86356c6d-ea9f-4961-89d0-1aa047c2a15c.mov

As you can see in the video, the correct entries are shown when we open a dashboard for another user. In regards to the popupbar, if you are seeing in your end what you can see in the video then it should be good. Because we want to always see the popupbar, even if we scroll.

**Review by vitorsaa2k — APPROVED** [review]
Working as intended as showed on the video.

https://user-images.githubusercontent.com/17365161/230978130-84ac29b7-7be1-4165-93b8-dd089e1453fc.mp4

**Review by Lucas-E — APPROVED** [review]
Just re-reviewed it and it works as expected. I've found and error while visiting another user's dashboard: the right tasks are not shown correctily, but I'm fixing it on my PR.
Captura de tela de 2023-04-10 16-59-28

**Pull request merged**
