### PR TITLE
Masasa - applied all name and description updates

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
This PR applies the update about name and description updates on the permission page such that they match the names in this [spreadsheet](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit#gid=0)
Screenshot 2023-08-19 at 4 10 11 PM

## Related PRS (if any):
No related PRs
…

## Main changes explained:
changed the naming in for permission labels in UserRoleTab.jsx
Changed the corresponding descriptions in RolePermission.jsx

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner user
4. go to OtherLinks→ Permissions Management→ choose user role→…
5. Make sure the names and descriptions have been updated

## Screenshots or videos of changes:
Screenshot 2023-08-19 at 4 19 55 PM
Screenshot 2023-08-19 at 4 20 05 PM

### CODE REVIEW

**Review by Chuehleo — DISMISSED** [review]
Everything works as expected, great job!
Screenshot 2023-08-19 174627
Screenshot 2023-08-19 174529

**Comment by AnishPandita** [comment]
Hi, the PR works well. No errors found.
Screenshot 2023-08-19 at 5 48 00 PM
Screenshot 2023-08-19 at 5 47 53 PM

**Review by TheDescendant39 — DISMISSED** [review]
Hi @ThapeloMasasa, I checked your PR changes and they work well except for the following case. Could you please clear up my doubts?

I couldn't see descriptions for some of the permissions:
1. See Badge Management Tab (Full Functionality): I see that you have added a Description in your PR but it is not shown on the UI
2. Edit Project Category or Status
3. Change Date on Intangible Time Entry
4. Edit Own Time Entry
5. Delete Own Time Entry
6. See Permissions Management Tab and Edit Permission.

I may be misunderstanding your assigned work for this PR. Will someone else add the description for the permissions? I checked the google sheet and I see that there are descriptions for these above-mentioned permissions already so I thought they would be displayed. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/ff9e27e9-2e98-4464-9cad-7c180806b44e

**Review by n0vay — DISMISSED** [review]
Works with no errors.
image
image

**Review by ss23046 — CHANGES_REQUESTED** [review]
Hi @ThapeloMasasa ,
Tested the PR and it works for most of the permissions. 
Screen Shot 2023-08-19 at 9 41 53 PM
Screen Shot 2023-08-19 at 9 41 44 PM

There are a few permissions with an empty description box. Kindly have a look at those
See Badge Management Tab (Full Functionality)
See Permissions Management Tab and Edit Permission.
Change Date on Intangible Time Entry
Edit Project Category or Status
Delete Own Time Entry
Edit Own Time Entry

**Review by luisarevalo21 — DISMISSED** [review]
Hello @ThapeloMasasa 
I tested your PR and works as intended. Great job!

Logging into as an owner, I am able to view the updating styles in the, Permissions management component and I am able to view a description about each right. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/bf860b0b-4d20-42b9-80de-68fabc2861ab


However, as some have noted, there are a few that are empty. I'd suggest fixing those. 
I've confirmed the following do not have a description inside. 



- See Badge Management Tab (Full Functionality)
- See Permissions Management Tab and Edit Permission.
- Change Date on Intangible Time Entry
- Edit Project Category or Status
- Delete Own Time Entry
- Edit Own Time Entry

**Review by yurisokolovicz — DISMISSED** [review]
Dear @ThapeloMasasa 
Good work! I can now see the new styles applied in the permissionsmanagement. However, some of the permissions lack descriptions: **intangible time entry, edit own time entry, delete own time entry, see permissions management tab and edit permission, see all the reports tab,  view and interact with task x,  exit weekly Summary options.**

Screenshot from 2023-08-21 11-04-23

**Review by beblicarl — DISMISSED** [review]

**Review by belagaam — DISMISSED** [review]
Tested the PR as per the instruction. Everything works as expected. Good work.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/5e17f184-fe5c-490a-bf46-cb86d318d0c7

**Comment by Jiyuanxia** [comment]
Hi @ThapeloMasasa , while reviewing your pull request, I encountered some issues. Specifically, I couldn't locate the "Other Links" tab at the top of the page. I attempted to address this by clearing my cache and refreshing the page, but unfortunately, these steps didn't resolve the problem.
Screenshot 2023-08-24 204347

**Review by n0vay — DISMISSED** [review]
Even if I hover over the info button the dialog box opens. I think it should eith open on click or should close automatically when we move cursor away from info button.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85691749/53f066d6-f3aa-4472-a23c-1bccd874df52

**Review by LunaticLeo — DISMISSED** [review]
Hi, after I deployed your changed, I can't find other links on dashboard.
image

**Review by robertoooc — DISMISSED** [review]
Hi @ThapeloMasasa, I made sure to go through all the icon descriptions of each permission across all roles. I personally did not encounter any issues unlike other people, made sure to checkout the blank descriptions that some pointed out and I found everything to work as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/ba99e26d-aea7-41d7-86c6-eb0646ef5eae

**Review by Shubhu0 — DISMISSED** [review]
Tested the PR. Working as intended.

261828785-5ecd62b5-3d42-4db3-9697-8c70bd7c34ce

**Comment by ThapeloMasasa** [comment]
Please Do not add an approval as a comment..

**Comment by emunkh404** [comment]
Works Great Job
image

**Review by Alforoan — CHANGES_REQUESTED** [review]
I can't seem to start the local server.
image

**Pull request closed without merging**
