### PR TITLE
Nahiyan dark mode for reports page

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
THIS IS A FOLLOW UP PR TO [2105](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2105)
This PR makes dark mode available for the following pages:
- Reports page and all the tables
- Projects report page
- People report page
- Teams report page

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Implemented dark mode for the reports page and all the tables
- Implemented dark mode for the projects report page
- Implemented dark mode for the people report page
- Implemented dark mode for the teams report page

## How to test:
1. check into current branch
2. do `npm install` and npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Reports → Reports Page
6. verify that dark mode works properly on reports page and all its tables
7. verify that dark mode works on a project report page
8. verify that dark mode works on a people report page
9. verify that dark mode works on a team report page

## Screenshots or videos of changes:
Screenshot 2024-04-07 152745
Screenshot 2024-04-07 152814
Screenshot 2024-04-07 152915
Screenshot 2024-04-07 152950

### CODE REVIEW

**Review by linkhanthtel — DISMISSED** [review]
Looks good! Dark mode work on all the report pages. Only one thing, the project header in project report is still white in the dark mode. 

#2126 (Project Report)
#2126 (Team Report)

#2126 (People Report)

**Review by SRamen1999 — COMMENTED** [review]
All the new dark mode UI changes work as expected. The only thing I would change is the project header as it is still white in the dark mode.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/e3298d48-13a8-4e3b-9ca9-f24dded52ffb

Also I feel like the badge summary should also change with the dark mode theme.
Screen Shot 2024-04-11 at 4 24 06 PM

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi, I just reviewed your PR and all the pages are working fine with dark mode as you mentioned. Attaching the images for reference.

Screenshot 2024-04-11 at 7 51 50 PM
Screenshot 2024-04-11 at 7 51 04 PM
Screenshot 2024-04-11 at 7 50 51 PM
Screenshot 2024-04-11 at 7 50 38 PM

**Review by anandsesha — DISMISSED** [review]
Hi, the dark modes in project reports, people, reports table, and teams report page work as expected.
Screenshot (790)
Screenshot (791)
Screenshot (792)
Screenshot (793)
Screenshot (795)
Screenshot (797)

**Comment by Nahiyan-16** [comment]
@SRamen1999 @linkhanthtel Great catch! Just fixed it in the recent commit.

**Review by SushmithaPrathap — DISMISSED** [review]
Hey, I have tried this PR. It works as expected. The dark mode works perfectly on the Report pages. 

here is the screen recording:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/eca0e15e-6377-4215-9a1a-84d07eb61347

**Comment by hiralsonip** [comment]
Hello...I have checked this PR and everything is working as expected. 

PR2126_report

**Comment by metaphor987** [comment]
Hi Nahiyan, I'm testing the changes using the admin account, and I've encountered a problem. When I stay in dark mode, I can successfully access the people report page. However, the page becomes blank if I try to switch to white mode (as shown at about 00:50 in the recording). This issue doesn't exist for the team report page and the project report page. Additionally, it exists when navigating directly to the people report page while in the light mode. I'm not entirely sure if this is a problem with my setup, but I think it's worth checking. Thanks!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/6c766a63-1f3d-48ef-8267-2bb725ac7961

**Review by metaphor987 — CHANGES_REQUESTED** [review]
Hi Nahiyan, 
I'm testing the changes using the admin account, and I've encountered a problem. When staying in dark mode, I can successfully access the people report page. However, the page becomes blank if I try to switch to light mode (as shown at about 00:50 in the recording). The screenshot shows the error log at that point. This issue doesn't exist for the team report page and the project report page. Additionally, the issue also exists when navigating directly to the people report page while in the light mode.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/d7695481-d750-49de-90dc-3e08ffeeabea

error log

**Review by aaryaneil — DISMISSED** [review]
All the dark mode UI changes work as expected. Good work.
Screenshot 2024-04-13 at 8 29 10 AM
Screenshot 2024-04-13 at 8 29 53 AM
Screenshot 2024-04-13 at 8 30 59 AM
Screenshot 2024-04-13 at 8 31 08 AM
Screenshot 2024-04-13 at 8 31 51 AM
Screenshot 2024-04-13 at 8 32 41 AM
Screenshot 2024-04-13 at 8 33 30 AM

**Review by Tiantian-C — COMMENTED** [review]
Everything works fine!
Screenshot 2024-04-13 at 4 10 40 PM
Screenshot 2024-04-13 at 4 10 45 PM
Screenshot 2024-04-13 at 4 10 56 PM
Screenshot 2024-04-13 at 4 11 01 PM

**Review by Parth-tech — DISMISSED** [review]
Hey Nahiyan,
I have tested your PR and it works as intended. I have checked it for both Owner as well as admin account. The changes do not seem to affects any other functionality as well.
Screenshot 2024-04-13 at 3 53 04 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/99d1363e-d2f8-4973-8958-0ac59d57df5a

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
