### PR TITLE
Abdel streamlined data input for new members

### PR DESCRIPTION
**Pull request by abdel-lall**
# Description

#### $\textcolor{red}{\textsf{(PRIORITY HIGH) Jae:}}$: Create a way for easy/nearly-automated data input for creating a new member 
- I’d like to be able to have a way for people to input their own information for initial setup in the software. Right now I set them up manually and it takes me a fair amount of time. It would be better to be able to send them a 1-time link that would have them set up the information for themselves. 
- Link needs to be 1-time so that people can’t just randomly create users
- Link should be generated by me just inputting their email somewhere like the top of the User Management page
- The parts that will need to be set up by me after they set themselves up are their Team and Projects/Tasks, so they shouldn’t have access to choose these. The rest though they should set up themselves. 
- I’d like to get an email each time a person sets themselves up, so I can easily check the details without logging into the software. If errors were made, I could also ask them to correct them by just forwarding the email with the corrections. 

## Related PRS:
- This frontend PR is related to the [#464](https://github.com/OneCommunityGlobal/HGNRest/pull/464) backend PR.

## Main changes explained:
- Updated route.js, userManagment.jsx and usermanagment.css.
- Added setupNewUserPopup.jsx, SetupProfile.jsx, SetupProfileUserEntry.jsx and SetupProfileInvalidToken.jsx.

## How to test:
- check into the current branch.
- do `npm run start:local` to run this PR locally.
- Test for the requirements in the description. 

## Test:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/55f1753d-e3d4-4310-832d-513bed58d269

### CODE REVIEW

**Review by winghojackyli — COMMENTED** [review]
Hi @abdel-lall , I've tested your PR and it worked fine. 
I can receive the email and set up a new account on it, but the page stuck if I don't change the value inside "Weekly Committed Hours". I can't leave it as default (10 hours a week). 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/bbef9d0d-7eb9-4807-8c31-0dfd0324f9fc

**Comment by abdel-lall** [comment]
@winghojackyli Good catch! Thank you for your review. The issue has been fixed now. Please re-test and let me know if it's resolved.

**Review by winghojackyli — APPROVED** [review]
Hi @abdel-lall , I've tested the PR again and it works perfectly! I can leave the weekly committed hourse as default.

**Comment by jacky776690g60** [comment]
Hi @abdel-lall,

I've tested both frontend and backend update. It works perfectly. It also blocks user from revisiting the link. Wonderful job!

Screenshot 2023-07-31 at 5 16 01 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70770465/bdebae52-0262-43b3-b3f4-41c30cca7ed3

**Review by DavidC0126 — DISMISSED** [review]
Hi @abdel-lall, I tested your PR and everything works as intended. I was able to send a link to desired email and create an account, also the link would not be able to re-visit. My manager email account can receive the notification email.

sent_link
create_acc
successfully_create

received_link


notify_manager

**Review by xaanders — DISMISSED** [review]
Hi @abdel-lall ! 
I've tested your PR. Works perfect. Amazing work.
Console is clean, mails came, link is one time use and manager is notified. 

[scrnli_8_1_2023_11-05-49 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/db804c40-ded1-428c-8e2c-640ca015f9a9)

**Review by sxiong5 — DISMISSED** [review]
The PR works well, nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/45e4c1dd-b3b3-4f3c-8232-b2c345f5fc9c

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/0d9c0e93-1d42-43bf-a624-261aa830ae3a

**Review by joyceiphone — APPROVED** [review]
LGTM. Working as expected.
Screen Shot 2023-08-01 at 8 30 01 PM
Screen Shot 2023-08-01 at 8 30 15 PM

**Review by eduvarjaor — COMMENTED** [review]
Hi @abdel-lall 

I tested this PR as manager, owner, and admin. As a manager, I wasn't able to send the link and as owner/admin I was able, but I didn't receive the link to create a new account. 

Which account role it's supposed to use? Am I doing something wrong?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/1843ec58-8ce2-47d2-b24c-c273c68ea2d5

**Comment by abdel-lall** [comment]
Hi @eduvarjaor 
Thank you for testing. Regarding the roles, a setup link can be sent by any role that can create a user. If you're having trouble  sending emails, it's probable that the issue comes from the configuration of environment variables on the backend. I recommend carefully verifying these variables.

**Review by Indujaks — DISMISSED** [review]
Verified your changes with both valid and invalid token. I was able to setup a new account through the link received. 
Screenshot 2023-08-03 at 4 29 21 PM
Screenshot 2023-08-03 at 4 29 35 PM
Screenshot 2023-08-03 at 4 31 54 PM

After successful creation of the account, i was able to get a notification about the new account being created (manager).
 
Screenshot 2023-08-03 at 4 33 40 PM

**Comment by n0vay** [comment]
Works as intended, Great Job on the Code.
I was able to create a new user with volunteer role, the time API feature is well executed. 
Great Job!!

**Review by n0vay — DISMISSED** [review]

**Review by veronicacheng2 — DISMISSED** [review]
Hi @abdel-lall, I have tested the PR according to the instructions and everything works as intended

1. Sending invitation link via email
image

2. Profile setup email received
image

3.  Setting up user profile
image

4. Account created and logged in 
image

5. Manager received an email about new user profile being set up
image

6. Confirmed user profile information is the same as what I filled in
image

**Review by navneeeth — APPROVED** [review]
The functionality works great and the UI flow works as expected. Verified the signup with both valid and invalid token and it works as intended.

**User setup link sent:**
user_setup_link_sent

**Profile Setup Email Received:**
profile_setup_email_received

**New user created:**
new_user_created

**Manager notified:**
manager_notified

**User info matches the signup data:**
uesr_profile_info_verified

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
