### PR TITLE
Nahiyan_Dark mode on Teams page modals

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Implemented dark mode on all modals that can be found in the Teams page

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Dark mode for all modals on the Teams page

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links → Teams
6. verify that all modals on the Teams page are working properly

## Screenshots or videos of changes:
Screenshot 2024-05-17 111848
Screenshot 2024-05-17 111912

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
All modals on the Teams page are working properly. Nice work!

Screenshot 2024-05-17 at 11 56 51 PM
Screenshot 2024-05-18 at 12 00 57 AM
Screenshot 2024-05-18 at 12 01 07 AM

**Review by Ramaruva — APPROVED** [review]
Hi I have verified your changes and they are working as expected nice work!
image
image
image

**Review by MinSun0814 — APPROVED** [review]
image
New dark mode looks nice! Good work!

**Review by sucheta90 — APPROVED** [review]
Hello @Nahiyan-16 , I have reviewed this PR and would like to confirm that everything works as expected. Pictures are attached for reference.
Screenshot 2024-05-18 at 8 06 31 AM
Screenshot 2024-05-18 at 8 04 05 AM

**Comment by iTvX** [comment]
For my side, I can not open team. As you can see from the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/37c9c06e-b15b-41d3-82de-b49ff3fd3a65

**Review by tdkent — APPROVED** [review]
Dark mode changes are correctly applied on the specified page and modals

**Review by aaryaneil — COMMENTED** [review]
I am getting a white screen when I switch to the teams link.
Screenshot 2024-05-18 at 2 17 01 PM

**Review by KurtisIvey — APPROVED** [review]
Everything seems to check out. Great job. I found all of the modals and different functionality of the Teams page to have a proper functioning Dark mode as intended. 

Screenshot 2024-05-18 at 4 03 50 PM
Screenshot 2024-05-18 at 4 04 05 PM
Screenshot 2024-05-18 at 4 04 17 PM
Screenshot 2024-05-18 at 4 04 25 PM
Screenshot 2024-05-18 at 4 04 37 PM
Screenshot 2024-05-18 at 4 06 29 PM

**Review by cvtqx — APPROVED** [review]
I've reviewed all the modals on teams page and in dark mode they all look good. Great job!

Screenshot 2024-05-18 at 7 04 11 PM

Screenshot 2024-05-18 at 7 05 17 PM

Screenshot 2024-05-18 at 7 04 57 PM

**Review by hbodgal — APPROVED** [review]
image

All functionalities works well with dark mode. Just pointing out one thing that can be a seperate issue. When we delete team member there should be warning message with proper UI. (Refer image)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
