### PR TITLE
Zijie lint fix reducer phase2

### PR DESCRIPTION
**Pull request by iTvX**
# Description
This is lint fix for all the file under src/reducers/ except: actionltemsReducer.js, allProjectsReducer.js, allTasksReducer.js, allTeamsReducer.js, allTimeEntriesReducer.js from src/reducers file

I haven't changed the export to a default export because I've found that even if I make the change and remove the curly braces in the index.js file, something still goes wrong.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user

(Please be sure you record a video)
5. **Verify that the reducer is working normally.**

(No need to test below)
~~6. Delete .eslintignore file in the root: `rm .eslintignore`
7. `npx eslint all the file under src/reducers/ except: actionltemsReducer.js, allProjectsReducer.js, allTasksReducer.js, allTeamsReducer.js, allTimeEntriesReducer.js from src/reducers file`
11. `git restore .`~~

### CODE REVIEW

**Comment by iTvX** [comment]
> Hi @iTvX, I've tested your PR, and I encountered two errors while running 'npx eslint' in 'userTeamMembersReducer.js' and 'userProfileByIdReducer.js'.
> 
>    

Thank you, I have fix it(add ignore to them, since I don't want to delete any code).

**Review by Shubhu0 — CHANGES_REQUESTED** [review]
Hi @iTvX tested your PR but noticed that the index file displayed an error

image
image
image
image

**Comment by iTvX** [comment]
> Hi @iTvX tested your PR but noticed that the index file displayed an error
> 
> image image image image

Thank you for the review.

The error you encountered is due to not following my instructions. Please ensure you are in the root directory and use the command npx eslint src/reducers/index.js.

If you're not in the root directory, it will not be able to detect any other modules.

**Comment by mounica-dingari-by** [comment]
Hi @iTvX , I've tested your PR and there are errors only in index.js file. There are no errors in rest of the files.

Screenshot from 2023-10-20 20-52-37
Screenshot from 2023-10-20 20-57-37
Screenshot from 2023-10-20 21-01-14

**Review by Iris-Song — APPROVED** [review]
Hi, I have tested and found no error. The lint looks also good. good job. 
image

**Review by StrawberryCalpico — APPROVED** [review]
Hi I tested your PR, it worked perfect and eslint all good.
Screenshot 2023-10-21 at 2 28 40 PM

**Comment by palakgosalia** [comment]
Hey, I reviewed and tested the lint errors. I found no errors. Thank you. 

image

**Comment by iTvX** [comment]
> Hi @iTvX , I've tested your PR and there are errors only in index.js file. There are no errors in rest of the files.
> 
> Screenshot from 2023-10-20 20-52-37 Screenshot from 2023-10-20 20-57-37 Screenshot from 2023-10-20 21-01-14

Thank you for the review.

The error you encountered is due to not following my instructions. Please ensure you are in the root directory and use the command npx eslint src/reducers/index.js.

If you're not in the root directory, it will not be able to detect any other modules.

**Review by DavidC0126 — APPROVED** [review]
Hi @iTvX I tested the PR and no error occurs when running eslint. Good job!

Uploading phase2.mov…

Screenshot 2023-10-24 at 1 38 44 AM
Screenshot 2023-10-24 at 1 40 59 AM
Screenshot 2023-10-24 at 1 41 11 AM

**Pull request closed without merging**
