### PR TITLE
Jiayu --> Cheng-Yun Implementation Sorting on Most Recent Edit for Inventory and Members

### PR DESCRIPTION
**Pull request by DavidC0126**
# Description
Implemented two sorting buttons' UI on inventory and project members headings, as well as created sorting functions that can be one-click sorting the project by most recent edit ones.

## Related PRS (if any):
This frontend PR is related to the #1812  FE PR.
…

## Main changes explained:
- Update projects.jsx for implementing new sorting functions
- Create FE sorting buttons for inventory and members headings
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user 
4. Go to Other Links -> Projects
5. click two buttons and see if projects are sorted correctly
6. You can create a new project, add members inside and see if it's on the top of the projects

## Screenshots or videos of changes:

Screenshot 2024-03-08 at 12 14 46 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/bfdc07e3-2e9c-4b07-af5f-fd3ae45fc053

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Abi-Liu — COMMENTED** [review]
It works as expected, but I feel that this default sorting by most recently edited is not a great way to sort the member and inventory fields. It may be more beneficial to allow users to choose what they want to sort by, i.e. members highest to lowest,  lowest to highest, etc. It would require you to make changes to the `src/components/Projects/Projects.jsx` file as well as modify the code you submitted.

As a reference you could just look at the changes made in [this PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1812)

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and it works as intended. I was able to sort the recently edited projects. Please refer the video attached.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/f484a6a0-6c2a-45ba-9455-42b143ec0202

**Review by yaow62023 — APPROVED** [review]
The sorting functions are work as intended. check the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/45794b2f-8fa7-4718-a0a8-701be0dbdfe5

**Review by mohabbasd — CHANGES_REQUESTED** [review]
Hello, I tested you PR and it the 2 buttons work, but when I add a new Project it does not show up and there is no way where I can go back to the default projects shown in the list, only when I reload it the projects get shown so please make that change.
Below is a video for you reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/4f832ff3-6d3c-40b7-8c93-ef9f7f5d13db

**Review by yvonnep165 — APPROVED** [review]
Hi, I have tested this PR and it works as intended. I clicked two buttons and the projects are sorted correctly. And I created a new project, added members inside and it became on the top of the projects. Please refer to the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/1a92eabd-c896-4b4a-bffc-53902b9dff59

**Review by cgomezhub — CHANGES_REQUESTED** [review]
Hi Cheng,

I noticed that you implemented sort buttons for the project and inventory member headers. The project member sorting functionality seems to be working fine, but the inventory UI is not showing any data after sorting.

Furthermore, the project sorting feature currently sorts alphabetically rather than by most recent editions. except when you refresh the page

https://www.loom.com/share/c0c75cf156214472a15b6e4c1c7e5894?sid=baa29494-bacd-4714-a7d4-8ea26423ed77

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi David, 

Your changes are working, I do have a suggestion on top of this
Here are the working changes:
- Sorting by Inventory
image
- Sorting my Members does not change anything, please check if its working on your end.

- The change I request for is that, just by seeing the icon, Im not able to tell that clicking on the arrow next to Inventory will sort the list by datetime last edited. I suggest adding a tool tip or an appropriate icon to showcase that intent

**Comment by ZhangPeizhou** [comment]
I test your PR on my PC, it works as expected. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/2caba93a-4198-4428-bb6f-300ded3e8382

**Review by peter6866 — CHANGES_REQUESTED** [review]
Hi, I've checked your branch and when I click the inventory button there will be an error.
Also, after adding a user to a project, clicking the sorting button wouldn't work.
image

**Review by Kavil-Jain-514 — APPROVED** [review]
Hello,
The sorting button works well, and adding a new project comes at the top of the table.
image

image

**Comment by CloudyZ524** [comment]
Hi,
I noticed a issue when testing the sorting buttons. When I filtered it with the category "Other", "Inactive" and press the sorting button. The order of item displaying has changed but the number of items has also changed without reason. Please take a look at this issue. 
Screenshot 2024-05-31 at 16 37 46
Screenshot 2024-05-31 at 16 37 40

**Review by CloudyZ524 — CHANGES_REQUESTED** [review]
Hi David,
I noticed a issue when testing the sorting buttons. When I filtered it with the category "Other", "Inactive" and press the sorting button. The order of item displaying has changed but the number of items has also changed without reason. Please take a look at this issue. 
Screenshot 2024-05-31 at 16 37 46
Screenshot 2024-05-31 at 16 37 40

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as described. Good job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/9d397a48-b6d5-4e04-b105-b30062e2c969

**Comment by akshit0211** [comment]
Sorting buttons work as expected. Also, the new project comes at the top after adding a new member.

Without sorting
asc
desc
new project at the top

**Review by akshit0211 — APPROVED** [review]

**Comment by nishithaShetty** [comment]
Hi, Nice work! 
The functionality works as expected. The two sort buttons sort the projects correctly, and by default, the latest project is displayed at the top. However, when we click the inventory button, we encounter an error and the page does not load.
PR#2034_1
PR#2034_2
PR#2034_3
PR#2034_4

**Review by TXMO-dev — APPROVED** [review]
Sorting implementation sorting on most recent edit for inventory and members. Approved!

**Pull request closed without merging**
