### PR TITLE
Deepthi fix badge assignment UI

### PR DESCRIPTION
**Pull request by deepthikannan**
# Description
image

…

## Main changes explained:
- Updated file Badge.css: Adjusted input field and dropdown width to prevent layout shift when typing in the input fields.
- Updated file AssignBadge.jsx: Updated layout logic to ensure the elements remain aligned and fixed in position when suggestions are being fetched.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other links→ Badge Management→ Badge Assignment→ Assign Badge
6. verify that typing in the "first name" input field does not shift the "last name" input field.

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by RishithaMamidala — APPROVED** [review]
@deepthikannan 
I have reviewed the PR, typing in the "first name" input field does not shift the "last name" input field.
PR 2711

**Review by nikhilgiri0226 — APPROVED** [review]
image
verified that typing in the "first name" input field does not shift the "last name" input field.

**Review by chu-ziyu — APPROVED** [review]
I have tested this PR. When typing first name, last name keeps unchanged. It worked as expected.

https://github.com/user-attachments/assets/7d2db61f-9a44-45ba-86ed-ba19327424b5

**Review by slidracoon72 — APPROVED** [review]
#2711
@deepthikannan
I have examined the PR, and entering text in the "first name" input field does not cause the "last name" input field to move.

**Comment by tharunaa-1** [comment]
I have reviewed the PR, and it works as expected.

image

**Review by ashmita123 — APPROVED** [review]
Tested PR #2711. The input field alignment works as expected—typing in the "first name" input field does not shift the "last name" field. All changes function correctly.

https://github.com/user-attachments/assets/a25369b7-cb08-471b-9944-572362bc78ad

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and verified that typing in the "first name" input field does not shift the "last name" input field.

Screenshot 2024-09-26 151843
Screenshot 2024-09-26 151927

**Review by Dk-21 — APPROVED** [review]
PR-2711
@deepthikannan 
Tested the code changes and Working as Specified.
Screenshot 2024-09-26 at 4 50 14 PM

**Review by ziyanw52 — APPROVED** [review]
I have test the PR, typing in the "first name" input field does not shift the "last name" input field.
481727476368_ pic_hd

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Please remove the inline styling and replace it with Bootstrap classNames where appropriate. If additional styles are needed, consider creating a dedicated AssignBadge.css stylesheet. This would improve organization, maintainability, and make it easier to locate relevant styles for AssignBadge.jsx.

Remember, inline styles are rarely the best solution. Although you didn't introduce all of the existing inline styles, it's important to avoid contributing further to this pattern.

get rid of the inline styling and instead use built in bootstrap classNames.
image

Inline style needs to be removed and instead applied via a className. Though you didn't create all the inline styles here, you did contribute to it.
Screenshot 2024-09-28 at 7 48 56 AM


just delete the code. We can see the previous code in the commit history, so there's no need to comment it out
Screenshot 2024-09-28 at 7 50 07 AM


There's a style sheet for this. If you want a dedicated one for AssignBadge.css, it's fine to make one. In addition, due to using inline styles, you're introducing repetitiveness in the code that could be directly avoided via classNames.
Screenshot 2024-09-28 at 7 51 28 AM

Same as above:
Screenshot 2024-09-28 at 7 52 55 AM

your commented out code that you wrote yourself doesn't need to be in the style sheet. Delete
Screenshot 2024-09-28 at 7 57 03 AM

The current commit contains changes in files beyond the scope of the bug fix and includes unnecessary inline styles. This commit needs to be discarded completely.
Screenshot 2024-09-28 at 7 58 59 AM


P.S. there's also a merge conflict

**Review by Vincent-space — APPROVED** [review]
Hi, I've tested the function, everything works as expected.
image

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes to the first name field do not affect the last name field.
Screenshot 2024-09-28 at 10 25 29 AM

**Pull request closed without merging**
