### PR TITLE
Leo fix tasks dropdowns to the projects reports page

### PR DESCRIPTION
**Pull request by Chuehleo**
# Description
螢幕擷取畫面 2024-06-21 044412
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Main changes explained:
- Updated the TasksTable and TextSearchBox components to include new styling patterns and ensure consistency with dropdown lists.
- Created and applied a new CSS class .tasks-table-text-search-box to style the TextSearchBox component, allowing typing and sorting of names.
- Set the cursor to automatically focus on the dropdown input box when accessing the project page.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→Projects…
6. verify the TextSearchBox and Select components have consistent styling (feel free to include a screenshot here).
7. verify that the dropdown lists can be typed into and sorted correctly.
8. verify that the cursor automatically focuses on the typable dropdown input box when the project page is accessed.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/e4a83093-16fb-41cd-b19d-bc86c8539517

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by agryash** [comment]
I see the styles added in for all the components mentioned above. Here's a screenshot of what I see. 

image

**Review by agryash — APPROVED** [review]

**Review by jinxyou — APPROVED** [review]
Hi I saw the search box and select item being consistent in style, and the dropdown list can be typed. Also, the cursor can be focused. 
Screenshot 2024-06-22 192926
Screenshot 2024-06-22 193001

**Review by Jingyii800 — APPROVED** [review]
I have tested this PR. I verifed the search boxes have the same styling and the dropdown lists can be typed into and sorted correctly. Also, the cursor automatically focused.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/f5c4ab3e-5a19-4db5-a2f5-362a6111ca7a

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and the verified the consistent styling of TextSearchBox and Select components. The dropdown lists can be typed into and sorted and he cursor automatically focuses on the dropdown input box when the project page is accessed.

Suggestion: 
The table column header and data alignment is improper and there is overlapping of data in start and end date. Please correct the table alignment.

**Comment by IchinnorovTuguldur** [comment]
Hello Leo,

I was tested the dropdown and worked as expected. Great work! I have small suggestion for members table. When squeeze  the window into smaller one table styling is not consistent anymore. I think you can add some padding or box to prevent it from breaking. 

Screenshot 2024-06-28 at 8 32 46 PM

**Review by tianyangL11 — APPROVED** [review]
Verified that the TextSearchBox and Select components have consistent styling.
Dropdown Functionality:
Verified that the dropdown lists can be typed into and sorted correctly.
Verified that the cursor automatically focuses on the typable dropdown input box when the project page is accessed.
All tests have passed successfully.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
