### PR TITLE
Top bar is not updating fix

### PR DESCRIPTION
**Pull request by LeeSingChanYau**
Top bar is not updating when hours are completed for the week and/or a summary is submitted. Refresh is needed and then the !s turn to checks. Should Auto-refresh.  It should check and see if they have completed their hours for the week and turn the red ! to a green ✓ if they have. Right now the hours log in the bar but the check doesn't change like it should without a refresh.

### CODE REVIEW

**Comment by RJBornToWin** [comment]
I tried testing the branch locally. But I get an error while saving the weekly summary but the summary is saved. The summary turns to tick only after refresh. Am i missing something here

**Comment by LeeSingChanYau** [comment]
Uploading Screen Recording 2022-12-18 at 9.38.52 PM.mov…

**Comment by LeeSingChanYau** [comment]
Can you please share how long you waited?

**Comment by RJBornToWin** [comment]
The error popped up immediately after save and I waited for Upto 5 seconds before refreshing the screen.

**Comment by LeeSingChanYau** [comment]
Thank you for your feedback. Yes I believe axios is running normally on my end. It would be great if someone else can test this.

**Comment by EvianTan** [comment]
I just tested locally.

✅ Verified changes:
1. Wrote a summary and submit it, the page can be auto-refreshed to get the red exclamation to be changed into the green check sign, without any errors there.
Video can be accessed [here](https://www.dropbox.com/s/h6yi4nak658v10o/submit%20summary%20test%20for%20PR%20602.mp4?dl=0).
2. Change my weekly committed hours to 1, and logged more than 1 hour to meet the weekly committed hours, the page can be auto-refreshed to get the red exclamation to be changed into the green check sign, without any errors there.
Video can be accessed [here](https://www.dropbox.com/s/apwh4skmjf4e72a/log%20time%20meet%20test%20for%20PR%20602.mp4?dl=0)

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
