### PR TITLE
Chengyan phase2 reusables list UI

### PR DESCRIPTION
**Pull request by ChengyanOo**
# Pull Request Description

This Pull Request (PR) introduces significant updates to the UI and backend integration for managing reusable items in the BM Dashboard. The main focus of this PR is to enhance the user experience by providing a seamless interface for viewing, adding, and managing reusable items, paralleling the functionalities available for consumables.

## Related PRs (if any):
- [HGNRest_PR#750](https://github.com/OneCommunityGlobal/HGNRest/pull/750)

## Main Changes Explained:
- **Refactored Consumable/Material/Reusable List View**: Introduced a reusable list view component to simplify the creation of list views across the application.
- **UI Development for Reusable Items**: Initiated the development of a user interface that mirrors the existing consumables UI for consistency and ease of use.
- **Redux Integration**: Established a Redux workflow for fetching and updating the reusables store, ensuring robust and scalable state management.
- **UI Input Section**: Developed the UI for the input section, facilitating the addition and management of reusable items.
- **Table Section UI**: Ongoing development of the table section UI, crucial for displaying reusable items in an organized manner.

## How to Test:
1. Switch to the `Chengyan-Phase2-Reusables-List` branch on the [HGNRest repository](https://github.com/OneCommunityGlobal/HGNRest/tree/Chengyan-Phase2-Reusables-List) and start the server.
2. Check out the current branch of this PR.
3. Run `npm install` and `npm run start:local` to launch the application locally.
4. Clear your browser's site data/cache.
5. Log in as an admin user.
6. Navigate to the BM Dashboard → Reusables → Manual test at `http://localhost:3000/bmdashboard/reusables`.
7. Repeat step 6 for Consumables and Materials sections at their respective URLs.
8. Review the code for potential code smells.

## Screenshots or Videos of Changes:
This week

- Detailed walkthrough (**UPDATED**) : [https://www.loom.com/share/cb5c39bdd4da44f28d0237a3de6deaa0?sid=32e7db98-2395-47cf-9202-bd0b69194afe](https://www.loom.com/share/cb5c39bdd4da44f28d0237a3de6deaa0?sid=32e7db98-2395-47cf-9202-bd0b69194afe)

## Note
Please review the walkthrough videos before starting your review of this PR.

### CODE REVIEW

**Review by TareqMia — COMMENTED** [review]
Hi @ChengyanOo, I tested out this PR and everything did work as expected. I did find one bug, however. When you select a certain project and then try to sort it based on the "Name" or "Project", the values in the table change to all the data available and instead of displaying the currently selected project. I don't think that is the intended result. I was looking through the code and I think it has something to do with your ```handleSort()``` function in ```ReusablesTable.jsx```. Other than that, the table looks great, and the code is good as well-- nice and organized. The bug is shown in the last 10 seconds of the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/b6b5ce56-ef1a-4c2f-a38c-fb3b24babaa3

**Review by TareqMia — CHANGES_REQUESTED** [review]
Hi @ChengyanOo, I tested out this PR and everything did work as expected. I did find one bug, however. When you select a certain project and then try to sort it based on the "Name" or "Project", the values in the table change to all the data available and instead of displaying the currently selected project. I don't think that is the intended result. I was looking through the code and I think it has something to do with your ```handleSort()``` function in ```ReusablesTable.jsx```. Other than that, the table looks great, and the code is good as well-- nice and organized. The bug is shown in the last 10 seconds of the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/b6b5ce56-ef1a-4c2f-a38c-fb3b24babaa3

**Comment by ChengyanOo** [comment]
> Hi @ChengyanOo, I tested out this PR and everything did work as expected. I did find one bug, however. When you select a certain project and then try to sort it based on the "Name" or "Project", the values in the table change to all the data available and instead of displaying the currently selected project. I don't think that is the intended result. I was looking through the code and I think it has something to do with your `handleSort()` function in `ReusablesTable.jsx`. Other than that, the table looks great, and the code is good as well-- nice and organized. The bug is shown in the last 10 seconds of the video:
> 
>  Screen.Recording.2024-02-17.at.5.56.19.PM.mov

@TareqMia 
Thank you for your review, I'm working on the bug you just mentioned and will update the repo soon, please fell free to come back and test my changes!

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and it is working properly. The interface is quite user friendly and is rendering without any errors. The sorting and filtering functionalities are working properly. The items are being sorted properly in the main table as well as in the filtered table as well. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/a35c50df-77ee-4905-980f-ef388610a4ed

**Review by ShengjieMao — DISMISSED** [review]
The UI and sorting functions all worked well while testing. The problem mentioned above was also fixed and the contents now displayed well. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/36b891a1-2420-48d7-b2f2-9aec770b6ed1

**Review by XiaohanMeng — CHANGES_REQUESTED** [review]
Hi @ChengyanOo, I tested this PR and everything worked as expected, though I encountered a bug similar to the issue mentioned by TareqMia. Specifically, after selecting a project and reusable, then clicking "sort by name," the table values change, displaying data from the selected project instead of maintaining the current selection. The solution might mirror the one applied previously by adjusting the handleSort() method. This issue is evident in the last 10 seconds of the video provided.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/111290af-4d32-48e4-b301-51b2e5ce1722

**Review by TareqMia — DISMISSED** [review]
Hey @ChengyanOo, I re-tested this PR and the bug is gone. Great work 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/95d051a7-2c57-4cc5-af2b-558eba421f58

**Review by brandta-1 — DISMISSED** [review]
# Review
All drop down and sorting menus work correctly. Page successfully displayed new ```buildingInventoryItems``` created for testing.

# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/f4b04205-e3f0-4e89-bd6c-a81605e425bf

01_custom_item

**Comment by ChengyanOo** [comment]
Hey @TareqMia, @ShengjieMao, @meetpadhiar4, @XiaohanMeng, 

Apologies for the inconvenience, but I've made some significant updates to the PR after your initial reviews. When you have a moment, I'd really appreciate it if you could take another look at the changes. Your insights on any potential code smells or suggestions for improvement would be incredibly valuable. Please let me know your thoughts when you get a chance.

Thanks for your understanding and help!

**Review by meetpadhiar4 — CHANGES_REQUESTED** [review]
Hi, I reviewed your PR and all the 3 components are rendered correctly without any errors and the sorting and filtering functionalities work without any issues. However in the reusables component when the view button, in the purchases column, is pressed it loads up a blank screen instead of a modal. This happens only in reusable component and not in other two components. Also, there are blank values in the table, I am not sure whether resolving this issue is in scope of this PR. Please refer the videos attached for reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/1ab3aaad-3636-46ad-92ea-481d88b0deea


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/e1c54fda-6f70-43b8-bf21-46a130eb8f56

**Comment by ChengyanOo** [comment]
> Hi, I reviewed your PR and all the 3 components are rendered correctly without any errors and the sorting and filtering functionalities work without any issues. However in the reusables component when the view button, in the purchases column, is pressed it loads up a blank screen instead of a modal. This happens only in reusable component and not in other two components. Also, there are blank values in the table, I am not sure whether resolving this issue is in scope of this PR. Please refer the videos attached for reference.
> 
> 
> 
> 
> 
> https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/1ab3aaad-3636-46ad-92ea-481d88b0deea
> 
> 
> 
> 
> 
> https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/e1c54fda-6f70-43b8-bf21-46a130eb8f56
> 
> 
> 
> 

@meetpadhiar4 Thank you for your comment, these components were not planned to be addressed in this PR, so we can ignore it for now.

**Review by XiaohanMeng — CHANGES_REQUESTED** [review]
Hi, I retested this PR and found that the filtering, sorting, as well as the update and purchase buttons, mostly worked great! However, I encountered a small issue: selecting the blank option under 'material' results in 'No items data' displayed in the table. Yet, when 'All' is selected for material, data with empty names becomes visible. Please refer to the attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/b9622b13-ab4a-4c71-8875-e580b2a84b9a

**Comment by ChengyanOo** [comment]
> Hi, I retested this PR and found that the filtering, sorting, as well as the update and purchase buttons, mostly worked great! However, I encountered a small issue: selecting the blank option under 'material' results in 'No items data' displayed in the table. Yet, when 'All' is selected for material, data with empty names becomes visible. Please refer to the attached video.
> 
>  1956-result.mov

Hey @XiaohanMeng ,

Thanks for pointing out the filter issue with the 'material' selection. Found the problem was due to entries missing projectName and itemName, which shouldn't happen according to our database rules. I've fixed it so these entries won't show up in the UI anymore. This should clean up the filter behavior you mentioned.

Let me know if you spot anything else!

**Review by TareqMia — CHANGES_REQUESTED** [review]
Hi @ChengyanOo, I retested the PR and everything looks and functions well. I did find a very small issue. When any modal is open, there seems to be extra space created by a scroll bar that pushes the table to the left. The table shifts back when the modal is closed. I checked the previous versions (consumables and materials) and the extra scroll bar wasn't there. You can see the videos for reference: 

### Before

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/bb0a1d78-2278-42a2-a4a9-5468b60eed08

### After 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/8d74473c-1bc1-4af2-963b-b56c798513c1

I think the issue might be related to not setting ```overflow-y: hidden``` somewhere. Functionally, everything works fine and great job on this refactor. It will be very useful for other developers (especially me!) I just wanted to bring this to your attention.

**Review by ClemarNunes — CHANGES_REQUESTED** [review]
I tested your PR and I didn't find any problems other than those already mentioned above such as:

  selecting the blank option under 'material' results in 'No item data' displayed in the table

  extra space created by a scroll bar that pushes the table to the left.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/65df7cd4-6d85-4942-800c-df8c85c8a957

**Comment by ChengyanOo** [comment]
> Hi @ChengyanOo, I retested the PR and everything looks and functions well. I did find a very small issue. When any modal is open, there seems to be extra space created by a scroll bar that pushes the table to the left. The table shifts back when the modal is closed. I checked the previous versions (consumables and materials) and the extra scroll bar wasn't there. You can see the videos for reference:
> 
> ### Before
>  Screen.Recording.2024-03-02.at.7.04.05.PM.mov 
> 
> ### After
>  Screen.Recording.2024-03-02.at.7.16.59.PM.mov 
> 
> I think the issue might be related to not setting `overflow-y: hidden` somewhere. Functionally, everything works fine and great job on this refactor. It will be very useful for other developers (especially me!) I just wanted to bring this to your attention.

@TareqMia @ClemarNunes 

Can you guys please review the UI again?, I double check the UI and didn't trigger the extra space issue. I have attached a video of me testing with Safari and Chrome.

I have fixed the 'No item data' issue by deleting all data with no name(Since I believe these data should be handled on the backend on the first place since they are required fields according to the database scheme).

**Comment by dhairya-mehta** [comment]
Hi Chengyan, verified and checked the PR for all the filters:
image

**Review by sucheta90 — APPROVED** [review]
Hello @ChengyanOo , everything works as intended. I was able to sort the project both ways(ascending and descending) and by Name. By clicking View under purchase, was able to see the Modals. Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/8a2549f2-533a-4a3a-ad9d-24fa276df192

**Review by navyasrim — APPROVED** [review]
Hi,
Tested the PR and the checked for filter and sorting ..both are working as mentioned.. 
PR-1956
attached screenshot..

**Pull request merged**
