### PR TITLE
Xiaoyu Add “Media/DropBox Link” field to the new-user setup page

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
1.(PRIORITY HIGH) Jae: Add “Media/DropBox Link” field to the new-user setup page (WIP Xiaoyu)
a.Admin Login → Other Links → User Management → Create New User
b.I’d like this link above the Google Doc field in the picture below
Screenshot 2023-06-19 at 3 26 00 PM

i.Should be optional
ii. Should say “Weekly Summaries Link” on left and “DropBox Folder of Folders” in the field 

c.If entered, this media links should be auto-filled where the person enters their weekly summaries. 
i. If they go to edit it there, a popup should show that says: “Whoa Tiger! Are you sure you want to do that? This link was added by an Admin when you were set up as a member of the team. Only change this if you are SURE your new link is more correct than the one already here.”  
d.If entered, this media links should also be added as “WEEKLY SUMMARIES LINK” to the user’s profile with the other links:

## Main changes explained:
- Link mediaUrl to AdminLinks googleDocLink
- Modify mediaURL will popup warning
- Add confirm to edit the mediaURL
- Update the user setup
- Edit mediaUrl will update AdminLinks googleDocLink and Profile Link
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user create a user and enter the weekly summary link
4. log in as the created user and check the profile weekly summary link and try modify the summary link

## Note:
Include the information the reviewers need to know.
Create a user with weekly summary link
Screenshot 2023-06-21 at 11 45 08 AM
Screenshot 2023-06-19 at 3 02 28 PM
Then test like this:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/35a3e81b-5658-4b3b-95c1-cf599391c617

### CODE REVIEW

**Review by jonathancarpena — DISMISSED** [review]
@20chen-7 Good job on the changes and everything works like intended! 👍 

The placeholder text is much better than the one before! The weekly summary link was auto-filled  when creating a new weekly summary. After editing the link, the popup did show up. After clicking SURE I was allowed to edit the link and it was updated on my profile.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/f29d79ba-a938-4ceb-b2f4-b0a1d10e92be

**Review by yufeiStella — APPROVED** [review]
Good job! It works as intended.
Screen Shot 2023-06-22 at 18 49 59

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/e8b00460-0b76-4f18-872d-0b7a98fa7b0d

**Comment by AnishPandita** [comment]
Hi @20chen-7 I tested the PR and it works as intended. The link was autofilled in the text box and displayed expected behaviour.
 
Screenshot 2023-06-22 at 8 15 38 PM
Screenshot 2023-06-22 at 8 18 22 PM

**Comment by rachnapandya** [comment]
Checked everything mentioned. Works as intended.
whoatiger

**Review by Chuehleo — DISMISSED** [review]
Everything work as intended, great job!
Screenshot 2023-06-23 024403

**Review by eduhorta — DISMISSED** [review]
Working as intended! Great job! 👍
Screenshot 2023-06-23 09-48-19

**Review by cvtqx — APPROVED** [review]
Works as described! 

The correct media link is displayed in a newly created account's weekly summary:
Screen Shot 2023-06-23 at 9 55 31 AM

When attempting to edit the link, a popup warning appears:

Screen Shot 2023-06-23 at 9 55 46 AM

When checking in a user's profile section the same link appears there.

**Review by one-community — CHANGES_REQUESTED** [review]
Resolve the merge conflicts and I’ll move this one to final review

**Comment by 20chen-7** [comment]
> Resolve the merge conflicts and I’ll move this one to final review

Finished

**Review by NidaZaki — APPROVED** [review]
Great work! Works as intended!

**Review by AuroraLovesWhales — COMMENTED** [review]
Hi @20chen-7. I have tested your PR and everything is working as intended. The only thing is that the text in the Warning popup is not complete (see the screenshot below).
image


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/55fd5761-306c-418b-82fe-47144c5c6992

**Pull request merged**
