### PR TITLE
refactor team member task logic

### PR DESCRIPTION
**Pull request by Cirakuze**
# Description
Refactor the logic in the TeamMemberTask component.

## Main changes explained:
Simplifying how the `totalHoursRemaining` and the `activeTasks` are computed.

## How to test:
Check the total hours remaining and the active tasks on the dev branch, and compare them on this branch.

## Screenshots or videos of changes:
| BEFORE | AFTER |
|--------|--------|
| DEV | FEATURE |

### CODE REVIEW

**Review by sxiong5 — APPROVED** [review]
Hey @Cirakuze, I have tested your changes, and the app has no influence. Nice coding style! 👍
Screenshot 2023-08-08 at 15 53 42 (2)

**Review by jerryren527 — APPROVED** [review]
Hello, everything looks great to me! Great job!

development-vs-refactor-team-member-task-logic-side-by-side

**Review by luisarevalo21 — APPROVED** [review]
Hello @Cirakuze 
I tested your PR and looks great.

I also reviewed your code and great job refactoring it! 

Screenshot 2023-08-08 at 2 03 28 PM

**Review by TheDescendant39 — APPROVED** [review]
Hi @Cirakuze, I reviewed your changes and they did not affect the app. Great work.

Before (on "development" branch):

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/7e249ea7-c854-4050-b4dc-83b488c95f26

After(on "bk/refactor-team-member-task-logic" branch):

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/a7b7515f-537e-41bf-be3b-2344f1ec6f1f

**Review by navneeeth — APPROVED** [review]
LGTM! The refactoring you've done with the usage of 'reduce' and 'some' array methods enhances the readability and efficiency of the snippet while it does not change the output in the UI when compared with the development branch as noted below:
**Development:**
dev branch
**This PR:**
new branch

Good implementation!

**Review by robertoooc — APPROVED** [review]
Hi @Cirakuze, when testing your changes I didn't notice any differences in the UI. Good job with the array operators, they really help make the code easier to read.

Development branch:
BeforeIMG

This branch: 
AfterIMG

**Review by winghojackyli — APPROVED** [review]
Everything looks the same as the development branch. 

### This Branch
Capture1

### Development Branch
Capture2

**Review by yurisokolovicz — APPROVED** [review]
Dear @Cirakuze 

The refactored logic for team member tasks is functioning properly, just as before. Kindly review the software in the development branch and your branch for comparison.

**development:**


Screenshot from 2023-08-09 11-27-23


**refactored:**


Screenshot from 2023-08-09 11-30-04

**Comment by iTvX** [comment]
As I checked, there is no difference at all, good job!
before:
QQ截图20230809122432
after:
QQ截图20230809122548

**Comment by Lin1404** [comment]
Hi @Cirakuze , I have tested this PR and found no different between this branch and dev branch.

image
image

**Review by Lin1404 — APPROVED** [review]

**Review by Lin1404 — APPROVED** [review]

**Comment by Jiyuanxia** [comment]
Hi @Cirakuze , I have reviewed your PR and there is no difference between this branch and the dev branch. Good job.

Current branch
Screenshot 2023-08-09 170603

Dev branch
Screenshot 2023-08-09 170837

**Review by Jiyuanxia — APPROVED** [review]
Hi @Cirakuze , I have reviewed your PR and there is no difference between this branch and the dev branch. Good job.

Current branch
Screenshot 2023-08-09 170603

Dev branch
Screenshot 2023-08-09 170837

**Review by DavidC0126 — COMMENTED** [review]
Hi @Cirakuze, I tested your PR and it works as intended.

DEV:
Dev

This branch:
this_branch

**Review by ThapeloMasasa — APPROVED** [review]
The code works as expected on development and bk/refactor-team-member-task-logic

bk/refactor-team-member-task-logic
Screenshot 2023-08-09 at 4 36 37 PM


on development
Screenshot 2023-08-09 at 4 37 29 PM

**Review by yunshan111 — APPROVED** [review]
LGTM, the refactored code is more straightforward and it has better readability.

**Review by eduvarjaor — APPROVED** [review]
Hi @Cirakuze 

You made a good job. Everything working as intended. 

Before: before
After: after

**Review by veronicacheng2 — APPROVED** [review]
Hi @Cirakuze, I have tested the PR and everything looks the same

### development branch:
image



### bk/refactor-team-member-task-logic branch:
image

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this looks good on my device.
image

**Review by ramyaram2092 — APPROVED** [review]
Good job on the refactoring 
**Dev**:
PR1105-Dev

**Refactor branch** : 
PR1105-CurrBranch

**Review by n0vay — APPROVED** [review]
Great Job on the code. Works as Intended.
image

**Comment by beblicarl** [comment]
I can confirm that this functionality works as intended

Screenshot 2023-08-11 112254

**Review by beblicarl — APPROVED** [review]

**Review by eduhorta — APPROVED** [review]
Working as expected.
Good job! 👍

Before:
image

After:
image

**Pull request merged**
