### PR TITLE
Ramya Unit Test :UsersProfile/ EditableModal/roleInfoModal

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit test for src/components/UsersProfile/ EditableModal/roleInfoModal

## Main changes explained:
-  New files
      - **_roleInfoModal.test.js_** : unit test cases 

## How to test:
1. check into current branch
2. do npm test roleInfoModal.test.js
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Review by TareqMia — APPROVED** [review]
Hi @ramyaram2092, I tested this PR and all the tests passed 👍 . 
A suggestion would be to add a test to verify that the modal closes when the close button is pressed. Other than that, keep up the good work 👏 
Screenshot 2024-02-10 at 8 10 39 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 24 - PR2

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and all tests passed.

 
Captura de tela 2024-02-11 052213

**Review by AaronPersaud — APPROVED** [review]
Hi Ramya, I've tested and all the tests have passed! Good job.

image

**Review by 666saofeng — APPROVED** [review]
All tests passed and please refer to the image for the detail
image

**Review by meetpadhiar4 — APPROVED** [review]
Hi, tested your PR and all the test cases have been passed. Please refer the screenshot attached.

PR 1938

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
