### PR TITLE
Shefali colorsGenerator Unit Test

### PR DESCRIPTION
**Pull request by SMitta11**
# Description
Unit test for `src/components/common/PieChart/colorsGenerator.js`

## Main changes explained:
Added 2 extra test cases and refactored test case to test directory under PieChart folder to check for the following
- if numberOfColors exceeds the length of pieChartColors
- test if number of colors are 0

## How to test:
1. check into current branch
2. do `npm install`
3. do `npm test colorsGenerator.test.js`

#Screenshot while running:
Screen Shot 2024-09-12 at 11 53 17 PM

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and all test cases passed successfully

Screenshot 2024-09-13 143233

**Review by RishithaMamidala — APPROVED** [review]
@SMitta11 
Reviewed the PR, It passes all the test cases.
PR 2670

**Review by ArtemisNyx3 — APPROVED** [review]
image

Test cases passed 
code looks clean and readable

**Review by Saniya98 — APPROVED** [review]
All test cases have passed
image

**Review by jinxyou — APPROVED** [review]
All test cases have passed. Great work!
Screenshot 2024-09-13 220658

**Review by manikittu810 — APPROVED** [review]
Hello @SMitta11 
Everything is working as mentioned.
Screenshot 2024-09-13 at 11 28 35 PMThanks.

**Review by mohangadde1 — APPROVED** [review]
image
Two additional test cases executed successfully

**Comment by mianmiantea2019** [comment]
Everything is working as mentioned.

image

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture2670

**Review by Abhinav-Ankur786 — APPROVED** [review]
This is working as per PR and test cases are passing.

PR #2670

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (201)

**Comment by geetamatkar** [comment]
Hi @SMitta11 ,
Tested this PR and all test cases have passed.

PR2670

**Review by Abhinav-Ankur786 — APPROVED** [review]
Please ignore

**Review by KurtisIvey — APPROVED** [review]
Screenshot 2024-09-21 at 7 13 05 PM


Fantastic job! Your test file is comprehensive, in the right location, and well written. You cover all the different scenarios. Zero complaints from me.

Merge with confidence.

**Comment by SatyashanthiT** [comment]
I have reviewed the changes in the PR for the colorsGenerator unit test, and everything is working as expected. The test cases are functioning correctly and the refactoring looks good.
image

**Pull request merged**
