### PR TITLE
Bailey remove cropping from badges

### PR DESCRIPTION
**Pull request by BaileyM96**
# Description
(PRIORITY LOW) Jae: Remove the code cropping the badges.
Badges should show fully and not be cropped around the edges.

## Main changes explained:
- Made changes to the Badge Component.
- Main changes were from the Badge.css file such as .badge_image_sm, md, and lg.
- These changes take place anywhere the Badges are displayed.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as either admin user, volunteer, or owner
4. go to dashboard→ Badges→ New Badges Earned→  Badges Earned Before Last Week→  Badge Report.
5. go to View Profile→ Featured Badges→ Assign Badges→   Select Featured

## Screenshots or videos of changes:

BEFORE CHANGES
Badges BEFORE

AFTER CHANGES
Badges AFTER

Badge Report Summary

Badge Image Medium

## Note:
Badge Management functionality in other links is still being worked on for a other PR  so no badges will appear there right now.

### CODE REVIEW

**Review by tsunami776 — APPROVED** [review]
Hi @BaileyM96, I tested locally and it works as described. Now badges show fully in the following sections. Great work!
1. Profile->Badges
before:
#1382before
after:
#1382after

2. Profile->Select Featured/Assign Badges
before:
CleanShot 2023-10-05 at 21 43 33
after:
CleanShot 2023-10-05 at 21 44 06
3. Dashboard->Badges
before: 
CleanShot 2023-10-05 at 21 44 49
after:
CleanShot 2023-10-05 at 21 45 17
4. Report->People->User->Show Badges
CleanShot 2023-10-05 at 21 53 37
5. Report->People->User->Preview Badges
CleanShot 2023-10-05 at 21 53 46
6. Badge management->Assign Badge
CleanShot 2023-10-05 at 21 54 21

**Review by luisarevalo21 — APPROVED** [review]
Hello @BaileyM96,

I tested your PR and works as intended. Great work! 
Viewing the badges on the dashboard, user's profile, selecting badges and assigning badges no longer appear cropped. 

Great work! 
Screenshot 2023-10-05 at 8 14 29 PM
Screenshot 2023-10-05 at 8 14 50 PM
Screenshot 2023-10-05 at 8 15 01 PM
Screenshot 2023-10-05 at 8 16 05 PM
Screenshot 2023-10-05 at 8 16 18 PM

**Comment by lacnoskillz** [comment]
Dear @BaileyM96,

I have thoroughly tested your Pull Request, and it functions as expected. Fantastic job!
The issue with badge cropping in various views like the dashboard and user's profile has been successfully resolved. Additionally, the problem of badges appearing cropped when selected or assigned is now resolved as well.

Excellent work!

Screenshot (204)

Screenshot (203)
//

Screenshot (202)

Screenshot (201)
808b147)

Screenshot (199)

Screenshot (200)

Also I noticed a possible bug that's unrelated to your changes
It appears that a maybe redundant alert pops up when making changes to badges. 
ie: Select featured or Assign Badges
Screenshot (207)
Screenshot (208)

**Review by DavidC0126 — APPROVED** [review]
Hi @BaileyM96 I tested the PR and it works as described.

Profile:
profile

Edit:
edit

Assign:
assign

Dashboard:
db

**Comment by Vishala09** [comment]
Awesome work!! 
**BEFORE**:
image

image


**AFTER**:
_Badge Summary:_
image

_New Badges Earned:_
image

_User's profile:_
image

_Weekly Summary Reports Page:_
image

**Review by Vishala09 — APPROVED** [review]

**Review by yangfan2001 — APPROVED** [review]
I've tested your PR locally. Everything looks excellent, and the cropping issue has been resolved. Fantastic work!

View Profile
image
View Profile -> Select featured
image
View Profile -> Assign Badges
image
Dashboard -> badges
image
Dashboard -> badges -> Badges Report
image

**Comment by olenadanykh** [comment]
hi @BaileyM96 . I've tested your PR locally, and I'm pleased to confirm that everything appears to be in excellent shape. The cropping iss

ue has been successfully resolved. Great job!

**Review by lacnoskillz — APPROVED** [review]
Dear @BaileyM96,

I have thoroughly tested your Pull Request, and it functions as expected. Fantastic job!
The issue with badge cropping in various views like the dashboard and user's profile has been successfully resolved. Additionally, the problem of badges appearing cropped when selected or assigned is now resolved as well.

Excellent work!

Screenshot (204)

Screenshot (203)
//

Screenshot (202)

Screenshot (201)
808b147)

Screenshot (199)

Screenshot (200)

Also I noticed a possible bug that's unrelated to your changes
It appears that a maybe redundant alert pops up when making changes to badges. 
ie: Select featured or Assign Badges
Screenshot (207)
Screenshot (208)

**Review by eduhorta — APPROVED** [review]
Image badges are displaying as expected 👍 

Before:
image


After:
image

Also, I know this is not related to this PR, but, is anyone else getting this message when assigning new badges?

image

**Comment by beblicarl** [comment]
This functionality works as intended. Great work !!

badges--1

badges--2

badges--3

**Review by beblicarl — APPROVED** [review]

**Review by JYXiao-2021 — APPROVED** [review]
Hi, it works as intended.
Screenshot 2023-10-06 at 5 37 35 PM
Screenshot 2023-10-06 at 5 39 03 PM

**Comment by RheaWu1212** [comment]
Works as expected, great job!
before:
Screen Shot 2023-10-07 at 10 07 12

after:
Screen Shot 2023-10-07 at 10 10 21

**Comment by BaileyM96** [comment]
@one-community this PR has 9 approvals this can be resolved and closed out for your final testing

**Comment by Shreyj14** [comment]
Hi, This PR works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/1bd334cb-91aa-45eb-af69-b3df66fc2af8

**Review by wantingxu7 — APPROVED** [review]
Hi, the changes in this PR LGTM. Good work!

profile page:


Select featured:


dashboard:

**Review by zuhang2000 — COMMENTED** [review]
I've tested your PR following your instructions. Everything works perfect! The badges are not cropped now. Good job!
Screenshot 2023-10-07 at 3 14 59 PM
Screenshot 2023-10-07 at 3 14 29 PM

**Comment by AnishPandita** [comment]
Hey I tested the PR and every thing looks fine. Tested for badges on different screens profile, dashboard and featured badge page. Didn't observe any cropping of badges. 
Screenshot 2023-10-07 at 1 02 20 PM
Screenshot 2023-10-07 at 1 02 47 PM
Screenshot 2023-10-07 at 1 03 33 PM

**Review by TuanDinh140194 — APPROVED** [review]
The badget have removed cropping. I have test with owner, admin, and volunteer account. It display as described. 
Screenshot 2023-10-07 171601
Screenshot 2023-10-07 171534
Screenshot 2023-10-07 171515
Screenshot 2023-10-07 172335

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and works as intended. Great work!
Screenshot 2023-10-07 at 10 44 52 PM
Screenshot 2023-10-07 at 10 45 54 PM

Screenshot 2023-10-07 at 10 45 04 PM

**Review by Shubhu0 — APPROVED** [review]
Hi @BaileyM96 Reviewed the PR. It works well and as you can see i had no badges and could later assign badges to my profile

image

image

**Review by KurtisIvey — APPROVED** [review]
pr1382 badges no longer cropped


functions as intended. Badges are no longer cropped. Good job

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
