### PR TITLE
Vishala log materials bm dashboard

### PR DESCRIPTION
**Pull request by Vishala09**
**# Description**
The UI design for Log Materials component is implemented in this PR.
Implements # Phase 2 , WBS : 3.3.3

**## Main changes explained:**
- Created 3 jsx files and 1 css file to build the UI of Log materials page

**## How to test:**
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. log as admin user
4. go to (http://localhost:3000/bmdashboard/logMaterials)
5. verify if the UI matches with the wireframe design attached and check for responsiveness

**## Note:**
Using the same wireframe design of Tool/Equipment for Log Materials. Hence the terms used in the current branch will be related to Log Materials

**## Screenshots or videos of changes:**
Wireframe Design:
image

------------------------------------------------------------------------------------------------------------

**UI Changes:**
image

image

### CODE REVIEW

**Review by yi-lin-1234 — DISMISSED** [review]
Hello, I tested your PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/de49db80-fb6c-41d8-833e-62fcac1080b8

**Comment by beblicarl** [comment]
This functionality works as intended

image

**Review by beblicarl — DISMISSED** [review]

**Review by ChirayuRai — DISMISSED** [review]
All functionality works as the wireframes show and it also is responsive. Great job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/8e2bedcf-5100-457b-b548-54b8aee1e4d2

**Comment by emunkh404** [comment]
Tested UI matches
image
image

**Review by DavidC0126 — DISMISSED** [review]
Hi @Vishala09 I tested your PR and it works as intended!

UI

**Review by lacnoskillz — COMMENTED** [review]
Hello @Vishala09 
I pulled your code and it looks great!
I tested in multiple viewports and the responsiveness looks good
I have found that the buttons get off center when viewing on mobile view ports

image
GalaxyFold Viewport:
image

I also noticed when opening the dropdown of the last item in the list in a mobile viewport it causes things to stick out of their divs

[Untitled_ Oct 18, 2023 12_57 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/351d73f1-369c-4bd6-9ef6-5789c20169e9)

Other than my nitpicky finds it looks great!
Happy coding

**Review by StrawberryCalpico — DISMISSED** [review]
I tested your PR, and it works as expected!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/6f091d06-0632-427c-8686-3579eb4d3b57

**Review by navneeeth — APPROVED** [review]
Hey, @Vishala09! I tested your PR and the changes LGTM! Good implementation! The UI in the `bmdashboard/logMaterials` route matches with the wireframe design attached in the description. The implementation is also responsive for mobile and tablet screen sizes.

## Testing Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/e6a06b48-a89a-43d9-a71b-015a99ce7c3c

**Review by Sssky-18 — DISMISSED** [review]
Hi @Vishala09, I tested this PR, and the UI looks the same as the template. All the buttons are clickable and the dropdown looks fine. For different size of window, the page fits as expected.  Thank you for your contribution! 
 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/8cbe5b7f-036f-4177-8785-a9005c67ac52

**Comment by palakgosalia** [comment]
Hey, I have reviewed the PR and tested it. Looks Good, thank you.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/b6f731f0-13ff-4c77-bc29-cefc68dca7f9

**Pull request closed without merging**
