### PR TITLE
pavanswaroop-fixed-hours-section-to-lessen-vertical-space

### PR DESCRIPTION
**Pull request by pavanswaroopl**
# Description
Fix Dashboard>Task>Edit formatting so it takes up way less vertical space

## Related PRS (if any):
This frontend PR is not related to any backend PR.

## Main changes explained:
Modified Hours cases from a vertical alignment to a 2x2 grid with flexible animations

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ select a Task -> Edit -> Hours Section
6. verify functions for Hours modifications.
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/eb0e2093-09b2-4b08-806a-fffc590c4d59

Screenshot 2024-10-04 at 9 21 40 PM

### CODE REVIEW

**Review by Abi-Liu — DISMISSED** [review]
Just reviewed your changes. The vertical spacing does not look cramped and the text displays nicely.

https://github.com/user-attachments/assets/533c8be5-281e-4308-917e-c938f95c62ac

**Review by one-community — CHANGES_REQUESTED** [review]
Requesting these changes: https://www.loom.com/share/512add9120904baba8d9fde76f7bf76f?sid=7e61d6a8-b842-4e84-8db4-8a33d15540d9

**Comment by pavanswaroopl** [comment]
> Requesting these changes: https://www.loom.com/share/512add9120904baba8d9fde76f7bf76f?sid=7e61d6a8-b842-4e84-8db4-8a33d15540d9

Hi Jae,
As of now reverted the grid changes and kept them side by side, fixed some alignment issues in lower screen sizes before, added warning checks to ensure they spawn only if there is a warning, and added vertical space only when the warning message is displayed to maintain clarity on which field warning message is displayed.

Currently working on the other change suggested 

https://github.com/user-attachments/assets/15307f72-180f-405a-bd56-3f2f3c39624b

Screenshot 2024-10-12 at 10 07 10 PM
Screenshot 2024-10-12 at 10 40 04 PM

**Review by Muhideenthegreat — COMMENTED** [review]
Verification:

The hours row has been modified to be a one-liner as Jae suggested, and is also responsive for other devices as well

Suggested Improvement:

The edit and delete button could be on the same line here, here making the table more organized

**Comment by pavanswaroopl** [comment]
Changes are addressed and everything works now as expected.
Screenshot 2024-10-18 at 1 20 45 PM
Screenshot 2024-10-18 at 1 26 59 PM
Screenshot 2024-10-18 at 5 15 52 PM

**Review by RachanaZha — COMMENTED** [review]
The input boxes are vertically spaced and look neat. 
According to the text suggestions below the input boxes, the best hours should be least, the worst hours should be max and most hours should be between best and worst, however if i enter best as 5 worst as  and most as 9 and submit it , it is still updating successfully.I think user should be restricted  from updating if the best hours , worst hours and most hours do not meet the defined criteria

https://github.com/user-attachments/assets/7d828448-6786-4418-9262-1d70f6f80fe6

**Review by RachanaZha — CHANGES_REQUESTED** [review]
The input boxes are not horizontal alligned in pairs of two as shown in the video by developer. They are vertically alligned.
Also, according to the text suggestions below the input boxes, the best hours should be least, the worst hours should be max and most hours should be between best and worst, however if i enter best as 5 worst as  and most as 9 and submit it , it is still updating successfully.I think user should be restricted  from updating if the best hours , worst hours and most hours do not meet the defined criteria

https://github.com/user-attachments/assets/7d828448-6786-4418-9262-1d70f6f80fe6

**Review by zhiminV — DISMISSED** [review]
Base on the new request change:  https://www.loom.com/share/512add9120904baba8d9fde76f7bf76f?sid=7e61d6a8-b842-4e84-8db4-8a33d15540d9

The feature work as expected. I also checked in both light and dark mode.

https://github.com/user-attachments/assets/efcf3ded-39fa-41fd-8453-fba9aeb086dc

Screenshot 2024-10-26 at 2 22 11 PM

**Comment by zhiminV** [comment]
> The feature did not work as expected , it show vertical for the edit hours. I checked in both light and dark mode
> 
>  Screen.Recording.2024-10-26.at.2.18.21.PM.mov 
> Screenshot 2024-10-26 at 2 22 11 PM

**Comment by zhiminV** [comment]
> The feature did not work as expected , it show vertical for the edit hours. I checked in both light and dark mode
> 
>  Screen.Recording.2024-10-26.at.2.18.21.PM.mov 
> Screenshot 2024-10-26 at 2 22 11 PM

sorry for the mistake, I have checked that the request have change, and all work as expected. so approved it.

**Review by Rupa2400 — APPROVED** [review]
I’ve reviewed your changes in PR #2750. The adjustments have effectively reduced the vertical spacing, resulting in a more balanced layout. The text is displayed clearly and nicely. The feature works as intended, and I also tested it in both light and dark modes. Good job!

PR_2750_1

PR_2750_2

PR_2750_3

**Comment by pavanswaroopl** [comment]
> The input boxes are vertically spaced and look neat. According to the text suggestions below the input boxes, the best hours should be least, the worst hours should be max and most hours should be between best and worst, however if i enter best as 5 worst as and most as 9 and submit it , it is still updating successfully.I think user should be restricted from updating if the best hours , worst hours and most hours do not meet the defined criteria
> 
>  zha_rachana_PR.2750.mp4

Regarding Validations:
I rolled back and tested the previous build, the behavior was the same and it's not in the scope of this particular PR, may be we can report this and open a new bug.

Vertical Alignment:
It was Jae's suggestion to align them vertically

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
