### PR TITLE
Shuhua add google doc icon

### PR DESCRIPTION
**Pull request by Shuhua-L**
# Description
description

## Related PRS (if any):

This frontend PR is related to the [PR762](https://github.com/OneCommunityGlobal/HGNRest/pull/762) backend PR.

## Main changes explained:

- added reusable component `GoogleDocIcon` in `src/components/common/`
- refactored `src/components/WeeklySummariesReport/FormattedReport.jsx` with the new component
- Moved image file to designated assets folder
- Utilized the new component to render icon in tasks tab in `src/components/TeamMemberTasks/TeamMemberTask.jsx`

## How to test:

1. check into current branch
2. do `npm run start:local` to run this PR locally
3. Clear site data/cache
4. Verify icons match those from the reports page
    1. log in as Admin or Owner
    2. compare Google Doc icons in **Dashboard→ Tasks** tab and **Reports → Weekly Summaries Reports** page 
5. Verify volunteers CAN see the icon only if they have access to the Weekly Summaries Reports page
    1. log in as Volunteer
    2. make sure no icon in **Dashboard→ Tasks** tab
    3. log in as Admin or Owner and change the "See Weekly Summaries" permission through **Other Links → Permissions Management → Manage User Permissions → search volunteer name**
    4. go back to Volunteer’s home page, now they should have access to the icons
6. (Optional) Icons changes as adding/removing Google Doc links in user profile settings
    1. log in as Admin or Owner
    2. go to **Welcome, name → View Profile → LINKS** section under profile picture → **Edit**
    3. add or remove Google Doc link, and see icons in dashboard become colored or grey upon refresh

## Screenshots or videos of changes:
Step 4-6: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/2843fed6-5bad-41dd-9e70-a75c07fb9496

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/03b9a403-754f-4ca0-968c-d5e2dbefa84d

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/be61afd6-60b4-4937-ad8f-ba778273ac44

## Note:

1. These potential errors are unrelated
potential errors

### CODE REVIEW

**Review by skaush21 — APPROVED** [review]
Tested the features mentioned.
- logged in as admin checked google icon in tasks, clicked on link opening a new tab
- went to report ->weekly summaries, checked the icons
- gave weekly summaries permission to volunteer, checked to see if icon was visible (it was)
- logged back into admin account, removed permission, icon no longer visible
- updated google doc link by removing and adding a link.
all features worked, no others issues other than the ones you reported.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/ad7b75e3-cfa7-4693-8772-2df70b3afe0c

**Review by XiaohanMeng — APPROVED** [review]
Hi, I tested this PR, and every feature worked as intended! I tested the following:
* Both owners and admins can see the Google Doc icon in tasks and weekly reports, which is clickable when colored.
* Volunteers can see the Google Doc icon when they have the necessary permissions.
* Owners and admins can observe changes in the Google Doc icon's color when a Google link is added or removed.
There is a minor issue: when the owner assigned permissions to a volunteer, this permission became fixed and unclickable. 
Please see the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/1c325eb9-7b6d-45eb-86b5-67f038faa3ad

**Review by MALAV1308 — APPROVED** [review]
Hello , I have reviewed your PR and it is working perfectly. I logged IN as owner and I can able to see google doc icon and if I can add or remove Google Doc Link , I can see gray and colored icon. Apart from this, I can also checked by using volunteer account in weekly report summery and it's working good.  Overall, Great Job! Thank you.

**Review by bhuvan-dv — CHANGES_REQUESTED** [review]
Can you please verify these changes once again @Shuhua-L? I do not see these changes reflecting in your branch `Shuhua-Add_Google_Doc_Icon` when I run the changes locally on my machine. Feel free correct me if I am wrong.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67942070/65529cd7-12e4-41be-be97-351f2efd9458

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and worked as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/d33737f0-ce95-4953-8835-e73d264c13d2

**Review by navyasrim — APPROVED** [review]
Tested
PR-1980
 and working as expected...checked with both admin, volunteer....works as mentioned.

**Review by brandta-1 — APPROVED** [review]
# Review

Able to view icons as an owner and as a volunteer with ```See Weekly Summaries``` permission.

# Video


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/b558592b-4eec-4d87-860a-c338fd06c606

## Volunteer

01_volunteer_icons

02_volunteer_weekly_summaries

**Review by bhuvan-dv — APPROVED** [review]

**Review by PratimaSingh02 — APPROVED** [review]
- Google icon visible on an Owner's account

Screenshot (27)
Screenshot (28)

- Permission to view weekly summaries report disabled on a Volunteer's account
Screenshot (29)

- Google icon not visible on Volunteer's dashboard as no permission given.
- 
Screenshot (30)

- Adding permission to view weekly summaries report to the volunteer's account
Screenshot (32)

- Volunteer can now see the Google icon on the dashboard and the Reports link is now activated for them.
Screenshot (33)

- Volunteer can now also view the icons on the Weekly Summaries Report page
- 
Screenshot (34)

**Review by psharma1984 — APPROVED** [review]
Tested the features mentioned. Admin can see google doc links for tasks and weekly reports and volunteer can see the links with permissions

[screen-capture (1).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/3bc8fb36-256f-420f-a12a-91f439fadf40)

**Pull request merged**
