### PR TITLE
Mingqian fixed discrepancy issues

### PR DESCRIPTION
**Pull request by MQChen211**
# Description
PR_discrepancy
# (WBS) 

## Related PRS (if any):
This frontend PR is not related to any backend PR. Please use the development branch for testing.

## Main changes explained:
Matched filename and the class name.
Change onChange property to onChange={(e) => this.handleUserProfile(e)}

## How to test:
1. check into current branch: mingqian-frontend-testing
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user

### CODE REVIEW

**Review by pshereen — APPROVED** [review]
The class name discrepancy is fixed, and the user profile add feature is working as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/7da90394-dd55-467d-9771-92500792869e

**Review by Ramaruva — APPROVED** [review]
I have verified changes in my local env and changes are working fine 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/a5cf59bf-c2aa-4f44-a806-c061570dbe36

**Review by curiousfancier — APPROVED** [review]
Working as expected 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/27274513/95cda1bb-4c99-43ee-b660-78927f88c0eb

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
