### PR TITLE
Shrada Fix Projects Page UI

### PR DESCRIPTION
**Pull request by shradac**
# Description
Screenshot 2024-07-12 at 11 41 46 PM

## Related PRS (if any):
This frontend PR is related to the development backend PR.

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ click on the other links -> go to projects page
6. verify function -> when loading, you can see the spinning circle along with the loaded projects. Also the spinning circle is centered. (feel free to include screenshot here)
7. verify function ->  At 991px and below, the right and left margin have same padding.
8. verify function -> At 991px and below, in the second column, the down and up arrows are aligned properly.
9. verify function -> At 991px and below, the project search bar is the same length as the table.
10. verify function -> At 768px and below, the two cards on top have left padding.
11. verify function -> At 375px, the search bar's input is not small and is visible.

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/9e61b1fd-2dae-489b-92f6-02bb285ee21b

### CODE REVIEW

**Review by kdaga81 — APPROVED** [review]
1. Spinning Circle
image
2. 375px
image
3. 991px
image

All the functionalities are working as expected!

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected for different pixel values and the spinning circle is also visible before the contents load.

https://github.com/user-attachments/assets/5d93241c-9762-4803-ad18-90121490e7a5

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
The headings on the table are not aligned. Rest everything works fine. 
Good work!

https://github.com/user-attachments/assets/220211ff-1e7a-4869-a1fa-8b1843b66202

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and  Everything works as expected.
Screenshot (98)
Screenshot (97)
Screenshot (99)
Screenshot (100)
Screenshot (101)
Screenshot (102)

**Review by vijay10pk — CHANGES_REQUESTED** [review]
All the changes works as expected.
suggestion: Table headers are not aligned aligned properly and not responsive. Please update it.
Screenshot 2024-07-16 at 10 36 07 PM
Screenshot 2024-07-16 at 10 35 21 PM
Screenshot 2024-07-16 at 10 34 30 PM
Screenshot 2024-07-16 at 10 33 02 PM

**Review by Chetan0606 — DISMISSED** [review]
Tested all the functionalities and everything seems to work perfectly fine.
Screenshot (303)
Screenshot (302)
Screenshot (301)
Screenshot (300)
Screenshot (299)

**Review by SrikanthChowdary495 — APPROVED** [review]
I tested the PR. Everything is working as expected.
And tested whether the Spinning Circle is centered or not. At 991PX below the right and left margins have the same padding & Up and down arrows are working. The project search is the same length. At 768px and below the top two cards have the same padding. At 375PX the search bar is also visible. 


https://github.com/user-attachments/assets/7f5135a6-92de-4df0-81d5-607eea313257

**Review by vijay10pk — DISMISSED** [review]
Requested changes are made and all changes changes works as expected.
Screenshot 2024-07-19 at 11 17 51 PM
Screenshot 2024-07-19 at 11 18 54 PM
Screenshot 2024-07-19 at 11 18 32 PM
Screenshot 2024-07-19 at 11 18 18 PM

**Review by Pranay-ai — APPROVED** [review]
Hi Shrada,

I've reviewed the PR and everything looks good. The UI functions as expected. 
Thank You
image
image
image
image

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.

https://github.com/user-attachments/assets/99c74ced-e7cb-48f5-a29e-0b68bb354dad

**Review by cvtqx — APPROVED** [review]
All the listed UI fixes of the projects page have been implemented well. Good job!
See video testing:


https://github.com/user-attachments/assets/5b261abf-a6b1-4240-bb79-cd934ce8b0cb

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
