### PR TITLE
TuanDinh_InfringementsViz_UnitTest

### PR DESCRIPTION
**Pull request by TuanDinh140194**
# Description
Create Unit test for InfringementsViz.jsx

## Main changes explained:
- Add new file InfringementsViz.test.js
- The file implement 7 test case for InfringementsViz.jsx
- In InfringementsViz.test.js, the file have test if the InfringementsViz component renders without crashing, test if it renders the button to show the graph, and check the component will not show the modal initially. Moreover, it test if component renders the graph when the "Show Infringements Graph" button is clicked, displays the modal when the "Show Infringements Graph" button is clicked, displays close button when the "Show Infringements Graph" button is clicked. Finally, modal closes when "Close" button in the modal footer is clicked. 
…

## How to test:
1. check into current branch
2. do `npm install`
3. do `npm test InfringementsViz.test.js` to run the test
4. Verify all 7 test cases have passed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/c52173f0-8c95-4b20-a41c-5c98b2bcdbb5

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by palakgosalia** [comment]
Hey, I reviewed your code and ran the test. All 7 out of 7 test cases passed.  Thank you

image

**Review by DavidC0126 — APPROVED** [review]
@TuanDinh140194 Hi I tested the PR and it works as intended.

Screenshot 2023-11-27 at 4 45 53 PM

**Review by ZichanYang324 — APPROVED** [review]
All the test cases have passed, well done!

PR1587

**Review by pika-chu11 — APPROVED** [review]
Hi @TuanDinh140194 , the test passed on my end! Great Job!

PR 1587

**Comment by beblicarl** [comment]
All tests passed succesfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
