### PR TITLE
MonthlyEffort and OwnerMessage tests

### PR DESCRIPTION
**Pull request by LucileTech**
# Description

<google-sheets-html-origin>

src/components | file | has unit tests
-- | -- | --

<google-sheets-html-origin>

MonthlyEffort | MonthlyEffort.jsx | Yes. Need to move the file under the test folder
-- | -- | --

<google-sheets-html-origin>

OwnerMessage | OwnerMessage.jsx | No
-- | -- | --

https://docs.google.com/spreadsheets/d/1t26Y9h3yRJAfvaWbveRzOz28plXWNgbe3A8Ceiqwyu4/edit#gid=0

## Main changes explained:
MonthlyEffort tests moved and OwnerMessage tests created

## How to test:
1. check into the current branch and git pull
2. run the command `npm test -- --testPathPattern=src/__tests__/OwnerMessage.test.js` 
3. Check if the tests are passing
4. run the command `npm test -- --testPathPattern=src/__tests__/MonthlyEffort.test.js`
5. Check if the tests are passing

### CODE REVIEW

**Comment by Vishala09** [comment]
Great job! Reviewed the test files!
All tests cases passed!

image

image

**Review by Vishala09 — APPROVED** [review]

**Review by yangfan2001 — APPROVED** [review]
Hi! I have tested your PR, all tests were passed. Great Job!
image
image

**Review by DavidC0126 — APPROVED** [review]
Hi @LucileTech I tested your PR and it works as intended.

**Comment by olenadanykh** [comment]
hi @LucileTech .
Reviewed your PR, All tests cases passed! Great Job!!!
PR1378
PR1378-2

**Review by wantingxu7 — APPROVED** [review]
Hi @LucileTech 
I just tested it and everything LGTM. Great work.

**Review by harshidad — APPROVED** [review]
Tested PR. All test Pass. Great Work!
PR#1378_MonthlyEffort
PR#1378_OwnerMessage

**Comment by emunkh404** [comment]
Hello @LucileTech,

I have thoroughly tested it, and everything has passed successfully.

image
image

**Comment by Shreyj14** [comment]
Hi @LucileTech all the test cases passed.
Great work.
 
Screenshot 2023-10-05 at 4 01 47 PM
Screenshot 2023-10-05 at 4 01 24 PM

**Review by Shreyj14 — APPROVED** [review]

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended! Great job!

week 6 - PR2
Weeik6 -PR2(@)

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. Everything works as expected. All test cases are passing.

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-10-06 042713
Screenshot 2023-10-06 042623

**Review by Sssky-18 — APPROVED** [review]
Hi @LucileTech, I have tested this PR, and it worked as expected. All the test cases were passed so I approved this request. 

PR#1378_1

PR#1378_2

**Review by lacnoskillz — APPROVED** [review]
Hello Lucile
After pulling your changes and running the commands you shared I found that all the tests have passed!
Nice work
image
image

**Comment by emunkh404** [comment]
Test cases passed!
image

**Comment by beblicarl** [comment]
Both tests passed successfully

image

image

**Review by beblicarl — APPROVED** [review]

**Review by JYXiao-2021 — APPROVED** [review]
Hi, it works as intended and there's no error.
Screenshot 2023-10-06 at 5 20 29 PM

**Review by JeffLi117 — APPROVED** [review]
Tests passed, LGTM! Good job.

image
image

**Comment by RheaWu1212** [comment]
both tests were passes, great work!

Screen Shot 2023-10-07 at 10 32 14
Screen Shot 2023-10-07 at 10 32 41

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following the instructions. All test cases passed. The test code also looks good to me. 
Screenshot 2023-10-07 at 3 17 45 PM
Screenshot 2023-10-07 at 3 17 38 PM

**Review by TuanDinh140194 — APPROVED** [review]
I have review all the test case. All the test case have passed.
Screenshot 2023-10-07 175439
Screenshot 2023-10-07 175423

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
