### PR TITLE
Shrada - Fix profile team code dropdown

### PR DESCRIPTION
**Pull request by shradac**
Screenshot 2024-09-06 at 7 31 46 PM
After speaking with Jae, we have decided to update the position of "our" suggested dropdown since we cannot update the position of browser's autocomplete dropdown.

## Related PRS (if any):
This frontend PR is related to the development backend PR.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ View Profile → Tasks
6. Create autocomplete dropdown for the 'team-code' input field by following the steps in the video.
7. Verify that the browser's autocomplete dropdown and our suggested dropdown doesn't overlap.
8. Now verify these in different screen sizes as shown in the video.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/64227b9f-8641-4383-b5b0-de4f4f9db726

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by jinxyou — APPROVED** [review]
The dropdown of the team code is working automatically. Great work!
image

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

PR 2647
PR 2647-1

Thank You

**Review by panchalvatneu — CHANGES_REQUESTED** [review]
The autocomplete dropdowns are still overlapping for me
https://github.com/user-attachments/assets/95b391e7-ac1c-4b05-9945-6ab8caa982dc

**Review by sam19981 — APPROVED** [review]
Changes work as expected.
Screenshot 2024-09-07 at 8 26 40 PM
Screenshot 2024-09-07 at 8 44 03 PM
Screenshot 2024-09-07 at 8 44 28 PM

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.
Screenshot 2024-09-08 021241

**Review by ddshah878 — APPROVED** [review]
Changes work as expected. Good job!

Screenshot (54)
image

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and works as expected.

Screenshot 2024-09-11 155137

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/3952a5bf-9a69-42e9-959b-fdf2967834e9

**Review by mohangadde1 — APPROVED** [review]
image
changes are working as expected.

**Comment by mianmiantea2019** [comment]
everything works as expected!

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
