### PR TITLE
Xiaoyu - Make moving summary to another week reset the summary checkmark

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description

1. (PRIORITY MEDIUM) Jae: Make moving summary to another week reset the summary checkmark

a. If someone submitted their summary late for the week, and then forgot to submit it for the previous week and instead submitted it for this week, then it gets logged for this week and that (correctly) gives the green summary submitted checkmark. In cases like this, someone will sometimes need to move that summary to the last week. Right now, the green checkmark stays. If a summary is moved from this week to any other week, it should reset the checkmark. 

b. What we need is a "Move" button. This button will give the option to move the summary to "last week" or "week before last" and then open the submit modal with the information that is being moved.
Moving like this should clear the summary field for the current week and reset the green check so it’s clear the person still needs to submit a (new) summary for this week.

[Here's a video](https://www.dropbox.com/s/gu9m0mk9s2pqrdi/Move%20Summary%20Bug.mov?dl=0)

## Main changes explained:
- Add 'weekSelect' and creat checkbox to make sure you want to move the submitted summary
- The move button will show once the moveConfirm checkbox is clicked , this dropdown menu includ four options( 'this week', 'last week', Week Before Last', 'Three Weeks Ago'
- Create 'toggleMove' function to reset the selected removed content and switch to moveSelect week.
- - The activeTab will switch to moveSelect week.
- Disabled current week options in the current tab.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ 'Weekly Summary Due Date(click to open)→ select the rest three options, and check the content and green checkmark after submiting the summary.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/bdba5509-7dd6-47af-b6fc-22e9e8ef05d1

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/7c4a487a-9d21-40e3-a8e0-d86b0664f105

## Note:
After submitting the summary, you may require to refresh the website to see the green checkmark change.

### CODE REVIEW

**Review by jonathancarpena — APPROVED** [review]
@20chen-7 Good job implementing this! 👍

I submitted a summary for both this week and last week. The last week submission did not trigger this week's submissions and was saved to last week's instead. I did have to refresh to see the update for this week's submission just like you said. Aside from that, I really like the drop down! 😁 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/257df6ec-0427-4471-8462-92138fd78e32

**Comment by 20chen-7** [comment]
> @20chen-7 Good job implementing this! 👍
> 
> I submitted a summary for both this week and last week. The last week submission did not trigger this week's submissions and was saved to last week's instead. I did have to refresh to see the update for this week's submission just like you said. Aside from that, I really like the drop down! 😁
> 
>  2023-06-22.15-38-36.mp4

First of all, thank you for your suggestion! This is a good point. In this situation, we suppose that moving summary is rare. So I am not sure if the case you mention is out of scope or not. I need to double-check.

**Review by yufeiStella — APPROVED** [review]
It can be successfully moved to another week!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111897624/e9ab4666-af4d-4805-a528-887e3039ec64

**Review by KurtisIvey — APPROVED** [review]
Functions perfectly. Couldn't get this to mess up no matter what I tried to do. I was deleting local storage, logging into different users, etc. Great Job!

pr930 works

**Comment by rachnapandya** [comment]
Works very well. Great job! @20chen-7 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/74d3ff5a-41f1-43aa-8a9f-88f4131585b1

**Review by Chuehleo — APPROVED** [review]
Everything work as intended, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/c51830cf-c079-40f8-a4da-d68dc73cfa3c

**Review by eduhorta — APPROVED** [review]
It's working as intended! Nice job! 👍


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/15b20311-0e5f-4552-b45c-9c843c31fdcf

**Review by cvtqx — APPROVED** [review]
Works as intended, great job!

Video review:
https://www.dropbox.com/home/Highest%20Good%20Network%20Team/Olga/Videos?preview=PR%23930.mov

**Comment by one-community** [comment]
Excellent job everyone, moving to final review!

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @20chen-7. I have tested your PR and everything is working as intended. Great job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/6dee9270-8baa-4f1e-b00a-2a8a31e5e594

**Pull request merged**
