### PR TITLE
Zijie lint fix for reports component Phase 2

### PR DESCRIPTION
**Pull request by iTvX**
# Description
Lint fix for Reports component, this is phase 2.

## Files changed

- PeopleTableDetails.jsx
- ProjectTable.jsx
- ReportTableSearchPanel.jsx
- TeamTable.jsx
- TimeEntriesViz.jsx
- index.js

# How to Test

To test this pull request:

- Check out the current branch
- Run `npm install` and `npm run start:local` to run this PR locally  
- Log in as an admin user
- Go to Reports,  Check functionality is the same as before.
- Check all the functionality of the report is the same as before, and see if any bugs have appeared.(Please record a video)

Optional:
- Set up ESLint in VSCode/ IntelliJ IDEA, I personally use IntelliJ IDEA
- `cd src/components/Reports`
  - Run `npx eslint `for the files: PeopleTableDetails.jsx  ProjectTable.jsx  ReportTableSearchPanel.jsx  TeamTable.jsx  TimeEntriesViz.jsx  index.js

I have complete confidence that **the code will pass the ESLint tests.** Therefore, I kindly request that you f**ocus on testing the frontend**. Specifically, please ensure that the **report functionality remains consistent** with how it operated previously. Thank you for your time and effort!

Screenshot:
CleanShot 2023-09-29 at 22 05 21@2x

Please ignore the reports.jsx error, I will fix them later.

### CODE REVIEW

**Comment by DavidC0126** [comment]
Hi I checked the functionality and the page works as intended, also, no error shows when running `npx eslint `

Screenshot 2023-09-30 at 2 08 49 AM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended!

Week5 - PR12 (#1353)

**Comment by iTvX** [comment]
Hi @DavidC0126 @vikrambadhan, thank you for testing this PR.

Have you both had a chance to test the "Go to Reports" feature to ensure its functionality remains consistent with the previous version? Please also check if all other functionalities in the report are as expected, and let me know if you encounter any bugs.

Your feedback is much appreciated!

**Review by TuanDinh140194 — APPROVED** [review]
I have test your PR and don't see any error.
Screenshot 2023-09-30 123827

**Review by Haoj1 — APPROVED** [review]
@iTvX Good job! I have tested the reports components and have no errrors

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works as intended. There's no error when I running.
Screenshot 2023-09-30 at 6 43 56 PM

**Comment by astrjc0326** [comment]
Hi, I test the PR and it works as intended. Great Job!
Screen Shot 2023-09-30 at 10 36 21 PM

**Review by luisarevalo21 — APPROVED** [review]
Hello @iTvX,

I tested your PR and works as intended great work!
I saw no errors in the code or in the terminal when running the npx eslint.
Screenshot 2023-10-01 at 8 52 54 PM

**Review by Bhagyashree444 — APPROVED** [review]
Works as expected. No ESLint Errors.

Screenshot (179)

**Review by Sssky-18 — APPROVED** [review]
Hi @iTvX, I tested this PR. The report displayed correctly, and all the buttons behaved well. For the lint fix, there was no error in report folder, so I approved it.   
PR#1353

**Review by sxiong5 — APPROVED** [review]
Hey @iTvX, this PR LGTM! Great job!

Screenshot 2023-10-05 at 16 44 16

**Review by Shubhu0 — APPROVED** [review]
HI @iTvX I reviewed your PR and it is working as intended. 

image

**Comment by Vishala09** [comment]
Great Work!
No Lint Errors!
image

Please  find my video testing here:
[Untitled_ Oct 06,2023 11_55 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/4202c3f7-afde-4f6a-b4b8-5013204eaded)

**Review by Vishala09 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you everyone, moving to final review!

**Review by KurtisIvey — APPROVED** [review]
Everything passes linting

pr1353 all pass

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
