### PR TITLE
Sai deepak character countdown desc

### PR DESCRIPTION
**Pull request by SaiDeepak-NEU**
# Description
This PR is to test a newly added feature of Character countdown for description in the add equipment form of the bmdashboard of phase 2.

## Related PRS (if any):
None, this is just a frontend PR and can be tested using the latest development branch of backend
…

## Main changes explained:
- Added the countdown for the number of characters allowing only a maximum of 150 characters.
- Made changes in the AddTypeForm.jsx in BMDashboard folder under add under equipment
- added a CSS class in BMDashboard.css file
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin or owner user
5. navigate to /bmdashboard and login again and after logging in navigate to /bmdashboard/equipment/add
6. Test the working and accuracy of the character countdown added below the description text area. Verify that the color of the text turns to red when inputting more than 150 characters and changes back to black when less than 150 characters.

## Screenshots or videos of changes:
Screenshot (100)
Screenshot (99)

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested your PR and everything works as intended. One thing I noticed is that a blank space is also considered as a valid character and increases the character count by one. I am not sure whether this is a part of the functionality. If not, then we can improve upon this point. Please refer the video and the screenshot attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/937c5694-650e-4f27-b846-4842426d4117

PR 1976 change

**Review by ShengjieMao — DISMISSED** [review]
The checks worked as described in the instruction. The files also look great. 
PR_1976a
PR_1976b

**Review by skaush21 — DISMISSED** [review]
* logged in as owner, navigated to /bmdashboard
* logged in again, navigated to /bmdashboard/equipment/add
* checked character limit, limit is black until it exceeds the limit where it then turns red.
feature works great!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/3c8128f7-f8de-4926-a311-1bc2c1f50617

**Review by XiaohanMeng — COMMENTED** [review]
Hi, I tested this PR and found that it functions very well. However, I encountered the same issue as described by meetpadhiar: spaces are also counted as a valid character. I am wondering if this was an intentional design decision. Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/f77b4628-eb73-4cc5-ad4f-9ad7d0dff167

**Review by swathyjayaseelan — COMMENTED** [review]
The changes look good. As pointed out in the other reviews, even space is considered as a character and counted. It is better to place a check and avoid that from being sent to the api. 

Another UI enhancement would be to disable "Submit" button if the user types more that 150 words and show the error message as and when the user types more than the allowed limit and not when the submit button is clicked. That is a design level change which might not be in the scope of this PR.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/13fc69d7-3274-494e-87a0-3ec735116409

**Comment by FyisFe** [comment]
It works great. But I believe there are two improvements we could make

1. Space is considered as a character and not verified when submitting it, which means you could submit add equipment with blank description.

2. For now, the `Submit` button disable logic is only based on name, I feel we could also add description here `disabled={!name || desc.length === 0 || desc.length > 150}`
```jsx
<Button color="primary" disabled={!name}>
          Submit
</Button>
```


image
image

**Review by FyisFe — DISMISSED** [review]
It works great. But I believe there are two improvements we could make

1. Space is considered as a character and not verified when submitting it, which means you could submit add equipment with blank description.

2. For now, the `Submit` button disable logic is only based on name, I feel we could also add description here `disabled={!name || desc.length === 0 || desc.length > 150}`
```jsx
<Button color="primary" disabled={!name}>
          Submit
</Button>
```


image
image

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR, a small problem is that the white spaces are being counted.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/7da8ef76-724f-4c5a-9793-a238d1d9fc5a

**Review by navyasrim — APPROVED** [review]
Tested the changes ..after 125 count the number is changed to red colour., attached images. Working 
PR-1976-2
PR-1976-3
 as mentioned.

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I re-reviewed your PR and it now works correctly. Blank spaces are not counted as extra characters and the color functionality also works as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/0e7f3b0f-5d31-4653-b93e-b35742a922d2

**Review by tdkent — CHANGES_REQUESTED** [review]
The basic functionality of the character counter works as expected. The character count adds/subtracts correctly and turns red once the user exceeds the limit. However, the branch has several issues with white space.

White space should **not** be removed from the character count. By default, white space is counted in form character limits, and its very counterintuitive for users otherwise. 

Additionally, not counting white space gives a user the ability to include unlimited amounts of white space in their description. Remember that white space is a character just like any other. By excluding it from validation checks, it would be possible to send enormous data packets consisting entirely of white space characters. Users can also send weirdly-formatted descriptions if white space is not being controlled (see below. Obviously, this is possible with a 150 character limit. Just pointing out how truly weird it could get without any limits on white space).
Screenshot 2024-03-30 at 10 37 53 AM



Functionally, removing white space from the character count is causing the form to not behave properly. Note that Joi is being used to validate the max character limit (line 23, AddTypeForm.jsx), and Joi by default counts white space. Although you added a function to strip white space from the character counter function, as far as Joi is concerned the white spaces still count, so that validation check will fail even though the counter is less than 150. 

I also found that the counter will turn red at character counts less than 150, because the CSS controlling it is using only `desc.length > 150` without stripping the white space.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/cf9aa86e-e128-4666-b632-071e5f04a17b

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
