### PR TITLE
Roberto- changes open cage api call to backend

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
Changing the OpenCage http request to happen on backend rather than client. Keeping the get request on the client allows for security risks since anyone can view the network tab and see the api key. By transitioning the request to happen on backend the api key can stay secure and concealed while just returning needed information to client.

## Related PRS (if any):
This frontend PR is paired with the #[639 ](https://github.com/OneCommunityGlobal/HGNRest/pull/639)backend PR.

## Main changes explained:
- For the getTimeZone functions just added an axios get request to fetch timezone data from backend in BasicInformationTab.jsx, SetupProfileUserEntry.jsx, AddOrEditPopup.jsx, and UserProfileAdd.jsx.
- Deleted all redux properties related to the getTimeZone function as no longer needed and complicates logic.
- Corrects spelling for Kyiv and adds Zambia timezone to timeZones.js

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as owner
4. go to any user profile → Location → Enter a valid location → Click get timezone→ make sure the function works and timezone is appropriate
5. dashboard→ reports→ team locations→ select a user → edit location → verify it reflects well
6. dashboard → user management → create new user → verify location input works 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/31ecac0b-1200-4578-90dc-128b6c523db3

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/37fdc806-df70-40ab-a7e1-10faa677c441

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/b41b687f-6733-4241-aebc-f6df5a9f1ac6

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by this-journey — DISMISSED** [review]
Tested all the functionality described.  Please see attached videos.  Great job!

Uploading PR 1640+639.mov…

**Comment by DragonSlayer2401** [comment]
I tested this PR everything is working correctly. I changed a team location, my own location, and another user's location successfully. Please watch the overview video below:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/0e27b1aa-5387-44f7-9502-ed89fafc9682

**Review by Alforoan — DISMISSED** [review]
Everything works as it should. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/ac1c68a1-1ba6-435c-8942-64f251bb85cb

**Review by pshereen — DISMISSED** [review]
Tested the PR. Updated the API key.

In View Profile page, updating location to Vatican, Zagreb, Podgorica in Basic Info is causing the page to crash. See the video for details.

Uploading HGN APP and 11 more pages - Personal - Microsoft​ Edge 2024-01-25 21-51-03.mp4…

**Review by pshereen — DISMISSED** [review]
Tested PR.
All the Timezone features are working as expected in all three pages.
Attaching video from basic info page.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/dbea0e86-89be-4c75-9719-f9cb47c80b48

However, the basic info page is crashing if we try to get Time Zone for Vatican, Zagreb, Podgorica.

**Review by Renanluizssx — DISMISSED** [review]
Hi @robertoooc, i tested your application and it´s correct, nice.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/513ff24f-b0b8-4c9f-bec9-55d4c1a915af

**Review by Sophie-lei — COMMENTED** [review]
Hey!  I just tested this PR for both the backend and frontend. I tested the PR for changing the timezone with the backend development and Opencage API just before this test and everything working fine. However, I changed to this backend of PR#639. The API call is not working and shows an error like this. I am not sure what the problem is but looks like the API for https://opencagedata.com is not connected.    
Screenshot 2024-01-27 at 21 09 43

**Comment by galgalinidhi** [comment]
Hi @robertoooc, I tested the PR and works well! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/79f8c61a-d721-4231-857d-6097902efa60

**Review by SRamen1999 — DISMISSED** [review]
I tested this PR everything works as expected. I used an owner account and changed a team location, my own location, and another user's location successfully. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/0cbfb2a2-1fd3-4ae6-a4f3-e23495f174bc

**Review by Pandani07 — DISMISSED** [review]
Followed the testing instructions, and the backend PR steps. Functionality works as intended. The timezone is updated based on the location typed in the text box.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/678db083-9bd8-4ed3-a407-57fef4373247

**Review by KevHnh — DISMISSED** [review]
I tested using an owner account and everything works as expected. I was able to update my location and retrieve available time zones in my profile, from the team page, and from the location page. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/1a45ed07-b96e-4d04-b614-e77e827ba4e2

**Comment by xmyoot** [comment]
See comment on backend repo: https://github.com/OneCommunityGlobal/HGNRest/pull/639#issuecomment-1925503035

**Review by ClemarNunes — DISMISSED** [review]
I tested this PR everything is working correctly.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/3164c297-81b9-465f-ae9c-0ecc8fd91b26

**Review by SaiDeepak-NEU — DISMISSED** [review]
Hello Roberto,
I have added the api key to my env variables in my backend and I have tested all the cases presented in the PR. Here are my results:
1. Was able to get the correct timezone on inputting location.
Screenshot (63)
2. I am able to edit the location on the map in team locations successfully and it reflects well in the map as well. 
Screenshot (64)
Screenshot (65)
3. Adding location input to the new user in user management also went smoothly.
Screenshot (66)
Good job!

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested this PR and it works excellently. No problems were faced.
Screenshot 2024-02-09 at 12 36 14 AM
Screenshot 2024-02-09 at 12 40 56 AM

Screenshot 2024-02-09 at 12 42 25 AM

**Review by XiaohanMeng — COMMENTED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/c796c6c2-4e82-42b8-8df4-3ab1a263f277

Everything works as intended! I tested this using the Owner account, attempting to change my location, the team location, add a user with a location, and edit locations in the user list. The only thing to note is that the map requires some time to update with the new location for the user.

**Review by Coops023 — APPROVED** [review]
Hi i have reviewed your PR and checking functionality:

- [Y] go to any user profile → Location → Enter a valid location → Click get timezone→ make sure the function works and timezone is appropriate
- [Y] dashboard→ reports→ team locations→ select a user → edit location → verify it reflects well
- [Y] dashboard → user management → create new user → verify location input works
All works as intended, well done!

PR-1640+639

PR-1640

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by lacnoskillz — CHANGES_REQUESTED** [review]
Hello @robertoooc 
Nice work!
everything works as intended except for one thing I noticed
When creating a user via user management the users location isnt displayed on the map
see video below. I tried making a few users with no luck. refreshing and editing location after creating but they dont display on the map.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/351be81d-8353-4261-95ef-a2c7d23af63f

Maybe I am missing something so let me know if its just my end

here is me updating my profile location successfully

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/4fc7a773-bef4-4fa1-aba5-db0637d5082d


Overall awesome job!

**Review by scoopstroop92 — COMMENTED** [review]
The  page becomes un-responsive to me post login. Are you in the middle of making changes ?
image

**Comment by robertoooc** [comment]
@lacnoskillz, Hi about your comment of the user not showing up on the map after immediately creating them, I'm not too sure as I was not the creator of the map functionality but I'm pretty sure you would need to clock at least a week's worth of tangible time for the user to show up as seen here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1503
This is the original pr creating the map, and the logic seems to work specifically after the user has completed a weeks worth of their tangible time.

**Comment by robertoooc** [comment]
Hi @ramyaram2092, I haven't encountered that problem myself during testing this pr. 
Are you using the assigned backend ? Or is this error persistent on your local machine after a page refresh, Im not too sure what could be causing this?

**Review by lacnoskillz — APPROVED** [review]

**Review by navneeeth — APPROVED** [review]
Hello, @robertoooc! Reviewed your work and it looks ready to be merged! Excellent implementation throughout. 

## Test No. 1: Updating the Timezone for an existing user

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/7d068df0-0d27-447d-824e-a9073e832216


## Test No. 2: Updating an existing user's location on Reports -> Team Locations  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/78ecc3a2-f9d9-43c9-980a-93f0171579c8


## Test No. 3: Verifying a new user's location input

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/9fd92d6c-79ef-43d2-b773-f560a39633b8

In addition to the functionality working as expected, the implementation that ports a major portion of the relevant functionality, with the OpenCage HTTP Request, to the backend, is well-written. 

You're absolutely correct regarding the security risks posed when the API call is being done in the frontend, an example as you've mentioned being viewing the Network tab and retrieving the API key. This fix should eliminate such risks.

I was looking for the change you have mentioned in `timeZones.js` but then realized when reviewing the codebase on the IDE that the exact changes that you've mentioned were implemented & pulled in from a recent push to `development` from another PR and thus does not reflect in the `Files changed` tab here. Safe to remove that bullet point from the `Main changes explained` section in the PR's Description. 

LGTM! Approving!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
