### PR TITLE
Changhao - added unit tests for GeneratePdfReport.jsx

### PR DESCRIPTION
**Pull request by lichanghaogit**
# Description
added new unit test cases, fixed the file location issue.

## How to test:
1. check into current branch
2. do `npm install` and `npm test -- -u GeneratePdfReport.test.js` to run this PR locally
3. verify all 3 tests are passed

## Screenshot:
Screenshot 2024-01-30 at 12 28 52 PM

### CODE REVIEW

**Review by Renanluizssx — COMMENTED** [review]
Hi @Changhao3220K, all tests passed, but there is an error in GeneratePdfReport.test.js file
Screenshot 2024-01-30 214447

**Review by 666saofeng — APPROVED** [review]
All tests passed.
image

**Review by ShengjieMao — APPROVED** [review]
All tests passed. Can see the target component rendered successfully with the test props. Edge case was considered in the unit test case. Great work
PR_1901

**Review by yvonnep165 — APPROVED** [review]
Hi @Changhao3220K ,
All tests passed as below. Nice work!

**Review by peterson337 — APPROVED** [review]
All tests passed

a

**Review by Nahiyan-16 — APPROVED** [review]
## All tests have passed!
I have run the tests and everything seems to work as intended. 
However, I do have some suggestions:
- In your first test `(should render button that generates PDF reports)`, you're using `expect(screen.getByRole(...))`, but you should add an assertion like `toBeInTheDocument()` to ensure the button is actually in the document.
- While you have extended Jest's expectations with `@testing-library/jest-dom/extend-expect`, it's a good practice to explicitly import the matchers you need. Ex: `import { getByRole, toBeInTheDocument } from '@testing-library/jest-dom';`
- Add a comment explaining where the mock data (mockSummaries) comes from or its purpose, especially if it's located in a special directory like `__mocks__`. This provides context for anyone reading the test in the future.

Screenshot 2024-02-01 103627

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed as intended. Please watch the overview video for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/6635cb95-feff-4bb3-9f63-d36f6d860c7f

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 23 - PR4

**Comment by xmyoot** [comment]
Hello, 
all tests passed successfully
[
PR#1901(testsPassed)
](url)

**Review by X1aoZhang99 — APPROVED** [review]
Hi Changhao,

All tests passed. Nice work! 

Screenshot 2024-02-04 at 20 55 47

**Comment by mianmiantea2019** [comment]
Hi, I tested your PR and all the test cases passed!

image

**Review by yaow62023 — APPROVED** [review]
All the test case are passed! 
Screenshot 2024-02-10 at 12 56 57 AM

**Review by navneeeth — APPROVED** [review]
Hello, @Changhao3220K! I reviewed your test implementation and it satisfactorily covers the generated PDF report. Great implementation!

### Test Cases Result
test cases passing

The test cases result are all passing for the relevant implementation.

The tests that 
(i) Render a PDF Report given dummy data for summary, week index, and week dates and expect an 'Open PDF' button on the screen to appear. 
and
(ii) Expect the rendered `GeneratePdfReport` component as a fragment with mock data for summaries, week index, and week dates to match the snapshot.

are well-written.
Approving!

**Pull request merged**
