### PR TITLE
Shantanu unit test cases for colorsGenerator common component

### PR DESCRIPTION
**Pull request by n0vay**
# Description
Unit test case for color generator common component for pie chart

## How to test:
1. check into current branch
2. do npm install
3. npm test colorsGenerator.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:
Shantanu-1

### CODE REVIEW

**Comment by palakgosalia** [comment]
Hey, I reviewed your code and ran the test case. All the 5 out of 5 test cases passed. Thank you

image

**Review by sucheta90 — APPROVED** [review]
Hi @n0vay, reviewed code and ran test on the local branch, all tests passed. Below is the  screenShot
pr#1591_all_test_passed

**Review by keyunhuangg — APPROVED** [review]
Confirmed that all tests have passed 5/5.
Screenshot 2023-11-28 at 3 32 16 PM

**Review by pika-chu11 — APPROVED** [review]
Hi @n0vay , I have tested it and it passed on my end! Great Job!

PR 1591

**Comment by beblicarl** [comment]
All tests passed and the test cases are great

image

**Review by beblicarl — APPROVED** [review]

**Review by Alforoan — COMMENTED** [review]
All tests have passed. Nice!

image

**Review by Alforoan — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
