### PR TITLE
Prabh adding different background to rows and dot text fix

### PR DESCRIPTION
**Pull request by PrabhjotSembhi**
# Description
@one-community Requested to add different background colors to each row in the table on the mobile view, to make its easy to differentiate. And I have also centered the Resource Initials in Dot. 
  
## Related PRS (if any):
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/723
This frontend PR is related to this PR and I didn't update this because this is approved. And I think changing the background color should have a different PR. 

## Mainly changes explained:
Edited linehight of Resource Members Initials to make it centered
Add CSS to give different background to each row.
…

## How to test:
check into the current branch
do `npm install` and `...` to run this PR locally
log as admin user
go to dashboard→ Other links → Projects → AAA USE THIS PROJECT → Jae's WBS - USE THIS

## Screenshots or videos of changes:
**Before** 
Before

image

You can see initials are out of a circle and each row is white.

**After** 
image

Rows have a different color on Mobile and Initials are inside of the circle

## Note:
Some rows might have the same color. Example 
image

I tried to debug this a lot but I think it's due to the layout of the table. and it's not very frequent so I think it is good to go now.

**PLEASE IGNORE ALL CHANGES IN JSX FILES DUE TO PRETTIER.**

### CODE REVIEW

**Review by ToobaJamal — APPROVED** [review]
Hey Prabh, I have tested your PR and it's working as expected!
PR744

**Review by vitorsaa2k — COMMENTED** [review]
Hello @PrabhjotSembhi. The tasks are indeed getting colors in smaller screens. Just a doubt that in this WBS this green color repeated a lot as you can see.

image

**Review by NataliaCavicchioli — COMMENTED** [review]
Hey @PrabhjotSembhi, I tested your PR and it is looking way better. On all widths, the icon's name is centered, and on small screens is colorful, which helps a lot in reading the columns.

image

**Review by NataliaCavicchioli — APPROVED** [review]

**Comment by AnishPandita** [comment]
hi @PrabhjotSembhi I tested your PR and it looks great. Everything seems proportional and nicely centered.

Screenshot 2023-03-31 at 2 41 06 PM

**Comment by one-community** [comment]
Looks great! Moving this to final review, thank you everyone.

**Comment by PrabhjotSembhi** [comment]
> Hello @PrabhjotSembhi. The tasks are indeed getting colors in smaller screens. Just a doubt that in this WBS this green color repeated a lot as you can see.
> 
> image

It's out of the scope of this PR to fix it. I think this happened due to some flaw in the table layout. and I don't think it's that necessary to put that much effort for now.

**Comment by Jorge-Nerd** [comment]
Hi @PrabhjotSembhi  I tested the PR amnd it work has intended
After
image

**Comment by Jorge-Nerd** [comment]
I suggest you can put diferent background to diferentiate the task that has sub task

**Comment by one-community** [comment]
It does not appear that you are pulling the latest code @Jorge-Nerd and/or reviewing what this PR is actually about. Please take more care in your PR reviews.

**Comment by EvianTan** [comment]
Nice job on the responsive small screen!

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
