### PR TITLE
Test fix to a crash Aashish was getting with an unhandled rejection 

### PR DESCRIPTION
**Pull request by Red4lpha**
Test fix to a crash Aashish was getting with an unhandled rejection from setUserProfile in badge report for badge deletion

- -I could not get the crash, so this is a test fix until Aashish can verify it no longer crashes.

I also commented out the force reload since its unnecessary

### CODE REVIEW

**Review by aashish-thapa-magar — APPROVED** [review]

**Comment by one-community** [comment]
Can't merge because "This branch has conflicts that must be resolved"

**Comment by one-community** [comment]
Following up on this and the conflicts that won't allow me to merge it.

**Comment by one-community** [comment]
Following up again on this and the conflicts that won't allow me to merge it.

**Comment by one-community** [comment]
Following up again on this

**Comment by one-community** [comment]
Following up on this, does it still need to be reviewed and integrated?

**Comment by EvianTan** [comment]
No longer needed.

**Pull request closed without merging**
