### PR TITLE
Shrey_unit_test_SkeletonLoading

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for SkeletonLoading component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test SkeletonLoading.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-11-25 at 12 54 40 PM

### CODE REVIEW

**Review by Hemsharavanan — APPROVED** [review]
- Impressive coverage across different templates, checking for specific class renderings and quantities where applicable.
- Code is well-structured and easy to follow.
- Great use of jest.spyOn to handle console.error during tests.
- Overall your tests provides proper coverage, validating the expected rendering of various templates.
PR #1583

**Review by vikrambadhan — APPROVED** [review]
Hi! Good job! All the test cases passed!

Week 13 - PR7

**Comment by palakgosalia** [comment]
Hey, I reviewed and ran the test, all 9 out of 9 test cases passed. 

image

**Review by ZichanYang324 — APPROVED** [review]
I have reviewed and ran the tests, and verified that all the test cases passed.
PR1583

**Review by Alforoan — APPROVED** [review]
All passed. Nice!

image

**Pull request merged**
