### PR TITLE
Ramya Unit tests for Reports/TeamReport/components/TeamChartsGroup

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit test for src/components/Reports/TeamReport/components/TeamChartsGroup

## Main changes explained:
-  New file
      - **TeamChartsGroup.test.jsx** : unit test cases 

####  Test cases 
image

## How to test:
1. check into current branch
2. do npm test TeamChartsGroup.test.jsx
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Review by hdani18 — DISMISSED** [review]
Screen Shot 2024-01-06 at 4 36 15 PM
LGTM!!

**Comment by belagaam** [comment]
Tested the PR. All test cases pass. Good work

Screenshot 2024-01-06 at 5 27 46 PM

**Review by bienzguoa — CHANGES_REQUESTED** [review]
All test cases passed. But it seems Test case 1 and Test case 4 are identical, testing the same functionality. Please remove or repurpose one of the tests to avoid redundancy.

Screenshot 2024-01-06 at 4 32 36 PM

**Review by vikrambadhan — DISMISSED** [review]
Hi, i tested your PR and all the test cases passed!

Week 19 - PR1

**Review by bajajtushar094 — DISMISSED** [review]
Hi @ramyaram2092, All test cases passed. Thanks. 
Screenshot 2024-01-08 at 23 16 05

**Review by ChengyanOo — DISMISSED** [review]
Hi @ramyaram2092,

Excellent work on developing the unit tests. I've run them and am happy to report that all tests passed successfully. Attached is a screenshot for your reference.

Screenshot 2024-01-10 at 13 59 03

**Comment by ramyaram2092** [comment]
> All test cases passed. But it seems Test case 1 and Test case 4 are identical, testing the same functionality. Please remove or repurpose one of the tests to avoid redundancy.
> 
> Screenshot 2024-01-06 at 4 32 36 PM

Thank you for catching it. Removed it

**Review by bienzguoa — APPROVED** [review]
Reviewed your changes, good job! 
Screenshot 2024-01-13 at 1 41 46 AM

**Review by bajajtushar094 — APPROVED** [review]

**Comment by belagaam** [comment]
All test cases passed Successfully

Ramya Unit test - Team Chart

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
