### PR TITLE
Faye Deleted src/components/ProfileLinks/** according to PR1671

### PR DESCRIPTION
**Pull request by FayeLV**
# Description
Updated lint ignore file and Deleted profile link file according to PR1671.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1671

## How to test:
check into current branch
do npm install and ... to run this PR locally
Clear site data/cache
log as admin user
check all the function is normal

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/ea3ff8b5-51e9-4175-8b58-2624762e63be

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by FayeLV** [comment]
Uploading HGN APP - Google Chrome 2024-10-16 14-40-29.mp4…

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/05c66bdc-a573-40a4-8f0e-15dc49f4f9a2

**Review by manikittu810 — APPROVED** [review]
Hello @FayeLV 
Everything is working fine.


https://github.com/user-attachments/assets/5f47385e-f2e1-40c9-a5a6-e448673cc298


Thank you.

**Review by NK3101 — DISMISSED** [review]
Tested the PR, everything works as expected.

https://github.com/user-attachments/assets/28b729c2-4baf-4564-ad24-e0b80c4c2fd6

**Review by Ankuriboh — APPROVED** [review]
Tested and working on my end, all components deleted have no uses before PR. This should be safe to merge.

**Review by EvianTan — APPROVED** [review]

**Comment by EvianTan** [comment]
Works as expected but had conflicts so I just resolved them and approved&merged.
image

**Pull request merged**
