### PR TITLE
Manikrishna-found-redundant-code-removed

### PR DESCRIPTION
**Pull request by manikittu810**
Screenshot 2024-08-19 at 11 58 01 PM

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. paste this URL ->   http://localhost:3000/totalorgsummary 
6. verify there is no more than one "Volunteer Roles and team Dynamics" section in the UI.

## Screenshots of changes:

Before : 
Before

removed one extra section of "Volunteer Roles and team Dynamics"

After : 
After

### CODE REVIEW

**Comment by AJAYINAVOLU** [comment]
The removed redundant section has been verified. However, when I log in using an administrator role, all the sections on the page display "loading spinner" rather than information.




Thank You

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (177)

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and all unnecessary code removed .

Screenshot 2024-08-21 180700
Screenshot 2024-08-21 180718

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected.
Screenshot 2024-08-23 at 9 39 36 AM

**Review by Pranay-ai — APPROVED** [review]
Hey @manikittu810 
I have reviewed the PR the Changes are Working as expected
image

Thank you

**Review by SMitta11 — APPROVED** [review]
I tested the PR and approved changes as everything working as expected.
Screenshot:

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.
Screenshot 2024-08-25 020623

**Review by ArshakBadalyan — APPROVED** [review]
Tested and validated PR. Everything is okay.

361154065-a279e3f5-4fe1-4ceb-8e00-186f615b8d4f

**Review by Saniya98 — APPROVED** [review]
Everything is working as expected

**Review by sri0606 — APPROVED** [review]
hey @manikittu810 , I have tested your changes and the duplicate section is not there anymore.

image

**Review by mohangadde1 — APPROVED** [review]
image
changes are working as expected

**Review by KurtisIvey — APPROVED** [review]
Approved. Great job on the fix! I tested both the original and updated versions, and confirmed that a duplicate section was indeed present. Your solution effectively resolved the issue, and I didn't encounter any functionality problems during testing.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
