### PR TITLE
Peterson implement add members button and modal to profile teams tab teams

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request has been opened to implement the 'Add Members' button and modal, specifically in the 'Teams' table within the 'Profile' section and 'Teams' tab.

## Related PRS (if any):
None
…

## Main changes explained:
Four components (MembersAutoComplete.jsx, TeamMembersPopup.jsx,  TeamMember.jsx and UserTeamsTable.jsx) have been modified to implement the 'Add Members' button and modal.

## How to test:
1. check into current branch
2. do npm install, git pull and ... to run this PR locally
3. Clear site data/cache
4. Log in as an administrator or owner.
5. go to view profile→ Teams tab
6. After clicking on the button in the members column of the teams table, a modal will open. Test if it is possible to add or remove users.

## Screenshots or videos of changes:
Peterson_implement_Add_Members_button_and_modal_to_Profile_Teams_tab_teams

## Note:
None

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Hello @peterson337  ,
Followed the Steps from the description. Everything is working as mentioned.


https://github.com/user-attachments/assets/a36e102f-1caa-4278-bb2f-4cb0d8622f04


Thank you.

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR and its working as expected.


https://github.com/user-attachments/assets/bf11b370-8dea-4cba-a4a9-ae9405fcc01d

**Comment by beblicarl** [comment]
this functionality works as intended 

[screencast-localhost_3000-2024.09.05-13_46_50.webm](https://github.com/user-attachments/assets/07e9d1e8-6d5e-485b-baec-f85e2a2d7988)

**Review by beblicarl — DISMISSED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Review by sri0606 — CHANGES_REQUESTED** [review]
Hey @peterson337 , I have reviewed the changes and everything works as expected. Although, as @RishithaMamidala mentioned, any leading or trailing spaces in the input breaks the search functionality. Please fix that.

Refer to the below video:

https://github.com/user-attachments/assets/98b0ff8b-60b8-49c4-90b7-f1c619bbd9a7

**Review by sri0606 — APPROVED** [review]
@peterson337 , Thanks for fixing the bugs. The search works well now and can add/delete users.

https://github.com/user-attachments/assets/6930591b-db39-4c12-9440-74af927babe4

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/d5144805-1d47-436e-91a0-d88015c5708d

**Review by Jingyii800 — APPROVED** [review]
I have tested this feature. As an admin/owner account, I can add/delete team members in profile->team tab. Great job.

https://github.com/user-attachments/assets/c047b7ed-1e32-450f-8d84-db4e2eb9bc20

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

image

Thank You

**Review by CillianRen — APPROVED** [review]
Works as expected.

https://github.com/user-attachments/assets/0f307845-3b01-4001-a0eb-774d2ef1d438

**Review by RishithaMamidala — APPROVED** [review]
@peterson337 
Now the filter works accuratly even with the spaces. Everyting works as intentded. Great job on fixing it.
PR 2637-2

**Review by Gauravmg6 — APPROVED** [review]
It is working as expected.
Screenshot 2024-09-08 015443
Screenshot 2024-09-08 015532

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
