### PR TITLE
Shihao - Fix 'Get Time Zone' Button Appearance

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Screenshot 2023-08-08 at 13 23 34

## Main changes explained:
- Changed the size of the button
- Adjusted the layout

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any user
4. go to dashboard→ Profile→ Basic Information → Time Zone
5. try to change the width of the window to check if the text in the button wraps

## Screenshots or videos of changes:
**Before**
Screenshot 2023-08-08 at 13 33 50

**After**
Screenshot 2023-08-08 at 13 34 14

### CODE REVIEW

**Review by TheDescendant39 — APPROVED** [review]
Hello @sxiong5, I tested your changes with different window sizes and the results are as expected. 

Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/3402d9fd-e963-48e3-b768-9192ae17c92b

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/4676eed1-3618-484a-a1eb-150c0da1316c

**Review by navneeeth — APPROVED** [review]
LGTM! 

- Smart implementation in removing padding on either side for the 'Get Time Zone' button and removing only the right padding for the Column that holds this button. 
- Elegant refactoring in the decision of preferring to set a zero left margin to the row that holds these two columns.
- I presume that the issue was because the Button's styling was exclusively inside a \<div\> tag and hence, it expanded without synchronization with the other column in its row. 

Tested the implementation for varying browser sizes and sharing a small video snippet of the UI in this PR versus the development branch:

**Development branch:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/98639528-6542-40c1-a693-a0b668fc2b35

**This PR:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/87d6c904-716a-4be4-9802-041bbb859b0c

**Review by robertoooc — APPROVED** [review]
Hi @sxiong5, I tested your implementation and the button size does stay consistent through different window sizes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/49241e32-f917-44d5-9bb1-e0a5650b38eb

**Comment by AnishPandita** [comment]
Hi @sxiong5 the implementation works correctly with change in window size.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/ace7e7f9-000c-4b93-82ab-fb7af397385d

**Review by winghojackyli — COMMENTED** [review]
Styling works great in this PR! 

[screen-capture.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/b2b64f17-e533-4bd9-9b01-85244c1dd425)

**Review by eduhorta — APPROVED** [review]
Working as intended. Great job! 👍

image

image

**Review by yurisokolovicz — APPROVED** [review]
Dear @sxiong5 

I have tested it, and the button is now correctly fixed. Please review the videos showing the before and after states. Good job!


**Development (Before):**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/d220e085-be84-48ad-b0dd-d21f5a44a763


**Current Branch (After):**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/88ef03aa-0f6b-49ea-8adf-430168b9c7a7

**Comment by iTvX** [comment]
I tested and compared to the development branch, worked as described. Great job!
Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/77f47db8-bf19-41ed-8c48-76e72b51bb76

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/3a48df48-a045-4290-9ac5-d9e6897af778

**Review by Jiyuanxia — APPROVED** [review]
Hello, @sxiong5! I have tested your implementation, and it functions well regardless of how the window width changes. Excellent work!

Normal size window
Screenshot 2023-08-09 174727

Half size window
Screenshot 2023-08-09 174754

**Review by jerryren527 — APPROVED** [review]
The 'Get Time Zone' button appears as intended. Great job!

**Review by ThapeloMasasa — APPROVED** [review]
The time zone button has been formatted accordinly

Screenshot 2023-08-09 at 4 55 17 PM

**Review by luisarevalo21 — APPROVED** [review]
Hello @sxiong5,

I tested your PR and works great. Great job.
The text inside the button remain aligned and do not wrap into a new line.

Before changes: 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/0be6fa5d-0fd5-4e22-a939-9c7b097d2c67

After changes: 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/301cb907-474c-4d93-a02f-faacd63f6a1f


I do have one suggestion. 
When the screen is large the text inside the button has padding. 
Screenshot 2023-08-09 at 8 46 47 PM

However, once the screen begins to shrink the button loses most of the padding. I think adding a little more padding will make it much better. Instead of the text being squished inside. 
Screenshot 2023-08-09 at 8 46 58 PM


View the screenshots for reference. Overall great work!

**Review by DavidC0126 — APPROVED** [review]
Hi @sxiong5,

I tested your PR and it works as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/2110e6fa-003e-4168-8eb6-1b20232251a8

**Review by eduvarjaor — APPROVED** [review]
Hi @sxiong5 

This implementation worked as intended accordingly with the width change. Great job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/689c1c5f-e95d-45da-b71d-606ef4baf5d0

**Comment by beblicarl** [comment]
This functionality works as intended and the code looks great!

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.08.10-15_53_19.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/387246c8-eee3-4579-95c5-0fc03b874a8d)

**Review by veronicacheng2 — APPROVED** [review]
Hi @sxiong5, I have tested the PR and everything works perfectly. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/83f1ce67-9802-4997-a2f8-13ccf4cc1a6f

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this changes work good on my device.

image

**Review by ramyaram2092 — APPROVED** [review]
Looks good. Good Job 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/5a300c0b-9d7b-40de-91d8-f7286c44cea2

**Review by n0vay — APPROVED** [review]
Looks good to me, Good Job!
image

**Review by EdwinLauM — APPROVED** [review]
Hey @sxiong5. Code changes look good and changes work as expected! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/2b0fa986-9334-459e-8f0f-ec09ad2ad707

**Comment by Lin1404** [comment]
Working as intended. Good Job!
image
image
image

**Review by Lin1404 — APPROVED** [review]

**Comment by Shreyj14** [comment]
The code works as intended. great work.
Screenshot 2023-08-11 at 5 41 27 PM
Screenshot 2023-08-11 at 5 41 20 PM

**Review by Shreyj14 — APPROVED** [review]

**Review by yaow62023 — APPROVED** [review]
Change the window size does not affect the button size. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/cda7a390-ed0d-49cf-a9be-1af21636cf59

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions. The button works as expected!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/0a1fe1dc-ee97-48ad-9d4a-b724579b4d00

However I experience dashboard crashing both for Volunteer and Admin account.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/19797d8b-c293-458f-aec5-8ed9df384323

**Review by Abiddy — APPROVED** [review]
Works! Nice job!

[Screencast from 08-12-2023 06:42:49 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77697776/6d47c9aa-5274-4f30-8bea-4fc7ed613da5)

**Comment by belagaam** [comment]
Tested the PR with the given instruction. Works perfectly, great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/dff1f047-b56d-450d-afad-3e96efb36f8e

**Review by belagaam — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging

**Pull request merged**
