### PR TITLE
Kaikanes Reports page console errors fix

### PR DESCRIPTION
**Pull request by lacnoskillz**
When viewing a user on the `peoplereport` page multiple warnings are displayed in the console. 
adding keys to the BadgeSummaryPreiview page `key={value._id}`
and
 importing and using `forwardRef` for the InputWithCalendarIcon function and adding a `readOnly` property to the input feild.
 Removes these console errors.

## Related PRS (if any):
This frontend only PR 

## Main changes explained:
- add key values to `BadgeSummaryPreiview` 
- imported and used `forwardRef` in function component
- adding `readOnly` to input feild

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as Admin or Owner (anyone who can use/see reports page)
5. go to dashboard→ reports→ people→ select user and open console
6. verify the console does not display the warnings

## Screenshots or videos of changes:
image

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/b7332bff-c60e-4eef-a417-8811dc3b8ae4

### CODE REVIEW

**Review by X1aoZhang99 — APPROVED** [review]
Hi Kaikanes,

I followed your steps and all warnings are gone in the console. Nice work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/3842dcb7-a4d1-45da-a813-76c748cdf350

**Review by peterson337 — APPROVED** [review]
[lacnoskillz](https://github.com/lacnoskillz), I tested your application, and everything worked as expected. Good job!

one comunnity

**Review by Pandani07 — APPROVED** [review]
I tested this with the latest dev branch and I did not run into the errors that you described! Good job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/1c6f7347-6a29-4b93-a290-73460fec1cbd

**Review by swathyjayaseelan — APPROVED** [review]
Tested and there are no console errors on the user reports page.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/332fadcc-50b9-4293-be84-b39500341aaa

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and everything worked as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/c292c6e5-8b27-41f2-bdf9-11d1c9d52ae9

**Review by prnvjn — CHANGES_REQUESTED** [review]
The console doesn't throw the described error but it does throw another error which is persistent throughout the app. It's also visible on the development branch.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/3525231/4e609f5b-faf6-41c1-a98c-513ecd6f14ad

Screenshot 2024-02-08 at 7 00 39 PM

**Review by n0vay — APPROVED** [review]
Looks good to me.
image

**Review by ShengjieMao — APPROVED** [review]
Errors mentioned did not appear this time. Great work. You can ignore the error as shown on my console since they are caused by my adblocks.
PR_1923

**Review by TapanPathak — APPROVED** [review]
Hi, I followed your steps, and everything worked as expected. 

Screenshot 2024-02-09 at 3 23 45 PM

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, there is no error message when open the people page. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/5a1e0425-d175-4822-98c1-e549dfe7f022

**Review by SaiDeepak-NEU — CHANGES_REQUESTED** [review]
Hello Kaikanes,
I tested the changes mentioned in the PR and found some warnings in the console.
I first logged in as an owner and then navigated to the reports page and clicked on people and then selected a user.
Here I noticed that, for few users when i click on show badges, there are no warnings but for some users warnings appear. I am thinking it is in the case where there more number of badges which fill the entire modal or something. The warning appeared especially when i tested for 0Sherley Volunteer. Please take a look at the screen shot.
Screenshot (89)

**Review by 666saofeng — CHANGES_REQUESTED** [review]
Hi, there are some errors on my side. Please refer to the video for the details

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/9a4185b4-fca6-471b-bc53-ed6688ca5cc2

**Comment by galgalinidhi** [comment]
Hi @lacnoskillz, I tested the PR and I didn't get any errors on the console.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/2195362f-1b8c-4182-a9d3-41ff0efb69cb

**Review by mohabbasd — APPROVED** [review]
Hello, I tested this PR and it works perfectly.
Screenshot 2024-02-11 at 12 22 25 AM
Screenshot 2024-02-11 at 12 22 38 AM

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and everything works as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/fff2f23f-c030-4129-8d4f-e6d59bdc047c

**Comment by dhairya-mehta** [comment]
Hello, I verified the PR, it works perfectly!
image

**Comment by dhairya-mehta** [comment]
> Hello, I verified the PR, it works perfectly! image

**Review by dhairya-mehta — APPROVED** [review]

**Review by XiaohanMeng — APPROVED** [review]
Hi, I reviewed your PR and confirmed that it works as expected. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/7918394e-eecb-4fda-a024-99d79375d29a

**Review by YHX6 — APPROVED** [review]
I tested it and the errors are not displayed anymore
before

after

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by one-community** [comment]
> Hello Kaikanes, I tested the changes mentioned in the PR and found some warnings in the console. I first logged in as an owner and then navigated to the reports page and clicked on people and then selected a user. Here I noticed that, for few users when i click on show badges, there are no warnings but for some users warnings appear. I am thinking it is in the case where there more number of badges which fill the entire modal or something. The warning appeared especially when i tested for 0Sherley Volunteer. Please take a look at the screen shot. Screenshot (89)

Requesting the Badges Bugs team look into this

**Pull request merged**
