### PR TITLE
Shiwani Make permission for "total valid weekly summaries" number editable

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Screenshot 2023-10-19 at 1 37 12 PM

## Related PRS (if any):
This frontend PR is related to the #[747](https://github.com/OneCommunityGlobal/HGNRest/pull/747) backend PR.

## Main changes explained:
- Added isEditCount to FormattedReports.jsx to check if 'totalValidWeeklySummaries' permission is preset in the permission list.
- Added 'totalValidWeeklySummaries' to permissionLabel in UserRoleTab.jsx
- Added 'Edit Total Valid Weekly Summaries' to modalInfo in RolePermissions.jsx

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner user
5. go to dashboard→ Other Links → Permission Management → Manage User Permission → type any user -> Add 'Edit Total Valid Weekly Summaries' → Submit. If the chosen user does not have reports tab in header then add 'See Only Weekly Summary Reports tab' along with the permission set before.
6. log in as the user for whom the permissions were set.
7. go to dashboard → Reports -> Weekly Summaries Reports
8. Check if Total Valid Weekly Summaries is editable and also check if Total Valid Weekly Summaries is not editable when the permissions are removed.
9. Feel free to leave any comments or screenshots

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/7aaf7adc-ee0c-4a3a-b54d-809d0eaa90db

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by olenadanykh** [comment]
hi @Shiwani99 . I have tested this PR locally with related 588 backend PR and all works as intended. Total Valid Weekly Summaries is editable. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/ab3e96e8-a94b-4c7b-b3a8-1f1b0d7e612f

**Review by malikjahanzaib — APPROVED** [review]
Hi @Shiwani99, I have tested this PR locally and it works as intended. When 'Edit Total Valid Weekly Summaries' permission was assigned to the user, it was able to edit the 'Total Valid Weekly Summaries' for any user. Also 'Total Valid Weekly Summaries' was no longer editable when the permission was removed for the user. Check out my test recording below. Great job!!! 

Test rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/b08af92e-a943-40e8-b13e-83892f2d2c38

**Review by ChirayuRai — APPROVED** [review]
Looks good! I can toggle it on and off for a different user. Nice work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/015e6347-019d-4e72-b4d5-e99f4783fa8d

**Review by DavidC0126 — DISMISSED** [review]
Hi @Shiwani99 I tested your PR and it works as described.


Uploading editable_weekly_time.mov…

**Comment by palakgosalia** [comment]
Hey, I created a new user which initially did not have editing permission, after changing the permission, I was able to edit it as intended. Works great! Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/a0968de5-679a-49ce-923f-5d4bee0b5048

**Comment by kavya151** [comment]
Hi @Shiwani99 I have tested this PR with PR#973. everything is working as expected for owner account. I was able to change permissions with the help of Owner account. 

Uploading shiwani.mov…

**Review by sxiong5 — APPROVED** [review]
Hey @Shiwani99, I have tested the PR and it worked as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/3217be17-a51d-466a-9d2f-826c7f574a66

**Comment by Shuhua-L** [comment]
Hi @Shiwani99, I logged in as an admin user and couldn't find the 'Manage User Permission' option under the Permission Management page. Am I missing something here?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/e4bc3281-9bb1-4b23-b76d-664dcb69dad9

**Review by Shuhua-L — DISMISSED** [review]
Hi @Shiwani99, I've tested this PR, and it works as expected. Great job!

When we give the 'Edit Total Valid Weekly Summaries' permission to the user, they can edit the 'Total Valid Weekly Summaries' for anyone. Similarly, when we remove the permission, this feature becomes uneditable.

I also noticed that the user needs to log out and log back in to see the updated changes; simply reloading the page is not enough. I am not sure if this is an issue that needs to be addressed though

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/6c1fb6b6-da4e-4614-8938-9e90589296c6

**Comment by Shiwani99** [comment]
> Hi @Shiwani99, I've tested this PR, and it works as expected. Great job!
> 
> When we give the 'Edit Total Valid Weekly Summaries' permission to the user, they can edit the 'Total Valid Weekly Summaries' for anyone. Similarly, when we remove the permission, this feature becomes uneditable.
> 
> I also noticed that the user needs to log out and log back in to see the updated changes; simply reloading the page is not enough. I am not sure if this is an issue that needs to be addressed though
> 
>  PR1459+588.mp4

Hi, Yes, this is an expected behavior for the permissions to only reflect on the account after logging back in.

**Review by shubhankarval — DISMISSED** [review]
Hey @Shiwani99, I tested the PR and it works exactly as intended, good job! 

When permission is given to edit Total Valid Weekly Summaries:
Screenshot 2023-11-04 132717
\
When permission is not given to edit Total Valid Weekly Summaries:
Screenshot 2023-11-04 133043

**Comment by KurtisIvey** [comment]
Hey there, would love to be able to push this through to final review if possible since its passing with flying colors so far. Could you clear up the merge conflicts please, and I'll rally some of the troops to knock out the pr reviews for you afterwards. Thank you!

**Review by Alforoan — DISMISSED** [review]
It all seems to work as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/a64a09d9-1145-4c24-bce3-1ef280eef458

**Review by Pandani07 — CHANGES_REQUESTED** [review]
Hi, tested this PR and i could edit the weekly summaries, but I got an error message (see screenshot)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/6e04ede9-b940-42fa-93ac-725d2fe0253e
Screenshot 2024-02-07 at 12 42 52 PM

**Comment by Shiwani99** [comment]
> Hi, tested this PR and i could edit the weekly summaries, but I got an error message (see screenshot)
> 
> https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/6e04ede9-b940-42fa-93ac-725d2fe0253e Screenshot 2024-02-07 at 12 42 52 PM

Hi,
Thank you for your review. I just now rebased changes with development branch. Can you check if you are encountering this error again? I tried to check from my end again and it seems to work as expected without the error. I have raised a new backend PR https://github.com/OneCommunityGlobal/HGNRest/pull/747 Please do let me know if you are encountering the issue again.

**Review by Pandani07 — APPROVED** [review]
Tested this PR and the functionality works as intended. When I added the permissions, I could edit them (as shown in the video). I could longer edit the total valid weekly summaries after the permission was removed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/1f67064d-2fee-4d57-9bb6-60d852b245e8

**Review by cvtqx — COMMENTED** [review]
When I test with an owner account the functionality works as described. I can add permission to update weekly summaries count to a user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/e20c2f6f-bf72-49a3-9ba6-d4e5ac40976c

When the permission is disabled that user is no longer able to update the count:

Screen Shot 2024-02-23 at 2 29 21 PM

In the PR description you mention that both admin and owner have ability to add permission however,when testing from an admin account I am not able to update any permissions, see the image of what my admin view looks like:
 
Screen Shot 2024-02-23 at 2 22 07 PM

Is this intended and the functionality is only meant for owner account?

**Comment by Shiwani99** [comment]
> When I test with an owner account the functionality works as described. I can add permission to update weekly summaries count to a user:
> 
>  Screen.Recording.2024-02-23.at.2.24.04.PM.mov 
> When the permission is disabled that user is no longer able to update the count:
> 
> Screen Shot 2024-02-23 at 2 29 21 PM
> 
> In the PR description you mention that both admin and owner have ability to add permission however,when testing from an admin account I am not able to update any permissions, see the image of what my admin view looks like:
> 
> Screen Shot 2024-02-23 at 2 22 07 PM
> 
> Is this intended and the functionality is only meant for owner account?

Hi,
Thank you for your review. This PR was created when the administrator had access to manage user permissions under permission management, but some PR that was merged after my PR was raised had changed that to allow only owners to access manage user permissions button. I recently rebased my changes with current development which is the reason why you are not able to access manage user permissions button for administrators in this PR. I'm attaching a video below which shows that administrator does not have manage user permissions button under permission management even in current development branch. Thank you for notifying about this as I forgot to edit the instructions.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/07396015-796e-4911-b128-6a857fc2c4f1

**Review by cvtqx — APPROVED** [review]
@Shiwani99 Thank you for clarification, approving!

**Pull request merged**
