### PR TITLE
Ivy-invalid password alert and errors to be displayed appropriately below the text input area.

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
Screenshot 2024-08-09 at 2 59 52 PM
Screenshot 2024-08-09 at 3 00 06 PM

## 
This frontend PR is related to the [#1077](https://github.com/OneCommunityGlobal/HGNRest/pull/1077) backend PR.

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch for frontend and backend
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ yourname → update password → enter the new password first, followed by the confirm and then type the current password, check the error displayed properly
https://github.com/user-attachments/assets/b88dde7f-967e-464a-a62b-7e0dcd95cd6f

6. go to login → update password → incorrect email format error
 Screenshot 2024-08-09 at 2 43 49 PM
Screenshot 2024-08-09 at 2 43 56 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected.

https://github.com/user-attachments/assets/c82c4ec1-0734-42b2-8f51-5ed47f95c260

**Review by Gauravmg6 — APPROVED** [review]
The alerts are popping up as expected.

Screenshot 2024-08-11 012144
Screenshot 2024-08-11 012205

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected.
Screenshot 2024-08-11 at 12 29 46 AM
Screenshot 2024-08-11 at 12 29 56 AM
Screenshot 2024-08-11 at 12 30 01 AM
Screenshot 2024-08-11 at 12 30 23 AM

**Review by manikittu810 — DISMISSED** [review]
Hello @20chen-7 
Everything is working as mentioned. Below are the screenshots for reference.

Screenshot 2024-08-12 at 12 02 17 AM
Screenshot 2024-08-12 at 12 03 00 AM

Thank you.

**Review by Aishwarya0898 — APPROVED** [review]
Hi,

The PR is working as expected. Here are the screenshots for reference, Great Job!

PR #2549 Image1
PR #2549 Image2
PR #2549 Image3
PR #2549 Image4

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey @20chen-7 
The PR is Working as expected for few input fields but when i try to login using an incorrect password the error message is displayed  below the email input field where as it should be below the password input field.
image

Thank You

**Comment by 20chen-7** [comment]
> Hey @20chen-7 The PR is Working as expected for few input fields but when i try to login using an incorrect password the error message is displayed below the email input field where as it should be below the password input field. image
> 
> Thank You

Updated, you can check it at the frontend and backend.

**Review by SnelPatare — DISMISSED** [review]
I have tested the PR. I would like to detail couple of issues I faced during testing

1. Steps followed:
    - Profile -> Update password -> entered password - New Password field and Confirm Password field.
    - Didn't touch Current password field
   Issue: Not displaying error " Current password is not allowed to be empty"
Error is only shown when we try to enter current field and erase it (which should not be the case)
Note: If the current field is empty it should show the error even when we are trying to enter new password field or confirm password field w/o touching the current password field 
Please find the image below
image

2.  Getting error even after "New passwords and Confirm passwords" are matching
     Please find below image
image

3. Error for password length (8) is not displayed for sign in page. 
Please find image below
image

**Review by vishnupriyaatheti — CHANGES_REQUESTED** [review]
@20chen-7 After verifying the changes I have found below issues:

issue 1: 
Login screen
First give wrong password and click submit button, not getting 'Invalid Password'
error message. Again click submit button then error message is displaying.
Expected: On First click of submit button itself it should display message,
please check.

issue 2:
go to Update password screen and update the password accordingly. the app will
logout automatically and redirect for login page again. Here first give wrong 
password and try to login. Error message is displaying as Expected. After that
correct the password given earlier and try to login, the app is redirecting to 
dashboard page with showing 'Invalid Password' error message in login page while
redirecting to dashboard page.
Expected: Error message should not display on giving correct password.

issue 3:

In Update password screen 'Current password' field must show error message if user
goes to new password & confirmation password fields first without entering current password, once we got keystroke event on it we can clear the error message.

other functionality seems working as expected for me. Thankyou

https://github.com/user-attachments/assets/0a762905-d1f5-4ee2-840a-de8c5db99713


https://github.com/user-attachments/assets/19b8587d-919e-480e-8a29-4951e589aa5e

**Review by cgomezhub — DISMISSED** [review]
after-PR2549 (2)
This change is working good!

after-PR2549
This error label should be displayed below the password entry.

**Review by preethamdnr — APPROVED** [review]
Hello Ivy,
I've reviewed your PR and It is working as expected.
image
image

**Comment by 20chen-7** [comment]
> I have tested the PR. I would like to detail couple of issues I faced during testing
> 
> 1. Steps followed:
>    
>    * Profile -> Update password -> entered password - New Password field and Confirm Password field.
>    * Didn't touch Current password field
>      Issue: Not displaying error " Current password is not allowed to be empty"
>      Error is only shown when we try to enter current field and erase it (which should not be the case)
>      Note: If the current field is empty it should show the error even when we are trying to enter new password field or confirm password field w/o touching the current password field
>      Please find the image below
>      image
> 2. Getting error even after "New passwords and Confirm passwords" are matching
>    Please find below image
>    image
> 3. Error for password length (8) is not displayed for sign in page.
>    Please find image below
>    image
For the first question, for the form built by previous developer, he/she set the disable button part, so the logic here is if you do not even touch anything in the currentpwd, the submit btn will help you check every input schema correctly or not. if not, the submit button will not be able to click. Previous bug related to point 1 in the description, so in order to solve that, I make this invoked by type the input then it auto validate the input.  For the second error, mine does not show such error, checked the screenshot. For the third, if you checked my code, you will find I did not change the length of login form. Because it is designed by previous developer.
Screenshot 2024-08-22 at 11 05 30 AM

**Comment by 20chen-7** [comment]
> > I have tested the PR. I would like to detail couple of issues I faced during testing
> > 
> > 1. Steps followed:
> >    
> >    * Profile -> Update password -> entered password - New Password field and Confirm Password field.
> >    * Didn't touch Current password field
> >      Issue: Not displaying error " Current password is not allowed to be empty"
> >      Error is only shown when we try to enter current field and erase it (which should not be the case)
> >      Note: If the current field is empty it should show the error even when we are trying to enter new password field or confirm password field w/o touching the current password field
> >      Please find the image below
> >      image
> > 2. Getting error even after "New passwords and Confirm passwords" are matching
> >    Please find below image
> >    image
> > 3. Error for password length (8) is not displayed for sign in page.
> >    Please find image below
> >    image
> >    For the first question, for the form built by previous developer, he/she set the disable button part, so the logic here is if you do not even touch anything in the currentpwd, the submit btn will help you check every input schema correctly or not. if not, the submit button will not be able to click. Previous bug related to point 1 in the description, so in order to solve that, I make this invoked by type the input then it auto validate the input.  For the second error, mine does not show such error, checked the screenshot. For the third, if you checked my code, you will find I did not change the length of login form. Because it is designed by previous developer.
> 
> Screenshot 2024-08-22 at 11 05 30 AM

And for your concern, it can be posted as a new bug in the Bug Doc. In my opinion, every PR should not changed a lot.

**Comment by 20chen-7** [comment]
> after-PR2549 (2) This change is working good!
> 
> after-PR2549 This error label should be displayed below the password entry.

resolved

**Comment by 20chen-7** [comment]
> @20chen-7 After verifying the changes I have found below issues:
> 
> issue 1: Login screen First give wrong password and click submit button, not getting 'Invalid Password' error message. Again click submit button then error message is displaying. Expected: On First click of submit button itself it should display message, please check.
> 
> issue 2: go to Update password screen and update the password accordingly. the app will logout automatically and redirect for login page again. Here first give wrong password and try to login. Error message is displaying as Expected. After that correct the password given earlier and try to login, the app is redirecting to dashboard page with showing 'Invalid Password' error message in login page while redirecting to dashboard page. Expected: Error message should not display on giving correct password.
> 
> issue 3:
> 
> In Update password screen 'Current password' field must show error message if user goes to new password & confirmation password fields first without entering current password, once we got keystroke event on it we can clear the error message.
> 
> other functionality seems working as expected for me. Thankyou
> 
>  PR.2549.issue2.mp4 
>  PR.2549.issue1.mp4

resolved, I updated the backend, so for the issue2, I add await loginUser, so if there are any error related, we are required to wait 1-2 seconds for updating error.

**Comment by SnelPatare** [comment]
> > > I have tested the PR. I would like to detail couple of issues I faced during testing
> > > 
> > > 1. Steps followed:
> > >    
> > >    * Profile -> Update password -> entered password - New Password field and Confirm Password field.
> > >    * Didn't touch Current password field
> > >      Issue: Not displaying error " Current password is not allowed to be empty"
> > >      Error is only shown when we try to enter current field and erase it (which should not be the case)
> > >      Note: If the current field is empty it should show the error even when we are trying to enter new password field or confirm password field w/o touching the current password field
> > >      Please find the image below
> > >      image
> > > 2. Getting error even after "New passwords and Confirm passwords" are matching
> > >    Please find below image
> > >    image
> > > 3. Error for password length (8) is not displayed for sign in page.
> > >    Please find image below
> > >    image
> > >    For the first question, for the form built by previous developer, he/she set the disable button part, so the logic here is if you do not even touch anything in the currentpwd, the submit btn will help you check every input schema correctly or not. if not, the submit button will not be able to click. Previous bug related to point 1 in the description, so in order to solve that, I make this invoked by type the input then it auto validate the input.  For the second error, mine does not show such error, checked the screenshot. For the third, if you checked my code, you will find I did not change the length of login form. Because it is designed by previous developer.
> > 
> > 
> > Screenshot 2024-08-22 at 11 05 30 AM
> 
> And for your concern, it can be posted as a new bug in the Bug Doc. In my opinion, every PR should not changed a lot.

I agree with statements related to issues 1 and 3.
For issue 2. I did negative testing and steps I followed are
1. Add new password -> Add confirm password with non matching characters. Edit confirm password to matching password - Error will be gone. (Positive Scenario)
2. But when you edit confirm password and then try to edit new password as per confirm password. Even though passwords are matching it still shows error. (Negative Scenario)

The changes are working well for positive scenario. But, it will be great if we can address negative scenario as well.

**Comment by 20chen-7** [comment]
> > > > I have tested the PR. I would like to detail couple of issues I faced during testing
> > > > 
> > > > 1. Steps followed:
> > > >    
> > > >    * Profile -> Update password -> entered password - New Password field and Confirm Password field.
> > > >    * Didn't touch Current password field
> > > >      Issue: Not displaying error " Current password is not allowed to be empty"
> > > >      Error is only shown when we try to enter current field and erase it (which should not be the case)
> > > >      Note: If the current field is empty it should show the error even when we are trying to enter new password field or confirm password field w/o touching the current password field
> > > >      Please find the image below
> > > >      image
> > > > 2. Getting error even after "New passwords and Confirm passwords" are matching
> > > >    Please find below image
> > > >    image
> > > > 3. Error for password length (8) is not displayed for sign in page.
> > > >    Please find image below
> > > >    image
> > > >    For the first question, for the form built by previous developer, he/she set the disable button part, so the logic here is if you do not even touch anything in the currentpwd, the submit btn will help you check every input schema correctly or not. if not, the submit button will not be able to click. Previous bug related to point 1 in the description, so in order to solve that, I make this invoked by type the input then it auto validate the input.  For the second error, mine does not show such error, checked the screenshot. For the third, if you checked my code, you will find I did not change the length of login form. Because it is designed by previous developer.
> > > 
> > > 
> > > Screenshot 2024-08-22 at 11 05 30 AM
> > 
> > 
> > And for your concern, it can be posted as a new bug in the Bug Doc. In my opinion, every PR should not changed a lot.
> 
> I agree with statements related to issues 1 and 3. For issue 2. I did negative testing and steps I followed are
> 
> 1. Add new password -> Add confirm password with non matching characters. Edit confirm password to matching password - Error will be gone. (Positive Scenario)
> 2. But when you edit confirm password and then try to edit new password as per confirm password. Even though passwords are matching it still shows error. (Negative Scenario)
> 
> The changes are working well for positive scenario. But, it will be great if we can address negative scenario as well.
I follow your way, but here is my Latest video. Do you use chorme incognito mode? That will be better to test to get rid of some cache issues.

https://github.com/user-attachments/assets/469ad3fe-1742-4c72-bc72-d1eb9cd7b870

**Review by SMitta11 — APPROVED** [review]
Tested this PR and it works as expected
Screenshots:
Screen Shot 2024-08-23 at 1 07 36 AM
Screen Shot 2024-08-23 at 1 07 54 AM
Screen Shot 2024-08-23 at 1 08 27 AM
Screen Shot 2024-08-23 at 1 08 34 AM

**Comment by SnelPatare** [comment]
> > > > > I have tested the PR. I would like to detail couple of issues I faced during testing
> > > > > 
> > > > > 1. Steps followed:
> > > > >    
> > > > >    * Profile -> Update password -> entered password - New Password field and Confirm Password field.
> > > > >    * Didn't touch Current password field
> > > > >      Issue: Not displaying error " Current password is not allowed to be empty"
> > > > >      Error is only shown when we try to enter current field and erase it (which should not be the case)
> > > > >      Note: If the current field is empty it should show the error even when we are trying to enter new password field or confirm password field w/o touching the current password field
> > > > >      Please find the image below
> > > > >      image
> > > > > 2. Getting error even after "New passwords and Confirm passwords" are matching
> > > > >    Please find below image
> > > > >    image
> > > > > 3. Error for password length (8) is not displayed for sign in page.
> > > > >    Please find image below
> > > > >    image
> > > > >    For the first question, for the form built by previous developer, he/she set the disable button part, so the logic here is if you do not even touch anything in the currentpwd, the submit btn will help you check every input schema correctly or not. if not, the submit button will not be able to click. Previous bug related to point 1 in the description, so in order to solve that, I make this invoked by type the input then it auto validate the input.  For the second error, mine does not show such error, checked the screenshot. For the third, if you checked my code, you will find I did not change the length of login form. Because it is designed by previous developer.
> > > > 
> > > > 
> > > > Screenshot 2024-08-22 at 11 05 30 AM
> > > 
> > > 
> > > And for your concern, it can be posted as a new bug in the Bug Doc. In my opinion, every PR should not changed a lot.
> > 
> > 
> > I agree with statements related to issues 1 and 3. For issue 2. I did negative testing and steps I followed are
> > 
> > 1. Add new password -> Add confirm password with non matching characters. Edit confirm password to matching password - Error will be gone. (Positive Scenario)
> > 2. But when you edit confirm password and then try to edit new password as per confirm password. Even though passwords are matching it still shows error. (Negative Scenario)
> > 
> > The changes are working well for positive scenario. But, it will be great if we can address negative scenario as well.
> > I follow your way, but here is my Latest video. Do you use chorme incognito mode? That will be better to test to get rid of some cache issues.
> 
>  Screen.Recording.2024-08-22.at.3.32.52.PM.mov

I tried using Incognito mode. I am still getting the issue. Please let me know if I am missing any steps. Here is the recorded video.

https://github.com/user-attachments/assets/c2c1fc8c-0e1f-48e6-967b-ddad4d522197

**Review by Lemonnycodes — APPROVED** [review]
Hi,

Tested the PR and it works as expected.

Screenshot 2024-08-23 232656
Screenshot 2024-08-23 233017

**Comment by yashwanth170** [comment]
Hi,

The PR is functioning as expected. I've attached screenshots for your reference.
360810077-db69ea6b-13c2-4708-9809-ba37793e9676 (1)
360810077-db69ea6b-13c2-4708-9809-ba37793e9676
Screenshot 2024-08-28 212750

**Comment by 20chen-7** [comment]
> > > > > > I have tested the PR. I would like to detail couple of issues I faced during testing
> > > > > > 
> > > > > > 1. Steps followed:
> > > > > >    
> > > > > >    * Profile -> Update password -> entered password - New Password field and Confirm Password field.
> > > > > >    * Didn't touch Current password field
> > > > > >      Issue: Not displaying error " Current password is not allowed to be empty"
> > > > > >      Error is only shown when we try to enter current field and erase it (which should not be the case)
> > > > > >      Note: If the current field is empty it should show the error even when we are trying to enter new password field or confirm password field w/o touching the current password field
> > > > > >      Please find the image below
> > > > > >      image
> > > > > > 2. Getting error even after "New passwords and Confirm passwords" are matching
> > > > > >    Please find below image
> > > > > >    image
> > > > > > 3. Error for password length (8) is not displayed for sign in page.
> > > > > >    Please find image below
> > > > > >    image
> > > > > >    For the first question, for the form built by previous developer, he/she set the disable button part, so the logic here is if you do not even touch anything in the currentpwd, the submit btn will help you check every input schema correctly or not. if not, the submit button will not be able to click. Previous bug related to point 1 in the description, so in order to solve that, I make this invoked by type the input then it auto validate the input.  For the second error, mine does not show such error, checked the screenshot. For the third, if you checked my code, you will find I did not change the length of login form. Because it is designed by previous developer.
> > > > > 
> > > > > 
> > > > > Screenshot 2024-08-22 at 11 05 30 AM
> > > > 
> > > > 
> > > > And for your concern, it can be posted as a new bug in the Bug Doc. In my opinion, every PR should not changed a lot.
> > > 
> > > 
> > > I agree with statements related to issues 1 and 3. For issue 2. I did negative testing and steps I followed are
> > > 
> > > 1. Add new password -> Add confirm password with non matching characters. Edit confirm password to matching password - Error will be gone. (Positive Scenario)
> > > 2. But when you edit confirm password and then try to edit new password as per confirm password. Even though passwords are matching it still shows error. (Negative Scenario)
> > > 
> > > The changes are working well for positive scenario. But, it will be great if we can address negative scenario as well.
> > > I follow your way, but here is my Latest video. Do you use chorme incognito mode? That will be better to test to get rid of some cache issues.
> > 
> > 
> > Screen.Recording.2024-08-22.at.3.32.52.PM.mov
> 
> I tried using Incognito mode. I am still getting the issue. Please let me know if I am missing any steps. Here is the recorded video.
> 
>  PR2549.mp4

https://github.com/user-attachments/assets/3df17ba7-38d8-47e8-a0a1-f36fc3012e1c

Did you pull my latest change?

**Comment by vishnupriyaatheti** [comment]
> > @20chen-7 After verifying the changes I have found below issues:
> > issue 1: Login screen First give wrong password and click submit button, not getting 'Invalid Password' error message. Again click submit button then error message is displaying. Expected: On First click of submit button itself it should display message, please check.
> > issue 2: go to Update password screen and update the password accordingly. the app will logout automatically and redirect for login page again. Here first give wrong password and try to login. Error message is displaying as Expected. After that correct the password given earlier and try to login, the app is redirecting to dashboard page with showing 'Invalid Password' error message in login page while redirecting to dashboard page. Expected: Error message should not display on giving correct password.
> > issue 3:
> > In Update password screen 'Current password' field must show error message if user goes to new password & confirmation password fields first without entering current password, once we got keystroke event on it we can clear the error message.
> > other functionality seems working as expected for me. Thankyou
> > PR.2549.issue2.mp4
> > PR.2549.issue1.mp4
> 
> resolved, I updated the backend, so for the issue2, I add await loginUser, so if there are any error related, we are required to wait 1-2 seconds for updating error.

@20chen-7 I don't see issue1 also not resolved. Can you please check.

**Review by oliviahyw — APPROVED** [review]
I have tested this PR and it's working as expected.
Screenshot 2024-08-30 at 5 02 22 PM
Screenshot 2024-08-30 at 5 02 41 PM

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected. Below are the screenshots for reference:
PR_Review_2549_1
PR_Review_2549_2
PR_Review_2549_3

**Review by vedantg24 — APPROVED** [review]
Tested the PR, and the changes are working as expected. When trying to update password, if we enter the new password first, there is an alert saying “Current Password is not allowed to be empty”. After entering the current password, the alert is cleared. Also, when logging in, the “Invalid Password” alert is now placed perfectly.

https://github.com/user-attachments/assets/a003cc3b-fd31-4acc-a283-6433d286743a

**Comment by FayeLV** [comment]
Hi,
All tested functionalities passed perfectly, demonstrating that the error handling and validation logic is working as expected. Below is a summary of the testing results:
**Change Password Page:**
When the current password field is left empty, the appropriate error message "Current Password is not allowed to be empty" is displayed correctly.
When the new password does not meet the required criteria, the error message "New Password should be at least 8 characters long and must include at least one uppercase letter, one lowercase letter, one number and one special character" is correctly shown.
When the confirmation password does not match the new password, the correct error message "Confirm Password must match new password" is displayed.
**Login Page:**
When the email field is left empty, the error message "Email is not allowed to be empty" is displayed as expected.
When an invalid email format is entered, the error message "Email must be a valid email" is correctly shown.
Snipaste_2024-08-31_12-12-56
Snipaste_2024-08-31_12-14-58
Snipaste_2024-08-31_12-15-37
Snipaste_2024-08-31_12-17-09

**Review by FayeLV — APPROVED** [review]

**Review by ashayk9 — CHANGES_REQUESTED** [review]
Hi, All tested functionalities passed successfully, confirming that the error handling and validation logic is working as intended. Here is a summary of the testing results:
Change Password Page:
* When the current password field is left empty, the error message "Current Password is not allowed to be empty" is correctly displayed. However, entering the current password after filling in the new password removes the "Current Password cannot be empty" error as expected.
* When the new password does not meet the required criteria, the error message "New Password should be at least 8 characters long and must include at least one uppercase letter, one lowercase letter, one number, and one special character" appears as expected.
* When the confirmation password does not match the new password, the error message "Confirm Password must match new password" is correctly shown.
Login Page:
* When the email field is left empty, the error message "Email is not allowed to be empty" is displayed as expected.
* When an invalid email format is entered, the error message "Email must be a valid email" is correctly shown.

However, when an invalid password is entered, the error message appears under the email field instead of the password field. I am not sure if I made a mistake during testing. I checked out both the frontend and backend branches and ran npm install as well. Please let me know if I made any errors in my testing process.

Screenshot 2024-09-04 at 10 56 23 AM
Screenshot 2024-09-04 at 10 56 39 AM
Screenshot 2024-09-04 at 10 57 16 AM
Screenshot 2024-09-04 at 10 57 41 AM
Screenshot 2024-09-04 at 10 58 41 AM
Screenshot 2024-09-04 at 11 33 53 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
