### PR TITLE
Harshida fix user management changes

### PR DESCRIPTION
**Pull request by harshidad**
# Description
Make new people added to system show up at the top of the user list.
1. Admin Login → Other Links → User Management
2. Newest people should show up at the top of the user list. Currently, if I add multiple people one after another, it looks like it is alphabetizing them by day and based on their first names. Newest people should always be at the top. 
3. Please also add a copy icon and ability by their first name, last name, and end date. 

Screenshot 2023-10-07 100112

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ Admin Login → Other Links → User Management
5. check copy icon available by their first name, last name, and end date. (Similar to email)
6. Now create new user. 
7. Verify newest people should show up at the top of the user list. (Note: user list to be organized with latest START date at the top)

## Note:
User list to be organized with latest START date at the top.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/d202f1e9-589a-401c-9886-6901f1c69b0b

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/6a944238-d201-4a7c-b474-99ceebda1c65

### CODE REVIEW

**Review by JeffLi117 — DISMISSED** [review]
Changes work as intended. Great job!

Initial view:
image

Testing the copy icons for first name, last name, and end date:
image

New user profile created that automatically gets listed at the top of the list:
image

**Review by TuanDinh140194 — DISMISSED** [review]
Hi! I have test your PR and everything look good. When I create new user name, It appear on top of the list. When I click copy icon and past it, it appear to copy the text. Nice jobs !

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/7a243304-c94e-4fc9-9011-e9e680d4bcdc

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions. The feature is working great. I tested that the users are ordered by the time they are created. The order is not alphabetically. Good job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/3eb7da28-414f-4832-8645-caec21cfdd80

**Review by yangfan2001 — APPROVED** [review]
Hi, I have tested your PR and it worked as expected. Great Job!
Newly created user will be at the top of the list:
image
I can also copy basic info using copy button:
image

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works as intended.
Screenshot 2023-10-07 at 8 10 06 PM

**Comment by yi-lin-1234** [comment]
Hi, I have tested your PR and it worked as expected. Great Job!
1. The newest users should appear at the top of the user list, rather than being sorted by first name.
2. The copy and paste functions work correctly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/37a40573-3561-45df-ab25-e8ca3002579d

**Review by yi-lin-1234 — APPROVED** [review]
Hi, I have tested your PR and it worked as expected. Great Job! The newest users should appear at the top of the user list, rather than being sorted by first name. The copy and paste functions work correctly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/48ce1673-1b89-4c04-925d-43a09beb3369

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/eb6f5102-3764-4bc5-8b99-858591b379eb

**Review by Shubhu0 — APPROVED** [review]
Hi @harshidad Reviewed and tested the PR. Working as intended. I was able to copy both the info and use it to create a new user! Good job! 

image

image

**Review by belagaam — APPROVED** [review]
I tested the PR as per the instructions. Everything works as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/4ebc0225-91a0-4152-bf67-65bd5ce4ff82

**Comment by beblicarl** [comment]
When i created a new user, the new user went on top of the list. However, when I created a subsequent user shortly, the subsequent user was second on the list instead of first.

[screencast-localhost_3000-2023.10.09-15_59_07.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/e6105042-8170-4e72-85d2-0f3f96a980e2)


image

**Review by lacnoskillz — DISMISSED** [review]
Hello Harshida!
I pulled your changes locally and tested them
It appears it is working as intended and when I create a new user it is displayed at the top nice work!

[Untitled_ Oct 9, 2023 3_37 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/8b0ccece-a48c-49ab-8961-9432d70c619e)

Note there is some console.log errors unrelated to your changes
image

**Review by Sssky-18 — DISMISSED** [review]
Hi @harshidad, I tested this PR, and for all of the features mentioned above, this PR worked as expected. The copy icons were clickable and the text can be copied properly. The "create account" button worked normally, and the newly created account was listed on the top of the sheet. Great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/c851c8d2-6419-4a1b-9e7a-5147e553d262

**Review by DavidC0126 — APPROVED** [review]
Hi I tested the PR and it works as described.

Uploading PR1389.mov…

**Review by KurtisIvey — APPROVED** [review]
pr1389 is good to go. Users are sorted properly. confirmed this as well through implementation of the start date column to ensure everything was consistent

Screenshot 2023-10-11 at 2 25 07 PM
Screenshot 2023-10-11 at 2 29 36 PM

**Comment by one-community** [comment]
Thank you all! Address the merge conflicts here and I'll merge this!

**Comment by Lin1404** [comment]
Hi @harshidad  , I have tested your PR and it worked as expected. Great Job!
PR1389

**Review by Lin1404 — APPROVED** [review]

**Review by StrawberryCalpico — CHANGES_REQUESTED** [review]
Hi I tested your PR! The copy and past functionality works as expected, great job!
However when i create a new user, it won't be guaranteed to be on the top of the user list.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/bdd5b015-a49e-47e0-af03-d06f645d9d90

**Review by KurtisIvey — APPROVED** [review]
Everything still works after clearing up the merge conflict. Newest user is at the top and all copy buttons work. Good job

Screenshot 2023-10-31 at 1 02 58 PM

**Pull request merged**
