### PR TITLE
fix usermanagement not getting update

### PR DESCRIPTION
**Pull request by suigunfjc**
# Description
Fix bug:
(PRIORITY MEDIUM) Vitor/Jae: When updating a role of a user on the “Profile Page”, the “User Management” page doesn’t get updated, and the changed role of the user remains the same as before.

## Mainly changes explained:
One line change, fix the bug caused by commit [Set final day button admin front-end](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/68ca7d79e4ce9823dae22bf06125c694a728471b)
This bug causes user management page can't trigger the user profile fetch action. In current app, after update a user's role, the user management page can be updated by opening reports and teams management pages since these pages will trigger the action correctly:
Screenshot 2023-03-07 223032
Screenshot 2023-03-07 223111

## How to test:

1. Dashboard -> User management
2. Choose a user and update its role
3. Go back to user management page to see the change.

### CODE REVIEW

**Comment by vitorsaa2k** [comment]
Thank you for fixing this bug @suigunfjc!

It's working as intended.


https://user-images.githubusercontent.com/17365161/223828047-c9d66d35-5da6-4fc0-b0e4-beeaeba5ec42.mp4

**Review by Lucas-E — APPROVED** [review]
Hey, just reviewed this PR, and it's working very well. I changed the Lucas Test Volunteer from Volunteer to Administrator as it's shown.
Great job!
Captura de tela de 2023-03-08 23-42-14

Captura de tela de 2023-03-08 23-42-33

**Comment by mpavithr** [comment]
Hi, I have tested this and it is working for me as well. I changed the role and it reflects the changes correctly.
pr699
pr699_2

**Comment by crystalsong2021** [comment]
@suigunfjc I tested the function and works as intended. Nicely done!
https://user-images.githubusercontent.com/18197013/223943553-86ddf359-fa55-4015-a4d5-ea58cfddd2fb.mov

**Review by crystalsong2021 — DISMISSED** [review]

**Comment by NyahJ** [comment]
Hi @suigunfjc,

I have changed the role of one of my testing accounts shown as below, the process was smooth and the result shows as intended: the updated role appears in the user management page. Thanks for your efforts!
截屏2023-03-09 下午2 15 18

**Review by kangjay88 — DISMISSED** [review]
Hi @suigunfjc, I have tested this PR and it works as intended. Switched my user role from 'mentor' to 'volunteer',  and the update reflects on user management. Nice one line change!
PR699 #1
PR699 #2

**Comment by Jorge-Nerd** [comment]
Hi @suigunfjc  I just tested the task and it work fine for me

https://user-images.githubusercontent.com/77848827/224520856-6a40b124-fdcb-4e47-a8e6-5e12c12bc8d1.mp4

**Review by rauleffting — DISMISSED** [review]
Hi @suigunfjc. Your PR worked as intended.

https://user-images.githubusercontent.com/29555732/224745969-11be38f5-4a6b-4901-b4a2-6996ca55fb3f.mp4

Good job!

**Comment by one-community** [comment]
From Yiyun: "Please push an empty commit without any codes changes to this PR, try to rerun those builds, lets see whether the build fixes itself."

**Comment by suigunfjc** [comment]
> From Yiyun: "Please push an empty commit without any codes changes to this PR, try to rerun those builds, lets see whether the build fixes itself."

Made the commit but didn't fix it.

**Comment by one-community** [comment]
Thank you for trying. The details of the CircleCI issue say: 
Could not find a usable config.yml, you may have revoked the CircleCI OAuth app.
Please sign out of CircleCI and log back in with your VCS before triggering a new pipeline.

Any idea what that means?

**Comment by suigunfjc** [comment]
@one-community Fixed at #730

**Pull request merged**
