### PR TITLE
Shuhua - Create different view for ! summary

### PR DESCRIPTION
**Pull request by Shuhua-L**
# Description
task-description

## Related PRS (if any):
N/A

## Main changes explained:
- Update the file **`src/components/SummaryBar/SummaryBar.jsx`** to incorporate a different view for users exempt from summary submission

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Verify that Mentor users see the desired view, and summary submission function still works
  4.1. Log in as a Mentor user, and confirm that the !summary view meets the expectations
  4.2. Click the text “You don’t need to …” to submit a summary
5. Verify that the view updates properly as summary requirements change
  5.1. Log in as an Admin user, and verify that the Summary Bar shows the default view
  5.2. Change the Weekly Summary requirement: Go to View Profile → Volunteering Times tab, set "**Weekly Summary Options**" to "**Not Required**", and save the change
  5.3. Go back to the Dashboard and verify the updated view
  5.4. (Optional) Toggle the "**Weekly Summary Options**" back and see the updated view
6. (Optional) Verify step 5 with a user other than Mentor/Admin

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/f3ee7431-45c2-4892-bc1a-f90ca15803da

## Note:
1. Use a backslash to escape `!` if you switch branches in the terminal: 
  `git checkout -b Shuhua-Create-different-view-for-\!summary`
2. You might have noticed my [previous PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1652/) for this task. I ran into some trouble resolving merge conflicts and stumbled upon a simpler fix, hence this new PR
3. These potential errors are unrelated 
potential errors

### CODE REVIEW

**Review by mohabbasd — CHANGES_REQUESTED** [review]
Hello, I tried your PR but unfortunately it is not working as expected, I logged in as owner and as admin but none of them shown any changes.
Screenshot 2024-02-10 at 10 34 00 PM
Screenshot 2024-02-10 at 10 34 07 PM

**Review by meetpadhiar4 — CHANGES_REQUESTED** [review]
Hi, I tested your PR but the changes are not reflected in the dev environment. I tested with mentor and admin accounts, please refer the videos attached.



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/1c5c2744-2577-4755-8c9c-83297b860514


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/ef7f6f4c-067f-43bf-996c-5acf30c8f6f6

**Comment by Shuhua-L** [comment]
> Hi, I tested your PR but the changes are not reflected in the dev environment. I tested with mentor and admin accounts, please refer the videos attached.
> 
>  PR.1941.admin.mov 
>  PR.1941.mentor.mov

@meetpadhiar4 Thanks for reviewing! Everything seems fine when I check your accounts from my owner account. So im not sure what went wrong. Have you checked into the current branch and cleared the site cache before starting the app? Are there any errors in the console?
Screenshot 2024-02-12 at 3 36 41 PM
Screenshot 2024-02-12 at 3 40 10 PM

**Review by swathyjayaseelan — DISMISSED** [review]
The changes look good. I logged in as a Mentor and as a Volunteer with the 'Summary Not Required' flag. In both the cases, I was able to the see the other view. 

One suggestion here is to avoid using '!' in the branch name. The exclamation mark is not a valid character in branch names. Some terminal shells interpret it as a shell command and we can use it as a branch only if we escape it with a backslash.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/73664442-897d-4056-947f-d5bb3cd04866

**Review by TareqMia — DISMISSED** [review]
Hi @Shuhua-L, tested this PR and everything works as expected 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/3ce990fd-4d21-440d-ad7f-c07f89721181

**Review by XiaohanMeng — DISMISSED** [review]
Hi, I tested this PR using both the Mentor and Admin roles. Both functioned very well: mentors can opt not to add a weekly summary, while admins have the option to toggle the addition of a weekly summary. Please see the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/b5e1332f-f718-4ecd-9510-73f21ca30a7d

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I re reviewed your PR and it is working correctly. Please refer the screenshots attached.

PR 1941 1
PR 1941 2

**Review by yaow62023 — DISMISSED** [review]
Hi, I have test your PR, The box of summary status change at different status. Check the video below for more details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/560aa43e-6dc9-4f8b-941b-873b26c4058b

**Comment by anandsesha** [comment]
Hi, I tested this PR using the Mentor, Admin, as well as Volunteer roles. All functions as expected. Admins can opt to not add a weekly summary. For Volunteer users, that option is unavailable. Please see screenshots below.

Screenshot (721)
Screenshot (720)
Screenshot (722)
Screenshot (715)
Screenshot (716)

for volunteer the option to opt-out is not given as expected
Screenshot (723)
Screenshot (724)

**Comment by MQChen211** [comment]
Hi, I tested your PR with both the Mentor and the Owner accounts, and it works perfectly.

Tested by the Mentor account:
截屏2024-04-04 16 29 05
截屏2024-04-04 16 34 30
截屏2024-04-04 16 37 29


Tested by the Owner account:
截屏2024-04-04 16 39 06
截屏2024-04-04 16 41 00

**Review by MQChen211 — DISMISSED** [review]

**Review by kylepham — DISMISSED** [review]
I tested on Mentor and Admin account as suggested and confirmed that summary submission summary worked well, and the text displayed correctly based on the Mentor role and summary requirement setting.

Mentor account: 
Screenshot 2024-04-07 at 3 59 21 PM

Screenshot 2024-04-07 at 4 02 10 PM

Admin account:
Screenshot 2024-04-07 at 4 04 08 PM

Screenshot 2024-04-07 at 4 04 27 PM

**Review by yvonnep165 — DISMISSED** [review]
Hi @Shuhua-L , I have tested your PR with Mentor, Admin and Owner accounts and everything works as intended. Please refer to the video below.  Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/545a4be6-ad05-459e-8381-da6e40c3b1ee

**Review by p-suram — APPROVED** [review]
Hey. Good Work. I verified with Mentor role, and I removed `required` for Volunteer, Manager roles and tried, Working as expected. Please find attached video for Volunteer user.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/c959a968-4c4a-4f8a-8475-91b7ab91480d

 **Suggestion:**
- It would be better to disable `Weekly Summary Options` for all user roles other than `Admin` in their own Profile -> Volunteering Times page. Current functionality is that we are showing them option to update on UI (where we are actually not updating). It is misleading. Please find attached video below of `Manager` user.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/b35b7432-ecb4-442f-8593-e409599b1cb8

**Review by j-corp-25 — COMMENTED** [review]
Hi @Shuhua-L ,

I was also having issues with testing the Admin instructions. Mentor view shows as expected but Admin summary does not show purple.

I recorded my testing below.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/2f6e9773-2009-4f5b-8785-277169b950d5

**Review by p-suram — CHANGES_REQUESTED** [review]
Following up on my previous review : 
- It would be better to disable `Weekly Summary Options` for all user roles other than `Admin` in their own Profile -> Volunteering Times page. Current functionality is that we are showing them option to update on UI (where we are actually not updating). It is misleading. Please find attached video below of `Manager` user.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/b35b7432-ecb4-442f-8593-e409599b1cb8

**Comment by Shuhua-L** [comment]
> Following up on my previous review :
> 
> * It would be better to disable `Weekly Summary Options` for all user roles other than `Admin` in their own Profile -> Volunteering Times page. Current functionality is that we are showing them option to update on UI (where we are actually not updating). It is misleading. Please find attached video below of `Manager` user.
> 
>  2024-04-13.18-02-11.mp4

Hi @p-suram , thanks for reviewing. The design/implementation of the `Weekly Summary Options` is out of the scope of this task. This feature branch focuses on rendering the "!Summary" view conditionly.

**Pull request merged**
