### PR TITLE
Nahiyan_Fix User Profile Buttons for Dark Mode

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Now all buttons on the user profile should have a solid background when in dark mode.

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Updated all buttons on user profile in dark mode
- Created a slight border on dark mode button

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard→ user profile
6. verify that all buttons have a solid background when in dark mode

## Screenshots or videos of changes:
Screenshot 2024-08-03 112239
Screenshot 2024-08-03 112316

### CODE REVIEW

**Review by abdel-lall — APPROVED** [review]
LGTM, Nice job!
Screenshot 2024-08-03 114354
Screenshot 2024-08-03 114401

**Review by manikittu810 — APPROVED** [review]
Hello @Nahiyan-16 , I have gone through the mentioned steps and everything working as  mentioned. Here is the screenshot.

Screenshot 2024-08-03 at 9 39 39 AM

Thankyou.

**Review by SatyashanthiT — APPROVED** [review]
Reviewed this PR and could observe the dark background for the buttons!!

db-2
dB-1

**Review by Gauravmg6 — APPROVED** [review]
The changes are as expected. It's good.

Screenshot 2024-08-03 164452

**Review by jinxyou — APPROVED** [review]
All the button seems fine. Great work!
image

**Review by aaryaneil — COMMENTED** [review]
Tested the PR and all the buttons have a solid background in dark mode.
Screenshot 2024-08-04 at 6 28 31 PM

**Pull request merged**
