### PR TITLE
Haoyue fix formatting of created title

### PR DESCRIPTION
**Pull request by oliviahyw**
# Description
(PRIORITY HIGH) Jae: Quick Setup Tool: Fix Formatting of Created Titles (WIP Haoyue)
Profile page>Add a New Title>Click Existing
Linked is Required should be “Link” is required
“Add A New Title” should be “Add New QST” with mouseover text that says “Click this to add a new Quick Setup Title”
Media Folder should wrap within the box, no overflow. Should also be a live/clickable link

## Related PRS (if any):
This frontend PR is not related to any backend PR.

## Main changes explained:
Update AssignSetupModal.jsx and QuickSetupModal.jsx for modifying text, adding mouseover text, fixing the overlapping text and adding media folder link.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to View Profile→ Add New QST
6. verify the button text has changed to "Add New QST"
7. verify the mouseover text of "Click this to add a new Quick Setup Title"
8. Click existing QST, verify the text changed to "Link is required"; the Media Folder text does not overflow; and if the media folder is a link, it should be clickable.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/5b1d1a02-6a30-42ac-bf77-0750e3163d1f

### CODE REVIEW

**Review by RishithaMamidala — APPROVED** [review]
@oliviahyw 
The add QST button has a mouse over text and the media link is required and clickable.

https://github.com/user-attachments/assets/22f88fd7-195c-43af-815f-caa54dddd7e0

**Review by jinxyou — DISMISSED** [review]
When creating new QST, the button and mouseover text is working fine. For existing QST, the displaying text is good. Great work!
Screenshot 2024-09-06 223904
Screenshot 2024-09-06 223958

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.

PR 2648

Thank You

**Review by panchalvatneu — APPROVED** [review]
Changes are working as expected:

https://github.com/user-attachments/assets/004f6623-a86d-4620-a81c-021430344150

**Review by Gauravmg6 — APPROVED** [review]
All the functionalities mentioned in the instructions are working as expected.
Screenshot 2024-09-08 021705

**Review by vishavk1992 — DISMISSED** [review]
I have reviewed this PR and everything works as expected
Screenshot 2024-09-11 154218

**Review by ddshah878 — DISMISSED** [review]
Changes are working as expected. Good job!

https://github.com/user-attachments/assets/a253566e-a2da-4e9c-b59e-ace45d40f4b8

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/5be775e5-0c92-4835-aee6-dfcbfdc43d8d

**Review by mohangadde1 — APPROVED** [review]
image
image
changes mentioned are working as expected.

**Review by ArtemisNyx3 — DISMISSED** [review]
All changes working as expected. Good code 👍🏽 
image
image

**Review by Watchdog00 — COMMENTED** [review]
Tested the changes locally and everything works as expected. The 'Add New QST' button displays the correct text, the tooltip appears as specified, the error message has been updated to 'Link is required', and the media folder link is functional without any text overflow. Great job on the fix!

**Review by Abhinav-Ankur786 — DISMISSED** [review]
It is working as per request
PR - #2648

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
