### PR TITLE
Harshida fix filtering option on Material list component

### PR DESCRIPTION
**Pull request by harshidad**
# Description
Material List component having the Filter Option. 
Filter by : Project and Filter by: Material Name.

## Main changes explained:
- Go to Materail List 
- Verify Filter Options: Project and Maretail. 
- Check Material List gets filter by both the options.

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to BMDashboard→ MaterialList
5. verify Filter Options available By Project and Marerial. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/4a5a420b-ca2a-4509-bfaa-bc94d4d9b49d

### CODE REVIEW

**Review by lichanghaogit — APPROVED** [review]
Hi @harshidad 
I tested this PR on my local environment and the filter functions as expected, nice work!

Screenshot 2023-11-22 at 8 28 24 PM
Screenshot 2023-11-22 at 8 28 32 PM
Screenshot 2023-11-22 at 8 28 39 PM
Screenshot 2023-11-22 at 8 28 53 PM

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-localhost_3000-2023.11.23-03_28_57.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/2dbda161-c6ae-49e3-898a-5ce7bfaf3aeb)

**Review by beblicarl — APPROVED** [review]

**Comment by Cavein254** [comment]
Hi @harshidad, tested the functionality of the code and the code works as intended :+1: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/c5011666-b1de-43c0-8498-a6901eff4029

**Review by shalabhtayal — APPROVED** [review]
works as intended. 

One question to @harshidad, when the project isnt selected, material filter doesnt work. Maybe while ordering in bulk, it would be nice to have this feature.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10181678/846b6244-56b4-4e9c-a46b-8226b0d82c2d

**Comment by ptrpengdev** [comment]
Tested the Project and Material filters, and the feature works as expected, except for the issue mentioned by [shalabhtayal](https://github.com/shalabhtayal). The data grid does not show any results if only the material filter is selected without the project filter.

Screenshot attached **(No result returned if only material filter applied)**:
 



Other features work as expected:

**Review by tdkent — APPROVED** [review]

**Pull request merged**
