### PR TITLE
Masasa - added indentation to subpermissions in modal

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
# Description
Indentation necessary for subpermissions in the permissions modal component
Screenshot 2023-08-22 at 1 26 17 PM

## Related PRS (if any):
No related PRs
…

## Main changes explained:
- created a condition in UserPermissionsPopUp.jsx to differentiate between main permissions and sub_permissions and then added the necessary formatting

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner user
4. go to other links→ Permissions Management→ Manage User permissions
5. verify that the main subperimissions have been indented

## Screenshots or videos of changes:

Screenshot 2023-08-24 at 3 30 47 PM

### CODE REVIEW

**Review by ramyaram2092 — APPROVED** [review]
Hello @ThapeloMasasa  Looks good to me. Good job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/924146aa-7cb0-4511-87bb-704868e95f91

**Review by tsunami776 — APPROVED** [review]
I've tested the functionality using both the Admin and Owner accounts. In the "Manage User Permissions" section, the main permissions are prominently displayed, while the sub-permissions are appropriately indented. This layout matches the visuals provided in your screenshot.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/fbaf9eae-0be8-4882-816b-6d0629004bc9

**Review by DavidC0126 — DISMISSED** [review]
Hi @ThapeloMasasa, test your PR and it looks good to me.

Screenshot 2023-08-22 at 2 45 18 PM
Screenshot 2023-08-22 at 2 45 33 PM
Screenshot 2023-08-22 at 2 45 40 PM

**Comment by one-community** [comment]
Looking good! Just need the missing "i" icons added here and I'll merge this.

**Review by eduvarjaor — DISMISSED** [review]
Working as intended. Great job!

Screenshot_1
Screenshot_2

**Review by iTvX — APPROVED** [review]
I have tesed your pr, lt looks good. Good job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/5a53372f-0ccc-45a1-9b34-f36f8cc366a7

**Review by BaileyM96 — DISMISSED** [review]
Good afternoon @ThapeloMasasa !

I reviewed your changes and everything looks great for the user permissions great work

[PR #1163 Indentation to sub permissions.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/198de4e3-534b-4114-85fd-d118e7070aa2)

**Review by yunshan111 — DISMISSED** [review]
Tested this PR, LGTM.

image

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @ThapeloMasasa 

I reviewed your PR but I am unable to test it.
When I logged into an owner account I do not see others links or permission mangement. 
I revieed the rights and my owner account has full rights yet I cannot see those permissions. 
When logged into the development branch I am able to view everything correctly. 

I am running nvm and switch to Node 14.17.6, I am also using the development backend as well. 


Screenshot 2023-08-23 at 8 13 33 PM

**Review by Haoj1 — APPROVED** [review]
All subperimissions have been indented. Looks good to me. Great job @ThapeloMasasa 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/f5c1cd90-a0a2-4bd8-b885-021a1c817c30

**Review by EdwinLauM — CHANGES_REQUESTED** [review]
Hey @ThapeloMasasa! Changes work as expected! Was wondering if maybe you could add more vertical spacing between the add buttons?

**Review by yurisokolovicz — APPROVED** [review]
Dear @ThapeloMasasa 

Your pull request works as intended. I can now differentiate between permissions and sub_permissions. Good job!

image

**Review by Jiyuanxia — APPROVED** [review]
Hi @ThapeloMasasa , I have reviewed your pull request and tested it. It works as you intended. Good job!
Screenshot 2023-08-24 172555

**Review by belagaam — APPROVED** [review]
I tested the PR as per the instructions. Looks good to me. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/ff919e61-3975-4c12-a58b-9cff379252b7

**Comment by n0vay** [comment]
Not able to test. Getting the following Errors:
image

**Review by liaoyufu-leo — DISMISSED** [review]
Hi, this change not works good on my device, the page not show correctly.
image

**Comment by ThapeloMasasa** [comment]
> Hi, this change not works good on my device, the page not show correctly. image

@liaoyufu-leo I do not think that is a issue from this pull request.. also make sure you ran 'npm install'
thank you.

**Comment by ThapeloMasasa** [comment]
> Not able to test. Getting the following Errors: image image

Hi 

> Not able to test. Getting the following Errors: image image

Hi @n0vay The issue you having might have to do with not being on the development branch in the backend or not running 'npm install' after checking into branch. Thank you.

**Review by robertoooc — DISMISSED** [review]
Hi @ThapeloMasasa, I checked out your branch and everything looks fine. The list of sub-permissions were indented as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/4c76b8a1-cfeb-4fca-b31c-8c267d054d02

**Review by EdwinLauM — DISMISSED** [review]
Hi @ThapeloMasasa! Reviewed the new changes and the vertical spacing looks good! Please resolve the branch conflicts and tag me so I can approve!

Screen Shot 2023-09-01 at 8 52 16 PM

**Review by vikrambadhan — DISMISSED** [review]
Hi,
I tested your PR on my system and I am unable to find the "Manage user Permission" Tab. I tried this out with different users, however, I wasn't able to find that tab. The same can be seen in the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/76da9266-9517-4132-80db-b752890a9448

**Comment by ThapeloMasasa** [comment]
> Hi, I tested your PR on my system and I am unable to find the "Manage user Permission" Tab. I tried this out with different users, however, I wasn't able to find that tab. The same can be seen in the video below.
> 
>  2023-09-04.21-12-55.mp4

Have you loggen in as an Owner?? it only shows up for owners.. as descrbided in the directions for the PR testing

**Comment by ThapeloMasasa** [comment]
Hi @EdwinLauM Please review this PR.. I have solved the merge conflicts as requested.. thank you.

**Comment by beblicarl** [comment]
The main subpermissions are indented like you said

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
