### PR TITLE
Induja Add Link validation to Google Doc and Media File

### PR DESCRIPTION
**Pull request by Indujaks**
# Description
Add more specific link validation to Media File and GDoc links
This bug was noticed from my after reviewing pull request 980 on the front end.
Custom Regex validator function specifically for the “Google Doc” & “Media Folder(dropbox)” needs to be created and implemented in the google doc and media folder input field. Currently, the “isValidUrl” is validating that, but only verifies that is starts with https:// etc. We need one that validates more specifically since the fields themselves are specific. This validator should be accessible in a central location such as the “utils” folder as it needs to be implemented both on the userprofile>links>edit & the otherlinks>userManagement>createNewUser modal. Images have been provided below of the target locations and the only validator function currently:

## Main changes explained:
Add specific validation regex pattern for google docs in new file under utils folder
Added specific validation check in editmodal instead of using a generic prototype.
Included an extra step of validation while creating a new user, added a form error incase of invalid links.
Added basic URL validation check for media files.

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. log as admin user
4. Navigate to: Dashboard → Other Links → User Management → Create New User.
5. Fill in user details as per instructions.
6. Verify Admin Document and Media Folder accept valid links.
7.  Access the user profile page for the newly created user.
8. Edit User's Links:
    Navigate to the user's profile page.
9. Verify Google Doc and Media Folder Links:
     Test if only valid links are accepted for Google Doc and Media Folder fields.

## Screenshots or videos of changes:

Before: 
Earlier while creating a user profile/Editing a profile, it was accepting any valid link irrespective of it being a google doc.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/a67c389d-4467-4e00-a8b0-c12cb03fc0bb

After:
While creating a user profile/editing a profile, it accepts only specific valid links for google doc and any valid link for media files.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/fdf1d91a-6ece-4523-b396-c9b75be4e50c

## Note:
Please note that since media folder is not specific to drop box, basic url validation function is added.

### CODE REVIEW

**Review by TheDescendant39 — COMMENTED** [review]
Hi @Indujaks, I reviewed your changes and tried many invalid and valid link combinations. All worked well. Great job. 

However, I have a suggestion:
- If the media folder link is allowed to be any link, can we change the placeholder text from "Dropbox Folder" to maybe "E.g. Dropbox, Google Drive" or anything that would suggest that any link is allowed? 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/3a221c4a-3a8b-4754-9fa0-a50fe65781bd

**Review by luisarevalo21 — APPROVED** [review]
Hello @Indujaks 
I tested your PR and works as intended great job. 

Upon creating a new user' adding dummy links will not allow the user to be created. A toast error occurs saying the links must be valid. 
Once I added valid links the user was created. 
When viewing their profile page and attempting to change the links I also received invalid error if the link wasn't valid. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/2f45af24-d073-4dec-bf4b-3d8ad745be06
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/3401fb1f-8b60-4846-8490-ea468d05b071
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/40a5faa8-4b82-47a1-928b-77c47b0dd683


One suggestion I have is an error message should appear, when the user clicks away from the input field when they've entered an invalid link. Instead of validating when they are done filling the form and attempting to submit a new user. 
The message could appear underneath the input field? 
An example of this would be, when creating a new user' the errors appear below the input fields, I've attached an image below. 

Let me know your thoughts. 

Screenshot 2023-09-07 at 7 49 24 PM
Screenshot 2023-09-07 at 7 49 45 PM

**Review by harshidad — COMMENTED** [review]
@Indujaks ,
I tested PR as the steps mentioned
Below I observed. 
1. When a new user is created with an empty Google doc / Media link, then no required validation message is displayed. 
2. Media Link takes any link. I added https://google.com even though it allows me while creating new users. I didn't receive a valid dropbox error message. 

So can you please confirm if the above scenarios are intended or not?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/8d2d6eac-c802-4b4a-892c-737437a17341


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/970a4221-1bbc-4c2c-911c-03446ea263c7


In other cases it worked fine  and received invalid errors if the link wasn't valid.

**Comment by Indujaks** [comment]
> @Indujaks , I tested PR as the steps mentioned Below I observed. 
> 
> 1. When a new user is created with an empty Google doc / Media link, then no required validation message is displayed.
> 2. Media Link takes any link. I added https://google.com even though it allows me while creating new users. I didn't receive a valid dropbox error message.
> 
> So can you please confirm if the above scenarios are intended or not?
> 
>  PR1280_Invalid_Dropbox_link.1.mp4 
>  PR1280_EmptyField.mp4 
> In other cases it worked fine  and received invalid errors if the link wasn't valid.

these are intended, Admin doc and Media files does allow empty string, and given that media files can be any media and not restricted to drop box, it should accept any valid url.

**Review by harshidad — APPROVED** [review]
@Indujaks 
Thank you for your confirmation on my previous test. so it works as intended.  Great job.

PR#1280

**Review by robertoooc — APPROVED** [review]
Hi @Indujaks, I checked out your branch and it did perform as expected. There is correct validation to restrain users from submitting any other links than to the expected ones. Nice Job. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/3e5315a9-51c6-4418-a223-025e232149ca

**Review by zuhang2000 — CHANGES_REQUESTED** [review]
Hi! I've tested your PR following your instructions. However I do encounter problems when I do the testing. 

Firstly, I test with the google doc link. It's correctly refusing incorrect link with incorrect format. When I test with the Media File link, it's allowing me put any media link which is expected. 

However when I wants to update the google doc link and media file link on profile page. It's not allowing me to do so even if I do copy the real link with correct format. It's always reporting that the link is not valid. Please check the below recording correct me if I'm wrong with the testing. Thank you.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/ac134bfd-555b-4285-b97e-97f3b7fff46d

**Review by Haoj1 — APPROVED** [review]
@Indujaks Good job. The validation works as intended 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/48ef23e0-a516-4ac3-9084-16adfd44dafb

**Comment by Indujaks** [comment]
> Hi! I've tested your PR following your instructions. However I do encounter problems when I do the testing.
> 
> Firstly, I test with the google doc link. It's correctly refusing incorrect link with incorrect format. When I test with the Media File link, it's allowing me put any media link which is expected.
> 
> However when I wants to update the google doc link and media file link on profile page. It's not allowing me to do so even if I do copy the real link with correct format. It's always reporting that the link is not valid. Please check the below recording correct me if I'm wrong with the testing. Thank you.
> 
>  Test1280.mov

Google doc link doesn't not seem to be valid, can you paste the link here

**Review by winghojackyli — APPROVED** [review]
Hi @Indujaks , I've tested the PR and it works as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/14e177a0-6d8e-4062-b9e9-8de584cb5f26

**Comment by Sssky-18** [comment]
Hi, I just tested this new feature, and it worked as described.
Firstly, I typed random string into the Admin Documents and Link to Media File, and two warnings popped up. When I added the ".com", I found the only warning was for Admin Documents. Finally, I had to type in a real doc link to pass the validation. Therefore, I think this feature is efficient. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/a9f49272-986a-45ec-9e04-e55849f135cd

**Review by navneeeth — COMMENTED** [review]
Hi @Indujaks! Tested your PR and it looks good to me. Good implementation! First, I performed the tests with creating an user and working with the two link fields. The URL checks that you have updated work as intended:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/25270bf6-6362-4e0c-ada2-7ef8efcef033

Next, I tested the changes in updating the account links and they work as expected:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/752305c7-6ae1-4d91-8d30-ad0e361dcb7d

Before approving the PR, I wanted to check with you if the following test where I remove the link for either fields and update the changes is intended behaviour:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/688915c9-51ee-46b0-ac2c-07a1af690ea6

**Review by GaryB93 — APPROVED** [review]
Great work in implementing a more specific check on the urls. In testing, an error occurs when trying to input an invalid google doc link when creating or editing a user profile. The media link also displays an error if anything but a valid url is entered.
Screenshot 2023-09-11 at 1 26 58 PM
Screenshot 2023-09-11 at 1 36 46 PM

**Review by DavidC0126 — APPROVED** [review]
Hi @Indujaks I tested your PR and it works as intended. When creating a user, google and media links would be validated before they are created. After creating, those validation still work.

invalid_media
invalid_media_edited

invalid_edited
invalid_google

**Comment by Indujaks** [comment]
> Hi @Indujaks! Tested your PR and it looks good to me. Good implementation! First, I performed the tests with creating an user and working with the two link fields. The URL checks that you have updated work as intended:
> 
>  create.account.mp4 
> Next, I tested the changes in updating the account links and they work as expected:
> 
>  update.account.mp4 
> Before approving the PR, I wanted to check with you if the following test where I remove the link for either fields and update the changes is intended behaviour:
> 
>  remove.links.mp4

Hi Navneeth, yes it is as expected, the links are allowed to be empty!

**Review by navneeeth — APPROVED** [review]
@Indujaks That's great! Everything works as intended. Approving this PR now.

**Review by Chris33871 — CHANGES_REQUESTED** [review]
Hi @Indujaks ,

I first created a user with links - worked fine.
Logged into that user, from there, I could add new links to any website but couldn't change the already created ones - I don't know if that is intended.
From the admin account, I could change the existing links and create new ones - worked fine.
From the admin account, no warning when changing the GDoc link to a YouTube link - Not working.
From the admin account, the warning when changing the DropBox link to a YouTube link - worked fine.
From the admin account, the update changes button didn't work - Not working.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68507104/935946c9-882a-4e47-9c4c-d271324afbc0

**Comment by Indujaks** [comment]
> Hi @Indujaks ,
> 
> I first created a user with links - worked fine. Logged into that user, from there, I could add new links to any website but couldn't change the already created ones - I don't know if that is intended. From the admin account, I could change the existing links and create new ones - worked fine. From the admin account, no warning when changing the GDoc link to a YouTube link - Not working. From the admin account, the warning when changing the DropBox link to a YouTube link - worked fine. From the admin account, the update changes button didn't work - Not working.
> 
>  Recording.2023-09-13.111649.mp4

Hi Chris, the current code changes are not related to warning message printed above, this only refers to validating the link and giving the option to update, please refer to the working video posted above.

**Comment by one-community** [comment]
Thank you all! Moving this to final review!

**Comment by beblicarl** [comment]
This functionality works as intended

[screencast-localhost_3000-2023.09.18-12_47_33.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/9b31a2aa-b125-434c-ae5e-ef82610cf466)

**Pull request merged**
