### PR TITLE
Shihao - Fix Badges' Display Issue

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Fix the issue of badges that cannot be displayed on the weekly summaries report page after it is assigned.

## Main changes explained:
- Ignore the property `showReport` to display badges
- Fixed lint errors

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. Assign one or more badges to a user
5. go to dashboard→ Report → Weekly Summaries Report
6. Check whether the badge is shown and displayed in the **correct tab**.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/c04429f8-0c65-457f-aca0-14d24e0ec5f8

### CODE REVIEW

**Comment by Vishala09** [comment]
Working as expected. Great work!

[Untitled_ Sep 27,2023 11_05 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/0ba5bdc3-5af9-4cd4-bfcd-361f67c43ee3)

**Review by Vishala09 — DISMISSED** [review]

**Comment by astrjc0326** [comment]
Hello, I've thoroughly reviewed the pull request, and it performs flawlessly in accordance with the provided description. Additionally, it serves as a valuable reminder of the conceptual distinction between the 'filter' and 'find' methods.
Great Job!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/aca7d6b9-eeef-44ab-9473-2e5661f7195c

**Comment by olenadanykh** [comment]
Hi all! I reviewed the pull request, checked into the current branch, logged in as an administrator, and recreated all actions. However, for some reason, after I assigned some badges to myself, I am unable to see them under the Weekly Summary Report Page. I'm not sure if it's just me or if there are any account settings that hide badges for specific users. Please correct me if I'm mistaken. Thank you.



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/c96173d7-f8cc-4223-9bbd-1c03099013a2

**Comment by DavidC0126** [comment]
Hi @sxiong5 I cannot see the assigned badges on weekly summary page, either. I clicked load badges few times and also wait for ~10 mins. I also tried to assign badges to different roles but still did not show on the page.
badges
no_show

**Comment by luisarevalo21** [comment]
Hello @sxiong5,

I tested your PR and works as intended. Great work! 

Logging into as an Admin I assigned a few badges to my volunteer account. When viewing the weekly summary, there were no badges, after loading the badges the user' showed their badges. 
One suggestion, I have would be once the "load badges" is clicked a modal/spinner should appear letting the user know the badges are currently loading. As there is no feedback currently for the user. Maybe this could be a separate PR. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/fa686fdb-522f-4742-a2c0-a66f3d51844c

**Comment by AriaYu927** [comment]
Hi @sxiong5 , I also encouter the same issue that @olenadanykh mentioned. I'm not able to see the badges on Weekly Summaries Report page after I assigned badges.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/c9c608a4-093b-4c8f-9180-1e1b185e747c

**Comment by sxiong5** [comment]
Hey @AriaYu927, @DavidC0126, @olenadanykh, thanks for your review! From your videos, I just found you were loading the badges in the "Last Week" tab, and I think that's why you guys cannot see them. If you assign the badges when you are testing, they should appear in the "This Week" tabs.

**Comment by sxiong5** [comment]
> @sxiong5 I reviewed your changes and I just have a question is this functionality supposed to work for the admins or the owner roles? In your directions you say login as admin but in your video walkthrough you are using an owner account.
> 
> ## Issue
> I am able to see and make new changes in the badges in This Week summaries as the Owner role, but not as admin.
> 
> ## Videos
>  Badges.not.displayed.for.weekly.summary.for.ADMIN.webm 
> OWNER Role
> 
>  PR.1346.Fix.Badges.not.showing.on.weekly.summaries.OWNER.webm 
> ## Notes
> If this functionality is for the Owner role then it works great and as intended, but if it is for the Admin role then it does not work.

Hey @BaileyM96, thanks for your review. And sorry I didn't clarify, but the admin and the owner should have the same permission. And I just tested the admin account on my end, it works for me. So I checked your testing video for admin, and I found that it seems like you failed to assign the badges to the user because the total count of the badges didn't change. That's why you cannot see the badges on the report page. Can you please check it again and let me know if you still encounter the same issue?

**Review by eduhorta — APPROVED** [review]
Hey @sxiong5!
Just tested on my end and it is working as expected!
Great job! 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/512c9464-8eaa-4d24-a0f0-74b2d3578a10



image

**Comment by olenadanykh** [comment]
> Hey @AriaYu927, @DavidC0126, @olenadanykh, thanks for your review! From your videos, I just found you were loading the badges in the "Last Week" tab, and I think that's why you guys cannot see them. If you assign the badges when you are testing, they should appear in the "This Week" tabs.

Hey @sxiong5, great catch! Thanks for pointing that out. I retested it using the 'This Week' tab, and everything seems to be working as expected. The only issue I noticed is the loading time; it took around 30 seconds or even longer for the badges to be displayed on the page.

Nonetheless, great job!

**Comment by emunkh404** [comment]
I thoroughly tested your PR, and it works as intended, demonstrating excellent work! As an admin, I assigned badges to my volunteer account and noticed that initially, the weekly summary didn't display badges until they were loaded. I recommend considering a modal or spinner to provide user feedback when the "load badges" button is clicked since the current lack of feedback can be improved, perhaps in a separate PR. I also checked into the current branch, logged in as an admin, and replicated all actions, but unfortunately, I couldn't see the badges I assigned to myself on the Weekly Summary Report Page. I'm unsure if this is specific to my account or if there are account settings affecting badge visibility. Please clarify if needed. Nonetheless, your PR functions flawlessly according to the provided description and serves as a valuable reminder of the distinction between the 'filter' and 'find' methods. Great job!

**Review by Jiyuanxia — APPROVED** [review]
Hi @sxiong5 , I have reviewed your pull request and tested it. It works as you intended. Good job!

Screenshot 2023-09-28 184811

Screenshot 2023-09-28 184820

Screenshot 2023-09-28 185054

**Comment by AnishPandita** [comment]
Hey tested the PR and it seems to work well. The badges can be added and are shown without any errors.
Screenshot 2023-09-28 at 4 29 36 PM
Screenshot 2023-09-28 at 4 37 18 PM

**Review by tsunami776 — APPROVED** [review]
Hi @sxiong5 I tested with an admin account, and badges were displayed correctly in 'this week' tab after they were assigned to a user. I also tested lint for the files, and those files will auto-correct lint-related issues upon saving the files. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/2de1e689-8c9e-4dca-8f03-0f5807ca577e

**Review by Bhagyashree444 — APPROVED** [review]
Works as expected. Great work.

Screenshot (132)

Screenshot (133)

**Review by BaileyM96 — DISMISSED** [review]
@sxiong5 I went ahead and Re-tested the admin role for assigning badges to a user and this time it worked. Here is the video of my test

## Video 
[PR #1346 Badges Display Re-Test for ADMIN.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/44613821-1f60-49e3-8bb9-953f6d0909e4)

**Comment by Lin1404** [comment]
Hi @sxiong5 , I have tested your PR and it works intended. Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/e0693832-29a5-443a-9ce2-8a7138f0c806

**Review by Sssky-18 — APPROVED** [review]
HI @sxiong5, I tested this PR and it worked as expected. I logged in using my admin account and assigned 3 random badges to my test account, then the badges were displayed correctly in the weekly summary pages. Therefore, I think your fix should be successful and I approved it. 

PR#1346_1

PR#1346_2

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I tested this and it works as intended.
Screenshot 2023-09-29 at 7 49 25 PM

**Review by EdwinLauM — DISMISSED** [review]
Hey @sxiong5, works as expected! Good job! 

Screen Shot 2023-09-29 at 10 23 23 PM

Screen Shot 2023-09-29 at 9 47 38 PM

**Review by JeffLi117 — APPROVED** [review]
Works as intended! On an Admin account, I added two badges to my test account (Jefftest) and was able to see those badges load within the Weekly Summaries Reports page when I 1) switched to "This Week" and then 2) clicked "Load badges". 

image

One thing I noted (that I'm not sure others may have experienced) is a prolonged wait time in loading the badges - I usually don't have this issue with anything on the HGN app, but maybe it's just my computer. Regardless, great job!

**Review by Lin1404 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all. I will merge this as soon as this fix request is integrated: 
image

**Comment by RheaWu1212** [comment]
Hi @sxiong5 I tested your PR, assigned new badges to my test user --> new badges showed up in report right away --> go to week summary --> look for the same user, choose this week, show badges --> only showed for one badge for another user, my test user showed nothing, and the same after 10 mins.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/f8416678-8dfc-4a00-82a0-7a3921b6da27

**Review by TuanDinh140194 — APPROVED** [review]
It's really nice. The badge display as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/7aae8002-3f1b-4333-9244-3e643d1d2d55

**Pull request merged**
