### PR TITLE
Wanting_UnitTest_AddWBS.jsx

### PR DESCRIPTION
**Pull request by wantingxu7**
# Description
Unit test for `AddWBS.jsx`

## Main changes explained:
- Created file `AddWBS.test.jsx`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run `npm test AddWBS.test.js`
4. verify that all tests pass with no error

## Screenshots or videos of changes:
AddWBS_unittest

### CODE REVIEW

**Comment by DragonSlayer2401** [comment]
I tested your PR everything seems to be working as intended good job. Please watch the overview video below:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/f4defa34-839f-4164-84d9-12aeb4c6e967

**Review by ZichanYang324 — APPROVED** [review]
Hi @wantingxu7 , I just ran the test and all the test cases passed, well done!
Screenshot 2023-12-09 at 15 51 54

**Review by pika-chu11 — APPROVED** [review]
Hi @wantingxu7 , I have the tested and it passed! Great Work!
PR 1672

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-12-10 at 12 57 17 AM

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Comment by Lin1404** [comment]
All test cases passed successfully!
PR1672_1

**Review by Lin1404 — APPROVED** [review]

**Review by cvtqx — APPROVED** [review]
All tests pass, great job!

Screen Shot 2023-12-15 at 12 25 20 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
