### PR TITLE
Zichan Change the button appearance align with the report->person page

### PR DESCRIPTION
**Pull request by ZichanYang324**
# Description
Screenshot 2023-12-23 at 23 03 33

## Related PRS (if any):
N/A

## Main changes explained:
- Change the button background color to linear gradient for the project page
- Fix the button height and make sure these two buttons are in the same line

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Log as the admin user
5. go to dashboard>Other Links>Teams and Other Links>Projects, check whether these two buttons are in the same row or not
6. and also go to dashboard > Reports>Reports>People><choose person> pages, just to compare if the buttons on this page are similar to the buttons on the dashboard>Other Links>Teams and Other Links>Projects page.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86720318/f525cd94-675e-4954-a186-ec7de45c88d9

## Note:
N/A

### CODE REVIEW

**Review by Alforoan — CHANGES_REQUESTED** [review]
As you can see, the buttons are slightly different in size on the team's page.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/0b649ef6-8c89-4888-846d-0619a081b644

**Comment by ZichanYang324** [comment]
Hi @Alforoan , I have updated the teams page as well, thank you for the reminder, please check

**Review by ilyaflaks — DISMISSED** [review]
I tested this PR and found that everything is working as described. 
I double checked that I see the same misalignment on the development branch:
PR1746-dev-reproduce-01
Current branch under "Teams"
PR1746-zichan-teams-02
Current branch under "Projects" 
PR1746-zichan-projects-03
The buttons did not shrink or misalign with a smaller screen size:
PR1746-mobile
Great job! Good to see the number of div's reduced when possible.

**Review by Alforoan — CHANGES_REQUESTED** [review]
They are still not aligned properly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/ab2f695a-a3d4-420b-8687-615927e44b30

**Comment by ZichanYang324** [comment]
> They are still not aligned properly.
> 
>  pr.review.1746.mp4

Hi @Alforoan, everything seems fine on my local page, have you tried to use git fetch and git pull for the latest changes?

**Review by Alforoan — DISMISSED** [review]
@ZichanYang324 Sorry, I must not have done git pull. Approving because everything is perfect now.  Nice!

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
