### PR TITLE
Jiangwei - create unit tests for the ReportTableSearchPanel component

### PR DESCRIPTION
**Pull request by Jiangwei-shi**
# Description
Create a unit test for the ReportTableSearchPanel component to confirm whether it working as intended.

## Main changes explained:
- Create file ReportTableSearchPanel.test.js to do the unit tests

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. open file src → tests → ReportTableSearchPanel.test.js
4. run `npm run test src/__tests__/ReportTableSearchPanel.test.js`

## Screenshots or videos of changes:
屏幕截图 2023-11-04 195206

## Note:
If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by kavya151 — APPROVED** [review]
Hi @Jiangwei-shi , I have Reviewed the PR and all tests have passed. Good work!
Screenshot 2023-11-04 at 5 12 40 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-11-04 at 10 50 35 PM

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR and everything works as expected. All tests passed!
Screenshot 2023-11-04 at 11 02 28 PM

**Review by pika-chu11 — APPROVED** [review]
Hi, I Tested! And all passed on my end. Good work!
 
Screenshot 2023-11-04 202929-FE#1489

**Review by savio-henrique — APPROVED** [review]
Hi @Jiangwei-shi , I've run the test cases and they passed as expected! Great work! :+1: 

# Screenshots

terminal

**Comment by palakgosalia** [comment]
Hey, I have tested your PR and everything works as intended. Thank you
image

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
