### PR TITLE
XiaoW_Refactor of time entry controller and fix edit history issue

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
This PR along with the backend changes aims to refactor the time entry controller for post, edit, and delete time entries. They also fix the edit time entry history not added to history issue. 

## Related PRS (if any):
This frontend PR is related to the [#881](https://github.com/OneCommunityGlobal/HGNRest/pull/881#issue-2234712272) backend PR.
…

## Main changes explained:
- integrated all the changes to `userprofile` caused by time entry operation into the backend (such as `updateHoursByCategory` and `editHoursByCategory` in TimeEntryForm component)
- refactor the logic
- remove unused files/logic

## How to test:
1. check into current branch and backend PR #[881](https://github.com/OneCommunityGlobal/HGNRest/pull/881#issue-2234712272)
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user -> test any operations on time entry (create, edit, delete, change others'...)
5. log as vol user -> test any operation on time entry.

### CODE REVIEW

**Comment by alla0810** [comment]
Looks good except for some console errors and violations.

looks good

**Review by SushmithaPrathap — CHANGES_REQUESTED** [review]
Hey, I've tested your PR that refactors the time entry controller for post, edit, and delete actions following the steps provided. Here is what I found:

- Owner account operations (add, edit, delete time entries) are functioning as expected.
- Encountered an issue when attempting to add a time entry for a volunteer account; this operation was unsuccessful.

Attached are screen recordings that demonstrate both scenarios for further review.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/ee5ec84c-39a2-45f1-bbd4-01950c645ac9


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/48655a06-bd0b-497d-bf26-db54df9ed205

**Review by jennZhang93 — CHANGES_REQUESTED** [review]
For admin account, add, edit, and delete time entry worked. Although for deleting time entry there's an error pop up modal at upper right corner, it still successfully deleted it.

For volunteer account, I cannot add time entry because of the Date field error. 
 
**Admin - Adding time entry and editing time entry worked:** 
Screenshot 2024-04-10 at 9 18 00 PM  Screenshot 2024-04-10 at 9 18 15 PM

**Admin - Deleting time entry worked but had an error pop up at upper right corner:**
Screenshot 2024-04-10 at 9 18 22 PM

**Volunteer - cannot add time entry**
Screenshot 2024-04-10 at 9 21 14 PM

**Review by Jaiwin-4998 — CHANGES_REQUESTED** [review]
Hey! I just tested your PR.
In owner account the everything is working fine as expected(edit, update, delete)
In team account it is not working as expected, as it is not allowing to log time and throwing the error of the date. I have attached the video and screenshot of it.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62836815/093a18c8-3d54-4746-aad9-6253fc4bc734
Screenshot 2024-04-11 at 2 54 22 PM

**Comment by hiralsonip** [comment]
Hi...I have tested this PR. It is working fine for the admin. For the volunteer account, it is giving the error for a date. Please refer to the attached video for admin and the image for volunteer. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66827672/2f79f9ba-e5f3-4f6e-ad31-801ef4b5a2a9

**Review by SRamen1999 — CHANGES_REQUESTED** [review]
When testing this PR I encountered some errors for both the admin and volunteer accounts. For admin account you can add, edit, and delete time entry worked. However for deleting time entry there's an error pop up modal at upper right corner, it still successfully deleted it. For the volunteer account, I cannot add time entry because of a Date field error.
 
Admin 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/74656687-29fc-4ab5-896c-61a309a009d8


volunteer

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/76b765ad-93f6-4779-a570-4ad7fc2b468e

**Review by ljrirene — CHANGES_REQUESTED** [review]
Hi Xiaow, I logged in as an admin user and a volunteer user. Both of them have a little bit problem needed to be fixed.

Admin:
1. I can't directly edit the hour here. I can only use the arrow here. Does this need to be fixed?
image
2. There is an error message occurs here:
image
3. After I set a time for AL User. I can't track the latest record:
image

Volunteer user:
I'm not allowed to add the time entry here even I refreshed the page and clean the cache.
image

**Review by metaphor987 — CHANGES_REQUESTED** [review]
Hi XiaoW,
I've tested the time entry functionalities using both the admin and volunteer accounts. 
- For the admin account, I was able to successfully add, edit, and delete both tangible and intangible time entries. The only issue is that an error message appears after deleting a time entry (as shown in the screen recording below), even though the deletion functionality is successful.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/78d6fa65-98eb-4947-a879-477e703f9b36


- For the volunteer account, there's an issue with the date saying "invalid date", which prevents the addition of both tangible and intangible time entries (as shown in the screenshots below).
Screenshot 2024-04-13 at 1 38 37 AM
Screenshot 2024-04-13 at 1 39 41 AM

**Review by aaryaneil — CHANGES_REQUESTED** [review]
Tested the PR and noticed these things:
1. The create and edit functionality works well when logged in from the admin account.
2. The delete works as expected but throws an error in the admin account.
3. In the volunteer role the create functionality doesn't work as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/13f25a85-e8b9-45f4-89d1-158dfb51287b

Screenshot 2024-04-13 at 9 24 07 AM

**Review by Tiantian-C — COMMENTED** [review]
Hi, I found that when I logged in as a  volunteer, I can't add the time entry.
Screenshot 2024-04-13 at 3 50 15 PM

**Review by hiralsonip — CHANGES_REQUESTED** [review]
Hi...I have tested this PR. It is working fine for the admin. For the volunteer account, it is giving the error for a date. Please refer to the attached image for a volunteer. 

PR2131

**Review by jennZhang93 — CHANGES_REQUESTED** [review]
good work! I tested with owner account for create, modify, and delete time entry. The only thing that I noticed was that when deleting time entry, it can successfully delete it, but it shows an error pop up message at the right top corner (screenshot is below).

also tested with volunteer account for the same time entry creation, modification and deletion. Same error happened for deletion as well. All the other functionalities are working good.

errScreenshot 2024-04-16 at 9 35 36 PM

**Comment by wang9hu** [comment]
> 3. After I set a time for AL User. I can't track the latest record: image

Hi @ljrirene, thank you for your reviews! I have made some changes to fix these issues, but I am not sure about this one, since my PRs shouldn't be working on the time off section. Could you elaborate on what is your concerns here?

**Comment by ptrpengdev** [comment]
Hi Xiao,

I've tested your PR, and two issues caught my attention. 
1. when deleting a time entry, an error message is displayed, but the entry is successfully deleted after refreshing the page. 
2. the backend throws an error when I change the time entry type. 

Review also left in the backend PR.

Video: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/b6ac4c2c-7c2c-44b2-939c-e682112b671c

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
