### PR TITLE
Aditya - Fix Error Labels on Create New User Form

### PR DESCRIPTION
**Pull request by adityasure9**
# Description
This pull request resolves the issue with error labels being preloaded on the "Create New User" form. Now, error labels will only be displayed when a user makes an error or leaves a required field empty. Additionally, asterisks (*) have been added next to required fields to make it clear which fields are mandatory.
image

Fixes # (Priority Low Pranay: Fix the Error Labels on Create New User Form)

## Main changes explained:
Updated validation logic to ensure error labels only appear after the user submits invalid input or misses a required field.
Added asterisks (*) next to required fields to indicate that they are mandatory.
Improved user experience by ensuring that error labels don't show until after user interaction.

## How to test:
1. Copy the Code: Apologies, but I’m currently unable to push changes directly to the main repository due to permission issues. Please copy the code from the files changed in this pull request.
2. Run npm install and npm run start:local to run this PR locally.
3. Clear site data/cache to ensure no prior data conflicts.
4. Log in as an admin user.
5. Go to User Management → Create New User.
6. Try submitting the form without filling in required fields. Verify that error labels appear only after the form is submitted with missing information.
7. Confirm that all required fields have an asterisk (*) next to them.
8. Verify the functionality works in dark mode.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/0d6b00f2-4810-4e37-9540-d47c2ca970c0

## Note:
Apologies for the inconvenience. I’m currently unable to push changes directly to the main repository due to permission issues. I’ve contacted Jae Sabol regarding this, and once I receive the necessary permissions to create a new branch, I will update you. In the meantime, please copy the code from the files changed in this pull request to test the updates. If you need any assistance or have questions, feel free to reach out. I’m here to help!

### CODE REVIEW

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

image

Thank You

**Review by panchalvatneu — APPROVED** [review]
Fixed as required, good work! 
image

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are not working as expected. The error labels are visible on the Create New User dialog box opening, without even needing to submit the form with missing information. Below is the screenshot for reference:
Capture2653

**Review by sam19981 — APPROVED** [review]
Tested the changes Error are not showing up before hand and only pop up when user removes the required content and not fills it up.

Screenshot 2024-09-07 at 7 42 24 PM

https://github.com/user-attachments/assets/93c8be1e-7998-4f5e-8cfb-0c70f79b7d99

**Comment by adityasure9** [comment]
> Verified the PR and the changes are not working as expected. The error labels are visible on the Create New User dialog box opening, without even needing to submit the form with missing information. Below is the screenshot for reference: Capture2653



> Verified the PR and the changes are not working as expected. The error labels are visible on the Create New User dialog box opening, without even needing to submit the form with missing information. Below is the screenshot for reference: Capture2653

Thanks for the feedback, @ishangoel17. Could you share a screenshot or video of the issue? Others have confirmed it works as expected, but I'd like to ensure it's resolved for all.

Apologies for the inconvenience. I'm currently unable to push changes due to permission issues and have contacted Jae Sabol. Once I have access, I'll update. Meanwhile, please test with the code from the PR, and feel free to reach out if needed!

**Review by vishnupriyaatheti — CHANGES_REQUESTED** [review]
@adityasure9 I have reviewed your PR and I found one issue in displaying error message. 
Weekly Committed Hours is not displaying error message when it is empty, Please find the screenshot.
FE PR 2653

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (196)

**Review by mohangadde1 — CHANGES_REQUESTED** [review]
image
For weekly committed Hours, the error message requires clearing twice before it becomes visible.

**Review by Abhinav-Ankur786 — APPROVED** [review]
Changes are reflecting as per PR

image

**Review by Gauravmg6 — APPROVED** [review]
It is working as expected

Screenshot 2024-09-16 134604

**Review by Watchdog00 — COMMENTED** [review]
I have completed the testing and got the expected results. Good job!

**Comment by navya9989** [comment]
2653 # PR
I have tested this PR , I appreciate your work , but the Error message appears before submitting the form this is a bit different as expected.

**Pull request closed without merging**
