### PR TITLE
Wanting new make 5 letter codes editable only by admin&owner

### PR DESCRIPTION
**Pull request by wantingxu7**
# Description
截屏2023-11-03 上午11 16 18

## Related PRS (if any):
BE # **[648](https://github.com/OneCommunityGlobal/HGNRest/pull/648)**

## Main changes explained:
- Update WeeklySummariesReport.jsx file for Owner/Admin/whoever is given "edit team code" permission to edit 5-letter team code in 'Weekly Summaries Report page'
- Update UserProfile.jsx file for Owner/Admin/whoever is given "edit team code" permission to edit 5-letter team code in profile's teams tab
- Updated other related files

## How to test:
1. check into current branch and BE # **[648](https://github.com/OneCommunityGlobal/HGNRest/pull/648)**
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as owner/admin user
        a. go to Reports -> Weekly Summaries Report
        b. verify that the 5-letter team code is editable
        c. go to User Profile -> Teams tab
        d. verify that the 5-letter team code is editable
4. edit a team code, refresh the page, and check the edited team code is saved
5. log as any role EXCEPT admin/owner(like volunteer, manager, mentor, etc.)
        a. go to Reports -> Weekly Summaries Report
        b. verify that the 5-letter team code is NOT editable
        c. go to User Profile -> Teams tab
        d. verify that the 5-letter team code is NOT editable
6. log as owner, go to "Other Links" -> Permissions Management -> Manage User Permissions -> search for the user who doesn't have permission to edit team code -> select "See Only Weekly Summary Reports Tab"(at very front) and "Edit Team 4-Digit Codes"(at the end) and submit
7. log as the user in step 6, go to Reports -> Weekly Summaries Report and User Profile -> Teams tab, verify that the 5-letter team code is editable

## Screenshots or videos of changes:
**editable team code example:**
截屏2023-10-20 下午1 11 24

截屏2023-10-20 下午1 45 17

**uneditable team code example:**
截屏2023-10-20 下午1 17 32

截屏2023-10-20 下午1 21 32

### CODE REVIEW

**Comment by mounica-dingari-by** [comment]
Hi @wantingxu7 , I've tested your PR and it works perfectly. When logged in as Owner, I was able to edit the code and It stays after refresh. I've logged in as volunteer and tested it, the reports tab is not visible and in teams of profile page, the code is not visible. Included some screenshots below. Good work!!


Screenshot from 2023-11-03 17-26-47
Screenshot from 2023-11-03 17-27-56
Screenshot from 2023-11-03 17-29-22
Screenshot from 2023-11-03 17-29-32
Screenshot from 2023-11-03 17-31-22

**Comment by AriaYu927** [comment]
Hi @wantingxu7 , I've tested this PR and find that all of the functionalities work great except one. When I logged as a core team user with "Edit Team 4-Digit Codes" permission and tried to change the team code on profile page, I cannot see the "save changes" button. Please refer to the screenshot below:
Screenshot 2023-11-04 at 10 45 42

Other functions work excellent, great job!

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hello @wantingxu7, I've completed a review of the this PR and wanted to report that everything functions correctly, with the exception of a bug I discovered. When using an owner account, attempting to edit the team code through the user profile and clicking save results in an error. I've captured this issue in my first recording for your review. Aside from that, all works good. Excellent work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/e008fc70-c5b3-4836-99f3-51dafcfca92c


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/7b7d50b3-af0e-4290-bf32-dee52773d7ae


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/7d88603f-a039-4ad4-887e-3dc0fe3c79d4

**Review by shubhankarval — DISMISSED** [review]
Hey @wantingxu7, the PR works as intended and can be merged. Great job!
Verified that Admin/owner can edit team codes:
Screenshot 2023-11-04 102258
Screenshot 2023-11-04 102516
<br/>

Verified that Admin/owner can change Team code form User Profile.  
Screenshot 2023-11-04 103011
\
Verified that volunteer cannot change team code
Screenshot 2023-11-04 103216

Verified that users who cannot edit team codes, can do it with Owner permission.
Screenshot 2023-11-04 104013
Screenshot 2023-11-04 104033

**Review by sahilpatel18 — DISMISSED** [review]
I was successfully able to accomplish tasks 1 through 5. I first logged in as an admin and was able to update a team code, create a team code, and confirm that the created team code was saved. I also logged in as a manager and verified that i could NOT update existing team codes OR create them. great work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/08c296ff-34c8-41e9-a15f-732990214843

updatedTeamCode

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/1f1f5ca5-b711-4f07-a4f3-df134d825402

**Review by jerryren527 — APPROVED** [review]
Hi @wantingxu7 ,

Great job, your code changes worked as intended!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/bdc84bdf-a921-4098-a834-340b788d74bc



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/9f82380e-1d5c-43fe-8b2c-c5d1d1dfa1e5

**Review by jerryren527 — DISMISSED** [review]
Hi @wantingxu7 ,

I left a more detailed review in the [frontend PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485#pullrequestreview-1713901857). Great job!

**Comment by palakgosalia** [comment]
Hey, I have reviewed and tested your PR. It works as intended. Thank you. Great work.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/e2269296-8a5c-438c-9b67-d8605828f5e8

**Review by Shuhua-L — APPROVED** [review]
Hi @wantingxu7, I've tested all these actions and am happy to report that everything went smoothly. Nicely done!

- as an admin, the team code was editable in both the Weekly Summaries Report and User Profile sections
- as a volunteer, the team code was not editable in both sections initially, but after being granted permissions by an owner, the team code became editable
- as an owner, you can toggle the permission of editing 5-letter team code for any user


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/eafbdd1e-e68f-4a05-bf66-4b5115d17078

**Comment by kavya151** [comment]
Hi @wantingxu7 I have run this PR locally and everything is working as intended when I have logged in as an admin, I was able to edit the team code. When I logged in as a volunteer I didn't find any reports tab.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/de2de8cc-c6e8-4c6d-9da4-ecf52d3316b2



Screenshot 2023-11-11 at 5 55 52 PM

**Comment by one-community** [comment]
> When I logged in as a volunteer I didn't find any reports tab.

You need to give your volunteer the permission to see the Reports page to be able to test this: 
Permissions Management > Manage User Permissions > See Only Weekly Summary Reports Tab

Please do that and then retest it

**Comment by ptrpengdev** [comment]
Hi @wantingxu7, I think it would be great if you could pull the latest code from the development branch using "`git pull origin development`" to ensure that you are up to date with the latest changes.

**Review by lichanghaogit — COMMENTED** [review]
Please see the updated review.

**Comment by ptrpengdev** [comment]
Env Setup:
frontend commit [60815f3](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/commit/60815f30cbedbeb98780469af307085ec48b0c39) and backend commit [c819cc8](https://github.com/OneCommunityGlobal/HGNRest/commit/c819cc8c81d0e6543b0fec006def60161121b5f8).

Tested both Admin and Owner role:
1. Update team code in weekly summaries component (**Success**)
2. Update team code in user profile component (**Success**)

Tested tester role:
1. Should **not** able to update team code in user profile component (**Success**)
2. Should **not** able to update team code in weekly summaries component (**Fail**)
  -  No Report Tab in the navigation bar. Video Attached:
  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/aedc9e71-2873-466f-95f1-6f6b485042b3

**Review by ptrpengdev — CHANGES_REQUESTED** [review]
Reference: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1485#issuecomment-1817354150

**Review by Bali2Mohit — COMMENTED** [review]
Hi @wantingxu7 ,
I reviewed your PR. I can see the user profile giving permission error and in the UI, was able to see the error alert, for both weekly summaries and profile page. Also, on profile page after the error alert, it shows a success message as well but the team name is not getting updated.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94716419/e2dd63fd-c8ba-448f-8ff4-3bf4319202d9

**Review by Hemsharavanan — DISMISSED** [review]
- The team code editing functionalities works fine.
- Verified that Admin can modify team codes both via User Profiles and in Reports section
- As intended, the system restricts volunteers from altering team codes and accessing the reports section when logged in as a volunteer.

Check the below screenshots.

Verifying from admin's end
PR #1485 ss1
PR #1485 ss2
PR #1485 ss3


Verifying from volunteer's end
PT #1485 ss4
PT #1485 ss5

**Review by Alforoan — CHANGES_REQUESTED** [review]
It keeps giving me a 500 error as an owner. Please look into the possible fix. Thanks.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/30e6df77-4003-4b1b-a84b-0139be73f2aa

**Comment by DragonSlayer2401** [comment]
I tested this on an Owner, Admin, and Volunteer account. Both the owner and admin had the same problem of getting a status 500 on the weekly summaries page after editing the code. The volunteer account was not able to edit the profile team code as intended. All of the accounts with the permission were able to edit the profile team code successfully. Please see the overview video below for more details:


Uploading 2023-12-02 11-21-28.mov…

**Comment by DragonSlayer2401** [comment]
I tested this on an Owner, Admin, and Volunteer account. The owner and admin had the same problem getting a status 500 on the weekly summaries page after editing the code. The volunteer account could not edit the profile team code as intended. All of the accounts with the permission were able to edit the profile team code successfully. Please see the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/09fc03ae-f8c3-4c5a-802d-07b8b01f8e03

**Review by sucheta90 — COMMENTED** [review]
Hi @wantingxu7 , I have tested this PR as Owner and as Volunteer.  
**OWNER** - The Team codes can be modified within the weekly summary tab, but encountering a 500 error prevents the changes from being saved. However, within the User Profile > Team section, the code can be edited and successfully saved. Even after refreshing the page, the code remains visible in the Team tab. Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/c294bc12-7a58-4b09-a4fa-75237fc49340

**Volunteer** - The Reports tab remains hidden unless access permissions are granted. Upon granting permission, the observations made within the tab remain consistent with those of the Owner.

**Review by lichanghaogit — DISMISSED** [review]
Hi @sahilpatel18 
I tested this PR on local env and all functions work perfect.
Admin users are able to Modify and save change of the team code
Screenshot 2023-11-17 at 2 08 53 PM
Team visibility button works fine.
Screenshot 2023-11-17 at 2 11 31 PM

Volunteer users are able to see the team code but not able to edit it.
Screenshot 2023-12-11 at 11 18 05 AM
Screenshot 2023-12-11 at 10 50 36 AM

Owner users could modify the code in both report and profile sections.
Screenshot 2023-12-11 at 10 34 17 AM
Screenshot 2023-12-11 at 10 49 52 AM

**Review by sucheta90 — COMMENTED** [review]
Hello @wantingxu7 , I conducted testing on this PR while assuming roles as Owner, Admin, and Volunteer. While logged in as Admin or Owner, I successfully edited the 5-digit team code in both Reports > Weekly Reports and User Profile > Team sections, and the changes persisted upon page refresh. However, when logged in as a Volunteer, the Reports tab was not available as expected, and the User Profile > Team section did not allow code editing, aligning with the application's expected behavior. Notably, the application's Badges in the top right corner of the dashboard were not visible across all roles. Overall, the functionality aligned as anticipated for the designated roles. Great job on the implementation.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/d832d792-29d9-4246-a818-39d325380833



The Screen Shot Shows the badges missing!
missing_badges_PR1485

**Review by sucheta90 — DISMISSED** [review]
@wantingxu7 I successfully assigned permissions to the Volunteer account, granting access to the Reports tab this time. Additionally, I confirmed that the Team code was editable in both the Weekly Summary and

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/cfbacd74-d040-4c69-837b-9fedade5711c

 User Profile sections. I'm proceeding with approval for this.

**Comment by ptrpengdev** [comment]
Hi @wantingxu7 , I tested all the features, and the code worked as expected. It would be great to add a toast message after updating the team code on the report page. Please remember to pull the latest change from the development branch.

- verified owner role can edit team code in weekly report and user profile.




- verified volunteer role not able to see weekly report and not able to edit user profile team code.



- verified that manage user permission is functional. The volunteer can see the weekly report and edit team code in both reports and user profiles after permission is assigned.

**Comment by AriaYu927** [comment]
Hi @wantingxu7, I've tested this PR and it works as expected.

Owner and Admin class can edit team code on weekly summary report page and profile page:
Screenshot 2023-12-12 at 13 09 19
Screenshot 2023-12-12 at 13 10 35

Users other than Owner&Admin and without permission cannot edit team code:
Screenshot 2023-12-12 at 13 18 22

**Review by AriaYu927 — DISMISSED** [review]

**Review by Shuhua-L — DISMISSED** [review]
I've tested these steps again with the new backend branch. Everything works as intended, and no bugs have been found. Well done! 

Be sure to take a look at the failing CI build, though.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/e589503d-f2f3-4011-b655-78f16e1e8491

**Comment by wantingxu7** [comment]
> I've tested these steps again with the new backend branch. Everything works as intended, and no bugs have been found. Well done!
> 
> Be sure to take a look at the failing CI build, though.
> 
>  PR1485+648.mp4

**Review by keyunhuangg — APPROVED** [review]
Owner: can be edit and save under profile and weekly summaries

Screenshot 2023-12-23 at 11 01 25 AM
Screenshot 2023-12-23 at 11 01 37 AM

Manager: cannot edit in weekly summaries and profile
Screenshot 2023-12-23 at 11 03 48 AM
Screenshot 2023-12-23 at 11 04 03 AM

**Comment by one-community** [comment]
Thank you all, moving to final review and DMd people for their final reviews.

**Review by ptrpengdev — APPROVED** [review]
lgtm. Re-tested. All features worked as expected. Please do pull the latest from the development branch before merging. Great job!

**Review by Alforoan — APPROVED** [review]
I re-reviewed and everything works as intended. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/97bc4947-a1f4-45d1-ba53-8e0eca4bf09d

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
