### PR TITLE
Shiqing restore reports page formatting

### PR DESCRIPTION
**Pull request by yvonnep165**
# Description
Screenshot 2024-03-28 at 3 18 38 PM

## Related PRS (if any):
This frontend PR is related to the latest backend.

## Main changes explained:
Make the result table of the search function to show up on the right when the screen is wide enough. If the screen gets narrow down, the result table shows up below the search function. Before the user makes selection, the search function is always in the middle of the page horizontally. 

## How to test:
1. check into current branch
2. do npm run start:local to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to Reports→ Reports → Projects/People/Teams → Type any letter in the search bar (optional) → adjust the window to be narrower or wider
6. verify the page formatting to see whether it fits horizontally or not: When the window is wide enough, the result table should be on the right. When you make the window narrower, the result table is below the search function

## Screenshots or videos of changes:
Before selecting any tab:
Screenshot 2024-03-28 at 9 47 18 PM

After selecting a tab:
Screenshot 2024-03-28 at 9 47 54 PM

If narrow the window:
Screenshot 2024-03-28 at 9 48 28 PM

## Note:
n/a

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
The page format fits well. The result table is on the right on wider screen and it is below the search field when we make the window narrower.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/d43440e4-6486-478f-ab3f-06e8a5bc7b74

**Review by ImzIssa — APPROVED** [review]
Hey, tested your PR and the page is responsive and works as expected. Nice work!

PR 2096
PR 2096 (2)

**Review by abdel-lall — APPROVED** [review]
Works as described. Good job!
Screenshot 2024-03-29 191459

#### On a small Screen.
Screenshot 2024-03-29 191532

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and it work perfectly. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/4d6a7034-172d-4d36-9bee-6ff2e62ff05d

**Review by hbodgal — APPROVED** [review]
The UI is responsive. And it should work fine when user clicks on any of the Category.
Here is the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/6d8aa7fd-0a4d-403d-9f51-45f27d50a696

**Review by aaryaneil — APPROVED** [review]
Tested the changes and they work as described.

Screenshot 2024-03-30 at 5 39 15 PM
Screenshot 2024-03-30 at 5 39 32 PM
Screenshot 2024-03-30 at 5 39 51 PM
Screenshot 2024-03-30 at 5 39 45 PM

**Review by lacnoskillz — APPROVED** [review]
Hello @yvonnep165 
I have pulled and tested your changes and they work how you described!

The page now has the search results of on the right on larger view ports

image

but still maintains mobile responsiveness by shifting it below on smaller view ports

image


Nice job and happy coding!

**Comment by Gayathr-2012** [comment]
Hi,
The UI is responsive. And it should work fine when user clicks on any of the Category. It works as expected.

image

image

image

image

**Review by SushmithaPrathap — CHANGES_REQUESTED** [review]
Hey,

I've reviewed the PR and everything works as expected. I tested it on both wide and narrow screens. 

One suggestion I have is to reconsider the design of the search function section on narrow screens. Right now, users might not realize results have appeared without scrolling down. Maybe we could find a way to make it more obvious that the search has produced results?

Screenshots and Screen Recording:

Screenshot 2024-04-03 at 10 58 51 PM
Screenshot 2024-04-03 at 10 56 58 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/6c6ba77a-23de-46c5-876b-df435af19b7d

**Review by SushmithaPrathap — APPROVED** [review]

**Comment by MQChen211** [comment]
Hi, I tested your PR and it works as expected.

截屏2024-04-04 12 02 45
截屏2024-04-04 12 10 12
截屏2024-04-04 12 10 33

**Review by MQChen211 — APPROVED** [review]

**Review by SRamen1999 — APPROVED** [review]
Everything is working as expected. The UI is responsive and resizes properly based on the window size. Also selecting a tab is now toggled and easy to see.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/e5f7c466-0b43-4174-92ad-a7aa6390c26a

**Review by Parth-tech — APPROVED** [review]
Hey Shiqing,

I have tested the functional requirements of this PR and it works correctly.

Tested the following:
- [x] When No Category is selected the Search Form must be `Horizontally center-aligned`
- [x] If the Screen size is `Large/XL` then the results table is displayed by side of the search form
- [x] If the screen size is small then the results are displayed right below the table

`View of screen with Search Form Only`
Screenshot 2024-04-04 at 2 12 42 PM

`Screen After Search is performed`

- __Large Screen__
Screenshot 2024-04-04 at 2 09 22 PM


- __Small Screen__
Screenshot 2024-04-04 at 2 10 08 PM
Screenshot 2024-04-04 at 2 09 05 PM

**Review by Parth-tech — COMMENTED** [review]
I have already approved the PR as it works perfectly. Here I wish to highlight my  observations.

Suggestion to improve the UI for Reports:


- I noticed that when on `Small Screen`, the 3 categories i.e `Projects`, `People` & `Team`, take up an entire row which looks kinda odd. It would be visually appealing at least to me if I had them side by side on all screen sizes.
- It would also be visually appealing if the `Show Total Project Report`, `Show Total People Report`, `Show Total Teams Report` & `Add Lost Time` Buttons were also horizontally center-aligned in the row.

This should not be part of this PR but just wanted to share a personal observation. Feel free to ignore/discuss it.

**Review by anandsesha — APPROVED** [review]
Hi, I've tested the search function on the Reports page, and it appears suitable for screen widths both above and below max-width 1350px. 

Just to double down on the previous suggestions:
- Suggest adjusting search function section (for narrow screens) to ensure users can easily notice when results appear without needing to scroll down.
- Suggest horizontally center-aligning the buttons located above the search results in the row for enhanced visual appeal.
Screenshot (731)

max width above 1350
max width below 1350px

**Review by Renanluizssx — APPROVED** [review]
Hi @yvonnep165, i reviewed your application and it's running correctly

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/91915133-313b-4970-bc4c-44dd242cd4aa

**Review by Tiantian-C — COMMENTED** [review]
I have tested it and it looks really nice!
Screenshot 2024-04-06 at 2 31 01 PM
Screenshot 2024-04-06 at 2 31 22 PM

**Review by MohdShahzil29 — APPROVED** [review]
The page format is well-suited, with the result table positioned to the right on wider screens and below the search field when the window is narrower.

https://www.loom.com/share/0327226c54b44d4d9efca81072ad35a9

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
