### PR TITLE
Hiral fix profile page formatting

### PR DESCRIPTION
**Pull request by hiralsonip**
# Description
Fix the design issue of the profile page

## Related PRS (if any):
This frontend PR is related to the Development backend PR.

## Main changes explained:
- Fix the design issue in the Basic Information tab on the profile page
- Update the design for the team tab when no team is assigned 

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin user
5. go to dashboard→ Profile
6. verify the design for the regular screen and check for the responsiveness as well. 
7. go to dashboard→ Profile → Team → Assign Team and check for the background colour in the dropdown menu
8. go to dashboard→ Profile → Project → Assign Project and check for the background colour in the dropdown menu

### Before

Profile_Page_Basic_Info_Before

Team_Assigned_Before

Team_Not_Assigned_Before

Assign_team_before

### After

Profile_Page_Basic_Information

Profile_Page_Team_Assigned

Profile_Page_Team_Not_Assigned

Assign_Project

Assign_Team

### Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66827672/a5c44239-9880-492a-a0dc-5a07c071abd2

### CODE REVIEW

**Review by lacnoskillz — DISMISSED** [review]
Hello @hiralsonip 
I pulled your code and revied your changes and they look great!
Nice work and good eye for detail. little things like this really help the page appear more professional and clean.

See below images

# Profile page Before
profile before

# Profile page after

profile after

# Teams section before

profile teams section before

# Teams section after

profile teams section after

# Also maintained its mobile responsiveness!
profile after mobile

profile teams section mobile after

Great work
and happy coding!

**Review by hbodgal — CHANGES_REQUESTED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/b9c641a5-d4e4-4a83-88ed-bd4311d04ca4

I have double checked that I have checked in this branch locally and in development branch in backend. I have installed dependencies as well. I have used Admin login still I see white screen in profile page.

**Comment by hiralsonip** [comment]
> HGN.APP.-.Google.Chrome.2024-05-04.12-47-38.mp4 
> I have double checked that I have checked in this branch locally and in development branch in backend. I have installed dependencies as well. I have used Admin login still I see white screen in profile page.

Hi @hbodgal 

I have applied these steps and it worked for me. Kindly check. 

- Pull the latest code and install all the dependencies for the frontend and backend. 
- Also, build the backend project and run the project. 
- Review the thread at - (https://highest-good.slack.com/archives/CSCN20FA5/p1714537724845419)

**Review by SushmithaPrathap — DISMISSED** [review]
Hi Hiral, I just reviewed this PR. The changes looks good! Its responsive as well!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/bb42205d-a281-468f-aaf1-cfab8df361e6

**Review by linkhanthtel — DISMISSED** [review]
I reviewed your PR and new UI look good and responsive! Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/04d14cac-7563-48e0-bf5e-89067febda99

**Review by Ramaruva — DISMISSED** [review]
Hi verified your changes in my local env and they are working as expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/f5af873b-8df5-4d82-84ae-5fe4f5d19c3b

**Review by MinSun0814 — DISMISSED** [review]
New UI design looks clean and is responsive! Good work!
image
image

**Comment by KaushikMreddy** [comment]
Hi, 

I've reviewed your changes, they look good. The drop-downs look uniform and profile page is neater
image
image
image

Same pages after decreasing resolution
image
image

Good work!

**Review by dkt6 — APPROVED** [review]
Thank you for your great work! LGTM

**Comment by ZhangPeizhou** [comment]
Works as expected.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/4d8d6f3e-6528-4ad0-a99a-48cfa8bce1e0

**Comment by CloudyZ524** [comment]
Hi Hiral, I just reviewed this PR which function works well and the page is responsive!

There are two suggestions:

1. The Status and Active currently appeared in two lines. 
Screenshot 2024-05-31 at 13 39 06

2. The box next to the Assign Team button with "X-XXX" looks confusing and I'm not sure if it has any function related to team assignment. It would be better to make it more clear with instructions and placeholders.

Screenshot 2024-05-31 at 13 42 34

**Review by CloudyZ524 — DISMISSED** [review]
Hi Hiral, I just reviewed this PR which function works well and the page is responsive!

There are one suggestion: The box next to the Assign Team button with "X-XXX" looks confusing and I'm not sure if it has any function related to team assignment. It would be better to make it more clear with instructions and placeholders.

Screenshot 2024-05-31 at 13 42 34

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works as intended. Great Job! Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/493fb6a9-4693-45ec-9b0d-dfd20fe6d78e

**Review by JatinAgrawal94 — DISMISSED** [review]
1)checked into the current branch
2)Executed npm install and npm run start:local to run this PR locally
3) Clear site data/cache
4) log in as an admin user

The profile page looks great and is responsive.
Screenshot 2024-06-01 at 8 13 12 PM
Screenshot 2024-06-01 at 8 13 23 PM
Screenshot 2024-06-01 at 8 13 41 PM
Screenshot 2024-06-01 at 8 13 52 PM

**Comment by akshit0211** [comment]
Hello Hiral, I reviewed your changes and they look good.

Basic information
Basic Dark mode
Team
Team Dark mode
Assign project
Responsive


Suggestion: Assign Project and Team drop-down windows should follow the dark mode color scheme.

Assign project - should be correct in dark mode
Assign team - should be correct in dark mode

**Review by akshit0211 — DISMISSED** [review]

**Comment by nishithaShetty** [comment]
Hi Nice work, 
The design is rendered as expected, attached the screenshots below. They are responsive as well.
PR#2225_1
PR#2225_2
PR#2225_3
PR#2225_4
PR#2225_5

**Review by hbodgal — DISMISSED** [review]

**Review by Trip2310 — APPROVED** [review]
Reviewed this PR with development backend; In Project and Team , assign project and assign team is not visible for me other than that it works smooth.
a) At light and dark mode
b) checked page responsiveness for different dimensions(phone/desktop)
great work

2PR#2225
PR#2225

**Review by suaniii — APPROVED** [review]
I verified your changes in my local environment, and they are working as expected. The new UI looks clean, responsive, and uniform. Nice work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/b2272d04-b8ee-45e7-afed-470608d1d9c1

**Review by Sudershhh — APPROVED** [review]
The Profile Page including the Teams and Projects Modals are responsive for different viewports. The UI is clean and seamless. Good Work.

PR 2225 - 2

PR 2225

**Review by vishavk1992 — APPROVED** [review]
Hi Hiral, I've tested your pull request. It works as intended. The profile page looks great and is responsive.

PR-2225
PR-2225-1

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/17616127-f2bc-40f8-8648-9a83e1901195

**Review by DiyaWadhwani — APPROVED** [review]
Hey Hiral,
Went over your changes in both desktop and mobile versions and the UI looks clean and organized. Deletion of a team or project maintains the UI tables and assignment of either  adds to the table properly without messing with the overall structure of the UI.
Added a video of testing below. Great work.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/14dec832-46fa-4948-b723-b810f53c7516

**Review by Sarath-3119 — APPROVED** [review]

**Review by Sarath-3119 — APPROVED** [review]
The changes requested in the pr seems to be working properly. Checked the subsections in the profile page in both light and dark modes. The page formatting is seen as expected and the app entirely is responsive as well. Good work!

https://www.loom.com/share/307fc951f7f14505a5d1f7d597493657?sid=3859076c-27d4-40f3-87ce-b37ca91b7c50

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
