### PR TITLE
Zuhang_fix_compressed_view_of_dashboard_tasks_tab

### PR DESCRIPTION
**Pull request by zuhang2000**
# Description
- On the dashboard page, there are two columns: the left column(tasks and timelogs) and the right column(Leaderboard).
- Previously both columns shrink at the same time, making the information on the left not visible.
- Jae now want that when he shrink the browser window, only the right column shrinks and the left column stays the same. 

For more detail, please check the below link for what's needed:
https://www.loom.com/share/698ff0609a3c45879581b8557b10eb7c?sid=11912a5d-6c0f-4534-95bd-cd03a2dcb196

## Main changes explained:
- Update file Dashboard.jsx for the corresponding components. 
- Update file Dashboard.css. Creating new css styles for the components.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard
6. verify when you shrink the browser window, only the right columns shrinks. And the left stays the same until there's not enough spaces for any.

## Screenshots or videos of changes:
Before changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/6e82d2fe-5947-4c34-8c86-0e6a9238813d

After changes: 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/18d63fd5-aa2c-473f-a4fd-ea9556abb847

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by abdel-lall — CHANGES_REQUESTED** [review]
the changes work as described, but there's a tiny problem the layout isn't switching like it should at the breaking point.
Screenshot 2024-01-27 221959

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Zuhang,

All functionalities worked as intended; please refer to the video. Congrats! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/4964de38-0464-4689-9752-61dae4c05705

**Review by Renanluizssx — COMMENTED** [review]
Hi @zuhang2000, i tested your application and it's correct the responsive, but i noticed the tasks and timelog element is above the other, for example the container is above the weekly summary, see my review please:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/1342970e-24b6-4664-8a38-c62d03ccaafd

**Review by peterson337 — CHANGES_REQUESTED** [review]
The layout doesn't switch as it should at the break.

one comunnity

**Comment by Nahiyan-16** [comment]
## Not working for me
Hi Zuhang, I am testing this PR on Windows using Chrome as my browser. I first tested what the development version of the dashboard UI looked like: 
[screen-capture.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/e6d57008-0e30-4716-acff-178fc181c497)
Then I went on to test your changes and noticed a couple of issues. The left side column seems to overlay over the clock and when I shrink the window, they both start shrinking at the same time, and then at around 1000px wide, I start noticing that the left side would shrink while the right remained the same. Here is a video demonstration: 
[screen-capture (1).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/1f634b04-5739-43a4-a7b8-0422dca13af6)

**Review by ShengjieMao — COMMENTED** [review]
Hi, the page did shrink as expected, but as i keep shrinking the page, the right side (leaderboard parts) is covered by the left side. Please check the video for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/9e1a1862-56b0-4cdc-937d-64d7adab75ff

›

**Review by Sophie-lei — CHANGES_REQUESTED** [review]
I just tested this PR. I found only the right columns shrunk at the beginning. but at the break, there is only the right column instead of both columns.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/833c9ad9-71fc-4599-acc4-9583c93e6397

like this 
Screenshot 2024-02-03 at 15 43 25

**Comment by xmyoot** [comment]
Hello, 
The responsiveness of the layout looks good to me, instead of having both tangible time and total time, on the smaller breakpoints we could just display the progress bar which basically provides similar information. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/adc0ed9d-57ee-4ffe-bae0-e9cf4c872fd8

**Review by TapanPathak — CHANGES_REQUESTED** [review]
Hi, I reviewed the changes and the responsiveness works great. Only the right column shrinks but the tasks and timelog element overlaps as seen in video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/e4782047-5094-41d0-b8dd-6601cb7e1f52

**Review by Pandani07 — CHANGES_REQUESTED** [review]
The columns move as you described but the weekly summary reports component gets overlapped by the tasks part.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/8cb996dd-d840-4a98-b4ff-9ab8926fc30d

**Comment by galgalinidhi** [comment]
Hi @zuhang2000, I tested your PR and I noticed that the layout doesn't change and as I shrink the window, the Weekly Summary Due Date component is overlapped by the Tasks and Timelogs component.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/3ec40771-3986-4be9-84f6-301d8c3e3ba9

**Review by Jingyii800 — CHANGES_REQUESTED** [review]
Hi @zuhang2000. I tested this feature with Chrome on Windows. It didn't change as expected when I shrunk the window. Also, the timer, logs, and tasks overlapped, which looked unclear. Please check more details in this video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/189fa6d3-4955-46ee-89f4-00d73f54b032

**Review by XiaohanMeng — DISMISSED** [review]
Hi, I've reviewed this PR and it works well, achieving the intended effect where the right column shrinks while the left remains unchanged. Additionally, the tasks and timelog elements no longer overlap. Well done!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/87ec4ec9-c784-4b34-89e6-66afd7fcb634

**Pull request closed without merging**
