### PR TITLE
Haohui - fix permission for edit tasks

### PR DESCRIPTION
**Pull request by Lin1404**
# Description
image

## How to test:
1. check into current branch
2. do npm run build and npm run start to run this PR locally

**Permissions assign to individuals**

3. log as owner user call user A
4. go to dashboard→ Other Links→ Permissions Management→ Manage User Permissions
5. input another user name, call user B
6. find the “Edit Task”, click the add button
7. scroll down and click submit button
8. log out and login as user B(if already logged in, make sure to log out and log back in)
9. go to “Dashboard”→ "Other Links" -> "Projects" -> "WBS Button" -> "Choose any WBS" -> "Edit" -> "Edit" 
10. make some change of the task then submit.

**Managers account**

11. log as owner user call user A
12. go to dashboard→ Other Links→ Permissions Management→ Manage User Permissions
13. input manager user name, call user C
14. click the "Reset to Default" button on top right
15. scroll down and click submit button (double check "Edit Task" is unselected)
16. log out and login as user C(if already logged in, make sure to log out and log back in)
17. go to “Dashboard”→ "Other Links" -> "Projects" -> "WBS Button" -> "Choose any WBS" -> "Edit" -> "Edit" 
18. make some change of the task then submit.

## Screenshots or videos of changes:
Managers account

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/c8d6239e-9d8f-486d-9ab6-b186984c3359

Permissions assign to individuals

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/c47f1ddd-275d-4452-b8d8-fd676b236d45

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by this-journey — CHANGES_REQUESTED** [review]
Hello!  I've attached a video of my review here.  I logged into my owner account and tried to update user permissions on several accounty, but couldn't scroll to the bottom to submit or scroll down and find the "edit task" button.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/5ab947b1-096a-450b-a8e6-71da6d456c77

**Comment by DragonSlayer2401** [comment]
I tested your PR on my owner account I was able to reset to default but I was unable to scroll through the user permissions. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/f498c860-caae-4254-8136-7ae0698871af

**Review by pika-chu11 — COMMENTED** [review]
Hi @Lin1404 , I can't scroll down when I tried to asign the permission for the **Manager** Account. 
Here is the video for detail:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/a6e50a74-8f2d-4d7e-a421-3f1b320c3707

**Review by keyunhuangg — CHANGES_REQUESTED** [review]
Logged in as owner account, went to manage user permission and cannot scroll down and access the page. 
Screenshot 2023-12-21 at 2 28 35 PM

**Pull request closed without merging**
