### PR TITLE
Deepthi fix spacing between labels and input fields 

### PR DESCRIPTION
**Pull request by deepthikannan**
# Description
image
…

## Main changes explained:
- Converted text to <label> elements and linked them to their corresponding <input> fields using htmlFor and id attributes.
- Adjusted CSS to maintain consistent spacing and layout between the labels and the input fields.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other links→ Send email …
6. verify that the labels and it's respective input field spacing has been adjusted for consistency, ensuring proper alignment.

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by RishithaMamidala — DISMISSED** [review]
@deepthikannan 
I have reviewed the PR, the formatting changes regarding spacing between input and labels is consistent.
PR 2715

**Review by nikhilgiri0226 — APPROVED** [review]
image

This looks good. And have proper spacing.

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and everything working as expected

Screenshot 2024-09-24 171426

**Review by chu-ziyu — DISMISSED** [review]
I have tested this PR and everything worked as expected in both light and dark mode.
Screenshot 2024-09-24 at 3 00 44 PM

**Review by manikittu810 — APPROVED** [review]
Hello @deepthikannan 
Everything is working as mentioned.

Screenshot 2024-09-24 at 8 17 05 PM

Thanks.

**Comment by tharunaa-1** [comment]
The adjustments looks perfect, as expected.

image

**Review by slidracoon72 — APPROVED** [review]
#2715
@deepthikannan
I have tested this PR and things are working as expected.

**Review by Lexie5212 — DISMISSED** [review]
I tested the PR, everything looks good to me. There is the space between the label and its respective input box.
Screenshot 2024-09-25 at 13 12 41

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working properly 

Screen Shot 2024-09-25 at 6 58 05 PM

**Review by ashmita123 — APPROVED** [review]
Tested PR #2715 in both light and dark mode. The spacing between labels and input fields is consistent and aligned as expected. Everything works as intended. 

https://github.com/user-attachments/assets/1d500f43-5036-4454-b804-4464de55660b

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and the spacing between the labels is consistent.

Screenshot 2024-09-26 172029

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (209)

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Hi Deepthikannan, great work so far and the spacing between the labels and inputs are now a pixel perfect match up since we're styling the spacing simulataneously. I just have one small fix, and you'll 100% have my approval. 

If you can replace the inline styling on all 3 of the labels and instead apply ternary classNames depending on the state of dark mode. Generally, we want to avoid inline styling such as style={{}} if at all possible as it's bad practice, impacts performance, and decreases maintainability in the long run. I've included an example below. 

<label
  htmlFor="upload-header-input"
  className={darkMode ? 'text-light' : 'text-dark'}
>
  Upload Header (or footer):
</label>
<input
  type="file"
  id="upload-header-input"
  onChange={addImageToEmailContent}
  className="input-file-upload"
/>

p.s. there's also a merge conflict. Feel free to send me a message on slack, and I'll get this reviewed asap.

**Review by ziyanw52 — COMMENTED** [review]
The format looks good.
431727475251_ pic_hd

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the spacing looks in the input field and label looks good.
Screenshot 2024-09-28 at 8 14 28 AM

**Review by KurtisIvey — APPROVED** [review]
Looks great and the code works perfectly. Thanks for putting up with all the small changes I advised. Ready for merge

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
