### PR TITLE
Changhao - Unit test for textsearchbox

### PR DESCRIPTION
**Pull request by Changhao3220K**
# Description
Unit test for textsearchbox

## How to test:
1. check into current branch
2. do `npm install` and `npm test TextSearchBox.test.js` to run this PR locally
3. check all 6 tests passed

## Screenshot:
Screenshot 2023-12-07 at 11 00 29 AM

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-09 at 12 15 49 AM

**Review by Hemsharavanan — APPROVED** [review]
- Overall, the test suite covers essential functionality and interaction scenarios for the TextSearchBox component. 
- Consolidating descriptions, refining test names, and verifying parameter passing will enhance the clarity and maintainability of the test suite. 
- Great job!
PR #1667 Unit test for textsearchbox

**Comment by DragonSlayer2401** [comment]
I tested your PR and all tests passed great work. Please watch the overview video below for more detail:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/acf5371e-816f-4bb6-9052-dbd2d11d08ef

**Review by pika-chu11 — APPROVED** [review]
Hi @Changhao3220K , the tests are passed! Great job!
PR 1667

**Review by ZichanYang324 — APPROVED** [review]
Hi @Changhao3220K , I have run the test and all the test cases passed, well done!
Screenshot 2023-12-09 at 16 57 35

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-09 at 2 17 50 PM
Good job, @Changhao3220K ! All the cases passed!

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-12-10 at 12 59 30 AM

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Comment by Lin1404** [comment]
I tested your PR and all tests passed great work.
Screenshot 2023-12-15 at 7 59 10 AM

**Review by Lin1404 — APPROVED** [review]

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 16 - PR6

**Review by ChengyanOo — APPROVED** [review]
Hi @Changhao3220K,

Congratulations, all tests have passed successfully! Excellent work.

Screenshot 2024-01-10 at 15 41 51

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Please fix the test file location of this test as well

**Review by yvonnep165 — APPROVED** [review]
Hi @Changhao3220K,
The tests covered are comprehensive and all tests are passed. Nice work!
PR 1667

**Review by 666saofeng — APPROVED** [review]
Hi, All tests passed. Great job!
image

**Review by XiaohanMeng — APPROVED** [review]
All cases passed! Great Work!
PR1667 UnitTest result

**Comment by Gmon-k** [comment]
Test cases has passed and below is the screenshot for it

**Comment by beblicarl** [comment]
@Changhao3220K , kindly fix the merge conflicts

**Comment by beblicarl** [comment]
All tests passed successfully 

image

**Review by beblicarl — APPROVED** [review]

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
