### PR TITLE
Mounica dashboard css fix

### PR DESCRIPTION
**Pull request by mounica-dingari-by**
# Description
Fixed the Hours and Summary's css in the Dashboard.

## How to test:
1. check into current branch
2. do `npm install` and checkout to `mounica_dashboard_css_fix` to run this PR locally
3. log as any user
4. go to dashboard and check the Activity bar below the navigation bar.

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by yaow62023 — APPROVED** [review]
The screenshot is the update version of Dashboard page. 

Screenshot 2023-08-19 at 8 51 28 PM

**Review by TheDescendant39 — APPROVED** [review]
Hi, I was able to verify your changes. 

Before:
Screen Shot 2023-08-19 at 6 43 14 PM

After:
Screen Shot 2023-08-19 at 7 00 57 PM

**Review by n0vay — APPROVED** [review]
Works as intended.
image

**Review by tsunami776 — APPROVED** [review]
Tested with both admin and volunteer accounts. The dashboard looks as depicted in your screenshot.
CleanShot 2023-08-20 at 15 05 56
CleanShot 2023-08-20 at 15 06 33

**Review by jerryren527 — COMMENTED** [review]
Hello @mounica-dingari-by ,

I am having trouble checking out your branch:
Screenshot 2023-08-20 at 8 35 01 PM

Any advice from you or anyone else would be much appreciated! Thanks!

**Comment by one-community** [comment]
Simple fix, thank you all. Will merge as soon as Edwin approves this. Can someone help @jerryren527 too?

**Comment by luisarevalo21** [comment]
> Hello @mounica-dingari-by ,
> 
> I am having trouble checking out your branch: Screenshot 2023-08-20 at 8 35 01 PM
> 
> Any advice from you or anyone else would be much appreciated! Thanks!

Hello  @jerryren527 try using "gh pr checkout 1142." this is located at the top right of each repo under "code" 
You may need to install GH to your terminal and sign in as well. I find this much easier then typing the entire branch name.

Hope this helps.

**Review by luisarevalo21 — APPROVED** [review]
Hello @mounica-dingari-by 
I tested your PR and works as intended. Great job!

Before: 
Screenshot 2023-08-20 at 8 23 25 PM


After: 

I tested for both an admin account and volunteer account. The top bar is now aligned correctly. 
Screenshot 2023-08-20 at 8 24 04 PM

Screenshot 2023-08-20 at 8 23 51 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by jerryren527** [comment]
> > Hello @mounica-dingari-by ,
> > I am having trouble checking out your branch: Screenshot 2023-08-20 at 8 35 01 PM
> > Any advice from you or anyone else would be much appreciated! Thanks!
> 
> Hello @jerryren527 try using "gh pr checkout 1142." this is located at the top right of each repo under "code" You may need to install GH to your terminal and sign in as well. I find this much easier then typing the entire branch name.
> 
> Hope this helps.

Hi @luisarevalo21, thanks for the suggestion to use GitHub CLI. I was able to successfully checkout this branch using GH! Thanks for your help!

**Pull request merged**
