### PR TITLE
Supriya-Add-User-Role-below-their-name-in-Tasks-Tab

### PR DESCRIPTION
**Pull request by SupriyaSudini**
# Description
The role of the user was added in the Tasks tab 

## Related PRS (if any):
No related PRs
…

## Main changes explained:
Added the role of the user(except Volunteer) below their names and above tracking in TeamMemberTask.jsx  for both Light mode and dark mode

image

…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Tasks→ task→…
6. verify you can see the role under their name
7. verify this new feature works in [dark mode]

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/70ea7538-27ab-4208-a2d4-2dcf1e8604ed

## Note:
Test for different modes and with different roles

### CODE REVIEW

**Review by Nahiyan-16 — APPROVED** [review]
Hi Supriya,

I've reviewed the pull request for adding user roles below usernames. It looks good. The roles are displayed clearly, except for volunteers, and the styling adjusts based on the dark mode setting. The implementation conditionally renders the user role with appropriate font size and color, ensuring a clean and consistent look across different modes.


https://github.com/user-attachments/assets/6c8205fc-794f-4600-af0d-9584e33065a6

**Review by anji-annavarapu — APPROVED** [review]
Screenshot 2024-11-09 224627
Screenshot 2024-11-09 230153

It showing user roles perfect, except volunteers, everything else good

**Review by RashmiKY98 — APPROVED** [review]
Reviewed the code and tested the PR in dark and light mode. Ensured to test the functionality with multiple user role. For volunteers the user role is not displayed.
Screenshot 2024-11-16 224525
Screenshot 2024-11-16 224422

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working as expected 

Screen Shot 2024-11-19 at 6 22 46 PM

**Review by vijay10pk — APPROVED** [review]
Changes are working as expected.
Screenshot 2024-11-19 at 10 11 33 PM
Screenshot 2024-11-19 at 10 11 13 PM

**Comment by SatyashanthiT** [comment]
Verified that the user role is displayed correctly below their name in the Tasks tab for both light and dark modes. Everything works as expected, and the feature aligns with the requirements. Approved the changes.

image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/ff0ff1c0-7d5f-45e6-bf3f-bbcdcd13c6cf

**Review by SS-Reddys — APPROVED** [review]
Changes are working as expected both in light and dark modes

the user role is displayed under their name except for volunteers.


image


image

**Comment by ppsahu** [comment]
I have tried to review this PR, however I am getting login issues for all 3 accounts. If you have any fixes please let me know. below are the screenshots for reference.

Screenshot 2024-11-29 at 2 16 59 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
