### PR TITLE
Nahiyan_Added hover effects on tables in dark mode

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Hover effects were added on all tables in dark mode.
Pages: 
- Dashboard (Leaderboard, Team Member Tasks, Badge Report Modal)
- All tables on Reports page
- Team Locations (User Lists)
- User Management (User table, Setup Invitation History Modal)
- Badge Management (Assign badge, Badge Development)
- Projects (Projects table, Members, WBS)
- Teams (Teams table, Members modal)
- Permissions Management (Roles)

## Related PRS (if any):
This frontend PR is related to the dev backend.

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log in as owner user
5. go to the pages mentioned in the description
6. verify that when hovering over the table row in dark mode, the background color lightens 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/8b0c5871-508f-4979-86f7-294572134976

### CODE REVIEW

**Review by Kavil-Jain-514 — DISMISSED** [review]
All the mentioned pages have the functionality working as expected. The hover on all the tables works in dark mode.
Here are a few screenshots:
image
image
image
image

**Review by peter6866 — DISMISSED** [review]
Great work on implementing the hover effects for tables in dark mode!

Here's my review based on the provided testing steps:

✅ **Hover Effects Implementation:**
- Checked out the current branch and ran `npm install` and `npm run start:local`.
- Cleared site data/cache and logged in as an owner user.
- Navigated to the following pages and verified that hovering over a table row in dark mode lightens the background color as expected:

*   Dashboard (Leaderboard, Team Member Tasks, Badge Report Modal)
*   All tables on the Reports page
*   Team Locations (User Lists)
*   User Management (User table, Setup Invitation History Modal)
*   Badge Management (Assign badge, Badge Development)
*   Projects (Projects table, Members, WBS)
*   Teams (Teams table, Members modal)
*   Permissions Management (Roles)

✅ **Visual Consistency:**
- Confirmed that the hover effect is visually consistent across all tables and pages mentioned in the description.

- Should be unrelated to this PR but discovered a bug where typing in the Team Locations text field causes the app to crash. 

https://www.loom.com/share/4bf4f4d9effd4a43ba2d7d12afdcb8ba?sid=3fdfb9c7-14e6-4818-a1b2-aa4831eaf881

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested your PR and it works as intended. Please refer the attached screenshots.
Screenshot 2024-06-01 at 12 51 29 PM
Screenshot 2024-06-01 at 12 51 37 PM
Screenshot 2024-06-01 at 12 51 58 PM
Screenshot 2024-06-01 at 12 52 15 PM
Screenshot 2024-06-01 at 12 53 17 PM

**Review by Sandhya1236 — DISMISSED** [review]
I have successfully tested the addition of hover effects on all tables in dark mode across various pages. This frontend PR is related to the dev backend. The pages tested include Dashboard (Leaderboard, Team Member Tasks, Badge Report Modal), all tables on the Reports page, Team Locations (User Lists), User Management (User table, Setup Invitation History Modal), Badge Management (Assign badge, Badge Development), Projects (Projects table, Members, WBS), Teams (Teams table, Members modal), and Permissions Management (Roles). After checking into the current branch, running npm install, and starting the application locally, I cleared the site data and cache. Logging in as an owner user, I navigated to the mentioned pages and verified that the background color of table rows lightens when hovered over in dark mode. All hover effects worked correctly, providing the intended visual feedback.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/cc106ba8-5d01-4854-bd78-dd918ff24283

**Review by tianyangL11 — DISMISSED** [review]
All  pages mentioned have added a hover effect.  Please see the screenshot attached
a3ce54d1239859e91a37024ee498987
241fe1cfab8a4c79de309e783e01ae5
a4e3328315388fb273dd4a0c94f9251
489d5aad801015c1ca2a743f167a607

**Comment by Vijeth-V** [comment]
Great work Nahiyan, this works perfectly well. I have tested all the pages to make sure it works well and everything works great.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/75d268fd-dec2-467a-85f0-ca408aa25f11

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the hover functionality works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/22ee9212-7a6d-4c27-b54d-13943af03228

**Comment by beblicarl** [comment]
Great work! This functionality works as intended and the code is great

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.06.05-14_49_49.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/0fb02447-cf92-4765-b27e-0af370da690d)

**Review by beblicarl — DISMISSED** [review]

**Pull request merged**
