### PR TITLE
Rishitha_Fix_team_code_requirement_new_users

### PR DESCRIPTION
**Pull request by RishithaMamidala**
# Description
(PRIORITY High) Jae:  Fix team code requirement for creating new users (WIP Rishitha)
Admin Login → Other Links → User Management → Create New User
The team code should not be required or throw the error shown below

## Related PRS (if any):
This frontend PR is related to the Developemnt backend PR.

## Main changes explained:
- Updated src/components/UserProfile/AddNewUserProfile/UserProfileAdd.jsx to ensure team code is not mandatory

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links → User Management → Create New User
6. Verify that a new user is successfully created when no team code is provided

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/ed1f1439-97c7-4b59-85b2-0098632c2bc6

### CODE REVIEW

**Review by Muhideenthegreat — APPROVED** [review]
Verification:

- Successfully created new user without team code requirement. No errors thrown during user creation process

Screenshot 2024-11-06 at 9 25 03 PM
Screenshot 2024-11-06 at 9 25 49 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/9cc7e90d-4486-4580-a2b1-e8708d79c602

**Review by manikittu810 — APPROVED** [review]
Hello @RishithaMamidala 
Everything is wokring as mentioned.
Thankyou

https://github.com/user-attachments/assets/bd420c23-3ac6-42db-a510-48bd1dcdcbea

**Comment by beblicarl** [comment]
This feature works as intended and the code is great

[7d675403-3dec-4255-9151-66ae9d3d8922.webm](https://github.com/user-attachments/assets/a10ccb41-7ed7-42ae-9460-9973ad6933f5)

**Review by beblicarl — APPROVED** [review]

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working properly

Screen Shot 2024-11-08 at 11 10 58 AM
Screen Shot 2024-11-08 at 11 10 33 AM

**Comment by RashmiKY98** [comment]
The feature works fine. Reviewed the code. Good job!
Screenshot 2024-11-08 232650


Suggestion: 
While testing the code, I observed that an "Unexpected Error" is displayed when an unauthorized person attempts to create a new user. To enhance user experience, it would be beneficial to show a more informative error prompt, alerting the user to their lack of authorization.
Screenshot 2024-11-08 233135

**Review by nikhilgiri0226 — APPROVED** [review]
I have reviewed this PR and I verify that I was able to create a new user when no team code was provided.


https://github.com/user-attachments/assets/7f34ec13-0ecc-4234-9dec-148ecddb238c

**Review by aaryaneil — APPROVED** [review]
Tested the PR and was able to create user without the requirement of a team code.

https://github.com/user-attachments/assets/fff37c5b-b495-4452-9256-72137184b956

Screenshot 2024-11-09 at 5 01 15 AM

**Review by vijay10pk — APPROVED** [review]
All the changes are working as expected.
Screenshot 2024-11-09 at 9 52 17 PM
Screenshot 2024-11-09 at 9 51 42 PM

**Pull request merged**
