### PR TITLE
Shrey_unit_test_TinymceEditor

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for TinyceEditor component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test TinymceEditor.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-11-25 at 12 44 56 PM

### CODE REVIEW

**Review by Hemsharavanan — APPROVED** [review]
- Well-defined test scenarios covering essential aspects like rendering, label display, error handling, and class application.
- Appropriately utilized async/await with waitFor and findBy methods for handling asynchronous rendering and assertions.
- Majority of assertions use screen queries, aligning well with Testing Library best practices.
- Over all the tests provide comprehensive coverage for the component, validating its rendering, label display, error handling.
PR #1582

**Review by Alforoan — APPROVED** [review]
All passed. Nice!

image

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 20 - PR3

**Review by 666saofeng — APPROVED** [review]
Hi, all tests passed and it worked as intended.
image

**Pull request merged**
