### PR TITLE
Shiwani BlueSquare unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for BlueSquare component

## Main changes explained:
- Added 9 test cases: userProfile prop present, userProfile prop is not present, check date and description, check if + sign is visible when infringementAuthorizer permission is not added, check if + sign is visible when infringementAuthorizer permission is added, check if handleBlueSquare is called when user clicks on the button, check if handleBlueSquare is not called when user does not click on the button, check hasPermission function returns false if permission is not present, check hasPermission function returns true if permission is present.

## How to test:
1. check into current branch
2. do `npm test src/components/UserProfile/BlueSquares/__tests__/BlueSquare.test.js` 
3. Verify if all the test cases pass without any errors or warnings

## Screenshots or videos of changes:
Screenshot 2024-01-31 at 6 35 31 PM

### CODE REVIEW

**Review by 666saofeng — APPROVED** [review]
All tests passed. 
image

**Review by yvonnep165 — CHANGES_REQUESTED** [review]
Hi @Shiwani99 ,
I have tested your cases but there's one test case failed. Please refer to the below for more details:

**Comment by Shiwani99** [comment]
> Hi @Shiwani99 , I have tested your cases but there's one test case failed. Please refer to the below for more details:
> 
> 

Hi,
Thank you for your review. Have you changed date while testing in the code?

**Review by ShengjieMao — COMMENTED** [review]
Hi, I ran into the same error as @yvonnep165 did and I didn't change anything in your original file while running the testing command. Also can't see your image so not sure whether I need to make any modification while testing. Please check the image for the error message.
PR_1904

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 23 - PR1

**Review by peterson337 — DISMISSED** [review]
[Shiwani99](https://github.com/Shiwani99), All Tests passed. Good job!

a

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, reviewed your PR and all the test cases passed successfully. Please refer the screenshot attached.

PR 1904

**Review by yvonnep165 — COMMENTED** [review]
Hi @Shiwani99 , only when i changed the file to below, all the tests can be passed:
Screenshot 2024-03-22 at 8 03 51 PM
Screenshot 2024-03-22 at 8 04 39 PM
Otherwise, there's still one test can not be passed:
Screenshot 2024-03-22 at 8 06 06 PM

**Comment by Shiwani99** [comment]
> Hi @Shiwani99 , only when i changed the file to below, all the tests can be passed: Screenshot 2024-03-22 at 8 03 51 PM Screenshot 2024-03-22 at 8 04 39 PM Otherwise, there's still one test can not be passed: Screenshot 2024-03-22 at 8 06 06 PM

Hi,
Thank you for reviewing again. Actually the date should not get changed. I will further check what the issue is.

**Comment by yvonnep165** [comment]
Hi, I checked out this PR again to run the test cases after removing the previous branch. So I think I should cover all your modifications. I noticed all the BlueSquare scheduled on the following Sunday. Does that affect your unit testing here?

**Comment by Shiwani99** [comment]
> Hi, I checked out this PR again to run the test cases after removing the previous branch. So I think I should cover all your modifications. I noticed all the BlueSquare scheduled on the following Sunday. Does that affect your unit testing here?

That shouldn't be an issue because the data sent to the blue square component while testing is the one that I have set up in the file, so while testing the component my data will get passed to the component instead of what is already present in the database. I will check again to see what the issue might be. Thank you for your review.

**Pull request merged**
