### PR TITLE
 Jingyi_Add intangible time reminder/confirmation modal

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
Dashboard>Add Intangible Time Entry
When people add an intangible time entry that they want converting to tangible, they should always put a reason why it wasn’t logged properly using the timer. I want a confirmation modal to make sure this happens from now on. 

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- Add timelogconfirmationModal.jsx to display the message
- Edit TimeEntry.jsx to integrate new Modal

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard→ Add Intangible Time Entry
6. Fill in the form and submit the form.
7. verify a modal pops up when submitting the form, which ask the user to confirm their choice. If the user includes a reason for converting tangible time or it's intangible time, the form will be submitted, if the user hits "take me back", the page will back to the time entry form.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/f66961fb-3890-437a-a6c8-03dc4409c137

### CODE REVIEW

**Comment by ppsahu** [comment]
I tried to review this PR, however, I am facing some login issues, I have tried deleting the repo in my system and cloning it again, still, the problem persists. If you have any leads on how to fix this, please let me know.

Screenshot 2024-11-28 at 12 20 08 AM

**Review by SS-Reddys — COMMENTED** [review]
I cant able to change intangible time to tangible time.


image

**Review by nikhilpittala16 — CHANGES_REQUESTED** [review]
I have tested the PR and the checkbox is not working.

https://github.com/user-attachments/assets/fb842f1d-570c-4ade-aa0d-0327792d5687

**Review by anirudhsk2107 — CHANGES_REQUESTED** [review]
Facing the same issue raised above.
Clicking on the checkbox is not doing anything. 
Screen Shot 2024-12-04 at 11 01 15 AM

Getting an error on the console when i click on "Add tangible time entry"

**Comment by Jingyii800** [comment]
> I cant able to change intangible time to tangible time.
> 
> image

Please make sure your admin account has this "Toggle Tangible Time Self" permission : 
image

**Comment by Jingyii800** [comment]
> Please make sure using your admin account and your admin account has this "Toggle Tangible Time Self" permission :

Screenshot 2024-12-05 154549

**Comment by Jingyii800** [comment]
> I have tested the PR and the checkbox is not working.
> 
>  PR.vid.102.mp4

Please make sure your admin account has this "Toggle Tangible Time Self" permission :
Screenshot 2024-12-05 154549

**Comment by Jingyii800** [comment]
> Please make sure your admin account has this "Toggle Tangible Time Self" permission :

Please make sure your admin account has this "Toggle Tangible Time Self" permission :

**Comment by Jingyii800** [comment]
> Facing the same issue raised above. Clicking on the checkbox is not doing anything. Screen Shot 2024-12-04 at 11 01 15 AM
> 
> Getting an error on the console when i click on "Add tangible time entry"

Please make sure using your admin account and your admin account has this "Toggle Tangible Time Self" permission :
Screenshot 2024-12-05 154549

**Review by HowieMiao — APPROVED** [review]
image

Modal shows up and submission causes no problems, looks great!

**Pull request merged**
