### PR TITLE
Hoang make mark task as done and remove task from user more efficient

### PR DESCRIPTION
**Pull request by kylepham**
# Description
Screenshot 2024-06-11 at 3 14 24 PM

## Related PRS (if any):
None.

## Main changes explained:
- Implemented optimistic update to locally reflect changes to the user's task list when clicking "Mark as done" (1 in check mark, and 1 in dropdown menu) and "Remove user from task" (in X mark).
- Refactored code for readability.

## How to test:
1. Check into current branch
2. Do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. Log as admin user
5. Open network tab on the admin side.
6. Create a task and assign to a volunteer *(since volunteer account has a faster load time for convenient testing, but you can also try other roles)*.
  6.1. On the volunteer side, submit the task for review.
  6.2. On the admin side, mark task as done in the dropdown.
  6.3. Verify that the task disappears without triggering a request to the server to fetch the list again. Also, verify that the list doesn't show loading state.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/ebbffa43-9c10-4ecd-a72e-ea5061e6dd45

7. Create a task and assign to a volunteer.
  7.1. On the admin side, mark task as done by clicking the green check.
  7.2. Verify that the task disappears without triggering a request to the server to fetch the list again. Also, verify that the list doesn't show loading state.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/c0d88d3c-c37a-4bb3-96eb-0e72bc19b565

8. Create a task and assign to a volunteer.
  8.1. On the admin side, remove user from task by clicking the red X mark.
  8.2. Verify that the task disappears without triggering a request to the server to fetch the list again. Also, verify that the list doesn't show loading state.
  8.3. Go back to the assign task page, verify that the user has been removed from the assigned users list.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/c18069c2-a468-45f9-8652-1488f36b9c53

## Screenshots or videos of changes:
See above.

## Note:
Since the task list is extremely long (over 1000 items), the app will *inevitably* freeze for a short amount of time, then will become interactive again.

### CODE REVIEW

**Review by Kavil-Jain-514 — APPROVED** [review]
The functionality works great. I have reviewed the PR for all the three scenarios. Find the video below for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/5a1d88d0-5f9a-4aa3-aef0-b3b23745bf4a


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/cef1ab2c-e596-4230-9ee3-55a5c14e5bf8


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/88117488-1e87-4bd3-97af-9194bb015907

**Comment by kdaga81** [comment]
I replicated all the steps mentioned in the video and everything worked as expected!

**Review by kdaga81 — APPROVED** [review]
Working as expected!

**Review by Jingyii800 — APPROVED** [review]
It worked well. I followed all steps to test marking task as done by "green check" and dropdown button, it can smoothly remove the task without fetching data again. And it also worked well with "removing user from task". Please find more details in my video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/039c7847-893f-46a5-bda3-fe812b0c450f

**Review by suaniii — DISMISSED** [review]
Hi, the changes work well for existing tasks as demonstrated in video 1. However, if I create or edit a task, the page crashes as shown in video 2. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/97d5444d-8668-451d-b16d-ee49cdab6b74


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/a0882fea-1ef4-4ba7-a327-059d9a7e7b76

**Comment by kylepham** [comment]
> Hi, the changes work well for existing tasks as demonstrated in video 1. However, if I create or edit a task, the page crashes as shown in video 2.
> 
>  PR.2347-1.mov 
>  PR.2347-2.mov

Hi @suaniii, did the console show error? Could be more helpful if you could provide a more detailed reproduction. Thank you.

**Review by DiyaWadhwani — APPROVED** [review]
Hi Hoang,
I have tested your changes as per the instructions provided. 
I logged into the owner account and created 3 tasks to test all 3 cases mentioned in this PR. They all work as expected. I've added a video of the successful working of your changes below.
Great work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/debfac0f-f9f2-40f7-903f-ae6d13d7e500

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and it works as expected and assigned task from my owner account to volunteer account and submit task for review , then mark completed task from my owner account . 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/056ceba2-45a7-4e2d-a15c-3b2d3eb0d69a

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Great Work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/fb13b891-6edc-4b2f-960d-b5602de2f756

**Review by HowieMiao — APPROVED** [review]
Tested all 3 PR tasks, having trouble uploading all 3 videos so attached is the first task:

No problems submitting task for review as volunteer, marking as done and seeing it disappear on volunteers side.

No problems marking task done as admin and verifying on volunteer side

No problems removing user from task as admin, verifying the task disappears without request, and that the user has been removed

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73614967/d40b70ad-1aa3-40dd-a8ae-4829e02b0226

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this feature for three scenarios and it works fine. However, I was able to record only for two scenarios.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/fd78e3c5-3841-4679-a8d1-9333c023e124


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/4ce1a5f5-4fe5-43c7-b3a8-220636802709

**Review by vijay10pk — APPROVED** [review]
All the changes work as expected.
Screenshot 2024-07-12 at 2 33 40 PM
Screenshot 2024-07-12 at 2 31 24 PM
Screenshot 2024-07-12 at 2 31 05 PM
Screenshot 2024-07-12 at 2 30 21 PM
Screenshot 2024-07-12 at 2 24 20 PM

**Review by AnujVakil — APPROVED** [review]
I have tested this PR and working as expected
PR #2347_1
PR #2347_2
PR #2347_3
PR #2347_4

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
