### PR TITLE
Changhao - Unit testing for CountdownTimer

### PR DESCRIPTION
**Pull request by Changhao3220K**
# Description
Unit tests for `CountdownTimer.jsx`

## Main changes explained:
Added unit tests

## How to test:
1. Check into current branch
2. Do `npm install`
3. Do `npm test CountdownTimer.test.js`
4. Verify all 5 tests have passed

## Screenshots of changes:
Screenshot 2023-11-30 at 4 04 39 PM

### CODE REVIEW

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed! Great Work!

Week 14 - PR4(#1619)

**Review by skaush21 — APPROVED** [review]
Verified that unit test passes.
Screen Shot 2024-03-01 at 12 06 17 AM

**Review by yvonnep165 — APPROVED** [review]
Hi, I tested the PR and all the test cases passed! Nice Work!
Screenshot 2024-03-22 at 4 37 58 PM

**Review by deepthikannan — COMMENTED** [review]
image
Tried multiple times to test the unit test cases, but ended up with failed error.

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture1619

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
