### PR TITLE
Kurtis_fix_new_timer_issues

### PR DESCRIPTION
**Pull request by KurtisIvey**
<h1 align="center"> Kurt's Awesome timer fix </h1>

<h2>Description:</h2>
<em><strong>Implementation of new timer. </strong></em>Fix Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase') when submitting tangible time and optimize other .toLowerCase() instances
## Related PRS (if any):
This frontend PR is related to the <a href="https://github.com/OneCommunityGlobal/HGNRest/pull/435
">#435 backend PR</a>.

…

## Main changes explained:
- Implementation of new timer
- fix Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase') when submitting tangible time
- optimize other instances of .toLowerCase 
- fix timer auto-restarting after submitting tangible time entry
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any role of user
4. start time and stop it to submit a tangible time entry
5. verify functionality and that no errors are occuring besides the memory leak(still trying to track it down, any help is appreciated) 

## Screenshots or videos of changes:
error in console that I fixed:
image

timer autorestart fixed:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/a02511bd-6322-4cd6-8b74-c93660c0edb7

## Note:
<em><strong>Issues that are still present:</strong></em>
Memory leak after submitting a time entry

### CODE REVIEW

**Review by tdkent — APPROVED** [review]
Local tests confirm that submitting a tangible time report via the timer function correctly logs the time entry to **Current Week Timelog** without incurring a `toLowerCase()` error.

I did encounter two issues potentially unrelated to this PR:

1.  As already noted in the PR description, once the time log is submitted, the timer automatically resets and begins counting down again.
2. The following error was logged in the console on submission of the time log form:

Screenshot 2023-07-05 at 2 54 29 PM

Testing video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/8e973ca2-228a-42c9-b1f5-d5160206a26e

**Review by BaileyM96 — DISMISSED** [review]
Hello Kurtis!

I tested the recent changes and I can confirm that the .toLowerCase issue has been resolved and did not appear in my dev logs. 

## Issues

1. First error I received was a React state error on index.js 1 after submitting the tangible time.
2. Last issue was the note you attached to the PR which was the timer reseting after logging the time.

## Screenshot

Screen Shot 2023-07-05 at 4 27 05 PM

## Video

[toLowerCase() undefined.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/fb7b5339-7658-4276-a55f-c6e7713b1362)

**Comment by beblicarl** [comment]
1. The toLowerCase() error has been resolved however I encountered other issues

### ISSUES

1. I encountered a React state error.
2.  The timer resets after logging tangible time
3.  An error in the console about throwing inside of an async function without a catch block

### SCREENSHOT AND VIDEO

[issue #974.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/d08ce18f-6702-4622-a8f1-21ac48a9ea1f)

error-logs

issue #974

**Review by shiva2096 — APPROVED** [review]
Hello Kurtis,

Changes works as expected. Great work !
- fix Uncaught (in promise) TypeError: No error was logged in the console 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/92bf21cc-171a-44c1-b650-879534581e77

I got this warning message after submitting tangible time:

Screenshot 2023-07-06 at 5 55 38 PM

**Review by igorrochadasilva — APPROVED** [review]
Hi @KurtisIvey! 
I hope you are well 😃

The Pr works well. The toLowerCase issue has been resolved and did not appear in my dev logs.

review-974_2023-07-06_5

The code looks like well 🚀

**Comment by ramyaram2092** [comment]
The PR behaves exactly as @KurtisIvey 's description .  
I am new to the project . Is the  reset of the timer and the error we  see in console  has spawned because of the the Lowecase() fix or was it already present? 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/aee97011-d23a-457f-b4b7-901903c2500a

**Review by ramyaram2092 — COMMENTED** [review]
The system behaves exactly as  given in the description .
Hello @KurtisIvey I am new to the project . Just trying to understand Is the reset of the timer and the error we see in console has spawned because of the the lowecase() fix or was it already present?

If this PR has indeed caused this  isn't it better to merge the changes after fixing the issue we see now 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/cb3e82d0-8749-4610-85c4-bae54a70ad17

**Comment by luisarevalo21** [comment]
Hello KurtisIvey,

Tested for toLowerCase() giving an undefinded error. 
Upon running the application. I can confirm the error is gone. 

However, I do see a "React cannot perform update on an unmounted component" which can lead to a memory leak. As others have pointed out. 
Timer does reset and restarts after submission. 

Great job fixing the undefined error.

Screenshot 2023-07-06 at 7 54 18 PM

**Review by AaronPersaud — APPROVED** [review]
Hi Kurtis, I've tested it and can confirm the `.toLowerCase()` error is gone.

<b>Logging Tangible Time Entry</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/2be036d9-9c45-48fb-8de2-9a2f9bb3092c

I also encountered the aforementioned errors: the memory leak and timer restarting upon entry submission

**Review by luisarevalo21 — APPROVED** [review]

**Comment by AnishPandita** [comment]
Hi @KurtisIvey the PR looks great. The mentioned error was resolved.
Screenshot 2023-07-06 at 11 05 57 PM

**Comment by KurtisIvey** [comment]
> The system behaves exactly as given in the description . Hello @KurtisIvey I am new to the project . Just trying to understand Is the reset of the timer and the error we see in console has spawned because of the the lowecase() fix or was it already present?
> 
> If this PR has indeed caused this isn't it better to merge the changes after fixing the issue we see now https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/cb3e82d0-8749-4610-85c4-bae54a70ad17

So this is the new timer that is going to eventually be implemented if all the bugs can be worked out. The changes here stem off of #pr430 & #pr954. The error you're seeing is a memory leak that a bunch of people are currently trying to track down as it seems to be the only bug left. The .toLowerCase() issue was a separate error that was present in the front end of pr #954 that was fixed through this pull request.

I'll have a new commit going out later today that resolves the timer reset issue upon submitting tangible time entry. 

Thank you for taking the time to review this

**Comment by KurtisIvey** [comment]
> 1. The toLowerCase() error has been resolved however I encountered other issues
> 
> ### ISSUES
> 1. I encountered a React state error.
> 2. The timer resets after logging tangible time
> 3. An error in the console about throwing inside of an async function without a catch block
> 
> ### SCREENSHOT AND VIDEO
>  issue.974.webm 
> error-logs
> 
> issue #974

interesting error. I and a lot of others haven't been able to replicate that issue. We'll have to look into that one as it could possibly be contributing to the memory leak. Thanks for posting a picture of the error so we can look into it.

**Review by mahamakhan — COMMENTED** [review]
I am getting this error after checking.
image

**Comment by Jiangwei-shi** [comment]
Hi Kurtis, the work looks as indeed! Just like others say the .toLowerCase() error is fixed. And memory leaks still exist.
image

**Review by ramyaram2092 — COMMENTED** [review]
I am assuming the last commit / review request was for the timer fix so I went ahead and retested the latest branch @KurtisIvey . I still see the  timer reset issue . If you haven't pushed the changes then the following observation can be discarded

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/42ccc04a-ae19-46d5-8849-b530e30c0456

**Review by luisarevalo21 — APPROVED** [review]

**Pull request closed without merging**
