### PR TITLE
ZiyuAdd Unit Test for Warnings

### PR DESCRIPTION
**Pull request by chu-ziyu**
# Description
Unit Test for Warnings.jsx

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- Updated Warnings.test.js to correctly mock asynchronous actions.
- Used mockResolvedValue and mockRejectedValue to simulate both success and failure scenarios for asynchronous operations.
- Ensured that error messages are displayed correctly in the component during testing.

## How to test:
1. Check into the current branch.
2. Run npm install to ensure all dependencies are installed.
3. Execute npm test Warnings.test.js.
4. Verify that all test cases pass without errors.

## Screenshots or videos of changes:
Screenshot 2024-12-04 at 11 39 26 PM

### CODE REVIEW

**Review by anirudhsk2107 — APPROVED** [review]
All tests have passed 
Screenshot 2024-12-05 115556

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (255)

**Comment by pallavithorat** [comment]
All test cases have passed!
Screenshot 2024-12-05 at 3 56 31 PM

**Comment by beblicarl** [comment]
All tests passed successfully and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Review by NazaninHashemian — COMMENTED** [review]
Observations
Warnings in Logs:

The following warnings were observed:
React Error: jsxWithValidation from WarningIcon (line 77).
act-compat error related to react-testing-library.
These warnings indicate potential issues in WarningIcon and its usage of React's JSX validation.

Testing Results:

All test cases in Warnings.test.js passed successfully:
Non-admin users render correctly without warnings.
Admin users see the tracking button.
The warning display toggles as expected.
Code Areas Highlighted by Logs:

WarningIcon Component:
Line 77 might include improper prop usage or missing validation.
This could be a result of invalid or undefined props being passed.

**Pull request merged**
