### PR TITLE
Shihao weekly summary content tooltip unit test

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Unite test for `WeeklySummaryContentTooltip.jsx`

## Main changes explained:
- Add test id and unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test WeeklySummaryContentTooltip.test.js` to run the test
4. Verify that all 5 tests have passed

## Screenshots or videos of changes:
Screenshot 2023-11-17 at 14 32 43

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great Work!

PR 1556

**Comment by wanglu1207** [comment]
Hi @sxiong5 , good job! All the cases passed.

**Review by pika-chu11 — APPROVED** [review]
Hi @sxiong5 , the test passed! Great job!
PR 1556

**Review by vikrambadhan — APPROVED** [review]
Good Job! All the the test cases passed!

Week12 - PR7

**Review by Hemsharavanan — APPROVED** [review]
- Your tests cover essential functionalities such as rendering without errors and icon-click interactions for toggling tooltips.
- Tests are straightforward, focusing on specific functionalities related to tooltip rendering and interaction.
- Nice work!
PR #1556 Shihao weekly summary content tooltip unit test

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
