### PR TITLE
yihan create way to see 6 months & yearly anniversaries

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
This frontend PR is related to the [#627](https://github.com/OneCommunityGlobal/HGNRest/pull/627) backend PR.

## Main changes explained:
- Update file leaderBoardData.js, URL.js and LeaderBoard.container.jsx for including a function of posting trophy data.
- Update file leaderBoard.jsx and FormattedReport.jsx for adding trophy icon to leaderboard and summary page.
- Create file anniversaryPermissions.js for date calculation functions.

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. log as owner/admin/core/mentor/manager user
4. go to leaderboard, verify if you can see a trophy icon with 6M, 1Y, ..., 10Y under a user's name whose anniversary is in the past week. 
a. For example, today is Nov 29, so the trophy icon is showed if the create date of the user if between Nov 23 and Nov 29.
5. Click on the trophy icon-> Confirm botton, verify if the trophy icon then turns yellow. (This process may take some time)
6. Go to Reports → Weekly Summaries Reports Page, verify if you can see the trophy icon of the user whose create date is in this week. 
a. For example, today's date is Nov 29, so under "This week" tab, the trophy icon is showed if create date is between Nov 26 and Dec 2, under "Last Week" tab, the icon is showed if create date is between Nov 19 and Nov 25... 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/f7e23e2d-85c5-4f4c-9a90-a81bda60d89a

### CODE REVIEW

**Comment by ptrpengdev** [comment]
Hi @AriaYu927 , I am able to see the 6m trophy icon with the user BadaKim Volunteer under leaderboard and weekly report. Great work! Feature work as expected.


<br/>

**Review by pika-chu11 — COMMENTED** [review]
Hi @AriaYu927 , I have tested your PRs. You did a great job! Here is my testing:
I logged in as the Owner Account:

- I didn't see a trophy icon under any user's name on the leaderboard.
    - Since I was able to see the tropy icon on the leaderboad, I can't click on it and verify the tropy icon turning color.
- I do see a trophy icon under some user's names Under Reports -> Weekly Summaries Reports. (I only see two, maybe miss some when I scroll down fast).

Please watch the video for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/78c42157-7a3b-463c-9409-b902165e6527

**Comment by keyunhuangg** [comment]
Hello, I checkout your branch. I logged in as admin and follow a gray 6m trophy icon. And verified that his date is correct. But  I don't see the same trophy under "weekly reports."
Screenshot 2023-12-12 at 11 20 39 AM
Screenshot 2023-12-12 at 11 23 08 AM
Screenshot 2023-12-12 at 11 20 56 AM

**Comment by AriaYu927** [comment]
> Hi @AriaYu927 , I have tested your PRs. You did a great job! Here is my testing: I logged in as the Owner Account:
> 
> * I didn't see a trophy icon under any user's name on the leaderboard.
>   
>   * Since I was able to see the tropy icon on the leaderboad, I can't click on it and verify the tropy icon turning color.
> * I do see a trophy icon under some user's names Under Reports -> Weekly Summaries Reports. (I only see two, maybe miss some when I scroll down fast).
> 
> Please watch the video for more details:
> 
>  PR.1603.+.627.mp4

Thanks for your test! I've fixed this issue and now trophy icon are showed on leaderboard, please check.
image
For Aishwarya's icon, it is in yellow color because I clicked it.
Screenshot 2023-12-12 at 12 07 46

**Comment by AriaYu927** [comment]
> Hello, I checkout your branch. I logged in as admin and follow a gray 6m trophy icon. And verified that his date is correct. But I don't see the same trophy under "weekly reports." Screenshot 2023-12-12 at 11 20 39 AM Screenshot 2023-12-12 at 11 23 08 AM Screenshot 2023-12-12 at 11 20 56 AM

Thank you the testing! Please make sure that you checked the icon under the correct tab. The 6M trophy icon of Maham Volunteer is supposed to be showed under "This Week" (From Dec-10-23 to Dec-16-23) because the created date is Jun-10-23:
Screenshot 2023-12-12 at 12 12 15

And it wouldn't display under other tab (Last Week/Week Before Last/...):
Screenshot 2023-12-12 at 12 15 57

**Review by keyunhuangg — DISMISSED** [review]
This is a followup regrading my last comment.

What I have tested:
Logged in as admin and clicked on a gray 6m trophy icon under the leaderboard. A message popped up and asked if i want to follow it. I verified that his start date until now is 6 months. Under weekly summaries report -> this week saw that the 6m trophy icon is also present.

<the other 3 pics are in my other comment>
Screenshot 2023-12-12 at 4 32 05 PM

**Review by pika-chu11 — COMMENTED** [review]
Hi @AriaYu927 , thank you for the update and your effort!
I have re-tested the PR based on the fix.
This is a followup comment: 

1. I did fetch and merge the newest version of the both [FrontEnd#1603](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603) and [BackEnd#627](https://github.com/OneCommunityGlobal/HGNRest/pull/627)repository.

2. I have tried to clear the site data, and log in again. But I still got the same issue.

I logged in as the Admin Account: 

- Under the leaderboard
   - I was still unable to see the tropy icon of `Maham Volunteer` user or any other ones. (Probably I didn't something wrong or miss a step, but I put a video below which it includes my walkthrough of how I test. Please let me know if I did something wrong, thank you XD)

- Under the Reports -> Weekly Summaries Reports.
    -  I was able to see the grey tropy icon of `Maham Volunteer` user.

Please watch the video for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/3f956406-067d-4e44-b70d-b2cf1cb203ae

**Comment by AriaYu927** [comment]
@pika-chu11 , thanks for providing the video! 
It looks like you missed a command before `npm start` on backend. Please try to run `npm run build` then `npm start`, I think this may solve the problem.

**Review by pika-chu11 — DISMISSED** [review]
Hey @AriaYu927 , thank you so much for the instruction! XD. You did a great job!
I was able to see the tropy icon under both the _leaderboad_ and _Weekly Summary Reports_.

Here is the re-test based on the instruction:

I logged in as the Admin Account:

Under the leaderboard

- I was able to see the tropy icons of all users who has one.
- I can also turn the color of the tropy icon into yellow by clicked on it and confirmed the popup.

Under the Reports -> Weekly Summaries Reports.

- I was able to see the grey tropy icon besides the same user I see under the leaderboad.

Please watch the video for more detail:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/a5eb1ff9-fe36-4720-ba28-73842484e34d

**Review by ilyaflaks — DISMISSED** [review]
I have reviewed this PR and the 6mo + 1yr anniversaries work. 
Here's a profile with a start date of 6/20/23 (6 months ago today - 12/20/23)
PR1603+PR627-6mo-works

Here is one with a start date of 12/20/22 (1 year ago today):
PR1603+PR627-1yr-works

Same users on This Week's Summary:
PR1603+PR627-weekly-1

PR1603+PR627-weekly-2

Great job!

**Review by Alforoan — CHANGES_REQUESTED** [review]
I was able to see the trophy and by confirming it changed the color to yellow, but I could not seem to see the badge for when a user is created less than a week ago.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/a339dad9-7804-4e7e-aa4a-9d9484048068

**Comment by AriaYu927** [comment]
> I was able to see the trophy and by confirming it changed the color to yellow, but I could not seem to see the badge for when a user is created less than a week ago.
> 
>  pr.review.1603.mp4

Thank you for testing!
Sorry, I don't quite get the point. I rechecked my code and confirmed it doesn't affect the badge part on profile page. And I also checked the user's badge data in database. It shows this user doesn't have badge collection in db. Could you please clarify the issue with more details?
image

**Comment by mianmiantea2019** [comment]
HI @AriaYu927 , 

I logged in as an admin and began following a user who had earned a 6-month trophy under the "Weekly Summaries Report." Then, I adjusted the system time to a point six months later, and the trophy appeared for the user as expected. This function is working as expected. However,  I'm unable to see any users on the leaderboard. Is there anything else I might have missed in my testing? 

- This month
 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/6cead462-6d95-4f1b-bd45-d10c0ad74253

- 6 months later
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/c7c1d0f0-bb8f-47f9-ba99-2851c9b69f85

**Comment by Haoxiang310** [comment]
Hi, I logged in through Admin and was able to see the trophy under weekly summary reports. I also checked the date and it was correct.
frontend2-PR#1603

**Comment by DragonSlayer2401** [comment]
So I tested this PR and I did not see any trophies on the leaderboard. However like others have mentioned I did see trophies on the weekly summaries page. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/29b614e4-393c-4bda-b1b5-4f627aebba60

**Review by pshereen — CHANGES_REQUESTED** [review]
I tested this PR, and I did not see any trophies on the leaderboard. But I did see trophies on the weekly summaries page. 

For example:
1. For the user, Aaron Persaud a Month trophy is visible in the weekly summary report of Last week, but the trophy is not visible in the Leaderboard for the same user. 

2. For the user, Anish SuperOwner 6Month trophy is visible in This Week of weekly Summary report, but the trophy is not visible in Leaderboard for same user.

Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/e0c8b9db-0419-4fed-b760-756ab1e65499

**Comment by yuhuimin1996** [comment]
Hi Yihan,
I've tested this FE pr along with the BE pr #627. I didn't see any trophies on the leaderboard. 

Snipaste_2024-01-15_19-13-32
 But as other reviewers mentioned above, I did see trophies on the weekly summaries page. Please see the screenshots for more details:
 
Snipaste_2024-01-15_19-13-00

**Review by Sophie-lei — CHANGES_REQUESTED** [review]
Hey, I just reviewed this PR. I found that the trophy icon has successfully shown for people who created their personal accounts for 6M in the weekly summary report. However, I can not find any people listed under the Leaderboard. like the pic below. I think it is the problem of the backend.
Screenshot 2024-01-15 at 9 27 54 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/18cbb5ec-d877-497d-a5f3-ebaeb4574748

**Review by Renanluizssx — CHANGES_REQUESTED** [review]
hi @AriaYu927, i tested your application, and when i navigated to leaderboard and the anish superOwner, i didn't see the trophy, but when i navigated to weekly summaries report, the trophy appears.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/6357b737-9ae6-481a-b935-356a899da5d9

**Review by X1aoZhang99 — CHANGES_REQUESTED** [review]
Upon reviewing this PR, I have observed that the trophy icon is correctly displaying for users named Alex Wang who achieved 1yr in the weekly summary report. However, I have noticed that there are no users listed on the Leaderboard, as shown in the image below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/43c4cbe7-c6bc-40e7-9cba-889e8446d994

**Review by 666saofeng — CHANGES_REQUESTED** [review]
I was able to see the trophy in Weekly Summaries Report. However, I've identified a significant issue: the Leaderboard is not displaying any users who have received trophies.
image
image
image

**Review by 666saofeng — COMMENTED** [review]
I left comments under PR1603https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1603#pullrequestreview-1834189005

**Review by KevHnh — CHANGES_REQUESTED** [review]
Trophies only function properly in "weeklysummariesreport" page.  I believe it might be a backend issue [PR#627](https://github.com/OneCommunityGlobal/HGNRest/pull/627). I provided a screenshot of an error message that occurs when loading into the dashboard where the leaderboard resides.

Weekly Summaries Report Page:
image

Leaderboard:
image

Backend Console Errors Message:
image

**Comment by xmyoot** [comment]
I reviewed the PR and I was not able to see the trophies on either the dashboard leaderboard component or the weekly summaries pages, please reference video: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15240538/fe89f34f-cf7a-41cd-b0c2-c075c0d68b48

**Comment by galgalinidhi** [comment]
Hi @AriaYu927, I get an error when I try running the backend PR#627. Please refer to my comment here-https://github.com/OneCommunityGlobal/HGNRest/pull/627

As for the frontend, I logged in as Admin but the leaderboard and the Team Member Tasks do not load.

**Review by yvonnep165 — COMMENTED** [review]
Hi @AriaYu927 ,
I reviewed the PR and I was not able to see the trophies on either the dashboard leaderboard component or the weekly summaries pages as below. I have leave the comment and screenshot including the error in the PR 627 at the Backend. 
Screenshot 2024-01-27 at 4 12 07 PM

**Review by Pandani07 — COMMENTED** [review]
Hi, I followed your testing steps and I could not see the leaderboard (it did not load)

I have attached a file for your reference
Screenshot 2024-01-30 at 4 42 26 PM

**Review by peterson337 — CHANGES_REQUESTED** [review]
I encountered an error when attempting to run the backend. 

a

As for the frontend, I logged in as Admin but the leaderboard and the Team Member Tasks do not load.

a

**Review by SRamen1999 — CHANGES_REQUESTED** [review]
when using the backend for this PR I got this error message.

Screen Shot 2024-02-08 at 6 31 50 PM

When using the Frontend I logged in as Admin but the leaderboard and the Team Member Tasks do not load.

Screen Shot 2024-02-08 at 5 29 20 PM

**Review by XiaohanMeng — CHANGES_REQUESTED** [review]
Hi @AriaYu927, I tested with Admin account and found that there are no members in Leaderboard. In the backend terminal, there are several errors jumping out. Please see them in the video and screenshot.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/e553450a-a4b0-4b52-9715-9030dbd18d9f

#1603_bug

**Review by mohabbasd — CHANGES_REQUESTED** [review]
Hello, I tested your PR and I couldn't find any user on the leaderboard with a trophy but I found one on the weekly summary reports. And when I went back to check with the same name for that user I still could not see it.
Screenshot 2024-02-15 at 11 22 39 PM
Screenshot 2024-02-15 at 11 21 57 PM

**Review by brandta-1 — CHANGES_REQUESTED** [review]
# Review
Upon login, the dashboard is unable to retrieve leaderboard information, due the same MongoDB error others have cited. For reference, please see my [back end review](https://github.com/OneCommunityGlobal/HGNRest/pull/627#pullrequestreview-1887063047)

**Comment by nnamdixobi** [comment]
I tested like specified in your instructions and I was not able to view leaderboard information

**Pull request closed without merging**
