### PR TITLE
Kaushik-Cheng-Yun_WBS.jsx_Unit_test

### PR DESCRIPTION
**Pull request by DavidC0126**
# Description
Implemented Unit test functions include render WBS and check modal display

## Related PRS (if any):
NA

## Main changes explained:
- Create test file WBS.test.jsx for testing WBS component

## How to test:
1. check into current branch
2. do `npm install` and `npm test src/components/Projects/WBS/wbs.test.jsx` to run this PR locally

## Screenshots or videos of changes:
Screenshot 2024-04-18 at 12 27 44 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by alla0810 — CHANGES_REQUESTED** [review]
Hi, [DavidC0126](https://github.com/DavidC0126),
I'm gonna request change for this PR because,
even if this PR passes the intended test cases, it also generates console errors complaining like below.
I've looked over the source code to figure out why this console error is generated, and I think the table DOMs like `<table>, <tr>, <th>` are mixed up, so it keeps complaining about the violations of table DOM rules.
console error also complains about ' `<tr>` cannot appear as a child of `<div>`', which seems because in WBSItem.jsx, `{props.index}` is encircled by `<div></div>`.
This can be neglected because the testcases are passing anyway, but we're building a large chunk of source code packages, so I think keeping the source code tidy is important as the complexity of the software is getting higher.
Please see the screenshots below.

image

image

**Comment by iTvX** [comment]
Tests pass, but it generate many error. Please fix it.

image
image

**Review by aaryaneil — CHANGES_REQUESTED** [review]
Tested your PR and the test cases passed but generated a lot of errors.
Screenshot 2024-04-19 at 10 14 36 PM
Screenshot 2024-04-19 at 10 16 55 PM

**Review by linkhanthtel — COMMENTED** [review]
All tests passed but it showed error messages.

Screenshot 2024-04-20 at 11 23 26 AM
Screenshot 2024-04-20 at 11 23 49 AM

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and it passed all the test cases without any errors. Please refer the screenshot attached.

PR 2169

**Review by KaushikMreddy — COMMENTED** [review]
Hi @DavidC0126,

I tested your changes and got no errors, all the test cases have passed. Your code looks concise and simple enough to understand

image

**Review by jayyy-s — COMMENTED** [review]
I ran your unit tests and all of them pass. They also thoroughly check all the possible props for a WBSItem, so good job on that front as well.
tests pass

One edge case I would consider adding as a test is one where the 'deleteWbs' permission is not present. There is conditionally rendered HTML in WBSItem.jsx dependent on this permission, so it would be good to check for it.

**Review by MinSun0814 — DISMISSED** [review]
Hello, I ran the tests and everything passed.
image

**Review by dkt6 — APPROVED** [review]
All test cases are working as expected.
Thank you for the great work!

**Review by nathcarnevalli — APPROVED** [review]
Nice work :)

Screenshot 2024-05-15 114037

**Review by Sandhya1236 — DISMISSED** [review]
Hi, all test cases have successfully passed, and it appears that the previous errors have been resolved. I've attached a screenshot of my testing environment.
image

**Comment by ZhangPeizhou** [comment]
Passed all the tests
PR#2169

**Review by Kavil-Jain-514 — DISMISSED** [review]
All test cases passed.
image

**Review by JatinAgrawal94 — DISMISSED** [review]
All tests passed successfully.
Great work!
Also please mention in description that one needs to checkout development branch of backend to test this, or else they would run into errors.

**Review by Wenboooooo — APPROVED** [review]
All tests have passed, it looks good to me.

**Review by deepthikannan — DISMISSED** [review]
image
All test cases passed.

**Comment by akshit0211** [comment]
All test cases passed. While running the npm test command make sure your development backend is running. Good work!

All test cases passed

**Review by akshit0211 — DISMISSED** [review]

**Review by shradac — DISMISSED** [review]
All tests passed. The tests cover all specified scenarios. Good Work!

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and all test cases passed successfully!!!

PR-2169

**Comment by KaushikMreddy** [comment]
The table errors have been fixed in the right place. The changed code does not affect the visual of the wbsItems on the wbs table.
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
