### PR TITLE
Nicolle fix team weekly summaries

### PR DESCRIPTION
**Pull request by nicollext**
# Description
image

## Mainly changes explained:
The button has been changed as requested, along with an update to the text message.

 The code has been refactored to prevent errors, and the user interface has been enhanced to provide a smoother and more intuitive experience.
…

## How to test:
check into current branch
do `npm install` and `...` to run this PR locally
log as any user
go to dashboard→ View Profile
click on the "Team Weekly Summaries" button, select a profile and verify if the summaries are being displayed correctly.  

## Screenshots or videos of changes:

**Before**

https://user-images.githubusercontent.com/101591708/231541071-98d1ee54-741b-484f-910e-bbe10bbc5f4d.MP4

...
**After**
...

https://user-images.githubusercontent.com/101591708/231541661-f144e918-92d2-41d1-9488-e8accb8713c2.MP4

### CODE REVIEW

**Review by ypan710 — COMMENTED** [review]
Hi @nicollext, for developers who have submitted their weekly summary for a certain week, you can view that week's summary for that developer (e.g. Goku Owner for 4/9 to 4/15), but when I checked for another developer (0Nicolle ADM), the weekly summary did not show any message for weeks before 4/9. Is this an issue or is it because the account (0Nicolle ADM) hadn't been created before 4/9?

Screen Shot 2023-04-12 at 12 24 45 PM

Screen Shot 2023-04-12 at 12 24 36 PM

Screen Shot 2023-04-12 at 12 37 42 PM

**Comment by AnishPandita** [comment]
hi @nicollext I tested your PR and it seems to work nicely. It looks great visually as well. Good job.

https://user-images.githubusercontent.com/111321945/231598895-b581b760-f964-4bdd-a4c4-5fe7a78d6456.mov

**Review by LucileTech — APPROVED** [review]
Hi @nicollext! I tested your PR and it works perfectly: 

When I choose the weekly summary to view, the “Team Weekly Summaries” changes to say “Hide Weekly Summaries”

When someone hasn’t submitted a summary for the current week the text is saying “<Name> did not submit a summary yet for this week.”

Last week and weeks before options don’t have an extra “a submit”


https://user-images.githubusercontent.com/111132148/231605906-7b91daed-bc9c-4fd9-8eba-5a9868930049.mp4

**Review by ToobaJamal — APPROVED** [review]
Hi Nicolle, I Just tested your changes and it's working fine on my end. Good job!

**Comment by nicollext** [comment]
> Hi @nicollext, for developers who have submitted their weekly summary for a certain week, you can view that week's summary for that developer (e.g. Goku Owner for 4/9 to 4/15), but when I checked for another developer (0Nicolle ADM), the weekly summary did not show any message for weeks before 4/9. Is this an issue or is it because the account (0Nicolle ADM) hadn't been created before 4/9?

Hey @ypan710! Yes, I decided to show only the summaries for the time after the user was created, as it may not be relevant to show summaries for weeks before a user's account existed.

**Review by Elisaudo — COMMENTED** [review]
I Nicolle, I tested PR#766 and saw that you fixed the button as requested and the enhanced of user interface was great.
My only question is that in PR there are 3 sentences about the weeks, that were changed. “current week”, “last week” and  "week before”. does not user want maintain them?

[PR#766 video fix team weekly summaries.webm](https://user-images.githubusercontent.com/64317219/232136705-e832fa75-db4f-4454-bf1d-75f595744a6b.webm)

**Review by abdel-lall — APPROVED** [review]
works perfectly. nice job!

PR766

**Comment by AriaYu927** [comment]
Hi @nicollext , I've tested this PR and it works perfect, thank you!
PR766

**Review by vitorsaa2k — CHANGES_REQUESTED** [review]
Working as intended. But I suggest to instead of the initial label of the button being "Team Weekly Summaries" it should be "Show Team Weekly Summaries" for better consistency.

**Comment by one-community** [comment]
I agree with "Show Team Weekly Summaries" - please make that change and I'll merge this one.

**Review by vitorsaa2k — APPROVED** [review]

**Pull request merged**
