### PR TITLE
Aaryaneil - Unit tests for LoginPrivilegest

### PR DESCRIPTION
**Pull request by aaryaneil**
# Description
Added unit tests for the LoginPrivileges Component.

## Main changes explained:
Added test cases to check for the following:

1. Test Render Radio Buttons
2. Test Selected Input Checked
3. Test Handle Input Change Called
4. Test Default Selected Input
5. Test Radio Buttons Interact
6. Test No Role Selected
7. Test Multiple Renders

## How to test:
1. check into current branch
2. do `npm install` and `npm test LoginPrivileges.test.js`

## Screenshots or videos of changes:
Screenshot 2024-07-28 at 12 17 08 AM

### CODE REVIEW

**Review by Chetan0606 — APPROVED** [review]
Reviewed as per the provided instructions and everything looks good.
image

**Comment by iTvX** [comment]
Good Job


LoginPrivileges Component
  ✓ test_render_radio_buttons (23 ms)
  ✓ test_selected_input_checked (18 ms)
  ✓ test_handle_input_change_called (6 ms)
  ✓ test_default_selected_input (2 ms)
  ✓ test_radio_buttons_interact (3 ms)
  ✓ test_no_role_selected (3 ms)
  ✓ test_multiple_renders (6 ms)

Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshots:   0 total

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (156)

**Review by vijay10pk — APPROVED** [review]
All the test cases are passed.
image

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by gowthamdongari — APPROVED** [review]
All test cases working Fine
image

**Review by JatinAgrawal94 — APPROVED** [review]
All test cases passed. Good Work.
Screenshot 2024-08-01 at 10 32 37 PM

**Comment by jayyy-s** [comment]
Tests look good, good job.
image

**Pull request closed without merging**
