### PR TITLE
Peterson_fixed_the_create_team_bug_on_the_profile_page_and_Teams_tab

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request has been opened to fix the bugs with the create team feature on the profile page and Teams tab.

## Related PRS (if any):
None.

## Main changes explained:
The component AddTeamPopup has been modified to fix the bugs.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log in as an administrator or owner.
5. Go to view profile→ Teams tab
6. Your user should be added to a team after it has been created.
7. After clicking the confirm button with a team that doesn't exist, two buttons should be displayed: one to create a team and the other to cancel the create team mode.

## Screenshots or videos of changes:
Peterson_fixed_the_create_team_bug_on_the_profile_page_and_Teams_tab

## Note:
None.

### CODE REVIEW

**Comment by AJAYINAVOLU** [comment]
Changes are working as expected.

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (180)

**Review by manikittu810 — APPROVED** [review]
Hello @peterson337 
The PR is working as mentioned.

Screenshot 2024-08-22 at 10 14 11 AM

Thank you.

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and i am able to add team , everything working as expected. 
Screenshot 2024-08-22 162058
Screenshot 2024-08-22 162115

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.

https://github.com/user-attachments/assets/4775281f-72c5-4655-8c67-99edca67bee6

**Review by Pranay-ai — APPROVED** [review]
Hey @peterson337  The Pr is Working as Expected
image
Thank You

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
