### PR TITLE
Peterson - Fix the issue causing the user profile page to display a white screen upon  access

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request has been opened to fix the bug that causes the screen to appear white and multiple errors to appear in the browser console.

## Related PRS (if any):
none
…

## Main changes explained:
The user profile  component has been modified to fix the bug.
…

## How to test:
check into current branch
do npm install and ... to run this PR locally
Log in with any account that hasn't saved the start date:
photo 2

go to view profile
The user profile page should render all user information, and the errors shown in the image below shouldn't be displayed in the browser console:
photo

## Screenshots or videos of changes:
Before my fix:
a

After my fix: 
b

## Note:
none

### CODE REVIEW

**Comment by Ramaruva** [comment]
Hi @peterson337  when I wanted to test these changes I am unable to create an user without an start date
can you please provide an user profile without an start date to test as I was unable to find an user without an user profile

**Review by Ramaruva — APPROVED** [review]
Since I was unable to find an account with invalid date so I have purposely given null to startdate for an account and even after given null the profile page is loading without any errors

**Review by Ramaruva — DISMISSED** [review]
Since I was unable to find an account with invalid date so I have purposely given null to startdate for an account and even after given null the profile page is loading without any errors
image

**Comment by beblicarl** [comment]
There were no errors in the console after following the instructions

image

**Review by beblicarl — DISMISSED** [review]

**Review by nathcarnevalli — APPROVED** [review]
Worked as expected :)

Screenshot 2024-05-10 230430

**Comment by nishithaShetty** [comment]
Hi @peterson337 I could not find an account having an empty start date and there are several validations in FE, backend and DB which does not allow us to add a null date value. I tested the change and it works as expected, the page loads correctly with just 2 warnings in the console. Could not test it with the empty date condition.
image
warning1

**Review by hbodgal — CHANGES_REQUESTED** [review]
I can still see the white screen. I am not sure about what "Log in with any account that hasn't saved the start date" means.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/e75768ce-bb20-4b12-9b6e-979ffb3dda33

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected.
Great work!

**Review by CloudyZ524 — CHANGES_REQUESTED** [review]
Hi Peterson, 

I've tested your pull request to set a start date for my account. The new date can be saved successfully but the console shows the error "The specified value "2024-06-05T07:00:00.000Z" does not conform to the required format, "yyyy-MM-dd"" as show in the screenshot. Please take a look at it and address to the potential issues. 

Screenshot 2024-06-06 at 12 42 28

**Review by CloudyZ524 — APPROVED** [review]

**Review by TXMO-dev — APPROVED** [review]
Th issue has been resolved successfully! Approved!

**Review by Sudershhh — CHANGES_REQUESTED** [review]
I am not able to recreate this PR as I am not able to edit the start date for my accounts. Do you have a user profile for this scenario that I can use to test?

Also, I tried putting in the user profile id in one of the earlier comments and tested that, it gave me a white screen and errors were logged to the console.

PR 2233

**Review by hbodgal — DISMISSED** [review]

**Review by AnujVakil — DISMISSED** [review]
I have tested this PR and working as expected.
PR #2233_1

**Review by SrikanthChowdary495 — COMMENTED** [review]
I have tested this PR. But I am facing errors while complaining. I have followed all the steps given. I am attaching the image.

**Review by adityasure9 — APPROVED** [review]
I have tested the PR and found that the issue causing the user profile page to display a white screen has been resolved successfully. The profile page now loads all user information without errors, and no issues were encountered during testing. Great work on addressing this bug.

**Review by oliviahyw — CHANGES_REQUESTED** [review]
Hi @peterson337 I have tested this PR and I got this error. Please check the attached screenshot.
PR2233

**Review by oliviahyw — APPROVED** [review]
Hi @peterson337 I have tested the latest code and the error has been resolved!
PR2233

**Comment by FayeLV** [comment]
Hi,
I just tested the function, and it works well. There's no white page, and the data has been successfully updated to the new values.
Snipaste_2024-09-05_18-00-22
Snipaste_2024-09-05_18-03-26
Snipaste_2024-09-05_18-03-34
Snipaste_2024-09-05_18-05-14

**Review by vedantg24 — COMMENTED** [review]
I couldn’t find an account having an empty start date. I tried to update a user to have a null start date, but backend validations restrict that. I tested the change with a user having a start date, and the changes are working as expected. The user profile page renders all user information, and there are no errors in the browser console. Could not test it with the empty date condition.

Screenshot 2024-09-10

**Review by SFA23SCM35V — CHANGES_REQUESTED** [review]
I’m unable to recreate this PR because I cannot edit the start date for my accounts. Could you provide a user profile suited for this scenario to assist with testing?
Screenshot (21)

**Review by nevatiarishabh — DISMISSED** [review]
Attempting to set a user’s start date to null was blocked by backend validation. I tested the update on a user with an existing start date, and it functioned correctly. The profile page displayed all the user details without any issues in the console.

Screenshot 2024-09-26 at 7 06 10 PM

**Review by neeharikakoniki — CHANGES_REQUESTED** [review]
I tested the update on a user who already had a start date, and it did not work as expected.

image

**Review by Muzammil603 — APPROVED** [review]
image
i can not see the way to change the empty start date

**Review by mrinalini-raghavendran19 — DISMISSED** [review]
Hello!

I don't quite understand how to create a profile with an empty start date, since the app doesn't allow me to. 

Additionally, there are checks and validations for checking date format while entering a start date on the app. 

But the PR works as expected, as I can load the user profile. If you can, please add additional details to the PR which tells how to create a profile with an invalid start date.

Screenshot 2024-10-02 at 11 37 47 AM

**Review by khushijain03 — DISMISSED** [review]
The attempt to set a user's start date to null was denied by backend validation.  I tested the PR with a user's start date, and the changes work as intended. The PR works as expected since the user profile page displays all user information.

Screenshot 2024-10-06 at 12 05 30 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
