### PR TITLE
Fix timelog

### PR DESCRIPTION
**Pull request by Programmingrelated1999**
PR for default Tabs. The tasks tab should be default if the user is admin/owner/mentor/manager. The tasks tab should also be default if the user is any other roles but have task assigned. 

First I check if the user role is any of the following "admin/owner/mentor/manager". Then I set the default to task tab.

For other roles, I create a function called doesUserHaveTaskWithWBS which goes through user's tasks and check if there are any task with wbs assigned. Then I set the default tab to tasks.

The two pictures show differences between volunteer with task and volunteer with no tasks when logging. 

volunteer no task

volunteer default tab

### CODE REVIEW

**Review by LeeSingChanYau — COMMENTED** [review]
Looks good. Just needs to pass the node test.

**Comment by one-community** [comment]
Following up on this, does it still need to be reviewed and integrated?

**Comment by Programmingrelated1999** [comment]
I am waiting for Aashish to review the PR. If everything goes correct, it should be ready!

**Comment by Programmingrelated1999** [comment]
One more thing, the Node.js CI fails here, I am working to resolve this and will give an update.

**Comment by one-community** [comment]
Ok, thank you. Please follow up with him by PM if you haven't already.

**Comment by Filipe-Oliv** [comment]
Is this PR still being reviewed?

**Comment by one-community** [comment]
This one needs to be taken over and wrapped up by someone else.

**Comment by Filipe-Oliv** [comment]
@one-community, @EvianTan give a help here, please. To see this happening "... differences between volunteer with task and volunteer without task when registering." I need to add a task in: USER PROFILE > PROJECTS > ADD TASK. But in the image below I am at the bottom of the page and the "ADD TASK" section is not showing up. Is there any other way to add a task?
Is this a bug?

**Comment by RafaelCastilhoCastro** [comment]
I tested the features and all worked as intended. The task tab is being called on front on the cases intended by the PR.

I tried to solve the file conflicts but I'm not sure how to proceed about the package.json file. It contains dozens of updates on libraries versions and their related integrity hashes. I'm not sure if I should update them or keep the old versions. I'm consulting the senior devs about this and will return to this PR asap.

**Comment by one-community** [comment]
Excellent, thank you

**Comment by tingedudu8** [comment]
I tested this PR and the feature it tried to implement works well so far.

https://user-images.githubusercontent.com/70128933/219540436-1b247562-b129-4bdc-9560-9f7509856987.mp4

**Comment by Filipe-Oliv** [comment]
Hi @RafaelCastilhoCastro 

It's working as intended. Thank you for your help.

[02-17-2023 (1).webm](https://user-images.githubusercontent.com/114119668/219647012-495cb566-ff0d-4fcd-a6d5-84f21d9836a9.webm)

**Comment by AnishPandita** [comment]
Hey, I tested this PR #535 and it seems to be working perfectly as required. The outcome is displayed correctly according to the user currently logged in.

https://user-images.githubusercontent.com/111321945/219821162-728bb2c3-7d2c-4ffa-8144-1a98b7809225.mov

**Comment by PrabhjotSembhi** [comment]
@one-community this one is old PR.  Contributer's last commit was in November. I think We can close this

**Comment by one-community** [comment]
No, it's a PR that needs to be finished and merged. He left the team without completing it. Rafael is taking on the task of finishing what's needed.

**Comment by RafaelCastilhoCastro** [comment]
Hi guys,
This PR should be disconsidered and dismissed. Its porpose was transfered to this PR[#686](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/686/files#diff-ac56c4d75df0c0cf3d8595e94ace5a462b16475aaff419fbf32d0ab175a3d140).

**Pull request closed without merging**
