### PR TITLE
olena copy of reverted pr1854 with fixed issues

### PR DESCRIPTION
**Pull request by olenadanykh**
# Description

## Related PRS (if any):
This PR is the copy of reverted PR 1854 and 1924
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1924
(https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1854) with corresponded change made in Lessons.css
-the only one change was made here to the file  Lessons.css:

The problem was in Dashboard with background color and font sizes:

dashboard-2

### CODE REVIEW

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Olena,

The font size and background color have now been corrected. Nice work! 

### Image
Screenshot 2024-02-05 at 16 15 25

**Review by 666saofeng — APPROVED** [review]
Hi, I tested with the admin account. The font size and background color have been adjusted. Good work!
image

**Review by ShengjieMao — DISMISSED** [review]
Hi, the layout now is good and the fonts are correct and same now. Great work
PR_1924

**Review by Pandani07 — DISMISSED** [review]
Reviewed this PR and the background color and font size have been fixed.

Screenshot 2024-02-07 at 12 28 59 PM

**Review by n0vay — DISMISSED** [review]
Looks good to me
image

**Review by peterson337 — DISMISSED** [review]
Hi olena, I tested your application, and everything worked as expected. Good job!

a

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested the PR and all the changes are working properly. Please refer the screenshot attached.

PR 1924

**Review by chrischenlixing — DISMISSED** [review]
Hi Olena, I reviewed you change on the css file and the localhost and it's all good
image

**Pull request merged**
