### PR TITLE
Xiaow task system improvement

### PR DESCRIPTION
**Pull request by wang9hu**
# Description
This PR aims to cooperate with backend to overhaul the task system logic and improve UI. Major changes include but not limited to: overhaul Task component and task controller display logic, improve logic of task import, addition, move, delete and edit,  improve task reducer logic, and make code more organized.

## Related PRS :
This frontend PR is related to the [#455](https://github.com/OneCommunityGlobal/HGNRest/pull/455#issue-1816682991) backend PR.

## Main changes explained:
- Frequent DOM manipulations are not recommended for React app, so one major change for this PR is that it converts most DOM manipulation to the way react handles its states and make the render output solely controlled by React.
- Task components now have nested lower level Task components, which will only rendered on page when unfolded a higher level task
- "All" filter on the top only works as a filter just like the rest of the filters, and "Fold/Unfold" button is added to control all tasks collapse
- Task controller is moved out of Task as a different component, and it makes sure only one controller is shown on page, and folding higher level task will close the controller for lower level tasks.
- For each task item, parentIds and mother props are revised, and the backend logic for tasks is rewrite to reconcile with this change. It makes sure that the tasks of different levels are properly organized.

- For add task functionality:
add task
  - Now have a correct num (WBS #) showing on the top of the modal, and it depends on where the new task is added. Previously it will not show the correct num for some edge cases.
  - For "status", according to the xlsx file there should be four options: Active, Not Started, Paused and Complete. Proper changes are made to accommodate this. For Task component, different icons are used as well (from top to bottem are Active, Not Started, Paused and Complete)
status icons
  - Now when you add a new task, app will check with backend to make sure database is not changed since you load the page, in a special case which another admin use add a new task to the same WBS, app will alert current user that database has changed, and once user clicks OK, app will refresh the page with the most recent data. This will prevent different users create task with the same number.
repeated task num created
  - Copy functionality should also work now, be sure to copy a task in its controller bar and then use the paste button at the top of the add task modal.
- For import task functionality:
  - now in xlxs file, resources column can have multiple names, but it must be inside of the name list of current project member, otherwise app will warn user.
import warn
  - a reset button is added 

- For move task functionality:
  - now not only the target task will be moved, any child tasks inside of target task will move along with it.
  before move:
before move
  after move:
after move

- some other QoL changes, such as tooltips and proper response/loading icon as feedback for any task function operation 
- I disabled 'Level -1' test cases since I replace it with case: EMPTY_TASK_ITEMS and this test is not applicable anymore.

## How to test:
1. check into current branch and backend PR [#455](https://github.com/OneCommunityGlobal/HGNRest/pull/455#issue-1816682991)
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to dashboard → Other Links → Projects → choose one Project  → choose one WBS 
5. verify import task (only from empty WBS), add task (both from the top of the table and from task controller), edit, remove, move, copy (then paste to new task) all work as intended.

## Note:
- import task can only be tested in empty WBS, and you could ask Jae for the template xlsx file for testing.
- since a lot of changes were made to accommodate the new task system, it is recommended to create a new WBS and create new tasks for testing move functionality
- to test add task with same number, use two browser pages and login the same WBS, create one task on one page and then try to create a new task on the second page, see if you could get the alert.
- I haven't figure out how the Hours works yet, since you could add a sub task that has way more hours than its mother task, but from the import logic in the backend it seems that the hours of a mother task should be the sum of all of its child tasks, which baffles me

### CODE REVIEW

**Comment by one-community** [comment]
> * import task can only be tested in empty WBS, and you could ask Jae for the temple xlsx file for testing.

Here's the file: https://www.dropbox.com/scl/fi/ka2qciglxszfucnhdgkwo/WORKING-TEST-FILE-WBS-Imported-to-software-on-8-9-22.xlsx?rlkey=jqii7l0tq4gt466vegc2zvlud&dl=0

**Comment by one-community** [comment]
> * I haven't figure out how the Hours works yet, since you could add a sub task that has way more hours than its mother task, but from the import logic in the backend it seems that the hours of a mother task should be the sum of all of its child tasks, which baffles me

Mother tasks shouldn't ever be assigned, so their hours don't matter. They could be though as a general task with a less-specific deadline, and in those special cases, we'd want the flexibility to add whatever hours we want. This really shouldn't ever happen though, there's just no problems I can think of if it did.

**Review by winghojackyli — DISMISSED** [review]
PR looks great and works perfectly. Great work! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/02cd4068-16e9-4bb1-9a75-dda78fbf855e

**Review by xaanders — DISMISSED** [review]
Hi @wang9hu! 
I have tested you PR. This is a big one and you did it great.

- I was getting this error 
photo_2023-07-24_10-32-53

Had to change Resources column inside testing file from Unassigned to the name of the user to be able upload a file.

Regarding the functionality:

[scrnli_7_24_2023_10-25-54 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/35bb446b-8c99-4954-9c7c-8666fc8b6273)

Another browser page adding: 


And current page: 

[scrnli_7_24_2023_10-30-17 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/eb83c752-b350-44b8-a1a2-25cf5403cf6d)

So before creating and filling the form for a new task it is better to refresh the page to get latest data otherwise you can lose a new task after submitting the alert

**Review by DavidC0126 — DISMISSED** [review]
Hi @wang9hu,
I tested your PR and it works perfectly!

-  I can import task in empty WBS using xlsx template provided by Jae (need to change resource column to my admin role name)
import_task_1
import_task_2

- When I try to add another task in another page, the alert will show.
alert_1

-  If I click ok, the page will be refreshed

**Comment by eduvarjaor** [comment]
Hi @xaanders

Which username do you put?

**Comment by Shreyj14** [comment]
Hi @wang9hu  I tested this PR, and I was able to work on it smoothly. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/1536a51e-e2d6-4fbc-b6e0-c0bdb539b64d

**Review by Shreyj14 — APPROVED** [review]

**Comment by xaanders** [comment]
> Hi @xaanders
> 
> Which username do you put?

I've just put first name and last name of my admin user

**Review by shiva2096 — DISMISSED** [review]
Hi @wang9hu 

I have tested all the functionalities. The app is working as expected.

Screenshot 2023-07-29 at 8 45 38 PM

**Comment by Lin1404** [comment]
Hi @wang9hu! I have tested you PR. PR looks great and works perfectly.

image

**Review by Lin1404 — APPROVED** [review]

**Review by zuhang2000 — APPROVED** [review]
I test your PR by following your instructions. It works as expected!

I test import functionality by importing the example xlsx file. And it works great!
Screen Shot 2023-08-04 at 1 23 54 AM


I also test move, edit, delete, copy. All of these functionalities are working as expected! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/bb2eb5fd-a23e-4b5e-963f-62781cb934dd

**Review by ThapeloMasasa — APPROVED** [review]
The changes work as expected.. Great job.....


Screenshot 2023-08-04 at 11 27 31 AM




Screenshot 2023-08-04 at 11 25 27 AM

hestGoodNetworkApp/assets/73863365/40905fc3-f91c-4a1b-9af1-56134e4d968e">
Screenshot 2023-08-04 at 10 29 48 AM

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @wang9hu. I have tested your PR and everything is working perfectly as intended. Great work!

For add task functionality:
- Correct num (WBS #) showing  ✅
- "Status" icon updated when the status of the task changes  ✅
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/fcaef471-d12c-45b6-8280-b809e4d0507d

- Alert current user that database has changed when adding a task ✅
- Copy task functionality ✅
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/aae82168-c0ab-4faa-a119-49a2457dacfa

For import task functionality:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/e60c1c4e-8f82-4296-bbe1-fbe2df430c4b

For move task functionality:
- Child tasks inside of target task will move along with the parent task ✅
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/c8a3c4d4-3b39-4cc2-961a-dd9aafbd224c

**Pull request merged**
