### PR TITLE
Yili fix active status issue on team management page

### PR DESCRIPTION
**Pull request by suaniii**
# Description
image

## Related PRS (if any):
For backend use development branch

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links→ Teams
6. Click the `active` indicator of any team
7. Click `confirm` to change the active status
8. Verify that the indicator color changes immediately to reflect the new status (green for active and grey for inactive)
9. Verify that the page will not be stuck and no page refresh is needed to see the updated indicator status

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/3c62df8b-7629-414c-8bd2-3be82b1e7994

### CODE REVIEW

**Review by kdaga81 — APPROVED** [review]
image

Changes are working as expected. Status is getting changes without page getting stuck or refreshing.

**Review by Pranay-ai — APPROVED** [review]
Hey @suaniii 
The Pr is working as expected , please find the video for reference 

https://github.com/user-attachments/assets/0321a3d9-1431-4847-a35d-04c4276e3de6

Thank You

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.



Thank You

**Review by Lemonnycodes — APPROVED** [review]
Hi,

I have tested the changes in this PR, and everything works as expected. 

- The active indicator color updates immediately upon changing the team status, reflecting the correct status without requiring a page refresh. 
- The page remains responsive, and there are no issues with freezing or delays.
 
 Image References:
 
 
PR 2610 (1)
PR 2610 (2)
PR 2610 (3)

**Review by SMitta11 — DISMISSED** [review]
I followed the instructions and for backend I used the development branch and for front end I used yili_active_indicator_fix branch but when I am clicking on indicator of any team active/inactive page is getting stuck and it is not giving expected result.
Screenshot:
Screen Shot 2024-08-24 at 5 19 09 PM

**Review by Gauravmg6 — APPROVED** [review]
Everything works as expected.
Screenshot 2024-08-25 023635

**Review by Saniya98 — APPROVED** [review]
Everything is working as expected.

**Review by manikittu810 — COMMENTED** [review]
Hello @suaniii 

It is taking a lot of time to make the status inactive and the current page is not responsive.


https://github.com/user-attachments/assets/168afffd-67bb-4510-acc4-dbf258163c14

Thank you.

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.

https://github.com/user-attachments/assets/67e47356-b58c-48f9-a06f-b3eacacb15e2

**Review by preethamdnr — APPROVED** [review]
Hello Yili,
I have reviewed this PR and it is working as expected.

https://github.com/user-attachments/assets/13a92248-fcfb-4a8e-8f01-1ce72e404312

**Review by gowthamdongari — APPROVED** [review]
Hello Yili,
I have reviewed your PR and working as expected.

https://github.com/user-attachments/assets/d5bd396b-dddf-4d57-b8bd-b7d02a21fbad

**Review by CillianRen — APPROVED** [review]
https://github.com/user-attachments/assets/ed6c4ff4-87b1-4830-afd7-7f9dde2ec6ff


The active and inactive buttons function correctly without any errors.

**Review by RishithaMamidala — DISMISSED** [review]
@suaniii 
I have followed the instructions and used development branch for backend and have run this front branch, but the page frezees when trying to change the active status.
PR 2610

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/6f9d4d98-7228-4008-8e6f-a0537219c7c5

**Review by mohangadde1 — APPROVED** [review]
https://github.com/user-attachments/assets/b44b420f-8fb5-49ea-8349-819c8b530d5f

changes are working as expected.

**Review by panchalvatneu — APPROVED** [review]
Changes are working as expected 

https://github.com/user-attachments/assets/2ab815a1-f555-43d5-b1f5-a4cd2772c51d

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
