### PR TITLE
Jay unit tests for SetUpFinalDayPopUp

### PR DESCRIPTION
**Pull request by jayyy-s**
# Description
Implements unit tests for `/src/components/UserManagement/SetUpFinalDayPopUp.jsx`

## Related PRS (if any):
This is not related to any other PRs
…

## Main changes explained:
- Create file SetUpFinalDayButton.test.js which contains unit tests for component SetUpFinalDayButton.jsx
- Tests for the following cases:

On render:
1. If user profile end date is not set, then button text is Set Final Day
2. If user profile end date is set, then button text is Delete Final Day

When button is clicked:
1. If the user has an endDate, then an alert will appear with message: This user's final day has been deleted.
2. If the user has no endDate, SetUpFinalDayPopUp will be open

For code coverage:
1. setUpFinalDayPopupClose should close SetUpFinalDayPopUp 
2. When deactiveUser is called by child component, popup should close and alert will appear with following text: This user's final day has been set.

## How to test:
1. check into current branch
4. run npm test -- SetUpFinalDayButton.test.js
5. verify that all tests pass and accomplish 100% code coverage

## Screenshots or videos of changes:
SetUpFinalDayButton all tests working and full code coverage

### CODE REVIEW

**Review by Sandhya1236 — APPROVED** [review]
I have thoroughly tested the new unit tests implemented for the SetUpFinalDayButton component in SetUpFinalDayButton.test.js. The tests cover all specified scenarios, including checking the button text based on whether the user profile's end date is set, and verifying the appropriate alerts and popup behaviors upon button clicks. Additionally, the tests ensure that the setUpFinalDayPopupClose function correctly closes the popup and that the deactiveUser function triggers the expected alert and popup closure. I confirm that all tests have been executed successfully, achieving 100% code coverage.

image

**Comment by beblicarl** [comment]
All test cases passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by KaushikMreddy** [comment]
Hi jay, 
all of your test cases are working. 
image

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-06-01 at 9 30 04 PM

**Review by tianyangL11 — APPROVED** [review]
All test cases passed!

**Review by shradac — APPROVED** [review]
All tests passed. The tests cover all the specified scenarios. Good Work! 

week1-13

**Review by deepthikannan — APPROVED** [review]
image
All test cases passed, tested your PR.

**Review by KaushikMreddy — APPROVED** [review]

**Review by vishavk1992 — APPROVED** [review]
All test cases passed successfully!!!

PR-2297

**Review by cecilia-uu — APPROVED** [review]
截屏2024-07-21 下午3 08 25
All tests have passed!

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested this PR. It passes all the Scenarios and test cases. I have gone through the code.

**Review by Pranay-ai — APPROVED** [review]
Hey @jayyy-s 
All of the test cases passed
image

**Comment by Gmon-k** [comment]
I have test the PR and it has passed all the test cases. Below is the screenshot for it.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
