### PR TITLE
Lucas fix tasks another user dashboard

### PR DESCRIPTION
**Pull request by Lucas-E**
This PR should solve: (PRIORITY LOW) Jae: Fix tasks view when viewing another person’s dashboard

### In this PR, the volunteer user can see the Onwer/Administrator/Core Team data

<hr>

### Main changes

Previously: When vieweing another user's dashboard, it would show the currently authenticated user's dashboard instead of the viewed user's dashboard;
Now: When the currently authenticated user is seeing another user's dashboard (clicking the green dot on the left of the user, under the Leaderboard), the tasks tab (of the viewed user) will show what the viewed user would see in it's dashboard.

<hr>

### How to test

- Checkout the current branch on frontend
- npm install
- npm run start:local
- Login as various users roles and teams and check other users dashboard
- Go to the tasks tab and see what is shown there
- Check on the user's tasks tab to see if the data that is shown is coherent with the user's dashboard data

### How to check another user's dashboard

- Click on Dashboard
- Go to the Leaderboard
- It should show some users if the logged user is on a team or is an Owner/Administrator/Core Team
- Under the Status theres a green dot
- Click the green dot to check the other user's dashboard
- On the other user's dashboard, see the "Tasks" under the "Tasks and Timelogs"
- The "Tasks" tab should show what the viewed user would see in it's tasks

### The expected behaviors changed because I've made the changes stated on the item "d" of the task, please review the PR again

What was happening before my pr

https://user-images.githubusercontent.com/92558269/230201921-7777885f-b1c0-4824-ad08-b1eda1212170.mp4

What should you see

https://user-images.githubusercontent.com/92558269/232823611-cdac2e94-0a8f-4d83-a5e7-33fd22cfc282.mp4

<hr>

The changes on the code are commented on the commits.

### CODE REVIEW

**Review by ypan710 — COMMENTED** [review]
For the instruction, "when the current authenticated user is seeing another user's dashboard, the tasks tab will show what the user would see in it's dashboard", what do you mean by "another user's dashboard"? Do you mean another user of the same role (e.g. admin)?

I have created two accounts (one for Yongjian Pan and another for Yongjian2 Pan2). I have set both roles to be the admin role and have clicked on the "Tasks" tab when viewing the dashboard, as shown below. If this is not what you expected, please correct me.

Screen Shot 2023-04-01 at 11 18 02 AM

Screen Shot 2023-04-01 at 11 17 29 AM

**Comment by Lucas-E** [comment]
> For the instruction, "when the current authenticated user is seeing another user's dashboard, the tasks tab will show what the user would see in it's dashboard", what do you mean by "another user's dashboard"? Do you mean another user of the same role (e.g. admin)?
> 
> I have created two accounts (one for Yongjian Pan and another for Yongjian2 Pan2). I have set both roles to be the admin role and have clicked on the "Tasks" tab when viewing the dashboard, as shown below. If this is not what you expected, please correct me.
> 
> Screen Shot 2023-04-01 at 11 18 02 AM
> 
> Screen Shot 2023-04-01 at 11 17 29 AM

I'll correct the main changes and the instructions to be more clear on how to test and what to expect when testing!

**Comment by one-community** [comment]
Reminder Admin accounts see everyone in their dashboard and tasks lists... Volunteer accounts should only see themselves and people in their teams. Be sure to test this with two different kinds of accounts so what is seen in Tasks tab is actually different.

**Comment by ypan710** [comment]
I believe this is what you expected. Logging into my dummy account with role set to admin/volunteer gives me the same view on the list of tasks under "Tasks" tab in the dashboard page as clicking on the "green" or "red" dot to check the respective user's list of tasks under the "Tasks" tab in the dashboard page for the respective role. If this is what you expected, then yes, both of the views for the respective roles are the same. If not, please correct me. Thanks.

For admin role:

Screen Shot 2023-04-01 at 4 22 14 PM

Screen Shot 2023-04-01 at 4 23 04 PM


For volunteer role:

Screen Shot 2023-04-01 at 4 27 27 PM

Screen Shot 2023-04-01 at 4 27 43 PM

**Comment by ypan710** [comment]
Reviewed PR with author and author has confirmed his expectations as shown below.

For volunteer roles in teams:
Screen Shot 2023-04-01 at 5 18 36 PM

For admin roles in teams:
Screen Shot 2023-04-01 at 5 22 42 PM

**Comment by one-community** [comment]
Right, so the "tasks" view will always show whomever is in a person's Team after clicking their dot in the leaderboard. Regardless of their role when being viewed via that dot. 

FRINGE/SPECIAL CASE I JUST THOUGHT OF: 
However, if an Admin or Owner views another Admin, this would be a fringe case where it should show exactly what the Admin/Owner sees... which is ALL tasks because that is part of the permissions for an Admin and Owner. 

If an Admin/Owner happens to be on a team though, we don't want some non-Admin/Owner to have access to all that information by just clicking the dot by the Admin/Owner's name. That's why those other roles should just see whomever else is in their team for an Admin/Owner. 

Does that make sense?

**Comment by Lucas-E** [comment]
> Right, so the "tasks" view will always show whomever is in a person's Team after clicking their dot in the leaderboard. Regardless of their role when being viewed via that dot.
> 
> FRINGE/SPECIAL CASE I JUST THOUGHT OF: However, if an Admin or Owner views another Admin, this would be a fringe case where it should show exactly what the Admin/Owner sees... which is ALL tasks because that is part of the permissions for an Admin and Owner.
> 
> If an Admin/Owner happens to be on a team though, we don't want some non-Admin/Owner to have access to all that information by just clicking the dot by the Admin/Owner's name. That's why those other roles should just see whomever else is in their team for an Admin/Owner.
> 
> Does that make sense?

It does make sense, Jae! Once this PR is reviewed and merged, it could be another requested functionality on the list!

**Comment by one-community** [comment]
Sounds good, thank you. Adding my notes under this but on the Doc.

**Comment by NataliaCavicchioli** [comment]
Hey Lucas, I tested your PR. 

Before:
Admin viewing a volunteer dashboard:
image

Volunteer viewing an admin dashboard: 
image

After: 
Admin viewing a volunteer dashboard:
image

Volunteer viewing an admin dashboard:
image

Volunteer viewing itself dashboard:
image

Well, from what I understood, this is not working as expected, as the volunteer should not be able to see the tasks of others users.

**Review by vitorsaa2k — COMMENTED** [review]
Hello @Lucas-E these are my testings:

Tasks on my dashboard:
image

Tasks seeing another user's dashboard:
image

**Comment by Lucas-E** [comment]
> Hey Lucas, I tested your PR.
> 
> Before: Admin viewing a volunteer dashboard: image
> 
> Volunteer viewing an admin dashboard: image
> 
> After: Admin viewing a volunteer dashboard: image
> 
> Volunteer viewing an admin dashboard: image
> 
> Volunteer viewing itself dashboard: image
> 
> Well, from what I understood, this is not working as expected, as the volunteer should not be able to see the tasks of others users.

Hey Natalia, how you doing? So, the volunteer seeing another user's tasks is the correct behavior. On another PR, we are going to solve the non Owners/Administrator/Core Team seeing all the platform's info when seeing the Owner/Administrator/Core Team dashboard.

**Comment by Elisaudo** [comment]
Hi, lucas, I tested PR#746. And it passed all most test. Only don,t past in the last issue data Jae edited.

"If an Admin/Owner happens to be on a team though, we don't want some non-Admin/Owner to have access to all that information by just clicking the dot by the Admin/Owner's name. That's why those other roles should just see whomever else is in their team for an Admin/Owner."

1) Login in HGN as volunteer.

#P746 -access team as volunteer access

2) Its shown team of volunteer and admin.

#P746 -access team as volunteer access - click in DOT in Admin role - is shown all information of Admin

3) Click in DOT in admin role.

#P746 -access team as volunteer access - click in DOT in Admin role

4) Is shown all task information of admin role in a volunteer access.

#P746 -access team as volunteer access - click in DOT in Admin role - is shown all information of Admin

**Comment by Lucas-E** [comment]
> Hi, lucas, I tested PR#746. And it passed all most test. Only don,t past in the last issue data Jae edited.
> 
> "If an Admin/Owner happens to be on a team though, we don't want some non-Admin/Owner to have access to all that information by just clicking the dot by the Admin/Owner's name. That's why those other roles should just see whomever else is in their team for an Admin/Owner."
> 
> 1. Login in HGN as volunteer.
> 2. Its shown team of volunteer and admin.
> 
> #P746 -access team as volunteer access
> 
> 3. Click in DOT in admin role.
> 
> #P746 -access team as volunteer access - click in DOT in Admin role
> 
> 4. Is shown all task information of admin role in a volunteer access.
> 
> #P746 -access team as volunteer access - click in DOT in Admin role - is shown all information of Admin

Hey Elisaudo, how are you doing? The Volunteer situation will be solved in another PR. The Volunteer user being able to see Onwer/Administrator/Core Team data is the expected behavior on this PR.

**Review by Elisaudo — CHANGES_REQUESTED** [review]
"If an Admin/Owner happens to be on a team though, we don't want some non-Admin/Owner to have access to all that information by just clicking the dot by the Admin/Owner's name. That's why those other roles should just see whomever else is in their team for an Admin/Owner."

**Comment by LucileTech** [comment]
Hi @Lucas-E ! I really hope it is the right way to test, you explained so well I am just new to the platform's features:
Admin point of view of a Volunteer in a team

Admin point of view of a Volunteer in a team

Admin point of view on his own tasks

Admin point of view on his own tasks

Volunteer seing is own tasks

Volunteer seing is own tasks

Volunteer seing tasks of someone in his/her team

Volunteer seing tasks of someone in his:her team

Volunteer with admins rights seing tasks of someone in his/her team

Volunteer with admins rights seing tasks of someone in his:her team

Volunteer with mentor rights seing tasks of someone in his/her team

Volunteer with mentor rights seing tasks of someone in his:her team

**Comment by AriaYu927** [comment]
Hi @Lucas-E I've tested your PR and I think it works as expected.

An admin user own tasks:
Admin-own-task

The admin user view another user's tasks:
admin-see-volunteer

An volunteer's own tasks:
volun-own-tasks

The volunteer view another user's tasks:
volun-see-other

**Comment by AuroraLovesWhales** [comment]
Hi Lucas! I have tested your PR. But when an admin tries to view a volunteer’s dashboard, the admin’s view doesn’t match with what the volunteer’s actual view is. It seems to be working for people who have tested out your PR previously, so I'm not sure what I'm doing wrong here.


Previous behavior:

Volunteer XiaoTest Volunteer viewing her own dashboard:
Pasted Graphic 20


Admin XiaoTestAdmin viewing XiaoTest Volunteer’s dashboard (views don’t match):
https://user-images.githubusercontent.com/44281916/232254191-234fdf03-3cb7-45a1-ba3a-525f752e537b.mov

Current behavior:
Volunteer XiaoTest Volunteer viewing her own dashboard:
Pasted Graphic 22

Admin XiaoTestAdmin viewing XiaoTest Volunteer’s dashboard (views still don’t match):
Pasted Graphic 23

**Comment by Lucas-E** [comment]
> Hi Lucas! I have tested your PR. But when an admin tries to view a volunteer’s dashboard, the admin’s view doesn’t match with what the volunteer’s actual view is. It seems to be working for people who have tested out your PR previously, so I'm not sure what I'm doing wrong here.
> 
> Previous behavior:
> 
> Volunteer XiaoTest Volunteer viewing her own dashboard: Pasted Graphic 20
> 
> Admin XiaoTestAdmin viewing XiaoTest Volunteer’s dashboard (views don’t match): https://user-images.githubusercontent.com/44281916/232254191-234fdf03-3cb7-45a1-ba3a-525f752e537b.mov
> 
> Current behavior: Volunteer XiaoTest Volunteer viewing her own dashboard: Pasted Graphic 22
> 
> Admin XiaoTestAdmin viewing XiaoTest Volunteer’s dashboard (views still don’t match): Pasted Graphic 23

I've made the changes stated in item "d" of the tasks, so the expected behaviors are different. I'm updating the testing instructions and videos, take a look and please test again, okay? You can send my a DM on slack if you have any further questions.

**Comment by AuroraLovesWhales** [comment]
> > Hi Lucas! I have tested your PR. But when an admin tries to view a volunteer’s dashboard, the admin’s view doesn’t match with what the volunteer’s actual view is. It seems to be working for people who have tested out your PR previously, so I'm not sure what I'm doing wrong here.
> > Previous behavior:
> > Volunteer XiaoTest Volunteer viewing her own dashboard: Pasted Graphic 20
> > Admin XiaoTestAdmin viewing XiaoTest Volunteer’s dashboard (views don’t match): https://user-images.githubusercontent.com/44281916/232254191-234fdf03-3cb7-45a1-ba3a-525f752e537b.mov
> > Current behavior: Volunteer XiaoTest Volunteer viewing her own dashboard: Pasted Graphic 22
> > Admin XiaoTestAdmin viewing XiaoTest Volunteer’s dashboard (views still don’t match): Pasted Graphic 23
> 
> I've made the changes stated in item "d" of the tasks, so the expected behaviors are different. I'm updating the testing instructions and videos, take a look and please test again, okay? You can send my a DM on slack if you have any further questions.

Hi Lucas! I have tested your PR as admin and volunteer and now the views match.

**Comment by NataliaCavicchioli** [comment]
Hey @Lucas-E, I re-tested your PR, and it is working exactly as expected. Well done!

Before - Logged in as admin, viewing a volunteer dashboard: 
image

After - Logged in as admin, viewing a volunteer dashboard: 
image

**Review by NataliaCavicchioli — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, moving to final review

**Review by AuroraLovesWhales — APPROVED** [review]

**Comment by AriaYu927** [comment]
> Hi @Lucas-E I've tested your PR and I think it works as expected.
> 
> An admin user own tasks: Admin-own-task
> 
> The admin user view another user's tasks: admin-see-volunteer
> 
> An volunteer's own tasks: volun-own-tasks
> 
> The volunteer view another user's tasks: volun-see-other

Tested this PR again and everything works as expected, thank you!

**Review by vitorsaa2k — APPROVED** [review]
Working as expected!

My dashboard:

image

Another user's dashboard:

image

**Pull request merged**
