### PR TITLE
Sahil_BadgeDevelopment_UnitTest

### PR DESCRIPTION
**Pull request by sahilpatel18**
# Description
Create Unit Tests for BadgeDevelopment.jsx

## Main changes explained:
- Added a new file: BadgeDevelopment.test.js
- In BadgeDevelopment.test.js, I have added 5 test cases to evaluate BadgeDevelopment.jsx.

## How to test:
1. Check into current branch
2. Do `npm install` 
3. Do `npm test BadgeDevelopment.test.js`  to run the test
4. Verify that all test cases pass successfully

## Screenshots or videos of changes:

Screenshot 2023-11-23 at 1 03 25 PM

### CODE REVIEW

**Review by vikrambadhan — APPROVED** [review]
Hi, i tested the PR and all the test cases passed! Great Job!

Week 13 - PR2

**Review by lacnoskillz — APPROVED** [review]
Hello @sahilpatel18 
I pulled your changes and ran your tests and they all passed!
nice work
image

**Review by scoopstroop92 — APPROVED** [review]
Hello @sahilpatel18  You have covered all possible cases in your test
Good job

**Comment by AnishPandita** [comment]
Hey, I tested the test suites according to the guideline and it works as intended. All the test cases passed without any issues.
Screenshot 2023-11-24 at 10 46 52 PM

**Review by ZichanYang324 — APPROVED** [review]
There is no issue with this part and all the tests have passed.
Screenshot 2023-11-25 at 2 59 50 AM

**Review by Hemsharavanan — APPROVED** [review]
- Your tests cover essential functionalities like rendering, button clicks, popup appearance and disappearance, and the existence of the BadgeDevelopmentTable component.
- The tests are straightforward and easy to follow, focusing on specific functionalities and interactions.
- Overall tests provide coverage for key functionalities such as confirming rendering, interaction triggering, and popup closure.
PR #1579 Sahil_BadgeDevelopment_UnitTest

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by one-community** [comment]
Merged this but saw this in Circle CI 
image

**Pull request merged**
