### PR TITLE
Sarthak fix projects reports formating

### PR DESCRIPTION
**Pull request by Sarthak32**
# Description
Fixes the formatting of the table in Project reports which was previously not misaligned

## Related PRS (if any):
This PR is not related to any

## Main changes explained:
- This Fixes the size alignment of the table head names in Project reports and also aligns them to left. 

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard then Reports → Reports → Projects → Choose Project
6.  you should be able to see this fixed alignment of table head names like this: 
 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/0c5e04fc-9ff6-4f18-8b48-3f055b2a813f

Screenshot 2024-04-13 103234
Screenshot 2024-04-13 104842

## Note:
choose the project which has multiple members

### CODE REVIEW

**Review by 20chen-7 — COMMENTED** [review]
Hi, code looks good. I prefer some space between the last row and the page number line. Could do you adjust it?
Screenshot 2024-04-13 at 3 03 16 PM
Screenshot 2024-04-13 at 3 10 57 PM

**Review by hbodgal — CHANGES_REQUESTED** [review]
image

The header and column is not aligned. I loaded this in Incognito. Cleared Cache. But still facing this issue.

**Review by aaryaneil — APPROVED** [review]
Reviewed your PR and the changes work as expected on my end.
Screenshot 2024-04-14 at 1 41 19 AM

**Review by linkhanthtel — CHANGES_REQUESTED** [review]
I reviewed your PR and I still see the page number rows and last rows are not aligned properly.

Screenshot 2024-04-15 at 6 54 25 PM

**Review by Pandani07 — COMMENTED** [review]
PR works sometimes. The alignment is not consistent. I would also suggest reducing the amount of width the '#' column takes. And the alignment of the active indicator (green circle) is messed up.

Screenshot 2024-04-16 at 11 08 41 PM

Also why is the test center justified in the WBS part but left justified in the members part?
Screenshot 2024-04-16 at 11 09 16 PM
Screenshot 2024-04-16 at 11 08 20 PM
Screenshot 2024-04-16 at 11 07 57 PM

**Pull request closed without merging**
