### PR TITLE
Iven - Allow accounts with permission make suggest on tasks and see the notification after approval

### PR DESCRIPTION
**Pull request by iven-yao**
# Description
image
This request started from #721, #949, #1458

## Related PRS (if any):
This frontend PR is related to the [#914 backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/914).
…

## Main changes explained:
- Update `src/components/Projects/WBS/WBSDetail/EditTask/EditTaskModal.jsx`, modify the logic in rendering Edit/Suggest/View buttons, and based on the button render different modal layout and submit function
- Update `src/components/TaskEditSuggestions/thunks.js`, fix the bug here to get correct data

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as Manager/Mentor user 
5. go to dashboard→ Tasks→ click on any tasks (If you are not assigned with any task, please do it before testing this PR)
6. should be able to see both Edit and Suggest Button for Manager/Mentor, and any user is granted with `Suggest Changes on a task`
image

7. verify that `Edit` will update the task content directly
8. verify that `Suggest` will update the task content after Admin/Owner approval
9. After making a suggest on task
10. log as Admin/Owner user
11. you could see a red dot with a number beside Dashboard on the top banner, you should be able to click and see suggestions need to be approved
image

12. approve the suggestion, then log as Other user
13. verify that everyone on this task could see a red bell beside Dashboard->Tasks
image

14. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by Ramaruva** [comment]
Hi can you please explain more about this point 
"go to dashboard→ Tasks→ click on any tasks (If you are not assigned with any task, please do it before testing this PR)"
As I was new, I am not sure how to assign task to a manager can you help me here how to assign task is admin who assigns or manger role himself will assign?

**Comment by Ramaruva** [comment]
Hi I have verified changes but I am unable to verify the point 13  and remaining first 12 steps I am able to verify it

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/64dbed0d-b029-4cf9-80cb-31438722cec4


image

**Comment by iven-yao** [comment]
> Hi I have verified changes but I am unable to verify the point 13 and remaining first 12 steps I am able to verify it
> 
>  edit.mp4 
> image

Hi Ramaruva, 
I think your second picture showed the step 13 as expected, both members assigned with task 2 could see a red bell in their own row, and could click it, see the difference and mark as read. If you could verify this step, please confirm with an approve, or let me know what seems off. Thanks :)

**Review by Ramaruva — DISMISSED** [review]
Hi I have verified  the changes with your suggested steps it is working well 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/9159698a-3fae-4aaf-ab18-a54d469546d4

**Review by nathcarnevalli — COMMENTED** [review]
Hi Iven, the functionalities are working as expected, as you can see below. However, dark mode is not working properly in Projects > WBS > Task and Dashboard > Notification. Also, I'd like to suggest that when someone makes a suggestion, the success message could be 'Suggestion sent,' or something similar. I'm not sure if any of this is related to your task, so please let me know if it's not. :)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/01b194d1-247a-4fa4-a0f5-77e70fd55dda

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/3dcf8667-f016-48cc-8f61-f794c0647c23

**Comment by nishithaShetty** [comment]
Hi Iven, Nice work!
The functionalities work as expected.
Is this the intended behavior for this particular test case: if the task has more than one mentor and both provide a suggestion, the latest suggestion is considered by the admin and approved or rejected? Irrespective of the number of suggestions from different mentors, the admin dashboard will only show one notification per task.

PR#2200_1
PR#2200_2
PR#2200_3
PR#2200_4
PR#2200_5
PR#2200_6

**Review by peter6866 — DISMISSED** [review]
Excellent work on implementing the task edit and suggestion feature! This PR enhances collaboration and streamlines the task management process. Here's the review based on the testing steps you provided:

✅ Logged in as a Manager:
   - Verified that the Manager user can see both Edit and Suggest buttons for tasks they are assigned to.
   - Tested the Edit button and confirmed that it updates the task content directly.
   - Tested the Suggest button and confirmed that it creates a task suggestion pending Admin/Owner approval.

✅ Logged in as an Admin:
   - Verified that the Admin user receives a red dot with the number of pending suggestions beside the Dashboard on the top banner.
   - Clicked on the notification and confirmed the ability to view and approve the task suggestion made by the Manager.
   - Approved the suggestion successfully.

✅ Logged in as a Volunteer:
   - Verified that the Volunteer user can see a red bell beside Dashboard->Tasks, indicating an approved task suggestion.
   - Confirmed that the task content reflects the approved changes made by the Manager.
https://www.loom.com/share/06e692829a0e494db9546bc8805a4f8e?sid=8bea6d5f-0385-4aa8-b522-0420d3e1673e

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
