### PR TITLE
Gowtham filter by over hours

### PR DESCRIPTION
**Pull request by curiousfancier**
# Description
Screenshot 2024-07-02 183124

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Fixed filter for people who set the total work hours as zero
- When the Filter is on it should ignore people with zero set hours / zero logged hours

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log in as an admin user
5. go to reports→ Weekly Summary Reports → Filter by over hours

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/27274513/a7dfde15-d442-4ca3-a94d-9a02657ece86

### CODE REVIEW

**Comment by vijay10pk** [comment]
Tested this PR with the admin account and the change is working as stated above.

Screenshot 2024-07-02 at 8 21 38 PM

**Before Enabling the filter** : It shows all the users who has 0 loggedIn hours.
Screenshot 2024-07-02 at 8 22 29 PM

**After enabling the filter** : It is ignoring the users who has 0 loggedIn hours.
Screenshot 2024-07-02 at 8 22 37 PM


Everything is working as expected. Looks good to me.

**Review by vijay10pk — DISMISSED** [review]

**Review by kdaga81 — COMMENTED** [review]
With filter "on" for "Three Weeks ago"
image

With filter "off" for "Three Weeks ago"
image

With filter "off" for "Three Weeks ago", I'm not sure if it's the right expected behavior. I could see multiple entries with '0' hours.
image

 Could you please provide more information on this?

**Comment by rmcgummadi** [comment]
The PR is working as expected

**Without Filter**: We can see people with 0 hours in the last week
Screenshot 2024-07-02 at 11 44 49 PM


**With Filter:** We only see people who meet the criteria 
Screenshot 2024-07-02 at 11 49 20 PM

**Comment by gowthamdongari** [comment]
> With filter "on" for "Three Weeks ago" image
> 
> With filter "off" for "Three Weeks ago" image
> 
> With filter "off" for "Three Weeks ago", I'm not sure if it's the right expected behavior. I could see multiple entries with '0' hours. image
> 
> Could you please provide more information on this?

if the filter is off you could see people with 0 logged hours and if you set the filter on it should ignore the zero hours people

**Comment by gowthamdongari** [comment]
> > With filter "on" for "Three Weeks ago" image
> > With filter "off" for "Three Weeks ago" image
> > With filter "off" for "Three Weeks ago", I'm not sure if it's the right expected behavior. I could see multiple entries with '0' hours. image
> > Could you please provide more information on this?
> 
> if the filter is off you could see people with 0 logged hours and if you set the filter on it should ignore the zero hours people

**Review by HowieMiao — DISMISSED** [review]
Filter by Over Hours toggle works great, displays Jay over hours 3 weeks ago, turning it off shows everyone with under their set hours.

image

**Review by sahithidhulipala9 — APPROVED** [review]
PR working as expected!
PR 2410 - 1
PR 2410

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi Gowtham, 

The filter by hours is very vague to be honest, a tooltip would help with the description. But the code works. 
image


Some improvements that I suggest: 

1. Try to make it a dropdown filter, that sorts by a set number of hours, like <10, <20 etc
2. If that's different from the sorting you've done, you can categorise the current mode, like <25% completed, >25 and <50% completed. 

This would make sorting the data more helpful. Also do add some description of the feature as a tooltip, so the user knows what it is used for.

**Review by Rishitha1309 — APPROVED** [review]
PR working as expected
Filter OFF with this week
pr2410-3
Filter ON with this week
pr2410-2
Filter ON for three weeks
pr2410-1

**Review by MinSun0814 — DISMISSED** [review]
I can see the result correctly pops up after filtering the hour 
image

**Comment by gowthamdongari** [comment]
> Hi Gowtham,
> 
> The filter by hours is very vague to be honest, a tooltip would help with the description. But the code works. image
> 
> Some improvements that I suggest:
> 
> 1. Try to make it a dropdown filter, that sorts by a set number of hours, like <10, <20 etc
> 2. If that's different from the sorting you've done, you can categorise the current mode, like <25% completed, >25 and <50% completed.
> 
> This would make sorting the data more helpful. Also do add some description of the feature as a tooltip, so the user knows what it is used for.

Thank you for the suggestions! The tooltip feature is a great idea and will certainly help users understand the functionality better. As for the filter by 25% or less than 50% completion, it won't be necessary since anyone who has worked over 25% of their committed hours will receive a badge.

**Comment by gowthamdongari** [comment]
> > Hi Gowtham,
> > The filter by hours is very vague to be honest, a tooltip would help with the description. But the code works. image
> > Some improvements that I suggest:
> > 
> > 1. Try to make it a dropdown filter, that sorts by a set number of hours, like <10, <20 etc
> > 2. If that's different from the sorting you've done, you can categorise the current mode, like <25% completed, >25 and <50% completed.
> > 
> > This would make sorting the data more helpful. Also do add some description of the feature as a tooltip, so the user knows what it is used for.
> 
> Thank you for the suggestions! The tooltip feature is a great idea and will certainly help users understand the functionality better. As for the filter by 25% or less than 50% completion, it won't be necessary since anyone who has worked over 25% of their committed hours will receive a badge.

**Review by jinxyou — DISMISSED** [review]
The filter toggle works as expected. Great work! 
Screenshot 2024-07-06 175306
Screenshot 2024-07-06 175337

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
filter off
Screenshot (121)

filter on
Screenshot (122)

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected.

https://github.com/user-attachments/assets/081f664f-7172-4860-89c9-78907b7562b6

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected.
Screenshot 2024-07-20 at 5 38 40 PM
Screenshot 2024-07-20 at 5 38 44 PM

**Comment by souravwalke** [comment]
Tested the functionality and found a slight delay during toggle. The toggle button lagged before switching. Attaching the video for reference.

https://www.loom.com/share/b3e7fb410dda4041b4adad4171baea69?sid=0f957218-81c8-4a23-a080-a1eba9b64948

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and its working as expected with and without filter.


https://github.com/user-attachments/assets/e012d04d-7553-4aeb-ab25-1de21d424a45

**Review by angelalalacheng — APPROVED** [review]
Hi,
I use `Gowtham_Filter-By-over-Hours` for frontend and the latest development branch fir backend. Both Light and Dark mode work as expected.

Dark:
Screenshot 2024-07-21 at 3 27 09 PM
Screenshot 2024-07-21 at 3 27 35 PM

Light:
Screenshot 2024-07-21 at 3 29 04 PM
Screenshot 2024-07-21 at 3 29 26 PM

**Review by ishan-miglani — APPROVED** [review]
I have verified the changes in this PR. It works well in both light and dark mode. I am able to filter people who have worked over 25% over their hours. It also filters out people with zero set hours/ logged hours. Good work!

https://github.com/user-attachments/assets/2739acd5-a5a9-4a12-b949-8dc3211eaf47

**Review by Shadhrush5 — APPROVED** [review]
Hi, I reviewed PR #2410. I followed the steps as mentioned and the features works well. Thank you for the great work. I have attached a video below.


https://github.com/user-attachments/assets/8a2c0edc-d2d6-4540-a33f-4b9cf8eb1a81

**Review by Pranay-ai — APPROVED** [review]
The Functionality is Working as Expected

https://github.com/user-attachments/assets/2e3166b1-3194-48ad-8cc8-3b010331ddf2

Thank You

**Review by SaiLavanya1 — COMMENTED** [review]
Before applying the filter, the Weekly Summary Reports displayed all users regardless of their logged or set hours. After implementing the filter, it now correctly shows only the users who log over their set hours. The UI remained responsive, and no issues were encountered during the testing process.
Screenshot 2024-07-23 at 5 00 11 PM
Screenshot 2024-07-23 at 5 00 22 PM

**Review by kabraambika — APPROVED** [review]
I have tested the frontend pull request with the backend development branch. The filter is functioning correctly across all tabs. Please refer to the images below.
image
image
image

**Comment by arunsrao9** [comment]
I have tested the PR and it is working as expected.
Here are the Screenshots with and without the filter:
Screenshot 2024-07-26 at 10 47 01 AM
Screenshot 2024-07-26 at 10 46 54 AM
Screenshot 2024-07-26 at 10 46 41 AM
Screenshot 2024-07-26 at 10 46 34 AM

**Review by ReinaT5678 — APPROVED** [review]
The filter works well on my end! It correctly removes those who worked 25% over hours.

Here is the testing before the toggle is on: 
PR - # 2410

Here is the testing after the toggle is on:
PR - #2410 2

**Review by varunreddy03 — CHANGES_REQUESTED** [review]
I have tested this PR and I have observed that it worked as intended but it is also displaying users whose hours are set to 0 and logged hours more than zero. Please observe it in the images below.
And in Dark mode some of the text is not visible due to the dark blue color of the text, also please verify that from last images below.


PR 2410_1
PR 2410_2
PR 2410_3
PR 2410_4

**Review by SatyashanthiT — APPROVED** [review]
I have reviewed the frontend PR related to the dev backend. The main changes include fixing the filter for people with zero set hours and ensuring the filter ignores zero logged hours. I tested the functionality, and everything works fine, but there is a slight lag when toggling the filter. 

https://github.com/user-attachments/assets/f98e1769-c53c-4bf7-8b0b-b8ac89fd8378

**Comment by Gmon-k** [comment]
I have tested as per the PR and it is working fine

**Review by adityasure9 — APPROVED** [review]
Tested the PR with both the filter on and off. The filter works as expected, excluding users with zero set hours or zero logged hours when turned on. There’s a slight delay when toggling the filter, but overall the functionality is solid. Also, the tooltip addition is a great enhancement. 

With filter,



Without filter,

**Comment by Lemonnycodes** [comment]
Hi Gowtham,
I have tested the PR and the "Filter by over hours"  feature in the Weekly Summary Reports correctly ignores users with zero hours, and the page functions without any issues. 
PR 2410 (1)
PR 2410 (2)

**Review by SnelPatare — APPROVED** [review]
The changes are working as expected. But, it took time to enable filter over hours and load data. 
Please find images below. 
image

**Review by vedantg24 — APPROVED** [review]
Tested the PR, and the filter by over hours is working perfectly fine. Also, it works fine in dark mode with all the text visible.

https://github.com/user-attachments/assets/4e608b6b-647b-436e-bfda-f32ee1c1c524

**Comment by gowthamdongari** [comment]
> I have tested this PR and I have observed that it worked as intended but it is also displaying users whose hours are set to 0 and logged hours more than zero. Please observe it in the images below. And in Dark mode some of the text is not visible due to the dark blue color of the text, also please verify that from last images below.
> 
> PR 2410_1 PR 2410_2 PR 2410_3 PR 2410_4

the requested changes are already there please review again

**Review by ashayk9 — APPROVED** [review]
I have tested the pull request, and the "Filter by Over Hours" feature in the Weekly Summary Reports correctly excludes users with zero hours.
Screenshot 2024-09-06 at 11 38 24 AM
Screenshot 2024-09-06 at 11 38 54 AM

**Comment by sud306** [comment]
Hello,
I reviewed this PR and it works as expected.

5  PR2410_1
5  PR2410_2

**Review by yashwanth170 — APPROVED** [review]
Everything is working as expected. I am attaching before and after the changes SS.
after:
over_time_hours
before:
over_time_hours_before

**Comment by swaroop-2007** [comment]
@gowthamdongari 
I reviewed this PR, and it is working as expected. 
Screenshot (364)

After filtering by over hours
Screenshot (365)

**Review by swaroop-2007 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
