### PR TITLE
Jacky fix remove user from task

### PR DESCRIPTION
**Pull request by winghojackyli**
# Description
Fix: After clicking the “remove user from task” button on the modal, it works but the modal does not close by itself. 

## Related PRS (if any):
N/A

## Main changes explained:
- Remove loading useState in TaskCompleteModal.jsx
- Use react-toastify to notify data has been updated
- Close the modal after confirm removal of user from task

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ Team Member Tasks
5. look for a test user which has task(s) assigned
6. click the red 'x' button on the task under the user to see the changes

### Before: 
User can be deleted from the task, but there is no toast shown whether the deletion is successful. The loading modal cannot close itself. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/b379989b-6280-449d-92f0-a41ce0b92732

### After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/5d3a3a8d-90cd-4779-87ca-8e2ff0b5492b

### How to create task under project and assign user to the task

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/c5316a1a-38db-4ab5-ac4f-e69d09786974

### CODE REVIEW

**Review by Sssky-18 — APPROVED** [review]
Hi @winghojackyli, I just checked this fix. The popup worked well with correct text inside, and the modal closed itself. Also, the task was removed successfully. Thank you for your contribution! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/79791cc8-7d51-4c82-b60d-8e55938bc164

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR and it works as expected. I tested by trying to check if the task was removed in dashboard, profile, task page, and it was removed in all of these pages. I'm attaching a screen recording of test.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/6b9dc503-586f-407a-88fc-0e4891760523

**Review by DavidC0126 — APPROVED** [review]
Hi @winghojackyli, I tested your PR and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/66d08c1b-6ae7-4cd1-9765-27762a222d45

**Comment by astrjc0326** [comment]
Hi,
I tested your PR and it works well! 

Uploading firstPR.mov…


Uploading Screen Recording 2023-09-18 at 9.41.34 PM.mov…

**Review by Chris33871 — APPROVED** [review]
Hi @winghojackyli ,

I've reviewed the changes and everything seems to work fine 👍 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68507104/4798f173-4eda-48b5-9286-243264396253

**Review by tsunami776 — APPROVED** [review]
Hi @winghojackyli , I tested your PR and now the prompt modal closes after user confirm deleting a task. The toast notification also works as described. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/4d16c85d-21cd-4d0c-8265-638ea1de41f3

**Review by navneeeth — APPROVED** [review]
Hey @winghojackyli! Tested your changes and they work as intended: I do not see the 'Loading...' text in the modal after attempting to remove the task from an user. The task gets removed successfully. Good implementation! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/745d56d0-d6ff-47a0-9340-d16397d68272



Your tutorial on creating a task for users under a WBS for a project proved useful in following the steps of this PR. Thank you!

**Review by Bhagyashree444 — APPROVED** [review]
Works as intended. Great Job!
I was able to "Create WBS" only from owner account and not from administrator account. 

PR #1310

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/0b4a6959-98b1-4ccb-bd6c-122d93dcdda6

**Review by iTvX — APPROVED** [review]
I tested your pr, it worked as expected, but it is very slow on my end.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/0c72c840-9446-4b7d-9321-5426eae37fa6

**Comment by one-community** [comment]
thank you everyone, merging!

**Pull request merged**
