### PR TITLE
akshit added warning when team already exists

### PR DESCRIPTION
**Pull request by akshit0211**
# Description
Screenshot 2024-07-29 at 8 58 36 PM

## Related PRS (if any):
This frontend PR is related to the development backend.

## Main changes explained:
Updated code logic in this file src/components/Teams/CreateNewTeamPopup.jsx.

## How to test:
1. Check into the current branch.
2. Do `npm install` and `...` to run this PR locally.
3. Clear site data/cache.
4. Log in as owner/admin user.
5. Go to Other Links→ Teams→ Create Team.
6. Verify that you can see a warning when the team name already exists. 

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/98d3b094-96ae-46a8-8357-298b566098ce

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (157)
Screenshot (158)

**Review by vijay10pk — APPROVED** [review]
All the changes are working as expected.
image

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Review by Pranay-ai — COMMENTED** [review]
Hey @akshit0211 
The PR Is Expected , but when i try to enter the same team name without white spaces it still gets accepted, to avoid confusion between team name's it would be better before comparing the team names remove all the white space
Thank You.

**Comment by Gmon-k** [comment]
I have tested from my side and below is the screenshot of it. It is working fine

**Review by gowthamdongari — APPROVED** [review]
Works as expected

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work!

https://github.com/user-attachments/assets/e4c373a1-e79a-46d3-b0ce-285a2588d0c4

**Comment by jayyy-s** [comment]
Warning is there for me when adding a team that doesn't exist, looks good to me.
image

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and it's working as expected.


https://github.com/user-attachments/assets/7d4a3097-a98c-4f27-81ca-b31617aeb3ab

**Review by Gauravmg6 — APPROVED** [review]
It's working as needed.

Screenshot 2024-08-03 184041

**Review by jinxyou — APPROVED** [review]
The team already exists warning is working fine. Great work!
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
