### PR TITLE
Kaikanes lessonform update

### PR DESCRIPTION
**Pull request by lacnoskillz**
# Description
Integrated backend post route to the front end page. Now users are able to post new lessons on the front end using the lessonForm. 

## Related PRS (if any):
This frontend PR is related to the  https://github.com/OneCommunityGlobal/HGNRest/pull/716 backend PR.

## Main changes explained:
- Create lessonActions
- Updated schema to hold the files and allowedRoles feilds
- Update lessonForm.jsx to dispatch action
- Imported toast to display success/error/info

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard -> bmdashboard -> log in again -> bmdashboard/lessonform 
6. verify function submitting lessonform creates it in the backend
7. also check project specific form
8. go to bmdashboard -> select a project from the dropdown -> click 'Go to Project Dashboard' -> click 'Lessons' button
9. verify this functions the same too

## Screenshots or videos of changes:
bmdashboard/lessonform/

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/6a0d58d7-4967-4f71-90fe-57643f24f2a1

bmdashboard/lessonform/:lessonId

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/8e3f3837-0b82-430b-8e2f-d9e5a6d3322e

## Note:
The bmdashboard styles seem to be messed up. (unrelated to this PR)
image

Need auth token and set header to see backend in insomnia/postman

GRAB TOKEN IN APP FRONT END LOCAL STORAGE
image
 HEADER (I use insomnia)
image

### CODE REVIEW

**Comment by Cavein254** [comment]
@lacnoskillz , tested the pr and everything works as intended

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/40254b43-0d14-4310-a1be-bc0b79f11a68
Screenshot 2024-01-27 132100

**Review by abdel-lall — APPROVED** [review]
Works as described. Good job!

Screenshot 2024-01-27 163433

Screenshot 2024-01-27 163701

**Review by X1aoZhang99 — APPROVED** [review]
Hi Kaikanes, 

I tested your PR with BE #716, all functionalities worked as intended. Please refer to the video. 

### Submit Lessonform

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/c47a244e-1f00-4b46-8efd-4a1a38257bf7

Screenshot 2024-01-28 at 18 32 39

### Project Specific Form

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/b87732b0-758e-490e-8307-28ecee79c430

Screenshot 2024-01-28 at 18 35 14

**Review by Renanluizssx — COMMENTED** [review]
Hi @lacnoskillz, i tested your endpoint in the insomnia but i didn't get to put the userid, see my review:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/f7cca1b5-dab4-4efe-abbe-42cd4edd9b66

**Comment by lacnoskillz** [comment]
Hey @Renanluizssx thanks for the review. 
Not sure why your edit isnt working. it was working for me and i as able to edit your lesson you created. maybe try clicking send a couple times sometimes it bugs out.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
