### PR TITLE
clemar update team list after adding or removing team 

### PR DESCRIPTION
**Pull request by ClemarNunes**
# Description
PR

## Related PRS (if any):
This frontend PR is not related to any backend pr.

## Main changes explained:
-Updated numberOfTeams  e numberOfActiveTeams   in Teams.jsx:  fix a bug that occurred when adding or removing teams, where the team counter was not being updated correctly.
-Added sortTeamsByModifiedDate() a addNewTeam e onDeleteUser: to update the team list

## How to test:
1. check into current branch
2. do npm run start:local to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links→ teams
6. Create New Team
7. Check if when adding a new team, "Teams" and "Active Teams" are updated correctly.
8. Verify if when adding or removing a team the team list is updated.

## Screenshots or videos of changes:
before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/2b24f03d-7064-48b5-8c22-1a5ea51cf8a7

after:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/5359779c-eabc-4421-8fd4-e2d46406fe12

### CODE REVIEW

**Review by linkhanthtel — DISMISSED** [review]
"Teams" and "Active Teams" are updated correctly after adding a new team. The team list is also updated. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/f4286103-7224-4acd-a46e-35e82de4d0d9

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account and all mentioned features worked. I can add/delete team and see it takes effect in the teams list immediately. Good work!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/3594bbb0-629e-4a99-a4da-f136a8f08436

**Review by MinSun0814 — COMMENTED** [review]
Hello. I found two small issues when testing.

When adding a new team to the list and then searching for it. After deleting the newly added team, the team sometimes reappears briefly before finally disappearing. Also, the list did not revert back to its original state when empty out the search bar. Instead, it continued to display the old search results.

I've attached a video that demonstrates the two issues I encountered while testing the feature.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/5fc73de6-1f31-4f8a-bb42-1896a46964c0

**Review by Ramaruva — DISMISSED** [review]
I have checked the changes in my local env and they working fine

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/9c07f90d-7a29-4ffd-b61e-959221458a33

**Review by curiousfancier — DISMISSED** [review]
loged in as admin user in the dashboard navigated to  Other Links from there to teams
Create New Team successfully Checked if when adding a new team, "Teams" and "Active Teams" are updated correctly. Verified if when adding or removing a team the team list is updated.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/27274513/64b57c39-bd8d-4e70-9a14-e057e92b6fe4

**Review by hbodgal — DISMISSED** [review]
image
image
image
image

It works well!

**Review by Sandhya1236 — DISMISSED** [review]
I checked out the current branch, ran npm install and npm run start:local to set up the PR locally, and cleared the site data/cache. I logged in as an admin/owner/mentor/manager user and navigated to the dashboard → Tasks. I verified that the three multi-select filters for Team Names, Team Codes, and Color (WeeklySummaryOptions) functioned correctly. Additionally, I confirmed that this new feature worked as expected in dark mode. All tests were successful, confirming the proper functionality of the filters and their compatibility with dark mode.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/0f2b00e3-e47e-40aa-bc59-39fb722b6ab5

**Review by peter6866 — DISMISSED** [review]
Great work on implementing the immediate update for team list. The changes work as expected.

https://www.loom.com/share/370397dcc5c14323b10348f162753e12?sid=46bf5c4b-4673-45f9-8b1e-c24fc631adda

**Comment by kylepham** [comment]
Hi @one-community, this problem has been solved in the latest `development` branch, so this PR won't be necessary any more. Please refer to the video below. 

I'll close this PR, but feel free to re-open if you spot something related to this problem on your end, and I'll take care of it. Thank you.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/4b4a4377-8bf8-4656-9515-de81073e43f0

**Pull request closed without merging**
