### PR TITLE
Shihao - Loading Unit Test

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Create unit test for common/loading.jsx 

## Main changes explained:
- Add test id for loading

## How to test:
1. check into current branch
2. do npm install
3. do npm test Loading.test.js to run the test
4. Verify that all 2 tests have passed

## Screenshots or videos of changes:
Screenshot 2023-11-15 at 17 12 18

### CODE REVIEW

**Review by tsunami776 — APPROVED** [review]
Hi @sxiong5, your unit test looks good to me. I ran your unit test locally and all tests passed. Nice work!
CleanShot 2023-11-15 at 23 33 41

**Review by pika-chu11 — APPROVED** [review]
Hi @sxiong5 , tested and it passed on my end! Good job!
PR 1540

**Comment by beblicarl** [comment]
All tests passed and the code is great

image

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great work! 

PR 1540

**Review by StrawberryCalpico — APPROVED** [review]
Screen Shot 2023-11-18 at 4 40 46 PM
Hi tested your PR, great work

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
