### PR TITLE
Jerry - Unit test NewRolePopUp.jsx

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
Create unit tests for `src/components/PermissionsManagement/NewRolePopUp.jsx`

## Related PRS (if any):
N/A

## Main changes explained:
- Added a new file: `src/components/PermissionsManagement/__tests__/NewRolePopUp.test.js`

## How to test:
1. On the `development` branch of HGNRest (backend), run the server by running the following command: `npm i && npm run build && npm start`
2. check into current branch on HighestGoodNetworkApp (frontend).
3. do `npm install`
4. Run `npm test NewRolePopUp.test.js` to run the unit tests

## Screenshots or videos of changes:

Screenshot 2024-03-17 at 6 21 01 PM

### CODE REVIEW

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.

PR 2072

**Review by Abi-Liu — APPROVED** [review]
Looks good! Tests are all passing.

Screenshot 2024-03-18 at 2 36 01 PM

**Comment by dhairya-mehta** [comment]
Hey Jerry, I tested out the functionality, all 5 test cases passed, good job!
image

**Review by ImzIssa — APPROVED** [review]
Hello, I've tested your PR and all test cases pass. 

PR#2072

**Review by Pandani07 — APPROVED** [review]
All the test cases passed, I've attached a screenshot.
Screenshot 2024-03-20 at 1 21 27 PM

**Review by Tiantian-C — COMMENTED** [review]
All the tests have passed!
Screenshot 2024-03-23 at 2 31 20 PM

**Review by sameersdeshpande — APPROVED** [review]
Hello @jerryren527 
I tested this as per instructions and was able to pass the tests.
Approving
Screenshot 2024-03-23 at 6 29 36 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 30 - PR3

**Review by navneeeth — APPROVED** [review]
Hello, @jerryren527! The test cases are all passing:
test cases passing

Good use of mockStore, thunk, and the Provider to set up the renderComponent and the mock server! The tests to: 
- Render NewRolePopUp component
- Render PermissionList child component
- Create button on click dispatches action to store
- Error message appears when adding a duplicate role (particularly where you await a change in text after changing the role input)
are all great! Approving! LGTM!

**Pull request merged**
