### PR TITLE
Lucas fix another user dashboard

### PR DESCRIPTION
**Pull request by Lucas-E**
# Description
(PRIORITY MEDIUM) Jae: Fix viewing another person’s dashboard view of header  (WIP Lucas)
Leaderboard → Click dot by person’s name
This view should show the other person’s dashboard completely… right now it still shows the header like the viewer of the dashboard. I want an anyone who clicks those dots to see exactly what they see
The exception should be that non Admin/Owner accounts shouldn’t be able to interact with the other person’s header options. An Admin/Owner account SHOULD be able to though… as if they were that other person. 
Need this for diagnosing problems

## Main changes explained:
Now, when viewing another user's dashboard, the view of the header will match what the user would see with some minor differences.

1. Owner/administrator users viewing another user's dashboard will be able to interact with the timer, reset password, visit the timelog window and other things.
2. Non Owner/administrators should only be able to see the header, the timelog page and the profile page
3. On the timelog page, on the tasks tab, the tasks should match the viewed user's tasks
4. When interacting with the timer, the tasks/projects should match the viewed user's tasks/projects

## How to test:
1. check into current branch
5. do `npm install` and `...` to run this PR locally
6. log as Owner/administrator user
7. On the Leaderboard, click on the dot on the left side of the user's name
8. See if the header matches the viewed user's header with the explicitated cases
9. log as non Owner/administrator user
10. See if the header matches the viewed user's headers with the explicitated cases

## Note:
Please make sure to see if everyting works as it should on the authenticated user's dashboard and on the viewed user's dashboard.

### CODE REVIEW

**Comment by freecode23** [comment]
Hi, can you help me clarify things: 
Question1: how do I actually see another user's dashboard?
Is the below video how you do it?
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/a95fb8a3-5c25-4893-8118-c8291d049873

Question 2: Which is the timelog page and the profile page?

**Comment by Lucas-E** [comment]
> Hi, can you help me clarify things: Question1: how do I actually see another user's dashboard? In the video below I want to access Aaron Admin's dashboard. I am already logged in as owner. Is this how you do it?
> 
>  Screen.Recording.2023-07-13.at.8.03.06.PM.mov 
> Question 2: Which is the timelog page and the profile page?

Just edited the instructions to make it more clear. Added a part that says how to visit another user's dashboard. Any further questions please DM me on Slack!

**Comment by iTvX** [comment]
I believe I have tested it as requested and encountered no issues. The first account I logged in with was the administrator account, and the second one was the volunteer account. Please let me know if do wrong.
Admin:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/42c82d7f-1b21-4660-a679-842b0d56441b

Volunteer:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/ee8735b7-4cb8-4497-a53e-9b298b09baf1

**Review by xaanders — CHANGES_REQUESTED** [review]
Hi Lucas! 
I have tested you PR. 

- logged in as an admin and clicked to view manager's dashboard: 





- I could interact with the dashboard and change the profile information: 



adding tangible time: 



couldn't change Owner's profile information, but could interact with his dashboard: 



- logged in as a manager and couldn't interact with volunteer's dashboards or profile information:



but I could submit their weekly summary by clicking on the clock: 




- and I could do the same with volunteer account:

**Review by cvtqx — DISMISSED** [review]
1. **When logged in as admin** and clicked on a user's account, I was able to add a time entry for that user, add weekly summary, change password, assign a team. 

Submitting time entry:
Submitting time entry

Assigning a team:

assigned team

User's tasks were matching those in their timelog:

tasks in timelog

Submitted weekly summary for that user. (Sidenote - After submitting the page needs to be refreshed for the green checkmark to appear on top):

weekly summary submitted but no checkmark

2. **When logged in as volunteer or manager** and checking another user's dashboard I was not able to interact with anything BUT I was able to update user's weekly summary:

updating weekly summary as manager

**Comment by Lucas-E** [comment]
> I believe I have tested it as requested and encountered no issues. The first account I logged in with was the administrator account, and the second one was the volunteer account. Please let me know if do wrong. Admin:
> 
>  1.mp4 
> Volunteer:
> 
>  2.mp4

The videos have no image here. Can you see the videos?

**Comment by Lucas-E** [comment]
> Hi Lucas! I have tested you PR.
> 
> * logged in as an admin and clicked to view manager's dashboard:
> 
> 
> 
> 
> 
> * I could interact with the dashboard and change the profile information:
> 
> 
> 
> adding tangible time:
> 
> 
> 
> couldn't change Owner's profile information, but could interact with his dashboard:
> 
> 
> 
> * logged in as a manager and couldn't interact with volunteer's dashboards or profile information:
> 
> 
> 
> but I could submit their weekly summary by clicking on the clock:
> 
> 
> 
> * and I could do the same with volunteer account:
> 
> 

The problem with the clock is out of the scope of this PR. Please specify what changes you think I should be making.

**Comment by Lucas-E** [comment]
> 1. **When logged in as admin** and clicked on a user's account, I was able to add a time entry for that user, add weekly summary, change password, assign a team.
> 
> Submitting time entry: Submitting time entry
> 
> Assigning a team:
> 
> assigned team
> 
> User's tasks were matching those in their timelog:
> 
> tasks in timelog
> 
> Submitted weekly summary for that user. (Sidenote - After submitting the page needs to be refreshed for the green checkmark to appear on top):
> 
> weekly summary submitted but no checkmark
> 
> 2. **When logged in as volunteer or manager** and checking another user's dashboard I was not able to interact with anything BUT I was able to update user's weekly summary:
> 
> updating weekly summary as manager

Thank you for the review! If the changes match the task specifications, please approve the PR so it can be moved to final review!

**Comment by Jiangwei-shi** [comment]
When I log in as Adm. I can view another user's dashboard and will be able to interact with the timer, reset the password, visit the time log window, and other things. good job!
image
image
image

**Review by HectorAgudelo — APPROVED** [review]
Everything works as expected. Users are able to see other profiles, but admistators/owners could manipulate features volunteers can't.
PR#991-clickDot
PR#991-administrator
PR#991-volunteer

**Comment by freecode23** [comment]
Thank you for the clarification. I have done several tests. Can you clarify if these 2 behaviours are intended?
If so, then everything else works as intended
Test 1: As Owner I need to first click start or refresh the page to make the timer reflect the actual Volunteer’s timer. Is this intended ?
See video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/9945024e-db5b-4331-ba19-b2a38301aff5

Test 2: Manager and volunteer cannot see other users in leaderboard. Is this intended ? See photo below:
vol
man

**Comment by Lucas-E** [comment]
> Can you clarify if these 2 behaviours are intended? If so, then everything else works as intended Test 1: As Owner I need to first click start or refresh the page to make the timer reflect the actual Volunteer’s timer. Is this intended ? See video below:
> 
>  Screen.Recording.2023-07-14.at.8.34.28.PM.mov 
> Test 2: Manager and volunteer cannot see other users in leaderboard. Is this intended ? See photo below: vol man

1. This question would be better treated on a PR regarding timer behavior when viewing another user's dashboard
2. This question is out of the scope of this PR, I think asking Jae would be better.

If it works as expected, please approve the PR.

**Comment by Lucas-E** [comment]
> When I log in as Adm. I can view another user's dashboard and will be able to interact with the timer, reset the password, visit the time log window, and other things. good job! image image image

Thank you! Could you approve the PR if everything works fine?

**Comment by Lucas-E** [comment]
> 1. **When logged in as admin** and clicked on a user's account, I was able to add a time entry for that user, add weekly summary, change password, assign a team.
> 
> Submitting time entry: Submitting time entry
> 
> Assigning a team:
> 
> assigned team
> 
> User's tasks were matching those in their timelog:
> 
> tasks in timelog
> 
> Submitted weekly summary for that user. (Sidenote - After submitting the page needs to be refreshed for the green checkmark to appear on top):
> 
> weekly summary submitted but no checkmark
> 
> 2. **When logged in as volunteer or manager** and checking another user's dashboard I was not able to interact with anything BUT I was able to update user's weekly summary:
> 
> updating weekly summary as manager

Please specify what changes I should be delivering.

**Review by shiva2096 — DISMISSED** [review]
Hi @Lucas-E 

Great job! Changes are working as described in the PR.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/7d5c5139-d1a9-46a9-acf4-42c46550f79c

**Comment by one-community** [comment]
> Test 2: Manager and volunteer cannot see other users in leaderboard. Is this intended ? See photo below:

The should (only) be able to see other users on their team. If not on a team, they'll only see themselves. Is that the behavior you are getting Sherly?

**Review by DavidC0126 — DISMISSED** [review]
Hi @Lucas-E, I tested your PR and everything works as described! 

-  When I logged in as admin user, I was able to add a time entry for that user, add weekly summary report, change password, assign a team and a task project.
- Normal volunteer user can see the profile but not able to modify those features.

Screenshot 2023-07-20 at 12 40 17 PM
Screenshot 2023-07-20 at 12 44 27 PM
Screenshot 2023-07-20 at 12 45 54 PM
Screenshot 2023-07-20 at 12 49 22 PM

**Review by ramyaram2092 — COMMENTED** [review]
Hello @Lucas-E  the functionality works great. 
I was able to  do the following functionalities
1. open another user's dashboard 
2. start/stop timers
3.  adding tangible times
4.  open the dashboard of other team members while being in the dashboard 
5.  Update profile 

**Possible Issue:**
**Steps to produce :**
1.  Log into Owner account  
2.  open a manager user (which opens in a new window altogether)
3.  From  the  manager dashboard try opening another team member 's dashboard (possibly a volunteer)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/a8239ce2-6917-4c38-9d4b-f37179ad7fa5


**What i see? :** 
The volunteer dashboard overrides the manager dashboard and there is no way to switch back to the manager dashboard .
Is this an expected behaviour ?

**Review by eduvarjaor — APPROVED** [review]
I tested this PR and works as intended.  Great job! 

Admin:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/f4a1d199-9807-4805-b18b-e9615655411e

Volunteer:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/a16780a4-ac85-4b70-aaef-4235250603ee

**Comment by Lucas-E** [comment]
> Hello @Lucas-E the functionality works great. I was able to do the following :
> 
> 1. open another user's dashboard
> 2. start/stop timers
> 3. adding tangible times
> 4. open the dashboard of other team members while being in the dashboard
> 5. Update profile
> 
> **Possible Issue:** **Steps to produce :**
> 
> 1. Log into Owner account
> 2. open a manager user (which opens in a new window altogether)
> 3. From  the  manager dashboard try opening another team member 's dashboard (possibly a volunteer)
> 
>  PR-991.mp4 
> **What i see? :** The volunteer dashboard overrides the manager dashboard and there is no way to switch back to the manager dashboard . Is this an expected behaviour ?

The question about opening another user's dashboard while viewing another user's dashboard is out of the scope of this PR. But, I think it works as it should. If you have no more questions, please approve the PR so I can move it to final review!

**Review by ramyaram2092 — APPROVED** [review]
Approving the PR on the same note

**Comment by Lin1404** [comment]
Hi @Lucas-E, I have tested your PR, it works well!
image

Added tangible time:
image

**Review by yunshan111 — APPROVED** [review]
Tested this PR, LGTM!

**Pull request merged**
