### PR TITLE
Yiyun - complete the configuration

### PR DESCRIPTION
**Pull request by EvianTan**
# Description
This PR is one one the ESLint PR series.
It's for the below purposes:
1. run Prettier as one of the ESLint rules
2. add Husky lint check as pre-commit check
3. update the GitHub action
4. make sure current repo is lint error-free 
image

## Related PRS (if any):
N/A

## Main changes explained:
- `.eslintignore`, `.prettierignore`: update the files ignored by ESLint and Prettier
- `.eslintrc.js`: update ESLint rules to be more strict
- `.github/workflows/node.js.yml` update the github workflow action
- `.husky/pre-commit`: add Husky lint check as the pre-commit check
- `package.json`: update the lint check commands
- `public/config.js`: removed cause no need anymore
- `Utils/index.js`: removed cause no need anymore
- other changes are done by running `npm run lint` as the first time

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any user
4. verify no functionality break because of this PR

## Screenshots or videos of changes:
Below images show run the commands `npm run lint` and `npm run lint:fix`
image
image
Below image shows when commit your changes, it will automatically check if your changes are lint error-free.
image

## Note:
Ref: https://www.youtube.com/watch?v=ZXW6Jn6or1w

### CODE REVIEW

**Review by ramyaram2092 — APPROVED** [review]
Hello @EvianTan 
I dont see any functionalities issues so far . I tested the following functionalities 

### **Volunteer , Admin, Manager, Owner, Mentor:** 
1. Start/stop timer
2. Update profile
3. Update password
4. Badge Management->Assign Badge
5. Add weekly summary

### **Admin & Owner**
1.  User Management
2.  Weekly Reports
3.  Create/Delete New Task 
4.   Create/Delete New project
8.  Open the dashboard of another user from dashboard page and log time /update profile

**Review by yaow62023 — APPROVED** [review]
Hi, I have tested Volunteer role, Administrator role, Core team, Manager and Mentor. The features I tested are: time log, weekly summary, profile page, report and dashboard. All the features are works great. Good Job!

**Comment by igorrochadasilva** [comment]
Hi @EvianTan !
I hope you are well =D 

I've tested your PR, the  Volunteer role, Administrator role,

Administrator role
Team
1. Create team
2. Add members to the team
3. Update team

Projects
1. Create new project
2. Add member to the project.
3. Create new WBS
4. Create new task
5. Update task

User Management
- Update volunteer user

Other functions
1. Start/stop timer

Volunteer role

Profile
1. Update profile

Other functions
1. Start/stop timer
2. Week summary
3. View task

**Review by shiva2096 — APPROVED** [review]
Hi @EvianTan 

I have tested the following functionalities and nothing breaks. Great work !

For Volunteer , Admin, Manager, Owner and Mentor:

- Start/stop timer
- Update profile
- Update password
- Assign Badge
- Add weekly summary

For Admin & Owner

- User Management
- Weekly Reports
- Create/Delete New Task
- Create/Delete New project
- Update any user's profile

**Review by joyceiphone — APPROVED** [review]
LGTM.
Tested the following. User/Admin: Add task/Badge assignment/add summary/timer/dashboard/project management/user management.
Run npm run lint: no code changes.

**Review by vemanamadhu — APPROVED** [review]
I logged in as the admin, volunteer and tried a bunch of things. The functionality seems to be working fine everything works well

**Review by n0vay — APPROVED** [review]
Everything works perfectly, Good Job!
image

**Comment by Lin1404** [comment]
Hi @EvianTan, I logged in as the mentor, volunteer and coreteam and tested. Everything works well.

image
image
image

**Review by Lin1404 — APPROVED** [review]

**Comment by beblicarl** [comment]
Everything works perfectly, I tested it with my Admin, Owner, Manager and Volunteer accounts. Great work

**Review by beblicarl — APPROVED** [review]

**Review by eduvarjaor — APPROVED** [review]
Hi @EvianTan 

I tested this PR and everything is working well. Good job!

Screenshot_1
Screenshot_2

**Comment by one-community** [comment]
Thank you everyone, merging this

**Pull request merged**
