### PR TITLE
Tareq- Add Map Component Table

### PR DESCRIPTION
**Pull request by TareqMia**
# Description
Screenshot 2024-04-20 at 11 48 13 PM

## Related PRS (if any):
Use the Development backend to test this PR.

## Main changes explained:
- Created a new component for the TeamLocations page for easier viewing of team members, their locations, and their current status. 

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as any user
5. go to dashboard→ Reports→ Team Locations 
6. Verification: 
  
  #### Toggling Table Visibility:
  * verify that there is a table icon next to the text “Total Countries” 
  * Clicking the table icon will display the table, and clicking it again when the table is shown will make it disappear
  
  #### Table Functions:
  * When the table is visible, verify that you can scroll through the list of users. By default, all active users will be shown first 
  * Select the different table headers and verify that the sorting works properly. Pressing “Team Member” or “Location” will sort in ascending order and then descending. Pressing the user icon will reset the sorting 
  * Searching
    *  verify that pressing the search icon will show the search bar. In this search bar, you should be able to search by a user’s name or location, all case-insensitive 
    * pressing the search icon while the search bar is visible should make it disappear 
    * sorting functions should work when searching from a subset of all users
  * When selecting a user, the map should pan to the user’s location, with a popover open displaying the user’s name, title, and 	location
  * if the table is not visible and the user is zoomed into the map such that all popovers are open, toggling the table visibility should make the popovers disappear. Toggling the table to be visible will make the popover markers reappear again (if the zoom level did not change) 
  

  #### Table Layout: 
  * changing the size of the window/screen should also change the table size. if the width of the screen is less than 350px, the table will not be visible at all

 #### Dark Mode: 
  * Verify that when in dark mode, the map background changes color and that the table is still visible

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/2923c141-e218-4640-81cd-494b1353b5c8

## Note:
Please test thoroughly and let me know if there are any improvements that can be made

### CODE REVIEW

**Review by MinSun0814 — APPROVED** [review]
image
The new location table looks really good and the search works! Nice work!

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and the new functionality is working as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/66c39880-e567-4c7b-9369-5ea75f7b0ec1

**Review by linkhanthtel — APPROVED** [review]
I reviewed your PR and everything work as expected! One thing, it would be nicer if 'Edit User Profile' component is also in dark theme. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/ee795cd8-7227-4a53-9839-478da4fce639

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great as well

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.05.09-17_50_44.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/52c3d89c-c2a4-43c3-8ae0-321307ccf8d2)

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
