### PR TITLE
Navneeth create see teams management tab custom permission

### PR DESCRIPTION
**Pull request by navneeeth**
# Description
feature description

## Related PRs:
This PR is linked to the BE PR [#556](https://github.com/OneCommunityGlobal/HGNRest/pull/556).

## Main changes explained:
- Employing consistent naming of permissions in `src/utils/routePermissions.js`.
- Deciding that when a volunteer account has the `See Teams Management Tab (Create Teams and edit team members only)`, then the account will be able to add teams and add/delete members. 
- Rendering the UI according to the permissions wherein an account with just the `See Teams Management Tab (Create Teams and edit team members only)` permission will not be able to delete teams and edit team names.
- Updating the permission description for the `See Teams Management Tab (Create Teams and edit team members only)` permission.

## How to test:
1. Follow the steps in the backend (BE PR [#556](https://github.com/OneCommunityGlobal/HGNRest/pull/556)) to run the relevant PR.
2. In the frontend, check into the current branch.
3. do `npm install` and `npm run start:local` to run this PR locally
4. Log in as Owner -> Dashboard -> Other Links -> Permissions Management -> Manage User Permissions
5. Enter the username of an account that does not have the `See Teams Management Tab (Create Teams and edit team members only)` permission. 
6. Next to `See Teams Management Tab (Create Teams and edit team members only)`, click on Add. Then scroll down and click on Submit.
7. Log in as the volunteer account (if already logged in, make sure to log out and log back in). The `Other Links` button should appear with ONLY the `Teams` option visible/accessible.
8. Verify that the volunteer account can add teams and add/delete members in the Teams Management page (Teams).

## Test Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/460d9abf-895e-4ed5-a85d-f2a8eedc98b2

### CODE REVIEW

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great Work. I tested your PR and it is working as expected. I tested by creating, editing, deleting team members from volunteer.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/f2f19c74-f221-46b8-bc6d-45897fb2854e

**Review by malikjahanzaib — DISMISSED** [review]
Hi @navneeeth, I have tested the Teams Management Full as well as Partial functionality as directed. Everything seems to work as intended. Great job!

Test rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/ddc624e3-8c8e-46cb-9abb-ccbb46a411ee

**Review by JYXiao-2021 — DISMISSED** [review]
Hi, I test this pr and it works as intended shown in the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/22df00e8-fa06-444c-a3e0-2a2326c7f098

**Review by StrawberryCalpico — APPROVED** [review]
Hi! I just reviewed the PR, it works as expected. Great job! I can assign the permission, create/edit team, and delete successfully. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/0d21e32e-264b-4402-b094-300cfe6335b6

**Comment by navneeeth** [comment]
> Hi I'm not able to create a new team, please take a look and let me know if anything:
> 
>  Screen.Recording.2023-10-10.at.11.26.02.mov

Hello, @RheaWu1212! Can you check if you have pulled the related backend PR? Seems to be an issue related to it. Please let me know. Thank you!

**Review by wantingxu7 — DISMISSED** [review]
Hi @navneeeth 
the PR works as intended, when given full permission and only create team permission, the buttons and functions are different and function well. Good work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/c0e02009-8cc9-4fca-ad59-4454f3205c04

**Review by Jiyuanxia — APPROVED** [review]
Hi @navneeeth , I have reviewed your pull request and tested it. It works as you intended. Well done!
assign permission
Screenshot 2023-10-12 224245
create a new team
Screenshot 2023-10-12 224337
edit a team
Screenshot 2023-10-12 224355
add team member
Screenshot 2023-10-12 224408

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/34743c63-ae14-4c9a-a947-27ec90a41425

**Comment by palakgosalia** [comment]
Hi, the PR looks good, I was able to do CRUD operations in the Teams section

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/338202c9-888b-4a53-a70e-e5c5b62e5108

**Review by sxiong5 — DISMISSED** [review]
Hey @navneeeth, I have tested the PR, and it worked well. Nice job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/9f5c858b-3b92-4259-b037-f45a3f698b52

**Comment by Lin1404** [comment]
Hi @navneeeth , I have test your PR, but I cannot add the team member in the volunteer user. Please check the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/d90a5fdc-8153-4437-bd12-e18eaad01447

**Comment by navneeeth** [comment]
> Hi @navneeeth , I have test your PR, but I cannot add the team member in the volunteer user. Please check the video:
> 
>  My.Movie.mp4

Hi @Lin1404! Thanks for your review. I tried to recreate your issue but for some reason, it's not being reflected on my end and works just fine. Can you try emptying the cache and doing a hard reload in the browser? Also, do an npm install before you run the backend and frontend code. I look forward to hearing from you once you have tested this to see if the bug persists. Thank you!

**Comment by Lin1404** [comment]
> > Hi @navneeeth , I have test your PR, but I cannot add the team member in the volunteer user. Please check the video:
> > My.Movie.mp4
> 
> Hi @Lin1404! Thanks for your review. I tried to recreate your issue but for some reason, it's not being reflected on my end and works just fine. Can you try emptying the cache and doing a hard reload in the browser? Also, do an npm install before you run the backend and frontend code. I look forward to hearing from you once you have tested this to see if the bug persists. Thank you!

Hi @navneeeth , thank you for the information. I have tried to retest and met the same problem. I have hard reloaded the browser, npm install FE, npm build BE. Please let me know if there is any other information you want to know.

**Review by ChirayuRai — COMMENTED** [review]
I tested your changes locally, and it seems that I cannot see the updated permissions in my volunteer account. The "other links" section does not appear, regardless of setting "full functionally", adding all the permissions, or both.

Chirayu Test permissions on Owner (before hitting submit)
Screenshot 2023-10-24 at 10 51 35 PM (2)

Chirayu Test dashboard after logging out and logging back in
Screenshot 2023-10-24 at 10 50 47 PM

**Comment by navneeeth** [comment]
> > > Hi @navneeeth , I have test your PR, but I cannot add the team member in the volunteer user. Please check the video:
> > > My.Movie.mp4
> > 
> > 
> > Hi @Lin1404! Thanks for your review. I tried to recreate your issue but for some reason, it's not being reflected on my end and works just fine. Can you try emptying the cache and doing a hard reload in the browser? Also, do an npm install before you run the backend and frontend code. I look forward to hearing from you once you have tested this to see if the bug persists. Thank you!
> 
> Hi @navneeeth , thank you for the information. I have tried to retest and met the same problem. I have hard reloaded the browser, npm install FE, npm build BE. Please let me know if there is any other information you want to know.

Hello again, @Lin1404! I see. Since the PR has worked as expected for the testers above and because there were no code changes in this PR ever since, I believe it's just a caching issue on your end. I tried it out now again and I can see the team members names being displayed when I search for them in order to add members to a team:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/1e2c3dec-a866-46e2-91d9-3fef3ddafb39

Also, when you say `npm install FE, npm build BE`, I want to ensure that we're on the same page:
### For the FE:
Switch to the `navneeth-create-see-teams-management-tab-custom-permission` branch if on VS Code.
In the terminal:
```
git pull navneeth-create-see-teams-management-tab-custom-permission
npm install
npm run start:local
```

### For the BE:
Switch to the `navneeth-create-see-teams-management-tab-custom-permission` branch if on VS Code.
In the terminal:
```
git pull navneeth-create-see-teams-management-tab-custom-permission
npm install
npm run build
npm run start
```

Please try again with the above steps and let me know. Thank you!

@ChirayuRai, Hi, thanks for your review. I suggest the same steps as above to recreate testing this PR. It is probably just a caching issue. Please try again and let me know. Thank you!

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Hey @navneeeth, I left a comment on the BE PR [#556](https://github.com/OneCommunityGlobal/HGNRest/pull/556).

**Comment by navneeeth** [comment]
> Hey @navneeeth, I left a comment on the BE PR [#556](https://github.com/OneCommunityGlobal/HGNRest/pull/556).

Hello! Just addressed your comment in the backend PR thread. Thank you!

**Review by tsunami776 — APPROVED** [review]
Hi @navneeeth, I tested your PR locally and it works as intended. I logged in as owner and can successfully change volunteer's permission to view and add teams. And as volunteer, I can view and add teams afterwards. Volunteer can also add and remove team member from the created teams. Great work!

Test video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/688f3aed-6f9a-400c-8390-271add3faa13

**Review by Shiwani99 — APPROVED** [review]
Hi,
I tested your PR. It works as expected. I am only able to create new team and add or delete team members. I tried to change the active status of the team and it didn't change. Great work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/326d810d-f5de-4e18-8d29-e952499a97ca

**Review by wantingxu7 — APPROVED** [review]
Hi @navneeeth ,
I've reviewed the updated version and the function works as intended. The volunteer can create team and add/delete member when granted the permission. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/579a3840-749d-412b-96d1-506ea9ef737c

**Review by shubhankarval — APPROVED** [review]
Hey @navneeeth, the PR is now working as expected, great job!
    
Gave permission to Volunteer account:
Screenshot 2023-12-03 181337
    
Create Teams functionality: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59073366/79e94daf-3fc0-483d-b3db-f0f2b61040c8

**Review by Alforoan — APPROVED** [review]
They all work. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/3cbd6689-a753-4095-89de-5b2ba84cc233

**Review by Pandani07 — APPROVED** [review]
Works great! I could add the see teams management tab for my volunteer user. And from my volunteer account, I could only see 'teams' under that tab. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/a85416d4-7e0c-489b-bcd1-19ff5ffa915f

**Review by XiaohanMeng — APPROVED** [review]
Hi, I tested this PR. After being granted permissions by the owner account, the volunteer account was successfully able to create a new team, add members, and delete members. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/ac2a722b-3fb7-4145-8234-149f057ee7fa

**Pull request closed without merging**
