### PR TITLE
Jiayu took this over from Miguel - User Suggestion Edit

### PR DESCRIPTION
**Pull request by Cloid**
# Description
image

## Related PRS (if any):
N/A

## Main changes explained:
- Updated SummaryBar.jsx to accommodate new "Edit" radio button and logic
- Update SummaryBar.css to have specialized styles for Edit list.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as Owner user. If you don't have one, I believe Jay can manually make one for you.
5. Under the dashboard, there should be five different icons at the top right side. Click on the lightbulb icon, "Suggestions Development"
6. Click on the Dropdown menu and verify the order. Example:
image

7. Click "Edit Category" button at top left of modal.
8. Click "Edit", a list of the dropdown options should appear as draggable boxes.
9. Click and drag on the white box to re-order them to any order you specifiy.
10. Click on the pencil-notepad icon at the top right of the white box to edit the text.
11. Click Submit to submit the changes to dropdown.

## Screenshots or videos of changes:

Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/9a2b5c53-64fe-470d-964c-cefc31b403a0

### CODE REVIEW

**Review by Sophie-lei — DISMISSED** [review]
Hey, I just tested this PR. The user suggestion can be edited and drugged successfully. Please see the video for more details.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/0cf0bb88-a371-469b-bdde-f0729b6cd8f0

**Comment by galgalinidhi** [comment]
Hi @Cloid, I tested the PR and it works as expected!



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/3fff003b-5ef6-4192-8d5a-c83602e2efa1

**Review by Pandani07 — DISMISSED** [review]
I could see the suggestions after clicking the lightbulb. I could then edit the suggestions, drag them, and reorder them, and even select a suggestion and then submit it. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/1d18e679-05d1-40fa-8b01-5eeae73e18a8

**Review by Nahiyan-16 — CHANGES_REQUESTED** [review]
## An small issue
Hi Miguel, testing your PR I was able to edit and drag options seamlessly using an owner account. This is a very cool feature and a very good user experience. I did however notice a small issue regrading the check button when editing an option. The user is able to delete the check mark by pressing backspace when clicking little to the left of the button. Check video below:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/d978f616-3983-44aa-8d33-b5af79e948ff

Otherwise, this is an awesome feature! Keep up the good work

**Comment by TareqMia** [comment]
Hey Miguel, I tested the PR with an Owner account and was able to drag/drop and edit the suggestions. Really good work on implementing this feature. However, as Nahiyan mentioned above, there is a small issue of the check mark being deleted by accident when editing a suggestion. I'm sure that it will be a simple fix. The screen recordings are attached for reference:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/76b8357a-30f7-4a30-81f4-720242eac201


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/b5c0a23f-523b-4acd-95a3-6138e154aaf0

**Review by n0vay — DISMISSED** [review]
Looks good to me
image

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Miguel,

I've tested your PR, and all functionalities worked as intended. The suggestion from the user can be modified and dragged as needed. For further details, please refer to the video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/06e2f678-6387-4c36-af46-fe46503724f8

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and all features worked as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/7d00cc07-fe73-48c6-82d1-e03e50528852

**Comment by Cloid** [comment]
@Nahiyan-16, @TareqMia thanks for the feedback on the bug. I believe I fixed it alongside other bugs I've found. Feel free to re-test it.

**Review by yaow62023 — DISMISSED** [review]
Hi, i have test your PR, all the function work as intended. Great Work!  
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/6182fd0a-1995-4ed3-95a6-6fb8743870f8

**Review by TapanPathak — DISMISSED** [review]
Hi, I just tested this PR. Everything works as expected! I can edit the suggestions, drag them, and reorder them. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/f76bb8ae-ffac-4275-b00d-cd12ea1756d7

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and all the functionalities are working properly. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/3c88ec73-4cc5-4e7c-a0dd-23786140c18c

**Review by XiaohanMeng — DISMISSED** [review]
Hi, I tested this PR and everything looks great on my end. I can edit categories and rearrange their order through dragging. Please see the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/0d07c7d5-4aaf-4b88-8d08-1b91cf62d855

**Review by Jingyii800 — DISMISSED** [review]
Hi, I tested this feature. It works well! I can drag the suggestions and reorder them, as well as edit and save them. Please check more details in the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/a246013c-d8fe-416e-809f-bf08c5f4e165

**Review by skaush21 — DISMISSED** [review]
* cleared cache
* logged in using owner account
* clicked light bulb
*  edited the suggestion options
* reordered the options
features match description, feature works.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/b22a3d26-5a29-4e3b-b18e-7cfaf89b627e

**Comment by dhairya-mehta** [comment]
Hey, I verified the working of all test cases, good job!
image

**Review by Nahiyan-16 — DISMISSED** [review]
Great job. Its fixed @Cloid

**Comment by MQChen211** [comment]
Hi, I tested your PR and it works as expected.

截屏2024-04-09 15 26 58
截屏2024-04-09 15 27 04
截屏2024-04-09 15 28 00
截屏2024-04-09 15 28 12

**Review by MQChen211 — DISMISSED** [review]

**Review by SRamen1999 — DISMISSED** [review]
Everything works as expected. I can edit the suggestions, drag, reorder, add and delete them.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/d2ad6c7c-fc6f-4a74-aafe-9c5fc0a8786d

**Review by anandsesha — DISMISSED** [review]
Hi, I have tested this PR, and the feature works as expected. I can edit an existing option, drag and reorder them, and save changes. Edit issue mentioned above is not seen. Adding new items and delete also works. Screenshots attached. 

Screenshot (842)
Screenshot (843)
Screenshot (844)
Screenshot (845)
Screenshot (846)
Screenshot (847)
Screenshot (848)
Screenshot (849)
Screenshot (850)
Screenshot (852)

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account and all described features work. Good work!
Not sure if this is intended, but after I change the texts inside a box, and if I close the modal and reopen it, the changes of the text and the reorder of the options does not persist.

Screenshot 2024-05-04 at 10 44 02 PM
Screenshot 2024-05-04 at 10 43 49 PM
Screenshot 2024-05-04 at 10 43 42 PM

**Comment by kaushikMreddy293** [comment]
Hi Cloid, 
The your changes are working perfectly
image
Great work!

**Comment by ZhangPeizhou** [comment]
It works as expected, the only suggestion is this part is not affected by the dark mode. It is still bright when the app is switched to the dark mode. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/dd0d9b38-a36f-4800-b5ad-e8a70c4621dd

**Comment by KaushikMreddy** [comment]
Hi Cloid, 
The your changes are working perfectly
image
Great work!

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as described. Good Work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/1e9305ca-509b-4228-bdd0-ef530fe5713d

**Review by Kavil-Jain-514 — DISMISSED** [review]
The functionality works as expected.
I have recorded a video for this PR.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/fc55f336-e0e9-4a0b-bf7b-b28ac9513bfe

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
