### PR TITLE
Yi _ProjectMemberTable_UnitTest 

### PR DESCRIPTION
**Pull request by yi-lin-1234**
# Description
Unite test for `ProjectMemberTable.jsx`

## Main changes explained:
- Add the unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test ProjectMemberTable.test.js` to run the test
4. Verify that all 5 tests have passed

## Screenshots or videos of changes:
Screenshot 2023-11-29 at 11 55 23 PM

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed but I got this error message in the console

image

**Review by ZichanYang324 — APPROVED** [review]
All the test cases have passed
Screenshot 2023-12-01 at 1 30 04 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully

Screenshot 2023-12-01 at 2 33 41 PM

**Comment by belagaam** [comment]
All test cases Passed
Yi _ProjectMemberTable_UnitTest

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!
image

**Comment by beblicarl** [comment]
All tests passed but i still see this error in the console

image

**Pull request merged**
