### PR TITLE
Masasa_Visualizations for Teams

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
# Description
Screenshot 2023-12-10 at 10 12 45 AM

This PR aims at developing the requested features as described in the Picture above. Please see the video below for how to test the implementation.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/5561407e-71c7-4860-ab10-35be54d76248

## Related PRS (if any):
None
…

## Main changes explained:
- Intergrated  the chart using recharts library into weeklySummariesReport.jsx…
- created a new component called teamChart.jsx and its styling teamChart.css to display the table of the members…
- integrated the logic to enable the table and chart to dynamically reflect properties of the selected teams …
- added the ability to visit a member's profile by clicking on thier name in the table
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin or owner
5. go to dashboard→ Reports→ weekly Reports→…
6. verify that the implementation works as shown in the video

### CODE REVIEW

**Review by Alforoan — DISMISSED** [review]
All worked. Nice!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/b025d549-85f5-4189-85f7-a3d65091ae6d

**Comment by keyunhuangg** [comment]
hello, I checkout your branch and  i also git pull but it seem like it can't be compiled.
Screenshot 2023-12-12 at 1 45 15 PM

**Comment by keyunhuangg** [comment]
Hello
1) I tested for selection of one team and the pie chart show correct number 
2) I tested for selection of 2-7 team and pie chart show correct number
3) the name, role is correctly display sorted with team codes
4) selection with color is also available and working 
5) clicked a random role and successfully lead me to the profile pages

however when i select the "SELECT ALL" button on the team code, the page went blank. I am not sure this was intend not to be implemented. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/7bda7468-e71f-4eb0-a638-9f06592bc977

**Review by this-journey — CHANGES_REQUESTED** [review]
Hello!! I reviewed your PR and found that the functionality is working as expected, however, I wasn't able to get the "Load Trophies" button to load anything and as another reviewer noted, when you choose "Select All" the page goes blank.  I've attached a couple videos for reference.

Initial Functionality

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/a7135b09-6e0b-45bb-9b9c-6f383464b7fb

Load trophies and Select all

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/12d3e5bf-5fde-4230-b495-d11e4a7f23fd

**Review by ShengjieMao — CHANGES_REQUESTED** [review]
Hi, all options rather than the "select all" worked perfectly with all functions achieved as described. Can see the dynamic changes while i made selections. The selection all checkbox still not work. Please refer to the error message for details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/0e782e44-3282-4674-8e0a-488fa3489ff1

**Review by skaush21 — DISMISSED** [review]
* logged in as Owner, navigated to reports -> reports weekly
* selected a random team code, pie chart appeared with list of team members
* clicking team member takes user to team members profile page
* tested pie chart and team list by selecting multiple team codes
took a look at the code, looks good

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/75b43030-05b8-4183-9b70-15f16b02d306

**Review by MALAV1308 — DISMISSED** [review]
Hello , I have tested your PR and I got desire output as per the changes. Great Job!

**Review by Gugor99 — DISMISSED** [review]
### Report
Hi Masasa, I tested your functionality and it works as expected. After logging in as admin, I navigated to the weekly reports page, I then tested all the functionalities and everything seems to work as intended. Good job! Please see the screenshots for reference
### Screenshots
Cattura1
Cattura2
Cattura3

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Pull request closed without merging**
