### PR TITLE
Peterson fix the bug where the team code input can be edited by users who are not owners or administrators

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This PR was opened to fix the bug that allowed users who are not owners or administrators to edit the team code input.

## Related PRS (if any):
None

## Main changes explained:
Threen components have been modified to fixed the bug.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Go to View Profile → Teams.
4. Log in as a user who is not an owner or administrator, and the team code input should be disabled.
5. Log in as an owner or administrator and check if the team code input can be edited.

## Screenshots or videos of changes:
After my fix

## Note:
None

### CODE REVIEW

**Review by vijay10pk — APPROVED** [review]
All the changes works as expected. 
Screenshot 2024-09-17 at 10 09 57 PM
Screenshot 2024-09-17 at 10 09 32 PM

**Review by manikittu810 — APPROVED** [review]
Hello @peterson337 
PR is working as mentioned.

https://github.com/user-attachments/assets/e61a437d-34ad-4520-9c43-68c7d12d4c9e


Thank you.

**Comment by tharunaa-1** [comment]
As a user, the option is disabled
image

**Review by ArtemisNyx3 — DISMISSED** [review]
[Video](https://www.loom.com/share/b6343893e2f545b091f167f637dec632?sid=ad0dee3f-8841-4458-9b1e-6f7d66b7f86a)

Changes are working as expected. Good work 👍🏽

**Comment by beblicarl** [comment]
this functionality works as intended and the code is great

[screencast-localhost_3000-2024_09_20-08_49_49.webm](https://github.com/user-attachments/assets/af8e4869-3486-4183-87af-2d09492c17d1)

**Review by beblicarl — APPROVED** [review]

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and everything works as expected. 


https://github.com/user-attachments/assets/c1537405-b245-4943-8bbc-67fa0d0e9f33

**Review by jinxyou — DISMISSED** [review]
The text input is controlled correctly in volunteer and admin/owner. 
Screenshot 2024-09-20 221310
Screenshot 2024-09-20 221502

**Review by mohangadde1 — APPROVED** [review]
image
As a user, Team code is disabled.

**Review by sam19981 — APPROVED** [review]
Changes work as expected.

Screenshot 2024-09-21 at 6 10 34 PM

Screenshot 2024-09-21 at 6 11 26 PM

**Review by Gauravmg6 — APPROVED** [review]
It is working as expected.
Screenshot 2024-09-22 181025

**Review by RishithaMamidala — APPROVED** [review]
@peterson337 
For user who is not an owner or administrator, and the team code input is disabled and for owner and admin users it is enabled to change.
Admin:
PR 2686
Volunteer:
PR 2686 - 1

**Review by AshishNags — APPROVED** [review]
Working as expected, team code is not editable in Volunteer user login and it is editable in admin user login. Approving this PR.

Screenshot 2024-10-08 183316



Screenshot 2024-10-08 183542

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
