### PR TITLE
Sherly correct stars past weeks front

### PR DESCRIPTION
**Pull request by freecode23**
# Description
1. Make it so changing a person’s required hours doesn’t create incorrect stars for past weeks
Screenshot 2023-08-01 at 8 58 45 PM

2. Add history icon to the user's profile page and a modal that shows the history if there is one.  
image

# How to Test
## 0. Prerequisites:  
npm version 6.14.^

#### Back end
1. Checkout to this branch for back end (PR#466): [sherly-correct-stars-redo](https://github.com/OneCommunityGlobal/HGNRest/pull/466)
2. Run `npm i`
4. Run `npm run build`
5. Run `node src/utilities/addNewField.js`
This will make sure that all users will have their schema updated
6. Run` npm start`

#### Front end
1. Checkout to current branch for front end
2. Run `npm i`
3. Run `npm run start:local`
4. Log in as Owner
5. Make the user you want to test have already committed hours in the past week that is 20% more than the required hours: 
	Example:
	0Sherly Volunteer: has committed 60.07/40 on week before last. 

### Test 1: Check if history of promised hours icon is working
1. Go to dashboard —> click on your user to test—> Volunteering Times Tab
2. Find weeklyCommittedHours —> click on the history icon
3. If the user has never made any changes to weekly committed hours, it will just say so 
Example: 0Sherly Volunteer
6. Change the committed time of this user. Say reduce by 20 hours
7. Click history icon again. It should show a new one 
8. If you update again, it should not change. Because changing committed hours within a day should not affect anyhing
We don’t want to keep all these unnecessary data in database
9. Keep note of the history of this user:
40 hours 
20 hours

**Video description for test 1: (Turn sound on)**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/087c5a6b-3957-4159-981c-017947317a72

### Test 2: Check that stars are awarded correctly in weekly summaries report
1. Go to Dashboard —> Go to report —> weekly summaries report
2. Check that your user past history committed hours, mine was 40 has not changed and stars has not changed
3. Check that if you add a new tangible hour to this user,  the star still works correctly

**Video description for test 2: (Turn sound on)**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/e0156b80-c2a6-4b94-9ff0-6abf2a9076fd

### Test 3: Check that in weekly summaries report the commitment dates are assigned correctly
1. Have a user with 2 or more promised hours in the past.
This is ideally tested using unit testing for more rigorous testing. But please help test with whatever scenario you guys have in mind. 
2. Go to dashboard —> click on your user to test—> Volunteering Times Tab:
3. Click on the history icon and take note of the dates:
My example:
Promised hours 5- starting date August 1
Promised hours 7 - starting date July 27th
Promised hours 12 - starting date June 4th

4. Below is an illustration of the timeline to check:
Screenshot 2023-08-01 at 9 00 19 PM

5. Make sure the weekly committed hours follows the history correctly both on webpage and pdf (See video for details).

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/bb2c70ce-05fa-486a-9302-18b6b8f6b6e5

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hi @freecode23 , I've tested the PR and it works as intended. 

### Test 1
The history of promised hours icon works and I can view history of weekly committed hours. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/1e81b331-7381-47a5-b75c-9b59806d23f8

### Test 2
I do not have a test account which has earned stars before, so I use your test account to do this test. It works great and changing current committed hours won't change previous records. Stars from previous weeks keep their states. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/fbe901e4-c673-4deb-bab8-7403d16bdaf4

### Test 3
This test account was opened on July 23. It has no weekly committed hours for 2 weeks ago and 3 weeks ago. I changed its weekly committed hours from 10 to 20. The summary report changes according to the timeline. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/6c8549d7-c2b6-4100-8e68-5c44d8b905b6

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great. Good work Sherly

### Test 1

[Test-001.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/db244bad-97c7-4263-95e2-4d121c40af76)

### Test 2

[Test-002.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/7d16ab4c-018d-42a7-8964-f6a7e43b5fc0)

### Test 3

[Test-003.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/753ec275-17ba-46a2-9034-b4cd7f13f9ed)

**Review by beblicarl — APPROVED** [review]

**Review by DavidC0126 — DISMISSED** [review]
Hi @freecode23,

I tested your PR and all tests work perfectly.

### Test1

History of promised hours icon is working

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/6fc175b7-aff0-43f4-aaaa-05e0fb7bcc2b


### Test2

Stars are awarded correctly in weekly summaries report

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/952d1b73-693f-4a12-b6d8-8d0b8663f975

###  Test3

The commitment dates are assigned correctly in weekly summary report.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/fdcb5fac-57c1-4077-a2cb-782d43195390

**Review by veronicacheng2 — DISMISSED** [review]
Hi @freecode23, I have tested the PR and everything works great!

**Test 1** (Changes in committed hours will be reflected in Past Promised Hours history)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/761e6281-234f-4652-a97c-ccc4db8fc33b

**Test 2** (Reducing the current week's committed hours will not affect the star earned in previous week)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/a2b77543-1e1f-4e2f-838b-6e2167e509e6

**Test 3** (the changed committed hours will be reflected correctly in the weekly reports)

- Promised Hours History
Promised Hours

- Current Week
Current Week (PDF)
Current Week

- Last Week
Last Week (PDF)
Last Week

- Week Before Last Week
Week Before Last (PDF)
Week Before Last

- Three Weeks Ago
Three Weeks Ago (PDF)
Three Weeks Ago

**Review by xaanders — APPROVED** [review]
Hi Sherly. I've tested your PR. Works perfect!!

I couldn't find any other user with history of changes to test except yours. So some tests with my user, and those which need older changes with your user. 

**Test 1**

[test1.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/c38bf1c3-b019-40c6-a67b-4c3d237ac592)

history of changes 0Sherly Volunteer:



**Test 2**

[test2.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/353104cf-3e13-4b2d-ac39-f7bb409987e1)


current week pdf



**Test 3**

[test3.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/34ed9ced-2be9-49ee-bab3-4a8072384077)

**Review by Abiddy — APPROVED** [review]
Test 1 and 2 and they look good to me. Great job Sherley!

***Test 1***

[Screencast from 08-05-2023 10:48:32 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77697776/648de00d-1294-40a3-bdd4-7123afeee45d)


***Test 2***

[Screencast from 08-05-2023 11:00:42 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77697776/6939b320-5c5b-44f8-912b-8059576ac465)

**Review by ThapeloMasasa — APPROVED** [review]
The changes work as expected as can be seen here in the the screenshots, the promised hours of the particular week are reflected in the weekly summary of the respective week

Screenshot 2023-08-05 at 11 49 07 AM
Screenshot 2023-08-05 at 12 20 05 PM

**Comment by AuroraLovesWhales** [comment]
Hi @freecode23. I have tested your PR and I ran into an issue for Test 2. 

I added 40 committed hours for the user (XiaoTest Volunteer) last week (7.27). Original required hour is 10 from the Profile page. 

Test 1:
Go to Profile page for the user. Change the required hour from 10 to 20. Then change the required hour to 22 for the user. The history list’s newest data is updated to 22 within the same day.
Pasted Graphic 2

However, when I go to the Current Week tab, the required hour is still shown as 10. I updated some different required hours value for the user, but still got the same result:
image
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/4db97544-0f81-47ff-b527-26cdbac5e63f

**Comment by freecode23** [comment]
@AuroraLovesWhales Thank you for finding a bug! will check it!

**Comment by AuroraLovesWhales** [comment]
> @AuroraLovesWhales Thank you for finding a bug! will check it!

Hi @freecode23! I have tested your updated code and it is working as expected now. Great job!

**Pull request merged**
