### PR TITLE
Mounica - When deleting a user, made the user’s name bold, in delete popup of user management

### PR DESCRIPTION
**Pull request by mounica-dingari-by**
# Description
When deleting a user, added the user’s name and made it bold, in delete popup of user management.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ Other Links→ User Management→Create a new user and click on Delete Popup

## Screenshots or videos of changes:
Screenshot from 2023-08-19 22-20-16

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by arcan9 — APPROVED** [review]
Nice job! Tested, and username in the popup is bolded as intended.

Screenshot 2023-08-19 at 11 15 09 PM

**Review by luisarevalo21 — APPROVED** [review]
Hello @mounica-dingari-by 
I tested your PR and works as intended. Great job!

Upon deleteing a user, the their username is bolded. 
Might I suggest making the text red? Maybe the same color as the red button in the modal to really make it stand out. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/5026eaf4-bbfc-40de-a0c2-c1dbbd77e980

Screenshot 2023-08-20 at 8 09 14 PM

**Comment by one-community** [comment]
Excellent!

**Comment by AnishPandita** [comment]
Hi, great job. The PR works well. Name is bold when performing delete action.
Screenshot 2023-08-22 at 5 12 25 PM

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

issue #1146

**Review by beblicarl — APPROVED** [review]

**Review by harshidad — COMMENTED** [review]
Hi @mounica-dingari-by 
Can you please share the branch name . I am not able to get the brach with "mounica-dingari-by:mounica_add_username_to_userManagement_modal" name.

**Comment by iTvX** [comment]
> Hi @mounica-dingari-by Can you please share the branch name . I am not able to get the brach with "mounica-dingari-by:mounica_add_username_to_userManagement_modal" name.

I can help with you.

Add the new remote repository:
git remote add mounica-dingari-by https://github.com/mounica-dingari-by/HighestGoodNetworkApp.git

Fetch the branch from the new remote repository:
git fetch mounica-dingari-by mounica_add_username_to_userManagement_modal

Create a local branch and switch to it:
git checkout -b mounica_add_username_to_userManagement_modal mounica-dingari-by/mounica_add_username_to_userManagement_modal

**Comment by Jiyuanxia** [comment]
Hi @mounica-dingari-by, while reviewing your pull request, I encountered some issues. Specifically, I couldn't locate the "Other Links" tab at the top of the page. I attempted to address this by clearing my cache and refreshing the page, but unfortunately, these steps didn't resolve the problem.
Screenshot 2023-08-24 204347

**Review by EdwinLauM — APPROVED** [review]
Hi @mounica-dingari-by! Changes work as expected! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/15c3394d-bd06-4e3b-a514-8744cc0efcee

**Review by n0vay — APPROVED** [review]
Works perfectly.
image

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works well on my device.
image

**Review by veronicacheng2 — APPROVED** [review]
Hi @mounica-dingari-by, I tested the PR on my device. Everything looks good.

image

**Review by zuhang2000 — CHANGES_REQUESTED** [review]
Hi I tested your PR following your instructions. However I encountered a strange bug. The top navigator on the dashboard page does not have "Other Links". More strangely, it does not work even when I try to directly redirect the url to http://localhost:3000/usermanagement. If I do that, the page will be automatically redirected to dashboard page. 

I tested your PR by checking out into your branch and the latest backend PR. I'm not receiving any error from both front-end and back-end. I also tried different front-end branch which are correctly displaying the "Other Links".

Here is the detail.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/894918c4-5cbf-41e6-a6c8-bcba7824e1ef

**Comment by one-community** [comment]
> Hi I tested your PR following your instructions. However I encountered a strange bug. The top navigator on the dashboard page does not have "Other Links". More strangely, it does not work even when I try to directly redirect the url to http://localhost:3000/usermanagement. If I do that, the page will be automatically redirected to dashboard page.

This bug has been fixed on the Dev. Please pull the latest code and that should fix it for you too.

**Review by Haoj1 — APPROVED** [review]
Hi @mounica-dingari-by. Your changing looks great! The other link issue is still in current dev. I tested it on the BE commit #452 and this PR looks good.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/9b938820-bf1c-4843-b68a-d9e6338dc09c

**Review by zuhang2000 — APPROVED** [review]
Hi Mounica! This is a follow up PR review. I tested your PR again and everything work as expected! Good job.
Screen Shot 2023-09-02 at 8 05 09 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, Great job! I tested your PR and it works as intended.


week2 - Pr4

**Comment by one-community** [comment]
I want to approve and merge this but I don't know what the "workflow awaiting approval" is here at the bottom. Please address that.

**Comment by GaryB93** [comment]
Hi @one-community, just wanted to see if you still have the "workflow awaiting approval" message. Seems like a good PR to merge.

**Comment by one-community** [comment]
> Hi @one-community, just wanted to see if you still have the "workflow awaiting approval" message. Seems like a good PR to merge.

Thank you for the tag, merging!

**Pull request merged**
