### PR TITLE
Assign badge

### PR DESCRIPTION
**Pull request by zhangwen829**
Please log in as a user with the Administrator role (You may use this email "devadmin@hgn.net", credentials included in the Instructions for Running HGN React App locally) Find the "Badge Management" link in the header under other links, and go to the badge assignment tab.

### CODE REVIEW

**Comment by daoquangvy** [comment]
Everything is working for me. I am able to add badges into new user.

However, I don't know how far is the assign baded feature conver, so I will list out some bugs that I run into while runing this on my local machine. If you are planing to cover them in the future, please feel free to ignore those bugs below.

This happens few time when I try to choose which badges to assign into a user. It happens randomly.
TypeError: toAdd.add is not a function
image

This next error happend when I tried to enter and Name (Account) that is not existed in the database.  I belive you already plan to cover this in the future.
image

**Review by daoquangvy — COMMENTED** [review]
Everything is working for me. I am able to add badges to new users. 

However, I don't know how far is the assigned badge feature cover, so I will list out some bugs that I run into while running this on my local machine. If you are planning to cover them in the future, please feel free to ignore those bugs below and merge it to the development branch.

This happens few times when I try to choose which badges to assign to a user. It happens randomly.
TypeError: toAdd.add is not a function
https://i.imgur.com/qyTPR7v.png
image

This next error happened when I tried to enter and Name (Account) that does not exist in the database.  I believe you already plan to cover this in the future.
https://i.imgur.com/P1baomE.png
image

**Comment by zhangwen829** [comment]
Thank you for the comments. I am working on the error handling when the name entered is not in the database. I will look into the TypeError: toAdd.add is not a function.

**Comment by zhangwen829** [comment]
@daoquangvy Please review this PR. All the issues in previous comments have been addressed.

**Comment by zhangwen829** [comment]
Continued on PR #121

**Pull request closed without merging**
