### PR TITLE
Vijay Anand - UI fix for i icon in tasks and timelogs component

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description
image 

## Related PRS (if any):
To test this frontend PR you need to check out the development branch.

## Main changes explained:
- Refactored the stylesheet to make the tooltip visible when hovered over the "i" icon above the progress bar in Tasks and Timelog Component.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard→ Tasks and Timelogs → Click on Tasks Tab → Hover over "i" icon above the progress bar in Time and Tasks log Component.
6. verify if the info tooltip is visible in different screen size, either the contents should be full visible or scrollable depending on the screen size.

## Screenshots or videos of changes:
**Before Changes**
Screenshot 2024-09-04 at 9 17 27 PM

**After Changes**
Screenshot 2024-09-12 at 11 08 44 AM
Screenshot 2024-09-12 at 11 08 23 AM
Screenshot 2024-09-12 at 11 02 12 AM

## Note:
The dashboard component is slow sometimes because it has to make so many API calls. This is not a functional change and the changes only affect the tooltip exclusively.

### CODE REVIEW

**Review by RishithaMamidala — COMMENTED** [review]
@vijay10pk 
The i icon works correctly.
PR 2660

But there are some problems with screen size adjustements 
1) Cannot scroll after 730 * 594
2) It takes long time to readjust the layout to screen size
but am not sure if its in the scope of this PR, please let me know. See below video for details.

https://github.com/user-attachments/assets/cf3a66b6-16aa-4a7d-bc66-3368d37507c9

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/85ba4cec-d7f9-411e-ace9-9219ad87e30b

**Review by jinxyou — APPROVED** [review]
The text is visible in different window size. 
Screenshot 2024-09-13 215414
Screenshot 2024-09-13 215423

**Review by manikittu810 — APPROVED** [review]
Hello @vijay10pk 
I have the info, attaching the pricture the below. Working as mentioned.

Screenshot 2024-09-13 at 11 45 58 PM

Thank you.

**Review by mohangadde1 — APPROVED** [review]
Screenshot 2024-09-14 124009
Screenshot 2024-09-14 124035
 Tooltip is visible and scrollable across multiple screen sizes.

**Review by Abhinav-Ankur786 — APPROVED** [review]
The i icon works as per PR

image

**Review by Gauravmg6 — APPROVED** [review]
It is working as expected.

Screenshot 2024-09-16 142912

**Review by Watchdog00 — COMMENTED** [review]
My results seem different from what was expected. Some parts are still being cut off.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
