### PR TITLE
Renanluiz add missing shadow style

### PR DESCRIPTION
**Pull request by Renanluizssx**
# Description
Screenshot 2024-02-24 143846

## Related PRS (if any):
This frontend PR is related to the [PR878](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/878) frontend PR.
…

## Main changes explained:
Added box-shadow style in reports.css
Added box-shadow style in LeaderBoard.css
Added box-shadow style in Timelog.css
Added box-shadow style in Badge.css
Added new classes name in Timelog.jsx
Added new class name in Badge.jsx

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log any user
5. verify if the box-shadow is appearing properly in the video below:

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/28931cea-611d-4489-a2a9-445515a3f647

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and the box shadows are visible. Please refer the attached video.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/f02fcf2b-7179-4d49-81af-5ad3f71f0f72

**Review by XiaohanMeng — DISMISSED** [review]
Hi, I checked your PR and all box shadows are showing. Great job. Please see the attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/4730308d-d6e9-40e7-b666-dd7ffd49301f

**Review by ShengjieMao — DISMISSED** [review]
The box shadow worked as expected on all pages mentioned in the instruction. Great work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/9d6fb1a6-32ba-4c51-bbd9-1e4867c99588

**Review by Gugor99 — DISMISSED** [review]
### Report
Hi Renan,
I checked out your implementation and it seems to work well! Navigated to the various pages where you applied changes and I found the added shadow where it was supposed to be. Well done!
### Screenshots
Cattura1
Cattura2
Cattura3
Cattura5

**Review by skaush21 — APPROVED** [review]
Shadow feature appears in dashboard, the shadow is visible around the task and time log box, badges and is visible in reports.
Implemented feature works great!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/1c5e5dc0-9357-48f2-a46f-bcfe1d8ca2d5

**Comment by KurtisIvey** [comment]
Hey Renan, code looks great. Would love to get this moved to final review once the merge conflicts are cleared up.

**Review by yaow62023 — DISMISSED** [review]
I have tested your change on those page. The new shadow style are apply to each of the page mentioned. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/7aaf913e-ebbc-4549-b2ae-2f3edf1655c7

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/ac74564e-d477-40cf-8d62-cb2079986d24

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed this PR  again and it works as intended. Please refer the screenshots attached.

PR 1991 2
PR 1991 3
PR 1991 4

**Review by Pandani07 — APPROVED** [review]
Box shadows have been added! Looks good, PR works as intended
Screenshot 2024-03-05 at 10 25 51 PM
Screenshot 2024-03-05 at 10 25 29 PM
Screenshot 2024-03-05 at 10 24 40 PM

**Comment by beblicarl** [comment]
These changes work as intended. Great work

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.03.08-14_39_23.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/c5b5b515-e487-4f0f-96ba-768ade71728b)

**Review by beblicarl — APPROVED** [review]

**Comment by KurtisIvey** [comment]
image


Looks good to me as well. Nice job. Happy to see proper use of CSS style sheets as well.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
