### PR TITLE
Shiwani unit test for AddTeamPopup

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for AddTeamPopup.jsx

## Main changes explained:
- Added 11 test cases: renders modal elements when addTeamPopupOpen is true, does not render modal elements when addTeamPopupOpen is true, check if confirm button works, check if close button works, check team name does not exist message, check searched value results, check results without team name, check if postNewTeam action works as expected, check if getAllUserTeams action works as expected, check if postNewTeams puts out an error message when the axios post request fails, check if getAllUserTeams puts out an error message when axios get request fails.
- Added key prop to AddTeamsAutoComplete.jsx due to this warning 'Warning: Each child in a list should have a unique "key" prop.' as AddTeamsAutoComplete is a child component to AddTeamPopup

## How to test:
1. check into current branch
2. do `npm test src/components/UserProfile/TeamsAndProjects/__tests__/AddTeamPopup.test.js` 
3. Verify if all the test cases pass without any errors or warnings.

## Screenshots or videos of changes:
Screenshot 2024-01-17 at 4 32 49 PM

### CODE REVIEW

**Review by Alforoan — COMMENTED** [review]
All passed and the tests look very comprehensive. Nice!

image

**Comment by beblicarl** [comment]
All tests passed 

image

**Review by beblicarl — DISMISSED** [review]

**Comment by mianmiantea2019** [comment]
All tests passed.

image

**Review by bienzguoa — CHANGES_REQUESTED** [review]
Good job! All test cases passed. But I think it's better to make more tests included for error handling, for the 'postNewTeam' and 'getAllUserTeams' actions, include error handling scenarios, such as what happens if the post request fails. Thanks!
Screenshot 2024-01-06 at 4 49 14 PM

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 19 - PR5

**Comment by Shiwani99** [comment]
> Good job! All test cases passed. But I think it's better to make more tests included for error handling, for the 'postNewTeam' and 'getAllUserTeams' actions, include error handling scenarios, such as what happens if the post request fails. Thanks! Screenshot 2024-01-06 at 4 49 14 PM

Thank you for your review. I will add that test case too.

**Review by bajajtushar094 — DISMISSED** [review]
Hi @Shiwani99, I tested your PR and all the test cases worked. 
Screenshot 2024-01-08 at 23 25 12

**Review by ChengyanOo — DISMISSED** [review]
Hi @Shiwani99,

I've reviewed your tests and I'm impressed with how well they're written. They all run successfully, which is fantastic! Attached is a screenshot showing the successful test results.

HighestGoodNetworkApp_PR#1767

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work! 

Screenshot 2024-01-12 at 10 06 07 PM

**Review by bienzguoa — APPROVED** [review]
Hi, Good job! Added tests look so good,  All test cases passed.

Screenshot 2024-01-23 at 12 36 27 AM

**Pull request merged**
