### PR TITLE
Alan fix committed

### PR DESCRIPTION
**Pull request by LeeSingChanYau**
This misspelling occurs over 200 times on the frontend, and 40 on the backend.  Most of which are in “weeklyCommitedHours”.  All occurrences should be fixed to proper spelling and the app tested for resulting errors, section by section as each spelling correction is made.

How to test:
-Check if the correct weeklyCommittedHours value is displaying in the summaryBar.

More testing should be done, and ask teammates to help me debug any errors that may occur in this PR. Thanks.

### CODE REVIEW

**Comment by tingedudu8** [comment]
Hi @LeeSingChanYau, I used global search and found out that there is still one mispell left in BE files. Thanks!
PR671

**Comment by Gukal7** [comment]
Hi @LeeSingChanYau, I have also tested this PR and like @tingedudu8 mentioned there is still one place in the code where it is misspelled as "weeklycomittedHours".
Screenshot 2023-02-02 at 10 21 47 PM

**Comment by AnishPandita** [comment]
Hey @LeeSingChanYau, replicating what others said there is one instance of "weeklyCommittedHours" that is still present. Rest looks okay.
Screenshot 2023-02-03 at 1 47 01 AM

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau . 

One instance with weeklyComittedHours in the frontend.
week 02 - 02-03-23 (1)

Nine with weeklyCommitedHours in the frontend.
week 02 - 02-03-23 (2)

199 results with the correct spelling weeklyCommittedHours in the frontend.
week 02 - 02-03-23 (3)

Fifty two weeklyComittedHours in the backend.
week 02 - 02-03-23 (4)

Zero results with the correct spelling for weeklyCommittedHours in the backend.
week 02 - 02-03-23 (5)

**Review by PrabhjotSembhi — COMMENTED** [review]
Hey @LeeSingChanYau 
I have checked and Found these

1. "commited"  with 1 "t" is in 14 files and used 48 times
PR 671 1

2. "comitted"  with 1 "m" is in 27 files and used 188 times
PR 671 2

 3. "weeklyCommitedHours"  with 1 "t" is in 2 files and used 4 times
PR 671 3

 4. "weeklyComittedHours"  with 1 "m" is in 24 files and used 178 times
PR 671 4

**Comment by LeeSingChanYau** [comment]
@PrabhjotSembhi sorry about that, fixed the problems. Please review again.

**Comment by LeeSingChanYau** [comment]
I did leave one instance of WeeklyComittedHours where it is spelled with one **m** in the summaryBar component. I did this to display the value correctly, since this is how we are storing the variable name currently.

**Comment by PrabhjotSembhi** [comment]
@LeeSingChanYau 
> I did leave one instance of WeeklyComittedHours where it is spelled with one **m** in the summaryBar component. I did this to display the value correctly, since this is how we are storing the variable name currently.

can we rename it?

Everything else is fine now. If we can rename it that will be good too

**Comment by LeeSingChanYau** [comment]
@PrabhjotSembhi yes we could change the variable name but as of right now, any user you logged in as wont be able to see their weekly committed hours in the summary since we haven't saved the new correct variable name in the database yet. In other words, it would we blank.

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau 

I checked again and found the following:

Zero with one 't' on frontend.
week 03 - 02-06-23 (3)

Only one with one 'm', like you said before, on frontend.
week 03 - 02-06-23 (2)

Ten results with one 'm' on the backend. 
week 03 - 02-06-23 (4)
Is this related to how we are storing the variable name and/or linked to the frontend case you mentioned before?

For the rest, everything is right.

**Comment by NyahJ** [comment]
Hi @LeeSingChanYau,

Here I found some incorrect spelling, could you please take a look? Thanks!

截屏2023-02-09 下午5 21 19

**Comment by Lunaliar** [comment]
Hello @LeeSingChanYau 
I took a look through using search terms "weeklyCommittedHours", "weeklyComittedHours", "weeklyCommitedHours" and "weeklyComitedHours"
I only found one incorrect term which was already discussed above as being intentionally left for a later time.

@NyahJ I tried looking for your spelling but I think Im not able to find it because it's on the HGNRest. Are you searching for it while on branch "alan-fix-misspelling-committed" for the HGNRest?

Otherwise it looks great!

Screenshot from 2023-02-13 13-07-03
Screenshot from 2023-02-13 13-07-18
Screenshot from 2023-02-13 13-07-11
Screenshot from 2023-02-13 13-07-26

**Comment by angelinatr15** [comment]
Hello @LeeSingChanYau , 

I checked out this branch and it is working as expected. 

Only 1 "comitted" was found which was also to be expected. 

Screenshot 2023-02-15 at 2 33 07 PM

**Comment by Filipe-Oliv** [comment]
Hi @LeeSingChanYau 

I made a mistake checking out this PR. My bad.

It's working as intended.

**Review by Filipe-Oliv — APPROVED** [review]

**Review by angelinatr15 — APPROVED** [review]

**Review by PrabhjotSembhi — APPROVED** [review]
All spellings are corrected

**Comment by one-community** [comment]
Thank you. Moved to PR Review Management Team for final review before merging.

**Review by vanelnw — APPROVED** [review]
Hello @LeeSingChanYau, 
Great job, I did not find any spelling problems.
Capture d’écran 2023-02-17 à 04 01 35

**Review by rauleffting — APPROVED** [review]
Hi @LeeSingChanYau! You did a great job.
Everything is working as expected:

**Comment by suigunfjc** [comment]
Hi @LeeSingChanYau ! Everything looks good to me, you did a great job!
Screenshot 2023-02-17 152216
Screenshot 2023-02-17 152513

**Review by suigunfjc — APPROVED** [review]

**Pull request merged**
