### PR TITLE
Shiwani Teamsview unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for Teamsview component

## Main changes explained:
- Added 8 test cases: Team Table Data component: check team name displaying properly when the user is assigned to teams, check if team name not getting displayed when user is not assigned to a team, check if mockhandleTeam called when delete button is clicked, check if mockhandleTeam not called when delete button is not clicked. Teams component: renders without crashing, Teams header appears as expected, check modal opens when add a team button is clicked, check if modal does not open when add a team button is not clicked.

## How to test:
1. check into current branch
2. do `npm test src/components/UserProfile/__tests__/Teamsview.test.js`
3. check if all test cases pass without any errors

## Screenshots or videos of changes:
Screenshot 2024-01-17 at 5 16 09 PM

### CODE REVIEW

**Review by pshereen — APPROVED** [review]
Tested the PR.
All the tests are passed.

Screenshot 2024-01-17 193248

**Review by Vishala09 — APPROVED** [review]
Tested!
All test cases passed!
image

**Review by bajajtushar094 — APPROVED** [review]
@Shiwani99 All test cases passed. Thanks

**Review by X1aoZhang99 — APPROVED** [review]
Hi Shiwani,

I have tested your PR; all tests have passed. Nice work! 
Screenshot 2024-01-18 at 20 59 58

**Comment by yuhuimin1996** [comment]
Hi, 
I've tested this PR. All tests passed. Good job!
Snipaste_2024-01-19_18-30-20

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2024-01-20 at 12 19 46 AM

**Review by scoopstroop92 — APPROVED** [review]
Good job on the test cases . Approving on the same note 
image

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests ran correctly. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/c9c917a5-a00e-4314-b601-87b7ed29fb8a

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 21 - PR1

**Review by bienzguoa — APPROVED** [review]
All test cases passed, rendered thoroughly and correctly.
Screenshot 2024-01-21 at 12 27 21 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
