### PR TITLE
Deepthi fix adjust spacing between label and input field

### PR DESCRIPTION
**Pull request by deepthikannan**
# Description
image
…

## Main changes explained:
- Reduced the margin-bottom of labels (label element) to 5px to ensure tighter spacing between the label and its respective input field.
- Adjusted the spacing for paragraph elements within the form (.emails p) by setting margin-bottom to 3px to bring text descriptions closer to the input fields below.
- Set a margin-top of 3px for input fields and textareas (.input-text-for-announcement, textarea) to ensure uniform and minimal spacing across all input components.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other links→ Send email …
6. verify that the label and it's respective input field spacing has been adjusted for consistency, ensuring proper alignment.

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by panchalvatneu — CHANGES_REQUESTED** [review]
I think the issue is not quite fixed I think it would help if "Email" were a paragraph element with a bottom margin of 3px just like "Insert header" see image for reference 
image

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

image

Thank You

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are not working as expected. There are still some irregular spacing present in the formatting of the text of the page. Spacing between "Email List" text and its corresponding text box is different from the spacing between "Insert header or image link" text and its text box. Below is the screenshot for reference:
Capture2652

**Review by CillianRen — APPROVED** [review]
image
Works as expected

**Review by SMitta11 — APPROVED** [review]
Changes are working as expected
Screen Shot 2024-09-07 at 6 35 36 PM

**Review by sam19981 — APPROVED** [review]
Tested the changes: The spacing between the email text input box and the insert header text input box is even.

Screenshot 2024-09-07 at 7 57 06 PM

**Review by Jingyii800 — APPROVED** [review]
I have tested this feature, and it works as expected. The space looks good.

https://github.com/user-attachments/assets/f708f97d-91fe-48f6-9b72-f912447d343a

**Review by abdel-lall — APPROVED** [review]
LGTM, Good job!

Screenshot 2024-09-08 000803

**Review by ddshah878 — APPROVED** [review]
Changes are working as expected

image

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and it works as expected. 

Screenshot 2024-09-10 153402

**Review by Saniya98 — APPROVED** [review]
I have tested this PR and it is working as expected .
image

**Review by RishithaMamidala — COMMENTED** [review]
@deepthikannan 
I have reviewed the changes and the spacing and layout is correct.
PR 2652

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (197)

**Comment by beblicarl** [comment]
This feature looks like expected.

image

**Review by beblicarl — APPROVED** [review]

**Review by SnelPatare — APPROVED** [review]
changes are working as expected.
image

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
I'm going to request changes on this due to the code itself being structured poorly prior to you even messing with it. Your changes are only a bandaid on a poorly structured base which is not your fault.


Things that do need to be done to address this:

image

1.Convert "Email List (comma-separated):" and "Insert header or image link" into labels for their corresponding inputs. 
2. Properly apply Ids and html fors to connect them.
3. modify the "label" styling in "Announcements.css" as that will directly affect this. Weight, Styling, etc may need to be adjusted to revert to what it was at before, but that shouldn't be very hard
image


There should be no other files touched besides these two as they pertain to the exact scope. 

I would recommend just scrapping pull request 2652 and starting over from scratch with a new and up to date branch off the front end repo.

**Review by Abhinav-Ankur786 — APPROVED** [review]
Spacing is proper and it looks good.
Screenshot 2024-09-14 at 3 21 47 PM
Screenshot 2024-09-14 at 3 18 47 PM
Screenshot 2024-09-14 at 3 18 31 PM

**Pull request closed without merging**
