### PR TITLE
Ishan- hotfix for teams table and badge redirection issues

### PR DESCRIPTION
**Pull request by ishan-miglani**
# Description
This PR is a hotfix for issues found in 2 previous PRs.
**Issue 1:**
- The team code field in the teams table on the reports page was getting cut off for mobile dimensions.

Screenshot 2024-08-22 at 6 52 45 PM
Screenshot 2024-08-22 at 6 52 59 PM
Loom Link for Teams Table Issue: https://www.loom.com/share/e6dd4bc836a84e0dace3edece47bd194 

**Issue 2:**
- The redirection on clicking the badges and tasks icon form the summary bar in dashboard was working intermittently.

Screenshot 2024-08-22 at 6 52 05 PM
Screenshot 2024-08-22 at 6 52 20 PM
Loom Link for Badges Redirection: https://www.loom.com/share/152e9d62f04f4e87b161d94aa58f4051?sid=3d9a3d4e-d2f6-44f0-8bd8-848a7ec98392 

## Related PRS (if any):

To test this PR you need to checkout the development backend branch.

## Main changes explained:
- Fixed redirection for badges and tasks icons in Timelog.jsx
- Added css class in TeamTable so that teamCode field has minimum width

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user

 **Issue #1**
5. go to dashboard→ Reports→ Teams→…
6. verify for mobile dimensions the teamCode field is not cut off and has enough width.

**Issue #2**
7. go to dashboard→ badges & tasks icon in the summary bar.
8. verify that clicking these icons redirects you to the correct tabs. Verify that changing between tabs and clicking the icons again works correctly
9. verify this new feature works in dark mode

## Screenshots or videos of changes:
**Before:** 

https://github.com/user-attachments/assets/870416a4-15bf-42bf-ab42-55313df8a49e

**After:**

https://github.com/user-attachments/assets/afac7061-5e7a-44c7-ba32-75ccfbe9b83f

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/ef0774a7-5265-4730-b18a-951e5a8bb8dc

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.



https://github.com/user-attachments/assets/258eef28-2414-4846-9c05-999e872c2a74



Thank You

**Review by jinxyou — APPROVED** [review]
I tested the fix for the issues. The cutout issue if fixed, and the badge and task icon s now linked to the correct page.
Screenshot 2024-08-23 155722

**Review by SnelPatare — APPROVED** [review]
Changes are working as expected

https://github.com/user-attachments/assets/58da0c91-c86b-4ddb-9ec6-d0885a04521c

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
