### PR TITLE
TuanDinh_TeamReportLogs_Unit_Test

### PR DESCRIPTION
**Pull request by TuanDinh140194**
# Description
Create the unit test for TeamReportLogs component

## Main changes explained:
- Add new file TeamReportLogs.test.js
- In TeamReportLogs.test.js, i added 7 test case to test the TeamReportLogs.jsx component.
- First, I have tested if the component renders without crashing. Test if the component handles the props correctly such as title, number of team members, correct teamTotalBlueSquares number, teamWeeklyCommittedHours, and totalTeamWeeklyWorkedHours, 

…

## How to test:
1. check into current branch
2. do `npm install` 
3. do npm test TeamReportLogs.test.js to run the test
4. Verify that all 7 tests have passed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/b848bb1e-f7ff-458a-9fd3-e54094cf2af7

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-11-12 at 2 30 56 AM

**Review by wantingxu7 — APPROVED** [review]
Hi, I tested and got PASS message. Nice work!

**Review by navneeeth — APPROVED** [review]
Hello, @TuanDinh140194! Good implementation of the tests! Approving the PR for passing all the tests:
test cases passing

**Comment by beblicarl** [comment]
All tests passed and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 12 - PR3

**Review by DavidC0126 — APPROVED** [review]
Hi, tested it and works as intended.

teamReportLog

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-11-16 050240

**Review by zuhang2000 — APPROVED** [review]
Hi, I've tested this PR. 

Your code looks good to me. All tests have passed. 
Screenshot 2023-11-19 at 12 35 24 AM

**Pull request merged**
