### PR TITLE
Shihao fix refresh issue

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Screenshot 2023-12-07 at 16 15 35
[video](https://www.loom.com/share/a9d336faf8a84a1f9d0014c1c51210cc?sid=b417d677-f9a3-4f6e-80e9-d3c9fcfb82fc)

## Related PRS (if any):
This PR continue the work of #1651 

## Main changes explained:
- do not allow reload after marking the task resolved

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to the dashboard
6. Click the "check" icon and then click the "Mark as Done" button
7. To see if the page is reloaded

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/f752508e-6cac-4a7c-8e33-6e0c706eff5f

### CODE REVIEW

**Comment by Haoxiang310** [comment]
I've tested your PR with admin and owner role. Everything works as expected. 
Admin role: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/b287d2b0-d604-445b-80d9-742a13dcc3c6

Owner role:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/135764868/03e6825c-90fb-4896-ba47-34fee05ff5a3

**Comment by beblicarl** [comment]
This functionality works as intended

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.01.11-10_57_10.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/79c67dfd-6dc4-4582-8654-39020985533f)

**Review by beblicarl — DISMISSED** [review]

**Comment by DragonSlayer2401** [comment]
I was unable to run your PR. When I load the PR it is stuck on a white page. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/c07e9ddd-6051-4e6b-8262-048adebd0bef

**Comment by sxiong5** [comment]
> I was unable to run your PR. When I load the PR it is stuck on a white page. Please watch the overview video below for more details:
> 
>  2024-01-11.14-48-01.mov

Hey @DragonSlayer2401, did you try to run `npm i` and restart the project? Please let me know if this doesn't work.

**Comment by yuhuimin1996** [comment]
Hi @sxiong5,
I've tested this PR with Admin user and Owner user. For Admin user, everything works well, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/908421ff-9bec-4332-9636-0ab2df694bec

While for Owner user, when I click the check button and marked as done, this task didn't disappear and nothing happened. please have a look.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/abcb4224-07fb-4d8d-88bc-044edaee6ea9

**Comment by sxiong5** [comment]
Hello all, I have been investigating an issue where the owner of a task is unable to mark it as done due to an error being generated by one of the APIs. It seems that this error is unrelated to this PR. I suspect that the problem is related to recent changes made to the backend. I was able to test the PR using my Owner's account and it worked fine. Therefore, I believe that the issue needs to be fixed from the backend.

Screenshot 2024-01-12 at 13 38 26

**Comment by mianmiantea2019** [comment]
Hi @sxiong5,

I've tested this PR with Admin user and Owner user. 

For Admin user, everything works well, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/5d362790-0381-47f2-b18d-1d0cdc4585cb


For Owner user, I ran into the same issue mentioned in previous comments. The fix for taskHelper.js as discussed in other PRs is still pending merge. I will test again once the merge completed.

image

**Review by Renanluizssx — APPROVED** [review]
Hi @sxiong5, i tested your application and this is correct, i I logged in as an admin, and when i clicked on check icon, the "Mark as done" button appeared, when i clicked on it, the page was reloaded, very good.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/5e8913b1-d708-4615-87f8-d222172d245b

**Review by pshereen — CHANGES_REQUESTED** [review]
I tested the PR for admin user. 
I found out that the task has disappeared after "mark it done" for the admin user. However, the tasks list takes time to reload, and a white screen is displayed for a couple of seconds until then. 

Please take a look at the details from the video.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/89d1dbec-9f80-4bef-96ac-0b4f0fdf01ab

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
