### PR TITLE
Jianjun - add total people report feature

### PR DESCRIPTION
**Pull request by juneluo**
# Description
(PRIORITY HIGH) **Jae: Create “Teams Summary” on the Reports page**
Admin/Owner Login → Reports → Reports
In the view below, I need a “Total People Report” button to see exactly how many total people have contributed time to the project for a designated time period
People must have had at least 10 hours logged for them to count/be included
Should be able to choose the period of time and the result should show on this page or as a Modal
Should include a “Total Hours” section showing total tangible time logged by all team members during the selected period
Would like to run a “details” report that will list all the people and hours contributed by each for that time period too, with clickable names to visit their profiles
Need an “i” by the button to explain what the button does (all of the above)
This is needed because it is a metric we’re using from here on forward to measure the growth and progress of our nonprofit. So I want to be able to easily run this for individual months and/or an entire fiscal year to compare results with previous years.
A bar graph visualization of each month when seeing the yearly summary would be super helpful too

## Main changes explained:
- Add the “Total People Report” button and its 'i' data tip. (The content for the other two button is out of the scope of this PR)
- create the information card that shows the number of total qualified members (with more than 10 hours) and the total tangible time logged in this period.
- Two bar graph to show the number of the valid members monthly or yearly.
- A detail table listing all the people and the hours in the period with link to the profile, which can hide/show by clicking the button.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. Admin/Owner Login → Reports → Reports
5. try to select different start/end date and then click the 'Total People Report' button.

## How to test:
Note that the two bar graph will not always show in this section. It depends on the length of the time period you select.
Now the conditions are as following:
The time period is less than one month: no bar graph.
between one month to about twelve month: show monthly bar graph.
The start date and the end date are in different year: show yearly bar graph.

### CODE REVIEW

**Comment by Jiangwei-shi** [comment]
I've tested this branch, the 'i' data tip works indeed. The "Total People Report" button is also functioning.
image
image
“Show Detaills” button also works well.
image

**Comment by beblicarl** [comment]
Both functionalities work as intended as seen in the video below. Awesome !!!

[total-people-report-2023.07.01-15_17_34.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/acd0ea95-b611-43b8-9a25-04ff4e67bfd3)

**Review by beblicarl — DISMISSED** [review]

**Review by HectorAgudelo — APPROVED** [review]

**Review by yaow62023 — DISMISSED** [review]
The "i" info function works indeed.
Screenshot 2023-07-01 at 11 39 07 AM

The newly add feature also works indeed. 
Screenshot 2023-07-01 at 11 38 22 AM

Update test:
Test more period of time, bar graph show different period of time if choose different time period.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/2dc8c33e-609b-439c-a4ab-cc3b06fef02a


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/79291abb-c9bb-4ea6-b31c-3dadd93ebf13


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/14daa9d8-f616-4518-a0de-987e070ee1d5

**Comment by one-community** [comment]
There's 3 approvals on this but, correct me if I'm wrong, aren't the dates selected totally different than the output happening here: 
image

**Comment by one-community** [comment]
This looks fantastic! 

Please be sure to test different periods. Show me what happens if someone only chooses 1 year... it should show monthly details. PR Team please test fringe cases and try and break this. Everyone testing the exact same thing is fairly pointless.

**Review by HectorAgudelo — CHANGES_REQUESTED** [review]
Upon further revision of the added features, they work as specified on the PR. However, there seems to be an issue when changes the dates. the user will have to click twice the Total People Report button.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/650c491b-62b8-4503-84fc-1935887c9caf

**Comment by beblicarl** [comment]
1. The date format for the input field is ( DD/MM/YY ) and the display text up there is in the format of (YY/MM/DD ). This could be confusing. Also, I realized the start date (07/01/2010) is usually reduced by a day in the text displayed ( 2010-06-30). I am curious if it is intentional. Everything else works as intended when the difference is more than a year

test-1

2. When the difference between the start date and the end date is just a month it works as intended. On the first try, I clicked on the "Total People Report" once and it worked. On the second attempt, When you change the date, you need to click twice for it to work again. Everything else works as intended

[test-2.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/51cc2892-1184-4479-8a3d-19f17edaea31)

3. When the difference between the dates is a year we have everything working as intended.

[test-3.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/36e5bab1-721b-4228-ad4b-d99b57031574)

**Review by BaileyM96 — CHANGES_REQUESTED** [review]
Good work on the total people report feature, everything works as intended! I did find a few problems with the page.

1. For the information button next to the "Total Task", and "Total Team Report" buttons, the information does not appear in its box and is showing that it is empty.

2. After picking a date and having the bar graph appear, then you want to pick another date the data above the graph updates but you get no indication or quick loader that the date and data has changed. This could be confusing to other users making them think they need to click the "total people" button twice to get the new date and data. Maybe we can add a loader for that data.

## Video
[HGN APP TEST.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/7da0dab8-0a6c-4e06-bb33-f7712ee80219)

**Comment by juneluo** [comment]
Thank you all for the review, please check the update below:
1. The one day gap caused by the inconsistency in the date selected and used now should be fixed.
2. Now changing the date selected will refresh the data in the information card automatically and no need to close and reopen the section.
Note:
Any content related to the button "Total Task" and "Total Team Report" will not be included in this PR.

**Review by ramyaram2092 — CHANGES_REQUESTED** [review]
Hello @juneluo good work on the Total People Report feature . 

PF my observations in addition to the ones mentioned by other reviewers. 
1. Is it required to display both  yearly chart as well as monthly chart when the date range involves dates from two different years ?  The difference between two date  given is less than a year
image


2. The system continues to show details of the new selected date range . Ideally it should  hide the details and prompt the user to click on "show details"
**Steps to reproduce :** 
- user clicks on Show  Details  for a selected date range 
- user changes  the date range again
**Check the video for reference** 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/421f58d2-3d9d-467f-a2c4-ac70c2ca2943

3.  The following fix you made works. The page automatically refreshes as the user selects a date range without having to click the "Total People Report" button 
"_changing the date selected will refresh the data in the information card automatically and no need to close and reopen the section"_

**Review by HectorAgudelo — COMMENTED** [review]
The issues persist. However, you made the app render the data automatically once the user changed the dates without the need of pressing the Total People Report button.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/1ae1ff2d-9f98-4dfb-92fe-e7dbb7fd0c0e

**Comment by juneluo** [comment]
> The issues persist. However, you made the app render the data automatically once the user changed the dates without the need of pressing the Total People Report button.
> 
>  HGN.APP.-.PR.969-reviewed-changes.mp4

Could you please point out the issue for me? Now that clicking the blue button will hide or show the report and changing the date selected will automatically re-render the data. Please let me know the changes you require.

**Comment by juneluo** [comment]
> Hello @juneluo good work on the Total People Report feature .
> 
> PF my observations in addition to the ones mentioned by other reviewers.
> 
> 1. Is it required to display both  yearly chart as well as monthly chart when the date range involves dates from two different years ?  The difference between two date  given is less than a year
>    image
> 2. The system continues to show details of the new selected date range . Ideally it should  hide the details and prompt the user to click on "show details"
>    **Steps to reproduce :**
> 
> * user clicks on Show  Details  for a selected date range
> * user changes  the date range again
>   **Check the video for reference**
>   https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/421f58d2-3d9d-467f-a2c4-ac70c2ca2943
> 
> 3. The following fix you made works. The page automatically refreshes as the user selects a date range without having to click the "Total People Report" button
>    "_changing the date selected will refresh the data in the information card automatically and no need to close and reopen the section"_

For the first concern, we can definitely restrict the time range to be longer than a certain length, like one year. However, in my understanding, even if we restrict showing 'yearly' needs over one year time range (for example, May 2022-July 2023, the bar will represent 8 months and 7 months), it is not going to change the concern that each bar may only represent a few months in a specific year. A shorter time range like October 2022- July 2023 should have a similar view as the time range mention above.

For the second question, my thought is that if a user wants to learn about the 'details' of the report, they will not have to click the button every time they change the dates. 

Thank you very much for the helpful suggestions. I will double check with Jae to see which way he prefers.

**Comment by juneluo** [comment]
Update:
Add 'number of months' description to the yearly bar graph.


@ramyaram2092 After the discussion with Jae, the update is to avoid your first concern, and for now we are not going to add more action for your second concern.
@BaileyM96 @HectorAgudelo Please review this PR again and approve if there are no bugs/problems. If there is any requested improvements, please let me know the exact outcome you expect.

**Review by shiva2096 — CHANGES_REQUESTED** [review]
Hi @juneluo 

Everything is working as expected , however I have observed some **weird flickring** when I hover over the **writen months** value "12 month or 7 month" , please check the video below.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/d48861db-1853-48f9-81c3-20ab5ee1282e

**Comment by Shreyj14** [comment]
Hi @juneluo

As mentioned in the previous comments the reports look pretty good, but there is some flickering when you hover over the bars of the graph , please check the video below.
new_recording_-_7_19_2023,_5_02_57_pm (Original).mp4

**Review by Shreyj14 — CHANGES_REQUESTED** [review]
There is some flickering over the graph when it is hovered over. Please check for that.

**Comment by AnishPandita** [comment]
Hi @juneluo the functionality now seems to work according to the latest requirements apart from the flicker issue mentioned by @shiva2096 and @Shreyj14 .
Screenshot 2023-07-19 at 3 04 55 PM
Screenshot 2023-07-19 at 3 13 22 PM
Screenshot 2023-07-19 at 3 14 17 PM

**Review by DavidC0126 — COMMENTED** [review]
Hi @juneluo, I tested the PR and everything is working as expected including those changes someone has mentioned previously in this post. The only small issue is the flickering when the hovering over the number of the bar chart (Also has mentioned by others in the post).
pr#969_chartAndDate
pr#969_iAndDetails

**Comment by juneluo** [comment]
Thank you all for the review. 
This PR is closed and all the work here will be included in the latest PR1005(three new features combination). The update and fix mentioned in this one will also be made in the new one.

**Pull request closed without merging**
