### PR TITLE
Shiwani TagsSearch unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/Projects/WBS/WBSDetail/components/TagsSearch.jsx`

## Main changes explained:
- Added a new folder called __tests__ under components and added a new file under__tests__ called TagsSearch.test.js
- Added 4 test cases: renders without crashing , check if search bar works properly, check filtered text click: add resources, check filtered text click: remove resources 

## How to test:
1. check into current branch
2. do `npm test src/components/projects/WBS/WBSDetail/components/__tests__/TagsSearch` 
3. check if all test cases pass without any error.

## Screenshots or videos of changes:
Screenshot 2023-12-12 at 9 20 06 PM

### CODE REVIEW

**Review by this-journey — DISMISSED** [review]
Hello! I have reviewed your PR and all 4 tests passed.  Great job!

Screenshot 2023-12-14 at 12 37 43 PM (2)

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 16 - PR3 (#1696)

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work! 
Screenshot 2023-12-16 at 12 32 44 AM

**Review by bienzguoa — DISMISSED** [review]
Good job! All test cases passed! Code looks clear and good.
Screenshot 2023-12-17 at 12 11 18 AM

**Review by Alforoan — DISMISSED** [review]
All tests passed. Nice!

image

**Review by ChengyanOo — DISMISSED** [review]
@Shiwani99 

Great news! The unit tests you wrote have successfully passed. To document this, I've attached a screenshot for your reference. You can view it at the following link: 
Screenshot 2024-01-09 at 15 12 05
Keep up the good work!

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by beblicarl — DISMISSED** [review]

**Review by scoopstroop92 — COMMENTED** [review]
Hello Shiwani great job on the test cases !
I have one small suggestion , in the third test case negative assertion also can be added  like you have in the second test case "**check if search bar works properly**"
Ex: User bbb have not be used to call the add Resource  function
image

**Comment by Shiwani99** [comment]
> Hello Shiwani great job on the test cases ! I have one small suggestion , in the third test case negative assertion also can be added like you have in the second test case "**check if search bar works properly**" Ex: User bbb have not be used to call the add Resource function image

Thank you for your review. Do you mean to add a test to check if add resources has not been called before a user name is entered or whether to check if add resources is not called with user name that is not registered?

**Comment by ramyaram2092** [comment]
> > Hello Shiwani great job on the test cases ! I have one small suggestion , in the third test case negative assertion also can be added like you have in the second test case "**check if search bar works properly**" Ex: User bbb have not be used to call the add Resource function image
> 
> Thank you for your review. Do you mean to add a test to check if add resources has not been called before a user name is entered or whether to check if add resources is not called with user name that is not registered?

Hello Shiwani,  something like this in test case 3 :
 expect(addResources).**not**.toHaveBeenCalledWith(
      allMembers[2]._id,
      allMembers[2].firstName,
      allMembers[2].lastName,
    );

**Review by 666saofeng — APPROVED** [review]
All tests passed. It worked as expected.
image

**Comment by DragonSlayer2401** [comment]
All tests passed. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/ffb49754-8cbd-4fc5-ae2a-0bdb0ab469a3

**Review by scoopstroop92 — APPROVED** [review]
Looks good !

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
