### PR TITLE
Mounica - Make managers, mentors, and assistant manager obvious on teams. 

### PR DESCRIPTION
**Pull request by mounica-dingari-by**
# Description
Make managers, mentors, and assistant manager obvious on teams. 
1. Order them from most to least permissions: Owner, Admin, Core Team, Manager, Assistant Manager, Mentor… So owner would be at top. 
2. Make them bold and include their role after their name and in parentheses (i.e. Tim Kent (Manager)

## How to test:
1. check into current branch
3. do `npm install` and `...` to run this PR locally
4. log as admin user
5. Go to Other Links>Teams>Choose Team 

## Screenshots or videos of changes:
Screenshot from 2023-09-06 22-33-44

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by iTvX** [comment]
I have tested your pull request, it worked as described. Good job.

CleanShot 2023-09-06 at 23 48 16@2x

**Review by vinaykumarh — APPROVED** [review]
Reviewed the PR and the functionality works as expected.

Before:
image

After:
image

**Comment by Sssky-18** [comment]
Hi I just tested this change locally, and it worked as expected.
Before, the order of members was based on added date, but after this change they were ordered well based on their role.
Besides, the Manager was also bold as intended. 
Great work! 

PRreview_#1274_before

PRreview_#1274_after

**Review by DavidC0126 — DISMISSED** [review]
Hi @mounica-dingari-by I tested your PR and it works as expected.
roles

**Review by harshidad — DISMISSED** [review]
It worked as described.

Before:
PR#1274_Before

After:
PR#1274_After

**Review by robertoooc — DISMISSED** [review]
Hi @mounica-dingari-by , I tested your branch and it did perform as expected. The order of team members does list them in greatest to least hierarchy. Although the functionality works well and didn't receive any console errors, I would suggest running eslint fix on the file because there some small things that don't abide by the eslint rules. Overall though nice job.
Your Branch:
Screenshot 2023-09-07 at 1 38 00 PM
Development:
Screenshot 2023-09-07 at 1 50 39 PM
Eslint:
Screenshot 2023-09-07 at 1 57 28 PM

**Review by belagaam — APPROVED** [review]
I tested the PR as per the instructions. Everything works as expected.
1274 - mounica_sort_team_by_roles
1274 - mounica_sort_team_by_roles 2

**Review by EdwinLauM — DISMISSED** [review]
Hey @mounica-dingari-by! Code changes work as expected! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/ed8b3bd6-5f45-4419-9be2-7e0fd707ae72

**Review by GaryB93 — APPROVED** [review]
Great work! It is now obvious which team members hold the role of Manager and the team members on a team are sorted by role.

Screenshot 2023-09-08 at 3 34 58 PM

**Review by luisarevalo21 — APPROVED** [review]
Hello @mounica-dingari-by 
I tested your PR and works as intended. 

Visiting the teams displays what member has what role, owner, volunteer admin via parentheses. 
Screenshot 2023-09-08 at 7 54 48 PM

**Comment by AnishPandita** [comment]
Hi @mounica-dingari-by I tested the changes according to the guidelines and its working as intended. The role of member is clearly indicated in the popup.
Screenshot 2023-09-09 at 12 43 43 AM

**Review by vikrambadhan — DISMISSED** [review]
Hi, Great work ! I tested your Pull request and it works as intended. 

week2 - PR9

**Review by zuhang2000 — DISMISSED** [review]
Hi I've tested your PR following your instructions! The functionality is working as expected. They are ordered correctly. And also the bold text is correctly displayed.
Screen Shot 2023-09-09 at 10 41 57 PM

**Review by gabi-lima — APPROVED** [review]
Great job!
image

**Review by Chris33871 — APPROVED** [review]
Hi @mounica-dingari-by ,

I reviewed the code and feature, it looks good on my end 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68507104/f2c11a85-1310-4d26-8f9d-acb4ee422bcf

**Review by tsunami776 — APPROVED** [review]
I tested the PR locally and it works as described. Now team members are sorted by permission order and their roles are in parentheses with the manager's name in bold.
CleanShot 2023-09-14 at 17 06 00

**Review by Jiyuanxia — APPROVED** [review]
Hi @mounica-dingari-by , I have reviewed your pull request and tested it. It works as you intended. Well done!
Screenshot 2023-09-15 133559

**Review by Haoj1 — DISMISSED** [review]
@mounica-dingari-by Roles are correctly displayed in team page. Good job!

**Comment by beblicarl** [comment]
This functionality works as intended

[screencast-localhost_3000-2023.09.18-13_51_30.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/36cb4bf4-418c-4afa-b18d-2f6f939fbc80)

**Review by beblicarl — DISMISSED** [review]

**Comment by GaryB93** [comment]
Hi @one-community, this PR is a simple implementation and looks like a good one to move to final review.

**Review by Shiwani99 — DISMISSED** [review]
Hi,
I tested your PR. It works as intended. Managers and assistant managers are highlighted where as the rest of the team members are not highlighted.

Screenshot 2023-09-19 at 7 06 07 PM

**Review by Bhagyashree444 — APPROVED** [review]
Hi Mounica, the PR you mentioned worked correctly. 

However, I came across a scenario but I'm not sure whether it is a part of your PR or not -  while creating a user  I'm assigning a team to that user (Shree Test)  and expecting the user automatically getting added in that team but when I go into  Teams -> shree_test_Team  to verify, I did not find the user in it.

Your PR works correctly
PR #1274

Images for other Scenario
Screenshot (81)

Screenshot (82)

**Comment by one-community** [comment]
Address merge conflicts and I'll merge this one!

**Pull request merged**
