### PR TITLE
Nahiyan_Hofix for dark mode button issue

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
The dark mode button now functions properly.

## Related PRS (if any):
This frontend PR is related to the dev backend.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard
6. Click on the dropdown on the top right where the username is
7. Toggle on and off the dark mode button to ensure there is no issue.

### CODE REVIEW

**Comment by nikethaanand** [comment]
I have run the application, both the dark mode on and off toggle buttons are working correctly.
image

image

**Comment by nikethaanand** [comment]
I have run the application, both the dark mode on and off toggle buttons are working correctly.
image

image

**Comment by nikethaanand** [comment]
I have run the application, both the dark mode on and off toggle buttons are working correctly.
image

image

**Comment by nikethaanand** [comment]
I have run the application, both the dark mode on and off toggle buttons are working correctly.
image

image

**Review by nikethaanand — APPROVED** [review]
I have run the application, both the dark mode on and off toggle buttons are working correctly. I acciedently commented and closed the request instead of approving the review.
image

image

**Review by vijay10pk — APPROVED** [review]
Fix is working as expected. Able to switch between dark mode and light mode.
Screenshot 2024-07-09 at 7 49 25 PM
Screenshot 2024-07-09 at 7 49 39 PM

**Review by kdaga81 — COMMENTED** [review]
image

image


I had a suggestion of adding a toggle button to make it more intuitive.

**Review by sahithidhulipala9 — APPROVED** [review]
I made sure to check the application in both light and dark mode. Application is working perfect.
Screenshot (107)
Screenshot (108)

**Review by nyelmela — APPROVED** [review]
I have tested this PR, and it works perfectly fine. I checked into the current branch, ran `npm install`, and `npm run start:local` to run the PR locally. After clearing the site data and cache, I logged in as any user and went to the dashboard. I clicked on the dropdown at the top right where the username is located and toggled the dark mode button on and off to ensure there were no issues. Everything worked as expected.
image

image

**Comment by Nahiyan-16** [comment]
> image
> 
> image
> 
> I had a suggestion of adding a toggle button to make it more intuitive.

This is brilliant! I will attempt to recreate this soon. Thank you for the idea.

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good Work!
Screenshot 2024-07-12 at 3 30 04 PM
Screenshot 2024-07-12 at 3 30 15 PM

**Review by jennZhang93 — CHANGES_REQUESTED** [review]
Tested with admin account. One problem I found is that the page will switch to different modes only if I click on the text in the button. If I click on the right side of the button that doesn't have text, it wouldn't switch modes, but still shows that button has been clicked on. See video below for the testing process. Thanks

https://github.com/user-attachments/assets/0903ea5f-d14b-40ef-ad5b-a78104d491c3

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected in both light and dark mode.
Screenshot 2024-07-12 at 9 31 32 PM
Screenshot 2024-07-12 at 9 31 40 PM

**Review by jinxyou — APPROVED** [review]
There's no issue with the dark mode. Great work!
Screenshot 2024-07-13 174123

**Pull request closed without merging**
