### PR TITLE
Fix WBS task Responsiveness

### PR DESCRIPTION
**Pull request by PrabhjotSembhi**
# Description
Fix WBS Tasks Responsiveness. WBS tasks are not responsive on mobile and it only shows the first 5 columns. 

## Mainly changes explained:
I have displayed all columns on mobile. You have to scroll to the right to see.
I have made all toggle/ filter buttons look better on mobile by giving them display flex.
…

## How to test:
check into the current branch
do `npm install` and `...` to run this PR locally
log as admin user
go to dashboard→ Other links → Projects → AAA USE THIS PROJECT  → Jae's WBS - USE THIS 

## Screenshots or videos of changes:
Before 
Screenshot 2023-03-20 083659

after
https://user-images.githubusercontent.com/82662768/226238408-2133366b-dcb9-4282-a75f-adeb277cf290.mp4

## Note:
I have also tried a second option without a scrollbar but that didn't work well.

### CODE REVIEW

**Review by nicollext — COMMENTED** [review]
The WBS is working as expected. 

**Before**

https://user-images.githubusercontent.com/101591708/226703814-aca833b7-0bd0-42b5-8411-b7aa6762e159.MP4


**After**

https://user-images.githubusercontent.com/101591708/226702871-2a86309f-5ee8-44fc-8fd7-355e26d351fc.MP4

But when I open the "Add Task" modal  or the "Edit" modal the page **is not responsive**. Is this also scope of this PR?

https://user-images.githubusercontent.com/101591708/226706673-4360c5b3-af6a-4e7c-8580-878bfb47a467.MP4

**Comment by AnishPandita** [comment]
Hi, I tested your PR and WBS responsiveness seems to be working well. I verified it on multiple screen sizes on chrome as well as safari browser.

https://user-images.githubusercontent.com/111321945/226826199-11245e66-d30e-4585-b5b3-5002419fc08d.mov

**Comment by AriaYu927** [comment]
Hi @PrabhjotSembhi , I've tested the functionality and it works as expected. Thank you !

https://user-images.githubusercontent.com/94303659/227390167-d4b1fe2e-3d8e-4eea-bf32-ca99d94d077f.mp4

**Review by kangjay88 — APPROVED** [review]
Hi @PrabhjotSembhi , I have tested this PR and it works as intended. Nice use of flex for responsiveness. Thank you!
PR723

**Comment by NataliaCavicchioli** [comment]
Hey @PrabhjotSembhi I tested your PR and is working as intended. Good job!

There are some fixes, but I am not sure if it should be done on this branch. 

As the print below, it would look way better if the initials would be in the center of the container.
Also, the modals are not responsive for mobile. 

image

**Review by NataliaCavicchioli — APPROVED** [review]

**Comment by Jorge-Nerd** [comment]
Hello @PrabhjotSembhi  I tested and it seems to work properly 
before 
Pull#723
After
Pull#723_2

But I think you should put a litlle padding on some of the buttons

**Comment by PrabhjotSembhi** [comment]
> Hey @PrabhjotSembhi I tested your PR and is working as intended. Good job!
> 
> There are some fixes, but I am not sure if it should be done on this branch.
> 
> As the print below, it would look way better if the initials would be in the center of the container. Also, the modals are not responsive for mobile.
> 
> image

I will work on a new branch for some other changes. an I will look into these changes too

**Pull request merged**
