### PR TITLE
Ramya Unit Test : UsersProfile/ ToolTips/BasicTabTips

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit test for src/components/UserProfile/ToolTips/BasicTabTips

## Main changes explained:
-  New file
      - **_BasicTabTips.test.jsx_** : unit test cases 
-  Existing file
      - **_BasicTablTips_**  : Added  test id to the objects for unit testing 
####  Test cases 
image

## How to test:
1. check into current branch
2. do npm test BasicTabTips.test.jsx
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Review by this-journey — CHANGES_REQUESTED** [review]
Hi @ramyaram2092 !  I've tested your PR and am getting the following error.

PR 1735 FE

**Comment by ramyaram2092** [comment]
Hello @this-journey . There was a mistake in the file name. I just updated it in description. Try now : npm test BasicTabTips.test.jsx. It should work. Thanks for bringing it to my attention

**Review by this-journey — APPROVED** [review]
@ramyaram2092 just re-tested and everything passed.  Well done!

image

**Review by Alforoan — APPROVED** [review]
They all passed and your tests look well-organized and comprehensive. Nice!

image

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
