### PR TITLE
yixiao_taskactionsselectors_unit

### PR DESCRIPTION
**Pull request by JYXiao-2021**
# Description
Create two unit test for the actions and selectors component to confirm whether it working as intended.

## Main changes explained:
- Create file actions.test.js and selectors.test.js to do the unit test.

## How to test:
1. check into current branch
2. do npm install to run this PR locally
3. run npm test actions.test.js 
4. run npm test selectors.test.js

## Screenshots or videos of changes:
npm test actions.test.js :
image
npm test selectors.test.js:
image

### CODE REVIEW

**Review by scoopstroop92 — COMMENTED** [review]
Hello @JYXiao-2021   it's preferable to generate a separate pull request for each component as it facilitates easier tracking.

**Review by bienzguoa — COMMENTED** [review]
There is a typo in the test command for "action" in description. All test cases passed.
Screenshot 2024-01-13 at 11 14 31 PM

Screenshot 2024-01-13 at 11 14 43 PM

**Review by bajajtushar094 — APPROVED** [review]
@JYXiao-2021 All test cases passed but there is a typo of "actions" in the description. Thanks 
Screenshot 2024-01-15 at 12 19 42

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

PR 1829
PR 1829 plus

**Review by Renanluizssx — APPROVED** [review]
hi @JYXiao-2021, i test your tests and it's correct
pull#1829

**Comment by mianmiantea2019** [comment]
All test cases passed successfully. And the command to test actions.test.js should be  "npm test actions.test.js".   Great work! 

image

**Comment by DragonSlayer2401** [comment]
i tested your PR and all of the tests ran as expected. Please fix the typo in the actions test command. Please watch the overview video for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/275c483f-16ad-4dd0-9ddb-89433eef7de3

**Comment by JYXiao-2021** [comment]
> Hello @JYXiao-2021 it's preferable to generate a separate pull request for each component as it facilitates easier tracking.

Thanks for reminding, I will follow it next pr.

**Comment by JYXiao-2021** [comment]
> All test cases passed successfully. And the command to test actions.test.js should be "npm test actions.test.js". Great work!
> 
> image

changed the typo mistake, thanks.

**Comment by JYXiao-2021** [comment]
> i tested your PR and all of the tests ran as expected. Please fix the typo in the actions test command. Please watch the overview video for more details:
> 
>  2024-01-20.18-50-52.mov

changed the mistake, thanks

**Comment by Lin1404** [comment]
Hi @JYXiao-2021 I tested you PR, all test cases passed.

image

**Review by Lin1404 — APPROVED** [review]

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and the test cases passed!

Week 3 - Pr4-1

week 3 - PR4-2

**Review by X1aoZhang99 — APPROVED** [review]
Hi Yixiao,

All tests passed. Nice work! 

Screenshot 2024-01-30 at 00 37 37
Screenshot 2024-01-30 at 00 37 45

**Review by 666saofeng — APPROVED** [review]
All tests passed.
image
image

**Review by Pandani07 — APPROVED** [review]
Tested this PR and all the cases passed. Additionally, I checked the app and tried to find bugs, everything worked great!

**Review by navneeeth — APPROVED** [review]
Hello, @JYXiao-2021! I reviewed your PR and the tests for both `src/components/TaskEditSuggestions/actions.js` and `src/components/TaskEditSuggestions/selectors.js` files are well-designed for the relevant implementation and have the sample test cases passing. Great work!

### Test Cases Results
#### `actions.test.js`
actions test cases passing

#### `selectors.test.js`
selectors test cases passing

The unit tests that utilize the `redux-mock-store` fully cover all of the following Redux Actions in the implementation:
```javascript
FETCH_TASK_EDIT_SUGGESTIONS_BEGIN
FETCH_TASK_EDIT_SUGGESTIONS_SUCESS
FETCH_TASK_EDIT_SUGGESTIONS_ERROR
REJECT_TASK_EDIT_SUGGESTION_SUCCESS
TOGGLE_DATE_SUGGESTED_SORT_DIRECTION
TOGGLE_USER_SORT_DIRECTION
FETCH_TASK_EDIT_SUGGESTIONS_COUNT_SUCESS
```
Once again, good job on maintaining the action names consistently in the tests despite the typos in the action cases in the relevant implementation. Perhaps the typos can be corrected by replacing the case names across all files in a future PR.

The test written for the `getTaskEditSuggestionsData` const function that returns data based on the state is thorough as well.
LGTM! Approving!

**Review by mohabbasd — APPROVED** [review]
Hello, I tested you PR and it is working as expected. All the test cases have passed.
Screenshot 2024-02-13 at 12 06 50 AM
Screenshot 2024-02-13 at 12 08 43 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
