### PR TITLE
keyun- fix blue square hover-box position

### PR DESCRIPTION
**Pull request by keyunhuangg**
Screenshot 2023-12-28 at 4 30 00 PM

## Related PRS (if any):
None

## Main changes explained:
- move .report to the left 
- make the a fix width

## How to test:
1. Checkout this branch
2. Run npm start in BE
3. Clear site data/cache
4. Run npm run start:local in FE
6. Logged in as any user
7. Go to  Profile Page>Blue Squares Component, and check hover box does not cover any text on the page

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/056edbef-8a65-4e78-bbcf-9dbd5b15301f

### CODE REVIEW

**Review by Alforoan — APPROVED** [review]
It works as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/1fcbf3a5-2135-4f54-bd04-1cca609eaab9

**Review by abdel-lall — APPROVED** [review]
Works as described. Good job!

Screenshot 2023-12-30 183015

**Review by bienzguoa — APPROVED** [review]
Works as intended!
Screenshot 2023-12-30 at 5 36 53 PM

**Review by bajajtushar094 — APPROVED** [review]
working as described.
Screenshot 2024-01-09 at 22 40 09

**Comment by one-community** [comment]
Thank you all, moving to final review!

**Review by cvtqx — APPROVED** [review]
Works as described on computer screen, the blue square stays off other components. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/190ca004-3327-4c9b-93dd-63de02f2bf02

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
