### PR TITLE
John  Add “Hours by Team Member” Visualization to the Projects Reports page

### PR DESCRIPTION
**Pull request by Cavein254**
# Description
Screenshot 2024-02-17 101449

## Related PRS (if any):
None

## Main changes explained:
- Added a new component WbsPieChart.jsx

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Reports→Projects
6. Choose any project and check the checkbox "show piechart"
7. Should display a piechart  
## Also:
8. copy and paste `http://localhost:3000/projectreport/5f6cdff77b73161ddb32a0e5` on your browser
9. You should have similar results as below
## Screenshots or videos of changes:

Screenshot 2024-02-24 143007

Screenshot 2024-02-24 142949

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/246f5004-0e8e-4c44-947c-0e35f00389b2

### CODE REVIEW

**Review by XiaohanMeng — DISMISSED** [review]
Hi, I tested this PR and all pie chart in projects worked as intended!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/5c24abb3-d324-44f8-ba07-ddd437380b4e

**Review by skaush21 — DISMISSED** [review]
features implemented work
* checked multiple projects and pie chart displays
* able to see team members hours and hours contributed
* total hours displays in center of pie chart
* button to hide pie chart works

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/44b9524a-56ea-4dd8-b8a4-8878d721af31

**Review by meetpadhiar4 — CHANGES_REQUESTED** [review]
Hi, I reviewed your PR and everything works as intended. The pie chart is rendered correctly without any errors. However, I encountered one issue while checking for different screen sizes. The labels of the pie chart and the project title are overflowing the container for smaller screen sizes. Please refer the screenshot attached.

PR 1960 1
PR 1960 2
PR 1960 3

**Review by navyasrim — APPROVED** [review]
tested your changes and the pie chart is showing as mentioned.
PR-1960
PR-1960-2

**Comment by dhairya-mehta** [comment]
Hi, I tested the PR, it works as expected!
image

**Review by yaow62023 — APPROVED** [review]
Hi, I have test your PR, the pie chart displayed when mark the "Show Piechar". check the video below for more:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/7d4df5fa-1f82-4026-8da2-beeaf0bf5d1d

**Review by yvonnep165 — APPROVED** [review]
Hi @Cavein254 , I tested this PR and it worked as intended. Nice work! I chose the projects to check the piechart and also use the url http://localhost:3000/projectreport/5f6cdff77b73161ddb32a0e5 to get the same piechart shown by you. Please refer to the video below:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/64680a6f-04ec-4ec6-8a9b-96ef767ddd1f

**Review by aaryaneil — APPROVED** [review]
Tested the PR and can see the pie chart functionality for the projects section. Good work.
Screenshot 2024-04-20 at 11 26 19 PM
Screenshot 2024-04-20 at 11 26 56 PM

**Review by jennZhang93 — APPROVED** [review]
Tested with owner account and everything worked. I've checked with a project I created, and the project link you mentioned. Good work!
Screenshot 2024-04-30 at 8 00 47 PM
Screenshot 2024-04-30 at 8 00 56 PM

**Comment by cgomezhub** [comment]
> Hi, I reviewed your PR and everything works as intended. The pie chart is rendered correctly without any errors. However, I encountered one issue while checking for different screen sizes. The labels of the pie chart and the project title are overflowing the container for smaller screen sizes. Please refer the screenshot attached.
> 
> PR 1960 1 PR 1960 2 PR 1960 3

**Review by cgomezhub — COMMENTED** [review]
Hi!

Everything is working as planned! The pie chart renders correctly without any errors. However, I encountered an issue when testing for different screen sizes: the title and checkboxes are overflowing.

Please refer the screenshot attached.

https://www.loom.com/share/a51e94a85efe42e4a061338d1d8a0cff?sid=7db83044-6afb-47fc-877f-310cd07e0d65

**Review by cgomezhub — COMMENTED** [review]
Hi!

Everything is working as planned! The pie chart renders correctly without any errors. However, I encountered an issue when testing for different screen sizes: the title and checkboxes are overflowing.

Please refer the screenshot attached.

https://www.loom.com/share/a51e94a85efe42e4a061338d1d8a0cff?sid=d9bbd7d7-6540-42c3-8c84-dffbee1ef8b8

**Pull request merged**
