### PR TITLE
Changhao-added new unit tests for weeklysummariesreport.test.jsx

### PR DESCRIPTION
**Pull request by Changhao3220K**
# Description
Update: error are now fixed
added new unit tests for weeklysummariesreport.test.jsx, please ignore prexisting err caused by `EditableInfoModal` and scrow down to see the test results.

## How to test:
1. check into current branch
2. do `npm install` and `npm test WeeklySummariesReport.test.js` to run this PR locally
3. verify all 10 unit tests are passed

## Screenshot:
Screenshot 2024-02-06 at 1 14 21 PM

### CODE REVIEW

**Review by ShengjieMao — COMMENTED** [review]
All tests passed as expected. Can see all the components rendered successfully with necessary props
PR_1907(2)


But got these console errors. Please check the image for details.
PR_1907

**Review by Sophie-lei — COMMENTED** [review]
hey, I tested this PR and there are 17 passes in total.
Screenshot 2024-02-03 at 15 32 19

**Review by bienzguoa — APPROVED** [review]
Hi Changhao,
All test cases passed and renderings are correctly. But here are some console errors.
Screenshot 2024-02-03 at 3 11 34 AM

**Comment by DragonSlayer2401** [comment]
I tested your PR and the test appears to have errors stopping it from running. Please watch the overview video below for more details: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/66057b2c-e54c-4cfa-a239-de4e356e1a33

**Review by 666saofeng — CHANGES_REQUESTED** [review]
All tests passed, but there are some console errors. Please refer to the video for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/fd92860a-cffa-4232-b6e0-6abb055079f9

**Review by vikrambadhan — CHANGES_REQUESTED** [review]
Hi, I tested your PR and all the test test cases failed. 

week 23 - PR2

**Comment by xmyoot** [comment]
Hello, 
I tested this and all tests passed but I got the same 401 status codes, not sure if this API requires some kind of credentials that aren't be passed with the request: 
PR#1907(testsPassed)

**Review by X1aoZhang99 — CHANGES_REQUESTED** [review]
Hi Changhao,

All tests passed, but several console errors appeared. 

Screenshot 2024-02-04 at 20 53 12

**Review by peterson337 — DISMISSED** [review]
All Tests passed, however, there are some errors in the console that do not affect the tests that pass.

a

b

**Review by peterson337 — DISMISSED** [review]
All Tests passed.

a

**Review by 666saofeng — APPROVED** [review]
All tests passed. LGTM
image

**Comment by mianmiantea2019** [comment]
All tests passed. 

image

**Review by Pandani07 — APPROVED** [review]
All tests passed and the app works fine. No errors anywhere
Screenshot 2024-02-09 at 6 31 37 PM

**Review by yaow62023 — DISMISSED** [review]
All the test are passed! 
Screenshot 2024-02-10 at 12 54 30 AM

**Review by TareqMia — APPROVED** [review]
All tests passed 👍 
Screenshot 2024-02-10 at 2 07 04 PM

**Review by TapanPathak — APPROVED** [review]
Hi, All the test cases passed. 

Screenshot 2024-02-10 at 11 47 44 AM

**Review by vikrambadhan — APPROVED** [review]
Hi, i tested your PR again and all the test cases passed!

Week 24 - PR5

**Review by prnvjn — APPROVED** [review]
All 10 test cleared
image

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and it works as expected.
Screenshot 2024-02-10 at 11 56 31 PM

**Comment by Changhao3220K** [comment]
> Hi Changhao,
> 
> All tests passed, but several console errors appeared.
> 
> Screenshot 2024-02-04 at 20 53 12

Hi @X1aoZhang99 , the error should be fixed now, please checkout the latest update and test. Thank you!

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it passed all the test cases without any errors. Please refer the screenshot attached.

PR 1904

**Review by ramyaram2092 — CHANGES_REQUESTED** [review]
Hello @Changhao3220K I  think more test cases can be added. Also I see two file with same name with different extensions(.js, .jsx). Could you confirm the difference between  the two files  as well 
image

**Review by PratimaSingh02 — APPROVED** [review]
Hi, all the test cases have been passed!
1907 Changhao-added new unit tests for weeklysummariesreport test jsx

**Review by Tiantian-C — COMMENTED** [review]
I have tested it and come across some console errors.
Screenshot 2024-03-12 at 11 16 49 PM

**Review by Tiantian-C — COMMENTED** [review]
It works well!
PR 1907

**Comment by rajnada** [comment]
Hii,

All test cases passed Successfully.

image

**Review by dkn6 — APPROVED** [review]
All test cases are working as expected!

test

**Comment by Gmon-k** [comment]
Test cases has passed and below is the screenshot for it

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Comment by beblicarl** [comment]
@Changhao3220K can you please work on the merge conflicts

**Comment by SatyashanthiT** [comment]
I verified that the updates addressed previous errors and confirmed that all 10 test cases passed successfully
image

**Comment by geetamatkar** [comment]
Tested this PR and all the test cases have passed.

Screenshot 2024-10-25 at 6 57 46 PM

**Comment by VMD281** [comment]
Hi I reviewed this PR and all the test cases passed.
Screenshot 2024-10-26 at 5 13 49 PM

**Comment by humera314** [comment]
The test cases have pass
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
