### PR TITLE
Tuan dinh report charts and team chart group unit test

### PR DESCRIPTION
**Pull request by TuanDinh140194**
# Description
Unit test for ReportChart.jsx and TeamChartGroup.js

## Main changes explained:
Add two new file called ReportChart.test.js and  TeamChartGroup.test.js
In ReportChart.test.js, add 4 test cases: renders the component with the given title, renders PieChartInfoDetail components with correct data, renders the PieChartInfoDetail components with the correct color squares, and renders the PieChartInfoDetail components with the correct text.
In  TeamChartGroup.test.js, add 2 test cases: renders two ReportCharts with correct titles and pieChartIds and renders with the correct CSS class names
…

## How to test:
1. check into current branch
2. do npm test ReportCharts.test.js to run test for ReportChart
3. Confirm that all 4 tests have passed
4. do npm test TeamChartsGroup.test.js to run test for TeamChartGroup
5. Verify that all 2 tests have passed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/96a04748-f2c0-40d0-a305-f0e37aa3d1ca

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by navneeeth — CHANGES_REQUESTED** [review]
Hello, @TuanDinh140194!

Good implementation of the tests! Here are the results from my testing:

### ReportCharts.test.js
### 4/4 passed

Report Charts test


### TeamChartsGroup.test.js
### 1/2 passed
Failing test: renders two ReportCharts with correct titles and pieChartIds

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/8da98e66-ed23-4575-9575-d76deefd843b

Please update the PR description with the correct test file names: change 'Chart' to 'Charts' in both commands to run the tests as `npm test ReportCharts.test.js` and `npm test TeamChartsGroup.test.js`. Thank you.

**Comment by Iris-Song** [comment]
Hi, when do npm test ReportChart.test.js to run test for ReportChart, some error happens.
Screenshot 2023-11-10 at 22 17 32

**Comment by TuanDinh140194** [comment]
> Hi, when do npm test ReportChart.test.js to run test for ReportChart, some error happens. Screenshot 2023-11-10 at 22 17 32

Hi! I notice you use incorrect file name. Make sure to use the correct file name: npm test ReportCharts.test.js

**Comment by wanglu1207** [comment]
Hi, it shows some errors when I doing test

**Comment by TuanDinh140194** [comment]
> Hello, @TuanDinh140194!
> 
> Good implementation of the tests! Here are the results from my testing:
> 
> ### ReportCharts.test.js
> ### 4/4 passed
> Report Charts test
> 
> ### TeamChartsGroup.test.js
> ### 1/2 passed
> Failing test: renders two ReportCharts with correct titles and pieChartIds
> 
>  Team.Charts.Group.mp4 
> Please update the PR description with the correct test file names: change 'Chart' to 'Charts' in both commands to run the tests as `npm test ReportCharts.test.js` and `npm test TeamChartsGroup.test.js`. Thank you.

Test 2 fixed. It should be pass to check two chart have the same title.

**Review by Alforoan — APPROVED** [review]
Both tests passed. Nice!

image

**Comment by ramyaram2092** [comment]
Closing this pull requests and creating  a new one

**Pull request closed without merging**
