### PR TITLE
Ivy-Fix the incomplete Members list when the ALL-TIME button is selected

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
Screenshot 2024-08-03 at 12 14 02 PM

## Main changes explained:
- Delete file A for removing unused components …
- Update file B for including new pattern …
- Create file C for introducing new components …
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports →Reports → Projects→ select project→ Compare the Members list with the "ACTIVE" selection and the "ALL-TIME" selection.
https://github.com/user-attachments/assets/d4397087-8a47-44b9-bae5-1f02ba2f0a23

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Hello @20chen-7 
Followed the mentioned steps and everything is working as mentioned.

https://github.com/user-attachments/assets/eb5e4990-364f-439f-97b9-a75bff1d0d92



Thank you.

**Review by Gauravmg6 — APPROVED** [review]
Everything is working as expected.


https://github.com/user-attachments/assets/bca16180-77b5-4afb-ade0-3725aa7b7a2b

**Review by SatyashanthiT — APPROVED** [review]
PR has been reviewed and found the changes that are required

**Review by abdel-lall — APPROVED** [review]
LGTM, Good job!
Screenshot 2024-08-03 212744

Screenshot 2024-08-03 212737

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected.
Screenshot 2024-08-04 at 6 17 32 PM

**Review by Pranay-ai — APPROVED** [review]
Hey @20chen-7 
I have tested the PR it's working as expected , all the members and active member are visible  accurately.
Thank You
image
image
Thank You

**Comment by beblicarl** [comment]
this feature works as intended and the code is great

image


image

**Review by beblicarl — APPROVED** [review]

**Review by Aishwarya0898 — APPROVED** [review]
Hi @20chen-7 
The PR is working as expected, here is the reference.

PR #2532 Image 2
PR #2532 Image1

**Pull request merged**
