### PR TITLE
Shengjie added handleInput tests

### PR DESCRIPTION
**Pull request by ShengjieMao**
# Description
Added handleInput tests based on previous component test. 
(Closed the last pull because of operating error)

## Related PRS (if any):
None

## Main changes explained:
- Created test cases for handleInput for its props render, button functions, etc.

## How to test:
1. check into current branch
2. do `npm install` and `npm run test ForgotPassword.test.jsx  ` to run this PR locally
3. Check if all tests passed
## Screenshots or videos of changes:
output

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by ImzIssa — APPROVED** [review]
Hey, I've tested your PR and all test cases passed.

PR 2122

**Review by aaryaneil — APPROVED** [review]
All the test cases passed. Good work.
Screenshot 2024-04-06 at 11 07 14 AM

**Review by AaronPersaud — APPROVED** [review]
Hi @ShengjieMao, I've tested and everything passed! Good job.

image

**Review by n0vay — APPROVED** [review]
Looks Good to me
image

**Review by hbodgal — APPROVED** [review]
It works well. I checked the test file as well.

image

**Review by linkhanthtel — APPROVED** [review]
I tested your PR and all tests passed! Nice work!

**Review by bhuvaneswarignanasekar — APPROVED** [review]
I have tested your PR, Looks great. All test case passed.

Screenshot 2024-04-08 at 3 51 00 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
