### PR TITLE
Jerry - Unit test AssignBadge.jsx

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
Create Unit Tests for AssignBadge.jsx

## Related PRS (if any):
N/A

## Main changes explained:
- Added a new file: `src/components/Badge/__tests__/AssignBadge.test.js`

## How to test:
1. On the `development` branch of HGNRest (backend), run the server by running the following command: `npm i && npm run build && npm start`
1. check into current branch on HighestGoodNetworkApp (frontend).
2. do `npm install`
3. Run `npm test AssignBadge.test.js` to run the unit tests

## Screenshots or videos of changes:

Screenshot 2024-03-09 at 3 59 05 PM

### CODE REVIEW

**Comment by mianmiantea2019** [comment]
Hi Jerry, the tests have passed, but I encountered some errors below.

image
image

image

**Comment by nnamdixobi** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/2ad0e39a-b22b-4605-932d-e73e21ba184d

Tests seem to have passed but alot of errors were generated while testing that needs to be addressed

**Review by nnamdixobi — CHANGES_REQUESTED** [review]
Tests seem to have passed but a lot of errors were generated while testing that needs to be addressed, checkout my comment review along with the video

**Review by AaronPersaud — CHANGES_REQUESTED** [review]
Hi @jerryren527, all the tests passed, but I saw the exact same errors as the comment above mine

image

Error: Error: connect ECONNREFUSED 127.0.0.1:4500

image

That error usually happens when a request is made to a server and it fails, and I know our backend usually runs on port 4500. Since this a frontend test, the backend won't be running and will need to be mocked, or there might be another solution I'm not thinking of.

**Comment by dhairya-mehta** [comment]
Hey Jerry, tested and verified all the test cases, good job!
image

**Review by meetpadhiar4 — CHANGES_REQUESTED** [review]
Hi, I tested your PR it passed all the test cases, but is giving errors before and after the execution of the tests. Please refer the screenshot attached.

PR 2042

**Comment by jerryren527** [comment]
Hello all, thank you for bringing to my attention the warning messages. I have edited the `How to test` section this PR description to the following:

## How to test:
1. On the `development` branch of HGNRest (backend), run the server by running the following command: `npm i && npm run build && npm start`
1. check into current branch on HighestGoodNetworkApp (frontend).
2. do `npm install`
3. Run `npm test AssignBadge.test.js` to run the unit tests

Running the backend server first should remove the warning messages.

**Review by Abi-Liu — APPROVED** [review]
Hey Jerry! All tests are passing.

Screenshot 2024-03-20 at 10 45 09 PM

**Review by Tiantian-C — COMMENTED** [review]
All the tests have passed! Great!
Screenshot 2024-03-23 at 2 52 48 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, i tested your PR and all the test cases passed!

Week 30 - PR6

**Review by navneeeth — APPROVED** [review]
Hello, @jerryren527! Great implementation of the tests for `AssignBadge.jsx`! This is a really thorough implementation of testing on the Badge component! I liked how you gave a `data-testid` property in the `<i>` tag in the component itself and also spotted that typo.

Wonderful implementation of the tests to 
- render without crashing, 
- render the label element, 
- check first name and last name input, 
- check the autosuggestion component's rendering, 
- use the reducer to mock store and dispatched action, 
- render the assign badge button, 
- render the tool tip hover message, 
- dispatch action(s) when the badges are assigned, 
- and check if the "2 badges selected" message shows up. 
Great use of the redux-mock-store and the `mockUserProfilesData` array is well-defined to test with assigning badges.

The test cases are all passing:
test_cases_passing
 
Approving!

**Comment by rajnada** [comment]
Hii,

I have test this PR, and all test cases passed Successfully ! Great.

image

**Pull request merged**
