### PR TITLE
Shrada Fix Time Log OverLap

### PR DESCRIPTION
**Pull request by shradac**
Screenshot 2024-08-10 at 1 00 48 AM

## Related PRS (if any):
This frontend PR is related to the development backend PR.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Profile→ Project -> assign yourself to any project
6. go to dashboard and click on "Add Intangible time entry" and add some random big text. 
8. verify that the text and "edit and delete button" are not overlapping.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/fb0e04ac-512a-4a5d-b862-8d808867dbde

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Nahiyan-16 — APPROVED** [review]
Before:
Screenshot 2024-08-10 143306
After:
Screenshot 2024-08-10 143329

This PR works perfectly fine. Great work!

**Review by JatinAgrawal94 — DISMISSED** [review]
Both the buttons don't overlap with the text.
Screenshot 2024-08-10 at 7 31 42 PM

**Review by Aishwarya0898 — DISMISSED** [review]
Hello @shradac 
The PR is working as expected. Here is the reference.


https://github.com/user-attachments/assets/f8ea7c87-be8b-40cc-a204-1344a9ee2df9

**Review by Gauravmg6 — APPROVED** [review]
Everything works as expected.

Screenshot 2024-08-11 011117

**Review by manikittu810 — DISMISSED** [review]
Hello @shradac 
Everything is working fine as mentioned above.

Screenshot 2024-08-11 at 5 20 10 PM

Thank you.

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as described and there is no overlap between the text and the buttons.
Screenshot 2024-08-11 at 6 02 52 PM

**Review by Pranay-ai — DISMISSED** [review]
Hey @shradac 
I have reviewed The PR it is Working as expected.
image

Thank You

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and it works as expected. Good Work
Screenshot 2024-08-22 172201

**Review by sri0606 — APPROVED** [review]
Hey, I have tested the UI for any overlapping of edit and delete buttons. Everythin looks good on various screen sizes.

image
image
image

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

image

Thank You

**Review by mohangadde1 — APPROVED** [review]
image
buttons no longer overlap

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
