### PR TITLE
Shiwani TaskDifferenceModal unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/TeamMemberTasks/components/TaskDifferenceModal.jsx`

## Main changes explained:
- Added 18 test cases: check if Mark as read button gets displayed when logged in user id is same as user id, check if Mark as read button does not get displayed when logged in user id is not same as user id, check if modal is open when isOpen is set to true, check if modal is not open when isOpen is set to false, check if modal body does get displayed when task notification user id is same as user id, check if modal body does not get displayed when task notification user id is not same as user id, check if modal body gets displayed when old task is not present, check if task name and Task Name header gets displayed properly, check if priority and Assigned gets displayed properly, check if status and Hours - Best-case gets displayed properly, check if Hours - Worst-case and Hours - Most-case gets displayed properly, check if estimated hours and Classification gets displayed properly, check if Why this task is important and Design Intent gets displayed properly, check if Start Date and End Date does not get displayed when Start and End Date is set to null, check if Start Date and End Date gets displayed when Start and End Date is not set to null, check if EndState gets displayed as expected, check if links, resources does not get displayed when the array size is 0, check if links and resources get displayed as expected when links and resources arrays are set to entries more than 0.

## How to test:
1. check into current branch
2. do `npm test HighestGoodNetworkApp/src/components/TeamMemberTasks/components/__tests__/TaskDifferenceModal. test.js` 
3. check if all the test cases pass as expected without any warnings or errors

## Screenshots or videos of changes:
TaskDifferenceModal_Unit_Test_Output

### CODE REVIEW

**Review by aaryaneil — APPROVED** [review]
All the test cases passed.
Screenshot 2024-04-11 at 12 59 42 PM

**Comment by alla0810** [comment]
All test cases passed successfully.  Nice work done.

image

**Review by curiousfancier — APPROVED** [review]
All test cases passed and its working successfully!
review 2

**Review by yvonnep165 — APPROVED** [review]
Hi @Shiwani99 I have checked all the test cases and ran the tests. All tests passed. Nice work! Please refer to the screenshot below:
Screenshot 2024-04-26 at 8 01 00 PM

**Review by dkt6 — APPROVED** [review]
Thank you for the great work!
The results in my local environment meet the expectations as well.

TaskDifferenceModalUnitTest

**Comment by KaushikMreddy** [comment]
Hi @Shiwani99 , 

I ran your test cases, please check if anything has been changed from before. There are many more test cases and warnings compared to the previous comments.
image

**Review by shradac — APPROVED** [review]
All tests passed. The tests cover all specified scenarios. Good Work!

**Review by deepthikannan — APPROVED** [review]
image
All test cases passed and working great!

**Pull request merged**
