### PR TITLE
Yi - Dashboard: refine editable info modal tooltips text

### PR DESCRIPTION
**Pull request by FyisFe**
# Description
image

## Related PRS (if any):
This frontend PR is related to the backend dev.

## Main changes explained:
Change the tooltips text from "Click for user class information" to "Click for information about this"
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. login
5. go to dashboard
6. verify all tooltips in dashboard

## Screenshots or videos of changes

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/b4c375dc-79fc-4899-8558-e2550bb10f15

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and everything works as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/f6af20f2-40b9-4b16-aa6f-b68d82fc6d5f

**Review by Gugor99 — APPROVED** [review]
### Report
Hi Yi,
I checked out your implementation and it worked as expected. I couldn't take any screenshot of the effect, but I have seen that for every tooltip in the dashboard, on mouse over the text "click for info about this" was appearing successfully. Well done!

**Comment by dhairya-mehta** [comment]
Hey Yi, I verified the tooltips on the dashboard, well done!
image

**Review by navyasrim — APPROVED** [review]
Hi,
Tested your code and working as mentioned, attached is the screenshot.
PR-2030

**Review by Abi-Liu — DISMISSED** [review]
Looks good! I can view all tooltips in the dashboard page
Screenshot 2024-03-19 at 9 32 37 PM

**Review by yaow62023 — DISMISSED** [review]
Hi, I have test your PR. The mouse over text all updated. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/170814b4-c20c-4592-b1ca-04a344d821d3

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works perfectly. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/96b78c8b-f831-47eb-b4c9-ed7391c36123

**Review by kylepham — DISMISSED** [review]
Tooltip text correctly shows "Click for information about this".
Screenshot 2024-04-01 at 2 20 41 PM (2)
Screenshot 2024-04-01 at 2 20 39 PM (2)
Screenshot 2024-04-01 at 2 20 30 PM (2)

**Review by hetvi11110 — DISMISSED** [review]
I have reviewed the PR as explained, and all hover texts look good.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/124c7230-ee37-4bac-8e10-94573f911bc7

**Comment by Gayathr-2012** [comment]
I could see modal tooltips. It works as expected. Good Job
image

image

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi, I just checked your PR and is working as intended. I have attached the images for the reference.
Screenshot 2024-04-03 at 12 53 34 PM
Screenshot 2024-04-03 at 12 53 25 PM

**Comment by MQChen211** [comment]
Hi, I tested your PR. It works out as expected.

**Review by SRamen1999 — DISMISSED** [review]
Everything works as intended. You can see and toggle each tooltip.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/f2fb9dbe-7f50-4502-b1c1-a4e7be859c7b

**Review by Renanluizssx — DISMISSED** [review]
Hi @FyisFe, i reviewed your application and it's running correctly, see my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/ffd52961-ed81-43a8-bfbb-8ab27df8ff81

**Comment by hiralsonip** [comment]
I reviewed the changes and it is working as expected. Find the screenshot here. 

PR2030

**Review by MohdShahzil29 — APPROVED** [review]
i have checked this one and it's working fine
Screenshot from 2024-04-18 13-33-22

**Pull request merged**
