### PR TITLE
Yaohong improve people report appearance

### PR DESCRIPTION
**Pull request by YHX6**
# Description
image

…

## Main changes explained:
- Change the font color of the numbers in the boxes
- Move “Show Infringements Graph” below “Show Time Entries Graph”
- Hide the Tasks Contributed filters if no tasks have been logged
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Reports →Reports → Choose a person without tasks
6. check if the interface work as intended
 
## Screenshots or videos of changes:
For people who has no tasks logged:
Screenshot 2024-04-09 at 6 50 18 PM

For people who has time logged:
Screenshot 2024-04-09 at 6 38 06 PM

### CODE REVIEW

**Review by hbodgal — DISMISSED** [review]
It is working as required for the user without any tasks. Great Job!

image

**Review by jennZhang93 — DISMISSED** [review]
Tested with admin account. The UI looks great and functionalites are all working. Good work!

**Suggestion:** it might be better if there can be a Back button on the page. It confuses me a bit when I wanted to go back to the Reports Page and search again for other users.

With tasks logged:
Screenshot 2024-04-09 at 10 12 05 PM

Without tasks logged:
Screenshot 2024-04-09 at 10 10 37 PM

**Review by MohdShahzil29 — APPROVED** [review]
Awesome! working perfectly
https://www.loom.com/share/699096af7cb742cc8bd4cbcdc4f66f68

**Review by Parth-tech — DISMISSED** [review]
Hey Yaohong,

Everything looks great! I do have a suggestion though i.e black text look better than the dark blue. 

Screenshot 2024-04-09 at 10 22 47 PM
Screenshot 2024-04-09 at 10 36 29 PM

Black Text:
Screenshot 2024-04-09 at 10 33 02 PM

**Comment by alla0810** [comment]
works great!
works great

**Review by ShengjieMao — DISMISSED** [review]
Nice work. the page now looks like what described in the instruction and the filter worked well too.

**Review by SRamen1999 — DISMISSED** [review]
Everything works as expected. All the UI changes look great. One Suggestion I would give is changing the blue font too black.

Without tasks logged
Screen Shot 2024-04-11 at 2 17 14 PM

With tasks logged:
Screen Shot 2024-04-11 at 2 19 39 PM

**Comment by hiralsonip** [comment]
Hi..I have tested this PR. Everything is working as expected. 

PR2130

**Comment by hiralsonip** [comment]
Hi.. I tested this PR. Everything is working as expected. 

PR2130

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi, I test you pr and it looks fine. But I have suggestion if you like can we make the text color to #0A0206 on gradient boxes.
Screenshot 2024-04-11 at 6 27 27 PM
Screenshot 2024-04-11 at 6 26 38 PM

**Review by anandsesha — DISMISSED** [review]
Hi, I have tested the changes in the Reports view and it is displayed as expected.

For user with no logged task
Screenshot (785)


For user with time logged
Screenshot (784)
Screenshot (783)

**Review by aaryaneil — DISMISSED** [review]
The changes work as expected.
Screenshot 2024-04-11 at 8 31 48 PM

For people with logged hours:

Screenshot 2024-04-11 at 8 33 18 PM

**Review by p-suram — DISMISSED** [review]
Changes look good and working as expected. Good Work. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/6fe00216-72bb-4c3c-aeb0-655cb93a10cb

**Doubt :**
**Do we want to show filter when tasks are assigned but not yet started (because we still might want to search them) ?** Right now as logged time is 0, we are not showing filter as shown in below screenshot
image

**Review by j-corp-25 — DISMISSED** [review]
Hi @YHX6 

I followed the directions and logged in as admin and changes are working correctly. Tested mobile view on multiple sizes and no elements are out of bounds.

Below are screenshots of different views: 

- Mobile View

MobileView

- No Tasks View from admin


NormalViewNoTasks

- Person with Tasks view

TasksNormalView

**Review by p-suram — CHANGES_REQUESTED** [review]
**Do we want to show filter when tasks are assigned but not yet started (because we still might want to search them) ?** Right now as logged time is 0, we are not showing filter as shown in below screenshot
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
