### PR TITLE
Shantanu_add_badge_summary

### PR DESCRIPTION
**Pull request by n0vay**
# Description
bug_details

## Related PRS (if any):
None

## Main changes explained:
Added a preview button with a preview component to view only badges

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to dashboard→ Reports→ Reports→Select people
5. you can see the preview button next to show badges that will show badges of the user

## Note:
No idea why it shows that the icon is changed, its the same that is used in development branch.

### CODE REVIEW

**Review by Chris33871 — APPROVED** [review]
Hi @n0vay, the changes look great on the front end. I included pictures of what shows up for a user with and without badges.

This is just a suggestion, I think it would be good to include a text to say that this user has no badges. Either way, the changes work 👍 

No Badges view
Badges view

**Review by Shiwani99 — APPROVED** [review]
Hi @n0vay, 
Preview for badges has come out really well and there is just a small suggestion from my side which is to add a count for the number of badges that particular user has collected either near the badges or when hovering over the badges. Also, as previously mentioned, you can add a message when there are no badges.

I'm attaching some screenshots of what I had tested for admin and manager view:

Admin view:
No badges:
Admin View - volunteer


With badges:
Admin View - mentor


Manager view:

No badges:
Manager view


With Badges:
Manager View - Volunteer

**Review by DavidC0126 — APPROVED** [review]
Hi @n0vay I tested your PR and it works as intended. 
no_badge
preview

**Review by vikrambadhan — COMMENTED** [review]
Hi, I tested your PR locally and it works as intended! As a suggestion please add a functionality where one can see the total badge count a person has acquired. Also, in case a person has no badges a popup can be displayed to show that this individual has no badges.


week3 - PR 2
week3 - PR 2(1)

**Comment by n0vay** [comment]
image
 Added text for no badges.

**Review by Sssky-18 — CHANGES_REQUESTED** [review]
Hi @n0vay, I tested your added feature for the preview of Badges. The icon displayed well and it worked if this individual didn't own any Badge. However, if he or she had at least one, the Badges and the text "No Badges to show" would display at the same time, so I think there should be a bug when deciding whether or not to show the text because right now the text showed for everyone. 
No Badge:
PR#1291_Nob
One or more Badges:
PR#12191_1b
PR#1291_moreB2

**Review by Sssky-18 — APPROVED** [review]

**Comment by Sssky-18** [comment]
Just noticed that 3 minutes before my last comment requesting changes, @n0vay had already solved this bug, so I tested it again with newly pulled code. This time, there is no bug and the text displays as expected. Congrats!
#1291_new2

#1291_new1

#1291_new3

**Review by dah00 — APPROVED** [review]
Hey @n0vay, I just tested the changes and everything works as expected. I can also see the text update you made when the person has no badges. Great Job!
PR1291_no_badges
PR1291_with_badges

**Review by Haoj1 — APPROVED** [review]
@n0vay Badge summary looks good to me!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/8343770f-1b8d-4ec9-848a-413aa5049112

**Review by tsunami776 — APPROVED** [review]
I tested the PR and Badge Summary Preview works as described. Now when there is no badge for the person, 'No badges to show' will appear in the modal. 
CleanShot 2023-09-14 at 11 31 37
CleanShot 2023-09-14 at 11 31 07

**Review by GaryB93 — APPROVED** [review]
Hi @n0vay, I was able to test this PR with a success. Logged in as both admin and owner and was able to utilize the new button to show a badge summary for the user. Great work!
Screenshot 2023-09-14 at 1 41 56 PM

**Review by Jiyuanxia — APPROVED** [review]
Hi @n0vay , I have reviewed your pull request and tested it. It works as you intended. Well done.
Screenshot 2023-09-14 233729
Screenshot 2023-09-14 233801

**Comment by Shreyj14** [comment]
hi @n0vay the code work as intended. Maybe you can put a hover over the preview button that shows the text for preview badge.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/76daead8-eb5f-4612-9121-b25c2e38566e

**Review by iTvX — APPROVED** [review]
I have tested your pr and it worked as described. Good job!

CleanShot 2023-09-15 at 16 08 33@2x


CleanShot 2023-09-15 at 16 10 34@2x

**Comment by AnishPandita** [comment]
Hey, tested the PR and the add badge summary feature worked well for user with no badge as well as users with badges.
Screenshot 2023-09-14 at 9 56 12 PM
Screenshot 2023-09-14 at 9 56 28 PM

**Review by navneeeth — APPROVED** [review]
Hi @n0vay! Tested your changes and they LGTM! Logged in as an admin user and navigated to Dashboard->Reports->Reports->Select People and observed the preview button next to show badges that will show the badges of the user. 

Checked for an user with badges:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/e84fab7d-d553-4e2b-85f6-6c4c1a73e0c9


And for an user without badges:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/d247616e-1bf9-4bc8-8465-8ab3d6123b7b

Good implementation!

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions. The feature is working as expected! I test the cases including people with badges and without badges. And all these cases work perfect! Your code also look great. Good job!

people with badges
Screen Shot 2023-09-16 at 4 47 39 PM

people without badges
Screen Shot 2023-09-16 at 4 48 24 PM

**Review by gabi-lima — APPROVED** [review]
Everything working as expected. Great job!
image

**Review by robertoooc — APPROVED** [review]
I tested your pr and it does work well. The preview button does bring up a pop up of all the badges that someone has. The only I would've expected to see with it as well is a count of the badges, but I do understand that it would just defeat the purpose of show badges button if so. 
Screenshot 2023-09-16 at 5 13 45 PM

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
