### PR TITLE
Shengwei add stop blue sqaure added to new user

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
image

Updated Requirement:
image

## Related PRS (if any):
This frontend PR is related to the [795 backend ](https://github.com/OneCommunityGlobal/HGNRest/pull/795) PR.
…

## Main changes explained:
- Update the create new user UI: include the start date value, set the create date to today rather than the next date, and add a feature to prevent the selection of a past date earlier than today in the date picker component.
   -  Update src/components/Reports/PeopleReport/PeopleReport.jsx to use the user's startDate value rather than createdDate
   - Update src/components/Reports/PeopleTable.js to use the user's startDate value rather than createdDate
   - Update src/components/Reports/Reports.jsx to use the user's startDate value rather than createdDate
   - Update  src/components/UserManagement/UserManagement.jsx to use the user's startDate value rather than createdDate
   - Update src/components/UserManagement/UserTableData.jsx to use the user's startDate value rather than createdDate
   - Update  src/components/UserProfile/UserProfile.jsx  to use the user's startDate value rather than createdDate
- Add frontend logic for start date validation - the default date will be the current date.
- Remove multiple console.log statements in the frontend components that were pushed to the dev branch.
- Add blue square assignment (New User): Should not assign blue square to new user before the start date.
- Add blue square assignment (Short-Week): Should not assign blue square to new user who qualify for short week - start date is on or later than Tuesday
- New users add tangible or intangible timelog for first time should update the start date.
- Add a warning message to the user who had a history of time log and tried to modify the start date in user profile.
- Add a new function to prevent submitting time log before account creation for new users in both user and admin/owner dashboard view.
- Add the account created date column in the user profile page - src/components/UserProfile/UserProfileEdit/UserProfileEdit.jsx file.
- Update the user management data table to display the start date, not the account created date.
- Update people report frontend UI to display the start date rather than the account created date.
- Add the start date when creating a new user.
- Add user start date defaults to the creation date when sending a new invitation link.
- Update the user profile save feature (start date should be different from the created date).
- Add validation to prevent intangible/tangible time log before account creation for new users.
- Implement a new notification feature in the frontend to display, update, and retrieve user notifications.
   - create src/actions/notificationAction.js  
   - create src/components/Notification/notificationCard.jsx
   - create  src/constants/notification.js
   - create src/reducers/notificationReducer.js
- Remove legacy unused code
   - src/reducers/notificationsReducer.js  
- Update src/components/Header/Header.jsx to include the new notification card component to display user notifications.

## How to test:
1. check into the current branch and the [backend ](https://github.com/OneCommunityGlobal/HGNRest/pull/795)
2. Setup Email Sending service in the backend ([Tutorial](https://docs.google.com/document/d/1HJJTDtWykjGb4IfiIFlHXDfp_IABvmwKxsMPqqF6rG8/edit)) 
3. do `npm install` and `...` to run this PR locally
4. Clear site data/cache
5. log as admin user
6. Navigate to Other Links → User Management → Create New User (preferably with an Admin role for later testing convenience).
7.Log in as the new user and visit the user profile page to extract the user ID from the URL.
image

8. Stop the backend server and make the following modifications to the backend code in the userProfileJobs file to run the blue square assignment task every minute:
   - Comment out the regular timer and uncomment the testing CRON expression 
   - Comment out all jobs within the block except for the blue square assignment task.
image

9. Modify the backend code in the **assignBlueSquareForTimeNotMet** function of the **userHelper** file as follows:
    -  Comment out the line subtract() for the variable pdtStartOfLastWeek and pdtEndOfLastWeek to run the check for the current week. 
    - image
    -  Add a new line and paste the new user's ID to run the task against the specific user. image

10.  Navigate to the email sender code block around line 647 and modify the first variable (recipient value) to the email address you would like to receive the infringement email.  (**If you create an account with makeup email address. you might want to replace the line with a real email address to receive the email. Otherwise, the email will send to the email associated with the new user**)
   - image

11. Start the backend server and test the following scenarios for the new user (Blue Squares can be viewed in the frontend user profile page):
   - **0-hour time logged**: Blue square assignments should be blocked until the user logs their first timelog into the system.
   - **Not started**: Blue squares assignment should be blocked before the user's start date.
   - **Short week**: Blue squares assignment should be blocked if the user's start date is on Tuesday or later of the week being checked.
   - **Verify** that the start date will automatically update when the user logs their first hour.
      - Check the start date on the user profile page - volunteering time tab
      - Add a time entry for the user on the dashboard page via the add time button (preferably less than the weekly required time for subsequent testing).
   - **Regular week and time not meet** : Blue squares should be assigned to users who have logged fewer hours than required and have a start date on or after Tuesday of the week being checked.
       - If the account's start date is later than Tuesday, modify the start date on the user profile page under the volunteering time tab.
       - The date picker doesn't allow modification of the start date before the account's creation date. Disable the min line in the VolunteeringTimeTab.jsx frontend file to pick any date as the start date.
       - image
   - **Short week, log hour, time meet, but no summary** : Blue squares should be assigned to users who have logged the required hours but haven't submitted a weekly summary, regardless of the start date.

## Note:
Include the information the reviewers need to know.

## Screenshots or videos of changes:
Test cases 1 - 5:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/8c8b652e-3534-410e-a74b-f6f55e8c9e96

Test case 6:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/355fd78e-94ec-44a8-b444-e319e83a958e

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by sucheta90 — COMMENTED** [review]
Hello @ptrpengdev , I reviewed this PR. The instructions to test the PR is very descriptive. After creating a new user, I was able to set a start-date to a later date. On logging time before the start-date the system's start date changes to the date on which the time was logged. However, I tried changing the system date to a later date to see if I got the infringement email, I did not receive an infringement email. This could be my gmail api set up issue.

**Review by 20chen-7 — DISMISSED** [review]
I went through all five cases and looks as expected. 
automated corrected start date:
Screenshot 2024-04-20 at 2 12 45 PM
for case 6
Screenshot 2024-04-20 at 3 14 02 PM

**Review by abdel-lall — DISMISSED** [review]
Works as described. Good Job!
Screenshot 2024-04-20 182118

**Comment by one-community** [comment]
Thank you all, merging as soon as branch conflicts are resolved!

**Pull request merged**
