### PR TITLE
Zijie lint fix inventory

### PR DESCRIPTION
**Pull request by iTvX**
# Description
image

Eslint fixed:
CleanShot 2023-11-02 at 18 48 03@2x

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. Check if the inventory function is normal as before.

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Bali2Mohit — COMMENTED** [review]
Hi @iTvX , I tested your PR and it works great. well done!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94716419/e90c4f4b-6bf4-4a94-9fb5-a5b7186aa1f3

**Review by malikjahanzaib — APPROVED** [review]
Hi @iTvX, no lint errors and inventory works fine. Nice work!!!

Test rec/Screenshot:

image


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/a8f3cacd-590c-43e3-a0d2-4ea3b15bf391

**Review by Hemsharavanan — APPROVED** [review]
Builds without issue.
Followed coding standards
Functionality works without any issue

Zijie lint fix inventory #1483 code app

**Comment by mounica-dingari-by** [comment]
Hi @iTvX , I can see that there are no errors when the inventory button is clicked. So, I think the lint fix hasn't disturbed it. Good Work!
Screenshot from 2023-11-03 17-47-27

**Review by jerryren527 — APPROVED** [review]
Hi @iTvX !

The Inventory button functionality works without any errors. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/130d6863-4cb8-4e1f-9a57-a225d92e6bda

**Review by savio-henrique — APPROVED** [review]
Hi @iTvX , I've tested your PR and the inventory functionality is working as intended, the lint didn't produce any errors. Great work :+1: !

# Video 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83360232/659f1764-567e-460a-9d20-0c6bef0cefbd

**Comment by palakgosalia** [comment]
Hey, I have tested your PR and everything works fine. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/fb6b2711-b8f5-493f-85ab-5743a5f6b79e

**Review by pika-chu11 — APPROVED** [review]
Tested! Works as expected!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/2b169760-4787-4658-9b41-7c38b720865b

**Review by Sssky-18 — APPROVED** [review]
Hi @iTvX , I tested this PR about Lint fix on inventory, and it worked as expected. The inventory component displayed normally. Congrats! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/e57ae3b7-76d2-4820-91ef-39e2473b6997

**Review by yi-lin-1234 — DISMISSED** [review]
Hello, inventory function is the same as before. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/7e7e4c63-3ec7-450e-a64e-b88f4eac63d4

**Review by Bali2Mohit — APPROVED** [review]

**Review by Alforoan — DISMISSED** [review]
It all seems to work as usual. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/ec8f8c90-6c02-4e45-90ed-4dfc86ac236f

**Review by EvianTan — APPROVED** [review]

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
