### PR TITLE
Imran_See_User_Management_Tab_Full_Functionality

### PR DESCRIPTION
**Pull request by ImzIssa**
# Description
Create "See User Management Tab (Full Functionality)" permission.
Make the "Other Links" -> "User Management" option appear/accessible with full functionality of User Management page (user is able to create, delete, and update users) for users who have the "See User Management Tab (Full Functionality)" permission. 

## Related PRS (if any):
This frontend PR is related to the [#1039](https://github.com/OneCommunityGlobal/HGNRest/pull/1039) PR.

## Main changes explained:
- add new permission 'userManagementFullFunctionality'
- Updated UserTableData.jsx with new Permission
- Update UserTableData.test.js

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log in as Owner -> Other LInks -> Permissions Management -> Manage User Permissions
5. Enter the username of a user that does not inherently have the “See User Management Tab (Full Functionality)” permission (i.e., a Volunteer). Click on Submit.
6. Login as the chosen user (if already logged in, make sure to log out and log back in). The “Other Links” button should appear with the “User Management” option available with access to the full functionality of the page (create, delete, and update users).

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/f42ef2af-738c-42fa-b2cb-9b2bbcfba11f

## Note:
Related bug: See below the image of a popup message displayed when a user with 'User Management' permission attempts to delete another user. The popup lacks a button to finalize the deletion process.
bug

### CODE REVIEW

**Review by JatinAgrawal94 — DISMISSED** [review]
Functionality works as expected. Good work!

https://github.com/user-attachments/assets/94ca2d03-144b-45e0-bdc4-7ef2be5fa093

**Review by Pranay-ai — DISMISSED** [review]
Hey @ImzIssa 
The PR is working as expected , please find the attached  screenshots for reference
image

image

image

Thank You

**Review by SMitta11 — DISMISSED** [review]
I login as owner and gave permission to volunteer account "see user management tab full functionality":
Screen Shot 2024-08-17 at 6 14 08 PM
Then I login to that volunteer account and I am getting options to create,update and delete users.
By update do you when to activate or deactivate current user ?If that is what updating a user is then this works correctly.
Please find below screenshots:
Screen Shot 2024-08-17 at 6 16 44 PM

Screen Shot 2024-08-17 at 6 16 53 PM

**Review by SnelPatare — CHANGES_REQUESTED** [review]
I tested the PR. I am able to see User Management tab under other links for volunteer profile. But, I am unable to see it's functionality. 

Please find below image for reference

image
image

**Comment by ImzIssa** [comment]
> I tested the PR. I am able to see User Management tab under other links for volunteer profile. But, I am unable to see it's functionality.
> 
> Please find below image for reference
> 
> image image

What do you mean you're unable to see it's functionality? You can't navigate to the screen?

**Review by Lemonnycodes — APPROVED** [review]
Hi,

Tested the PR and it works as expected 

- Checked the process of assigning permissions to a user without inherent "See User Management Tab (Full Functionality)" permission.
- After assigning, verified the user could access and utilize the User Management functionalities as expected.

Functionality Verification:
- Tested login as a Volunteer user and ensured the “Other Links” with “User Management” option appeared, allowing full page functionality.

PR 2478 (1)
PR 2478 (3)
PR 2478 (2)

**Comment by SnelPatare** [comment]
> > I tested the PR. I am able to see User Management tab under other links for volunteer profile. But, I am unable to see it's functionality.
> > Please find below image for reference
> > image image
> 
> @SnelPatare What do you mean you're unable to see it's functionality? You can't navigate to the screen?

Yes that's correct. Now I am not able to see User management tab also. Please find below video

https://github.com/user-attachments/assets/2554c42d-95e2-4355-b5a3-e5dbb7f09478

**Review by vishnupriyaatheti — CHANGES_REQUESTED** [review]
@ImzIssa I have tested this PR in local but I am facing some issues. 
I have created one user and tried to add  See User Management Tab (Full Functionality) permission with the owner account. Then I logged out from owner account and tried to login to this account, but here I don't see the otherlinks option. Can you please check.
FE PR 2478 issue

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected. I have created a new volunteer account and added permission to the user management tab and it works perfectly fine.




Thank You

**Review by sri0606 — APPROVED** [review]
Hey @ImzIssa , I tested the PR and everything seems to work as expected.

* I have logged into a woner account and gave an user the "See user management" permission.
* Then logged back into that volunteer account.
* I can see the "User management" option on "Other links" dropdown and that page is functional
Screenshot 2024-09-04 140656
Screenshot 2024-09-04 140753

**Review by vedantg24 — COMMENTED** [review]
Tested the PR and found some issues. I created a new user, and when I logged in with owner account, I saw it has the "See User Management Tab (Full Functionality)" by default. Also, after logging in as the volunteer, there is no User Management tabs.

Screenshot 2024-09-04 at 7 45 53 PM

Screenshot 2024-09-04 at 7 46 36 PM

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and observed that after creating a user and logging into the owner account, the "See User Management Tab (Full Functionality)" was set to default. Also, after logging in as the volunteer, there is no User Management tabs in the top menu. Below are the screenshots for reference:
Capture
Capture2

**Review by Shreyav2000 — CHANGES_REQUESTED** [review]
I followed the steps as outlined, logged in as the owner/admin, and went to manage user permissions. I assigned the “See User Management Tab (Full Functionality)” permission to both my test and volunteer accounts, but the expected functionality did not work. For both accounts, I was able to see the "Other Links" option, but the full user management functionality did not appear. I also ensured that I’m on the correct branch and up to date with the changes. Could you please check and confirm the issue? Thanks in advance!

https://github.com/user-attachments/assets/9d5a5bad-9982-4235-ac9e-35021a0c4c9d

**Review by yashwanth170 — APPROVED** [review]
Hello Imran,

I have tested the PR and everything is working as expected for me. I was able to find the other links and locate User Management tab.
see_user_management
see_user_management_1

**Review by swaroop-2007 — APPROVED** [review]
@ImzIssa 
I reviewed your PR and everything works as expected. I was able to view user management on my volunteer account. 
Screenshot (383)
Screenshot (385)

**Review by ashayk9 — CHANGES_REQUESTED** [review]
I tested the pr with the proper frontend and backend branches and found some issues. I created a new user, and when I logged in with owner account, I saw it has the "See User Management Tab (Full Functionality)" by default. Also, after logging in as the volunteer, there is no User Management tabs.
Screenshot 2024-09-10 at 5 45 11 PM
Screenshot 2024-09-10 at 6 16 05 PM

**Comment by saurabhshetty29** [comment]
Tested by logging in as the owner and granting the volunteer account permission to "see user management tab with full functionality." After logging in as the volunteer, I confirmed that the options to create, update, and delete users are available.
Screenshot 2024-09-10 at 11 04 57 PM
Screenshot 2024-09-10 at 11 05 33 PM

**Review by crystallow1168 — APPROVED** [review]
Hi @ImzIssa,

Changes are working as expected and below are my findings:


image

✅ "Other Links" appear on user's dashboard after assigning a user (core team role) with "See User Management Tab (Full Functionality)" permission.


image

Side note: ❗️When trying to assign the "See User Management Tab (Full Functionality)" permission to user with volunteer role, it shows that the permission has been assigned. Also, "Other Links" does not shows up on the volunteer user's dashboard.

image
✅ The user (core team role) has access to the full functionality of the page (create, delete, and update users).

**Review by neeharikakoniki — CHANGES_REQUESTED** [review]
I tested the PR using the correct frontend and backend branches and encountered a few issues. When I created a new user and logged in with the owner account, I noticed that the new user had the "See User Management Tab (Full Functionality)" permission enabled by default. Additionally, when logging in as the volunteer, the User Management tabs were not visible.
image
image

**Review by Muzammil603 — APPROVED** [review]
image
I have tested this functionality but it is not working .

**Review by SFA23SCM35V — APPROVED** [review]
Logged IN as the chosen user, navigated to  The “Other Links” button appeared with the “User Management” option available with access to the full functionality of the page (create, delete, and update users).

approving

**Review by mrinalini-raghavendran19 — CHANGES_REQUESTED** [review]
Hello, I reviewed this PR and created a -
1) Owner account
2) Volunteer account 

I used the PRs mentioned for complete testing and did not find the changes working for me. 

The new volunteer account doesn't display the `other links` tab for me. Please let me know if I missed out on any steps or permissions to re test the PR or add it to your `how to test`.

Screenshot 2024-09-30 at 4 43 36 PM

Cheers

**Comment by navya9989** [comment]
Hi, The PR is working as expected, Here is the screenshot for reference.
PR 2478

**Review by navya9989 — APPROVED** [review]

**Pull request closed without merging**
