### PR TITLE
Niketha - Fix Category column on Projects page

### PR DESCRIPTION
**Pull request by nikethaanand**
# Description
Fix Category column on Projects page 
Other Links>Projects>Category
All projects have an ‘Unspecified’ category by default when all projects are loaded. It should show their actual category. 

Fixes # (bug list priority high/medium/low x.y.z)

## Related PRS (if any):
This frontend PR is related to the Niketha_categorycolumn PR.

## Main changes explained:
- Added category column in projects page

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links→ Project
6. The category name should load automatically. Earlier all the field in the dropdown would load as unspecified.
7. Category name loads as saved in the project details.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/24eecbe6-d041-43c0-9d90-1dfdf1ebba2e

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by chu-ziyu — APPROVED** [review]
I have tested this PR and everything worked as expected in both light mode and dark mode.
Screenshot 2024-09-24 at 2 20 45 PM
Screenshot 2024-09-24 at 2 21 40 PM
Screenshot 2024-09-24 at 2 22 00 PM

**Review by mrinalini-raghavendran19 — APPROVED** [review]
Looks good to me!

The categories for all projects were initially 'unspecified' and now they show the actual categories of the projects:

Before:

Screenshot 2024-09-24 at 6 14 13 PM

After:

Screenshot 2024-09-24 at 6 15 29 PM

Screenshot 2024-09-24 at 6 15 51 PM

**Review by manikittu810 — APPROVED** [review]
Hello @nikethaanand 
Everything is workin as mentioned
Screenshot 2024-09-24 at 7 18 26 PM

Thank you.

**Review by RishithaMamidala — APPROVED** [review]
@nikethaanand 
The changes in PR works as expected. The Category name loads as saved when adding project details.
PR 2719
PR 2719-2

**Review by Lexie5212 — APPROVED** [review]
I tested the PR. The projects will show their own categories when refreshing the page and adding a new project with its category.

https://github.com/user-attachments/assets/f7bfab63-d24f-493c-9559-a3a7bb8dcce6

**Comment by saurabhshetty29** [comment]
I tested this PR, It is working as expected.
Screenshot 2024-09-24 at 9 34 37 PM

**Comment by tharunaa-1** [comment]
Tested the PR and looks as expected.

image

image

**Review by SFA23SCM35V — APPROVED** [review]
Everything is working as expected approving the PR
PR 2719

**Review by nevatiarishabh — APPROVED** [review]
I have tested this PR. Everything is working as expected. The actual category of the projects is shown instead of 'Unspecified'. 

Screenshot 2024-09-25 at 11 24 50 AM
Screenshot 2024-09-25 at 11 26 30 AM

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and it works as expected. 

Screenshot 2024-09-25 163316

**Review by anirudhsk2107 — APPROVED** [review]
Changes are working as expected 
Screen Shot 2024-09-25 at 6 17 07 PM

**Review by khushijain03 — APPROVED** [review]
Hello @nikethaanand ,
Looks good to me, everything is working as mentioned. 
Before: 
Screenshot 2024-09-25 at 8 35 18 PM

After: 
Screenshot 2024-09-25 at 8 45 18 PM

**Review by neeharikakoniki — APPROVED** [review]
he addition of the category column to the Projects page works seamlessly. I tested the changes by following the provided steps, and the category names now load correctly as saved in the project details, instead of defaulting to "Unspecified." Everything worked as expected without any issues.
image

**Review by ashmita123 — APPROVED** [review]
Tested PR #2719. The category column now correctly displays project categories instead of 'Unspecified' on the Projects page in both light and dark mode. Everything works as expected. 

https://github.com/user-attachments/assets/a9c6648a-6647-4ebe-b653-78e690e6f9f1


https://github.com/user-attachments/assets/f09ce0d7-8ed4-4f1a-8cf5-773a49eabff8

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
sc

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and its working as expected.


https://github.com/user-attachments/assets/0c592daa-b5c7-4d38-81a4-bd0f968891f8

**Review by Vincent-space — APPROVED** [review]
Hi @nikethaanand. I tested this PR and everything looks good.
PR 2719

**Review by ziyanw52 — APPROVED** [review]
It works for me. The category column was automatically show with specific content when I enter into this project page. And when I try to add a new project with an assigned category, it can be added properly as well.
101727406172_ pic_hd

91727405997_ pic_hd

**Review by nishitag5 — APPROVED** [review]
Everything is working as expected.

https://github.com/user-attachments/assets/0da240a5-f65c-42a2-9605-df181728a3f1

**Review by lcohen730 — APPROVED** [review]
All projects now show their correct category when the projects page is loaded. Good job.

https://github.com/user-attachments/assets/2dfffe79-1c03-48ef-8758-216c99854408

**Review by aaryaneil — APPROVED** [review]
The changes work as expected and the category loads as mentioned during project creation.
Screenshot 2024-09-28 at 9 02 01 AM
Screenshot 2024-09-28 at 9 02 08 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
