### PR TITLE
Peizhou_Fix the To Date to be Earlier than From Date Issue

### PR DESCRIPTION
**Pull request by ZhangPeizhou**
# Description
Capture2

## Related PRS (if any):
This frontend PR is not related to any backend PR, please just check in to the development branch.

## Main changes explained:
- Fix the issue that on the Dashboard, under Tasks and Timelogs, in Search by Date Range, the To date can be earlier than the From date

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in
5. on the Dashboard, under Tasks and Timelogs, in Search by Date Range, check if the To date can be earlier than the From date. An alert will be displayed if so.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/8b5d9c82-6b91-4431-9e4f-2d3770fdb28d

## Note:
The issue of the system default alert not being beautiful enough will be handled in a separate PR. This PR focuses on functionality.

### CODE REVIEW

**Comment by vishnupriyaatheti** [comment]
@ZhangPeizhou As per the given information I have verified this PR and below are the observations:
1) Valid Date Range: Working Fine, but I dont see any data populated on the screen after click of search button, I have used Admin account for this testing, Please let me know where data will be populated and which account should use to test it.
2) Invalid Date Range: 
            ii) From Date is given before the To Date. Working as Expected.
3) Same Date: Working fine, As part of data population on screen I need to valid test account. please let me know how to see the data on screen after click of search.
4) Empty Dates: I have clear Date in from date range( or vice versa i,e..To Date Range) and clicked on Search button. No data is displayed. But when I click on Calendar icon, the icon is not displaying. And also check by clear Date in two date ranges, no Calendar icon is displaying after click on calendar icon,
PR #2587
PR #2587(1)

**Comment by AJAYINAVOLU** [comment]
Invalid Date Range:
The start date is set after the end date. This is functioning correctly.

Empty Dates:  When I clear the date in the start date field (or the end date field), press the Search button, and then click on the Calendar icon, it doesn't appear.





https://github.com/user-attachments/assets/8b80fff0-dc85-456d-939c-a6cfab1bcdb1

Thank You

**Review by manikittu810 — APPROVED** [review]
Hello @ZhangPeizhou 
I have reviewed the PR as mentioned and it is working fine by displaying an alert message.

Screenshot 2024-08-22 at 11 18 45 AM

As @vishnupriyaatheti mentioned , code could be improved in terms of readability.
Thank you.

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.

https://github.com/user-attachments/assets/18a34731-2b5e-4b89-bc2b-8fa553671c41

**Review by SMitta11 — APPROVED** [review]
I tested and it is giving the required popup when to date is earlier than end date.
Screenshot:

**Review by Gauravmg6 — APPROVED** [review]
Everything works as expected.
Screenshot 2024-08-25 013337

**Review by RishithaMamidala — CHANGES_REQUESTED** [review]
The alert from date to be before to date works correctly.

But when we clear dates using clear button, the page freezes and does not work. See below video for details.

https://github.com/user-attachments/assets/5070d805-6021-4867-a247-0943acf4a1a2

**Review by Pranay-ai — APPROVED** [review]
Hey @ZhangPeizhou 
I have Revied the PR it's working as expected, PFA for reference
image
Thank You

**Review by Abhinav-Ankur786 — APPROVED** [review]
If the end date is before the start date it is throwing the error message as per PR

Screenshot 2024-09-14 at 3 31 51 PM

**Review by sam19981 — CHANGES_REQUESTED** [review]
hi @ZhangPeizhou ,

I tried testing the changes, but I don't see a message popping up when the 'To' date is earlier than the 'From' date for an administrator. Please take a look at the video below.


https://github.com/user-attachments/assets/de2c3cbf-06bc-4ab7-82e5-d1a7dcdb0e27

**Comment by tharunaa-1** [comment]
it throws the pop up as expected.
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
