### PR TITLE
Dhrumil-Badge-Management-Page-Refresh-Fix

### PR DESCRIPTION
**Pull request by ddshah878**
# Description
image

## Related PRS (if any):
Related https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2539 and https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2800

## Main changes explained:
Fixed the search bar issue that caused it to navigate to a different page or refresh the page.

## How to test:

1. Check into the current branch
2. Do npm install and ... to run this PR locally
3. Clear site data/cache
4. log as admin/owner
5. Go to Other Links → Badge Management
6. Type a name in the search bar and press Enter. The page should not refresh or navigate to another page.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/629de82a-74a0-439f-ba21-19064db57b06

### CODE REVIEW

**Review by CodewithKoushica — APPROVED** [review]
Tested the fix, and everything works smoothly. The search bar no longer refreshes or navigates away on pressing 'Enter,' which makes for a better user experience. This change addresses the issue effectively without disrupting other components on the Badge Management page. Nice work! Approving the changes.


https://github.com/user-attachments/assets/732f5ddf-7e99-4b38-a2ec-691b11aaa95b

**Review by samarth9201 — APPROVED** [review]
Works as expected! Searching does not refresh page

Screenshot 2024-11-01 003105

**Review by hqzhu0913 — APPROVED** [review]
Search now works smoothly without refresh.
Screenshot 2024-11-01 at 4 35 57 PM

**Comment by SatyashanthiT** [comment]
Works as expected. 
image

**Comment by anji-annavarapu** [comment]
https://github.com/user-attachments/assets/3aa51733-87b4-4a0e-a2d5-cb83af4a049f

its working as expecting

**Review by anji-annavarapu — APPROVED** [review]

**Review by Jingyii800 — APPROVED** [review]
I have tested the feature. Now texting in the search bar issue doesn't cause it navigates to a different page or refresh the page.

https://github.com/user-attachments/assets/81a26363-f7fb-4b4e-929d-36194805383f

**Review by nikhilgiri0226 — APPROVED** [review]
I have reviewed this PR. The issue with badge assignment tab becomes disable after pressing enter in the search bar is fixed now. Kindly find the video below.


https://github.com/user-attachments/assets/c628b6e0-3106-4537-a8ee-6b137a8d4a58

**Review by varun-elango — APPROVED** [review]
The change looks good and the functionality is working as expected. Typing a name in the search bar does not refresh or navigate to another page.
PR2830_1
PR2830_2

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the search functionality does not navigate to a new page on clicking "Enter".

https://github.com/user-attachments/assets/154e1a35-8e94-4bfe-8b7b-fe75ec5b39c6

**Comment by RashmiKY98** [comment]
Checked the functionality and is working fine. Tested the same with different web page dimensions and different browser. Tested in dark mode as well. No issues found. 
Screenshot 2024-11-03 000946
Screenshot 2024-11-03 000602

**Review by vijay10pk — APPROVED** [review]
Change are working as expected.

https://github.com/user-attachments/assets/46b880f4-df2b-4f54-abc5-93d95a9901b2

**Review by Muhideenthegreat — APPROVED** [review]
Verification:

Doesn't refresh unneccesarily upon hitting Enter key, bug resolved!

Screenshot 2024-11-06 at 11 47 19 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/bb9091e4-0a11-4b7a-97a5-96e750f42ef6

**Review by manikittu810 — APPROVED** [review]
Hello @ddshah878 
Everything is working as expected.
Thank you.
Screenshot 2024-11-07 at 8 41 22 PM

**Comment by geetamatkar** [comment]
Testing this PR and the page did not refresh or navigated to another page.

Screenshot 2024-11-08 at 6 59 09 PM

**Review by humera314 — APPROVED** [review]
works fine it does not refresh or go to another page

https://github.com/user-attachments/assets/40d1625b-7ae2-41f4-b99e-d0a498bff9c1

**Pull request merged**
