### PR TITLE
Shereen Add Tool - Created API call

### PR DESCRIPTION
**Pull request by pshereen**
# Description
Updated Add Tool component. Added API call for passing Add Tool form data to the backend, added form validation, made updates to store the add tool data into redux store.
# (WBS): 4.5.7

## Related PRS (if any):
This frontend PR is related to the [#970](https://github.com/OneCommunityGlobal/HGNRest/pull/970) backend PR.

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. check into [#970](https://github.com/OneCommunityGlobal/HGNRest/pull/970) backend and start the backend
5. go to http://localhost:3000/BMdashboard/tools/add (log in if you are prompted to do so)
6. Enter data in the form
7. check that after clicking submit button, all the form data is saved successfully.
8. Note that if the tool name is already present in the database, it will give an error message saying, 'Oops!! Tool already exists!'.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/c5106b4f-fa2a-44be-9733-bb6df33d2de3

### CODE REVIEW

**Review by Kavil-Jain-514 — CHANGES_REQUESTED** [review]
I cannot submit the form even after filling out all the details.
This is the error I am getting.
image

image
image


Also, there are a few changes I would like to suggest.
Firstly, please provide asterisk symbols wherever the field is required.
Secondly, error messages should be available for all required fields; for example, here, with the purchase and return date, shipping fee, taxes, phone number, image, and purchase link, does not have any error message even if I leave that blank.
image

Lastly, the error message for a few fields appears twice in the form.

**Review by Sandhya1236 — DISMISSED** [review]
I have successfully tested the updated Add Tool component, which now includes an API call to pass form data to the backend, form validation, and updates to store the data in the Redux store. This frontend PR, related to backend PR #970, was tested by checking out the current branch, running npm install, and starting the backend from the dev branch. Navigating to http://localhost:3000/BMdashboard/tools/add and logging in if prompted, I entered data into the form and verified that clicking the submit button saved all form data successfully. Additionally, if the tool name already existed in the database, the appropriate error message, 'Oops!! Tool already exists!', was displayed, confirming that all functionalities worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/7fa5d23d-9522-4f15-9040-3d20ed155f03

**Review by jinxyou — CHANGES_REQUESTED** [review]
hi, after several tries with all the details filled, and under different account, I'm keeping getting this error message. Can you please check this isue?
Screenshot 2024-06-15 195357
Screenshot 2024-06-15 195603

**Comment by pshereen** [comment]
> I cannot submit the form even after filling out all the details. This is the error I am getting. image
> 
> image image
> 
> Also, there are a few changes I would like to suggest. Firstly, please provide asterisk symbols wherever the field is required. Secondly, error messages should be available for all required fields; for example, here, with the purchase and return date, shipping fee, taxes, phone number, image, and purchase link, does not have any error message even if I leave that blank. image
> 
> Lastly, the error message for a few fields appears twice in the form.

Thank you for your detailed feedback and suggestions.
One of the backend PR links was taking to the wrong page. I have removed it.
Please go to the related backend PR and pull it. I have provided asterisk symbols wherever the field is required. And removed the repeating error at the bottom of the form and gave a generic error massage instead.
Kindly verify updated feature again.

**Comment by pshereen** [comment]
> Thank you for your detailed feedback and suggestions.
> One of the backend PR links was taking to the wrong page. I have removed it.
> Please go to the related backend PR and pull it.

Thank you for your feedback.
One of the backend PR links was taking to the wrong page. I have removed it.
Please go to the related backend PR and pull it again.
Kindly verify all the updated features are working.

**Review by HowieMiao — DISMISSED** [review]
Still seem to be having similar errors to above after updated and npm installing and updated changed PR-970

image

**Review by Parth-tech — CHANGES_REQUESTED** [review]
Hey Shereen,

I tested the code and it does add the tool correctly. I changed your pull request description to highlight what backend to checkout to before testing.

I would like to see validation for:
1. `Only numbers allowed for Supplier Phone Number`
2. `End Date >= Start Date`
3. UI : `Add Type: Tool` -> 'Add a Tool` (just a suggestion)


I was able to add a Tool with the following data: (`phone number is alphabets and return date is less that purchase date`)
Screenshot 2024-06-28 at 3 49 03 PM

**Review by DiyaWadhwani — CHANGES_REQUESTED** [review]
Hi Shereen,

Tested out your changes as per your instructions. Tools are getting created and duplicate ones give me the error with pop-up mentioning there is already a tool with the same name. I have attached a video of this below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/631384c8-7f8f-4901-9e51-ff72432a52ac

However, creating a tool with phone number as alphabets is also being allowed, which should not be the case. The phone number text field must ideally only accept numbers from 0-9. Also there is no specified length and I can add numbers of length>10.
The start date must either be before or same as the end date.
I would suggest having an information icon next to the invoice number or ID (to maybe inform the user of the format or mention where they can find this)

Screenshot 2024-06-29 at 5 03 54 AM

Kindly review these.
Thank you

**Review by nyelmela — DISMISSED** [review]
I've successfully tested the updated Add Tool component. I tested the frontend PR (linked to backend PR #970) by navigating to http://localhost:3000/BMdashboard/tools/add and logging in if needed, I filled out the form and confirmed that the submit button correctly saved the data. Additionally, the error message 'Oops!! Tool already exists!' appeared if a duplicate tool name was entered, confirming that all functionalities worked as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/c57e72e1-87ce-4864-856b-a2c816e497d2

image

**Comment by pshereen** [comment]
> Hey Shereen,
> 
> I tested the code and it does add the tool correctly. I changed your pull request description to highlight what backend to checkout to before testing.
> 
> I would like to see validation for:
> 
> 1. `Only numbers allowed for Supplier Phone Number`
> 2. `End Date >= Start Date`
> 3. UI : `Add Type: Tool` -> 'Add a Tool` (just a suggestion)
> 
> I was able to add a Tool with the following data: (`phone number is alphabets and return date is less that purchase date`) Screenshot 2024-06-28 at 3 49 03 PM

Hi Parth,
Thank you for your detailed feedback.
I have fixed the issues related to Phone number and Rental To Date validation.
Please pull again and test it.
Make sure to clear the cache before testing.

**Comment by pshereen** [comment]
> Hi Shereen,
> 
> Tested out your changes as per your instructions. Tools are getting created and duplicate ones give me the error with pop-up mentioning there is already a tool with the same name. I have attached a video of this below.
> 
>  970+2306.mp4 
> However, creating a tool with phone number as alphabets is also being allowed, which should not be the case. The phone number text field must ideally only accept numbers from 0-9. Also there is no specified length and I can add numbers of length>10. The start date must either be before or same as the end date. I would suggest having an information icon next to the invoice number or ID (to maybe inform the user of the format or mention where they can find this)
> 
> Screenshot 2024-06-29 at 5 03 54 AM
> Kindly review these. Thank you

Hi Diay,
Thank you for your detailed feedback.
I have fixed the issues related to Phone number and Rental To Date validation.
(The information icon next to the invoice number or ID to maybe inform the user of the format feature will be a new requirement and can be created as a new PR in future.)
Please pull again and test it.
Make sure to clear the cache before testing.

**Comment by pshereen** [comment]
> Still seem to be having similar errors to above after updated and npm installing and updated changed PR-970
> 
> image

Hi,
Please pull backend from the below link for testing this frontend. 
https://github.com/OneCommunityGlobal/HGNRest/pull/970
Make sure to clear cache before testing.

**Comment by pshereen** [comment]
> I cannot submit the form even after filling out all the details. This is the error I am getting. image
> 
> image image
> 
> Also, there are a few changes I would like to suggest. Firstly, please provide asterisk symbols wherever the field is required. Secondly, error messages should be available for all required fields; for example, here, with the purchase and return date, shipping fee, taxes, phone number, image, and purchase link, does not have any error message even if I leave that blank. image
> 
> Lastly, the error message for a few fields appears twice in the form.

Hi Kavil,
Thank you for your detailed feedback.
I have fixed the issues related to validation.
Please pull backend from the below link.
https://github.com/OneCommunityGlobal/HGNRest/pull/970
Make sure to clear cache before testing.

**Review by HowieMiao — DISMISSED** [review]
Changes in place are functional, only numbers are accepted for phone number and rental date validation looks good. Cannot add duplicate tools

image

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR as per the instructions mentioned and was able to add details and price of tool and got a pop up message that tool has been successfully created. Below is the video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/c822f327-2f2a-4f7a-9e61-0442df7f489a

**Review by jinxyou — DISMISSED** [review]
All tests are going well now and no more error will be popped off. Great work!
Screenshot 2024-07-05 221018
Screenshot 2024-07-05 221026

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and it works as expected. I got a popup when the form data was submitted and got an error popup for duplicate entries.
Screenshot (32)

Screenshot (33)

**Review by Parth-tech — DISMISSED** [review]
Hey Sheeren,
Great job done. I am able to add a tool successfully and the validation rules look great too.

`Image Reference:`
Screenshot 2024-07-05 at 10 58 51 PM

**Review by Kavil-Jain-514 — CHANGES_REQUESTED** [review]
All the fields are working fine, but there is one change. 
When the user selects Rental for the Purchase/Rental field and again changes the dropdown to purchase, then while submitting the form, the Return date says required as technically it should not show that error message.

Please take a look at the video below for reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/2529cd49-aaaf-4c48-9c06-6acb5a605b36

**Comment by pshereen** [comment]
> Hi Shereen,
> 
> Tested out your changes as per your instructions. Tools are getting created and duplicate ones give me the error with pop-up mentioning there is already a tool with the same name. I have attached a video of this below.
> 
>  970+2306.mp4 
> However, creating a tool with phone number as alphabets is also being allowed, which should not be the case. The phone number text field must ideally only accept numbers from 0-9. Also there is no specified length and I can add numbers of length>10. The start date must either be before or same as the end date. I would suggest having an information icon next to the invoice number or ID (to maybe inform the user of the format or mention where they can find this)
> 
> Screenshot 2024-06-29 at 5 03 54 AM
> Kindly review these. Thank you
Addressed.

**Comment by pshereen** [comment]
> All the fields are working fine, but there is one change. When the user selects Rental for the Purchase/Rental field and again changes the dropdown to purchase, then while submitting the form, the Return date says required as technically it should not show that error message.
> 
> Please take a look at the video below for reference.
> 
>  PR.2306-970.mp4

Fixed the issue.
Please review again.

**Comment by pshereen** [comment]
> All the fields are working fine, but there is one change. When the user selects Rental for the Purchase/Rental field and again changes the dropdown to purchase, then while submitting the form, the Return date says required as technically it should not show that error message.
> 
> Please take a look at the video below for reference.
> 
>  PR.2306-970.mp4

Addressed

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
