### PR TITLE
Shereen unit test weekly summary modal

### PR DESCRIPTION
**Pull request by pshereen**
# Description
Unit test weekly summary modal

## How to test:
1. check into current branch
2. do `npm install` and `npm test WeeklySummaryModal.test.js` to run this PR locally
3. Make sure all the tests are passed.

## Screenshots or videos of changes:

image

### CODE REVIEW

**Review by linkhanthtel — DISMISSED** [review]
All test passed! Nice work!

**Review by Pandani07 — DISMISSED** [review]
The tests passed as expected. 
Screenshot 2024-04-16 at 10 07 17 PM

**Review by curiousfancier — DISMISSED** [review]
All test cases are working well
review 1

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-04-19 at 10 27 16 PM

**Review by dkt6 — APPROVED** [review]
All test cases are working as expected.
Thank you for the great work!

UnitTestWeeklySummary

**Review by MinSun0814 — DISMISSED** [review]
image
Tested PR and all tests passed.

**Comment by KaushikMreddy** [comment]
Hi, 
all your test cases have passed
image

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and it passed all the test cases. Please refer the screenshot attached.
PR 2164

**Review by scoopstroop92 — CHANGES_REQUESTED** [review]
Hello @pshereen good job ! However  a test case verifying the toggle functionality can also be added  because  the state of the toggle switch is also one of the core functionality of the component

**Review by JatinAgrawal94 — DISMISSED** [review]
All test's passed. Good work!

**Comment by pshereen** [comment]
> test case verifying the toggle functionality

Added.
Please test again.

**Comment by pshereen** [comment]
> Hello @pshereen good job ! However a test case verifying the toggle functionality can also be added because the state of the toggle switch is also one of the core functionality of the component

Added.
Please test again.

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
1 test failed out of 5.
Screenshot 2024-07-04 at 3 42 26 PM (2)
Screenshot 2024-07-04 at 3 42 29 PM (2)

**Comment by pshereen** [comment]
> All test's passed. Good work! 

Issue Fixed.

**Pull request merged**
