### PR TITLE
 removed line 14 in public/index.html that was redundant and causing …

### PR DESCRIPTION
**Pull request by lacnoskillz**
# Description
 (PRIORITY LOW) Kai: Fix config.js console error
In our public html we are looking for a config.js but there isn't any such file which is causing an error in the console

image
Determined that the config.js file is no longer needed/ was not missing and can remove the line 14 in public/index.html causing the error

## Related PRS (if any):

N/A

## Main changes explained:
- Delete line 14 in public/index.html

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. open the console and confirm the error is no longer there

## Note:
The  config.js was added in PR#[82](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/82#issue-691270063),  and deleted in PR#[1053](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1053#issue-1823389008)

### CODE REVIEW

**Review by Jiyuanxia — COMMENTED** [review]
Hi @lacnoskillz , I have reviewed your pull request and tested it. The error message has been removed in the concole. Good job!

Screenshot 2023-10-24 152224

**Review by Sssky-18 — APPROVED** [review]
Hi @lacnoskillz, it looks like that the error has been successfully removed after your smart fix. Thank you for your contribution!
**Before:**
PR#1444_before


**After:**
PR#1444

**Review by AaronPersaud — APPROVED** [review]
Hi @lacnoskillz, everything looks good!

<b>Before</b>

image

<b>After</b>

image

**Review by KurtisIvey — APPROVED** [review]
Great fix! Was trying to find where this thing was for a while but didn't think to check the index.html. Living up to your github username for sure 😂

Tested out the app for general user interactions and found everything to still function as before. Great job

pr1444 no issues

**Pull request merged**
