### PR TITLE
Shereen - Unit tests for pause and resume button component.

### PR DESCRIPTION
**Pull request by pshereen**
# Description
Unit tests for pause and resume button component.

## How to test:
1. check into current branch
2. Do npm install and npm test PauseAndResumeButton.test.js to run this PR locally
3. check all 7 tests are passed

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by Coops023 — APPROVED** [review]
Hi i reviewed your PR and all 7 tests passed 

PR-1951

**Comment by dhairya-mehta** [comment]
Hi , I reviewed your PR and all the 7 test cases passed!
image

**Review by ShengjieMao — APPROVED** [review]
All tests passed. Well-tested components and tested edge cases and different action scenerios
PR_1951

**Review by TareqMia — APPROVED** [review]
Hi @pshereen, tested the PR, all the tests passed. The components rendered and functioned properly 👍 
Screenshot 2024-02-16 at 6 53 22 PM

**Review by TapanPathak — APPROVED** [review]
Hi, All test cases passed! 

Screenshot 2024-02-16 at 7 06 08 PM

**Review by AaronPersaud — APPROVED** [review]
Hi @pshereen, I've tested and all the tests pass! Good work!

image

**Review by swathyjayaseelan — APPROVED** [review]
The test cases look good and they all PASS.
Untitled

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 25 - PR1

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and worked as expected.

Captura de tela 2024-02-17 225349

**Comment by nnamdixobi** [comment]
All test cases passed and looks good 
image

**Review by Renanluizssx — COMMENTED** [review]
Hi @pshereen, i tested your branch and it's running correctly, but i noticed something, sometimes when i click in pause, when the modal is open, the "..." don't appear, is it correct? See my review below
Screenshot 2024-02-20 102902


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/ddda4118-5c2f-4655-bff0-886ae5b93c22

**Comment by beblicarl** [comment]
All test cases passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
