### PR TITLE
Shrey_unit_test_userManagement_DropDownSearch

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for DropDownSearchBox component

## How to test:
1. check into current branch
2. do `npm install` 
3. npm test DropDownSearchBox.test.js
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-12-02 at 10 35 55 PM

### CODE REVIEW

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed. Great Job!

Week 15 - PR3

**Comment by ptrpengdev** [comment]
I tested your PR. All cases passed without any issue.

image

**Comment by Cavein254** [comment]
Hi @Shreyj14, the test run as expected
Screenshot from 2023-12-07 14-24-42

**Comment by DragonSlayer2401** [comment]
I tested your PR and all tests passed with no warnings or errors. Please watch the PR video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/ea7c2045-ebbc-499d-88f3-18694061047b

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
