### PR TITLE
Nida Fix -  Sort list of names (Resources) in the WBS Add Task/Edit Task by first name or last name

### PR DESCRIPTION
**Pull request by NidaZaki**
# Description
image

# Fixes (bug list priority medium)
Added `sortByStartingWith` function in the TagsSearch component that filters the members list based on `includes` and then using `sort` function on the filtered list, giving higher priority to the names starting with the input using `startsWith` function.

## Main changes explained:
 `sortByStartingWith` function filters the members list based on `includes` and then using `sort` function to give high priority to the first name that starts with the input, then the last name starting with the input (in case the first name does not start with the given input), followed by other names that include the input.

## How to test:
1. Check into current branch
2. Log as admin user
3. Go to Other Links→ Projects→ WBS→ Select any task → Add Task Button/ Edit Button → Resources field (type in names)
4. Verify that the list of names is sorted by either the first name or the last name starting with the input, followed by other names that include that input.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/16ce2152-a87a-434c-aa22-d3a9cff4c229

### CODE REVIEW

**Comment by AnishPandita** [comment]
Hi @NidaZaki I tested your PR and it seems to work well.
Screenshot 2023-06-27 at 5 06 26 PM
Screenshot 2023-06-27 at 5 00 00 PM

**Review by AnishPandita — APPROVED** [review]

**Comment by Lucas-E** [comment]
Thank you everyone! I will be moving this one to final review!

**Review by cvtqx — APPROVED** [review]
Sorting algorithm works as described!

Searching by first name:

Screen Shot 2023-06-28 at 11 34 57 AM


Searching by last name:

Screen Shot 2023-06-28 at 11 35 06 AM

**Comment by KaixiangGU** [comment]
Screenshot 2023-06-28 at 11 47 57 AM
Works as intended!

**Pull request merged**
