### PR TITLE
yihan eliminate need for additional “save” with adding Projects or Teams

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Main changes explained:
- Update UserProfile.jsx for (1)adding handleSubmit property on TeamsTab and ProjectsTab, (2) using userProfileRef.current to update user profile, (3) transfering disabled property to TeamsTab and ProjectsTab.
- Update TeamsTab.jsx and Projects.jsx for transfering submit function and disabled property to AddTeamPopup and AddProjectPopup component.
- Update AddTeamPopup.jsx and AddProjectPopup.jsx for executing handleSubmit function when clicking on "confirm" button.
- Update UserProjectsTable.jsx/.css and UserTeamsTable.jsx/.css for disabling assign button and adding toolTip to button when save changes warning exists.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to a user's profile → Teams/Projects tab → Assign teams/projects → choose teams/projects → Confirm
5. verify (1) assigned team/project are saved successfully without clicking on "save changes" button, (2) team popup close automatically after click on confirm button, (3) Assign Team and Assign Project button are disabled when save changes warning exist.

## Screenshots or videos of changes:
Assign Team:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/7f83b756-f94c-417d-a3af-b43cf0b82144

Assign Project:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/cb19371b-a246-40b3-875b-e563a3220cfd

## Note:
When assigning projects, you may notice that the save changes warning is still there after clicking on "confirm" button. This bug appears in Dev as well, so I gonna log it in the bug list. As a result, you can refresh the page to check if the assigned projects are saved successfully when testing that part.

### CODE REVIEW

**Review by jonathancarpena — DISMISSED** [review]
@AriaYu927 Everything is working like you described. 👍

After I assigned the user to a team, there was no need to press save changes. I believe it would be nice to have a feature similar to this for the delete team function, but instead prompt the user for confirmation. This other feature would promote an easy user flow.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/63978806/8b4be797-3c3c-4daf-8d38-b7717680367a

**Comment by rachnapandya** [comment]
I tried everything it's not working for me.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/53634437/5ca35d0b-084b-4c41-a37a-c40a69cd5991

**Comment by AuroraLovesWhales** [comment]
Hi @AriaYu927. I have tested your PR. The functionality works for adding Project/Tasks, but I can't test it for adding Teams. For some reasons, the team names are not populating for me when I input the first few initial characters. Please check the video below for reference:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/d2d02080-9a1b-4c8f-b4b9-e9c86628fe1b

**Comment by GKD890** [comment]
Hi I don't if it's just me, but seems my search function in **assigning projects** doesn't work. I have tried re-login, refresh, and using private window. Moreover, even copy and paste exact project name, it still doesn't allow me to assign. I delete the tested volunteer user from one project and was testing if I could reassign the user into the same project.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/57503876/f1f5c18e-79ff-418c-95a3-c55bf2c822f7

During my several times test, there were one time that the search is working properly.

**Review by KurtisIvey — DISMISSED** [review]
Works as intended. Great improvement that enhances user experience. 
pr936 works well

**Comment by beblicarl** [comment]
I can confirm that the autosave works as you have described. Kudos to you !!

[screencast-hgnapplication_react_beta.surge.sh-2023.06.27-13_46_47.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/64633efd-8b7b-4040-bb39-328fae1a4869)

**Review by beblicarl — APPROVED** [review]

**Review by cvtqx — COMMENTED** [review]
One question: after clicking 'confirm' button do we want the 'add team' popup window to stay? perhaps would be a better user experience if this window (below) disappeared?  

After saving

Other than that, the functionality of this PR has been implemented perfectly. Both assigning a team and a project work as described and are saved upon clicking confirm button. 

Assigning team:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/904e9912-061b-4327-9009-2d9095f5bcce

Assigning project:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/849f8f83-a830-448b-a426-7b21d8bfb101

**Review by mahamakhan — APPROVED** [review]
Added the project and no confirmation needed. Works as mentioned. 

image

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this to final review!

**Comment by one-community** [comment]
> One question: after clicking 'confirm' button do we want the 'add team' popup window to stay? perhaps would be a better user experience if this window (below) disappeared?

Good suggestion! Please apply this. ONLY for the team popup though. For Projects, it should stay up so I can add the person to multiple projects.

**Comment by AnishPandita** [comment]
HI @AriaYu927 I tested it and didn't have to use save button to reflect the changes. Working as desired.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/23f87b13-d2e6-4c07-babe-64c9c01b213f

**Review by NidaZaki — APPROVED** [review]
Amazing job! Tested this PR and it works great!

**Comment by AriaYu927** [comment]
Hi guys, thanks for all your reviewing. I added the functionality which is close the team popup after choosing a team and clicking on confirm button. Since my search team function is not working, I test the code on Project tab where it succeed. But I'm not sure if it also works for team tab. So, please review this PR again and let me know if there's any problems.

**Comment by LucileTech** [comment]
Hi @AriaYu927 I am not completely sure if the final result is what's intended, but here is a video of my test. The teams and projects are saved without clicking the save button. However, the pop up do not close when choosing a project. 
It is closing when choosing a team. 
Here's my test : 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111132148/b9b262b5-09b2-42b6-9efe-77072fee2d14

**Review by iTvX — CHANGES_REQUESTED** [review]
My search team function is not working, and I cannot add any team (even when I write down "AI team," it also cannot be added). However, the project function works as described.

**Review by yaow62023 — COMMENTED** [review]
Hi, @AriaYu927. I have tested the newly added feature, and in the teams tab, the assign team function will automatically close the popup window after selection, while in the projects tab, the popup window does not close automatically. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/f387f412-e34e-4138-b83a-30a1acf32185

At the same time, I discovered a bug: when I switch to another window and then return to the HGN page, the first time of the assign team function becomes ineffective. It requires selecting the same team for the second time to successfully assign. You can see the specific details in the recording.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/7c134e83-f994-46e3-bd43-5b8a25496b60

**Comment by AriaYu927** [comment]
> Hi @AriaYu927 I am not completely sure if the final result is what's intended, but here is a video of my test. The teams and projects are saved without clicking the save button. However, the pop up do not close when choosing a project. It is closing when choosing a team. Here's my test :
> 
>  HGN.APP.-.30.June.2023.mp4

Hi @LucileTech , thanks for your testing! This is the expected result.

**Comment by AriaYu927** [comment]
> My search team function is not working, and I cannot add any team (even when I write down "AI team," it also cannot be added). However, the project function works as described.
> 
> video: https://www.dropbox.com/s/rik146454zp0xez/2.mp4?dl=0

Hi @iTvX , the search team function issue is out of scope. We have other members who are looking into this bug. However, you can fix this by (1) logging in as an Admin/Owner, (2) Other Links -> Teams -> Add yourself to a team, (3) logout and login again.

**Comment by iTvX** [comment]
@AriaYu927 I see, after follow your new instruction, it works fine. Great job, thanks!

**Review by iTvX — APPROVED** [review]

**Comment by AriaYu927** [comment]
> Hi, @AriaYu927. I have tested the newly added feature, and in the teams tab, the assign team function will automatically close the popup window after selection, while in the projects tab, the popup window does not close automatically.
> 
>  2023-06-30.23-21-53.mp4 
> At the same time, I discovered a bug: when I switch to another window and then return to the HGN page, the first time of the assign team function becomes ineffective. It requires selecting the same team for the second time to successfully assign. You can see the specific details in the recording.
> 
>  2023-06-30.23-29-39.mp4

Hi @yaow62023 , thanks for you testing. I tried to reproduce the bug, but I find the root cause of this issue is that you didn't click on "save changes" button after deleted a team. I think a better way to solve this problem is disable the "assign teams" button before we save changes.

**Comment by one-community** [comment]
> I think a better way to solve this problem is disable the "assign teams" button before we save changes.

I agree, let's do that. Thank you both

**Comment by AriaYu927** [comment]
Hi guys, I have added new functionality and updated the description. Please follow the new description to re-review this PR. Thank you!

**Pull request merged**
