### PR TITLE
Kaikanes lessonform design

### PR DESCRIPTION
**Pull request by lacnoskillz**
# Description
This is the design of the Lesson form page from Phase II. It was created based off the prototype below:
image

## Related PRS (if any):
N/A

## Main changes explained:
-Created route
-Created Lesson Page to resemble figma

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as anyone/everyone
4. go to http://localhost:3000/bmdashboard/lessonform
5. check the design against the prototype, check for responsiveness in different screen sizes
6. make sure the new line `overflow: hidden;` in App.css doesn't negatively affect any other pages
## Screenshots or videos of changes:
image

## Note:
No functionality as of now
Working on Drag and drop which  will be a separate PR

### CODE REVIEW

**Review by DavidC0126 — COMMENTED** [review]
Hi @lacnoskillz I tested the PR and it works as intended.

Uploading UI.mov…

**Review by Chuehleo — DISMISSED** [review]
The prototype looks good as well as the responsiveness, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/1ca9d8ce-2047-4c88-9469-20d6db30dc59

**Comment by olenadanykh** [comment]
Hi @lacnoskillz, I've tested your PR, and the lesson form looks great and is responsive. Great work!

PR1477

**Review by Bali2Mohit — COMMENTED** [review]
Hi @lacnoskillz, I have tested your PR and it looks great. Good work.
Screenshot 2023-11-02 at 17 05 48
Screenshot 2023-11-02 at 17 07 20

**Review by Shuhua-L — COMMENTED** [review]
Hi @lacnoskillz, I like your implementation! It matches the prototype and is responsive. However, there seems to be some extra white space at the bottom of the page on certain screen sizes. Is this expected?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/4b310ca7-e1f3-44b0-ab62-0d6396ceea85

**Comment by lacnoskillz** [comment]
@Shuhua-L 
Interesting
Im not getting that on my end
I will look into it

**Comment by lacnoskillz** [comment]
@Shuhua-L 
I think I found a fixed the issue if you could re verify that would be awesome!

**Comment by lacnoskillz** [comment]
fixing double scroll bar issue I found

**Comment by lacnoskillz** [comment]
Think I fixed white space bug

**Review by Shuhua-L — APPROVED** [review]
Nice job fixing the white space. Everything works as intended. Well done!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/4db7e332-5e7f-4331-8f91-099eeb650bd4

**Review by malikjahanzaib — APPROVED** [review]
Hi @lacnoskillz, the design looks as described. Nice work!!!

Test Rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/8182c263-600d-481c-80e5-d32a59d36a81

**Comment by AriaYu927** [comment]
Hi @lacnoskillz , the design looks great! But when I change the screen size, I found that the white space still exist when I zoom the screen to 150%. Please see the video below.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/a2babf03-8d48-4ad3-acbf-af3dd32519e9

**Review by Hemsharavanan — APPROVED** [review]
UI looks pleasing and the form is mobile responsive. Nice work!

Kaikanes lessonform design #1477

**Review by sahilpatel18 — COMMENTED** [review]
The design aligns well with the Figma specifications, and the overall structure is great. However, there are a couple of issues that need attention:

Dynamic Content Resizing: When the .FormContainer grows the .MasterContainer should also adjust to contain it, and the sky blue background should remain consistent around the form. But this is not the case as shown in the video. 

Textarea Resizing: I've noticed that the textarea can be resized to become quite small, compromising usability. To address this, I recommend setting a min-height CSS property for the textarea. This will ensure that it remains functional and maintains a user-friendly appearance, even at its smallest allowable size.

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions. The page looks good to me. It looks as what you described. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/7d9ca82b-05ac-466e-92f0-63d90636be69

**Review by sahilpatel18 — COMMENTED** [review]
The design aligns well with the Figma specifications, and the overall structure is great. However, there are a couple of issues that need attention:

Dynamic Content Resizing: When the .FormContainer grows the .MasterContainer should also adjust to contain it, and the sky blue background should remain consistent around the form. But this is not the case as shown in the video. 

Textarea Resizing: I've noticed that the textarea can be resized to become quite small, compromising usability. To address this, I recommend setting a min-height CSS property for the textarea. This will ensure that it remains functional and maintains a user-friendly appearance, even at its smallest allowable size.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/b463a82f-31ec-4075-8976-8b4c73ba25f9

**Comment by mounica-dingari-by** [comment]
Hi @lacnoskillz , I've tested your PR and it looks great.

Screenshot from 2023-11-04 22-11-36

**Review by savio-henrique — DISMISSED** [review]
Hi @lacnoskillz , the Form looks great! The responsiveness is great too,, the only problem is with the white space in 150% zoom.

# Screenshots

screenshot
mobile

**Review by eduhorta — APPROVED** [review]
Everything is looking good as shown on the Figma design 👍 

image

Responsiveness is working properly.
image

No white spaces at the bottom of the page using 150% Zoom.

image

Great job! 👏

**Review by yi-lin-1234 — APPROVED** [review]
Hi, I've tested your PR, and the lesson form looks great and is responsive. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/f1fd94b9-fb4f-40bf-b37b-e2b206461789

**Review by Shuhua-L — DISMISSED** [review]
I've tested your PR again, with a focus on the blue background and the textarea reacting to different screen sizes. I also wondered if the `overflow: hidden;` under the `root` element would break anything in the app. Happy to report that everything went smoothly, and no bugs were found. Excellent job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/7b0e7645-0684-4ec0-a6fb-973ac2ce14d8

**Review by Bali2Mohit — APPROVED** [review]

**Review by eduhorta — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
