### PR TITLE
Wanting_UnitTest_ProjectTableHeader

### PR DESCRIPTION
**Pull request by wantingxu7**
# Description
unit test for `ProjectTableHeader.jsx`

## Related PRS (if any):
…

## Main changes explained:
Add file `ProjectTableHeader.test.jsx`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. do `npm test ProjectTableHeader.test.js`
4. verify that all tests pass with no error

## Screenshots or videos of changes:
unittest_ProjectTableHeader

### CODE REVIEW

**Review by this-journey — APPROVED** [review]
All tests passed.  Great job!

PR 1639 FE

**Comment by Cavein254** [comment]
Hi @wantingxu7,  checkout you pr and the tests are all passing as expected

Screenshot from 2023-12-07 22-42-10

**Review by pika-chu11 — APPROVED** [review]
Hi @wantingxu7 , the test is passed! Great Job!
PR 1639

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and everything works as intended!

Week 15 - PR6

**Comment by DragonSlayer2401** [comment]
I tested your PR and all tests passed as intended. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/46190e0e-5d33-4ae5-9adf-a3e9f26f263f

**Review by Hemsharavanan — APPROVED** [review]
- The test cases effectively verify the conditional rendering of the delete column based on user permissions.
- Good approach in setting up test suite with Redux mock store and rendering the ProjectTableHeader component within a Provider. 
- All tests have passed.
PR #1639 Wanting_UnitTest_ProjectTableHeader

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-09 at 3 00 08 PM
Good job, @wantingxu7 ! All the cases passed!

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by cvtqx — APPROVED** [review]
All tests pass, great job!
Screen Shot 2023-12-15 at 12 19 15 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
