### PR TITLE
Manikrishna - alert visibility issue resolved, working on both dark and light mode's

### PR DESCRIPTION
**Pull request by manikittu810**
# Description
Screenshot 2024-09-11 at 8 40 33 AM

## Main changes explained:
- Deleted 'danger' bootstrap visibility to light in all places such that it works on both light and dark modes.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ other links ->Badge Management->search By Full Name ->.....
6. enter a name ->select name -> click directly on confirm and check how's the visibility of alert message.
7. enter a name ->select name -> assign badge -> click on confirm and check how's the visibility of alert message.
8. check the alert message is clearly visible on both the modes (light and dark).

## Screenshots or videos of changes:

Before : 
before1_D
before1_L

After : 
After1_D
After1_L

### CODE REVIEW

**Review by vishnupriyaatheti — APPROVED** [review]
@manikittu810 I have reviewed your PR and changes are working as expected.
Screenshot (137)
FE PR 2657
FE PR 2657 (dark mode)
FE PR 2657(light mode)

**Review by RishithaMamidala — APPROVED** [review]
@manikittu810 
I have reviwed the PR and the alert fubctions works and is correctly visible in both the modes.
PR 2657

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/01e26774-4faa-4047-bdea-8992f121983e

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected, good work.
Screenshot 2024-09-12 at 5 30 00 PM
Screenshot 2024-09-12 at 5 30 38 PM
Screenshot 2024-09-12 at 5 31 31 PM
Screenshot 2024-09-12 at 5 31 39 PM

**Review by ArtemisNyx3 — DISMISSED** [review]
The message is readable and visible now. UI is also consistent with other parts of the app.

image
image
image
image

**Review by mohangadde1 — APPROVED** [review]
Screenshot 2024-09-14 111700
Screenshot 2024-09-14 111716
Screenshot 2024-09-14 111742
Screenshot 2024-09-14 111800
Tested the PR, alert is visible both light and dark mode

**Review by Abhinav-Ankur786 — DISMISSED** [review]
checked the functionality and the pop up prompt is coming up both in light and dark mode as per PR
Screenshot 2024-09-14 at 3 13 00 PM
Screenshot 2024-09-14 at 3 12 31 PM

**Review by sam19981 — APPROVED** [review]
Changes are working as expected

Screenshot 2024-09-14 at 10 27 12 PM
Screenshot 2024-09-14 at 10 27 32 PM

**Review by Gauravmg6 — APPROVED** [review]
Working well as expected.
Screenshot 2024-09-16 141230
Screenshot 2024-09-16 141302

**Review by Watchdog00 — APPROVED** [review]
I have completed the testing and got the expected results. Good job!

**Pull request closed without merging**
