### PR TITLE
Xiao F Make map add new user fields edit more easily

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-12-14 at 18 13 26

## Related PRS (if any):
See https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1549 for instructions on setting up geocoding API

## Main changes explained:
- Update file `src/components/TeamLocations/AddOrEditPopup.jsx` for setting up placeholder text correctly
- Create file `src/components/TeamLocations/CustomInput.jsx` for custom input component that can be focused when modal opens
## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as Owner user
5. go to dashboard->Report->Team Locations->Add person->Check if cursor starts at first name->Check if placeholder text works
6. go to dashboard->Report->Team Locations->Add person->Type in valid first name, last name, job title, and location->Click on 'Get location'->Click on 'Save to map'->Upon successful submission, the modal will refresh and the cursor will be placed on first name again

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/34078d92-e927-4b6d-b9d9-e7361eb93aed

### CODE REVIEW

**Comment by keyunhuangg** [comment]
I am not sure how to get the correct location, tried 3 locations shown below.
Screenshot 2023-12-15 at 2 43 52 PM
Screenshot 2023-12-15 at 2 43 38 PM
Screenshot 2023-12-15 at 2 43 14 PM

**Comment by tsunami776** [comment]
Hi @keyunhuangg, thanks for reviewing! Did you set up geocoding API? If not, see [https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1549](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1549) for instructions of using geocoding API.

**Review by pika-chu11 — APPROVED** [review]
Hi @tsunami776 , I have tested your PR and you did a great job!

Here is the test workflow and the code works as expected:

- Log in as Owner Account:
    - Under the dashboard -> Report -> Team Locations -> Add Person
        - The cursor did start at the firstname textfield.
        - All the placeholders in the textfield seems right to me.
        - I was able to add a person with their firstname, lastname, title, and location.
            - Missing one field won't let me clicked the "Save to Map" button. 
        - A popup will show other right upper corner after I clicked the "Save to map" button indicate that I am successfully added to the map.
    - Under the dashboard -> Report -> Team Locations -> Users list
       - I was able to see the users that I just saved from the previous step.
       - I can also delete them.
 
Please watch the video for the detail:

   

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/9ba4338a-1f16-4646-b871-c1ac7d8632a9

**Comment by mianmiantea2019** [comment]
Hi @tsunami776 , everything works as expected.

Log in as Owner Account:
Under the dashboard -> Report -> Team Locations -> Add Person
image

image

Under the dashboard -> Report -> Team Locations -> Users list. I was able to see the users that I just saved from the previous step and delete them.

image

image

**Review by bienzguoa — APPROVED** [review]
Good job! I set up the API and test step by step, it works perfect! Code is clear.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/4861c6f5-0853-43b7-aaa2-d5c53ac9bfea

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
