### PR TITLE
Ramya unit test: Userprofile/TeamWeeklySummaries

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit tests for src/components/UserProfile/TeamWeeklySummaries

## Main changes explained:
-  New file
      - **TeamWeeklySummaries.test.js** : unit test cases 
-  Existing file
      - **TeamWeeklySummaries**  : Added  test id to the objects for unit testing 
####  Test cases 
image

## How to test:
1. check into current branch
2. do npm test TeamWeeklySummaries.test.jsx
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Comment by Cavein254** [comment]
@ramyaram2092  ran test as stated in the pr and everything works as intended
Screenshot from 2024-01-12 15-00-16

**Review by bajajtushar094 — APPROVED** [review]
@ramyaram2092 I tested your PR and all the test cases passed as said. Thanks 
Screenshot 2024-01-12 at 21 45 48

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Review by ChengyanOo — APPROVED** [review]
Hi @ramyaram2092,

I wanted to reach out regarding the unit tests you've written. I've run through all of them, and I'm pleased to report that they all pass successfully! It's particularly impressive how thoroughly you've approached this task, considering not just boundary conditions but also ensuring comprehensive testing of every function within the component. This level of detail in testing is excellent and greatly appreciated. Keep up the fantastic work!

Screenshot 2024-01-12 at 15 20 20

**Review by bienzguoa — APPROVED** [review]
All test cases passed! It's thoroughly and correctly rendered. Thanks!
Screenshot 2024-01-12 at 8 41 05 PM

**Comment by belagaam** [comment]
All test cases passed successfully

Ramya Unit test - Team weekly Summary

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
