### PR TITLE
vitor fix delete badge when count is zero

### PR DESCRIPTION
**Pull request by vitorsaa2k**
fixes bug 11 from BADGES COMPONENT - (PRIORITY LOW) Jae: Select Featured changing count to 0 should delete a badge.

## Description
The Badges should disappear when the ‘count’ is set to zero, but they don’t.

## Main changes
1. Now, when the count is set to zero and the save button is clicked, the badges which the count is zero will be removed from the user's list of badges.

## How to test
1 - check into current branch
2 - do npm install and `npm run start:local` to run this PR locally
3 - log as admin user
4 - Go to dashboard → User Profile → Featured Badges → Assign Badges → Assign any quantity of  Badges to the user, then go to ‘Selected Featured’ and change the count to zero → Save.
5 - The badges which the count was zero when you saved should be removed from the user's profile.

## Example of how to test

https://user-images.githubusercontent.com/17365161/225116246-12dd09a3-1dbe-4eb2-9cb4-00518306aa9d.mp4

### CODE REVIEW

**Comment by johny4437** [comment]
@vitorsaa2k  I tested this PR, it is working as intended, good job.

https://user-images.githubusercontent.com/39320057/225170352-470c482b-f17e-4b07-8fda-409a001e8c88.mp4

**Review by johny4437 — APPROVED** [review]

**Comment by nicollext** [comment]
Hey @vitorsaa2k I tested and it works as intended when I use the arrows at the input number. 

https://user-images.githubusercontent.com/101591708/225193137-a3544b7e-d8a8-4d98-8a01-cc98629a0489.MP4

But when I manually type 0 the Badges are not removed.


https://user-images.githubusercontent.com/101591708/225193325-f6b79e3e-53b9-4d61-898c-2e95c7ba065e.MP4

**Comment by AnishPandita** [comment]
Hi, I tested your PR its working as intended when i use dropdown to make badge count 0. But if I manually enter amount 0 it doesn't work.

https://user-images.githubusercontent.com/111321945/225202908-f947d094-b8db-458f-abfe-133a7e0282fb.mov

**Review by NataliaCavicchioli — COMMENTED** [review]
Hey Vitor, I tested your PR and it is deleting with the arrows! Good job.

The only thing is that if I manually change the count to 0, it doesn't delete the badge. It just replaces the number with 0.

Even if the number was manually set to 0, to delete, I have to click on the drop arrow, then it works and deletes the badge. Otherwise, the badge remains there.


https://user-images.githubusercontent.com/103126226/225335826-18774341-bf7b-4971-a448-ee9af137929d.mp4

**Comment by vitorsaa2k** [comment]
Thanks for the reviews you all! @johny4437, @nicollext, @AnishPandita, @NataliaCavicchioli, please review again and tell me if you are facing the same problems.

**Review by nicollext — DISMISSED** [review]
Great Job! It is working perfectly.


https://user-images.githubusercontent.com/101591708/225430701-08439625-ec9d-4e33-9b31-55cd97ca8d48.MP4

**Comment by AriaYu927** [comment]
Hi @vitorsaa2k , I tested your PR and it worked well! Good job, thank you!

https://user-images.githubusercontent.com/94303659/225469213-fe7f93a1-c45e-4004-9116-d9b809d1c015.mp4

**Review by NataliaCavicchioli — APPROVED** [review]
Great job Vitor! Now it is working as expected.

**Review by PrabhjotSembhi — COMMENTED** [review]
The page reloads when we remove a badge. also when you add a badge. 

I think we need to fix the implementation. 
The potential easy fix will be: adding `e.preventDefault()` in relevant handler functions.

**Comment by PrabhjotSembhi** [comment]
PR 712 1
PR 712 After

The badge is removed once its count is 0.  The problem is page reloads when we click save.

**Comment by PrabhjotSembhi** [comment]
> > The page reloads when we remove a badge. also when you add a badge.
> > I think we need to fix the implementation. The potential easy fix will be: adding `e.preventDefault()` in relevant handler functions.
> 
> Hello @PrabhjotSembhi, thank you for your review! Both problems you faced are not in the scope of this PR. Jae already reported the issue about the page reloading in the Bugs Doc and I will take care of it on another PR.

ok.

**Comment by one-community** [comment]
I don't remember adding these new bugs and didn't see them on the Bugs Doc. Please add them Vitor along with Prabhjot's suggested easy fix and comment on them so I can review. Or just add the suggested fix and comment on them if they are already there.

**Review by kangjay88 — APPROVED** [review]
Hi @vitorsaa2k, I have tested this PR and it works as intended. Nice implementation!

https://user-images.githubusercontent.com/108297706/226103575-b57edf8f-a904-446e-809d-88cc5c651143.mp4

**Comment by NyahJ** [comment]
Hi @vitorsaa2k,

I have followed your test suggestion, they all worked as intended. Thanks for your hard work!

截屏2023-03-18 下午12 01 40
截屏2023-03-18 下午12 01 55
截屏2023-03-18 下午12 02 06

**Comment by mpavithr** [comment]
Hi, looks like it works as intended for me!
I assigned some badges and afterwards once I set the count to 0, they are removed.
pr712_1
pr712_2
pr712_3
pr712_4

**Comment by Jorge-Nerd** [comment]
Hi @vitorsaa2k  I tested the PR and compared to previous 
image

It work fine for me
image

**Comment by ayush0904** [comment]
I have tested this PR and it is working perfectly. Thank you for the work.
Screen Shot 2023-03-18 at 2 41 50 PM
Screen Shot 2023-03-18 at 2 42 00 PM
Screen Shot 2023-03-18 at 2 42 07 PM

**Comment by one-community** [comment]
Reminder everyone to please approve PRs if they are working and the code looks good, don't just say it is working. Moving this one to final review.

**Review by AriaYu927 — APPROVED** [review]

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
