### PR TITLE
Eduardo_batch_email_generator

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
image

## Main changes explained:
- Created mail-bulk icon that triggers a function that divides the list of emails into batches of 90 addresses and then opens the user's default email client for each batch with a delay of 2 seconds
- Created Tooltip

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to dashboard→ Reports→ Weekly Summaries Reports→ Scroll to bottom→ Click on Mail Bulk Icon
5. verify if your email client open into batches of 90 addresses

## Screenshots or videos of changes:
image
image

[Video Preview](https://www.loom.com/share/a31638d262734656ac51e325594dd3cc?sid=701ed569-bac3-4dff-9720-8813583b983f)

### CODE REVIEW

**Review by Sssky-18 — DISMISSED** [review]
Hi @eduhorta, I tested your added code and the email button shows well. Both the icon and the text were displayed correctly. 
Besides, when I clicked this button, it will lead my laptop to send emails to several addresses, which was the same as the function shown in your video preview, so I think this feature works as expected.  

PR#1293_1
PR#1293_2

**Review by DavidC0126 — DISMISSED** [review]
Hi @eduhorta I tested your PR and it works as intended. After I clicked the email button, the window automatically popped up.

email_90

**Review by Chris33871 — COMMENTED** [review]
Hi @eduhorta , 

I reviewed the code and functionality and it works fine on my end 👍 . 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68507104/6a7c8d33-3eb7-48e2-8ff5-2594ac31da46

It took me a long time to scroll all the way down, I think a button to scroll down might be welcomed. What do you think?

**Comment by eduhorta** [comment]
Hey @Chris33871,
Thank you for your feedback!

> Just some quick thoughts: In the video you can notice some input delays, that is probably due to my machine. However, once the button is clicked the pop-up stays there even after switching the page. Is that intended?

There is a delay of 2 seconds to open each batch of email so your machine is behaving the expected way.

About the new tab pop-up.
I tried to configure the email client to open without triggering the pop-up or opening a new tab. 
However, when Chrome opens a significant number of emails, a security measure is activated, demanding a user gesture for validation. 
So if you trigger it in a new tab it doesn't required that.

> It took me a long time to scroll all the way down, I think a button to scroll down might be welcomed. What do you think?

@one-community 
What do you think about it?

**Comment by Chris33871** [comment]
> Hey @Chris33871, Thank you for your feedback!
> 
> > Just some quick thoughts: In the video you can notice some input delays, that is probably due to my machine. However, once the button is clicked the pop-up stays there even after switching the page. Is that intended?
> 
> There is a delay of 2 seconds to open each batch of email so your machine is behaving the expected way.
> 
> About the new tab pop-up. I tried to configure the email client to open without triggering the pop-up or opening a new tab. However, when Chrome opens a significant number of emails, a security measure is activated, demanding a user gesture for validation. So if you trigger it in a new tab it doesn't required that.
> 
That wasn't the popup I was talking about but thank you for mentioning that, I didn't know that that was how it worked. 
I was referring to the popup that shows over the email button when you hover. In the video, after I click it you can see that it says active even after I change the page. 

> > It took me a long time to scroll all the way down, I think a button to scroll down might be welcomed. What do you think?
> 
> @one-community What do you think about it?

**Comment by eduhorta** [comment]
> That wasn't the popup I was talking about but thank you for mentioning that, I didn't know that that was how it worked. I was referring to the popup that shows over the email button when you hover. In the video, after I click it you can see that it says active even after I change the page.

Are you talking about the Tooltip?
image

If you just click anywhere outside of the mail-bulk icon after triggering the function it will be gone.

**Review by Haoj1 — DISMISSED** [review]
@eduhorta All emails are correctly added into the pop-up email sender.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/83acb683-ab0c-4213-b489-4e3f3e1c2338

**Comment by Chris33871** [comment]
> > That wasn't the popup I was talking about but thank you for mentioning that, I didn't know that that was how it worked. I was referring to the popup that shows over the email button when you hover. In the video, after I click it you can see that it says active even after I change the page.
> 
> Are you talking about the Tooltip? image
> 
> If you just click anywhere outside of the mail-bulk icon after triggering the function it will be gone.

Yep, I was just wondering if that was on purpose or if it was supposed to only appear on hover

**Review by tsunami776 — DISMISSED** [review]
Tested with an admin account, clicking on the mail-bulk button will popup email clients into batches each with less than 100 recipients. Great work!

**Review by robertoooc — DISMISSED** [review]
Hi @eduhorta, I tested your new implementation. The email icon does work well and it also did distribute the emails in chunks of 90 at a time. Nicely done. 
Screenshot 2023-09-14 at 11 12 07 AM

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Hi @eduhorta, I'm having some issues with this new functionality. When a click on the email icon the behavior doesn't seem to be predictable. I always get the first batch to show up in my email client and it's using my Mail application on MacOS. But it doesn't seem to be opening an instance of my email client for each batch even after waiting 2 seconds. I might just be using this feature wrong but it doesn't seem to be performing the way I would expect it to. If I click the email button once, only one draft of the first batch of email addresses opens up. See video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/05ba6b5f-7376-4380-a031-a67e87801fb9

**Comment by eduhorta** [comment]
> Hi @eduhorta, I'm having some issues with this new functionality. When a click on the email icon the behavior doesn't seem to be predictable. I always get the first batch to show up in my email client and it's using my Mail application on MacOS. But it doesn't seem to be opening an instance of my email client for each batch even after waiting 2 seconds. I might just be using this feature wrong but it doesn't seem to be performing the way I would expect it to. If I click the email button once, only one draft of the first batch of email addresses opens up. See video below.
> 
>  Screen.Recording.2023-09-14.at.2.22.24.PM.mov

Hey @GaryB93! 
Thank you for the feedback.

On my previous comment I've explained my approach to implement the e-mail batch feature:
> About the new tab pop-up.
I tried to configure the email client to open without triggering the pop-up or opening a new tab.
However, when Chrome opens a significant number of emails, a security measure is activated, demanding a user gesture for validation.
So if you trigger it in a new tab it doesn't required that.

I did see on your video the Pop-ups blocked icon:
image

Would you mind allowing pop-ups from the HGN app and testing again?

**Review by dah00 — DISMISSED** [review]
Hey, your PR works fine, the email client opens into batches of 90 as expected. It took a few seconds before the email client opened up, but it is probably my machine. Great work


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/53328aeb-d80f-4b1f-8ff4-567cd1dc231a

**Review by Jiyuanxia — DISMISSED** [review]
Hi @eduhorta , I have reviewed your pull request and tested it. It works as intended. Well done.

Screenshot 2023-09-14 230314

**Review by GaryB93 — DISMISSED** [review]
Thank you for the assistance and clarification @eduhorta. Allowing popups fixed the issue. Clicking the email button opened up several instances of my email client with different batches of 90 email addresses respectively. I did find the 4-5 extra tabs that opened up in my browser an unwanted side effect but it sounds like that was just the way it had to be done from your description. Unless there's something we can do to prevent the several new tabs from opening.

**Review by iTvX — CHANGES_REQUESTED** [review]
It's not working on my end: MacOS system, test with Arc and Chrome browser.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/639e511c-3eaf-4d4e-b688-bbfb0c96dc5e

**Review by zuhang2000 — COMMENTED** [review]
Hi Eduardo! I tested this PR following your instructions. However I do encounter problem when clicking the button. The new browser window just keeps popping up. And the email client is not popping up. I'm not sure why that's happening. Here you may see the details in the following recording.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/ed8b45a1-76be-47f7-b974-06f14e3dafcc

**Review by gabi-lima — DISMISSED** [review]
Working as expected. Great job!
image

**Review by TuanDinh140194 — APPROVED** [review]
Hi ! I have test your pull review. After I clicked on the email icon, it pop-up the email as expected. However, after 2 seconds it doesn't pop-up another automatically. Is that intended?
Thank you
Screenshot 2023-09-16 175648
Screenshot 2023-09-16 175619

**Comment by eduhorta** [comment]
> It's not working on my end: MacOS system, test with Arc and Chrome browser.
Hey @iTvX! Thank you for the feedback!

I believe this feature will be mostly used by Jae, so I asked him which email client he does use and he is using the default email app on MacOS.
Would you mind re-testing on it?

Also, can you check if there is a pop up block?
image



> Hi Eduardo! I tested this PR following your instructions. However I do encounter problem when clicking the button. The new browser window just keeps popping up. And the email client is not popping up. I'm not sure why that's happening. Here you may see the details in the following recording.

Hey @zuhang2000!! Thank you for the feedback! 👍 

Can you check if you are using the default email app for MacOS?
image

Also, can you check if there any blocked pop-ups for the HGN App?

**Comment by one-community** [comment]
Excellent, thank you everyone! Moving to final review!

**Review by cvtqx — APPROVED** [review]
I've tested this PR and all works as described. The code is clear and concise. Excellent job! 

Tooltip:
Screen Shot 2023-09-19 at 11 10 15 AM

Email client opened with email chunks of 90 each:
Screen Shot 2023-09-19 at 11 08 14 AM

**Pull request merged**
