### PR TITLE
Vitor fix save changes warning disappear

### PR DESCRIPTION
**Pull request by vitorsaa2k**
fixes bug (PRIORITY LOW) - 12 from USER PROFILE COMPONENT

## Description
When making changes to a user's profile, a reminder alert to click the save button is displayed. But even if the changes are undone before saving, the reminder alert remains on screen
 a. The reminder alert should disappear in case all changes on the user's profile are undone.

## Mainly changes
1. Now, the warning disappear when the user mannualy go back on the changes.
2. there was an optmization when changing the `updatedTasks` state.

## How to test
1 - check into current branch
2 - do npm install and `npm run start:local` to run this PR locally
3 - log as admin user
4 - Go to dashboard → User Profile → Change and go back to original on all possible changable inputs.
5 - Make sure to go through all tabs, Basic Information, Volunteering Times, Teams, Projects.

## Example of how to test

https://user-images.githubusercontent.com/17365161/224114612-b72b7d77-f00f-4db7-936a-0aa5886e9a24.mp4

### CODE REVIEW

**Review by Lucas-E — COMMENTED** [review]
Hey Vitor, just reviewed your PR and everything works very well, great job!

https://user-images.githubusercontent.com/92558269/223905593-faeb4000-1d53-46ef-a8ef-b8e9a545ef1c.mp4

**Comment by crystalsong2021** [comment]
@vitorsaa2k , I testes the functionality and it works as intended. Nicely done.
https://user-images.githubusercontent.com/18197013/223949110-cd8f4525-4297-417d-92ac-7fdb3c484909.mov

**Comment by NyahJ** [comment]
Hi @vitorsaa2k,

Great job! I went through all tabs: Basic Information, Volunteering Times, Teams, Projects, the functionality all worked perfectly. 
Just one concern, do we need to take care of preventing the negative input shown as below? Thanks!

截屏2023-03-09 下午8 12 00

**Comment by vitorsaa2k** [comment]
> Hi @vitorsaa2k,
> 
> Great job! I went through all tabs: Basic Information, Volunteering Times, Teams, Projects, the functionality all worked perfectly. Just one concern, do we need to take care of preventing the negative input shown as below? Thanks!
> 
> 截屏2023-03-09 下午8 12 00

Yes the negative numbers should be prevented, but this issue isn't on the scope of this PR. Someone should raise a PR to solve this.

**Comment by mpavithr** [comment]
Hi went through the functionality and it seems to work well, other than weekly committed hours. Changed it from 0 and when I change it back to 0 the reminder is still there as seen below.
pr700_3

**Comment by NyahJ** [comment]
> > Hi @vitorsaa2k,
> > Great job! I went through all tabs: Basic Information, Volunteering Times, Teams, Projects, the functionality all worked perfectly. Just one concern, do we need to take care of preventing the negative input shown as below? Thanks!
> 
> @NyahJ Yes the negative numbers should be prevented, but this issue isn't on the scope of this PR. Someone should raise a PR to solve this.

Sounds great! Then all good from my side, thanks!

**Review by kangjay88 — APPROVED** [review]
Hi @vitorsaa2k, I have tested this PR and also found that everything works besides the weekly committed hours. I looked at the code, and it seems that 'committed' is not spelled consistently (either missing a 't' or 'm') - Not sure if this is what is causing the error, but probably a separate PR can be raised to make the spelling consistent for easier edits in the future. I think PR#704 has let it remain as 'weeklycomittedhours'. Overall awesome work! It would be awesome to see if someone could let the warning show when screen is in mobile use in the future.
PR#700 spelling

**Comment by vitorsaa2k** [comment]
> Hi went through the functionality and it seems to work well, other than weekly committed hours. Changed it from 0 and when I change it back to 0 the reminder is still there as seen below.

hi @mpavithr. Could you record a video so I can understand better what is happening? Because when i tested it worked normally.

https://user-images.githubusercontent.com/17365161/224761130-1e14f434-9b09-401b-8360-8b14f0d0ea1c.mp4

**Comment by nicollext** [comment]
> > Hi went through the functionality and it seems to work well, other than weekly committed hours. Changed it from 0 and when I change it back to 0 the reminder is still there as seen below.
> 
> hi @mpavithr. Could you record a video so I can understand better what is happening? Because when i tested it worked normally.

Hey @vitorsaa2k I faced the same problem, you can see at the video of the first comment that I added

**Comment by vitorsaa2k** [comment]
Thanks for the reviews you all! @nicollext, @mpavithr could you please test again? Tell me if you are still facing the same problems as before.

**Comment by vitorsaa2k** [comment]
> Hi @vitorsaa2k, I have tested this PR and also found that everything works besides the weekly committed hours. I looked at the code, and it seems that 'committed' is not spelled consistently (either missing a 't' or 'm') - Not sure if this is what is causing the error, but probably a separate PR can be raised to make the spelling consistent for easier edits in the future. I think PR#704 has let it remain as 'weeklycomittedhours'. Overall awesome work! It would be awesome to see if someone could let the warning show when screen is in mobile use in the future.

Hi @kangjay88, yes, I noticed this issue when editing this file, but couldn't do much about it. This misspelling was made by some another developer some time ago. I changed it to the correct spelled one now.

**Comment by nicollext** [comment]
> 

Hey @vitorsaa2k I just tested and still having the same problem.

https://user-images.githubusercontent.com/101591708/225426764-fce23ce7-fcc0-433f-a2a4-c40f35ef847a.MP4

**Comment by AriaYu927** [comment]
Hi @vitorsaa2k , I reviewed PR and tested through all tabs. Everything works well, thank you!
PR#700-change
PR#700-undone

**Review by rauleffting — APPROVED** [review]
Hi @vitorsaa2k! Your PR is working as expected. 

https://user-images.githubusercontent.com/29555732/226074550-89da4d09-7083-4e96-af30-f7982cc755f0.mp4


I saw that you also improved the code by removing unnecessary lines, debug outputs, and variables. Great job!

Approved!

**Comment by one-community** [comment]
Works great and great catch on this bug/function. I wouldn't have even thought to fix this but it is way better now.

**Pull request merged**
