### PR TITLE
Nikhil - fixed new user popup issue

### PR DESCRIPTION
**Pull request by nikhilgiri0226**
# Description

The process of adding a new user and sending a setup email was delayed due to the email-sending operation taking significant time on the backend, resulting in the frontend response hanging indefinitely. The updated implementation now displays a success message as a toast notification at the top-right corner, consistent with other success messages in the project. Additionally, the "hours" field will retain its value, while the email field will clear upon receiving a success response. The changes involved adding a toast notification and removing the setAlert function in src\components\UserManagement\setupNewUserPopup.jsx.

Fixes # (bug list priority high)

## Related PRS (if any):
This frontend PR is related to the #[1157](https://github.com/OneCommunityGlobal/HGNRest/pull/1157) backend PR.
…

## Main changes explained:
Made some changes in file src\components\UserManagement\setupNewUserPopup.jsx including showing toast success message and closing popup once we have the success response from the BE.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ user management → send setup link → add a new email and press send button.
6. verify the popup is closed with a success message.
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

Issue

https://github.com/user-attachments/assets/7fe7708d-20f2-460e-9137-48fba9da8d60

After fix

https://github.com/user-attachments/assets/a64c198f-f44e-420c-bc51-dae66c1f22ca

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.




Thanks

**Review by anirudhsk2107 — DISMISSED** [review]
The changes worked as expected 
Screen Shot 2024-11-20 at 3 35 47 PM
Screen Shot 2024-11-20 at 3 35 53 PM
Screen Shot 2024-11-20 at 3 37 32 PM

**Review by SS-Reddys — APPROVED** [review]
Changes are working as expected both in light and dark mode with popup is closed with success message.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
