### PR TITLE
Shuhua - Inventory types page

### PR DESCRIPTION
**Pull request by Shuhua-L**
# Description
Implement 5.1.1 List view of ALL inventory types

## Related PRS (if any):
N/A

## Main changes explained:
- Implemented a timestamp to reflect the current time.
- Implemented accordions and tables to render all inventory types by category
- Implemented a table for Units of Measurements

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to [http://localhost:3000/bmdashboard/inventorytypes](http://localhost:3000/bmdashboard/inventorytypes)
6. Verify the following features:
    1. The timestamp component displays the current time when the page is loaded and can be edited
    2. Blue bars are expandable/collapsible, and the arrows change accordingly
    3. Check the data stored in the `buildingInventoryTypes` collection to make sure all types are listed by category

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/e62878ed-4441-4299-9ad5-cf08d5608eee

## Note:
- The page differs from the original [wireframe](https://www.figma.com/file/kpwXZP2pLtOJ1Fn2u7Sivn/HGN-PII?type=design&node-id=450-6151&mode=design). Changes were made with Jae’s approval to adapt the current data scheme and improve user experience
- The add, edit, and delete features are not implemented yet
- The same for the “Back to the previous page” button
- These errors are unrelated
potential errors

### CODE REVIEW

**Review by X1aoZhang99 — CHANGES_REQUESTED** [review]
Hi Shuhua,

Just finished testing your PR with a volunteer user, and I've noticed an issue that seems counterintuitive. When I first hit the page, it looks like the types in all categories (except for 'Units of Measurement') aren’t loading up until I refresh or change the timestamp. Check out the video I've attached for a clearer picture of what's happening.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/f6ec232f-a3f4-44fe-8533-2dbfaa7e0970

**Comment by Shuhua-L** [comment]
> Hi Shuhua,
> 
> Just finished testing your PR with a volunteer user, and I've noticed an issue that seems counterintuitive. When I first hit the page, it looks like the types in all categories (except for 'Units of Measurement') aren’t loading up until I refresh or change the timestamp. Check out the video I've attached for a clearer picture of what's happening.
> 
>  Screen.Recording.2024-01-23.at.22.14.29.mov

@X1aoZhang99 Thanks for catching that! I've made a commit to fix it, could you take another look?

**Review by Nahiyan-16 — DISMISSED** [review]
## Hey Shuhua
I saw that Xiao made a comment about items not loading up initially and I saw the same thing before your latest commit. After pulling your latest commit though, it seems that you have fixed the problem as it loads up on page initialization. I tested it using both volunteer and owner accounts and it works just fine. Great job!
Screenshot 2024-01-24 133809

**Review by Renanluizssx — DISMISSED** [review]
Hi @Shuhua-L, i tested your application and it´s very correct, look my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/f5689bef-9484-4b7f-a545-da3f16ebed05

**Review by 666saofeng — APPROVED** [review]
Hi, I tested with both admin and volunteer account. It worked as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/ec6f3083-bcdf-4c47-b0c9-134f8ae401c8

**Review by peterson337 — DISMISSED** [review]
HI Shuhua, tested your application, and everything worked as expected. Good job!

one comunnity

**Review by Pandani07 — DISMISSED** [review]
Hi, I followed the steps and tested this frontend PR with the latest development backend. I could see the BM Dashboard (I had to login) and then I could see the different inventory types. The blue components are collapsible and I also could not edit / delete any inventory type.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/5fdf610f-87a4-407d-b5d4-38b9b76ca511

**Review by TapanPathak — APPROVED** [review]
Hi, I tested the PR with both admin and volunteer account. Everything works as expected! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/74f7a26d-2e60-4696-93a4-75b1bdbcae8d

**Review by swathyjayaseelan — APPROVED** [review]
Works as expected. The Add, Delete and Back functions are not yet implemented. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/c96277ea-bead-4697-8410-b59c858d32c3

**Review by TareqMia — DISMISSED** [review]
Everything looks good to me and everything worked as expected. Great job 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/65feed55-03c7-4d22-93bd-c5fb3b79eae1

**Pull request merged**
