### PR TITLE
Ajay - fix date mismatch on reports and user management

### PR DESCRIPTION
**Pull request by AJAYINAVOLU**
# Description
This pull request addresses the one-day difference in start dates between the **user management** page and the **reports** page, particularly affecting accounts with no time logged. We ensure consistent date displays across both pages by using moment.utc() for date formatting and adding explanatory comments about UTC. This fix maintains the use of moment.js to prevent disruptions in other components that rely on it. The added comments clarify the purpose of using UTC, aiding future maintenance and preventing similar issues. To verify the fix worked, I used Python scripts to extract user data from the reports page and compared it with the JSON data.

Fixes # (PRIORITY LOW) Howie: Some accounts have an off by one start date inaccuracy for some reason

## Related PRS (if any):
This frontend PR is related to the [development](https://github.com/OneCommunityGlobal/HGNRest) branch of the backend repository.
…

## Main changes explained:
- Updated **PeopleTable.jsx** to use moment.utc() for date formatting
…

## How to test:
1. Check into the current frontend branch and the development backend branch.
2. Do npm install and npm run start:local to run this PR locally.
3. Clear site data/cache.
4. Log in as an owner-user.
5. Go to Dashboard → Reports → Reports → People.
6. image
7. Open Dashboard → Other Links → User Management [in a new tab].
8. image
9. Verify the start date matches on both the pages [reports page and the user management page] for the users.

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/51d54128-f9e4-4497-a019-bbd124caa88c

**Review by shivansh-nathani — APPROVED** [review]
I have tested the code and changes look fine.
Screenshot 2024-10-17 at 8 22 59 PM
675b-492d-a052-01951a4e2faf">

**Review by lng2020 — APPROVED** [review]

**Review by manikittu810 — APPROVED** [review]
Hello @AJAYINAVOLU 
Everything is working as mentioned.

Screenshot 2024-10-18 at 7 24 03 AM

Screenshot 2024-10-18 at 7 24 11 AM


Thank you.

**Review by NK3101 — APPROVED** [review]
Tested the PR, the start date matches on both the pages.

**Review by Jingyii800 — APPROVED** [review]
I have tested this feature, it works well. Now the people  in reports and the user management display same start date.
image

**Review by javid679 — APPROVED** [review]
Hey Ajay, I have reviewed this PR and the dates in reports page and usermanagement page are matching.

Report page

Screenshot (52)


usermanagement page
Screenshot (53)

**Comment by geetamatkar** [comment]
Hi @AJAYINAVOLU ,
I have tested this PR and start date is same on both the reports page and the user management page.

Screenshot 2024-10-19 at 3 10 18 PM
Screenshot 2024-10-19 at 3 10 28 PM

**Review by vijay10pk — APPROVED** [review]
Changes are working as expected.
Screenshot 2024-10-19 at 8 22 28 PM
Screenshot 2024-10-19 at 8 22 21 PM

**Comment by sheetalmangate** [comment]
I just having  a question :  can we use formatDateLocal() function instead of moment().format()? 
If there are any changes in date display format in the future we won't need to change it in the each file.

**Review by Rupa2400 — APPROVED** [review]
This pull request effectively addresses the issue of inconsistent date displays between the user management page and the reports page, particularly for accounts with no time logged. The use of moment.utc() for date formatting enhances the reliability of date displays across the application.

user_management
reports_people

**Review by nikhilgiri0226 — APPROVED** [review]
I have tested the PR. The start date is as expected on both people table and user management table.

People Table

Screenshot_2798_people

User Management Table

Screenshot_2798_user

**Comment by hqzhu0913** [comment]
Hi,
I tested the PR. Both user management and people table's start date are as expected.
UserManagement:
Screenshot 2024-10-21 at 1 56 56 PM
Screenshot 2024-10-21 at 1 57 14 PM
People table work as follows:
Screenshot 2024-10-21 at 1 58 14 PM

**Review by hqzhu0913 — APPROVED** [review]
Screenshot 2024-10-21 at 1 58 14 PM
Screenshot 2024-10-21 at 1 57 14 PM
Screenshot 2024-10-21 at 1 56 56 PM
I tested the PR. Both user management and people table's start date are as expected.
UserManagement:

**Review by Rui-Liu-github — COMMENTED** [review]
Hi, @AJAYINAVOLU , I reviewed PR #2798. the start date is as expected on both the people table and the user management table.

review#2798_1
review#2798_2

**Review by Rui-Liu-github — APPROVED** [review]

**Review by CodewithKoushica — APPROVED** [review]
The changes work well, and the flow behaves as expected.

### Suggestion:
Moment.js is a large library and is now in maintenance mode. I suggest considering lighter alternatives like the native `Intl.DateTimeFormat` or `date-fns`. For example, you can use `date-fns` like this:

```
const formattedDate = format(parseISO(person.startDate), 'MM-dd-yy');
```

This can help reduce bundle size and improve performance.

Screenshot 2024-10-22 at 8 23 35 AM
Screenshot 2024-10-22 at 8 23 04 AM

**Review by samarth9201 — APPROVED** [review]
Verified the changes, LGTM!
image

**Review by slidracoon72 — APPROVED** [review]
#2798 
@AJAYINAVOLU 
I have tested this feature, and it works as expected. The start dates for people in both reports and user management now display consistently.

Screenshot 2024-10-23 at 12 47 09 PM
Screenshot 2024-10-23 at 12 47 26 PM

**Review by bhavya17prakash — APPROVED** [review]
Working as expected. Verified same value on both pages.
PR 2798(2)
PR 2798

**Comment by VMD281** [comment]
Hi, I reviewed this issue and checked the dates on both reports and user management page. Everything is working fine!
PR#2798_1
PR#2798_2

**Review by varun-elango — APPROVED** [review]
The code changes look good and the change is working as expected. The start date matches in both reports page and the user management page. 
PR2798_1
PR2798_2

**Comment by mianmiantea2019** [comment]
The code changes look good and the change is working as expected.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
