### PR TITLE
Palak - AssignTableRow Unit Test Cases

### PR DESCRIPTION
**Pull request by palakgosalia**
# Description
Unit test for `AssignTableRow.jsx`

## Main changes explained:
- Added a new file called AssignTableRow.test.js
- Added 8 test cases: 
Renders component with checkbox
Handles checkbox change correctly when initially checked
Handles checkbox change correctly when initially unchecked
Renders without crashing with invalid badge ID in selected badges
Renders without crashing when selectedBadges prop is missing
Renders without crashing with incomplete or invalid badge data
Renders without crashing with an invalid index
Renders without crashing with missing badge image URL

## How to test:
1. check into current branch
2. do `npm test src/__tests__/Badge/AssignTableRow.test.js`
3. check if all the test cases pass

## Screenshots or videos of changes:

image

### CODE REVIEW

**Review by sahilpatel18 — COMMENTED** [review]
All test cases passed successfully. Great work! 
Screenshot 2023-12-10 at 2 38 34 AM

**Review by Alforoan — DISMISSED** [review]
All tests passed. Nice!

image

**Review by this-journey — DISMISSED** [review]
Hello!  I reviewed your PR and all 9 tests passed.  Great job!

Screenshot 2023-12-14 at 12 48 47 PM (2)

**Comment by Lin1404** [comment]
Hi @palakgosalia ! I reviewed your PR and all 9 tests passed. Good job!

Screenshot 2023-12-16 at 4 59 17 PM

**Review by Lin1404 — DISMISSED** [review]

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-18 at 10 27 45 PM
All tests have passed successfully. Excellent job!

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your Pr and all the test cases passed!

Week 18 - PR5

**Review by bienzguoa — DISMISSED** [review]
Good job! The tests are quite thorough, covering a wide range of scenarios. All test cases passed.
Screenshot 2024-01-06 at 5 04 59 PM

**Review by ChengyanOo — DISMISSED** [review]
Hi @palakgosalia,

I've reviewed your latest submission and am pleased to inform you that all the tests have passed successfully. However, I encountered a console error during the process. For your convenience, I've attached a log file detailing this issue. Additionally, I've included a screenshot demonstrating the successful test outcomes for your reference.

[Server.log](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/files/13892049/Server.log)

Screenshot 2024-01-10 at 14 20 07

**Review by bajajtushar094 — DISMISSED** [review]
All test cases passed. Thanks 
Screenshot 2024-01-11 at 23 31 27

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Please fix the test file location per the standard outline in the following link <a>https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit#heading=h.m9b033294wic</a>

I'd like to go ahead and move this forward to Final review once that issue is taken care of since you have a lot of approvals on it. Great Job!! 😁

**Comment by palakgosalia** [comment]
I have fixed the file location. Thank you for all your feedback!

**Review by KurtisIvey — APPROVED** [review]
Looks good and functions well. File location has also been fixed too. 

Screenshot 2024-03-02 at 4 43 57 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
