### PR TITLE
Sucheta- Improve Add New Task modal format

### PR DESCRIPTION
**Pull request by sucheta90**
# Description
(PRIORITY HIGH) Jae: Improve “Add New Task” modal format
- Make Task Name box bigger
- Fix Status Section so everything fits on 2 lines
- Fix hours input width so up to a 4-digit number will show
- [Video clarification](https://www.loom.com/share/80b70f2750ad4f00abee0d6fdeeca4f9?sid=8f6037a8-169b-4b97-bf79-39051f93fea3)

## Related PRS (if any):
None

## Main changes explained:
- Changed html tags in `AddTaskModal.jsx` , from `<tr>` to `<div>` and `<td>` to `<span>` for the form labels and input fields

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Projects → WBS -> Tasks -> Add Task
6. The input fields now take more space than the labels.

## Screenshots or videos of changes:
Before the change: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/2482fa39-6d7c-4078-ab7f-b2fab529aa2c

After the change: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/91fc9ee0-bc4a-40bc-8eeb-cc519e70eaef

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
The new input field looks good! Nice work!

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected. Good work.
Screenshot 2024-04-20 at 5 41 11 AM

**Review by lacnoskillz — APPROVED** [review]
Hello @sucheta90 
I have pulled your code and tested it
And it functions as expected.
The Add New Task Modal format looks so much better! And all functionality remains the same. Nice work!
See below images

# Before:
add task before
add task mobile before


# AFTER:
add task with changes
image
Also your changes fixed this small bug on mobile view
small bug


## NOTE
I did notice a small bug where the error/warning message kind of pushes the text box in front of the title ( See below image )
image

**Comment by sucheta90** [comment]
> Hello @sucheta90 I have pulled your code and tested it And it functions as expected. The Add New Task Modal format looks so much better! And all functionality remains the same. Nice work! See below images
> 
> # Before:
> add task before add task mobile before
> 
> # AFTER:
> add task with changes image Also your changes fixed this small bug on mobile view small bug
> 
> ## NOTE
> I did notice a small bug where the error/warning message kind of pushes the text box in front of the title ( See below image ) image

Thank you so much for reviewing this PR. I see what you pointed out about the warning messages. I will try to fix them.

**Comment by sucheta90** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2198

**Comment by sucheta90** [comment]
This PR consists of a bug that appears when the hours needed to complete the task are not filled correctly. Please refer to the picture
Screenshot 2024-04-26 at 1 36 24 PM
as pointed out in one of the PR reviews.

**Pull request closed without merging**
