### PR TITLE
Luis summary intro btn

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description
Added a copy button to the user's profile, which copies and generates the summary intro for managers, assistant managers and administrators.
Copies the text to the user's clipboard, and checks if the user's in the team have submitted their weekly summaries, and categorizes based on that and saves it to the clipboard.

## Main changes explained:
Added a new button to the user's profile which generates the string to the clipboard.
Also, utilized existing permissions, using hasPermission method. Since the user's I am targeting are Managers, Admins and Owners. They all have getProjectMembers permission, so I am using this permission to check if they can see the button.
 
Only Managers, Admins and Owners should be able to see the button. 
**Volunteers cannot see the button.**

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. log as admin/owner
4. go to dashboard→ View profile
5. Check if "Generate Summary Intro" appears
6. Click the button, and paste what appears.
7. Check if the user's who submitted a summary have and those who haven't are listed in the correct spot.
8. Make sure your user is a apart of a team, to view all the correct members who have and who haven't submitted a summary.
9. The current user is assigned the manager role since they are clicking the button.
10. Retest using a volunteer account and the button should not appear.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/3e2dee14-f4c0-45c1-a55a-cf7ed372a7fb

## Note:
If you have a suggestion to improve the code that would be great. 
Thanks. 
The following warnings appear plaese disregard them 
Screenshot 2023-10-18 at 8 40 42 PM

### CODE REVIEW

**Review by DavidC0126 — APPROVED** [review]
Hi @luisarevalo21 I tested your PR and it works as described.

Volunteer:
vol

Admin:
copied
copiedMessage
manager_btn

**Comment by olenadanykh** [comment]
hi @luisarevalo21 . I have tested your PR and all works as expected. Great work
PR1428
!
Pr1428-2

**Review by shubhankarval — DISMISSED** [review]
Hey @luisarevalo21, I checked the functionality of `Generate Summary Intro` button on Admin and Volunteer accounts, and it works great!
Admin:
PR 1428
PR 1428 (1)
</br>
Volunteer:
PR 1428 (2)

**Review by lacnoskillz — COMMENTED** [review]
Hello @luisarevalo21 
I pulled your changes and tested them locally

I have ran into an issue with displaying my Admin accounts profile when clicking 'View Profile' I found that it doesn't load their profile if they are not on a team/project. But works when I created a new Admin thats on a team/project.

[Untitled_ Oct 19, 2023 12_58 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/67e52743-05cb-445f-8d09-f88da962aefb)

confirm it does work on Owner Account

[Untitled_ Oct 19, 2023 1_00 PM (1).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/448b5fc8-aaa7-48ce-a509-518aa28a5622)

I also confirmed it does now show when viewing as a volunteer

image

Nice work! Happy coding!

**Review by tsunami776 — COMMENTED** [review]
Hi @luisarevalo21, I tested your PR locally with owner, admin and volunteer accounts. The 'Generate Summary Intro' button works as described. It will copy the summary intro according to the user's name. Great work!

Test video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/ea0b058b-693d-43f2-a870-e4f66054c926



I am not sure if this is related to this PR, as mentioned by @sxiong5, I also encountered with the same issue he had with owner account trying to access its own profile page. I checked development branch, and it does not have this issue. It seems it is only owner account though, admin account has no issue accessing its own profile. See my test video:

development:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/554cffd5-5ff1-4ba8-88e9-032e31e9655c

Owner trying to access its own profile:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/5bc9cd26-1ec0-4f14-b6a1-93a50032c15f

**Review by wantingxu7 — DISMISSED** [review]
I tested the PR and logged in as admin/owner/volunteer, the function works as described.
admin:

owner:

volunteer:


the clipboard:

**Comment by luisarevalo21** [comment]
> Hello @luisarevalo21 I pulled your changes and tested them locally
> 
> I have ran into an issue with displaying my Admin accounts profile when clicking 'View Profile' I found that it doesn't load their profile if they are not on a team/project. But works when I created a new Admin thats on a team/project.
> 
>  Untitled_.Oct.19.2023.12_58.PM.webm 
> confirm it does work on Owner Account
> 
>  Untitled_.Oct.19.2023.1_00.PM.1.webm 
> I also confirmed it does now show when viewing as a volunteer
> 
> image
> 
> Nice work! Happy coding!

Hello, 
Thanks for the find! 
I didn't have a check, to see if they are on a team or not hence why it crashed. 
However, I added code to check if they are on a team and will work regardless.

**Comment by luisarevalo21** [comment]
> Hi @luisarevalo21, I tested your PR locally with owner, admin and volunteer accounts. The 'Generate Summary Intro' button works as described. It will copy the summary intro according to the user's name. Great work!
> 
> Test video:
> 
>  1428-test.mp4 
> I am not sure if this is related to this PR, as mentioned by @sxiong5, I also encountered with the same issue he had with owner account trying to access its own profile page. I checked development branch, and it does not have this issue. It seems it is only owner account though, admin account has no issue accessing its own profile. See my test video:
> 
> development:
> 
>  1428-dev.mp4 
> Owner trying to access its own profile:
> 
>  1428-owner-profile-issue.mp4

Hello, 
I didn't have a check, to see if the user is on a team or not hence why it crashed. 
However, I added code to check if they are on a team and will work regardless.

**Comment by luisarevalo21** [comment]
> Hey @luisarevalo21, I pulled your changes and tried to test the function. However, I got some errors when I opened the profile page; please check the video for more information. I also switched back to the `development` branch, and it worked well on that branch.
> 
> Also, the button required a mouseover text as Jae's description, and it seems like you missed this feature from what I've seen from the demo video.
> 
>  Screen.Recording.2023-10-19.at.15.52.23.mov

Hello, 
I didn't have a check, to see if the user is on a team or not hence why it crashed. 
However, I added code to check if they are on a team and will work regardless. 

Also, the button does have a hover action. See the screenshot below. 
Thanks.
Screenshot 2023-10-19 at 7 33 00 PM

**Comment by luisarevalo21** [comment]
One note, 
With the new changes, I also hid the button if the user isn't on a team. To prevent further crashes.

**Review by StrawberryCalpico — COMMENTED** [review]
I tested your PR, it works as the description. Good Work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/5c822cf8-8d12-45ab-b99f-a4f2c15a3bb1

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/50cb1046-793c-429f-8497-f031b7354844

**Review by KurtisIvey — APPROVED** [review]
Works as intended. The code looks really good as well. Doesn't crash whenever navigating to user profile that's not a part of a team. In addition, it shows the button for higher level roles and doesn't show it for volunteer roles. 

View with owner account:
pr1428 shows new btn with owner account


View with volunteer account:
pr1428 doesn't show button with volunteer acct

**Pull request merged**
