### PR TITLE
Nahiyan_Added Dark Mode on Time Off Modal

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Added dark mode on Time off modal and Ready for Review dropdown

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Added dark mode to Time Off Modal
- Added dark mode to Ready for Review dropdown

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Tasks and Timelogs → Tasks
6. verify that when clicking "Ready for Review", the dropdown background is in dark mode
7. verify that when you click on details after finding a user who has taken time off, the modal is in mode.
8. You can find these options if you scroll on the tasks section on a owner account

## Screenshots or videos of changes:
Screenshot 2024-08-16 193032
Screenshot 2024-08-16 193033

### CODE REVIEW

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
The options in dropdown from "Ready to Review" have a white background on mouseover due to which text is not visible. Please fix that. Rest everything works fine.

https://github.com/user-attachments/assets/130b36ac-77e7-48af-b4a2-c682a1c9313f

**Comment by Nahiyan-16** [comment]
@JatinAgrawal94 Fixed!

**Review by kdaga81 — APPROVED** [review]
image
image

Changes working as expected

**Review by Aishwarya0898 — APPROVED** [review]
Hello @Nahiyan-16 
The PR is working as expected, here is the reference.


https://github.com/user-attachments/assets/aa1f07f2-99b1-441c-8282-02fc51543d81

**Review by Gauravmg6 — APPROVED** [review]
Working as expected.
Screenshot 2024-08-18 013309
Screenshot 2024-08-18 013709

**Comment by beblicarl** [comment]
this feature works as intended

image

image

**Review by beblicarl — APPROVED** [review]

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (176)
Screenshot (175)

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.




Thank You

**Review by Saniya98 — APPROVED** [review]
Everything is working as expected

**Review by Pranay-ai — APPROVED** [review]
Hey @Nahiyan-16 
The PR is Working as Expected PFA for reference
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
