### PR TITLE
Nahiyan_Fixed dark mode on dashboard issue

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
There is an issue where when going to any other page besides dashboard and toggling on and off dark mode, coming back to dashboard, you can see some of the table headers are broken as they are appearing in light mode instead of dark mode.

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Updated colors of table item background to yinmn blue
- Fixed table header not reverting back to dark mode
- Fixed table item hover effect appearing in light mode while in dark mode

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ toggle on dark mode -> go to reports page -> toggle on and off dark mode -> back to dashboard
6. verify the timelog table header and items act properly and display in dark mode colors
7. verify the leaderboard table header and items act properly

## Screenshots or videos of changes:
Before:
Screenshot 2024-04-27 104127
After:
Screenshot 2024-04-27 105113

### CODE REVIEW

**Review by tdkent — DISMISSED** [review]
Updates work as intended. The table headers and hover effects appear in dark mode on the Dashboard. The color scheme remains correct after navigating off Dashboard, toggling dark/light mode, then navigating back to Dashboard.

Current table header:
dashboard-current

Updated table header:
dashboard-new

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected.
Screenshot 2024-04-27 at 3 22 42 PM

**Review by lacnoskillz — DISMISSED** [review]
Hello @Nahiyan-16 
I was able to replicate this bug on dev and confirmed your changes fixes is.
All functionality appears to be the same and works as intended
Nice job!
Please see below images

## Before
pr 2203 before


## After
after pr 2203

**Comment by beblicarl** [comment]
This functionality works as intended, tables and headers remain in black mode even after toggling between pages.

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.04.28-07_13_27.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/433fce86-a35c-49a2-943c-4bccbfe01afe)

**Review by beblicarl — DISMISSED** [review]

**Review by MinSun0814 — DISMISSED** [review]
Works as intended.
Old:
image
New:
image

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and it is working as intended. Please refer the screenshot attached.

PR 2203

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
