### PR TITLE
Shiwani hotfix for AssignBadgePopup unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Failed one of the test cases in development for AssignBadgePopup component due to a change in onClick function name in development.

## Main changes explained:
- Changed toggle to submit in AssignBadgePopup.test.js because another PR had changed the name of the onClick function and it was merged into development while the unit test for AssignBadgePopup was open for review with the old change .

## How to test:
1. check into current branch
2. do `npm run test src/__tests__/AssignBadgePopup.test.js` 
3. check if all test cases pass

## Screenshots or videos of changes:
Screenshot 2023-12-09 at 7 16 47 PM

### CODE REVIEW

**Comment by DragonSlayer2401** [comment]
I tested your PR all of the tests passed as intended. Please watch the overview video for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/ec8a5da3-2b82-4d4c-bb77-c297d99d9df3

**Review by AaronPersaud — APPROVED** [review]
Hi Shiwani, I've tested and you've fixed the failing test that was merged earlier. Nice work!

image

All tests pass now.

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-12-10 at 12 55 25 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
