### PR TITLE
Yuri - Design navigation bar

### PR DESCRIPTION
**Pull request by yurisokolovicz**
# Description
This PR is associated with the design of the navigation bar for Phase II of HGN Software. Two elements require testing: (i) the standard Header, which is currently utilized and (ii) the prototype (provided below) included in HGN Phase II for Materials, Equipment, and Tools.

The current Header, featuring the new navbar connecting BMDashboard and Project from HGN Software Phase 2 implementation, is displayed in the attached image.

Screenshot 2023-10-14 115246

The prototype below will be integrated into the existing Header in the future, with the links being managed through states. To test this, you should comment out the Header and uncomment the BMHeader in the “src/routes.js” file.

Screenshot 2023-10-06 145548

Screenshot 2023-10-06 145747

## How to test:
1.0 Current Header component
1.1 Check out the current branch.
1.2 Run "git pull".
1.3 Run "npm install" and "npm run start:local" to run this PR locally.
1.4 Go to http://localhost:3000/
1.5 Verify the normal functioning of the following elements: owner message, timer, login/logout, and ensure that the BMDashboard and all new Project links are operational.
1.6 Check if there are any errors.
_____________________________________

2.0 To test the BMHeader, please comment out the Header and uncomment the BMHeader in the “src/routes.js” file.
2.1 Compare the design to the prototype.
2.2 Test for responsiveness in different screen sizes.
2.3 Verify that the reports, userprofile and login/logout functionality are working normally.
2.4 Check the other navbar links; they should redirect you to blank pages that will be developed further as part of the Phase 2 project.
2.5 Check if there are any errors.

## After:

Screenshot 2023-10-13 124527

Screenshot 2023-10-06 145022

### CODE REVIEW

**Review by beblicarl — DISMISSED** [review]

**Comment by olenadanykh** [comment]
Hi @yurisokolovicz,

I've tested your PR, and it looks great. The navbar links appear exactly as shown in the picture, and they are responsive as well. The login/logout, user profile, and reports functionality work without any issues. Additionally, the other navbar links redirect to blank pages as expected. Great work!!!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/c79890f7-350c-4e5a-86dc-07c695dc1b54

**Review by wantingxu7 — DISMISSED** [review]
Hi @yurisokolovicz 
I've tested it and the PR LGTM. The function of report, profile and login/logout works well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/5a8e5ac5-db10-44aa-a229-ff7c397d4d06

And I also noticed that the inspector loads the following warning:
截屏2023-10-09 上午11 02 56

**Comment by emunkh404** [comment]
The changes made in the pull request closely match the provided picture and exhibit responsive design. Extensive testing has confirmed that the navbar links, login/logout, user profile, and reports functionality function smoothly. Furthermore, other navbar links redirect to blank pages as intended. Excellent job!

image

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/f88476e0-b239-4e87-8d2c-5a8271ea3181

**Review by yi-lin-1234 — DISMISSED** [review]
Hello, I tested your PR and works as intended. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/4e42b20e-3225-482a-bac2-43afd0ba732c

**Review by navneeeth — DISMISSED** [review]
Hello, @yurisokolovicz! I tested your PR and everything works as expected. Great work!
Tested for responsiveness in different screen sizes, verified that the reports, user profile, and login/logout functionality are working normally. The other navbar links redirect to blank pages.
Could not detect any errors.

### Testing video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/640344d2-5ec5-454b-9107-14ef816dac97

**Review by malikjahanzaib — APPROVED** [review]
Hi @yurisokolovicz, I have reviewed the changes in this PR. The Navbar UI looks exactly as in the reference picture. Also the functionalities such as Reports, User Profile and Login/Logout seems to work without any errors. 
P.S. I also didn't notice any console errors when logging into the application dashboard. 
Great Job!

Test Rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/7c56cfb1-2196-4fd5-98d7-06448f6d4c4d

**Comment by luisarevalo21** [comment]
Hello @yurisokolovicz.

I tested your PR and works as intended. Great work! 
The navbar is responsive and looks identical to the mark up.

A couple things:
Weekly summary report does not load and crashes.
The following errors occur. I don't think its related to your PR. It loaded once but hasn't since. 
Screenshot 2023-10-10 at 8 50 48 PM

Next reports has two scroll bars. 
Screenshot 2023-10-10 at 8 49 26 PM

Lastly, there's no way to return to the dashboard, after selecting a link. 
I am unsure if this is intentional, since you are adjusting the the navbar. There should be a way to return to the dashboard.

Overall great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/8fb98f23-cb12-464f-97bc-8d969b0e725b

**Comment by DavidC0126** [comment]
Hi @yurisokolovicz I tested your PR and it works as intended. Good job! I also agree with the suggestion from luisarevalo21 on no way to go back to the dashboard.


Uploading pr1396.mov…

**Review by lacnoskillz — COMMENTED** [review]
Hi Yuri
I pulled your changes and ran them locally
The design seems to match your mock up as well as passing the galaxy fold responsive test

**Note that with your changes that when attempting to logout in the non existent pages like > Log Issue > Logout we get stuck on that page
Also Note that the DropDown Menu for View Profile/Update Password/ Logout is shifted out side of the view port slightly

image


I think it might be unrelated to your changes because its in development too

video of my test:

[Untitled_ Oct 11, 2023 11_31 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/173520e1-eebc-4c9a-b151-e2b84875c781)

Nice work! and happy coding

**Review by Sssky-18 — DISMISSED** [review]
Hi @yurisokolovicz, I tested this PR and it worked as expected. First of all, the design is the same as the prototype, and all the buttons are clickable. The reports, user profile and login/logout functionality are working normally, and all others are directed to blank pages. Besides, the pages are responding properly in different sizes. Therefore, I approved this PR and thank you for your contribution! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/d6d7fa90-fdad-44a0-bae0-7d8f173bfdc9

**Comment by Lin1404** [comment]
Hi @yurisokolovicz,

I've tested your PR, and it looks good. The navbar links appear exactly as shown in the picture.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/eec1c552-ee0b-4296-82cc-ddbd3c7b8e63

**Review by Lin1404 — APPROVED** [review]

**Review by sxiong5 — APPROVED** [review]
Hey @yurisokolovicz, the PR works as described. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/7a72a872-d5e6-4922-81b0-3f48e28d28de

**Review by eduhorta — COMMENTED** [review]
Hey @yurisokolovicz!

Everything seems to be working as expected.

My question is:

What will happen to the "Other Links" option?
Screenshot 2023-10-12 at 14 47 49

image

**Review by yangfan2001 — APPROVED** [review]
Hi, I have tested your PR. It works well in different screen size, Great Job!
image
image

**Comment by yurisokolovicz** [comment]
> Hey @yurisokolovicz!
> 
> Everything seems to be working as expected.
> 
> My question is:
> 
> What will happen to the "Other Links" option? Screenshot 2023-10-12 at 14 47 49
> 
> image

This is a navbar that will be used in specific parts of Phase 2, not when you enter in the app. I will create another PR to connect the Phase 1 and Phase 2 navbars, integrating BMDashboard and Projects into the Phase 1 navbar. I will create and commit changes to comment out the current navbar in this PR, but it will be used in the future.

**Review by tdkent — CHANGES_REQUESTED** [review]
This branch appears to remove critical features in order to make it look exactly like the phase 2 wireframe (which is not necessary):

- The timer has been removed
- The logo has been removed
- Dashboard, Timelog, and Other Links navigation have all been removed

I'm also concerned about replacing the current Header component with a new BMHeader component that is confusingly placed in the BMDashboard file hierarchy. IMO a better approach is to update the current Header component with necessary links to the BMDashboard, leaving other vital functions and routing in place.

The added links should probably be 'BM Dashboard', which routes to '/bmdashboard' and a Projects dropdown with links to various areas of the BM portal.

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Hello @yurisokolovicz, I can see how you were trying to split up the different links logically and that's a good idea. But as Tim suggested, I think the aim was to have maybe a separate Header for the BMdashboard and not remove any functionality from the current Header. Not sure if the best implementation would be to have two different headers for the main dashboard and the bm dashboard or if we should conditionally render the links in one header in accordance to what page is being viewed. I'm sure there's a way we can just have one header but I can see how quickly that could get confusing within the Header component. As per the figma diagrams for Phase II, we may need to brainstorm on this one.
Screenshot 2023-10-13 at 12 44 47 PM

**Review by tdkent — DISMISSED** [review]
Since @yurisokolovicz's intention (not clear from the PR description but I discussed with him) is to add a commit that comments out **BMHeader** (for use at a later time) and comments back in **Header** I am updating to approve.

**Comment by yurisokolovicz** [comment]
> Since @yurisokolovicz's intention (not clear from the PR description but I discussed with him) is to add a commit that comments out **BMHeader** (for use at a later time) and comments back in **Header** I am updating to approve.

I decided to add all the corrections in this PR and integrate them with the current header to avoid creating another PR. Please check it now.

**Comment by yurisokolovicz** [comment]
> Hello @yurisokolovicz, I can see how you were trying to split up the different links logically and that's a good idea. But as Tim suggested, I think the aim was to have maybe a separate Header for the BMdashboard and not remove any functionality from the current Header. Not sure if the best implementation would be to have two different headers for the main dashboard and the bm dashboard or if we should conditionally render the links in one header in accordance to what page is being viewed. I'm sure there's a way we can just have one header but I can see how quickly that could get confusing within the Header component. As per the figma diagrams for Phase II, we may need to brainstorm on this one. Screenshot 2023-10-13 at 12 44 47 PM

Thank you for your review, Gary, please check it again now.

**Review by yi-lin-1234 — DISMISSED** [review]
Hello, I tested your updated PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/32afa42a-0fab-4e3d-aa7a-db8f7eb9a16e

**Review by ChirayuRai — APPROVED** [review]
I tested both headers. All pages/links in the navbar seem to working as intended, and the new navbar is very responsive. Nice job!
Screen Shot 2023-10-14 at 11 32 26 PM
Screen Shot 2023-10-14 at 11 31 01 PM

**Review by GaryB93 — DISMISSED** [review]
BM Header component successfully created following documentation for Phase II. Discussed with developer future consideration of reviewing design and implementation details and possibly remove the need for an additional header component.

**Review by wantingxu7 — APPROVED** [review]

**Review by navneeeth — APPROVED** [review]

**Review by beblicarl — APPROVED** [review]

**Review by malikjahanzaib — APPROVED** [review]
Hi @yurisokolovicz, I have reviewed and tested this PR again after changes and everything seems to work as described. All UI changes are responsive and old functionalities also seem to work just fine as before. Good job!!!

Screenshots:

Screenshot 2023-10-17 162338

Screenshot 2023-10-17 162021


Screenshot 2023-10-17 162143

**Review by cvtqx — APPROVED** [review]
Great work, @yurisokolovicz ! I've tested this PR,  it works as described and is responsive.

Here is the header:
Screen Shot 2023-10-18 at 10 49 36 AM

And the BMheader:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/c83eefe4-b63e-46c4-b9e4-3e212ed61773

**Pull request merged**
