### PR TITLE
Tianjue fix timelog icon format

### PR DESCRIPTION
**Pull request by tingedudu8**
# Description
Fix TIME LOG COMPONENT
(PRIORITY MEDIUM) Jae: Fix appearance of icons when logging tangible/intangible time
Log time and you’ll see what’s below for the description field 
Screen Shot 2023-03-23 at 5 38 10 PM

## Mainly changes explained:
Adjust the CSS file and block the icon.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. login in as any role
4. go to dashboard→ log time→ you will see the icons are formatted

## Note:
It should also work for the icons on the block to write "Weekly summaries".

### CODE REVIEW

**Review by nicollext — APPROVED** [review]
It works as intended.  Also  tested for for the icons on the block to write "Weekly summaries". Great job!

**Before**

https://user-images.githubusercontent.com/101591708/227668608-cbbf89d5-6a0b-4c97-9f36-9f88689f184d.MP4


**After**

https://user-images.githubusercontent.com/101591708/227668612-2d38587e-2f28-4b60-b741-cbdb92ddf5af.MP4

PR#732tianjue_fix_timelog_icon_format

**Comment by AnishPandita** [comment]
Hi @tingedudu8 I tested your PR and its looks great. Icons look clear and nice on tangible time entry as well as on summary option.

https://user-images.githubusercontent.com/111321945/227714545-7d13492e-3a97-4796-9d39-c9964740e369.mov

**Review by PrabhjotSembhi — DISMISSED** [review]
It's working fine 
icons

**Review by kangjay88 — APPROVED** [review]
Hi @tingedudu8 , I have tested this PR and it works as intended. Tangible, Intangible, and Weekly Summary icons are responsive and show up great! Thank you

https://user-images.githubusercontent.com/108297706/227736751-71fd9fcd-14e1-46e6-a029-b78e18ac3654.mp4

**Comment by calexander3108** [comment]
All working great! Thanks for the hard work!

Tangible
image

Intangible
image

Weekly Summaries
image

**Comment by Jorge-Nerd** [comment]
Hello @tingedudu8 I tested and compared to
 before changes
PULL#732_1

After, Good Job

Pull#732_2

**Comment by one-community** [comment]
Thank you all. Moving to final review but @tingedudu8 please resolve the merge conflicts.

**Comment by PrabhjotSembhi** [comment]
@tingedudu8 Hey I Have reviewed it. It working well. The icons are looking good. But please resolve conflicts

**Comment by one-community** [comment]
Ok, closing it, thank you. Not sure what caused this to fix itself... thank you everyone for your effort though.

**Pull request closed without merging**
