### PR TITLE
Jacob - Optimize member search

### PR DESCRIPTION
**Pull request by DragonSlayer2401**
image

## Related PRS (if any):
This frontend PR is related to the #1912 frontend PR.
This frontend PR is related to the [#739](https://github.com/OneCommunityGlobal/HGNRest/pull/739) backend PR.
…

## Main changes explained:
- Optimize member filtering
- Add full name searching
- Clear search results when none are found
…

## How to test:
1. check into current branch
2. check into the related backend branch
3. do `npm install` and `npm run start:local` to run the frontend locally
4. Clear site data/cache
5. login as Owner user
6. go to Dashboard→ Other Links → Projects → any project's members
7. verify all searches occur and finish quickly
8. verify search results clear when no members are found
9. verify you can search by first name (case-insensitive)
10. verify you can search by last name (case-insensitive)
11. verify you can search by full name (case-insensitive)
12. verify you can search by substrings such as Jac (case-insensitive)

## Screenshots or videos of changes:
Before:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/9a5b653e-48b0-431f-9b10-c40109898234

After:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/68051a17-978a-4125-b9be-3a308150fc6a

### CODE REVIEW

**Review by TareqMia — APPROVED** [review]
Hi @DragonSlayer2401, I tested this PR with the related backend PR and everything worked as expected. The results loaded relatively quickly and I was able to search by the different criteria mentioned. Overall, really great job on implementing this 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/7f46ea6b-866e-48c4-8fe2-a3dda04a8830

**Comment by galgalinidhi** [comment]
Hi @DragonSlayer2401, I tested your PR and the search filter works correctly. I noticed the following:
 1. I see that when I type "nid" the results with the substring "Ni" show up first. 
 2. When I typed in a Random string I still see results. 
 I was curious if this is how it is supposed to work.

Please refer to the screenshots I have provided. 
Screenshot 2024-02-10 at 5 29 59 PM

Screenshot 2024-02-10 at 5 40 27 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/4b1f2357-540e-4429-a35f-5a8c2a0f5088

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and worked as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/ad97a2dd-4a1b-448b-ae7c-df7e179e3c5b

a small detail that I noticed, is that some profiles, in the name/or surname field, more than 1 "name" were used, e.g.: name field: clemar nunes, surname field: adm, result: clemar nunes adm, so, when Try to locate using, for example, "clemar nunes", you will not find the user.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/8ac0d5b6-7c5c-4232-9653-6a7baf9c504c

**Review by SaiDeepak-NEU — APPROVED** [review]
Hello Jacob, Tested the changes in the PR and everything worked very smoothly, I was able to fetch the search results pretty quick and search by firstname and lastname worked flawlessly.
Screenshot (94)
Screenshot (93)
Screenshot (92)

**Review by XiaohanMeng — APPROVED** [review]
Hi, I tested this PR, and it worked as intended. The search functionality within the project is very fast and operates flawlessly in various scenarios. I tested it using first names, last names, full names, partial names, and random strings, and all worked exceptionally well. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/09b2b0dc-4a51-4751-9d57-7e0fdaa9f8ac

**Review by Jingyii800 — APPROVED** [review]
Hi, @DragonSlayer2401. Well done! I tested all cases, they worked as described and vert fast. I can search the member by first name, last name, full name, and also substring. Please check more details from my video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/e3d6fe1c-51ca-4cb7-9e39-70a64edd9e54

**Review by TapanPathak — APPROVED** [review]
Hi, I tested the changes in the PR and everything worked very smoothly. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/dca0bb23-47da-47a2-858d-eef1995b959b

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.16-17_22_38.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/e8b46902-4e03-45f7-8757-03824a4f527c)

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
