### PR TITLE
yihan Create way to manually add in lost hours for past years of volunteers

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
This frontend PR is related to the [#611](https://github.com/OneCommunityGlobal/HGNRest/pull/611) backend PR.

## Main changes explained:
- Create AddLostTime.jsx for introducing Add Lost Time modal.
- Create LostTimeHistory.jsx and EditHistoryModal.jsx for introducing tracking method of additions of lost time.
- Update Reports.jsx for including AddLostTime and LostTimeHistory component on reports page.
- Update TotalProjectReport.jsx, TotalPersonReport.jsx and TotalTeamReport.jsx for adding lost time to reports.

## How to test:
1. check into current branch on both FE and BE
2. do `npm run start:local` to run this PR locally
3. log as Owner user
a. go to dashboard→ Reports→ Reports, verify if the Owner user can see the "Add Lost Time" and "show project/person/team lost time" at the bottom of the page. 
b. Click on "Add Lost Time" button and add time for a project/person/team, then go to "Show Total Project/Person/Team Report", see if the time is added to the report correctly.
c. Then, click on "show project/person/team lost time", verify if the user can see, edit and delete the addition.
4. log as Admin user
a. go to dashboard→ Reports→ Reports, verify if the user can only see "show project/person/team lost time" at the bottom of the page.
b.  Click on "show project/person/team lost time", verify if the user can see, edit and delete the addition.
5. log as Manager/Mentor/Core team user
a. go to dashboard→ Reports→ Reports, verify if the user can only see "show project/person/team lost time" at the bottom of the page.
b.  Click on "show project/person/team lost time", verify if the user can see, but cannot edit or delete the addition.

## Screenshots or videos of changes:

Owner can add, edit and delete lost time:
Screenshot 2023-11-20 at 11 40 24

Administrator can edit and delete lost time:
Screenshot 2023-11-20 at 11 39 47

Manager/Mentor/Core team can only see the lost time:
Screenshot 2023-11-20 at 11 41 02

Example of testing Project: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/e4910cd8-3879-4d20-851a-563e2c45a969

Steps of testing Person and Team are same.

## Note:
An error of "currentTarget" might occur when showing Total Project Report, which also happens on dev branch and is out of scope of this PR:
image

### CODE REVIEW

**Comment by palakgosalia** [comment]
Hey, I reviewed and tested your PR. From the Owner account, I am able to see all the tabs mentioned in the description. I was able to add lost time to a project and edit and delete it. 

When I logged in as a manager, I did not see the add lost time button as expected but when I tried to edit the lost time that I had added, I got a 403 error and I was not able to edit it. I was able to delete the lost time. 
Details in the video


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/1ca831c6-9554-4606-899d-1e2ba49d829d

**Comment by AriaYu927** [comment]
> Hey, I reviewed and tested your PR. From the Owner account, I am able to see all the tabs mentioned in the description. I was able to add lost time to a project and edit and delete it.
> 
> When I logged in as a manager, I did not see the add lost time button as expected but when I tried to edit the lost time that I had added, I got a 403 error and I was not able to edit it. I was able to delete the lost time. Details in the video
> 
>  1535_611.mp4

Thanks for testing! I've updated this PR and its description. Now, only Owner and Administrator can edit and delete time entries, Mentor/Manager/Core team can only see the time entry table. Please re-review it when you get a chance, thank you!

**Comment by ptrpengdev** [comment]
I tested the PR and all functions work as expected. However, there was a glitch in the Reports Page for all accounts. The data grid is hidden if the "Show Project/Person/Team Lost Time" button is clicked "EVEN" times, for example, the 2nd, 4th, and 6th time clicked on the button. 

Log in as **Admin** user:
a. Verified the user can only see "show project/person/team lost time" at the bottom of the page.
b. Clicked on "show project/person/team lost time", and verified that the user can see, edit, and delete the addition.
image

Log in as **Owner** user:
a. Verified the Owner user can see the "Add Lost Time" and showed "project/person/team lost time" at the bottom of the page.
b. Clicked on the "Add Lost Time" button, added time for a project/person/team, and verified the time was added to the report correctly.
c. Clicked on "show project/person/team lost time". Verified the user can see, edit, and delete the addition.



Log in as **Mentor** user
a. Verified the user can only see "show project/person/team lost time" at the bottom of the page.
b. Clicked on "show project/person/team lost time", and verified the user can see, but cannot edit or delete the addition.
image

**Comment by AriaYu927** [comment]
> Hi @AriaYu927, I tested the PR and all functions work as expected. **However**, **there was a glitch in the Reports Page for all accounts**. The data grid will be hidden if the "Show Project/Person/Team Lost Time" button is clicked "EVEN" times, for example, the 2nd, 4th, and 6th time clicked on the button. I am not sure if this is the expected behavior. Please correct me if I am wrong. Thank you!
> 
> Log in as **Admin** user: a. Verified the user can only see "show project/person/team lost time" at the bottom of the page. b. Clicked on "show project/person/team lost time", and verified that the user can see, edit, and delete the addition. image
> 
> Log in as **Owner** user: a. Verified the Owner user can see the "Add Lost Time" and showed "project/person/team lost time" at the bottom of the page. b. Clicked on the "Add Lost Time" button, added time for a project/person/team, and verified the time was added to the report correctly. c. Clicked on "show project/person/team lost time". Verified the user can see, edit, and delete the addition. 
> 
> Log in as **Mentor** user a. Verified the user can only see "show project/person/team lost time" at the bottom of the page. b. Clicked on "show project/person/team lost time", and verified the user can see, but cannot edit or delete the addition. image

Thanks for your testing! The data table is expected to close when the button is clicked even time. I implemented the "show ... lost time" button as a toggle. After clicking on the "show ... lost time", we'll see it turns into "Hide ... lost time". It can change back to "Show ... lost time" if we click it again.

**Comment by ptrpengdev** [comment]
> > Hi @AriaYu927, I tested the PR and all functions work as expected. **However**, **there was a glitch in the Reports Page for all accounts**. The data grid will be hidden if the "Show Project/Person/Team Lost Time" button is clicked "EVEN" times, for example, the 2nd, 4th, and 6th time clicked on the button. I am not sure if this is the expected behavior. Please correct me if I am wrong. Thank you!
> > Log in as **Admin** user: a. Verified the user can only see "show project/person/team lost time" at the bottom of the page. b. Clicked on "show project/person/team lost time", and verified that the user can see, edit, and delete the addition. image
> > Log in as **Owner** user: a. Verified the Owner user can see the "Add Lost Time" and showed "project/person/team lost time" at the bottom of the page. b. Clicked on the "Add Lost Time" button, added time for a project/person/team, and verified the time was added to the report correctly. c. Clicked on "show project/person/team lost time". Verified the user can see, edit, and delete the addition. 
> > Log in as **Mentor** user a. Verified the user can only see "show project/person/team lost time" at the bottom of the page. b. Clicked on "show project/person/team lost time", and verified the user can see, but cannot edit or delete the addition. image
> 
> Thanks for your testing! The data table is expected to close when the button is clicked even time. I implemented the "show ... lost time" button as a toggle. After clicking on the "show ... lost time", we'll see it turns into "Hide ... lost time". It can change back to "Show ... lost time" if we click it again.

Thanks for the clarification! I have no issue with the PRs. Will remove the glitch part from the previous comment. Thanks!

**Review by pika-chu11 — COMMENTED** [review]
Hi @AriaYu927 , I have tested your PRs using different type of account. You did a great job!
Here is my test result:

- Log in as Owner
    - Under dashboard -> Reports -> Reports
        - I was able to see the "Add Lost Time" and other buttons like "show project/person/team lost time" at the bottom of the page as described.
     - When clicked on the "Add Lost Time" button
         - I was able to add time to the specific project I selected and submitted.
     - When clicked on the "Show project/person/team/lost time" button
         - I was able to see and do edit/delete to added project time.
     - When clicked on the "Show Total Project/Person/Team Report" button
         - I was able to see first 80 users's total project time and it shows the correct time after added/deleted.
   
 - Same thing works for the Admin user except an Admin won't be able to see the "Add Lost Time" button just as described.
 
 - Same thing works for the Mentor/Manager/Core Team user as they can only see the data not modifying them.
        
> **Note:** I also encountered the error you mentioned in the Note, when it occured it seems that the whole page is frozen and need to refresh the page to get in work. 

For more details please watch the video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/5253e11f-4d7a-4760-a9aa-af3f51d1dc82

**Review by Alforoan — DISMISSED** [review]
They all seem to work. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/641bf974-3a7c-4685-a68f-9275385d21aa

**Comment by one-community** [comment]
Thank you all, moved to final review.

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

Owner role:
image

Admin role:
image

Manager role:
image

**Review by beblicarl — APPROVED** [review]

**Review by navneeeth — COMMENTED** [review]
Hey there! Just reviewed your PR and everything looks good! 

# Owner Role
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/9d7ddbb3-ff4c-480f-a79a-743cd50ed2a0

# Admin Role
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/ef6bd1a3-67ff-44ab-8db0-07743a065ecc

# Core Team Role
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/c8a82535-ea91-4662-952b-34da81d253a5

# Manager Role
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/04dc9cac-8ade-4bc1-84d3-ee129a1d9db4

#Manager Role and Responsiveness
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/022b3e70-3c3a-49fa-bba6-a06eecc1b594

Good implementation!

**Pull request merged**
