### PR TITLE
Yi - Add Overview Report page route and permission control

### PR DESCRIPTION
**Pull request by FyisFe**
# Description
image

## Related PRS (if any):
This frontend PR is related to the dev backend PR.

## Main changes explained:
- Create file OverviewReport.jsx for introducing new OverviewReport component.
  - For now, it is an empty page, sub-components will be introduced in future PRs
- Add a new Permission `getOverviewReport` to control visibility/access to the page

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as an user without `getOverviewReport` permission
5. go to dashboard→ Reports → OverviewReport should be invisible
6. try to access `http://localhost:3000/overviewreport` and will be redirected to dashboard
7. give `getOverviewReport` to the user and try to access it again

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/15bb414d-3a7f-4745-9d7b-ff1c178a78d9

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
Looks good! There is a new permission getOverviewReport to access to the page.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/67441f45-9d3b-4b80-b56f-085ef93f67ac

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it is working as intended. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/67a7c2ac-71eb-4c72-bbbb-c231112823e4

**Review by ImzIssa — APPROVED** [review]
Hello,  I've tested your PR, the route is accessible and I can view the placeholder text in component.

PR#2070

**Review by Pandani07 — APPROVED** [review]
Gave my owner account the permission and could see the placeholder text in http://localhost:3000/overviewreport
Screenshot 2024-03-20 at 2 02 57 PM

**Review by Abi-Liu — APPROVED** [review]
Looks good! After giving my user permission I can now access the overview report page.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/8319a514-cacd-4545-bc1c-a7fd3294b54d

**Review by Sarthak32 — APPROVED** [review]
I tested your PR and it works as expected after giving permission:
Screenshot 2024-03-24 113638
Screenshot 2024-03-24 113742

Screenshot 2024-03-24 114304

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and it works perfectly. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/0b9502b0-dd63-4a6b-80be-c50eefe31e11

**Pull request closed without merging**
