### PR TITLE
Nahiyan_Dark mode for Permissions Management Modals

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Implemented dark mode on all modals that can be found on the Permissions Management page

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Dark mode for all modals on the Permissions Management page

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links → Permissions Management 
6. verify that all modals on the Permissions Management page are working properly

## Screenshots or videos of changes:
Screenshot 2024-05-20 131139
Screenshot 2024-05-20 131208

### CODE REVIEW

**Review by cecilia-uu — APPROVED** [review]
It works well as expected! 
截屏2024-05-21 下午2 40 25

**Review by Sandhya1236 — APPROVED** [review]
All modals are implemented in dark mode on the Permissions Management page. Everything works as expected. 
image

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and it works as intended. Please refer the screenshots attached.

PR 2272 1
PR 2272 2

**Review by hbodgal — APPROVED** [review]
image

works well!

**Review by Kavil-Jain-514 — APPROVED** [review]
Dark mode works for all Modals
image
image
image

**Review by curiousfancier — APPROVED** [review]
This PR  works as intended. Please refer to the screenshots attached.
Screenshot 2024-05-23 224051
Screenshot 2024-05-23 224108

**Review by nathcarnevalli — APPROVED** [review]
Worked as expected

Screenshot 2024-05-24 160928
Screenshot 2024-05-24 160935
Screenshot 2024-05-24 160956

**Review by Pandani07 — APPROVED** [review]
Night mode works properly and all the modals change style accordingly 
Screenshot 2024-05-24 at 4 57 10 PM
Screenshot 2024-05-24 at 4 56 55 PM

**Review by MinSun0814 — APPROVED** [review]
image
image
Dark mode looks good. Nice work.

**Comment by one-community** [comment]
Thank you all, merging!

**Review by mohabbasd — COMMENTED** [review]
Hello, I tested your PR and it works perfectly. Great Job! Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/a36e8b69-ea60-47cb-b588-6f58ac1b4604

**Pull request merged**
