### PR TITLE
Chris_ignore_spaces_inputs_user_management_search

### PR DESCRIPTION
**Pull request by chrischenlixing**
# Description
Screenshot 2024-06-10 at 10 47 13 PM
The search for the User Management search should ignore the starting and trailing spaces

## Related PRS (if any):
Not related to any backend prs. For the backend please just check in to the development branch

## Main changes explained:
Ignored the starting and trailing spaces for the following searchbox and the headers
- firstNameSearchText
- lastNameSearchText
- emailSearchText
- weeklyHrsSearchText
- wildCardSearchText

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Admin Login → Other Links → User Management
6. For the SearchBox enter:    ChrisAdmin
7. For the FirstName enter:   Chris  
8. For the LastName enter:     Chen  
9. For the Email enter:     chrischen  
10. For the Weekly Committed Hours enter:   5   
(For the test, you can use your own test cases, just add some starting and trailing spaces to them 

## Screenshots or videos of changes:
[The original problem recorded by Jae](https://www.loom.com/share/965d643e027b437f9116d18602504020?sid=e4a4700b-453e-46a6-b63d-4ce0bf660036)

This is my fixture of problem
For the TextBox, it's not allowing spaces anyway
Screenshot 2024-06-10 at 11 17 07 PM
For the first name, you can see the search results with the spaces
Screenshot 2024-06-10 at 11 17 34 PM
For the last name, you can see the search results with the spaces
Screenshot 2024-06-10 at 11 17 54 PM
For the email, you can see the search results with the spaces
Screenshot 2024-06-10 at 11 18 16 PM
For the Weekly Committed Hours, you can see the search results with the spaces
Screenshot 2024-06-10 at 11 18 36 PM

## Note:
For the search box, it's automatically voiding the starting and trailing spaces, but for other text boxes in the headers, it does not ignore the spaces. The main goal of this PR is to be able to bring up the search results with the spaces.

### CODE REVIEW

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and the Search results are displayed with starting and trailing spaces of search text in First Name, Last Name, Email and Weekly hours. 
For Search text box the spaces is cleared when typing or pasting, thus displaying the exact search results. The ignore space functionality works fine!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/2a81dcd9-03a1-478a-b1c5-5e7859d011a3

**Review by TXMO-dev — APPROVED** [review]
Great job! I checked everything, and it is working perfectly. Approval granted.

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/9dffe1c0-1d4d-4e5f-a790-c7dec6694524

**Review by Kavil-Jain-514 — DISMISSED** [review]
The trim() works well for all the fields.
image
image
image
image

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi Chris, 

I reviewed your changes, the search bars work as expected. I've checked these in dark mode as well.
image
image


They even work in conjunction with each other
image

I do have one concern: 

1. Please add a placeholder inside search boxes or an icon that signifies that the added boxes are to be used for searching. 

Apart from this, the functionality works great!

**Review by nathcarnevalli — DISMISSED** [review]
Hi Chris, worked well for me.
image

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected. 
Screenshot 2024-06-15 at 4 47 59 AM
Screenshot 2024-06-15 at 4 48 11 AM
Screenshot 2024-06-15 at 4 48 25 AM

**Review by tianyangL11 — APPROVED** [review]
I‘ve checkout everything.   It work as expected. Great job!
3338dc56680f3735a735f2b7b6f9395
730a4cd86b620d50105b015bd7e6f36

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
