### PR TITLE
Shihao - Unit Test for TimeZoneDropDown

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Unite test for `TimeZoneDropDown.jsx`

## Main changes explained:
- Add the unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test TimeZoneDropDown.test.js` to run the test
4. Verify that all 7 tests have passed

## Screenshots or videos of changes:
Screenshot 2024-01-08 at 14 11 34

### CODE REVIEW

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-16 at 12 28 11 AM

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-15 at 10 19 31 PM
All the test cases were successful. Excellent job!

**Comment by Lin1404** [comment]
All the tests have passed. Good job!
Screenshot 2023-12-16 at 4 41 30 PM

**Review by Lin1404 — DISMISSED** [review]

**Review by ljrirene — DISMISSED** [review]
The test passed on my side. Good work!

**Review by Alforoan — CHANGES_REQUESTED** [review]
All tests pass, but I have some suggestions.

1. Maybe a little more descriptive test description. Instead of "renders with default props," you can try "should render the time zone dropdown with default props."
2. Some edge cases such as when selected prop is not provided or filter prop is empty, or when time zones do not match the filter criteria.

image

**Review by vikrambadhan — DISMISSED** [review]
Hi, Great Job! I tested your PR and everything works as intended!

Week 17 - PR6

**Review by bienzguoa — CHANGES_REQUESTED** [review]
All test cases passed! One suggestion: if there are any error states or edge cases (such as an invalid selected value or empty timeZones object), please add tests for them.
Screenshot 2024-01-06 at 9 38 15 PM

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Review by Alforoan — COMMENTED** [review]
All tests pass and the descriptions look good. Nice! 

image

**Review by Alforoan — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
