### PR TITLE
EduardoV - create unit tests for the MembersAutoComplete component

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the MembersAutoComplete component to confirm whether it working as intended.

Screenshot_1

## Main changes explained:
- Export file MembersAutoComplete.jsx for the test component
- Create file MembersAutoComplete.test.js to do the unit tests

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install` to run this PR locally
4. open file src → tests → Teams → MembersAutoComplete.test.js
5. run `npm run test src/__tests__/Teams/MembersAutoComplete.test.js`

## Screenshots or videos of changes:

This is the result it's supposed to get:

Screenshot_2

If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by harshidad — APPROVED** [review]
All tests passed, everything worked as intended.

PR#1275

**Review by DavidC0126 — APPROVED** [review]
I tested the PR and it works as intended.
member

**Review by robertoooc — APPROVED** [review]
Hi @eduvarjaor, I tested your new unit test and it does seem correct and also passed all tests. Nice job !
 
Screenshot 2023-09-07 at 2 12 07 PM

**Review by ss23046 — APPROVED** [review]
LGTM, all tests passed
Screen Shot 2023-09-07 at 8 51 05 PM

**Review by Sssky-18 — APPROVED** [review]
Tested the code locally, and it passed the tests as expected.

PR#1275

**Review by vikrambadhan — APPROVED** [review]
Hi, Nice Job! I tested your PR and everything works as intended.

Week 2 - PR8

**Review by GaryB93 — APPROVED** [review]
Great work on testing the MembersAutoComplete component. I ran into one issue that is technically out of scope for this PR but it would be an easy fix. In running the tests I received a console.error related to "children in a list should have a unique 'key' prop. See image below.

Screenshot 2023-09-08 at 4 01 44 PM

**Comment by AnishPandita** [comment]
Hi, I ran the tests according to the guidelines and everything seems to be working well. There were no errors discovered.
Screenshot 2023-09-08 at 4 08 17 PM

**Review by luisarevalo21 — APPROVED** [review]
Hello @eduvarjaor
I tested your PR and works as intended. Great work!
Running the script provides 6 passed test. 
Screenshot 2023-09-08 at 7 49 46 PM

However, as @GaryB93 pointed out I also, get the unique key prop error. As stated unrelated to this PR.
Screenshot 2023-09-08 at 7 49 42 PM

**Review by zuhang2000 — APPROVED** [review]
Hi, I've tested your PR. All tests are passed. The test cases also look good to me. Good job!
Screen Shot 2023-09-09 at 9 31 44 PM

**Review by EdwinLauM — APPROVED** [review]
Hey @eduvarjaor! Tested and the test passes! Good job 

Screen Shot 2023-09-09 at 6 42 16 PM

**Review by gabi-lima — APPROVED** [review]
Well done Edu!
image

**Review by veronicacheng2 — APPROVED** [review]
Hi @eduvarjaor, I have tried running the test on my local environment and all tests passed.

image

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
