### PR TITLE
Shiwani lint fix for constants

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Lint fix for Constants folder `src/constants/*`

## Main changes explained:
- Removed the folder path from .prettierignore and .eslintignore
- Files that were fixed with lint --fix
- Added export default to timer.js, projects.js, team.js, userProjects.js, materialConstants.js

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as any user
4. check if the app is working properly
5. Check if any of the files in constants folder have any lint errors
6. Additionally, please check if there are any lint errors when you do `npx eslint src/constants/*`
7. Feel free to add any comments or screenshots of your test

## Screenshots:

Screenshot 2023-10-20 at 5 39 12 PM

### CODE REVIEW

**Comment by mounica-dingari-by** [comment]
Hi @Shiwani99 , I've tested your PR and it works as intended !

Screenshot from 2023-10-20 19-57-54

**Review by StrawberryCalpico — APPROVED** [review]
Hi, I tested your PR, the app works properly, and no error appears!

Screenshot 2023-10-21 at 12 22 21 AM

**Review by Cloid — APPROVED** [review]
Hi there.

I tested the following components:

- Tested various parts on the website:
   -  Timer buttons
   -  Updating information on separate user's profile page
   - Projects page; creating a project
   - Creating  a new user
   - Manually checked each .js file in constants folder
   - ran command and checked it again

Screenshot 2023-10-20 230201

Overall, everything works from what I've tested and checked.

**Review by DavidC0126 — APPROVED** [review]
Hi @Shiwani99 I tested it and it looks good to me.

lintfix

**Review by Iris-Song — APPROVED** [review]
Hi，I have reviewed your PR, it works as intended. Good job.
image

**Comment by RheaWu1212** [comment]
Hi I tested your PR, works as expected!

Screen Shot 2023-10-21 at 09 46 59

**Comment by AnishPandita** [comment]
Hey, I tested the updates and it seems to be running without any errors. The app functions without any issues. Checked the files for lint errors and everything looks good to me. Good Job!
Screenshot 2023-10-21 at 2 09 21 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended!

Week9 -PR4 (#1435)

**Review by malikjahanzaib — APPROVED** [review]
Hi @Shiwani99, I tested this PR, no lint errors and app functions normally. Nice job!!!

Screenshot:

Screenshot 2023-10-21 153904

**Comment by palakgosalia** [comment]
Hey, I tested this PR for lint issues but it did not get any errors. I also checked the app locally and it works as expected. Thank you

image

image

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-10-21 214205

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions. I have checked no files in constants folder have any lint errors.
Moreover, I also checked that no lint errors when I do npx eslint src/constants/*.
The app is also working correctly.

Screenshot 2023-10-22 at 12 48 45 AM

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
