### PR TITLE
Xiaoyu - Add editable role info and editable mouseover modal

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description
Screenshot 2023-07-19 at 6 40 56 PM
Screenshot 2023-07-25 at 10 53 43 AM
Screenshot 2023-07-25 at 10 54 15 AM
Screenshot 2023-07-25 at 10 54 31 AM
Screenshot 2023-07-25 at 10 55 08 AM
Screenshot 2023-07-25 at 10 56 20 AM

## Related PRS (if any):
This frontend PR is related to [#452](https://github.com/OneCommunityGlobal/HGNRest/pull/452) backend PR
…

## Main changes explained:
- Crete editable modal and info components
- create information.js for action, constants, inforeducer, informationService
- Create a readable modal in report page avoid re-render issues (content will changed based on the role info in the permission role info)
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
Login as Owner:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/76c4fc65-98aa-474f-92c6-6aa4dba8f396

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/354ef5e3-855a-43de-967b-14b4cdd75fcb
## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by ramyaram2092 — COMMENTED** [review]
Hello @20chen-7 
I tested both the front end and back end (PR452)(https://github.com/OneCommunityGlobal/HGNRest/pull/452)

**Observation**:
The end to end functionality works good. Good job 👍 

**Testing video as Owner:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/4c712204-cec7-4c47-81fe-63648e758dc1



**Testing video as Admin :**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/7d089807-c32f-474d-a228-7a2f151c31e2



**Testing video as Volunteer :** 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/2ac7ebdc-b929-498b-a9d6-bd436fe939c2



**Suggestions**:
I feel the information should look more like a pop up when the mouse hovers over the 'i' icon. for people who dont have edit access to the information
Currently it looks like a big  form  with  no edit access . Let me know your thoughts on this  

**Bug** : 
I see the same information that I updated through the profile page of owner in admin as well . Is that an expected behaviour ?
**Owner's profile page :** 
image

**Admin profile page :**  
image

**Comment by 20chen-7** [comment]
> Hi @20chen-7
> 
> You have done a great job! I have tested the PR and I have found the following inconsistencies: Also if these are expected behaviours, then please ignore.
> 
> 1. I saw that 'i' icon on Profile page shows same information for Owner and Administrator, so if I edit the 'i' icon information with Owner user, the information for Administrator is also edited. **(3.c.i > says that information should be for the user class that is selected , and hence not common)**
>    The image shows that the info is edited by Owner, but same is visible to Administrator.
>    Screenshot 2023-07-19 at 9 44 17 PM
> 2. Information shown on the Profile page is different from the info shown on the Permission Management page.
>    The video below shows that information shown for Owner on profile page is different from info on Permission page.
> 
>  Screen.Recording.2023-07-19.at.9.38.22.PM.mov 
> Apart from that the functionality that the 'i' is visible to only Admin and Owner and not to Volunteer is working fine.
> 
>  Screen.Recording.2023-07-19.at.9.41.53.PM.mov 
> Please let me know if you have any questions.

Visibility will implement in the next PR.

**Comment by 20chen-7** [comment]
> Hello @20chen-7 I tested both the front end and back end (PR452)([OneCommunityGlobal/HGNRest#452](https://github.com/OneCommunityGlobal/HGNRest/pull/452))
> 
> **Observation**: The end to end functionality works good. Good job 👍
> 
> **Testing video as Owner:**
> 
>  PR-1025-Owner.mp4 
> **Testing video as Admin :**
> 
>  PR-1025-Admin.mp4 
> **Testing video as Volunteer :** https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/2ac7ebdc-b929-498b-a9d6-bd436fe939c2
> 
> **Suggestions**: I feel the information should look more like a pop up when the mouse hovers over the 'i' icon. for people who dont have edit access to the information Currently it looks like a big form with no edit access . Let me know your thoughts on this
> 
> **Bug** : I see the same information that I updated through the profile page of owner in admin as well . Is that an expected behaviour ? **Owner's profile page :** image
> 
> **Admin profile page :** image

It is not a bug, owner is the only role to edit the information, and visibility will be implemented in the next PR.(admin is supposed to see this information)

**Comment by one-community** [comment]
image
This link on your PR doesn’t lead to where it should for me. Leads here: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/452 instead of https://github.com/OneCommunityGlobal/HGNRest/pull/452

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @20chen-7 

I tested your PR and works as intended great job!
Owner is able to view and edit the description on their account, in permission mangement and on the weekly reports page. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/1b074f90-05b9-45d0-a54b-639b454bfb5f

Admin can view it in all three locations but cannot edit it.
Volunteer cannot see it and therefore cannot edit the text. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/f0a75efb-1200-4e5c-8000-27fca46ce58a

However, a couple adjustments I would make.
1. Clicking directly into the text box should allow the owner to edit it directly, instead of clicking the edit button to edit the text. 
2. When editing the text and once you've saved it, the still says "save" instead of switching back to edit
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/b52dcb70-7a45-4e7b-8145-772cb7418081

Overall great work.

**Review by freecode23 — CHANGES_REQUESTED** [review]
For backend I checked out to this branch. Is this correct ?https://github.com/OneCommunityGlobal/HGNRest/pull/452

Encountered the same inconsistencies as shiva2096 .
In addition to those I also found these (possible) bugs:

**Bug 1:**
Owner / Admin Login —>  Weekly Summaries Reports:
Problem encountered: each person will have different info (not each role)
Video description (please turn audio on)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/900205f4-4429-4a89-a6e9-4cf94557cac5

**Bug 2:**
Volunteer Login —> Reports —> Weekly Summaries Reports:
Problem encountered: No “I” blue icon on each person
Screenshot 2023-07-20 at 1 07 07 PM


Question:
Shouldn’t we have the “I” icon as well? 
Although I just saw in the [doc](https://docs.google.com/document/d/1n5NIb3dbiSrIRuOG1ZCwt34pEP1poqddCv1guaQml88/edit) that this feature will be taken by Edwin

**Comment by 20chen-7** [comment]
> For backend I checked out to this branch. Is this correct ?[OneCommunityGlobal/HGNRest#452](https://github.com/OneCommunityGlobal/HGNRest/pull/452)
> 
> Encountered the same inconsistencies as shiva2096 . In addition to those I also found these (possible) bugs:
> 
> **Bug 1:** Owner / Admin Login —> Weekly Summaries Reports: Problem encountered: each person will have different info (not each role) Video description (please turn audio on)
> 
>  Screen.Recording.2023-07-20.at.1.01.44.PM.mov 
> **Bug 2:** Volunteer Login —> Reports —> Weekly Summaries Reports: Problem encountered: No “I” blue icon on each person Screenshot 2023-07-20 at 1 07 07 PM
> 
> Question: Shouldn’t we have the “I” icon as well? Although I just saw in the [doc](https://docs.google.com/document/d/1n5NIb3dbiSrIRuOG1ZCwt34pEP1poqddCv1guaQml88/edit) that this feature will be taken by Edwin

**Review by BaileyM96 — CHANGES_REQUESTED** [review]
Good evening @20chen-7, I recently reviewed your PR and have a few issues that need to be looked at. Otherwise the new feature is coming along great! Please let me know if you have any questions.

## Issues

1. When adding editable role info as an owner the information does not carry over to the "permissions management" tab, or to the "Weekly Summaries report page".
2. When you edit the role info as an owner the information will also display if you login as an admin in the "Basic Information" tab as admin.
I will show what some of these issues look like in the video walkthrough section.

## Video Walkthrough
This shows the owner info not carrying over to the "permissions" tab.

[PR #1025 Add Editable role info for _Owner_ Issue.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/fe5e5a13-69c1-4c45-9450-063e33d5efc4)

This shows the editable owner info carried over the admin page, and the permissions tab for admin is empty as well.

[PR #1025 Add editable role info _Admin_ Issue.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/9ac619ad-b73f-4389-9001-096cc2578858)

This shows when you login as a volunteer the info button is not visible since the volunteers do not have permissions to edit the role.

[PR #1025 Add editable role info _Volunteer_.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/9d61e650-f52c-4d87-b43f-28ad535568f8)

## Screenshots

This image shows that information does not save to weekly summaries report section as a owner

PR #1025 Error

**Review by eduvarjaor — COMMENTED** [review]
I tested this PR as a volunteer and administrator. Both work well.

Volunteer:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/3fce69e6-d2cc-40f7-bfd5-8039634a0325


Administrator: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/bdc7aa7c-a99a-4b16-8a37-1e2a9cd12fe0


But when I try to change to an owner account, this option doesn't appear to me.
Screenshot_1

I tried to create a new account but didn't appear the owner account option.
Screenshot_2

Maybe I'm doing something wrong, but as the other 2 users-classes working, probably the owner account is working too.

**Review by winghojackyli — COMMENTED** [review]
### Testing
I tested the PR and it works great. 

Owner can read and edit the mouseover info. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/bb80c390-f2e2-4a5a-9f50-7aaa3e4a6a72

Admin can only read the mouseover info. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/c3081115-f546-4e63-8c29-efd769743879

The info logo is not shown in volunteer role, therefore, volunteer cannot read and edit the mouseover info. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/c50b6cf1-edb6-4acc-99d3-662def904bb1

### Adjustments
- I agree with @luisarevalo21 , making the text box editable by clicking the text box itself. 
- After saving the changes, the modal should disappear. 
I think the modal should not disappear, as we need to double-check whether the content is correct or not. If the modal is just closed, how do you know whether there is a typo?

**Review by DavidC0126 — COMMENTED** [review]
Hi @20chen-7,
I tested the PR with Owner, Admin and Volunteer roles. All of them work as described.

-  Owner is able to edit the content and the blue icon is visible.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/f950d655-bfa0-4bdb-bf7c-444c479864e0

-  Admin is able to see the icon and content, but cannot modify the text.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/ecc9e599-0cd7-40b1-ae1f-f1d2a8aee889

-  Finally, Volunteer is not able to see the icon and edit the text content.
volunteer_pr1025_1
volunteer_pr1025_2

**Comment by 20chen-7** [comment]
> I tested this PR as a volunteer and administrator. Both work well.
> 
> Volunteer:
> 
>  volunteer.mp4 
> Administrator:
> 
>  adm.mp4 
> But when I try to change to an owner account, this option doesn't appear to me. Screenshot_1
> 
> I tried to create a new account but didn't appear the owner account option. Screenshot_2
> 
> Maybe I'm doing something wrong, but as the other 2 users-classes working, probably the owner account is working too.

You could request that from Jae

**Comment by 20chen-7** [comment]
> ### Testing
> I tested the PR and it works great.
> 
> Owner can read and edit the mouseover info.
> 
>  HGN.APP.-.Google.Chrome.2023-07-24.16-01-34.mp4 
> Admin can only read the mouseover info.
> 
>  HGN.APP.-.Google.Chrome.2023-07-24.16-03-18.mp4 
> The info logo is not shown in volunteer role, therefore, volunteer cannot read and edit the mouseover info.
> 
>  HGN.APP.-.Google.Chrome.2023-07-24.16-04-17.mp4 
> ### Adjustments
> * I agree with @luisarevalo21 , making the text box editable by clicking the text box itself.
> * After saving the changes, the modal should disappear.
 I think the modal should not disappear, as we need to double-check whether the content is correct or not. If the modal is just closed, how do you know whether there is a typo?

**Comment by 20chen-7** [comment]
> ### Testing
> I tested the PR and it works great.
> 
> Owner can read and edit the mouseover info.
> 
>  HGN.APP.-.Google.Chrome.2023-07-24.16-01-34.mp4 
> Admin can only read the mouseover info.
> 
>  HGN.APP.-.Google.Chrome.2023-07-24.16-03-18.mp4 
> The info logo is not shown in volunteer role, therefore, volunteer cannot read and edit the mouseover info.
> 
>  HGN.APP.-.Google.Chrome.2023-07-24.16-04-17.mp4 
> ### Adjustments
> * I agree with @luisarevalo21 , making the text box editable by clicking the text box itself.
> * After saving the changes, the modal should disappear.

I think the  save btn worked as a way to double-check the content. If Owner has some typos?

**Comment by 20chen-7** [comment]
> Hello @20chen-7
> 
> I tested your PR and works as intended great job! Owner is able to view and edit the description on their account, in permission mangement and on the weekly reports page. https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/1b074f90-05b9-45d0-a54b-639b454bfb5f
> 
> Admin can view it in all three locations but cannot edit it. Volunteer cannot see it and therefore cannot edit the text.
> 
>  Screen.Recording.2023-07-19.at.8.31.52.PM.mov 
> However, a couple adjustments I would make.
> 
> 1. Clicking directly into the text box should allow the owner to edit it directly, instead of clicking the edit button to edit the text.
> 2. When editing the text and once you've saved it, the still says "save" instead of switching back to edit
>    https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/b52dcb70-7a45-4e7b-8145-772cb7418081
> 
> Overall great work.

fixed

**Review by BaileyM96 — APPROVED** [review]
Good evening sorry for taking so long to get back to you @20chen-7 .

I reviewed your changes and based on the directions and functionality everything works great!

## Videos

Owner tests of basic profile page

[PR #1025 Add editable role info and editable mouseover modal (Owner).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/a747a15f-1aa3-46bb-b7ae-941d6264939e)

Owner Permissions Management

[PR #1025 Add editable role info Permissions management(owner).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/e40ea721-a2c3-4849-8889-b6b7d565bfa2)

Admin Weekly Summaries Management

[PR #1025 Add editable role info Weekly Summaries (Admin).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/b6c09e5e-9529-49b8-9e4d-f39a1ec2ce6e)

Volunteer basic profile page

[PR #1025 Add editable role Info (Volunteer).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/5ae70eb4-3b5d-4728-9dd8-91bf6a3b8c1f)

**Review by ThapeloMasasa — DISMISSED** [review]
Tested the PR and it works as expected in the description
Screenshot 2023-08-04 at 9 13 18 AM
Screenshot 2023-08-04 at 9 24 24 AM

Screenshot 2023-08-04 at 9 13 48 AM

**Review by veronicacheng2 — DISMISSED** [review]
Hi @20chen-7, I have tested the PR and everything works as intended.

Test 1 (Mouseover role on summaries report page)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/639da064-b973-47f9-9952-50720bda97c1

Test 2 (Editable Modal on user profile page and permission management page)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/c8485323-0bb3-440b-9d8f-28a8724843d0

**Review by TheDescendant39 — COMMENTED** [review]
Hi @20chen-7, I logged-in as Owner (Video 1) and Volunteer. I was able to mouseover for information and also able to edit the modal. However, I was not able to edit information modal in weekly summary reports as owner. Is it intentional?

Video1:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/a08459a9-99ff-4cfb-8ad1-2ac5a6ac3277

Video 2:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/bef99d72-501e-414f-8b28-3bec842b469c

**Comment by Jiyuanxia** [comment]
Hi @20chen-7, I have viewed your pull request and tested it, it works as you intended. Well done.
Screenshot 2023-08-15 163507
Screenshot 2023-08-15 163709
Screenshot 2023-08-15 163721
Screenshot 2023-08-15 163750
Screenshot 2023-08-15 163810
Screenshot 2023-08-15 163852

**Comment by AuroraLovesWhales** [comment]
Hi @20chen-7. I have tested your PR and the edit functionality as Owner works as intended. However, I do have some confusions regarding the functionality's design choice here.

1. When I log in as Owner and edit a user class's info from the Permission Management page, the change is not reflected in the Profile Page → Basic Information page for that user class. Likewise, when I edit a user class's info from the Profile Page → Basic Information page, the change is not reflected in the Permission Management page for that user class. What is the purpose of this inconsistency if I may ask? Or maybe I'm not understanding the task requirement correctly.

eg. Edit info for Manager class:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/71576818-cef3-4dbe-b0fe-d85796e8d386

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/03decc37-e8e4-4dea-ae50-9c883d3abcac

2. In the task description, it states the following:
image
But right now, mousing over “i” shows all the user classes.

**Review by winghojackyli — COMMENTED** [review]
Hi @20chen-7 , I've tested the PR with owner, admin and volunteer accounts. 

### Owner
Owner can edit mouseover modal text on user profile page and permissons management page. The change from permissons management page reflects on weekly summary report page. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/010bb1da-535b-4478-b96e-f7745c7e9528

### Admin
Admin can only view mouseover modal text on user profile page, permissons management page and weekly summary report. Content cannot be changed  by admin. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/3a57969d-bf74-4aee-86c4-603787839215

### Volunteer
Volunteer cannot view or edit mouseover modal text on user profile page. It cannot visit the permissions management page. But it's a bit strange on the "i" on the weekly summary report page. Volunteer cannot see the "i" on some users (e.g. owner, admin, mentor) on the weekly summary report page. It turns to "Please Input Informations first!" 

If volunteer should be permitted to see modals for volunteers and managers only, is it better to show nothing for other roles instead of showing "Please Input Informations first!"? 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/cb180aa2-e347-45ef-9ee7-c523d3a41efa

comparison

**Comment by 20chen-7** [comment]
> Hi @20chen-7. I have tested your PR and the edit functionality as Owner works as intended. However, I do have some confusions regarding the functionality's design choice here.
> 
> 1. When I log in as Owner and edit a user class's info from the Permission Management page, the change is not reflected in the Profile Page → Basic Information page for that user class. Likewise, when I edit a user class's info from the Profile Page → Basic Information page, the change is not reflected in the Permission Management page for that user class. What is the purpose of this inconsistency if I may ask? Or maybe I'm not understanding the task requirement correctly.
> 
> eg. Edit info for Manager class:
> 
>  Screen.Recording.2023-08-15.at.6.43.14.PM.mov 
>  Screen.Recording.2023-08-15.at.6.50.34.PM.mov 
> 2. In the task description, it states the following:
>    image
>    But right now, mousing over “i” shows all the user classes.

This is based on the requirement to show all user class information and I have shown this to Jae

**Comment by 20chen-7** [comment]
> Hi @20chen-7 , I've tested the PR with owner, admin and volunteer accounts.
> 
> ### Owner
> Owner can edit mouseover modal text on user profile page and permissons management page. The change from permissons management page reflects on weekly summary report page.
> 
>  HGN.APP.-.Google.Chrome.2023-08-16.15-38-49.mp4 
> ### Admin
> Admin can only view mouseover modal text on user profile page, permissons management page and weekly summary report. Content cannot be changed by admin.
> 
>  HGN.APP.-.Google.Chrome.2023-08-16.15-40-45.mp4 
> ### Volunteer
> Volunteer cannot view or edit mouseover modal text on user profile page. It cannot visit the permissions management page. But it's a bit strange on the "i" on the weekly summary report page. Volunteer cannot see the "i" on some users (e.g. owner, admin, mentor) on the weekly summary report page. It turns to "Please Input Informations first!"
> 
> If volunteer should be permitted to see modals for volunteers and managers only, is it better to show nothing for other roles instead of showing "Please Input Informations first!"?
> 
>  HGN.APP.-.Google.Chrome.2023-08-16.15-41-48.mp4 
> comparison

The pop-up model could set visibility, which you could change the visibility.

**Comment by AuroraLovesWhales** [comment]
> > Hi @20chen-7. I have tested your PR and the edit functionality as Owner works as intended. However, I do have some confusions regarding the functionality's design choice here.
> > 
> > 1. When I log in as Owner and edit a user class's info from the Permission Management page, the change is not reflected in the Profile Page → Basic Information page for that user class. Likewise, when I edit a user class's info from the Profile Page → Basic Information page, the change is not reflected in the Permission Management page for that user class. What is the purpose of this inconsistency if I may ask? Or maybe I'm not understanding the task requirement correctly.
> > 
> > eg. Edit info for Manager class:
> > Screen.Recording.2023-08-15.at.6.43.14.PM.mov
> > Screen.Recording.2023-08-15.at.6.50.34.PM.mov
> > 2. In the task description, it states the following:
> > image
> > But right now, mousing over “i” shows all the user classes.
> 
> This is based on the requirement to show all user class information and I have shown this to Jae

I see! All the other functionalities work as intended. I will go ahead and approve this PR right now. Great work!

**Pull request merged**
