### PR TITLE
Jerry - See Only Weekly Summaries Reports Tab

### PR DESCRIPTION
**Pull request by jerryren527**
# Description
see only weekly summaries reports tab - description

The main motivation of this pull request is to allow an Owner account to assign the "_See Only Weekly Summaries Reports Tab_" to an account that does not have that permission by default (e.g., a Volunteer account).

## Related PRS (if any):
None

## Main changes explained:
- Conditionally render `Reports->Weekly Summaries Reports` option in the header for a Volunteer account that had the “_See Only Weekly Summaries Reports Tab_” permission added by an Owner account.
- Similarly, an Owner account can remove a Volunteer account’s “_See Only Weekly Summaries Reports Tab_” permission and the `Reports->Weekly Summaries Reports` option in the header will no longer be visible/accessible.
- Fixed permission title to “_See Only Weekly Summaries Reports Tab_” in `UserRoleTab.jsx`
- Fixed typo in `languages/en/ui.js` -- “Weekly Summaries Report” was missing a ’s’ in “Report”. It is now “Weekly Summaries Reports"
- Added `RoutePermissions.seeOnlyWeeklySummariesReports` to the `routePermissions` prop of the `ProtectedRoute` component (`src/routes.js`).
- Added “seeOnlyWeeklySummariesReports” key-value pair to `RoutePermissions` in `src/utils/routePermissions.js`
- Updated the title on the Permissions Management Page to "_See Only Weekly Summaries Reports Tab_" and updated the "i" description too to: _Makes the "Other Links" -> "Reports" button and ONLY the "Weekly Summaries Reports" option appear/accessible_.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Log in as Owner -> Other LInks -> Permissions Management -> Manage User Permissions
4. Enter the username of an account that does not have the “See Weekly Summary Reports Tab” permission by default (i.e., a Volunteer account). Click on Submit.
5. Login the Volunteer account (if already logged in, make sure to log out and log back in). The “Reports” button should appear with ONLY the “Weekly Summaries Reports” option visible/accessible.
6. The Owner account can also remove the “See Weekly Summary Reports Tab” permission. Click on Submit. Log into the Volunteer account and see that the "Reports" button is no longer visible/accessible.
7. **Note**: There is a typo in “Weekly Summaries Report” option where there is a missing ’s’ in “Report”. It should now be “Weekly Summaries Reports”. Also the title on the Permissions Management Page to is updated to "_See Only Weekly Summaries Reports Tab_". And the "i" description is also updated to: _Makes the "Other Links" -> "Reports" button and ONLY the "Weekly Summaries Reports" option appear/accessible_.

## Screenshots or videos of changes:

Development Branch:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/3c8c7a66-b723-4118-892c-0a747bde6e7d

Current Branch:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/eba47976-d7fd-4842-bfee-13cf0beec8e4

## Note:
Adding and removing the "_See Only Weekly Summaries Reports Tab_" to/from an account that has the permission to access the Weekly Summaries Reports page by default does not have any affect. This is because the code in this pull request conditionally renders the "_Weekly Summaries Reports_" tab based on whether or not the "seeOnlyWeeklySummariesReports" permission is present in `userProfiles.permissions.frontPermissions`. Since a Volunteer account does not have the permission to view the Weekly Summaries Reports page by default, this pull request will check if "seeOnlyWeeklySummariesReports" is inside `userProfiles.permissions.frontPermissions` and grant the volunteer account access to the Weekly Summaries Reports page.

**Edit (Aug 29, 2023)**: Due to a general problem, your Owner account may have the “Other Links” button in the header disappeared. You can try Empty Cache and Hard Reset (instructions in the screenshot below):

Screenshot 2023-08-29 at 3 07 09 PM

Or create a new Owner account. I had issues creating new accounts in localhost, so I created a new Owner account in the HGN dev app. Hopefully your new Owner account will have the “Other Links” button in the header.

### CODE REVIEW

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @jerryren527 
I tested your PR but unfortunately it crashes for me. 

I am running Node 14.17.6 and working on the development backend. 
When I log in as an owner and adjust the volunteers permission. I log into the volunteer account and I am able to view the weekly summary tab. However, once I select the link the app waits then crashes. 

See video for errors. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/24f3287d-be53-4acd-a84c-047eb23d35cc

**Comment by Arsamat** [comment]
Tested after giving permission to a volunteer user and had a similar issue. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67019552/26e1baa3-9d1f-495d-ab2d-491e188a6038

**Comment by jerryren527** [comment]
> Hello @jerryren527 I tested your PR but unfortunately it crashes for me.
> 
> I am running Node 14.17.6 and working on the development backend. When I log in as an owner and adjust the volunteers permission. I log into the volunteer account and I am able to view the weekly summary tab. However, once I select the link the app waits then crashes.
> 
> See video for errors.
> screen-recording-2023-08-27-at-82507-pm_xxiiOLQU.mov

Hello @luisarevalo21 ,

Thank you for your review! From watching your screen recording, I realized that I should have removed a redundant permission label. See how you clicked on "See Weekly Summary Reports Tab" instead of "See Only Weekly Summary Reports Tab" in the permissions management modal. So I removed "See Weekly Summary Reports Tab" from the modal. Please try again by clicking on "See Only Weekly Summary Reports Tab" in the modal. 

Screenshot 2023-08-28 at 3 07 29 PM

Please pull this branch's latest commit. Then you may need to either create a new volunteer account, Or find the current volunteer account in the MongoDB database and manually remove any items in `permissions.frontPermissions`.

**Comment by Haoj1** [comment]
@jerryren527 Weekly summary reports first time loaded as intended after acquiring permission, but sometimes memory leak issues happened in summary reports.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/35117a0f-f883-4ef5-a93c-81166a9497c5

**Review by robertoooc — DISMISSED** [review]
Hi @jerryren527, I tested your branch and it performed as expected. I was able to assign the see only weekly summaries report tab to another account that didn't previously have access to view. In the video below it shows it's functionality, although the weekly summaries report did take a long time to load it did, and I was able to remove the access to that tab as well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/4de07eb3-4c2b-480d-83c1-f544e1aa6928

**Review by yurisokolovicz — COMMENTED** [review]
Dear @jerryren527 

Unfortunatelly I am having the ''other links'' dissapearing issue. This was a general problem related to the  PR 991. I tried to Empty the Cache and Hard Reload but still with this problem.

Screenshot 2023-08-29 143700

**Comment by gabi-lima** [comment]
Unfortunately for me, I cannot access the Weekly Summary Reports page.

image

**Comment by Jiyuanxia** [comment]
Hello, @jerryren527. Despite attempting to clear the cache and create another owner account through the development app, I am still unable to view the tab for other links.

**Review by Haoj1 — CHANGES_REQUESTED** [review]
@jerryren527 I give the permission to a volunteer user but still denied the the access to the weekly summary reports. The Reports tap displays correctly tho. See the error in console 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/bf20c2cb-b152-4778-8ad7-c02997cf905e

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Tested functionality of adding permission to seeOnlyWeeklySummariesReport and it works. It does take a long time for the Weekly Summaries Report page to load and that page actually never loaded for me. I know there was a fix for the loading speed for this page so maybe this pull request doesn't have the most recent fix for that or it was reverted.

Also, I was kind of expecting the "i" accessibility info to be in the modal as well, instead of having to go back to the different role permissions to see it. I think that you should also be able to see the accessibility "i"s when accessing the "Manage User Permissions" modal.

Screenshot 2023-09-01 at 1 08 19 PM

Another thing I saw was the semi-colon randomly on the "Permissions Management Page" that needs to be removed.

Screenshot 2023-09-01 at 12 26 59 PM

**Review by belagaam — COMMENTED** [review]
I tested the PR as per the instructions. I got an error after I add permission to one of the users and clicked Save. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/58e43a0d-fd6a-4bc3-8787-95bba608ceeb

**Review by winghojackyli — DISMISSED** [review]
Hi @jerryren527 , I've tested the PR and it works as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/2eba8e8b-144a-437e-981c-c8dbc8855ee0

**Comment by Shubhu0** [comment]
Tested PR, working as intended

**Review by Shiwani99 — CHANGES_REQUESTED** [review]
Hi,
I tested your PR. I am able to see reports tab when I set permissions to volunteer, but the problem is that when I click on weekly summaries tab in volunteer, it does not load the page. I'm attaching a screen recording of what is happening in my end.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/6bac25fe-a405-4af5-bb37-9fdf764c00c1

**Review by Alforoan — CHANGES_REQUESTED** [review]
Editing permission did not seem to do anything.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/9a4cf38f-bf3c-4a6f-93b3-446b84087340

**Comment by jerryren527** [comment]
Thank you all. I’m closing this PR as another developer has already addressed the changes it aimed to make. Please see refer to this [google sheet](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit?usp=sharing).

**Pull request closed without merging**
