### PR TITLE
Jiangwei-Apply Tasks Tab time log format to the individual timelogs tabs2

### PR DESCRIPTION
**Pull request by Jiangwei-shi**
# Description
Please include the exact bug/functionality description and a summary of the changes/ related issues. Please also include any other relevant motivation and context:
Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):

…

## Main changes explained:
- Add 72+ button in the timelog
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to dashboard→ Tasks→ task→…
5. verify function “A” (feel free to include screenshot here)

## Screenshots or videos of changes:
Owner:
image

Volunteer:
image

### CODE REVIEW

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @Jiangwei-shi 

I tested your PR and unfortunately I get a 400 not found error code. 
I logged in as an admin and owner and both accounts receive the error code when clicking the 72+Hour button. 

I am running Node 14.17.6 and checked into the development backend. 

See video for error. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/bfe9f217-b5bf-4f81-8f05-24e2c5e807bb

**Comment by Arsamat** [comment]
@Jiangwei-shi Tested your code and ran into a similar issue. Getting errors after clicking 72+ button and trying to see individual's tasks. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67019552/22cbad2a-2292-4d6d-a5f6-d01bf79df93c

**Review by yurisokolovicz — COMMENTED** [review]
Dear @Jiangwei-shi 

I have identified the same errors in the console as those previously mentioned. Kindly review the video for further clarification.



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/ecea48dd-79ee-4a40-ac9b-5bc3cb21f33d

**Review by tsunami776 — COMMENTED** [review]
I encountered the same browser console error as others. I get a "400 bad request" when I click the 72h+ button.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/58c94106-ca5e-4ad6-a0fa-7fe52ed2fb81

**Review by robertoooc — CHANGES_REQUESTED** [review]
Hi @Jiangwei-shi, I tested your branch and just like everyone else I am also having issues with it presenting many browser errors. It continues to throw a status 400 request like seen below.
Screenshot 2023-08-29 at 2 50 58 PM

**Comment by DavidC0126** [comment]
Hi @Jiangwei-shi  I also encounter same issue as others on this PR, when I click on the 72+ button, I got not found errors. I tried to refresh the page and click again, there was a time I did not get the error but after the dashboard loading, the error showed up again.

error_72+

**Comment by Jiyuanxia** [comment]
Hi @Jiangwei-shi , I met the same issue while I was reviewing your pull request.

Screenshot 2023-08-30 170242

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Great work! Team Member Tasks time logs can now be filtered with the 72hrs+ button. I also received the above errors. However, the development branch also has these errors so I don't think it has anything to do with this pull request. The only difference I can see is that the development branch doesn't showcase these errors as ribbons on the frontend.

After further research into ERR_INSUFFICIENT_RESOURCES, it seems like these errors are indicating the browser is running out of memory due to the amount of AJAX calls the app is making to retrieve each task. I haven't gone too deep into the code but seems like the app might be fetching each task separately and not all at once? Not sure if this is actually the case.

Screenshot 2023-08-30 at 5 29 03 PM

Screenshot 2023-08-30 at 4 36 29 PM

Code fixes: I did notice a little something in reviewing the code and has nothing to do with the current changes, but I noticed there was an async/await put before a dispatch call in TeamMemberTasks.jsx and from what I understand Redux.dispatch is synchronous so there's no need for it. SEE IMAGE BELOW

Screenshot 2023-08-30 at 4 59 37 PM

**Comment by iTvX** [comment]
The function worked great except showing 400 error.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/1288e4d4-5e7f-4a7f-bed5-862efaea5023

**Comment by Shreyj14** [comment]
Hi @Jiangwei-shi  the code still gives the same error as everyone else above.
Screenshot 2023-09-02 7 01 25 PM

**Comment by Jiangwei-shi** [comment]
According to the comments on the PR, the 72+ option appears to display correctly when clicked by the user. However, there is a 400 error that shows up in the console. I also tested this on the current develop branch by clicking on 24h, and it similarly produces a 400 error. I've recorded a video demonstrating my tests. So it seems that the 400 error is a legacy issue, not something introduced by my branch. The objectives for my branch have been met, as you can see the status before 72+ is available.

**Comment by Jiangwei-shi** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/676d67dc-651d-4bd2-a863-2f8241e30f97

**Review by yaow62023 — CHANGES_REQUESTED** [review]
Hi, I have tested your PR. As the comments above the "72+" tab have shows the error message when click it.  All the other tab also have the 400 error,  but the "72+" tab have the pop up message "Unexpected error". Check the video below for details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/5de16254-e9cd-4cd9-beb0-b6e9c0cb2be2


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/ae379ed7-24c2-4ec8-afb9-1511887ecff7

**Review by zuhang2000 — COMMENTED** [review]
Hi Jiangwei! I tested your PR following your instructions. The "unexpected error" pop out when I click 72hours. Please correct me if this is not related to this PR. But this is definitely a problem that should be fixed.

Moreover, I've been experiencing extreme lag on the "Task" tab. I have a suggestion that might be useful to optimize this problem. Please considering adding paging, like page 1, page2, etc. In this way, the tasks would not be fetched all at once.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/c349b8ac-aa90-4752-83bb-64167a74dd57

**Review by GaryB93 — DISMISSED** [review]
The intended functionality of filtering timelogs by when they were submitted has been met. The current 400 error does seem to be a legacy issue and is present on the current development branch.

**Review by Haoj1 — COMMENTED** [review]
@Jiangwei-shi You changes work as intended. However, I have the same 404 error as other mentioned above. See video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/d20501e1-4b5e-4dd3-a455-1a653c0464cd

**Comment by Jiangwei-shi** [comment]
If I set the 72+ button from 72h to the maximum slot before the legacy issue has been solved. It will still report the unexcepted error. In order to avoid this occurs. I set 72+ actually 96 hours. the unexcepted error will not exist.

**Review by yurisokolovicz — APPROVED** [review]
Thank you!

**Review by harshidad — CHANGES_REQUESTED** [review]
I also encountered the same browser console error, "400 bad request" when I click the 72h+ button.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/02014547-98be-4735-afed-098b0035869f

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Aside from the 400 error which is a legacy issue, it seems the filter functionality of the different timelog buttons are inoperable. I went ahead and created a timelog to test the functionality but it seems like the buttons are no longer filtering. Unless I'm misunderstanding what they should be doing, please advise.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/d756f127-bc13-4cdb-ae1f-5e897578052a

**Comment by AnishPandita** [comment]
Hey, the PR is throwing error for me as well on clicking the 72+ hours button.
Screenshot 2023-09-08 at 7 36 28 PM

**Comment by Jiangwei-shi** [comment]
> 

the 400 error is a legacy issue.

**Comment by Jiangwei-shi** [comment]
> Aside from the 400 error which is a legacy issue, it seems the filter functionality of the different timelog buttons are inoperable. I went ahead and created a timelog to test the functionality but it seems like the buttons are no longer filtering. Unless I'm misunderstanding what they should be doing, please advise.
> 
>  Screen.Recording.2023-09-07.at.1.38.10.PM.mov

when you created a time log. You can see it in 24h, 48h, 72h, 72h+. Only 24 hours later. you will not see your timelog in 24h.

**Comment by GaryB93** [comment]
> > Aside from the 400 error which is a legacy issue, it seems the filter functionality of the different timelog buttons are inoperable. I went ahead and created a timelog to test the functionality but it seems like the buttons are no longer filtering. Unless I'm misunderstanding what they should be doing, please advise.
> > Screen.Recording.2023-09-07.at.1.38.10.PM.mov
> 
> when you created a time log. You can see it in 24h, 48h, 72h, 72h+. Only 24 hours later. you will not see your timelog in 24h.

Upon reviewing this branch knowing the intended functionality, I was still unable to view a timelog with the timelog buttons. I had submitted a timelog on Sept 7 and was unable to view it with any of the timelog buttons as it should show up in one of the filters as it has been longer than 24 hours.

Screenshot 2023-09-10 at 12 08 17 PM
Screenshot 2023-09-10 at 12 15 33 PM

**Review by eduhorta — APPROVED** [review]
Working as expected.
Great job! 👍 
image

**Comment by Shubhu0** [comment]
Working as expected. Good job!

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Unable to confirm what I need to test due to no instructions whatsoever provided in the pull request.

**Comment by Lin1404** [comment]
Hi @Jiangwei-shi , I have tested your PR but it showed error after I clicked 72h+ button. Do we miss any backend change?

PR1183_1

**Pull request closed without merging**
