### PR TITLE
Xiao update shadow consistency throughout app

### PR DESCRIPTION
**Pull request by AuroraLovesWhales**
# Description
image

## Main changes explained:
Added missing shadow style for buttons throughout app by applying style={boxStyle} to the buttons

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as owner/admin user
4. check that the main buttons throughout the app has shadow style applied to them

## Screenshots or videos of changes:
Other Links -> Projects -> click on the "WBS" button for any project
image

Other Links -> Projects -> click on the "Members" button for any project -> on the right side of "Find User" search tab, click "All"
Pasted Graphic 1

User Profile -> Change Photo -> update a photo that exceeds 50KB
Pasted Graphic 3

Weekly Summaries -> Move This Summary -> choose a different week
Pasted Graphic 4

Weekly Summaries
Pasted Graphic 5

Dashboard -> Team Member Tasks -> click on the red bell next to a task
Pasted Graphic 6

Leaderboard -> click on the dot to the left of the username
Pasted Graphic 7

Dashboard -> Report App Bug
Pasted Graphic 8

Leaderboard -> click on the info icon next to “Note: You are currently invisible to the team(s) you are on. ”
Pasted Graphic 9

Tasks and Timelogs -> Current Week Timelog -> click the trash icon for one of the time entries
Pasted Graphic 10

User Profile -> switch to a smaller screen size
Pasted Graphic 15

User Profile -> Basic Information
Pasted Graphic 11

User Profile -> Volunteering Times
Pasted Graphic 12

User Profile -> Teams
Pasted Graphic 13

User Profile -> "Select Featured" button (for badges)
Pasted Graphic 16

Log in as Owner -> Permission Management
Pasted Graphic 18

## Note
Please check throughout the app to make sure the style stays consistent.
In the future, in case you need to add any new buttons for a functionality, please import { boxStyle } from 'styles' and apply the style to the new buttons.

### CODE REVIEW

**Review by joyceiphone — APPROVED** [review]
Checked the css changes of the places indicated in this PR. LGTM.

**Comment by winghojackyli** [comment]
I tested the PR and the followings works perfectly. 

image

image

image

image

image

image

image

image

image

image

image

image

image

image

However, the "Mark as read" button did not appear in Dashboard -> Team Member Tasks -> Red bell 

image

**Review by winghojackyli — COMMENTED** [review]
I tested the PR and the followings works perfectly. 

image

image

image

image

image

image

image

image

image

image

image

image

image

image

However, the "Mark as read" button did not appear in Dashboard -> Team Member Tasks -> Red bell 

image

**Review by yaow62023 — APPROVED** [review]
All buttons on the page I tested have shadows. I tested the timelog, reports, all the other links, and profile pages.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/e53833ca-9c7d-405c-badd-bd142a66806f

**Review by AaronPersaud — APPROVED** [review]
Hi, I've tested the changes and it looks great!

<b>Checking for shadow styling on some of the buttons</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/58862e59-e8d6-41ee-99b8-f8563977aa74

- checked all the pages that were listed in the screenshots and verified that the styling was consistent

One thing to note, as @winghojackyli mentioned above the "Mark as read" button doesn't show up after clicking the red bell for tasks. I believe this problem is outside of the PR.

Nice job!

**Comment by mounica-dingari-by** [comment]
Hi @AuroraLovesWhales , I've tested your PR and I can see that, the application hangs a lot,  after I've switched to your branch. I'm not sure if that has something to do with this branch or not. But, the buttons have the shadow effect throughout the application. 

Screenshot from 2023-07-22 22-22-46
Screenshot from 2023-07-22 22-46-14
Screenshot from 2023-07-22 22-46-21
Screenshot from 2023-07-22 22-46-35
Screenshot from 2023-07-22 22-46-58
Screenshot from 2023-07-22 22-48-22
Screenshot from 2023-07-22 22-50-28
Screenshot from 2023-07-22 22-50-38
Screenshot from 2023-07-22 22-51-05
Screenshot from 2023-07-22 22-51-19
Screenshot from 2023-07-22 22-56-33

**Comment by Shreyj14** [comment]
Hi @AuroraLovesWhales I tested your PR and the buttons have shadow throughout the application. But as @mounica-dingari-by mentioned, the app actually hangs a lot after switching to your branch. Please take a look on that, will approve the PR once you confirm it.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/ea3be08c-58eb-4c3a-b998-1d2aae647c99

**Comment by AnishPandita** [comment]
Hi @AuroraLovesWhales I tested the PR and the Shadow update throughout the app works well as seen below.
Screenshot 2023-07-23 at 4 50 45 PM
Screenshot 2023-07-23 at 4 50 34 PM
Screenshot 2023-07-23 at 4 50 09 PM
Screenshot 2023-07-23 at 4 49 31 PM
Screenshot 2023-07-23 at 4 49 01 PM
Screenshot 2023-07-23 at 4 48 32 PM
Screenshot 2023-07-23 at 4 48 18 PM

**Comment by beblicarl** [comment]
I tested this PR and it works as intended. The code is excellent as well, however, the page hangs a lot when working in this branch

[screencast-www.youtube.com-2023.07.24-13_01_23.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/a0503986-7e9b-4355-8f3c-bfa06aab4053)

**Review by beblicarl — APPROVED** [review]

**Review by yurisokolovicz — APPROVED** [review]
I approve the changes, it's working well. Following the collection of pages where I tested the shadow style.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/b7002bf6-34e0-4129-977d-fa1f3946cfda

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/0a4e89cf-0c50-44cb-a359-199a069774f2

Screenshot from 2023-07-24 10-09-48
Screenshot from 2023-07-24 10-13-26
Screenshot from 2023-07-24 10-25-08
Screenshot from 2023-07-24 10-25-35
Screenshot from 2023-07-24 10-27-54

Screenshot from 2023-07-24 10-32-51

**Review by BaileyM96 — APPROVED** [review]
Good evening @AuroraLovesWhales I tested your PR and everything looks great and works as intended great work!

## ScreenShots

PR #1034 Shadows in wbs tab

PR #1034 Members page

PR #1034 shadows on projects page

PR #1034 Jump to personal dashboard

PR #1034 Leaderboard Info

PR 1034 Profile Picture error shadows

PR #1034 Owner Permissions page

**Review by xaanders — CHANGES_REQUESTED** [review]
Hi @AuroraLovesWhales! I've checked all the buttons and found this one. 
Could you add styles to it as well?
profile -> select featured

**Review by eduvarjaor — APPROVED** [review]
Disconsidering the shadows button from the dashboard page (I couldn't test it because it's crashing all the time), all button shadows are working perfectly. Great job!

Screenshot_1
Screenshot_2
Screenshot_3
Screenshot_4
Screenshot_5
Screenshot_6
Screenshot_7
Screenshot_8
Screenshot_9

**Comment by iTvX** [comment]
In the first video, I have checked:
Other Links -> Projects -> click on the "WBS" button for any project
User Profile -> Change Photo -> update a photo that exceeds 50KB

**Comment by iTvX** [comment]
For the first video, I have checked below:
Other Links -> Projects -> click on the "Members" button for any project -> on the right side of "Find User" search tab, click "All"
Other Links -> Projects -> click on the "WBS" button for any project
Other Links -> Projects -> click on the "Members" button for any project -> on the right side of "Find User" search tab, click "All"

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/23da7732-8e09-4ec7-bcab-18b45ed2b01f

**Pull request closed without merging**
