### PR TITLE
Palak - New Badges Unit Test case

### PR DESCRIPTION
**Pull request by palakgosalia**
# Description
Unit test for NewBadges.jsx

## Main changes explained:

- Added a new file NewBadges.test.js
- Added 6 unit test cases. 

Renders Empty Message When No New Badges are Earned
Renders New Badges Correctly
Renders BadgeImage Components with Correct Props
Renders Empty Message When No New Badges are Earned
Handles Invalid Badge Data Gracefully
Filters New Badges Correctly

## How to test:

1. check into current branch
2. do npm test src/__tests__/Badge/NewBadges.test.js
3. check if all the test cases pass

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by bienzguoa — APPROVED** [review]
All tests passed! The tests are comprehensive and renders correctly.
Screenshot 2024-01-05 at 11 12 55 PM

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Great job on the tests you've made so far. All of your tests pass as they've been designed to. Just had some fixes needed before I could give approval on this. 

We've been making a big push to ensure test file location is in the right spot, so I've left a link advising on the location of where the test file needs to be. Please refer to the link on where to move it <a>https://docs.google.com/document/d/1-SMFLeoBoJhn8FUas5oLkofYoLTRM-Tz1HfjZ0gbBuk/edit</a>

Additional tests need to be added to confirm proper filtering out of badges older than a week.

"renders Badge Image components with correct props" also needs to be redone. You're only confirming the existence of one piece of a text element in there when there should be a lot more data verified. Would advise increasing the length of your mock badges to ensure proper data consistency through larger lengths. Use a forEach loop to iterate over the indexes of mockBadges with "expects" , so you don't have to write a ton of lines for this. (this should also be integrated into the badge filtering test since badges older than a week should be filtered out).

You should add a test to confirm that the "empty message" isn't present whenever there are badges as well.


You should add tests to confirm functionality of all aspects of the sorting in this component as well.

task list for approval:
1. fix test file location
2. add tests to confirm functionality of filtering out badges older than a week
3. fix and fortify to however many tests needed for the current test "renders Badge image component with correct props"
4. add test to confirm empty message not present when badges are present
5. add tests to confirm sorting functionality


Hopefully, some of the other members can chime in as well if there are any other optimizations I missed that need to be added for more comprehensive code coverage in this component rather than just running the test file and approving because it passes.

**Comment by iTvX** [comment]
All test pass.

CleanShot 2024-01-06 at 13 19 20@2x

**Review by vikrambadhan — CHANGES_REQUESTED** [review]
Hi, I tested your PR and encountered this error!

Week 19 - PR2

**Review by ChengyanOo — APPROVED** [review]
Hi @palakgosalia,

Great job – all tests have passed successfully! I would recommend adding an additional test to ensure that the "empty message" is not displayed when badges are present. Attached is a screenshot of the successful tests for your reference.

Screenshot 2024-01-10 at 15 48 56

**Comment by DragonSlayer2401** [comment]
I tested your PR and everything worked as intended. However I do recommend changing the test command in your How to test section to npm test NewBadges. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/69e703e8-6376-4e4b-872f-64e6af06399d

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2024-01-12 at 9 59 17 PM

**Comment by mianmiantea2019** [comment]
All tests have passed successfully. The correct command to execute the test is 'npm test NewBadges.test.js'. In addition, it would be beneficial to include more test cases, such as verifying that the 'empty message' is absent when badges are present.

image

**Review by 666saofeng — APPROVED** [review]
All tests passed.
image

**Review by peterson337 — CHANGES_REQUESTED** [review]
All Tests passed, however, there are some errors in the console that do not affect the tests that pass.

a

b

**Review by X1aoZhang99 — APPROVED** [review]
Hi Palak,

All tests passed. Nice work! However, the command to run the test should be `npm test src/__tests__/Badge/NewBadges.test.js`, please fix the text. 

Screenshot 2024-02-07 at 12 38 42

**Pull request closed without merging**
