### PR TITLE
Christy - add filters to weekly summaries reports

### PR DESCRIPTION
**Pull request by chappdev2019**
# Description

image

This PR enables the integration of two new filters into the weekly summary reports, which only visible to Admins and Owner

## Related PRS (if any):

none

…

## Main changes explained:
- Implements Two new filters to the weekly summary reports: one to quickly identify people who exceed their work hours by 25% or more, marked by colored stars, and another to find people eligible for bio posting, indicated by a yellow bar. 

…

## How to test:
1. Check into current branch.
2. Do npm install and npm run start:local to run this PR locally.
3. Clear site data/cache.
4. Log in with an Admin or Owner account. 
5. Go to dashboard→ Weekly Summaries Reports, the new filter toggles become accessible. Filter By Over Hours to identify people exceeding their hours by 25% or more, marked with colored stars, and filter by Bio Status to identify people eligible for bio posting, indicated by a yellow bar.
6. Log in with any role other than Admin or Owner without  'See Highlight for Bios Eligible to be Posted' 
7. Go to dashboard→ Weekly Summaries Reports, the new filter toggles are not available.
8. Log in with any role other than Admin or Owner with 'See Highlight for Bios Eligible to be Posted' 
9. Go to dashboard→ Weekly Summaries Reports, the filter by Bio Status is available.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/906666a4-a6c3-4b29-8daa-8d32921a715a

## Note:

If you're testing with an Owner or Admin account, or with another user account granted the 'See Highlight for Bios Eligible to be Posted' permission, you'll see specific users listed in the bio status filter if they meet the necessary criteria.

For  'See Highlight for Bios Eligible to be Posted' permission, please see https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1664#event-11397575005 for more details.

### CODE REVIEW

**Comment by peterson337** [comment]
I used the Bio Status filter, but it returned 0 users.

one comunnity

**Review by SaiDeepak-NEU — DISMISSED** [review]
Tested the changes in this PR and everything worked well.
1. Logged in as an admin and navigated to weekly summary reports.
2. There I could see the new filters over by hours and filter by bio status.
3. There were 1056 users with summaries before turning on the filter over hours
4. After turning on the filter, list returned only 1 user with a green star beside and the percentage 38% marked over it.
5. Turning on the bio status filter dint return any users but the filter was working.
Screenshot (79)
Screenshot (78)
Screenshot (77)

**Review by TareqMia — DISMISSED** [review]
Hi @mianmiantea2019, I tested out this PR and everything worked as expected. I logged in as an Admin and checked the weekly summaries report, and the new filter buttons were visible. I was able to filter by the "over hours" option, and it returned the people who exceeded their hours. The "bio status" filter didn't return anything, but I am assuming that is because any of the profiles did not match the criteria. 

I also logged in as a Manager to verify that the filter buttons were not present. Great job on implementing this 👍 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/fde108cc-0e17-425f-8524-ec61cc3da661


Screenshot 2024-02-09 at 6 45 58 PM

**Review by Renanluizssx — DISMISSED** [review]
Hi @mianmiantea2019, i tested your branch and it's running correct as you said, very nice.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/2410602b-6609-40e5-bbc9-006b1b40d2c6

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and everything worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/9e4d9a74-dcae-4c5b-8e54-9fa24d354063

**Comment by mianmiantea2019** [comment]
@peterson337 @TareqMia @SaiDeepak-NEU @Renanluizssx @ClemarNunes  Thank you all for reviewing my pull request. I took another look and figured out why the bio filter wasn't showing any users: it's because the bio permission has to be enabled by the Owner account. So, if you're testing with an account that doesn't have this permission turned on, you won't see any users come up.
Please see [PR1664 ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1664#event-11397575005) for more details. Therefore, when testing with an owner account or an Admin account with the "See Highlight for Bios Eligible to be Posted", you will observe certain users appearing under the bio permission filter. I will revise my testing instructions for greater clarity.

**Review by lacnoskillz — COMMENTED** [review]
Hello @mianmiantea2019 
I pulled your changes and the filter by hours works as described nice work
image

however im unable to test the filter by bio status

image



Also your addition is mobile responsive
image

**Review by swathyjayaseelan — APPROVED** [review]
The filter function works as expected. One UX improvement I see in this toggle button and all the checkboxes throughout the application is that a style of 'cursor: pointer' can be added on all the elements that have 'OnClick' or 'OnChange' handlers.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/c6dd3283-195b-46b5-bd08-6e592cf0e775

**Comment by galgalinidhi** [comment]
Hi @mianmiantea2019, I tested your PR and the filters work as expected but I see that there's a lag when I try to switch the toggle button on/off. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/0fc0b203-9349-47c8-bf91-41e87ae7b360

**Comment by mianmiantea2019** [comment]
> Hi @mianmiantea2019, I tested your PR and the filters work as expected but I see that there's a lag when I try to switch the toggle button on/off.
> 
>  1929.mov

Hi @galgalinidhi , the lag you experienced was due to the large data set needing to render in the component. Given that could become a performance concern, this PR wasn't intended to address it directly. I will note it under future improvements. Thanks for testing!

**Review by TapanPathak — APPROVED** [review]
Hi, I followed your outlined steps, logged in as Owner and the filters functions works fine! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/38bfe219-ef12-4e53-b7e3-75a4f462c09e

**Comment by galgalinidhi** [comment]
> > Hi @mianmiantea2019, I tested your PR and the filters work as expected but I see that there's a lag when I try to switch the toggle button on/off.
> > 1929.mov
> 
> Hi @galgalinidhi , the lag you experienced was due to the large data set needing to render in the component. Given that could become a performance concern, this PR wasn't intended to address it directly. I will note it under future improvements. Thanks for testing!

Hi @mianmiantea2019, that makes sense. Thank you!

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and the over hours toggle works perfectly.
Screenshot 2024-02-13 at 1 22 38 AM
Screenshot 2024-02-13 at 1 22 50 AM

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by Coops023 — APPROVED** [review]
After checking functionality of the weekly summaries filtering feature, everything seems to work well and the code looks good, only thing is perhaps leaving comments on the more complex conditions so its easy to read as a first time reader. great job.

FilterWeeklySummaries

**Review by peterson337 — APPROVED** [review]
Hi mianmiantea2019, I tested your application, and everything worked as expected. Good job!

one comunnity

one comunnity

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.16-17_08_28.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/2982349f-1052-4125-a5de-503babae9e82)

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
