### PR TITLE
Shrey unit test AboutModal

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for AboutModal component

## How to test:
1. check into current branch
2. do `npm install` 
3. npm test AboutModal.test.js
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-12-21 at 11 31 39 PM

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 17 - PR2

**Comment by one-community** [comment]
Thank you all, merging!

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-29 at 11 58 15 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
