### PR TITLE
Yi _BadgeImage_UnitTest 

### PR DESCRIPTION
**Pull request by yi-lin-1234**
# Description
Unite test for `BadgeImage.jsx`

## Main changes explained:
- Add the unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test BadgeImage.test.js` to run the test
4. Verify that all 3 tests have passed

## Screenshots or videos of changes:

Screenshot 2023-12-01 at 4 12 12 AM

### CODE REVIEW

**Review by ZichanYang324 — APPROVED** [review]
Hi @yi-lin-1234 , I have run the test file and all the tests cases have passed, no error, well done!
Screenshot 2023-12-01 at 1 33 25 PM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-01 at 2 24 39 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and everything works as intended!

Week 14 - PR5

**Comment by Cavein254** [comment]
Hi @yi-lin-1234, tested the code and everything works as expected
Screenshot from 2023-12-02 23-46-24

**Comment by beblicarl** [comment]
All test cases passed successfully 

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
