### PR TITLE
Shiwani TeamMemberTasks unit test failure hotfix

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
This PR fixes the issue with TeamMemberTasks unit test failure due to teams object not added in mock redux store.

## Related PRS (if any):
This PR is related to #2322 

## Main changes explained:
- Added team object to mock redux store in TeamMemberTasks.test.js

## How to test:
1. check into current branch
2. do `npm test src/components/TeamMemberTasks/__tests__/TeamMemberTasks.test.js` 
3. check if all the test cases passes without any errors or warnings

## Screenshots or videos of changes:
Screenshot 2024-07-17 at 6 02 09 AM

### CODE REVIEW

**Review by kdaga81 — APPROVED** [review]
image
All testcases passed!

**Review by vijay10pk — APPROVED** [review]
All the test cases passed.
image

**Review by beblicarl — APPROVED** [review]

**Comment by beblicarl** [comment]
All tests passed successfully.

image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (118)

**Comment by nikethaanand** [comment]
All the test cases have passed as expected.
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
