### PR TITLE
add change bio announcement to permission management

### PR DESCRIPTION
**Pull request by juneluo**
# Description
While many roles have the permission to view the weekly summaries report page, we expect only admin/owner can change/edit the bio announcement status with a toggle switch, and other roles just see the label. But outside of Owner/Admin, there will be people who will be granted editing ability. The users or classes can be granted special editing ability via the Other Links --> Permissions Management option.

## Related PRS (if any):
This frontend PR is related to the [backend PR382](https://github.com/OneCommunityGlobal/HGNRest/pull/382)  (So that by default the owner/admin has the editing ability).

## Main changes explained:
- add `changeBioAnnouncement` as an entry of the permission.
- use `hasPermission` to check the editing ability in the weekly summaries report page and then pass the result to the `formattedReport` component.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as roles who can only view the report (for example, manager) --> go to Reports→ weekly summary report--> can see the label of the bio announcement.

5. log as admin/owner --> go to Reports→ weekly summary report--> can edit the toggle switch of the bio announcement.

7. log as owner --> go to Other Links --> Permissions Management 
--> 1)click a role to change the permission of bio status --> the editing ability of any user from that class/role will change. 

-->2)click the blue button 'Manage User Permissions' --> search and select a user to change their permission of bio status -->the editing ability of that exact user will change.

## Screenshots or videos of changes:
Owner can change the permission for a role:

Owner can change the permission for a specific user:

## Note:
The changes made to the `mockAdminState.js, mockStates.js, WeeklySummary.test.jsx and WeeklySummariesReport.test.jsx` are just to make the test file consistent with the update, they should not make any differences to the running app.

### CODE REVIEW

**Review by stevenpaalz — COMMENTED** [review]
I am able to confirm that the code is working as intended for admin and manager accounts. I cannot access an owner account to test so cannot confirm that functionality.

Manager:
Screenshot 2023-06-03 at 8 38 19 PM

Admin:
Screenshot 2023-06-03 at 8 42 10 PM

**Review by EdwinLauM — APPROVED** [review]
Works as intended! Good job!

Manager Account (No access to toggle switch): 

Screen Shot 2023-06-03 at 7 20 29 PM

Admin/Owner Account (access to toggle switch):

Screen Shot 2023-06-03 at 7 26 07 PM

Admin/Owner Account (permission assign access):

Screen Shot 2023-06-03 at 7 26 17 PM

**Review by KurtisIvey — COMMENTED** [review]
first part works as intended
managerView

However, I was unable to recreate the toggle on two Admin accounts. Still new to the PR reviews, so it may have been something I was doing unintentionally. I traced the code and it seems that my admin account may not have permissions to do such associated with it as "bioCanEdit on line 188 of FormattedReport.jsx" is returning false from the "hasPermissions" function.

Here's the redux persisted userProfile state below on my Admin test account:

image

**Review by 20chen-7 — CHANGES_REQUESTED** [review]
I login as volunteer, it looks as intended. But I found the admin user does not have the permission. And I checked the permission management. It looks like this.
Screenshot 2023-06-05 at 12 26 33 PM

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Further explored the changes and created an Owner account to test. I was able to view the toggle switch with the owner account, but not the 2 admin accounts I used like the PR had advertised. These two admin accounts were created through the HGN portal and the Owner account was made through postman if that helps.

attached image verifying Owner account toggle functionality:
ownerVerify

**Review by KurtisIvey — APPROVED** [review]
Thanks for the clarification
Code checks out and functions as shown when admin functionality to edit bio was enabled through owner account.

adminCheck

**Review by 20chen-7 — APPROVED** [review]
It works as intended.
Login as admin:
Screenshot 2023-06-05 at 3 33 22 PM
Login as volunteer:
Screenshot 2023-06-05 at 3 38 55 PM

**Review by bienzguoa — COMMENTED** [review]
Works as intended for different roles!
Manager:
manager
Admin:
Admin
Owner:
Screenshot 2023-06-07 at 12 28 57 AM
Screenshot 2023-06-07 at 12 29 41 AM

**Review by bienzguoa — COMMENTED** [review]
Works as intended for different roles!
Manager:
manager
Admin:
Admin
Owner:
Screenshot 2023-06-07 at 12 28 57 AM
Screenshot 2023-06-07 at 12 29 41 AM

**Review by bienzguoa — APPROVED** [review]

**Review by OAkinbode — COMMENTED** [review]
The PR seems to work as intended. Looks good.

Admin view
Admin PR 879

Owner view
Owner PR 879

**Review by eduhorta — APPROVED** [review]
The PR works as intended. Nice job! 👍

Admin:
Screenshot 2023-06-07 14-53-56

Manager:

Screenshot 2023-06-07 14-58-21

**Comment by one-community** [comment]
Low-risk PR with 4 approvals, merging, thank you.

**Pull request merged**
