### PR TITLE
Shantanu unit test pie chart

### PR DESCRIPTION
**Pull request by n0vay**
# Description
Wrote unit test cases for the Pie Chart component

image
image

## Main changes explained:
- Added a null safety zero in the file
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. run in tersimal: npm test PieChart.test.jsx
4. check if everything passed

## Note:
Include the information the reviewers need to know.
The Map function in the component do not have a key property

### CODE REVIEW

**Review by JeffLi117 — APPROVED** [review]
image

Tests all passed and your code looks good to me! Great job!

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

PR 1554

**Review by keyunhuangg — APPROVED** [review]
I reviewed your code and it looks great! And ran the tests locally and everything was passed shown in the screenshot below.
Screenshot 2023-11-17 at 8 07 00 PM

**Review by Changhao3220K — APPROVED** [review]
hi @n0vay Test all passed, good work!
Screenshot 2023-11-17 at 9 00 58 PM

**Comment by StrawberryCalpico** [comment]
Screen Shot 2023-11-18 at 4 35 55 PM
Tested your PR, great work!

**Review by StrawberryCalpico — APPROVED** [review]
Screen Shot 2023-11-18 at 4 35 55 PM
Tested your PR, great work!

**Comment by wanglu1207** [comment]
Hi @n0vay , good job! All the cases passed.

**Review by pika-chu11 — APPROVED** [review]
Hi @n0vay , all tests are passed! Great job! 
PR 1554

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-18 at 11 39 07 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
