### PR TITLE
Shiwani add permission for edit project category or status

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Make permission management fix for edit project category or status.

## Related PRS (if any):
This frontend PR is related to [#650](https://github.com/OneCommunityGlobal/HGNRest/pull/650) backend PR.

## Main changes explained:
- Added anEditCategoryAndStatus to Project.jsx which will check if 'editProject' permission is present in frontend permissions. If it is true then category and status field will be editable.
- Added canEditCategoryAndStatus as a condition in return to make it editable.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner user
4. go to dashboard→ Other links -> Permission Management -> Manage user permissions -> type name of any user -> Add 'Edit project Category or Status' -> click submit
5. If the user for whom the permission is being set does not have projects tab under Other links then add 'See Project Management Tab (Add team members, upload new WBSs only)' permission as well for that user
6. Log in as the user for whom the permission was added
7. go to dashboard -> Other links -> Projects -> check if category and status is editable.
8. Check if name is not editable, there are no 403 errors in browser console when trying to edit category or status.

## Screenshots or videos of changes:
Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/72ce48ed-e3c4-4366-a34d-64fc0d85059b

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/65c5e668-b1d9-46e7-be2a-b5dcc1fa4ff9

## Note
- Owner, Administrator, Manager have permission to edit name, category, status as there are preset permissions for these roles that allow them to be edited by default.
- Check for roles that do not have category or status edit permission like volunteer, assistant manager, test or any other role.

### CODE REVIEW

**Review by Shuhua-L — COMMENTED** [review]
Hi, I've tested your PR. 

The project category and status became editable once the user got permission (See recording 1). 

However, it looks like the new permission was only granted on the FrontEnd because when I tried to make an actual change, there were 403 errors (see recording 2) while the Owner user can edit projects as usual. 

I am using the latest dev branch for the backend. Is there a specific backend branch I should use?


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/468a966b-ee63-4dca-a25f-8f482c5a46e2

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/5c1852c1-0aac-4f2a-86b7-77080e861891

**Comment by Shiwani99** [comment]
> Hi, I've tested your PR.
> 
> The project category and status became editable once the user got permission (See recording 1).
> 
> However, it looks like the new permission was only granted on the FrontEnd because when I tried to make an actual change, there were 403 errors (see recording 2) while the Owner user can edit projects as usual.
> 
> I am using the latest dev branch for the backend. Is there a specific backend branch I should use?
> 
>  PR1606-project-category-status-editable.mov 
>  PR1606-403-permission-error.mov

Hi,
Thank you reviewing. I think I may have misunderstood the description of the task since It was given that the backend was working when I initially started to work on it. I will take a look at this and fix the issue.

**Review by Shuhua-L — APPROVED** [review]
I was able to run through all the steps. Great job!

First, I logged in as a volunteer, and the project info was not editable. I confirmed that there were no associated 403 errors. Although there were some 404 errors, it seems like they are related to the Owner Message and not the Projects. I then logged in as an owner and gave permission to the volunteer, who became able to edit category or status. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/2bdea8e6-edb4-4f17-85c9-859f17ee2d26

**Review by ilyaflaks — APPROVED** [review]
I have tested this PR and everything works as described! 
I created a new volunteer account just for this test and added the specified permissions from the owner account: 
PR1606+650-owner-manage-perm-01
Then I logged in from the account I just granted permissions to and was able to see the "Projects" tab in "other links":
PR1606+650-vol-can-see-projs-02
There I was able to change the active status and the category of any project: 
PR1606+650-edit-active-cat

Good job completing this task with minimal code! My only suggestion would be to remove the console logs on the front end

**Review by Alforoan — APPROVED** [review]
Everything worked as it should. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/9fef4e4d-4300-45b0-afc2-3f4495bc3f5d

**Comment by mianmiantea2019** [comment]
I have tested this PR and everything works as described! Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/20150664-6799-427f-852d-58ce04bab13a

**Review by Pandani07 — DISMISSED** [review]
Tested this PR along with the backend PR and everything works as expected. I added the edit category permission for a user, but the user could not see the projects link. So, I added that permission as well as you had mentioned. Functionality works!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/8f1c111e-12b1-442c-8d16-f1bfbe8c915b

**Review by Gugor99 — APPROVED** [review]
### Report
Hi Shiwani,
I tried your implementation and it seems to be working as intended. Here are the steps I took: logged in as owner to change my volunteer's permission to edit a project category. I then logged in with my volunteer account and once navigated to the projects section, I was indeed able to modify project's categories. Please see screenshots for reference.
### Screenshots
Cattura1
Cattura2
Cattura3

**Review by XiaohanMeng — APPROVED** [review]
Hi, I tested this PR with backend PR and all worked as intended. I granted permission to volunteer role and it can edit the project. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/f0ea9f8a-0779-4f23-9905-d2ab23656dd4

**Comment by KaushikMreddy** [comment]
Hi, 
I've tested and reviewed your changes with my owner and volunteer account. The images below are from the testing/ volunteer account.

Before permissions
image

After providing permissions
image
image

Good work!

**Review by peter6866 — DISMISSED** [review]
Great work on implementing the permission management fix for editing project category and status! The PR looks well-structured and addresses the required changes effectively. Here are the key points:
✅ Added canEditCategoryAndStatus check in Project.jsx to determine if the user has the 'editProject' permission.
✅ Conditionally rendered the category and status fields as editable based on the canEditCategoryAndStatus flag.
✅ Ensured that the project name remains non-editable for users without the necessary permissions.
✅ Verified that no 403 errors appear in the browser console when attempting to edit category or status.
Testing:
- I followed the provided testing steps and confirmed that the permission management works as expected.
- Users with the 'Edit project Category or Status' permission can successfully edit the category and status fields.
- Users without the necessary permissions cannot edit the category or status fields, and no errors are observed in the console.
image
image

**Comment by akshit0211** [comment]
Hi Shiwani, the changes are working as expected. Good work!

without permission
without permission result
with permission
with permission result

**Review by akshit0211 — DISMISSED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
