### PR TITLE
Kaushik hotfix: fix issue on load application

### PR DESCRIPTION
**Pull request by KaushikMreddy**
# Description
This is a hotfix for the error faced on the UI on loading the front-end server. 
image

## Main changes explained:
- Commented out GPT code for later use, in case the node version is ever updated from 14 to 18.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Check if application works as normal

## Notes
PRs 2299 frontend and PR 966 backend should not be merged right away. They have a node version dependency and the node version needs to be updated from node v14 to node v18. Unless this happens the feature is not supported. This hotfix is to comment the code for the feature so it can be picked up again at a later time if needed.

### CODE REVIEW

**Review by vijay10pk — APPROVED** [review]
App is loading properly without any error and able to navigate through major routes.

https://github.com/user-attachments/assets/c66b8b73-9ba7-42a5-afc1-8e00b8ab61d4

**Review by kdaga81 — APPROVED** [review]
image

image

Application coming up!

**Review by DiyaWadhwani — APPROVED** [review]
Hi Kaushik,
Thanks for the quick response and changes. The server runs and I'm able to login now. Great work. I have attached a video testing below.
Thank you

https://github.com/user-attachments/assets/ca5cb425-57fe-4333-9d93-56d56ed0aefb

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by nikethaanand** [comment]
The changes are working as expect on navigating to different pages with the loading sign after the user logs in.

https://github.com/user-attachments/assets/0a16d334-1794-44f9-b8f1-6e38d3d2da73

**Pull request merged**
