### PR TITLE
Anne fix hovering in dark mode subtask get white issue for WBS tasks

### PR DESCRIPTION
**Pull request by Annezhang673**
# Description
Addressing issue raised by Shrinivas Patil while testing a previous PR
image

## Related PRS (if any):
This frontend PR is related to the development backend PR.
This frontend PR is an update to https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2709, fixing the issue as described in the description above. 

## Main changes explained:
- Update file /HighestGoodNetworkApp/src/components/Projects/WBS/WBSDetail/wbs.css to include the scenario when there is on hover action in the dark mode, the background of the sub task remains dark, instead of white. 

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links>Projects>[Click WBS Icon](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa)
6. Please refer to the above link on how to create WBS task and sub tasks. There are minor differences.
7. Add task A , then proceed to add sub task B, then proceed to add sub task C. 
8. Check if under darkmode, when hovering above the subtasks, the background did not turn white, instead it should remain dark and the texts should be clear and recognizable

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/e7b4c676-0ac2-4c8a-915c-1638114b6843

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/d8c8e259-083a-4161-bc1e-1d7b4174ba56

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and everything working as expected.

Screenshot 2024-10-10 195651

**Review by chu-ziyu — DISMISSED** [review]
I tested this PR in dark mode and everything worked as expected.
Screenshot 2024-10-11 at 5 52 25 PM

**Comment by ShreyaLaheri** [comment]
Hi - I am on the current branch and followed the steps but I don't see the change
image

**Review by shivansh-nathani — DISMISSED** [review]
I have tested the code and the bug is fixed.
Screenshot 2024-10-11 at 10 56 13 PM

**Review by Nahiyan-16 — APPROVED** [review]
Hi Anne, I have tested your PR, and it works great. I do not see any issues with your changes.

https://github.com/user-attachments/assets/4ed02ae5-3a61-4fd4-b76d-0e18d7026fcf

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected in darkmode and the hover functionality works as expected.
**Just a minor change in the hover the <br/> tag is still visible.**

Screenshot 2024-10-13 at 3 36 09 AM
Screenshot 2024-10-13 at 3 36 16 AM

**Comment by pallavithorat** [comment]
The PR is working as expected, with task A, subtask B, and subtask C added successfully. Under dark mode, hovering over the subtasks keeps the background dark, and the text remains clear and recognizable, without turning white.
PR#2773

**Review by shashankhv — APPROVED** [review]
Checked in dark mode, the hover effect works as expected with no background color issues. Approving the PR.

[anne-PR.webm](https://github.com/user-attachments/assets/914f67a6-0850-4ddd-afb5-70de821ebcb2)

**Review by CodewithKoushica — CHANGES_REQUESTED** [review]
Tested in dark mode, and the hover effect works well with no background color issues. However, the tooltip currently displays HTML tags. Please update the tooltip to remove the tags.
Screenshot 2024-10-22 at 5 34 20 PM

**Review by samarth9201 — APPROVED** [review]
Reviewed the PR, works as expected.

image

**Review by NK3101 — CHANGES_REQUESTED** [review]
Tested the PR in dark mode, the hover effect functions as expected. However, there's a hover text currently displaying HTML tags for sub-tasks.

Screenshot 2024-10-25 at 9 29 31 PM

**Review by Muhideenthegreat — APPROVED** [review]

**Review by Muhideenthegreat — DISMISSED** [review]
Verification:

Everything in this PR works as expected

Screenshot 2024-10-26 at 2 38 46 PM

**Comment by Annezhang673** [comment]
Hi @NK3101 @CodewithKoushica! Thanks for the review. The issue you mentioned is not in the scope of this PR. I believe this issue has existed beforehand. You can comment in the bug document to raise a bug. Thank you.

**Pull request merged**
