### PR TITLE
Team task UI change

### PR DESCRIPTION
**Pull request by Programmingrelated1999**
This PR is for making the “Team Member Tasks” section a tab as part of the “Time Entries” section.

There were several changes made. They are listed below. 

* The TeamMemberTasks is no longer rendered from the Dashboard component, instead it is now rendered as a tab in Timelog component, and is passed asUser variable which is also passed as props.asUser from Dashboard to Timelog. 
* activeTab was used to be assigned as 0 for current week timelog, 1 for last week, 2 for week before last, and 3 for search by Date Range. Now it is assigned to as 0 for tasks, 1 for current week timelog, 2 for last week, 3 for week before last, and 4 for search by Date Range.
*  The activeTab was used in startOfWeek() and endOfWeek() for calculating dates for the week. Since the value of activeTab changes now, i use activeTab - 1 to adjust the changes. For example value for current week timelog now is 1, while it used to be 0 so to adjust it subtract 1. 
* activeTab condition in EfforBar.jsx is also changed.

Now the time Entries has one more tab which is Tasks. The summary also shows the same way as previously. Current Tab text color is also black while other tab text color is blue. 

The screenshots are shown below:
TeamTaskTimeLog1
TeamTaskTimeLog2

### CODE REVIEW

**Review by brucelin006 — APPROVED** [review]
I have reviewed and approved this PR review.

**Comment by kseniaxu0704** [comment]
Hi Kaung,
Nice change. I see you successfully change task member section from the dashboard to the time log- Task. 
For two things that may need to be noticed:
1) please rebase before pushing PR to make the code update to be the last version.
2) when I click the task, current week time log, last week time log, and search by the range that looks all good; However, when I click the week before last week, it returns a blank. could you please check what happened to that?
Screen Shot 2022-09-14 at 9 48 47 PM

**Review by kseniaxu0704 — CHANGES_REQUESTED** [review]
Hi Kaung,
Nice change. I see you successfully change task member section from the dashboard to the time log- Task.
For two things that may need to be noticed:

please rebase before pushing PR to make the code update to be the last version.
when I click the task, current week time log, last week time log, and search by the range that looks all good; However, when I click the week before last week, it returns a blank. could you please check what happened to that?
Screen Shot 2022-09-14 at 9 48 47 PM

**Comment by Programmingrelated1999** [comment]
Hi. I have updated fixes along with a new functionality, please review https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/518. It is created under a new branch "movePseronTaskIfAssigned".

**Pull request closed without merging**
