### PR TITLE
Obeda fix another person view dashboard view header

### PR DESCRIPTION
**Pull request by dah00**
# Description
task

## Related PRS (if any):
Reverted [#991](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/991)
…

## Main changes explained:
- The Header.jsx always displayed the header of the logged in account even when viewing another account because it used data from props.auth, which contains data of the logged in user
- In Header.jsx, replaced props.auth to props.userProfile and made minor adjustments according to it so that the header of the viewed account is displayed
- Likewise, in the Permission file, used state.auth instead of state.userProfile

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in with different user roles (read note below)
4. Leaderboard -> Click dot by person's name -> Click OK
5. Check the header section to ensure that: 
	a. the correct name of the viewed account is displayed
	b. the correct menu options are displayed according to their account type 
	c. the menu options work properly

## Screenshots or videos of changes:
Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/03ea6aed-b6b9-4300-b58e-60f8a456965e

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61763829/cd52ae9b-034a-4ab7-9d93-2ca75a0f6b43

## Note:
 1. Admin/Owner account should be able to interact with other accounts
 2. Non admin/owner account should not be able to interact with other person's header options

### CODE REVIEW

**Review by Iris-Song — APPROVED** [review]
Hi, I log in as a volunteer user. And open a user's account on leaderbroad. The menu option show as expected. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/6de82f0a-814b-407a-9177-f874cbcd335a

**Review by JeffLi117 — APPROVED** [review]
Changes work as intended. The correct header options were shown.

Logged in on Owner, I was able to access multiple parts of a Volunteer/Admin account:
image
image
image
image
image

Logged in as Volunteer, I am not able to access anyone else's accounts: 
image

Great job!

**Review by TuanDinh140194 — APPROVED** [review]
I have tested your PR with owner and volunteer account. For the owner account, when view the other person, the header show the correct name of the other person, and correct menu options are displayed according to their account type. With the  owner account, I can interact with the other person. Next, with the volunteer account, It also works correct function, but I can change the other account setting.
Here is test with owner account: 
 
Screenshot 2023-10-14 181726
Screenshot 2023-10-14 181711
Here is the test with volunteer:
Screenshot 2023-10-14 181052
Screenshot 2023-10-14 181116

Screenshot 2023-10-14 181209

**Review by Cloid — APPROVED** [review]
Hi there.

I tested the following:

- As Admin, viewed dashboard as a Manager user. Interacted with various drop-down menu such as  opening up another dashboard as volunteer (within manager profile)
- As Admin, viewed the dashboard as a volunteer and made sure I could interact with the components I would see if I were logged in as a volunteer.

Everything seems to work fine. Good Job.
image

image

**Comment by John-Flavian** [comment]
Hi nice job.

However, I observed that the code is failing one test: TimeEntryForm.js.
image

consider using conditional rendering.

kudos.

**Review by lacnoskillz — APPROVED** [review]
hello @dah00 
I pulled your code and tested it locally and it appears to work as intended!
When I tested on development I confirmed that the dashboard was displaying the wrong name when viewing someone elses dashboard.
When I pulled/tested your code the dashboard now displays the correct name and retains all the functionality.

image

also confirmed that volunteers/admins still have the correct menu options are displayed according to their account type
image
Nice work!

**Comment by JeffLi117** [comment]
When I log in on the Volunteer account, I am able to view the dashboard and interact with the header of another volunteer's account (go to dashboard, timelog). Is this intended? I'm uncertain as to what your note "Non admin/owner account should not be able to interact with other person's header options" specifically means by "header options". 

image

Other than this, it works as you intended initially!

**Comment by Jiyuanxia** [comment]
Hi @dah00 , I have reviewed your pull request and tested it. It works as you intended. While I log in as owner role, I am able to interact with other account but volunteer role is not able to. Well done!

As owner
Screenshot 2023-10-19 211001

As volunteer
Screenshot 2023-10-19 211534

**Comment by RheaWu1212** [comment]
Hi I tested your PR, working as expected! 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/7f414949-650b-46b9-afb5-dcceea8b4588

**Comment by RheaWu1212** [comment]
Hi I tested your PR and working as expected, great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/33a8db8f-616d-469e-8306-5fc8e660e2b9

**Review by StrawberryCalpico — APPROVED** [review]
I tested your PR. It works as expected! Great job.




https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/e6197008-7606-474a-962b-dcc190790026

**Review by yi-lin-1234 — COMMENTED** [review]
Hello, I tested your PR and works as intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/9e15289f-86f3-45db-967c-fc961e18ccfb

**Comment by dah00** [comment]
> When I log in on the Volunteer account, I am able to view the dashboard and interact with the header of another volunteer's account (go to dashboard, timelog). Is this intended? I'm uncertain as to what your note "Non admin/owner account should not be able to interact with other person's header options" specifically means by "header options".
> 
> image
> 
> Other than this, it works as you intended initially!

Thank you for pointing this out @JeffLi117. I am going to clarify this with Jae and get back to you.

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions. This feature looks so good. 
The functionality is working as expected! 
You may check the testing details below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/2294cccd-2b4f-4626-ab24-bf71dd555709

**Review by luisarevalo21 — APPROVED** [review]
Hello @dah00,

I tested your PR and works as intended. Great work.
Selecting a user opens a new window and I am able to view the correct user. 
Great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/f63b79b1-2306-400d-a743-70f3b163fc9c

**Comment by dah00** [comment]
> When I log in on the Volunteer account, I am able to view the dashboard and interact with the header of another volunteer's account (go to dashboard, timelog). Is this intended? I'm uncertain as to what your note "Non admin/owner account should not be able to interact with other person's header options" specifically means by "header options".
> 
> image
> 
> Other than this, it works as you intended initially!

@JeffLi117  Yes, this is intended. What I mean by interacting with another person's header options is the ability to click on their menu options (Dashboard, Timelog, View Profile, Update Password, etc) and see exactly that person sees

**Comment by AnishPandita** [comment]
Hey I tested the PR and everything seems to work great. Tested with Owner account and correct name of viewed account and menu options were shown and interaction was permitted. When testing with volunteer account everything changed accordingly but interaction with account settings was not permitted.
Screenshot 2023-12-06 at 3 22 50 PM
Screenshot 2023-12-06 at 3 30 38 PM
Screenshot 2023-12-06 at 3 28 23 PM

**Review by BaileyM96 — COMMENTED** [review]
Good evening I have reviewed your PR great work everything seems to work as described.

## Videos

[Seeing if I can interact with Owner account header with volunteer account.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/675c9d62-a795-4d7f-bec9-2b2749505ad2)

[Viewing a Volunteer Account.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/c71353fb-98cb-4f84-8562-37f4b5666a80)

[Viewing a Owner account dashboard.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/ab92b561-51a0-4885-966f-bfd9bc8d61bf)

**Pull request merged**
