### PR TITLE
Kaikanes LessonForm Tags Functionality 

### PR DESCRIPTION
**Pull request by lacnoskillz**
# Description
Added Tags functionality to the lessonform. 
Display all projects and roles in dropdown
Added Lessonform button to the project dashboard.

## Related PRS (if any):
building off of theses previous PR's
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1477 (figma design)
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1577 (drag and drop)
…

## Main changes explained:
Fetched projects and roles so the dropdowns displays all the  projects/roles in the database
Users can now enter tags by typing and pressing enter. 
When a user selects a project from the dropdown it automatically adds that project as a tag.
Added a lesson button on the bmdashboard that displays a project specific form that has the belonging project locked.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as anyone
4. go to http://localhost:3000/bmdashboard/  -> select a project and click the new lessonform button
5. verify the project specific form displays the correct projectID. (just using projectID dummy data for now until /bmdashboard is displaying real data.
6. test the new tags functionality. tr to break it. users should not be able to add duplicate tags. 
7. go to http://localhost:3000/bmdashboard/lessonform/ and test the non project specific form also

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/4fd8e3a6-e1a7-4b84-add7-e8d1f748cdb4

## Note:
When selecting a specific project from the dropdown the displayed title is different because we are using the projectId not the project name.  Later will probably do a fetch or pass more props.
image

image

### CODE REVIEW

**Review by lichanghaogit — DISMISSED** [review]
Hi @lacnoskillz 
I tested this PR on my local environment and this works as expected, nicely done!

The page loads properly and the add tag entry works well.
Screenshot 2023-11-23 at 10 18 17 AM
Screenshot 2023-11-23 at 10 18 37 AM

Tags could be deleted as well
Screenshot 2023-11-23 at 10 19 42 AM

Using the new link the project drop down works fine and I could select any projects and add tags/ delete tags for them.
Screenshot 2023-11-23 at 10 20 22 AM
Screenshot 2023-11-23 at 10 20 44 AM

Project switch will keep the original added tags.
Screenshot 2023-11-23 at 10 21 10 AM

**Comment by palakgosalia** [comment]
Hey, I reviewed and tested your PR. It works as intended. The project IDs displayed are correct and I was able to add and delete tags. Duplicate tags were not getting added. Great work
Thank you

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/57024fe8-399c-4f0a-a704-02550427c234

**Review by Alforoan — DISMISSED** [review]
The functionality seems to work well. Nice

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/905bc285-5f44-441c-831d-459a12574549

**Comment by lacnoskillz** [comment]
Figure since my reviews will be stale from fixing conflicts 
id add a small feature the 'Title' field.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
