### PR TITLE
Nathan separate reports from weekly summaries

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR separates the permissions for seeing the weekly summaries and reports under the reports tab.

## Related PRS (if any):
This frontend PR is related to the [#643](https://github.com/OneCommunityGlobal/HGNRest/pull/643) backend PR.

## Main changes explained:
- Add permisison check for 'getReports' in header to access the reports page
- Limit 'getWeeklySummaries' to only the weekly summaries page

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as users with each combination of the `getReports` and `getWeeklySummaries` permissions (see notes)
5. go to the dashboard
6. Check if the reports tab appears if you have either `getWeeklySummaries` or `getReports` permissions
7. Check if 'Reports' appears in the tab if you have `getReports`

## Screenshots or videos of changes:
Both permissions:
image
Only reports:
image

Only summaries:
image

Neither permission (no reports tab):
image

## Note:
You can check what permission your user has with redux dev tools under:
1. `state.auth.user.permissions.frontPermissions` for individual permissions
2. `state.role.roles.{the role of your account}` for role permissions

If you need to assign permissions to a user, log in with an Owner account and go to Other Links->Permission Management->Manage User Permissions and give/remove needed permissions from a volunteer account

On the permissions management page, `getReports` is labeled 'See Analytics Reports' and `getWeeklySummaries` is labeled 'See Weekly Summaries'.

### CODE REVIEW

**Comment by DragonSlayer2401** [comment]
I tested your PR the dropdown shows the correct options. However, when you only have the Reports permission, it appears that the Reports page becomes inaccessible. The the weekly summaries permission both with and without the reports permission seems to work fine outside of an icon not showing on the weekly summaries page. With both permissions enabled, both pages are accessible via the dropdown. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/bab572e4-6fab-4c13-be2b-237b9f6433f1

**Comment by nathanah** [comment]
> I tested your PR the dropdown shows the correct options. However, when you only have the Reports permission, it appears that the Reports page becomes inaccessible. The the weekly summaries permission both with and without the reports permission seems to work fine outside of an icon not showing on the weekly summaries page. With both permissions enabled, both pages are accessible via the dropdown. Please watch the overview video below for more details:
> 
>  2023-12-09.14-44-30.mov

Yes, those are the permissions I was referring to. It's the key (which would appear in redux dev tools as you found) instead of the label that you see in Permissions Management. I updated the instructions and fixed your issue.

**Review by pika-chu11 — APPROVED** [review]
Hi @nathanah , I have tested your PR. It looks functional on assigning both getReportss and getWeeklySummaries to the user.  Great work!

- When assigning the getReports permission to the user, the user website did show a `Reports` button under the `Other Links` and it did direct me to the correct page. The Redux dev tools did show that it has the correct variable `getReports`.

- When assigning the `getWeeklySummaries` permission to the user, the user website did show a `Weekly Summaries Reports` button under the `Other Links` and it did direct me to the correct page. The Redux dev tools did show that it has the correct variable `getWeeklySummaries`.

- When assigning the both permission to the user, the user website did show both buttons under the `Other Links` and it did direct me to the correct pages. The Redux dev tools did show that it has the correct variables as above.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/c4d0a02e-1d9f-4a20-9df0-dffc3c3e4cb5

**Review by Alforoan — APPROVED** [review]
All work as expected. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/9d2e718c-d59a-47b8-9f11-f76202968be6

**Review by BaileyM96 — APPROVED** [review]
Hello @nathanah I tested your PR and everything works just as explained. I tested on Admin, owner and volunteer great work!

## Screenshots

Reports Only 
Reports only

Only seeing weekly summary reports and Team Locations

Owner Account with all options showing

**Review by sucheta90 — APPROVED** [review]
Hello @nathanah , I've carried out a test on this PR and verified that the features function as specified. The tabs display according to the permissions assigned to various roles.

**As Manager**
PR1658+643_manager

**As Owner**
PR1658+643_owner

**As Volunteer**
PR1658+643_volunteer

**Review by keyunhuangg — APPROVED** [review]
1) Logged in as volunteer without 'report'
Screenshot 2023-12-15 at 4 23 51 PM

2) Gave permission to this volunteer with report->reports and report->weekly summary report
Screenshot 2023-12-15 at 4 26 39 PM

3) Gave permission to this volunteer with only report->weekly summaries report
Screenshot 2023-12-15 at 4 28 28 PM

4) Gave permission to this volunteer with only report->report
Screenshot 2023-12-15 at 4 30 49 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
