### PR TITLE
Peizhou_team report white page issue_Follow up Work Required

### PR DESCRIPTION
**Pull request by ZhangPeizhou**
# Description
image
https://drive.google.com/file/d/1zHp1oI43cSn6Wed7ubn2XbKj0mtxuAKL/view

## Related PRS (if any):
This frontend PR is not related to any backend PR, please just check in to the development branch.

## How to Test
1. check into the current branch
2. do npm install and ... to run this PR locally
3. Clear site data/cache
4. log in as an admin/owner user
5. go to dashboard→ Reports→ Reports→ Teams
6. Select a random team and stay on that page, see if the page will turn into a white page or not. It should NOT turn into a white page no matter how long you stay there.

## Additional Follow-up Work is Required!
In the "TeamReport.jsx" file, line 494, there is a "handleSearch()" function that causes the undefined-function error, and will lead to the white page issue. However, I tried many ways but was still not able to fix this issue. Additionally, this function will also lead to not being able to pass the TeamReportTest, so I have to comment all the test code to push this branch. Please fix the issue if you know how to do that. What I did was just comment all these things. At least now the white page issue will no longer occur.

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/9d4dfc47-c15b-4de2-8ba1-5e8e05f1f78d

### CODE REVIEW

**Review by kdaga81 — CHANGES_REQUESTED** [review]
image

Getting white page after refreshing the page. However, it's coming back after some time (around 10-15 secs)

**Review by jinxyou — APPROVED** [review]
So far I waited for a long time and no blank screen popped up. Great work!
Screenshot 2024-07-20 192023

**Review by Chetan0606 — COMMENTED** [review]
I don't see a white page, but I have noticed a different issue. When I click on a team and then go back to check another team, the team name is not getting updated. I need to refresh the page to see the updated team name. Please correct me if I'm wrong. I have attached a video for your reference.


https://github.com/user-attachments/assets/1ba69d55-315e-4b21-9416-da6efd03c970

**Review by aaryaneil — COMMENTED** [review]
Tested the PR and the white page error is not occurring but after switching to a different team the previous teams data persists and the new teams data loads after a delay.

https://github.com/user-attachments/assets/8dbac0a9-eeeb-463b-b1a0-3b9b4c7712a9

**Review by Gauravmg6 — APPROVED** [review]
Screenshot 2024-07-22 154844
I waited long enough and the page doesn't turn white. It's working fine.

**Comment by ZhangPeizhou** [comment]
> [Chetan0606](/Chetan0606)

Thank you for letting me know! This issue will be handled in an other PR.

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey @ZhangPeizhou 
I have Tested the PR it is working fine in certain states however i found few bugs
1)The Team Data is persisting in some scenarios initially and later its updating the page.
Thank You

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested this PR. It is working great. No error is occurring if I stay on the page long time. Great work !

https://github.com/user-attachments/assets/91ea21bf-b5f6-4c9d-bb90-7b6ec4351e62

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/bd0cfb82-0d2f-4bf8-a812-f173ab83c69a

**Comment by ZhangPeizhou** [comment]
> image
> Getting white page after refreshing the page. However, it's coming back after some time (around 10-15 secs)

Thank you for your reply! Could you please test one more time, since I does not have the issue on my device? Thank you!

**Comment by ZhangPeizhou** [comment]
> Hey @ZhangPeizhou I have Tested the PR it is working fine in certain states however i found few bugs 1)The Team Data is persisting in some scenarios initially and later its updating the page. Thank You

Hello, thank you very much for your review! Could you please include a video about this issue, since I tested multiple times, but still cannot recurrence this issue. Thank you very much!

**Comment by one-community** [comment]
Thank you all, merging so we can test this live on the Dev.

**Pull request merged**
