### PR TITLE
Eduardo lint fix force password update component

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
Lint fix for the Force Password Update component:
`src/components/ForcePasswordUpdate/*`

## Main changes explained:
Executed the lint checker
Fixed changes manually apart from fix done by lint--fix
Removed the component from .prettierignore and .eslintignore

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. do `npx eslint src/components/ForcePasswordUpdate/*`
4. log as admin user
5. go to /forgotpassword
6. verify if the app is working properly

## Images

image
image

## Notes:
It is expected to have a warning when running the command due to the `alert` function.

image
image

### CODE REVIEW

**Review by lacnoskillz — APPROVED** [review]
Hello Eduardo
It appears that with your changes the functionality of the forgot password page still works
I tested clicking the forgot password button before login
image

and manually entering the route

image

I also tested reseting the password and got a successful response
image

nice work

**Review by Sssky-18 — APPROVED** [review]
Hi @eduhorta, I tested this PR, and it worked great. All the eslint errors have been fixed, and the forget password page displayed well. Thank you for your contribution!

PR#1397
PR#1397_2

**Review by sxiong5 — APPROVED** [review]
Hey @eduhorta, the PR works great, and there is no eslint error. Great job!

Screenshot 2023-10-11 at 14 21 19
Screenshot 2023-10-11 at 14 19 14

**Review by wantingxu7 — APPROVED** [review]
Hi, I've tested the pr locally. There is no error in the console after running the command.


The forget password function also LGTM. I can only submit when all the fields are correct, otherwise there is a warning message at top right corner. When success, there is a success message at top right corner.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/15c98f17-7e5e-4cdb-88ca-5234914b79ed

**Comment by beblicarl** [comment]
This functionality works as intended

image

image

**Review by beblicarl — APPROVED** [review]

**Comment by olenadanykh** [comment]
hi @eduhorta. I have tested your PR locally, no eslint error were noticed. Also the Forgot Password functionality works great!
Good job!
eslint

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/65b5056d-974c-4df5-8c86-18ad3ad30847

**Review by Jiyuanxia — APPROVED** [review]
Hi @eduhorta , I have reviewed your pull request and tested it. It works as you intended. Good job!
Screenshot 2023-10-12 170807
Screenshot 2023-10-12 170912

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
