### PR TITLE
Howie add double confirmation for task link submission 

### PR DESCRIPTION
**Pull request by HowieMiao**
# Description
Previously added requirement for a https link with at least 20 characters in the form for a task to be submitted.
There has also now been a second modal added before full submission that allows the user to confirm that the link they are putting in the submission is desired and to reconfirm

## Related PRS (if any):
This frontend PR is related to the #2703 Frontend PR of requiring the link for submission
…

## Main changes explained:
- New confirmSubmitModal State: controls visibility of the second confirmation modal.
- Second Confirmation Modal: Shows the link the user pasted and asks for a final confirmation before submitting
- submitReviewRequest() Update: Instead of submitting directly, it now shows the second confirmation modal.
- handleFinalSubmit(): This handles the final submission after the user confirms in the second modal.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard
6. verify that when submitting a task for completion without a VALID link it blocks you
7. verify that when submitting a task for completion WITH a valid link it asks for you to confirm and shows a working hyperlink to your submission
8. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/4e557700-f604-49c0-9399-1328c843bc57

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by AshishNags — APPROVED** [review]
Approving this PR, double confirmation working as expected.
Screenshot 2024-10-16 133401
Screenshot 2024-10-16 133431
Screenshot 2024-10-16 133445

**Comment by samarth9201** [comment]
Reviewed the code and verified the changes.
Screenshot (82)
Screenshot (83)
Screenshot (84)
Screenshot (85)

**Comment by zhiminV** [comment]
Code Review:
1. I tested various links, including:
- Empty links
- Links without 'https://'
- Correct links that are less than 20 characters
- Correct links with empty spaces

All these cases return the same error message: "Please enter a valid URL starting with 'https://.'" Would it be more informative to display different error messages for each case?

empty_link
no_https
correct link_butless than 20 characters
correct link_but with empty space

2.  It accepts http:// links.
http_work

3. Show information of valid link for confirm
valid link for confirm

4. The functionality works well in dark mode.
work on dark mode

**Review by zhiminV — APPROVED** [review]
1. I tested various links, including:

- Empty links
- Links without 'https://'
- Correct links that are less than 20 characters
- Correct links with empty spaces
All these cases return the same error message: "Please enter a valid URL starting with 'https://.'" Would it be more informative to display different error messages for each case?
empty_link
no_https
correct link_butless than 20 characters
correct link_but with empty space

2. it also accepts http:// links.
http_work

3. display information confirming a valid link
valid link for confirm

4. The functionality works well in dark mode.
work on dark mode

**Review by Jingyii800 — APPROVED** [review]
I have tested this feature and it worked as expected. It has a double confirmation for task link when submitting for review.

https://github.com/user-attachments/assets/d91200d7-a8e7-4f5d-99b4-db0dba71e482

**Review by shashankhv — APPROVED** [review]
Tested the PR and confirmed the double confirmation feature for the task link is working as expected. Approving the PR.

[Howie-PR.webm](https://github.com/user-attachments/assets/05e2a9f9-95d8-494b-a7b5-d5fe97f1eba0)

**Comment by sheetalmangate** [comment]
I'm trying to test this PR locally but am having trouble generating a scenario. I can't seem to find the "Submit for Review" button.

PR2787-testing-data-issue

**Pull request merged**
