### PR TITLE
Kurtis ~ re-implement 'add start date to user management table' with my fix from pr1278

### PR DESCRIPTION
**Pull request by KurtisIvey**
<h1 align="center">Adding Start Date to the user management table</h1>

## Description
This pull request is a continuation of pr1278 due to it going stale despite the fix being 100% available. Therefore, I went ahead and implemented the fix, so this small feature could be added. This fix was the proper handling of the props.user object. All these changes were implemented off of the current frontend dev branch from 10/02/2023

## Related PRS (if any):
This frontend PR is a continuation of [pr1278](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1278) as it has gone stale

## Main changes explained:
- Implementation of start date in the user management table
- Implementation of my fix to show the start date through proper props usage

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin/owner user
4. go to dashboard→ other links→ user management -> pause any user and verify start date shows
5. verify functionality through pausing volunteer (feel free to include screenshot here)

## Screenshots or videos of changes:

<h4>Before without start date column:</h4>

Start date before

<h4>After with the start date column changes:</h4>

Start date in usermanagement table

### CODE REVIEW

**Review by navneeeth — APPROVED** [review]
Hello, @KurtisIvey! I tested your PR and it works as expected! 
Navigated to `Dashboard-> Other Links-> User Management` and paused a Volunteer account. Upon pausing the user, the start date shows up. Good implementation!

### Test:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/709978ff-8b07-4a14-9ddc-7fbfd07d99be

**Comment by Vishala09** [comment]
Working perfectly! Great Job!!

Pausing a volunteer updates Pause Date and End Date appropriately
Resuming a volunteer removes Pause Date and End Date appropriately
Applying an PAST DATE gives the appropriate error message
I was able to pause an ADMIN and an OWNER too . I hope that is allowed.

Please find my video testing here:
[Untitled_ Oct 03,2023 2_46 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/87667a07-1875-48a8-abfd-4709254ebe99)

**Comment by emunkh404** [comment]
Great job! The following functionalities have been tested and are working perfectly:

Pausing a volunteer correctly updates the Pause Date and End Date fields.
Resuming a volunteer appropriately removes the Pause Date and End Date.
When applying a PAST DATE, the system displays the expected error message.
Additionally, I successfully paused both ADMIN and OWNER accounts, which I hope is within the allowed scope.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/5b0eddc6-8918-4ddd-ac75-4ebb900ec986

**Review by Vishala09 — APPROVED** [review]

**Review by eduhorta — APPROVED** [review]
Hey @KurtisIvey!

Everything seems to be working as expected. 👍 
Tried to enter invalid dates and got an error.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/057b2b19-78e3-4ebb-abbd-2b56a4eaac90

The only detail I see is that when you click on "Pause" -> "Close Modal" -> "Pause" -> "Close Modal" the pause button stays as "..."
I don't think this is related to your PR but that was the only unexpected behavior I found.


image

**Comment by beblicarl** [comment]
This functionality works like intended and the code is great!

[screencast-localhost_3000-2023.10.05-17_46_58.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/010d7f79-e2e1-4796-959a-f6d614849393)

**Review by beblicarl — APPROVED** [review]

**Review by harshidad — APPROVED** [review]
I tested your PR and it works as expected!
Navigated to Dashboard-> Other Links-> User Management . Start date shows up.  Great Work!

PR#1369_Start_Date

**Review by tsunami776 — APPROVED** [review]
Hi @KurtisIvey, I followed the steps and tested with an admin account. I agree that `props.user.createdDate` should be used here for start date column. Everything works as described in the PR. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/af2260ca-c570-486e-ab41-aaaeb0e75d7d

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
