### PR TITLE
Howie accurate end date

### PR DESCRIPTION
**Pull request by HowieMiao**
# Description
If a person stops working without notice, or is activated and deactivated at some point in the future, their end date is the day I deactivate them. This is not accurate. A person’s end date should be the last week they contributed hours. 
Making a person inactive should have the software check for the last week they contributed hours and set the last day of that week as their end date. 
This should be reflected in these 3 areas:
Profile Page
Reports → Reports → People → Their report page
Other Links → User Management page

## Main changes explained:
- Updated timeEntries.js to add getTimeEndDateEntriesByPeriod to return day with time entries based on date range
- Updated userManagement.js so when a user is set to inactive, calls getTimeEndDateEntriesByPeriod to find last week worked and set End Date as the last day they worked. If no work history is found, sets the user's End Date to the date their account was created.
- Updated UserProfile.jsx so that when a user is toggled inactive from their profile, getTimeEndDateEntriesByPeriod is also called to set the End Date as the last day they worked. If no work history is found, sets the user's End Date to the date their account was created.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links→ User Management Page
6. verify that when a user WITH work history is set to inactive, their end date is set to the last week they worked, not current date
7. verify that when a user WITHOUT work history is set to inactive, their end date is set to the date their account was created
8. verify that when a user is set to inactive from their user profile as well (http://localhost:3000/userprofile/{userid}) 
image
That the end date reflected is also the same as expected above
9. Make sure the end dates reflected are all the same in Reports, User Management, and the User Profile -> Volunteering Times tab

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/3ba9acdc-81e3-4ae6-abaf-4d8a8787b56e

https://github.com/user-attachments/assets/f769883e-9141-4eaa-9fa7-c8483ff0ce73

## Note:
If you don't have accounts with/without work history
Howie Volunteer has work history the week of July 27th
Howie test has NO work history

Feel free to try out with these accounts

There is a inaccuracy bug with start dates sometimes between Reports and User Managment that has been noted but not a bug with this PR

I have had some issues with this version of Development where the User Profile doesn't always save when made inactive, this is NOT from this PR.

### CODE REVIEW

**Review by Jingyii800 — CHANGES_REQUESTED** [review]
I have tested this PR and it works well. I logged in with an admin account and accessed the user management dashboard. I selected two volunteers to set as inactive. For the volunteer with a work history, the end date displayed as the last Saturday they contributed. For the volunteer without any work history, the end date showed as the enrollment date. However, there is an issue where the webpage cache should be cleaned and refreshed immediately after changing the user status. Otherwise, the user management page continues to display the old status, despite the profile being updated. Please find more details in my second video.

https://github.com/user-attachments/assets/86354d26-04d3-43a9-8c1e-1098fabf63e4


https://github.com/user-attachments/assets/62a2ffe1-f138-4b0d-831e-ad05e8d6ca18

**Comment by arunsrao9** [comment]
I have tested the PR according to the instructions and for the volunteer with a work history, the end date displayed as the last Tuesday.
Screenshot 2024-08-01 at 6 04 59 PM
Screenshot 2024-08-01 at 6 04 28 PM
Screenshot 2024-08-01 at 6 04 21 PM

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey Howie ,
I have reviewed the PR and i found a bug in the implementation  it's working fine when we try to inactive a user from the user management page but when we try to inactivate a user from a user profile page it sets the end date as today.
image

image

Thank You

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
I added hours for a profile and tried to set it to inactive. But the final day shown is in future? Please fix that. Refer to video for more. Please let me know if I am missing anything here.

https://github.com/user-attachments/assets/f8e1e990-726f-4fa9-a0c9-3dbc7186faa7

**Review by manikittu810 — CHANGES_REQUESTED** [review]
Hello @HowieMiao 
Everything works good when done from user management. But when some one visits the profile and makes the user inactive , then the results are varying.  Same happened with the volunteering times as well. Below are the screenshot for non working times and video attached for the working time.


https://github.com/user-attachments/assets/7e4897cf-5951-464d-8b04-9d33812d4cf3



https://github.com/user-attachments/assets/54b93035-3e44-447c-a2e7-3749c27741d1

Screenshot 2024-08-02 at 6 33 52 AM

Thank you.

**Comment by souravwalke** [comment]
I have tested this PR and it works well. I logged in with an admin account and accessed the user management dashboard. I deactivated a user with and without work history and the end date works as expected in all places.

https://www.loom.com/share/f66c528347fe4512a76af3dbc19e2a4d?sid=11d28b95-4be2-4077-9223-623778c716d5

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected.
Screenshot 2024-08-04 at 9 32 12 PM
Screenshot 2024-08-04 at 9 33 42 PM
Screenshot 2024-08-04 at 9 36 18 PM

**Comment by HowieMiao** [comment]
@Pranay-ai @JatinAgrawal94 @manikittu810 

PR Has been updated to reflect the changes requested:

No longer does it return the last Saturday but the last day worked instead, this should fix the issue of the "Future End Date" as well as make the End Date more accurate

Bug Fix has been added to the user profile page so that when inactivity is toggled it should be an accurate expectation as if used on the User Management Page

Please Note: I have had some issues with this version of Development where the User Profile doesn't always save when made inactive, this is NOT from this PR.

**Review by adityasure9 — APPROVED** [review]
Hi @HowieMiao,

The PR works accurately. I followed the testing steps, and the volunteer's end date is shown as expected.




One minor issue I noticed is that on the report page, the dates are showing differently than expected. I'm not sure if this is a significant concern, but I wanted to bring it to your attention for further consideration.



Overall, great job on this fix!

**Review by manikittu810 — APPROVED** [review]
Hello @HowieMiao 
I have observed the changes that you have made. Everything is working as mentioned.
Screenshot 2024-08-11 at 2 49 12 PM
Screenshot 2024-08-11 at 2 52 57 PM
Screenshot 2024-08-11 at 3 04 11 PM

Thank you.

**Comment by Lemonnycodes** [comment]
Hi,
I have reviewed the  this PR, and everything works as described

Tested Areas:
Profile Page: The end date reflects the correct last contribution week.
Reports → People: The report page shows the accurate end date.
Screenshot 2024-08-12 195304

User Management Page: The end date is properly displayed here as well.

Verified  (Volunteer and Admin) : 
User with Work History:
Screenshot 2024-08-12 185344

User without Work History:
PR Admin

Deactivation from Profile:
Screenshot 2024-08-12 185456

**Comment by Lemonnycodes** [comment]
Hi,

I have reviewed the changes in this PR, and everything works as described. 
Tested Areas:
Profile Page: The end date reflects the correct last contribution week.
Reports → People: The report page shows the accurate end date.
Screenshot 2024-08-12 195304
User Management Page: The end date is properly displayed here as well.

User with Work History:
Screenshot 2024-08-12 185344


User without Work History: 
PR Admin

Deactivation from Profile: 
Screenshot 2024-08-12 185456

**Review by Pranay-ai — APPROVED** [review]
Hey @HowieMiao 
I have tested the PR again after the changes and the Functionality is Working as expected.

**Review by Parth-tech — APPROVED** [review]
Hey Howie,
The PR works well and the required functionality is met. Great job.

`Image References:`

Screenshot 2024-08-15 at 6 35 10 PM
Screenshot 2024-08-15 at 6 35 35 PM
Screenshot 2024-08-15 at 6 36 09 PM
Screenshot 2024-08-15 at 6 37 02 PM

**Review by SMitta11 — CHANGES_REQUESTED** [review]
I reviewed the PR and login to admin account and used howie volunteer and test account to test this PR.
When I set howie test account to inactive as it has no work history it showed startdate as end date which is expected result:
Screen Shot 2024-08-17 at 6 53 55 PM
And then I set howie volunteer account to inactive and it shows end date as Jul 23:
Screen Shot 2024-08-17 at 6 53 37 PM
Then I checked user profile and it shows same end date for howie volunteer user:
Screen Shot 2024-08-17 at 6 57 21 PM
But when I checked reports the end date is 22nd July for howie volunteer user which is incorrect:
Screen Shot 2024-08-17 at 6 59 31 PM

**Pull request merged**
