### PR TITLE
Dhrumil - Added tests cases for UserManagement.

### PR DESCRIPTION
**Pull request by ddshah878**
Description
Unit test for src/components/UserManagement/UserManagement.jsx

## Main changes explained:
•	Added a new file under __tests__ called UserManagement.test.js
•	The list of test cases for `UserManagement`
- renders UserManagement component without errors
- calls `getAllUserProfile` and `getAllTimeOffRequests` on `componentDidMount`
- updates state when `onFirstNameSearch` is called
- calls `updateUserStatus` when `onPauseResumeClick` is called with status 'Active'
- sets `activationDateOpen` to true and `selectedUser` when `onPauseResumeClick` is called with status not 'Active'
- updates state when `onActiveFiter` is called with 'active'
- opens new user popup when `onNewUserClick` is called 

How to test:
1.	check into current branch
2.	do npm install and npm test UserManagement.test.js
3.	check if all test cases pass without any error.

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture2762

**Review by Ankuriboh — APPROVED** [review]
All tests passed on my end.

**Comment by pallavithorat** [comment]
All test cases have passed. Please see the attached screenshot for reference.
PR#2762

**Comment by lucy-xfl** [comment]
image
All the test cases have passed. Here is the screenshot.

**Review by lucy-xfl — APPROVED** [review]

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and all test cases passed successfully

Screenshot 2024-10-08 161159

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and all test cases passed successfully.

Screenshot 2024-10-09 215022

**Review by slidracoon72 — DISMISSED** [review]
#2762 
@ddshah878 
I have tested this PR and all test cases pass successfully.

PR 2762

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (225)

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — DISMISSED** [review]

**Comment by geetamatkar** [comment]
Hi,
I tested this PR and all test cases have passed.

PR2762

**Comment by tharunaa-1** [comment]
All the test cases passed!

image

**Comment by SatyashanthiT** [comment]
I have reviewed and tested this PR, including the unit tests for the UserManagement component. All test cases passed successfully, and the functionality works as expected.
image

**Comment by mianmiantea2019** [comment]
All the test cases passed!

image

**Review by CodewithKoushica — APPROVED** [review]
Reviewed and tested the new unit tests for UserManagement.jsx, and everything is working as expected. All tests run successfully without any errors. Nicely done!

Screenshot 2024-10-31 at 3 03 57 PM

**Review by vijay10pk — DISMISSED** [review]
All the test cases passed.
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
