### PR TITLE
Chengyan phase2 reusable purchase item form frontend

### PR DESCRIPTION
**Pull request by ChengyanOo**
# Description
This update significantly enhances the purchase request component, emphasizing better reusability and completing the "Reusables: Purchase Request" feature. It streamlines the workflow and improves the application's efficiency and maintainability.

## Related PRS (if any):
This frontend enhancement is coupled with backend changes found in PR [#758](https://github.com/OneCommunityGlobal/HGNRest/pull/758).

## Main changes explained:
- **Refactoring**: The material purchase request form has been refactored into a reusable component, streamlining the development process and improving maintainability.
- **Redux Workflow**: A new Redux workflow has been implemented to support the reusable items purchase request form, ensuring a more robust and scalable state management solution.
- **Testing and Verification**: The reusable items purchase request form has undergone thorough manual testing to ensure its functionality within the application.

## How to test:
1. Begin by switching to the `Chengyan-Phase2-Purchase-Reusable-Record-Backend` branch in the backend repository [here](https://github.com/OneCommunityGlobal/HGNRest/pull/758), and start the server.
2. Switch to the current branch on the frontend.
3. Run `npm install` followed by `npm run start:local` to initiate this PR locally.
4. Ensure you clear the site data/cache before proceeding.
5. Login with an admin user account.
6. For a guided test, refer to the detailed walkthrough video provided.
7. Navigate to `BM Dashboard → Reusables → Purchase Manual test` at `http://localhost:3000/bmdashboard/reusables/purchase` to test the functionality firsthand.
8. Review the code changes to spot potential areas for improvement or any code smells.

## Screenshots or videos of changes:
Screenshot of the updated purchase request form
https://www.loom.com/share/816ed66b7bbf41e5b7f11616d1680e98?sid=f5fe006e-f075-47fa-84e4-ef1e423db8ca

### CODE REVIEW

**Comment by nnamdixobi** [comment]
Tested as instructed and everything looks good frontend wise. No errors were find and functionality works as expected 
video: https://www.loom.com/share/b45c33a10d0044e0b6e96cf57d641aef

**Review by ShengjieMao — DISMISSED** [review]
The feature worked as expected and updates mentioned in the instructions were all fulfilled. The updates in the backend worked smoothly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/89728909-6f5e-4de3-8071-bcf8501f2642

**Review by XiaohanMeng — DISMISSED** [review]
Hi, I tested this PR and all worked as intended. The update is seamless.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/467541f4-3503-46b4-a70a-12cd3a5ae1b9

**Review by skaush21 — APPROVED** [review]
Feature implemented works
* logged in as admin
* navigated to bmdashboard, logged in
* navigated to reusables/purchase
* tested drop down menus, counter, and submit button. 
* feature works
* took a look at the code, found no issues.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/3baf6deb-869a-4559-885d-40a03b822e35

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/cd013f15-cc63-4a97-b807-ac13bf162b5d

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.03.08-15_22_32.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/c2c6b4db-a081-464d-8e70-5939c06c5b2c)

**Review by beblicarl — DISMISSED** [review]

**Comment by dhairya-mehta** [comment]
This functionality works as intended and the code is great
image

**Review by sucheta90 — DISMISSED** [review]
Hello @ChengyanOo , I have reviewed this PR and the functionality of this PR works as intended for both Frontend and Backend. The form can not be submitted until filled out. On submitting the form, I see a Toast - mentioning that the purchase request was successful. The items were listed in the redux- state. Great work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/87daba83-6559-49a1-94a8-853e1be8314c

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
