### PR TITLE
Peterson_impl_improve_user_Management_page_search_function_to_include…

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request was crafted with the intention of enhancing the input fields responsible for filtering the users displayed in the table on the user management page. Previously, when typing a user's name, it would appear in the table. However, if there was an extra space at the end of the name, the user would disappear from the table. This issue has been addressed in this pull request.

## Related PRS (if any):
None
…

## Main changes explained:
The user management component has been modified to improve the input responsible for filtering users.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log in as an administrator or owner
5. go to other links→ User Management
6. Please enter something in all input fields for first name, last name, search, and email, with spaces added at the beginning or end.
7.  Please enter numbers in input fields for Wkly Committed Hrs or search, with spaces added at the beginning or end

## Screenshots or videos of changes:
Before my improvement: 
a

After my improvement:
Improve User Management page search function to include spaces

## Note:
None

### CODE REVIEW

**Review by hbodgal — APPROVED** [review]
image

It works as metioned. The users are being displayed with spaces in search text as well.

**Review by MinSun0814 — DISMISSED** [review]
The search now works with space before, in between and after the input for all input fields.
image

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account. I can see my search result no matter how many spaces I have in between letters. Good work
Screenshot 2024-05-02 at 8 22 12 PM
Screenshot 2024-05-02 at 8 21 50 PM
Screenshot 2024-05-02 at 8 21 46 PM

**Review by peter6866 — APPROVED** [review]
Changes work as expected.
Not sure if it's related but searching with first and last name together wouldn't work.
image
image
image

**Review by Sandhya1236 — APPROVED** [review]
I have successfully tested the enhancements to the input fields for filtering users on the user management page. The issue where users would disappear from the table if there was an extra space at the end of the name has been resolved. The main changes involved modifying the user management component to improve the input filtering functionality. After checking into the current branch, running npm install, and starting the application locally, I cleared the site data and cache. Logging in as an administrator or owner, I navigated to Other Links → User Management and entered text with spaces at the beginning or end in all input fields for first name, last name, search, and email. I also entered numbers with spaces in the input fields for Wkly Committed Hrs and search. The filtering functionality worked correctly, displaying the users as expected. All tests confirmed the successful enhancement of the input fields.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/79351059/11e4f478-4acb-4a84-baab-06a4c6559242

**Review by nyelmela — APPROVED** [review]
I have tested this PR 2197 by running the application locally, clearing site data, and logging in as an administrator or owner. I navigated to User Management and entered data with spaces added at the beginning or end in all input fields for first name, last name, search, email, and numbers for Wkly Committed Hrs. Everything works perfectly fine. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/afd4ead7-b82e-4f8d-b753-dd4a777bb574

2197(Peterson_impl_improve_user_Management_page_search_function_to_include_spaces)

**Review by Pranay-ai — APPROVED** [review]
Hey @peterson337 
The PR is working as Expected
image
Thank You for the Changes

**Review by manikittu810 — DISMISSED** [review]
Hello @peterson337 
Search works for  input with spaces in between, before and after.

https://github.com/user-attachments/assets/2ab5efb6-93de-462a-948d-4ebaea72b404

Thank you.

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by sri0606 — APPROVED** [review]
@peter6866 , The search functionality works seamlessly. 

https://github.com/user-attachments/assets/b854535b-6c62-4b54-b908-8c45c3e3c523

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
