### PR TITLE
Kaixiang - Create 24/48/72 hours button on team member tasks tab

### PR DESCRIPTION
**Pull request by KaixiangGU**
### **Description:**
 Implement the 24/48/72h buttons to show the time logs during this period. 
Ex: If the user click 24hours button on May 6, it will fetch time log from May 5 - May 6 (May 6 included).
     If the user click 48hours button on May 6, it will fetch time log from May 4 - May 6 (May 6 included).
     and so on...

### **Mainly change explained:**
1. Restructure the code in `teamMemberTasks `component. 
2. Created 24/48/72h buttons, view/hide icon, delete icon.
3. Optimize the logic of fetching timelogs data. 
4. Loading animation at the first render of those three buttons. (Fetching data from database).
5. No change on backend.

### **UI explained:**
new UI
1. 24/48/72 buttons: Original status is colored text and border. When selected it turns into colored background and white text.
2. Eye/Eye-Slash icon: It will not show up until you select one of the buttons. Click to show/hide timelogs.
3. Delete icon: Clear the view of time logs, and view of eye/delete icon.

### **How to test**
1. Try three buttons see if timelogs can be correctly displayed.
2. Try the eye/delete icon.
3. Also try other functionalities in this component to make sure everything working well after the restructuring of the code.
4. If you want to display the timelog that you just submitted, you just need to refresh the page.

### CODE REVIEW

**Comment by one-community** [comment]
Needs a description

**Comment by GKD890** [comment]
Hi Kaixiang, I've tested these buttons, works as intended. Just a small user experience related question, I don't think a `garbage` icon to remove the filter is a good idea, it looks like a more dangerous operation to click.

I could be wrong for blow part: as they both remove filter in terms of their functions, it would be a good idea to keep only one `eye` icon for removing filter buttons, which is more intuitive. But since it's a user experience suggestion, it could be just me.

Frontend_PR#800_feedback

**Review by Sneha1b — APPROVED** [review]
Awesome Work! Changes LGTM

https://user-images.githubusercontent.com/29037428/236649217-89c502ba-7e2e-4a17-9ba3-a61067fb22c4.mov

**Comment by EdwinLauM** [comment]
Hi Kaixiang, I tested your new changes and ran into a small problem. The current status is only colored when I click on 72 hrs. Whenever I click on 48 or 24 hours it renders the timelogs but the status is not colored. Aside from that, it works as intended! 

https://user-images.githubusercontent.com/42288987/236652269-1a6c6f2a-3157-44a8-87dc-db2b7d753bb1.mov

**Comment by wang9hu** [comment]
Hi KaiXiang,

I tested the functionality and it works perfectly. Good job!

In terms of the user interface, I kind of agree with @GKD890, the meaning of the trash can icon could ambiguous. I suggest maybe make the time buttons (24h, 48h and 72h) to also work as filter-cancel buttons.

https://user-images.githubusercontent.com/77769556/236652519-347f30da-14a3-45bf-a23f-c0fa15a4d430.mp4

**Review by abdel-lall — COMMENTED** [review]
72h filter showing time entry from the 05/02/23.
Test date : 05/06/23

PR800

**Comment by one-community** [comment]
> 

Yes, please make clicking those buttons again unfilter whichever ones are clicked. Please also keep the hide-all eye icon, so that can be clicked to remove ALL filters. Remove the trashcan. Do this in a separate PR if it isn't super easy.

**Review by yoyoweiii — COMMENTED** [review]
I tested the functionality and it works perfectly. Good job!
Test date : 05/11/23

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/60588210/7d7f416b-995f-4aa5-8eb4-d008149d8ceb

**Comment by KaixiangGU** [comment]
### Updated on 5/11
As discussed with Jae, I removed eye icon and trash bin icon.
To make it simple and clean, the user can click to show and hide timelogs.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98206107/d5458695-e31a-4090-a4e5-66cf415da3f0


Please review it again, thank you.

**Comment by alexander-huerta** [comment]
This review reflects the latest edits after the last commit*

Great Work! I am confirming the following functionality:

1. Clicking the time button filter (24,48,72) will filter and display only tasks in that time range. Clicking the same icon again removes the filter.
2. The trash icon has been removed 

I ran this test on May 12, 8:41
- 24 hour filter- shows logs for May 11
- 48 hour filter- shows logs for May 11, May 10
- 72 hour filter- shows logs for May 11, May 10, May 9

[800_working.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59572783/c74e9417-535f-4c36-8140-872dbcf466b6)


One question though- Jae’s comment on this PR asked to keep the all eye icon and have it remove all filters on click. Was there further communication regarding this feature ? 

I do notice only one time filter can be applied at a time, so a remove all is no longer needed. Which I like! 

Thanks again, nice job.

**Review by alexander-huerta — DISMISSED** [review]
This review reflects the latest edits after the last commit*

Great Work! I am confirming the following functionality:

1. Clicking the time button filter (24,48,72) will filter and display only tasks in that time range. Clicking the same icon again removes the filter.
2. The trash icon has been removed 

I ran this test on May 12, 8:41
- 24 hour filter- shows logs for May 11
- 48 hour filter- shows logs for May 11, May 10
- 72 hour filter- shows logs for May 11, May 10, May 9

[800_working.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59572783/c74e9417-535f-4c36-8140-872dbcf466b6)


One question though- Jae’s comment on this PR asked to keep the all eye icon and have it remove all filters on click. Was there further communication regarding this feature ? 

I do notice only one time filter can be applied at a time, so a remove all is no longer needed. Which I like! 

Thanks again, nice job.

**Comment by KaixiangGU** [comment]
@alexander-huerta Hi Alex, thanks for review. I had a discussion with Jae on Slack. Sorry for confusing.

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @KaixiangGU! I have tested your latest commit. Everything works great. 

Test date: May 12:
24 hr button: shows tasks on May 11 and 12
48 hr button: shows tasks on May 10, 11, and 12
72 hr button: shows tasks on May 9, 10, 11, and 12

I also noticed that clicking on another button without un-clicking the current button would automatically switch to the new view, which offers better user experience. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/ac57ef8c-0367-4a89-b101-89ee31c34d51

**Review by Cirakuze — APPROVED** [review]
Confirming clicking the three buttons show the desired time frame for member tasks. Clicking the selected button toggles it off, and clicking another button while there's one already selected switches to the new time frame.

Couple minor non-blocking requests.
There were some errors in the console log like this:
Screenshot 2023-05-12 at 20 29 28

Adding some more optional chaining like this on lines 22 and 33 of `FilteredTimeEntries` remove those errors:
```
setProjectCategory(res?.data?.category?.toLowerCase() || ''); // lline 22
...
setTaskClassification(res?.data?.classification?.toLowerCase() || ''); // line 33
```

And there's a unique key prop warning for `TeamMemberTasks`.

**Comment by one-community** [comment]
Yes! Thank you all, merging!

**Pull request merged**
