### PR TITLE
Shree create blue square reason scheduler forall fe

### PR DESCRIPTION
**Pull request by Bhagyashree444**
# Description
bug_desc_1

bug_desc_2

## Related PRS (if any):
To test this frontend PR you need to checkout the [#614](https://github.com/OneCommunityGlobal/HGNRest/pull/614) backend PR.

## Main changes explained:
- Update file BlueSquareLayout.jsx to add conditions on accessing the scheduler when there are no blue squares present.
- Update file ScheduleReasonModal.jsx to change text,add buttons, create flag to track   reason edits, add placeholder, title.
- Create file ScheduleReasonModal.css

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally. The frontend is up and running.
3. To save the reason - either add a new reason or edit an existing one.
4. Look and focus only on the text changes and FAQ button (no action/text is expected), please ignore other css. 

## Screenshots or videos of changes:
Before :
Before

After :
After

### CODE REVIEW

**Comment by ptrpengdev** [comment]
The code base is outdated. Please do "`git pull origin development`" to sync with the latest code from development branch before merging.
pr641-pullDev

**Review by ptrpengdev — DISMISSED** [review]
Looks good to me. 
Functionality tested:
- "Schedule Blue Square Reason" Button is functional
- Text contents match to description from PR 
- Error message -"**The selected day must be a sunday so the code can work properly**" is functional when incorrect date selected
- Success message is functional
- Gmail API is functional

Addition note:
For the message, I know the PR description doesn't have the "sunday" capitalized. But, I personally think it would be great to have it capitalized. Other than that, all functions work as expected.

**Comment by keyunhuangg** [comment]
1) **Text Changes Verification**: checked and can confirm that all the text changes made in this PR are accurate
2) **Date Selection**: It's working as intended: an error is appropriately triggered when any date other than Sunday is selected.
3) **Buttons**: The 'Close' and 'Save' buttons are both functional and responsive. I observed  the FAQ button is present as expected, and it currently does not lead to any destination.

**Review by keyunhuangg — DISMISSED** [review]
1) **Text Changes Verification**: checked and can confirm that all the text changes made in this PR are accurate
2) **Date Selection**: It's working as intended: an error is appropriately triggered when any date other than Sunday is selected.
3) **Buttons**: The 'Close' and 'Save' buttons are both functional and responsive. I observed  the FAQ button is present as expected, and it currently does not lead to any destination.

**Review by pika-chu11 — DISMISSED** [review]
- _Schedule Blue Square Reason Button_  has no issue
- Description shows correctly on the page of schedule a time
- Error message shows when dates other than Sunday is selected
- Scheduling success when the date is correct and a successful message will pop up and notify that.

Everything works as expected! Good job! @Bhagyashree444 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/192ba94d-c24e-4f9b-aa65-0d22441e4484

**Comment by Changhao3220K** [comment]
Schedule Blue Square Reason Button works perfect
Description of reason show properly
Error message shows correctly when date is not propetly selected
Screenshot 2023-11-16 at 8 05 55 PM
Screenshot 2023-11-16 at 8 06 35 PM
Nice job @Bhagyashree444

**Review by ZichanYang324 — DISMISSED** [review]
(1)**Text change**: The text for the blue square has been changed according to the requirement. 
(2)**The top form**: The top form has been updated as "_Choose to use a blue square_".
(3)**Updated the text for this feature**: All the text has been updated according to requirements and displayed.
(4) **Buttons**: The close/save button can response well, I don't know what should be displayed after choosing the FAQ button, it just closed this form. 

Everything is perfect, good job!

Screenshot 2023-11-16 at 10 19 42 PM


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86720318/eca56da4-7f2c-431a-a5a5-190a3d25ada3

**Review by Shuhua-L — COMMENTED** [review]
Great job, @Bhagyashree444 👏

The Scheduler modal looks fantastic, meeting all expectations with its descriptive text, Save/Close buttons, and error and success messages!

As I mentioned in the BE PR, my only concern is with **`.gitattributes`**. You can find details and screen recording in the BE [review](https://github.com/OneCommunityGlobal/HGNRest/pull/614#pullrequestreview-1736035877).

**Review by KavyaAlla — DISMISSED** [review]
Hi @Bhagyashree444 , I have run this PR with PR#614 and the blue square reason scheduler is working as expected.
Details:
When I select a day other than sunday, "You must choose the Sunday YOU'LL RETURN as your date. This is so your reason ends up as a note on that blue square." message is being displayed.

When I select a sunday before todays date, "You should select a date that is yet to come" is being displayed.

When I select a future sunday my reason is being saved and an email is being received to the email id.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/be1f4ef5-fbf9-4658-8f5c-e109b6f10edf

Screenshot 2023-11-16 at 9 56 51 PM

**Review by Haoj1 — COMMENTED** [review]
@Bhagyashree444 Looks good to me!
No problem with the blue square reason button on the schedule
Instructions on the schedule page display correctly
Error message displays when a date other than Sunday is selected
When the date is correct, scheduling is successful and a success message notification pops up.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/d4318358-1673-4dd7-83a5-02c070e909c9

**Review by Shuhua-L — APPROVED** [review]
Looking good overall! Appreciate your effort! 🙌

**Review by Haoj1 — APPROVED** [review]
@Bhagyashree444 looks all good, comments is given

**Review by ptrpengdev — APPROVED** [review]
lgtm. All functions tested.

**Review by lichanghaogit — APPROVED** [review]
Schedule Blue Square Reason Button works perfect
Description of reason show properly
Error message shows correctly when date is not propetly selected
Screenshot 2023-11-16 at 8 05 55 PM
Screenshot 2023-11-16 at 8 06 35 PM
Nice job @Bhagyashree444

**Review by keyunhuangg — APPROVED** [review]
Due to some changes it became a comment instead of a approval here was my init comment link:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1542#pullrequestreview-1735609201

Text Changes Verification: checked and can confirm that all the text changes made in this PR are accurate
Date Selection: It's working as intended: an error is appropriately triggered when any date other than Sunday is selected.
Buttons: The 'Close' and 'Save' buttons are both functional and responsive. I observed the FAQ button is present as expected, and it currently does not lead to any destination.

**Review by ZichanYang324 — APPROVED** [review]
I just approved the pull request yesterday, I did the unit test and all the features seemed perfect, and here is the link to my pull request review.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1542#pullrequestreview-1735998168

**Review by Hemsharavanan — APPROVED** [review]
- Save and edit blue square operations works perfect.
- Error handling functions well, triggering appropriate error messages when selecting past or non-Sunday dates, enhancing user guidance. 
- Great work Shree!
- Below is the video of functionality testing
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/28252459/f1be797c-029b-4920-84c2-0ff1c1567e05

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by cvtqx — APPROVED** [review]
Everything works and looks as described. I can't schedule for a Sunday or a time in the past.
Here is a video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/832843e5-db85-4306-bdfd-07efb7529d04

**Comment by wanglu1207** [comment]
shree_create_blue_square_reason_scheduler_forall_FE2
shree_create_blue_square_reason_scheduler_forall_FE1
Good job! Everything works as intended!

**Review by pika-chu11 — APPROVED** [review]
Re-approve due to changes.

- Schedule Blue Square Reason Button has no issue
- Description shows correctly on the page of schedule a time
- Error message shows when dates other than Sunday is selected
- Scheduling success when the date is correct and a successful message will pop up and notify that.

**Pull request merged**
