### PR TITLE
John Add popup “i” icon to Weekly Summaries Reports page

### PR DESCRIPTION
**Pull request by Cavein254**
# Description
Screenshot 2024-02-02 224055
## Related PRS (if any):
None
…

## Main changes explained:
- Added editable "i" component by owner

…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to Admin Login → Reports → Weekly Summaries Reports
6. On this page the description “i” popup should be visible on the page
7. log as any Owner
8. go to Admin Login → Reports → Weekly Summaries Reports
9. On this page the description “i” popup should be visible on the page
10. "i" popup should be editable on click

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/0f3976b8-5bc7-436a-b75d-60fc75605d01

### CODE REVIEW

**Review by TareqMia — DISMISSED** [review]
Hi @Cavein254, I reviewed this PR and everything looks good. Logged in as Admin and Owner and the icon is there for both. Good work 👍 
Screenshot 2024-02-10 at 11 05 02 AM
Screenshot 2024-02-10 at 11 05 14 AM

**Comment by galgalinidhi** [comment]
Hi @Cavein254, I tested your PR and the 'i' icon displays the popup for both Admin and Owner accounts. However, I see that the popup isn't editable for the Owner account. I have attached a screen recording for your reference. Please let me know if I'm missing something. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/48abf4e5-325f-4fdf-a8d7-1d4fbe096f0f

**Review by TapanPathak — DISMISSED** [review]
Hi, I reviewed your PR. I logged in as Admin and see that 'i' button pop up is not editable. 
 
Screenshot 2024-02-14 at 11 43 43 AM

Then I logged in as Owner and can edit the 'i' pop up content. 
Screenshot 2024-02-14 at 11 59 43 AM

Note - It took a lot of time to load the weekly summary page due lots of data, hence it was slowing the app down.

**Review by chrischenlixing — CHANGES_REQUESTED** [review]
image
Hello, I think when you log in as an admin, you are not able to edit the user info. Also, should the text on the top of the modal be 'Core TeamInfo Information Page' or something else?

**Comment by skaush21** [comment]
Tried testing the icon but couldn't, whenever I click on the icon, my web page just freezes. Unable to test feature.

**Review by XiaohanMeng — CHANGES_REQUESTED** [review]
Hi, I have tested this PR with the latest development backend, and it appears to be not functioning correctly. Specifically, when I log in as the owner role, the 'i' component does not respond. Please refer to the attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/c84b5e6a-9d1a-4905-a239-6fce5c3365f5

**Comment by Cavein254** [comment]
> does

@XiaohanMeng kindly check if the error is fixed

**Comment by Cavein254** [comment]
> image Hello, I think when you log in as an admin, you are not able to edit the user info. Also, should the text on the top of the modal be 'Core TeamInfo Information Page' or something else?

@chrischenlixing kindly check if the error is fixed on your end

**Review by yvonnep165 — CHANGES_REQUESTED** [review]
Hi @Cavein254, I have tested this PR with the latest development backend. But when i log in with the admin account, the 'i' component does not respond and nothing shows up. Actually the whole page is responding very slowly. Please refer to the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/cfb23fa3-c34a-44e3-be3b-96a68cb9860d

**Review by anandsesha — CHANGES_REQUESTED** [review]
Hi, I have tested your PR and I am facing the same issue mentioned by [yvonnep165](https://github.com/yvonnep165) above. When I login with an admin/owner account the weekly summaries pages take long time to load and when the "i" icon is clicked, the popup is not visible. No particular console error seen. The page seems to be frozen.

Screenshot (853)
Screenshot (854)

**Review by SRamen1999 — CHANGES_REQUESTED** [review]
This PR does not work as intended, When I login with an admin/owner account the weekly summaries pages take long time to load and when the "i" icon is clicked, the popup is not visible. There is no console error seen. Also the page seems to be frozen.

admin video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/f1becbad-688f-4e1b-b661-21af3d9a194a


owner video 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/0253dfc8-0656-43da-bc52-556c76682aa1

**Review by jennZhang93 — CHANGES_REQUESTED** [review]
Tested with owner account, but when I click on the 'i' icon, it freezes the page and didn't show any pop up modal. No console error was found as well. I also tested with the development backend branch.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/23b72709-deac-4955-91a1-c56b894e0473

**Pull request closed without merging**
