### PR TITLE
Mengtian_Notification_unittest

### PR DESCRIPTION
**Pull request by Tiantian-C**
# Description
Unit Test for notificationCard.jsx

## Main changes explained:
- Add a unit test for notificationCard.jsx

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. do  `npm test notification.test.js `

## Screenshots or videos of changes:

Screenshot 2024-06-13 at 5 39 04 PM

### CODE REVIEW

**Comment by akshit0211** [comment]
All test cases passed. Good work!

All test cases passed

**Review by akshit0211 — DISMISSED** [review]

**Review by deepthikannan — DISMISSED** [review]
image
All test cases passed.

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and all the test cases passed. Good work.
Screenshot 2024-06-15 at 1 54 06 AM

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and all the test cases are passed!.

PR2353

**Review by jinxyou — DISMISSED** [review]
All the test cases have passed. Great work!
Screenshot 2024-06-15 183723

**Comment by beblicarl** [comment]
All tests passed successfully. Test cases covered specified scenarios

image

**Review by beblicarl — DISMISSED** [review]

**Comment by sahithidhulipala9** [comment]
All test cases passed! 
Screenshot 2024-06-19 180357

**Review by sahithidhulipala9 — APPROVED** [review]

**Comment by iTvX** [comment]
Please fix conflicts:

2024-06-27 at 17 36 54@2x

**Pull request merged**
