### PR TITLE
Ramakrishna fix fetch user history error

### PR DESCRIPTION
**Pull request by Ramaruva**
# Description
image

## Related PRS (if any):
Please use latest development branch in backend
…

## Main changes explained:
- added proper condition for api call for setupinvitationdata in setupinviation component
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user(volunteer preferred) who has permission to see/create users (you can give any user permission using an admin/owner account )
5. Navigate dashboard -> user Management 
6. And absorb you didn't see any fetching Error: Invitation History toast message.
7. Try to repeat the above two steps(5,6) to another usertypes(like mentor, manager) who has permission to see/create users.

### CODE REVIEW

**Review by Kavil-Jain-514 — APPROVED** [review]
I have reviewed the PR and tested with two volunteer accounts with See All Users permission, and on the navigation to the User Management page, I did not receive any Toast message error

image

image

**Comment by Vijeth-V** [comment]
I reviewed the PR in a volunteer Account and I didn't get any toast after navigating to the user management page. It works perfectly well.
Screenshot 2024-06-12 at 11 34 50 PM

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested this PR as Volunteer, Manager and Mentor and didn't get any fetching Error: Invitation History toast message.  The issue is fixed!
PR2349

**Review by nathcarnevalli — APPROVED** [review]
Worked as expected.

image

**Comment by akshit0211** [comment]
It is working as expected. There is no error message. Good job!

no error message

**Review by akshit0211 — APPROVED** [review]

**Review by tianyangL11 — APPROVED** [review]
It work as expected.    So great!

**Comment by sahithidhulipala9** [comment]
No fetching error appeared after granted permissions (to see and create new users) to volunteer. 
PR 2349

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by jinxyou — APPROVED** [review]
I tried fetching user list on three different accounts with different permissions. And it seems no error. Great work! 
Screenshot 2024-06-22 194423

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
