### PR TITLE
Shengwei fix user profile quick setup

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
image

## Related PRS (if any):
This frontend PR is related to the #[1028 ](https://github.com/OneCommunityGlobal/HGNRest/pull/1028) backend PR.
…

## Main changes explained:

- Update file **AddNewTitleModal.jsx** for including new **data validations** on **Team Code** for quick setup modal.
- Update file **AssignSetupModal.jsx** to include new data validations on team/project assignments. Prevent duplicate and invalid data which leads to page crashes. 
- Update file **UserTeamsTable.jsx** to include null value handling for team data to fix issue 'When assigning a title to a new user who does not have a team and project, the page will crash’
- Update file **UserProfile.jsx** to include null value handling for team data and fix the issue that a warning message of “please click on save changes…” displays even after users click on the “save changes” button on the left part of the page
- **Fix bug**: "Please ... Save Changes" message displayed after changes saved.
- **Fix bug**: Quick Setup Modal will not update the team tab's team code field after the quick setup application.
- **Add a feature**:  provide suggestions on team code input change in Quick Setup Modal
- Integrate new team code API

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to user profile -> use the quick setup modal on the left side 
6. Verify that no duplicate project/team is added to the user profile with the use of quicket setup modal.
  - image
  - image

7. Verify that after deleting all project/team data, using the existing quick setup configuration and applying changes will not lead to a page crash.
8. Verify that data validation of  'Add A New TItlte' form is working. E.g. Team code, team name, and project validation should work as expected.
   -  image

9. Verify that 'Add A New Title' is working as expected by saving a new quick setup config.
10. Verify that after saving new info with use of quick setup modal, no warning message of 'please click on save changes…' displayed 
## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi, 

1. Please update the error message : Team Code Does not exist or not found
image
2. Could also share some valid Team codes to test adding a new title
3. While adding a new title, it gives me an error that says " invalid team code", but the confirm button is enabled. When I click the confirm button, the page crashes
image
Ideally the confirm button should be enabled until all the required fields are filled.
4. Please add an auto-fill list to pop up when any team code is being entered, just like how it is for the Team name


Please share video on the changes you've made to make it easier to follow along.  I'd like to test more, but the team code is a blocker, please provide a dummy team code to test. 

Thank you

**Comment by ptrpengdev** [comment]
> Hi, I tried testing this PR and ran into multiple issues,
> 
> 1. Please update the error message : Team Code Does not exist or not found
>    image
> 2. Could also share some valid Team codes to test adding a new title
> 3. While adding a new title, it gives me an error that says " invalid team code", but the confirm button is enabled. When I click the confirm button, the page crashes
>    image
>    Ideally the confirm button should be enabled until all the required fields are filled.
> 4. Please add an auto-fill list to pop up when any team code is being entered, just like how it is for the Team name
> 
> Please share video on the changes you've made to make it easier to follow along. I'd like to test more, but the team code is a blocker, please provide a dummy team code to test.
> 
> Thank you

Hi @KaushikMreddy 

The PR is meant to fix the page crash and incorrectly displayed error message issue in the original implementation. Since you have mentioned all the suggestions, I will also include the enhancements in this PR. I have marked this PR as 'DO NOT REVIEW' for now.

**Review by JatinAgrawal94 — DISMISSED** [review]
Even on selecting team names from the list , it shows team name not found. Please fix that.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/daa80677-8184-497e-a1ca-af84c7884078

**Review by pavanswaroopl — CHANGES_REQUESTED** [review]
Hello,

Great work, but I ran into some issues, firstly, can you please share some test values for 'add a new title option', and when I add a valid name in team assignment, it says team name doesn't exist. steps to reproduce:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/0077114e-6d23-4cc2-a1af-3a06948662ed

**Comment by ptrpengdev** [comment]
> Even on selecting team names from the list , it shows team name not found. Please fix that.
> 
>  PR.2339.mp4

Hi @JatinAgrawal94 

Sorry for the confusion. I had some local changes and forgot to push it to the remote branch. Please re-rest. I also attached a demo video for reference. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/20f78b6d-6c90-4467-87bf-d0987ccd310f

**Comment by ptrpengdev** [comment]
> Hello,
> 
> Great work, but I ran into some issues, firstly, can you please share some test values for 'add a new title option', and when I add a valid name in team assignment, it says team name doesn't exist. steps to reproduce:
> 
>  Screen.Recording.2024-06-29.at.6.35.56.PM.mov

Hi @pavanswaroopl 

Please re-test. I have pushed my latest changes.

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
Ran into a issue when assigning a team. Below video has all the details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/de65e260-9865-4326-86d1-61b2c2f0f967

**Review by vijay10pk — CHANGES_REQUESTED** [review]
I followed the steps to test the changes. As you can see in the below video I am getting a error saying that team name is not valid and also the team code is not auto populating like project assignment or team assignment once I start typing in the input field.
Please refer the video attached.
https://github.com/user-attachments/assets/7eb96ba4-31b2-4d20-8266-141170752bb0

**Comment by ptrpengdev** [comment]
> Ran into a issue when assigning a team. Below video has all the details.
> 
>  Untitled.video.-.Made.with.Clipchamp.2.mp4

Hi @Vigneshwar-Muriki 

Just found out that the issue was caused by the cache data in my local broswer. I have added the allTeamCode in the Team redux store as one of the initial states. I have re-tested the QSC feature in incognito mode.  Please pull the latest frontend code in this PR and the backend PR [1028 ](https://github.com/OneCommunityGlobal/HGNRest/pull/1028).Thanks.

**Comment by ptrpengdev** [comment]
> I followed the steps to test the changes. As you can see in the below video I am getting a error saying that team name is not valid and also the team code is not auto populating like project assignment or team assignment once I start typing in the input field. Please refer the video attached.
> 
>  Screen.Recording.2024-07-12.at.10.41.57.PM.mov

Hi @vijay10pk 

Just found out that the issue was caused by the cache data in my local broswer. I have added the allTeamCode in the Team redux store as one of the initial states. I have re-tested the QSC feature in incognito mode.  Please pull the latest frontend code in this PR and the backend PR [1028 ](https://github.com/OneCommunityGlobal/HGNRest/pull/1028).Thanks.

**Review by nyelmela — DISMISSED** [review]
I have thoroughly tested the current branch by performing `npm install` and running the application locally. I cleared the site data/cache and logged in as an admin user. Using the quick setup modal in the user profile, I verified that no duplicate project/team entries are added. I also confirmed that deleting all project/team data and reapplying the quick setup configuration does not lead to a page crash. Data validation for the 'Add A New Title' form works as expected, including validation for team code, team name, and project fields. The 'Add A New Title' functionality successfully saves a new quick setup configuration. Additionally, no warning message of 'please click on save changes…' is displayed after saving new information using the quick setup modal. All features are functioning perfectly. 

image
image
image
image

**Review by SaiLavanya1 — DISMISSED** [review]
Hi,
When testing the user profile quick setup modal, I encountered an error stating "Team Name Not Exists" when entering a team name. This error appears regardless of the input, indicating a validation issue with the team name. The error prevents the assignment of team and project data to the user profile.  Please review the team name validation logic to resolve this issue.
Screenshot 2024-07-24 at 1 39 22 PM
Screenshot 2024-07-24 at 1 38 56 PM

**Review by jinxyou — APPROVED** [review]
No error message popped when quick setup the user's profile. Even after I deleted all the QSC it works fine. 
Screenshot 2024-07-27 131355
Screenshot 2024-07-27 131401
Screenshot 2024-07-27 131533

**Review by ReinaT5678 — DISMISSED** [review]
Hi, I'm also experiencing the same "Team Name Not Exists" error pop up when I try to add a new title. I attached a screenshot of the issue and as well as the console errors.

Screenshot 2024-07-29 at 5 05 21 PM

**Comment by ptrpengdev** [comment]
Hi Team, 

I just pulled the code from this branch and re-tested the feature without any modification. I was not able to reproduce the issue mentioned in the previous comments.  Video attached.

https://github.com/user-attachments/assets/382acd35-c1bb-4cd0-9512-07c35bcb2981

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
