### PR TITLE
Howie fix team scroll bar

### PR DESCRIPTION
**Pull request by HowieMiao**
# Description
This pull request was opened to fix the bug that the horizontal scrollbar would only be accessible when at the very bottom of the teams page. The solution is now when the window is at a size where the horizontal scrollbar is necessary, the teams table will now resize and fit into the current window, making the horizontal scrollbar permanently usable

## Related PRS (if any):
None
…

## Main changes explained:
Updated Team.jsx to create a new div to wrap the table contents
Updated Team.css to create overflow parameters at certain width margins
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links → Teams 
6. verify that when the window width is dropped below 750px, the horizontal scrollbar shows and is static to the page
7. verify this new feature works in [dark mode]

## Screenshots or videos of changes:
Before:
https://github.com/user-attachments/assets/37d965a6-7370-4c7e-b686-88fec0423b30

After:
https://github.com/user-attachments/assets/ecee578f-8b7e-41ee-b859-6f81d8860ea0

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected. 
Screenshot (144)
Screenshot (145)

**Review by Chetan0606 — APPROVED** [review]
Reviewed the PR everything  looks good.

https://github.com/user-attachments/assets/5d87ba00-288e-487a-ba39-d8a571b9d77d

**Comment by nikethaanand** [comment]
The changes work as expected, a horizontal scroll appears after the width is below 750px and the page becomes static.

https://github.com/user-attachments/assets/edcc8391-4dd7-4b4a-9747-27077f3335bf

**Review by Pranay-ai — APPROVED** [review]
Hey @HowieMiao 
I have tested the PR Works well
image
Thank You

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested this PR.  I have gone through the dashboard→ Other Links → Teams
verified that when the window width is dropped below 750px, the horizontal scrollbar shows and is static to the page. This is working in dark mode also. 

https://github.com/user-attachments/assets/c109df9d-99f3-4881-b32f-8da62f9425d6

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.

https://github.com/user-attachments/assets/1aa7af15-76ab-42f2-9450-eca3f5fed34b

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected and can see the scroll bar for narrow screen size.

https://github.com/user-attachments/assets/9987e458-38e2-4a6e-aac6-ca1f1b5810cd

**Review by Gauravmg6 — APPROVED** [review]
Everything works well! 

Screenshot 2024-07-27 230957

**Review by gowthamdongari — APPROVED** [review]
I have tested the PR thoroughly and everything works as expected.

https://github.com/user-attachments/assets/80263a99-a7d6-4392-9dd6-416ba71f2be1

**Comment by arunsrao9** [comment]
I have tested the PR according to the instructions and everything looks good in light mode:
Screenshot 2024-08-01 at 11 33 48 AM
Screenshot 2024-08-01 at 11 30 51 AM

The dark mode looks good but I think if the scrollbar was a lighter color it'd be better:
Screenshot 2024-08-01 at 11 34 18 AM
Screenshot 2024-08-01 at 11 34 17 AM

But the rest looks good!

**Review by jinxyou — APPROVED** [review]
The window and scroll bar fix seem fine. Great work!
Screenshot 2024-08-03 225306
Screenshot 2024-08-03 225316

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
