### PR TITLE
Shiwani Create a Leaderboard way to see when people are off for the week

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Screenshot 2023-12-18 at 6 10 55 PM

## Related PRS (if any):
Related PRs [PR1542](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1542)+614, [PR1081](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1081)

This frontend PR is related to the [#PR660](https://github.com/OneCommunityGlobal/HGNRest/pull/660) backend PR.

## Main changes explained:
- Added style conditions to check if currentDate was equal to or between timeOffFrom and before timeOffTill date to Leaderboard.jsx, TeamMemberTask.jsx, FormattedReport.jsx
- If the above condition is true, then the color of the name in task, leaderboard, weekly summaries report would be gray if not it will be the default color.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as any user
5. go to View Profile -> click on schedule blue square -> fill in the details -> click submit -> click on dashboard -> check if your name in tasks, leaderboard has changed to gray. You can also check if the name turns to default color if the current date is not between the dates last requested for time off by changing the date in mongoDB for your user.
6. If the logged in user has permission for reports page then verify if the name of the user is in gray under reports-> weekly summaries reports. You can also verify this by logging in as any user that has weekly summaries reports permission to check if the name of the user is grayed out.

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/9a5e009d-b0fa-4b42-b10d-9d62c9435289

## Note:
- Please do also test on how the frontend looks when the current date does not fall between the last time off dates requested and also when the time off dates are preponed or postponed.
- You can also modify dates in mongoDB to test how the frontend looks for different cases.

### CODE REVIEW

**Review by this-journey — APPROVED** [review]
Hello @Shiwani99 !! I reviewed your PR as an owner, admin, and volunteer and everything was working as it should.  Great job!  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/f1144511-593b-45bc-a240-630d16cace41

I do have a couple of suggestions that may be outside this PR, but when I hover over a system generated blue square it covers all of the blue squares and as an owner who may want to edit these or delete them for whatever reason it makes it difficult to see which square I'm choosing.

Hover Issue

Secondly, it may be worth it to add the ability to delete a blue square I've scheduled for myself in case my plans change and I no longer want to use one.  Perhaps once the hours have been logged and the weekly summary submitted it won't be issued, but just in case it may be worth it to add.

Delete Blue Square

**Comment by Shiwani99** [comment]
> Hello @Shiwani99 !! I reviewed your PR as an owner, admin, and volunteer and everything was working as it should. Great job!
> 
> Uploading PR 1722.mov…
> 
> I do have a couple of suggestions that may be outside this PR, but when I hover over a system generated blue square it covers all of the blue squares and as an owner who may want to edit these or delete them for whatever reason it makes it difficult to see which square I'm choosing.
> 
> Hover Issue
> Secondly, it may be worth it to add the ability to delete a blue square I've scheduled for myself in case my plans change and I no longer want to use one. Perhaps once the hours have been logged and the weekly summary submitted it won't be issued, but just in case it may be worth it to add.
> 
> Delete Blue Square

Hi,
Thank you for your review. I didn't work on creating the blue square scheduling modal so this is outside my PR, but I agree about the suggestions you pointed out. I too had difficulty in deleting blue squares because the hovered part took up almost the entire blue square part. I also agree with your second suggestion. I guess you can talk to jae about this and add it to the bugs document.

**Comment by one-community** [comment]
This is excellent! As a followup PR, please also add a way to see if they are off for additional weeks too. Grey with a +1, +2, +3 etc. after their name on the Leaderboard if they've scheduled future weeks off too.

**Comment by one-community** [comment]
> Hello @Shiwani99 !! I reviewed your PR as an owner, admin, and volunteer and everything was working as it should. Great job!
> 
>  PR.1722.mov 
> I do have a couple of suggestions that may be outside this PR, but when I hover over a system generated blue square it covers all of the blue squares and as an owner who may want to edit these or delete them for whatever reason it makes it difficult to see which square I'm choosing.
> 
> Hover Issue
> Secondly, it may be worth it to add the ability to delete a blue square I've scheduled for myself in case my plans change and I no longer want to use one. Perhaps once the hours have been logged and the weekly summary submitted it won't be issued, but just in case it may be worth it to add.
> 
> Delete Blue Square

Yes, these ideas are both excellent. Please add the 1st one to the Bugs Doc and comment on it for my approval. The 2nd one is already included here: 
image

**Review by Alforoan — CHANGES_REQUESTED** [review]
When I cleared data/cache, the leaderboards stopped loading for some reason.

image

**Comment by Shiwani99** [comment]
> When I cleared data/cache, the leaderboards stopped loading for some reason.
> 
> image

This is actually a problem with MongoDB that has been going on for a while, its not related to this PR. I had the same problem a few minutes back and there was an error in the myTeam collection which is why you are encountering this, but it worked fine after sometime.

**Comment by beblicarl** [comment]
Functionality works as intended and the code is great

[screencast-localhost_3000-2023.12.22-16_41_19.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/985b31ed-0f82-42b7-803d-405228580deb)

**Review by beblicarl — APPROVED** [review]

**Review by ilyaflaks — APPROVED** [review]
Everything works as intended. Database:
PR660+1722-compass
Tasks and leaderboard with that user:
PR660+1722-leaderboard+tasks
Weekly summary:
PR660+1722-wk-summary

High quality efficient code! Good job!

**Review by keyunhuangg — APPROVED** [review]
1) Logged as in volunteer and schedule a blue square. Verified the name became gray in leaderboard and under task.

Screenshot 2023-12-23 at 10 34 26 AM
Screenshot 2023-12-23 at 10 34 29 AM

2) Logged in as owner and verified that the name under weekly summaries is gray.
Screenshot 2023-12-23 at 10 39 30 AM

**Review by Alforoan — APPROVED** [review]
My name as a volunteer user was grayed out and it worked as intended. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/8dd563bc-237b-4843-b3bf-13dbd3f53bab

**Comment by mianmiantea2019** [comment]
Logged as in volunteer and schedule a blue square. Verified the name became gray in leaderboard and under task.

image

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
