### PR TITLE
Leo_fix_issue_update_with_updating_existing_password

### PR DESCRIPTION
**Pull request by Chuehleo**
# Description
Screenshot 2023-10-13 151833

## Related PRS (if any):
This frontend PR is related to the [#571](https://github.com/OneCommunityGlobal/HGNRest/pull/571)  backend PR.
To test this frontend PR you need to checkout the [#571](https://github.com/OneCommunityGlobal/HGNRest/pull/571) backend PR.
…

## Main changes explained:
- Update UpdatePassword.jsx for including an eye icon for users to select the visibility of their password …
- Create a showPassword state to manage the visibility
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin or Owner user
4. go to dashboard→View Profile→Update password
5. check if you can change your own password successfully and see if the eye icon allows to hide or show the password
6. login with the new password
7. find an volunteer user you have access to and click on the profile→ Reset Password→…
8. change the password and login as the volunteer user with the new password
9. find a user and click on their profile, see if there is no buttons for the volunteer user to reset others password
10. go to dashboard→View Profile→Update password
11. check if you can change your own password successfully and see if the eye icon allows to hide or show the password

## Screenshots or videos of changes:
Login as volunteer:
Screenshot 2023-10-13 153550
Login as admin/Owner:
Screenshot 2023-10-13 153629

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/c2adce2c-954b-470a-9220-b5c9754d4e6d

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by StrawberryCalpico — CHANGES_REQUESTED** [review]
Hi I tested your PR, for updating own password, the restriction didn't apply(no special character required, see video for detail), but when updating other user using admin/owner account, the restriction applied, however, I cannot test if the volunteer can set other user's password since I can't find other user in the leader board.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/96223e69-6926-4813-85a5-f298e48d7d37

**Comment by Chuehleo** [comment]
> Hi I tested your PR, for updating own password, the restriction didn't apply(no special character required, see video for detail), but when updating other user using admin/owner account, the restriction applied, however, I cannot test if the volunteer can set other user's password since I can't find other user in the leader board.
> 
>  video1945557190.mp4

Hi @StrawberryCalpico, if you can't access other user in the volunteer account, simply add the volunteer account to a team in the teams tab and set other team user as visible in their profile, you will be able to see others in your leaderboard.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/743c9fa5-b528-43ff-ae9a-acf5f7a073c0

**Review by JeffLi117 — DISMISSED** [review]
Changes work as intended. Good job!

On Owner account, I was able to change my own password (and use the eye icon to toggle whether I could see the PW or not):
image

I was then able to find a Volunteer account I had access to, change their password, login, and view another user (as a Volunteer). This is the view I had - with no ability to change anyone's password but my own:
image

Finally, still on my Volunteer account, I was able to change my own password successfully and log back in.

**Comment by Cloid** [comment]
I tested the following and it works fine:
- Admin/Manager/Volunteer updating own password and making sure the password eye icon is visible. 
- Admin changing Volunteer password and logging in with volunteer with new password.
- Admin making new Volunteer, resetting password to new password, logging volunteer with that password
- Volunteer accessing a different volunteer profile and seeing if I'm able to change a different volunteer password (attached is a video trying to do that).


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/c460bc37-7aee-48b3-b171-a2144ac6d40c


Suggestion: 
- Make eye icon show when resetting a volunteer password. Makes it consistent with the UI.
- Show Password requirement message when editing volunteer password 

(The below imagse shows the current difference between "Volunteer password reset" vs "Self-Password Reset"
image
image


Other than that this works for the intended base case and changes. Good job.

**Review by malikjahanzaib — COMMENTED** [review]
Hi @Chuehleo, I have tested this PR locally any all the features that were described work perfectly.  All the functionalities are implemented without any bugs. Although I would suggest some UI changes for the consistency as already suggested by @Cloid:
- Add the password visibility icon (eye) to the Reset Password modal when owner is resetting password for the volunteer.
- In the same modal the password requirements appear only when the owner/admin clicks Reset password, make it appear as the Owner is typing the password(s), similar to when changing own password.

Nice work!!!

Test Rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/e80cbbd1-46f3-4710-b55e-a10b65d410c9

**Review by yangfan2001 — COMMENTED** [review]
Hi, I have reviewed and tested your PR and it functions well.

As an admin user:

- I was able to change my password on the profile page, log in with the new password, and change a volunteer's password on their profile page.
- The hide icon functionality is working as expected.

As a volunteer user:

- I was able to change my password and log in with the new password.
- I was unable to change other volunteers' passwords, which is as expected.
- The hide icon functionality is working as expected.

image
image
image
image
image
However, I encountered some inconsistencies which have mentioned above by @Cloid when logged in as an admin and attempting to change a volunteer's password:

- The hide icon on this page does not match the one on the password update page.
- The notification only pops up after I send the request, which is inconsistent with the behavior on the password update page.

image
In general, all the exepected functions are achieved and is without bug. Great Job!

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Hey @Chuehleo, I want make a request for a change. When I go to reset password for a volunteer user from an admin account, I don't have the functionality of the eye icon. Please fix this and add that functionality. 
</br>
For admin:
pr
pr2
</br>
For volunteer:
pr3
pr4

**Comment by RheaWu1212** [comment]
PR works as it expected, great work! 

Screen Shot 2023-10-14 at 09 42 03
Screen Shot 2023-10-14 at 09 43 08
Screen Shot 2023-10-14 at 09 48 57

**Review by Cloid — CHANGES_REQUESTED** [review]
Forgot to include the status review. I'm not sure if adding the password strong/visibility icon is needed when changing different user password as Admin. Adding this would make it more consistent with UI. (see my comment above)

**Review by ChirayuRai — COMMENTED** [review]
Hey! I went over these changes and it all seems to be working as expected! Logging in as an admin or a volunteer gives the same functionality when updating your own password, including hiding and making passwords visible. It also seems that you cannot update a password if the one you entered is incorrect. Overall it seems to be functioning well!

Screen Shot 2023-10-14 at 6 14 10 PM
Screen Shot 2023-10-14 at 6 21 31 PM
Screen Shot 2023-10-14 at 6 32 38 PM
Screen Shot 2023-10-14 at 6 33 27 PM

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions! Your PR seems working as expected to me. I've tested in the following ways.
1. The "eye" button is working correctly. It displays/hides the password as I click on it.
2. The current password must be provided to update the password.
3. The new password must satisfy the requirement.
4. The new password must match with each other in the two input fields.
5. After updating the password, user should be able to log in with the new password.
I have tested all of these, and they are working as my expectation.
Screenshot 2023-10-15 at 12 29 02 AM
Screenshot 2023-10-15 at 12 27 34 AM

**Review by lacnoskillz — APPROVED** [review]
Hello @Chuehleo 
I pulled both frontand back end codes. Ran npm run build in the back end and was able to see your changes! Nice work

I was able to test reseting passwords for myself and for other users when using a admin/owner accound. I successfully reset passwords using the Other Links > User Management  And going to other user profiles directly. I also Confirmed that Volunteers cant see/ reset other users passwords!



[Untitled_ Oct 17, 2023 5_39 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/c735ba79-7b63-43cd-86fa-e891f2b05954)


[Untitled_ Oct 17, 2023 5_36 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/5caa0041-c3fb-4b2e-84ec-37448b5993c7)

[Untitled_ Oct 17, 2023 5_45 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/d6ba691d-a194-41a2-be6e-2c4f956930e1)

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Hey @Chuehleo, I reviewed the changes per your request. But I don't see the functionality of eye icon, while resetting a volunteer's password from admin account, added to the changes. Could you please add it?

PR 1414+571

**Review by Jiyuanxia — APPROVED** [review]
Hi @Chuehleo , I have reviewed your pull request and tested it. It works as you intended. Well done!

Update owner's own password
Screenshot 2023-10-19 214153

Update another volunteer account's password using owner account
Screenshot 2023-10-19 214029

Access other user's profile using volunteer account
Screenshot 2023-10-19 214135

Update volunteer's account password
Screenshot 2023-10-19 213753

**Comment by AriaYu927** [comment]
Hi @Chuehleo , I've tested your PR and it works as expected.

Owner can change other users' password:
Screenshot 2023-10-26 at 19 15 45

Screenshot 2023-10-26 at 19 20 46

Owner can reset own password:
Screenshot 2023-10-26 at 19 16 46

Screenshot 2023-10-26 at 19 20 14

Volunteer cannot change other's password:
Screenshot 2023-10-26 at 19 17 59

Volunteer can reset own password:
Screenshot 2023-10-26 at 19 19 00

**Review by shubhankarval — APPROVED** [review]
Hey , I re-reviewed the PR and now everything works as intended, great job! 

When Admin updates their password:
Screenshot 2023-11-04 144433
\
When Admin resets volunteer’s password:
Screenshot 2023-11-04 144614
\
When Volunteer updates their password:
Screenshot 2023-11-04 145229

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Review by StrawberryCalpico — APPROVED** [review]
Hi, I tested your PR again, it worked as expected! Great Job!
Owner reset own:
Screen Shot 2023-11-04 at 9 03 20 PM
Owner changed others:
Screen Shot 2023-11-04 at 9 03 40 PM
View from Volunteer:
Screen Shot 2023-11-04 at 9 04 49 PM

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-localhost_3000-2023.11.05-08_07_30.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/0849ddc8-2b9a-4aef-8a65-d5e638204f21)

**Review by beblicarl — APPROVED** [review]

**Review by Cloid — APPROVED** [review]
Hi there,

I tested your new changes with the password eye icon in the following cases.

- Own account updating their own password
- Using Admin/Owner to update separate user profiles.
- Using admin/owner viewing it as a separate user profile's dashboard and updating it through that.

 The code looks great. Overall, it works great - good job on the quick implementation.

edit: added ss
image

**Comment by one-community** [comment]
Thank you all, merging!

**Review by brandta-1 — COMMENTED** [review]
# Review
Unable to test due to the dashboard page becoming unresponsive after ~1 second. Hard Reload and Empty Cache does not restore page responsiveness.

# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/fde123cd-2699-419a-8b34-60a500749cc2

# Error

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at _callee$ (ownerMessageAction.js:14:1)
    at tryCatch (regeneratorRuntime.js:44:1)
    at Generator.<anonymous> (regeneratorRuntime.js:125:1)
    at Generator.next (regeneratorRuntime.js:69:1)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
```
```
Uncaught (in promise) Error: Request failed with status code 400
    at createError (createError.js:16:1)
    at settle (settle.js:17:1)
    at XMLHttpRequest.onloadend (xhr.js:54:1)
```
```
GET http://localhost:4500/api/wbs/user/65d0f8a1cf23bb6228fa9d32 404 (Not Found)
```

```
GET http://localhost:4500/api/tasks/user/65d0f8a1cf23bb6228fa9d32 404 (Not Found)
```

# System
Chrome 121.0.0
Windows 10

**Pull request merged**
