### PR TITLE
EduardoV - create unit tests for the TeamTableSearchPanel component 

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the TeamTableSearchPanel component to confirm whether it working as intended.

## Main changes explained:
- Export file TeamTableSearchPanel.jsx for the test component
- Create file TeamTableSearchPanel.test.js to do the unit tests

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install` to run this PR locally
4. open file src → tests → Teams → TeamTableSearchPanel.test.js
5. run `npm run test src/__tests__/Teams/TeamTableSearchPanel.test.js`

## Screenshots or videos of changes:
This is the result it's supposed to get:

Screenshot_2

If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by DavidC0126 — APPROVED** [review]
I tested the PR and it works as intended. 
Screenshot 2023-09-20 at 10 00 25 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended!

Week4 - PR5

**Review by sxiong5 — APPROVED** [review]
Hey @eduvarjaor, I have ran the test command, and everything LGTM.

Screenshot 2023-09-21 at 12 35 56

**Review by wantingxu7 — APPROVED** [review]
LGTM! good work

**Review by dah00 — APPROVED** [review]
Hey, all tests passed as intended. Great work!
PR1326_tests_passed

**Comment by astrjc0326** [comment]
I tested the test, it works perfectly.  Great Job! [
Screen Shot 2023-09-21 at 12 45 19 PM
](url)

**Review by navneeeth — APPROVED** [review]
Hi @eduvarjaor! Tested your PR and the test results are as expected!

**Review by Bhagyashree444 — APPROVED** [review]
All the test cases passed.

PR #1326

**Review by Jiyuanxia — APPROVED** [review]
Hi @eduvarjaor , I have reviewed your pull request and tested it. It works as you intended. Well done!
Screenshot 2023-09-21 172949

**Comment by Sssky-18** [comment]
Hi @eduvarjaor, all tests are passed, so I think this unit test works as expected.

PR#1326

**Comment by AnishPandita** [comment]
Hey, the tests look great. No errors found. Good job.
Screenshot 2023-09-21 at 4 23 47 PM

**Review by Haoj1 — APPROVED** [review]
@eduvarjaor All tests for TeamTableSearchPanel passed. Good job!

**Review by Chuehleo — APPROVED** [review]
Everything works as intended, great job!
Screenshot 2023-09-21 234958

**Review by EdwinLauM — APPROVED** [review]
Hey @eduvarjaor! Works as expected and code changes look good!

Screen Shot 2023-09-22 at 9 41 46 AM

**Review by JeffLi117 — APPROVED** [review]
Code looks good, tests passed as intended. 
As there are a significant number of approvals - @EvianTan 

image

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this PR and it works as intended.
Screenshot 2023-09-22 at 7 38 36 PM

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging

**Pull request merged**
