### PR TITLE
Sucheta show new icon on ai prompt update

### PR DESCRIPTION
**Pull request by sucheta90**
# Description
(PRIORITY HIGH) Jae: Make it clear when a new AI Prompt is available (WIP Sucheta)
- Related [PR1510](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1510)
- The AI Prompt is now editable. I’d like it to be obvious to a person when they see the button below for the first time after the AI Prompt has been updated.
Screenshot 2024-01-20 at 8 41 37 PM

- Ideally, I’d like it to look like what’s shown below: 
   - Cleaned up [200x160px image link ](https://www.dropbox.com/scl/fi/0g9cvqlzy9gj00sie28mk/New-HGN-Icon-11kb-200x160px.png?rlkey=vkngel8ezl0cbhbjutmlotvin&dl=0)to use. Give me the exact dimensions needed and I’ll create a new one. 
- After a person has copied the link for the first time, the button should return to what you see above.
Screenshot 2024-01-20 at 8 39 50 PM

## Related PRS (if any):

To test this frontend PR you need to checkout to backend [PR711](https://github.com/OneCommunityGlobal/HGNRest/pull/711)
…

## Main changes explained:
- Adds new property `modifiedDateTime` to `weeklySummaryAIPrompt` - model
- Adds new property `copiedAiPrompt` to `userProfile` - model
- Adds new end points to get and put the `CopiedPromptDate`.
- Updates the `modifiedDateTime` when the owner edits the Ai prompts.
- Updates the `copiedAiPrompt` when a user copies the Ai prompt.
…

## How to test:
1. Check into current branch
2. Do `npm install` , `nmp run build` and `npm start`  to run this PR locally
3. Clear site data/cache from browser's `Application` tab.
 
Test as `OWNER`: 
1. Log as `Owner` user
2. Go to WeeklySummary submission modal, then click the button `View and Copy Current AI Prompt`. As an owner, the user should have the permission to edit the AI prmpt. 
3. Once the AI prmpt has been updated, the button changes to show a `new` icon - making it visually known that the AI prompt has been updated. 
4. The visual indication will only persist until the user has copied the updated Ai prompt. Once copied , the button changes and the `new` icon disappers.

Test as any other user:

1. Log as any user
2. Go to WeeklySummary submission modal. 
3. The button `View and Copy Current Ai Prompt` should be normal if there is no change in the AI prompt since last time the prompt was copied
4. If the AI prmpt was updated, the button changes to show a `new` icon - making it visually known that the AI prompt has been updated. 
5. The visual indication will only persist until the user has copied the updated Ai prompt. Once copied , the button changes and the `new` icon disappers.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/9b7d32c8-7d2f-4433-ae48-f50fef567c0b

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by pshereen — APPROVED** [review]
Tested the PR. And the implemented feature is working as per the requirement.
Logged in as Owner and updated the AI prompt.
After updated AI prompt, new icon appeared on the button.
Once owner copied the updated AI prompt, the new icon disappeared.

Logged in as volunteer. 
AI prompt button had the new icon, as it was updated by the owner.
Once the volunteer copied the AI prompt, the new icon disappeared.

Please check the below video for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/d365509b-dca4-469a-989e-6041e3b143c2

**Review by Sophie-lei — APPROVED** [review]
Hey, I just tested this PR's FE and BE. All things worked as expected. I tested it in Owner Roles, and it has the edit button. After editing the AI prompt, there is a New button pop-up. The New button disappeared after the copy prompt.
in Owner role

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/dce57b28-07df-4f78-82ad-f7ff43d46be5

in the Volunteer role, the New button shows the first time and the prompt can not be edited. The new button disappeared after copying the AI prompt. 
in Volunteer

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/b542aca7-c3ea-49e6-ade8-65a48af5ff14

**Review by Sophie-lei — APPROVED** [review]
Tested and made commend in the PR#1899 FE. All things are working!

**Review by lacnoskillz — COMMENTED** [review]
@sucheta90 
nice work! the funtionality works great. Owners can only edit the prompt. and when others view a recently edited prompt it has the 'NEW' tag that dissapears when copyed for the first time.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/d2de40e7-8a2e-4e29-b913-e2a9228ae08f



My only note is that the responsiveness of the page could use work
image

maybe adding some media query's to `summary-instructions-row` changing  to flex column would look  better
image

**Review by Renanluizssx — APPROVED** [review]
Hi @sucheta90, i tested your application and it's running very nice:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/584eb5b4-4424-4225-8759-8144c02dea60

**Review by X1aoZhang99 — APPROVED** [review]
Hi Sucheta,

I have tested your PR with BE #711 and both owner and volunteer users. All functionalities worked as intended. After I edit the prompt with the owner user, I then use both the volunteer and owner to copy the prompt. After I copy the prompt for both users, the button changes, and the new icon disappears. Nice work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/9eb35fa2-b7f7-44ca-a7e5-e8caae08fbe7

**Review by SaiDeepak-NEU — APPROVED** [review]
Checked into the backend PR 711 and tested the changes. Logged in as owner first and edited the AI prompt. Was able to see the NEW icon after editing prompt and the icon dissapeared after copying.

Then logged in as Volunteer and could see the NEW icon there as well and the icon dissapeared after copying and no edit option was there for volunteer.

Screenshot (36)
Screenshot (35)
Screenshot (34)

**Review by Nahiyan-16 — COMMENTED** [review]
## Great Work!
Hi Sucheta, I reviewed your PR and I'm happy to say that your functionality works as intended. I did however notice a **tiny issue** when you click on the edit button and don't make any changes, the "New" icon still shows up. I don't believe that was the intended result. Otherwise, the code is very well written and organized. 

Here is a demonstration video from an owner account: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/58e969fe-f918-42a1-a745-4c554f9fd45b

Here is a demonstration video from an volunteer account: 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/ecaa094e-3e32-400d-8fed-bc06b17b53e5

**Review by Pandani07 — APPROVED** [review]
Tested this PR and it works as intended. I logged in as an owner and I could see, copy and edit the AI prompt. The updated AI prompt was visible to my owner account. 

With my volunteer account, I checked to see if the AI prompt was updated and it was. I also could not edit the prompt as I could with the owner account.
In terms of the UI, I think the prompt may look better with some margin and padding. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/803312b3-4f82-4124-a493-604ff7439d70

**Review by yvonnep165 — APPROVED** [review]
Hi @sucheta90 ,

I have tested the PR with the owner account and the manager account.
Log as Owner user: 
A new icon showed up originally.
I can edit the AI prmpt successfully.
Once the AI prmpt has been updated, the button changed to show a new icon.
The visual indication only persisted until the onwer has copied the updated Ai prompt. 
Once copied , the button changed and the new icon disappeared.

Test as a manager:
The button changed to show a new icon since the ai prompt has been updated by the owner.
The visual indication only persisted until the onwer has copied the updated Ai prompt. 
Once copied , the button changed and the new icon disappeared.

All work as intended. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/9fe3e9b8-8aff-45e5-bda2-97cdb13914cd

**Review by ClemarNunes — APPROVED** [review]
Hi Sucheta, I have reviewed your PR and am pleased to report that the functionality is operating as expected.

testnew

**Review by KevHnh — COMMENTED** [review]
I tested using an owner account and followed the setup and test process very closely. However, I was not able to replicate the expected results. After editing the AI prompt, the new png does not appear. I verified that I pulled the most updated code and the image itself is in the asset folder. 

Any idea why this might be happening? 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/a3eba35a-2c82-4ff8-ae26-9c44a536b858

**Comment by sucheta90** [comment]
> I tested using an owner account and followed the setup and test process very closely. However, I was not able to replicate the expected results. After editing the AI prompt, the new png does not appear. I verified that I pulled the most updated code and the image itself is in the asset folder.
> 
> Any idea why this might be happening?
> 
>  2024-02-01.22-22-18.mp4

Hello @KevHnh , thank you so much for reviewing this PR. Just wanted to confirm if you had installed the packages by running `npm install` for both front-end and the back-end code. And then an additional step for the backend branch `npm run build`. I tried to run this remote branch on my machine it worked as expected. Can you try one more time to make sure all required steps have been followed.

**Comment by sucheta90** [comment]
> ## Great Work!
> Hi Sucheta, I reviewed your PR and I'm happy to say that your functionality works as intended. I did however notice a **tiny issue** when you click on the edit button and don't make any changes, the "New" icon still shows up. I don't believe that was the intended result. Otherwise, the code is very well written and organized.
> 
> Here is a demonstration video from an owner account:
> 
>  screen-capture.mov 
> Here is a demonstration video from an volunteer account:
> 
>  screen-capture.1.mov

Hello @Nahiyan-16 , thank you for reviewing this PR. This is a very good observation, however the click event on the save button , sends a request to save the AI prompt regardless of the prompt being changed. The icon will not appear unless the and update request was sent to the database. 

@one-community Please advise, if I need to make this change.

**Review by SRamen1999 — APPROVED** [review]
After testing this PR everything works as expected. Only the owner account can edit the AI prompt. After updating the AI prompt a new icon appeared on the button.
Once owner copied the updated AI prompt, the new icon disappeared.

After editing the AI prompt with the owner account I logged in using the admin, volunteer and manager accounts and you can see the new icon. Once the AI prompt is copied the new icon disappears. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/22f12f1c-3315-459b-b02a-25be6b094e0d

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/9166da5f-f616-4ea5-ae06-bd408d931c62

**Comment by KevHnh** [comment]
> > I tested using an owner account and followed the setup and test process very closely. However, I was not able to replicate the expected results. After editing the AI prompt, the new png does not appear. I verified that I pulled the most updated code and the image itself is in the asset folder.
> > Any idea why this might be happening?
> > 2024-02-01.22-22-18.mp4
> 
> Hello @KevHnh , thank you so much for reviewing this PR. Just wanted to confirm if you had installed the packages by running `npm install` for both front-end and the back-end code. And then an additional step for the backend branch `npm run build`. I tried to run this remote branch on my machine it worked as expected. Can you try one more time to make sure all required steps have been followed.

I reinstalled everything and tested it out again, and it works as expected. Thanks for the response!

[After changing prompt]
image

[After copying prompt]
image

**Comment by sucheta90** [comment]
> > > I tested using an owner account and followed the setup and test process very closely. However, I was not able to replicate the expected results. After editing the AI prompt, the new png does not appear. I verified that I pulled the most updated code and the image itself is in the asset folder.
> > > Any idea why this might be happening?
> > > 2024-02-01.22-22-18.mp4
> > 
> > 
> > Hello @KevHnh , thank you so much for reviewing this PR. Just wanted to confirm if you had installed the packages by running `npm install` for both front-end and the back-end code. And then an additional step for the backend branch `npm run build`. I tried to run this remote branch on my machine it worked as expected. Can you try one more time to make sure all required steps have been followed.
> 
> I reinstalled everything and tested it out again, and it works as expected. Thanks for the response!
> 
> [After changing prompt] image
> 
> [After copying prompt] image

@KevHnh thanks once again.

**Comment by galgalinidhi** [comment]
Hi @sucheta90, I tested the PR using a Owner and a Volunteer account and it works well!
 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/cef5e768-47db-4bbf-a65e-24f3fe0602b6

**Review by mohabbasd — APPROVED** [review]
Hello, this PR is working perfectly, when I logged in with my owner account I could edit the prompt and when I logged in with my test account I could only copy the prompt.
Screenshot 2024-02-05 at 10 18 31 PM
Screenshot 2024-02-05 at 10 18 55 PM
Screenshot 2024-02-05 at 10 19 35 PM
Screenshot 2024-02-05 at 10 19 42 PM

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.08-15_25_42.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/bd42b990-504d-418a-b4ec-8c4c809400c3)

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
