### PR TITLE
Aishwarya - Purchase tool request form-frontend

### PR DESCRIPTION
**Pull request by Aishwaryak01**
Description
Adds Purchase Request: Tool page and form to the BM Dashboard (Phase 2).

Related PRS (if any):
Backend PR 670 must be running to test this branch.

Main changes explained:
Adds an ability to initiate a purchase request for a tool to be used on a specific project.
request must include quantity and priority level, with an optional 'preferred brand' field.
adds actions and reducers to store tool types data in redux store
adds error handling to fetch request on page load
adds success and error toasts after submitting purchase request

How to test:
follow checkout instructions for backend PR 670
git checkout Aish purchase tool request form (frontend)
npm install
npm run start:local
log in to HGN as a volunteer user
navigate to http://localhost:3000/bmdashboard and enter credentials again
navigate to http://localhost:3000/bmdashboard/tools/purchase

Test basic form submission:
Project and Tools options should auto-load into respective fields
Enter info into all required fields (Preferred Brand is optional) and click Submit
Note whether a success toast notification is received
Optional: check Network tab in browser tools to check for a 'tools' request with status code 201 (Created).

Test form validation:
Test that Submit button is disabled unless all required fields are entered
Test that entering a decimal or technically-allowable letter 'e' (ex: 10e10) in Quantity field results in a validation check/error.
Note: there are validation checks for all form fields, but these are harder to test without manipulating the HTML.
Test that Cancel button clears form and returns user to previously visited page.

Test error handling:
- To test error handling on initial page load, you can deactivate the backend server and reload the page. This will load an error page with code 503.
- To test error handling if form submission fails, change the fetch route in src/actions/bmdashboard/toolsActions > purchaseTools from ENDPOINTS.BM_TOOLS to ENDPOINTS.BM_TOOLS + "s". This should result in an error toast with code 404.

Screenshots or videos of changes:
image

Notes:
Please remember to either Approve or Request Changes. Do not just leave a comment.
Please leave a review for BOTH front and backend branches after you have finished testing!
Permissions are currently not being built into the Phase 2 codebase. All functionality should be accessible to volunteer users.
The form will eventually only be accessible to Building Manager users. Purchase requests will be limited to the BM's own projects. For now these limitations are not in place.

### CODE REVIEW

**Review by Alforoan — DISMISSED** [review]
Everything worked as it should. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/30c0c093-5994-446c-b9aa-ae753973ce8c

**Review by abdel-lall — DISMISSED** [review]
Works as described. Nice job!

MergedImages

**Comment by Aishwaryak01** [comment]
@tdkent I have made the changes and also made files in sync with the current dev branch. Can you please check?

**Comment by Aishwaryak01** [comment]
@one-community  Can anyone apart from me and Tim test this PR and approve so that we can proceed with merging it.

**Review by Renanluizssx — APPROVED** [review]
Hi @Aishwaryak01, i tested all aspects you said and it's running very well, see my review

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/9ba54f8c-5267-4cbc-a608-6cebb660974a

**Review by KevHnh — APPROVED** [review]
I tested using a volunteer account and everything works as expected. I was able to navigate into the bmdashboard and login using my credentials then navigate into the purchase tool request form to successfully submit a request.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/21e45f31-bc04-4a51-a378-74837e5cbd13

**Review by ClemarNunes — APPROVED** [review]
In general, the PR seems to be working as expected, and I did not identify any significant issues during testing.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/8040f7e9-7b50-48ae-83f5-fc81546fd1a3

**Review by Nahiyan-16 — CHANGES_REQUESTED** [review]
## One little issue
Hi Aishwarya, when I was testing this PR, I didn't see any glaring issues at hand but something that I noticed was that for the "Est. Time of Use" form field, the User is allowed to give any type of input. I feel like we can better validate this data as this can be important for keeping track. Otherwise, I didn't notice any problems with this feature and it was incredibly well written and displayed. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/a14dba47-5aee-4996-9b3b-23b6ba2e769e

**Comment by xmyoot** [comment]
All endpoints worked properly (/bmdashboard) (bmdashboard/tools/purchase), every looks great!
At Bmdashboard signin:
PR#1752:670(signingIn)

At form before submission:
PR#1752:670(formWorks)

After form submission:
PR#1752:670(formSubmissionSuccessesful)

**Review by Pandani07 — APPROVED** [review]
I tested this PR and everything works as intended. I have attached a video.  I could log in as a user, navigate to bmdashboard and purchase tools as well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/f6a786d2-7800-4e59-8ef3-18d3044360f6

**Review by ilyaflaks — APPROVED** [review]
I tested this PR from a volunteer account and everything works as described. 
Validation handles multiple edge cases: 
PR1752validations

Submitting the valid form results in a 200 response from the API:
PR1752-success

purchaseRecord gets updated on the database
PR1752-db

The only suggestion is to have the cancel button redirect somewhere like [bmdashboard/tools/](http://localhost:3000/bmdashboard/tools/) in case the user somehow navigated to this page from another website (like I did from github.com). This is a rare case, so I won't insist. 

Overall, very high quality code! Not overengineered, yet all edge cases are taken into consideration

**Review by TapanPathak — APPROVED** [review]
Hi, I reviewed the PR and it works as expected. I was able to login as volunteer and test all functionality. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/5c576ad7-4aaf-4c48-9024-52c32aff998d

**Review by SaiDeepak-NEU — APPROVED** [review]
Hello Aishwarya,

I have tested the form submission in the bmdashboard in tools/purchase and everything worked smoothly. The form looked great and clean. 
This is before the submission. The submit button was disabled until all the fields were filled out.
Screenshot (71)
This is after the submission. Verified that 201 created is shown on the network tab.
Screenshot (72)

Note: One additionI would suggest to make is that, adding a small red '*' on top of all the mandatory fields makes more sense. It gives users a better idea of which fields are mandatory to fill in order for the submit button to get enabled. I think this is standard practice in html forms. Please give it a thought.

**Comment by Aishwaryak01** [comment]
@Nahiyan-16 @ilyaflaks @SaiDeepak-NEU  Thank you for your suggestions. We can make these required changes in the next updated version or maybe in bugs as these are minor changes. I would like this PR to get merged sooner as upcoming PRs have shared files with this one.

@one-community Can you move this to the next step?

**Review by mohabbasd — APPROVED** [review]
Hello, tested this PR and it works as expected.
Screenshot 2024-02-08 at 11 25 41 PM
Screenshot 2024-02-08 at 11 27 29 PM
Screenshot 2024-02-08 at 11 32 33 PM
Screenshot 2024-02-08 at 11 33 59 PM

**Review by SRamen1999 — APPROVED** [review]
I was able to navigate into the bmdashboard and login using my credentials then navigate into the purchase tool request form to successfully submit a request.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/7bfd05b2-0fe9-4a25-823a-fe0403b9794f

when deactivating the backend gives the proper error msg.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/973e4cd7-3b37-404a-b966-da466096b690

**Review by Nahiyan-16 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
