### PR TITLE
Tianyuan_fix_email_list_visibility

### PR DESCRIPTION
**Pull request by Sssky-18**
# Description
截屏2023-11-08 18 55 28

## Related PRS (if any):
No

## Main changes explained:
- Pass the state "auth" from WeeklySummaryReport component to FormattedReport component in order to get the account role 
- Create a new component EmailsList to contain all the behaviors related to the email list  
- Program the logical code to make only Admin and Owner have access to the email list 
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin/owner/mentor/manger/core team user (they are the only five roles have acess to the WeeklySummaryReport page)
4. go to dashboard→ Reports→ WeeklySummaryReport→ waiting for the page loading -> after loading, scoll to the bottom of the page 
5. Test this PR in two steps:
If you log as **admin/owner**, make sure you can have the access to see the email list
If you log as **mentor/manger/core team**, make sure you can **NOT** see the email list 

## Screenshots or videos of changes:
In this video, the console displays the role of account, but in this PR I have commented the console log code to print the role of account. **So you don't need to open your console.** 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73833864/9fd7d4c5-9538-4663-b1b0-bd3da66a6144

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Jiyuanxia — APPROVED** [review]
Hi @Sssky-18 , I have reviewed your pull request and tested it. It works as you intended. Well done!

email list does not appear while logging in as mentor
Screenshot 2023-11-09 110313

email list appears while logging in as admin
Screenshot 2023-11-09 105749

**Review by Shuhua-L — COMMENTED** [review]
Hi @Sssky-18, I've tested your PR locally and verified that Admins/Owners have access to the email list while Mentors/Managers/Core Team don't. Nice work!

However, I noticed that some image files and CSS files unrelated to the Weekly Summaries Report were modified. Could you verify if these changes are necessary?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/0d9d065f-0081-4683-98db-6092acd7d052


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/e5c03a4f-13be-4ab1-a36a-26467ec54ba8



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/f28df38d-ce04-4f78-a1e8-d4c4a77f6f53

**Comment by Sssky-18** [comment]
> Hi @Sssky-18 , I have reviewed your pull request and tested it. It works as you intended. Well done!
> 
> email list does not appear while logging in as mentor Screenshot 2023-11-09 110313
> 
> email list appears while logging in as admin Screenshot 2023-11-09 105749

@Shuhua-L , yeah I also notice this problem that even if I have already merged development into my branch and checked my branch is already up to date, there are still several images that have difference from development branch. I didn't change anything to these images. Really confused about this problem. Maybe I should pull the development branch again. Do you have any suggestion for this problems?

**Comment by Sssky-18** [comment]
> Hi @Sssky-18, I've tested your PR locally and verified that Admins/Owners have access to the email list while Mentors/Managers/Core Team don't. Nice work!
> 
> However, I noticed that some image files and CSS files unrelated to the Weekly Summaries Report were modified. Could you verify if these changes are necessary?
> 
>  PR1504-admin-owner.mov 
>  PR1504-mentor-manager.mov 
>  PR1504-core-team.mov

@Shuhua-L , yeah I also notice this problem that even if I have already merged development into my branch and checked my branch is already up to date, there are still several images that have difference from development branch. I didn't change anything to these images. Really confused about this problem. Maybe I should pull the development branch again. Do you have any suggestion for this problems?

**Comment by Shuhua-L** [comment]
> > Hi @Sssky-18, I've tested your PR locally and verified that Admins/Owners have access to the email list while Mentors/Managers/Core Team don't. Nice work!
> > However, I noticed that some image files and CSS files unrelated to the Weekly Summaries Report were modified. Could you verify if these changes are necessary?
> > PR1504-admin-owner.mov
> > PR1504-mentor-manager.mov
> > PR1504-core-team.mov
> 
> @Shuhua-L , yeah I also notice this problem that even if I have already merged development into my branch and checked my branch is already up to date, there are still several images that have difference from development branch. I didn't change anything to these images. Really confused about this problem. Maybe I should pull the development branch again. Do you have any suggestion for this problems?

I also ran into a situation where Visual Studio Code shows image files as modified when they are not. After browsing through Slack discussions, I believe it was due to the CRLF x LF issue. I can pin you in those discussions.

**Review by Shubhu0 — CHANGES_REQUESTED** [review]
Hi @Sssky-18 I tested your PR and it is working as intended.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/8b7306e2-25ac-47bf-ab66-9382e8479555

**Review by sahilpatel18 — COMMENTED** [review]
While the admin account is allowing access to the email list as intended, there appears to be an issue for other roles. Notably, when logged in as a mentor, I still have access to the email list. 

Admin Account: 

adminSS

**Mentor Account:**

mentorSS

**Comment by Sssky-18** [comment]
> Hi @Sssky-18 I tested your PR and it is working as intended.
> 
>  HGN.APP.-.Personal.-.Microsoft.Edge.2023-11-10.00-18-32.mp4

Hi @Shuhua-L , I noticed you requested a change, but your comment shows that the PR worked as intended. Could you re-review this PR and tell me the what should I change?

**Pull request closed without merging**
