### PR TITLE
add refresh button on user profile page

### PR DESCRIPTION
**Pull request by KaixiangGU**
Added a refresh button on the user profile page, allowing users to reload the user profile component to see any changes they made instead of refreshing the whole page.

google_docs
Google Docs

fix_refresh_bug_on_userProfile

### CODE REVIEW

**Review by LeeSingChanYau — APPROVED** [review]
Looks good!

**Comment by one-community** [comment]
Works great. Please move that button here though, so it is clearer that that button is for the purpose of refreshing these numbers.
Screen Shot 2022-12-02 at 2 45 00 PM

 I don't see a need for one at the bottom because there's the one already built in to everyone's browser.

**Comment by KaixiangGU** [comment]
Got it, will do!

**Comment by one-community** [comment]
Thank you!

**Pull request merged**
