### PR TITLE
Imran manage admin links in user profile

### PR DESCRIPTION
**Pull request by ImzIssa**
# Description
Gives the user permission to edit the links of any user on the user profile page. "User Profile" -> "Links button"

## Related PRS (if any):
This frontend PR is related to the [PR#916](https://github.com/OneCommunityGlobal/HGNRest/pull/916) backend PR.

## Main changes explained:
- Add manageAdminLinks to PermissionsConst.js
- replaced 'putUserProfileImportantInfo'  permission check with 'manageAdminLinks' in EditLinkModal.jsx

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user -> Other Links -> Permissions Management -> Manage User Permissions.
5. Enter the username of an user that does not have the “Manage Admin Links in User Profile” permission. Add the permission and Click on Submit.
6. Login as the chosen user (if already logged in, make sure to log out and log back in). 
7. Navigate to  "User Profile" -> "Links" -> "Edit". The user should now be able to edit their admin links.
8. Visit any other user's profile and should be able to edit admin links.

## Screenshots or videos of changes:
**Navigate to Profile as a without permission to manage Admin Links. Verify that the edit button is visible** 
Step 1

**Verify that you can't see admin Links**
Step 2

**Visit profile of any other user and verify you can't see edit button next to Links. (Note: if the logged in user has other permissions such as Edit User Profile, you should be able to see the button but not admin links in the dialog**
Step 3 (2)

**Logout and Log back in as admin and navigate to permission management screen to give user permission to manage admin links**
Step 3
Step 4

**Log back in as the user given permission and navigate to profile and verify you can now manage admin links**
Step 5
Step 6

**Visit any other user's profile and verify you can now add or edit their admin links too**
Step 7

### CODE REVIEW

**Review by cgomezhub — DISMISSED** [review]
It was possible to add manageAdminLinks permission form an Admin User to a Volunteer User
Screenshot 2024-05-02 120716
Screenshot 2024-05-02 120857
Screenshot 2024-05-02 122845

**Review by curiousfancier — DISMISSED** [review]
In the video, I demonstrated the following steps to manage user permissions and edit admin links
Log in as an admin user. and then Navigate to "Other Links" and select "Permissions Management".
Click on "Manage User Permissions".
Enter the username of a user who lacks the "Manage Admin Links in User Profile" permission. and now Add the permission to the user’s profile and click "Submit".
Log out and then log in as the user who just received the new permission. now Go to "view Profile", then "Links", and click on "Edit". This user should now have the ability to edit their admin links.
Visit another user's profile to confirm that the admin links can be edited there as well.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/27274513/fa2fe904-9b1f-45ba-9b97-52670cd04a35

These steps ensure that the specified user can manage admin links not only in their own profile but also in other users’ profiles.

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as described.
Without permission:
Screenshot 2024-05-03 at 8 16 11 PM

With permission:
Screenshot 2024-05-03 at 8 14 38 PM

**Review by Ramaruva — DISMISSED** [review]
Hi I have verified your changes in my local env  and I was only able to add admin links to the user which has only admin links permission
image
image

**Review by hbodgal — DISMISSED** [review]
image

It works well. i have tested it with volunteer user.

**Review by MinSun0814 — DISMISSED** [review]
I have tried editing link with and without permission. The changes work as expected. I can see the option to edit links after granting the volunteer account the permission to edit. Nice work!
Before:
image

After:
image

**Pull request merged**
