### PR TITLE
Nahiyan_Fix table header for mobile display

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Created a fix for all table headers in dark mode. Previously, the background of all table headers would change to light mode.

## Related PRS (if any):
This frontend PR is related to the dev backend

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Leaderboard
6. verify that in dark mode, the table header when smaller than 544px doesn't convert back to light mode
7. Another place to check is user management table and reports table

## Screenshots or videos of changes:
Before: 
Screenshot 2024-06-17 102749

After:
Screenshot 2024-06-17 102812

### CODE REVIEW

**Review by kdaga81 — APPROVED** [review]
Screenshot 2024-06-17 at 11 52 33 AM

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and verified that in the dark mode, the table header converts to dark color. Checked for the light and dark mode for smaller window screen (lesser than 544px) as well. The header fix for the dark mode in mobile display works fine.!

**Comment by sahithidhulipala9** [comment]
Have tested the PR by keeping less than 544px for Leaderboard, User Management Table & Reports Table in Dark Mode.
Screenshot (40)
Screenshot (38)
Screenshot (39)

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by shradac — APPROVED** [review]
This change has been tested and it works as expected.
Here is a summary of the results:

1. Log in as owner user 
2. Go to dashboard -> Leaderboard
3. Verified that in dark mode, the table header when smaller than 544px and it does not convert back to light mode.
4. Verified that the user management table in the given conditions.
5. Verified reports table in the given conditions.


Screenshot 2024-06-17 at 10 15 43 PM
Screenshot 2024-06-17 at 10 17 06 PM
Screenshot 2024-06-17 at 10 17 52 PM

**Review by Sudershhh — APPROVED** [review]
Hi Nahiyan,

I tested the changes and checked the user management, leaderboard and reports table. It is showing the dark mode correctly.

PR 2365

**Review by Jingyii800 — APPROVED** [review]
It works well. When in the dark mode and the window is smaller than 544 px. The table header in leaderboard remained dark mode and didn't convert to light mode.
image

**Review by suaniii — APPROVED** [review]
Hi, I've tested the changes on owner account. The table header of dashboard, report page and  user management page displayed well in dark mode for smaller window screen (lesser than 544px). All worked well as expected. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/09566957-5e86-4bfb-afb1-e95af99d92d2

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

image

image

image

**Review by beblicarl — APPROVED** [review]

**Review by Parth-tech — APPROVED** [review]
Hi Nahiyan,

In dark mode the table headers do not switch to light mode on small screen device. The codebase is concise and correct as well.

Screenshot 2024-06-21 at 11 45 37 AM
Screenshot 2024-06-21 at 11 46 07 AM
Screenshot 2024-06-21 at 11 50 04 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Review by ImzIssa — COMMENTED** [review]
I have tested the PR and verified that in the dark mode reflects on the table header in the following pages. 

**Dashboard**
Screenshot (398)

**Badge Management**
Screenshot (397)

**Teams**
Screenshot (395)
Screenshot (396)

**User Management**
Screenshot (394)

**Pull request merged**
