### PR TITLE
Shihao - UserLinkLayout Unit Test

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Unite test for `UserLinkLayout.jsx`

## Main changes explained:
- Add the unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test UserLinkLayout.test.js` to run the test
4. Verify that all 3 tests have passed

## Screenshots or videos of changes:
Screenshot 2023-11-28 at 15 59 26

### CODE REVIEW

**Review by pika-chu11 — APPROVED** [review]
Hi @sxiong5 , the tests passed on my end! Great job!
PR 1599

**Comment by beblicarl** [comment]
All tests passed and the test cases are cool

image

**Review by beblicarl — APPROVED** [review]

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-01 at 10 27 31 PM
Good job @sxiong5 ! All the test cases passed!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
