### PR TITLE
Shefali_Unit_Test_Correct_Test_Folder

### PR DESCRIPTION
**Pull request by SMitta11**
# Description
Unit test code refactored( added test file in corresponding __tests__ folder)

## How to test:
1. check into current branch
2. npm install

Then run all below tests(16 tests):
npm test Checkbox.test.js
Checkbox test file

npm test CheckboxCollection.test.js
CheckboxCollection test file

npm test FileUpload.test.jsx
FileUpload test file

npm test Input.test.jsx
input test file

npm test SkeletonLoading.test.jsx
SkeletonLoading test file

npm test Dropdown.test.jsx
Dropbox test file

npm test Modal.test.jsx
Modal test file

npm test Paging.test.jsx
Paging test file

npm test Member.test.jsx
Note : Even if you see console error here in this test, it is not related to this PR, code is just refactored here so functionality remains same.So it is okay to get this error and raise a separate PR and work on this if anything needs to be done here.

Member test file

npm test TinymceEditor.test.jsx
TinymceEditor test file

npm test AssignTableRow.test.js 
AssignTablerow test file

npm test FoundUser.test.jsx

FoundUser test file

npm test AddProject.test.jsx
AddProject test file

npm test Radio.test.jsx
Radio test file

npm test Selectors.test.js

Selectors test file

npm test TasksTable.test.js

TaskTables test file

### CODE REVIEW

**Review by shivansh-nathani — APPROVED** [review]
I've reviewed the refactored files and tested the unit tests for modified/refactored files, tests are running perfectly fine. Also, the error in Member.test.jsx is pointing towards connection refused, that means that the test in trying to connect to backend server, I tried running the test with backend server and did not encounter that error, so things for member.test.jsx seem to be fine, we don't need another PR to fix it.
Screenshot 2024-10-13 at 6 31 16 PM
Screenshot 2024-10-13 at 6 30 53 PM
Screenshot 2024-10-13 at 6 29 56 PM
Screenshot 2024-10-13 at 6 29 38 PM
Screenshot 2024-10-13 at 6 29 16 PM
Screenshot 2024-10-13 at 6 28 45 PM
Screenshot 2024-10-13 at 6 28 21 PM
Screenshot 2024-10-13 at 6 27 47 PM
Screenshot 2024-10-13 at 6 27 23 PM

Screenshot 2024-10-13 at 6 33 05 PM
Screenshot 2024-10-13 at 6 32 37 PM
Screenshot 2024-10-13 at 6 32 21 PM
Screenshot 2024-10-13 at 6 31 59 PM
Screenshot 2024-10-13 at 6 31 39 PM

Screenshot 2024-10-13 at 6 47 33 PM
Screenshot 2024-10-13 at 6 26 30 PM
Screenshot 2024-10-13 at 6 33 25 PM

**Comment by lucy-xfl** [comment]
image
image
image
image
image
image
image
image
image
Everything works well

**Review by lucy-xfl — APPROVED** [review]

**Comment by pallavithorat** [comment]
All test cases passed!
Screenshot 2024-10-17 at 4 03 12 PM
Screenshot 2024-10-17 at 4 05 47 PM
Screenshot 2024-10-17 at 4 06 45 PM
Screenshot 2024-10-17 at 4 07 39 PM
Screenshot 2024-10-17 at 4 08 09 PM
Screenshot 2024-10-17 at 4 09 03 PM
Screenshot 2024-10-17 at 4 09 37 PM

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (228)

**Review by manikittu810 — DISMISSED** [review]
Hello @SMitta11 
Everything is working as mentioned.
Screenshot 2024-10-18 at 8 56 56 AM
Screenshot 2024-10-18 at 8 57 51 AM
Screenshot 2024-10-18 at 8 58 19 AM
Screenshot 2024-10-18 at 9 00 04 AM
Screenshot 2024-10-18 at 9 00 37 AM

Thank you.

**Review by vijay10pk — DISMISSED** [review]
All test cases passed.
Screenshot 2024-10-18 at 11 34 27 PM
Screenshot 2024-10-18 at 11 31 26 PM
Screenshot 2024-10-18 at 11 30 28 PM
Screenshot 2024-10-18 at 11 29 52 PM

**Comment by geetamatkar** [comment]
Hi @SMitta11 ,
I have tested all the unit tests and it is working as expected.

PR2783
Screenshot 2024-10-19 at 1 52 37 PM
Screenshot 2024-10-19 at 1 52 55 PM
Screenshot 2024-10-19 at 1 53 19 PM
Screenshot 2024-10-19 at 1 53 39 PM
Screenshot 2024-10-19 at 1 53 56 PM
Screenshot 2024-10-19 at 1 54 19 PM
Screenshot 2024-10-19 at 1 54 34 PM
Screenshot 2024-10-19 at 1 54 58 PM
Screenshot 2024-10-19 at 1 56 17 PM
Screenshot 2024-10-19 at 1 58 44 PM
Screenshot 2024-10-19 at 1 59 02 PM
Screenshot 2024-10-19 at 1 59 20 PM
Screenshot 2024-10-19 at 1 59 38 PM
Screenshot 2024-10-19 at 2 00 04 PM

**Review by lng2020 — DISMISSED** [review]
LGTM for a test refactoring PR.

**Comment by mianmiantea2019** [comment]
All test cases passed.

image
image
image
image
image
image
image
image
image

**Review by SharadhaS24 — DISMISSED** [review]
I've reviewed all 16 refactored unit test cases, and they are all passing successfully. 

image
image
image
image
image
image
image
image
image
image

**Review by NK3101 — APPROVED** [review]
I have tested all the unit tests and it is working as expected.
Screenshot 2024-10-24 at 10 44 43 PM
Screenshot 2024-10-24 at 10 43 29 PM
Screenshot 2024-10-24 at 10 43 04 PM
Screenshot 2024-10-24 at 10 42 40 PM
Screenshot 2024-10-24 at 10 42 14 PM
Screenshot 2024-10-24 at 10 41 28 PM
Screenshot 2024-10-24 at 10 40 41 PM
Screenshot 2024-10-24 at 10 39 32 PM
Screenshot 2024-10-24 at 10 38 53 PM
Screenshot 2024-10-24 at 10 23 48 PM
Screenshot 2024-10-24 at 10 23 32 PM
Screenshot 2024-10-24 at 10 23 17 PM
Screenshot 2024-10-24 at 10 22 52 PM
Screenshot 2024-10-24 at 10 22 17 PM
Screenshot 2024-10-24 at 10 21 54 PM
Screenshot 2024-10-24 at 10 21 06 PM

**Comment by beblicarl** [comment]
All tests covered specified scenarios and passed successfully

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

image

**Review by beblicarl — DISMISSED** [review]

**Review by samarth9201 — DISMISSED** [review]
Verified that all the test cases are working. 
Screenshot 2024-10-25 170521
Screenshot 2024-10-25 170542
Screenshot 2024-10-25 170601
Screenshot 2024-10-25 170621
Screenshot 2024-10-25 170642
Screenshot 2024-10-25 170706
Screenshot 2024-10-25 170724
Screenshot 2024-10-25 170745
Screenshot 2024-10-25 170803
Screenshot 2024-10-25 170821
Screenshot 2024-10-25 170844
Screenshot 2024-10-25 170902
Screenshot 2024-10-25 170922
Screenshot 2024-10-25 170954
Screenshot 2024-10-25 171022

**Review by anirudhsk2107 — DISMISSED** [review]
All the tests passed 
Screen Shot 2024-10-25 at 8 37 58 PM
Screen Shot 2024-10-25 at 8 38 13 PM
Screen Shot 2024-10-25 at 8 38 25 PM
Screen Shot 2024-10-25 at 8 38 36 PM
Screen Shot 2024-10-25 at 8 38 48 PM
Screen Shot 2024-10-25 at 8 38 57 PM

**Review by RachanaZha — APPROVED** [review]
Have testes all 16 files. All test cases in all 16 files have passed successfully
CheckboxCollection.test.js
Checkbox.test.js
FileUpload.test.jsx
Input.test.jsx
SkeletonLoading.test.jsx
Dropdown.test.jsx
Modal.test.jsx
Paging.test.jsx
Member.test.jsx
TinymceEditor.test.jsx
AssignTableRow.test.js
FoundUser.test.jsx
AddProject.test.jsx
Radio.test.jsx
Selectors.test.js
TasksTable.test.js
zha_rachana_PR#2783_#1
zha_rachana_PR#2783_#2
zha_rachana_PR#2783_#3
zha_rachana_PR#2783_#4
zha_rachana_PR#2783_#5
zha_rachana_PR#2783_#6
zha_rachana_PR#2783_#7
zha_rachana_PR#2783_#8
zha_rachana_PR#2783_#9
zha_rachana_PR#2783_#10
zha_rachana_PR#2783_#11
zha_rachana_PR#2783_#12
zha_rachana_PR#2783_#13
zha_rachana_PR#2783_#14
zha_rachana_PR#2783_#15
zha_rachana_PR#2783_#16

**Review by CodewithKoushica — APPROVED** [review]
All the test cases passed! 
Screenshot 2024-10-30 at 10 01 10 AM
Screenshot 2024-10-30 at 10 00 48 AM
Screenshot 2024-10-30 at 9 59 59 AM
Screenshot 2024-10-30 at 9 59 07 AM
Screenshot 2024-10-30 at 9 58 35 AM
Screenshot 2024-10-30 at 9 57 41 AM
Screenshot 2024-10-30 at 9 56 21 AM

**Pull request merged**
