### PR TITLE
Shiwani TeamMemberTasks unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/TeamMemberTasks/TeamMemberTasks.jsx`

## Main changes explained:
- Added 16 test cases: renders without crashing, check if Team Member Tasks header is displaying as expected, check if Team Member header is displaying as expected, check if Weekly Committed Hours header is displaying as expected, check if Total Hours Completed this Week header is displaying as expected, check if Total Remaining Hours header is displaying as expected, check if Tasks(s) header is displaying as expected, check if Progress header is displaying as expected, check if the skeleton loading html elements are shown when isLoading is true, check if the skeleton loading html elements are not shown when isLoading is false, check if class names does not include color when dark mode is false, check if class names does include color when dark mode is true, check if show time off button works as expected, check if days button works as expected, check if TeamMemberTask without time entries gets displayed when isTimeFilterActive is set to False, check if TeamMemberTask with time entries gets displayed when isTimeFilterActive is set to True 

## How to test:
1. check into current branch
2. do `npm test src/components/TeamMemberTasks/__tests__/TeamMemberTasks.test.js` 
3. check if all the test cases passes without any errors or warnings.

## Screenshots or videos of changes:
Screenshot 2024-06-06 at 12 16 17 PM

### CODE REVIEW

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it is working as intended. Please refer the screenshot attached.
PR 2322

**Review by Kavil-Jain-514 — APPROVED** [review]
All test cases have passed without any error or warning.
image

**Review by deepthikannan — APPROVED** [review]
image
Tested your PR and all test cases have passed perfectly.

**Review by cecilia-uu — APPROVED** [review]

**Review by tianyangL11 — APPROVED** [review]
All test case passed without any error.  Great job!

**Review by shradac — APPROVED** [review]
All tests passed. The tests cover all specified scenarios. Good Work!

week1-15

**Review by KaushikMreddy — APPROVED** [review]
Hi Shiwani, 
All your test cases are working.
image

**Comment by beblicarl** [comment]
All test cases passed. Test cases cover specified scenarios 

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
