### PR TITLE
Jingyi permission management create/edit/delete badge

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
This PR is related to badge [permission management fixes](https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit#gid=0). It enables users with create/edit/delete badges permission to see the changes of badges immediately.

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
Whenever any of the badge management permissions ("createBadges," "updateBadges," or "deleteBadges") are activated for a user, the "seeBadges" permission is automatically included.

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Badge Permission -> Choose a user without badge management permissions such as 'create badges' 'edit badges' or 'delete badges' -> add the permission for this user -> Scroll down then submit
6. When adding the permission to create/edit/delete the badge, you will find 'see badge' is automatically activated.
7. log into the account that was just granted permission and go to Other Links -> Badge Management to test the permission you just added. For example, create one badge, edit one badge or delete one badge.
8. You will see the change immediately on the page.

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/d879dabd-4d4e-48d4-a60c-7982e0ceb097

### CODE REVIEW

**Review by linkhanthtel — DISMISSED** [review]
It looks good! I logged into my account and add permission for badge management. Then, I test creating one badge, editing one badge and deleting one badge.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/45dfca26-aed9-4b2c-9a44-14432844d31d

**Review by XiaohanMeng — COMMENTED** [review]
Hi Jingyi, I tested your feature and it looks good on the badge management side. But I noticed a small issue: After I delete the badge, the deleted badge still show on the profile page. Please refer my video for detail.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/99a001f3-5758-4860-9551-f72cc6d8c585

**Review by mohabbasd — APPROVED** [review]

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/59433934-c634-4519-964d-043e52f7a170

**Review by abdel-lall — DISMISSED** [review]
LGTM.
Screenshot 2024-03-30 204610

**Review by yvonnep165 — DISMISSED** [review]
Hi @Jingyii800 , I have tested this pr and it works as intended. I used the owner account to grant permission to a manager account. I logged into my manager account to test creating badges, editing badges and deleting badges. Nice work! Please refer to the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/00ad0ae2-bc0b-4f6a-b4b3-970283fa51fb

**Review by aaryaneil — COMMENTED** [review]
I was able to enable permissions for a user to create, edit, and delete a badge. All the functions work as expected.
Screenshot 2024-04-06 at 4 44 36 AM
Screenshot 2024-04-06 at 4 45 09 AM

**Review by aaryaneil — DISMISSED** [review]
I was able to enable permissions for a user to create, edit, and delete a badge. All the functions work as expected.
Screenshot 2024-04-06 at 4 44 36 AM
Screenshot 2024-04-06 at 4 45 09 AM

**Review by ShengjieMao — DISMISSED** [review]
the function and assignment of abilities worked well with no error. the functions in the descriptions are all met. great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/57db4c04-05f5-4808-8c39-836708ea1e6c

**Pull request closed without merging**
