### PR TITLE
Kyrene - Allow volunteers, admin and owners to click task and navigate to task page

### PR DESCRIPTION
**Pull request by KyreneAF**
…ructure key to allow volunteers to open /wbs/tasks/taskId route

# Description
- This bug is to fix the ability for members to open their tasks from the landing page under Tasks tab. 

Screenshot 2024-06-07 at 3 52 37 PM

[Video of bug](https://drive.google.com/file/d/1zNa7cRoKpSLFoa6L_5ZRGlMZbUQV1LmF/view)

## Related PRS (if any):
This frontend PR is related to the #1458.

…

## Main changes explained:
-Added 'suggestTask' to the 'workBreakdownStructure' key in the routePermissions.js to grant permission to access the protected route /wbs/tasks/:taskId, which includes the Task and its suggest task page.
…

## How to test:
1. check into current branch: [Kyrene_fix_bug_opening_task_page]
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as volunteer user
5. go to dashboard→  'Tasks and Timelogs' table on landing page > Tasks tab → under Tasks(s)→  click blue text for task description…
(if there are no tasks you must create one for your volunteer account using an owner or admin account. how to video below)
7. verify you can click on the task link as a volunteer, admin and owner

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/04519abe-02a6-42ed-9e49-c8d629661668

## Screenshots or videos of changes:
- Final desired functionality:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/129882345/fe64bccf-b952-4d2b-ab09-881091535eed

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Parth-tech — COMMENTED** [review]
Hi Kyrene,
I have tested the PR and I can now suggest as a volunteer. But I do not see my suggestion when I login as as owner and neither do I see it when I re-login in as Volunteer. 
Please let me know if this is intended then I would approve the PR.

**Comment by cecilia-uu** [comment]
It's weird.. I cannot open it.
截屏2024-06-08 下午10 23 55

**Comment by KyreneAF** [comment]
Hi Parth,
this PR is only for the ability to click on the task and navigate to the
suggestion page. The suggest functionality is for the related PR.



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
06/08/24,
09:54:02 AM

**Comment by KyreneAF** [comment]
@Parth-tech 
Hi Parth, this PR was only for the ability to click on the link and navigate to the suggest task page. The suggest functionality is for the related PR.

**Comment by nishithaShetty** [comment]
Hi Kyrene,
Good work! I was able to open the link through the Owner, Volunteer, and Admin accounts.
Attached are the screenshots below.
PR#2331_1
PR#2331_2
PR#2331_3

**Review by jennZhang93 — CHANGES_REQUESTED** [review]
Tested with owner and volunteer account. I can input, save, and view locally the suggestions I put in a task as owner or volunteer account. But when I switch account or logged off, the previous changes are not saved. See video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/cfe11cea-893e-42f2-9807-c8206aae5ffe

**Comment by nathanah** [comment]
> Tested with owner and volunteer account. I can input, save, and view locally the suggestions I put in a task as owner or volunteer account. But when I switch account or logged off, the previous changes are not saved. See video below.
> 
>  Screen.Recording.2024-06-08.at.1.28.39.PM.mov

You're suggesting changes and not editing the task, so it shouldn't be updated where you're looking. ... I forget exactly where task suggestions appear. I think it's in one of the numbered red circles. Regardless, I think it's out of the scope of this PR.

**Review by nathanah — APPROVED** [review]

**Comment by akshit0211** [comment]
Hi, I can successfully make suggestions on the task both as a volunteer and as an admin. Good work!

adding volunteer to the task
volunteer task
volunteer suggestion
admin suggestion

**Review by akshit0211 — APPROVED** [review]

**Review by jinxyou — APPROVED** [review]
I was able to click the task link, tested as volunteer, owner, and admin. And i'm able to suggest. Great work!
Screenshot 2024-06-08 203655
Screenshot 2024-06-08 203705
Screenshot 2024-06-08 214001
Screenshot 2024-06-08 214017

**Comment by Trip2310** [comment]
Hi Kyrene, I have tested the PR. it is opening the link 
HGN APP - Google Chrome 6_10_2024 11_39_09 AM

Uploading HGN APP - Google Chrome 2024-06-10 11-39-31.mp4…

**Review by JatinAgrawal94 — APPROVED** [review]
Task Description Window is visible on selecting the task.
But when I try to go back using the back button on the task description page, it doesn't take me back to the dashboard. This also throws couple errors in console. Please have a look at it. Considering the scope of this PR, the functionality works good.
Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/e5b8e9c5-2515-4846-a267-433d667a3427

**Review by Jingyii800 — APPROVED** [review]
Hi, I have tested this function and I can successfully interact with the suggest button in admin, owner and volunteer accounts. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/3a8470a7-b90e-4e04-8fc4-49985d6f8891

**Comment by Vijeth-V** [comment]
Hello Kyrene,
This works well, I tested with volunteer and admin account it works perfectly well.

Screenshot 2024-06-11 at 11 22 16 PM

**Review by Parth-tech — APPROVED** [review]
Hi Kyrene,
The suggestion works for all 3 users: Volunteer, Admin, Owner. Great Job!

Owner:
owner - dashboard
owner suggesting

Admin:
admin - dashboard
admin suggesting

Volunteer:
Vol - dash
Vol - task
Vol -suggesting
Vol - Suggest successful

**Review by TXMO-dev — APPROVED** [review]
Great work on this PR! The changes effectively allow volunteers, admins, and owners to navigate to the task page by clicking on a task. Everything looks good and the implementation is clean. Approved!

**Review by suaniii — APPROVED** [review]
Hi Kyrene,
I've tested this function with both volunteer and admin account and it works perfectly as expected. Great work!

Admin:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/14afdce0-b14f-4d4e-bc16-c41e46b09345


Volunteer:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/0711b7b0-ca31-4222-b328-33b18ea2638e

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
