### PR TITLE
Shefali PeopleReport selectors unit test

### PR DESCRIPTION
**Pull request by SMitta11**
# Description

Unit test for src/components/PeopleReport/selectors.js

Created test cases for selectors.js
selectors.test.js file created and added test cases in it.

- should return the correct pie chart data
- should handle edge case where number of tasks is exactly 5
- should handle case where number of tasks is greater than 5
- should return the correct data from state

## How to test:
1. check into current branch
2. do npm install
3. do npm test selectors.test.js 

## Screenshots of changes:
Screen Shot 2024-09-18 at 10 58 52 PM

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Hello @SMitta11 
Everything is working as mentioned.
Screenshot 2024-09-18 at 9 25 10 PM


Thank you.

**Review by chu-ziyu — APPROVED** [review]
I tested this PR and all tests passed. Thank you.
shefali-Unit-Test-PeopleReport-selectors

**Review by Lexie5212 — APPROVED** [review]
Hi, I have tested PR and all tests passed.
Screenshot 2024-09-18 at 23 50 14

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and all test cases passed successfully!!!

Screenshot 2024-09-19 135209

**Review by ArtemisNyx3 — APPROVED** [review]
image
tests passed

**Comment by tharunaa-1** [comment]
Everything works as mentioned.

image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the testcases have passed.
Screenshot (200)

**Comment by geetamatkar** [comment]
Hi @SMitta11 ,
I tested this PR and it is working as expected.

PR2692

**Review by RishithaMamidala — APPROVED** [review]
@SMitta11 
The PR passes all the test cases.
PR 2692

**Review by ashmita123 — APPROVED** [review]
The test cases are passing. Thanks!
Screenshot 2024-09-20 at 1 08 48 PM

**Review by jinxyou — APPROVED** [review]
image
All test case passed. Great work!

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the test cases passed.
Screenshot 2024-09-21 at 7 38 22 AM

**Review by Logeshwari-Renu — APPROVED** [review]
Tested the PR and all the test cases are passed!!

**Review by mohangadde1 — APPROVED** [review]
image
Test cases have been verified and passed

**Review by panchalvatneu — APPROVED** [review]
the tests passed and the logic is solid, but a few tweaks could improve it:

Instead of filtering and finding tasks/projects repeatedly, using _.groupBy might boost performance.
I'd also store "otherTasksTotalHours" as a constant for clarity.
Finally, edge cases like no logged hours or project-task mismatches should be covered in the tests.

image

**Comment by mianmiantea2019** [comment]
Test cases have been verified and passed

image

**Review by Gauravmg6 — APPROVED** [review]
All test cases have passed.
Screenshot 2024-09-22 183401

**Review by adityasure9 — APPROVED** [review]
It's working as expected. Great Job!

image

**Comment by SatyashanthiT** [comment]
I have reviewed the PR for the unit test of PeopleReport selectors, and the test cases are functioning as expected. The selectors are returning the correct data, handling edge cases properly, and the implementation looks solid.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
