### PR TITLE
yihan add team code permission

### PR DESCRIPTION
**Pull request by AriaYu927**
# Description
image

## Related PRS (if any):
The related backend PR is [#494](https://github.com/OneCommunityGlobal/HGNRest/pull/494)
This is the 2nd PR of #1162 which hasn't been merged to dev yet.

## Main changes explained:
- Update file RolePermissions.jsx and UserRoleTab.jsx for adding Edit Team 4-Digit Codes permission to permission management page.
- Update file UserProfile.jsx and WeeklySummariesReport.jsx for allowing edit team code section if the user is owner or has that permission.
- Update file FormattedReport.jsx and create TeamCode.jsx for separating TeamCode component from FormattedReport.jsx

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. log as Owner user
a. go to any user's profile page -> Teams Tab -> Team Code section, or Reports -> Weekly Summaries Report
b. verify if you can edit Team Code input field.
c. go to Other Links -> Permissions Management -> Manage User Permissions to add Edit Team 4-Digit Codes to a user who is not Owner.
4. log as that not-owner user who has Edit Team 4-Digit Codes permission
5. repeat step 3.a to see if this user can edit team code section.
6. log as any not-owner user who doesn't haveEdit Team 4-Digit Codespermission
7. repeat step 3.a, verify if the user cannot edit team code section.

## Screenshots or videos of changes:

1. Owner and other users who has Edit Team 4-Digit Codes permission:
截屏2023-08-31 15 28 01

3. Other users who doesn't have Edit Team 4-Digit Codes permission:
截屏2023-08-31 15 24 03

### CODE REVIEW

**Comment by iTvX** [comment]
I tested your pr, with the owner account it worked as described.
Snipaste_2023-08-31_14-02-51
Snipaste_2023-08-31_14-00-10
Snipaste_2023-08-31_14-01-20

However, I find I can not add permission to a specific user. 
Snipaste_2023-08-31_14-03-21


 not-owner user who doesn't have Edit Team 4-Digit Codes permission.
 
Snipaste_2023-08-31_14-05-24


However, I don't find report tab with using non owner account:
image

**Review by Haoj1 — DISMISSED** [review]
@AriaYu927 Your PR works as expected. The non-admin user can only edit the team code with permission. Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/4677cf26-0476-4945-b667-284e11c494d0

**Review by DavidC0126 — DISMISSED** [review]
Hi @AriaYu927 I tested your Pr and it works as intended.

editable

weeklySummary

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/f0939887-d859-40cd-b088-17c69b6d41ea

**Review by gabi-lima — APPROVED** [review]
Well done! It's working as expected!👍 
Owner account:
Captura de tela 2023-09-01 093506
Volunteer account with permision:
Captura de tela 2023-09-01 093625
Admin account with default permissions: 
Captura de tela 2023-09-01 093701

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Tested with backend PR#494. Adding and removing the permission to Edit 4-digit Team Code on an account works as intended. My only suggestion is can we add the functionality to enforce the 4-digit Team Code format? Currently you can add a team code with more than 4 digits. I haven't tested for adding a team code with less than 4 digits but my assumption is you're probably allowed to. 

It would also be a good feature to not have to require the user to manually enter a '-' into the team code and it just gets populated after entering the first character. We could also allow the user to enter lowercase characters that get converted to uppercase.

Also, I'm curious to know if the team names are connected to the team codes or not.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/704fe955-1259-4912-beda-43720a9f0aca

Screenshot 2023-09-01 at 3 05 17 PM

Screenshot 2023-09-01 at 3 06 27 PM

**Review by winghojackyli — COMMENTED** [review]
Hi @AriaYu927 , I've tested the PR and the owner part works great. 
Owner can change the team code of a user. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/2dd94d6a-6488-41e1-a5d6-3028a196fd74



But I cannot find the button for changing the permission of users. Besides, I cannot change the permissions of roles as well. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/859f032f-e06b-4360-be1c-eca74562e8c8

**Comment by AuroraLovesWhales** [comment]
Hi @AriaYu927. I have tested your PR and the functionality works as intended. Great job!

I have one suggestion. On the Weekly Summaries Report page, the Team Code field is in between text "Media URL" and the link to open the url, which may look confusing to the user. Maybe consider moving the Team Code field below it?

image

**Comment by one-community** [comment]
> I have one suggestion. On the Weekly Summaries Report page, the Team Code field is in between text "Media URL" and the link to open the url, which may look confusing to the user. Maybe consider moving the Team Code field below it?

Please put code to the LEFT of the "Media URL" words. I don't want it below because I don't want to take up any more vertical space. 

Please make this code editable on that page by an Owner also. Changes should auto-save just like they do with the Bio toggle there. 

For Profile Page, please move the box for entering this code into the Teams row and fix the alignment of the "Assign Team" button: 
image

**Comment by one-community** [comment]
> But I cannot find the button for changing the permission of users. Besides, I cannot change the permissions of roles as well.

Your account was downgraded to Volunteer. I've updated it back to Owner, so it should work now. As a volunteer, you shouldn't have had access to that page at all though. Please check if this is a new bug or you had some sort of special permissions.

**Review by belagaam — APPROVED** [review]
I tested your PR as per the instructions. Everything works as expected. I was able to make changes to the team code if the user had permission.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/f4487946-7ceb-4b38-a02d-9304b5ec778e

**Review by winghojackyli — DISMISSED** [review]
Hi @AriaYu927 , I've tested the PR and the owner part works great. 
Owner can change the team code of a user. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/2dd94d6a-6488-41e1-a5d6-3028a196fd74

I can also change the permission of other users to let them change the team code of others. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/80100b25-8eed-4246-b71c-2164fc081a49

**Comment by AriaYu927** [comment]
> > I have one suggestion. On the Weekly Summaries Report page, the Team Code field is in between text "Media URL" and the link to open the url, which may look confusing to the user. Maybe consider moving the Team Code field below it?
> 
> Please put code to the LEFT of the "Media URL" words. I don't want it below because I don't want to take up any more vertical space.
> 
> Please make this code editable on that page by an Owner also. Changes should auto-save just like they do with the Bio toggle there.
> 
> For Profile Page, please move the box for entering this code into the Teams row and fix the alignment of the "Assign Team" button: image

I've fixed issues that you mentioned in #1162 since this PR is for permission.
Update made in #1162:
1. Moved team code input field to the left of Media URL on weekly summaries page.
2. Changes that the user made is auto-saved
3. Moved the team code input box into Teams row and fixed alignment issue of "Assign Team" on profile page.

**Comment by AriaYu927** [comment]
> Tested with backend PR#494. Adding and removing the permission to Edit 4-digit Team Code on an account works as intended. My only suggestion is can we add the functionality to enforce the 4-digit Team Code format? Currently you can add a team code with more than 4 digits. I haven't tested for adding a team code with less than 4 digits but my assumption is you're probably allowed to.
> 
> It would also be a good feature to not have to require the user to manually enter a '-' into the team code and it just gets populated after entering the first character. We could also allow the user to enter lowercase characters that get converted to uppercase.
> 
> Also, I'm curious to know if the team names are connected to the team codes or not.
> 
>  Screen.Recording.2023-09-01.at.3.10.55.PM.mov 
> Screenshot 2023-09-01 at 3 05 17 PM
> 
> Screenshot 2023-09-01 at 3 06 27 PM

I have updated #1162 based on your suggestion cause this PR is for edit team code permission. Besides, team names haven't been connected to codes yet. I'll in the next PR of this task.

**Review by GaryB93 — DISMISSED** [review]
The functionality of this PR works as intended. Suggestions for enforcing the Team Code format were accepted. Great work!

Screenshot 2023-09-05 at 2 45 58 PM

**Review by Shiwani99 — DISMISSED** [review]
Hi,
Great job. I tested your PR and it works as expected. I tested by adding and removing edit 4 digit permissions for administrator account and it worked as mentioned.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/2a7d69b3-7d2e-4aab-af57-d96d5b66569e

**Review by navneeeth — APPROVED** [review]
Hi, @AriaYu927! Tested your changes and they LGTM! First, logged in as an Owner user and navigated to Reports->Weekly Summaries Report to verify if I can edit team code input field. It worked fine. Then went to Other Links -> Permission Management -> Manage User Permissions to add the Edit Team 4-Digit Codes to a user who is not a owner (Admin).

Logged in as this admin and checked Reports -> Weekly Summaries Report and I was able to edit the team code input field.

Next, logged in as a Volunteer account and realized that there was no access to Other Links. So, logged back in as another Admin account which didn't have the Edit Team 4-Digit Codes permission and as expected, I could not edit the team 4-digit codes. Good work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/0ef43c88-a6ea-42e0-a4b8-cd5de1f302fd

**Review by wantingxu7 — DISMISSED** [review]
Hi @AriaYu927, I've tested the PR and it works as expected. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/34714d7c-57af-4244-b8ba-8169852ed248

**Review by EdwinLauM — COMMENTED** [review]
Hey @AriaYu927, I was able to successfully change the team code using an owner account. However, after granting the permission to a non-owner user I went to another user's profile page -> teams tab -> changed the team code but there is no save button to save the changes of the new team code

Video of changing the team code as an owner and changing the permissions for a non owner user:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/d1b4909e-0bb9-4f66-8f0a-9a426e03c796

Video of logging into the non-owner user and not bale to save changes for the team code

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/4139135f-5913-4f74-a541-3910e656fbd7

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Found this pull request to fail under it's own testing conditions in the circumstance of:

"Admin" user that doesn't have "Edit Team 4-Digit Codes" permission granted to it. When navigating to the "Weekly Summaries Report" page. team code is showing up as an input when it shouldn't be. 

Please clarify if this is an unintended or intended. I'll be requesting changes in the meanwhile, since your testing guide shows it as something that I shouldn't be able to do.

pr1208 admin doesnt have permission

pr1208 admin doesnt have edit team code permission but shows as input


Rest of the conditions are fine. My admin account cannot edit team codes on user profile pages.
pr1208 admin can't change team code due to not having permiss


Owner account can change team codes without issue since permission is granted:
pr1208 can change team code

volunteer account can't change team code by default:
pr1208 volunteer can't change team code
volunteer account can change team code after having permission granted to it:
pr1208 volunteer can change after altered permission

**Comment by KurtisIvey** [comment]
Here's what I'm seeing on my end. It shows as it should on the userprofile, but on weekly summary report page the input is editable
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/19482363/2e00dc70-4d0e-4e71-bf73-69d9194cce86

**Comment by AriaYu927** [comment]
@KurtisIvey  Thanks for letting me know. I've fixed this issue, please check.

**Comment by AnishPandita** [comment]
Hey, I tested all the cases and here is what i found:
1. Owner account can freely change the permissions and team code.
Screenshot 2023-09-26 at 1 03 37 PM
2. Admin account without edit permission cannot update the team code on user profile or summary report page. The issue raised by @KurtisIvey seems solved.
Screenshot 2023-09-26 at 1 04 38 PM
Screenshot 2023-09-26 at 1 11 38 PM
Screenshot 2023-09-26 at 1 13 31 PM
3. The volunteer cannot change the code by default but can do it after permission is granted.
Overall I think everything works fine.
Screenshot 2023-09-26 at 1 05 25 PM
Screenshot 2023-09-26 at 1 08 06 PM

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Your frontend is secure and functioning properly now. However, your backend doesn't have an authorization check to prevent my admin account from changing the team code to whatever I want it to be. Forcing my way in like this might've been slight overkill, but it does show that the backend allows admin accounts to make changes to the team code. Therefore, if only an owner should be allowed to make that change, it may be worth creating a specific controller to handle that or modifying the current. 

Not to mention, my new team code:**Bruh Y this happening**  ~  exceeds the 4 digit code standard too. Want want some sort of length validation to reject team codes that aren't in the 4 digit format.

Screenshot 2023-09-27 at 4 02 35 PM

**Review by KurtisIvey — APPROVED** [review]
Everything works now. I can't edit team codes using my admin account in postman.

pr494 no longer able to edit team code
Screenshot 2023-10-03 at 1 45 48 PM
Screenshot 2023-10-03 at 1 46 31 PM

**Pull request merged**
