### PR TITLE
Make 'Save' button visible to the users who have 'Edit User Profile' Permission

### PR DESCRIPTION
**Pull request by EdwinLauM**
# Description

Screen Shot 2023-08-24 at 9 55 57 PM

## Main changes explained:

- Made code changes for button to be visible under user profile section when user has Edit User Profile Permission

## How to test:

1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as Owner user
4.  Other Links -> Permissions Management -> Manage User Permissions -> Give "Edit User Profile" permission to a non Admin/Owner user
5. Log into that user -> Click into any user -> Make sure you are able to see all buttons under user profile section

## Videos/Screenshots of changes:

Before:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/ab64edf9-4377-47f5-a60b-e3bf3c657946

After:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/2ab2b07c-69f3-4b15-b105-c0ccb9bf9237

### CODE REVIEW

**Comment by palakgosalia** [comment]
Hey, I reviewed and tested your PR. I was able to assign the edit user profile permission to my volunteer account. I tried to edit a field and save the change but got an error. Is this expected? Details in the video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/d6818533-01a6-4b60-a21a-52d7607de702

**Comment by wanglu1207** [comment]
@EdwinLauM , after doing the review, I didn't see the two button. In the console, it shows the backend has errors. I am wondering if there is a relationship with the backend part?

**Review by kavya151 — APPROVED** [review]
Hi @EdwinLauM I have tested your PR locally. 
Observation:
After giving edit profile permission to an user, the user is able to edit any other users profile and save the changes. I have also checked that the user is unable to access save button on his profile. Everything is working as intended.
Good Job!!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/9f63b6c5-3466-4830-8452-bdeca37a88a2


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/61841929/3c36ed7d-445a-4f5b-8ab2-c1b6b42dd3cb

**Review by nathanah — CHANGES_REQUESTED** [review]

**Review by Changhao3220K — COMMENTED** [review]
Hi @EdwinLauM 
I tested this PR on my local machine using dev branch as backend, but I need some assistance to create a onwer account. Currently both the local and dev site does not allow me to create one. I tested the function under admin but the buttons does not show up.
Screenshot 2023-11-20 at 8 06 35 PM
Screenshot 2023-11-20 at 8 10 40 PM

**Comment by beblicarl** [comment]
This functionality works as intended.

[screencast-localhost_3000-2023.11.21-12_44_36.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/2f49cb8b-ab26-410a-97fe-44804aec166c)

**Review by beblicarl — APPROVED** [review]

**Pull request closed without merging**
