### PR TITLE
Nahiyan finishing for Jay fix header UI mobile optimization

### PR DESCRIPTION
**Pull request by jayyy-s**
# Description
image
Fix Header UI for smaller viewports
- Don't show header on login
- Space items on small viewports

## Related PRS (if any):
This is unrelated to backend PRs. Use latest `development` branch of HGNRest

## Main changes explained:
- Update `src/components/Header/Header.jsx` to return null if location pathname is `/login`
- Update `src/components/BMDashboard/BMHeader/BMHeader.jsx` to do the same because there is a comment in `route.js` saying to uncomment `BMHeader` component
- Update `src/components/Header/Header.css` to not use `column` for `flex-direction`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log out and verify that header is not present
5. log as admin/volunteer (any) user
6. go to dashboard
7. resize viewport in developer tools so either width is below  760px
8. verify alignment of header is correct

## Screenshots or videos of changes:
no header on login
Before
dev branch header
After
new header spacing

### CODE REVIEW

**Review by kdaga81 — DISMISSED** [review]
image
The alignment of header is correct

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and verified the alignment of header for width below 760px. The resize functionality works fine.

**Comment by agryash** [comment]
I see this PR works great for these two viewports:

image

image

but I see icons overlapping here:

image

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works as intended. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/69e20496-af82-42e8-b7a5-8ee0aa914b31

**Review by jinxyou — DISMISSED** [review]
The header fix looks good after resizing. Great work! 
Screenshot 2024-06-22 192017

**Review by Nahiyan-16 — CHANGES_REQUESTED** [review]
Hi Jay, great job getting rid of the header on the login screen, but we still see the overlapping issue for the header items. Along with that, we need some space for the logo. I suggest that we keep the header collapsing into two rows, but let's just have some spacing when the items are tightly grouped. 

Screenshot 2024-06-24 110202
Screenshot 2024-06-24 110408

SUGGESTION, add space between items when header is 767px or below:
Screenshot 2024-06-24 110949

**Comment by sahithidhulipala9** [comment]
Working as expected!
Screenshot (78)

**Review by sahithidhulipala9 — APPROVED** [review]

**Comment by jayyy-s** [comment]
> Hi Jay, great job getting rid of the header on the login screen, but we still see the overlapping issue for the header items. Along with that, we need some space for the logo. I suggest that we keep the header collapsing into two rows, but let's just have some spacing when the items are tightly grouped.
> 
> Screenshot 2024-06-24 110202 Screenshot 2024-06-24 110408
> 
> SUGGESTION, add space between items when header is 767px or below: Screenshot 2024-06-24 110949

Hi Nahiyan, I've implemented some of the suggestions that you've made in the recent commit.

**Comment by IchinnorovTuguldur** [comment]
Hello Jay,
 Tested the header and it is below 760px and doesn't show up on login screen.

**Review by tianyangL11 — CHANGES_REQUESTED** [review]
Good job expect an little issue about the overlapping on the header.  As you can see in the picture, some of the logos are misplaced.

**Review by Nahiyan-16 — DISMISSED** [review]
Hi @jayyy-s, great job fixing the issue and on the PR itself. The spacing on the header items is perfect and working as expected.  Please resolve merge conflicts and it's ready. @one-community

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected.

https://github.com/user-attachments/assets/441fb1e1-8845-45c1-a5af-0df929e6eca5

**Review by SrikanthChowdary495 — COMMENTED** [review]
I have tested this PR. I  the overlapping issue for the header items. Everything good. I am attaching a video for reference.

https://github.com/user-attachments/assets/3b5fd401-0068-42da-a17b-5e589f58842a

**Comment by angelalalacheng** [comment]
Hi,
 I use `Jay_fix_header_UI_mobile_optimization` for frontend and latest `development` branch of HGNRest. There is no header in Login Page but some icons overlapped around 1000px screen width. Other alignment works as expected.

Screenshot 2024-07-21 at 3 39 53 PM
Screenshot 2024-07-21 at 3 42 04 PM
Screenshot 2024-07-21 at 3 44 27 PM
Screenshot 2024-07-21 at 3 45 46 PM
Screenshot 2024-07-21 at 3 46 29 PM

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey Jay,
Here are few issues i found
1) Their is overlapping of header elements during certain pixels
image
2)In smaller views When menu is opened its not fitting all the content together
image
3)"Please only use the Dev Admin account to create your own accounts. (AND PLEASE DO NOT EDIT THIS!!!!)" Message is Visible on few Screen sizes  and is Not visible on other
image

Thank You.

**Comment by arunsrao9** [comment]
I have tested the PR and verified the alignment of header for width below 760px. The resize functionality works fine in few cases but there is overlapping of header elements during certain cases(especially when the width > length).
Here are the Screenshots of my observation: 
Overlap_SS
SS1

**Review by kabraambika — CHANGES_REQUESTED** [review]
I have reviewed the frontend PR along with the associated backend PR. Here are my observations:
Menu items are overlapping as shown below:
image

Dark mode text is overlapping behind the clock buttons as shown below:
image

**Review by varunreddy03 — CHANGES_REQUESTED** [review]
I have tested this PR and the Header File is overlapping for screens width 1024px and below. I have attached the images of the issue below.

PR 2378_1
PR 2378_2

**Review by AnkitLall — COMMENTED** [review]
Hi @jayyy-s,

I have tested the feature according to the instructions in the PR and found a couple of issues. There is overlapping of elements in the header, and when testing on different devices, the header gets cut off on the iPad Pro screen size. Additionally, I noticed a console error upon page load. Please refer to the screenshots of the issues below.

Screen Shot 2024-08-09 at 5 36 41 PM
Screen Shot 2024-08-09 at 5 54 35 PM
Screen Shot 2024-08-09 at 5 54 53 PM

**Review by adityasure9 — APPROVED** [review]
Tested the PR and verified the header UI on different screen widths. The header does not appear on the login page as expected, and the alignment looks correct for most small viewports. However, there are still some overlapping issues with header elements around certain screen widths (e.g., 1024px and below). Additionally, in smaller views, the menu content doesn't fit well, and the dark mode text overlaps behind certain elements. These issues need to be addressed before the PR can be approved.

Before,



After,


At 1000px,

**Review by SnelPatare — COMMENTED** [review]
I tested the PR for 920 X 736. I can see header overlapping icons . Please find the image below

image

**Review by oliviahyw — APPROVED** [review]
I have tested this PR and the styling worked as expected.
PR2378

**Comment by FayeLV** [comment]
Hi,

Great job! Overall, everything looks good, just a few small suggestions:
Snipaste_2024-08-29_21-50-38
Snipaste_2024-08-29_21-51-17
Snipaste_2024-08-29_21-54-06
Snipaste_2024-08-29_22-02-32

The badge icon on the right is a bit too close to the screen edge. It might be helpful to add more right margin to enhance its appearance on small screens.
The timer buttons seem slightly misaligned, and the spacing between them is uneven on larger screens. It could be beneficial to adjust the alignment and spacing for a more consistent and balanced layout.
Additionally, it might be worth considering a color change for the "dark mode on" text when in dark mode to improve visibility.

Thank you for your hard work!

**Review by vedantg24 — COMMENTED** [review]
Tested the PR, and there are a few issues I noticed. There is no header on the login page as expected, but there are overlapping issues in header elements for screens width 1024x and below. Also, for small viewports, the menu contents doesn’t fit well and some items are cut off. I have attached screenshots for reference.

Screenshot 2024-08-31
Screenshot 2024-08-31
Screenshot 2024-08-31

**Comment by sud306** [comment]
Hello,
I have tested the PR and apart from the overlapping issue, everything else looks fine.
6  PR2378_1
6  PR2378_2
6  PR2378_3

**Review by swaroop-2007 — CHANGES_REQUESTED** [review]
Hi, I've reviewed this PR and here are my observations:

1. The menu items are overlapping in some pixels. Here is the screenshot for reference.
Screenshot (386)
2. For the mobile view, the suggestions development section is not fully visible. 
Screenshot (387)

**Review by strallia — CHANGES_REQUESTED** [review]
### These changes are working as expected:

- Header is not present on login screen

### Issues found:
These are present on all user account types except owner, which I don't have a dev account for.

- The “Please only use the Dev Admin account …” text disappears at widths between 1050-1280px

https://github.com/user-attachments/assets/675ce2af-1db9-491a-947c-27a75475b522 

- Overlapping of header elements occurs between 575-750px

https://github.com/user-attachments/assets/5a4d6014-536b-4c27-9151-aa051ea466ac

- Menu items in the hamburger menu get cut off at 550px and below

https://github.com/user-attachments/assets/613c220d-d579-4459-8724-f1de416879f2

https://github.com/user-attachments/assets/d62bb873-7143-419c-8603-e07995599501

**Review by crystallow1168 — COMMENTED** [review]
image
✅ Header isn't showing on login page

image

✅ Items in header looked aligned at 1200px width
❗️The "Welcome, <name>" looks cutoff on the right when width is around 1200px 

image

❗️Icons looks to be overlapping on "Dark Mode On" on screen width between 1050px to 768px

image

❗️After clicking on the hamburger menu, the navigation links doesn't look aligned (Ignore if fix isn't in this change scope)

image

❗️At screen width 460px and below, the timelog icons isn't aligned

**Pull request closed without merging**
