### PR TITLE
Carlos improvement team hours visualization

### PR DESCRIPTION
**Pull request by cgomezhub**
# Description

Improved Project Report Pie Chart

   - new switch toggle button have been added
   - Select postition: you can select by one each member by Control + click 
   - All position: you set all memmbers involved in the project

## Related PRS (if any):
This frontend PR you have to use backend development branch 

…

## Main changes explained:

visuaization before:

https://www.loom.com/share/96202310aeb543518cacca3f2e68806d?sid=fb746e19-3706-46e5-a7d9-2e6a4d084b64

Visualization after:

https://www.loom.com/share/e95656f545c34ef387b987b0f7d98fe5?sid=39b061a7-119a-4d3b-8042-7ef8752a37d6

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ reports→ reports→ and choose any project
6. verify function “A” (feel free to include screenshot here)
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

https://www.loom.com/share/e95656f545c34ef387b987b0f7d98fe5?sid=39b061a7-119a-4d3b-8042-7ef8752a37d6

### CODE REVIEW

**Review by anji-annavarapu — APPROVED** [review]
https://github.com/user-attachments/assets/c2943918-0a7c-4df5-9ea6-e233de7ecbd6

i was tested thoroughly, it is working fine

**Review by audreydieuanh — APPROVED** [review]
It is working both in light mode and dark mode.

test7

**Review by Rui-Liu-github — APPROVED** [review]
HI I reviewed PR #2855 by pulling the latest version. All works well as mentioned.

image

image

**Comment by RashmiKY98** [comment]
Tested the functionality. Below are the observations.
1. When clicked on the toggle button, there is an overlap of text displaying the percentage with the pie chart.
Screenshot 2024-11-10 001444
Screenshot 2024-11-10 001346

2. For the Project report Aa-2443-PR, The select toggle button did not work.
Screenshot 2024-11-10 001629

**Comment by beblicarl** [comment]
This feature works as intended and the code is great

[668e24ec-fed7-4924-8b9b-d0b081f052ca.webm](https://github.com/user-attachments/assets/ec6a1878-5957-4d6a-82d2-7027c9ffabe8)

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/439d2e90-e075-45db-b1e1-ff3a1c9cc5f9

**Review by nikhilgiri0226 — APPROVED** [review]
I have reviewed the PR and everything is working fine. The new toggle switch was working fine and the overall transition of the pie chart on mouse hover looks good.


https://github.com/user-attachments/assets/cabe76fd-dd43-4627-81ac-4dd1b1c3e407

**Review by SS-Reddys — APPROVED** [review]
Changes are working as expected.

image


image


image

**Comment by ppsahu** [comment]
I have tried to review this PR and I am seeing login issue for all the 3 accounts. it is not allowing me to enter the dashboard of HGN app. Below are the screenshots for reference.

Screenshot 2024-11-29 at 1 49 02 PM
Screenshot 2024-11-29 at 1 53 05 PM

**Comment by ppsahu** [comment]
Update from my side: I got my account issues resolved.

I have tested the changes, All the changes are working as expected. However, there is a minor error, where when I select the "Select All" toggle button for the weekly committed pie chart(bottom), it does not work for bottom pie chart, but instead toggles the all-time total hours pie chart(above), if both the pie charts are enabled. The button does work when only weekly committed pie chart is enabled.  [I hope this is understandable!] I have attached the recording below.

This happens the same in dark mode.

https://github.com/user-attachments/assets/cafc2601-0307-45e0-9a0d-9cf9014dc691

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
