### PR TITLE
Lucas timelog page not loading

### PR DESCRIPTION
**Pull request by Lucas-E**
### **DESCRIPTION**
<hr>
I've seen that the timelog page was not loading on the development branch, so i searched the reason and the userId state on the page was getting an undefined state.

### **Main Changes**
<hr>
Inside the Timelog.jsx file, changed userId from this.props.asUser to this.props.auth.user.userid

### **How to test**

- Checkout to current branch
- npm install and npm run start:local
- Log in as various users and roles
- See if timelog page is loading and showind the right data

*note: If you guys know anything about the asUser object, let me know. I've seen that this error happening in other branches too.

beforeSolvingProblem
afterSolvingProblem

### CODE REVIEW

**Comment by vitorsaa2k** [comment]
Working well on both Administrator and Volunteer account. Thank you for fixing this bug @Lucas-E!

image

**Review by vitorsaa2k — APPROVED** [review]

**Review by NyahJ — APPROVED** [review]
Hi @Lucas-E,

It worked for different account as intended, thank you!
截屏2023-03-03 下午2 38 43

**Comment by angelinatr15** [comment]
Hi @Lucas-E,

I tested this branch by logging into the following users: role master, mentor, manager, testing, volunteer, core team, and admin. The Timelog page rendered for all the users i logged into. The results are as expected, below is an image of the page that rendered on admin. 

Before:
Screenshot 2023-03-03 at 3 05 11 PM


After:
Screenshot 2023-03-03 at 3 04 21 PM

**Review by angelinatr15 — APPROVED** [review]

**Comment by agujjar2206** [comment]
Hello @Lucas-E, I have tested this PR using Admin and Volunteer accounts, and it works as expected.

Before:


After:



Thank you.

**Review by agujjar2206 — APPROVED** [review]

**Review by tingedudu8 — APPROVED** [review]
@Lucas-E, I tested several roles and the results are as intended. Thanks!
PR692

**Comment by anant2047** [comment]
I tested the code for various user types. The website works as expected and the code changes looks good. Sharing the screenshots for different users - 
Screen Shot 2023-03-03 at 6 36 47 PM
Screen Shot 2023-03-03 at 6 37 19 PM
Screen Shot 2023-03-03 at 6 38 51 PM

**Review by anant2047 — APPROVED** [review]

**Comment by RafaelCastilhoCastro** [comment]
Hi @Lucas-E,
I tested your PR using all account roles and the Timelog are displayed as intended. Good job.

**Comment by ayush0904** [comment]
Hi @Lucas-E I have tested the PR and it is working as expected. Thank you. However, not related to this PR please see the below pic, The Current week(highlighted) is not align with the Summary. 
Screen Shot 2023-03-04 at 12 09 28 PM

**Pull request merged**
