### PR TITLE
Ilya - Tools table

### PR DESCRIPTION
**Pull request by ilyaflaks**
tool-list-task

# Description
Adds functionality for the user to navigate to [/bmdashboard/tools](http://localhost:3000/bmdashboard/tools), and view a list of all tool items currently in the system. The table can be sorted by tool name or by project and the results can be filtered by tool name. Update History and Purchase History can be viewed for each item in a modal. 

## Related PRS (if any):
This frontend PR is related to the [#913](https://github.com/OneCommunityGlobal/HGNRest/pull/913) backend PR.
To test this frontend PR you need to checkout the #913 backend PR.
…

## Main changes explained:
- A new route was added to routes.js to correspond to "/bmdashboard/tools"
- ToolsList.jsx, ToolItemListView.jsx, ToolItemsTable.jsx, ToolRecordsModal.jsx and UpdateToolModal.jsx components were created
- New redux action created to make an API call and receive a list of tool items
- Table columns correspond to the information found on tool item schema, which is vastly different from Material or Consumable items

## How to test:
1. Check out **ilya_tools_list branch** on the back end. Make sure you are using Node version 14.17.6. Run **npm install** and **npm run build && npm start** to run the backend locally
2. Check out the current branch on the frontend. Run commands **npm install** and **npm run start:local** to launch the front end application
3. Log in as any user
4. Go to [/bmdashboard](http://localhost:3000/bmdashboard) and log in again
5. Navigate to [/bmdashboard/tools](http://localhost:3000/bmdashboard/tools). A list of all tools currently in the system should display. 
6. Test the filtering by Project and Tool function (the dropdowns above the table)
7. Test sorting by project and by name (the arrows next to "Project" and "Name" in the table header
8. Pressing the View button under Updates should open an Updates Record modal (not all items have information to display)
9. Pressing the View button under Purchases should open an Purchase Record modal (not all items have information to display)
10. Pressing the pencil should open an Update Tool Form modal. The content of this modal is outside of the scope of this task

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105448137/fdd8c961-0d34-4219-b1c5-743aef1c2820

### CODE REVIEW

**Review by alla0810 — DISMISSED** [review]
Hi, Ilya!
Nice work!
All functions are working as intended.
I could successfully access [`](http://localhost:3000/bmdashboard/tools) without error, and I could access this url with minimum performance delay.

I could see the list of tools on this url, and also filtering by project/tools worked great.
By clicking the `view` buttons and pencils, I could see the detailed `Update Record` history.

Thumbs up!




https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131193110/e97bee68-0e51-4712-8115-a6eea4a2a5d2

**Review by Ramaruva — DISMISSED** [review]
Hi, I have verified changes in my local env and they are working as expected 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/64008831/5b3092cc-6371-4a57-8cbe-d24e5352bbba

**Review by Parth-tech — DISMISSED** [review]
Hey Llya,
I have review you code base it works as intended. Great job!

Video Reference:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56110372/95da419f-966e-40c8-ad78-b4e65336ddb7

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and all the changes work as mentioned. Good work.
Screenshot 2024-05-03 at 10 46 29 PM
Screenshot 2024-05-03 at 10 46 33 PM
Screenshot 2024-05-03 at 10 46 36 PM
Screenshot 2024-05-03 at 10 46 42 PM
Screenshot 2024-05-03 at 10 46 54 PM
Screenshot 2024-05-03 at 10 47 15 PM
Screenshot 2024-05-03 at 10 47 19 PM

**Comment by KaushikMreddy** [comment]
Reviewed this PR on the backend: https://github.com/OneCommunityGlobal/HGNRest/pull/913#issuecomment-2105934161

**Review by nathcarnevalli — COMMENTED** [review]
Reviewed on [backend](https://github.com/OneCommunityGlobal/HGNRest/pull/913#pullrequestreview-2055505064).

**Comment by ilyaflaks** [comment]
@KaushikMreddy @nathcarnevalli please try again now

**Review by nathcarnevalli — DISMISSED** [review]
No issues or errors, nice work :)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/bd3d73a0-ee5e-402f-b025-d18f6c2febca

**Comment by ZhangPeizhou** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95693786/0223dc14-ea07-4fb5-9753-93db8668de16

All functions work well, but the dark mode is not working. Maybe we can fix it in a different PR.

**Review by DaveB4r — DISMISSED** [review]
Everything is perfect!
Great Job!
Building Management Dashboard OK!
bmdashboardlogin
Building and Inventory Management Dashboard OK!
bmdashboard
Tools OK!
bmdashboardtoolsfilter
Sort Tools OK!
bmdashboard-sort-runs
Purchase Record OK!
purchase

**Comment by nishithaShetty** [comment]
Hi Ilya, Great work, filters for the table work as expected. The updates and purchases modal work as expected as well. 
Sorting only works when the project value or tool value is ALL - screenshot PR#913_1
if you change that value to anything else, you cannot sort the columns after that - PR#913_2
PR#913
PR#913_1
PR#913_2

**Comment by KurtisIvey** [comment]
Hi Ilya, if you can clear up the merge conflict on this, I would love to move it to final review, so it can get merged asap

**Comment by ilyaflaks** [comment]
@nishithaShetty that is the intended behavior

@KurtisIvey yes, please! I fixed the merge conflict. Please help me merge this before more conflicts arise

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
