### PR TITLE
Lucas revert to time log

### PR DESCRIPTION
**Pull request by Lucas-E**
# Description
(PRIORITY LOW) Rafael/Jae: Fix Tasks revert to Time Log tab for users OTHER THAN VOLUNTEER 
Only applies to Volunteer accounts, since all other account roles should always stay with the Task tab as default.  (WIP Lucas)
Tested [THIS PR 734](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/734) and accounts other than Volunteer are now reverting to Timelog tab too. Not all, but some. Need a new PR that fixes this so ONLY Volunteer accounts display this function. 
If a VOLUNTEER has no tasks, then their default tab should be "Current Week Timelog" not "Tasks". If their tasks are resolved via the green checkmark, and they have none left, then their view should return to "Current Week Timelog".

## Main changes explained:
Once a volunteer user has no task, the Time Log tab should be the default tab for that user

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. give task to volunteer user
5. check if the Tasks Tab is shown first for that user
6. dismiss the task
7. refresh the volunteer user page and check if the Timelog tab is activated by default

### HOW TO CREATE A TASK, ASSIGN IT TO AN USER AND TEST MY PR

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92558269/40a95abc-aaab-4e4c-bbf0-060aaeac1186

### CODE REVIEW

**Review by bienzguoa — APPROVED** [review]
works as intended!
Screenshot 2023-06-13 at 1 31 57 AM
Screenshot 2023-06-13 at 2 02 09 AM

**Comment by KurtisIvey** [comment]
Instructions aren't clear enough for someone new to the code base and app, so I'm unable to properly review this. Please provide some additional instructions in the steps to assign tasks while logged in as an admin to a volunteer, and I'll be more than happy to finish up.

**Review by mahamakhan — APPROVED** [review]
Added a few tasks and checked the volunteer everything works as mentioned. 

image

**Review by stevenpaalz — APPROVED** [review]
Changes appear to be working as intended.

With a task assigned on load.
Screenshot 2023-06-13 at 3 23 32 PM

With no task assigned on load.
Screenshot 2023-06-13 at 3 16 25 PM

**Comment by Lucas-E** [comment]
Thank you everyone! Moving to final review!

**Review by cvtqx — COMMENTED** [review]
I agree that for new team members the instructions provided are not clear enough to review this PR. It was not clear how to create a task and whether I should check it and dismiss it from Admin account or a volunteer account.  It would be easier if there was a video showing the implemented functionality.

**Comment by Lucas-E** [comment]
> I agree that for new team members the instructions provided are not clear enough to review this PR. It was not clear how to create a task and whether I should check it and dismiss it from Admin account or a volunteer account. It would be easier if there was a video showing the implemented functionality.

I'm going to record a video on how to create a task and what should be tested on this PR. As soon as add it, I'll DM you and the other member so you guys can watch it and review my PR!

**Review by KurtisIvey — APPROVED** [review]
Finally got this thing to work. Just wanted to mention in case any other fellow newbies are having issues seeing tasks assigned on their tasks section. Create a new team and assign the test volunteer account to it. Doing so will allow the tasks assign to be visible.

functions as intended 😅

after assigning tasks
pr908 load task tab on volunteer login

clearing tasks with owner account and checking for functionality
pr908 reverts to current week timelog after clear task

**Review by NidaZaki — APPROVED** [review]
Good job! Works as intended!

**Comment by KaixiangGU** [comment]
Work as intended!

**Review by KaixiangGU — APPROVED** [review]

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @Lucas-E. I have reviewed this PR and the functionality is working as intended. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/420d79a4-ffea-4da2-b314-0530ed521cc9

**Pull request merged**
