### PR TITLE
Xiaoyu add editable role info modal  on profile/permission

### PR DESCRIPTION
**Pull request by 20chen-7**
# Description

Screenshot 2023-07-11 at 4 30 47 PM

## Main changes explained:
- Create RoleInfo Reducer to store roleInfo text
- Make an editable model
- Change the visibility and editability
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
Log in as Owner:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/bbdafbfa-376e-4d94-9ba4-624372672975

Login as manager:

Screenshot 2023-07-11 at 4 35 05 PM
Login as volunteer:
Screenshot 2023-07-11 at 4 35 30 PM

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by siddharthmohite — APPROVED** [review]
Logged in as an Owner, I could see the information icon " i " in blue. Editable and can be saved.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37925823/1adeeb3a-cc08-4b83-89d2-2fcce5d6faea

Logged in as Owner:
Screenshot 2023-07-11 at 7 27 58 PM

Logged in as Volunteer
Screenshot 2023-07-11 at 7 32 32 PM

All of the updates work as intended.

Suggestion:
There can be a bit of a delay on the "i" icon when the user hovers over the button.

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello [20chen-7](https://github.com/20chen-7),

I reviewed your PR and looks great works as intended. 
Owner's can view the "i" and edit it the text. When a new role is created, the "i" is also added and can be clicked and edited. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/dc1cce63-fd34-42eb-9c5a-6a4286dfde13


Admins can also view the "i" however, are unable to edit it. They can also view it in the permissions mangement page as well. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/198751e4-dc18-4519-a54f-9f8120f3897e


Volunteers are unable to view in their profile pages which is expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/59dfe298-437a-461c-b4a8-40e0e4d6bed2


A few changes I'd recommend 

- the "i" is to cloes to the text in the permerssion mangement page. Adding a bit of margin should fix it. 

Screenshot 2023-07-11 at 8 10 41 PM

- I think there should be a delay as well [siddharthmohite](https://github.com/siddharthmohite) pointed it out and I agree. It is to snappy and feels a bit unnatural. 

- Next, the background is different depending on which page you are on. If you view the "i" on the profile page, the background becomes gray and see through. 
Screenshot 2023-07-11 at 8 12 14 PM

However, if you hover over the "i" on the permissions page it becomes completely dark. 
Screenshot 2023-07-11 at 8 11 47 PM

I'd say keep it consistent and select the grey background. 

Lastly, I'd add default text, just like you did in your testing, describing each role so when user's view it they can get the correct details.

**Review by AaronPersaud — CHANGES_REQUESTED** [review]
I've tested and it looks good!

<b>Icon not visible for Volunteer role</b>

996_volunteer_no_icon

<b>Opening and editing modal</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/fbb76090-de9a-4aac-b023-3973610e57f7

- when hovering the icon, the modal appears
- can open and close modal successfully
- can edit and save text in modal successfully

 However, I have a few suggestions.

1.) Profile -> Basic Information -> Scroll to bottom of page -> Hover icon -> Click close or click outside modal

This causes the page to jump to the top which I'm not sure is the intended behaviour as this doesn't happen if you're scrolled down in the Permissions Management page.

2.) Closing the modal without saving still saves the new text, which makes the save button redundant. Either remove the save button, or make sure it doesn't save automatically when closing the modal.  
- Another consequence of this is upon reopening the modal without saving, the modal text is automatically editable and the button says "Save" instead of "Edit". I feel that closing the modal should always grey out the textbox (disable) and change the button back to "Edit".

3.) In the Permissions Management, the "i" icon can be a bit smaller and shifted to the right a bit as to not touch the text.

image

If you look at the image above, you can see it almost always touches the text
(This suggestion is more of a personal preference, I'm not sure what the styling practices for this would be).

**Comment by one-community** [comment]
For the non-editable view, please make this look consistent with the ones we already have, like this: 
image

This is from the Dashboard --> Tasks and Timelogs "i"

**Review by tdkent — CHANGES_REQUESTED** [review]
Local testing confirms

- the blue **i** icon has been added to the **User Profile** page.
- this icon is visible and interactable to all classes _except_ Volunteer.
- the blue **i** icon has been added to the **Permissions Management** page.
- this icon is attached to each user class listed in the User Roles menu, including any newly created class.
- hovering over the icon immediately in either location launches the **Class Information** popup, which is viewable to all classes (except Volunteer) and editable only by Owners.

However, there appears to be some missing functionality as well as styling issues that should be addressed:

Functionality:

- Any edits made in the form are applied globally. As a result, there is no differentiation in the text based on the class being hovered.
- the modal state is not updated when the modal is closed by clicking the **Close** button or background. Text updates and the Save button state persist until the page is reloaded.
- On the User Profile page, there is no icon available when selecting the Volunteer class as an Owner or other allowed class.
- the PR description indicates the icon should be added to three locations. It is not clear where the third location is, or if this has been implemented.
- the icon is not visible in the mobile version (< 1024px) of the User Profile page.
- since the popup activates on hover, interaction may be difficult on touch screens.

Styling:

- there is a slight screen shift when hovering the icon the User Profile page
- the effect on the background when the popup activates is not consistent. User Profile background is a grey screen, in Permissions Management its a (jarring) fade to full black.
- popup retains the "Edit Form" styling when activating in a non-Owner class, which is not consistent with other informational popups.

Mobile Testing:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/1f0bcffd-0e7d-490d-86e1-757377b27add

Main Testing:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/a3853715-647e-4850-9414-4140fdd6a935

**Comment by AnishPandita** [comment]
Hi @20chen-7 I tested the PR and can confirm the functionality for owner/ volunteer works. However closing the modal does not does not update the modal state. It persists till reload.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/c8ddc8c4-4615-46ab-8cc2-e92dff33d270


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/96036c0d-4fbd-4569-82d6-9cf12f28e944

Also for smaller screen size the icon is not there.

Screenshot 2023-07-12 at 2 30 47 PM

**Comment by Jiangwei-shi** [comment]
I've tested and it looks good! The icon was not visible for the Volunteer role. and Admin can only see the information but not edit it. However, I do not have an owner-role account. So I could not test what it will be like as a ower user login. And I can't select my role as owner.

image
image

**Review by freecode23 — COMMENTED** [review]
Tested the above mentioned functionality with 3 different roles. All works as expected. 
Suggestion and questions:
- Should change the black background when hovered in permission page to match the grey translucent one.
- May not be scope of this PR, but is it not possible to delete role after adding it?

**Review by shiva2096 — APPROVED** [review]
Hi @20chen-7 

Change are working as expected, however there are a few inconsistencies.
1. Black background when 'i' button hovered in Permission Management page.
2. I don't understand why we need so many 'i' buttons in Permission Management page, when the all show the same information.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/856716e6-5c80-4001-a1f9-38b1e35ed606

**Comment by AriaYu927** [comment]
Hi @20chen-7 , I've tested your PR. The main functionality works as expect. However, I have some questions about this PR.

1.  In the description, it says "should be visible to all classes except volunteers", but I noticed Volunteer user can see this icon when they go to the profile page of other users of Admin/Mentor/...... I'm not sure if this is expected. Here's an video:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/c48ead19-d343-4d67-b7f3-6eeace4e876f

2. In Bugs doc, it says the icon should also appear in the following location, but I didn't see it. Is this location still a requirement or not?

截屏2023-07-17 15 56 06

3.  On user permission page, all icons show the same information. I'm wondering if it's necessary for us to do that.

截屏2023-07-17 15 53 36

Thanks for your working!

**Pull request closed without merging**
