### PR TITLE
Alan mark task done dashboard

### PR DESCRIPTION
**Pull request by LeeSingChanYau**
This PR is to solve a mistake I made when resolving a conflict with development last time I made a pull request. As guided by @Aishwaryak01, I reimplemented her code into the branch. I merged from this branch: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/685/files.
How to test:
- Make sure that all the functionalities and code changes of PR 685 are in this pull request.

### CODE REVIEW

**Review by ypan710 — COMMENTED** [review]
Hi @LeeSingChanYau, I've tested your PR by assigning four tasks to a newly created user and all the functionalities worked as expected as from PR 685.

Screen Shot 2023-04-08 at 9 02 25 AM

Screen Shot 2023-04-08 at 9 08 12 AM

Screen Shot 2023-04-08 at 9 19 01 AM

Screen Shot 2023-04-08 at 9 27 07 AM

**Review by Aishwaryak01 — COMMENTED** [review]
Required changes in TeamMemberTasks.jsx is not present.Please check

**Review by Aishwaryak01 — APPROVED** [review]
The changes look good to me now.

**Review by PrabhjotSembhi — COMMENTED** [review]
Hey, I created a new user to test this. That user is not showing in the dropdown to assign test tasks. 
image

**Review by ToobaJamal — COMMENTED** [review]
I tried running the changes but it throws the following error

#761_error

**Comment by one-community** [comment]
Still examples of this not working on the Main and Dev. Here's one from the Dev:
image

**Comment by LeeSingChanYau** [comment]
@one-community can you explain to me what is not working. I will gladly take a look.

**Comment by one-community** [comment]
Here's our conversation from Slack: 
image

**Comment by Aishwaryak01** [comment]
@LeeSingChanYau In file TeamMembersTasks.jsx I can see only the changes that I had made. Have you added anything more in it to solve the issue? Can you please check the file again here?

**Pull request merged**
