### PR TITLE
Ramya Unit Test : PopUpBar

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit test for src/components/PopUpBar/

## Main changes explained:
-  New file
      - **PopUpBar.test.jsx** : unit test cases 
-  Existing file
      - **PopUpBar**  : Added  test id to the objects for unit testing 
####  Test cases 
image

## How to test:
1. check into current branch
2. do npm test PopUpBar.test.jsx
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Review by Alforoan — COMMENTED** [review]
All unit tests pass and everything looks good and concise. Nice!

image

**Comment by AriaYu927** [comment]
Hi @ramyaram2092 , I've tested your pr and each case looks good.
Screenshot 2023-12-23 at 10 02 34

**Review by AaronPersaud — APPROVED** [review]
Hi Ramya, I've tested and it works perfectly! Nice job.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
