### PR TITLE
Shrey unit test WorkHistory

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for WorkHistory component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test WorkHistory.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-12-30 at 8 10 11 AM

### CODE REVIEW

**Comment by abdel-lall** [comment]
All tests have successfully passed. There's just a minor typo in the description. Could you update "npm test WorkHistory.test.jsx" to "npm test WorkHistory.test.js"?

Screenshot 2023-12-29 214106

**Review by abdel-lall — DISMISSED** [review]

**Comment by mianmiantea2019** [comment]
All tests have successfully passed. 

image

**Review by bienzguoa — DISMISSED** [review]
Good job! The test is so well-structured and renders correct for components. All test cases passed.
Screenshot 2023-12-29 at 10 49 26 PM

**Review by yangfan2001 — DISMISSED** [review]
Hi, I have reviewed and tested your PR, looks like all tests are passed, great Job!
image

**Review by Alforoan — COMMENTED** [review]
All tests pass. Nice!


image

**Comment by Lin1404** [comment]
All tests pass. Good Job!

image

**Review by Lin1404 — DISMISSED** [review]

**Review by n0vay — DISMISSED** [review]
LGTM
image

**Review by scoopstroop92 — CHANGES_REQUESTED** [review]
Hello @Shreyj14  Good job on the unit test cases
However can you  move the test cases to the path as suggested in the unit-testing  channel in slack for the PR to get approved/merged

**Review by ChengyanOo — DISMISSED** [review]
Hi @Shreyj14,

Great job on testing the WorkHistory component! I noticed that all tests have passed, which is excellent. However, I'm a bit puzzled about the implementation. The component appears to be completely hardcoded, and I'm trying to understand its usage context. Could anyone provide some insights or clarification on how this component is being utilized?

HighestGoodNetworkApp_PR#1759_test

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Review by beblicarl — CHANGES_REQUESTED** [review]
This change is very important 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1759#pullrequestreview-1799596187

**Comment by Shreyj14** [comment]
@beblicarl @ramyaram2092 please check the latest commit. I updated the path for this unit test.
Screenshot 2024-01-04 at 3 55 02 PM

**Comment by ramyaram2092** [comment]
Approving the PR

**Review by scoopstroop92 — APPROVED** [review]
Approving the PR

**Review by beblicarl — APPROVED** [review]

**Comment by Haoxiang310** [comment]
All test cases have successfully passed.
PR#1759

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by yuhuimin1996** [comment]
Hi, I've tested this PR and all tests passed successfully. Good job!
Snipaste_2024-01-11_19-18-19

**Pull request merged**
