### PR TITLE
Vishavdeep fix timelog page UI issues for 375px and up

### PR DESCRIPTION
**Pull request by vishavk1992**
# Description
Screenshot 2024-07-22 181121

## Related PRS (if any):
This frontend PR2488 is related to the Development backend branch.

…

## Main changes explained:
- Adjusted the margin on both the left and right sides of the Timelog component to ensure a consistent appearance across 
  screen sizes from 375px to 1144px.
- Implemented media queries for different screen sizes to ensure the Timelog component displays correctly on various 
-  devices.
- Removed the fixed right-side padding which was not required, to streamline the layout.

## How to test:
1. check into current branch
2. do `npm install` and `npm start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Timelog 
6. verify function on different screen sizes from 320px 
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Video Before changes : - 
Screenshot 2024-07-22 182122
Uneven Margin both side 

https://github.com/user-attachments/assets/cbe925c2-a221-4052-b098-a96bc3f1f4b3

## video after changes 

https://github.com/user-attachments/assets/bf6eb634-68db-406a-915d-5b85d602e661

### CODE REVIEW

**Review by Chetan0606 — DISMISSED** [review]
Reviewed as per the instructions and everything looks good. Here's a video of my observation

https://github.com/user-attachments/assets/e846621e-dacb-4ff6-8de2-f0d4f9427821

**Comment by arunsrao9** [comment]
Reviewed as per the instructions and everything looks good(even in dark mode). Here's a Screenshot of my observation
Screensho2
Screenshot1
Screenshot3
Screenshot4

**Review by Shadhrush5 — DISMISSED** [review]
Hi, I have reviewed PR #2488. I followed the instructions while executing the test as mentioned. The functionality works as stated. Thank you for the great work. I have approved the same. The below video depicts my testing.

https://github.com/user-attachments/assets/9dcab0d3-553e-4d8e-983d-64d60d95fb2f

**Review by Nahiyan-16 — APPROVED** [review]
Works well

**Review by SrikanthChowdary495 — COMMENTED** [review]
I have reviewed the Pull request. It is working as expected from above 375px. Attaching an Image for reference.
timelog

**Comment by nikethaanand** [comment]
Tested all the changes logging in as an admin, the changes worked well for light theme and dark theme. Below is a video.

https://github.com/user-attachments/assets/6b8a656e-6732-45fc-b4d8-e6f5bbdc6099

**Comment by beblicarl** [comment]
The screen looks as expected when the width is above 375px. Great work

image

**Review by beblicarl — DISMISSED** [review]

**Review by SaiLavanya1 — DISMISSED** [review]
I have tested the PR #2488, and the Timelog page UI issues for 375px and up have been successfully resolved. The margins on both the left and right sides of the Timelog component are now consistent across different screen sizes. Additionally, the changes work well in dark mode. No issues were found during the testing.
https://www.loom.com/share/c8a8c3c4a58b4403a65607d42e398271

**Review by Jingyii800 — APPROVED** [review]
I tested this PR and the page looks just as described. Both light mode and dark mode work. Great job!

https://github.com/user-attachments/assets/5b943357-96e7-4b4e-8bb6-cf22f1b6307e

**Review by vamshik2024 — APPROVED** [review]
I have verified the changes, it is working as mentioned in the description.

https://www.loom.com/share/9a8807ef0c9f420c82ccb6f048a65858

**Review by Annezhang673 — APPROVED** [review]
Works as expected. The margin are the same after the changes with narrow screen size. No bugs to be detected. 
PR2488

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
Left and Right Margins don't seem to be the same for the timelog component in the specified range. Please check video for reference.

https://github.com/user-attachments/assets/e5fe382f-f439-4ad2-aaef-ede68477378d

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/66a4fc62-2049-4b44-9189-7fcbad44be47

**Comment by vishavk1992** [comment]
> Left and Right Margins don't seem to be the same for the timelog component in the specified range. Please check video for reference.
> 
>  PR2488.mp4

Hi JATIN , you are testing for dashboard Page. I fixed this for TIME Log page. Please check again

**Comment by vishavk1992** [comment]
> Left and Right Margins don't seem to be the same for the timelog component in the specified range. Please check video for reference.
> 
>  PR2488.mp4

Hi Jatin @JatinAgrawal94  You are testing on Dashboard Page . But i clearly mentioned this is for Timelog Page . Please check again.

**Review by kabraambika — CHANGES_REQUESTED** [review]
There is no spacing on either side of the timelog component, which varies across different screen sizes, as shown in the image below:
image

**For a detailed view, please refer to the short video:**
PR2488mov-ezgif com-video-to-gif-converter

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as mentioned in the description.

https://github.com/user-attachments/assets/e81414b6-1780-4c4e-b1c8-2f24d7bbc64e

**Review by aaryaneil — CHANGES_REQUESTED** [review]
Tested the PR and the changes work as mentioned, though I noticed that the spacing on the either side is not equal.

https://github.com/user-attachments/assets/e47de7fa-be84-4b1c-84d3-8c2e94714727

**Review by ReinaT5678 — APPROVED** [review]
I followed the instructions and the UI seems to be working as expected for both light and dark mode! I attached a video of the testing below.

https://github.com/user-attachments/assets/b6f78e69-a247-4218-8c99-77c05cd1f8d0

**Review by Gauravmg6 — APPROVED** [review]
It works well as needed.


https://github.com/user-attachments/assets/997d5056-b0a3-40cb-8350-c798bb8d05d2

**Review by varunreddy03 — CHANGES_REQUESTED** [review]
I have verified this PR and noted a few inconsistencies in terms of padding and margins.
1. In Light mode when in resolution 1024x778, there is an extra margin on the left that can also be observed from the screenshot below. 
2. In light mode for tasks and timelogs container there is no padding to the left and right sides, for the screens resolution below 768x584.
3. In Light mode for the hours and summary dashboard the padding is not consistent on the left for the screens 375px and below.
-> But on observing the same 3 points for Dark mode, It seems to have only the point 1 issue but point 2,3 issues are not present for the dark mode.

PR 2488_1

PR 2488_2

PR 2488_3

**Comment by Gmon-k** [comment]
I have tested for 375px and 1144 px and it looks fine for me. Below is the screenshot.

**Comment by jayyy-s** [comment]
Hey Vishav, your changes to the timelog UI look good to me. I tested them in the following video and they mirror your results.

https://github.com/user-attachments/assets/40d12d01-0f71-4e5f-ab4c-d5eb76396037

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey @vishavk1992 
I have reviewed the PR the functionality is working as expected
 

https://github.com/user-attachments/assets/07a5c411-ac14-4f0f-98ae-89db5501143c

but the component needs some updates
image

The buttons and some UI parts are overlapping the boundary.
Thank You

**Comment by souravwalke** [comment]
Hi I have tested the PR in accordance with the instructions and the UI seems to be working as expected.

https://www.loom.com/share/fee76d87afa646c7acf8c909d982df02?sid=720bb627-6d7e-46cc-a629-6f88519e65e6

**Review by jinxyou — APPROVED** [review]
The window resize works fine in both modes. Great work!
Screenshot 2024-08-03 232447
Screenshot 2024-08-03 232510

**Comment by vishavk1992** [comment]
> Hey @vishavk1992 I have reviewed the PR the functionality is working as expected
> 
> but the component needs some updates image
> 
> The buttons and some UI parts are overlapping the boundary. Thank You

@Pranay-ai  This PR is only for fixed the issue for both side margin and space.

**Comment by vishavk1992** [comment]
> There is no spacing on either side of the timelog component, which varies across different screen sizes, as shown in the image below: image
> 
> **For a detailed view, please refer to the short video:** PR2488mov-ezgif com-video-to-gif-converter [ PR2488mov-ezgif com-video-to-gif-converter ](https://private-user-images.githubusercontent.com/90600253/352678439-de16b78d-b570-46be-b657-7007da4baa2b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzM1NTEsIm5iZiI6MTcyMjk3MzI1MSwicGF0aCI6Ii85MDYwMDI1My8zNTI2Nzg0MzktZGUxNmI3OGQtYjU3MC00NmJlLWI2NTctNzAwN2RhNGJhYTJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE5NDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZGI2ZDljNjU1NGI2YjFlMzZiZjNhYTQ1ZDdlMjA4NWU1Mjc2ZDZmNmIzNTkyNWVjYjM2YzMwYjg0OTk4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6ovWbljvMW5PKUV9R-UEhChy7RJ94FKR1R9aS86DNg) [ ](https://private-user-images.githubusercontent.com/90600253/352678439-de16b78d-b570-46be-b657-7007da4baa2b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NzM1NTEsIm5iZiI6MTcyMjk3MzI1MSwicGF0aCI6Ii85MDYwMDI1My8zNTI2Nzg0MzktZGUxNmI3OGQtYjU3MC00NmJlLWI2NTctNzAwN2RhNGJhYTJiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDE5NDA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmZGI2ZDljNjU1NGI2YjFlMzZiZjNhYTQ1ZDdlMjA4NWU1Mjc2ZDZmNmIzNTkyNWVjYjM2YzMwYjg0OTk4ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.i6ovWbljvMW5PKUV9R-UEhChy7RJ94FKR1R9aS86DNg)

@kabraambika  please review again and checkout the branch PR2488 and follow the given steps

**Review by AnkitLall — APPROVED** [review]
Hi @vishavk1992,

I have tested the feature, following the instructions in the PR, and it works as expected. Please refer the screenshots attached below.
Screen Shot 2024-08-09 at 1 03 01 AM
Screen Shot 2024-08-09 at 1 03 24 AM

**Review by adityasure9 — APPROVED** [review]
Hi Vishav, The fix works well. The spacings are displayed correctly, both on the right and the left side of the timelog.

**Review by SatyashanthiT — APPROVED** [review]
I verified that the Timelog component now displays consistently across various screen sizes, from 375px to 1144px, and functions properly in dark mode. The adjustments made to the margins and removal of unnecessary padding have improved the layout. Everything works as expected, so I am approving this PR.
https://github.com/user-attachments/assets/78402eb5-1534-4b4f-8cba-51f1e47c34de

**Review by SnelPatare — APPROVED** [review]
I have verified timelog page UI for light and dark mode and it works well. 
Images are as below
dark
lightmode

**Review by preethamdnr — APPROVED** [review]
Hello Vishav,

I have followed the steps mentioned, and it is working as expected in both the modes.
image
image
image

**Review by Lemonnycodes — APPROVED** [review]
Hi,
- I have tested the new feature thoroughly across different screen sizes, including the smallest breakpoint at 320px. 
- The feature works as expected, maintaining functionality and user experience across all tested screen sizes. 
- verified the feature in dark mode, and it functions without any inconsistencies.

**Image References :** 
PR 2488
PR 2488 (2)
PR 2488 (3)
PR 2488 (1)
PR 2488 (5)

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected. Good work.

https://github.com/user-attachments/assets/83a2de99-e957-4a47-b8b7-8f60bfbdc7dd

**Pull request merged**
