### PR TITLE
Tim: Update & fix Material List, Material Update pages

### PR DESCRIPTION
**Pull request by tdkent**
# Description
Updated Material List and Update pages to work with updated data model. Fixed data structure set by reducer to prevent build time page crashes.

## Related PRS (if any):
[Backed PR 656](https://github.com/OneCommunityGlobal/HGNRest/pull/656) must be running

## Main changes explained:
- Material pages no longer crash
- Code refactored
- Files renamed to remove confusing pluralization

## How to test:
1. `git checkout Tim_update_mat_pages`
2. `nvm i`, then `npm i`, then `npm run start:local`
3. Clear site data/cache
4. Log in as volunteer
5. Navigate to "/bmdashboard" and confirm credentials
6. Navigate to Material List page: "/bmdashboard/materials"
7. Check that the page does not crash. Check Updates and Purchases modals for accurate display of records.
   - If the page does crash, try [clearing your browser's cache and cookies](https://support.google.com/accounts/answer/32050)
9. Click the pencil icon to add an update record for an item. Check that data submits correctly and the page is updated to reflect new values.
10. Navigate to Material Updates page: "/bmdashboard/materials/update"
11. Check that the page does not crash. Test the form.
   - If the page does crash, try [clearing your browser's cache and cookies](https://support.google.com/accounts/answer/32050)

### CODE REVIEW

**Review by this-journey — CHANGES_REQUESTED** [review]
Hi @tdkent! I reviewed your PR request and was not able to find a pencil icon to make any updates.  I also found that none of the buttons are usable.  I attempted to go to the second site listed and the app immediately crashed.  I've attached a video for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/93569791/ac16043b-ac14-4ad7-b01b-924319144699

**Comment by tdkent** [comment]
@this-journey Thanks for your review! Looks like the page is still crashing. I'll work on another fix.

**Comment by tdkent** [comment]
@this-journey can you try [clearing your browser's cache and cookies](https://support.google.com/accounts/answer/32050) to see if that fixes the page crashing?

Also, please note that after logging in to the BM Dashboard you need to manually enter **/bmdashboard/materials** into your URL bar to access the Materials List page.

**Review by Alforoan — CHANGES_REQUESTED** [review]
As can be seen by the image, I seem to getting a request failed with status code 404 error.
image

**Review by Vishala09 — CHANGES_REQUESTED** [review]
Hi @tdkent ! Everything seems to be working fine for me. 
The only issue is , since `/bmdashboard/materials` is routed before `/bmdashboard/materials/update` the update page is not routable. Changing the order seems to work (in routes.jsx). 

Please find my video recording here!

[Untitled_ Dec 19,2023 11_55 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/94211656-72db-41f0-8bc7-3c5127114268)

**Pull request closed without merging**
