### PR TITLE
Roberto- BadgeHistory Unit Test

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
Creates a unit test for the BadgeHistory component.

## Main changes explained:
- Created the BadgeHistory.test.js file and added tests to check for rendering filtered badges, sorting filtered badges correctly, filtering badges based on time, and handling emptying datasets

## How to test:
1. check into current branch
2. do `npm install` and `npm test src/__tests__/Badge/BadgeHistory.test.js`

## Screenshots or videos of changes:
Screenshot 2023-11-02 at 4 23 20 PM

### CODE REVIEW

**Review by Chuehleo — APPROVED** [review]
Everything works as expe
Screenshot 2023-11-02 163107
cted, great job!

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 10 - PR5

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Good work

Screenshot 2023-11-03 at 1 58 47 AM

**Review by Bali2Mohit — APPROVED** [review]
Hi @robertoooc , I have reviewed your changes. Nicely written unit tests. Well Done!
Screenshot 2023-11-03 at 14 36 36

**Review by navneeeth — APPROVED** [review]
Hello, @robertoooc! The tests are all passing. Great implementation of the tests!

unit test cases passing

**Review by malikjahanzaib — APPROVED** [review]
Hi @robertoooc, all tests passing. Nice job!!!

Screenshot:
image

**Review by Hemsharavanan — APPROVED** [review]
All test cases have passed. Great job!

Roberto- BadgeHistory Unit Test #1481

**Comment by kavya151** [comment]
Hi @robertoooc , All testcases passed! Good Job!
Screenshot 2023-11-04 at 12 18 25 PM

**Comment by mounica-dingari-by** [comment]
Hi @robertoooc , tested your PR and it works perfectly.

image

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR and all test cases passed!
Screenshot 2023-11-05 at 12 29 03 AM

**Review by savio-henrique — APPROVED** [review]
Hi @robertoooc , I've tested your PR and the test cases passed as expected! Great work! :+1: 

# Screenshots

terminal

**Review by pika-chu11 — APPROVED** [review]
Hi @robertoooc ! I have ran the test on my end and it passed! Great job!
FE#1481

**Comment by palakgosalia** [comment]
Hey, I tested your PR and all test cases passed. Thank you

image

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-11-10 at 12 05 10 AM

**Comment by cvtqx** [comment]
Great job, all tests pass.

Screen Shot 2023-11-10 at 5 27 39 PM

**Comment by wanglu1207** [comment]
Roberto_unit_test_Badge_History
Good job! It works for me!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
