### PR TITLE
Vedant Add reset filter option to badge data filtering

### PR DESCRIPTION
**Pull request by vedantg24**
# Description
Added a reset filter button to reset all the badge data filters

Screenshot 2024-09-17 at 3 00 04 PM

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
Updated file `BadgeDevelopment.jsx` and added a reset filter button which resets all the filter fields

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ Other Links → Badge Management → Badge Development → Add Filters
6. Click on the Add Filters and fill in the fields to filter out badges. After filtering click on Reset Filters.
7. Verify that the filters field are set back to default.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/a6cd15a4-5fd2-44e0-b60d-f9169bf6adf3

### CODE REVIEW

**Review by vijay10pk — CHANGES_REQUESTED** [review]
All the functionalities works as expected. I would suggest you to change the styling of the input field and dropdown uniform, so that it will be same as everywhere.
https://www.loom.com/share/626b377cf5c14754931e526548ded8ae?sid=f61084c0-3d80-49b9-af6f-50a375c3dfc0

**Review by RishithaMamidala — APPROVED** [review]
@vedantg24 
The reset filters works correctly and resets the badges table.
PR 2687
After reset
PR 2687-2

**Review by manikittu810 — APPROVED** [review]
Hello @vedantg24 
Everything is working as mentioned. Good work.

https://github.com/user-attachments/assets/466df626-706b-4e3a-9157-d6c4b21da451



Thank you.

**Comment by tharunaa-1** [comment]
After adding the filter and reset the filter, it clears everything. works fine as expected.
image

After Reset Filter
image

**Review by chu-ziyu — APPROVED** [review]
I tested this PR and everything worked as expected in both light mode and dark mode.

https://github.com/user-attachments/assets/64a7e231-b371-4ac9-b01b-226ef4d905d9

**Comment by geetamatkar** [comment]
Hi @vedantg24 ,
Tested this PR and everything is working as expected.

PR2687
PR2687-1

**Review by jinxyou — DISMISSED** [review]
The filter and reset is working properly. Great work!
Screenshot 2024-09-20 220936
Screenshot 2024-09-20 220942

**Review by mohangadde1 — APPROVED** [review]
https://github.com/user-attachments/assets/689ab06d-f189-470f-8b5e-b0cdcd46b340
Reset functionality works fine

**Review by panchalvatneu — APPROVED** [review]
Works, great job!

https://github.com/user-attachments/assets/4caba3de-05e0-45c6-bf43-c5cac279115b

**Review by slidracoon72 — DISMISSED** [review]
#2687
@vedantg24
The reset filters functionality is working as expected, successfully resetting the badges table in both dark and light modes.

Video Demonstration:
https://www.loom.com/share/88427f184d4a440bb24645e8232d8128?sid=d975f290-3936-446f-80e8-787765397719

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/532ff26b-1d57-40bb-b0ff-85dbaf522703

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected. Below are the screenshots for reference:
Capture2687
Capture2687_1

**Review by SharadhaS24 — DISMISSED** [review]
The PR functions correctly in both light and dark modes across all filters. It accurately filters the content by rank or when a specific rank is specified.
image
image
image

**Review by AshritaCherlapally — APPROVED** [review]
This is working fine, filtered results are cleared out when clicking on the reset filter button.

**Review by SupriyaSudini — DISMISSED** [review]
The reset filter function in badge management is working as expected. It successfully cleared all the selected filters.

image

image

**Review by Rupa2400 — DISMISSED** [review]
PR #2687 Everything functions as expected. The reset filters feature performs well, effectively clearing and resetting the badges table without any issues.


https://github.com/user-attachments/assets/80a0ee90-b7b0-44a6-ae40-4dd27905effa

**Review by audreydieuanh — DISMISSED** [review]
Everything works correctly!
test5

**Review by Rui-Liu-github — APPROVED** [review]
Hi, I reviewed PR#2687 by pulling the latest version from Vedant. I tested the Filters feature and fill in the fields to filter out badges. After filtering click on Reset Filters.
I verified the filters field are set back to default. 

https://github.com/user-attachments/assets/c87d85fb-7c68-4812-ac9b-6dd4f55e93dc

**Comment by SatyashanthiT** [comment]
Tested and validated the reset filter functionality. Verified that all filter fields reset to their default state as expected when the "Reset Filters" button is clicked. 
https://github.com/user-attachments/assets/6ad9263a-bdbb-4278-946e-11185a03143f

**Review by Muhideenthegreat — APPROVED** [review]
Verification: 
- Reset filter option works as expected

https://github.com/user-attachments/assets/25b774e1-949c-4f54-9605-a53a0830cc52

**Comment by one-community** [comment]
Thank you all, merging!

**Review by NazaninHashemian — COMMENTED** [review]
I tested the PR as follows:

Checked out the current branch.
Ran npm install and started the app using npm run start:local.
Cleared site data/cache.
Logged in as an owner/admin user.
Navigated to Dashboard → Other Links → Badge Management → Badge Development → Add Filters.
Verified that the reset filter functionality works as intended, resetting all fields to their default values.
Everything was working fine except I was unable to log in using a developer account. This may require further investigation to confirm if it's related to the PR or an environment-specific issue.

**Comment by pallavithorat** [comment]
I have tested the PR by navigating to the Dashboard → Other Links → Badge Management → Badge Development and applying various filters, then clicking on “Reset Filters.”All filters were successfully reverted to their default settings, confirming that the changes function as intended.
Screenshot 2024-12-05 at 3 36 36 PM
Screenshot 2024-12-05 at 3 36 56 PM

**Pull request merged**
