### PR TITLE
Remove ability for anyone but Owners/Admins to see the green check by…

### PR DESCRIPTION
**Pull request by abdel-lall**
# Description

 (PRIORITY HIGH) Jae: Remove ability for anyone but Owners/Admins to resolve tasks
    1. Only Owners/Admins should be able to see the green check by tasks in the Tasks tab of the Dashboard and be able to click  it to resolve/make those tasks go away

image

## Mainly changes explained:
    1. Added a constant ‘isAllowedToResolveTasks’ to check if the current user role is allowed to resolve tasks.
    2. Added conditional rendering to the green check, so that the component is only displayed when the user is allowed to resolve tasks
## How to test:
    1. check into current branch
    2. do `npm run start:local` to run this PR locally
    4. log as (admin/owner) role user and select the Tasks tab
    5. check if the green ckeck is displayed.
    6. log in as a user with a role other than admin or owner, who has a task assigned to them, and check if the green check appears again.

### Befor:

befor

### After:

after

### CODE REVIEW

**Comment by papiasharmin** [comment]
The functionality is working as intended. great work.
adminnotify
volnotify

**Review by papiasharmin — APPROVED** [review]
Code looks good.

**Review by EdwinLauM — APPROVED** [review]
Hi @abdel-lall, Tested your changes and works as intended! Good job! 

Before:
PR #827 After

After:
PR #827 Before

**Review by eduhorta — APPROVED** [review]
Working fine. Good job!

Admin:
image
Volunteer:
image

**Review by yoyoweiii — APPROVED** [review]
I 've tested your changes @abdel-lall, and it looks good! Great work!

Before:
HGN APP and 1 more page - Personal - Microsoft​ Edge 5_15_2023 1_39_33 PM
After:
HGN APP - Personal - Microsoft​ Edge 5_15_2023 1_38_05 PM

**Comment by one-community** [comment]
Thank you everyone, moving this to final review!

**Comment by AnishPandita** [comment]
Hi @abdel-lall I tested your PR and its working correctly. The task resolve check marks work perfectly according to the current role I am logged in.
Screenshot 2023-05-16 at 10 01 50 PM
Screenshot 2023-05-16 at 10 01 13 PM

**Review by Cirakuze — APPROVED** [review]

**Pull request merged**
