### PR TITLE
Ramakrishna_Fix white screen when returning to Dashboard from Reports page

### PR DESCRIPTION
**Pull request by Ramaruva**
# Description
This PR is fix for below issue  
image

## Related PRS (if any):
Please use latest backend dev branch
…

## Main changes explained:
- Added useState and exception handling in timeEntry component which is causing crash issue 
- Added exception handling in NewBadges, BadgeSummaryPreview, BadgeSummaryViz components
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Reports →  people →  select any userprofile 
6. And come back to dashboard  and make sure that website is not crashing or turning white (please refer to this video for more details https://drive.google.com/file/d/1sePqSpsGlTmoLtZerr4AB510GkGN0BY4/view?usp=sharing)
7. Please go to another links and try come back to dashboard if you see any website crashing please report the steps in which website has crashed  (this is optional)

### CODE REVIEW

**Review by peter6866 — APPROVED** [review]
Changes work as expected. When I'm at the profile page for a random user, I'm able to get back to the dashboard without errors.
image
image

**Review by MinSun0814 — APPROVED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/fc385314-98f9-49d2-b7ee-b3571096372c

I tried to nevigate to other people from report page and then come back to dashboard. The crash didn't happen and everything works afterwards. Nice work.

**Review by mohabbasd — CHANGES_REQUESTED** [review]
Hello, I tested your PR and for me the people are not shown on the reports page. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/11b4e0b6-9515-43bb-bdfa-5016f9dddad5

**Comment by Ramaruva** [comment]
> Hello, I tested your PR and for me the people are not shown on the reports page. Below is a video for your reference.
> 
>  Screen.Recording.2024-05-24.at.8.21.47.PM.mov

Hi  @mohabbasd  thanks for taking time and testing this PR and in given video I didn't see any website crashes and I this changes are to fix website crashing and also the people data loading are taking time as fast loading was not part of this pr changes please let me know if that you perform sequence steps as stated in pr and getting website blank screen (please do see referred video)

**Review by linkhanthtel — APPROVED** [review]
Whenever I come back to dashboard, the App is not showing white screen anymore. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/9cf7796a-9f13-4d48-8d98-354a40309764

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
