### PR TITLE
Eduardo lint fix for leaderboard component

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
Lint fix for the Leaderboard component (`src/components/Leaderboard/*`).

## Main changes explained:
Executed the lint checker
Fixed changes manually apart from fix done by lint--fix
Removed the component from .prettierignore and .eslintignore

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. do `npx eslint src/components/LeaderBoard/*`
4. log as admin user
5. go to dashboard/leaderboard
6. verify if the app is working properly

### CODE REVIEW

**Comment by Vishala09** [comment]
I did run the commands as per your instructions. I ran into the following error. 
If you are not linting css files , Can you consider ignoring it?
image

**Review by Iris-Song — APPROVED** [review]
seem work on my computer

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/10b1d343-3d4d-4136-9d9e-6875a0b415dd

**Review by vikrambadhan — COMMENTED** [review]
Hi, I ran the command given in the instructions and am getting an error as shown in the screenshot below.
 
Week5 - Pr 3

I also checked the app and everything is working as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/187d9f4a-0572-41ec-a319-d6a8f03c61c9

**Review by DavidC0126 — COMMENTED** [review]
Hi @eduhorta I tested the PR and the page works as intended, but I encountered the same error on eslint check for Leaderboard.css, either.
eslint_check

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/ee1a2c71-f6e6-49f4-808c-fba40a77a46a

**Comment by AnishPandita** [comment]
Hey, I ran the code and got same error as others about the css file. Although the app seems to function well. Are you linting the css as well?
Screenshot 2023-09-27 at 4 28 12 PM

**Comment by luisarevalo21** [comment]
Hello @eduhorta ,

I tested your PR and works as intended. Great work!
Running the scrip the app runs as normal. 
As others have stated, the css file gives a warning on the file. Since your comment "npx eslint src/components/LeaderBoard/*" I think adding eslint to the css file would be ideal.

Also, selecting a file inside of leaderboard, shows red lines. Does npx eslint not resolve this issue?

**Comment by eduhorta** [comment]
Hey everyone!
Thank you for the great feedback! 👍 

I haven't done any lint fix for any CSS file.
So what is happening is it's expected behaviour.

I did try to add a rule to ignore the CSS files on the `eslintrc.js` file and here is the screenshot

Screenshot 2023-09-28 at 14 23 21

@EvianTan are we supposed to lint fix CSS files or should we change the `eslintrc.js` rule?

**Review by sxiong5 — APPROVED** [review]
Hey @eduhorta, the PR LGTM, and there are no errors in the console. Great job!

Screenshot 2023-09-28 at 15 07 33 (2)

**Comment by Jiyuanxia** [comment]
Hi @eduhorta , I have reviewed your pull request and tested it. The leaderboard is working well but I got one error message when I execute the command.
Screenshot 2023-09-28 184000
Screenshot 2023-09-28 184146

**Comment by beblicarl** [comment]
I got this error in the console

image

**Comment by eduhorta** [comment]
Thank you for the reply @beblicarl and @Jiyuanxia!

As I mentioned before, I haven't done lint fix for any CSS file.
So what you are seeing is it's expected behavior.

**Review by beblicarl — APPROVED** [review]

**Review by Sssky-18 — CHANGES_REQUESTED** [review]
Hi @eduhorta, I tested your PR, and the CSS file had a parsing error as shown in the picture below. But the dashboard and leaderboard worked normally. 

 
PR#1345

PR#1345_2

**Review by Sssky-18 — APPROVED** [review]

**Comment by Sssky-18** [comment]
> Hi @eduhorta, I tested your PR, and the CSS file had a parsing error as shown in the picture below. But the dashboard and leaderboard worked normally.
> 
> PR#1345 PR#1345_2

Hi @eduhorta, I didn't see your reply before my above review, but now I just change to approve. I think right now it is approved state. Thank you for your contribution!

**Review by JYXiao-2021 — APPROVED** [review]
Hi，I tested this pr and the learner board works well. I also encountered the same in command.
Screenshot 2023-09-29 at 8 11 46 PM

**Review by EdwinLauM — APPROVED** [review]
Hey @eduhorta! I have tested your PR and works as expected. Got the same error in the CSS files as everyone else but I saw in your comments that you did not adjust that. Other than that everything works great!

Screen Shot 2023-09-29 at 9 35 58 PM

Screen Shot 2023-09-29 at 9 37 15 PM

**Review by JeffLi117 — CHANGES_REQUESTED** [review]
Testing with your command of `npx eslint src/components/LeaderBoard/*` gives me this error:
image

Within this PR, the application still works: 

image

I'm unsure if this problem/error is intended, but I imagine it would be better to resolve it before approving & merging.

**Comment by one-community** [comment]
> Hey @eduhorta! I have tested your PR and works as expected. Got the same error in the CSS files as everyone else but I saw in your comments that you did not adjust that. Other than that everything works great!
> 
> Screen Shot 2023-09-29 at 9 35 58 PM Screen Shot 2023-09-29 at 9 37 15 PM

We still need to fix it though, right? Someone else may have changed it in some other PR and we don't want merging this one to introduce a new problem. Correct me if I'm wrong.

**Review by Haoj1 — COMMENTED** [review]
@eduhorta There is an error in css at my end. And other look good to me

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions! The App is working as expected!
Screenshot 2023-09-30 at 10 40 04 PM
However I do get this error after running "npx eslint src/components/LeaderBoard/*"
 
Screenshot 2023-09-30 at 10 41 31 PM

**Comment by Shreyj14** [comment]
Hi @eduhorta 
I am getting the same error as others, but as mentioned its not something you changed. It works well
Screenshot 2023-09-25 at 12 43 19 AM

**Comment by eduhorta** [comment]
Hey @JeffLi117!

> I'm unsure if this problem/error is intended, but I imagine it would be better to resolve it before approving & merging.

This behavior is expected.

Hey @one-community!

> We still need to fix it though, right? Someone else may have changed it in some other PR and we don't want merging this one to introduce a new problem. Correct me if I'm wrong.

I did send a DM to @EvianTan so we can talk about setting a rule to ignore .CSS files on lint fixes or what other alternative she has in mind.

**Comment by wantingxu7** [comment]
Hi, I tested and the UI works as intended, but the console shows error after running the command
 

1345-console

**Comment by RheaWu1212** [comment]
Works as expected, good job! 
Screen Shot 2023-10-02 at 17 03 11

**Comment by one-community** [comment]
> I did send a DM to @EvianTan so we can talk about setting a rule to ignore .CSS files on lint fixes or what other alternative she has in mind.

Thank you!

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
