### PR TITLE
yixiao_taskeditsuggestion_unittest

### PR DESCRIPTION
**Pull request by JYXiao-2021**
# Description
Create a unit test for the TaskEditSuggestions component to confirm whether it working as intended.

## Main changes explained:
- Create file TaskEditSuggestions.test.js to do the unit test.

## How to test:
1. check into current branch
2. do npm install to run this PR locally
3. run npm test TaskEditSuggestions.test.js

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-09 at 12 16 53 AM

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed as intended. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/96c52a3f-e980-41e9-a600-adff42cd800b

**Review by BaileyM96 — APPROVED** [review]
Good afternoon @JYXiao-2021 I ran your unit test and all the tests have passed. Good work!

## Screenshots

taskEditSuggestions unit test

**Review by ZichanYang324 — APPROVED** [review]
Hi @JYXiao-2021 , I have run the test and all the test cases passed, well done!
Screenshot 2023-12-09 at 16 53 41

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-09 at 2 56 25 PM
Good job @JYXiao-2021 ! All the cases passed!

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Comment by Lin1404** [comment]
I ran your unit test and all the tests have passed. Good work!
Screenshot 2023-12-15 at 7 56 30 AM

**Review by Lin1404 — APPROVED** [review]

**Review by scoopstroop92 — APPROVED** [review]
Unit tests looks good . Good job @JYXiao-2021

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
