### PR TITLE
Navneeth create see project management tab custom permission

### PR DESCRIPTION
**Pull request by navneeeth**
# Description
bug description

## Related PRs:
This PR is linked to the BE PR [#545](https://github.com/OneCommunityGlobal/HGNRest/pull/545).

## Main changes explained:
- Employing consistent naming of permissions in `src/utils/routePermissions.js`
- Deciding that when a volunteer account has both `See Project Management Tab (Full Functionality)` AND `See Project Management Tab (Add team members, upload new WBSs only)`, then the `See Project Management Tab (Full Functionality)` permission will have priority. I.e., the volunteer account will be able delete, edit, and create users. 
- Rendering the UI according to the permissions wherein an account with just the `See Project Management Tab (Add team members, upload new WBSs only)` permission will not be able to update, delete, or create new projects.

## How to test:
1. Follow the steps in the backend (BE PR [#545](https://github.com/OneCommunityGlobal/HGNRest/pull/545)) to run the relevant PR.
2. In the frontend, check into the current branch.
3. do `npm install` and `npm run start:local` to run this PR locally
4. Log in as Owner -> Other Links -> Permissions Management -> Manage User Permissions
5. Enter the username of an account that does not have the “See Project Management Tab (Full Functionality)” permission by default (i.e., a Volunteer account). 
6. Next to “See Project Management Tab (Full Functionality)” or “See Project Management Tab (Add team members, upload new WBSs only)”, click on Add. Then scroll down and click on Submit.
7. Log in as the volunteer account (if already logged in, make sure to log out and log back in). The “Other Links" button should appear with ONLY the “Projects” option visible/accessible.
8. The volunteer account can create, update, and delete projects, add WBSs, and add team members in the Project Management page (Projects) if "See Project Management Tab (Full Functionality" permission was added. If only the "See Project Management Tab (Add team members, upload new WBSs only)" permission was added, then the volunteer can do all of the above except for creating, updating, and deleting projects.

## Video on how to test (with steps):

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/687dd9dd-260b-4140-b345-25c186a84753

### CODE REVIEW

**Review by Jiyuanxia — APPROVED** [review]
Hi @navneeeth , I have reviewed your pull request and tested it. It works as you intended. Well done!

See Project Management Tab (Add team members, upload new WBSs only)
Screenshot 2023-09-28 180202

Can ONLY see the "Projects" under "other links"
Screenshot 2023-09-28 180236

Can see the project list but can not add a new one, edit names nor delete one
Screenshot 2023-09-28 180515

Add a team member
Screenshot 2023-09-28 180551

Add a new WBS
Screenshot 2023-09-28 180615

See Project Management Tab (Full Functionality)
Screenshot 2023-09-28 180710

Can see add new project button and delete button, project names are editable
Screenshot 2023-09-28 180747

Add a new project
Screenshot 2023-09-28 180832

Change new project's name to "jiyuantestproject123"
Screenshot 2023-09-28 180855

Click delete to delete and confirm
Screenshot 2023-09-28 180903

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR. It works as expected. I tried to create project, add members to project, delete members from project, delete project.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/bf77cd05-d430-4a64-8ed7-fd8b3fbb5905

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works as intended. Well done!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/9c7e2880-4301-4617-b70a-51266fa6325c

**Review by harshidad — APPROVED** [review]
I tested PR and it working fine. Great Work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/2adb552d-8d47-4bb7-a20a-dd3d0b7ec407


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/aeca436e-2937-4244-a4a9-d13287968598

**Comment by Lin1404** [comment]
Hi @navneeeth , I have tested your PR and it works intended. Good Job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/2467015f-e338-4f85-ad33-05b805b2d74b


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/67ac780b-ed15-4153-8441-c9af44e7a18d

**Review by Lin1404 — APPROVED** [review]

**Review by Haoj1 — APPROVED** [review]
@navneeeth I have tested your pr. The vo with the permission is able to create project, wbs and view the project page. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/f81c68de-827d-4974-98c7-7530b8cf3407

**Review by EdwinLauM — APPROVED** [review]
Hey @navneeeth! Tested your PR and works as expected

Full Functionality Permission:

Screen Shot 2023-09-30 at 6 09 18 PM

Creating a project:

Screen Shot 2023-09-30 at 6 10 57 PM

Editing a projects name:

Screen Shot 2023-09-30 at 6 11 26 PM

Deleting a project:

Screen Shot 2023-09-30 at 6 11 32 PM

Not Full Functionality Permission:

Screen Shot 2023-09-30 at 6 13 44 PM

Can't add projects:

Screen Shot 2023-09-30 at 6 14 52 PM

Add a team member:

Screen Shot 2023-09-30 at 6 15 34 PM

Adding a new WBS:

Screen Shot 2023-09-30 at 6 16 13 PM

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
