### PR TITLE
Ruike message after submit task

### PR DESCRIPTION
**Pull request by StrawberryCalpico**
# Description
Screenshot 2023-11-25 at 1 23 30 PM

## Related PRS (if any):
N/A

## Main changes explained:
- Update Text and color in related files to replace

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as owner/admin
4. go to Other Links—>Projects—>WBS—>Choose the WBS—> Assign the task or “Add Task” to volunteer
6. log in as volunteer user
7. submit a task for review
8. make sure the text is no longer "more work needed..."
9. instead, it shows "Work Submitted and Awaiting Review"

## Screenshots or videos of changes:
before:
Screenshot 2023-11-25 at 1 29 46 PM
after:
Screenshot 2023-11-25 at 1 44 15 PM

### CODE REVIEW

**Comment by palakgosalia** [comment]
Hey, I reviewed and tested your code. It works as intended. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/93e93b49-6b26-4a70-8649-54c060835290

**Review by Alforoan — CHANGES_REQUESTED** [review]
I'm not sure if it's intended, but if I click on the button again, it goes back to submit for review? 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/20816fbd-79dc-4f05-ae4c-0fe84b37af8f

**Review by sucheta90 — COMMENTED** [review]
@StrawberryCalpico Looks like the button works as intended (logged in as Volunteer)
, however if I happen to click the button "Work Submitted and Awaiting Review" , it changes back to "Submit". Just wanted to confirm if this is the expected behavior. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/bcb8ff99-4c6e-4a08-823e-416bc1807366

**Comment by StrawberryCalpico** [comment]
> I'm not sure if it's intended, but if I click on the button again, it goes back to submit for review?
> 
>  2023-11-29.17-08-01.mp4

Just updated, disabled the button once user submitted

**Comment by StrawberryCalpico** [comment]
> I'm not sure if it's intended, but if I click on the button again, it goes back to submit for review?
> 
>  2023-11-29.17-08-01.mp4

Just updated, disabled the button after user submitted

**Comment by this-journey** [comment]
Not sure why, but I'm not getting the option to submit a task.  This may be my own user error, but I figured I'd reach out just in case.
PR 1585 FE

**Review by ljrirene — COMMENTED** [review]
Does anyone have the same problem as me? When I logged in as a volunteer, I had no task which can be submitted. 
image

**Review by sucheta90 — COMMENTED** [review]
@StrawberryCalpico This is my 2nd attempt to review PR, as mentioned in the instruction, I logged in as Volunteer (backend server running on the most updated development branch), however the assigned task section did not load. 
PR1585_review_part2

**Review by pika-chu11 — COMMENTED** [review]
Hi @StrawberryCalpico, there is no task for me to be submitted when I logged in as a Volunteer. 
PR 1585

**Review by keyunhuangg — APPROVED** [review]
Hello,

Logged in as volunteer and clicked on the 'Submit for a review' button. The button was disabled and shown 'work submitted and awaiting for review'
Screenshot 2023-12-15 at 1 25 29 PM

**Review by sucheta90 — APPROVED** [review]
Hi @StrawberryCalpico , after testing this PR, I logged in as a Volunteer. When I clicked the "Submit for review" button, it transitioned to "Work Submitted and Awaiting review," and subsequently became disabled. It appears to be functioning as expected. Excellent job!
Screenshot 2023-12-16 at 7 50 22 PM

**Comment by mianmiantea2019** [comment]
Hi @StrawberryCalpico, 

To test these changes, I logged in as an owner, accessed the project, and assigned the task to a volunteer user. Then, I logged in as a volunteer user and successfully submitted the task for review. I verified that the displayed text now correctly shows "Work Submitted and Awaiting Review," demonstrating that the updates function as intended. Good job!

I logged in as an Owner and assigned a task.

image

image

I logged in as a Volunteer and submitted the task.

image

image

**Review by ljrirene — APPROVED** [review]
Hi Ruike, I retested this PR. And it works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/f0a3b328-c4ba-497b-8f69-1d2c0b321855

But I have one more question, when I tried to add resources to the task. I can only see three users started with "Jiarong". However, there should be seven users here. Do you know which PR can I refer to?

**Review by Aishwaryak01 — APPROVED** [review]
Code looks good to me! Not able to test this functionality currently as tasks are not loading on dev account.
Approving as code looks good and this is a very minor change.

**Review by Aishwaryak01 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
