### PR TITLE
Roberto- fix adding person to existing team

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
While creating a new user, assigning them to a team didn't register on Teams section.
Screenshot 2023-09-23 at 5 06 28 PM

Fixes # (bug list priority high/medium/low x.y.z)
Or Implements # (WBS) 

## Related PRS (if any):
…

## Main changes explained:
- Added a function in UserProfileAdd file that assigns user to teams After the user is created. In order to add a member to a team userId is needed first so function executes as soon as the modal returns a userId.
- Edited the TeamsTab file to perform the same function.
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin/owner user
4. go to `dashboard→ Other Links→ User Management→ Create New User`
5. Fill out the modal and assign the new user to a team. Now go to `Other Links→ Teams`, look up the team and verify the user you created is showing in the member list. 
6. Additionally visit that user's account → Teams Tab → Assign them to another team and verify that it works as well.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/ec59d0aa-af02-4aea-985d-d8230c3b4928

## Note:
You might see this in the console but not related:
Screenshot 2023-09-23 at 5 23 49 PM

### CODE REVIEW

**Review by navneeeth — DISMISSED** [review]
Hello, @robertoooc! I tested your PR and the changes work as intended. Logged in as an owner user and first created two Teams. Then created a new user in `Other Links-> User Management-> Create New User` and assigned them to one of the above teams. Verified that the newly added member shows up in the `Other Links-> Teams` member list for the team. Reassigned the team member to another team and the changes are reflected in the member list. Good implementation!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/d79522f6-1493-4c68-a4fb-939d26f9b6f4

**Comment by Vishala09** [comment]
Tested the changes! Working perfectly!! Great work!!!

[Untitled_ Sep 28,2023 11_44 AM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/f2aaea4b-2b92-4dc1-9a8a-3007f88f3c2b)

**Review by Vishala09 — APPROVED** [review]

**Comment by astrjc0326** [comment]
Hi, I tested the PR and it works as expected! 
Test1 :  the new user creation and team assignment

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/24557129-2386-491d-91dc-255690eb31cb

Test2: Userprofile and Teams board 
Screen Shot 2023-09-29 at 11 32 47 AM

**Comment by RheaWu1212** [comment]
Hi I tested PR, 
 - NOT in the team if: admin dashboard (team already created) --> go to the member --> select team --> add to team --> showed in the current page right away --> go to 'other links/teams' --> users I just added NOT in the team
 - YES in the team if: admin dashboard --> go to 'other links/teams' --> search for team --> search a member, add to the team --> user SHOWED in the team

Screen Shot 2023-09-30 at 18 56 10
Screen Shot 2023-09-30 at 18 51 46
Screen Shot 2023-09-30 at 18 52 08
Screen Shot 2023-09-30 at 18 53 25

**Comment by beblicarl** [comment]
this functionality works as intended and the code is great

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.10.02-16_52_14.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/7278d0e4-214d-42a9-a91a-be5409ff4ed3)

**Review by beblicarl — DISMISSED** [review]

**Review by Bhagyashree444 — DISMISSED** [review]
Works perfectly!
Screenshot (182)

Screenshot (183)

Screenshot (184)

**Comment by wantingxu7** [comment]
Hi @robertoooc, I just tested the PR, and the function works well as expected except for one thing, after creating the new user, go directly to the team and find the team member, it takes several seconds to show the recently created user. I'm not sure whether it is a common issue, you can see in the recording that it shows "undefined undefined" at first.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/22871891-6e7e-4d65-93b5-711ada6422ab

**Comment by one-community** [comment]
Fix the merge conflicts here and DM me and I'll move this to final review

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR and it works as expected. I checked if the team is added in user profile for that user and members tab under teams.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/d32f0918-30dc-4d68-bedb-b445eeb4dde6

**Review by tsunami776 — APPROVED** [review]
Hi @robertoooc, I tested with an admin account to create a new user with its team assigned. After user creation, its profile will show the corresponding team. And in the Teams tab, the assigned team also shows the newly created user. Everything works as described in the PR. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/a1f85f0e-8e65-4fe8-ac12-bbe52b2f69fe

**Review by JeffLi117 — CHANGES_REQUESTED** [review]
Creating initial user & assigning them to a team:
image

Confirming they are indeed on the team via other links > teams:
image

Confirming within the user's account > teams tab:
image

Assigning to another team: 
image

Confirming addition to new team:
image

While all the above works great, when I go to the user's account > teams tab and delete them from an assigned team, the user is still listed under that team if I search through other links > teams > searching that team & checking the members. It is only when I go to other links > teams > that team > delete member that the user is removed from the team (& confirmed also on user account page). 

### Changes requested
When deleting/un-assigning a team from the user account page, ensure that change is reflected within the other links > teams page

For clarification purposes, this is the user account page I am referencing:
image

This is the place where I hope to see changes reflected:
image

**Comment by robertoooc** [comment]
> Creating initial user & assigning them to a team: image
> 
> Confirming they are indeed on the team via other links > teams: image
> 
> Confirming within the user's account > teams tab: image
> 
> Assigning to another team: image
> 
> Confirming addition to new team: image
> 
> While all the above works great, when I go to the user's account > teams tab and delete them from an assigned team, the user is still listed under that team if I search through other links > teams > searching that team & checking the members. It is only when I go to other links > teams > that team > delete member that the user is removed from the team (& confirmed also on user account page).
> 
> ### Changes requested
> When deleting/un-assigning a team from the user account page, ensure that change is reflected within the other links > teams page
> 
> For clarification purposes, this is the user account page I am referencing: image
> 
> This is the place where I hope to see changes reflected: image

Hey @JeffLi117, when creating this pr I kept the actions separate but the requested changes you mention are actually the [1350](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1350) pr.

**Review by sxiong5 — APPROVED** [review]
Hey @robertoooc, I have tested the PR, and it works as intended. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/c83d2945-20e3-49dc-a40a-823732689375

**Review by cvtqx — APPROVED** [review]
I've tested this and the functionality works as described. See video review:

https://www.loom.com/share/3657024fde174781ac308717eb261829?sid=62cfbbf8-f6a1-49e7-b5d7-45f204a74195

**Pull request merged**
