### PR TITLE
Shiwani TeamReport unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/Reports/TeamReport/TeamReport.jsx`

## Main changes explained:
- Added 18 test cases: renders without crashing, check if team not found message is displaying as expected when there are no teams, check if the team name is getting displayed when the team is present, check if the created date and its is getting displayed when the team is present, check if team ID header and its value is getting displayed when the team is present, check if Last updated header and its value is getting displayed when the team is present, check if Number of Members and its value is getting displayed as expected, check if Total Team Blue Squares, Weekly Committed Hours, Total Worked Hours This Week gets displayed as expected, check if Breakdown of Weekly Hours So Far This Week header gets displayed as expected, check Name, Created After, Modified After header displays as expected, check All, Team, Status header displays as expected, check Team Members, ID, Created At header displays as expected, check if date picker for Created After works as expected when the correct date is given, check if date picker for Created After gives updated date when invalid date is given, check Active checkbox works as expected when the box is checked, check Inactive checkbox works as expected when the box is checked, check if loading message is getting displayed when all teams is empty, check if Name input element is working as expected

## How to test:
1. check into current branch
2. do `npm test src/components/Reports/TeamReport/__tests__/TeamReport.test.js` 
3. check if all the test cases passes without any errors or warnings

## Screenshots or videos of changes:
Screenshot 2024-06-06 at 4 24 45 PM

### CODE REVIEW

**Comment by Changhao3220K** [comment]
Hi @Shiwani99,
Nice work of the unit test, however on my end I could only see 11 tests for this unit test branch. Could you double check the unit test file?
屏幕快照 2024-06-06 下午10 32 24

**Comment by Vijeth-V** [comment]
Hello,
Nice work on unit test. All 20 tests passed without any errors.
Screenshot 2024-06-06 at 10 44 16 PM

**Review by Logeshwari-Renu — APPROVED** [review]
All the test cases have been passed!

PR2324

**Comment by Shiwani99** [comment]
> Hi @Shiwani99, Nice work of the unit test, however on my end I could only see 11 tests for this unit test branch. Could you double check the unit test file? 屏幕快照 2024-06-06 下午10 32 24

Hi,
Thank you for your review. It looks like you have executed the tests from the 1st commit I made because I added only the 11 test cases in my first commit. Can you try pulling the latest changes in the branch and try executing it again? because the latest commit has all the 20 test cases.

**Review by deepthikannan — APPROVED** [review]
image
All unit test cases passed. Nice work !

**Review by tianyangL11 — APPROVED** [review]
Nice work and all test case passed
image

**Review by cecilia-uu — APPROVED** [review]
截屏2024-06-08 下午9 56 23
All tests passed!

**Review by shradac — APPROVED** [review]
Good work! 
All tests passed!

week1-12

**Comment by iTvX** [comment]
Good job, all tests pass

2024-06-09 at 11 34 09@2x

**Comment by beblicarl** [comment]
All test passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
