### PR TITLE
huijie work distribution bar chart for TotalOrgSummary

### PR DESCRIPTION
**Pull request by metaphor987**
# Description
Implements the role distribution pie chart in the totalOrgSummary as in the [design document](https://www.figma.com/design/qkRC9ivsIE2uG2M7WOPTg0/Weekly-Volunteer-Summary-Mockup-%26-social-architecture-tracking-and-management-system):
design

## Related PRS (if any):
This frontend PR is related to the #https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1062 backend PR(https://github.com/OneCommunityGlobal/HGNRest/pull/1062)

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Total Org Summary → open the "Volunteer Roles and Team Dynamics" tab, and the bar chart is on the left
6. verify that the bar chart is shown as expected. The number of bars may not be the same as in the design doc. It depends on the users' data.

## Screenshots or videos of changes:
screenshot

Thank you!

### CODE REVIEW

**Review by nikhilgiri0226 — CHANGES_REQUESTED** [review]
image

image

I can see the chart loaded properly. One thing I want to mention is its loading icon is different then the other charts. please check image.

**Comment by tharunaa-1** [comment]
Sometimes I dont see the chart loaded properly.

image

**Review by Dk-21 — CHANGES_REQUESTED** [review]
### PR 2713
@metaphor987 
The Tab is just keep Loading. 
Not showing any charts.
PR 2713

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected. Below are the screenshots for reference:
Capture2713

**Review by ajitp4292 — CHANGES_REQUESTED** [review]
the tab just keeps loading, no results fetched.
Screenshot 2024-11-02 at 5 10 28 PM

**Comment by SatyashanthiT** [comment]
Charts are not loading as expected
image

**Review by NazaninHashemian — COMMENTED** [review]
After testing both locally and on the Netlify deploy preview, the work distribution bar chart is not loading and remains in a loading state. The issue persists across both environments.

I believe this is related to an authentication issue on my end, which may be preventing the chart from rendering. Once the backend authentication issue is resolved, I will re-test and provide further feedback.

**Review by SammanBaidya — COMMENTED** [review]
I followed the instruction on how to test but the distribution chart did not load for me. I can see it worked for some reviewers but on my end it did not. No results fetched here.
PR 5 1 #2713

**Pull request closed without merging**
