### PR TITLE
Nathan fix permission toggle category - Assign or Remove Add permission buttons for components

### PR DESCRIPTION
**Pull request by nathanah**
# Description
image

## Main changes explained:
- Re-adds parameters to functions that were removed from a lint fix
- Names parameters uniquely to pass linting

### CODE REVIEW

**Review by Pranay-ai — APPROVED** [review]
Hey @nathanah 
I have reviewed the PR, and its expected as working.

https://github.com/user-attachments/assets/59701195-d782-4cd7-85d9-93f272ffd84a
Thank You.

**Comment by Gmon-k** [comment]
I have reviewed the PR and it is working fine. Below is the screenshot for it.

**Review by manikittu810 — APPROVED** [review]
Hello @nathanah 
Reviewed the PR , working as expected. Below is the video attached.


https://github.com/user-attachments/assets/63c172ff-3b91-4b38-9c20-0dc05cd9cf61

Thanks

**Review by JatinAgrawal94 — APPROVED** [review]
Buttons work as expected. Good work.

https://github.com/user-attachments/assets/37427f64-bc87-44ee-bfdd-a06bfab2be00

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and it's working as expected. When a button of a particular category is clicked, all the options under that category are selected.


https://github.com/user-attachments/assets/afae9370-e0a8-41f8-b1a1-afa6457d5e8c

**Review by preethamdnr — APPROVED** [review]
Hello Nathan,

I have tested this PR and it is working perfect. Buttons are working as expected, if a particular category is clicked, then its all the options got selected under that category.

image
image

**Review by RishithaMamidala — APPROVED** [review]
@nathanah 
W
PR 2512
orking as expected. When a button of a particular category is clicked, all the options under that category are selected.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
