### PR TITLE
Eduardo Lint fix for Dashboard Component

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
Lint fix for the Dashboard component (`src/components/Dashboard/Dashboard.jsx`).

## Main changes explained:
Executed the link checker
Fixed changes manually apart from fix done by lint--fix
Removed the component from .prettierignore and .eslintignore

## How to test:
1. check into current branch
2. do `npx eslint src/components/Dashboard/Dashboard.jsx`
3. do `npm install` and `npm run start:local` to run this PR locally
4. log as admin user
5. go to dashboard
6. verify if the app is working properly

### CODE REVIEW

**Comment by beblicarl** [comment]
The linting works and the app works perfectly

image

[screencast-localhost_3000-2023.09.19-16_51_15.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/55a60043-a431-419f-b5e7-c1b099c2e521)

**Review by beblicarl — APPROVED** [review]

**Review by navneeeth — APPROVED** [review]
Hey @eduhorta! Tested your changes and the app works properly. Good implementation!

No lint-related errors:
Dashboard jsx file with no LINT errors

App running:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/baa2f481-af0b-47a5-b7dc-73e6d68b4eba

**Review by tsunami776 — APPROVED** [review]
Hi @eduhorta, I followed the steps in your PR and there are no lint-related issues in `src/components/Dashboard/Dashboard.jsx`. The dashboard also works normally.

CleanShot 2023-09-19 at 16 03 56
CleanShot 2023-09-19 at 16 02 15

**Review by Bhagyashree444 — APPROVED** [review]
There are no lint-related issues in src/components/Dashboard/Dashboard.jsx. and the dashboard  works fine.

PR #1314

**Review by wantingxu7 — APPROVED** [review]
Tested and LGTM. Good work!
截屏2023-09-19 下午4 01 50
截屏2023-09-19 下午4 02 07

**Review by DavidC0126 — APPROVED** [review]
No issue when testing the PR.
eslint

**Review by Sssky-18 — COMMENTED** [review]
Hi @eduhorta , I tested the code, and there is no error inside. When I run the App with my Admin account, the Dashboard looks fine. So I think this PR works as expected. 

PR_#1314
PR_#1314_2

**Review by iTvX — COMMENTED** [review]
I tested your pr, followed your instruction, I don't see any error.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/1552e9bc-e32f-48d0-a9ba-505f4ac5b955

**Review by ramyaram2092 — COMMENTED** [review]
Hello @eduhorta  firstly,  good job. 
I think you havent fixed the **_Dashboard.test.jsx file._** if that file is not relevant then it should be removed / @EvianTan  @AaronPersaud @sxiong5  please confirm this 
image

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
