### PR TITLE
Deepthi fix teams UI

### PR DESCRIPTION
**Pull request by deepthikannan**
# Description
image
…
## Related PRS (if any):
This frontend PR is related to the #2416 
…

## Main changes explained:
- Enhanced Responsive Table Design: Updated media queries to improve table layout, padding, and font sizes at various breakpoints, ensuring better readability and functionality across devices.
- Improved Overflow and Button Management: Adjusted .table-container overflow to prevent horizontal scrolling, and introduced a .btn-group for consistent button alignment and spacing, enhancing the responsive layout.
- Unified Card and Table Styling: Defined specific column widths and standardized card styles for a cohesive visual structure, simplifying the maintenance and scalability of the CSS.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ other links→ teams
6. verify the changes to ensure responsive layouts, improved overflow handling, and unified styling are applied correctly across screen sizes

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/6391f42d-839d-4715-876e-9615f2eb4948

### CODE REVIEW

**Review by Nahiyan-16 — APPROVED** [review]
Hi Deepthi, just reviewed your PR and I see no issues. The team's page is fluid and responsive and the table works perfectly fine. The code is clean and well-commented. Great work with this PR.


https://github.com/user-attachments/assets/731ae67a-e3e8-476e-a789-c42ff97577eb

**Review by hqzhu0913 — DISMISSED** [review]
The table UI is responsive. I test all the width and the font changes accordingly. No overflowing problem.
Screenshot 2024-11-02 at 9 44 50 AM
Screenshot 2024-11-02 at 9 44 31 AM
Screenshot 2024-11-02 at 9 43 18 AM
Screenshot 2024-11-02 at 9 42 40 AM

**Review by anji-annavarapu — APPROVED** [review]
https://github.com/user-attachments/assets/5eda86e8-5377-4c06-8e3a-17a7e86552a6

i tested thoroughly in all cases, it is very responsive and align correctly.

**Review by samarth9201 — APPROVED** [review]
The teams table is responsive. LGTM!

Screenshot 2024-11-02 162243
Screenshot 2024-11-02 162250
Screenshot 2024-11-02 162257

**Comment by RashmiKY98** [comment]
Verified that there is no overflow of table content. The web page is responsive. No issues found. Good work!
Screenshot 2024-11-02 221916
Screenshot 2024-11-02 221751

**Review by abdel-lall — DISMISSED** [review]
LGTM. nice job!
Screenshot 2024-11-03 004555

**Review by anirudhsk2107 — COMMENTED** [review]
The changes work properly 
Screen Shot 2024-11-05 at 5 47 58 PM
Screen Shot 2024-11-05 at 5 47 51 PM
Screen Shot 2024-11-05 at 5 47 41 PM
Screen Shot 2024-11-05 at 5 47 33 PM

**Review by vijay10pk — DISMISSED** [review]
Changes are working as expected in different screen size.
Screenshot 2024-11-05 at 6 43 32 PM
Screenshot 2024-11-05 at 6 42 42 PM
Screenshot 2024-11-05 at 6 42 29 PM
Screenshot 2024-11-05 at 6 41 50 PM

**Review by Muhideenthegreat — APPROVED** [review]
Verification:

Teams pages is completeley responsive and all of the padding issues have been resolved as well!

Screenshot 2024-11-06 at 11 23 34 PM
Screenshot 2024-11-06 at 11 23 52 PM
Screenshot 2024-11-06 at 11 24 23 PM
Screenshot 2024-11-06 at 11 25 03 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/0dcd12e9-9138-4b91-90e3-e5002eaf0063

**Review by nikhilgiri0226 — APPROVED** [review]
Hi Deepthi, I have reviewed this PR and the teams table's responsiveness is as per the requirements. It's responsive and consistent for each type of screen in both light and dark mode.


https://github.com/user-attachments/assets/e50e095c-702e-48b8-8a56-90fe16073234

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[135a8864-a52d-4217-9d32-6d523c72f551.webm](https://github.com/user-attachments/assets/3acf0704-615a-484a-abef-f366d90a29eb)

**Review by beblicarl — APPROVED** [review]

**Review by Rui-Liu-github — DISMISSED** [review]
HI， I reviewed PR #2838, the team's page is fluently and the table works perfectly. The code is clean and well-commented. Great work.

image
image
image
image

**Comment by RashmiKY98** [comment]
Reviewed the changes. No issues found. The page is responsive and no overflow issue found. Tested in dark mode as well.
Screenshot 2024-11-09 234810
Screenshot 2024-11-09 234745

**Pull request closed without merging**
