### PR TITLE
Ashish_add_status_column_header

### PR DESCRIPTION
**Pull request by AshishNags**
# Description
image

## Related PRS (if any):
This frontend PR is related to the development backend PR.

…

## Main changes explained:
- added column header for a table in TeamMemberTasks.jsx
- 
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard→ Tasks tab
6. verify first column in Tasks Table has 'User Status' header

## Screenshots or videos of changes:
image

### CODE REVIEW

**Comment by SatyashanthiT** [comment]
Verified that the 'User Status' column header is correctly added to the Tasks Table on the dashboard and displays as expected for all users. Everything is functioning as intended.

image

**Review by anirudhsk2107 — APPROVED** [review]
The changes are working as expected. 

Screen Shot 2024-11-21 at 1 36 37 AM

**Review by vijay10pk — APPROVED** [review]
Changes are working as expected.
Screenshot 2024-11-21 at 11 20 18 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (250)

**Comment by ShraddhaShahari** [comment]
Verified 'User Status' column header is added correctly to the Tasks tab on the dashboard page and it is displayed 
as expected for all users. Everything is functioning as intended. It is working for both dark and light mode.
PR-review-2882-Screenshot

PR-review-2882-Screenshot2

**Review by ShraddhaShahari — DISMISSED** [review]
Verified 'User Status' column header is added correctly to the Tasks tab on the dashboard page and it is displayed
as expected for all users. It is working for both dark and light mode.
PR-review-2882-Screenshot
PR-review-2882-Screenshot2

**Review by RashmiKY98 — APPROVED** [review]
Reviewed the code changes. Tested the feature to ensure User Status is visible. Tested in dark and light mode. No issues found.
Screenshot 2024-11-24 003322

image

**Review by SS-Reddys — DISMISSED** [review]
Changes are working as expected i can see the column with user status header.


image

**Review by SammanBaidya — APPROVED** [review]
Reviewed the code and verified that the changes are working properly. Verified "User Status" column header is added and working on both light and dark mode. No issues faced during review. 
R1
R2

**Review by Lakshan-K — APPROVED** [review]
The new functionality is working as expected. In the Go to the dashboard → Tasks tab, the task table now has a User Status header. Great job!

https://github.com/user-attachments/assets/275ebf11-534a-43bf-b828-d5219ca52c0c

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
