### PR TITLE
Shereen - Unit tests for Time Entry Edit History component

### PR DESCRIPTION
**Pull request by pshereen**
Created TimeEntryEditHistory.test.js for unit testing TimeEntryEditHistory component.

# Description
Unit tests for Time Entry Edit History component

## How to test:
1. Check into current branch
2. Do npm install and npm test TimeEntryEditHistory.test.js to run this PR locally.
3. Check all 4 tests are passed

## Screenshots or videos of changes:

image

### CODE REVIEW

**Review by Abi-Liu — APPROVED** [review]
Looks good! All tests passing.
Screenshot 2024-03-14 at 8 43 12 PM

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.

Screenshot 2024-03-15 at 11 14 48 AM

**Comment by iTvX** [comment]
Everything looks good, thank you!
2024-03-15 at 11 55 55@2x

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
