### PR TITLE
Olga create unit tests for add project

### PR DESCRIPTION
**Pull request by cvtqx**
# Description
Unit tests for AddProject.jsx component

## How to test:
1. check into current branch
2. do `npm test AddProject.test.jsx`
3. verify that the tests pass

### CODE REVIEW

**Comment by AnishPandita** [comment]
Hey I tested the PR and the test ran without any errors. Approving.
Screenshot 2023-09-28 at 1 18 42 PM

**Review by AnishPandita — APPROVED** [review]

**Comment by olenadanykh** [comment]
Hi @cvtqx Olga!
No errors on my end. Works as expected!
Great job!

**Comment by emunkh404** [comment]
Screenshot 2023-09-27 232628

**Review by DavidC0126 — APPROVED** [review]
Hi @cvtqx I tested the PR and it works as expected.
Screenshot 2023-09-28 at 3 36 43 PM

**Comment by emunkh404** [comment]
PASS src/components/Projects/AddProject/AddProject.test.jsx AddProject component structure
it renders correctly (33 ms)
✓ input field should initially be empty (61 ms) select element should initially have a value of unspecified (34 ms)
✓ button should not be in the document when the input field is empty (9 ms) ✓ user should be able to type in the input field (77 ms)
✓ user should be able to select a category (106 ms)
button should appear when user types in the input field (55 ms)
AddProject component state handlers Input change handler updates state correctly (18 ms)
✓ Select change handler updates state correctly (20 ms) ✓ Button click handler calls addNewProject with correct arguments (33 ms)
Test Suites: 1 passed, 1 total
Tests:
10 passed, 10 total
Snapshots: ◊ total
Time:
4.179 s

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this and it works ast intended.
pr1348

**Review by Jiyuanxia — APPROVED** [review]
Hi @cvtqx , Ihave reviewed your pull request and tested it. It works as you intended. Well done!
Screenshot 2023-09-28 221354

**Review by luisarevalo21 — APPROVED** [review]
Hello @cvtqx 

I tested your PR and works as intended. Great work!

I also reviewed your code and looks great! 
Screenshot 2023-09-28 at 7 20 41 PM

**Comment by astrjc0326** [comment]
Hi, I reviewed your PR code and ran the test. It works as expected! 
Screen Shot 2023-09-28 at 8 03 02 PM

**Review by tsunami776 — APPROVED** [review]
Hi @cvtqx I ran the unit test in your PR and it works as described. Nice work!

**Review by vikrambadhan — APPROVED** [review]
Hi, All the test cases executed perfectly! Great Job!

Week5 - PR9 (#1348)

**Comment by AnishPandita** [comment]
Hey, tested the PR and commented on the git repo. The unit tests for add project works great without any errors.
Screenshot 2023-09-28 at 10 43 44 PM

**Review by Bhagyashree444 — APPROVED** [review]
All Test Cases Passed as expected. Good Work.

Screenshot (129)

**Review by yangfan2001 — APPROVED** [review]
Hi, I have reviewed and test your pr, and all tests were passed.
image

**Review by BaileyM96 — APPROVED** [review]
@cvtqx I ran your test and all the tests passed great job!

## Screenshots

screenshot of unit test for add project #1348

**Comment by BaileyM96** [comment]
@one-community This one is good to be merged

**Comment by one-community** [comment]
Thank you all, merged!

**Comment by one-community** [comment]
Thank you, merging!

**Pull request merged**
