### PR TITLE
Nandini Fix checkbox and label alignment in  PieChart section

### PR DESCRIPTION
**Pull request by nyelmela**
# Description
The checkboxes and their labels in the pie charts section of a project report are misaligned, causing them to appear visually unorganized.
image

 
## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
Update `PieChartByProject.jsx`: Modified the JSX to ensure both checkbox sections use the `.pie-chart-description` class for consistent styling.
Update `PieChartByProject.css`: Added CSS rules to align checkboxes and their labels properly and to ensure consistent spacing and alignment.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Go to Dashboard → Reports → Select a project → Scroll to the Pie Charts section.
6. Verify that the checkboxes and their labels are aligned correctly. Check both:
- All-Time Total Hours by Member (Show PieChart)
- Weekly Committed Hours By Member (Show Piechart)
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by Chetan0606 — COMMENTED** [review]
Working perfectly fine in the light mode but need minor fix in the dark mode, as per my observation I am getting  white background for the All-Time Total Hours by Member section.
Screenshot (339)
Screenshot (338)

**Review by Pranay-ai — DISMISSED** [review]
Hey @nyelmela ,
Working As Expected
image
Thank You.

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected but needs a fix in the dark mode, as per my observation I am getting white background for the All-Time Total Hours by Member section.
Screenshot (150)
Screenshot (151)

**Comment by nikethaanand** [comment]
The changes work as expected in light mode, but in dark mode the first checkbox does not appear in dark mode.

https://github.com/user-attachments/assets/979f18d7-f00b-4ee5-81b2-5374ec40b2b1

**Review by jinxyou — APPROVED** [review]
The label aligns well. But in dark mode it needs a little fix. 
Screenshot 2024-07-27 120521
Screenshot 2024-07-27 120530

**Review by Gauravmg6 — APPROVED** [review]
Alignment is working as described and expected but a slight CSS issue on the background color for the dark mode. Please look into it.

Screenshot 2024-07-28 003940

Screenshot 2024-07-28 003959

**Review by manikittu810 — CHANGES_REQUESTED** [review]
Hello @nyelmela ,
Everything is good as mentioned. But the first checkbox's description is not visible when on dark mode when compared with light mode.

https://github.com/user-attachments/assets/69217b66-8ada-44f0-97c6-4fcbae97056d


Thanks.

**Comment by Gmon-k** [comment]
In the dark mode, text in the white banner should be changed to different font color, it is hard to read it, below is the screenshot of it

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
Tested this PR and the checkboxes are in line with the text. However, there is an issue when switching to dark mode. The text isn't visible for the first checkbox. Below are the screenshots.
Screenshot 2024-08-03 152403
Screenshot 2024-08-03 152414

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes look good in light mode but do not work as expected in dark mode.
Screenshot 2024-08-10 at 6 25 15 PM
Screenshot 2024-08-10 at 6 25 23 PM

**Review by preethamdnr — DISMISSED** [review]
Hello Nandini,
There is no issues with the alignment it is perfect in both the modes. but there is a background color issue in the dark mode, rest everything is fine.
image
image

**Comment by nyelmela** [comment]
@Chetan0606 
@Vigneshwar-Muriki 
@nikethaanand 
@jinxyou 
@aaryaneil 
@Gmon-k 
@ishan-miglani 
@Pranay-ai 
Can you please re-review this PR. Changes have been made in the dark mode accordingly.

**Review by ishan-miglani — CHANGES_REQUESTED** [review]
Hi @nyelmela, I have tested the change. The text is now visible in both light and dark mode. But in the dark mode I think the text should be white in color similar to the rest of the page. Please address that. Thanks!


https://github.com/user-attachments/assets/18c7de39-0413-4434-98e7-12385290a252

**Review by manikittu810 — DISMISSED** [review]
Hello @nyelmela 
Everything is working as mentioned.
Screenshot 2024-08-29 at 11 28 45 PM


Thank you.

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.

PR 2505
PR 2505-1

Thank You

**Review by Saniya98 — APPROVED** [review]
Changes are working as expected in dark and light mode
image
image

**Review by ishan-miglani — APPROVED** [review]

**Review by slidracoon72 — CHANGES_REQUESTED** [review]
#2505
@nyelmela
The alignment looks fine, but the "Pie Charts" heading is not visible in light mode, though it appears correctly in dark mode.

PR 2505 1
PR 2505 2

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
