### PR TITLE
Howie Add Dropdowns for Owner Perms Table and removing bloat

### PR DESCRIPTION
**Pull request by HowieMiao**
Howie Add Dropdowns for Owner Perms Table and removing bloat

# Description
Need expand/collapse arrow in Permissions Added and Permissions Removed columns
Need to figure out why what’s seen below is showing up in the Main
[VIDEO](https://www.loom.com/share/1688cb3f99514fe8bb80f9a8124bc1b1?sid=a06d80a9-05dd-4ba3-ad46-091e38e0df44)
image

## Main changes explained:
Added drop-down menu functionality already in Permissions column to Permission Added/Removed columns as well
Added front end filter to skip and not add any Permissions added that are empty to the table to remove the bloat mentioned

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as **OWNER** user
5. go to dashboard→ Other Links→ Permissions Managment→ 
6. verify function Dropdown menu button on all 3 permissions columns (image)
7. There are no empty columns with commas 
image
8. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/8ba9a76e-1a61-40b4-b33b-190f33df00a2

### CODE REVIEW

**Review by vishnupriyaatheti — COMMENTED** [review]
@HowieMiao I have reviewed your changes, dropdown functionality is working as expected,
In the attached loom video under the description there should be change done under the Role Name column also mentioning that it should display username not the Role Name . Can you confirm on this that it should cover under this PR or not.
FE PR 2656

**Comment by HowieMiao** [comment]
> @HowieMiao I have reviewed your changes, dropdown functionality is working as expected, In the attached loom video under the description there should be change done under the Role Name column also mentioning that it should display username not the Role Name . Can you confirm on this that it should cover under this PR or not. FE PR 2656

The owner role management table currently covers history for role permission changes(Owner, Admin, Volunteer etc), not individual user permission, so it should not be in this PR.

**Comment by SFA23SCM35V** [comment]
App is not running locally needs to be reviewed again 
PR!

**Comment by HowieMiao** [comment]
> App is not running locally needs to be reviewed again PR!

Do you have the back-end development server running as well?

**Review by manikittu810 — APPROVED** [review]
Hello @HowieMiao 
Everything is working as mentioned.

Screenshot 2024-09-11 at 11 19 21 PM

Thank you.

**Review by SnelPatare — APPROVED** [review]
The changes are working as expected. Please find screenshots below. 
image

image

**Review by swaroop-2007 — APPROVED** [review]
Hey @HowieMiao, 
I reviewed your PR. The dropdown works well on all the columns. 
Screenshot (389)

Just a suggestion—I'm not sure if it's within the scope of this PR, but we could consider removing the Add/Delete buttons on the titles since they don't perform any action. Please see the attached screenshot for reference.
Screenshot (390)

**Review by ashayk9 — APPROVED** [review]
I have reviewed your changes, dropdown functionality is working as expected,
Screenshot 2024-09-12 at 12 16 38 PM
Screenshot 2024-09-12 at 12 17 21 PM

**Review by ddshah878 — APPROVED** [review]
The changes are working as expected. Good job!

image

**Comment by geetamatkar** [comment]
Hi @HowieMiao ,
I reviewed this PR and it is working as expected. The dropdown functionality is working fine and it is working in dark mode also.

PR2656

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.
Screenshot (194)

**Review by SFA23SCM35V — APPROVED** [review]
Reviewed again, working good approving 
prr

**Review by Parth-tech — DISMISSED** [review]
Hey Howie,
The PR looks great and the permission table has a perfectly working dropdown. There are no huge chunks of `,` occupying cells. Great job.

`Image References:`
Screenshot 2024-09-12 at 6 41 02 PM
Screenshot 2024-09-12 at 6 41 13 PM

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and it works as expected 

Screenshot 2024-09-13 143839
Screenshot 2024-09-13 143902

**Review by Shreyav2000 — DISMISSED** [review]
Tested and everything looks good!

The dropdowns in Permissions Added and Permissions Removed work smoothly, matching the existing Permissions column.
The front-end filter effectively removes empty entries, reducing bloat in the table.
All functionality is as expected. Nice work!
Screenshot 2024-09-13 at 8 30 03 PM

**Review by mohangadde1 — APPROVED** [review]
image
changes working as expected.

**Review by nishitag5 — DISMISSED** [review]
The changes are working as expected. There are no empty columns with commas and the function Dropdown menu button on all 3 permissions columns works as expected.
image

https://github.com/user-attachments/assets/636fddcc-b814-450a-ab04-f5a95d8b1f2d

**Comment by saurabhshetty29** [comment]
Everything looks good!
Screenshot 2024-09-15 at 1 53 18 PM

**Review by preethamdnr — APPROVED** [review]
Hello Howie,

I have reviews this PR and working perfectly in both the views


https://github.com/user-attachments/assets/66ad6385-f8a7-4cd8-a411-586c3f7fdcfe

**Review by strallia — APPROVED** [review]
I verified that the changes for the static column widths are working and double checked that all the other functionality are working as well. Great job!

https://github.com/user-attachments/assets/e0538dfb-8fb1-4810-a259-20d89c9c3d3f

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
