### PR TITLE
Induja - Update DropBox Link and text on Weekly Summaries Reports page

### PR DESCRIPTION
**Pull request by Indujaks**
# Description
Update DropBox Link and text on Weekly Summaries Reports page 
Any user Login → Reports → Weekly Summaries Reports 
Despite a warning telling people not to, many keep editing their DropBox link when submitting their summaries. The links they change to don’t work in many cases because they don’t know how to create a proper DB share link. I want to remove the ability for people to edit this link here.
Change everything about the link to a clickable “Your DropBox Media Files Link (Share your files here)” that will be the link they are set up with during New User Setup and that is only editable from their Profile Page
Remove the “(required)” from the other point… all of these are required and having that there implies otherwise
Screenshot 2023-08-11 at 2 50 49 PM

Fixes (Priority High)

## Main changes explained:
1. Users can input a Dropbox link only if the link field is empty.
2. The Dropbox link can be added only once on the summary page. It is saved upon adding. Users can add or modify the link through the profile page.
3. If a Dropbox link is added, the media label becomes clickable, and clicking it redirects to the linked media folder.
4. Once a Dropbox media link is added and saved, it cannot be modified from the Weekly Summary Update page. Modifications can only be made from the profile page.

## How to test:

1. check into current branch
2. do npm run start:local to run this PR locally
3. log as any user
4. On the dashboard → Open Weekly Summary
5. Verify and Test Media Link:
      a. If a media link is added during profile setup, ensure it's visible on the dashboard.
      b. Clicking the media link should redirect to the associated media (Dropbox) folder.
6.  Set Up Media Link (if absent):
      a. If no media link is set up, input the media link in the box
      b. The modified link will be saved and used for subsequent submissions.
8. Once the summary is updated and successfully saved, go to Reports-> Weekly Summaries Report
9. Verify if summary is updated accordingly.

## Screenshots or videos of changes:
Case 1:  If Dropbox media link is set up earlier:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/ff78b093-2dac-4635-b4e7-21df2451c62b

Case 2:  If Dropbox media link is not set up initially:

If dropbox media link is not setup, user can add the link and verify if its saved for the next update.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/68885bab-ec73-452b-b572-03004f94198e

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hi @Indujaks , I've tested the PR and it works as intended. 
I used a new account without dropbox link. After adding dropbox link at the first time, I cannot edit it at the weekly summary report session. Besides, I can open my dropbox through the summary report submitted. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/925b710f-8b2a-4fcc-8b61-15e51da48b47

**Review by robertoooc — APPROVED** [review]
Hi @Indujaks, I tested your branch with both cases being the pre-saved link and the non-saved link and it worked as expected for both cases.

Not saved link:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/e7bedf06-e093-435b-afcf-095bf5486859


Saved Link:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/30ea3a23-ed13-492f-b04f-d978fd786ba3

**Review by DavidC0126 — CHANGES_REQUESTED** [review]
Hi @Indujaks I tested your PR and here is what I have observed.

1. When I logging as a volunteer role. All functions work well (for both the absent link and default existing link situations).

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/bea2d3de-337c-4794-bb2a-70c4149dc23a

2. However, if I log in as Admin or Owner, originally if there is no Dropbox link, the weekly summary report page would not show the empty box for me to add the link when I try to edit it at the  first time. Instead, it will show me a clickable url link test and I will be directed to a blank page.

first_time_edit
blank


I still can go to -> Profile and add the link, and everything works for me as intended except for this one as Admin and Owner. I don't know if I misunderstood something during the testing.

**Review by ramyaram2092 — APPROVED** [review]
Hello @Indujaks  . The functionality works as expected. Good Job 
Before Adding link

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/1528c62c-2b20-4a81-a306-0cfc96ae9cf1


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/40432d27-bd51-4620-a1ab-a119aba6728c



After Adding link

**Comment by Indujaks** [comment]
> Hi @Indujaks I tested your PR and here is what I have observed.
> 
> 1. When I logging as a volunteer role. All functions work well (for both the absent link and default existing link situations).
> 
>  volunteer_weeklyReportLink.mov 
> 2. However, if I log in as Admin or Owner, originally if there is no Dropbox link, the weekly summary report page would not show the empty box for me to add the link when I try to edit it at the  first time. Instead, it will show me a clickable url link test and I will be directed to a blank page.
> 
> first_time_edit blank
> I still can go to -> Profile and add the link, and everything works for me as intended except for this one as Admin and Owner. I don't know if I misunderstood something during the testing.

I tested the changes for admin/owner, if the link is not present initially, it shows an empty blank.
 **can you please confirm the proper working link is added during the setup, i think that might be causing the issue.**
Screenshot 2023-08-11 at 4 43 22 PM

**Comment by n0vay** [comment]
Tested with present link and with link addition. Works as expected, Good Job!
image

**Review by n0vay — APPROVED** [review]

**Review by luisarevalo21 — APPROVED** [review]
Hello @Indujaks 
I tested your PR and works as intended. Great work!

Link already in place. 
Admin account already has a link. Clicking the link redirects the user to the link. In my case it was set to google.com.
I can also click the link on the weekly summary reports 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/8714327a-fa22-4767-b252-62c96c1c5945

Created a new volunteer account and logged in. The usr didn't have a DB link so i added one. Again I used google.com as an example. Once created. I can go into weekly summaries and select the link once again which redirects to google.com

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/30085889-f65d-4580-8e05-1354299276ac

**Comment by AuroraLovesWhales** [comment]
Hi @Indujaks. I have tested your PR and both cases work as expected. Great job!!

Case 1: If Dropbox media link is set up earlier:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/5871a422-163f-4bef-97c8-a38164f44719

Case 2: If Dropbox media link is not set up initially:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/b9f8d041-52ec-4da0-9849-9260d215ddf9

**Review by yunshan111 — APPROVED** [review]
I tested your PR, LGTM!

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions! 

For the volunteer account, the functionality is working as expected. It's telling me to input a dropbox link if it was not provided. Then after I provide a link, it will be displayed there and redirect to the link correctly. However, the problem is that there is no way for me to update the dropbox link in profile page or elsewhere. Here is my recording of volunteer account.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/1418c099-d61f-4511-9fea-4e23b258f484

For the Admin account, I can update the link in the profile page. And the link will be displayed after I provide the link. However, if I delete the link in the profile page and save changes. Somehow the summary page is always remembering the dropbox link and I could not delete the link. I can only update the dropbox link using other url. It does not update as expected after I delete the link.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/e040ecb2-cce0-4cb4-a5e0-97293073ae2e

**Comment by DavidC0126** [comment]
> > Hi @Indujaks I tested your PR and here is what I have observed.
> > 
> > 1. When I logging as a volunteer role. All functions work well (for both the absent link and default existing link situations).
> > 
> > volunteer_weeklyReportLink.mov
> > 2. However, if I log in as Admin or Owner, originally if there is no Dropbox link, the weekly summary report page would not show the empty box for me to add the link when I try to edit it at the  first time. Instead, it will show me a clickable url link test and I will be directed to a blank page.
> > first_time_edit blank
> > I still can go to -> Profile and add the link, and everything works for me as intended except for this one as Admin and Owner. I don't know if I misunderstood something during the testing.
> 
> I tested the changes for admin/owner, if the link is not present initially, it shows an empty input. **can you please confirm if proper working link is added during the setup, i think that might be causing the issue.** Screenshot 2023-08-11 at 4 43 22 PM

Hi I tested it again and it works well. I think I have already added a link before and that's what caused
empty_box
 the problem.

**Review by DavidC0126 — APPROVED** [review]
LGTM now!

**Review by TheDescendant39 — APPROVED** [review]
Hi @Indujaks, I reviewed and tested your PR. Everything lookds good.

Case 1: When the link is already present.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/c41606cd-dee2-4585-a4d3-10c0c2de0e77

Case 2: When the link isn't added already.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/bbd54eab-91f1-4478-b269-8c3560cba2fb

**Review by jerryren527 — APPROVED** [review]
Hi @Indujaks ,
I tested your changes and everything works as you intended! Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/b45b8fb2-5ed5-408b-a9d1-d3c3aef81749


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/57833ff9-bfe6-4bb9-afdd-85aaa2e7b776

**Review by yaow62023 — APPROVED** [review]
I have tested your PR. If the account already set up the link, I can access the link by click it, also the link is showing at weekly summary report. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/ac1dde6e-e9e1-4503-b3e8-ab4d696e209b

**Review by EdwinLauM — APPROVED** [review]
Hey @Indujaks! I have tested your PR and it works as expected! Good job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/e93a9489-61e5-4497-b83a-296a2832084f

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/9b806bfa-50b4-468c-bb70-ccb5e1bc54e6

**Review by ThapeloMasasa — APPROVED** [review]
I tested the PR and it works as expected
googelscren

Screenshot 2023-08-12 at 4 31 03 PM

**Review by Abiddy — APPROVED** [review]
Works nice on my end. Pretty useful feature.

Adding the link:

[Screencast from 08-12-2023 06:03:30 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77697776/4062f7d8-545c-4839-8427-7999166f308c)

Using the same link later: 

[Screencast from 08-12-2023 06:05:53 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77697776/c46f8a9b-446a-4c26-b44c-c9314d39b6c2)

**Review by navneeeth — APPROVED** [review]
LGTM!

Tested both cases and the PR works as expected. Good implementation!

**Case 1: DropBox media link being set up earlier:**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/8ca413cc-104f-4b9b-aa7a-73316f9967b2



**Case 2: If DropBox media link is not set up initially:**



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/be578078-43ae-4270-b055-23fd5311ad02

**Comment by Jiyuanxia** [comment]
Hello @Indujaks, I've completed the review of your pull request and conducted testing using both owner and volunteer roles. Everything appears to be functioning as anticipated. The link is successfully incorporated upon initial summary creation, and subsequent modifications are restricted. The clickable link functions effectively, redirecting me to the linked page without any issues. Furthermore, the link operates seamlessly on the weekly summaries report page as well. Excellent work!

Creating weekly summary with blank box
Screenshot 2023-08-14 161609

Weekly summaries page with clickable link whick can redirect me to the dropbox page
Screenshot 2023-08-14 161929

Trying to modify the weekly summary with clickable link
Screenshot 2023-08-14 162215

**Review by eduhorta — APPROVED** [review]
Working as expected. Great job! 👍

image

**Comment by one-community** [comment]
Excellent, thank you everyone. Merging!

**Pull request merged**
