### PR TITLE
Mohan - Hotfix team code autocomplete in mobile view

### PR DESCRIPTION
**Pull request by mohangadde1**
# Description
in mobile view the team codes do not show up if we click on this section. We get a white box with no codes visible. On coming back to normal view, the entire teams section disappears

## Main changes explained:
made changes to the following components UserTeamsTable.jsx and AutoCompleteTeamCode.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links→ User Management→ Create New User
6. verify function of Team Code auto complete with different view port sizes

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/7bfacfe2-7abe-4335-9b73-acdd4a8d3acd

### CODE REVIEW

**Review by samarth9201 — APPROVED** [review]
Works as expected. LGTM

Screenshot 2024-11-02 161920
Screenshot 2024-11-02 161938
Screenshot 2024-11-02 161954
Screenshot 2024-11-02 162001

**Review by RashmiKY98 — COMMENTED** [review]
The functionality works as expected. Tested with Firefox and Microsoft Edge. Tested by varying the width and height of the web page. No issues found. 
Screenshot 2024-11-02 214155

**Comment by RashmiKY98** [comment]
Tested in dark mode and works fine. Observed the changes by changing the web page width and height. No issues found. 
image
Screenshot 2024-11-02 223153

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
