### PR TITLE
Jingyi leaderboard time off indicator

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
image
image

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- Implement calculation logic in Leaderboard.jsx file

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. login as **different users in one team** then schedule the timeoff currently and in the future.
5. Log in as owner/admin/manager user, navigate to the dashboard, and then to the leaderboard section to view the time off indicators.
6. Verify that names are grayed out for users who are currently on time off for the current week.
Screenshot 2024-08-23 230207
7. Confirm that users with **more than the current week off** display a **"+number"** indicating additional weeks off.
8. Confirm if the user has scheduled a **future week off** then a number **without +** would be added next to name in leaderboard which would indicate the number of weeks from now for the next time off to take place for that user.
Screenshot 2024-08-23 230200
9. Hover over the number next to a user's name to view a tooltip explaining what the number represents.
10. Finally log in as a volunteer account, make sure the volunteer role cannot see the number indicator beside the name.
Screenshot 2024-08-23 230847

## Video of changes
https://github.com/user-attachments/assets/097bb8ad-b6f5-4ae8-9f13-612da4338324

### CODE REVIEW

**Review by RishithaMamidala — CHANGES_REQUESTED** [review]
Everything works as expected. 
PR 2611-1
But when someone is currently on time off and has another time off scheduled a few weeks later, the system doesn't display the upcoming time off with the number of weeks remaining until it occurs.
PR 2611-4

PR 2611-3

**Review by RishithaMamidala — DISMISSED** [review]

**Comment by Jingyii800** [comment]
> Everything works as expected. PR 2611-1 But when someone is currently on time off and has another time off scheduled a few weeks later, the system doesn't display the upcoming time off with the number of weeks remaining until it occurs. PR 2611-4
> 
> PR 2611-3

Thank you for reviewing this! Yes, the mechanism is that the indicator only displays the ongoing time or the most recent time. Therefore, if a person is currently on time off and has scheduled a future time off a few weeks later, the indicator only displays the current one.

**Review by JatinAgrawal94 — DISMISSED** [review]
When I add a time off for a user, it displays for sometime on the dashboard , later it disappears and resets the value.

https://github.com/user-attachments/assets/caa9fb0c-372b-499b-85b1-8c5543f4d596

**Comment by panchalvatneu** [comment]
I’ve reviewed the code and here are some areas where we could make improvements:

**Code Structure and Best Practices:** The component is doing a lot—handling API calls, state management, rendering UI, and complex conditions. It might help to move API calls to a custom hook or a separate service file to keep things organized. Also, functions like fetchInitial and renderTeamsList have some repetitive logic. We could create a reusable function or custom hook for API requests to avoid this duplication.

**Performance Considerations:** useDeepEffect calls getLeaderboardData(userId) every time timeEntries or userId changes. This might lead to unnecessary API calls and re-renders. We could optimize performance by debouncing or throttling this effect. Additionally, setInnerWidth(window.innerWidth) in a useEffect hook might lead to unnecessary updates. It might be better to add an event listener for window resizing and update the state only when necessary.

**Code Quality:** Managing multiple states at the component level can get complex. We might want to use a state management library like Redux, or move some state logic to custom hooks. Error handling in fetchInitial and renderTeamsList could be more robust. Right now, errors are caught and displayed using toast.error. We could add retry mechanisms or more user-friendly messages. Also, using strings like 'Owner', 'Administrator', or 'Select a Team' in multiple places might lead to inconsistencies. Using constants or an enum could help. There’s some duplication in handling dropdown and button states as well—refactoring could reduce repetition.

**Readability and Maintainability:** The JSX contains complex logic and inline functions, making it hard to read. It would help to abstract the teamName function and conditional rendering logic into separate functions. Some variable and function names could be more descriptive, like renaming textButton to something like currentView. Adding more comments, especially in the useEffect hooks and useDeepEffect, would also improve readability.

**Security Considerations:** The current API error handling might expose sensitive information. We should ensure that error messages don’t leak any sensitive data.

**User Experience:** We could improve loading states by using a skeleton loader instead of just a spinner. Error messages should be more informative—guiding the user on what they can do next rather than showing a generic error.

**Accessibility:** Ensure all tooltips are accessible via keyboard and screen readers. All icons and non-text content should have accessible text alternatives.

**Dark Mode Support:** Check that all UI components support dark mode. Abstracting dark mode classes into utility functions or constants might help with consistency.

**Testing:** Adding unit tests for critical functions like useDeepEffect, fetchInitial, and renderTeamsList would be useful. We should also consider snapshot testing to catch any unexpected changes in the UI.

**Dependencies:** We might be able to reduce the dependency footprint by avoiding lodash’s isEqual if the data structures are simple. React’s useEffect with a dependency array could handle deep comparisons if structured properly.

**Security and Data Handling:** Storing user information in sessionStorage has security implications. We should ensure that sensitive data is not stored there and is encrypted if necessary.

Overall, the component works but could benefit from some refactoring to improve performance, maintainability, and user experience. Improving code reusability, state management, and error handling will enhance the quality significantly.

**Review by sri0606 — DISMISSED** [review]
Hey @Jingyii800 , Everything works as expected. Please refer to the below video:


https://github.com/user-attachments/assets/a1036019-58c6-47d8-9989-8a47d2366355

Screenshot 2024-09-04 180352

WhatsApp Image 2024-09-04 at 18 10 00_350a0dd0

**Comment by Jingyii800** [comment]
> I’ve reviewed the code and here are some areas where we could make improvements:
> 
> **Code Structure and Best Practices:** The component is doing a lot—handling API calls, state management, rendering UI, and complex conditions. It might help to move API calls to a custom hook or a separate service file to keep things organized. Also, functions like fetchInitial and renderTeamsList have some repetitive logic. We could create a reusable function or custom hook for API requests to avoid this duplication.
> 
> **Performance Considerations:** useDeepEffect calls getLeaderboardData(userId) every time timeEntries or userId changes. This might lead to unnecessary API calls and re-renders. We could optimize performance by debouncing or throttling this effect. Additionally, setInnerWidth(window.innerWidth) in a useEffect hook might lead to unnecessary updates. It might be better to add an event listener for window resizing and update the state only when necessary.
> 
> **Code Quality:** Managing multiple states at the component level can get complex. We might want to use a state management library like Redux, or move some state logic to custom hooks. Error handling in fetchInitial and renderTeamsList could be more robust. Right now, errors are caught and displayed using toast.error. We could add retry mechanisms or more user-friendly messages. Also, using strings like 'Owner', 'Administrator', or 'Select a Team' in multiple places might lead to inconsistencies. Using constants or an enum could help. There’s some duplication in handling dropdown and button states as well—refactoring could reduce repetition.
> 
> **Readability and Maintainability:** The JSX contains complex logic and inline functions, making it hard to read. It would help to abstract the teamName function and conditional rendering logic into separate functions. Some variable and function names could be more descriptive, like renaming textButton to something like currentView. Adding more comments, especially in the useEffect hooks and useDeepEffect, would also improve readability.
> 
> **Security Considerations:** The current API error handling might expose sensitive information. We should ensure that error messages don’t leak any sensitive data.
> 
> **User Experience:** We could improve loading states by using a skeleton loader instead of just a spinner. Error messages should be more informative—guiding the user on what they can do next rather than showing a generic error.
> 
> **Accessibility:** Ensure all tooltips are accessible via keyboard and screen readers. All icons and non-text content should have accessible text alternatives.
> 
> **Dark Mode Support:** Check that all UI components support dark mode. Abstracting dark mode classes into utility functions or constants might help with consistency.
> 
> **Testing:** Adding unit tests for critical functions like useDeepEffect, fetchInitial, and renderTeamsList would be useful. We should also consider snapshot testing to catch any unexpected changes in the UI.
> 
> **Dependencies:** We might be able to reduce the dependency footprint by avoiding lodash’s isEqual if the data structures are simple. React’s useEffect with a dependency array could handle deep comparisons if structured properly.
> 
> **Security and Data Handling:** Storing user information in sessionStorage has security implications. We should ensure that sensitive data is not stored there and is encrypted if necessary.
> 
> Overall, the component works but could benefit from some refactoring to improve performance, maintainability, and user experience. Improving code reusability, state management, and error handling will enhance the quality significantly.

Thanks for your comment. It would be better to test the function itself, review the code related to this feature and post related videos/images, instead of reviewing the whole script or system. Please refer to the onboarding doc about how to review the PR. Thanks.

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and work as expected. 

Screenshot 2024-09-06 153636
Screenshot 2024-09-06 153911

**Review by Parth-tech — APPROVED** [review]
Hi Jingyi,
The PR works correctly. The text is grayed and the number beside the user matches with the number of weeks that are scheduled off.

`Image References:`
`Volunteer View:`
Screenshot 2024-09-12 at 6 02 30 PM


`Owner Account's View:`
Screenshot 2024-09-12 at 6 17 42 PM
Screenshot 2024-09-12 at 6 20 34 PM

**Review by SnelPatare — DISMISSED** [review]
The changes are working as expected. I tested the changes for 1 week to 3 weeks off. The number and note are indicated correctly. Testing account doesn't show the number "+". Please find below screenshots 
image
image

**Review by ashayk9 — DISMISSED** [review]
I have tested the PR and confirmed that the changes work as expected. Names are correctly grayed out for users on time off during the current week. Users with extended time off are displayed with a "+number" indicating additional weeks off, while those with scheduled future time off show a number (without "+") representing the weeks until their next leave. 
Screenshot 2024-09-13 at 1 10 36 PM
Screenshot 2024-09-13 at 1 10 55 PM

**Review by Abhinav-Ankur786 — APPROVED** [review]
"I have tested this PR, and it functions as expected. All changes align with the intended requirements."
Screenshot 2024-09-13 at 4 58 29 PM
Screenshot 2024-09-13 at 5 04 10 PM

**Review by Shreyav2000 — DISMISSED** [review]
The changes worked as expected. I tried logging in with different accounts (roles) to test the functionality. It displays the most details about the most recent time off. 
Screenshot 2024-09-13 at 9 05 38 PM
Screenshot 2024-09-13 at 9 06 42 PM

**Comment by saurabhshetty29** [comment]
I have reviewed and tested this PR, and it functions as expected.
Screenshot 2024-09-14 at 11 26 17 AM
Screenshot 2024-09-14 at 11 29 06 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
