### PR TITLE
Supriya -Add-Projects-dropdown-in-bmdashboard-with-404-NotFound-page

### PR DESCRIPTION
**Pull request by SupriyaSudini**
# Description
1. Add the Projects dropdown only after selecting the project and enters into its dashboard
2. Show the 404 page if any page is not designed yet or a new link is entered. 

image

## Related PRS (if any):
You can checkout with same PR in backend 
…

## Main changes explained:
1. Added a dropdown for Projects in the bmdashboard header (after selecting a particular project)
2. Added the specific pages to the specific items in the dropdown 
4. Added a 404 - Not Found Page for any links which are not existed will show this page
5. Added the 404 page in dark mode too
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to bmdashboard -> Select a Project -> Go to Project Dashboard -> Projects(in Header) -> check the dropdown Pages
    http://localhost:3000/bmdashboard/login
6. Verify each and every page in dropdown list
7. If no page is created then it leads to 404 page (Not found) (dark mode too)
8. Verify with any random links to check 404 page entire App.

## Screenshots or videos of changes:
[

https://github.com/user-attachments/assets/2afeb8d1-04c9-46bf-82d5-c72537f63abf

](url)

## Note:
Pages in the dropdown list are not in the dark mode yet

### CODE REVIEW

**Review by ShraddhaShahari — COMMENTED** [review]
I have tested this PR and all the pages under dropdown are working as expected. Tested this scenario on both the modes for particular cases as mentioned in the steps, they are working fine. Below is the screen recording attached for the reference.

https://github.com/user-attachments/assets/29abc809-d427-4e82-8b19-58f7fa297375

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/b376e8c7-ed47-40c2-85aa-ff0624940dfc

**Review by RashmiKY98 — COMMENTED** [review]
Reviewed the code. No issues found in the code. However, when testing the functionality, I am not able to see the Projects tab. I am logged in as the admin user. Request you to look into this scenario. Thanks! Good work!
Screenshot 2024-12-14 233754

**Comment by SupriyaSudini** [comment]
> Reviewed the code. No issues found in the code. However, when testing the functionality, I am not able to see the Projects tab. I am logged in as the admin user. Request you to look into this scenario. Thanks! Good work! Screenshot 2024-12-14 233754

Hi @RashmiKY98 You have to select a project and then go to project dashboard, then you could see the dropdown

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
