### PR TITLE
Nahiyan_Optimized permissions management page for mobile displays

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Optimized permissions management page for all viewports 375px wide and above.

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Redesigned pagination so it fits all viewports.
- Added side-scrolling to the table
- Added responsive font sizes.
- Fixed permission item page as well

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links -> Permissions Management 
6. verify that this page is functioning with no issues under all viewports 375px and above
7. Click on a permission item
8.  verify that this page is functioning with no issues under all viewports 375px and above
9. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:
Screenshot 2024-07-11 164310
Screenshot 2024-07-11 164328
Screenshot 2024-07-11 164628

### CODE REVIEW

**Review by AnujVakil — CHANGES_REQUESTED** [review]
I have tested this PR in light and dark mode. Everything looks fine but for the mobile displays, info section icon for Save and Delete Role button is not visible.

Screen Shot 2024-07-11 at 2 15 04 PM

It is visible in normal window view.
Screen Shot 2024-07-11 at 2 14 04 PM

**Review by nyelmela — APPROVED** [review]
I have tested this PR, and everything works perfectly well. I checked into the current branch, ran `npm install`, and `npm run start:local` to run the PR locally. After clearing the site data and cache, I logged in as the owner user and navigated to the dashboard → Other Links → Permissions Management. I verified that this page functions without any issues under all viewports 375px and above. Additionally, I clicked on a permission item and confirmed that the page continued to function correctly under all viewports 375px and above. Lastly, I ensured that this new feature works seamlessly in dark mode. Everything worked as expected.

image

image

**Comment by Nahiyan-16** [comment]
@AnujVakil You're not on the correct branch. Please retest this.

**Comment by angelalalacheng** [comment]
Hi Nahiyan-16,

I set the frontend branch as `Nahiyan_Optimize-Permissions-Management-Page` and backend branch as `development`.  Then page is functioning with no issues at viewports 375px in both light and dark mode and permission list works good as well.
Screenshot 2024-07-11 at 3 41 15 PM
Screenshot 2024-07-11 at 3 41 41 PM
Screenshot 2024-07-11 at 3 43 35 PM
Screenshot 2024-07-11 at 3 42 03 PM
Screenshot 2024-07-11 at 3 42 29 PM

**Review by angelalalacheng — APPROVED** [review]

**Review by vijay10pk — APPROVED** [review]
All the changes works as expected.

https://github.com/user-attachments/assets/0afd59b9-ae77-4610-8db3-f1ac73dd32ff

**Review by AnujVakil — DISMISSED** [review]
I have re-tested this PR on current branch and it is working fine.
Screen Shot 2024-07-11 at 4 52 06 PM

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected for both light mode and dark mode.
Screenshot (74)
Screenshot (75)
Screenshot (76)
Screenshot (77)

**Review by SaiLavanya1 — APPROVED** [review]
I've tested this PR and it is working fine.
https://www.loom.com/share/5cf1fc4ca43947b38165f6d4e8ca683f

**Review by kdaga81 — DISMISSED** [review]
image
image

The changes are working as expected!

**Review by sahithidhulipala9 — APPROVED** [review]
Tested this feature, in all the above mentioned steps, feature working as expected.
PR 2446 1
PR 2446 2
PR 2446 3

**Review by rmcgummadi — APPROVED** [review]
I have logged in as the local Admin User and tested Pull Request #2446. It is working as expected. I tested it in both dark mode and light mode with a viewport of 375px wide and above. The functionality is working as expected.
[Screenshot 2024-07-12 at 9 33 20 AM
](URL)
Screenshot 2024-07-12 at 9 34 47 AM

**Review by Vigneshwar-Muriki — DISMISSED** [review]
I tested this PR by logging in as an admin and verifying the feature on mobile displays and other viewports. All the buttons align correctly across all viewports. Additionally, when a permission item is clicked, the page functions properly on all viewports and in dark mode.

https://github.com/user-attachments/assets/81c57f21-34da-4e48-bbd1-027b01fd7fb2

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

image

image

**Review by beblicarl — DISMISSED** [review]

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and everything works as expected. Great Work!!!


https://github.com/user-attachments/assets/6daa7490-cef1-4174-9d10-7d61c1586f52

**Review by Rishitha1309 — APPROVED** [review]
I have tested this PR in both light mode and dark mode, everything works perfectly fine.

**Review by aaryaneil — DISMISSED** [review]
Tested the PR for 375px for light and dark mode and the changes work as expected.
Screenshot 2024-07-12 at 9 11 24 PM
Screenshot 2024-07-12 at 9 11 40 PM
Screenshot 2024-07-12 at 9 12 57 PM
Screenshot 2024-07-12 at 9 13 22 PM

**Review by cecilia-uu — DISMISSED** [review]
截屏2024-07-13 下午11 24 49
截屏2024-07-13 下午11 24 57
It works as expected!

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi Nahiyan, 

The Mobile layout looks good. Most of it works pretty well. I found a minor issue.
1. In 390 px, The user name gets cut out if the drop-down in other links in opened.
image
This occurs in 430px as well
image

everything else looks good!

**Review by MinSun0814 — DISMISSED** [review]
image
Screenshot 2024-07-13 at 16 55 14
Nothing looks overlapping. Nice work!

**Review by Shadhrush5 — DISMISSED** [review]
Hi, I reviewed PR #2446 by following the steps mentioned.
Checked out the branch "Nahiyan_Optimize-Permissions-Management-Page".
Ran the npm run start:loclal command
Logged in as owner -> Other Links -> Permission management

The  page functions without any issues under all viewports 375px and above.

Screenshot 2024-07-15 at 10 18 32 AM


Additionally, I clicked on a permission item and confirmed that the page continued to function correctly under all viewports 375px and above.  

Screenshot 2024-07-15 at 10 19 16 AM
Screenshot 2024-07-15 at 10 19 32 AM

Everything works as expected. Thank you for the great work.

**Comment by Nahiyan-16** [comment]
@KaushikMreddy The header is not solely part of the permission management page. It is its component and there is a [PR](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2378) handling this.

**Review by Chetan0606 — APPROVED** [review]
Tested all the functionalities as per the provided steps and everything looks fine.
Screenshot (311)
Screenshot (310)
Screenshot (309)
Screenshot (308)

**Review by SrikanthChowdary495 — COMMENTED** [review]
I logged in as the local Admin User and tested Pull Request #2446. Everything works as expected in both dark mode and light mode, with a viewport of 375px wide and above. 
please find the video for reference. 

https://github.com/user-attachments/assets/3243c7c5-d9b9-4d03-bde5-cf77cfcc7774

**Comment by ReinaT5678** [comment]
The Permissions Management page works as expected. I was able to test the functionality for both light and dark screens with viewports below and above 375px and both worked well. See screenshots below from when I was testing!

Screenshot 2024-07-20 at 3 02 17 PM

Screenshot 2024-07-20 at 3 02 27 PM

Below are images from exploring the different pages within the permissions management page and testing different popups and buttons.

Screenshot 2024-07-20 at 3 04 33 PM

Screenshot 2024-07-20 at 3 05 02 PM

**Review by ReinaT5678 — APPROVED** [review]

**Review by pavanswaroopl — COMMENTED** [review]
Good work,

Permissions management initial page works on all viewports fine, but not sure whether this is in this PR scope, buttons go out of view when width < 375px. after entering a role.

https://github.com/user-attachments/assets/c30e9717-cb47-48b7-8017-0c0b75e478e0


https://github.com/user-attachments/assets/16106c34-58e2-4d3f-ab46-f3ebdf5a806b

Screenshot 2024-07-20 at 9 03 19 PM

**Pull request merged**
