### PR TITLE
Yixiao_TaskEditSuggestionRow_unittest

### PR DESCRIPTION
**Pull request by JYXiao-2021**
# Description
Create a unit test for the TaskEditSuggestionRow component to confirm whether it working as intended.

## Main changes explained:
- Create file TaskEditSuggestionRow.test.js to do the unit test.
- Change some structure of file TaskEditSuggestionRow.jsx for more friendly test.

## How to test:
1. check into current branch
2. do `npm install`  to run this PR locally
3. run `npm test TaskEditSuggestionRow.test.js`

## Screenshots or videos of changes:
image

### CODE REVIEW

**Comment by wanglu1207** [comment]
@JYXiao-2021 , good job! It works for me!
yixiao_TaskEditSuggestionRow_unit

**Review by Hemsharavanan — DISMISSED** [review]
Work fine. Nice work!

Yixiao_TaskEditSuggestionRow_unittest #1511

**Review by Bali2Mohit — COMMENTED** [review]
Hi @JYXiao-2021 , tested your changes. All test passed. Good work.
Screenshot 2023-11-11 at 23 10 28

**Review by pika-chu11 — DISMISSED** [review]
Hi @JYXiao-2021 , I have ran your test on my end and it passed. Great job!
PR 1511

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed! Great work!

Week 11 - PR 4

**Comment by kavya151** [comment]
Hii @JYXiao-2021 , All the test cases passed. Good Job!
Screenshot 2023-11-11 at 8 08 13 PM

**Review by zuhang2000 — DISMISSED** [review]
Hi I've tested your PR following your instructions. Everything works as expected! Good job. The code also looks good to me!
Screenshot 2023-11-11 at 10 18 09 PM

**Review by Bali2Mohit — APPROVED** [review]

**Review by DavidC0126 — DISMISSED** [review]
Hi @JYXiao-2021 I tested the PR and it works as intended.

Screenshot 2023-11-14 at 4 38 42 PM

**Review by navneeeth — DISMISSED** [review]
Hello, @JYXiao-2021! Great implementation of the tests! The test cases are all passing:
test cases passing

**Review by keyunhuangg — DISMISSED** [review]
Hello, seem like all 6 tests were passed!
Screenshot 2023-12-01 at 4 11 25 PM

**Review by Alforoan — DISMISSED** [review]
All tests passed. Nice!

image

**Review by bajajtushar094 — APPROVED** [review]
All test cases passed. Thanks
Screenshot 2024-01-11 at 23 56 45

**Review by yvonnep165 — DISMISSED** [review]
Hi @JYXiao-2021,
I ran the tests and all tests passed as intended. Nice work!
PR 1511

**Review by 666saofeng — APPROVED** [review]
All tests passed!
image

**Comment by DragonSlayer2401** [comment]
All tests ran without any issues please watch the video for more details

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/ce21b385-90cf-4c51-b2a9-b473d11c5bd5

**Review by XiaohanMeng — DISMISSED** [review]
All cases passed! Great Work!
PR1511 UnitTest result

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and worked as expected.

Captura de tela 2024-02-18 042028

**Review by skaush21 — APPROVED** [review]
ran the mentioned unit test, test passes all test
no errors in console

PR 1511

**Review by scoopstroop92 — CHANGES_REQUESTED** [review]
Hello @JYXiao-2021  good job! Kindly refer the unit test documentation and move  the unit tests to the appropriate path 
image

**Comment by JYXiao-2021** [comment]
> Hello @JYXiao-2021 good job! Kindly refer the unit test documentation and move the unit tests to the appropriate path image

please review again, thanks

**Review by scoopstroop92 — APPROVED** [review]
Approving the PR as the previous suggestion has been addressed

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
