### PR TITLE
Deepthi fix static dates dropdown menu 

### PR DESCRIPTION
**Pull request by deepthikannan**
# Description
image 
…

## Main changes explained:
- Update BadgeReport.css: Modified the .badge_dropdown class to remove the fixed height of 25vh. The dropdown now uses max-height and overflow-y: auto to dynamically adjust based on the number of items.
- Remove unnecessary scrollbars that were appearing due to the fixed height by setting the height to auto.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/ owner user
5. go to dashboard→ view profile→ featured badges→ select featured
6. verify that the "Dates" dropdown now resizes correctly when there is only one date listed, and no unnecessary space or scrollbars are present.

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Good work.
Screenshot 2024-08-24 at 10 10 33 PM

**Review by abdel-lall — APPROVED** [review]
LGTM. Good Job!

Screenshot 2024-08-25 002734

**Review by Vigneshwar-Muriki — APPROVED** [review]
Changes work as expected.
Screenshot 2024-08-26 213538

**Review by manikittu810 — APPROVED** [review]
Hello @deepthikannan 
Everything is working as mentioned.

Screenshot 2024-08-27 at 12 42 41 PM

Thank you.

**Review by RishithaMamidala — APPROVED** [review]
@deepthikannan 
The dates work as expected
PR 2617

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and verified that the "Dates" dropdown now resizes correctly when there is only one date listed, and no unnecessary space or scrollbars are present.

Screenshot 2024-08-29 162422

**Review by jinxyou — APPROVED** [review]
Screenshot 2024-08-30 214109
The dropdown menu seems to be fine. Great work!

**Review by Pranay-ai — APPROVED** [review]
Hey @deepthikannan 
The PR is Working as expected
image

**Review by CillianRen — APPROVED** [review]
image
It works great.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
