### PR TITLE
Sarath added TeamsOverview.css fixing the Teams UI (padding,cards)

### PR DESCRIPTION
**Pull request by Sarath-3119**
# Description
The Teams page in admin/owner profile has the following UI issues - 
        - At 768x and below, the table is not centered. Too much left side margin and too little right side.
	- At 768px and below, that top 2 cards have no padding
	- At 575px and below, the table starts side scrolling. We need to reduce font size to prevent this.
	- AT 479px and below, the cards stack vertically. We can make them smaller so this doesn’t happen.
	- Around 400px and below, the members modal’s table cuts off and starts side scrolling.

## Related PRS (if any):
This frontend PR is related to the #develpment backend PR.

…

## Main changes explained:
- Added file TeamsOverview.css to 
- Added a TeamsOverview.css styling page to make the cards adjust to the UI instead of stacking vertically.
- Added a padding as required. The table goes to scrolling mode when the rest of the table is not visible in the viewport at lower resolutions.

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. Click on other links and go to Teams page
6. Go to dev tools and verify the above changes in different resolutions, and also check the responsiveness of the page.

## Screenshots or videos of changes:

Before: 
https://www.loom.com/share/853a50e83a2f40a4a8c7cc065142fa0e

After Changes: 
https://www.loom.com/share/d7c3b8096dad460f9abfa70d5020e56b 
https://www.loom.com/share/f762567f1bf94c66b7b958ca7ae1456b

### CODE REVIEW

**Review by nyelmela — APPROVED** [review]
The PR has been tested and works as expected. Checked into the current branch, ran `npm install` and the necessary commands to run the PR locally, and cleared site data/cache. Logged in as an admin user, clicked on other links, and navigated to the Teams page. Used dev tools to verify the changes in different resolutions and checked the responsiveness of the page. Everything functions as demonstrated in the video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/0db5ca69-395c-4bcc-a64e-057a32ab4ef2

**Review by vijay10pk — DISMISSED** [review]
All the changes are working as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/0887ed7b-1080-48a9-9cd7-660649c49a4e

**Review by MinSun0814 — DISMISSED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/41264d2e-35ef-4ff9-8d72-a7eb74bf7e6e

The padding works as intended as there is no text or card overlaps. Nice work.

**Comment by IchinnorovTuguldur** [comment]
Verified the responsiveness of the page. It works as expected dynamically. Great Job!!
Screenshot 2024-07-05 at 4 21 49 PM

**Review by sahithidhulipala9 — APPROVED** [review]
PR working as expected!
PR 2416

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/6a986ea9-fdee-4553-9a5f-720fb08d3d20

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi Sarath, 

Your changes work as expected, but please do address this as well. Between 575 px to 765 px width of the screen, the table gets cut, the horizontal scroll is available but there is no padding to the right of the table. Please make the table convert into a mobile format if its below 800 px or a similar look can be taken up. 

image

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR  by following the given steps and  it works as expected. i have attached video for your reference

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/2dbf44a7-733a-4a14-abbf-a0ef47111579

**Comment by nikethaanand** [comment]
Tested the pull request and ran it locally. The alignment works correctly on changing the screen sizes!
[

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47215795/07151e08-0675-4de4-9baf-e4a81f05b12d

](url)

**Comment by Sarath-3119** [comment]
> Hi Sarath,
> 
> Your changes work as expected, but please do address this as well. Between 575 px to 765 px width of the screen, the table gets cut, the horizontal scroll is available but there is no padding to the right of the table. Please make the table convert into a mobile format if its below 800 px or a similar look can be taken up.
> 
> image

Can you please try now?

**Review by Rishitha1309 — APPROVED** [review]
tested the PR working perfectly.

**Comment by angelalalacheng** [comment]
I use your branch to test. However, for me, the behavior seems not consistent with what you want based on the description(?).
1. At 575px and below, the table starts side scrolling. We need to reduce font size to prevent this.
2. AT 479px and below, the cards stack vertically. We can make them smaller so this doesn’t happen.

Screenshot 2024-07-12 at 3 40 14 PM
Screenshot 2024-07-12 at 3 21 28 PM
Screenshot 2024-07-12 at 3 34 44 PM
Screenshot 2024-07-12 at 3 35 46 PM

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected for different resolutions.

https://github.com/user-attachments/assets/421b6532-6227-4340-b07f-dde67a829d6b

**Review by AnujVakil — CHANGES_REQUESTED** [review]
I have tested this PR. When I try to test if for 479px and below, Issue of the cards stack vertically is still occurring . I have tried running on sarath-teams-ui branch only.
PR #2416_1

**Comment by Sarath-3119** [comment]
> I have tested this PR. When I try to test if for 479px and below, Issue of the cards stack vertically is still occurring . I have tried running on sarath-teams-ui branch only. PR #2416_1

Hey Anuj, Can you kindly check , I have modified the UI as addressed.

**Comment by Sarath-3119** [comment]
> I have tested this PR. When I try to test if for 479px and below, Issue of the cards stack vertically is still occurring . I have tried running on sarath-teams-ui branch only. PR #2416_1

Kindly check with the latest checkout. Thank You

**Review by SrikanthChowdary495 — COMMENTED** [review]
I tested the PR and it works fine. I checked it into the current branch, ran npm install, and used the necessary commands to run it locally. I cleared the site data/cache, logged in as an admin user, and navigated to the Teams page, clicking on various links. Using dev tools, I verified the changes at different resolutions and checked the page's responsiveness. Everything works as shown in the video.

https://github.com/user-attachments/assets/8a79d2d6-4f45-4e05-b795-001241b45add

**Review by pavanswaroopl — DISMISSED** [review]
Excellent work,

Changes are working as expected.

https://github.com/user-attachments/assets/880e1a8d-7f70-4c04-b703-2fc000b8f411

Screenshot 2024-07-20 at 8 03 11 PM

**Review by jinxyou — DISMISSED** [review]
I tested the UI resizing. It seems to work fine. Great work!

https://github.com/user-attachments/assets/3ee55be9-6d2e-46fc-b489-d250769ff739

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR with with different resolutions and checked the responsiveness of the page. Below video has the details.

https://github.com/user-attachments/assets/a6682880-8b16-4a95-aa89-c5e243eb4708

**Comment by souravwalke** [comment]
Tested the implementation of the PR and everything works as expected.
https://www.loom.com/share/376519c9cb0940a88031d3a332d2ce23?sid=8b08aaea-1811-4e0a-8136-8c4f36df02b4

**Review by ReinaT5678 — DISMISSED** [review]
The CSS styles work as expected in different size viewports. I wasn't able to make a successful edit, but I'm not sure if that was a functionality issue before the changes. I added a video below of my testing!

https://github.com/user-attachments/assets/9f420ac1-4cea-49df-9af8-a121d6668ee0

**Review by Shadhrush5 — APPROVED** [review]
Hi, I have reviewed PR #2416. I followed the instructions while executing the test as mentioned. The functionality works as stated. Thank you for the great work. I have approved the same. The below video depicts my testing.

https://github.com/user-attachments/assets/55ef50e3-590d-4b2b-8900-ebe5ecd9d7ce

**Review by SaiLavanya1 — APPROVED** [review]
Hi,
The code changes address the UI issues on the Teams page effectively, ensuring the table and cards are properly aligned and responsive across various screen resolutions. The added CSS styling helps maintain consistent spacing and prevents side scrolling. After testing the PR, the UI adjustments work as intended without introducing any new issues.
https://www.loom.com/share/0f169697a1d64b698a6a62b16882f047

**Review by Pranay-ai — APPROVED** [review]
Hey @Sarath-3119 Everything is Working as Expected
image
image
image
Thank You.

**Review by Chetan0606 — APPROVED** [review]
Followed the description and verified accordingly. Everything looks good.

https://github.com/user-attachments/assets/a77782a4-c0d7-4737-aba6-6968250af6ef

**Review by Nahiyan-16 — CHANGES_REQUESTED** [review]
Hi @Sarath-3119, great job on this PR but there is a slight problem with the members modal. Please take a look at the video: 


https://github.com/user-attachments/assets/c53ecf86-9a80-4207-b0a7-dd432bdfd25b

**Review by kabraambika — CHANGES_REQUESTED** [review]
I have reviewed the frontend PR along with the associated backend PR. Here are my observations:

- [x] Resolution 768px and above: Working correctly in both light and dark modes.
- [x] Resolution between 425px and 768px: Working correctly in both light and dark modes.
- [x] Resolution between 375px and 425px: Working correctly in both light and dark modes.
- [ ] Resolution 325px: UI is not displaying properly.

image

**Comment by Sarath-3119** [comment]
> I have reviewed the frontend PR along with the associated backend PR. Here are my observations:
> 
> * [x]  Resolution 768px and above: Working correctly in both light and dark modes.
> * [x]  Resolution between 425px and 768px: Working correctly in both light and dark modes.
> * [x]  Resolution between 375px and 425px: Working correctly in both light and dark modes.
> * [ ]  Resolution 325px: UI is not displaying properly.
> 
> image

Could you please review the latest checkout. Thank you!

**Comment by Sarath-3119** [comment]
> Hi @Sarath-3119, great job on this PR but there is a slight problem with the members modal. Please take a look at the video:
> 
>  Recording.2024-07-27.121831.mp4

Thank you for bringing this up Nahiyan ,
This seems to be an existing issue, in the dev site itself. I will see if there are any fixes from my end.

**Comment by kabraambika** [comment]
> Could you please review the latest checkout? Thank You!
> 
> > I have reviewed the frontend PR along with the associated backend PR. Here are my observations:
> > 
> > * [x]   Resolution 768px and above: Working correctly in both light and dark modes.
> > * [x]   Resolution between 425px and 768px: Working correctly in both light and dark modes.
> > * [x]   Resolution between 375px and 425px: Working correctly in both light and dark modes.
> > * [ ]   Resolution 325px: UI is not displaying properly.
> > 
> > image
> 
> Could you please review the latest checkout. Thank you!

I tested the feature on the branch with the latest changes. In the 320px resolution [small mobile view], the UI components at the top of the table are not displaying with the correct spacing. Please refer to the video:

https://github.com/user-attachments/assets/7dfe28ea-dfbf-4b91-8a5a-4ae4ee0b35b8

**Review by kabraambika — COMMENTED** [review]
I've shared a video of my observation along with testing on latest changes in this [comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2416#issuecomment-2259237572)

**Comment by Sarath-3119** [comment]
> I've shared a video of my observation along with testing on latest changes in this [comment](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2416#issuecomment-2259237572)

@kabraambika  Thank you for bringing this up. I suspect this is an existing issue. I just checked the live site and it seems to be same case over there too. Please look into the below recording. 
https://www.loom.com/share/4d9fec6ca33b45a5b54ba140ca13216d

**Review by kabraambika — APPROVED** [review]
As mentioned above, the search text box, "Create New Team" button, and the other two bars shown below are present similarily in the main branch as well in resolution 320px. 
image
 Hence, approving the PR.

**Comment by arunsrao9** [comment]
Tested the PR with with different resolutions and checked the responsiveness of the page. Everything looks good, Good work!
Screenshot 2024-07-31 at 11 36 49 AM
Screenshot 2024-07-31 at 11 36 23 AM
Screenshot 2024-07-31 at 11 36 01 AM

**Review by SatyashanthiT — APPROVED** [review]
Based on the review of the PR #2416 and testing video, the changes implemented successfully address the UI issues on the Teams page across various resolutions. The padding, alignment, and responsiveness adjustments improve the overall layout, preventing unnecessary vertical stacking and side scrolling of elements. The page now displays correctly at different breakpoints. I recommend approving this PR as the enhancements effectively resolve the previously mentioned UI concerns.

https://github.com/user-attachments/assets/32c073f7-c741-4305-8809-1a7caa80afc7

**Review by adityasure9 — APPROVED** [review]
Hi Sarath,

I've tested the PR, and the UI changes work as intended across various resolutions. The issues with padding, card stacking, and table alignment are effectively resolved, and the Teams page is now much more responsive. Great work on addressing these UI concerns! However, I noticed a minor issue with the members' modal not displaying correctly at certain resolutions, particularly around 320px, but this seems to be a pre-existing issue. Other than that, everything looks good!

Before,



After,



Thanks for your effort in improving the UI!

**Review by AnkitLall — APPROVED** [review]
I have tested the feature, following the instructions in the PR, and it works as expected. I’ve attached a video recording of the testing process.

https://github.com/user-attachments/assets/cca67ad1-c411-4f0a-b7f0-0fb4e8830778

**Review by strallia — CHANGES_REQUESTED** [review]
An issue I found was that at 450px and below, I found the Search input bar to be too small, particularly when the placeholder text starts to cut off.

At 400px width:
Screenshot 2024-09-05 at 6 04 37 PM
At 350px width:
Screenshot 2024-09-05 at 6 04 48 PM
At 320px, the Search button detaches from the Search input. Design wise, I think they should stay together.
Screenshot 2024-09-05 at 6 13 56 PM

One solution is to move the Search button/input underneath the Create New Team button onto its own line at those widths.

Everything else is working as expected. Great work!

**Review by ashayk9 — APPROVED** [review]
I reviewed the pr. Everything is functioning correctly for most screen resolutions. At resolutions of 768px and above, as well as between 425px and 768px, the UI works properly in both light and dark modes. Similarly, for resolutions between 375px and 425px, the display is consistent and accurate across both modes. However, at a resolution of 320px, the UI is not displaying as expected.

https://github.com/user-attachments/assets/2dc87be1-4dd5-46a9-9672-3fd14619c41a

**Review by swaroop-2007 — CHANGES_REQUESTED** [review]
@Sarath-3119 
I reviewed your PR and checked your code. Everything works well. 
Just a suggestion: in less than 400 px, the search bar's input is not visible clearly. I have attached the screenshot. 

Screenshot (363)

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected.

image

Thank You

**Review by crystallow1168 — APPROVED** [review]
Hi @Sarath-3119,

I have tested the PR and below are my findings (refer to image below):

> At 768x and below, the table is not centered. Too much left side margin and too little right side. 
> At 768px and below, that top 2 cards have no padding

- ✅ At 768x and below, table is centered and the cards are aligned horizontally

> At 575px and below, the table starts side scrolling. We need to reduce font size to prevent this.

- ✅ At 575px and below, table is centered and the cards are aligned horizontally
    - ❗️Currently user will still need to side scroll to view the table (Ignore this if this is the expected behavior)

> AT 479px and below, the cards stack vertically. We can make them smaller so this doesn’t happen.

- ✅ At 479px and below, the cards are aligned horizontally

> Around 400px and below, the members modal’s table cuts off and starts side scrolling.

- ❗️ At 441px and below, user will need to side scroll to view the table(Ignore this if this is the expected behavior). The text for total teams and active teams look overcrowded

image

---

Other observations:  The right of the active teams button is not aligned with the table. 
image

**Comment by geetamatkar** [comment]
Hi @Sarath-3119 ,
I tested your PR for different screen resolutions and it is responsive as expected.

PR2416

**Review by SnelPatare — CHANGES_REQUESTED** [review]
I tested the changes. I have couple of observations. 
Requirements:
The Teams page in admin/owner profile has the following UI issues -
- At 768x and below, the table is not centered. Too much left side margin and too little right side.  - Working as per expectations
- At 768px and below, that top 2 cards have no padding - Working as per expectations 
- At 575px and below, the table starts side scrolling. We need to reduce font size to prevent this. - I have observed that the table goes to scrolling at 767px resolution and fable font can be reduced.
- AT 479px and below, the cards stack vertically. We can make them smaller so this doesn’t happen. - Working as per expectations

Changed can be made to reduce table font size as we did for cards.

image

**Review by Shreyav2000 — APPROVED** [review]
Tested the changes, and everything works as expected.

The table and cards are now properly aligned and responsive across various screen sizes.
Font size and padding adjustments prevent side scrolling, and the members modal table displays correctly at lower resolutions.
Great job on these UI fixes!

https://github.com/user-attachments/assets/06cedcf1-195e-4c1e-9cb1-86e83e3378da

**Review by nishitag5 — APPROVED** [review]
The changes are working as expected.

https://github.com/user-attachments/assets/d36ea48e-4c29-4013-a4d9-4ddda4ba844f

**Pull request closed without merging**
