### PR TITLE
Lucile - ForcePassword and Reports tests

### PR DESCRIPTION
**Pull request by LucileTech**
# Description
Unit Tests HGN

<google-sheets-html-origin>

ForcePasswordUpdate | ForcePasswordUpdate.jsx | Yes. Have test files in two places. Need to reconcile together.https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/blob/bc16494d8f4a3bdb371d5d86374cbd5522bf2642/src/__tests__/ForcePasswordUpdate.test.jshttps://github.com/OneCommunityGlobal/HighestGoodNetworkApp/blob/bc16494d8f4a3bdb371d5d86374cbd5522bf2642/src/components/ForcePasswordUpdate/ForcePasswordUpdate.test.jsx
-- | -- | --

<google-sheets-html-origin>

Reports | Reports.jsx | there is an empty test file
-- | -- | --

## Main changes explained:
- merge ForcePassword test files and create Reports test file

## How to test:
1. check into current branch
2. do `npm test` 
3. verify that ForcePassword & Reports tests PASS

### CODE REVIEW

**Review by KurtisIvey — APPROVED** [review]
pr1334 all tests pass
All tests pass and the code looks good 👍🏻

**Review by TuanDinh140194 — APPROVED** [review]
All the tests
Screenshot 2023-09-22 133307
Screenshot 2023-09-22 132707
Screenshot 2023-09-22 132502
 are passed

**Comment by Vishala09** [comment]
1. ForcePasswordUpdate: Test  -> Works fine
image
Good coverage!
image

2. Reports: Test  -> Works fine
image

**Review by DavidC0126 — APPROVED** [review]
Hi @LucileTech I tested this PR and it works as described.
all_
force
report

**Review by Chuehleo — APPROVED** [review]
All of the tests are passed, great job!
Screenshot 2023-09-22 185327
Screenshot 2023-09-22 185231
Screenshot 2023-09-22 185419

**Review by dah00 — APPROVED** [review]
Hey, all tests passed as expected. Great job!
PR1334_ForcePassword
PR1334_all_tests_passed
PR1334_true_report

**Comment by astrjc0326** [comment]
Hi, it works as described.
Screen Shot 2023-09-22 at 8 22 07 PM
Screen Shot 2023-09-22 at 8 22 43 PM

**Review by veronicacheng2 — APPROVED** [review]
Hi @LucileTech, I tested according to the description. It works as intended:

image

**Review by winghojackyli — APPROVED** [review]
Hi @LucileTech , all tests passed. Great work!

All tests passed. 


ForcePassword passed



Reports passed

**Review by Vishala09 — COMMENTED** [review]
Can you confirm me on this? "Regarding the Reports Test, Should we add more tests to increase some coverage or is the requirement to test the render of the Reports component?"

**Review by EdwinLauM — APPROVED** [review]
Hey @LucileTech, test pass and works as expected!

Screen Shot 2023-09-22 at 11 49 20 PM

Screen Shot 2023-09-22 at 11 50 15 PM

Screen Shot 2023-09-22 at 11 50 05 PM

**Comment by AnishPandita** [comment]
Hey, I tested the PRs and the test suites for forcepassword and reports seem to function properly. No errors found.
Screenshot 2023-09-23 at 1 03 07 AM
Screenshot 2023-09-23 at 1 01 20 AM
Screenshot 2023-09-23 at 1 04 10 AM

**Review by JeffLi117 — APPROVED** [review]
Tested as according to the description. LGTM, good job!

image

**Review by wantingxu7 — APPROVED** [review]
Hi, the test works fine as shown in the screenshot:

**Review by JYXiao-2021 — COMMENTED** [review]
Hi, I test the pr and it passed.
Screenshot 2023-09-23 at 6 25 54 PM

**Review by Haoj1 — APPROVED** [review]
@LucileTech All tests passed. Good job!

**Review by luisarevalo21 — APPROVED** [review]
Hello @LucileTech 

I tested your PR and works as intended. Great work. 
Upon running npm test. I can view the reports.test.js passes and the force password test also passes. Great work. 

Screenshot 2023-09-24 at 7 49 45 PM
Screenshot 2023-09-24 at 7 50 09 PM

**Review by Sssky-18 — APPROVED** [review]
Hi @LucileTech, I just tested this PR. I ran the test on each of the test file on my computer, and the code passed all test cases. So just approved it.
ForcePasswordUpdate:

#1334_ForcePasswordUpdate

Reports:

#1334_Reports

ForgotPassword:

#1334_ForgotPassword

**Review by vikrambadhan — APPROVED** [review]
Hi, All test cases passed! Great job !

week5 - PR1
week5 - PR1(2)
week5 - PR1 (1)

**Review by eduhorta — APPROVED** [review]
Everything working 👍 

image

**Pull request merged**
