### PR TITLE
Obeda lint fix AutoUpdate components

### PR DESCRIPTION
**Pull request by dah00**
# Description
Lint fix for AutoUpdate components 
src/component/AutoUpdate/**

## Main changes explained:
- Removed AutoUpdate folder from both .prettierignore and .eslintignore
- Run npm run lint:fix to automatically fix some errors
- Manually fixed the rest of errors 

## How to test:
1. check into current branch
2. Run `npm install` and `npx eslint src/components/AutoUpdate/*` to make sure there is no lint errors
3. Run `npm run test` to make sure that all tests pass 
4. Run `npm run start:local` 
5. log as any user
6. Make sure that the app works as usual 

## Screenshots or videos of changes:
all tests pass

## Note:
This is my first lint fix so feel free to give me suggestions for any necessary changes.

### CODE REVIEW

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended! All the test cases passed, there are no lint errors and the app works normally.

Week8 - PR5

Week8 - PR5 lint check

**Review by TheDescendant39 — COMMENTED** [review]
Hi @dah00, your lint changes work well. I ran the command to check if there were any errors and also checked the 
Screen Shot 2023-10-21 at 2 53 14 PM
normal functioning of the application.

**Review by malikjahanzaib — APPROVED** [review]
Hi @dah00, All tests passing and no lint errors. Great job!!!

Screenshots:

Screenshot 2023-10-21 153335

Screenshot 2023-10-21 153252

**Comment by RheaWu1212** [comment]
Hi your PR works as expected! All the test cases passed:
Screen Shot 2023-10-21 at 18 47 32

**Comment by palakgosalia** [comment]
Hey, I have reviewed your PR and tested the application. All test cases passed. Thank you

image

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-10-21 171851

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and works as intended. Great work!

Screenshot 2023-10-21 at 10 17 55 PM

**Review by ChirayuRai — APPROVED** [review]
All tests pass, and the app seems to run as intended. Good job!

Screenshot 2023-10-21 at 7 59 03 PM

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this file and it works as intended.
Screenshot 2023-10-21 at 11 08 45 PM

**Review by zuhangc180 — APPROVED** [review]

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions. Everything works as expected.
All test cases passed. "eslint" reports no error!
The app is also working correctly.
Screenshot 2023-10-22 at 12 44 45 AM

Screenshot 2023-10-22 at 12 45 03 AM

**Comment by beblicarl** [comment]
All tests passed, great work !!

image

**Review by beblicarl — APPROVED** [review]

**Pull request merged**
