### PR TITLE
Peterson implement default error page to be created and redirected to

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request has been opened to implement an error page after the user uses a link to redirect to a page that does not exist.

## Related PRS (if any):
None

## Main changes explained:
Six components have been modified to implement the page of error.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Log in as any user.
4. Go to a URL that does not exist, e.g., http://localhost:3000/project
5. If the user is logged in, two links should appear on the error page: the first redirects to the dashboard, and the second also redirects to the same route but should open the modal for suggestions and development.
6. If the user is not logged in, a link should appear on the error page that redirects to the login page.

## Screenshots or videos of changes:
Peterson_implement_Default_Error_Page_to_be_created_and_redirected_to

## Note:
None

### CODE REVIEW

**Review by vijay10pk — DISMISSED** [review]
The changes works as expected.
Screenshot 2024-09-17 at 10 17 56 PM
**Suggestion:**
It would be better if you centre align the content for small screen sizes.
Screenshot 2024-09-17 at 10 17 56 PM

**Review by RishithaMamidala — APPROVED** [review]
@peterson337 
When accessing a page that is not present, the error page i.e., page not found is correctly displayed with correct link to the home page.
PR 2685

**Review by ArtemisNyx3 — APPROVED** [review]
image


404 Page works well and its smart to throw 404 for unauthorized users (not logged in)

Good job 👍🏽

**Review by Lexie5212 — APPROVED** [review]
I tested the PR. All changes work as expected.

https://github.com/user-attachments/assets/92976e13-0490-4ac3-ab36-a4d36121c3c6

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Review by mohangadde1 — DISMISSED** [review]
image
changes work as expected

**Review by Logeshwari-Renu — APPROVED** [review]
Tested the PR and verified both the cases of invalid pages with nd without the user Logged in and  it redirects to the default error page. Great work!!

**Review by Gauravmg6 — APPROVED** [review]
The links are working as expected.
Screenshot 2024-09-22 180450

**Review by slidracoon72 — DISMISSED** [review]
#2685
@peterson337 
If the user is logged in, two links appear on the error page as expected: the first correctly redirects to the dashboard, and the second also redirects to the same route while opening the modal for suggestions and development.

Video Demonstration:
https://www.loom.com/share/b6f2fde7bfb74be68c3348d2a1168d77?sid=a3c9be66-dec4-407a-8106-fe05ffc5d642

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.
Screenshot (208)

**Comment by geetamatkar** [comment]
Hi @peterson337 ,
I tested this PR and everything is working as expected.

PR2685-1
PR2685-2

**Review by one-community — CHANGES_REQUESTED** [review]
This doesn't look anything like what I requested: 
image

**Pull request merged**
