### PR TITLE
Shiwani Projects.jsx unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/Projects/__tests__/Projects.test.js`

## Main changes explained:
- Added 11 test cases: renders without crashing, check if Projects header displays as expected, check if Project Name header displays as expected, check if Category header displays as expected, check if Active header displays as expected, check if Members, WBS header displays as expected, check if loading elements get displayed when fetched is false, check if AddProject does not get displayed when postProject permission is not added, check if AddProject gets displayed when postProject permission is added, check if modal title is set to error when the modal is not open, check if modal title is not set to error when modal is open 

## How to test:
1. check into current branch
2. do `npm test src/components/Projects/__tests__/Projects.test.js` 
3. check if all the test cases passes without any warnings or errors

## Screenshots or videos of changes:
Screenshot 2024-07-12 at 10 43 08 PM

### CODE REVIEW

**Review by vijay10pk — APPROVED** [review]
All the test cases passed
image

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Review by kdaga81 — APPROVED** [review]
image

All test cases passed!

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all test cases have passed.
Screenshot (78)

**Review by angelalalacheng — APPROVED** [review]
I test your branch and there is no error! 
Screenshot 2024-07-12 at 2 12 48 PM

**Comment by iTvX** [comment]
Good job

PR 2248

**Review by jennZhang93 — APPROVED** [review]
Tested locally and all test passed. Good work!
image

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-07-12 at 8 39 36 PM

**Review by nyelmela — APPROVED** [review]
I have checked out the current branch, executed `npm test src/components/Projects/__tests__/Projects.test.js`, and confirmed that all test cases for the Projects component pass without any warnings or errors. The implementation is verified and meets the required standards.

image

**Review by sahithidhulipala9 — APPROVED** [review]
All test cases passed!
PR 2448

**Review by KaushikMreddy — APPROVED** [review]
Hi, 
I've tested your PR and all the test cases work. Your code looks good as well.
image

**Review by cecilia-uu — APPROVED** [review]
All tests passed.
h2448

**Review by KurtisIvey — APPROVED** [review]
<strong>Everything functions great and has great code coverage.</strong>
</br>
image

</br></br>

<h2>Just tips for future test file improvement</h2>
Just a suggestion for in the future if you're looking to improve upon the structure of your test files. We do have a standard in the app of wrapping the router in the Provider and not the other way around. I'm not sure if there's any impact whatsoever in the test as it all still functions properly. Consider component wrapping the provider and memoryRouter to allow reuse in your various tests. Additionally, you could add the axios.get to the before each as you're utilizing the same response status through all of your tests. These things could reduce the amount of lines in your test file and increase readability since it sticks to DRY principles. Fantastic work regardless. I just didn't want to leave you without anything to help you develop further

image

**Review by jinxyou — APPROVED** [review]
All test cases have passed! Great work! 
Screenshot 2024-07-13 135022

**Review by MinSun0814 — APPROVED** [review]
image


All tests passed, nice work.

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and All test cases passed successfully !!!!

PR-2448

**Review by JatinAgrawal94 — APPROVED** [review]
All test cases work fine. Great Work.
PR 2448

**Comment by one-community** [comment]
Thank you all, merging!

**Comment by nikethaanand** [comment]
All the test cases have been passed successfully and work as expected.
image

**Pull request merged**
