### PR TITLE
Peterson implement the create project feature in the user profile section and in the project tab

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request has been opened to implement create project feature in  the user profile section and in the project tab. 

## Related PRS (if any):
None

## Main changes explained:
The AddProjectPopup, AddTeamsAutoComplete component, and the archive projects.js have been modified to implement the functionality.

## How to test:
1. Check into current branch.
2. Do npm install and ... to run this PR locally.
3. Log in as an administrator or owner.
4. Go to view profile → Project → Assign Project.
5. Select 'Create New Project' from the auto-complete suggestions.
6. Click on the create button and a toast will appear.
7. After the project is automatically selected, click the confirm button to add yourself to the project.

## Screenshots or videos of changes:
Peterson_Implement_the_create_project_feature_in_the_user_profile_section_and_in_the_project_tab

## Note:
The category of project selection dropdown appears for Owners and not for Administrators.

### CODE REVIEW

**Comment by sahithidhulipala9** [comment]
Functionality is working perfectly. Logged in as Admin user, created project from the suggestions, assigned the project, tried assigning already assigned project, tried creating already existing project too. Great work!

Here is the video link: https://www.loom.com/share/4eda1afbe1e945b3848e9136014feae1?sid=60bfb635-673b-47ee-b3ba-519f527cf97b

**Review by sahithidhulipala9 — APPROVED** [review]

**Comment by agryash** [comment]
Verified the functionality. Here's a screenshot of the same.


Screenshot 2024-06-24 at 9 52 20 PM
Screenshot 2024-06-24 at 9 52 20 PM

**Review by agryash — DISMISSED** [review]

**Review by kdaga81 — CHANGES_REQUESTED** [review]
image
I'm getting project creation failed error

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR as admin and able to assign project from Profile section. Great work!

**Review by Jingyii800 — CHANGES_REQUESTED** [review]
I have tested this PR in both admin and owner roles, but unfortunately, I cannot create a new project in profile -> projects -> assign projects. Please refer to my video.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/eac4d384-b531-4389-b9c2-ccf3d26e164e

**Review by Jingyii800 — DISMISSED** [review]
Hi Peterson, it works well now. As an admin/owner, I can create a project on profile page by assigning it.
Screenshot 2024-06-27 233232
Screenshot 2024-06-27 233313
Screenshot 2024-06-27 233307
Screenshot 2024-06-27 233238

**Review by kdaga81 — APPROVED** [review]

**Review by kdaga81 — DISMISSED** [review]
I verified the changes again and they are working as expected!

**Review by tianyangL11 — APPROVED** [review]
I've tested the pr and it can create new project successfully.  Good job!

**Review by nyelmela — DISMISSED** [review]
I tested PR 2385 the changes by checking out the current branch, running `npm install`, and starting the app locally. I logged in as an administrator/owner, navigated to `View Profile → Project → Assign Project`, selected 'Create New Project' from the auto-complete suggestions, and clicked the create button. A toast appeared as expected. After the project was automatically selected, I clicked the confirm button to add myself to the project. Everything worked perfectly fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/7c596012-cebe-4fae-a9da-07fee90e7562

**Review by jinxyou — DISMISSED** [review]
The creating new projects from dropdown list function works as expected. Great work!
Screenshot 2024-07-06 180525
Screenshot 2024-07-06 180535

**Review by vijay10pk — CHANGES_REQUESTED** [review]
Until project creation step everything working fine. But when I search to assign the project it is asking me to create a project again instead of showing up in the result dropdown. Please check and update the logic. Refer the video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/40633436/ebd0d49d-933c-488b-bf03-9e04966518a1

**Review by vijay10pk — APPROVED** [review]
Requested changes are working as expected. Now I am able to see the new project which I created immediately and able to assign it.
Screenshot 2024-07-15 at 1 44 00 PM
Screenshot 2024-07-15 at 1 43 49 PM
Screenshot 2024-07-15 at 1 43 36 PM

**Comment by nikethaanand** [comment]
All the changes are working as expected, after running the application able to assign project and remove projects for a user.

https://github.com/user-attachments/assets/be3d795e-2506-484d-baae-a9665b115449

**Review by JatinAgrawal94 — APPROVED** [review]
Changes work as expected.

https://github.com/user-attachments/assets/9372e41d-4643-41e3-9432-179b8c7da8c5

**Review by Pranay-ai — COMMENTED** [review]
Hey @peterson337 
I tested the PR working as expected


https://github.com/user-attachments/assets/3521e5f3-9d4c-4d89-aa61-4f084cbf5f36

Thank You

**Review by SatyashanthiT — APPROVED** [review]
I have reviewed this PR2385. The create project functionality works correctly, allowing new projects to be added through the user profile section and project tab. The implementation includes modifications to the AddProjectPopup and AddTeamsAutoComplete components, with successful confirmation and toast notifications. Based on the test results and improved functionality, I recommend approving this PR.

Screenshot 2024-08-04 195159
Screenshot 2024-08-04 195242
Screenshot 2024-08-04 195312
Screenshot 2024-08-04 195356

**Comment by Gmon-k** [comment]
I have tested the PR from my side and it is working successfully now

**Review by Abhinav-Ankur786 — APPROVED** [review]
Functionality is working as per PR

PR - #2385

**Review by ziyanw52 — APPROVED** [review]
I have test this PR, and the project can be added successfully.
891728003203_ pic
901728003220_ pic
911728003236_ pic
921728003259_ pic

**Review by AshishNags — APPROVED** [review]
Approving this PR, all functionalities working as expected.

Screenshot 2024-10-10 125553
Screenshot 2024-10-10 125611

**Pull request merged**
