### PR TITLE
EduardoV - create unit tests for the TeamStatusPopup component

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the TeamStatusPopupcomponent to confirm whether it working as intended.

Screenshot_1
 
## Main changes explained:
- Export file TeamStatusPopup.jsx for the test component
- Create file TeamStatusPopup.test.js to do the unit tests

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install` to run this PR locally
4. open file src → tests → Teams → TeamStatusPopup.test.js
5. run `npm run test src/__tests__/Teams/TeamStatusPopup.test.js`

## Screenshots or videos of changes:
This is the result it's supposed to get:

Screenshot_2

If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by Haoj1 — APPROVED** [review]
@eduvarjaor Good job. All tests passed!

**Review by DavidC0126 — APPROVED** [review]
Hi @eduvarjaor I tested your PR and it works as intended.
test_teamStatus

**Review by robertoooc — DISMISSED** [review]
Hi @eduvarjaor, I tested your new. branch and your unit test performed as expected. Found no issues at all. 
Screenshot 2023-09-13 at 6 44 41 PM

**Review by tsunami776 — DISMISSED** [review]
All tests passed and TeamStatusPopup component works as intended.

**Review by dah00 — DISMISSED** [review]
Hey @eduvarjaor, all tests passed. Good job!
PR1298

**Comment by AnishPandita** [comment]
Hi, tested the PR and all the test scenerios ran fine. No errors observed.
Screenshot 2023-09-14 at 12 52 06 PM

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Hey @eduvarjaor, great work on these tests! I do have a suggestion that I think is considered best practice just to make sure we are also checking accessibility. As far as the "Confirm" and the "Close" buttons are considered, instead of using `getByText` would it not be better practice to use `getByRole('button', {name: 'Confirm')`? That way we aren't just checking for the text to be rendered but a button with that text?

Screenshot 2023-09-14 at 3 26 09 PM

**Review by yunshan111 — APPROVED** [review]
Reviewed this PR, and ran the tests. LGTM

image

**Review by Jiyuanxia — DISMISSED** [review]
Hi @eduvarjaor , I have reviewed your pull request and tested it. It works as intended. Well done.
Screenshot 2023-09-14 214954

**Review by iTvX — APPROVED** [review]
I have tested your pr, it looks good!
CleanShot 2023-09-15 at 13 18 08@2x

**Review by Shiwani99 — DISMISSED** [review]
Hi,
Great job. Works as expected.

Screenshot 2023-09-15 at 5 22 24 PM

**Review by liaoyufu-leo — APPROVED** [review]
Hi EduardoV, this change works perfect at my device, nice job!

image

**Comment by Sssky-18** [comment]
Hi @eduvarjaor, just tested this PR, and the code works great. All the test cases are passed.
PR#1298

**Review by Chuehleo — DISMISSED** [review]
Everything works as expected, great job!
Screenshot 2023-09-15 230747

**Review by navneeeth — APPROVED** [review]
Hi, @eduvarjaor! Tested your PR by following the instructions and all the tests pass. The PR works as intended.

**Review by Bhagyashree444 — APPROVED** [review]
All test cases passed!
PR #1298

**Review by gabi-lima — APPROVED** [review]
Great job!
image

**Review by veronicacheng2 — DISMISSED** [review]
Hi @eduvarjaor, I have tested the PR according to instructions and all tests passed. 

image

**Review by TuanDinh140194 — DISMISSED** [review]
Hi! I have reviewed your pull request and tested it. It worked correctly. Thank you
Screenshot 2023-09-16 171714

**Comment by beblicarl** [comment]
This test passed!

image

**Review by beblicarl — DISMISSED** [review]

**Comment by eduvarjaor** [comment]
> Hey @eduvarjaor, great work on these tests! I do have a suggestion that I think is considered best practice just to make sure we are also checking accessibility. As far as the "Confirm" and the "Close" buttons are considered, instead of using `getByText` would it not be better practice to use `getByRole('button', {name: 'Confirm')`? That way we aren't just checking for the text to be rendered but a button with that text?
> 
> Screenshot 2023-09-14 at 3 26 09 PM

Hi @GaryB93,

Good suggestion. I added it. Please, recheck the code to confirm if everything working as intended.

Thanks for the review.

**Review by GaryB93 — APPROVED** [review]
Great work @eduvarjaor! Glad to see these changes, even if they were minor suggestions. All tests pass!

**Pull request merged**
