### PR TITLE
Hiral taking over for John - Weekly summary report page efficiency improvement

### PR DESCRIPTION
**Pull request by Cavein254**
# Description

Screenshot 2024-03-02 113230

## Main changes explained:
- Enhance the efficiency of the weekly summary page by improving its loading speed. 
- Implement pagination and include an option to change the number of records displayed per page.

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin user
5. Dashboard -> Report -> Weekly Summaries Report 
6. Check for the pagination on that page. 
7. Test pagination with different numbers of records on the page. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66827672/afa0253f-6a3d-43e4-8a73-623ece33d553

Default_Pagination

Items_Per_Page

### CODE REVIEW

**Comment by nnamdixobi** [comment]
ttttt
If this is what you are referring to it looks okay, how ever I did not see anywhere where uploading new files or changing files could be done

**Review by YHX6 — DISMISSED** [review]
Hi, I changed the page number and the items on the page are changed correctly.
Page 1: 
Screenshot 2024-03-09 at 3 30 39 PM
page 5:
Screenshot 2024-03-09 at 3 30 50 PM

**Review by psharma1984 — DISMISSED** [review]
Hi @Cavein254 I reviewed the PR and it displays the pagination feature and the links work
a
b

**Comment by sameersdeshpande** [comment]
Hi @Cavein254 
I have reviewed this PR as per the above instructions. This feature worked fine and the items in the page are changing as expected. Small thing I want to highlight is,  when the current page number is selected, it highlights the current number with blue box where as the number is again printed in between the pagination sequence.
Like if I click on 5, its 5 in between ....5...... and other numbers.
Can that be avoided of repeating the clicked number as its already highlighted with blue.
Screenshot 2024-03-12 at 3 16 37 AM
Screenshot 2024-03-12 at 3 15 48 AM
Screenshot 2024-03-12 at 3 15 41 AM

**Review by sameersdeshpande — CHANGES_REQUESTED** [review]
Hi @Cavein254
I have reviewed this PR as per the above instructions. This feature worked fine and the items in the page are changing as expected. Small thing I want to highlight is, when the current page number is selected, it highlights the current number with blue box where as the number is again printed in between the pagination sequence.
Like if I click on 5, its 5 in between ....5...... and other numbers.
Can that be avoided of repeating the clicked number as its already highlighted with blue.
Screenshot 2024-03-12 at 3 16 37 AM
Screenshot 2024-03-12 at 3 15 48 AM
Screenshot 2024-03-12 at 3 15 41 AM

**Review by hetvi11110 — COMMENTED** [review]
I tested your code as mentioned, and it is working fine. However, I have two suggestions.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/00d82e6b-0503-4669-9576-067babc5f13f

Firstly, in the pagination, I noticed that the last page is representing the first page. The number of pages shown in pagination is one more than the actual total number of pages. You can see this in my reference video, and I made a minor change in the code to resolve this. I have attached a screenshot for reference.
PR 2016-1


Secondly, the current page and the three dots (...) are clickable. I believe they shouldn't be clickable, as they add "#" at the end of the URL after being clicked. This issue is also visible in my reference video. I made a minor update in the coding file to resolve this. I have attached a screenshot for that as well.
PR 2016-2

**Review by Abi-Liu — CHANGES_REQUESTED** [review]
The pagination works as expected, but I do have a few suggestions to improve the user experience. Like other people mentioned, it does look slightly weird having the current page number in between the `...` buttons, but I can understand because if a user is inbetween pages 5 and 115, then they wont know what page they are on otherwise.

However, I feel that we can maybe move the pagination along with the current page the user is on. For example, if the user is on page 10, we could have the pagination look something like: `1 ... 8, 9, 10, 11, 12 ... last page`. 

It would also be helpful to have an input to allow users to jump to whichever page they want to, this way they dont have to manually click through to get to page 100.

Here is a picture for reference:
image

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/945103f8-df0d-4b81-954c-a29bc7142c8d

**Review by Gugor99 — COMMENTED** [review]
### Report
Hi John,
I reviewed your implementation and as mentioned from others there's a confusing bug with the pages numeration at the bottom. The active page's number reappears among the numbers. Except for that, the page was working fine and smoothly. Please see screenshots for reference

### Screenshots
Cattura5
Cattura6

**Review by SanketKaware — CHANGES_REQUESTED** [review]
**Issues:**
1. Pagination buttons are not center-aligned, affecting visual consistency.
 
2. Negative page numbers are displayed, and clicking the left arrow allows navigation below page 1, which is unexpected behavior.

**Current:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/061625a9-28c3-41e1-ab97-de56ab38d106



**Suggestions:**
1. Center Alignment:
Center-align pagination buttons provide a better user experience.
 
2. Negative Page Numbers:
Ensure that "0" and "negative" page numbers are not displayed and clicking the left arrow doesn't navigate below page 1 to maintain expected pagination behavior.

**Expected:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/d69ca4d0-9613-46a8-966d-f0fbdd281325

**Review by SRamen1999 — COMMENTED** [review]
After reviewing your PR everything works as expected. The only issue is there is a bug where he active page's number reappears among the numbers. 

here is an example of the bug you can see the number 3 reappear
Screen Shot 2024-03-15 at 4 44 23 PM


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/ae37068d-20e1-4011-82ba-205c9055498a

**Comment by rajnada** [comment]
Hi,

I have followed all the steps, and pagination is working. However, the only issue I can see is that it shouldn't display "0" or negative numbers. We can fix this by disabling the left arrow functionality, similar to when we click on the last page, i.e., 120 in our case. This number isn't reflected in the center of the pagination, unlike the other numbers that appear in the center.



Negative Number Displayed :
negative

Incorrect center number while we click on last page
center

**Review by SanketKaware — DISMISSED** [review]

**Comment by SanketKaware** [comment]
> **Issues:**
> 
> 1. Pagination buttons are not center-aligned, affecting visual consistency.
> 2. Negative page numbers are displayed, and clicking the left arrow allows navigation below page 1, which is unexpected behavior.
> 
> **Current:**
> 
>  Screen.Recording.2024-03-15.at.3.02.27.PM.mov 
> **Suggestions:**
> 
> 1. Center Alignment:
>    Center-align pagination buttons provide a better user experience.
> 2. Negative Page Numbers:
>    Ensure that "0" and "negative" page numbers are not displayed and clicking the left arrow doesn't navigate below page 1 to maintain expected pagination behavior.
> 
> **Expected:**
> 
>  Screen.Recording.2024-03-15.at.2.03.45.PM.mov

@Cavein254 I rechecked it. Now it's working as expected.

Approved.

Here is my today's review video for reference - 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/3c2203f7-b8cb-430f-a85e-474796f374bf

**Review by one-community — CHANGES_REQUESTED** [review]
Sorry, improvements for this must NOT include pagination or lazy loading. I need to see all members on these pages so I can use the browser "find" function on them.

**Comment by anandsesha** [comment]
Logged in as admin user to test pagination functionality to confirm feature operates as expected.

Addressed Previous Error Cases:
- Pagination displays correct page numbers.
- Improved usability with two numbers—one higher and one lower—alongside an ellipsis.
- Tested compatibility with team and color input.
- Ensured absence of negative or zero-numbered pages.

PR 2016 - alignment
PR 2016 - Page number
PR 2016 - Teams and color

Overall, pagination functions as expected.

**Comment by one-community** [comment]
Closing this because improvements made with Pagination. Improvements must not include pagination or lazy loading. All members must be visible so the browser find function can be used on this page. So looking only for improvements that can be made with refactoring or other methods.

**Pull request closed without merging**
