### PR TITLE
Nahiyan dark mode for user profile page

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Implemented dark mode for user profile

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Dark mode all of user profile including mobile view

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard→ User Profile
6. verify dark mode is properly working throughout the whole  page including mobile view

## Screenshots or videos of changes:
Screenshot 2024-04-15 141037

### CODE REVIEW

**Comment by alla0810** [comment]
dark mode works good in both desktop and mobile view


image
image

**Review by linkhanthtel — DISMISSED** [review]
Looks good! Dark Mode is working properly.

#2162 (Mobile)

**Review by Pandani07 — DISMISSED** [review]
Dark more for user profile page is working as expected. I can change it back to light mode as well, everything works great
Good job!
Screenshot 2024-04-16 at 10 10 06 PM

**Review by SRamen1999 — DISMISSED** [review]
Everything works as expected. Dark mode works in both desktop and mobile views.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/9c201dae-352c-45e4-b18f-d040d9e1517a

**Review by aaryaneil — DISMISSED** [review]
Tested your PR and the dark mode functionality works as expected for the profile page, good work.
Screenshot 2024-04-19 at 10 33 59 PM
Screenshot 2024-04-19 at 10 34 03 PM

**Review by Tiantian-C — COMMENTED** [review]
I have tested this PR review, and it works very well!
Screenshot 2024-04-20 at 3 41 14 PM

**Pull request merged**
