### PR TITLE
Jay unit tests for SameFolderTasks component

### PR DESCRIPTION
**Pull request by jayyy-s**
# Description
Implements unit tests for `src/components/Projects/WBS/SameFolderTasks/SameFolderTasks.js`

## Related PRS (if any):
No related backend PR, just use latest development branch

## Main changes explained:
- Add `src/components/Projects/WBS/SameFolderTasks/SameFolderTasks.js` to implement unit tests
- Update `src/components/Projects/WBS/SameFolderTasks/SameFolderTasks.js` to change projectId and wbsName in a useEffect and prevent memory leaks
- Tests do the following:'
  - Check that the no table renders work correctly
  - Check that the table render occurs
  - Check that the loading state happens
  - Check that when loading with tasks, they show up

## How to test:
1. check into current branch
2. run npm test -- SameFolderTasks.test.js
3. verify that all tests pass and accomplish 100% code coverage

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (135)

**Review by aaryaneil — APPROVED** [review]
Reviewed the PR and all the test cases passed.
Good work!!
Screenshot 2024-07-19 at 1 52 26 PM

**Comment by iTvX** [comment]
Please fix Node.js CI / build (14.x) (pull_request) 

2024-07-20 at 09 18 44@2x

**Review by gowthamdongari — APPROVED** [review]
All tests worked as expectd!
image

**Review by Chetan0606 — APPROVED** [review]
I have followed the steps in the instructions and everything seems to be good. Please find the screenshot below of my observations

image

**Review by Gauravmg6 — APPROVED** [review]
Screenshot 2024-07-22 155836

I ran the test and everything seems to be working fine.

**Review by SatyashanthiT — APPROVED** [review]
I have tested this PR by checking out the current branch and running the unit tests. All tests passed successfully, verifying the correct rendering of the table, no table state, loading state, and task display. 

image

**Comment by Gmon-k** [comment]
All the test has cases has passed for it

**Review by preethamdnr — APPROVED** [review]
Hello Jay,
All the tests are passed.
image

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
