### PR TITLE
Oleksandr leaderboard refresh animation

### PR DESCRIPTION
**Pull request by xaanders**
# Description
(PRIORITY LOW) Jae: Create indicator leaderboard refresh worked 
Right now when I click the little refresh icon, I don’t know it worked unless I scroll down and notice changes. I’d like some indicator without scrolling that the refresh happened.

## Main changes explained:
- Adding a loading state
- Adding a function that changes loading state, triggers a getLeaderboardData request and makes notification
- Adding animation class to icon when isLoading true
- Adding css animation to Leaderboard.css 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. open incognito browser page and login as any other user
5. submit some time entry
6. go back to admin user and find the user which you submitted hours in
7. check previous number and number after updating

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/e222eb0c-c084-4f3d-81b8-1387254839ef

### CODE REVIEW

**Review by veronicacheng2 — APPROVED** [review]
Hi @xaanders, I have tested the PR and the leaderboard refresh animation works perfectly. 

[Leaderboard Refresh.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/824a481b-0a37-4dde-967e-9d65b095dc2a)

**Review by DavidC0126 — APPROVED** [review]
Hi @xaanders I tested your PR and it looks good to me!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/4202032e-5c8d-416f-a289-89141b033bd8

**Review by tsunami776 — APPROVED** [review]
Tested by adding tangible hours to a volunteer account. The leaderboard refreshes with correct data and the animation worked as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/647e8d9d-2fb8-4100-b747-a929fa90b635

**Review by yunshan111 — APPROVED** [review]
Tested this PR, LGTM.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/1177afa7-8db8-4d2d-b1ed-ea579fa62aa3

**Review by Haoj1 — APPROVED** [review]
Hi @xaanders, I have tested the loading state and the refresh animation, both look good to me!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/50c3d1d0-73ec-4144-8679-dfb3577845b6

**Review by yurisokolovicz — APPROVED** [review]
Dear @xaanders 

The leaderboard refresh animation is working correctly. Good job! Please refer to the video proof below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/d0876fdf-c23c-444c-88cd-30945d08352f

**Review by belagaam — APPROVED** [review]
Tested the PR as per the instruction. Everything works as expected. 

https://www.dropbox.com/scl/fi/srxbp6skc0p9c2tuerp5o/1155-Oleksandr_leaderboard_update.mov?rlkey=bpwhlqsnpv3m6di2ljn8cbpv7&dl=0

**Review by ramyaram2092 — APPROVED** [review]
The PR works as expected . Good Job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/7f588234-3a96-4639-a06d-f31a0a4de1c5

**Review by BaileyM96 — APPROVED** [review]
Hello @xaanders I tested the new leaderboard change and everything seems to work as described.

[Leaderboard refresh message PR #1155.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/ba5c8b09-f724-473a-8bdb-c19258fd5a54)

**Comment by BaileyM96** [comment]
@one-community This has 7 approvals now and works great

**Comment by one-community** [comment]
Thank you, merging!

**Pull request merged**
