### PR TITLE
chris fix show total project/people/team reports

### PR DESCRIPTION
**Pull request by chrischenlixing**
# Description
Fix Show Total Project/People/Team reports (Priority High)
Reports →Reports → Projects/People/Teams→ Select last year as dates→ Click buttons and you’ll get a spinning wheel instead of the reports
The issue I identified is because the backend API we called calculates too much unnecessary data which slows down the API information retrieval and data transfer to the frontend. I optimized the API by creating a new API to match exactly what is necessary for rendering the report, which increased the API speed by 150%, avoiding the timeout of the API call, and therefore resolving the bug of the reports not rendering.

## Related PRS:
This frontend PR is related to the [#955](https://github.com/OneCommunityGlobal/HGNRest/pull/955) backend PR.

## Main changes explained:
- Changed the url call to calling the new api time_entries_report for the api call function loadTimeEntriesForPeriod in TotalPeopleReport, TotalProjectReport, and TotalTeamReport.
- Added more error handling for matched user to avoid the case the matched user is null.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Reports →Reports → Projects/People/Teams
6. Click on ‘Show Total Project Report’, ‘Show Total People Report’, and ‘Show Total Team Report’ one by one to check if they render correctly
7. Change the end date to last year or any date you would want to test, wait for a few seconds to see if the report stats change based on the new date

## Screenshots or videos of changes:
Before the pr, select last year as dates and click buttons and you’ll get spinning wheel instead of the reports
Screenshot 2024-05-18 at 9 55 44 PM

After the pr, all three reports are being retrieved 
Screenshot 2024-05-18 at 10 33 49 PM
Screenshot 2024-05-18 at 10 34 15 PM
Screenshot 2024-05-18 at 10 34 51 PM

The reports will be updated when the start date/end date is changed automatically without refreshing
Screenshot 2024-05-18 at 10 35 24 PM

## Note:
Since the report contains a large number of data, please wait for 5-10 with a spinning wheel for each report to render. Also, when you change the start/end date, wait for 3-5 seconds before the new graph is rendered.
Since there are more than a thousand people, iit takes a few seconds for the People data to show up on the page, which is longer than Teams and Project, if you click on People Report before the People data is retrieved, you will get a 0, so wait until the people data is retrieved to click on the people report.

### CODE REVIEW

**Review by hbodgal — APPROVED** [review]
image

Chart changes based on Date. it takes some time.

**Review by linkhanthtel — APPROVED** [review]
I reviewed your PR and the report stats changed based on date. Nice work!

**Comment by peter6866** [comment]
Great job on optimizing the api fetch time. I have reviewed the PR and the data loads faster for each of the reports. The stats and the chart also change accordingly to the date. 
image
image

**Review by peter6866 — APPROVED** [review]
Great job on optimizing the api fetch time. I have reviewed the PR and the data loads faster for each of the reports. The stats and the chart also change accordingly to the date.
image
image

**Pull request merged**
