### PR TITLE
Bug fix in handleSort() function, lint checked

### PR DESCRIPTION
**Pull request by ChengyanOo**
# Description
A logical inconsistency was identified in the ReusablesTable.jsx component by @TareqMia, leading to a similar discovery in the ConsumablesTable.jsx. This PR addresses a sorting issue where data was incorrectly sorted based on the entire dataset rather than the intended specific criteria. For background, see our discussion in [HighestGoodNetworkApp_PR#1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956). 

## Related PRS (if any):
[HighestGoodNetworkApp_PR#1956](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1956)

## Main changes explained:
- Refined and optimized the handleSort() function to eliminate redundant logic in ConsumablesTable.jsx, streamlining the component's efficiency.

## How to test:
1. Check out the latest backend branch and start the server.
2. Check out the current branch.
3. Execute `npm install` and `npm run start:local` to run this PR locally.
4. Clear site data/cache.
5. Log in as an admin user.
6. Navigate to the BM Dashboard → Consumables → Manual test at [http://localhost:3000/bmdashboard/consumables](http://localhost:3000/bmdashboard/consumables).
7. Review the code for potential code smells.

## Screenshots or videos of changes:
https://www.loom.com/share/8641cd56defa49ec8070d61c801f9c23?sid=1f3967f1-6e39-40ea-bac4-7ac4799e12e0

### CODE REVIEW

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR and everything works as intended. I was able to sort the items lexicographically when the project filter was applied as well as when the project filter was set to all projects. Please refer the attached video.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/de098d9b-ca56-41a4-a773-ea89da56d05e

**Comment by dhairya-mehta** [comment]
Hey, I verified the PR and tested all the filters and sorting functionalities
image

**Review by swathyjayaseelan — APPROVED** [review]
The changes look good. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/e52239ca-facf-47a3-88a0-f9457d9c1113

**Review by FyisFe — CHANGES_REQUESTED** [review]
I tested it following your instructions and found the bug below:

Step 1: Select a `Consumable`
image

Step 2: Click Sort icon

image

Then it overwrites the selection

**Comment by ChengyanOo** [comment]
> I tested it following your instructions and found the bug below:
> 
> 
> 
> Step 1: Select a `Consumable`
> 
> image
> 
> 
> 
> Step 2: Click Sort icon
> 
> 
> 
> image
> 
> 
> 
> Then it overwrites the selection
> 
> 

@FyisFe Thank you! I'll take a look and fix it asap, feel free to check back on this pr one or day days later to review it again!

**Pull request closed without merging**
