### PR TITLE
Nahiyan_Added a "Edit Tasks" button to reduce the number of requests

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Added this button because before on-page initialization, the app would have to make too many unnecessary requests to the backend. Now when the users want to edit tasks, they may click the new button which will then make all the requests to the backend needed.

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
-Added a "Edit tasks" button
-Should be disabled on page load
-When clicked should allow the user to edit tasks

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ reports→ Projects -> any project
6. verify that edit tasks button is there
7. verify that edit button is hidden for each task
8. verify that when clicking on edit tasks button, it enables the edit button next to each tasks
9. look at network tab to see if requests are being made after clicking on edit tasks button

## Screenshots or videos of changes:

Before clicking "Edit Tasks" button
Screenshot 2024-03-01 180758

After clicking "Edit Tasks" button
Screenshot 2024-03-01 180829

### CODE REVIEW

**Review by MALAV1308 — CHANGES_REQUESTED** [review]
Hello , I reviewed your PR and I can not able to see tasks in task menu and got some warnings. Please look into it and solve it. 
image

**Review by abdel-lall — CHANGES_REQUESTED** [review]
This PR has console errors and unnecessary logs.
Screenshot 2024-03-02 225922

**Comment by Nahiyan-16** [comment]
> This PR has console errors and unnecessary logs. Screenshot 2024-03-02 225922

@abdel-lall @MALAV1308 Thanks for the reviews and I have fixed the console log errors.
Screenshot 2024-03-04 123151

**Review by meetpadhiar4 — CHANGES_REQUESTED** [review]
Hi, I tested your PR and have encountered few issues. The tasks are not loading on the project info page and when I click the edit task button, no requests are being sent to the server. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/6936357e-e9ae-4c02-93ac-2b9611e45998

**Review by Pandani07 — CHANGES_REQUESTED** [review]
Im not able to see the tasks and clicking on edit tasks sends no request to the network


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/4b8ee67d-a2b4-4be9-9adf-1b328e55eba4

**Comment by dhairya-mehta** [comment]
Hey, I observed no changes after clicking on Edit tasks
image

**Review by iven-yao — CHANGES_REQUESTED** [review]
I just reviewed this pull request
I logged in as an owner role, go to a project reports from Reports->Projects.
- [x] there's an Edit Tasks button
- [ ] Edit button of each task is disabled  --> **Not disabled but hidden**
- [x] after clicking  `Edit Tasks`, making more request and show the edit button for each task

please make sure if we need task button for each task being hidden or disabled before clicking edit tasks button.
image
image

**Comment by Nahiyan-16** [comment]
> I just reviewed this pull request I logged in as an owner role, go to a project reports from Reports->Projects.
> 
> * [x]  there's an Edit Tasks button
> * [ ]  Edit button of each task is disabled  --> **Not disabled but hidden**
> * [x]  after clicking  `Edit Tasks`, making more request and show the edit button for each task
> 
> please make sure if we need task button for each task being hidden or disabled before clicking edit tasks button. image image

Yes, the `Edit Tasks` button should be hidden. The implementation was correct but the description was not.

**Review by iven-yao — DISMISSED** [review]
after clarifying the request, I approve this change according to [previous review](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2013#pullrequestreview-1970077249)

**Comment by Gayathr-2012** [comment]
I just followed this steps it works perfect as expected.
I logged in as an owner role, go to a project reports from Reports->Projects.

 there's an Edit Tasks button
 Edit button of each task is disabled --> Not disabled but hidden
 after clicking Edit Tasks, making more request and show the edit button for each task
please make sure if we need task button for each task being hidden or disabled before clicking edit tasks button.

image

image

image

image

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reviewed your PR and it is working as intended.

**Review by kylepham — DISMISSED** [review]
PR worked as described. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/e819882b-de0d-439e-a025-2bcec3ae6de2

**Review by Tiantian-C — COMMENTED** [review]
There are some errors.
Screenshot 2024-04-03 at 11 43 42 PM

**Review by Tiantian-C — COMMENTED** [review]
The function works,while it has some unexpected errors in the console.
Screenshot 2024-04-03 at 11 51 30 PM

**Review by SRamen1999 — COMMENTED** [review]
Requests are being made after clicking on edit tasks button. However I am also getting an error in the console.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/85c20602-9370-4f7d-8f13-e91b789d92db

This is the error
Screen Shot 2024-04-05 at 11 25 05 AM

**Review by anandsesha — DISMISSED** [review]
Hi, I've reviewed your PR and the changes work as expected. 
- Logged in as Owner user, verified the Edit Task button is there and each Edit button is hidden, which is only enabled on clicking Edit Task.
- Verified Networks tab to see requests made when Edit Task is clicked

Screenshot (753)
Screenshot (754)
Screenshot (755)

**Review by aaryaneil — DISMISSED** [review]
I have reviewed this PR and the changes work as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/9b2b27f9-821d-4a75-862d-94cfb02e0d4f

**Review by jennZhang93 — DISMISSED** [review]
Tested with the owner account and all features described in the PR worked. Good job!

Screenshot 2024-04-17 at 9 13 53 PMScreenshot 2024-04-17 at 9 13 58 PM

**Review by cgomezhub — DISMISSED** [review]
The functionality is working, well done!.
the UI needs general improvements

https://www.loom.com/share/cebfd39908934a7d9196f89d365d2180?sid=c0e9e4f4-c524-427a-8116-da762663a033

**Comment by ZhangPeizhou** [comment]
PR#2013
The code works as expected

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
Edit Sign is visible and is working.
Console has an error: "Warning: validateDOMNesting(...): <div> cannot appear as a child of <tr>."
At some page sizes the headings in task table overlap with each other.
Number of requests do not increase to a large number on clicking edit button.
Rest everything works fine.
Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/43590946-2213-44ec-9e03-a1b07417d112

**Review by JatinAgrawal94 — DISMISSED** [review]

**Review by akshit0211 — CHANGES_REQUESTED** [review]
Hi, the functionality is working as expected but there are some warnings in the console. Please look into this.

edit tasks
edit button
warnings

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
