### PR TITLE
Changhao - Unit tests for userSearchPanel

### PR DESCRIPTION
**Pull request by lichanghaogit**
# Description
added new unit tests for userSearchPanel.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm test UserSearchPanel.test.js` to run this PR locally
3. verify all 12 tests passed

## Screenshot:
Screenshot 2023-12-08 at 8 24 45 PM

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!

Screenshot 2023-12-09 at 12 14 10 AM

**Review by Hemsharavanan — DISMISSED** [review]
- Overall, your test suite for the UserSearchPanel component looks comprehensive and well-structured. 
- It covers both the structural rendering aspects and various behavioral scenarios.
- All 12 tests have passed. Good work!
PR #1668 Unit tests for userSearchPanel

**Review by sucheta90 — DISMISSED** [review]
All tests were successfully completed as anticipated.
Screenshot 2023-12-09 at 12 07 16 PM

**Review by ZichanYang324 — APPROVED** [review]
Great job! The unit tests are passing, which is a good sign.

Here is the image of the result as a reference.
Screenshot 2023-12-09 at 15 55 01

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed without any warnings or errors. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/d0c74820-4a35-4de5-a22a-adbfb995c051

**Review by pika-chu11 — DISMISSED** [review]
Hi @Changhao3220K , all tests are passed! Great job!
PR 1668

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-09 at 2 54 05 PM
Hi @Changhao3220K , all the test cases passed, good job!

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-10 at 12 58 32 AM

**Review by Alforoan — DISMISSED** [review]
All passed. Nice!

image

**Review by vikrambadhan — DISMISSED** [review]
Hi, Great Job! I tested your PR and all the test cases passed!

Week 16 - PR5

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-18 at 10 31 57 PM
All tests have passed successfully. Excellent job!

**Review by scoopstroop92 — CHANGES_REQUESTED** [review]
Great job on the test cases . Very detailed and structured. 
Kindly address the following two suggestions when you get some time 
1. Kindly remove Unused imports 
image
2. Move the unit test cases to the path as suggested in the unit-testing channel in slack

**Comment by KurtisIvey** [comment]
Looks like it's almost there. Great job. Once those changes Ramyaram2092 mentioned are addressed, I'd like to go ahead and move this to final review and merge.

**Comment by Changhao3220K** [comment]
> Great job on the test cases . Very detailed and structured. Kindly address the following two suggestions when you get some time
> 
> 1. Kindly remove Unused imports
>    image
> 2. Move the unit test cases to the path as suggested in the unit-testing channel in slack

Hi @ramyaram2092,
Thank you very much for your advice, I have modified the file location and imports.

**Comment by Changhao3220K** [comment]
> Looks like it's almost there. Great job. Once those changes Ramyaram2092 mentioned are addressed, I'd like to go ahead and move this to final review and merge.

Hi @KurtisIvey,
Thank you very much for checking in, all changes are done now!

**Review by scoopstroop92 — APPROVED** [review]
Looks good . Good job @Changhao3220K  . Approving the PR on the same note

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
