### PR TITLE
Hoang fix viewing other dashboard

### PR DESCRIPTION
**Pull request by kylepham**
# Description
Screenshot 2024-05-16 at 4 02 56 PM

[Video](https://drive.google.com/file/d/1ceJH_zhxNswWvk4Qxa_-05rpBOBi79_l/view?usp=sharing) of Weekly Summary  Report issue

## Related PRS (if any):
This frontend PR is related to the https://github.com/OneCommunityGlobal/HGNRest/pull/949 backend PR.
…

## Main changes explained:
- Update websocket contract to send JSON message.
- Implement new `GET_TIMER` websocket contract to get other person's timer data.
- Add owner/admin-only interaction to timer component, lower roles like Volunteer/Manager cannot interact with other's timer.
- Allow owner/admin to submit time entry on behalf of others.
- Fix fetching weekly summary data on changing dashboard view (see video in the description for reference).

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. All videos below show an Admin role account on the left and a Volunteer role account on the right. Verify that:
  - 5.1. Admin role can interact with the Volunteer role's timer. They can add/remove time, start/pause, and reset timer in real time.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/873f639a-ef56-4f5c-a538-8cdeec69598a

  - 5.2. Volunteer role cannot interact with the Admin role's timer. All timer's buttons are disabled.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/fd4edb18-ac1c-4787-84ab-86720c011cef

  - 5.3. Admin role's nav items on the right should reflect what lower role sees, with limited permissions to access different routes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/5915089a-5733-4215-afe3-e17dcbd24825

  - 5.4. Volunteer role's nav items on the right should reflect what lower role sees, with limited permissions to access different routes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/fa4922df-43a4-41a9-98e8-68f464336678

  - 5.5. Admin role's nav items on the right should reflect what higher role sees, with every permissions to access different routes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/7b4fb1ef-4dfd-414f-8b49-e09f582d0baa

  - 5.6. Admin role can submit time entry on behalf of other user.
 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/e9967bd6-4182-4c30-9d1f-51b79f25a78d

  - 5.7. Fetching weekly summary data on changing dashboard view properly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/49472b31-1c45-4e27-a706-db02dde1a7c2

## Note:
There is a limit that if user A is viewing user B's dashboard, B's interaction with their timer doesn't reflect to A in real-time, but A's interaction with B's timer will be real-time interaction.

### CODE REVIEW

**Review by TXMO-dev — APPROVED** [review]
Fix viewing other dashboard, works appropriately. Approved!

**Review by jinxyou — DISMISSED** [review]
I opened the dashboard of a specific user and monitor the user's dashboard in a separate window. The function works fine. Great work!
Screenshot 2024-06-15 175736

**Review by Sudershhh — DISMISSED** [review]
Hi Hoang,

I am able to update the timer for the volunteer account from my owner account in real time. The changes are immediately reflected but not the other way around.

PR 2257 + 949

**Review by suaniii — DISMISSED** [review]
I have tested the changes, and they work as expected. As an admin, I verified that the Admin role can interact with the Volunteer role's timer, allowing me to add/remove time, start/pause, and reset the timer in real time. Additionally, I confirmed that the Volunteer role cannot interact with the Admin role's timer, as all timer buttons are disabled for them.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113208952/8f3129a1-2365-47b9-a21f-c2d005d5c78f

**Review by shradac — DISMISSED** [review]
I have verified that an Admin role account can interact with a Volunteer role account's timer. The Admin can start/pause, and reset the Volunteer's timer in real time. Volunteer cannot start/pause Admin's timer. Good job!

Screenshot 2024-06-22 at 3 20 05 PM

**Review by DiyaWadhwani — DISMISSED** [review]
Hey Hoang,
Tested out these changes as per your instructions. 
I have logged into the owner account and can add/edit time, the description and have access to make the time tangible or not. I can also start/pause/stop/restart the timer for a volunteer role. I can view the summary and edit it as well. All of these are updated in the volunteer view. 
Logging into the volunteer account, I can only view the owner/admin account dashboard. I'm unable to view the 'Other Links' nav (as it is supposed to be) and all timer options/buttons for the owner are disabled. 

However, there is a bug I did notice while testing that can probably considered to be a separate task. The volunteer has access to edit their summary but the edit is unsuccessful. I have added this to the bugs document. 

Meanwhile, the changes implemented on this PR as per the requirement is working completely fine and as expected. I have added a video testing of this below.
Great work. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/2bfcada6-9b9b-4604-b63f-a51601051b51

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR with admin both left and volunteer on the right. Everything works as expected.
Screenshot (59)
Screenshot (60)
Screenshot (61)
Screenshot (63)
Screenshot (64)
Screenshot (65)
Screenshot (66)
Screenshot (67)
Screenshot (68)

**Review by AnujVakil — DISMISSED** [review]
I have tested this PR and working correctly
PR #2257_1

**Pull request merged**
