### PR TITLE
TuanDinh_TeamReportCharts_Unit_Test

### PR DESCRIPTION
**Pull request by TuanDinh140194**
Create unit test for TeamReportCharts.jsx component.

# Description
Create unit test for TeamReportCharts.jsx component.

## Main changes explained:
- Add new file TeamReportCharts.test.js
- In TeamReportCharts.test.js, i added 7 test case to test the TeamReportCharts.jsx component.
- Test if the component rendered successfully and resulted in a single root element in the DOM, Test if the component render correct props such as title, pieChartId, teamWeeklyCommittedHours, and totalTeamWeeklyWorkedHours. Test if the component renders all 3 pie charts. I also test if they renders correct CSS style.
…

## How to test:
1. check into current branch
2. do `npm install` 
3. do npm test TeamReportCharts.test.js to run the test
4. Verify that all 7 tests have passed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/fd98fb91-4222-48bf-8c4f-144c2efae751

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great work! 

Screenshot 2023-11-12 at 2 27 48 AM

**Review by wantingxu7 — APPROVED** [review]
I ran the test and got PASS message as below, nice work.

**Comment by beblicarl** [comment]
All tests passed and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

week 12 - PR 2

**Review by Sssky-18 — APPROVED** [review]
Hi @TuanDinh140194 , I have tested this PR, and all 7 tests are passed properly. Great work! 

PR#1528

**Review by DavidC0126 — COMMENTED** [review]
Hi I just tested the PR and it works as intended.

teamReport

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-11-16 044325

**Review by pika-chu11 — APPROVED** [review]
Hi @TuanDinh140194 , all tests are passed! Great job!
PR 1528

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions. All tests passed. Your code also looks good to me.
Screenshot 2023-11-19 at 12 05 30 AM

**Pull request merged**
