### PR TITLE
 Kaikanes drag and drop remake branch

### PR DESCRIPTION
**Pull request by lacnoskillz**
# Description
Added Drag and Drop feature to my lesson from design
turns out file inputs on mobile automatically have take photo options
(remake with git attribute changes)

## Related PRS (if any):
Added feature to Front end PR
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1477

## Main changes explained:
- added the ability to drag and drop

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as anyone
4. go to  http://localhost:3000/bmdashboard/lessonform
5. verify drag and drop functionality works in various view ports and scenarios
6. verify take photo option
7. go to https://hgnapplication_react_beta.surge.sh/bmdashboard/lessonform on your phone/tablet
8. Now when you click on the file drag and drop area you should see options to Take Photo or video/ photo library etc.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/009342a7-9157-466f-9d28-0b1bfba1ca0f

3y0ynczp

## Note:
This is a remake branch without gitattributes errors
Old branch
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1502

### CODE REVIEW

**Review by ramyaram2092 — COMMENTED** [review]
Hello @kaikanes good job on the functionality 

-  I was able to test it  successfully in laptop

I used my ipv4 address  like you mentioned to access the app .
image
 You can  see that in the  following  video 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/4d300c0f-f4d3-4120-9ffa-8d76924f9b82



- However In both Ipad/iphone i couldnt test the functionality. Could you point me to  the possible reason this may be happening?
1577-mobile

**Comment by ptrpengdev** [comment]
Hi @lacnoskillz, I was able to select files through File Explorer and drag and drop files in "http://localhost:3000/bmdashboard/lessonform". The feature functions as expected with the PC's browser.

However, I was not able to connect to the app through my phone. I copied the ip from ipconfig, replaced the .env file, and turned off the system firewall. Is there another alternative approach to connect to the ip and port through the phone? Thank you！

**Comment by lacnoskillz** [comment]
hey @ptrpengdev
I would try with firewall disabled it may be blocking your device from connecting.
Also make sure both devices are connected to the same network.

**Comment by lacnoskillz** [comment]
hello @ptrpengdev 
are both devices are connected to the same network?
I would disable data on phone/tablet and only use the wifi/network your hosted computer is using

**Comment by ptrpengdev** [comment]
> hello @ptrpengdev are both devices are connected to the same network? I would disable data on phone/tablet and only use the wifi/network your hosted computer is using

Hi @lacnoskillz , both devices are connected to the same network. I ran the app on my PC and disabled the PC's firewall, but I still failed to connect when attempting both the phone and laptop connections to the PC. I will try to troubleshoot the issue. Thanks!

**Comment by lacnoskillz** [comment]
@ptrpengdev 
I would double check the IP addresses in the .env and what it says in your ipconfig
then restarting both back/front end once you add the changes
other than that im not sure how else to test on mobile without deploying the changes

**Review by cvtqx — COMMENTED** [review]
Hi @lacnoskillz , the drag and drop works and looks great! 

Testing on PC:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/b4453b19-7ca7-4086-a414-5dc7eeb86664

I tested on my phone also and was able to connect, thanks for providing the detailed instructions, however when I click on the drag and drop field on my phone, I am taken to the file selector immediately and do not get any drop down options like you noted in the description, i.e. there is no 'take photo' option. Perhaps this depends on a phone's settings, do you know?

**Comment by lacnoskillz** [comment]
hello @cvtqx
thanks for the review
I'm currently testing on my iPhone and have no way of testing it on other devices which might be why you may not be getting the option?
I also updated the method as its easier now when its deployed. you can just go to https://hgnapplication_react_beta.surge.sh/bmdashboard/lessonform on your phone and try it.

**Comment by cvtqx** [comment]
> hello @cvtqx thanks for the review I'm currently testing on my iPhone and have no way of testing it on other devices which might be why you may not be getting the option? I also updated the method as its easier now when its deployed. you can just go to https://hgnapplication_react_beta.surge.sh/bmdashboard/lessonform on your phone and try it.

Mine is an android, so this might be the reason. But otherwise the file upload is working great on both PC and mobile. I am not sure if the ability to take photos is necessary in this feature or just an extra perk?

Also when I go to  https://hgnapplication_react_beta.surge.sh/bmdashboard/lessonform on my phone I am not able to log in with any of my accounts. Do you know what would be the reason?

**Pull request closed without merging**
