### PR TITLE
Xiao F differentiate personal max badge

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-09-12 at 21 08 45

## Related PRS (if any):
N/A

## Main changes explained:
- Update files `src/components/Badge/Badge.css` and `src/components/UserProfile/Badge.css` for the purple background color and shape of the count label
- Update files `src/components/Badge/BadgeImage.jsx` and `src/components/UserProfile/BadgeImage.jsx` to display 'x hr(s)' label for personal best badge
- Update file `src/components/Badge/Badge.jsx` to display additional text when the personal best badge is earned
- Update other files that passing `props.userProfile.personalBestMaxHrs` from Badges component to BadgeImage components

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
### Part a, b:
4. Go to User -> View Profile -> Badges -> Assign Badges -> Check 'New Max - Personal Record Award' badge -> Confirm
5. Check if the badge label's background color is purple and has 'x hr(s)' label in it
6. To test the change of 'x hr(s)', 
    step 1: go to MongoDB compass -> hgnData_dev -> userProfiles -> find a user of yours -> change 'personalBestMaxHrs' to a different number
    step 2: View Profile -> Badges -> Select Featured -> Delete 'New Max - Personal Record Award' badge
    step 3: View Profile -> Badges -> Assign Badges -> Check 'New Max - Personal Record Award' badge -> Confirm
7. In Dashboard -> Badges, the same steps 4-6 should work as well
### Part c:
1. Go to User -> View Profile -> Badges -> Assign Badges -> Check 'New Max - Personal Record Award' badge -> Confirm 
2. Go to Dashboard -> Badges, text 'Bravo! You have earned x badge(s) and a personal best of x hour(s) in a week!' should appear in the badges section
3. Go to User -> View Profile -> Badges -> Select Featured -> Delete 'New Max - Personal Record Award' badge if exists -> Confirm
4. Go to Dashboard -> Badges, check if the text shows either 'You have no badges.' or 'Bravo! You have earned x badge(s)!'

## Screenshots or videos of changes:
User -> View Profile -> Badges:
CleanShot 2023-09-13 at 21 33 15

Dashboard->Badges:

CleanShot 2023-09-13 at 21 32 53

Test video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/7151fd74-d87a-4ab6-81aa-b5adf2b61741

## Note:
Counting the correct number of hours of personal best is another task WIP: [FE PR#826](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/826)

### CODE REVIEW

**Comment by one-community** [comment]
Please center this better: 
image

**Comment by one-community** [comment]
Please come up with a way for this view not to have so much of the badge covered by the label... maybe just a number in this view? 
image

**Comment by tsunami776** [comment]
@one-community Hi Jae, thank you for the feedback. I've adjusted the view and label as you suggested and updated the screenshots and videos in my PR. Do these meet the standard?
CleanShot 2023-09-13 at 21 36 55
CleanShot 2023-09-13 at 21 36 33

**Review by DavidC0126 — APPROVED** [review]
Hi @tsunami776 I tested the PR and it works as intended.


999_dashboard
delete_999
delete999_dashboard
mongoDb
add_55
add_55_dashboard

**Review by GaryB93 — APPROVED** [review]
In testing this PR I was able to assign a New Personal Best Max hrs badge to a user and have it show up on the user profile and the dashboard. I was then able to change the personalBestMaxHrs in MongoDB and have it represented on the new badge. I was also able to delete the featured badge. Great work!
Screenshot 2023-09-15 at 2 12 48 PM

**Comment by one-community** [comment]
> @one-community Hi Jae, thank you for the feedback. I've adjusted the view and label as you suggested and updated the screenshots and videos in my PR.

Yes, looks excellent, thank you!

**Review by robertoooc — APPROVED** [review]
Hi @tsunami776, I tested your new branch and it does perform as expected. Updating the personal best hours through mongodb compass does also update the state of the hours that the badge holds. The bravo message also is being updated accordingly with the hours as well. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/f733b2bb-c498-41ab-8da1-f8e71278df61

**Review by ramyaram2092 — CHANGES_REQUESTED** [review]
Hello @tsunami776 great job on this functionality.
I have one doubt with the expected behaviour of the functionality 

I was successfully able to assign the badge . So thats good. But when I update the hours in backend it doesnt reflect in the front end immediately. I will have to repeat the assign badge step again for it to display in the front end. Is it an expected behavior ?

**Testing Video:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/60e54718-4bab-4865-8d87-cef629b77675

**Review by gabi-lima — COMMENTED** [review]
Working as expected.
Captura de tela 2023-09-16 182705

**Review by EdwinLauM — APPROVED** [review]
Hey @tsunami776! Works as expected!

Part A and B:

Assigning badge before mongoDB 'personalBestMaxHrs' change:

PR #1300 Before

MongoDB 'personalBestMaxHrs' change:

PR #1300 Mongo DB Change

After MongoDB 'personalBestMaxHrs' change:

PR #1300 After

Part C:

After assigning badge:
 
Screen Shot 2023-09-16 at 4 29 07 PM

Deleting featured badge:

Screen Shot 2023-09-16 at 4 29 31 PM

After deleting featured badge:

Screen Shot 2023-09-16 at 4 29 56 PM

**Comment by tsunami776** [comment]
> Hello @tsunami776 great job on this functionality. I have one doubt with the expected behaviour of the functionality
> 
> I was successfully able to assign the badge . So thats good. But when I update the hours in backend it doesnt reflect in the front end immediately. I will have to repeat the assign badge step again for it to display in the front end. Is it an expected behavior ?
> 
> **Testing Video:**
> 
>  1300.mp4

Hello, @ramyaram2092, thanks for the feedback! Because this badge will be assigned end of each week, to test this badge works in 'normal' way, you have to wait a week to have this badge assigned again. See the BE code snippets bellow:

CleanShot 2023-09-17 at 17 25 05
CleanShot 2023-09-17 at 17 27 40


 So, to test its functionality immediately, it works as expected to manually assign the badge again to see its effect.

**Review by Shiwani99 — APPROVED** [review]
Hi,
Great work. I tested your PR and it works as expected. I am attaching a screen recording of what I tested. I just had a small suggestion which is to add a count for "New Max - Personal Record Award" it does show the count when I click on featured badges and when I check mongoDB but when I hover over the badge it shows ! for the count. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/2aad3ba0-6769-4ae4-bceb-28e5499a0af9


This is how it looks when I hover over the badge

Screenshot 2023-09-18 at 6 26 15 PM

**Review by dah00 — APPROVED** [review]
Hey @tsunami776, I tested your PR, and all parts a, b, and c work as intended. Great job!
PR1300_purple_label
PR1300_modified_hour
PR1300_mongoDB_hours_change
PR1300_bravo_text
PR1300_no_badges

**Comment by one-community** [comment]
Great job, get Ramya's approval and I'll move this to final review!

**Comment by one-community** [comment]
> Hello @tsunami776 great job on this functionality. I have one doubt with the expected behaviour of the functionality
> 
> I was successfully able to assign the badge . So thats good. But when I update the hours in backend it doesnt reflect in the front end immediately. I will have to repeat the assign badge step again for it to display in the front end. Is it an expected behavior ?

Merging this to fix another problem, but please address this issue in a followup PR or add it to the bugs doc for someone else to address

**Pull request merged**
