### PR TITLE
Tim fix modify own badge amount

### PR DESCRIPTION
**Pull request by tdkent**
# Description
(Priority Medium) Vitor/Jae: Fix the “Modify Badge Amount” permission from the Manage User Permissions Component on Permission Management Page. Even after adding the permission, the user is not able to modify the amount of badges assigned to a user.

## Related PRS (if any):
N/A

## Main changes explained:
This PR fixes the remaining issues with allowing all users of a permitted role to modify the count of their own badges. Owner/Admin users are allowed by default to edit their own badge counts. Currently on the development branch, Volunteer and Mentor users have also have this ability enabled.
- Fixes an issue where modifying the badge count using the **User Profile > Select Featured modal** gives a concatenated result instead of a summed result in **Dashboard > Badges**

modify-badge-amount-bug1

- Fixes an issue where the sum of unique badges was being displayed instead of the sum of total badges in **Dashboard > SummaryBar** and **User Profile > Featured Badges**

modify-badge-amount-bug2

## How to test:

- `git checkout Tim_fix_modify_own_badge_amount` to check into current branch
- `npm install` to ensure your modules are up to date (no new modules are added in this PR)
- `npm run start:local` to run this PR locally
- (optional) if you do not have a volunteer or mentor user with assigned badges, log in first as an admin and use the **Assign Badges** modal on their User Profile page to award some badges
- log in as an either a volunteer or mentor user and navigate to **User Profile**
- use the **Featured Badges > Select Featured** modal to add or subtract to the badge count
  - note: setting a badge count to 0 will delete the badge
- check the badge count displays in the following locations are accurate:
  - **Dashboard > Summary Bar > Badges Earned**
  - **Dashboard > Badges > 'Bravo...' summary**
  - **User Profile > Select Featured > 'Bravo...' summary**

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/bcb9257f-269d-4793-95c0-1d9a6afef8e2

## Note:
Here are some of the issues I encountered while working on this fix:
- The first badges awarded by an admin to a new user will not be reflected on that user's dashboard the badge count has been modified at least one time.
- Attempting to modify badge counts using the **Dashboard > Badges > Badge Report** modal results in an error that freezes the app. The page must be refreshed, and the changes are not saved.
- The **User Profile > Featured Badges > Select Featured** modal currently allows negative numbers and numbers of infinite size to be manually added into the Count input.
- When editing badge counts in User Profile, exiting out of the modal without clicking Save Changes leaves any changes made in state rather than reverting the modal to its previous state.

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
Hi @tdkent , I've tested the PR and it works as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/dbf5b9d0-c495-47e6-937f-38be71a1bb0a

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works good on my device. @tdkent 

image

**Review by yunshan111 — APPROVED** [review]
Tested your changes, LGTM.

image

**Review by DavidC0126 — APPROVED** [review]
Hi @tdkent  I tested your PR and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/99a911cf-c3ed-4384-8aae-508511ff2bc8

**Comment by ss23046** [comment]
Hi @tdkent, tested your PR, looks good 

Screen Shot 2023-08-15 at 11 08 34 PM

**Review by ss23046 — APPROVED** [review]

**Review by ss23046 — APPROVED** [review]
Hi @tdkent, tested your PR, looks good

Screen Shot 2023-08-15 at 11 08 34 PM

**Review by yurisokolovicz — APPROVED** [review]
Dear @tdkent 
I have tested your fix on my own badge count, and it has been properly resolved. Congratulations!


Screenshot from 2023-08-16 08-26-32


Screenshot from 2023-08-16 08-27-42

**Review by eduvarjaor — APPROVED** [review]
Hi @tdkent 

I tested this PR and worked as intended. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/9d4141fe-3d34-4860-b669-979c86c3a25b

**Review by TheDescendant39 — APPROVED** [review]
Hi @tdkent, badge count was correct after adding/removing badges on all three locations. Great Job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/d8dc1c47-df6b-4b99-8170-fba29f3a2ce4

**Review by harshidad — APPROVED** [review]
Changes are looking good.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/dc802bc9-3dbf-439f-8645-f02eb10473ec

**Review by navneeeth — APPROVED** [review]
LGTM! Tested the changes and the PR works as expected. Good implementation!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/200076f5-7d87-499d-b3ef-acfa63556883

**Comment by Shreyj14** [comment]
Hi @tdkent I tested this PR, and it looks good to me. Works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/afed2a73-0583-4ce5-811e-a3e470f46e3a

**Review by Shreyj14 — APPROVED** [review]

**Review by luisarevalo21 — APPROVED** [review]
Hello @tdkent 
I reviewed your PR and works as intended great job!

I added badges to my Vol account. 
Once logged in I was able to view my badges inside of user profile. 
Afterwards I increased the values of the badges and the page updated.
Screenshot 2023-08-16 at 7 28 24 PM


I went to dashboard and saw the updated values as well. 
Screenshot 2023-08-16 at 7 28 31 PM

Great job. 
Also, I enjoyed your attention to detail.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/98347c23-8ef4-41a1-9553-7d9bee4f06c3

**Comment by Chuehleo** [comment]
Everything works as expected, great job!
Screenshot 2023-08-16 231958
Screenshot 2023-08-16 232043

**Comment by Chuehleo** [comment]
Everything works as expected, great job!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/c43fb66b-a0d5-422f-838f-30ed1e452e74

**Comment by Chuehleo** [comment]
Everything works as expected, great job!
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/08e5a14f-e5f7-40b9-9bbd-039ed003be90

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/1e4af339-dec1-46d4-8fc1-e4c01c8bac3f

**Comment by beblicarl** [comment]
this functionality works as intended and the code is excellent!!


[screencast-meet.jit.si-2023.08.17-12_43_48.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/20382e3f-763a-49f7-9b37-59e69eaa3449)

**Review by jerryren527 — APPROVED** [review]
Hello @tdkent!

Thank you for the detailed instructions and insightful notes. I was able to test your branch without any problems. Your code works as expected!

1. User Profile > Featured Badges shows sum of total badges, not total of unique badges.
2. Dashboard > Badges shows a summed result instead of a concatenated one.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/c3fb8bfe-0c5e-4627-b16e-01d969191d69

Great job!

**Review by Lin1404 — APPROVED** [review]

**Review by eduhorta — APPROVED** [review]
Working as intended!
Great job! 👍

image

**Review by iTvX — APPROVED** [review]
Hi, I have tested your pr, it worked as intended. Good job!



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/8c725f22-10e7-48b4-bea1-8b816d9fbbf9

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this one to final review!

**Comment by n0vay** [comment]
Used Admin account to assign badges to Volunteer account. Got the following error while changing the count opf badge thogh profile page although the count was saved :
image
Changing no. of badges from dashboard results in freezing of page as mentioned above with the following errors:
image

**Review by belagaam — APPROVED** [review]
I tested the PR as per the instructions and everything worked as expected. Great work.


[1127 - Tim fix modify own badge amount.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/8a3563c3-2dda-479a-be3f-8665eddab8a6)

**Review by veronicacheng2 — APPROVED** [review]
Hi @tdkent, I have tested the PR and everything works as intended. Good job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/f80134b9-46ad-490d-8be1-95476349a092

**Review by yaow62023 — APPROVED** [review]
PR testes, the new feature works as intended. Check the video below. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/3e328626-fc49-4f45-be2a-0b4465081e4e

**Comment by one-community** [comment]
Great job everyone, thank you. Merging!

**Pull request merged**
