### PR TITLE
Masasa_Reports_Visualization

### PR DESCRIPTION
**Pull request by ThapeloMasasa**
# Description
Screenshot 2024-04-20 at 1 06 24 PM

## Related PRS (if any):
This frontend PR is not related to any backend PR.
…

## Main changes explained:

- Intergrated the chart using recharts library into weeklySummariesReport.jsx…

- created a new component called TeamChart.jsx and its styling TeamChart.css to display the table of the members…

- integrated the logic to enable the table and chart to dynamically reflect properties of the selected teams …

- added the ability to visit a member's profile by clicking on their name in the table

…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Reports→ Weekly Summary…
6. verify  that  what video below shows happens
## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73863365/9424a59b-7ad2-47d7-9eb1-2ade96b69c1a

### CODE REVIEW

**Review by Alakabtaha0 — COMMENTED** [review]
Unable to checkout this branch. 

error: pathspec 'Masasa_Visualize_Charts' did not match any file(s) known to git

**Review by hbodgal — DISMISSED** [review]
image

It works well.

**Comment by MinSun0814** [comment]
It seems like I cannot open weeklysummariesreport
In terminal I am getting this error: 
Failed to compile.
./src/components/WeeklySummariesReport/WeeklySummariesReport.jsx
Module not found: Can't resolve 'recharts' in '/Users/minsun/HighestGoodNetworkApp/src/components/WeeklySummariesReport'

**Comment by ThapeloMasasa** [comment]
> It seems like I cannot open weeklysummariesreport In terminal I am getting this error: Failed to compile. ./src/components/WeeklySummariesReport/WeeklySummariesReport.jsx Module not found: Can't resolve 'recharts' in '/Users/minsun/HighestGoodNetworkApp/src/components/WeeklySummariesReport'

I think you might have not run npm install to have the recharts installed

**Review by MinSun0814 — DISMISSED** [review]
image
Thank you! The visualization looks good.

**Pull request closed without merging**
