### PR TITLE
Papia fix header height

### PR DESCRIPTION
**Pull request by papiasharmin**
Hello everyone, please review my PR #809 , thank you
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/809

**(PRIORITY low): Header height fixed**
headerheight

made the header height responsive. so that it there is a gap between header component and component below it.
headerheightnew

**How to Test:**
1. Check out this branch and run the application locally.
2. run "npm run start:local"
3. Log in to any user account.
4. change the screen size to see there is a gap between header and component below it

### CODE REVIEW

**Review by yoyoweiii — APPROVED** [review]
It works as intended that the member webpage does not have a gap now. It fits the size of the page.
Before

https://user-images.githubusercontent.com/60588210/236960791-f4c169f0-1677-4e72-9b79-c72336d92df4.mp4

after



https://user-images.githubusercontent.com/60588210/236961109-38b63f84-f873-4896-94e2-3dc467118994.mp4

Good job! Papia.

**Comment by wang9hu** [comment]
Hi @papiasharmin, I tested your code and it looks good! Good job! 

There is just one small thing I ran into while testing, I cannot directly switch to your branch cause it is from your forked repo, so I had to clone it and create a new '.env' file in your repo. I think it would be easier to test if you just create a branch on this repo.

after vs before:
compare 1
compare 2

**Review by wang9hu — APPROVED** [review]

**Comment by one-community** [comment]
Yes, that's correct. Thank you @wang9hu

**Comment by one-community** [comment]
This one is simple enough, moving it to final review. Please create future PRs on a branch on this repo though. The Leadership Team may request that for this one too.

**Review by alexander-huerta — APPROVED** [review]
Header height gap looks great now! 

Before fix 
908_before_formatting

After 

809_fixed_formatting

**Comment by Cirakuze** [comment]
Adding another confirmation of the header style fix.

| Before | After |
|--|--|
| https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15364639/23eb97d9-cdb6-49d2-a886-b82902c5d430 | https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15364639/a710bac6-e1e8-4f3e-900b-d99d79abdb47 |

**Review by Cirakuze — APPROVED** [review]
Adding another confirmation of the header style fix.

[Before](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15364639/23eb97d9-cdb6-49d2-a886-b82902c5d430) & [After](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15364639/a710bac6-e1e8-4f3e-900b-d99d79abdb47)

**Review by EdwinLauM — APPROVED** [review]
Works as intended. Header now has a gap! 

Before:
PR #809 Before

After: 
PR #809 After

**Comment by one-community** [comment]
Top lines are missing from this section: 
image
Please raise another PR that adds them.

**Pull request merged**
