### PR TITLE
Kurtis - Fix date format inconsistencies in app

### PR DESCRIPTION
**Pull request by KurtisIvey**
<div id="user-content-toc">
  <ul align="center">
    <summary><h1 style="display: inline-block">Fix date format inconsistencies in app</h1></summary>
     <summary><h1 style="display: inline-block">PR 1082</h1></summary>
     <summary><h2 style="display: inline-block">Finally finished!</h2></summary>

  </ul>
</div>

# Description
Inconsistency in the date format under weekly summary reports was noticed. Therefore, a fix was implemented as it was just a small formatting issue most likely. Luckily, the tz package pretty much takes care of it since it handles most if not all date formatting in the app. The date format in .tz.format ~~ was fixed to the desired format to address the issue.
~ in addition to that, I was told to fix all the instances of the date format in 'YYYY-MM-DD' and change it to the appropriate format 'MMM-DD-YY'

## Related PRS (if any):
Test with any backend. Personally, I used the current HGN rest dev backend
…

## Main changes explained:
- Change .format('YYYY-MMM-DD') to be   .format('MMM-DD-YY');
- enables date format consistency in weekly summary reports page
- Certain instances require configuring the Moment package to also be set to the "MMM-DD-YY"

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as an admin > verify weekly summary countdown timer has proper date format
4. go to reports > weekly summary reports > and double check the the date format is the same
5. go to view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.
6. go to view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res
7. go to view profile > look at the blue squares present and hover over them > date should be in proper format
8. go to timelog > current week timelog > verify date format in format such as "Jul-25-23"
9. <strong>(must be logged in as admin or higher)</strong>go to other links tab > usermanagement> pause someone, and verify the date format. be sure to unpause them if it's not your own account.
10. go to reports > teams > click any team to view created date format and verify in proper format. In addition, there is an invisible element with the class "update-date" you'll need to verify in the dom via inspecting on chrome. Search with the class and you'll find it.
11. dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.
12. dashboard > other links > projects > wbs > click one of the wbs task names > hopefully you found one with a start and end date, so you can verify it.

## Screenshots or videos of changes:
inconsistent format as noted in photo:

old date format pr1082

fixed:

fix weekly summ date consistency per jae

badge format desktop res:
pr1082 badge date format desktop
badge format tablet res:
pr1082 badge date format tablet
user report date format:
pr1082 update user report date format on individual
team report date format:
pr1082 fix format  team reports last updated date however is invisible
task date format:
pr1082 task date format
wbs date format:
pr1082 wbs task date format start and end
weekly summary countdown timer format:
pr1082 weekly summary due date countdown date format fix
blue square date format fix
pr1082 fix date format from bluesquare description via custom function

notes:
Basic information tab in user profile cannot be changed due to a date format error that occurs on the backend. Normal use shouldn't interact with this area much, so low priority.

### CODE REVIEW

**Comment by Cirakuze** [comment]
Hi @KurtisIvey, what was the reason to prefer the `'MMM-DD-YY'` format over the `'YYYY-MMM-DD'` format?

Is the goal the standardize the date to one format across the whole app? Looks like we're using every variety:
| Start with the year | Start with the month | Start with the date |
|--------|--------|--------|
| Screenshot 2023-08-02 at 10 55 07 | Screenshot 2023-08-02 at 10 55 29 | Screenshot 2023-08-02 at 10 55 44 |

**Comment by KurtisIvey** [comment]
> Hi @KurtisIvey, what was the reason to prefer the `'MMM-DD-YY'` format over the `'YYYY-MMM-DD'` format?
> 
> Is the goal the standardize the date to one format across the whole app? Looks like we're using every variety:
> 
> Start with the year	Start with the month	Start with the date
> Screenshot 2023-08-02 at 10 55 07	Screenshot 2023-08-02 at 10 55 29	Screenshot 2023-08-02 at 10 55 44

Jae wanted me to fix the date formatting for consistency in the weekly summary reports page, so I did it.

**Review by Indujaks — DISMISSED** [review]
Tested your changes, the date format on the weekly summary report looks consistent.
If the goal was only to resolve inconsistency on the summary page then these modifications are enough.
I approve!
Screenshot 2023-08-02 at 12 39 52 PM

**Review by veronicacheng2 — DISMISSED** [review]
Hi @KurtisIvey, I checked the changes on weekly summaries report page, and the dates are now consistent.

Standardized Date Format

**Review by joyceiphone — APPROVED** [review]
LGTM.

**Review by winghojackyli — DISMISSED** [review]
Hi @KurtisIvey , I've test the PR and the time shown in weekly summary report is now consistent. 

Capture

**Review by Abiddy — DISMISSED** [review]
LGTM!

**Comment by n0vay** [comment]
I can still see two different date formats.
image
image

**Comment by AnishPandita** [comment]
Hi @KurtisIvey I tested the PR and still can see two different formats as pointed by @n0vay 
Screenshot 2023-08-02 at 9 38 14 PM
Screenshot 2023-08-02 at 9 40 17 PM

**Review by DavidC0126 — COMMENTED** [review]
Hi @KurtisIvey I tested your PR and it works as intended.
consistency

**Review by eduhorta — DISMISSED** [review]
Working as intended. 👍

image

**Review by yurisokolovicz — COMMENTED** [review]
Dear @KurtisIvey,

I noticed that the 'weekly summary' is using the (year-month-day) format, while the 'From date to date' and 'summary submitted on' are following a different standard (month-day-year). Please check out the photos below.


Screenshot from 2023-08-03 11-15-00
Screenshot from 2023-08-03 11-15-27

**Review by sxiong5 — DISMISSED** [review]
The PR worked as expected!

Screenshot 2023-08-03 at 12 08 15

**Comment by jacky776690g60** [comment]
Confirm it works as intended!
Screenshot 2023-08-03 at 9 37 05 AM

**Comment by KurtisIvey** [comment]
> 



> Dear @KurtisIvey,
> 
> I noticed that the 'weekly summary' is using the (year-month-day) format, while the 'From date to date' and 'summary submitted on' are following a different standard (month-day-year). Please check out the photos below.
> 
> Screenshot from 2023-08-03 11-15-00 Screenshot from 2023-08-03 11-15-27

Thank you! I mentioned it to Jae, and he wants me to go ahead and do a scrape of the whole website to get everything in this format rather than just that one section that was brought up. 

I appreciate you taking the time to show me where else it wasn't applied

**Review by TheDescendant39 — DISMISSED** [review]
Hey, @KurtisIvey I tested your changes and they work great.
Screen Shot 2023-08-03 at 1 56 54 PM

**Comment by iTvX** [comment]
I have tested your pr and everything looks good. You can check the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/f657ef76-530e-41c5-95fb-0d715e6ead7d

**Comment by beblicarl** [comment]
I tested this PR and I happen to see two different date formats as seen below

issue #1082-1

**Comment by beblicarl** [comment]
I tested this PR and it works as intended. Great work

issue #1082-2

**Review by beblicarl — DISMISSED** [review]

**Comment by KurtisIvey** [comment]
> I tested this PR and it works as intended. However, I saw the error below in the backend console
> 

Fixed it, thanks for letting me know.

**Review by eduvarjaor — COMMENTED** [review]
Hi @KurtisIvey 

I tested this PR, and it worked as intended for weekly summary reports, but the data format for the current week timelog is 'YYYY-MMM-DD'.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/ec482097-f6ea-4fed-bcdf-ba419d046f35

**Comment by KurtisIvey** [comment]
> Hi @KurtisIvey
> 
> I tested this PR, and it worked as intended for weekly summary reports, but the data format for the current week timelog is 'YYYY-MMM-DD'.

Thanks, just addressed it. These two specific variables "endOfWeek & startOfWeek" were causing errors in the backend whenever I formatted them to MMM-DD-YY, so I had to make dedicated variables just for the display date to get it in the proper format and maintain functionality.

**Review by zuhang2000 — DISMISSED** [review]
Hi Kurtis! I have tested your PR following your instructions. Everywhere else are working as expected! Except I do catch that "Search by Date Range" is also display yyyy-mm-dd format. Please check it in the following screenshot.
Screen Shot 2023-08-05 at 1 05 58 AM

**Comment by beblicarl** [comment]
> > I tested this PR and it works as intended. However, I saw the error below in the backend console
> 
> Fixed it, thanks for letting me know.

This issue has been fixed. Great work!

issue #1082-no-error

**Review by ramyaram2092 — CHANGES_REQUESTED** [review]
Hello @KurtisIvey  Checked the following Pages  : 
1.  Reports -> Weekly Summary  : **Works as expected** 
image

2.  User Management-> Pause a profile: **I dont see the new format here**  
image

3. Current week Time log . **I just see the Month and year** 
image

4. Project-> Tasks :  Its in correct format 
image

I have one more query. In places where the rendering of date is  in the expected month-day-year format in some place it says Aug-03-2023  and in  some it is 08/03/2023. Shouldn't that be identical as well ?

**Comment by KurtisIvey** [comment]
> Hello @KurtisIvey Checked the following Pages :

> 2. User Management-> Pause a profile: **I dont see the new format here**
>    image
> 3. Current week Time log . **I just see the Month and year**
>    image
> 4. Project-> Tasks :  Its in correct format
>    image
> 
> I have one more query. In places where the rendering of date is in the expected month-day-year format in some place it says Aug-03-2023 and in some it is 08/03/2023. Shouldn't that be identical as well ?

I haven't reached the UserManagement Section yet. I've been pushing the changes one by one to ensure nothing effects the backend as that was an issue before. That is something I'm going to update though.

Current week time log seems to be deliberately in the format, so I'm just going to leave that one as is. There wouldn't be any benefit to having the year listed on a section that displays the current week only. 

It's still a work in progress. Thanks for highlighting some of the sections that I still need to update.

**Comment by KurtisIvey** [comment]
> Hi Kurtis! I have tested your PR following your instructions. Everywhere else are working as expected! Except I do catch that "Search by Date Range" is also display yyyy-mm-dd format. Please check it in the following screenshot. Screen Shot 2023-08-05 at 1 05 58 AM

Thanks! I'll knock that one out as well. There's like 50+ instances of the date format in the undesired way, so there's a lot of them to fix. The upper portion should be able to be changed, but the search form itself, will have to remain since it's a query.

**Review by yaow62023 — APPROVED** [review]
I tested your pr and all the time formats you mentioned are correct. The format are Month, Date, Year. Check the screen shoot for details. Great work! 

Screenshot 2023-08-06 at 11 05 58 AM
Screenshot 2023-08-06 at 11 13 38 AM
Screenshot 2023-08-06 at 11 16 37 AM

**Review by sxiong5 — APPROVED** [review]
Hey, I have checked the summary, profile, and timelog. All the formats are "MMM-DD-YY".

Screenshot 2023-08-07 at 14 47 03
Screenshot 2023-08-07 at 14 45 58 (2)
Screenshot 2023-08-07 at 14 52 11

**Review by yunshan111 — APPROVED** [review]
Checked your changes, LGTM!


8f776ba2f8b3ebcfd788f4ac812d0eb

**Review by luisarevalo21 — COMMENTED** [review]
Hello @KurtisIvey 
I reviewed your PR and works as intended. 
Great work.

I viewed the weekly summary and all the dates are formatted correctly.
Screenshot 2023-08-07 at 8 52 50 PM


I viewed a user's profile under the basic information and the date was also displayed correctly.
Screenshot 2023-08-07 at 8 55 28 PM


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/7d3b22fa-d35f-4942-9a0a-4e317d1c7275

**Review by luisarevalo21 — DISMISSED** [review]

**Comment by iTvX** [comment]
I have tested all the list; the time is consistencies now.



82a2463)

**Review by Jiyuanxia — DISMISSED** [review]
Hello, @KurtisIvey! I have reviewed and tested your implementation. However, due to the absence of badges, I'm unable to test the display of badge dates. Aside from that, everything appears to be functioning smoothly as you described. Well done!

Weekly summaries reports page with volunteer role:
Screenshot 2023-08-09 181417

End date display with volunteer role:
Screenshot 2023-08-09 181919

Current week timelog with volunteer role:
Screenshot 2023-08-09 182006

User management page after pause someone with admin role:
Screenshot 2023-08-09 182220

Weekly summaries reports page with admin role:
Screenshot 2023-08-09 182524

**Review by ThapeloMasasa — APPROVED** [review]
The date format is consistent in the expected regions

Screenshot 2023-08-09 at 4 47 19 PM
Screenshot 2023-08-09 at 4 47 54 PM
Screenshot 2023-08-09 at 4 49 28 PM

**Review by liaoyufu-leo — DISMISSED** [review]
Hi, this update works good on my device.

image

**Review by ramyaram2092 — APPROVED** [review]
Hello @KurtisIvey  PF the screenshot of all the screens . It looks good to me. 
Weekly summaries report :
image

User profile : 
image

**Select Featured Badge page** 
image

**TimeLog**  
image

**User Management View  :** 
image

**Reports->Team->Created Date :** 
image

Dashboard ->task: 
image

**Review by robertoooc — APPROVED** [review]
Hi @KurtisIvey, I tested your branch across various different occurrences of the date format and it did seem to stay consistent to the MM-DD-YYYY format that was intended.

WBS Task Date:
WbsDate

Team Created At Date: 
Team Created At

Paused Someone Date:
PausedElseDate

Task Date:
TasksDate

Badge Date:
Badge Date

Paused Self Account Date:
PausedDate
Weekly Summary Date:
WeeklySummaryDate

**Comment by KurtisIvey** [comment]
Finished implementing website date format changes. Shouldn't be any more updates unless someone else finds something I missed.

**Review by winghojackyli — DISMISSED** [review]
Hi @KurtisIvey , I've tested the updated PR and it works great! 

#### Countdown Timer
Capture1

#### Weekly Summary Reports
Capture2

#### End Date Triggered By Pause
Capture3

#### Featured Badges in Desktop and Tablet
Capture4
Capture5

#### Blue Squares Hover
Capture6

#### Current Week Timelog
Capture7

#### Team Created Date & Invisible Element
Capture8
Capture9

#### Individual Task
Capture10

#### WBS Task in Project
Capture11

**Review by eduvarjaor — APPROVED** [review]
I tested this update and looks great. Good job!

**Comment by Shreyj14** [comment]
Hi @KurtisIvey 
The dates are consistent throughout for the pages I tested.
Screenshot 2023-08-17 at 5 41 38 PM
Screenshot 2023-08-17 at 5 40 27 PM
Screenshot 2023-08-17 at 5 40 21 PM
Screenshot 2023-08-17 at 5 40 11 PM
Screenshot 2023-08-17 at 5 39 51 PM
Screenshot 2023-08-17 at 5 39 31 PM
Screenshot 2023-08-17 at 5 37 06 PM

**Review by Indujaks — APPROVED** [review]
These updated changes look good to me, I verified date consistency on profile page as well as weekly summary report.

Screenshot 2023-08-18 at 12 53 15 AM

Screenshot 2023-08-18 at 12 48 18 AM

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this date format change work good on my device. @KurtisIvey 

image
image

**Review by navneeeth — DISMISSED** [review]
LGTM! Good implementation! The changes work as expected. Tested the following:

**1. go to reports > weekly summary reports > and double check the the date format is the same **
weekly summary reports

**2.  go to view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.**
basic information tab after pausing

**3.  go to view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res**
**Desktop:**
featured badges desktop

**Tablet:**
featured badges tablet

**4.  go to view profile > look at the blue squares present and hover over them > date should be in proper format**
blue square hover

**5. go to timelog > current week timelog > verify date format in format such as "Jul-25-23"**
current week timelog

**6.  go to other links tab > usermanagement> pause someone, and verify the date format. be sure to unpause them if it's not your own account.**
pause user

**7.  go to reports > teams > click any team to view created date format and verify in proper format.**
teams created date

**8. dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.**
task start date and end date

**9.  dashboard > other links > projects > wbs > click one of the wbs task names > hopefully you found one with a start and end date, so you can verify it.**
task under projects

**Review by Chuehleo — APPROVED** [review]
Everything works as intended, great job!
Screenshot 2023-08-19 010509

**Review by ss23046 — APPROVED** [review]
Hi @KurtisIvey 
Tested the PR, LGTM!

The dates are consistent for all the pages I tested, good implementation!
Screen Shot 2023-08-19 at 2 32 20 PM
Screen Shot 2023-08-19 at 2 32 41 PM
Screen Shot 2023-08-19 at 2 32 57 PM
Screen Shot 2023-08-19 at 2 33 10 PM
Screen Shot 2023-08-19 at 2 33 41 PM
Screen Shot 2023-08-19 at 2 34 05 PM

**Review by belagaam — APPROVED** [review]
Tested the PR per the instruction and across multiple sections to check for date format. 
The format is consistent everywhere.
1082 - Kurtis - Fix date format inconsistencies in app - 1
1082 - Kurtis - Fix date format inconsistencies in app - 2
1082 - Kurtis - Fix date format inconsistencies in app - 3
1082 - Kurtis - Fix date format inconsistencies in app - 4
1082 - Kurtis - Fix date format inconsistencies in app - 5
1082 - Kurtis - Fix date format inconsistencies in app - 6

**Review by winghojackyli — APPROVED** [review]
Hi @KurtisIvey , I've tested the updated PR and it works great! 

#### Countdown Timer


#### Weekly Summary Reports


#### End Date Triggered By Pause


#### Featured Badges in Desktop and Tablet



#### Blue Squares Hover


#### Current Week Timelog


#### Team Created Date & Invisible Element


#### Individual Task


#### WBS Task in Project

**Review by navneeeth — APPROVED** [review]
LGTM! Re-reviewed the PR and it works as intended. Good implementation, @KurtisIvey!

Performed the following tests:
1) log as an admin > verify weekly summary countdown timer has proper date format
weekly summary countdown timer


2) go to reports > weekly summary reports > and double check the the date format is the same

weekly summary reports

3) go to view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.

manually pause profile

4) go to view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res

Desktop res:
select featured badges desktop

Tablet res:
select featured badges tablet


5) go to view profile > look at the blue squares present and hover over them > date should be in proper format

blue squares hover

6) go to timelog > current week timelog > verify date format in format such as "Jul-25-23"
(must be logged in as admin or higher)go to other links tab > usermanagement> pause someone, and verify the date format. 

current week timelog

7) go to reports > teams > click any team to view created date format and verify in proper format. 

team created date

8) dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.

individual task

9) dashboard > other links > projects > wbs > click one of the wbs task names > hopefully you found one with a start and end date, so you can verify it.

project task name

**Review by Shreyj14 — APPROVED** [review]

**Comment by Shreyj14** [comment]
Hi @KurtisIvey 
I can see the changes in date format, but I guess you missed out on this page. 
Screenshot 2023-08-24 at 3 53 06 AM

**Review by Indujaks — APPROVED** [review]
LGTM, It works as expected in the new update as well!

257923650-05c74ed0-3f8b-41b5-a984-7c07658a4bfc

**Review by Shreyj14 — APPROVED** [review]

**Review by navneeeth — APPROVED** [review]
LGTM!

**Review by ss23046 — APPROVED** [review]
LGTM! Reviewed the PR again, it works as intended! Good job @KurtisIvey

**Review by belagaam — APPROVED** [review]
Tested the PR. Everything works as expected. The date seems consistent across all sections. Great work.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/1231a909-8be6-4c69-8db8-72fdcb0fe84d

**Review by GaryB93 — APPROVED** [review]
Followed steps to test date formats as well as combed through application logged in as Admin to verify all dates follow same date format. All dates are using a universal format. Great work!
Screenshot 2023-08-25 at 9 07 00 AM
Screenshot 2023-08-25 at 9 07 46 AM

**Comment by one-community** [comment]
Thank you all! Moving this to final review!

**Comment by AuroraLovesWhales** [comment]
Hi @KurtisIvey. I have tested your PR and the intended change in date format works as expected. Great work!

1. log as an admin > verify weekly summary countdown timer has proper date format
image

2. go to reports > weekly summary reports > and double check the the date format is the same
image

3. go to view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab
image

4. go to view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res
image

5. go to view profile > look at the blue squares present and hover over them > date should be in proper format
image

6. go to timelog > current week timelog > verify date format in format such as "Jul-25-23"
image

7. go to other links tab > user management > pause someone, and verify the date format
image

8. go to reports > teams > click any team to view created date format and verify in proper format. In addition, there is an invisible element with the class "update-date" you'll need to verify in the dom via inspecting on chrome. Search with the class and you'll find it
image

9. dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format
image

11. dashboard > other links > projects > wbs > click one of the wbs task names
image

However, I am facing an issue when I visit the Weekly Summaries Report page. The entire page freezes after loading the content for "last week". This issue is not present on the dev branch. Please refer to the video recording below for reference:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/d940aed5-e64f-46cd-9cc6-8183877b79d5

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
