### PR TITLE
Ishan - Fix Badges Icon Redirection Behaviour

### PR DESCRIPTION
**Pull request by ishan-miglani**
# Description
BugDescription

## Related PRS (if any):
To test this PR you need to checkout the development branch backend.

## Main changes explained:
- Updated code in Timelog.jsx to show the correct tab depending on the hash in the url

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Badges icon in summary bar 
6. Verify that clicking on it redirects you to the badges tab
7. Do the same from the summary bar in the Timelog page
8. Verify steps 5,6,7 for the tasks icon too.

## Screenshots or videos of changes:
Before: 

https://github.com/user-attachments/assets/8ef9050c-c1a0-4cad-8213-2e2d78c773cd

After:

https://github.com/user-attachments/assets/caa93ad2-a940-4323-b8f3-c2da7c9713da

## Note:
You should now be able to redirect to the badges & tasks tabs in the Timelog from both the Dashboard and the Timelog pages

### CODE REVIEW

**Review by JatinAgrawal94 — APPROVED** [review]
Everything works as expected. Good Work.

https://github.com/user-attachments/assets/077b634c-f5a3-48a7-b235-26439d524335

**Review by manikittu810 — APPROVED** [review]
Hello @ishan-miglani 
I have gone through the steps mentioned and everything is working as mentioned and redirection from summary badges to badges earned working fine.

Screenshot 2024-08-17 at 7 30 43 AM


Thank you.

**Review by kdaga81 — APPROVED** [review]
image

All the icons are redirecting to their respective roles.

**Review by Aishwarya0898 — APPROVED** [review]
Hello @ishan-miglani 
The PR is working as expected, here is the video reference.

https://github.com/user-attachments/assets/62d6eb0c-95bf-44e1-b0a9-7e4940816770

**Review by jinxyou — APPROVED** [review]
After I tested it, the redirect works fine in every page. 
Screenshot 2024-08-17 211054
Screenshot 2024-08-17 211118

**Review by Gauravmg6 — APPROVED** [review]
Everything works as expected.

https://github.com/user-attachments/assets/965e952e-07ca-498d-94b3-a4263e5d54b8

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and its working as expected.


https://github.com/user-attachments/assets/29924a45-737c-4d6a-a6ad-b661b4826713

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
