### PR TITLE
Eduardo Add `.nvmrc` file. Node v14.

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
In this pull request, we're introducing a valuable addition to our project - the `.nvmrc` file. This file is designed to streamline the process of managing Node.js versions, ensuring that collaborators and contributors use the appropriate version when working on the project. 

## Related PRS :
[Back-end PR.](https://github.com/OneCommunityGlobal/HGNRest/pull/612)

## Main changes explained:
Do you use `nvm`? 
Then you can run `nvm install` or `nvm i` in the project folder to install and use the most appropriate version of Node.

Added .nvmrc file: 
This file specifies the required Node.js version for the project. 

## How to test:

1. check into current branch
2. do `nvm i` and `npm i` to run this PR locally
3. run `npm run start:local`
4. log as any user
5. verify if the app is working properly
***

## Alternative testing

1. Access the [branch URL](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/tree/Eduardo_add_.nvmrc_file).
2. Click on Code -> Create Codespace

image

3. Wait for the virtual environment to load

image

4. Run the command

image

## Video of change:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/e29644e9-3548-4a35-837e-d3f722cf894d

## Note:
If you already have the appropriate version of Node installed in your environment, running the command will perform the checkout.

### CODE REVIEW

**Review by tdkent — APPROVED** [review]
Followed instructions, running `nvm i` set node to v14.21.3. App runs correctly.

**Review by KurtisIvey — APPROVED** [review]
Thought my computer was going to undergo a catastrophic error there for a bit while nvm i was running lol. Have tested it and found it to perform exactly as intended. Really did simplify the process for mac users.


What I did:
   Delete my old version of node that I used with HGN (v14.17.6)
   confirm deletion with nvm ls
   Then run nvm i (takes a bit of time to install, so don't panic)
   Afterwards, confirm installation via "nvm ls". You should see the node version installed
   
   
Screenshot 2023-11-17 at 10 20 29 AM

**Review by sahilpatel18 — APPROVED** [review]
After testing, I found that everything works exactly as intended. Great work! 

Screenshot 2023-11-18 at 12 16 59 AM

**Comment by palakgosalia** [comment]
Hey, I installed the correct version of node using nvm i. Great work. I also tested the app and it works as expected. Thank you

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/adb32cc0-12a7-4b67-8480-b371162214ce

**Comment by eduhorta** [comment]
Hi @EvianTan! Thank you for the feedback! 👍 

> Great PR! Thank you @eduhorta I just have one question, for people using `nvm`, do they need to run `nvm i` before `npm install` & `npm run start:local` everytime when they want to up the app? If YES, please also revise the related part in our "running up apps instructions".

Running `nvm i` will install the appropriate version of node and proceed with the checkout. After that, you'll be able to run `npm install` & `npm run start:local`.

If you close and open your code editor, your node version will be set to it's default alias. If it's a different version from the one used by the project you'll have to change your node version before running the app, otherwise you'll face an error running `npm install` & `npm run start:local`.

You can proceed using the `nvm i` to do the checkout (since the correct version is already installed) everytime you want to run the app and then `npm install` & `npm run start:local`.

The `.nvmrc` file won't set your node default alias to be the same as the one used by the project. You'll have to run `nvm alias default lts/fermium` for that.

Once the default alias is set to the same as the one used by the project, you can just run `npm install` & `npm run start:local`.

> And for those people who don't use `nvm`, they will just do `npm install` & `npm run start:local`, right?

No, it won't work.
If people have a different version of node installed and try to run `npm install` there will be an error.

On the image bellow I got a VM with the latest version of node and I get an error running `npm install`.

image

I agree that we must revise the related part in our "running up apps instructions".
Right now we have instructions to install the project's dependencies and then we have the instructions about the node version. Which are not in the proper order.

image

**Review by AaronPersaud — APPROVED** [review]
Hi Eduardo, I've tested and it worked perfectly!

<b>Running `nvm i` to switch versions </b>

image

<b>Running `npm i` to install packages </b>

image

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
