### PR TITLE
Huijie fix add lost hours editing deleting

### PR DESCRIPTION
**Pull request by metaphor987**
# Description

## Related PRS (if any):
This frontend PR is related to the backend PR 1115(https://github.com/OneCommunityGlobal/HGNRest/pull/1115).
Please check the backend PR for more details. 

## Main changes explained:
Fix the error that owner user cannot add lost time for teams.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin or owner user
5. go to Reports -> Reports -> Add Lost Time, or Show Person Lost Time, verify that the errors in adding, updating and deleting lost hours do not occur. Please check the backend PR for more details. Thank you!

### CODE REVIEW

**Review by Dk-21 — APPROVED** [review]
### PR 2710 
@metaphor987 
Tested the Changes of Code and Working As Described.
Features of Adding, Updating and Deleting are working Fine.

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected. Features of Adding, Updating and Deleting are working as expected without any errors. Below are the screenshots for reference:
Capture2710_1
Capture2710_2
Capture2710_3

**Comment by pallavithorat** [comment]
I have verified the PR, and the changes are functioning as expected. The features for adding, updating, and deleting are all working smoothly without any errors. Please find the reference screenshots below.
PR#2710
Screenshot 2024-10-11 at 1 42 31 PM
Screenshot 2024-10-11 at 1 42 53 PM

**Comment by zhiminV** [comment]
I have checked many time that I am inn this branch, but when I login as Admin, I did not see button Add Lost Time. Not sure the problem. 
IMG_0872
Screenshot 2024-10-18 at 9 42 04 PM

**Review by javid679 — APPROVED** [review]
I have approved this PR and addition, deletion and update of files are working fine, below is the Video for reference: 


https://github.com/user-attachments/assets/768d52df-f2ec-4d72-89d3-38c97864d736

**Comment by zhiminV** [comment]
> I have checked many time that I am inn this branch, but when I login as Admin, I did not see button Add Lost Time. Not sure the problem. IMG_0872 Screenshot 2024-10-18 at 9 42 04 PM

I found the reason in backend that the admin account can not add lost hours, that's why I do not see the button
IMG_0879

**Comment by sheetalmangate** [comment]
I could not test this PR locally.  while adding new time entry it is showing me pop up with message blow

 "An error occurred while attempting to submit your time entry. Error code: 500"

PR_2710_error

**Comment by samarth9201** [comment]
Provided feedback in backend PR.

**Review by samarth9201 — APPROVED** [review]
Provided feedback in backend PR.

**Review by Rupa2400 — COMMENTED** [review]
I have verified the PR, and the changes are functioning as expected. The features for adding, updating, and deleting entries work without any errors. 
However, I encountered an issue when trying to update hours or delete an entry that has a value of 0. In these cases, an error occurs: "An error occurred while attempting to update your time entry. Error code: 400."

PR_2710_1

PR_2710_2

PR_2710_3

PR_2710_4

PR_2710_5

PR_2710_6

**Review by hqzhu0913 — APPROVED** [review]
Hi,
Everything works as explained. More details are in the frontend review.

**Review by Rui-Liu-github — APPROVED** [review]
Hi, I reviewed PR #2710, pulling the latest version code from Huijie. I tested the add lost time functionality, including add, update, edit, and delete options. all of them works as mentioned.

image
image
image
image
image
image

**Pull request merged**
