### PR TITLE
Yili - When entering WBS management page of a project with timer on, the timer will stop

### PR DESCRIPTION
**Pull request by suaniii**
# Description
WBS management page

## Related PRS (if any):
For backend use development branch

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log as admin user
5. Go to Dashboard - Other Links - Projects. 
6. Click the `WBS` button of any project. 
7. Start the timer
8. Click on the name of any WBS. If there’s none, create one and click the name of it. 
9. Verify that the timer works well when  entering the WBS management page.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/861cc1c1-b6cc-4460-805c-0fd687751ef4

### CODE REVIEW

**Review by jinxyou — DISMISSED** [review]
The timer fix works fine. It will continue to tick after entering WBS page. 
Screenshot 2024-09-06 222922
Screenshot 2024-09-06 222929

**Review by AJAYINAVOLU — DISMISSED** [review]
Changes are working as expected.

image

Thank You

**Review by panchalvatneu — APPROVED** [review]
Timer keeps running as expected, good work!
image

**Review by mohangadde1 — APPROVED** [review]
https://github.com/user-attachments/assets/5cf008af-9fdd-42e6-b18e-f67ae4b82d25
Timer is working fine after entering WBS management page.

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are not working as expected. The timer stopped ticking at 14:32 as soon as user is navigating to the WBS management page. Below are the screenshots for reference:
Capture2649

**Review by CillianRen — DISMISSED** [review]
https://github.com/user-attachments/assets/8a09d28e-aee9-4a83-ac15-e9ce78068055

the timer keeps running, good job!

**Review by SMitta11 — DISMISSED** [review]
Reviewed changes and timer works even after entering WBS page:
Screen Shot 2024-09-07 at 7 21 39 PM

**Review by sam19981 — APPROVED** [review]
The website no longer crashes, and the timer runs without stopping.
Screenshot 2024-09-07 at 10 52 59 PM

https://github.com/user-attachments/assets/39432ae0-37e8-4474-8f7b-82cbf6c8e1f4

**Review by ddshah878 — DISMISSED** [review]
Changes are working as expected.

image

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and Verified that the timer works well when entering the WBS management page.


https://github.com/user-attachments/assets/bf4d6d45-6765-4a58-af7e-2704d4eb4650

**Review by RishithaMamidala — DISMISSED** [review]
@suaniii 
The timer fix works fine. It will continues after entering WBS page.
PR 2649

**Comment by KurtisIvey** [comment]
Hi Anne, I noticed there was merge conflict on this. Looks like it's just one file. We'd love to get this moved to final review asap once it's cleared up

**Review by Gauravmg6 — APPROVED** [review]
Everything is worked as expected.

https://github.com/user-attachments/assets/dde10ac5-f170-4eab-a63a-797eda0fafad

**Review by Watchdog00 — COMMENTED** [review]
I have completed the testing and got the expected results. Good job!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
