### PR TITLE
Omar - Display only active users on create task modal

### PR DESCRIPTION
**Pull request by cone-7**
# Description

Make the Task Resources section only show active users

## Main changes explained:
- Filter out the inactive users.
- Use correct values for Assigned and Status fields.
- Use onclick events to update values.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. Admin Login → Other Links → Projects → Choose Project → Click WBS Icon → Choose WBS → Add Task
5. Check that only active users are shown
6. Assigned and Status fields are selected by default

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/9827488/f6efbc30-4d90-48b5-a286-baf9be78a7b1

## Note:
We should have an API to get only active users.

### CODE REVIEW

**Comment by Jiangwei-shi** [comment]
Hi Cone！ I have tested this PR. The Assigned and Status fields are selected by default, which fulfills the requirement. However, the requirement to "Check that only active users are shown" is not reflected in my test. I am unable to select an active or inactive user. Also, as shown in my video, there's a bug related to task movement. When the first task is deleted, the second task cannot be moved to the first position. Please help me translate this into English.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56906163/dce46e7c-d473-44b5-acb2-a4475c87935e

**Review by HectorAgudelo — APPROVED** [review]
These changes work as expected when sorting active users.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/05b91a6b-099e-42ed-bb4d-5ae5a0f42015

**Review by ramyaram2092 — APPROVED** [review]
Hello @cone-7 
I created a project called ramya-test-981. Added 3 active users and 1 in active user to the project and tried creating a task in the WBS


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/699be3bf-f996-4d61-9db5-c7bb13e04107


**Observations**:

- I am unable to see the inactive user  981(Inactive user in the project) while creating a task
- Assigned and Status fields are selected by default

The change works as expected .

**Review by shiva2096 — COMMENTED** [review]
Hello @cone-7 

Changes are working as expected. As soon as I make a user in-active, I am not able to make it a resource for a new task.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/569dc78f-0a89-4ef5-9c92-65f587b97645

**Review by xaanders — DISMISSED** [review]
Hi! I tested you PR. 
And found couple things that probably need to be fixed. I couldn't assign to a task admin/mentor/volunteer though they were as active users. 
It works proparly for manager and core team. 
[scrnli_08-07-2023_21-52-58.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/38899d74-e32e-43a8-bd43-f25fa0e536c6)

**Review by AaronPersaud — APPROVED** [review]
Hi, I've tested it and it looks good!

<b>Testing create task only shows active users</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/99e484cd-90c7-408f-bed9-d48048b210bd

- inactive users are not searchable
- task is Assigned and Status:Active by default

**Review by xaanders — APPROVED** [review]
I have tested this review. Works as inteded. Good job!

[scrnli_09-07-2023_10-54-12.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/f692f54f-4cb7-48a1-adb6-58c5f7fadf7f)

**Review by tdkent — APPROVED** [review]
Local testing confirms 
- inactive users assigned to the Project cannot be selected as Resources in the New Task form
- **Assigned** has default value `Yes`
- **Status** has default value `Started`

Testing Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/4bc5f533-6bc8-4991-99aa-2179f35e878a

**Review by BaileyM96 — APPROVED** [review]
Good evening Omar!

I reviewed your changes and everything works just fine.

## Video Walkthrough

[Display only active users.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/61be1c69-6f82-417b-8714-67e7460cc0f2)

**Review by siddharthmohite — APPROVED** [review]
I created a project called SiddharthTest and added four users to the project. I made one user inactive. Created a task and tried to add users to the 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37925823/df6e4c42-9d0f-442a-806a-257af148a132

task, but the inactive user did not show up.

It works as expected.
Status and Assigned fields are selected by default.

**Comment by ramyaram2092** [comment]
@one-community  This PR has like 7 approvals

**Review by NidaZaki — APPROVED** [review]

**Comment by Lucas-E** [comment]
Great job everyone! Moving this one to final review!

**Comment by one-community** [comment]
Nida already approved this one, so merging it. Thank you!

**Pull request merged**
