### PR TITLE
Mohammad - Middle name search on the Project team members search bar(Frontend)

### PR DESCRIPTION
**Pull request by mohabbasd**
# Description
Add middle name searching to the project member search bar:
Fixes # (bug list priority medium)
Modify getUserBySingleName and getUserByFullName in userProfileController.js located in HGNRest. To allow for middle name querying. 
Modify findUserProfiles in projectMembers.js in HighestGoodNetworkApp to extract and send the middle name to the backend.
Note: Users are stored with a firstName field and lastName field. The middle name should be concatenated to the end of the first name. The below table shows an example of how a user with a middle name is stored.

## Related PRS (if any):
This is the backend PR where you have to checkout separately to test #[786](https://github.com/OneCommunityGlobal/HGNRest/pull/786) 

## How to test:
1. check into current branch and check into backend branch separately
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ Other links→ Projects→Choose any project→Go to members→Go to All→Search for a user using the middle name

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/ecb6b3d1-7665-41a2-968c-89781da6283b

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by meetpadhiar4 — CHANGES_REQUESTED** [review]
Hi, I tested your PR and I was able to search the members with the middle name. However, the input is also considering blank spaces before the input string resulting in incorrect results. Please refer the video attached.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/faa4d2cd-79f5-4a4b-8d44-76b207ca831f

**Comment by mohabbasd** [comment]
> Hi, I tested your PR and I was able to search the members with the middle name. However, the input is also considering blank spaces before the input string resulting in incorrect results. Please refer the video attached.
> 
>  PR.2022.mov

Hello, Thank you for the suggestion, I have reviewed it and made changes. Please feel free to check it again.

**Review by Pandani07 — APPROVED** [review]
Works as expected!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/f204c435-40bb-46b6-8da1-c96d3557e875

**Comment by dhairya-mehta** [comment]
Hey, I verified the above PR, good job:
image

**Comment by nnamdixobi** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/ead21fea-6c3c-43d6-8d33-d643704d0a70

Looks good but I believe some work could be done to improve the search, when I searched 6 which was the middle name of one of the members it wasn't as fluid

**Review by 20chen-7 — APPROVED** [review]
I could use the 'Test' as the middle name and find users
Screenshot 2024-03-14 at 11 02 05 PM
Screenshot 2024-03-14 at 11 03 15 PM

**Review by ImzIssa — APPROVED** [review]
Hey, I've tested your PR and your changes including the one suggested by @meetpadhiar4 work correctly. Nice Work.
PR#2022

PR#2022 (2)

**Review by SanketKaware — APPROVED** [review]
This change is working as expected. I have followed your steps and it looks good.

- Able to search users by middle name.

Please see below video review for reference

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/9f9dff76-d56c-486a-a1da-1dbc491b1787

**Review by yaow62023 — APPROVED** [review]
Hi Mohammad, I have test your PR, the search by middle name is working as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/30e5e3e5-9214-44d6-b6a1-19b656b940b5

**Review by Sarthak32 — APPROVED** [review]
Hello , I have tested your PR as you mentioned it works well (as expected)!
Screenshot 2024-03-28 225213
Screenshot 2024-03-28 225334

**Review by iven-yao — APPROVED** [review]
I just reviewed this pull request, and the search bar works perfectly as expected.
image

**Review by SRamen1999 — APPROVED** [review]
This change is working as expected. I am able to search users by middle name on both admin and owner accounts.

Owner account

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/31c87bbc-214a-4a88-9aef-61aade3c7cbc


admin account

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/d52a0bc9-4d2e-4b05-9975-dc92df676b26

**Comment by MQChen211** [comment]
Hi, I tested the functionality and it worked out as expected.

**Review by MQChen211 — APPROVED** [review]

**Comment by Gayathr-2012** [comment]
Hi
I just reviewed it works as perfect as expected.
image

**Review by Jaiwin-4998 — APPROVED** [review]
HI I just check your PR and is working fine with the middle name.
Hereby attaching the image for the reference.

Screenshot 2024-04-03 at 1 21 17 PM

**Review by Tiantian-C — APPROVED** [review]
It works really nice!
Screenshot 2024-04-03 at 10 54 05 PM

**Comment by hiralsonip** [comment]
I have reviewed this PR and it is working as expected. We can search through middle names. Please review the below image.

PR2022

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected. Good work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/ff372753-bbb3-4be9-aaa1-aa7a832c744f

**Review by p-suram — APPROVED** [review]
Changes look good to me. Good Work. I have tested using Admin account. Please find video below. Backend PR Review is [here](https://github.com/OneCommunityGlobal/HGNRest/pull/786#pullrequestreview-1984845350)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/677594be-c557-4837-9cc7-d96a3ac2302b

**Review by meetpadhiar4 — APPROVED** [review]
hi, i re-reviewed your PR and it works as intended.

**Pull request merged**
