### PR TITLE
Xiao F make changing the date does not reset the reason

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-11-30 at 10 17 01

## Related PRS (if any):
N/A

## Main changes explained:
- Update file `src/components/UserProfile/ScheduleReasonModal/ScheduleReasonModal.jsx` for making the text box content does not change when date changes
- Create file `src/components/UserProfile/ScheduleReasonModal/CustomDatePickerInput.jsx` for a custom date picker for only showing Sundays as available options

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log in as user with any role
4. go to profile-> Schedule Blue Square Reason->Type in a new reason -> Change date to another -> Check if the reason typed in stays the same

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/a83dd840-73e9-4983-b211-591ea610e590

### CODE REVIEW

**Comment by keyunhuangg** [comment]
I am not sure if this was suppose to happen when I click on 'schedule blue square reason', there is already reason written on there. But after I edit it, the input stays the same across different dates 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/f8863256-baab-4d37-a095-b4538cb00dce

**Review by keyunhuangg — APPROVED** [review]
Tried it with a different account and everything was working! 
1) checkout of this brand
2) log in as volunteer 
3) schedule a blue square with reason 'testing' 
4) switch around the date and the input stayed the same 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/8ba9e9d4-6981-4e9a-b80c-da72f78f4142

**Comment by ptrpengdev** [comment]
Tested the PR with the Admin role. The code works as expected. 

- 12-17
image
- 12-10
image

**Comment by Lin1404** [comment]
Hi @tsunami776 , I have tested your PR and input kept the same after the date changed.
Screenshot 2023-12-07 at 11 25 54 AM
Screenshot 2023-12-07 at 11 26 11 AM

**Review by Lin1404 — APPROVED** [review]

**Review by Alforoan — APPROVED** [review]
I tried every month and it seems to work for every month. Nice!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/c8a05fce-16a0-429a-8618-d8885704b101

**Review by cvtqx — COMMENTED** [review]
Works well - when I change the date of a previously set reason, the reason text does not reset. 
Once small comment though - when I update the date but not the previously entered text, the save button is still disabled and I need to do a slight update in the text in order for the button to become active. This is a minor annoyance and I am not sure if it should be addressed in this PR or a separate one.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/161ad6e3-43ce-4740-be37-d6d89c900d1d

**Comment by tsunami776** [comment]
Hi @cvtqx, thanks for reviewing my PR! I think the reason for the 'Save' button is grey out is that the existing reason was fetched and nothing changed. After you change the blue square reason, then you can save the new reason.

**Comment by one-community** [comment]
> Works well - when I change the date of a previously set reason, the reason text does not reset.
> Once small comment though - when I update the date but not the previously entered text, the save button is still disabled and I need to do a slight update in the text in order for the button to become active. This is a minor annoyance and I am not sure if it should be addressed in this PR or a separate one.

Good catch! Creating a new bug for this

**Pull request merged**
