### PR TITLE
change the order of formatting commands & run it

### PR DESCRIPTION
**Pull request by EvianTan**
# Description
This PR is one of the re-enable Formatter and ESlint for our codes

## Related PRS (if any):
Jinchao did the previous works:
#938 
#983 

## Main changes explained:
My only manual change is in `package.json`
Other changes automated done by running command `npm run format`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
~~3. log as admin user~~
~~4. go to dashboard→ Tasks→ task→…~~
~~5. verify function “A” (feel free to include screenshot here)~~
3. log as any user account
4. test if any function work as normal, which means nothing break because of this PR.

## Note:
FYI: we have a "makre Prettier and ESLint work together plan [here](https://docs.google.com/document/d/1RmQw3GPADLfRJ5eYnbFa7iMJA1chw98dF3qwef1omCQ/edit)"

### CODE REVIEW

**Comment by freecode23** [comment]
hi, I am not so clear what am I supposed to do here. I dont understand step 4 and 5:

1. check into current branch
2. do npm install and ... to run this PR locally
3. log as admin user
4. go to dashboard→ Tasks→ task→…
5. verify function “A” (feel free to include screenshot here)

**Review by BaileyM96 — COMMENTED** [review]
Hello @EvianTan can you explain the changes and the how to test because I dont know what I need to test past the task --> tasks portion.

**Comment by Jiangwei-shi** [comment]
Do we just npm install and then run npm run format? Can you explain it clearly? And what effect should we expect

**Comment by beblicarl** [comment]
I think the description of this PR is not clear enough to replicate

**Comment by iTvX** [comment]
I don't know what to do, please be more specific.

**Comment by mahamakhan** [comment]
Don't exactly understand what to check here.

**Comment by n0vay** [comment]
How to verify function A?

**Review by HectorAgudelo — COMMENTED** [review]
This seems to be a interesting PR to review. However, like many have commented already, it is very unclear how to proceed. We need a better explanation on how to test it.

**Comment by EvianTan** [comment]
Hi All @HectorAgudelo @n0vay @mahamakhan @iTvX @beblicarl @Jiangwei-shi @BaileyM96 @freecode23 
I update the "how to test" test.
image

This PR related to this plan here - https://docs.google.com/document/d/1RmQw3GPADLfRJ5eYnbFa7iMJA1chw98dF3qwef1omCQ/edit?usp=sharing
I'm taking over previous developers' work, and clean it in this PR. Currently I'm on step 3. If you'd like to know more or work with me for formatting the whole repos, just let me know.

**Comment by n0vay** [comment]
Tested Website, there does not seem to be any bugs caused due to this. 
I noticed that the packagelock.json file does not change after doing npm install. Kudos to that.

image

**Review by shiva2096 — APPROVED** [review]
Hi @EvianTan 

I have checked the PR and the application is working without issues.

Screenshot 2023-07-18 at 8 15 19 PM

**Review by BaileyM96 — APPROVED** [review]
@EvianTan I tested your changes and did not run into any errors or bugs, great job!

## Screenshots

PR #1003 change the order of formatting

**Review by AaronPersaud — APPROVED** [review]
Hi, I've tested and everything works as expected!

<b>HGN Application after switching the order of commands in `format` script </b>

image

- no issues on screen or with any functionality
- no errors in console

Great work!

**Review by luisarevalo21 — APPROVED** [review]
Hello @EvianTan,

I tested your PR and works as intended. The application runs and doesn't crash.
Great work! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/5ee9f6a1-6e43-4f37-9617-94f6833d0079

**Review by igorrochadasilva — APPROVED** [review]
Hi @EvianTan !
I hope you are well =D

I tested your PR and works as intended great job!
1003_01_no-console-errors

**Review by n0vay — APPROVED** [review]

**Pull request closed without merging**
