### PR TITLE
Dhrumil - Fix Test File Throws an error and added test Cases

### PR DESCRIPTION
**Pull request by ddshah878**
# Description
Unit test for src/components/Teams/Teams.jsx

# Related PRS (if any):
Related PRs: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2788

## Main changes explained:

• Added a new file under tests called Teams.test.js
• Fixed the edge cases for the Teams file.

## How to test:

- check into the current branch
- do npm install and npm test Teams.test.js
- check if all test cases pass without any error.

## Screenshots or videos of changes:
Before: -
image
After: -
image

### CODE REVIEW

**Comment by pallavithorat** [comment]
I have reviewed the PR, and all test cases have been successfully passed.
Screenshot 2024-12-11 at 4 11 27 PM

**Review by anirudhsk2107 — APPROVED** [review]
All tests have passed
Screenshot 2024-12-12 142952

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (259)

**Review by ShraddhaShahari — APPROVED** [review]
I have tested this PR and all the test cases have been passed.
please find screenshot below for reference.
Screenshot 2024-12-13 at 3 24 57 PM

**Review by beblicarl — APPROVED** [review]

**Comment by beblicarl** [comment]
All tests passed successfully and the code is great

issue #2939

**Review by RashmiKY98 — APPROVED** [review]
Ran all the unit test cases. No issues found. Edge cases are covered.
image

**Review by KurtisIvey — APPROVED** [review]
Fantastic job! Very comprehensive code coverage here and you even covered edge cases. Zero complains from me on this one. Approved!
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
