### PR TITLE
Jay fix color discrepancy for pie chart in PeopleReport

### PR DESCRIPTION
**Pull request by jayyy-s**
# Description
Fixes color discrepancy for pie charts on people reports (medium priority bug)

image

## Related PRS (if any):
Use the latest development branch of HGNRest

## Main changes explained:
- Edit `/components/Reports/PeopleReport/components/PeopleTasksPieChart.jsx` so only the `dataLegend` prop changes with View All toggle
- Edit `/components/common/PieChart/PieChart.jsx` so there's a separate prop for chart labels called `chartLegend`

## How to test:
1. check into current branch
2. do `npm install` and `npm i` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ Reports dropdown→ Reports→People→type `Ilya` and check `Ilya Volunteer` (can check any other user that has tasks completed pie chart)
6. Verify that the colors on the pie chart match when toggling all and do not change when toggling between viewing all tasks and collapsing

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71467346/ab9a337f-53b4-4d07-8505-cddb0600cc1b

### CODE REVIEW

**Review by Kavil-Jain-514 — APPROVED** [review]
The functionality works perfectly fine.
The UI looks beautiful!!
image
image

I have a suggestion: in dark mode, the addYourProfilePic is not readable.
This is not related to PR but a suggestion if the image could be replaced with a better one where the text is visible
image

**Review by tianyangL11 — APPROVED** [review]
ed9292cade68f587cd296d7788c3c7c
The PR meets the requirements. The colors on the pie chart remain consistent when toggling between viewing all tasks and collapsing. Everything functions as expected. Great job!

**Review by shradac — COMMENTED** [review]
It matches when we collapse and expand, but noticed a discrepancy in the color in pie chart and tag for it. Check "Eat a pie 2", name tag is green and color on pie chart is pink.

week1-11

**Comment by beblicarl** [comment]
The colours did not match example "Eat a pie 2", "Eat a pie 3" and "Eat a pie 4"

[screencast-localhost_3000-2024.06.14-07_20_27.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/4af53f48-5cd4-4784-80de-f61bdd3f8b6c)

**Review by beblicarl — CHANGES_REQUESTED** [review]
The colours did not match example "Eat a pie 2", "Eat a pie 3" and "Eat a pie 4"

[screencast-localhost_3000-2024.06.14-07_20_27.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/3f48cd35-a37b-4e87-af6d-f1462e1f7dd9)

**Review by aaryaneil — CHANGES_REQUESTED** [review]
Some of the colors don't match on the pie chart. I've added a few to the screenshots, please look into it.
Screenshot 2024-06-15 at 12 53 25 AM
Screenshot 2024-06-15 at 12 54 56 AM
Screenshot 2024-06-15 at 12 55 04 AM

**Comment by jayyy-s** [comment]
> Some of the colors don't match on the pie chart. I've added a few to the screenshots, please look into it. Screenshot 2024-06-15 at 12 53 25 AM Screenshot 2024-06-15 at 12 54 56 AM Screenshot 2024-06-15 at 12 55 04 AM



> The colours did not match example "Eat a pie 2", "Eat a pie 3" and "Eat a pie 4"
> screencast-localhost_3000-2024.06.14-07_20_27.webm

This issue has been addressed in the latest commit and should now be fixed. Thank you for the thorough review + feedback!

**Review by kabraambika — DISMISSED** [review]
I reviewed the frontend PR with the latest backend on the development branch. The colors are displaying correctly in both dark and light modes. After using the view all and collapse functions, the colors match the associated legend as shown in the video.

https://github.com/user-attachments/assets/74f6a4da-363a-4c86-8922-b84cbb5d9ea7

**Review by ishan-miglani — APPROVED** [review]
Hi, I have verified the changes in this PR. the functionality works correctly. The colors on the pie chart match when toggling all and do not change when toggling between viewing all tasks and collapsing. Thanks!

https://github.com/user-attachments/assets/bc1503a5-dcd4-49c9-a4c9-22d7bbef7dae

**Review by SrikanthChowdary495 — APPROVED** [review]
The PR Working as expected. The colors on the pie chart match when toggling all and do not change when toggling between viewing all tasks and collapsing. 
color

**Review by angelalalacheng — DISMISSED** [review]
Hi, 
I use your branch `Jay_fix_color_discrepancy_pie_chart` and the latest develpent branch for backend. It all works good in both light and dark mode.

Screenshot 2024-07-21 at 5 12 09 PM
Screenshot 2024-07-21 at 5 12 45 PM
Screenshot 2024-07-21 at 5 13 02 PM
Screenshot 2024-07-21 at 5 12 54 PM

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey @jayyy-s 
I have reviewed the PR , the colors match fine with list items but i found some mis alignment in the components the hours column is missing in desktop view
image

**Comment by souravwalke** [comment]
Hi, I tested the changes in the PR and It all works as expected.

Screenshot 2024-07-27 at 11 26 19 PM

**Review by ReinaT5678 — DISMISSED** [review]
Looking at IIlya Volunteer and all the colors match the ones on the pie chart! I also played around with light and dark mode and changing between tasks and the colors did not change.

Screenshot 2024-07-29 at 9 29 16 PM

Screenshot 2024-07-29 at 9 29 30 PM

**Review by SatyashanthiT — APPROVED** [review]
I have tested this PR following the test instructions and have observed the features are working correctly
color img1
color img2

**Review by varunreddy03 — DISMISSED** [review]
I have verified this PR and viewed the report dashboard and the pie charts, the colors are consistent across both the light and dark mode. Great work with the UI and colors they are well suited for both modes

PR 2326_1
PR 2326_2

**Review by adityasure9 — APPROVED** [review]
Tested the PR and verified that the colors on the pie chart are consistent across both light and dark modes. The functionality works as expected when toggling between viewing all tasks and collapsing. Great work on maintaining the UI consistency.

Before,


After,

**Comment by jayyy-s** [comment]
> Hey @jayyy-s I have reviewed the PR , the colors match fine with list items but i found some mis alignment in the components the hours column is missing in desktop view image

I've addressed this in the latest commits. This wasn't in the original scope of the bug, but I don't think it's worth creating a new issue for it. Thanks for catching it so we could fix it in this PR.

**Review by Lemonnycodes — APPROVED** [review]
Hi,

I have tested the changes introduced in this PR:

- Verified that the pie chart colors for tasks completed by users (e.g., Ilya Volunteer) remain consistent when toggling between viewing all tasks and collapsing the view.
- The colors on the pie chart match and do not change during toggling, as expected.
- The feature works correctly in both light and dark modes

Screenshots:
PR 2326 (1)
PR 2326 (2)
PR 2326 (3)

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Comment by beblicarl** [comment]
the colors match perfectly now. This functionality works as intended. Great work

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all!

**Pull request merged**
