### PR TITLE
Bhuvan - Report Page and report components testfiles added

### PR DESCRIPTION
**Pull request by bhuvan-dv**
# Unit test for **ReportPage, ReportBlock, ReportCard, ReportCard_2 and ReportHeader**  component

## Main changes explained:

Added Five new files names 
1. [ReportPage.test.js](src/components/Reports/sharedComponents/ReportPage/__test__/ReportPage.test.js)
2. [ReportBlock.test.js](src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/__test__/ReportBlock.test.js)
3. [ReportCard.test.js](src/components/Reports/sharedComponents/ReportPage/components/ReportCard/__test__/ReportCard.test.js)
4. [ReportCard_2.test.js](src/components/Reports/sharedComponents/ReportPage/components/ReportCard/__test__/ReportCard_2.test.js)
5. [ReportHeader.test.js](src/components/Reports/sharedComponents/ReportPage/components/ReportHeader/__test__/ReportHeader.test.js)

## How to test:
1. check into current branch 
 ```bash
   git checkout bhuvan-report
```
2. do `npm install` and `...` to run this PR locally
you can choose to run the files individually or as whole (jump to step 7)
3. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/Reports/sharedComponents/ReportPage/__test__/ReportPage.test.js
```
image
4. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/Reports/sharedComponents/ReportPage/components/ReportBlock/__test__/ReportBlock.test.js
```
image
5. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/Reports/sharedComponents/ReportPage/components/ReportCard/__test__/ReportCard.test.js
```
image
6. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/Reports/sharedComponents/ReportPage/components/ReportCard/__test__/ReportCard_2.test.js
```
image
7. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/Reports/sharedComponents/ReportPage/components/ReportHeader/__test__/ReportHeader.test.js
```
image

OR you can choose to run all together
8. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/Reports
```
image

## Note:
check if all the test cases pass without any errors pertaining to **ReportPage, ReportBlock, ReportCard, ReportCard_2 and ReportHeader** files only

### CODE REVIEW

**Review by aaryaneil — COMMENTED** [review]
In the Pull Request provide the relative paths to the tests.

**Review by hbodgal — APPROVED** [review]
It passes all test cases you have added.

**Review by aaryaneil — APPROVED** [review]
All test cases passed.
Screenshot 2024-04-06 at 12 56 21 AM
Screenshot 2024-04-06 at 12 56 25 AM
Screenshot 2024-04-06 at 12 57 55 AM
Screenshot 2024-04-05 at 6 09 58 PM
Screenshot 2024-04-05 at 6 10 07 PM
Screenshot 2024-04-05 at 6 11 35 PM
Screenshot 2024-04-05 at 6 11 40 PM
Screenshot 2024-04-05 at 6 12 36 PM
Screenshot 2024-04-05 at 6 12 41 PM
Screenshot 2024-04-05 at 6 18 51 PM
Screenshot 2024-04-05 at 6 20 07 PM
Screenshot 2024-04-05 at 6 20 12 PM

**Review by ImzIssa — APPROVED** [review]
Hello, I've tested this PR and the test cases passed. Nice Work.

PR 2119
PR 2119 (2)

**Review by bhuvaneswarignanasekar — APPROVED** [review]
I have reviewed your PR. All test cases passed. 
Screenshot 2024-04-08 at 4 31 27 PM
Screenshot 2024-04-08 at 4 35 50 PM
Screenshot 2024-04-08 at 4 35 16 PM
Screenshot 2024-04-08 at 4 34 08 PM
Screenshot 2024-04-08 at 4 33 32 PM
Screenshot 2024-04-08 at 4 32 42 PM

**Comment by beblicarl** [comment]
All tests passed successfully. Kindly change all paths to relative paths so it is easier for others to test

image

image

image

image

image

image

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
