### PR TITLE
Shrey unit tests TangibleInfoModal

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for TangibleInfoModal component

## How to test:
1. check into current branch
2. do `npm install` 
3. npm test TangibleInfoModal.test.js
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-12-21 at 11 37 52 PM

### CODE REVIEW

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 17 - PR1

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-29 at 11 55 31 AM

**Comment by mianmiantea2019** [comment]
All test cases passed successfully. 

image

**Review by bienzguoa — COMMENTED** [review]
All test cases passed. Tests are well-structured and focused on the primary functionality of components. One suggestion is adding some tests for edge cases can be considered.

Screenshot 2023-12-29 at 11 07 59 PM

**Review by yangfan2001 — APPROVED** [review]
Hi, I have tested your PR and all tests are passed, great job!
image

**Comment by Lin1404** [comment]
All test cases passed successfully. Good job!
PR1737_1

**Review by Lin1404 — APPROVED** [review]

**Comment by n0vay** [comment]
LGTM
image

**Review by n0vay — APPROVED** [review]

**Pull request merged**
