### PR TITLE
Kaikanes infringe bugfix

### PR DESCRIPTION
**Pull request by lacnoskillz**
# Description
The people report page was not mobile responsive and the infringement button was bugged/ would not close when opened.

## Related PRS (if any):
This frontend PR only

## Main changes explained:
- renamed and created another state variable for modal close/open
- css/jsx changes for a more mobile friendly design

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin 
5. go to dashboard→ reports→ people→ choose a user
6. verify `show infringements graph` button modal closes properly
7. verify page is mobile responsive

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/2544444b-1382-4705-8403-f90050e10fa5

## Note:
I still don't know the purpose of the modal

While making these changes I discovered other functionalitys hidden off to the side.
now in view and works when clicked
image
(note the show dates/ other fuctionality of the graph can look cluttered and over lap other dates and should be addressed in another PR.) 
image

Note when viewing in small view ports like iphone it seems really small on pc but you will be able to use fingers to zoom in while on mobile.

ScreenShot below
moble infringement copy

### CODE REVIEW

**Comment by Cavein254** [comment]
@lacnoskillz  tested the pr as admin and everything works as expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/b4267671-f227-4daa-834e-58129755bc79

**Review by ChengyanOo — DISMISSED** [review]
Hi @lacnoskillz,

I've had the chance to review and test your recent implementation. It's impressive how well it functions, and your code is notably clean and well-structured. I do want to point out one aspect that might need a bit of tweaking. When the infringement graph is displayed, it might be more intuitive for users if the button label changed to 'Close Graph'. Currently, the label doesn't change, which might be a bit unclear for users. I've attached a video to demonstrate how I tested your implementation. Keep up the great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/716c007d-30f3-436b-ae12-9a74a3e79f44

**Comment by lacnoskillz** [comment]
@ChengyanOo Thank you for your review and suggestion
I think your right it would be more intuitive for the button to change from 'show' to 'hide'
I added those changes.
If you could view it again and test that would be greatly appreciated

**Comment by mianmiantea2019** [comment]
Hi @lacnoskillz,

I tested the PR as admin and everything works as expected. The update on the button from 'Show Infringements Graph' to 'Hide Infringements Graph' is successful. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/edc9abc8-80a3-43de-bffd-5f9d61011c17


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/9cb5fcf7-92fe-4e47-8c76-7684d8ef91d0

**Review by bienzguoa — APPROVED** [review]
Good job! Works as described for both web and mobile view.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92126559/b9996911-8025-4f1a-982b-f29bec57e751

**Review by Sophie-lei — APPROVED** [review]
Hi, I tasked this PR in the admin role. I found that the infringe button can show the graph perfectly for both the mobile side and the laptop side. After clicking the infringe button, the button changes to hide the graph, which is easy to understand. I think it works well! Please see the video for more information. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/98ee3264-8977-4120-97b3-766423945328

**Review by beblicarl — APPROVED** [review]

**Review by Renanluizssx — APPROVED** [review]
Hi @lacnoskillz, i tested your application and it is as expected as you said. The modal is opening and closing correctly, and the responsive is very nice both small screen and large screen, congratulations.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/5bd8277f-4840-413e-a4a4-77166ebec0e8

**Review by X1aoZhang99 — APPROVED** [review]
Hi Kaikanes,
  
I took a look at this PR in the admin role and noticed that the infringe button accurately displays the graph on both mobile and laptop platforms.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/4309a001-6d5b-4ded-8b9b-1c116ed3b153

**Comment by yuhuimin1996** [comment]
Hi Kaikanes,
I've tested this PR using admin user account, the two main changes worked well as you describe. The 'show infringements graph' button can open and close the modal properly, and this page is responsive properly. Well done!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108281570/459d346f-7be2-424d-87ea-7278d94576ff

**Review by 666saofeng — APPROVED** [review]
Hi, I've tested this PR. The modal opens and closes properly on both mobile and laptop. Congrats!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/e5f355c2-f1d8-4111-b7b2-c76d174516e7

**Review by pshereen — APPROVED** [review]
After clicking the infringe button, the button changes to hide the graph, which is easy to understand. I think it works well! Please see the video for more information.

And it is worth mentioning that you have used descriptive and meaningful variable names, for e.g., changed variable 'show' to 'graphVisible'.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/5ba00538-5f02-4c7f-9b37-f7713fb9d64d

**Review by keyunhuangg — APPROVED** [review]
Logged in as owner account. Pick a random user to test, and verified that all graph options closed properly with both computer view and phone view

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/42f53bdc-edf6-460d-8c72-fb7dd9eb1768

**Comment by Vishala09** [comment]
Working great. The button is opening and closing the graph now.
[Untitled_ Jan 18,2024 4_06 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65274029/c1ff9839-0c52-4c5a-b2a2-75b681d2aa0e)

**Review by rusalshrestha98 — APPROVED** [review]
Can confirm that the `Show/Hide Infringements Graph` button is opening/hiding the graph. Can also verify that the modal will now close on both desktop and mobile by clicking outside the modal, clicking on the "X" button on the top right of the modal, and by clicking the "close" button on the bottom right of the modal.

However, as the author mentioned in the PR notes, I am not sure what the purpose of this modal is either.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/48131438/ab015417-ea94-4f09-a198-b6258b57354d

**Review by Vishala09 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
