### PR TITLE
Nahiyan_dark mode on Dashboard and Timelog page

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
This PR is only implementing dark mode on the Dashboard page and Timelog page.

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Created a dark mode button on the nav bar
- New state variable
- Changes on dashboard components like Weekly Summaries, Summary Bar, Leaderboard, Tasks and Timelogs table, Badge section. 

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to the dashboard
6. verify each component flips to dark mode when the button clicked
7. Make sure they flip back to light mode
8. Do the same for the timelog page

## Screenshots or videos of changes:
Screenshot 2024-04-01 174340
Screenshot 2024-04-01 174430
Screenshot 2024-04-01 174500
Screenshot 2024-04-01 174529
Screenshot 2024-04-01 174556

## Note:
If you have any suggestions to make dark mode better, please let me know.

### CODE REVIEW

**Review by linkhanthtel — DISMISSED** [review]
Looks good! Each component flips to dark mode and they also flip back to light mode  when the button clicked.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/5ee8e927-c311-41e4-b163-d5a620374c48

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi, I just checked your PR an it is working fine with dark and light theme.

Screenshot 2024-04-02 at 7 44 31 PM

Screenshot 2024-04-02 at 7 43 36 PM

**Comment by Gayathr-2012** [comment]
Hi 
I've reviewed your PR. I noticed that when I click on "Summary" (http://localhost:3000/timelog), it redirects me to the timelog page, but the header I attached in the last image doesn't appear immediately. After refreshing, it becomes visible. Please check this issue. otherwise it works perfect.

image

image

image

image

image

Thank you

**Review by ImzIssa — DISMISSED** [review]
Hello, I've reviewed your PR and the toggle works great. Nice work

PR 2105
PR 2105 (2)


PR 2105 (3)
)

**Review by aaryaneil — DISMISSED** [review]
The dark mode toggle works really well. Good work.
Screenshot 2024-04-03 at 10 45 49 AM
Screenshot 2024-04-03 at 10 45 54 AM
Screenshot 2024-04-03 at 10 46 18 AM
Screenshot 2024-04-03 at 10 46 27 AM
Screenshot 2024-04-03 at 10 46 37 AM
Screenshot 2024-04-03 at 10 47 17 AM

**Comment by Nahiyan-16** [comment]
> Hi I've reviewed your PR. I noticed that when I click on "Summary" (http://localhost:3000/timelog), it redirects me to the timelog page, but the header I attached in the last image doesn't appear immediately. After refreshing, it becomes visible. Please check this issue. otherwise it works perfect.
> 
> image
> 
> image
> 
> image
> 
> image
> 
> image
> 
> Thank you

Great catch! My recent commit should fix that issue.

**Comment by anandsesha** [comment]
Hi, I've reviewed your PR and the dark mode looks great!

-  Each component in dashboard and timelog flips to dark mode and back to light on toggle.
- Timelog header is visible and issue mentioned above is resolved.

**Sugggestion**: Tooltip text partially goes out of the screen as shown in the first screenshot. In DarkModeButton.jsx - changing placement to 'auto' or using getBoundingClientRect() to dynamically adjust placement according to viewport may help resolve this issue. 

Tooltip Toggle issue

Screenshot (708)
Screenshot (709)
Screenshot (710)
Screenshot (711)
Screenshot (712)

**Review by bhuvaneswarignanasekar — DISMISSED** [review]
Hi, I've reviewed the PR. Toggle works. 
Screenshot 2024-04-03 at 2 06 25 PM
Screenshot 2024-04-03 at 2 10 39 PM
Screenshot 2024-04-03 at 2 09 39 PM
Screenshot 2024-04-03 at 2 06 37 PM

**Comment by SushmithaPrathap** [comment]
Hey, I've gone through your PR that adds a dark mode toggle functionality  to the Dashboard, Summary and Timelog pages. Here's what I found

- The dark mode toggle is functioning smoothly across these pages.
- Noticed that the light (sun) icon seems a bit off-center, leaning towards the left. It might need a bit of adjustment to sit right in the center.
- The helper text appears to be overflowing the screen boundaries. This could potentially cut off important information for users on smaller screens.
- On the Timelog page, when scrolling up, there's a noticeable white space at the bottom. It seems like the dark mode's background doesn't extend fully, possibly due to a fixed height setting somewhere.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/011f3c1e-c056-4d5c-af21-ecbdc9ea5bc6

dashboard
timelog
timelog+white
Screenshot 2024-04-03 at 5 47 06 PM (2)

**Review by Parth-tech — DISMISSED** [review]
Hi,
The dark mode button works as intended and no other functionality was affected by this change. 
`Suggestion:` The Sun/Moon icon is not center-aligned in the button. It would be great if we can resolve that. I notice that `0px padding` for Sun nearly center-aligns it. And for Moon you can keep `10px padding`.

Screenshots:
Screenshot 2024-04-03 at 2 54 40 PM
Screenshot 2024-04-03 at 2 54 25 PM
Screenshot 2024-04-03 at 2 54 15 PM
Screenshot 2024-04-03 at 2 53 55 PM
Screenshot 2024-04-03 at 2 53 34 PM

**Review by Tiantian-C — COMMENTED** [review]
I logged in as  a volunteer and tested, it works very well.
Screenshot 2024-04-03 at 3 50 23 PM

**Review by j-corp-25 — DISMISSED** [review]
Hi @Nahiyan-16 ,

I tested the toggle on Volunteer and Admin. 

Dashboard, Timelog, Badge modal.

Below is the video of the tested feature


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/d75253b2-b809-4d1c-9a19-1513aa172cc1

**Review by SRamen1999 — DISMISSED** [review]
Everything works as expected. Each component flips to dark mode and they also flip back to light mode when the button clicked.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/9fed082e-4f7c-4f3f-bf2d-f70a99f66473

**Review by hbodgal — DISMISSED** [review]
Its working fine. The dark mode remains as it should be on navigating to other pages as it should be. 

PR_2105

**Review by Renanluizssx — DISMISSED** [review]
Hello Nahiyan, i reviewed your application and it's running correctly, see my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/3738a5f5-0a19-4e68-a842-ab52fd80596f

**Review by brandta-1 — DISMISSED** [review]
# Review
All listed components correctly change back-and-forth to their darkmode and lightmode colors
# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/d0fddc29-9ec9-4485-9a09-f5406243a337

**Review by tdkent — DISMISSED** [review]
Light/dark mode toggle switch works correctly on both the Dashboard and Timelog pages. The dark mode setting also persists after logging out and logging in again.

My only suggestion is making sure the icons are centered inside background circle in a subsequent PR, perhaps in a subsequent PR.

Screenshot 2024-04-06 at 9 39 08 AM

**Review by p-suram — DISMISSED** [review]
Looks good. I am able to toggle between dark and light modes and seeing visible changes in Dashboard and Time log pages. Tooltip works correctly.

image
image

**Comment by MQChen211** [comment]
Hi, I tested your PR and the dark mode works as expected.
截屏2024-04-11 15 38 16
截屏2024-04-11 15 39 06
截屏2024-04-11 15 39 40

**Review by MQChen211 — DISMISSED** [review]

**Comment by hiralsonip** [comment]
Hello...I have tested this PR and it is working as expected. 

PR2105_dashboard

**Comment by metaphor987** [comment]
Hi Nahiyan, 

I tested the changes using both admin and volunteer accounts. Everything works perfectly on the dashboard page. There's only a small issue with the timelog page. When clicking to open the "Weekly Summary" section in the timelog page, the top header is lost, both in dark and light mode. Refreshing the page solves the issue and everything just goes back to normal. The following recording and screenshots show the details. Thank you!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/abe8d21f-df59-4fa7-ba97-b2c053a4dbbd

Screenshot 2024-04-13 at 2 46 32 PM
Screenshot 2024-04-13 at 2 48 26 PM

**Review by lacnoskillz — DISMISSED** [review]
Hello @Nahiyan-16 
I pulled your changes and tested them and the dark mode works as you described.
I'm a big fan of dark mode and love this new feature
Below are some screen shots of the Summary page and tasks/time log
Functionality seems to not be affected and also looks good on mobile
Nice work!
Pr2105 dark mode summary page
Tasks and timelog dark mode
##  #Note mobile Icons in mobile drop down is very slightly off 
dark mode mobile 2105

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Comment by Nahiyan-16** [comment]
@metaphor987 Great catch, I just fixed this issue in the recent commit.

**Comment by Nahiyan-16** [comment]
@lacnoskillz Fixed the alignment issue on mobile view.

**Review by j-corp-25 — DISMISSED** [review]
Hi @Nahiyan-16 ,

Darkmode is still working as intended. Timelog changes as well as Dashboard

Below is my video testing the updated changes:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95154804/86b196de-9e14-4b03-ac6d-952e82eb787c

I also want to mention that the icon is slightly off centered in mobile screens,


MobileViewIcon

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
