### PR TITLE
Shiwani AddNewTeamModal Unit Test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for AddNewTeamModal.jsx

## Main changes explained:
- Added 7 test cases: renders modal when isOpen is true, renders modal when isOpen is false, check modal title and its label, check team name option, check click on one of the options, check add team button, check cancel button

## How to test:
1. check into current branch
2. do `npm test src/components/UserProfile/__tests__/AddNewTeamModal.test.js` 
3. Check if all the test cases pass without any errors or warnings

## Screenshots or videos of changes:
Screenshot 2024-01-03 at 6 37 34 PM

### CODE REVIEW

**Comment by hdani18** [comment]
There is a typo in the above mentioned command to run this unit test. 
Here is the correct cmd: npm test src/components/UserProfile/__tests__/AddNewTeamModal.test.js

**Review by hdani18 — APPROVED** [review]
Screen Shot 2024-01-06 at 5 21 08 PM
LGTM!!

**Review by bienzguoa — APPROVED** [review]
All these tests rendered correctly, codes are clear. Test cases are passed!
Screenshot 2024-01-06 at 4 42 54 PM

**Review by vikrambadhan — CHANGES_REQUESTED** [review]
Hi, I tested your PR and encountered this error.

Week 19 - PR4

**Comment by Shiwani99** [comment]
> There is a typo in the above mentioned command to run this unit test. Here is the correct cmd: `npm test src/components/UserProfile/__tests__/AddNewTeamModal.test.js`

Hi,
Thank you. I have changed it now.

**Comment by Shiwani99** [comment]
> Hi, I tested your PR and encountered this error.
> 
> Week 19 - PR4

Hi,
Thank you. There was a mistake in the command I have changed it so you check now with the updated one.

**Review by ChengyanOo — APPROVED** [review]
Hi @Shiwani99,

Great job on creating the unit tests. However, I noticed that the command used for running the tests needs a slight adjustment. The correct command should be: npm test src/components/UserProfile/__tests__/AddNewTeamModal.test.js. I've attached a screenshot for your reference.

Screenshot 2024-01-10 at 14 05 00

**Comment by Shiwani99** [comment]
> Hi @Shiwani99,
> 
> Great job on creating the unit tests. However, I noticed that the command used for running the tests needs a slight adjustment. The correct command should be: npm test src/components/UserProfile/**tests**/AddNewTeamModal.test.js. I've attached a screenshot for your reference.
> 
> Screenshot 2024-01-10 at 14 05 00

Thank you. I have made the change now.

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2024-01-12 at 10 04 44 PM

**Review by 666saofeng — APPROVED** [review]
All tests passed!
image

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed as expected. Please watch the overview video below for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/3aafb8fd-074a-4c2b-bd65-2ab55c591775

**Review by X1aoZhang99 — APPROVED** [review]
Hi Shiwani,

All tests passed. Nice work! 

Screenshot 2024-02-07 at 12 43 11

**Review by TapanPathak — APPROVED** [review]
Hi, All test cases passed!

Screenshot 2024-02-10 at 12 40 51 PM

**Review by peterson337 — APPROVED** [review]
Hi Shiwani, all Tests passed. Good job!

a

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed! Great Job!

Week 25 - PR5

**Review by ChengyanOo — APPROVED** [review]
I've reviewed your code and am impressed by the thoroughness of your test coverage for the component. Excellent work!
Screenshot 2024-02-27 at 11 22 30

**Review by ChengyanOo — APPROVED** [review]
I've reviewed your code and am impressed by the thoroughness of your test coverage for the component. Excellent work!
Screenshot 2024-02-27 at 11 22 30

**Review by scoopstroop92 — APPROVED** [review]
Good job on the test cases Shiwani !
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
