### PR TITLE
Reina filtering UI badge management

### PR DESCRIPTION
**Pull request by ReinaT5678**
# Description
Made the filtering UI for badge management more user friendly by adding several features to filter by name, type, or rank.

## Related PRS (if any):
This frontend PR is related to the development backend PR.

…

## Main changes explained:
- Allows users to sort the badges in ascending or descending order according to name and rank.
- Added a button for additional features.
- Users can also search by name, type, and can filter by rank.
…

## How to test:
1. check into current branch
2. do npm install and npm run start:local to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ Other Links → Badge Management → Badge Development → Add Filters
6. Verify that the filter inputs (Name, Type, and Rank) under the Add Filters buttons works as expected

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/68ce3ffb-e161-408c-a3ee-7298fee46e1d

### CODE REVIEW

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
I don't know why but the Filter button is not visible. Please let me know if I am missing something.
Screenshot 2024-09-02 at 1 11 07 AM
Screenshot 2024-09-02 at 1 12 11 AM

**Comment by ReinaT5678** [comment]
@JatinAgrawal94 Did you look under the Badge Development tab? If it doesn't show it there, I'll take a look at it!

**Review by RishithaMamidala — CHANGES_REQUESTED** [review]
@ReinaT5678 
I have used the backend development branch, and I've run this branch and it mostly works as expected.

I do have a suggestion: 
when we input a space in the filter, it currently filters out all the entries. Instead, we could remove any leading or trailing spaces. This would prevent accidental space inputs from affecting the filtering process.
PR 2363 - 2
PR 2363 - 1
PR 2636
 accidental space inputs from affecting the filtering process.

**Review by manikittu810 — APPROVED** [review]
Hello @ReinaT5678 
Followed steps mentioned in the description. Everything is working as mentioned.
Screenshot 2024-09-03 at 10 52 13 PM
Good work.

Thank you.

**Review by sri0606 — CHANGES_REQUESTED** [review]
Hello @ReinaT5678, I have reviewed the changes you made and I have some suggestions:

* As of now, if there are any trailing or leading spaces, the search doesn't work as expected. You can strip the input text first.
* An input text field for rank too can be useful if we want to check a specific rank.

Please refer to the video below:

https://github.com/user-attachments/assets/63729944-1c66-4dbe-844f-5840f870dc69

**Review by beblicarl — CHANGES_REQUESTED** [review]
The filter button does not appear on the UI

image

**Review by beblicarl — DISMISSED** [review]
this functionality works as intended and the code is great

[screencast-localhost_3000-2024.09.05-14_12_47.webm](https://github.com/user-attachments/assets/3711ba7f-4ac4-4cbc-9a4d-ed14b080b825)

**Comment by sam19981** [comment]
tested as an Administrator on the Front End branch [reina-filtering-UI-badge-management] and the Backend branch [Development]. The functionality works as expected.

However, I was wondering—since the badge names and types are predetermined, wouldn't a dropdown menu be more convenient than a search bar? What do you think, @ReinaT5678?

backend-devlopment:frontend-Reina filtering UI badge management
Badge_management:Filter_button_screen
filter_input_search

**Review by sam19981 — CHANGES_REQUESTED** [review]

**Comment by ReinaT5678** [comment]
> tested as an Administrator on the Front End branch - reina-filtering-UI-badge-management and the Backend branch - Development. The functionality works as expected.
> 
> However, I was wondering—since the badge names and types are predetermined, wouldn't a dropdown menu be more convenient than a search bar? What do you think, @ReinaT5678?
> 
> backend-devlopment:frontend-Reina filtering UI badge management Badge_management:Filter_button_screen filter_input_search

Hi! I think that's a good idea for the types, however users can create a new badge with a new name. I'll reach out to you once I make the dropdown for the types!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
