### PR TITLE
Zijie lint fix update password

### PR DESCRIPTION
**Pull request by iTvX**
# Description
Lint fix for Update Password component

## How to test:

1. checkout to this branch, then `npm install`, `npm run start:local`
2. **Record a video to verify that the password update function is working normally.**

~~1. `rm .eslintignore`
3. `npx eslint src/components/UpdatePassword/UpdatePassword.jsx`
4. `npx eslint src/components/UpdatePassword/index.js`~~

### CODE REVIEW

**Review by DavidC0126 — DISMISSED** [review]
Hi @iTvX I tested it and it works as intended.

lintfix_updatePassword

**Review by Iris-Song — APPROVED** [review]
Hi I have logged in as admin and tried to update passwords. But something went wrong.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58033867/91a62a42-71f6-4caf-a89b-5185f65472b1

**Review by Shubhu0 — CHANGES_REQUESTED** [review]
HI @iTvX I reviewed the PR and it did not work. I tried changing my password and it did not work and threw an error at any attempt


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/fc6d2fa1-304e-46fb-8d3c-f6ca34a00589

**Comment by palakgosalia** [comment]
Hey, I tested your code but I wasn't able to update the password. Got an error. Details in the video. Thank you


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/486ba199-1373-481a-bdde-be864542299f

**Comment by iTvX** [comment]
@palakgosalia 

@Shubhu0 

@Iris-Song

Hi, I have tried on dev branch, same issue. So this bug is not related to this pull request

**Review by Bali2Mohit — COMMENTED** [review]
Hi @iTvX , I have tested your changes. Your code changes looks good.

But, there is some issue with the updatePassword service, which need a fix. At the moment we are getting 403 Unauthorised  while trying to update password for any user.

Screenshot 2023-11-03 at 14 59 46

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hib @iTvX, tested this PR locally using admin account but getting an error when trying to update my password. Refer to my test recording. Thank you.

Test rec:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/688af1c7-93a9-4ec0-aef2-293c065a2145

**Review by sahilpatel18 — COMMENTED** [review]
I logged in as admin and attempted to update my password, but something went wrong.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/24741818/18cc80b7-ba24-42c8-ba1a-1d13b63c61ed

**Comment by Cavein254** [comment]
Hi,
I am also unable to update the password while logged in as admin
[screen-recorder-mon-nov-20-2023-11-13-22.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/27f74242-51f5-48ce-a534-579a7e983eef)

**Comment by Cavein254** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/314ecf0b-7885-4ef7-b579-b01488ce3bd2

**Review by Alforoan — CHANGES_REQUESTED** [review]
It doesn't seem to work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/c7b19f39-3071-4838-b0d1-a8ddbecffdda

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
