### PR TITLE
add format action and run format

### PR DESCRIPTION
**Pull request by EvianTan**
# Description
This PR is for adding a new action in Checks

## Related PRS (if any):
include some changes in #1003 

## Main changes explained:
`.github/workflows/node.js.yml`:  add `npm run format` action here for GitHub checks
`package.json`: change the order when run `npm run format:fix`
other files are directed changed by run `npm run format:fix`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any user account
4. test if any function work as normal, which means nothing break because of this PR.

## Screenshots or videos of changes:
image

## Note:
NA

### CODE REVIEW

**Review by shiva2096 — DISMISSED** [review]
Hi @EvianTan 

I have test the PR, and I found no issues while running the application.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/26687177/98442645-939b-4dda-8456-315b2a261ed0

**Review by luisarevalo21 — DISMISSED** [review]
Hello @EvianTan,

I tested your PR and works as normal. 
The application
Screenshot 2023-07-19 at 8 57 53 PM
 doesn't crash and runs correctly. Great work.

**Review by DavidC0126 — DISMISSED** [review]
Hi @EvianTan I have tested this PR, and it runs as normal, no any problem occurs.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/88369ab0-0396-4943-b0ec-ad3b4a0e1b4c

**Review by HectorAgudelo — DISMISSED** [review]
The PR performs as expected. Ran  npm run format and npm test, and the app did not show any signs of error.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/d9c71f69-a725-42f6-90c8-ee1ef64f25fe

**Comment by Shreyj14** [comment]
Hi @EvianTan the PR does not break anything and there were no issues while running the application.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/02944efc-fac3-4417-8ce8-15a1be255a03

**Review by Shreyj14 — DISMISSED** [review]

**Comment by Shreyj14** [comment]
@one-community there are 5 approvals to this PR.

**Review by vemanamadhu — DISMISSED** [review]
Hello EvianTan,

The changes look good and everything seems to be working as expected

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13665284/e3da9a27-d532-4a79-8460-69b10ec3df5d

**Review by ramyaram2092 — APPROVED** [review]
No issues while running the application. Approving the PR on the same note 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/2585be91-7616-4b1c-826b-a3d147f62524

**Review by BaileyM96 — APPROVED** [review]
Hello @EvianTan  I have tested your PR and everything works, great work!

**Review by AaronPersaud — APPROVED** [review]
Hi, I've tested and it works as expected!

<b>Testing functionality on HGN</b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/016e4bbe-ad01-42a0-81cd-94ced3c41fcb

- as you can see everything is functioning as normal

Great work!

**Comment by iTvX** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/a488ce77-7971-4bff-b6dc-73e37427fdbb

I have tested your pr, no issue occur during the test

**Review by eduvarjaor — DISMISSED** [review]
Hi @EvianTan 

I tested this PR and everything it's OK! Good job!
Screenshot_1

**Review by n0vay — APPROVED** [review]
Good Job! everything runs perfectly.
image

**Review by yaow62023 — APPROVED** [review]
Both volunteer site and manager site have been tested. All the features are work as described.

**Comment by one-community** [comment]
Thank you all, this is the most approved PR I've seen. I'll merge it once merge conflicts are resolved and Yiyun clarifies what I need to do with PR #1003

**Review by sxiong5 — DISMISSED** [review]
Hey @EvianTan, the app worked as normal!
Screenshot 2023-07-24 at 15 45 13
Screenshot 2023-07-24 at 15 44 31

**Pull request merged**
