### PR TITLE
Vijay Anand separate components for filter and view reports by date range section in reports page

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description
Screenshot 2024-07-23 at 8 54 39 PM

## Related PRS (if any):
To test this Frontend PR you need to checkout the Development branch for backend.
…

## Main changes explained:
- Made filter and search part related code into a separate component.
- Made date picker and show total project/people/team report buttons related code into separate component
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to dashboard→ Reports
6. verify whether the filter component shows all the active projects/teams/people when the user chooses the "Active" radio button.
7. verify whether the filter component shows all the inactive projects/teams/people when the user chooses the "Inactive" radio button.
8. verify whether the filter component shows all the projects/teams/people when the user chooses the "All" radio button.
9. verify whether the user is able to view the total project/people/team report when the user clicks Show Total Project/People/Team Report buttons.

## Screenshots or videos of changes:
-Steps to test filter and search feature.

https://github.com/user-attachments/assets/400e3840-b3f8-4c2a-a238-c805702a25bd

-Steps to test view view the total project/people/team report feature.

https://github.com/user-attachments/assets/38ccc41a-ded7-43ba-986f-84caa2d3e82f

## Note:
This is not a new feature/bug fix; kindly add the suggestions/improvement in the bugs doc.

### CODE REVIEW

**Review by Pranay-ai — APPROVED** [review]
Hey @vijay10pk 
The PR is Working as expected.
Thank You.

https://github.com/user-attachments/assets/5b3fcdc4-788b-4f50-a021-0aa5633ea305

**Review by SrikanthChowdary495 — APPROVED** [review]
I have tested this PR. I have filter component that shows all the active projects/teams/people when the user chooses the "Active"  & "Inactive" & "All "radio buttons. I have also verified the total count if it is showing correctly. 

I have also been able to click the Total Project/People/Team Report buttons is gave me Bara chart Report. 

I have attached a video & image for you to look over. 

Great Work !!!

https://github.com/user-attachments/assets/d95716c1-6749-4a12-829f-7edda2cf4673

reports

**Review by Chetan0606 — APPROVED** [review]
Followed the description and verified the PR accordingly. Everything looks good and here's my observation

https://github.com/user-attachments/assets/e2617fd2-66d5-41f9-abe4-9cfdbc2f4afa

**Review by Gauravmg6 — APPROVED** [review]
Everything works as expected 


https://github.com/user-attachments/assets/0c8cbfc7-0fe3-443b-864e-ad432f4a1805

**Review by SatyashanthiT — APPROVED** [review]
I reviewed this PR by checking out the current branch, installing dependencies, and running the application locally. I verified that the filter component correctly shows active, inactive, and all projects/teams/people based on the selected radio button, and that the total project/people/team report buttons work as expected. The separation of components improves code organization and maintainability. I recommend approving this PR.

https://github.com/user-attachments/assets/1128ca6b-df2c-4aee-a408-759517da0381

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and it's working as expected for different filter options selected.


https://github.com/user-attachments/assets/ca34afdc-ac28-4d72-9eae-58760e30a554

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as described. Good work.

https://github.com/user-attachments/assets/78804557-54ff-444b-9dae-f6e7743111c7

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
