### PR TITLE
Anand_Added Date Error message validation in Add Task Modal 

### PR DESCRIPTION
**Pull request by anandsesha**
# Description
This PR adds validation for Start and End dates in the Add Task Modal, displaying error messages for invalid dates.
PR description

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Added error message validation in `AddTaskModal.jsx` for Start Date and End Date, ensuring users input correct date values.
- Included separate error messages in `messages.js` for each date field to inform users of the specific field with invalid input.
- Fixed error messages persisting on closing or minimizing the modal by resetting state and clearing errors using the useEffect hook.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner/admin user
5. go to dashboard→ Projects → WBS -> Select Task -> Add Task button
6. Open the Add Task Modal and enter a Start date and an End date and implement the below mentioned checks. 

## Screenshots or videos of changes:

Verify with start date greater than end date and the error message as shown below - Start Date should be lesser than the Due Date:
Screenshot (933)

Verify with End date less than Start date and the error message - Due date must be greater than Start Date:
Screenshot (936)

After an error message is show verify by closing (or clicking outside) the Add Task Modal. And then reopen the Modal to check if the error persists. It should clear the error when the Modal is reopened and show the default date field:
Screenshot (938)

For the same start and end date no error should be thrown.

## Note:
This implementation is based on the improved Add Task Modal format as per [PR 2284](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2284)
The add task page can be navigated to here in [this video](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa?sid=b05f5604-87cb-4ca1-80b8-49bd823893ee)

### CODE REVIEW

**Review by jennZhang93 — APPROVED** [review]
Tested with owner account, all features work as expected. When my end date is less than start date, it will pops an error message under end date. When my end date is greater than start date, it will have an error message under start date. Closing out the task panel and reopen, will reset both fields. Good work! 
image
Screenshot 2024-06-08 at 1 13 03 PM

**Comment by Vijeth-V** [comment]
Tested with owner account; all features work. Error messages for dates appear correctly. Closing and reopening the task panel resets both fields. Good work!
Screenshot 2024-06-08 at 4 31 40 PM
Screenshot 2024-06-08 at 4 30 35 PM

**Review by Kavil-Jain-514 — CHANGES_REQUESTED** [review]
The error message is now proper !!
image
image

However, if the user has set the date wrong (if end date is less than the start date or vice versa) then on click of reset, the error message still exists.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/8edbb2f5-3567-4759-be13-d6248d8da36d

**Review by tianyangL11 — CHANGES_REQUESTED** [review]
It work as expected.  However, The time selection panel is blank
90faaaa81750ba111e5e3972be24ef0

**Comment by Trip2310** [comment]
Error message for the date appears
PR#2335
 clearly.

**Review by Trip2310 — APPROVED** [review]
Tested this functionality
a)When end date is less than start date show error message.
*Error message is showing under start date too*
b) After closing modal and opening it again show default date with no error.
works well

**Review by Sudershhh — APPROVED** [review]
The Error Messages are displaying successfully for the given 2 conditions.

The Error message is cleared after exiting and entering the modal again.

PR 2335 - 2
PR 2335 - 3
PR 2335

**Comment by anandsesha** [comment]
> The error message is now proper !! 
> However, if the user has set the date wrong (if the end date is less than the start date or vice versa), then when the user clicks reset, the error message still exists.
> 
>  PR.2335.mp4

https://www.loom.com/share/d679cc4a16054ca8b925ef78ad5d9efc?sid=de03dba9-5d9b-4a2b-8c89-e638ad88c4d3

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and both cases work as expected. After an error messaged is displayed, when add task button is clicked again, the date is set to default. It works for both scenarios.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/496aeeae-12df-4454-8653-f54f0363ff19

**Review by AnujVakil — APPROVED** [review]
I have tested this PR and functionality is working as expected
PR #2335_1
PR #2335_2
PR #2335_3

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.
Screenshot (115)
Screenshot (116)
Screenshot (117)

**Review by SaiLavanya1 — APPROVED** [review]
I've tested PR #2335 and verified that the date validation for Start and End dates in the Add Task Modal works as expected. Error messages are displayed correctly for invalid date ranges, ensuring users input correct date values.
https://www.loom.com/share/6752ca51c53a453ba6b09d2bfdb88017

**Review by ishan-miglani — CHANGES_REQUESTED** [review]
I have tested the changes in this PR. The validation messages are correctly implemented and the modal errors are cleared after it is closed. 

But there is still an issue with the date picker not being visible in dark mode. Please address that. See attached video
Screenshot 2024-07-19 at 8 20 12 PM


https://github.com/user-attachments/assets/afc88bec-7232-44d8-951e-66a20e73ff6e

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the error messages are displayed for all the cases provided and the error messages go away when the modal is reopened.
Screenshot 2024-07-21 at 5 23 42 AM
Screenshot 2024-07-21 at 5 24 54 AM
Screenshot 2024-07-21 at 5 25 26 AM

**Review by angelalalacheng — COMMENTED** [review]
Hi,
I use your branch `Anand_Fix-Add-Task-Modal-Date-Validation` for frontend and the latest development for backend. The error log works good but it does not clear after reopen it.

Screenshot 2024-07-21 at 5 06 42 PM
Screenshot 2024-07-21 at 5 07 13 PM

Screenshot 2024-07-21 at 5 04 15 PM

The date reset to the default but the error still exists.
Screenshot 2024-07-21 at 5 05 04 PM

**Review by SrikanthChowdary495 — COMMENTED** [review]
I am getting an API error when I am trying to log in. Unexpected error. I am attaching the image for reference. Please correct me if I am wrong. @anandsesha

**Review by ReinaT5678 — DISMISSED** [review]
Hi, I tested the error messages and they seem to correspond with any invalid start and end dates! However, the calendar dates are not visible in dark mode. I attached screenshots below!

Screenshot 2024-07-30 at 8 24 31 PM
Screenshot 2024-07-30 at 8 23 42 PM

Screenshot 2024-07-30 at 8 24 47 PM

**Review by Pranay-ai — COMMENTED** [review]
When Ever i try to add Task details under new Task modal the modal just freezes and i am not able to interact with it.
Thank You,

**Comment by arunsrao9** [comment]
I have tested the PR and everything seems to be working as expected. Here are the screenshots:
1) Start date should be less than Due Date:
Screenshot 2024-08-06 at 6 35 09 PM 1

2) Due Date should be greater than Start date:
Screenshot 2024-08-06 at 6 36 00 PM 1

3)Same date, no errors:
Screenshot 2024-08-06 at 6 35 51 PM

**Comment by Gmon-k** [comment]
I have tested from my side and it works successfully. It shows error if start Date should be lesser than the Due Date. Below is the screenshot for it

**Comment by Lemonnycodes** [comment]
Hi, 
The PR Works as described. The Add Task modal works correctly, with the Start date and End date fields function shows an error when expected and the error is cleared when the modal is reopened.
Screenshots:

**Review by SnelPatare — DISMISSED** [review]
I have tested the PR. It works well for me. Please find images below

image

image

**Review by adityasure9 — APPROVED** [review]
I have thoroughly tested the changes in this PR. The date validation for the Start and End dates in the Add Task Modal works as expected. Error messages are displayed correctly when invalid dates are entered, and these messages are cleared appropriately when the modal is closed and reopened. 

image

The functionality seems solid, and I did not encounter any issues during testing. Excellent work on implementing these validations!

image

**Review by Lemonnycodes — DISMISSED** [review]
Hi, 
The PR Works as described. The Add Task modal works correctly, with the Start date and End date fields function shows an error when expected and the error is cleared when the modal is reopened.
Screenshots:

**Review by vedantg24 — APPROVED** [review]
Tested the PR, and the changes are working as expected. Here are the screenshots:
1. Start date should be less than due date:
Screenshot 2024-08-31

2. Due date should be greater than start date:
Screenshot 2024-08-31

3. Error is cleared when modal is reopened:
Screenshot 2024-08-31

**Comment by FayeLV** [comment]
Hi,
Great job! below is my review summary:
Checked error message "Start Date should be lesser than the Due Date" when Start Date > End Date.
Checked error message "Due Date must be greater than Start Date" when End Date < Start Date.
The modal is clear.
Snipaste_2024-09-05_19-30-29
Snipaste_2024-09-05_19-31-37

**Review by FayeLV — APPROVED** [review]

**Review by ashayk9 — DISMISSED** [review]
Hi, I tested the error messages, and they correctly trigger for any invalid start or end dates.
However, the calendar dates are not visible in dark mode. I've attached screenshots below for reference.
Screenshot 2024-09-06 at 11 59 14 AM
Screenshot 2024-09-06 at 12 01 42 PM
Screenshot 2024-09-06 at 12 01 59 PM

**Review by swaroop-2007 — CHANGES_REQUESTED** [review]
Hi, everything works as expected. 
However, the calendar dates are not visible in the dark mode. I have attached a screenshot below. 
Screenshot (388)

**Review by strallia — CHANGES_REQUESTED** [review]
### I tested and confirm that these changes are working: 

- Correct error messages display when Start Date is greater than Due Date
- Error messages are removed when click out of modal
- No error message is shown for same Start and End Dates 

https://github.com/user-attachments/assets/cedb72a5-dcd5-42bf-bd14-9d019c610cf2

### Issues found: 

- Date picker in dark mode needs more color contrast. However, I see you replied to someone else to submit this as a separate issue so ignore this bullet point.
- Even if there is an error message, because Start Date is greater than Due Date, I can still save the task as long as Task Name is filled out. Instead, the error message should prevent the task from being saved. See reference video: 

https://github.com/user-attachments/assets/cef7e192-2d96-4d6c-a773-ebf6bd62b24f

**Review by crystallow1168 — APPROVED** [review]
Hi @anandsesha,

Changes are working as expected and below are my findings:

image

✅ Verify with start date greater than end date and the error message as shown below - Start Date should be lesser than the Due Date:

image


✅ Verify with End date less than Start date and the error message - Due date must be greater than Start Date:

https://github.com/user-attachments/assets/b86494c9-eb70-476d-9702-884cec40db03

✅ After an error message is show verify by closing (or clicking outside) the Add Task Modal. And then reopen the Modal to check if the error persists. It should clear the error when the Modal is reopened and show the default date field

---

Other observations:
image

❗️The dates on the calendar are not clearly visible when in dark mode.

**Comment by anandsesha** [comment]
Issues Fixed:

- AddTaskModal task Saves only when the Start date and end date errors do not exist
- When the Dark Mode is enabled, the Day Picker Calender is dark-themed
- Reset will now clear the errors in the date fields
- Hover over AddTaskModal form fields in dark mode should not have any hover color 

Video for reference:
[https://www.loom.com/share/018b9268d8ab4dcb9af55cb45aa64d71?sid=ea52544a-eb31-4b84-97a7-5d96d25855c5](https://www.loom.com/share/018b9268d8ab4dcb9af55cb45aa64d71?sid=ea52544a-eb31-4b84-97a7-5d96d25855c5)

**Review by strallia — CHANGES_REQUESTED** [review]
> Issues Fixed:
> 
> * AddTaskModal task Saves only when the Start date and end date errors do not exist
> * When the Dark Mode is enabled, the Day Picker Calender is dark-themed
> * Reset will now clear the errors in the date fields
> * Hover over AddTaskModal form fields in dark mode should not have any hover color
> 
> Video for reference: https://www.loom.com/share/018b9268d8ab4dcb9af55cb45aa64d71?sid=ea52544a-eb31-4b84-97a7-5d96d25855c5

There is an issue where hovering over table row changes the background to a lighter color making the text hard to read. I suggest making the hovered background color darker or removing the effect.

https://github.com/user-attachments/assets/22b004d5-0dc9-47e1-b9e4-ba516aa76845

All other fixes are working. Great job!

**Comment by swaroop-2007** [comment]
> Issues Fixed:
> 
> * AddTaskModal task Saves only when the Start date and end date errors do not exist
> * When the Dark Mode is enabled, the Day Picker Calender is dark-themed
> * Reset will now clear the errors in the date fields
> * Hover over AddTaskModal form fields in dark mode should not have any hover color
> 
> Video for reference: https://www.loom.com/share/018b9268d8ab4dcb9af55cb45aa64d71?sid=ea52544a-eb31-4b84-97a7-5d96d25855c5



Hey, great job! My previous requested change is fixed. Approving this PR. 
Screenshot (403)

**Review by swaroop-2007 — APPROVED** [review]

**Review by strallia — DISMISSED** [review]
I verified that the color issue with hover in dark mode is fixed. Great work! 

image

**Review by nevatiarishabh — DISMISSED** [review]
Everything is working as expected. I have tested the working and implementation of the corrected part. Following are the images of my test.

Screenshot 2024-09-20 at 7 17 05 PM
Screenshot 2024-09-20 at 7 17 35 PM
Screenshot 2024-09-20 at 7 17 55 PM

**Comment by saurabhshetty29** [comment]
Tested; errors display correctly, and fields reset when reopened.
Screenshot 2024-09-21 at 3 02 46 PM
Screenshot 2024-09-21 at 3 05 49 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
