### PR TITLE
yixiao_lei_color_discrepancy_on_piechart

### PR DESCRIPTION
**Pull request by Sophie-lei**
# Description
Ensure that each segment of the pie chart is colored according to predefined preferences associated with personal test lists.
Enhance the pie chart by adding interactive tooltips that display the name of the test associated with each segment when the user hovers over it. These tooltips should disappear when the mouse is moved away from the segment.

Fixes # 
Screenshot 2024-03-09 at 22 14 06
	
## Related PRS (if any):
None
…

## Main changes explained:
- Adjust the Pie Chart Colors to Match Personal Test Lists
- Implement Interactive Tooltips with Mouseover and Mouseout Events

## How to test:
check into current branch on the front end and "development" branch on the backend
do npm install and npm run start:local to run this PR locally
Clear site data/cache
log as admin/owner user
Follow [these instructions](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa?sid=b05f5604-87cb-4ca1-80b8-49bd823893ee) to add a user account you want to test to a project and assign at least 10 tasks to that user
The tasks with no hours logged will not be displayed on the Pie Chart. To add hours logged, connect to hgnproddb using Mongo Compass, select the "tasks" collection, search for the task you need by taskName and add some number (not zero) to the "hoursLogged" field.
Screenshot 2024-03-09 at 22 17 40

Go to the Home Page -> Reports dropdown -> Reports -> People -> Search to find the user account you assigned tasks to and click on it -> test the functionality by clicking "View all"
Ensure that the colors displayed in the pie chart's legend accurately match the corresponding segments of the pie chart and the tasks on the pie can be shown when mouse over it. 

## Screenshots or videos of changes:
Before:

Screenshot 2024-03-09 at 22 41 47

After

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/af043410-2b1d-4861-9b10-4a4986ee3033

## Note:
None

### CODE REVIEW

**Review by Abi-Liu — CHANGES_REQUESTED** [review]
There are a few unnecessary lines that should be removed but other than that this looks good and functions as expected!

Maybe we could also add the amount of hours used inside the tooltip or put it as a percentage of the total hours. Could be beneficial for user experience.
For example, inside the tooltip we can have:
`Task: Test task
  Time spent: 10 hours`


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/1acde973-fb16-4b44-afec-ee06dac0b2e0

**Review by Abi-Liu — DISMISSED** [review]
Looks good!

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi Yixiao, I tested your PR and is working as expected and all the color are matching the data.

Screenshot 2024-04-03 at 12 04 14 PM

**Review by SRamen1999 — DISMISSED** [review]
Everything is working as expected and all the color are matching the data. When hovering over the color on the chart it displays the proper task related to the color.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/f93de7c2-8cfe-4841-8b67-4dab7ed3a63e

**Review by p-suram — CHANGES_REQUESTED** [review]
I tried running this in my local. On first render, i see only one color, if I refresh or click on "View All" button, I see all the colors. Rest all looks great. **Please let me know if you are able to replicate it**.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/157307140/04585b52-c515-4660-bb92-b9c99ee5bd4e

**Review by j-corp-25 — DISMISSED** [review]
Hi @Sophie-lei 

I tested this with a user that had 10 tasks and the colors are reflecting accordingly.

Below is the picture of my user with 10 tasks:

TestingCharts

**Review by metaphor987 — DISMISSED** [review]
Hi Yixiao,

The testing instructions are very clear. I tested the functionality by creating 10 tasks for a user and then manually adding time entries for each task. The pie chart on the report page displayed as expected, with colors in the legend matching those in the pie chart for each task. Additionally, the task names showed up when hovering over the corresponding part of the pie chart. Good work!

Screenshot 2024-04-13 at 11 15 16 PM

**Review by jennZhang93 — DISMISSED** [review]
Checked with owner account and everything described in the PR worked! Good job!

**Suggestion**: currently hovering on the ring will show a tooltip displaying the task name on that portion of the ring, but not the other way around. It would be nice to highlight the corresponding ring portion when hovering on a task from the list.

Screenshot 2024-04-16 at 8 12 21 PM

**Pull request merged**
