### PR TITLE
Luis - Hours logged should be red

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description

Screenshot 2023-09-26 at 8 01 08 PM
In short if hours haven't been fulfilled the text should be color red. Just like the "not provided" text

## Main changes explained:
Added a css class to weeklysummariesreport.css called hoursNotFulfilledwith color red.
If the hours aren't fulfilled the styling is added

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user or owner
4. go to dashboard→ reports → weekly reports
5. All user's who haven't fulfilled their hours should be red.

## Screenshots or videos of changes:
Screenshot 2023-09-26 at 8 13 31 PM

## Note:
There is one user who's text doesn't become red. Because it has default styling. I am unsure why it has default styling since, I adjusted the jsx. 

Screenshot 2023-09-26 at 8 13 11 PM

### CODE REVIEW

**Review by DavidC0126 — DISMISSED** [review]
Hi @luisarevalo21  I tested the PR and it looks good to me. I was able to see the red label when the logged hours not met the required volunteer hours.

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and it works as intended! Great Job!

week5 - PR2

**Comment by astrjc0326** [comment]
Hello, I've tested the code, and it functions exactly as described. Using the class name to manage the status not only enhances readability but also results in cleaner code. Great Job!


Screen Shot 2023-09-27 at 11 07 41 AM

**Review by navneeeth — DISMISSED** [review]
Hello, @luisarevalo21! Tested your changes and the font for most of the users who haven't met their weekly minimum hours in the `Dashboard-> Reports-> Weekly Summaries Report` are in red font as intended. However, as you mentioned in the note, there is an user whose text does not become red. This is because their hours logged are 0.00 / 0 and they are meeting their required weekly minimum hours. Good implementation!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/520f4fa6-8c41-4d37-9385-b030c741aa8e

**Review by Sssky-18 — DISMISSED** [review]
Hi @luisarevalo21, I just tested this PR, and the color in logged hours showed as intended. When the logged hours were lower than total required hours, it showed the red color correctly. If the required hours were fulfilled, it just showed black as shown in the screenshot. So I think this PR worked well, congrats!
PR#1343

**Comment by Vishala09** [comment]
Tested your PR! Works as expected! Great job!!

image

**Review by Vishala09 — DISMISSED** [review]

**Review by BaileyM96 — DISMISSED** [review]
Hey great job @luisarevalo21 I tested your changes and everything works as intended.

## Screenshots

PR #1343 Hours logged should be red

**Review by sxiong5 — DISMISSED** [review]
Hey @luisarevalo21, I've tested the PR, and it worked as intended.

Screenshot 2023-09-28 at 15 25 48 (2)

**Review by Jiyuanxia — DISMISSED** [review]
Hi @luisarevalo21 , I have reviewed your pull request and tested it. It works as you intended. Good job!
Screenshot 2023-09-28 182322

**Review by tsunami776 — DISMISSED** [review]
Hi @luisarevalo21 your PR works as described. Nice work! People whose committed hours are not fulfilled are colored red. People who fulfilled their committed hours are also colored correctly. One thing I am wondering is the purpose of file 'hours_should_be_red'. Another thing I noticed was that many files seem to be edited but they look the same.

**Review by Bhagyashree444 — DISMISSED** [review]
Works as expected. Good work.

Screenshot (135)

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Red text shows as intended for users below hours. Good job  👍🏻
pr1343 red text shows properly


The only fix required would be to fix the camelCased styling for the class "hoursNotFulfilled". 
pr1343 no camel cased css classes

CamelCased css class names are bad practice, and there's already a naming convention set forth in the app. Stick with kebab-style or use BEM. Here's an example of the kebab-style already present in WeeklySummariesReport.css. I'd probably suggest just going with that. Once fixed, I'll approve.
Screenshot 2023-09-29 at 2 21 23 PM

**Comment by Shubhu0** [comment]
Hi @luisarevalo21 Tested the PR and it works well. Displays the green color for anyone who has completed their required hours log. But I feel that it should also highlight those who are behind or have repeatedly not submitted their hour logs.

image

**Review by EdwinLauM — DISMISSED** [review]
Hey @luisarevalo21! Works as expected! Good job. Hours turn red when it's less than their weekly committed hours

Screen Shot 2023-09-29 at 9 31 43 PM

**Review by yangfan2001 — DISMISSED** [review]
Hi I have read your PR and tested it. It works as expected, Great Job!
image

**Review by JeffLi117 — DISMISSED** [review]
Changes work as intended. I've attached two screenshots where one can see that the hours logged is indeed red if the member has not met their set number of weekly hours, while the hours logged is black if they have.

Hours not met:
image

Hours met:
image

**Comment by one-community** [comment]
Thank you all! Will merge this one merge conflicts and Kurtis' request are resolved.

**Review by TuanDinh140194 — DISMISSED** [review]
Hi! I have test the PR and the hour text turn red as expected. Thank you
Screenshot 2023-09-30 163126

**Review by zuhang2000 — DISMISSED** [review]
Hi I've tested your PR and everything works as expected! Good job!
Screenshot 2023-09-30 at 11 48 31 PM

**Comment by beblicarl** [comment]
This functionality works as intended 

image

**Review by beblicarl — DISMISSED** [review]

**Comment by one-community** [comment]
Thank you everyone, I'll merge this as soon as the conflicts are resolved.

**Comment by luisarevalo21** [comment]
> kebab-style

Hello! Thank you for the feedback. I changed it from camel case to kebab-style instead.

**Pull request closed without merging**
