### PR TITLE
Gowtham fix weekly remaining summaries submission page formatting

### PR DESCRIPTION
**Pull request by curiousfancier**
# Description
This PR fixes the Weekly Summaries submission page formatting 

## Related PRS (if any):
This frontend PR is not related to the backend
To test this frontend PR you need to checkout the dev backend.

## Main changes explained:
- Formatting the weekly summaries page , media URL and alignment of all the components

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log in as admin/volunteer user
5. go to dashboard→ Submit Weekly Summary
6. verify the weekly summary modal before and after writing the summary and also add links to check the alignment before and after 

## Screenshots or videos of changes:
Before the update picture 1
Screenshot 2024-05-11 083724
Before the update picture 2
before #2
After the update  without link
after 1 without link
after the update with link
after 1 with link
after the update submitting summary
#wbs- fix weekly remaining summaries

### CODE REVIEW

**Review by one-community — CHANGES_REQUESTED** [review]
Please also add a space after the ":" here: 
image

**Review by hbodgal — APPROVED** [review]
image

Alignment and formatting looks fine to me.

**Review by MinSun0814 — APPROVED** [review]
New UI looks clean. Nice work!
image

**Comment by nishithaShetty** [comment]
Header and screenshots alignments looks good. The move this summary button and View and Copy AI Prompt is overlapping provided in screenshot 2
image
image

**Review by dkt6 — COMMENTED** [review]
Thank you for your great work! LGTM

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi Gautham, 

The UI looks clean and formatted now, I just noticed one bug in it, take a look
image

The open link button is not in its intended place

**Review by cvtqx — APPROVED** [review]
I've tested this PR from an admin and volunteer accounts, the alignment of the elements looks neat. See images below.

Header:
Screenshot 2024-05-11 at 7 58 08 PM

Media link:

Screenshot 2024-05-11 at 7 58 55 PM

I did not notice issues with button alignment or copy icon alignment that other reviewers mentioned.

**Review by abdel-lall — APPROVED** [review]
LGTM.
Screenshot 2024-05-11 223148

**Review by one-community — APPROVED** [review]

**Review by nathcarnevalli — APPROVED** [review]
Nice work :)


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69649453/3c476094-8f30-4a12-afd9-878db30abee8

**Review by linkhanthtel — APPROVED** [review]
New UI looks good to me! Nice work!

**Comment by gowthamdongari** [comment]
> Hi Gautham,
> 
> The UI looks clean and formatted now, I just noticed one bug in it, take a look image
> 
> The open link button is not in its intended place

I have verified the changes using different browsers link: https://drive.google.com/file/d/1tIobedRRhPy6F98OzS5G8LGJ23bORRyG/view?usp=sharing
I think the issue is due to the latest development changes not reflecting in this branch so I have updated this branch also can you recheck this issue by following the test instructions and let me know in detail in which scenario this issue is showing up

**Review by jayyy-s — APPROVED** [review]
Looks good to me. Tested on admin + volunteer account as well as pre and post summary written. I also tested at various screen sizes and the alignment looked good.
looks good
post summary

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
