### PR TITLE
akshit_fix_final_day_date

### PR DESCRIPTION
**Pull request by akshit0211**
# Description
Screenshot 2024-06-26 at 11 07 50 PM

## Related PRS (if any):
This frontend PR is related to the development backend.

## Main changes explained:
Made changes in the following files:
- src/components/UserManagement/UserTableData.jsx ([PR #2366](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2366))
- src/components/UserProfile/BasicInformationTab/BasicInformationTab.jsx
- src/components/UserProfile/UserProfile.jsx
- src/utils/formatDate.js

## How to test:
1. Check into the current branch.
2. Do `npm install` and `...` to run this PR locally.
3. Clear site data/cache.
4. Log in as owner/admin user.
5. Go to dashboard→ other links→ user management
6. Search for the user account from which you logged in and check if the "Set Final Day" button is disabled for the current user.
7. Set a final day for any other user and check if their profile reflects the exact final date (click on their name).

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/8e0f4d9f-f79f-40d4-be31-77077d5589c1

### CODE REVIEW

**Review by kdaga81 — DISMISSED** [review]
image
image
image

I verified the changes by setting final day and also verified the "Delete Final Day" button and verified by setting final day again. Everything working perfect!

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and verified the following for some users,

1. "Set final day" button is disabled for the logged in user.
2. "Set final day" in Profile page is displayed the exact date what user chose in User Management page. 

Thanks for fixing the issues, Great Work!!

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account. Everything works. My logged in account does not show the SetFinalDay button. For other users, I can set final day and be able to see the date reflected on user profile. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66922622/6a115e46-a992-48bf-9ae5-b475c5dedb26

**Review by Jingyii800 — DISMISSED** [review]
I tested this PR with an owner account and a volunteer account. It works well. The "Set Final Day" button is disabled for the current user. After setting a final day for a volunteer user and their profile can reflect the exact final date.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/1e678d58-46ff-45c3-bc1b-dc1a6ba57cf0

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-localhost_3000-2024.06.28-06_29_37.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/eeffa5d7-8a47-45be-90fb-d7b741b82f12)

**Review by beblicarl — DISMISSED** [review]

**Review by nathcarnevalli — APPROVED** [review]
Nice work! 

Screenshot 2024-06-28 104645

Screenshot 2024-06-28 104708

**Comment by IchinnorovTuguldur** [comment]
Tested set final data functionality. It works as expected. Able to set final date and delete final date.
Screenshot 2024-06-28 at 5 39 46 PM

**Comment by sahithidhulipala9** [comment]
Reviewed the PR and Tested mentioned Functionalities. Great work!
Screenshot (89)
Screenshot (90)
Screenshot (91)

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by tianyangL11 — APPROVED** [review]
It can reflex the given final date correctly. Great job!
edb240ba50609738307faf0d726d2aa

**Review by jinxyou — DISMISSED** [review]
All functions work great! I can't set final day for myself, and I can see the final day for users that has been set a final day.
Screenshot 2024-06-29 200035
Screenshot 2024-06-29 200047

**Comment by IchinnorovTuguldur** [comment]
Set final data button is working as expected

Screenshot 2024-07-05 at 6 07 43 PM

**Review by nyelmela — DISMISSED** [review]
I tested PR 2390 the changes by checking out the branch, running npm install, and starting the app locally. After clearing the site data/cache, I logged in as an owner/admin user and navigated to Dashboard → Other Links → User Management. I searched for the logged-in user account and verified that the "Set Final Day" button is disabled for the current user. I set a final day for another user and confirmed that their profile page reflects the exact final date. Everything worked successfully, and the date appears correctly on the profile page.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/1a430468-5b99-4559-802f-5b31b5367339

**Review by KaushikMreddy — DISMISSED** [review]
Hi Akshit, 

All 3 places now show the same date. Good work!
image
image
image

**Review by vijay10pk — DISMISSED** [review]
All the changes works as expected.
Screenshot 2024-07-06 at 7 38 36 PM
Screenshot 2024-07-06 at 7 40 18 PM
Screenshot 2024-07-06 at 7 40 52 PM

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected.

https://github.com/user-attachments/assets/f4e6f14b-c6d9-49f0-8dcb-c146e066654b

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
