### PR TITLE
Irenedev

### PR DESCRIPTION
**Pull request by thienphuvn95**
Added Task table, fixed filter by name, date, status

### CODE REVIEW

**Comment by migfernandes01** [comment]
So far, I has some problems with the testing, when running `npm start` and got some other error that were solved with other PR's a couple weeks ago. Did you merge the new changes into your branch?
error with irenedev branch
irenedev failed tests

**Comment by thienphuvn95** [comment]
image
I merged dev changes to my branch, ran build+start again and got this error. Have we changed anything to the endpoint so far?

**Comment by thienphuvn95** [comment]
Miguel, I have found the problem. The API called TASK_BY_USERID was refactored one month ago. I looked into the PR #383 . the TASK_BY_USERID is called for a list of members. 
image

**Comment by migfernandes01** [comment]
Hey @thienphuvn95 , I pulled the newest version and those errors are gone, good job! Did you merge the most recent changes from dev (they were merged to dev yesterday with the new user permissions system)?
I'm getting a weird behavior with you branch, not seeing certain windows that owners and admins should see. When I try to go to those routes manually, I just get redirected back to /dashboard. I'm not sure what it is, bull I'll send some screenshots:

Here is what I'm getting running the most recent version of your branch:
cannot see certain pages irenedev branch PR 411


Here is how it is (and should be) in dev:
how it should be for owners and admins
 
Let me know if I'm doing anything wrong or if you need help figuring something out. Once that's solved I can proceed with the testing nad approve it. I took a look at the code and so far looks good

**Comment by migfernandes01** [comment]
Good job correcting the errors @thienphuvn95, I was now able to run the app and test it. It looks great, except for a few thing I  found:
1) There's an error when I click on a person's report:
user profile report error

2) There is some errors on the frontend(name of person is undefined and UI is not showing up some words entirely):
people report undefined

3) You might want to correct the team report page and take this "teamProfile" string out of there
team report error

Other than that everything looks great. Let me know when you get that done so I can review it again and approve

**Comment by thienphuvn95** [comment]
Error 1: I'm not sure if you've already update my code, but that error came from this request.
image
And I added 
image


Error 2: The reason it's undefined because it's a delay from Database. It needs a few seconds to load up
Error 3: This PR does not include Team Report and Project Report. It only include People Report

**Comment by migfernandes01** [comment]
I did a git pull on your code, and I already have the endpoints you added:
tasks by userid
But I still get the same error, I am not sure why. Have you changed anything in the backend?
Other than this error I think everything is good. Let me know if I need to do anything else

**Comment by migfernandes01** [comment]
I made some changes, so now I don't get any errors. All that needs to be fixed now in order to approve this PR is the frontend. The table is too wide, as you see here, so there an horizontal scroll that makes the sides of the page go white:
PR 411 working

Let me know!

**Comment by thienphuvn95** [comment]
image
It looks like I would need to change both the table and red-blue profile area.

**Comment by one-community** [comment]
Reminder you’ve got Vera on your team now to help with the front end too. She’s got 4 years of frontend React experience, so please reach out to her and work out how she can help you. Also any tasks she might be able to take over on.

**Review by migfernandes01 — APPROVED** [review]
Looks great and passed all my tests

**Pull request merged**
