### PR TITLE
Yubo-Fix Edit link modal style

### PR DESCRIPTION
**Pull request by GKD890**
# Description
### Priority LOW:
Screenshot 2023-08-20 at 1 48 20 AM

## Main changes explained:
- Removed `<input>`, use`<label>` instead.
- import CSS properly.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as admin user
4. go to another user's profile page→ click links Edit under their pictures
5. verify the styles looks good (remember to add some link to be able to see **delete** button).

### Before --  After
Screenshot 2023-08-20 at 2 01 20 AM

### CODE REVIEW

**Comment by tsunami776** [comment]
Tested using an admin account; the styling appears well-implemented. The delete button is visible once links are added.
CleanShot 2023-08-20 at 14 11 28
CleanShot 2023-08-20 at 14 15 41

**Review by tsunami776 — APPROVED** [review]
Tested using an admin account; the styling appears well-implemented. The delete button is visible once links are added.
CleanShot 2023-08-20 at 14 11 28
CleanShot 2023-08-20 at 14 15 41

**Review by jerryren527 — DISMISSED** [review]
Hello @GKD890 ,

Great job on the CSS and using `label` instead of `input`. You improved the styling and accessibility of the Edit Links modal. Great job!

Edit Links modal before:
Screenshot 2023-08-20 at 8 05 38 PM

Edit Links modal after:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/5a5dd5ea-5339-4ed7-96b1-ade51f7f1d9e

**Review by luisarevalo21 — APPROVED** [review]
Hello @GKD890 

I tested your PR and works great. Great job!

Before: 
Screenshot 2023-08-20 at 7 56 43 PM

After: 
I am able to view the styling changes, and I can add a new link and new styles were added too. 
The link is saved and can be deleted. 

My only suggestion is are: 

- The "+" should be bigger it should match the "x" button in size. or reduce the padding on the "+" button
- Lastly, add a little bit of padding on the text "Add link" or make it bigger.
Those are my only suggestion to keep the styling consistent. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/6fec45a8-2efa-42ee-a654-89b4fce88bd2

Screenshot 2023-08-20 at 7 55 45 PM
Screenshot 2023-08-20 at 7 55 58 PM

**Review by DavidC0126 — COMMENTED** [review]
Hi @GKD890 I tested your PR and it looks good to me! However, I don't know why I logged in as Admin user but cannot see admin links modal.

style_fix_links

- Admin user account but no Admin links to edit
admin_role

**Review by yurisokolovicz — DISMISSED** [review]
Dear @GKD890 

I have tested your PR, and the style of the edit link modal was properly fixed. Please check the picture below. Good job!

Screenshot from 2023-08-21 11-35-18

**Review by GaryB93 — DISMISSED** [review]
Great job! Looks way better than before! I do think the UI would benefit from a couple easy changes. The first thing I noticed was the inputs don't have the same left padding as the rest of the input fields in the application. In an effort to keep everything uniform I would add some left and right padding unless that was left out intentionally.

9BA3A001-816A-4058-87F1-D622865AE0B3_1_201_a

Also, another easy suggestion would be to use the align-items: center property on the link-fields class containing the "Google Doc" and "Media Folder" labels. I just think it would look better in my opinion if they were centered vertically.

7D983294-0590-413B-AC58-57AA8CDA6DB7_1_201_a

Other than that, great work!

**Review by harshidad — APPROVED** [review]
Changes looks good!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/d0c0c43a-b45e-4452-b3da-f1fd9efde052

**Review by yunshan111 — APPROVED** [review]
Tested this PR, and the UI looks much better. Good Job.

image

**Review by beblicarl — DISMISSED** [review]

**Comment by AnishPandita** [comment]
Hey, the PR looks great. The UI looks great visually.
Screenshot 2023-08-23 at 1 18 15 PM

**Review by eduvarjaor — APPROVED** [review]
Working as intended. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/37ee6b97-7987-4d7d-95f5-bbc5d7ea3393

**Review by iTvX — CHANGES_REQUESTED** [review]
When I checked out your branch, the bottom of the title bar was missing. However, when I checked out back to the development branch, everything was fine.

You can check the video belo

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/ed3ed877-6bef-4d25-8ec9-dbbf4a9d7c84

**Comment by one-community** [comment]
> When I checked out your branch, the "other link" in the title bar was missing. However, when I checked out back to the development branch, everything was fine.
> 
> You can check the video below:
> 
>  CleanShot.2023-08-23.at.14.36.12.mp4

Thank you. This is is a known bug we're working on and outside of the scope of this PR... see the #coding-problems channel

**Review by iTvX — APPROVED** [review]
I have tested your PR, and it looks good. I have changed the request for changes to an approval for your request.

**Review by Haoj1 — APPROVED** [review]
Nice job! @GKD890 The link mode looks good and input steps are more friendly than before

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/18f1cea2-614c-4194-afba-22759cad4b22

**Review by Jiyuanxia — APPROVED** [review]
Hi @GKD890 , I have reviewed your pull request and tested it. It works as expected. Well done!

Screenshot 2023-08-24 182554

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Good job correcting the inputs to labels for Google Doc and Media folder. 
I would suggest revising those labels as follows:
 `<label htmlFor="linkURL1" className="custom-label">
  Google Doc
</label>
<input
  className="customEdit"
  id="linkURL1"
/>`

the id in the input for linkURL1 & 2 has no purpose functionally or stylistically throughout the app, so at the very least it should have the `htmlFor` within the label for accessibility. I know accessibility isn't a big focus within the app, so that's the extent of my revision request for that particular section.


This is a mainly css pull request, so I'm going to stick to the css. 
desktop res:
   -Google doc & media folder text are not vertically aligned. Would also suggest Aligning it with the "newly added link" text as well. Perhaps a new `className` styling would resolve this instead of using the old "customEdit"
   -All inputs except for the links added through "add link" lack padding inside the input. I 
  would suggest going with the standard of padding in the input. If you need more space, the container can also be widened since it's desktop res.
Screenshot 2023-08-25 at 1 20 55 PM

tablet and smaller res:
  - Same thing as above. All inputs except the newly added links lack padding inside the inputs.
  - You can also see that the containers are not of equal width across the screen. 
  - The "X" and "+" containers are nearly 8x the size, but that may just be a me thing, so unless other people mention it I'd just ignore this one.
 
Screenshot 2023-08-25 at 1 20 29 PM


All in all, way better than before. Good job.

**Comment by n0vay** [comment]
Getting the following errors while testing also other links has dissapeared:
image

**Comment by KurtisIvey** [comment]
> Getting the following errors while testing also other links has dissapeared:

You're experiencing an issue thats unrelated to the pr. Jae's got a little guide on resolving that issue in the slack

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works well on my device.
image

**Review by EdwinLauM — DISMISSED** [review]
Hey @GKD890! Changed work as expected! Code looks good as well!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/b76fc932-46ab-41eb-9d37-98757d0b5e02

**Comment by one-community** [comment]
Thank you all, merging as soon as Yubo confirms I can!

**Comment by GKD890** [comment]
Thank you @KurtisIvey for the detailed suggestion, I've changed them as best as I can like below. However, for the colour of the border, I didn't encounter that issue, the look all blue in my browser (Chrome on Mac).

Frontend_#1147_Changed

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Looks good 👍🏻 

desktop:
pr1147 rereview good

tablet and smaller res:
   ~the width of the elements is still an issue, but nobody else minds so its good enough for me
pr1147 re-review

Will approve it once 3 small changes are made. After that, it's good to go.
1. Delete the useReducer import since it's unused, line 1
2. Delete the col import from reactstrap since it's unused
3. Import the css from ./EditLinkModal.css as a normal css file and not a css module.
    use the code:   `import './EditLinkModal.css';` The last thing we need is another CSS styling method in this app lol

**Review by robertoooc — APPROVED** [review]
Hi @GKD890, overall your branch does what it's meant to do. I did have some concerns about not being able to see the admin links section unlike others, I made sure to login as an admin account but still couldn't view it. The main changes towards the styling did turn out as expected though.

Before: 
Before


After: 

After

**Comment by Shubhu0** [comment]
Reviewed the PR, it works as expected

**Comment by GKD890** [comment]
> Looks good 👍🏻
> 
> desktop: pr1147 rereview good
> 
> tablet and smaller res: ~the width of the elements is still an issue, but nobody else minds so its good enough for me(or either they didn't check different resolutions) pr1147 re-review
> 
> Will approve it once 3 small changes are made. After that, it's good to go.
> 
> 1. Delete the useReducer import since it's unused, line 1
> 2. Delete the col import from reactstrap since it's unused
> 3. Import the css from ./EditLinkModal.css as a normal css file and not a css module.
>    use the code:   `import './EditLinkModal.css';` The last thing we need is another CSS styling method in this app lol

Thanks for the detailed guide, especially number 3. So far the styling way is so different from members to members. That's why I tried not to touch them if I can. 
You can find my latest changes [here](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1147/commits/85daff8d70aa5e2b4775ed1bf72943b2c97089bc).  Let me know if that's good.

**Review by KurtisIvey — APPROVED** [review]
Awesome. Should be good to go 

Yeah, I've noticed that a lot too with the styling. I saw the module and was thinking "oh nooooo, not another way of styling within the app lol." We've got bootstrap, css, scss, and probably something else I forgot. Don't even get me started with the camelCased css class names all throughout the app 🥲

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
