### PR TITLE
(PRIORITY URGENT) Jae: Some (but not all) tasks are not saving my updates from the Tasks page

### PR DESCRIPTION
**Pull request by angelinatr15**
1. 3/17 update: This has been an ongoing problem for me. At one point I thought it was just my computer but I’ve just replicated this on my computer, my wife’s computer and my phone.
2. 3/21 update: It’s not the tasks that’s causing this problem, I can go in later on a task and it will sometimes work. Phone seems to work more often than computer for the same task, but today I tried to edit one on my phone and it didn’t work and then I was able to edit it on my computer. 
3. Here's a video I shot just now of this: https://www.dropbox.com/s/zrqmfqbtpnbr6ey/Tasks%20not%20updating.mov?dl=0 

### **Main Changes Explained:**
I added value to the assigned select tag and the status select tag. 

### **How to Test:**

1. check out this branch and the backend branch that is related to this PR as well. (see link below)
2. select a task that has been assigned to a user. This will send you to the page for that task. 
3. select edit and a small window should appear and allow you to make changes to that task. 
4. make changes to each section and click on the update button 
5. the page should reload and the new data should render. 

### **Additional Notes:**
This branch needs the backend branch 
https://github.com/OneCommunityGlobal/HGNRest/tree/angelina-some-but-not-all-tasks-are-not-saving-my-updates-from-the-task-page-backend

### CODE REVIEW

**Review by NataliaCavicchioli — APPROVED** [review]

**Review by LucileTech — APPROVED** [review]
Hit @angelinatr15 I just tested your PR with back and front and the tasks are updating and the changes remain. 
Here is a recording of it: 

https://user-images.githubusercontent.com/111132148/230507353-9cc0e45f-7aa1-451b-9158-f7a20da215a7.mp4

**Comment by AnishPandita** [comment]
Hi @angelinatr15 I tested your PR against several tasks and it seems to work great. 

https://user-images.githubusercontent.com/111321945/230508511-cb7e47fc-6a92-49a9-881b-090fb1565815.mov

**Comment by one-community** [comment]
Thank you everyone, moving this to final approval.

**Comment by agujjar2206** [comment]
Hi @angelinatr15, I have tested this PR along with the related backend branch (link provided) and can confirm that it works as expected. The task editing feature functions smoothly. Great work!

Video:
https://user-images.githubusercontent.com/94432002/230525997-373e6f13-7152-46a0-8f9f-e043883eb1c0.mov

**Review by agujjar2206 — APPROVED** [review]

**Comment by KaixiangGU** [comment]
Tried to update 10+ tasks, it's all worked. GOOD JOB!

**Comment by one-community** [comment]
Works great, thank you Angelina! Just added a related bug to the doc if you'd like to help with it: "WBS Categories Not Saving Correctly"--> same name but different problem

**Pull request merged**
