### PR TITLE
Xiao F create the ability for owners to approve and apply suggested changes on task

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-10-25 at 20 31 30

## Related PRS (if any):
[PR#949](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/949)

## Main changes explained:
- Update file `src/components/Header/Header.jsx` for fetching notifications for owners

## How to test:
1. check into current branch
2. Start the FE by `npm i` and `npm run start:local`
3. log in as a volunteer user
4. go to dashboard -> Tasks -> click on task name -> suggest -> make some changes to the task -> update
5. log in as owner user
6. go to dashboard -> left side of 'Dashboard' should show the number suggested changes -> click on the number -> view suggestion -> approve -> changes should reflect on the task

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/7dd5e58d-e0b8-438a-82e4-d97ef2f8cc6b

## Note:
1. For BE, this `TypeError: Cannot read property 'permissions' of null` error exists on dev branch:
CleanShot 2023-10-25 at 22 53 07

2. Manager has both edit and suggest permissions in the database, but edit permission overrides suggest so that 'suggest' button won't appear for manager.

### CODE REVIEW

**Comment by AriaYu927** [comment]
Hi @tsunami776 , I've tested your PR and it works well on my end.

Owner can see the suggestion on their dashboard:
Screenshot 2023-10-26 at 15 29 27

Screenshot 2023-10-26 at 15 29 37

The hours of task changed successfully after Owner's approval:
Screenshot 2023-10-26 at 15 39 09

**Comment by olenadanykh** [comment]
Hi @tsunami776. I've tested your PR, and everything works as intended. I was able to make a suggestion to the task from the Volunteer Account and review it from the Owner account as expected. Great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/9a380bfe-28a7-4186-81c2-d6e01ac35f85

**Review by DavidC0126 — DISMISSED** [review]
Hi @tsunami776 I tested the PR and it works as intended.

Screenshot 2023-10-26 at 5 59 12 PM
Screenshot 2023-10-26 at 6 00 26 PM
Screenshot 2023-10-26 at 6 02 02 PM

**Review by Shubhu0 — APPROVED** [review]
Hi @tsunami776 Tested your PR and it is working as intended.

image

image

**Comment by palakgosalia** [comment]
Hey, I was able to approve or reject the suggestions. Good work. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/cf4f969c-92eb-4b97-82a0-c313f31793ee

**Review by Bali2Mohit — COMMENTED** [review]
Hi @tsunami776 , I have tested your changes. It wroks perfect. Good job.

Owner is able to approve or reject:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94716419/5ecc6e51-1a7a-4ac2-ac95-49e311c9f46c

And dev is able to edit/suggest
Screenshot 2023-11-04 at 15 06 48

**Review by Bali2Mohit — APPROVED** [review]

**Review by Alforoan — COMMENTED** [review]
I can't seem to find a suggest button. Any idea why?

**Comment by mianmiantea2019** [comment]
Same here, I can't seem to find a suggest button. In addition, during my testing, I successfully initiated the app and logged in as a volunteer but ran into those error messages after. Am I missing anything?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/72b36a37-e836-4b6e-bf30-ae36d0210f67

**Comment by one-community** [comment]
> I can't seem to find a suggest button. Any idea why?

Did you do the same thing as the other reviewers that were successful?

**Comment by mianmiantea2019** [comment]
Hi @tsunami776 , I've tested your PR and it works well on my end.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/99b358b3-6250-4f06-acdb-3455ca0424a1

**Review by cvtqx — APPROVED** [review]
Works as described.
Logged in as volunteer, added changes to a task:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/9373a1ac-4387-434d-9c63-6e3363da2214

Logged in as owner, saw the added changes and approved:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/fb33c414-a2ae-4e9a-af3c-592463d66541

Then I could see all the changes made in the task:

Screen Shot 2024-01-17 at 11 12 51 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
