### PR TITLE
Aishwarya_fix_the_system_sending_multiple_emails_when_manually_issue_…

### PR DESCRIPTION
**Pull request by Aishwaryak01**
Description
Currently, when a blue square is manually assigned to a user, two or multiple notification emails are sent by the system.

Main changes explained:

Removed a hook 'useEffect' which was written twice in the code for blue square.
The useEffect hook was responsible for calling the handleSubmit function, which contains the logic for saving the user profile. 
However, due to the duplication of 'useEffect', handleSubmit was triggered twice, resulting in the profile being saved twice as well. 
As a result, two email notifications were sent out instead of the intended single notification.

How to test:

Before moving to testing, firstly you need to set up your own test email id to send the mail notification.
This is only for test purposes. Once tested you can revert these changes. These changes are not required on the main.

To send email using Gmail API using OAuth2 and nodemailer, kindly follow the below video and setup up a test mail id.
https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

Fill below variable values from the above setup in the .env file of the backend.
REACT_APP_EMAIL =
REACT_APP_EMAIL_CLIENT_ID =
REACT_APP_EMAIL_CLIENT_SECRET =
REACT_APP_EMAIL_REFRESH_TOKEN =
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE

=======================================================================

1. check into the current branch
2. do npm run start: local
3. Go to View Profile and at the left side pane, click on the '+' add button for Bluesquare.

image
image

4. Fill in the details and click on 'Submit'.
5. Now go to the mailbox of the email id set using the above-mentioned steps and check if you have received the notification only once.

Corner case checking:-
1. Try deleting a blue square manually.No notification should be sent for this.
2. Try updating an existing blue square summary.No notification should be sent for this.

### CODE REVIEW

**Comment by beblicarl** [comment]
Hello @Aishwaryak01 

After several hours I have been able to figure this out.  I got this error while trying to follow the tutorial 

`Access blocked: App not completed the Google verification process error in oauth2`

The error above can be resolved with this video https://www.youtube.com/watch?v=bkZns_VOB6I , you could add it to the description to help the next person.

I tested this functionality and it works as intended. Great Job!!

1. When I added a blue square I got just 1 infringement message.
2.  I got no messages when I edited the description of the blue square 
3. I got no message when I deleted the blue square as well as seen in the video below

[issue #964.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/f69f615b-4967-46c6-a73c-0d63a10a4680)

**Review by beblicarl — APPROVED** [review]

**Review by xaanders — APPROVED** [review]

**Comment by xaanders** [comment]
Spent some time setting up the gmail API. 
Works as explained.
- get only one email message when adding a new blue squere
- doesn't get any messages if removing or updating a blue squere
Good job!
[scrnli_04-07-2023_16-08-31.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108314277/6f70e5d8-bd39-4032-9507-ebed5d109c45)

**Comment by Aishwaryak01** [comment]
@beblicarl Sure.Thank you for the troubleshooting video!

**Comment by one-community** [comment]
Thank you all! This is a low-risk issue and high-priority merge, so merging now :)

**Pull request merged**
