### PR TITLE
Haoyue title summary on profile page

### PR DESCRIPTION
**Pull request by oliviahyw**
# Description
Screenshot 2024-09-20 at 1 26 40 PM

## Related PRS (if any):
This frontend PR is related to the [#1111](https://github.com/OneCommunityGlobal/HGNRest/pull/1111) backend PR.

## Main changes explained:
- Modified the displayed title up to 5 characters.
- Changed the styling of the title tags, making sure it looks good with up to 30 titles .
- Added the "Title Code" field, suggesting the first 5 characters of the Title Name, enabling users to modify.
- Added validation for Title Code field - up to 5 characters, cannot be empty, only lower/upper case characters.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to user profile → Add a New Title
6. verify adding a new title and modify the title code.
7. verify the validation error of invalid input for title code.
8. verify the styling is the same as the screenshots below.

## Screenshots or videos of changes:
Screenshot 2024-09-20 at 1 10 44 PM
Screenshot 2024-09-20 at 1 11 14 PM
Screenshot 2024-09-20 at 1 11 34 PM
Screenshot 2024-09-20 at 1 11 56 PM

https://github.com/user-attachments/assets/06503f89-2792-4486-b5b9-f3a5293daf26

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by ArtemisNyx3 — DISMISSED** [review]
[Nikita Test - PR 2700 & 1111.webm](https://github.com/user-attachments/assets/87a15c87-fdf8-45b1-8666-04c1086374aa)

Changes working upto spec

**Review by Logeshwari-Renu — APPROVED** [review]
Tested the PR and verified the Title code up to 5 characters. The validation for Title Code field verified for more than 5 characters, blank and lower/upper cases and its working fine. Great work!

**Review by jinxyou — DISMISSED** [review]
The title and team code restriction is working. Great work!
Screenshot 2024-09-21 175509
Screenshot 2024-09-21 175622

**Review by panchalvatneu — CHANGES_REQUESTED** [review]
Ok so your changes worked
image
But in my opinion input labels are still too crowded and they should have some more margin-top
additionally, titlecode is suggested based on the title name, in that it takes the first 5 characters of the title name which also includes any spaces there might be, I think we could do a better algorithm there. Kindly consider these changes.

**Review by chu-ziyu — DISMISSED** [review]
I have tested this PR and it worked as pected.
Screenshot 2024-09-24 at 4 59 39 PM
Screenshot 2024-09-24 at 4 58 34 PM

**Review by Dk-21 — DISMISSED** [review]
### PR 2700
@oliviahyw 
Tested the changes and Working up to the specifications.
PR-2700(2)
PR-2700(3)
PR-2700(1)

**Review by Gauravmg6 — APPROVED** [review]
Changes are working as expected.
Screenshot 2024-09-29 131502
Screenshot 2024-09-29 131522

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected. Below are the screenshots for reference:
Capture2700_0
Capture2700_1
Capture2700_2
Capture2700_3

**Review by AshishNags — APPROVED** [review]
Approving the Frontend PR.
Every functionality is working as expected except for one small change in the backend, left a detailed comment in the Backend PR 
[https://github.com/OneCommunityGlobal/HGNRest/pull/1111](url)


Screenshot 2024-10-09 131516

**Comment by ShreyaLaheri** [comment]
This PR looks good - everything works as mentioned

**Review by khushijain03 — APPROVED** [review]
Hi @oliviahyw, the functionality works as expected.


https://github.com/user-attachments/assets/b435a620-182b-41a2-aa12-1d932cf6577a

**Review by lng2020 — COMMENTED** [review]
If I understand correctly, the real change is adding a titleCode field in the title object. And there are three lines about them. The other changes are just formatting. Do the formatting changes should be included in this PR?

**Review by Ankuriboh — APPROVED** [review]
Code works as intended, but I found two small problems:

- After `Title Name` is changed, `Title Code` will be automatically updated to its first 5 characters. If I changed the code then change the name, all changes in the code field is unsaved.
- Since we validate if `code length <= 5`, we could also validate for English characters only. Current implementation allows input of numbers until form submission completed.

**Review by Anoushka21 — APPROVED** [review]
The expected validation check for `5` characters and initially copying first 5 from `title name` to `title code` works. Validation also working.

Uploading PR-2700.mp4…

**Review by bhavya17prakash — CHANGES_REQUESTED** [review]
I followed the instructions to test as given but did not get the validation error for Title Code field - up to 5 characters, cannot be empty, only lower/upper case characters.

https://github.com/user-attachments/assets/ed8a8c58-0618-40b9-acf5-fbe5eeebc9e8

**Review by javid679 — APPROVED** [review]
I have tested this PR and this is working fine:


Screenshot (69)

Screenshot (70)

**Comment by oliviahyw** [comment]
> I followed the instructions to test as given but did not get the validation error for Title Code field - up to 5 characters, cannot be empty, only lower/upper case characters.
> 
>  PR.2700.mp4

I have double checked and tried to replicate the same input, but I got the expected error message. Could you please clear your browser cache and try it one more time? Thank you!

https://github.com/user-attachments/assets/cb809bee-5185-419c-a875-f7785c9d1f73

**Review by bhavya17prakash — APPROVED** [review]

**Comment by bhavya17prakash** [comment]
Followed the instructions given by @oliviahyw , and checked out to both the backend and frontend branches. It is working as intended
image

**Review by hqzhu0913 — COMMENTED** [review]
Hi,
I found the UI is not the same as in the video. But the function work as explained. The code can only contain alphabetic and up to 5 characters.
Screenshot 2024-10-25 at 11 00 17 AM
Screenshot 2024-10-25 at 11 01 42 AM
Screenshot 2024-10-25 at 11 17 29 AM

**Review by zhiminV — APPROVED** [review]
I first checkout the related backend branch and then test frontend, which showed that this function work as expected in both light and dark mode.

https://github.com/user-attachments/assets/8b885cb7-a34e-4f62-b805-d52aba1065af

Screenshot 2024-10-26 at 3 07 02 PM

**Review by varun-elango — APPROVED** [review]
The functionality is working as expected with the corresponding branch on the backend. The button currently says "Add New QST" instead of "Add A New Title". The validations for title code and title tags styling up to 30 titles are as expected.  Verified in dark mode.
PR2700+1111_1
PR2700+1111_2
PR2700+1111_3

**Review by Rupa2400 — COMMENTED** [review]
I tested the PR and confirmed that the Title Code is validated correctly for up to 5 characters. The validation for the Title Code field is functioning as expected for inputs exceeding 5 characters, blank entries, and both lowercase and uppercase letters.

However, it is also accepting numerical Title Codes in my case. Please refer to the attached screenshots for further details.


PR_2700_1

PR_2700_2

**Pull request merged**
