### PR TITLE
Shrey unit tests for ReminderModal

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for ReminderModal component

## How to test:
1. check into current branch
2. do `npm install` 
3. npm test ReminderModal.test.js
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-12-15 at 11 40 07 PM

### CODE REVIEW

**Review by this-journey — APPROVED** [review]
Hello @Shreyj14 ! I reviewed your PR and all tests passed.  Great job!

Screenshot 2023-12-15 at 10 37 50 AM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-16 at 12 30 21 AM

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-15 at 10 23 53 PM
All the test cases were successful. Excellent job!

**Comment by DragonSlayer2401** [comment]
I tested this PR and all of the tests passed as expected. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/c2aec7c8-eb53-46c9-818a-a5fdc6b7b991

**Comment by Lin1404** [comment]
All test cases passed successfully. Good job!

Screenshot 2023-12-16 at 4 55 43 PM

**Review by Lin1404 — APPROVED** [review]

**Review by Alforoan — APPROVED** [review]
All tests passed. The tests seem to be covering various scenarios and look well structured. Nice!

image

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 17 - PR7

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
