### PR TITLE
Nathan reset permissions to default

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR addresses `Create a “Restore To Default” functionality that restores the user permissions to the default configurations`.

## Related PRS (if any):
This frontend PR is related to backend PR #559.
To test this frontend PR you need to checkout the backend PR.
https://github.com/OneCommunityGlobal/HGNRest/pull/559

## Main changes explained:
- Created `PermissionsPresetsModal.jsx` for updating permissions of roles to various presets
- Added redux logic for storing the presets of the role the user last viewed
- Added `Load Presets` and `Create New Preset` buttons in `RolePermissions.jsx`
- `Load Presets` opens the `PermissionsPresetsModal` and `Create New Preset` creates a new preset with the current permissions and auto assigns it the name of `New Preset #` with the lowest number that isn't taken.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as owner user
4. go to dashboard→ Other Links→ Permissions Management→any role, preferably a test role (I've been using DNE)
5. Verify each function (and that their changes persist after refresh if saved)
    1. `Create New Preset` and `Load Presets` buttons appear next to the `Save` and `Delete Role` buttons.
    2. `Load Presets` opens the `PermissionsPresetsModal` and loads presets for that role from the back end.
    3. `Create New Preset` saves the current permissions in state (regardless if they are not saved to be applied to the actual role) as a new preset which is visible when you open the `PermissionsPresetsModal`
    4. Verify `PermissionsPresetsModal` works
        1. A list of permissions will expand and collapse when the preset is clicked (on an area not covered by a button or input field)
        2. When the edit button is clicked, it will toggle the following features: the name for that preset becomes an input field, is selected, and has a `Save Name` button appear
        3. clicking `Save Name` will save name changes after refresh
        4. The `Delete` button removes presets
        5. The `Apply` button applies presets 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/23086054/71ea27de-aba9-41e9-8200-54fd82955b9b

### CODE REVIEW

**Comment by malikjahanzaib** [comment]
I checked out both the branches in frontend(#1374) and backend(#559) but am not able to see the "create preset" button. Also, I am not able to assign or delete any permissions to any roles even using the Admin account. I am new to this project and any help would be appreciated.

Here is my test recording:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/c7ea0b73-806a-4360-afaa-91519aeac2e7

**Comment by nathanah** [comment]
> I checked out both the branches in frontend(#1374) and backend(#559) but am not able to see the "create preset" button. Also, I am not able to assign or delete any permissions to any roles even using the Admin account. I am new to this project and any help would be appreciated.
> 
> Here is my test recording:
> 
>  03.10.2023_21.11.37_REC.mp4

I think something changed recently so only an Owner account will work now. I updated the instructions.

**Comment by malikjahanzaib** [comment]
Oh I see. Got it. 👍🏻

**Comment by RheaWu1212** [comment]
Hi I'm testing your PR but not able to create a new owner role for some reasons, somebody has the same situation?? 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/64dac596-f47e-4dc6-aa74-b33ab04cde10

**Comment by olenadanykh** [comment]
Hi @RheaWu1212, @nathanah 

I'm encountering the same issue—I can't create an owner account to test the PR. I've attempted it using both my personal admin account and [devadmin@hgn.net](mailto:devadmin@hgn.net), but with no success. The 'Owner' option doesn't appear in the dropdown menu for me. I've also tried it with both the current branch and the development one, but the issue persists.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/c0533324-5538-4100-93cb-25950745e7e7

**Review by wantingxu7 — APPROVED** [review]
Hi @nathanah 
I followed the instructions and used my previously created test role to test the functions. Everything looks good. I've included my recording below. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/0d3ba04d-7d0e-40ec-b5ff-23575d8fd42c

**Comment by emunkh404** [comment]
It has errors; I couldn't do anything. I tested it with backend PR #559 and frontend #1374.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/1d26891d-f5b7-4266-a016-38fbf11e2f17

**Review by navneeeth — DISMISSED** [review]
Hello, @nathanah! I tested your changes and the testing works as expected!
Performed the following tests:
Navigated to `Dashboard-> Other Links-> Permissions Management-> Random Role` and verified the functionality of the `Create New Preset`, `Load Presets`, `Save`, and `Delete Role` buttons and the `PermissionsPresetsModal`. The logic works as expected.

I also noticed that the saved presets are exclusive only to the specific user role for which they were created rather than being universally available for all user roles. If, for instance, we add two permissions to a user role and save this as 'Preset A', this preset can be accessed solely by this user role. I understand that this solves the issue by adding a "Reset Permissions to Default" functionality wherein the Owner user can create a 'Default' preset respective to each user role and also build customized presets pertaining to that user role. 

I really liked this solution. Good implementation! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/2003e795-34b2-4434-9592-c6ea03b694b4

**Comment by navneeeth** [comment]
Hello, @emunkh404, @malikjahanzaib, @RheaWu1212, and @olenadanykh! I see that you all are facing issues in testing this PR by @nathanah. You need an Owner account to test it successfully and you can get one of your test accounts in the HGN Dev app upgraded to 'Owner' by requesting Jae. You cannot create an Owner account from the User Management page. Having an Owner account will also allow you to test more PRs that require you to login as an Owner. Hope this helps. :)

**Comment by Shreyj14** [comment]
Hi @nathanah The code works as intended. Great Job !!!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/182410fe-c7bc-4d62-9e52-b2b68dfcbb16

**Review by Shreyj14 — APPROVED** [review]

**Comment by AriaYu927** [comment]
Hi @nathanah , I've tested this PR and it works as expected. All the functionalities works well and changes persist after refresh the page. Thank you!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/ad30eee3-873d-4390-a923-796118a51ac4

**Comment by DavidC0126** [comment]
Hi @nathanah I tested your PR and I can see the create preset on the new page and be able to click the button, however, I cannot see the presets after clicking the loading preset button. Do you think it might caused by the 404 error not found the BE PR#559 (so I used dev backend).
FE_preset

**Review by Shiwani99 — DISMISSED** [review]
Hi,
Great work. I tested your PR and It works as expected. I tested create presets, load presets, editing name of presets, apply, delete and everything worked well.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/f960ea0b-4fa9-4ff0-ab19-3c398a7d6829

**Review by JYXiao-2021 — DISMISSED** [review]
Hi, I test the pr and it works as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/024b2cdf-8b70-4f88-8b9c-4cf30e3c2c88

**Review by malikjahanzaib — APPROVED** [review]
Hi @nathanah, I tested all the features in this PR and everything seems to work perfectly as directed including Create New Preset, Load Preset, and changing the name for the presets. While creating a new preset by clicking the 'Create New Preset' button there should be some UI element letting the user know that a preset has been added (to the load presets). Rest everything seems functional. I have included my test recording below. Great job @nathanah!

Test Rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/3d417957-4611-429a-ae52-c2b838ad3fc8

**Review by Lin1404 — DISMISSED** [review]

**Comment by Lin1404** [comment]
Hi @nathanah , I've tested this PR and it works as expected. Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/48e21de1-f0a4-4e9d-bd2e-e4fdbb2c59a4

**Review by StrawberryCalpico — DISMISSED** [review]
Hi! I tested you PR, it worked really well! Great Job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/8acb63d4-450f-442a-a3f0-5aef6fcda8b6

**Review by KurtisIvey — APPROVED** [review]
Everything functions perfectly. Presets can be created, updated, renamed, and deleted without issue.
pr1374 role preset loads and persists
pr1374 role present persists on empty permiss
pr1374 delete preset works
pr1374 present name change persists and works

**Pull request merged**
