### PR TITLE
Jiangwei create unit test for project table.jsx

### PR DESCRIPTION
**Pull request by Jiangwei-shi**
# Description
Create a unit test for the project table component to confirm whether it working as intended.

## Main changes explained:
- Create file projectTable.test.js to do the unit tests

## How to test:
1. check into the current branch
2. do npm install and run this PR locally
3. open file src → tests → TeamTable .test.js
4. run `npm run test src/__tests__/projectTable.test.js`

## Screenshots or videos of changes:
image

## Note:
If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully. Great work! 

Screenshot 2023-11-19 at 1 25 32 PM

**Review by vikrambadhan — APPROVED** [review]
Hi, All the test cases passed! Great work!

Week 13 -  PR1

**Comment by beblicarl** [comment]
Went through the test cases and opened the UI. All tests passed

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
