### PR TITLE
Ruike enforce no space in file name

### PR DESCRIPTION
**Pull request by StrawberryCalpico**
# Description
Remove all files with filename contains a white space, and enforce rule by setting .gitignore

## Related PRS (if any):
N/A

## Main changes explained:
Changed several files' filename, replace ' ' with '_'
add **\ ** in gitignore to ignore changes with whitespace in the filename

## How to test:
1. check into current branch
2. do `npm install` (optional)
3. go to the parent directory of frontend/backend folder, for example, the Github folder
4. run the following python file and make sure no file path was printed
```
import os

backend = "HGNRest"
frontend = "HighestGoodNetworkApp"

def checkfile(folderName):
        for fileName in os.scandir(folderName):
                if os.path.isfile(fileName) and ' ' in os.path.basename(fileName):
                        print(os.path.relpath(fileName))
                elif os.path.isdir(fileName):
                        checkfile(fileName)

checkfile(backend)
checkfile(frontend)

```
5. can also test by creating new file with filename contains ' ', check that there's no change in git

## Screenshots or videos of changes:
add a new file that contains whitespace in filename
Screen Shot 2023-10-25 at 8 41 36 PM
i was using github desktop, make sure there's no local change
Screen Shot 2023-10-25 at 8 42 48 PM

## Note:
Make sure when run the script, the frontend/backend folder are in the same directory
such as 
|| /Github
||  => *.py(replace * with any name)
||  => /frontend
||  => /backend
and run python3 *.py(replace * with any name)

### CODE REVIEW

**Review by sxiong5 — APPROVED** [review]
Hey @StrawberryCalpico, I have run the Python, and everything looks good. Nice job!

Screenshot 2023-10-26 at 13 16 44

**Review by tsunami776 — APPROVED** [review]
Hi @StrawberryCalpico, I ran the python test you provided for dev and your branch. I found files that not in `node_modules` now do not have space in their file names. One minor question I wondered is if you can skip checking files in `node_modules` and `.git`. Nice work overall!
dev:
CleanShot 2023-10-26 at 15 39 47

Your branch:
CleanShot 2023-10-26 at 15 35 19

**Review by ChirayuRai — APPROVED** [review]
I checked out your PR, and it looks good! It only shows one space in node_modules in the backend folder. However, I don't know if that's important and should be something to consider? In the future it might be better to just skip over the folders in the gitignore for each directory or something.

Screenshot 2023-10-27 at 4 39 32 PM

**Review by Iris-Song — APPROVED** [review]
HI, I have tested your PR. It works as intended. Good job.
Screenshot 2023-10-28 at 10 56 16

**Review by yaow62023 — APPROVED** [review]
I have tested your pr, run the python code. No error at this pr. 

Screenshot 2023-10-28 at 6 57 54 PM

**Review by Shubhu0 — APPROVED** [review]
Hi @StrawberryCalpico Tested and reviewed your PR and it is working as intended.

image

**Review by zuhang2000 — APPROVED** [review]
Hi, I've tested your PR following your instructions. The code passes without a error. It reports the results as expected. Good job.
Screenshot 2023-10-28 at 11 41 04 PM

**Review by Aishwaryak01 — APPROVED** [review]
Hi Ruike,
Went through the regex provided in the .gitignore file to remove the space from the filename. It looks good to me. Approved!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
