### PR TITLE
Nathan highlight bio permission

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR adds a permission for highlighting the "Bio announcement" row on the Weekly Summaries Report page given certain criteria. 

## Main changes explained:
- Add `highlightEligibleBios` to `PermissionsConst.js`
- Check for `highlightEligibleBios` in `WeeklySummariesReport.jsx`
- Move highlight logic so it's not just for the bio toggle component

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an owner and give volunteer accounts the `highlightEligibleBios` permission labeled "See Highlight for Bios Eligible to be Posted" in Permissions Management→ Manage User Permissions
5. log in as users with and without the permission
6. go to dashboard→ Reports→ Weekly Summaries Report
7. find `0Sherly Volunteer` and verify the `Bio announcement` row isn't highlighted when you don't have the permission
8. find `0Sherly Volunteer` and verify the `Bio announcement` row is highlighted when you t have the permission

## Screenshots or videos of changes:
No highlight:
image
image

Highlight: 
image
image

## Note:
You can check what permission your user has with redux dev tools under:
1. `state.auth.user.permissions.frontPermissions` for individual permissions
2. `state.role.roles.{the role of your account}` for role permissions

If you need to assign permissions to a user, log in with an Owner account and go to Other Links->Permission Management->Manage User Permissions and give/remove the needed permissions to/from a volunteer account. You will have to log out and back in to update your permissions if you stayed logged in in another tab/window.

### CODE REVIEW

**Review by sucheta90 — COMMENTED** [review]
Hi @nathanah I conducted tests on this PR as the Owner and granted my test account ADMIN access to enable the highlight feature. Following the instructions to log out and log back in to observe the change, I discovered that it did not function as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/c51ded7b-b3ff-4494-a847-f162c11d17bb

**Comment by DragonSlayer2401** [comment]
It works as intended I tested it on a Volunteer account that I gave and removed the permission from. It highlighted it with the permission and removed the highlight when I turned off the permission. Please watch the video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/1b12f27b-f9a8-4ec7-99b4-b9be1ca3fd65

**Comment by nathanah** [comment]
> Hi @nathanah I conducted tests on this PR as the Owner and granted my test account ADMIN access to enable the highlight feature. Following the instructions to log out and log back in to observe the change, I discovered that it did not function as intended.
> 
>  Screen.Recording.2023-12-09.at.12.29.52.PM.mov

Did you log out and back in to update your permissions?

**Comment by sucheta90** [comment]
> > Hi @nathanah I conducted tests on this PR as the Owner and granted my test account ADMIN access to enable the highlight feature. Following the instructions to log out and log back in to observe the change, I discovered that it did not function as intended.
> > Screen.Recording.2023-12-09.at.12.29.52.PM.mov
> 
> Did you log out and back in to update your permissions?

@nathanah I did log out and log back in. I am not sure if is there something I need to change in my Volunteer profile in order for the feature to work. I would love to review it a second time. Let me know.

**Comment by nathanah** [comment]
> Hi @nathanah I conducted tests on this PR as the Owner and granted my test account ADMIN access to enable the highlight feature. Following the instructions to log out and log back in to observe the change, I discovered that it did not function as intended.
> 
>  Screen.Recording.2023-12-09.at.12.29.52.PM.mov

Oh, the permission is for the viewer to be able to see highlights. It looks like you're assigning the permission to `Sucheta Admin` and thinking it will highlight `Sucheta Admin`'s  entry. It should instead give that account permission to see the highlight on eligible entries. `0Sherly Volunteer` is one located near the top that should be highlighted if the account you're logged in with has permission.

**Review by Alforoan — DISMISSED** [review]
It doesn't seem to work as intended; pleaes watch the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/4bb6ec20-0752-4609-a8f3-8716f73ecf1d

**Comment by mianmiantea2019** [comment]
Hi @nathanah

I've tested these changes, and they appear to be functioning correctly.

- Logged in as users without the permission

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/0d47b41d-a6e5-4d66-9681-4709b456778b

- Logged in as users with the permission

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/b7b2f313-ab1c-4e73-91c9-9b75b787e207

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
