### PR TITLE
Akshit taking over for Yixiao - Improve tasks contributed section report

### PR DESCRIPTION
**Pull request by Sophie-lei**
# Description
Revise the "Task Name" table styling to ensure that task names align with their corresponding table headers, regardless of the task name length, whether it involves long strings or abbreviated ones. Implement a feature for text suggestions within input fields for task names, estimated hours, and resources, designed to dynamically shorten the list of recommendations based on the user's text input.

## Related PRS (if any):
None

## Main changes explained:
- Update the TableFilter file for the transfer filter option for the task.
- Update the PeopleTableDetails CSS file for styling the table.
- Create a file TextSuggestion component for suggestion text input.

## How to test:
1. check into the current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log in as an admin user
5. Add multiple tasks (combine with both short task name and long task name) for User A following [this instruction ](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa). (make sure to add task hours)
6. go to dashboard→ reports→ people->User A
7. verify  task names align with their corresponding table headers
8. Select each task name, estimated hours, and resources filter. make sure they have the suggestion list and dynamically shorten the list of suggestions based on the user's text input. 

### Video
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/66827672/59b45235-c420-4083-a09b-ca3e8ac6be64

### Screenshot for different screen sizes
Report_page_big_screen
Report_page_small_screen
Report_page_tablet_screen
Report_page

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I reveiwed your PR and it is working correctly. The table headers are well aligned with the content and dynamic filtering is also working correctly. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/a373203f-ba5e-4c12-9eea-6d7234bab6a3

**Review by FyisFe — COMMENTED** [review]
I tested your changes and it looks great on desktop view. However, if mobile view is needed, I believe it could still be improved. 

image


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59299011/cb45ef01-485a-4ecd-80ed-a108aba34bb6

**Review by lacnoskillz — CHANGES_REQUESTED** [review]
Hello @Sophie-lei 
I pulled your changes successfully and tested them on my end
I think you did a great job so far and made a huge leap in the right direction

image

However like someone above has mentioned I believe there's is some room for improvement and we should all have the 'mobile first approach' mind set. 

image

Im trying to think of a solution but im no css wizzard.
 My first instinct is to git rid of the `people-table-row reports-table-head` all together in smaller VP's and just putting the name of each item in each task div `people-table-row people-table-body-row`
Like this
image

Hope this helps or gives you an idea of how to make it more mobile friendly and again nice job,
Happy coding!

**Review by XiaohanMeng — DISMISSED** [review]
Hi, I tested this PR with the development backend and all worked as intended. The task names are properly aligned, and the filter's suggestion list is working well. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/5f9038da-15ad-45cd-a1c0-532337a23140

**Review by ShengjieMao — APPROVED** [review]
The form's layout and the textfield worked as expected. Can see details in the descriptions are all fulfilled. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/14f0ef5e-34a4-497d-891f-a8c4ee9a5674

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and worked as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/4ff90e4a-7a1a-4617-99ff-45e357793ea7

**Review by YHX6 — DISMISSED** [review]
This feature works fine on my side
This is the feature before

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113729159/9124a194-9c4b-4987-9a8c-e5dc0e66b11b

This is the result after

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113729159/2af889e1-0d56-432f-b0d6-bbc033242a63

**Comment by dhairya-mehta** [comment]
Verified the changes, good work
image

**Review by Pandani07 — CHANGES_REQUESTED** [review]
When i try to login as an admin, i get this error in the backend console. Im using the latest development backend. 
Im not able to upload the image for some reason, so I've pasted the error

`
MongooseError: Operation `userProfiles.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/pandani07/Downloads/OneCommunity/HGNRest/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `userProfiles.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/pandani07/Downloads/OneCommunity/HGNRest/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `userProfiles.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/pandani07/Downloads/OneCommunity/HGNRest/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `userProfiles.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/pandani07/Downloads/OneCommunity/HGNRest/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `userProfiles.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/pandani07/Downloads/OneCommunity/HGNRest/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `userProfiles.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/pandani07/Downloads/OneCommunity/HGNRest/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
MongooseError: Operation `userProfiles.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/Users/pandani07/Downloads/OneCommunity/HGNRest/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:198:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
`

**Review by mohabbasd — APPROVED** [review]
Hello, I tested you PR and it works perfectly. Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/7a08f2d8-a554-4b6b-b21b-e11ca74fe7d1

**Review by SRamen1999 — COMMENTED** [review]
Everything works as expected. Based on the user's input the task name, estimated hours, and resources filter have suggestion list and dynamically shortens the list of suggestions.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/b98fd6f4-955a-4844-abb7-02fcab6e5506

One suggestion I would make is to make is mobile friendly because the chart gets merged together.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/6396af19-11c2-4b8f-9070-6e7782e0c51a

**Review by j-corp-25 — APPROVED** [review]
Hi @Sophie-lei , 

I followed the instructions as shown above and its working as expected. 
- Suggestions base on input populate and and decrease dynamically

Below is the video of my test:

TestedPR

**Comment by hiralsonip** [comment]
I've reviewed this PR, and everything seems to be functioning as it should. Please double-check the responsiveness, but aside from that, everything looks good to go.

PR2005-Responsive

PR2005

**Review by SushmithaPrathap — DISMISSED** [review]
Hey, I've tested this PR and it functions well overall. Everything is working as expected. Followed the steps given and the video. 

Here are screenshots and screen recording:

Before adding tasks:
Screenshot 2024-04-12 at 8 41 24 PM

After adding tasks:
Screenshot 2024-04-12 at 8 42 03 PM

Screen recording:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/1e32664b-b708-4fb2-8657-967666c020ec

**Review by anandsesha — CHANGES_REQUESTED** [review]
Hi, I have reviewed your PR and the search and sort features in the Task Completed table work as expected based on Task name, Est hrs, Resources etc. 

Kindly check the issues with the responsiveness of the page. The mobile view has some text overlaps and when switched back to desktop view the UI still remains in the mobile view. Please refer the last two screenshots.  

Screenshot (824)
Screenshot (825)
Screenshot (827)
Screenshot (831)
Screenshot (832)
Screenshot (833)
Screenshot (834)
Screenshot (836)
Screenshot (837)

**Review by metaphor987 — DISMISSED** [review]
Hi Yixiao,

I've tested the changes using Admin and Owner accounts, and the main functionalities all work well. Nice work! I did encounter two issues related to the filters. I'm not sure if they are in the range of this PR but it would be best to check them:

- **User Name Filter Issue:** On the reports page for a specific user, the "Tasks contributed"->"Resources" filter displays both the old name and current name for the same user. This causes the filter to separate tasks based on the username at the time the task was assigned. For example, in my test, "Huijie_Test_0 Liu" and "Huijie_Test_Volunteer Liu" are old and new names for the same user. I'm not sure if this behavior needs to be adjusted.
resources filter
tasks for new name
tasks for old name
all tasks for this user


- **Status Filter Issue:** The status filter seems to not work correctly in my test. In my example, Despite all users' tasks being active, the filter cannot retrieve the active tasks.
status filter

Thank you!

**Review by jennZhang93 — CHANGES_REQUESTED** [review]
Tested with owner account, and all features work fine. But when the task name is one word with a lot of letters in it, the task name will still cramped together. But it might be fine since this won't be an expected user behavior. Or kindly give an warning message to warn user that a word is too long and may not display correctly.

image

**Review by Nahiyan-16 — CHANGES_REQUESTED** [review]
Hey @akshit0211, this PR is almost there but I have some minor requests. Can you please make the 'rehireable' label work in dark mode. And add some top margin on the cards from 1250px to 850px and then again from 435px to 375px. Thank you!


https://github.com/user-attachments/assets/01cf6b58-e96c-4443-aca0-12b0f5597418

**Comment by Gmon-k** [comment]
I have tested from my side and it is working fine

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
