### PR TITLE
Nida - Make devadmin@hgn.net password on the Dev editable only Jae

### PR DESCRIPTION
**Pull request by NidaZaki**
# Description

image

# Fixes (bug list priority Urgent)
- Currently **all** users are able to edit/reset/update the password or details for the devadmin@hgn.net account. 
- This issue is fixed by giving editing permissions to Jae (3 accounts given in the description)

## Main changes explained:
- Added editing permission for devadmin@hgn.net in the `permissions.js` file so that Jae has access to edit the input fields/password for that account
- Added an alert pop up in `ResetPasswordButton` and `UserProfile` when someone other than Jae attempts to update/reset the password for the devadmin@hgn.net account
- Made changes to the `canEdit` attribute in the `VolunteeringTimeTab` and `BasicInformationTab` in the `UserProfile` component which uses the functions in the `permissions.js`.
- Made changes to the `edit` attribute in the `TeamsTab` and `ProjectsTab` component as well.

## How to test: (2 places)
Check into current branch
**1st place**
1. Log into Dev Admin account
2. Go to User Login → Profile Page → Update Password 
3. Verify that Dev Admin cannot self edit its details or update its own password.

**2nd place**
1. Log into Admin account
2. Go to Admin Login → Other Links → User Management → search for devadmin@hgn.net → Reset Password and/or click on the devadmin@hgn.net
3. Verify that the details or the password of the Dev Admin account is not editable by anyone other than Jae (3 accounts given in the description)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/c784f39d-3a34-4a8c-898a-ded218dcee9d

### CODE REVIEW

**Comment by xaanders** [comment]
Hi! I've tested the PR. 
This is the view from dev admin:

- changing password: 
devadmin
-changing details: 
devadmin-details
I could change details in the profile. When you change any of the details data the button to save changes begin to work.


Logged into admin account: 
- password changing didn't work from the list screen:
admin-reset
But when I tried to change one symbol in the email without even saving it -> I could change the password (it didn't work with dev admin though):

admin-reset2

One of the ways to protect profile(It might be easier as I think) :
Not to track the email that can't be changed along with prof data, but add some extra password to save data. 
Like if the account has one of those emails in the profile -> saving data or changing profile password require password to confirm

**Review by xaanders — CHANGES_REQUESTED** [review]
Hi! I've tested the PR. 
This is the view from dev admin:
devadmin
And admin: 
admin


admin2

Works good!

**Comment by NidaZaki** [comment]
> Hi! I've tested the PR. This is the view from dev admin:
> 
> * changing password:
> 
> devadmin -changing details: devadmin-details I could change details in the profile. When you change any of the details data the button to save changes begin to work.
> Logged into admin account:
> 
> * password changing didn't work from the list screen:
> 
> admin-reset But when I tried to change one symbol in the email without even saving it -> I could change the password (it didn't work with dev admin though): admin-reset2
> One of the reasons could be devAdminEmail variable was equal to my email, but not to devadmin, so the denyPermissionToUpdatePassword didn't work admin-reset3
> 
> One of the ways to protect profile(It might be easier as I think) : Not to track the email that can't be changed along with prof data, but add some extra password to save data. Like if the account has one of those emails(tracking props email and not state that can be changed through input) in the profile -> saving data or changing profile password require password to confirm

That issue does not happen for me locally, can you please send a video as to what steps where followed for this to happen? Or maybe specify where exactly this issue seems to occur?

I just checked a minute ago and this is what I see.
image

**Review by xaanders — APPROVED** [review]

**Comment by xaanders** [comment]
> > Hi! I've tested the PR. This is the view from dev admin:
> > 
> > * changing password:
> > 
> > devadmin -changing details: devadmin-details I could change details in the profile. When you change any of the details data the button to save changes begin to work.
> > Logged into admin account:
> > 
> > * password changing didn't work from the list screen:
> > 
> > admin-reset But when I tried to change one symbol in the email without even saving it -> I could change the password (it didn't work with dev admin though): admin-reset2
> > One of the reasons could be devAdminEmail variable was equal to my email, but not to devadmin, so the denyPermissionToUpdatePassword didn't work admin-reset3
> > One of the ways to protect profile(It might be easier as I think) : Not to track the email that can't be changed along with prof data, but add some extra password to save data. Like if the account has one of those emails(tracking props email and not state that can be changed through input) in the profile -> saving data or changing profile password require password to confirm
> 
> That issue does not happen for me locally, can you please send a video as to what steps where followed for this to happen? Or maybe specify where exactly this issue seems to occur?
> 
> I just checked a minute ago and this is what I see. image

I'm sorry. I haven't noticed that my branch was by 2 commits... And when I got the alert I thought that It is the last one. 
I approved the PR. You did a great job!

**Comment by igorrochadasilva** [comment]
Hey @NidaZaki !
Great job, PR is working as expected.

 Dev Admin account:
994-Dev-admin

I received a message when I tried to change the password. 

Admin account
994-admin

When click in the "reset password, receive a warning message

admin account no button to reset password 
994-admin-no-button
"

Great job 😃

**Comment by beblicarl** [comment]
Awesome! This functionality works as intended and the code looks great

[screencast-hgnapplication_react_beta.surge.sh-2023.07.12-17_06_08.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/1bb8bc21-da14-489a-a825-f82c2cee6589)

**Review by beblicarl — DISMISSED** [review]

**Review by tdkent — CHANGES_REQUESTED** [review]
Local testing confirms

- when logged in as `devadmin@hgn.net` it is not possible to reset password from the **User Profile** page. Clicking **Reset Password** instead invokes an alert with an error message.
- when logged in as an admin account, it is not possible to reset password for account `devadmin@hgn.net` from **User Management**. Attempting to do so instead invokes an error alert.

However, there is missing functionality that should be addressed:

- the password can still be reset from the Welcome > Update Password page.

Also, as a suggestion, an alternative approach might be to remove the **Reset Password** button associated with `devadmin@hgn.net` for all users except an allowed account. The Reset Password page could also be removed from navigation when signed in as `devadmin@hgn.net`. (In addition to backend validation, of course).

Testing:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/f3f31720-e236-4058-b987-674ada7a94c7

994-demo2

**Comment by tdkent** [comment]
> > Local testing confirms
> > 
> > * when logged in as `devadmin@hgn.net` it is not possible to reset password from the **User Profile** page. Clicking **Reset Password** instead invokes an alert with an error message.
> > * when logged in as an admin account, it is not possible to reset password for account `devadmin@hgn.net` from **User Management**. Attempting to do so instead invokes an error alert.
> > 
> > However, there is missing functionality that should be addressed:
> > 
> > * the password can still be reset from the Welcome > Update Password page.
> > 
> > Also, as a suggestion, an alternative approach might be to remove the **Reset Password** button associated with `devadmin@hgn.net` for all users except an allowed account. The Reset Password page could also be removed from navigation when signed in as `devadmin@hgn.net`. (In addition to backend validation, of course).
> > Testing:
> > 994-demo1.mov
> > 994-demo2
> 
> I fixed the changes in the header for the update password in the drop down for the [devadmin@hgn.net](mailto:devadmin@hgn.net) account. Do you mind taking a look at it again?

The branch is currently crashing for Admin accounts. I think the culprit is a mistakenly deleted import in Header.jsx (see below)

994-crash1
994-crash2

**Comment by NidaZaki** [comment]
> > > Local testing confirms
> > > 
> > > * when logged in as `devadmin@hgn.net` it is not possible to reset password from the **User Profile** page. Clicking **Reset Password** instead invokes an alert with an error message.
> > > * when logged in as an admin account, it is not possible to reset password for account `devadmin@hgn.net` from **User Management**. Attempting to do so instead invokes an error alert.
> > > 
> > > However, there is missing functionality that should be addressed:
> > > 
> > > * the password can still be reset from the Welcome > Update Password page.
> > > 
> > > Also, as a suggestion, an alternative approach might be to remove the **Reset Password** button associated with `devadmin@hgn.net` for all users except an allowed account. The Reset Password page could also be removed from navigation when signed in as `devadmin@hgn.net`. (In addition to backend validation, of course).
> > > Testing:
> > > 994-demo1.mov
> > > 994-demo2
> > 
> > 
> > I fixed the changes in the header for the update password in the drop down for the [devadmin@hgn.net](mailto:devadmin@hgn.net) account. Do you mind taking a look at it again?
> 
> The branch is currently crashing for Admin accounts. I think the culprit is a mistakenly deleted import in Header.jsx (see below)
> 
> 994-crash1 994-crash2

Updated PR to address this.

**Review by luisarevalo21 — APPROVED** [review]
Hello @NidaZaki,

I tested your PR and works as intented great job!

Devadmin account 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/aaaa173a-3c5d-44e5-859d-7b9e9ca4da87

Admin account. When viewing the devadmin account there is no update password button which is great.
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/f810c80e-488f-4d8c-8e27-4fc83880251a

As [tdkent](https://github.com/tdkent) suggested removing the update password button entirely when logged into the devadmin account could work as well.

**Review by ramyaram2092 — APPROVED** [review]
Hello @NidaZaki  I am unable to  reset the password via  devadmin@hgn.net  portal s well as through other admin user(there was no reset button option which is pretty cool). No errors on the console. Good work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/4e44126b-f708-4b56-9f38-e751219a69b3

**Comment by Jiangwei-shi** [comment]
works great! unable to reset the password of devadmin@hgn.net portal s well as through other admin users. Works as indeed!
image
image

**Review by BaileyM96 — APPROVED** [review]
Good evening @NidaZaki I tested your changes and everything works, great job!

## Video Walkthrough

DevAdmin Account

[DevLogin Update Password.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/c7e139df-8057-4095-a43c-02658610e9c1)

Admin Account

[Dev Reset admin.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/4426820f-aa9e-4797-ab9e-97d68572e39c)

**Comment by AnishPandita** [comment]
Hi @NidaZaki The changes work well. 
For Dev Account:

Screenshot 2023-07-14 at 5 49 07 PM

For Admin Account:

Screenshot 2023-07-14 at 5 59 11 PM

**Review by AaronPersaud — APPROVED** [review]
Hi, I've tested and everything looks good!

<b>Trying to change password from "User Management" section of admin</b>

admin_reset

- alert pops up blocking the password change

<b>Trying to change password from User Profile of "devadmin@hgn.net"</b>

devadmin_reset

- alert pops up blocking password change 

<b>Trying to change password from Welcome dropdown in "devadmin@hgn.net" </b>

no_change_password

- removed the "Update Password" option as suggested by @tdkent

**Review by shiva2096 — APPROVED** [review]
Hi @NidaZaki 

Changes are working as expected.

1. Check from Admin Account from user management page.
Screenshot 2023-07-15 at 1 50 56 PM

2. Checking from the Profile page using Admin Account
Screenshot 2023-07-15 at 1 51 49 PM

**Review by tdkent — APPROVED** [review]
Tested again: 

- Import has been restored. App no longer crashes for admin accounts.
- The "Update Password" option has been removed from the Welcome menu when logged in as `devadmin@hgn.net`

Nice work

**Comment by one-community** [comment]
Thank you everyone, moving this to final review!

**Review by EdwinLauM — APPROVED** [review]
Works as intended! Good job! 

Dev Admin Account: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/85b1628f-d20a-49c2-a58a-6cdb44ca0288

Admin Account:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/9a9ec30a-44fd-41c7-b585-ea7feb835957

**Comment by one-community** [comment]
So glad to never have to fix this issue again! Thank you all!

**Pull request merged**
