### PR TITLE
Nahiyan_Optimized User Profile Page for Mobile Displays

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Optimized user profile page for all viewports 375px wide and above.

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Adjusted widths of components
- Centered container
- Other little adjustments to ensure total optmization

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard→ User Profile
6. verify that all components on the page are working properly when width is 375px and up
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/eefa064e-cbf9-42cb-9ea6-2a123a3ba5de

### CODE REVIEW

**Review by Pranay-ai — APPROVED** [review]
Hey @Nahiyan-16 
I Have Just reviewed the PR the Functionality is working as expected .


https://github.com/user-attachments/assets/c1472a41-f634-4e1e-b58d-5f6212d3082e


Thank You

**Review by Chetan0606 — APPROVED** [review]
Verified as per the description and everything looks good.

https://github.com/user-attachments/assets/4a729f3b-3d0b-45e7-9f09-fe9af1c29836

**Review by Shadhrush5 — DISMISSED** [review]
Hi, I have reviewed PR #2497. I followed the instructions while executing the test as mentioned. The functionality works well at the mentioned resolution in dark mode as well. Thank you for the great work. I have approved the same. The below images depicts my testing.

Screenshot 2024-07-24 at 11 22 07 AM
Screenshot 2024-07-24 at 11 22 15 AM
Screenshot 2024-07-24 at 11 22 26 AM
Screenshot 2024-07-24 at 11 22 31 AM

**Review by Pranay-ai — CHANGES_REQUESTED** [review]
Hey @Nahiyan-16 

Can Review The Teams Modal's Assign Team Button Misalignment on Large Screens
image

**Review by SrikanthChowdary495 — COMMENTED** [review]
I have tested this pull request. I noticed an issue. I don't know if it's related, but the dashboard symbol and refresh icon at the top are not aligned at 375px. I am attaching image & video for reference plz check.

Uploading Userprofile.mp4…

**Comment by arunsrao9** [comment]
I tested the program using the description and everything looks as expected! 
Screenshot 2024-07-24 at 5 00 00 PM
Screenshot 2024-07-24 at 5 00 22 PM
Screenshot 2024-07-24 at 4 59 50 PM

**Review by ReinaT5678 — APPROVED** [review]
I tested some functionality and component spacing  in light and dark mode and everything is working as expected!

https://github.com/user-attachments/assets/452933ff-a332-4c45-8371-65b11cf8cd7e

**Comment by nikethaanand** [comment]
I tested the PR, the allignment works as expected in both dark mode and light mode. I logged in as an admin and volunteer to check them.

https://github.com/user-attachments/assets/e7bc9945-e8f6-4725-a28e-ad62a753f9b6

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR  and it works as expected 

https://github.com/user-attachments/assets/30883284-2720-42c7-b8ad-cf2d6060ca00

**Comment by beblicarl** [comment]
I tested the component spacing in dark mode and it works as intended.

image

**Review by beblicarl — DISMISSED** [review]

**Review by Jingyii800 — DISMISSED** [review]
I tested this PR and it works well. I log in as any user and in the user profile, the page looks good in mobile size. Please find more details in my video.

https://github.com/user-attachments/assets/7fc70a70-cd91-4e60-b279-5bee4f935bee

**Review by JatinAgrawal94 — APPROVED** [review]
Page is loading good and works perfectly in dark mode.

https://github.com/user-attachments/assets/3e458594-ce5b-498c-befe-7e784dd01403

**Review by Parth-tech — CHANGES_REQUESTED** [review]
Hey Nahiyan,

The PR works well with both light mode and dark mode but I would like to request you to center align of the `Select Featured` and `Assign Badges` buttons at 376 px width:

Image Reference:
Screenshot 2024-07-26 at 8 19 29 PM

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the changes work as expected, the spacing and the components adapt well to different screen sizes for both light and dark mode.

https://github.com/user-attachments/assets/7ebc88c2-d8d1-466f-a80e-2b3dfa1b0c79

**Review by kabraambika — CHANGES_REQUESTED** [review]
I have reviewed the frontend PR and working correctly in 375px and up.

**Minor Observation**: Currently there is no space between information tooltip and save changes button as shown below:
image

**Review by angelalalacheng — APPROVED** [review]
Hi, 
I use your branch for frontend and the latest development branch for backend to test the responsiveness. It all works good for me in both light and dark mode.

https://www.loom.com/share/19e5a06546f04125938655562ea76dec?sid=74e94cc2-c027-459a-95ff-d66eb4913ac9

**Review by jinxyou — APPROVED** [review]
The layout here is a bit problematic, both in light mode and dark mode. Can you fix it?
Screenshot 2024-07-27 121713

**Comment by mianmiantea2019** [comment]
I tested the component spacing in dark mode and it works as intended.

image
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
