### PR TITLE
Yixiao  Checkbox  unit test

### PR DESCRIPTION
**Pull request by JYXiao-2021**
# Description
Create a unit test for the Checkbox component to confirm whether it working as intended.

## Main changes explained:
- Create file Checkbox.test.js to do the unit test.

## How to test:
1. check into current branch
2. do `npm install` to run this PR locally
3. run `npm test Checkbox.test.js` 

## Screenshots or videos of changes:
To check no error and all tests passed
Screenshot 2023-10-22 at 11 43 01 PM

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed, great work !!

image

**Review by beblicarl — APPROVED** [review]

**Comment by emunkh404** [comment]
Test passed, all cases successfully!
image

**Review by Sssky-18 — APPROVED** [review]
Hi @JYXiao-2021, I tested your PR, and all the test cases are passed. Congrats!

PR#1443

**Review by DavidC0126 — APPROVED** [review]
Hi @JYXiao-2021 I tested the PR and it looks good to me.

testCheckBox

**Review by Jiyuanxia — APPROVED** [review]
Hi @JYXiao-2021 , I have reviewed your pull request and tested it. It works as you intended. Well done!

Screenshot 2023-10-24 152654

**Review by ChirayuRai — APPROVED** [review]
Just tested this and all cases pass! Good job!
Screenshot 2023-10-24 at 9 57 00 PM

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!

**Review by tsunami776 — APPROVED** [review]
Hi @JYXiao-2021, your unit test for checkbox looks good to me! I ran the unit test locally and there was no error thrown. Nice work!

**Review by StrawberryCalpico — APPROVED** [review]
All test passed! Great work!
Screen Shot 2023-10-27 at 12 53 18 PM

**Comment by kavya151** [comment]
All tests have passed. Good Job!
Screenshot 2023-10-28 at 4 22 14 PM

**Review by vikrambadhan — APPROVED** [review]
All the tests passed! Great Work!

Week9 PR2

**Review by savio-henrique — APPROVED** [review]
Hi @JYXiao-2021 , I tested your PR, great work! All tests passed without any errors!
:+1: 

# Screenshots

terminal

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I run the `npm test Checkbox.test.js` and all the test cases are passed. Great work!

Screenshot 2023-10-31 at 3 22 45 PM

**Review by KurtisIvey — APPROVED** [review]
Good job. Works as intended and follows best practices.


Screenshot 2023-10-31 at 2 31 31 PM

**Pull request merged**
