### PR TITLE
Shefali_UnitTest_UserProfileEditTest

### PR DESCRIPTION
**Pull request by SMitta11**
# Description
Unit tests for src/components/UserProfileEdit.jsx
Created file UserProfileEdit.test.js and added test cases in it.

## Test cases included:
   ✓ should not error out due to no tests (popper.js.js)
    ✓ should not error out due to no tests (mockStates.js)
    ✓ renders the UserProfileEdit component
    ✓ displays loading spinner initially
    ✓ displays form fields after loading
    ✓ prevents submission if form validation fails
    ✓ disables the save button when required fields are empty
    ✓ displays a warning message when unsaved changes are detected
    ✓ calls updateUserProfile when save button is clicked 
    ✓ updates state when input fields change 

## How to test:
1. check into current branch
2. npm install
3. npm test UserProfileEdit.test.js

## Screenshots or videos of changes:
Run this command:
Screen Shot 2024-11-01 at 11 58 15 PM
And at the end you will get the below result:
Screen Shot 2024-11-01 at 11 58 33 PM

Note: Ignore the errors or warnings shown in console

### CODE REVIEW

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-11-02 at 4 18 30 AM

**Review by jinxyou — APPROVED** [review]
All test cases passed on my end
Screenshot 2024-11-02 092105

**Review by varun-elango — APPROVED** [review]
All the test cases are passing.
PR2836_1

**Comment by anji-annavarapu** [comment]
Screenshot 2024-11-02 124151
Screenshot 2024-11-02 124209


though its passed all test cases, it showing some errors so please correct me if i am wrong.

**Review by samarth9201 — APPROVED** [review]
All test cases passed.

Screenshot 2024-11-02 162700

**Comment by mianmiantea2019** [comment]
All test cases passed.

image

**Review by ptrpengdev — APPROVED** [review]
LGTM
PR_2836

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
