### PR TITLE
Gabriele - Fix layout in add task modal in projects/wbs

### PR DESCRIPTION
**Pull request by Gugor99**
# Description
In the "Hours" section in the add task modal, the inputs with the hours should be right aligned on all screen sizes to avoid too much empty space. The labels for those inputs should not be bold.

## Related PRS (if any):
To test this PR check into current branch for Frontend and for backend use the development branch.
…

## Main changes explained:
- Increased the left-side of the modal to the 50% of the width
- Aligned all hours inputs to the left
- Removed bold style from the four labels

## How to test:
1. Check into current branch
2. Do npm install and npm run start:local to run this PR locally
3. Clear site data/cache
4. Log as admin/owner user
5. go to dashboard→ Other Links → Projects→ WBS→ Select a name → Add Task
6. verify the text-weight in the "Hours" section is normal and the inputs are properly aligned in all screen sizes like in the picture of reference below

## Screenshots or videos of changes:
Before:
Cattura1

After:
Cattura2

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by ImzIssa — DISMISSED** [review]
Hey, I've tested your PR and your changes look good.

PR#2075

**Review by linkhanthtel — DISMISSED** [review]
Text weight is normal and the new layout properly aligned on all screen size.

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested your PR and it is working as intended. Please refer the screenshot attached.

PR 2075

**Review by Pandani07 — DISMISSED** [review]
The changes make the UI look great, good job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/823fb1cb-b298-4335-a1c9-d3b927c323cf

**Review by Abi-Liu — CHANGES_REQUESTED** [review]
Interestingly, when my screen size is full width, the inputs in the `Hours` row is overlapping with the text, but on smaller sizes it's right aligned as normal. Not entirely sure why but you can view it in the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59585815/d759d7c2-7128-49f5-a592-b9d729d93455

**Review by SRamen1999 — COMMENTED** [review]
After testing this PR I noticed a bug.

when you are on responsive mode the words in the hours tab are cut off.

Screen Shot 2024-03-21 at 8 32 13 PM


When I am on mobile mode the words are not cut off
Screen Shot 2024-03-21 at 8 31 48 PM

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested you PR and it works as expected. Below is a video for reference.

Screenshot 2024-03-22 at 1 50 54 AM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/617953a7-b2ed-4060-9a45-2c7e7b53b6f1

**Comment by dhairya-mehta** [comment]
Hello, I tested your PR, the hours row is looking as expected, good job!
image

**Comment by rajnada** [comment]
Hii,

I have tested your functionality and it's working well as you mentioned! Good Job!
 
image

**Review by Coops023 — DISMISSED** [review]
Hi Gabriel, i have tested this PR and changes are looking good! nice job.

PR2075

**Review by iven-yao — CHANGES_REQUESTED** [review]
I checked the css rules and flex-responsive will only apply when width is 200px-1496px, 
this causes label and input overlapping when the width is out of the range.
image
image
image

**Review by brandta-1 — DISMISSED** [review]
# Review
Modal successfully displayed and is responsive to various screen sizes as an admin user.

# Video

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/21df9319-7b1c-4aee-9fe4-35b0e5a6232c

**Review by yaow62023 — CHANGES_REQUESTED** [review]
Hi, I have test your PR, and the input box have over lapping when for a wide window. When change to a smaller window work as intended. May need some change on your CSS file. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/5b719acf-4f53-4e70-9bd3-baab86a6fa16

**Review by psharma1984 — DISMISSED** [review]
Hi @Gugor99 . Reviewed the PR. works as expected 

PR 2075

**Review by sameersdeshpande — DISMISSED** [review]
Hello @Gugor99 
I have tested this and checked on my local with the instructions and it seems good and looking as per the expectations. Approving.
Screenshot 2024-03-23 at 4 24 08 PM

**Review by Sarthak32 — DISMISSED** [review]
I tested your PR as you mentioned and it is working as expected. 
Screenshot 2024-03-24 083349

**Review by kylepham — CHANGES_REQUESTED** [review]
I confirm that the labels are not bold anymore, and inputs are right-aligned on mobile view.
Screenshot 2024-03-24 at 3 05 19 PM

However, if a user is on desktop view, the inputs overlap with the labels as below.
Screenshot 2024-03-24 at 2 56 24 PM

Also, I think each label-input pair is not aligned vertically with each other. Removing each label's margin would make it look better.
Screenshot 2024-03-24 at 3 14 43 PM

**Review by Tiantian-C — COMMENTED** [review]
I have tested the PR. The text-weight in the "Hours" section is normal and the inputs are properly aligned in all screen sizes like in the picture of reference.

Screenshot 2024-03-24 at 6 41 37 PM

**Review by hetvi11110 — DISMISSED** [review]
I've tested the layout across various screen sizes and browsers, and it appears fine.
image

**Review by kylepham — DISMISSED** [review]
Input boxes are aligned with labels on both desktop and mobile views.
Screenshot 2024-03-26 at 1 36 57 PM
Screenshot 2024-03-26 at 1 36 43 PM

**Review by Abi-Liu — DISMISSED** [review]
Looks better! Now there is no overlap between the text and inputs on all screen sizes.

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi, I just check your PR and is working properly.
PR 2075

**Review by SanketKaware — CHANGES_REQUESTED** [review]
I followed the provided steps to test this functionality but encountered a problem. Here's the scenario:

1. Keep "Best-case" as 0 and press the tab key for best, worst, most, and estimated: No errors are encountered.
2. However, when entering any value greater than 0 in "Most -case" and pressing tab for the next field, a warning occurs. This warning is coded in `src/components/Projects/WBS/WBSDetail/AddTask/AddTaskModal.jsx`.
Screenshot 2024-03-27 at 6 36 19 PM


**Observation:**

The alignment was not handled properly when there was a warning, as illustrated in the attached video review.

**Steps to Reproduce:**

1. Keep "Best-case" as 0.
2. Press the tab key for best, worst, most, and estimated.
3. Observe no error encountered.
4. Enter any value > 0 in Most-case.
5. Press the tab for the next field.
6. Observe the warning as described.

**Video Review:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/16b967b2-c269-4bd7-98fa-41a152c63657

**Comment by Gayathr-2012** [comment]
Hi
 I've reviewed your PR and noticed that there are alignment issues with the hours. It displays perfectly on mobile screens, but there are alignment problems elsewhere.

image

image

image

**Review by iven-yao — DISMISSED** [review]
Looks perfect. good job.
image

**Review by hbodgal — CHANGES_REQUESTED** [review]
This PR fulfills required UI changes. But if user hovers over any of the 4 'Hour inputs', it shows "Hours - Best Case" in tooltip. Either all tooltips should be removed or Texts of the tooltip should be specific to each 'Hours Input' box.

PR_2075

**Review by Renanluizssx — COMMENTED** [review]
Hello @Gugor99, i veryfied your application and it's running correctly, but i noticed a little detail in date inputs, in some smartphones, the inputs leaked out, please look my review below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/32503ce2-2dbb-49ae-9272-a27dc00f8511

**Comment by MQChen211** [comment]
Hi, I tested the functionality and it worked as expected.
PR2075

**Review by MQChen211 — DISMISSED** [review]

**Comment by hiralsonip** [comment]
Hello @Gugor99 ,

I've reviewed the changes, and everything looks great. However, on one screen size, the input boxes overlap the text, as shown in the screenshot.

Responsive

Galaxy_Fold

**Review by bhuvaneswarignanasekar — APPROVED** [review]
I have reviewer the PR. Looks good on all screen. 
Screenshot 2024-04-03 at 5 14 01 PM
Screenshot 2024-04-03 at 5 13 51 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
