### PR TITLE
Shefali_UnitTest_VolunteeringTimeTab

### PR DESCRIPTION
**Pull request by SMitta11**
# Description
Unit tests for src/components/UserProfile/VolunteeringTimeTab/VolunteeringTimeTab.jsx
Created file VolunteeringTimeTab.test.js and added test cases in it.

## Test cases included:
    ✓ should not error out due to no tests (popper.js.js) 
    ✓ should not error out due to no tests (mockStates.js) 
    ✓ should not error out due to no tests  (utils.js) 
    ✓ renders without crashing
    ✓ displays the correct Total Tangible Education Hours
    ✓ displays the correct Total Tangible Society Hours
    ✓ displays the correct Total Tangible Energy Hours
    ✓ displays the correct Total Tangible Food Hours 
    ✓ displays the correct Total Tangible Housing Hours
    ✓ displays the correct Weekly Committed Hours

## How to test:
1. check into current branch
2. npm install
3. npm test VolunteeringTimeTab.test.js

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (276)

**Review by neha3010 — APPROVED** [review]
It passed all the test cases.
Screenshot 2024-12-23 at 8 20 57 PM

**Review by beblicarl — APPROVED** [review]

**Review by nikhilgiri0226 — APPROVED** [review]
I have tested this PR and all the test cases passed successfully.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
