### PR TITLE
EduardoV - create unit tests for the TeamsOverview component

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the TeamsOverview component to confirm whether it working as intended.

## Main changes explained:
- Export file TeamsOverview.jsx for the test component
- Create file TeamsOverview.test.js to do the unit tests

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install` to run this PR locally
4. open file src → tests → Teams → TeamsOverview.test.js
5. run `npm run test src/__tests__/Teams/TeamsOverview.test.js`

## Screenshots or videos of changes:
This is the result it's supposed to get:

Screenshot_1

If all tests passed, everything worked as intended.

### CODE REVIEW

**Comment by AnishPandita** [comment]
Hey, the tests run perfectly without any errors. Looks good to me.
Screenshot 2023-09-21 at 6 26 52 PM

**Comment by astrjc0326** [comment]
The tests were able to run and pass without error.
Screen Shot 2023-09-21 at 6 37 59 PM

**Review by Jiyuanxia — APPROVED** [review]
Hi @eduvarjaor , I have reviewed your pull request and tested it. It works as you intended. Well done!
Screenshot 2023-09-21 223131

**Review by luisarevalo21 — APPROVED** [review]
Hello @eduvarjaor ,

I tested your PR and works as intended great work! 
Screenshot 2023-09-21 at 7 55 58 PM

**Review by Haoj1 — APPROVED** [review]
@eduvarjaor All tests passed! It works good

**Review by JYXiao-2021 — APPROVED** [review]
I test this and it run well
testpr

**Review by harshidad — APPROVED** [review]
All test passed. 

PR#1332

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-09-22 005207

**Review by Sssky-18 — APPROVED** [review]
Hi @eduvarjaor, just tested this PR. All the cases were passed, great work! 
PR#1332

**Review by EdwinLauM — APPROVED** [review]
Hey @eduvarjaor! Works as expected and code changes look good!

Screen Shot 2023-09-22 at 9 43 44 AM

**Comment by Vishala09** [comment]
Tested your code. All test cases passed. Works as expected.

image

Looking good in UI as well
image

**Review by Vishala09 — APPROVED** [review]

**Review by dah00 — APPROVED** [review]
Hey, all tests passed as intended. Great job!
PR1332_passed

**Review by KurtisIvey — APPROVED** [review]
Tests pass without issue
pr1332 test passed teamsoverview

**Review by DavidC0126 — COMMENTED** [review]
@eduvarjaor I tested the PR and it works as intended!
test_teamoverview

**Review by tsunami776 — APPROVED** [review]
All tests passed. Nice work!
CleanShot 2023-09-22 at 19 02 09@2x

**Review by TuanDinh140194 — APPROVED** [review]
I have test the PR, it run correctly without any error.
Screenshot 2023-09-22 184343

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended!


Week4 - PR7 (#1332)

**Review by EdwinLauM — APPROVED** [review]
Hey @eduvarjaor, works as expected and code changes look good!

Screen Shot 2023-09-22 at 11 00 23 PM

**Review by JeffLi117 — APPROVED** [review]
Tests work as intended, good job.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
