### PR TITLE
Gabriele - Fix user management inputs layout

### PR DESCRIPTION
**Pull request by Gugor99**
# Description
Two inputs in the User Management are missing style. Select input below "Role" should have the same height as the others, text input below "Wkly Committed Hours" should be centered. 

## Related PRS (if any):
To test this PR check into current branch for Frontend and for backend use the development branch.
…

## Main changes explained:
Increased select input size in DropDownSearchBox.jsx
Centered text input in UserTableSearchHeader.jsx

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. go to Other links→ User management
6. verify select input under "Role" is the same height of the others and text input under "Wkly Committed Hours" is centred above the column. Check everything is working as expected

## Screenshots or videos of changes:
Before:
Cattura2

After:
Cattura1

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by meetpadhiar4 — DISMISSED** [review]
Hi, I tested your PR and it works as intended. Please refer the screenshot attached.

PR 2065

**Review by Abi-Liu — DISMISSED** [review]
Looks good! The height for the `Role` input is the same as others and the `Weekly committed hours` input is centered.
Screenshot 2024-03-15 at 3 40 11 PM

**Review by sameersdeshpande — CHANGES_REQUESTED** [review]
Hello @Gugor99 
works as expected. the weekly hours is getting aligned at the centre and looks fine for me.
Also I would suggest the email field could also be made aligned in a same way as centre.
Keeping it as request changes and let me know if email should be kept the way it is.
Screenshot 2024-03-16 at 1 14 12 AM

**Review by linkhanthtel — DISMISSED** [review]
It look good! The role input field is same as the others.

Screenshot 2024-03-16 at 5 41 01 PM

**Review by lacnoskillz — DISMISSED** [review]
Hello @Gugor99 
I pulled your changes and tested them

Below you can see how the user management table looked before

pr 2065 before

And here you can see it with your changes and that the inputs now have style and match the others

pr 2065 after

Good find and nice work!

**Comment by dhairya-mehta** [comment]
Hey , I verified and tested your PR, the centre alignment of the input box under committed hours and the role look correct!
image

**Review by lacnoskillz — APPROVED** [review]
@Gugor99 
just tested the changes you made
The email alignment looks good!
Nice work
BEFORE:

user management header before

AFTER:
image

**Review by SRamen1999 — COMMENTED** [review]
After testing this PR everything works as expected.

Screen Shot 2024-03-21 at 9 58 50 PM

**Review by mohabbasd — APPROVED** [review]
Hello, I tested you PR and it looks okay but still the role is slightly shorter than the rest, it is not noticeable but still it is. Otherwise everything looks good.
Below is a screenshot for your reference.
Screenshot 2024-03-22 at 2 44 56 AM

**Comment by rajnada** [comment]
Hii,

I have checked the textbox it looks nice and no issue related to the design. Good Job!

image

On a Mobile Screen as well as on another screen it looks perfect!

image

**Review by Coops023 — APPROVED** [review]
Hi Gabriel, i have reviewed this PR and the styles are looking good.

keep3

**Comment by Gayathr-2012** [comment]
Hi 
"I tested the changes you made, and everything is functioning as expected. The weekly committed hours (Wkly Committed Hrs) are now centered for that column.

image

**Review by yaow62023 — APPROVED** [review]
Hi, I have tested you PR, the Role select box is align with other boxes, and weekly commit hours are center in the container. 
Screenshot 2024-03-22 at 11 16 21 PM
2065

**Review by psharma1984 — APPROVED** [review]
hi @Gugor99 the text is centered. 

[screen-capture.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/b69b525f-7ddd-4153-b080-f12e99dc037c)

**Review by iven-yao — APPROVED** [review]
Hi, I just reviewed this pr, and everything looks good!
- [x] inputs have the same height
- [x] Wkly committed hrs input is centered  
- [x] every filter working as expected
image

**Review by Jaiwin-4998 — APPROVED** [review]
It looks good.!! The role input field has the proper width and height. 
Screenshot 2024-03-23 at 6 55 06 PM

**Review by Sarthak32 — APPROVED** [review]
Hi, I tested your PR and it works as expected it looks good !
Screenshot 2024-03-24 115949

**Review by Tiantian-C — APPROVED** [review]
I have tested this. And the role field looks nice.
Screenshot 2024-03-24 at 6 48 53 PM

**Review by hetvi11110 — COMMENTED** [review]
I have reviewed the PR as explained, and the input fields look good.
image

**Review by bhuvaneswarignanasekar — APPROVED** [review]
I reviewed the PR. Input layout for 'Role' and for 'Email' looks good. 
Screenshot 2024-04-03 at 3 04 26 PM
Screenshot 2024-04-03 at 3 04 17 PM

**Comment by hiralsonip** [comment]
I've checked your PR, and everything is working well.

PR2065

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
