### PR TITLE
Nahiyan_Fix projects table when toggling dark mode

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
When toggling dark mode, the table would not update. Now the table and all its content update when toggling dark mode.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to dashboard→ Other Links -> Projects
6. verify that everything on the page works properly when toggling dark mode.

## Screenshots or videos of changes:
Before:
Screenshot 2024-06-18 142856

After:
Screenshot 2024-06-18 142913

### CODE REVIEW

**Review by kdaga81 — CHANGES_REQUESTED** [review]
image
image

Can we have white shadow for the icons in dark mode? It'd make the button more intuitive.

**Review by kdaga81 — CHANGES_REQUESTED** [review]
image

We can change the color for "Back to Top" button to make it go in better contrast with the dark mode.

**Comment by Vijeth-V** [comment]
In light mode 
Screenshot 2024-06-18 at 11 26 46 PM

In dark mode
Screenshot 2024-06-18 at 11 26 52 PM


It would be better if we could add row highlighters for the projects when we hover.

**Comment by Nahiyan-16** [comment]
Hi @Vijeth-V, thanks for the review. The hover effects will be implemented with this PR #2311

**Comment by Nahiyan-16** [comment]
Hi @kdaga81, thank you for the review. The requested changes are unrelated to what the PR is supposed to fix.  Please add these requests under the Dark Mode section on this [google doc.](https://docs.google.com/document/d/1n5NIb3dbiSrIRuOG1ZCwt34pEP1poqddCv1guaQml88/edit)

**Review by Logeshwari-Renu — APPROVED** [review]
When toggling dark mode, the DOM is changed to dark and works fine!

**Review by Jingyii800 — APPROVED** [review]
It looks good now. On projects page, the background and table changes black in dark mode, which looks great.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/7cf6c998-7512-492d-bc12-fd25008d4372

**Review by aaryaneil — APPROVED** [review]
The changes work as expected, just the shadow effect for buttons and back to the top button needs to changed based on the other reviews.
Screenshot 2024-06-21 at 2 39 59 PM
Screenshot 2024-06-21 at 2 39 52 PM
Screenshot 2024-06-21 at 2 40 31 PM

**Review by jinxyou — APPROVED** [review]
The night mode toggle works fine. Great work! 
Screenshot 2024-06-22 193855
Screenshot 2024-06-22 193911

**Review by deepthikannan — APPROVED** [review]
image
image
The dark mode toggle works fine.

**Review by KaushikMreddy — APPROVED** [review]
Hi, 

The project table toggles between light and dark mode well.
image

image

**Comment by IchinnorovTuguldur** [comment]
Hello Nahiyan,

Everything seems to be working when toggling between light and dark mode. But there is error message in the browser console saying " Encountered two children with the same key". Can you take a look at this error?

Screenshot 2024-06-28 at 8 46 38 PM

**Review by sahithidhulipala9 — APPROVED** [review]
Working Perfectly!

PR 2370

**Review by Rishitha1309 — APPROVED** [review]
everything works perfect when toggling dark mode
PR2370
PR2370-2

**Review by JatinAgrawal94 — APPROVED** [review]
Dark Mode works fine on the project page. Every feature on the page works as it should be. Good work!
Screenshot 2024-07-12 at 6 58 55 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
