### PR TITLE
Shiwani OwnerMessage component Lint fix

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Lint fix for OwnerMessage component

## Main changes explained:
- src/components/OwnerMessage/OwnerMessage.jsx

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as owner user
4. go to dashboard->click on the edit icon in the header -> add a new message
5. check if the functionality for OwnerMessage works as before and if there are any errors in OwnerMessage.jsx file
6. Additionally, please check if there are any lint errors when you do npx eslint src/components/OwnerMessage/OwnerMessage.jsx
7. Feel free to include any comments or screenshots of your test

### CODE REVIEW

**Comment by mounica-dingari-by** [comment]
Hi @Shiwani99 , I've tested your PR and it works as intended. I approve your PR.
Screenshot from 2023-10-13 13-53-28

**Review by yangfan2001 — APPROVED** [review]
Hi, I have read and reviewed your PR. It looks great. There is no lint error. Great Job
image

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test this pr and it works as intended. The functionality works well as shown in below image.
Screenshot 2023-10-14 at 3 11 01 PM
Screenshot 2023-10-14 at 3 10 18 PM

**Review by StrawberryCalpico — APPROVED** [review]
Hi, I tested your PR and everything works. Great Job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/40b6e7e6-581d-41f8-9dd9-7530241a5255

**Review by zuhang2000 — DISMISSED** [review]
Hi I've tested your PR following your instructions. Everything is working as expected. The feature is working correctly. And I don't find any errors when running "npx eslint src/components/OwnerMessage/OwnerMessage.jsx".
Screenshot 2023-10-15 at 12 47 45 AM

**Review by JeffLi117 — DISMISSED** [review]
Changes work as intended. Good job!

image
image

**Review by wantingxu7 — DISMISSED** [review]
Hi, I just tested and the function works well.

**Review by lacnoskillz — COMMENTED** [review]
Hey @Shiwani99 
I pulled your code and everything seems to be working as expected
However I noticed the upload picture doesn't seem to be working and will freeze when i try to upload a picture. I tested uploading on development and it works there.


vid of the error/bug I found:

[Untitled_ Oct 17, 2023 1_24 PM (1).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/e1450e4f-ea6e-4819-9df8-8b10fefdf89f)



Vid of me testing the edit successfully with text:

[Untitled_ Oct 17, 2023 1_09 PM (1).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/12893426-0993-4adc-99f0-b750f4e1a666)

Running npx
image

Nice work and happy coding!

**Comment by Shiwani99** [comment]
> Hey @Shiwani99 I pulled your code and everything seems to be working as expected However I noticed the upload picture doesn't seem to be working and will freeze when i try to upload a picture. I tested uploading on development and it works there.
> 
> vid of the error/bug I found:
> 
>  Untitled_.Oct.17.2023.1_24.PM.1.webm 
> Vid of me testing the edit successfully with text:
> 
>  Untitled_.Oct.17.2023.1_09.PM.1.webm 
> Running npx image
> 
> Nice work and happy coding!

Hi @lacnoskillz, Thank you for pointing this out. I had missed sending event to the image handler which is why you are experiencing this bug. I have made the changes and you can pull the recent changes and check on your end. I have checked it on mine and the image upload part works fine now.

**Review by Sssky-18 — APPROVED** [review]
Hi @Shiwani99, your lint fixes looks fine and there is no errors shown in the console. Congrats!

PR#1411

**Review by Iris-Song — APPROVED** [review]
hi, I have tested and things works as intended. Good job.
image
image

**Review by Shubhu0 — DISMISSED** [review]
Hi @Shiwani99 The PR is working as intended. Good job
image

**Comment by RheaWu1212** [comment]
Hi this PR working as expected!
Screen Shot 2023-10-21 at 10 43 03
Screen Shot 2023-10-21 at 10 44 42

**Review by Jiyuanxia — APPROVED** [review]
Hi @Shiwani99 , I have reviewed your pull request and tested it. It works as you intended and there is no lint error. Good job!
Screenshot 2023-10-24 191832
Screenshot 2023-10-24 191942

**Review by yi-lin-1234 — APPROVED** [review]
Hello, functionality of the OwnerMessage pages is the same as before. I can update the message successfully.  And, the ESLint passed without error. Great work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92185695/8136e598-1ad0-43e8-8f52-7c8d0050dbe0

Screenshot 2023-10-31 at 3 05 49 PM

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-11-03 162827

**Review by malikjahanzaib — CHANGES_REQUESTED** [review]
Hi @Shiwani99, everything works as intended. Clean code, no lint errors and app works normally.
Only thing I noticed is when I change the owner message it gets reflected fine but when I reload the page it returns to the original message. The changed message doesn't persist, it that how its supposed to work? 

Screenshot:

image

image

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/dd92871a-9a4e-4e9a-90df-bb597e4912c5

**Review by EvianTan — APPROVED** [review]

**Comment by EvianTan** [comment]
Hey @Shiwani99 , just want to check the status of this PR. Are you still seeing the problem @malikjahanzaib mentioned above?

**Comment by Shiwani99** [comment]
> Hey @Shiwani99 , just want to check the status of this PR. Are you still seeing the problem @malikjahanzaib mentioned above?

Hi, sorry for the delayed reply, everything else is working as expected except for the update standard message. If I reload the page, the standard message that I updated is reverting to original standard message. I noticed that even in development sometimes standard message does take a few reloads to update the standard message. Initially, there were a couple of redux actions that were imported and also added as arguments to the component and that was raising a lint error so i removed the those arguments from the function and I feel that might have caused this issue. I'm attaching a video of how the behavior of update standard message is in development. I'm not sure what is causing the issue as everything seems to be fine.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78906820/3315da91-774d-43e8-a130-c89b7a5945ad

This picture below updates the standard message after pausing for a couple of minutes and then reloading it
Screenshot 2023-11-25 at 8 06 47 PM

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
