### PR TITLE
Jacob fix blue square scheduler save button after switching dates

### PR DESCRIPTION
**Pull request by DragonSlayer2401**
# Description
image

## Related PRS (if any):
N/A

## Main changes explained:
- Remove unused code from ScheduleReasonModal.jsx
- Fix the save button from disabling 

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any kind of user
5. go to Dashboard→ Blue Square Record→ Schedule Blue Square Reason
6. verify that after changing the date, your reason stays and the save button works without having to update the reason

## Screenshots or videos of changes:
Before:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/df3a8c5c-b887-416d-9497-1fe2b9523716

After:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/c2928d79-7ba0-4659-b664-514eac19f6ea

### CODE REVIEW

**Comment by Cavein254** [comment]
@DragonSlayer2401  the functionality works as expected


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13707896/87977bab-8cf2-4f84-97d9-c7b08bd4eda8

**Review by scoopstroop92 — DISMISSED** [review]
Works as expected. Good job 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/b8ad4a36-39c6-4ecf-a612-c6f6de8df4f6

**Comment by mianmiantea2019** [comment]
@DragonSlayer2401 it works as expected. Good job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/59427068/19eff513-0ac8-4455-a09e-ebf0197e59aa

**Review by beblicarl — DISMISSED** [review]

**Review by bajajtushar094 — DISMISSED** [review]
@DragonSlayer2401 I tested your PR and it works fine. Thanks 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58565094/cfbf8925-1b47-466b-91d2-000a1d19a054

**Review by keyunhuangg — DISMISSED** [review]
Changed 3 different date without the text change and all of them could be saved!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/124097392/1ca270aa-3127-4642-8fe9-b00b4cd7eea2

**Review by ShengjieMao — DISMISSED** [review]
The page works as expected. Great work.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/447b40ff-525c-4d7a-bfed-1921284e5793

**Review by peterson337 — DISMISSED** [review]
it works as expected. Good job

one comunnity

**Review by peterson337 — DISMISSED** [review]
it works as expected. Good job

one comunnity

**Comment by swathyjayaseelan** [comment]
Works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/c6e748a3-b294-49b8-a455-772c34901fca

**Review by Pandani07 — DISMISSED** [review]
Works as intended!



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/e12951b6-1966-40f5-9022-c78b03301843

**Comment by DragonSlayer2401** [comment]
test

**Pull request merged**
