### PR TITLE
Nahiyan-Project's tab overhaul

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Issues:

1. When deleting a project from the projects tab within the user profile, the user can assign another project without saving it. This is incorrect because when the user attempts to add another project, it will not work. 
2. No tooltip on hover over the 'Assign Project' button when disabled.
3. The Cancel button would not revert the changes made to projects
4. Users who aren't able to delete projects or tasks can see the delete button column
5. When deleting a project, that project row disappears but the tasks affiliated with it do not. (Only after saving do they disappear) 
6. Buttons are not on the same line as the tasks header or the projects header
7. When clicking "Assign Project", the input should be autofocus on the popup

## Desktop Version:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/c7283701-6281-45d4-948f-e559e0462321
## Mobile Version:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/2eb14ef4-5fb1-472f-a1f0-c62d5d29f4f1

## Related PRS (if any):
Use development backend

## Main changes explained:
- Cursor automatically on popup input after clicking on the `Assign project` button
- The `Assign project` button is disabled when deleting a project
- Also the same for tablet/phone view
- When deleting a project, it also deletes the affiliated tasks.
- Users who are unable to delete projects, cannot see the delete buttons column
- Users who are unable to update tasks(add/remove) cannot see the add/remove columns
- Clicking on cancel will now revert any changes made to the tasks or projects
- Clicking on the 'X' button on mobile view will now revert any changes made to tasks or projects
- Extracted styling to CSS file or incorporated within the class name
- Moved the `Assignn Button`  to be on the same line as the Projects header
- Moved the tasks filter buttons to be on the same line as the Tasks header

## How to test:
1. check into the current branch
8. do `npm install` and `npm run start:local` to run this PR locally
9. Clear site data/cache
10. log in as owner user
11. Dashboard -> User Profile -> Projects Tab
12. Make sure the cursor is automatically on the popup input when clicking on `Assign project`
13. Add any project 
14. Delete any project
15. The following should occur: 
- `Assign project` button is disabled
- When the `save changes` button is clicked, then the `Assign project` button will be enabled again
16. Steps 5-6 should be repeated in a tablet or phone view (width lower than 1025px)
17. Make sure the `Assign project` button is disabled after deleting a project
18. Assign tasks to this user, check out this video on how to do that, [Video](https://www.loom.com/share/8bc672c323b64955aac4bce46c3794aa?sid=92b7b345-237d-4c9f-b05d-d16aebacf90f)
19. Attempt to delete a project (Do not hit save changes), the tasks affiliated with that should disappear
20. Click on cancel. 
21. Project(s) and tasks should have reverted to original

## Changes
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/ea80f395-504e-49ee-b659-eb2eda8475fd

### CODE REVIEW

**Review by TareqMia — DISMISSED** [review]
Hi @Nahiyan-16, I reviewed this PR and everything worked as expected. I logged in as a Owner user and the "Assign Project" button was disabled when I was deleting a project, and it was enabled again when I pressed "Save changes" (tested on a smaller screen size too). The tasks associated with a given project are also removed when deleting a project, and reappeared when the "Cancel" button was pressed. Everything was quick and snappy. Overall, great job implementing this. 

**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/2cf20f05-6db2-460d-b865-108408cbc772


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/248029ff-2b11-4fa5-96e8-1cc477c8ce7a

Smaller Screen:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/c815cba0-c364-4b67-8de8-5ad530f1607b


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/835a2404-c97c-487d-adcd-a9ac6f68c89e



Please note to address the merge conflicts.

**Comment by nnamdixobi** [comment]
After reviewing, the functionality works as expected . Following the documentation on how to test, I logged in as an owner and observed the "Assign Project" button correctly disabled during project deletion, only to be re-enabled upon pressing "Save changes." Additionally, tasks linked to the project were appropriately removed during deletion and reappeared when the "Cancel" button was pressed.

**Review by DiegoSalas27 — CHANGES_REQUESTED** [review]
Hi Nahiyan. After testing your changes, I noticed the project tab doesn't display the Save button or the cancel button. I think you may have missed to include the "activeTab === '4' as part of the conditions to dsiplahy those buttons. Please, update line 1405 to contain the following code:

`{canEdit && (activeTab === '1' || activeTab === '2' || activeTab === '3' || activeTab === '4') && (`

image

This is the only comment regarding your changes. Great work.

**Review by XiaohanMeng — COMMENTED** [review]
Hi, I tested this PR and found all functionalities well-implemented, especially the disabling of the 'assign project' button when a project is deleted without saving changes. However, I am uncertain about one aspect: it seems that after assigning a project, all changes can be saved without needing to click the 'save changes' button below. Please refer attached video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/0580379a-a5d3-47ff-82bc-cb3c64998a25


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/0197793a-2850-425d-a692-3f6b6d23324f

**Review by ClemarNunes — COMMENTED** [review]
I tested your PR and it worked as expected

However, I tried to add a task but it didn't appear on the profile, I don't know if I was making a mistake, follow the video.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/545af843-4b96-47ad-a6a8-7aa8ecb70d4e

**Comment by Nahiyan-16** [comment]
> I tested your PR and it worked as expected
> 
> However, I tried to add a task but it didn't appear on the profile, I don't know if I was making a mistake, follow the video.
> 
>  go.mp4

@ClemarNunes Hi Clemar, after doing a bit of digging, I was able to find the root of the problem and that is the caching system implemented in the backend. 
Screenshot 2024-02-29 125255
If we were to delete the highlighted code above and get rid of the caching, the issue no longer be there. 

Before, the cache expires after a couple of minutes and updates the user profile. 

This is something I have to ask Jae about since caching is very important to the speed and efficiency of the application itself.

**Comment by Nahiyan-16** [comment]
> Hi, I tested this PR and found all functionalities well-implemented, especially the disabling of the 'assign project' button when a project is deleted without saving changes. However, I am uncertain about one aspect: it seems that after assigning a project, all changes can be saved without needing to click the 'save changes' button below. Please refer attached video.
> 
>  1931_result1.mov 
>  1931_result2.mov

@XiaohanMeng Hi Xiaohan, the problem you were addressing is actually a feature that Jae wanted to implement

**Review by DiegoSalas27 — APPROVED** [review]
:)

**Review by skaush21 — DISMISSED** [review]
All implemented features mentioned in description work!
* when deleting a project, user must save changes
* Assign button is disabled when deleting a project
* verified that tasks disappear when project is deleted.
* verified that tasks appear when project is added (so long as tasks were assigned)
* verified that users without permissions (volunteers) are unable to add/delete projects, these features are invisible to them
* verified that if a project is deleted -> cancelled, project will reappear. changes will not be made.
* 'x' button on mobile reverts changes made
* reviewed code, changes look good, no issues found


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/e77c130b-1030-4d79-92d6-2b90a34588b7


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/141872402/f6de5f4e-ab63-4f73-8818-5ab2bfc7a5ed

**Review by psharma1984 — APPROVED** [review]
Hi @Nahiyan-16  The code worked as expected. I logged in as a Owner and the "Assign Project" button was disabled when I was deleting a project, and it was enabled again when I pressed "Save changes" (tested on a smaller screen size too). 

[screen-capture (4).webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123996264/1d54090a-0a93-4123-a173-880a25535154)

**Review by MALAV1308 — DISMISSED** [review]
Hello , I have reviewed your PR and it is working correctly as you mentioned in description. In below Screenshot, Assign Project button is disable during deleting the task but not saving the task.
Good Job!

**Review by sucheta90 — DISMISSED** [review]
Hello @Nahiyan-16, I have reviewed this PR and all functionalities work as expected. The `Assign Project` - button was disabled while deleting a project and was enabled once the change was saved. The Layout looked perfect on the mobile screen size as well. Well done. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/2ec52cfe-145b-4635-8ba9-ee6c989e021c

**Comment by SanketKaware** [comment]
**Followed all the mentioned steps and the changes look good to me.** 



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/17793708/9accded5-94d7-4c92-bad4-794ab6e1685d





**Suggestion**: 

After selecting a project, and "Confirm" it, the input field should auto-focus with the cursor, allowing users to add another project without manually focusing. 

This improves user experience. 

In the **AddProjectsAutoComplete** component, you would need to ensure that the input field receives focus/cursor when the component renders and adds the project.

**Review by DiegoSalas27 — DISMISSED** [review]

**Review by hetvi11110 — DISMISSED** [review]
Hello, I tested your PR as mentioned and it worked as expected. Here is the reference video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13557067/01c39e49-09a4-4828-bc47-1f082b0ba675

**Review by Sarthak32 — DISMISSED** [review]
I tested it as mentioned and it works as expected .
Here is the refrence video: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/92269596/7f07676c-add8-48a9-a87b-6cc68ebb45a5

**Review by bhuvan-dv — DISMISSED** [review]
Working as expected, good to be merged!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67942070/f70a462c-f9e1-4354-9894-e39d7523261d

**Review by iven-yao — DISMISSED** [review]
Hi, I reviewed this pr, and everything works perfectly as expected.
- delete project
- [x] `assign project` button is disabled
- [x] after click `save changes`, assign button will be enabled
- delete project with assigned task
- [x] related task will also disappear
- [x] project and tasks will show again if `cancel` is clicked
- [x] project and tasks will be deleted correctly if `save changes` is clicked 
image
image
image
image
image

**Review by SRamen1999 — COMMENTED** [review]
After reviewing this PR and all functionalities work as expected. You can add/delete projects and the tasks get removed/added properly based on the current projects.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/840ef729-e961-4723-9af5-fee4f4cce207

The Layout for mobile screen also works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/259d8222-b0f9-40a2-805d-fbfcb636dbf3

**Review by kylepham — COMMENTED** [review]
Every issues has been resolved and tested. Below is the testing video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/fb59f0ec-e9ee-44a8-8dcd-0c8cb6b842ff



I only have one concern: reverting the changes by clicking "Cancel" doesn't enable the "Assign project" button and disable the "Save changes" button. I think it's not very intuitive to revert changes of something and also have to save changes every time. Please refer to the video below.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/35129229/ca9d30a8-1692-4b3f-89ec-e359ae06f685

**Review by Jaiwin-4998 — DISMISSED** [review]
Hi i just checked your PR and the functionalities is working as expected in both mobile and desktop view.

Screenshot 2024-03-29 at 10 09 37 AM
Screenshot 2024-03-29 at 10 08 23 AM

**Review by anandsesha — DISMISSED** [review]
Hi, I have tested this PR and all changes work as expected both in Desktop and mobile below 1025px views.

- On clicking the 'Assign Project' cursor automatically on popup input
-  The Assign project button is disabled when deleting a project and when save is clicked assign button is available again
- Deleting project also deletes associated tasks
- Cancel when clicked reverts all changes made to task or project. Same for 'X' in mobile view

https://www.loom.com/share/44de853ac0b9467993663fd830c689b6?sid=fccc88fa-0542-4968-b6a9-8b64738f0baf

**Review by MQChen211 — DISMISSED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
