### PR TITLE
Xiao T - Add box shadow style throughout the app

### PR DESCRIPTION
**Pull request by AuroraLovesWhales**
This PR is a continuation of [PR862](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/862).
# Description
(PRIORITY LOW) Jae: Create Shadow Consistency for the Dashboard
a. Please add the shadow shown below to the rest of the buttons on that page: 
image
b. Definitely these two areas, but any other areas on this page you think they would look good too: 
image
c. Setting it up so everything throughout the app with these shadows can be adjusted with one code change. Then look at all the other pages and see where this can be applied there too... include all the Admin-level pages.

## Main changes explained:
Added styles.js file in the components folder to apply {boxShadow: '2px 2px 4px 1px lightgray',} to all the major buttons throughout the app to maintain style consistency. Also added some padding between the three icons next to "Tasks and Timelogs" to make it look better.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as any user and verify that the changes have been made

## Screenshots or videos of changes:
Some examples:
Pasted Graphic 25
Pasted Graphic 29
Pasted Graphic 27
Pasted Graphic 30
image

## Note:
Please check throughout the app, including owner/admin level, to make sure the style is consistent. Also, please let me know if you think the application of the style is unnecessary in some parts of the app.

### CODE REVIEW

**Comment by one-community** [comment]
Still has branch conflicts. Also, I added "do not review" to 862. Is everything in that here and should that be closed now?

**Comment by AuroraLovesWhales** [comment]
> Still has branch conflicts. Also, I added "do not review" to 862. Is everything in that here and should that be closed now?

Apologies. I will try to resolve it. Everything in 862 is here and 862 can be closed now.

**Review by NidaZaki — COMMENTED** [review]
Changes look good. Almost all the buttons have box shadow
But is it possible to apply box-shadow on these two buttons as well? Please refer the image
PR#878-3

**Comment by NidaZaki** [comment]
Great effort, but on a feedback note there should be a way to achieve global changes like this through a main css file without needing to repeatedly inject the css styles into each component. So the idea would be do apply the box shadow to all `button` tags/elements in the app to a main css that is inherited by all child components at runtime. Might be out of scope of the PR but definitely a worth while topic to be researched and discovered.

**Comment by yufeiStella** [comment]
When logged in as an admin, I noticed that the buttons below "Other Links" -> "Permissions Management" -> when clicking on any role, the "Add" and "Delete" buttons do not have the shadow style.
Screen Shot 2023-06-03 at 17 22 03

**Comment by alexander-huerta** [comment]
I was going to suggest the same @NidaZaki 

Doing this for each file ads a lot of redundant code but also will also have potential side effect to the tests for 65 files. 

Globally styling in the src/App.css is much easier for you to code and for anyone to maintain, debug, and will ensure no buttons are missed

**Comment by AuroraLovesWhales** [comment]
> Changes look good. Almost all the buttons have box shadow But is it possible to apply box-shadow on these two buttons as well? Please refer the image PR#878-3

@NidaZaki. Thank you for your feedback! I have added the missing style to these buttons.

**Comment by eduhorta** [comment]
Hi, @AuroraLovesWhales.
When I start the app on your branch my browser totally freezes. I have to close the app using task manager.

I did try your other commits and it worked fine.
Here is the commit I'm facing this issue: `8b6b18ea44fbef7439248dcece791958ec1e0234`



Screenshot 2023-06-06 09-36-55

**Review by 20chen-7 — COMMENTED** [review]
It looks like some code issues are fixed yesterday, but they still exist in this branch. I could not be able to test. 
Screenshot 2023-06-07 at 12 55 45 PM

**Comment by KurtisIvey** [comment]
Also experiencing the same issues as others that were resolved in the recent hotfix, but present here.

**Review by OAkinbode — COMMENTED** [review]
Hello, 

The PR doesn't seem to be working at all on my machine. I posted a video below that shows me checking into the branch and rerunning the front end. The branch displays nothing on the screen. Maybe I did something wrong. It might be what others have mentioned. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104801652/e33b0502-4b10-4d9d-a046-a807ba53e908

**Review by 20chen-7 — DISMISSED** [review]
Now, code and function as intended.

**Comment by eduhorta** [comment]
Hi, @AuroraLovesWhales!
I'm checking throughout the app and everything seems to be working.
Not sure if it's related to your PR but when I try to access "Other Links -> Projects -> WBS -> Pick any" the page won't load.
I did send you a message on Slack so we can sort this out.

**Comment by cvtqx** [comment]
Apart from the blue Back button mentioned by @Chuehleo , all other buttons look consistent in style.

Screen Shot 2023-06-16 at 2 58 02 PM

**Review by bienzguoa — COMMENTED** [review]
Hi,
Most box buttons have shadow style, but I think these can also have:
Dashboard->Tasks-> the bell button under "Progress"-> Mark as Read
Screenshot 2023-06-17 at 2 48 37 AM
Current Week Timelog -> any time entry -> the trash button -> Cancel /Delete
Screenshot 2023-06-17 at 2 44 13 AM
Leaderboard -> the dot/star besides names -> OK/ Cancel
Screenshot 2023-06-17 at 2 48 00 AM

**Comment by Lucas-E** [comment]
Hey @AuroraLovesWhales, awesome work! Please address the conflicts so I can move it to final review! Once the conflicts are resolved, please DM me on Slack!

**Review by jonathancarpena — DISMISSED** [review]
@AuroraLovesWhales All the box shadows are showing up like you intended.

However I feel like some buttons have unnecessary box shadows such as the Team Management page with Members, Edit and Delete button. Maybe add box shadow on hover for some of the _least_ important buttons? But that's just my personal preference 😁

Otherwise the box shadows are showing and working like you intended. Good job! 👍

**Comment by rachnapandya** [comment]
Most of the boxes have a shadow style.
image
image
image
image
image

**Comment by KaixiangGU** [comment]
Hi @AuroraLovesWhales codes looks good! Styles looks good!
Please address the conflicts and I will approve once you done that.

**Comment by AuroraLovesWhales** [comment]
> Hi @AuroraLovesWhales codes looks good! Styles looks good! Please address the conflicts and I will approve once you done that.

Hi @KaixiangGU. Thank you for reviewing my PR! I have resolved the conflicts.

**Review by KaixiangGU — APPROVED** [review]

**Pull request merged**
