### PR TITLE
Vedant Fix project delete modal in dark mode

### PR DESCRIPTION
**Pull request by vedantg24**
# Description
Fix project delete modal not working in dark mode

Screenshot 2024-11-22 at 12 05 31 PM

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
Updated file `Modal.jsx` and updated dark mode

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links → Projects
6. Set dark mode on 
7. Create a new test project
8. Attempt to “Archive”
9. Verify the modal appears in dark mode

## Screenshots or videos of changes:
https://github.com/user-attachments/assets/e553b9a1-152b-4cad-832c-1682884bffc1

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/bfff9377-7d48-42b6-923e-48d15f78c130

**Review by Nahiyan-16 — DISMISSED** [review]
Hi, great job on implementing dark mode for the archive modal! The UI looks excellent and transitions smoothly. However, there’s a failing unit test. Please check the test logs for details, ensure tests are updated for dark mode, and consider mocking dark mode settings if needed.

Once fixed, update the PR. Nice work overall!

https://github.com/user-attachments/assets/95beee2c-70cd-45c5-ab51-0aa12c784f96

**Comment by ShreyaLaheri** [comment]
Conducted PR review, I had an issue while trying to archive the project, when trying to Archive my page crashed(tested multiple times by adding and archiving project) but later after refreshing the page 2/3 times the project was archived
image

**Review by ShraddhaShahari — APPROVED** [review]
I tested creating new project and then archiving the same and everything works as expected. Modal is correctly shown in dark mode.

PR-review-2887-Screenshot

PR-review-2887-Screenshot 1

**Comment by ppsahu** [comment]
I tried to review this PR, however I am getting login issues of "Unexpected Error", for all the 3 accounts. If you have any leads on how to fix this please let me know.

Screenshot 2024-11-28 at 12 40 42 AM

**Review by SS-Reddys — DISMISSED** [review]
Changes are working as expected

image

**Review by SammanBaidya — COMMENTED** [review]
I reviewed and tested the changes, and everything was functioning well. I did encounter issues while archiving the project but after couple of attempts, the archiving process was successful, and the project was successfully archived.
d1
d2
d3
d4

**Comment by vedantg24** [comment]
> I reviewed and tested the changes, and everything was functioning well. I did encounter issues while archiving the project but after couple of attempts, the archiving process was successful, and the project was successfully archived. d1 d2 d3 d4

Hey @SammanBaidya, the issue for archiving the projects is out of scope for this PR, and it is already being resolved in another PR

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
