### PR TITLE
Lawrence - Hide sensitive data

### PR DESCRIPTION
**Pull request by lchua2314**
# Description

Task desc

## Main changes explained:
- Hide hardcoded login credentials using the .env file for creating a new user.

## How to test:
1. check into current branch
2. do `npm run start:local` to run this PR locally
3. log as admin user
4. go to Other Links→ User Management
5. press Create New User button and create a new user
6. verify that the user is created successfully which means the environment variable was used successfully.

## Screenshots or videos of changes:
Screenshot (2828)

## Note:
Your .env should already have the environment variable "REACT_APP_DEF_PWD" so there's nothing in the .env file that's needed to be changed for this PR.

### CODE REVIEW

**Review by winghojackyli — APPROVED** [review]
User can be created successfully. The PR works as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/d39fe594-8442-421b-8a80-3a33fe617402

**Review by TheDescendant39 — APPROVED** [review]
Hi @lchua2314, I was able to create a new user without any problems. PR works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/837fe380-74a4-4eba-aed6-f8a334bb328f

**Review by navneeeth — APPROVED** [review]
LGTM! The user can be created successfully and the PR works as expected.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/3e988fc9-7874-4d74-9bbf-e1d1e9f881a2

**Review by sxiong5 — APPROVED** [review]
The PR worked as expected! 👍

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/bf5dcb74-d17a-4a5e-bb99-9f10928113a3

**Comment by Lin1404** [comment]
Hi @lchua2314 , I have tested your PR and the user is created successfully. 

image
image
image

**Review by Lin1404 — APPROVED** [review]

**Comment by Jiyuanxia** [comment]
Hello, @lchua2314! I have reviewed your pull request, and it appears that your changes have been effective. Great job!
Screenshot 2023-08-09 164130
Screenshot 2023-08-09 164504
Screenshot 2023-08-09 164523

**Review by DavidC0126 — APPROVED** [review]
Hi @lchua2314 , I was able to create a new user without any problems. PR works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/af2c6413-324b-43c6-ac8f-06cd6afce105

**Review by Jiyuanxia — APPROVED** [review]
Hello, @lchua2314! I have reviewed your pull request, and it appears that your changes have been effective. Great job!
Screenshot 2023-08-09 164130
Screenshot 2023-08-09 164523
Screenshot 2023-08-09 164556

**Review by jerryren527 — APPROVED** [review]
Changes work as intended! I am able to create a new user. Great job!

**Review by yunshan111 — APPROVED** [review]
LGTM. Everything works well.

**Review by ThapeloMasasa — APPROVED** [review]
The new user was created successfully.. which means the environment variable worked as expected

Screenshot 2023-08-09 at 5 06 54 PM

**Comment by AnishPandita** [comment]
Hey @lchua2314 The PR works. Was able to create a new user.

**Review by robertoooc — APPROVED** [review]
Hi @lchua2314, I was able to create a new user with no issues. Didn't find any fringe cases, nice job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/5fc431e7-cbc9-4a9a-aa78-e8337d43c15d

**Review by luisarevalo21 — APPROVED** [review]
Hello @lchua2314 

I tested your PR and works as intended. Great job!
I logged into  an admin account and was able to create a new user with no issues. 
The user was created and I can view their details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/bd913f1f-ef35-4cdb-b6a4-904c868cd05d

**Review by yurisokolovicz — APPROVED** [review]
Dear @lchua2314 

I approved this PR, works as intended! Good job. Please check the video below.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/c7d99d09-d400-41d2-b25a-221682cdecbf

**Review by eduvarjaor — APPROVED** [review]
Hi @lchua2314 

I tested this PR and it is excellent. Good job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/236bd7cc-4168-44b2-ad08-86bb4ec6f5ec

**Review by ramyaram2092 — APPROVED** [review]
Works correctly. Good Job

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/6819a20b-f630-438e-99b3-90fd6b5131bb

**Review by veronicacheng2 — APPROVED** [review]
Hi @lchua2314, I have tested the PR and everything works as intended. I am able to create a new user.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/b7ca1c13-bf83-4637-a8c3-c0a42a89c9db

**Review by n0vay — APPROVED** [review]
I was able to create a new user and the code looks good. Good Job!
image

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, I can create a new user in this PR. Check the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/ee4b06c5-5f26-48b2-993b-3a9538aa0e8a

**Comment by Shreyj14** [comment]
This Pr works as intended. Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/c563721f-6a2b-4d4e-9377-76ca415bfff5

**Review by Shreyj14 — APPROVED** [review]

**Review by zuhang2000 — APPROVED** [review]
Great! I've tested your PR and work as expected! Good job!

Uploading Test1106.mov…

**Review by EdwinLauM — COMMENTED** [review]
Hey @lchua2314. Not too sure what I am doing wrong since it looks like everyone is able to successfully replicate your changes. However, I am not able to create a user and getting a "not implemented" error.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/187247fe-9f48-4b95-a59f-5a102cedbeb0

**Review by Abiddy — APPROVED** [review]
Looks good!

[Screencast from 08-12-2023 06:34:52 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/77697776/e9a301ea-2a77-45c8-90de-82657d594a06)

**Review by belagaam — APPROVED** [review]

**Comment by belagaam** [comment]
Tested the PR with the given instruction. Works perfectly, great work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/31c833c1-ffca-4960-abc3-01f07d83a21f

Lawrence - Hide sensitive data

**Comment by lchua2314** [comment]
@EdwinLauM You might not have the environment variable set up. I replicated the issue by editing the frontend's .env file and removed "REACT_APP_D234234EF_PWD=123Welcome!".

**Review by ss23046 — APPROVED** [review]
Tested this PR, worked perfectly!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99052235/b858b181-7f1c-4a93-a981-40d9f5e2a24c

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this one to final review!

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great! Good work

[screencast-localhost_3000-2023.08.18-11_06_57.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/ee92f55e-60ed-4236-b6ad-5275d55a04e1)

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
