### PR TITLE
Vijay Anand - Unit test weekly summaries report reducer

### PR DESCRIPTION
**Pull request by vijay10pk**
# Description
Added unit tests for the weeklySummariesReportReducer.

## Related PRS (if any):
No related PRs.

## Main changes explained:
- Created a new test file weeklySummariesReportReducer.test.js under the tests directory.
- Test cases include:
  - Returns the initial state when no valid action is provided.
  - Handles FETCH_SUMMARIES_REPORT_BEGIN by setting loading to true and clearing the error.
  - Handles FETCH_SUMMARIES_REPORT_SUCCESS by updating the summaries array and setting loading to false.
  - Handles FETCH_SUMMARIES_REPORT_ERROR by updating the error field and setting loading to false.
  - Handles UPDATE_SUMMARY_REPORT by updating the specific summary object in the summaries array.

## How to test:
1. Check out the current branch.
2. Run npm install if necessary.
3. Execute npm test weeklySummariesReportReducer.test.js.
4. Verify that all test cases pass without any errors.

## Screenshots or videos of changes:
image

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Comment by ppsahu** [comment]
I have tested this PR and all the checks pass upon running the file. Below is the screenshot for your reference.

Screenshot 2024-12-07 at 5 43 57 PM

**Review by RashmiKY98 — APPROVED** [review]
No issues found. Reviewed and tested the test cases. The test cases covers all the scenarios.
Screenshot 2024-12-07 235347

**Comment by chappdev2019** [comment]
all the checks pass 

image

**Comment by pallavithorat** [comment]
I have reviewed the PR, and all test cases have been successfully passed.
Screenshot 2024-12-08 at 3 38 18 PM

**Review by anirudhsk2107 — APPROVED** [review]
All tests have passed 

Screenshot 2024-12-12 124728

**Comment by beblicarl** [comment]
All tests passed successfully and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Review by nikhilpittala16 — COMMENTED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (260)

**Pull request merged**
