### PR TITLE
Ramya unit test : Reports/TeamReport/ReportCharts

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit test for src/components/ Reports/TeamReport/ReportCharts

## Main changes explained:
-  New files
      - **_ReportCharts.test.js_** : unit test cases 

## How to test:
1. check into current branch
2. do  npm test src/components/Reports/TeamReport/components/__tests__/ReportCharts.test.js
3. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Review by prnvjn — APPROVED** [review]
Cleared all tests. Just a small change in your description it should be 
`npm test src/components/Reports/TeamReport/components/__tests__/ReportCharts.test.jsx`
image

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and all tests passed.

Captura de tela 2024-02-11 054048

**Review by 666saofeng — APPROVED** [review]
Hi, all tests passed and it worked as intended!
image

**Review by peterson337 — APPROVED** [review]
Hi ramyaram2092, all Tests passed. Good job!

a

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested the PR and it passed all the test cases. Please refer the screenshot attached.
PR 1939

**Review by XiaohanMeng — APPROVED** [review]
All cases passed, nice!
PR1939 UnitTest result

**Comment by mianmiantea2019** [comment]
All cases passed, nice!

image

**Review by ShengjieMao — APPROVED** [review]
All tests passed. all components are tested properly. Props are well-considered as well.
PR_1939

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 25 - PR2

**Review by n0vay — APPROVED** [review]
Looks good to me 
image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
