### PR TITLE
EduardoV - create a unit test for the DeleteTeamPopup component

### PR DESCRIPTION
**Pull request by eduvarjaor**
# Description
Create a unit test for the CreateNewTeamPopup component to confirm whether it working as intended.

Screenshot_1
 
## Main changes explained:
- Export file DeleteTeamPopup.jsx for the test component
- Create file DeleteTeamPopup.test.js to do the unit test

## How to test:
1. check into current branch
2. cd HighestGoodNetworkApp
3. do `npm install` to run this PR locally
4. open file src → tests → Teams → DeleteTeamPopup.test.js
5. run `npm run test src/__tests__/Teams/DeleteTeamPopup.test.js`

## Screenshots or videos of changes:

This is the result it's supposed to get:

Screenshot_2

If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by harshidad — APPROVED** [review]
All tests passed, everything worked as intended.

PR#1270

**Review by robertoooc — APPROVED** [review]
Hi @eduvarjaor, I tested your new unit test. It passed all cases and had no issues. Linting and formatting also seem fine as well. 
Screenshot 2023-09-06 at 11 57 34 AM

**Comment by Sssky-18** [comment]
Hi eduvarjaor, I tested this unit test, and it works as our expected. Nice work!

 
PR #1270

**Review by DavidC0126 — DISMISSED** [review]
Hi it works as intended!
delete

**Review by Haoj1 — APPROVED** [review]
@eduvarjaor All tests passed. Good job!

**Comment by AnishPandita** [comment]
Hey, I followed your instructions and replicated the test results. It works as expects.
Screenshot 2023-09-06 at 7 29 42 PM

**Comment by iTvX** [comment]
Hi, I tested your PR, and it worked as described. Good job.

CleanShot 2023-09-06 at 23 50 38@2x

**Review by vinaykumarh — DISMISSED** [review]
Reviewed the PR and tested it out as per instruction. All the test case passed without any errors.
 Good work!

image

**Review by tsunami776 — APPROVED** [review]
I followed the steps in the PR and all tests passed. Nice work!

**Review by ss23046 — APPROVED** [review]
Hi @eduvarjaor , 
Works as intended 
Screen Shot 2023-09-07 at 8 48 41 PM

**Review by GaryB93 — CHANGES_REQUESTED** [review]
Great work on the tests! 

My only question is the implementation of the mock functions in the test file. Seems like you are defining the mock functions of onDeleteClick and onSetInactiveClick in defaultProps which is fine, but then in some instances passing a general mock function into DeleteTeamPopup component when you are already passing in the mock functions in defaultProps. 

To be more clear, you are passing certain mock functions into the component more than once. Just me being picky and aiming for clean code and consistency. Open to discussion or any thoughts on the matter.

Screenshot 2023-09-08 at 2 53 58 PM

**Comment by eduvarjaor** [comment]
> Great work on the tests!
> 
> My only question is the implementation of the mock functions in the test file. Seems like you are defining the mock functions of onDeleteClick and onSetInactiveClick in defaultProps which is fine, but then in some instances passing a general mock function into DeleteTeamPopup component when you are already passing in the mock functions in defaultProps.
> 
> To be more clear, you are passing certain mock functions into the component more than once. Just me being picky and aiming for clean code and consistency. Open to discussion or any thoughts on the matter.
> 
> Screenshot 2023-09-08 at 3 07 09 PM

You are right. I fixed it now. Please recheck if everything is correct now. 

If you find any error, please let me know to solve it. Thanks for the feedback, @GaryB93

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR. The tests all passed. The tests looks good. I also check your test code and they are pretty valid.
Screen Shot 2023-09-09 at 10 45 35 PM

**Review by gabi-lima — APPROVED** [review]
Great job Edu!
image

**Review by GaryB93 — APPROVED** [review]
Great work! All tests pass and the code is more consistent with defaultProps.
Screenshot 2023-09-10 at 11 53 21 AM

**Comment by beblicarl** [comment]
This test passed and the code is great!

issue #1270

**Review by beblicarl — APPROVED** [review]

**Review by vikrambadhan — APPROVED** [review]
Hi, All test cases passed! Works as intended! 

week3 - PR14

**Comment by one-community** [comment]
Thank you all, merging!

**Review by Bhagyashree444 — COMMENTED** [review]
Works as expected.

PR#1270(2)

**Pull request merged**
