### PR TITLE
Nahiyan_Fixed permissions management modals in dark mode

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
Fixed an issue where the modal title would not change in dark mode. Also removed text shadow in dark mode and added new colors that contrast well in the permissions list.

## Related PRS (if any):
This frontend PR is related to the dev backend

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log in as owner user
5. go to dashboard→ Other Links -> Permissions Management -> Click on Add new Role/ Manage User Permissions
6. verify that the modal works with dark and light modes.

## Screenshots or videos of changes:
Screenshot 2024-06-29 130837
Screenshot 2024-06-29 130859

### CODE REVIEW

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
Shouldn't the dropdown too have a dark theme? Please enable dark theme in the dropdown as well.
Rest everything else works fine.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/cb544eff-0001-44c1-80a2-4edc7a3f7641

**Review by jennZhang93 — DISMISSED** [review]
Tested with owner account, as screenshots shown below, the dark mode are tested to work. Good work!

Screenshot 2024-06-29 at 7 50 29 PM
Screenshot 2024-06-29 at 7 50 33 PM

**Comment by agryash** [comment]
Changes work as expected.

image

image

**Review by agryash — DISMISSED** [review]

**Review by aaryaneil — DISMISSED** [review]
The changes work as expected
Screenshot 2024-06-30 at 12 00 48 AM
Screenshot 2024-06-30 at 12 01 00 AM

**Comment by sahithidhulipala9** [comment]
Permission management model working as expected in dark mode and light model.
Screenshot (95)
Screenshot (96)

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by HowieMiao — CHANGES_REQUESTED** [review]
New role and User Permissions menus are both fully functional in light and dark mode. 

Only thing I believe can be improved is similar to Jatin's suggestion above, but the Manage user permission drop down menu could also be adjusted to fit dark mode as well

image

**Review by vijay10pk — APPROVED** [review]
Tested this PR in both dark and light mode and the changes work as expected. Everything looks good to me.

Dark Mode:
Screenshot 2024-07-03 at 12 44 40 PM
Screenshot 2024-07-03 at 12 45 13 PM

Light Mode:
Screenshot 2024-07-03 at 12 45 33 PM
Screenshot 2024-07-03 at 12 45 58 PM

**Comment by Nahiyan-16** [comment]
> Shouldn't the dropdown too have a dark theme? Please enable dark theme in the dropdown as well. Rest everything else works fine.
> 
>  PR2403.mp4

@HowieMiao and @JatinAgrawal94, thank you for the reviews. I agree that the dropdowns should be in dark mode. As of now, all dropdowns have a light background throughout the website. Please make a feature request on the bugs doc that we need to implement dark mode on all dropdowns as this PR should only focus on the bug fixes.

**Review by vijay10pk — DISMISSED** [review]
Tested with owner account. All the changes work as expected in both dark and light mode.
Screenshot 2024-07-04 at 10 38 06 PM
Screenshot 2024-07-04 at 10 38 39 PM

**Review by Rishitha1309 — APPROVED** [review]
model working as expected in both dark mode and light model
PR2403-1
PR2403-2

**Review by HowieMiao — DISMISSED** [review]
Both windows look great in dark and light mode, no further changes requested.

image

**Pull request merged**
