### PR TITLE
Olga Reconcile values of tangible hours in userprofile data

### PR DESCRIPTION
**Pull request by cvtqx**
# Description

 (PRIORITY MEDIUM) Shihao: Fix hours totals/summary on profile page (WIP Olga)
The value of totalTangibleHrs in profile page data doesn’t match the summation of hoursByCategory

### EXPLANATION OF THE PROBLEM

**>>>Please check if you observe the following behavior in your userProfile and if you do, then review the PR. This will not be happening to newer team members, so they won't be able to test this PR.<<<**

On Beta site go to your own user Profile page -> volunteering times tab -> right click to open dev tools -> open React Components and expand userProfile data:

Screen Shot 2023-08-24 at 11 33 21 AM

Those who have been with HGN more than a month,  may notice that Total Tangible Hours (#1 on the screenshot) on your profile page may show less hours than you’ve actually worked.  

If you look at the screenshot you will see that 1 (Total Tangible Hours in Volunteering Times Tab on user Profile page) is equal to the sum of elements in 2 (userProfile.hoursByCategory), but it is less than sum of elements in 3(userProfile.savedTangibleHrs), and 5 (userProfile.totalTangibleHrs) is a totally random number. This probably happened due to the bug affecting weekly summaries and blue squares - at some point some entries in the userProfile data stopped incrementing. As a result the number displayed on the user profile on the webpage is incorrect for some users. The correct numbers should be  as follows:

1 (Total Tangible Hours in Volunteering Times Tab on user Profile page) must be equal to 2 (userProfile.hoursByCategory) -  this is currently correct;
2 (userProfile.hoursByCategory) must be equal to the sum of 3 (userProfile.savedTangibleHrs)  + 4 (userProfile.tangibleHoursReportedThisWeek)
5 (userProfile.totalTangibleHrs) must be equal to the sum of all elements in 3 (userProfile.savedTangibleHrs), 

( NOTE: 5 is incremented by the value in 4 at the start of a new week when weekly summaries and blue squares are processed)

## Main changes explained:

Created a helper function to reconcile all the numbers if they are in disarray. The function will run when a new time entry is entered and should fix the numbers in userProfile data before they are incremented by a new time entry. If the hoursBycategory was smaller than actual total hours (which is the sum of savedTangibleHours) then the missing hours will be added into ‘unassigned’ category, because there is now way to find out which category those missed hours belonged to.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Log in as any user that has existed for a while and has a few time entries, not a newly created one. 
Open their profile page. Open React dev tools and expand the userProfile entry. Check the numbers in the above mentioned entries. Check if the numbers are in disarray as explained above. ***You may see that on localhost savedTangibleHrs array is super long, much longer than the total number of your weeks, disregard this for now. 
4. Add a new tangible timeentry through the dashboard. Refresh the page. Check the userProfile in dev tools again - check that:
1 (Total Tangible Hours in Volunteering Times Tab on user Profile page) is equal to 2 (userProfile.hoursByCategory) -  this is currently correct;
2 (userProfile.hoursByCategory) is equal to the total of 3 (userProfile.savedTangibleHrs)  + 4 (userProfile.tangibleHoursReportedThisWeek)
5 (userProfile.totalTangibleHrs) is equal to the sum of all elements in 3 (userProfile.savedTangibleHrs), 
The hours that were previously missing (the difference between the TotalTangbileHrs and total HoursBy Category) have been added to hoursBycategory under ‘unassigned’

## User Profile data after the fix (all above entries must be reconciled):

TASK255_test_result

## Video how to test: 

https://www.loom.com/share/55f6ec79beb2438fb2b6d1deecabbaa0

### CODE REVIEW

**Review by ramyaram2092 — COMMENTED** [review]
Hello Olga  firstly great job  on this . 
I tried the functionality . I had logged 5 hours for today in the admin profile I used for testing . I dint quite get the new total tangible hours figure. It jumped from 4 to 115.53. Could you help me understand the logic

**Testing Video :**
**Admin**: ramya_test_admin@gmail.com
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/6b2e9f78-8cc8-4a22-8bc3-c7043b702de2
**Volunteer**: ramya_test_volunteer@gmail.com
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/07e96df8-bd99-4a36-b6c7-99d512a22355

**Comment by cvtqx** [comment]
> Hello Olga firstly great job on this . I tried the functionality . I had logged 5 hours for today in the admin profile I used for testing . I dint quite get the new total tangible hours figure. It jumped from 4 to 115.53. Could you help me understand the logic
> 
> **Testing Video :** **Admin**: [ramya_test_admin@gmail.com](mailto:ramya_test_admin@gmail.com) https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/6b2e9f78-8cc8-4a22-8bc3-c7043b702de2 **Volunteer**: [ramya_test_volunteer@gmail.com](mailto:ramya_test_volunteer@gmail.com) https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/07e96df8-bd99-4a36-b6c7-99d512a22355

@ramyaram2092 Thank you for testing and a great question! 
This has been a tricky task because of strange behaviour of savedTangibleHours array. The savedTangbileHours array contains all hours for the weeks that you've worked. In other words, savedTangibleHours.length === number of weeks that a person has worked for HGN. In beta version this array is normal length (i.e. it is equal to the number of a person's total weeks), however in dev  this array is super long ( for some reason it gets incremented several times instead of one).  Since this array acts fine on beta site I decided to disregard it's  strange behavior on dev for now and only concentrate on reconciling the numbers (as per the description of the problem). 
So to answer your question - those many hours  that you've got in unassigned category come from that super long savedTangibleHours array. I hope this answers your question. 

Disclosure - I am not totally convinced this is the right way to fix the problem, because I was very confused by the behavior of the above mentioned array in different environments. But at least, it seems that the reconciliation of numbers works as intended.

**Comment by GaryB93** [comment]
I tried looking into this PR and seeing if this bug affected my user profile. I noticed on the beta site that my Total Tangible Hours being displayed seems to be correct. However, when diving into the userProfile data in the component it looks like totalTangibleHrs is more. Not sure how this is possible. I did notice that the bug last week seemed to duplicate tangible hours for the week and that is being added to totalTangibleHrs in the user profile data.
Still, the frontend displays the right amount of hours for me.

Screenshot 2023-09-05 at 3 23 21 PM

**Comment by cvtqx** [comment]
> I tried looking into this PR and seeing if this bug affected my user profile. I noticed on the beta site that my Total Tangible Hours being displayed seems to be correct. However, when diving into the userProfile data in the component it looks like totalTangibleHrs is more. Not sure how this is possible. I did notice that the bug last week seemed to duplicate tangible hours for the week and that is being added to totalTangibleHrs in the user profile data. Still, the frontend displays the right amount of hours for me.
> 
> Screenshot 2023-09-05 at 3 23 21 PM

Thank you for taking your time to review this @GaryB93 ! This is a weird bug with an unpredictable behavior in different environments and user profiles, so it's very helpful to know that your profile was not affected by this!

**Review by beblicarl — APPROVED** [review]

**Comment by KurtisIvey** [comment]
Works as intended and adds up appropriately as you've outlined.


pr1211 tested successfully

**Review by KurtisIvey — APPROVED** [review]
Works as intended and adds up appropriately as you've outlined.


pr1211 tested successfully

**Review by LucileTech — APPROVED** [review]
Screenshot 2023-09-12 at 20 22 51
Screenshot 2023-09-12 at 20 26 07
Screenshot 2023-09-12 at 20 27 24

**Comment by one-community** [comment]
Great PR and great job reviewing from everyone so far!

**Review by sxiong5 — APPROVED** [review]
Hey @cvtqx, I've tested the PR by following the instructions, and everything worked as intended.
Screenshot 2023-09-15 at 14 54 57

**Review by robertoooc — APPROVED** [review]
Hi @cvtqx, I tested your pr and everything seems to be working well. I didn't notice anything unusual, the hours logged seem fine. 
Screenshot 2023-09-16 at 6 20 09 PM

**Review by JYXiao-2021 — APPROVED** [review]
Hi, I test and it works for that. 
Screenshot 2023-09-23 at 10 25 15 AM

**Comment by one-community** [comment]
Wonderful, thank you everyone. Merging!

**Pull request merged**
