### PR TITLE
Shrey_unit_test_ActiveCell

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for ActiveCell component

## How to test:
1. check into current branch
2. do `npm install` 
3. npm test ActiveCell.test.js
4. verify that all tests pass

## Screenshots or videos of changes:

Screenshot 2023-12-02 at 11 49 26 PM

### CODE REVIEW

**Review by pika-chu11 — APPROVED** [review]
Hi @Shreyj14 , test passed! Great job!
PR 1628

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and everything works as intended!

Week 14 - PR1

**Review by scoopstroop92 — APPROVED** [review]
Hello @Shreyj14 good job on the test cases 
image

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests passed without any errors or warnings. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/b969e03c-6b6f-48e4-b204-b4a1390774b8

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
