### PR TITLE
Jay - PERMISSION: Manage Admin Link Permission

### PR DESCRIPTION
**Pull request by Alforoan**
# Description
This PR enables the user with the Edit Link Permission to be able to edit other users' links on their profile pages. 

## Related PRS (if any):
This frontend PR is related to the [#688](https://github.com/OneCommunityGlobal/HGNRest/pull/688)  backend PR.

…

## Main changes explained:
- Added conditional logic so that Edit button next to LINKS is visible to those with the permission.
- Granted permission to those with 'manageAdminLinks' permission.
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to Other Links -> Permissions Management -> Manage User Permissions -> Choose a user without user management permissions such as volunteer or core team -> add Manage Admin Links in User Profile permission
6. verify that user is now able to see other users' links by clicking on Edit button next to LINKS (it's below the profile picture)

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/17846e35-966a-432d-a56d-36b2f7373d40

## Note:
**Unmute the video.**
Also, please test the personal links as well. They should also work.

### CODE REVIEW

**Review by scoopstroop92 — DISMISSED** [review]
Hello @Alforoan  the functionality works as expected. Good job 

**Testing Video:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/7527ee37-8bda-4063-b7bd-f5333dde1b41

However, seeing some exception in the backend console in addition to console statements 
image

image

**Review by scoopstroop92 — COMMENTED** [review]
Hello @Alforoan  the functionality works as expected. Good job 

**Testing Video:**

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/89441435/7527ee37-8bda-4063-b7bd-f5333dde1b41

**Review by pshereen — DISMISSED** [review]
Tested the PR and Manage Admin Link Permission is working as per the requirement.

Logged in as admin and added Manage Admin Link Permission to volunteer user.
 
Screenshot 2024-01-22 195130

Then I logged in as the volunteer and the edit link is working.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/d5058b01-25e5-40b5-b4cf-d954640a59a6


However, there are warnings while compiling.

Screenshot 2024-01-22 200558

**Review by Sophie-lei — DISMISSED** [review]
Hey! I just tested this PR. Logged in as owner account to edit the permission of volunteer role's link permission. 
The volunteer role profile shows the link. Everything worked as expected. Please take a look at the video for more details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/698300ad-f2e9-46de-bda8-abd18d92b54f

**Review by SRamen1999 — DISMISSED** [review]
Tested this PR with an Owner account to give admin link permission to volunteer role's.  The Volunteer role can remove and edit links. Everything worked as expected. One thing I would add is to make the permissions list collapsible so it is easier to find the right permissions.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/4d4da9dc-74d9-4b4a-9aa1-c393a3cb600b

If you delete the media folder link it will remember the last used link.

Screen Shot 2024-01-23 at 3 42 25 PM

**Review by Renanluizssx — DISMISSED** [review]
Hi @Alforoan, i tested your application and it's correct, nice.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/2fc2a17b-f2d7-445e-b415-0e2a910d6949

**Review by KevHnh — DISMISSED** [review]
Nicely done, everything works as expected. Used an owner account to modify the permission on a volunteer account. Links were successfully updated and displayed properly.

I also tested with invalid links off camera and there was proper error handling. Well done. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/72af6892-baaa-41a8-a617-63cfe1d53a33

**Review by nathanah — CHANGES_REQUESTED** [review]

**Comment by galgalinidhi** [comment]
Hi @Alforoan, I tested the PR and it works as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44816413/25871d02-6f2b-4b0d-82bd-60bd9f585b16

**Review by SaiDeepak-NEU — DISMISSED** [review]
Logged in as an admin and added the manage admin links in user profile and then logged in as a volunteer and tested the edit link and everything is working as expected.

was able to add google doc links and checked redirection of the hyperlinks as well and seemed to be working well.

Screenshot (25)
Screenshot (24)

However sometimes while testing I observed that the submit button is not visible in my screen while adding the permission for volunteer in the manage permissions page, i don't know its my rendering or screen size issues, so please check that.

**Review by Pandani07 — DISMISSED** [review]
Tested this PR and it works as intended. Logged in as an owner account and added manage admin links. Logged out and then logged into the respective volunteer account and could add the link


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/69f728ab-eaf4-4e55-acaf-15d44aeea1fa

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR, All features worked as planned, but I received an error on the backend.

backProblem

**Review by X1aoZhang99 — CHANGES_REQUESTED** [review]
Hi Jay,

I tested your PR with owner and volunteer user, all functionalities worked as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/45bfb22e-318c-40aa-a0a7-abddd41d17d3

However, there is an error message in the console. Please refer to the image and check the backend code. 

### Image
Screenshot 2024-02-06 at 22 22 55

**Review by mohabbasd — DISMISSED** [review]
Hello, I tested your PR and it works just like you explained and it works flawlessly.
Screenshot 2024-02-08 at 10 15 33 PM
Screenshot 2024-02-08 at 10 15 45 PM
Screenshot 2024-02-08 at 10 17 30 PM
Screenshot 2024-02-08 at 10 18 31 PM

**Comment by nnamdixobi** [comment]
The changes seem to work seamlessly with the https://github.com/OneCommunityGlobal/HGNRest/pull/688 backend PR. and helps contribute to the overall user experience

**Review by XiaohanMeng — COMMENTED** [review]
Hi, I have tested this PR. After the owner account granted permission to the volunteer account, the latter was able to add and update the link. All functionalities are working as intended. Please refer to the video for more details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/97b64124-531a-47f3-8505-a079cbb4621d

Additionally, some errors appeared in the backend terminal.
PR1787_error

**Review by XiaohanMeng — DISMISSED** [review]

**Review by TapanPathak — DISMISSED** [review]
Hi, I tested your PR by logging as Owner and giving permission to a Volunteer. 

Screenshot 2024-02-15 at 6 23 19 PM

After getting the permission, Volunteer's edit link is working.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/55534eac-8e08-46c8-8fb5-9c931d493be8

**Pull request closed without merging**
