### PR TITLE
Nathan Fix key, tbody, and required prop warnings

### PR DESCRIPTION
**Pull request by nathanah**
# Description
This PR fixes 3 warnings on the dashboard view:

Warning: validateDOMNesting(...): \<div\> cannot appear as a child of \<tbody\>.

Warning: Each child in a list should have a unique "key" prop.

Warning: Failed prop type: The prop `timer` is marked as required in `TimeEntryForm`, but its value is `undefined`.
Warning: Failed prop type: The prop `resetTimer` is marked as required in `TimeEntryForm`, but its value is `undefined`.

## Main changes explained:
To fix validateDOMNesting(...) I wrapped \<Loading\/\> with a \<tr\> and \<td\>.
To fix the key error, I removed a \<\> wrapping the TeamMemberTask.
The timer and resetTimer props were not required in the case of intangible time entries, so I made them not required.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log in as any user
4. go to dashboard
5. Open dev tools console and make sure Errors are turned on.
6. verify none of these warnings appear in the dev tools console and the changes don't change any UI.

## Screenshots or videos of changes:
Before:
image
image
After:
image

### CODE REVIEW

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
So I've tested it under owner, admin, and volunteer. The owner and admin don't have any errors. However, the volunteer, while it doesn't have the errors you fixed, it does have some different errors. If these could be resolved or if fixing those things isn't within the scope of this, I'll approve. 

owner:
pr901Works

admin:
pr901 admin works


volunteer:
pr901 volunteer doesn't quite work

Luckily, these don't appear to be too crazy


I've included the fix for the p descendant of p. I end up using empty brackets over {parse(summary)} . passes all the tests built into the front end as well

fix p as descendent of p

**Review by leonzh2k — CHANGES_REQUESTED** [review]
I tested on admin and volunteer 

No errors on admin:
image

On volunteer, the errors that you intended to fix are indeed not present. I'm not getting the same error as the other reviewer though, so it's worth checking out.

image

**Review by OAkinbode — COMMENTED** [review]
Hello Nathan, 

Interestingly, I am getting the same errors on an admin that Kurtis is getting on the volunteer account. I tried his fix locally for the <p> tag error and it seems to work. 

PR 901 issues

**Comment by AriaYu927** [comment]
Hi @nathanah , 

I'm getting the same new warning as @KurtisIvey and @OAkinbode said on Owner account.
Owner
All the other account types work as expected, thank you!

**Review by bienzguoa — APPROVED** [review]
Hi @nathanah,
Tested for volunteer, admin and owner, there is no warnings you mentioned above. For the warning appeared in screenshots, it seems not related to this PR(so I approve), but I have no idea about them.
Screenshot 2023-06-09 at 9 26 32 PM
Screenshot 2023-06-09 at 9 25 26 PM
Screenshot 2023-06-09 at 9 23 56 PM

**Comment by nathanah** [comment]
> Hi @nathanah, Tested for volunteer, admin and owner, there is no warnings you mentioned above. For the warning appeared in screenshots, it seems not related to this PR(so I approve), but I have no idea about them. Screenshot 2023-06-09 at 9 26 32 PM Screenshot 2023-06-09 at 9 25 26 PM Screenshot 2023-06-09 at 9 23 56 PM

I looked into it and I'll make another PR for it later if I can figure out a fix.

**Comment by yufeiStella** [comment]
Log in as admin(only has one error):
admin
Log in as volunteer(have some other errors):
volunteer

**Review by KurtisIvey — APPROVED** [review]
Functions as intended and the additional p descendent of a p has been resolved as well. Great job. I'm going to go ahead and approve because those other things seem out of the scope after looking at the other comments. 

If anyone is interested and also encountering the issue of the key issue in TimeLog.jsx, I believe it to be caused in the area of line 273. This would likely need to be it's own pr though as my solution to this could potentially cause conflict. Doesn't fail any built in tests 
fix for timelog key issue

**Review by leonzh2k — APPROVED** [review]

**Comment by Lucas-E** [comment]
Thank you everyone! Moving to final review!

**Comment by AnishPandita** [comment]
Hi @nathanah I tested the PR from owner, admin and volunteer account and the warnings and error you pointed are not there. So the  functionality works.
Screenshot 2023-06-14 at 5 18 16 PM
Screenshot 2023-06-14 at 5 20 32 PM

**Review by cvtqx — APPROVED** [review]
Tested this as admin, manager and volunteer and those warnings are not seen in any of these.

Volunteer:
Volunteer

Admin:
Admin

Manager:
Manager

**Review by NidaZaki — APPROVED** [review]
Changes look good!

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @nathanah. I have tested this PR and the four warnings are not present anymore. I have tested all the user roles. Great work!

Log in as Owner:
image

Log in as Admin:
image

Log in as Volunteer:
image

Log in as Mentor:
image

Log in as Manager:
image

Log in as Core Team:
image

**Pull request merged**
