### PR TITLE
Luis fix weekly summary bug

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description
Weekly summary allowed summaries less than 50 words from being submitted. 
Screenshot 2023-09-21 at 7 38 14 PM

video of bug:
https://drive.google.com/file/d/1EQltPvUFPeB7nuap_VmXoinHfeHJMdDK/view

## Related PRS (if any):

…

## Main changes explained:
Got the word count from the Editor since it displayed the word count. 
I added another formElement parameter called wordCount and added it to the schema for JOI to test
Since the current Regex checks for whitespaces I added another check for word count, since this is why summaries less than 50 words were being submitted. The regex was only counting the white spaces.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user and volunteer. 
4. go to dashboard→ summary
5. Fill out the weekly summary with less than 50 words then attempt to submit it. 
6. Complete the summary by adding 50 words and should let you submit it. 
*Note make sure the user has a dropbox link otherwise you'll need add one when submitting. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/ee4b6f56-bf0c-4d3a-8d32-bb005f75afb7

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/6f167f9e-478b-4d0c-9620-464a8f42d594

## Note:
the following errors appear but are unrelated to the PR. when submitting via a volunteer account.
Screenshot 2023-09-21 at 7 46 12 PM

the following appeared for submitting via an admin
Screenshot 2023-09-21 at 7 48 51 PM

### CODE REVIEW

**Review by TheDescendant39 — COMMENTED** [review]
Hi @luisarevalo21 , I tried recreating the issue on the development branch on my local but I couldn't. By referring to the video could you tell me what I am missing something?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/f68eff42-5030-4fc1-8a6e-f17030e1bbe4

**Review by EdwinLauM — APPROVED** [review]
Hey @luisarevalo21, works as expected! Good job 

Can't save when the word limit reached >= 50 and then deleted words to make it < 50. 

Can save when the word count is >= 50

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/b32f94a4-8e6a-49ce-b493-37b55775a799

**Review by TuanDinh140194 — APPROVED** [review]
Hi @luisarevalo21 ! I have tested your PR and it worked as expected. When summary words less than 50, it is not available to submit. When words equal or more than 50, it's available to submit. I have tested with two role volunteer and owner and notice that it still have 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/a9672aaa-2682-4c87-8199-e0848ede4ca3

**Review by JeffLi117 — APPROVED** [review]
Tested by typing to >50 words, then <50 - this makes the user unable to submit the summary: 

Volunteer:
image
Admin:
image

Then, when the word count is increased >= 50, submission is successful:

Volunteer:
image
Admin:
image

Changes work as intended.

**Review by wantingxu7 — APPROVED** [review]
Hi, the function works as expected the 'save' button is available only when the summary contains more than 50 words and the link is filled. When deducting the words to less than 50, the 'save' button becomes unclickable. Good work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/8df479af-f1dc-4fc4-a9c4-c44a0030f945

**Review by dah00 — APPROVED** [review]
Hey, I tested your PR with more than 50 words first, which allowed me to click save. Then, I deleted some words to make it less than 50 words and the save button is no longer clickable as intended. Great job!
PR1333_more_than_50_words
PR1333_less_than_50_words

**Comment by Sssky-18** [comment]
Hi @luisarevalo21, I tested your fix on the summary, and it looked great.
When I typed in less than 50 words, the "Save" button was not clickable, and the warning text displayed as expected. When I added to 50 words, the summary can be saved, and the text disappeared. 
Therefore, I think this PR worked as expected. 

PR#1333+2

PR#1333

**Review by JYXiao-2021 — APPROVED** [review]
Hi, great job. I test this pr and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/24d933ab-c754-498f-a961-9768190740d3

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR following your instructions. The functionality is working as expected! The previous bug does not appear. The following is my testing video. Also the code looks great!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/ef44fbac-101c-40eb-8e43-585892bd0a3f

**Review by belagaam — APPROVED** [review]
I tested this PR as per the instructions and it works as expected on Admin and Volunteer accounts.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/33ff98c7-9510-448f-a696-28b0669572df

**Review by Haoj1 — APPROVED** [review]
@luisarevalo21 Good work! After deleting words when over 50, It successfully blocks submission 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/a9ca5189-fabc-4c41-b695-1ed068bd7800

**Comment by luisarevalo21** [comment]
> Hi @luisarevalo21 , I tried recreating the issue on the development branch on my local but I couldn't. By referring to the video could you tell me what I am missing something?
> 
>  Screen.Recording.2023-09-23.at.12.02.45.AM.mov

Hello 

please watch this video.
The bug also occurs when you have 49 words and add a space in between the last word and the period like so 
49th word -> "test        ." Adding space will allow the summary to pass. Even though their is only 49 words. Feel free to reach out if you can't duplicate the bug. 

https://drive.google.com/file/d/1EQltPvUFPeB7nuap_VmXoinHfeHJMdDK/view

**Review by DavidC0126 — APPROVED** [review]
Hi @luisarevalo21 I tested your PR and it works as intended.

Uploading summary_save.mov…

**Review by eduhorta — APPROVED** [review]
Working as expected. 👍 

Great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/b3881f62-9490-41e4-a3d4-64e0d5fdc9ed

**Comment by Vishala09** [comment]
Works perfectly.  Awesome Work!
Tested the changes

image

image

Displaying the error messages properly even after typing more than 50 words and deleting them back to less than 50.

**Review by Vishala09 — APPROVED** [review]

**Comment by one-community** [comment]
Great job everyone, thank you. Merging!

**Pull request merged**
