### PR TITLE
Roberto-Fixes assign badge delay

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
When assigning badges to users specifically on the badgemagement, there was either a delayed response which would take minutes to update the user profile or it wouldn't update at all.
Screenshot 2023-09-30 at 8 55 35 PM

## Related PRS (if any):
Test this frontend PR with the #[562 ](https://github.com/OneCommunityGlobal/HGNRest/pull/562)backend PR.
…

## Main changes explained:
- In AssignTableRow.jsx, changed the custom input's ID because the BadgeDevelopmentTable.jsx file has the identical ID and caused triggering wrong function issues. 
- Added useEffect and more logic to AssignTableRow.jsx to not trigger the function if you close modal and don't press confirm, and also will keep the checkmarked inputs when you reopen modal.
…

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as any user with Assign Badge Permission (suggested: admin / owner)
4. go to Other Links→ Badge Management→ Assign Badge→ Select a User→ Assign Badge→ Check user's profile and dashboard 
5. verify that assigning a badge through badge management will actually be reflected in the frontend and backend. 
6. verify that assigning a badge to user results in an immediate response, one page refresh should be enough to update the dashboard and user profile. (make sure to be checked into the assigned backend for this)

## Screenshots or videos of changes:
This Branch: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/4b3bc792-62d2-4aac-af32-220015d3506c

Development: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/d03b6e00-1279-4e84-85b9-ef86df3a3eb0

## Note:
These errors in the console aren't related.
Screenshot 2023-10-07 at 4 59 12 PM

### CODE REVIEW

**Review by StrawberryCalpico — DISMISSED** [review]
Hi, I test this pr and it works as intended. Great Work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/bb131964-66ca-4263-8099-cff43752e6b3

**Comment by emunkh404** [comment]
I tested and reviewed the pull request, and it appears to be functioning well. However, I noticed that in my second attempt, there was an additional refresh on the page when the result badges were displayed. Other than that, the functionality seems to be working as expected. Please take a look at the video for more details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/18c1c553-69b1-4079-9317-7db92d22cde2

**Review by navneeeth — DISMISSED** [review]
Hey @robertoooc! I tested your changes and they LGTM! Logged in as an Owner and navigated to `Other Links-> Badge Management` and assigned a badge to an user. Verified in their user profile in the frontend as well as in the backend (database) to see that the newly added badge is reflected in an immediate response with one page refresh. Good implementation!

### Testing Video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/6bfb46ad-b932-4931-bd5c-7717a7897523

**Review by lacnoskillz — APPROVED** [review]
Hello Roberto!
I pulled your changes and tested them locally. 
It seems the code works as intended nice work!

[Untitled_ Oct 9, 2023 4_14 PM.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/d26a7857-aefc-46be-9db0-befe0fcbd81e)

**Comment by robertoooc** [comment]
> I tested and reviewed the pull request, and it appears to be functioning well. However, I noticed that in my second attempt, there was an additional refresh on the page when the result badges were displayed. Other than that, the functionality seems to be working as expected. Please take a look at the video for more details.
> 
>  2023-10-09-1530-16.mp4

Hey @emunkh404, I haven't encountered your error at all. What do you see in the console or in the network tab when you face that?

**Review by malikjahanzaib — APPROVED** [review]
Hi @robertoooc, I ran your PR locally and all the fixes work perfectly. User badge assignment works flawlessly without any delay and badges get reflected instantly in a single refresh when viewing the profile. Great work!

Test Rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/90b651a2-e1a3-4143-90a5-464941ee6883

**Review by DavidC0126 — DISMISSED** [review]
Hi @robertoooc I tested both of your FE and BE PRs, and they work as described. I was able to assign new badges and see on mongoDB Compass and FE page.
1390_DB

Uploading PR1390.mov…

**Review by tsunami776 — DISMISSED** [review]
Hi @robertoooc, I tested your PR with an admin account. Now user's badges in profile will update immediately after badges assigned in`Other Links->Badge Management->Assign Badges`. The assign badge modal's functionality is handled correctly. One suggestion that may not related to this PR is that Assign Badge modal could be a scroll view because there is a long list of badges. Great job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/29d14ce1-0896-4cdb-9ad4-5dcdbed16824

**Review by JYXiao-2021 — APPROVED** [review]
Hi, great job! I test this pr and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49748716/fe5e0a0b-5124-4cac-b5d3-d005d07744e9

**Review by vikrambadhan — DISMISSED** [review]
HI, I tested your PR and it works as intended! Great Job!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/061afce9-5495-47c6-9e71-894aeed7a115

**Comment by emunkh404** [comment]
Tested your PR #1390 works as expected no delay
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145945063/a66b6826-edc8-4a50-a7e2-e12d197b5b3d
image

**Review by JeffLi117 — DISMISSED** [review]
LGTM! Code works as intended.

Logged in as Owner > Badge management > Selected user > Assign badge:
image
image

Immediately check user's profile:
image

The data persists and is able to be seen on other accounts as well. Good job!

**Review by Shubhu0 — DISMISSED** [review]
Hi @robertoooc I reviewed the PR and it is working as expected! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56580102/3e2e8c9f-dbf0-40a3-a119-c65016b4facd

**Comment by RheaWu1212** [comment]
Hi it works as expected, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109626741/4ba7c447-7f21-447a-a6c9-42fe026fc831

**Review by Cloid — DISMISSED** [review]
Hi there. I tested the following cases:
- Admin profile going to Badge Management and setting badges for itself.
- Check if badges show up immediately on both the Dashboard and My Profile Page.
- Admin gives badges to different profiles and seeing if badges show up immediately in their specified profiles.
- Created a user that starts as a Volunteer profile, changed that profile to admin, and repeated steps as the first base case.
- Created a custom badge and immediately assigned it to the user.

Overall everything works.

Attached is a video of me testing the last two cases.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/14044314/fa918389-9cc0-4997-9ce1-bd11b1386807

**Review by ChirayuRai — COMMENTED** [review]
Hey! I tested your cha

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/15188751/1bb22420-ec36-4c9a-ae09-9a57a9973fe2

nges, and it looks like it works as intended!

**Review by TuanDinh140194 — APPROVED** [review]
Hi! I have test your PR with the owner account. After assign the badges in Other Links->Badge Management->Assign Badges. The badges update after I refesh the pages. The function work as expected. However, the organization of the badge should be scroll cause if get more badges, we are unable to see it. I also noticed some error images on the header as show in video 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/23b7c15c-48ae-4ee9-bd32-28796f230073

**Review by Jiyuanxia — DISMISSED** [review]
Hi @robertoooc , I have reviewed your pull request and tested it. It works as you intended. Badges can be assigned successfully. Well done!
Screenshot 2023-10-19 205447
Screenshot 2023-10-19 205510

**Review by Lin1404 — APPROVED** [review]

**Review by shubhankarval — CHANGES_REQUESTED** [review]
Hey @robertoooc, the badge assignment functionality works as intended, great work!
</br>
pr
pr2

I would like to request a small change for the search functionality. Could you please fix the way the users appear so "Search by Name" isn't overlapping them as well as add a border around the user maybe, to recognize its a clickable item?

prnew

**Comment by Lin1404** [comment]
Hi @robertoooc , I have reviewed your pull request and tested it. It works as you intended and badges can be assigned.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/78375725/14b906fd-26a0-41f4-83b8-9fba72c75215

**Review by jerryren527 — COMMENTED** [review]
Hi @robertoooc !

Great job implementing this feature! I noticed a big improvement in the assign badge functionality that was much needed.

## Running on development branch:
❌ After clicking on Assign Badge, and clicking on the check boxes next to badge names do not show the check mark. Clicking on ‘Confirm’ causes this modal message to appear: “Um no, that didn’t work. Badge Select Function must include actual selection of badges to work. Better luck next time!” Then I look at the dashboard of the account that I assigned badges to, and I see no new badges added.

## Running on this branch:
✅ After clicking on Assign Badge, and clicking on the check boxes next to badge names DO show check marks. Clicking on ‘Confirm’ does NOT show any modal message. Then I look at the dashboard of the account that I assigned badges to, and I see the badges that I added!
✅ Confirmed that the badge changes appear in the database
✅ Confirmed that the badge changes appear when user logs in to their account.
✅ Confirmed that the badge changes appear in the dashboard and user profile in one page refresh.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/07f4842a-2154-4e52-995f-7a7700b429a0


Great job on this feature branch! 

## Potential Problem

A potential problem that is unrelated to the task is that you have committed changes made to unrelated files, such as Dockerfile, and various image files. I understand that this is related to an issue many developers have encountered where a large number of file changes are marked as unstaged. And a temporary solution has been to ignore those committed changes by commenting out the line in .gitattributes, then running ‘git stash’. 

It seems like you have pushed those changes to this remote branch. I am not entirely sure what will happen if all those unrelated file changes are merged into the development branch (perhaps they can be easily taken care of by the PR review team before this branch gets merged into development). But perhaps you can consider removing the changes made to unrelated files, such as the files shown in the screenshot below:

Screenshot 2023-10-21 at 5 25 49 PM

Screenshot 2023-10-21 at 5 25 33 PM

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/24511ab8-303e-41a6-9284-a60307cd9b17

**Comment by palakgosalia** [comment]
Hey, I have reviewed and tested it, and everything works fine


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/279bda7a-f074-43a7-8458-a6ca47d7e341

**Comment by one-community** [comment]
Thank you all, moving to final review!

**Review by KurtisIvey — APPROVED** [review]
Code is very clean and functions as intended. 

Badges updated after 1 refresh as mentioned in the testing instructions. I refreshed from the user's profile page in order to see if the changes took place. Also logged out and under a different user with the new badge still persisting. Fantastic job!
Screenshot 2023-11-10 at 11 17 04 AM
Screenshot 2023-11-10 at 11 16 23 AM

While not in the scope of this pr, I'm definitely in agreement with others on room for improvement in the user interface of the badge management section & badge popup modal. Perhaps that's something someone else can address in a future PR.

**Pull request merged**
