### PR TITLE
Aaron - Add new field "Start Date" to Create New User modal

### PR DESCRIPTION
**Pull request by AaronPersaud**
# Description
image

- the PR implements all the highlighted functionality (the red was discussed with Jae and it's no longer necessary)

## Related PRS (if any):
backend PR is [PR472](https://github.com/OneCommunityGlobal/HGNRest/pull/472)

## Main changes explained:
- when creating a new user as an admin/owner, creator can now choose the start date (uses date picker)
- date picker defaulted to the next day
- the first time a user logs time into HGN, their start date is updated to the current day 

## How to test:
1. check into current branch and backend branch with the same name
2. do `npm install` and `npm run start:local` to run this PR locally
3. log in as admin user
4. go to Other Links → User Management and click Create New User button
5. fill in whatever credentials you want except for Start Date
6. play around with the date picker for Start Date to make sure it works (switching months, switching days updates the field)
7. pick a date that's not today and click Create

Log out and log into the account you just created

1. Go to your profile and verify the start date is the date you set
2. Log time into HGN
3. Go back to your profile and verify the start date has been updated

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/7f002589-790a-4910-8b50-8c1259c6b9ff

## Note:
- createdDate used UTC for timezone before this change, so I went with the same convention and that's why my start date in the video is offset by 1 day from the timelog's date 
- to test if the start date only updates the first time, you'd have to wait one day and log time during the next day and make sure the start date didn't change. A workaround for this is adding a console statement in line 484 of `TimeEntryForm.jsx` and verify it's not printed for subsequent time logs

### CODE REVIEW

**Review by winghojackyli — DISMISSED** [review]
Hi @AaronPersaud , I've tested this frontend PR along with the backend PR and they work as intended. Start date is updated with the first timelog. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/55379242-7a85-491d-8a06-e112376ec2be

**Review by navneeeth — APPROVED** [review]
LGTM! Good implementation! 

The FE + BE PRs work as expected. Tested the changes by logging in as an admin user, creating a new user with a later Start Date, and then played around with the date picker for Start Date. Created an account, logged into the account, and checked the profile to confirm if the Start Date matches the set Start Date. After logging time, the start date is successfully updated to today. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/26351c20-a646-4c03-98af-184efb3b69e8

**Review by TheDescendant39 — COMMENTED** [review]
Hi @AaronPersaud, you have done a great job with this feature but I tried testing your PR changes and I am not getting the desired results.

**Test Steps**
1. I created a new User with a start date other than today(15th Aug 2023)
2. Verified that the new user was created with the start date I selected.
3. Logged-in as the new user and logged time for a few minutes. 
4. Refreshed the user profile page. (X Could not see the date change to 15th August)
5. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/335d1892-d0ff-4d02-98ce-ca9bae4b73fa


6. Found the following error in the console.
7. 
PR#1126Error

 

I see that other developers were able to test it positively so it could be just limited to my setup. I made sure that I had both the FE and BE branched active with everything compiled. Could you please look into this matter? We can ignore this if others can confirm it works for their systems. Thank you. 

|My Setup|
|---------|
|Macbook Air M2 2022|
|Node Version: v14.17.6|
|npm Version: v6.14.15|

Time Zone: PST

**Comment by AaronPersaud** [comment]
@TheDescendant39
Hi Vansh, thank you for reviewing!

> 6. Found the following error in the console.
> 
> PR#1126Error

<b>This error exists outside of this PR. If you try logging time on the development branch, this error is thrown sometimes.</b>

> My Setup
> Macbook Air M2 2022
> Node Version: v14.17.6
> npm Version: v6.14.15
> Time Zone: PST

<b>I don't believe any of these should affect the PR, these all look good</b>

> 4. Refreshed the user profile page. (X Could not see the date change to 15th August)
> 

Interesting, I have no idea why the Start Date didn't update. I would suggest doing the following and then trying it again:

- run `npm install` on FE and BE
- run `npm start` and `npm run start:local` as normal
- clear your cache
- hard refresh the browser (cmd-shift-R on mac)

Try these, test it again and get back to me. If none of those work, I'll have to do more investigating.

**Review by yunshan111 — DISMISSED** [review]
LGTM. Tested your changes.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/65985986/1914e872-3501-4ef3-af98-30dee3cf12ab

**Review by DavidC0126 — COMMENTED** [review]
Hi @AaronPersaud,
I tested your PR and all functions you mentioned were running as intended except for when I created a start date and when I logged time, the date would automatically shift by one day later than the time logged date. I cannot figure out why.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/cea7b15b-430d-4294-b391-6f5887aa4022

**Comment by AaronPersaud** [comment]
Hi @DavidC0126, thank you for reviewing!

See the "Note" section at the bottom of the PR description.

The current behaviour when creating a new user uses UTC for timezone. If you created a new user on dev branch and go and check the start date, the same behaviour would happen (for example, 9PM PST is 4AM UTC, that's why it will show the next day).

**Comment by DavidC0126** [comment]
> Hi @DavidC0126, thank you for reviewing!
> 
> See the "Note" section at the bottom of the PR description.
> 
> The current behaviour when creating a new user uses UTC for timezone. If you created a new user on dev branch and go and check the start date, the same behaviour would happen (for example, 9PM PST is 4AM UTC, that's why it will show the next day).

okay, I got it. Thank you!

**Review by eduvarjaor — COMMENTED** [review]
Hi @AaronPersaud 

I tested this PR with the proper backend PR (as you can see in the video) and the start date wasn't updated. Am I doing something wrong?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/c8b90e54-5191-4caa-bbe0-dcd5b0b13e3b

**Comment by TheDescendant39** [comment]
> @TheDescendant39 Hi Vansh, thank you for reviewing!
> 
> > 6. Found the following error in the console.
> > 
> > PR#1126Error
> 
> This error exists outside of this PR. If you try logging time on the development branch, this error is thrown sometimes.
> 
> > My Setup
> > Macbook Air M2 2022
> > Node Version: v14.17.6
> > npm Version: v6.14.15
> > Time Zone: PST
> 
> I don't believe any of these should affect the PR, these all look good
> 
> > 4. Refreshed the user profile page. (X Could not see the date change to 15th August)
> 
> Interesting, I have no idea why the Start Date didn't update. I would suggest doing the following and then trying it again:
> 
> * run `npm install` on FE and BE
> * run `npm start` and `npm run start:local` as normal
> * clear your cache
> * hard refresh the browser (cmd-shift-R on mac)
> 
> Try these, test it again and get back to me. If none of those work, I'll have to do more investigating.

Hello @AaronPersaud, I was able to test the changes successfully after clearing the cache and hard refresh. Thank you so much for the response.

**Review by TheDescendant39 — APPROVED** [review]

**Comment by AaronPersaud** [comment]
@eduvarjaor 
Hi Eduardo, thank you for reviewing!
 
> I tested this PR with the proper backend PR (as you can see in the video) and the start date wasn't updated. Am I doing something wrong?

It seems you've done everything correctly, so it might be a refresh issue. Please try these steps that I suggested to Vansh in a previous comment.

- run `npm install` on FE and BE
- run `npm start` and `npm run start:local` as normal
- clear your cache
- hard refresh the browser (ctrl-shift-R/cmd-shift-R)

Try these, test it again and get back to me. If none of those work, I'll have to do more investigating.

**Review by jerryren527 — DISMISSED** [review]
Hi @AaronPersaud !

Thanks for your clear instructions! I am able to test your FE and BE changes and can confirm that your code accomplishes the following:

1. `Start Date` field included and editable on `Create New User` page.

2. The date picker’s start date is, by default, the date after the user was created in the system.

3. Person’s start date is auto-updated to the current day when the user logs time into HGN for the first time.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/55968519/3e8f2b18-28d2-49a1-b9f2-dbe12e2edaeb


Great job!

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @AaronPersaud 

I tested your PR and thank you for the detailed instructions. 

However upon testing, I wasn't getting the desired results. The start date wasn't updating on the user profile. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/a5255adc-0043-4153-8163-3ad7dce5e981

In one instance, when I tried to reset the password on the user I created, all the users disappeared. Could be unrelated to your PR. 
Occurs at the :22 second mark.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/ed14ea2c-db11-4dd4-aef0-ae391cfa1ba2

Lastly, I would get this error on the backend. 
could be related to your PR.
Screenshot 2023-08-16 at 8 06 27 PM

**Comment by AaronPersaud** [comment]
Hi @luisarevalo21, thank you for reviewing the PR!


> In one instance, when I tried to reset the password on the user I created, all the users disappeared. Could be unrelated to your PR.

I think this is unrelated to the PR, I never experienced this once while developing/testing and none of the other reviewers saw this behaviour.

 > Lastly, I would get this error on the backend.
could be related to your PR.

This is outside of the PR. If you try logging time on dev branch, you'll see the same failing to find task error.

> However upon testing, I wasn't getting the desired results. The start date wasn't updating on the user profile.

Please do all of the following:
- run `npm install` on FE and BE
- run `npm start` and `npm run start:local` as normal
- clear your cache
- hard refresh the browser (ctrl-shift-R/cmd-shift-R)

After following those steps, try testing again and let me know.

**Comment by luisarevalo21** [comment]
> Hi @luisarevalo21, thank you for reviewing the PR!
> 
> > In one instance, when I tried to reset the password on the user I created, all the users disappeared. Could be unrelated to your PR.
> 
> I think this is unrelated to the PR, I never experienced this once while developing/testing and none of the other reviewers saw this behaviour.
> 
> > Lastly, I would get this error on the backend.
> > could be related to your PR.
> 
> This is outside of the PR. If you try logging time on dev branch, you'll see the same failing to find task error.
> 
> > However upon testing, I wasn't getting the desired results. The start date wasn't updating on the user profile.
> 
> Please do all of the following:
> 
> * run `npm install` on FE and BE
> * run `npm start` and `npm run start:local` as normal
> * clear your cache
> * hard refresh the browser (ctrl-shift-R/cmd-shift-R)
> 
> After following those steps, try testing again and let me know.

Hello @AaronPersaud 

I followed your guide, however, I was unsuccessful. The start date still showed the old date instead of updating it.

**Comment by n0vay** [comment]
Created a new user, I was able to edit the start date. Good Job!
image

**Review by n0vay — APPROVED** [review]

**Review by harshidad — COMMENTED** [review]
I tried to check multiple times but start date not showing as mentioned. I have attched the video for reference. Please let me know if I follow different steps here.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/e42a0c6a-4a6b-4dce-8ae6-82d2cc0ee367

**Review by liaoyufu-leo — APPROVED** [review]
Hi, this change works on my device. Excellent work! @AaronPersaud 

image
image
image

**Comment by AaronPersaud** [comment]
Hi @harshidad , thank you for reviewing the PR!

> I tried to check multiple times but start date not showing as mentioned.

There is a backend PR that also needs to be checked out. Did you do this? [PR472](https://github.com/OneCommunityGlobal/HGNRest/pull/472)

**Review by eduvarjaor — DISMISSED** [review]
I followed your new instructions and it worked as intended. Great job @AaronPersaud !

**Review by ss23046 — APPROVED** [review]
Hi @AaronPersaud 
I tested both FE and BE PRs and they work as expected. 
1. Logged in as an admin user
2. Created a new user with a later Start Date
3. Logged into the new account, checked the profile to confirm if the Start Date matches the new Start Date(the one I'd set). 
4. Started the timer and stopped after a minute, the start date is successfully updated to today.
Screen Shot 2023-08-18 at 10 04 39 PM
Screen Shot 2023-08-18 at 10 05 01 PM

**Review by Chuehleo — DISMISSED** [review]
Everything works as expected, great job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/122568562/e9bfcbe1-554a-4854-9740-cb39c699c84b

**Review by yaow62023 — APPROVED** [review]
I have test your PR, the new feature work as intended. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/49848342-56bf-43de-8c60-85aa9af25ea3


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/9e4ea082-2005-4e79-b296-3bed63c5408a

**Review by yurisokolovicz — COMMENTED** [review]
Dear @AaronPersaud 

The start date is currently accessible and it overrides the initial date set during user creation. However, it can be modified by editing using the owner account. Despite this, the start date does not automatically update for me after logging time for the first instance in the HGN software. I've observed that this feature functions properly for other developers, which is why I'm leaving this comment for reference. Kindly review the video below for additional clarification.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/5b186f6d-3ba0-441f-bb50-33e7e5c48f7e

**Comment by beblicarl** [comment]
This functionality works as intended however there were errors in the backend console

[screencast-localhost_3000-2023.08.24-09_15_08.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/3a3c5376-4848-472d-9abb-7cc2ac9455ef)


### ERROR (Backend Console)

issue #1126-error

**Review by beblicarl — DISMISSED** [review]

**Review by luisarevalo21 — DISMISSED** [review]

**Review by Haoj1 — APPROVED** [review]
@AaronPersaud The Start Date upated correctly after the new created user submitted a new Time Entry. Nice work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/1978c8f9-038c-4e87-8fdb-d24d82cc20ff

**Pull request merged**
