### PR TITLE
Shiwani UserProfileModal unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/UserProfile/UserProfileModal/UserProfileModal.jsx`

## Main changes explained:
- Added 19 test cases: renders without crashing, check if modal is open when isOpen is set to true, check if modal is closed when isOpen is set to false, check modal title displays as expected, check if Cancel button works as expected when the type is not save, check if Close button works as expected when the type is save, check if modal message gets displayed as expected when the type is save, check if Resize button works as expected when type is image, check if Resize button does not get displayed when type is not image, check type updateLink when putUserProfile permission is present, check type updateLink when putUserProfile permission is not present, check if add blue square works as expected when type is set to addBlueSquare, check if modify blue square works a s expected when type is set to modBlueSquare, check if view blue square works as expected when type is set to viewBlueSquare, check if close button gets displayed when type is set to save, check if cancel button gets displayed when type is not set to save, check if add blue square do not get displayed type is not set to addBlueSquare, check if modify blue square do not get displayed type is not set to modBlueSquare, check if view blue square do not get displayed type is not set to viewBlueSquare 

## How to test:
1. check into current branch
2. do `npm test src/components/UserProfile/UserProfileModal/__tests__/USerProfileModal.test.js` 
3. check if all the test cases passes without any errors or warnings

## Screenshots or videos of changes:
Screenshot 2024-07-14 at 2 11 34 AM

## Note:
- There are a couple of console.log statements which was already added in the component before testing.

### CODE REVIEW

**Review by kdaga81 — APPROVED** [review]
image

All test cases passed! Was going to comment on console log but saw your note ;)

**Review by jinxyou — APPROVED** [review]
All test cases have passed. Great work!
Screenshot 2024-07-13 172149

**Review by cvtqx — APPROVED** [review]
All test cases pass. 

Screenshot 2024-07-13 at 9 35 04 PM

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-07-13 at 9 38 10 PM

**Comment by nikethaanand** [comment]
All the test cases are passed as expected.
image

**Review by JatinAgrawal94 — APPROVED** [review]
All test cases passed.
Good work!
PR 2453

**Review by vijay10pk — APPROVED** [review]
All the test cases are passed.
image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (92)

**Review by AnujVakil — APPROVED** [review]
I have tested this PR on current branch and it has passed all the test cases.
PR #2453_1

**Comment by beblicarl** [comment]
All test cases passed. Great work !!

image

**Review by beblicarl — APPROVED** [review]

**Comment by beblicarl** [comment]
All tests passed. Great work!!

image

**Review by jennZhang93 — APPROVED** [review]
Tested locally. The unit test passed. Make sure to turn off console log. Good work!
Screenshot 2024-07-17 at 10 13 31 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
