### PR TITLE
Ruike fix permission toaster

### PR DESCRIPTION
**Pull request by StrawberryCalpico**
# Description
Screenshot 2023-12-02 at 2 24 06 PM

## Related PRS (if any):
N/A

## Main changes explained:
- Added logic to check for http response and then display related messages

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. go to other links/permission management/manage user permission
6. edit any user's permission and save
7. make sure the green toaster pop up
8. go to HighestGoodNetworkApp/src/components/PermissionsManagement/UserPermissionsPopUp.jsx
9. at line 96 modify the url so it will receive a 404 from server
10. refresh the page and do step 6 again
11. make sure the red toaster and error pop up
## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114443664/58226b50-025c-4b83-81d4-87e1ecacf388

### CODE REVIEW

**Comment by ptrpengdev** [comment]
Hi @StrawberryCalpico , I tested the PR, and the codes work as expected.

- Sucess message upon permission update.


- Failure message after url modification.

**Review by Shuhua-L — APPROVED** [review]
Hi @StrawberryCalpico, everything LGTM! 

I've tried changing the endpoint as well as the request method to cause errors intentionally, and the red roaster with the error message popped up as expected. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/db824c3e-c1b5-449d-8171-3b63727ecce7

**Comment by DragonSlayer2401** [comment]
It appears to have worked correctly I technically got a CORS error in the console but I did still get the red popup. For some reason all of the code is underlined with red but it could just be VS Code acting up. Please watch the overview video below for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/6f99ce35-c803-4d83-bd75-d6cb3bd48626

**Review by nathanah — APPROVED** [review]
Tested and it worked as intended. Thank you

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
