### PR TITLE
Prabh removed delete button for Volunteers

### PR DESCRIPTION
**Pull request by PrabhjotSembhi**
# Description
Remove the ability for volunteers to delete tasks from other volunteers
When using a volunteer account and clicking on a task from another volunteer, the delete button will appear and it is possible to delete the task.
…

## Mainly changes explained:
I have added a check in SingleTask.jsx and if user.role is Volunteer the delete button will be not rendered
…

## How to test:
check into the current branch
do `npm install` and `npm run start:local` to run this PR locally
log in as a Volunteer user
go to dashboard→ Tasks and Timelog→ Click on someone's task→ check if delete button appear or not

## Screenshots or videos of changes:
check this video I have explained everything and some issues about testing. Please watch it full

https://user-images.githubusercontent.com/82662768/232076772-afbf3fb8-690c-471e-9174-aec44abbf5b9.mp4

## Note:
Please make sure to watch the video fully.

### CODE REVIEW

**Review by ypan710 — COMMENTED** [review]
Hi @PrabhjotSembhi, I've tested your changes and the result worked as expected.

Admin role:
Screen Shot 2023-04-14 at 10 43 58 AM

Volunteer role:
Screen Shot 2023-04-14 at 10 43 00 AM

**Review by Elisaudo — APPROVED** [review]
Hi @PrabhjotSembhi, I tested PR#769 and it is working as expected now. Good job!

Before:

PR#769 BEFORE

After:

PR#769 AFTER

**Comment by LucileTech** [comment]
Hi [PrabhjotSembhi](https://github.com/PrabhjotSembhi) I am facing the same problem you mentioned in your video so I did just as you did in it, changed "Volunteer" to "Administrator" and the delete button is indeed erased : 
Screenshot 2023-04-14 at 15 08 14
Screenshot 2023-04-14 at 15 08 25

**Comment by AnishPandita** [comment]
Hi @PrabhjotSembhi I tested your Pr and its working as intended.  I logged in using admin and also as volunteer and tested your solution and the delete button showed only for the admin and not volunteer.

https://user-images.githubusercontent.com/111321945/232168769-d971121b-a95c-4c4b-81c2-b1ff7f78ee0c.mov

**Review by abdel-lall — COMMENTED** [review]
works as expected. good job!

pr769(1)
pr769

**Pull request merged**
