### PR TITLE
Unit test for LinkModButton

### PR DESCRIPTION
**Pull request by GKD890**
# Description
This is a unit test for `LinkModButton` at `src/components/UserProfile/UserProfileEdit/__test__/LinkModButton.test.js`

## Main changes explained:

- Add the unit test cases for `LinkModButton` component.

## How to test:
1. check into current branch
2. do `npm install` and `npm test src/components/UserProfile/UserProfileEdit/__test__/LinkModButton.test.js`
3. verify that all tests pass.

## Screenshots or videos of changes:
UnitTest_LinkModButton_Result

### CODE REVIEW

**Review by bienzguoa — APPROVED** [review]
Code for unit test looks great! All test cases passed. Good job!
Screenshot 2023-12-17 at 12 15 01 AM

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 
Screenshot 2023-12-17 at 1 18 10 AM

**Review by ljrirene — APPROVED** [review]
WX20231217-023745@2x
Well done! All tests passed.

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-18 at 10 16 53 PM
All tests have passed successfully. Excellent job!

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
