### PR TITLE
Tim fix dashboard badge modal

### PR DESCRIPTION
**Pull request by tdkent**
# Description
(PRIORITY MEDIUM) Fix View Full Badge History modal (Dashboard > Badges > Badge Report button) modal to not crash app. Attempting to edit values in the modal and clicking Save Changes results in an error that freezes the app and forces a page refresh.

app-crash-error

## Related PRS (if any):
N/A

## Main changes explained:
- The Badge Summary modal accessible on the Dashboard (Dashboard > Badges > Badge Report) has been changed from editable to the same static modal that displays on the People Reports page.
   - The crashes were caused by unavailable (because the necessary prop drilling had not been set up) functions being called.
- All Badge Summary modals (Dashboard, People Reports, User Profile) have been updated to show text if the user has no badges.
   - “You have no badges” if it is the user’s own report.
   - “This person has no badges” if it is another user’s report.
- `key` prop errors in the badge summary modals have been fixed.
- A `button` element has been replaced by a `div` to fix a nested button error.

nested-button-error

## How to test:
- `git checkout Tim_fix_dashboard_badge_modal` to check into current branch
- `npm install` to ensure your modules are up to date (no new modules are added in this PR)
- `npm run start:local` to run this PR locally
- Log in as an admin
- Navigate to Dashboard > Badges > Badge Report. The modal should not be editable and should not crash the app when closed. There should be no “key prop” or “nested button” errors in the console.
- In the User Profile > Select Featured modal you can temporarily delete your badges to check the text “You have no badges.” is displayed. You can test against various screen widths as well. Also check that this modal does not display “key prop” or “nested button” errors in your console.
- Lastly, use Other Links > User Management to navigate to a different user account who has no badges (you can delete the badges from one of your own test accounts, or use Tim Core). The text displayed should now be “This person has no badges.”
- You can run the same tests on the badge modal located at Reports > Reports > People > select a person > Show Badges.  

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/4cd85749-56f1-43ab-916c-9df33027ff44

### CODE REVIEW

**Review by GaryB93 — APPROVED** [review]
Tested Badge Summary on Dashboard, User Profile, and Reports page. Application doesn't crash and no errors are present in the console. Verified messages indicating that the user doesn't have any badges. Good work!

Screenshot 2023-09-05 at 3 48 51 PM

Screenshot 2023-09-05 at 3 51 59 PM

**Review by Haoj1 — APPROVED** [review]
@tdkent Good job! Badge models look good to me and there is no error when opening badge report.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/f7363268-bb35-460c-99c8-8722eba150cb

**Review by luisarevalo21 — APPROVED** [review]
Hello @tdkent,

I tested your PR and works as intended. Great work!

I loged in as an admin and viewed my badges on the dashboard. No error occurred and was able to view them.
I then viewed them on the user profile. deleted them and showed "You have no badges." I then viewed your "Tim Core" account and also showed "You have no badges."
Lastly, I viewed the acocunt via the reports component and viewed their details. 
It showed "this person has no badges"

Great work and great description of the problem and your branch. 

Screenshot 2023-09-05 at 8 31 51 PM
Screenshot 2023-09-05 at 8 33 08 PM

Screenshot 2023-09-05 at 8 33 57 PM

Screenshot 2023-09-05 at 8 33 20 PM

**Review by robertoooc — APPROVED** [review]
Hi @tdkent, I reviewed your pr and didn't receive any errors or encounter bugs while doing so. The badge report modal is working well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/3047d701-58ea-4885-a82e-ed386251d99e

**Comment by Sssky-18** [comment]
Hi tdkent, I have tried all three listed steps in this PR, and all of them works well. 
Firstly, the Badge Report page showed completely without any crash.
I also tried to the Select Featured modal on my Admin account and Volunteer account, and the text showed correctly. The text “This person has no badges” also displayed well when I checked others' badges.
So I think your contribution on the Badge modal is correct and efficient. Nice work! 

截屏2023-09-05 21 18 54

截屏2023-09-05 21 20 03

截屏2023-09-05 21 20 42

**Review by DavidC0126 — APPROVED** [review]
Hi @tdkent I tested your PR and everything works as intended.

no_error1
no_error2

**Review by harshidad — APPROVED** [review]
Here I tested both scenario mentioned in PR. 
If user has no badges then "“This person has no badges.” display.
PR#1262

If user has badges then
 1. Navigate to Dashboard > Badges > Badge Report. The modal should not be editable and should not crash the app when closed. 
 2. User Profile > Select Featured modal you can temporarily delete your badges 
 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/66f43e3c-b1fb-4398-a181-c50e9d9a7067

Also there is no errors in the console for “key prop” or “nested button” .

**Review by navneeeth — APPROVED** [review]
The changes LGTM! Good implementation. Tested the following:

Navigated to Dashboard > Badges > Badge Report. The modal was not editable and did not crash the app when closed. There were no “key prop” or “nested button” errors in the console.
In the User Profile > Select Featured modal, temporarily deleted badges to check the text “You have no badges.” is displayed and it was. This modal does not display “key prop” or “nested button” errors in my console.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/9691a596-13b9-4816-ad58-a8e2c8ff7cea



Went to Other Links > User Management to navigate to a different user account who has no badges. The text displayed was “This person has no badges.”
Same test on the badge modal located at Reports > Reports > People > select a person > Show Badges.  

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/ba1abff8-0b59-49de-a8b6-bf677cd9fe98

**Review by tsunami776 — APPROVED** [review]
I tested with an Admin account and followed the steps in the PR description. In Dashboard > Badges > Badge Report, I confirmed the changes that modal is now not editable and will not crash. No error was printed in the console. User Profile > Select Featured modal, badges can be deleted from the modal. When there is no badge, the correct text is displayed. When looking at others' profiles through both user management and reports, the correct text “This person has no badges.” is displayed if there is no badge for the user. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/df2a906e-3bdf-4876-89b4-cc70d4b65b2a

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by cvtqx — APPROVED** [review]
I've reviewed this PR and all looks good. Report below:

1. Navigate to Dashboard > Badges > Badge Report. The modal should not be editable and should not crash the app when closed. There should be no “key prop” or “nested button” errors in the console. - THIS WORKS AND NO ERRORS IN CONSOLE.

badgeReport

2. In the User Profile > Select Featured modal you can temporarily delete your badges to check the text “You have no badges.” is displayed. You can test against various screen widths as well. Also check that this modal does not display “key prop” or “nested button” errors in your console. - THIS WORKS AND NO ERRORS IN CONSOLE. MODAL LOOKS GOOD IN ALL SCREEN SIZES.

Large screen:
selectFeaturedModal

Mobile screen:

SelectFeaturedModalResponsive


3. Lastly, use Other Links > User Management to navigate to a different user account who has no badges (you can delete the badges from one of your own test accounts, or use Tim Core). The text displayed should now be “This person has no badges.” - THIS WORKS AND NO ERRORS IN CONSOLE.

AnotherUser


4. You can run the same tests on the badge modal located at Reports > Reports > People > select a person > Show Badges.  - THIS WORKS AND NO ERRORS IN CONSOLE.

ReportsReportsPeople

Great job!

**Pull request merged**
