### PR TITLE
Bug fix on save changes warning notification on profile page

### PR DESCRIPTION
**Pull request by johny4437**

### CODE REVIEW

**Comment by KaixiangGU** [comment]
Hi Johny, I tested your PR. The saving notification goes away after saving successfully, but the notification is not showing up when I edit anything after that. It should show up every time I make changes to the user profile and disappear after I clicked the save changes button. 

Please take a look again, thank you! If you have any question, leave a comment here!

**Comment by johny4437** [comment]
Hi  KaixiangGu, I tested  here, the save notification goes away after saving and is showing up again when I am trying to edit after that. Every time a make a change on the user profile is showing up.

**Comment by KaixiangGU** [comment]
Hey Johny, sorry for the late response, is that possible for you to send me a short video of how you tested this PR? You can DM me on Slack! Thank you!

**Review by KaixiangGU — APPROVED** [review]
Thanks for your video Johny! Approved this PR.

**Pull request merged**
