### PR TITLE
Nahiyan_Optimize dashboard for mobile display

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
This PR makes the dashboard 100% compatible with mobile displays (375px width and up).

## Related PRS (if any):
This frontend PR is related to the dev backend

## Main changes explained:
- Updated fonts on all components so they become more responsive.
- Updated some icons to be more responsive at smaller viewports
- Added max height on leaderboard and timelog tasks as they can take up too much space.
- Fixed widths on some components.
- Leaderboard will now show up at the bottom when at smaller viewports.

## How to test:
1. check into the current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to the dashboard
6. verify that all components and inner components on the dashboard are working properly and have no visual issues at all viewports.
7. verify this new feature works in [dark mode](https://docs.google.com/document/d/11OXJfBBedK6vV-XvqWR8A9lOH0BsfnaHx01h1NZZXfI)
8. The HEADER is NOT part of the PR.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/5877ccb8-7be6-4e46-8c40-71129822e431

### CODE REVIEW

**Review by HowieMiao — CHANGES_REQUESTED** [review]
Tested PR and leaderboard reorders and stacks well for mobile viewing as intended. 

image

Only problem I run into is around the 1024x768 margin, the <span> class = "message" disappears at this resolution or below, not sure if intentional and not sure if it mirrors on live service as the message is different but probably good to keep track of.

image

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and the alignment of the components fits in the page according to the width. Great work.

Suggestion: The dropdown field name like "Select Team", "Select Teamcode" and "Select color" text size remains same throughout various width, but the other text adjust to the screen width. ie. the tab name like "Task", "Current week Timelog" is having smaller text size compared to the dropdown field name.

**Review by kdaga81 — CHANGES_REQUESTED** [review]
1. Table member header overlapping with rows.
image

2. Alignment of search button 

image

3. Leaderboard header color in light mode

image

**Review by nyelmela — CHANGES_REQUESTED** [review]
I reviewed the dashboard and everything works well
The change I request is that when it is in mobile mode I am not able to change the date at Search By Date option.

image

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/b0d55022-685e-47f1-a801-24da58d6ece6

**Review by Jingyii800 — CHANGES_REQUESTED** [review]
Hi Nahiyan, I have tested this PR. It mostly works well with mobile display, no text overlap, things are in good size. One problem is there is a big white gap in the current week timelogs tab for mobile display. Please refer to my screenshot and video. It would be better if this white empty area could be in a proper size.
image

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/60c14482-4ac7-4fba-93e6-debbcd85bd4c

**Review by Sarath-3119 — DISMISSED** [review]
image

image


As per the steps mentioned and the requirement, this pr is working as intended in dark mode as well.

**Comment by Parth-tech** [comment]
Hey @Nahiyan-16,
Could you change the `Related PR's (if any)` section of your pull request? I believe this PR is related to `development` branch of backend. Just a suggestion as it would help avoid confusion.

**Review by Parth-tech — CHANGES_REQUESTED** [review]
Hey Nahiyan,
I review both light and dark mode and here are the issue that I encountered:

1. The user name is clipped for iPad Pro
Activity For Clips UserName

2. The dashboard page has horizontal scroll in light mode but not in dark mode
`Dark Mode:` Have a look at the border of `Activity for div block`
Dark Mode Horizontal Scroll Not possible

`Light Mode:` 
Light Mode Horizontal Scroll possible - 1
Light Mode Horizontal Scroll possible - 2

**Review by pavanswaroopl — CHANGES_REQUESTED** [review]
Hi, everything looks good, functionality-wise, but there are some improvements that make the app look good on a mobile display, 

1. When the screen size is reduced or expanded, the dropdown option text size doesn't change.
2. When the screen size is almost similar to an iPhone, the dropdown options like "Select Team", aren't padded well, the text is attached to the border, some padding around would look good.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/f16c2e61-9633-4789-a311-e5dbffee77d3


 

Screenshot 2024-06-28 at 1 23 27 PM

**Comment by IchinnorovTuguldur** [comment]
Hello Nahiyan, 

I tested the both light mode and dark mode. I didn't encounter any errors. 
Screenshot 2024-06-28 at 5 14 39 PM

**Review by tianyangL11 — APPROVED** [review]
I‘ve tested them and all components work properly.   Great job!
7c0d7f8690656f1b0f768881fb7668f
449f0d03f8960e939d9db72c7dbdaca

**Review by jinxyou — CHANGES_REQUESTED** [review]
This part of the layout doesn't work in any mobile view. Please review it.
Screenshot 2024-06-29 195624

**Review by vishavk1992 — COMMENTED** [review]
I  have tested this PR with dark mode and it works as expected . 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/a2fddc64-6409-4fbe-9089-994106906522

**Comment by Nahiyan-16** [comment]
> Tested PR and leaderboard reorders and stacks well for mobile viewing as intended.
> 
> image
> 
> Only problem I run into is around the 1024x768 margin, the class = "message" disappears at this resolution or below, not sure if intentional and not sure if it mirrors on live service as the message is different but probably good to keep track of.
> 
> image

Hi @HowieMiao, yes this is an intended feature as this represents a stand-in for the logo.

**Review by jinxyou — DISMISSED** [review]
It seems all right right now. Great work!
Screenshot 2024-07-03 210238

**Review by Kaushik-Malikireddy — CHANGES_REQUESTED** [review]
Hi Nahiyan, 
I tested your changes. The displays and the text from the dashboard page are all visible properly 375 pixels and above.

**Issues:**

The only issue I found in the mobile is this part being cut off, check the image below. 
image

**Improvements:**

Based on the images below, the sizing of text, icons and space used should be changed as per the resolutions. We can have separate sizes for mobile, iPad and desktops

image
image
image

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi Nahiyan, 

I tested your changes. The displays and the text from the dashboard page are all visible properly 375 pixels and above.

**Issues:**

The only issue I found in the mobile is this part being cut off, check the image below. 
image

**Improvements:**

Based on the images below, the sizing of text, icons and space used should be changed as per the resolutions. We can have separate sizes for mobile, iPad and desktops

image
image
image

**Review by MinSun0814 — DISMISSED** [review]
image

nothing overlaps and everything looks good! Nice work!

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
When switching to mobile display, the dropdown menu in team member tasks is left aligned. Also, the text inside Badges container also left aligned. The same applies for dark mode as well.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/980e40af-91d2-429d-85f2-8af205167ba9

**Review by HowieMiao — CHANGES_REQUESTED** [review]
Span is still disspearing under smaller resolutions, as well, the top right menu buttons should turn into a hamburger menu earlier to avoid the odd stacking that happens with  Dashboard and Timelog on top

image

**Comment by Nahiyan-16** [comment]
> Span is still disspearing under smaller resolutions, as well, the top right menu buttons should turn into a hamburger menu earlier to avoid the odd stacking that happens with Dashboard and Timelog on top
> 
> image

Hi @HowieMiao, the header is a different component and doesn't pertain to this PR. Please bring up this issue on the bugs doc.

**Comment by Nahiyan-16** [comment]
> When switching to mobile display, the dropdown menu in team member tasks is left aligned. Also, the text inside Badges container also left aligned. The same applies for dark mode as well.
> 
>  Screen.Recording.2024-07-05.111124.mp4

@Vigneshwar-Muriki, please test this again as it seems that you have reviewed the PR before my new commit. Also please use developer tools when adjusting the viewport as we can see accurate widths.

**Review by Shadhrush5 — DISMISSED** [review]
Hi Nahiyan,

I have reviewed PR#2391. I followed the steps of checking out to the branch "Nahiyan_Optimize-dashboard-for-mobile-display" and running the application with the dev backend.

I tested the leaderboard and tasks components and see they are working well for small viewports. I have attached screenshots below.

Screenshot 2024-07-08 at 12 06 28 PM
Screenshot 2024-07-08 at 12 06 11 PM
Screenshot 2024-07-08 at 12 05 54 PM

There are some issues but I see them in the main branch as well and have nothing do to with your fixes. So I have approved the same and great work.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/119898772/f5a4f376-533b-41c5-93e2-0d56238c3ec3


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/119898772/f07c3f22-8039-4bc6-8b37-71419713f6a6

**Review by HowieMiao — DISMISSED** [review]
Webpage stacks and looks as expected for mobile displays

image

**Review by AnujVakil — CHANGES_REQUESTED** [review]
I have tested this PR in Light and Dark mode and It looks good to me for most of the parts. One change can be done is spacing between title "Dashboard" and "Timelog" and also between other titles to get more clear vision about sections. I have tested it on Samsung Galaxy S20 Ultra.

PR#2391_2

PR#2391_1

PR#2391_4

PR#2391_3

**Comment by Nahiyan-16** [comment]
@AnujVakil, please re-test this. I do not see the issue in timelog. And for the header, it is a different PR that is going to handle it.
Screenshot 2024-07-11 113632

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
When switching to mobile display, the text is left aligned. You can adjust the padding for the text in div block. Below video has the details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/131609223/9340fa1e-6794-44c0-bbb0-307f384408d1

**Review by AnujVakil — DISMISSED** [review]
I have re-tested this PR and as header section is going to be handled in other PR, everything looks good!

Screen Shot 2024-07-11 at 10 52 52 AM

**Review by angelalalacheng — DISMISSED** [review]
I test this PR using `Nahiyan_Optimize-dashboard-for-mobile-display` for frontend and the latest `development` branch for backend. I think all the components are responsive in mobile, tablet and desktop view. Nice work!!

Desktop
Screenshot 2024-07-12 at 9 16 39 AM

Tablet
Screenshot 2024-07-12 at 9 17 19 AM
Screenshot 2024-07-12 at 9 18 19 AM

Mobile
Screenshot 2024-07-12 at 9 19 04 AM
Screenshot 2024-07-12 at 9 19 37 AM
Screenshot 2024-07-12 at 9 21 31 AM

**Review by Rishitha1309 — APPROVED** [review]
I tested PR in light mode and dark mode it works fine in both the modes.

**Review by SaiLavanya1 — DISMISSED** [review]
I have tested the PR and it is working good.Below is the video for testing the PR.
https://www.loom.com/share/32c2a82bebcd4495958d93af2eb122bb

**Review by JatinAgrawal94 — DISMISSED** [review]
Changes work as expected.

https://github.com/user-attachments/assets/b86a76c0-dc94-4459-a524-af4203db13ac

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
