### PR TITLE
Shengwei create setup history modal

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
image

## Related PRS (if any):
This frontend PR is related to the  [767 backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/767).

## Main changes explained:
- Added file src/components/UserManagement/SetupHistoryPopup.jsx 
- Updated file src/components/UserManagement/UserManagement.jsx to include new SetupHistoryPopup 
- Updated src/components/UserManagement/UserSearchPanel.jsx to include new icon 
- Updated src/components/UserManagement/setupNewUserPopup.jsx to include global state to trigger SetupHistoryPopup  record refresh
- Updated src/utils/URL.js to include new backend API links.

## How to test:
1. check into current branch and [backend PR 767](https://github.com/OneCommunityGlobal/HGNRest/pull/767).
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Setup backend Gmail Oauth and .env in the backend: [Link for video tutorial ](https://docs.google.com/document/d/1HJJTDtWykjGb4IfiIFlHXDfp_IABvmwKxsMPqqF6rG8/edit) 
5. log as admin/owner user
6. go to navigation bar -> Other Links -> User Management
7. Verify the icon exist
image <br/>
8. Verify that the table is filterable by email, and sortable by Created Date, Expired Date, and Status.
9. Created a new record in the Semd Setup Link modal in user management UI
10. Verify that the Refresh button work:
    - Make sure your backend is setup for email sending feature. This includes
         -  setup Gmail Oauth ([Link](https://docs.google.com/document/d/1HJJTDtWykjGb4IfiIFlHXDfp_IABvmwKxsMPqqF6rG8/edit) )
         -  Change the email variable in the **refreshSetupInvitation** function in **src/controllers/profileInitialSetupController.js** (backend). Comment out `const { email } = result;` and use `const email = 'YOUR_EMAIL_TO_RECEIVE_MSG@gmail.com';`
         - image
    - Click on the Refresh button on a cancelled record:
         - Verify that success toaster message should displayed.
         - Confirm that the record  status changes to Active.
         - Check that the expiration date extends by 3 weeks from the current date.
         - You should receive an email message  image
         - The setup link should be valid.  image

     - Click on the Refresh button on a active record: 
         - Verify that success toaster message should displayed.
         - Check that the expiration date extends by 3 weeks from the current date.
         - You should receive an email message image
         -  The setup link should be valid.  image
11. Verify that the cancel button is working as expected:
    - Success toaster message should displayed.
    - Record status should change to Cancelled status.
    The setup link should be invalid. You should receive an email with the setup link by hitting the refresh button in the previous step. You should see an invalid message UI once click on the link.  
image

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/6c86eb1e-8d0b-42db-9c15-28b18c81366b

## Note:
You need to Setup gmail oauth feature for testing. Also, change the email variable in the **refreshSetupInvitation** function in **src/controllers/profileInitialSetupController.js** (backend). Comment out `const { email } = result;` and use `const email = 'YOUR_EMAIL_TO_RECEIVE_MSG@gmail.com';` so that the application will send email to the email you defined!

### CODE REVIEW

**Review by skaush21 — COMMENTED** [review]
Left a comment on Backend [PR 767](https://github.com/OneCommunityGlobal/HGNRest/pull/767)

**Review by skaush21 — DISMISSED** [review]
commented on backend, works.

**Comment by nnamdixobi** [comment]
I looked at the front end and everything you mentioned works perfectly

**Review by 20chen-7 — COMMENTED** [review]
I do not know why, I received the fetch invitation error and invitation email looks good
Screenshot 2024-03-15 at 10 34 37 PM
Screenshot 2024-03-15 at 11 18 33 PM
Screenshot 2024-03-15 at 11 23 49 PM
Screenshot 2024-03-15 at 11 26 16 PM

**Comment by ptrpengdev** [comment]
> a

Hi @20chen-7 

For the error, what's the network request response from the backend? Could you inspect the network request in the developer mode from the browser? Should be something similar to the screenshot as follows:

image

**Comment by ptrpengdev** [comment]
> not know why, I received the fetch in

Hi @20chen-7 

For the error, what's the network request response from the backend? Could you inspect the network request in the developer mode from the browser? Should be something similar to the screenshot as follows:

image

**Review by metaphor987 — DISMISSED** [review]
Hi Shengwei,

I've tested the changes using an owner account and the main functionalities of the "Setup history modal" are working well. Nice work! The recording below shows my testing of the cancel and refresh buttons for a new setup record.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/ea4b36ab-d1b4-4f2a-a3d7-7c8052cecb9d

I encountered one issue for the filter: The "Created Date" and "Status" filters in the "Setup history modal" work well, but the "Expired Date" filter seems to not work correctly on my side, as shown in the recordings below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91745551/87f4263e-34dc-49f8-befa-19781e5998b3

Thank you!

**Review by 20chen-7 — DISMISSED** [review]
I logged as Owner account, every thing work as expected. But logged as Admin, I will receive the error like the previous review.
When I canceled, the link is invalid.
Screenshot 2024-04-20 at 1 21 23 PM
And on my device, the cancel btn is little hard to see. could do you make the model a little bit wider?
Screenshot 2024-04-20 at 1 16 16 PM

**Comment by 20chen-7** [comment]
> I do not know why, I received the fetch invitation error and invitation email looks good Screenshot 2024-03-15 at 10 34 37 PM Screenshot 2024-03-15 at 11 18 33 PM Screenshot 2024-03-15 at 11 23 49 PM Screenshot 2024-03-15 at 11 26 16 PM

Also, when I logined as admin account, I found the system showed error like this, if admin is not allowed to see the invitation history, can you remove the notification of about fetch error?
Like the video shows:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102696148/a6536195-dd89-4a06-998d-09989bad31a6

**Review by abdel-lall — CHANGES_REQUESTED** [review]
Hi @Shengwei, I just wanted to let you know that there's a function run by the cron job that automatically deletes expired tokens. You're attempting to display them in this PR. Perhaps consider adding a manual way to delete the expired tokens and removing the function.
Screenshot 2024-04-20 225252

**Comment by ptrpengdev** [comment]
> Hi @shengwei, I just wanted to let you know that there's a function run by the cron job that automatically deletes expired tokens. You're attempting to display them in this PR. Perhaps consider adding a manual way to delete the expired tokens and removing the function. Screenshot 2024-04-20 225252

Thank you for pointing out this issue. I will update the code accordingly.

**Review by abdel-lall — COMMENTED** [review]
Please add the toast import to the SetupProfileUserEntry.jsx file. It appears to have been removed.

**Comment by ptrpengdev** [comment]
> Please add the toast import to the SetupProfileUserEntry.jsx file. It appears to have been removed.

Hi @abdel-lall 

I ran a quick check. The toastify import is removed in commit ada083266371df5c779c7682113c5681732ca2e1 and excluded in the development branch since then. I will include toastify the import in this PR.

**Comment by ptrpengdev** [comment]
> Hi @shengwei, I just wanted to let you know that there's a function run by the cron job that automatically deletes expired tokens. You're attempting to display them in this PR. Perhaps consider adding a manual way to delete the expired tokens and removing the function. Screenshot 2024-04-20 225252

Updated in the backend.

**Review by metaphor987 — COMMENTED** [review]
Hi @ptrpengdev and @20chen-7,

I have re-tested the functionalities using owner and admin accounts. For both accounts, I didn't see the fetching error message. I did see an error message occasionally when entering the dashboard page:
Screenshot 2024-04-27 at 11 32 49 PM

However, after clearing the site data and logging in again, this message does not appear. So I guess this is not a problem.

For both accounts, the Cancel button works as expected. However, after clicking the Refresh button, the link gets refreshed, but I don't receive a new email now... I'm not sure if this is due to testing on an invitation email record that is added last week, or if it's related to a token refresh requirement for the gmail api. Thank you!

**Review by cgomezhub — CHANGES_REQUESTED** [review]
I am having some issues:

Make sure you are handling errors correctly. In particular, make sure you're using try/catch to handle promise errors.



https://www.loom.com/share/3b4c464352eb4356b12864e5c74b50d7?sid=609bc7aa-05cf-4fdf-9a10-7b61024ebba5

**Review by cgomezhub — DISMISSED** [review]
Good Job!

I tried by setting up a new user and sending the invite directly. It works as you described.

https://www.loom.com/share/d15b825e33644d0aa9ed98adfa6d814b?sid=99e03712-890f-4779-91f3-a4e353d92f49

**Comment by ptrpengdev** [comment]
> I am having some issues:
> 
> Make sure you are handling errors correctly. In particular, make sure you're using try/catch to handle promise errors.
> 
> https://www.loom.com/share/3b4c464352eb4356b12864e5c74b50d7?sid=609bc7aa-05cf-4fdf-9a10-7b61024ebba5

Hi @cgomezhub 

From the video, I think the error is introduced by the invalid/expired token used for the email-sending feature. The error is handled inside the emailSender.js explicitly. 

This means that the status of the response reflects the operation of the invitation token update, regardless of email delivery. There are several concerns regarding including email-sending status in the operation:

1. The token could be updated successfully but fail to deliver the email message. 
2. The SMTP server could be unreliable.
3. Overhead is added for handling errors from the SMTP server.

Hence, in my code, I didn't do anything for failed email delivery. Personally, I believe it would be sufficient to log the email failure event (log sends to Sentry in prod and dev and sends to console in local). Please let me know if you have a different opinion on this. Thanks.

**Review by abdel-lall — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
