### PR TITLE
Jiangwei - create unit tests for the TeamTable component

### PR DESCRIPTION
**Pull request by Jiangwei-shi**
# Description
Create a unit test for the TeamTable component to confirm whether it working as intended.

## Main changes explained:
- Create file TeamMembersPopup .test.js to do the unit tests

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. open file src → tests → TeamTable .test.js
4. run `npm run test src/__tests__/TeamTable.test.js`

## Screenshots or videos of changes:
image

## Note:
If all tests passed, everything worked as intended.

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-11-12 at 2 25 58 AM

**Review by wantingxu7 — APPROVED** [review]
I ran the test and got PASS. Good work!

**Comment by beblicarl** [comment]
All tests passed and the code is great !!!

image

**Review by beblicarl — APPROVED** [review]

**Review by DavidC0126 — COMMENTED** [review]
Hi I tested the PR and it works as described.

teamtabletest

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-11-16 045928

**Review by zuhang2000 — APPROVED** [review]
Hi I tested this PR. All tests passed. The testing code seems good to me. Good job!
Screenshot 2023-11-19 at 12 22 08 AM

**Comment by ptrpengdev** [comment]
All tests passed with no issues.

image

**Review by Alforoan — APPROVED** [review]
All tests passed. Nice!

image

**Review by ChengyanOo — APPROVED** [review]
Hi @Jiangwei-shi,

Outstanding work on the unit test! Your thorough approach and attention to detail are commendable.

Screenshot 2024-01-11 at 16 02 38

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
