### PR TITLE
update shadow style for new components

### PR DESCRIPTION
**Pull request by AuroraLovesWhales**
# Description
Update shadow style for new components and previously missed components throughout app.

## Main changes explained:
Add import { boxStyle } from 'styles' and style={boxStyle} to buttons that need shadow style to be applied.

## How to test:
check into current branch
do `npm install` and `...` to run this PR locally
log as owner/admin user
check the style is being applied in all the appropriate areas (see screenshots below)

## Screenshots or videos of changes:
Dashboard -> Tasks -> click on the red bell next to one of your own tasks
Pasted Graphic 14

Dashboard -> Tasks -> under one of your own tasks
Pasted Graphic 24

Other Links -> Projects -> AAA USE THIS PROJECT -> WBS
Pasted Graphic 16

Other Links -> Projects -> AAA USE THIS PROJECT -> Members
Pasted Graphic 17

Pasted Graphic 19

Other Links -> Projects -> AAA USE THIS PROJECT -> WBS -> Jae’s WBS - USE THIS -> Add Task
Pasted Graphic 15

Other Links -> Permissions Management -> click on the “I” icon next to one of the roles
Pasted Graphic 21

Other Links -> Permissions Management -> click on one of the roles
Pasted Graphic 22

Submit Weekly Summaries -> Move This Summary -> choose a different week
Pasted Graphic 25

Profile 
Pasted Graphic 27

Profile -> Change Photo -> choose a picture with size greater than 50KB
Pasted Graphic 28

## Note:
Please let me know if you think I have missed any areas where the style need to be applied.

### CODE REVIEW

**Review by ramyaram2092 — COMMENTED** [review]
I have  checked all the screens you had mentioned. It looks good. Will check more screens and update this if needed 

Pic1

Pic2


Pic3

Pic4


Pic6

Pic7





Pic8



Pic9


Pic10

**Review by yaow62023 — APPROVED** [review]
I've tested your pull request, and the buttons now have shadows. The page is also without any issues.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/cab384c7-072f-49c5-8ef2-a504fab3f01c

**Review by tsunami776 — APPROVED** [review]
I tested your PR and the components in your screenshots now have shadows. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/65addff1-f512-40f1-bc25-2bbd3675e466

**Review by BaileyM96 — APPROVED** [review]
Hello @AuroraLovesWhales I tested your changes and everything looks great the shadows are consistent throughout the components great work! 

## Screenshots

 Shadows for WBS
 
Shadows  WBS

Shadows for the members

Shadows Members

Jaes WBS shadow changes

Jaes WBS

Permissions Management

Permissions Management


Permissions Management click on role

Permissions Mangement click on role

Submit weekly summary buttons

Submit Weekly summary move summary close window

Blue square reason

Blue Square Reason

Profile Pic error

Profile Pic Error

## Notes 

I had two more images but they will not upload, other than that they all have the shadow added to them.

**Review by belagaam — APPROVED** [review]
Tested the PR as per the instructions. The style is changed and looks consistent. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/0bbf8717-aac9-4fee-860b-ce4110fe0d57

**Review by ss23046 — APPROVED** [review]
Hi @AuroraLovesWhales 
Tested your PR.
LGTM!
Screen Shot 2023-08-29 at 10 26 18 PM
Screen Shot 2023-08-29 at 10 26 43 PM
Screen Shot 2023-08-29 at 10 28 32 PM
Screen Shot 2023-08-29 at 10 46 03 PM
Screen Shot 2023-08-29 at 10 28 01 PM

**Comment by Jiyuanxia** [comment]
Hi @AuroraLovesWhales , I have reviewed your pull request and tested it. It works as you intended. Well done.

Screenshot 2023-08-30 164159
Screenshot 2023-08-30 164220
Screenshot 2023-08-30 165039
Screenshot 2023-08-30 165127

**Review by iTvX — APPROVED** [review]
I have checked your pr, it worked as described.
CleanShot 2023-08-31 at 18 17 54@2x
CleanShot 2023-08-31 at 18 17 36@2x
CleanShot 2023-08-31 at 18 17 04@2x
CleanShot 2023-08-31 at 18 15 49@2x
CleanShot 2023-08-31 at 18 14 47@2x
CleanShot 2023-08-31 at 18 14 37@2x

**Review by gabi-lima — APPROVED** [review]
Well done! Working as expected.
image

**Review by veronicacheng2 — APPROVED** [review]
Hi @AuroraLovesWhales, I have tested the PR and everything works perfectly.

image

image


image

image


image

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

[screencast-localhost_3000-2023.09.04-13_10_30.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/9ab23a8a-ea4f-45b4-96dd-976c965203d3)

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you everyone, merging!

**Pull request merged**
