### PR TITLE
Kurtis date format fix v2

### PR DESCRIPTION
**Pull request by KurtisIvey**
<div id="user-content-toc">
  <ul align="center">
    <summary><h1 style="display: inline-block">Fix date format inconsistencies in app v2</h1></summary>
     <summary><h1 style="display: inline-block">PR 1204</h1></summary>
     <summary><h2 style="display: inline-block">Finally finished!</h2></summary>

  </ul>
</div>

# Description
Inconsistency in the date format under weekly summary reports was noticed. Therefore, a fix was implemented as it was just a small formatting issue most likely. Luckily, the tz package pretty much takes care of it since it handles most if not all date formatting in the app. The date format in .tz.format ~~ was fixed to the desired format to address the issue.
~ in addition to that, I was told to fix all the instances of the date format in 'YYYY-MM-DD' and change it to the appropriate format 'MMM-DD-YY'
~ I have thoroughly checked for compatibility with the weekly summary page to ensure no crashing is present

## Related PRS (if any):
Test with any backend. Personally, I used the current HGN rest dev backend
…

## Main changes explained:
- Change .format('YYYY-MMM-DD') to be   .format('MMM-DD-YY');
- enables date format consistency in weekly summary reports page
- Certain instances require configuring the Moment package to also be set to the "MMM-DD-YY"

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as an admin > verify weekly summary countdown timer has proper date format
4. go to reports > weekly summary reports > and double check the the date format is the same
5. go to view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.
6. go to view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res
7. go to view profile > look at the blue squares present and hover over them > date should be in proper format
8. go to timelog > current week timelog > verify date format in format such as "Jul-25-23"
9. <strong>(must be logged in as admin or higher)</strong>go to other links tab > usermanagement> pause someone, and verify the date format. be sure to unpause them if it's not your own account.
10. go to reports > teams > click any team to view created date format and verify in proper format. In addition, there is an invisible element with the class "update-date" you'll need to verify in the dom via inspecting on chrome. Search with the class and you'll find it.
11. dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.
12. dashboard > other links > projects > wbs > click one of the wbs task names > hopefully you found one with a start and end date, so you can verify it.

## Screenshots or videos of changes:
inconsistent format as noted in photo:

old date format pr1082

fixed:

fix weekly summ date consistency per jae

badge format desktop res:
pr1082 badge date format desktop
badge format tablet res:
pr1082 badge date format tablet
user report date format:
pr1082 update user report date format on individual
team report date format:
pr1082 fix format  team reports last updated date however is invisible
task date format:
pr1082 task date format
wbs date format(must check individ task in dashboard as volunteer and projects tasks wbs as admin:
 ~ error in backend when viewing individ task as volunteer is present on development branch as well. its a bug not caused by this PR
pr1082 wbs task date format start and end
weekly summary countdown timer format:
pr1082 weekly summary due date countdown date format fix
blue square date format fix
pr1082 fix date format from bluesquare description via custom function

note: the missing "other links" section wasn't caused by me. It's like that on development

### CODE REVIEW

**Review by iTvX — DISMISSED** [review]
I followed your instructions and tested your pr, it worked as described. Great job.


CleanShot 2023-08-30 at 16 02 47@2x
CleanShot 2023-08-30 at 16 02 41@2x
CleanShot 2023-08-30 at 16 02 14@2x
CleanShot 2023-08-30 at 16 02 06@2x
CleanShot 2023-08-30 at 16 01 47@2x
CleanShot 2023-08-30 at 16 01 35@2x
CleanShot 2023-08-30 at 16 00 00@2x
CleanShot 2023-08-30 at 15 59 47@2x
CleanShot 2023-08-30 at 15 58 48@2x

**Review by navneeeth — DISMISSED** [review]
LGTM! The PR changes work as expected across all the areas of tests. Good implementation, @KurtisIvey!

Tested the following:
log as an admin > verify weekly summary countdown timer has proper date format
weekly summary countdown timer


go to reports > weekly summary reports > and double check the the date format is the same
weekly summaries report from and to

weekly summaries report submitted

go to view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.

view profile basic information tab

go to view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res
select featured badges desktop
select featured badges tablet


go to view profile > look at the blue squares present and hover over them > date should be in proper format

blue squares hover

go to timelog > current week timelog > verify date format in format such as "Jul-25-23"
(must be logged in as admin or higher)go to other links tab > usermanagement> pause someone, and verify the date format. 
pause user in user management


go to reports > teams > click any team to view created date format and verify in proper format. 

team created date

dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.

dashboard task

dashboard > other links > projects > wbs > click one of the wbs task names > hopefully you found one with a start and end date, so you can verify it.

projects wbs start and end date

**Comment by Jiyuanxia** [comment]
Hello, @KurtisIvey. I've gone through your pull request and conducted some tests. The functionality works as you intended, but there is one issue that needs to be addressed. When I attempt to select feature badges, the entire page goes blank. However, everything else seems to be working perfectly. Great job on your work so far!

Weekly summary countdown timer
Screenshot 2023-08-30 212354

Weekly summary reports
Screenshot 2023-08-30 212546

Date display after pausing an account 
Screenshot 2023-08-30 212643

Errors after clicking select features badges
Screenshot 2023-08-30 213016

Date display while hovering a blue square
Screenshot 2023-08-30 213144

Current week timelog
Screenshot 2023-08-30 213242

Date display after pause someone
Screenshot 2023-08-30 213357

Team creating date format
Screenshot 2023-08-30 213700

Individual task time display
Screenshot 2023-08-30 213853

Wbs task time display
Screenshot 2023-08-30 214025

**Comment by KurtisIvey** [comment]
> Hello, @KurtisIvey. I've gone through your pull request and conducted some tests. The functionality works as you intended, but there is one issue that needs to be addressed. When I attempt to select feature badges, the entire page goes blank. However, everything else seems to be working perfectly. Great job on your work so far!

Thank you! just pushed through a fix for that. Had the old date formatter called there instead of the new one. Should work fine now

**Review by robertoooc — DISMISSED** [review]
Hi @KurtisIvey, I tried to review all dates that I could find across the website and it worked well. All dates seem to be consistent with the MM-DD-YYYY format that you intended.

Screenshot 2023-08-30 at 9 07 01 PM
Screenshot 2023-08-30 at 9 06 44 PM
Screenshot 2023-08-30 at 9 06 26 PM
Screenshot 2023-08-30 at 9 04 22 PM
Screenshot 2023-08-30 at 4 24 06 PM
Screenshot 2023-08-30 at 9 02 05 PM

Screenshot 2023-08-30 at 4 20 57 PM
Screenshot 2023-08-30 at 9 02 59 PM

**Review by DavidC0126 — APPROVED** [review]
Hi @KurtisIvey I tested your PR and everything works great! Good job.

- weekly summary countdown timer 
Screenshot 2023-08-30 at 9 08 10 PM
Screenshot 2023-08-30 at 9 12 50 PM

- reports > weekly summary reports > and double check the the date format is the same
Screenshot 2023-08-30 at 9 14 49 PM
- profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.
Screenshot 2023-08-30 at 9 15 48 PM
-  view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res
Screenshot 2023-08-30 at 9 16 36 PM
Screenshot 2023-08-30 at 9 17 39 PM
- profile > look at the blue squares present and hover over them > date should be in proper format

Screenshot 2023-08-30 at 9 18 09 PM
- dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.
Screenshot 2023-08-30 at 9 24 11 PM


Screenshot 2023-08-30 at 9 32 31 PM
- reports > teams > click any team to view created date format and verify in proper format.
Screenshot 2023-08-30 at 9 46 58 PM

Screenshot 2023-08-30 at 9 41 17 PM

**Review by yurisokolovicz — DISMISSED** [review]
Dear @KurtisIvey 

The date was correctly fixed in the application. Good Job!


Screenshot 2023-08-31 113026

Screenshot 2023-08-31 113144


Screenshot 2023-08-31 113225


Screenshot 2023-08-31 113331


Screenshot 2023-08-31 113436


Screenshot 2023-08-31 113524

Screenshot 2023-08-31 113610


Screenshot 2023-08-31 113720


Screenshot 2023-08-31 113838


Screenshot 2023-08-31 114053

**Review by tsunami776 — DISMISSED** [review]
I followed your steps and tested each of those date formats. They worked as described in the PR.

1. Weekly summary countdown timer

CleanShot 2023-08-31 at 13 38 47


2. Reports > weekly summary reports > date format

CleanShot 2023-08-31 at 13 41 44


3. View profile > manually pause profile to trigger an end date


CleanShot 2023-08-31 at 13 43 09


4. View profile > select features badges > date (both res)

CleanShot 2023-08-31 at 13 44 54

CleanShot 2023-08-31 at 13 44 16


5. View profile > blue squares present and hover over them 

CleanShot 2023-08-31 at 13 48 15


6. Timelog > current week timelog

CleanShot 2023-08-31 at 13 48 53

7. Other links tab > usermanagement> pause someone

CleanShot 2023-08-31 at 13 49 20


8. Reports > teams > click any team

CleanShot 2023-08-31 at 13 52 16

CleanShot 2023-08-31 at 14 06 28


9. Dashboard > click any task in the "tasks" section

CleanShot 2023-08-31 at 13 53 19

10. Dashboard > other links > projects > wbs > click one of the wbs task names

CleanShot 2023-08-31 at 13 54 27

**Review by gabi-lima — DISMISSED** [review]
Well Done Kurtis! Everything working as expected.
Captura de tela 2023-09-01 095147

Captura de tela 2023-09-01 095152

Captura de tela 2023-09-01 094712
Captura de tela 2023-09-01 094814
Captura de tela 2023-09-01 094829
Captura de tela 2023-09-01 094837
Captura de tela 2023-09-01 094900
Captura de tela 2023-09-01 094946
Captura de tela 2023-09-01 095005
Captura de tela 2023-09-01 095043

**Review by harshidad — APPROVED** [review]
Date format - 'MMM-DD-YY'. 
I tested date format on below 9 steps mentioned and it's working good!
Great Work!!

1.admin > verify weekly summary countdown timer has proper date format
2.reports > weekly summary reports > and double check the the date format is the same
3.view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.
4.view profile > select features badges > date should be in proper format 
5.view profile > look at the blue squares present and hover over them > date should be in proper format
6.timelog > current week timelog > verify date format 
7.reports > teams > click any team to view created date format and verify in proper format.
8.dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.
9.dashboard > other links > projects > wbs > click one of the wbs task names > check record with a start and end date, to verify it.


Date format fix v2 #1204_9
Date format fix v2 #1204_8
Date format fix v2 #1204_7
Date format fix v2 #1204_6
Date format fix v2 #1204_5
Date format fix v2 #1204_4
Date format fix v2 #1204_3
Date format fix v2 #1204_2
Date format fix v2 #1204_1

**Review by yaow62023 — APPROVED** [review]
I have tested your PR, all the date format are changed. Check the video below for details. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/5a41fbbb-6c64-472c-80a1-79d9d3ee697f

**Review by luisarevalo21 — DISMISSED** [review]
Hello @KurtisIvey ,

I tested your PR and works as intended great work!
I reviewed all of the sections I should review and all of them had the correct date format and no issues. Great work.
Screenshot 2023-09-01 at 8 12 49 PM
Screenshot 2023-09-01 at 8 15 03 PM
Screenshot 2023-09-01 at 8 16 03 PM
Screenshot 2023-09-01 at 8 17 15 PM
Screenshot 2023-09-01 at 8 17 32 PM
Screenshot 2023-09-01 at 8 17 49 PM
Screenshot 2023-09-01 at 8 18 16 PM
Screenshot 2023-09-01 at 8 18 53 PM
Screenshot 2023-09-01 at 8 19 24 PM
Screenshot 2023-09-01 at 8 21 09 PM
Screenshot 2023-09-01 at 8 25 35 PM
Screenshot 2023-09-01 at 8 26 08 PM

**Review by navneeeth — DISMISSED** [review]
Hi @KurtisIvey! Reviewed your PR again and everything LGTM!

Tested the following changes:

log as an admin > verify weekly summary countdown timer has proper date format
weekly summary due date

go to reports > weekly summary reports > and double check the the date format is the same
weekly summaries reports page from and to

go to view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.
basic information pause user

go to view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res
Desktop:
featured badges

Tablet:
featured badges tablet

go to view profile > look at the blue squares present and hover over them > date should be in proper format
schedule blue square

go to timelog > current week timelog > verify date format in format such as "Jul-25-23"
current week timelog

(must be logged in as admin or higher)go to other links tab > usermanagement> pause someone, and verify the date format. 
user management pause user

go to reports > teams > click any team to view created date format and verify in proper format.
team reports created date

dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.
individual task

dashboard > other links > projects > wbs > click one of the wbs task names > hopefully you found one with a start and end date, so you can verify it.

**Comment by Shreyj14** [comment]
hi @KurtisIvey I tested your PR and it works well. good job

Screenshot 2023-09-02 at 2 04 24 PM

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by cvtqx — APPROVED** [review]
Excellent work and I appreciate the detailed instruction on how to test which made testing this PR a breeze! New formatting works as described:

1. log as an admin > verify weekly summary countdown timer has proper date format


2. go to reports > weekly summary reports > and double check the the date format is the same


3. go to view profile > manually pause profile to trigger an end date. Verify the dates in the correct format under the basic information tab.


4. go to view profile > select features badges > date should be in proper format such as "Jul-25-23" , must work on desktop and tablet res


5. go to view profile > look at the blue squares present and hover over them > date should be in proper format


6. go to timelog > current week timelog > verify date format in format such as "Jul-25-23"
(must be logged in as admin or higher)


7.go to other links tab > usermanagement> pause someone, and verify the date format. be sure to unpause them if it's not your own account.



8. go to reports > teams > click any team to view created date format and verify in proper format. In addition, there is an invisible element with the class "update-date" you'll need to verify in the dom via inspecting on chrome. Search with the class and you'll find it.



9.dashboard > click any task in the "tasks" section to go to the individual task. verify start and end date format.


10. dashboard > other links > projects > wbs > click one of the wbs task names > hopefully you found one with a start and end date, so you can verify it.

**Comment by one-community** [comment]
Thank you everyone, merging!!

**Pull request merged**
