### PR TITLE
Jingyi assign project to user permission management

### PR DESCRIPTION
**Pull request by Jingyii800**
# Description
Gives the user permission to add any user on the project members page. "Other Links" -> "Projects" -> "Members" -> "Find user input" 

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- Manage the conditional rendering for Member.jsx

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/Owner user
5. go to "Other Links" -> "Permission Management" -> "Manage User Permissions"
6. In the project management section, grant a volunteer account without the permission "Assign Project To User" permission.
7. log in to this volunteer account and go to "Other Links" -> "Projects" -> "Members" -> "Find user input." Check if this volunteer can assign and unassign a project to a user.

## Note:
Check the Permissions Management spreadsheet for desired behaviors of permissions
https://docs.google.com/spreadsheets/d/1TfiJY9OLDZuyP2UgF0C1wI9tOSLKbS9MiJFH6n1Dsao/edit#gid=0

### CODE REVIEW

**Review by hbodgal — CHANGES_REQUESTED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145157488/c5dcee2a-a6a4-4ddf-93a7-c089b9e8ba3e

I gave permission to a volunteer user. But I was not able to assign projects to the user. Please check the video if I am doing anything wrong. Let me know on Slack.

**Comment by Jingyii800** [comment]
> HGN.APP.-.Google.Chrome.2024-05-04.02-25-17.mp4 
> I gave permission to a volunteer user. But I was not able to assign projects to the user. Please check the video if I am doing anything wrong. Let me know on Slack.

Did you check out this branch, "Jingyi_AssignProjectToUser_Permission_Management," for the front end, and use the latest development branch for the backend? It should work, Please refer to my video. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/c852bff3-7dab-4cb1-8c27-ee03189b2d24

**Review by jayyy-s — DISMISSED** [review]
I tested both adding and removing the permission for a volunteer account. Removing correctly removed the permission to assign users to a project and adding correctly gave users the permission. The volunteer account was able to both remove and add users to a project. I also checked other project permissions such as project creation, setting categories, and task management. The permission does not grant any of these so it is functioning correctly.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71467346/01872c80-5b4c-4926-8905-a47d48ed3720

**Review by peter6866 — APPROVED** [review]
Changes work as expected.
image

**Review by mohabbasd — APPROVED** [review]
Hello, I tested your PR and it works as expected. Below is a video for your reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/cfc712f0-470a-4de5-bdfb-ab0a5ee7708c

**Review by manikittu810 — APPROVED** [review]
Hello @Jingyii800 
Everything is working as mentioned. 
Screenshot 2024-08-04 at 8 47 17 PM
Screenshot 2024-08-04 at 8 48 58 PM
Screenshot 2024-08-04 at 8 49 36 PM


Thankyou

**Pull request closed without merging**
