### PR TITLE
Nahiyan dark mode for login screen

### PR DESCRIPTION
**Pull request by Nahiyan-16**
# Description
THIS IS A FOLLOW UP PR TO [PR#2105](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2105)
This PR makes dark mode available for the following pages: 
-  Login Page
-  Forgot Password Page
-  Force Password Update Page
-  Update Password Page

## Related PRS (if any):
This frontend PR is related to the dev backend.

## Main changes explained:
- Implemented dark mode for login page
- Implemented dark mode for Forgot Password Page
- Implemented dark mode for Force Password Update Page
- Implemented dark mode for Update Password Page

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as any user
5. go to dashboard→ Enable dark mode
6. Log out 
7. verify login page and forgot password page flips to dark mode
8. login as owner
9.  go to dashboard→ user profile -> update password 
10. verify that page flips to dark mode
11. type in this URL with your user id: `http://localhost:3000/ForcePasswordUpdate/{userID}`
12. user id can be found on the user profile url
13. verify that page flips to dark mode

## Screenshots or videos of changes:
Screenshot 2024-04-03 134144
Screenshot 2024-04-03 134213
Screenshot 2024-04-03 134236
Screenshot 2024-04-03 134250

## Note:
Please review previous PR before reviewing this one

### CODE REVIEW

**Review by aaryaneil — DISMISSED** [review]
All the above mentioned pages change to dark mode. Good work.
Screenshot 2024-04-03 at 3 56 26 PM
Screenshot 2024-04-03 at 3 57 41 PM
Screenshot 2024-04-03 at 3 58 22 PM
Screenshot 2024-04-03 at 3 58 58 PM

**Review by linkhanthtel — DISMISSED** [review]
Looks good! All the pages flip to dark mode!

#2112(Log In)
#2112(Update Password)
#2112(Forced Password Update)
#2112(Forgot Password)

**Review by jennZhang93 — DISMISSED** [review]
I've followed the requested testing steps. All the mentioned webpage worked as expected. Good job!

Screenshot 2024-04-15 at 10 51 03 PMScreenshot 2024-04-15 at 10 52 52 PMScreenshot 2024-04-15 at 10 52 06 PMScreenshot 2024-04-15 at 10 51 23 PMScreenshot 2024-04-15 at 10 51 17 PM

**Review by SRamen1999 — DISMISSED** [review]
Everything works as expected. All the above mentioned pages change to dark mode.

Screen Shot 2024-04-18 at 11 15 41 PM
Screen Shot 2024-04-18 at 11 10 18 PM
Screen Shot 2024-04-18 at 11 10 38 PM
Screen Shot 2024-04-18 at 11 14 06 PM

**Pull request merged**
