### PR TITLE
Tapan - Fixed UI for Create New Role Without Name and Permission

### PR DESCRIPTION
**Pull request by TapanPathak**
# Description

Screenshot 2024-03-07 at 1 58 00 PM

Demo of Bug - [https://www.dropbox.com/scl/fi/ei3ag16xb57isrx2ek7ak/Create-new-role-click-with-empty-fields-white-screen.mp4?rlkey=vb01psyvwwwmeyoigwmm1x1j7&e=1&dl=0](url)

## Related PRS (if any):
N/A
…

## Main changes explained:
- Fixed UI for handling new role request when rolename and permission are empty
- Role Name needs to be given
- Atleast one permission needs be to selected

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as owner user
5. Other Links -> Permissions Management -> Add New Role -> Create
6. Try to create a role without giving rolename and without selecting any permission, it should thrown an error in UI. 

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/46659daa-fc24-4976-826a-5a175e539425

### CODE REVIEW

**Review by lacnoskillz — APPROVED** [review]
Hello @TapanPathak 
I have pulled your changes and tested your code and it works as described. Nice work!
I attempted to make a role on dev without a name/role selected and the page goes blank

but with your changes the proper checks prevent that from happening nice catch!
See below video of successful role create.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/114305309/bd6cd7fb-3fa2-4a08-ac5d-d93c3f8c663b

**Review by Gugor99 — COMMENTED** [review]
### Report
Hi Tapan,
I tried to review your PR but compilation failed and I got an error message in the console. Please see screenshot for reference.
### Screenshot
Cattura2

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it works as intended. The role validation works fine and passed all the test cases. Please refer the video attached.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67577022/41888d9c-1488-48ba-b534-f500f73572f5

**Comment by dhairya-mehta** [comment]
Hey Tapan, I tested and verified your PR, I verified the edge cases of no name for the role and no role assigned. Good Job!

**Comment by dhairya-mehta** [comment]
Hey Tapan, I tested and verified the PR, while checking the popup check
image

**Comment by nnamdixobi** [comment]
Screenshot 2024-03-08 165521
Everything compiled correctly but I was unable to see the button to add a new role

**Review by yaow62023 — APPROVED** [review]
Hi, I have test your PR. The error message though out when no role name or no Permissions selected. Check the video below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/137429365/53ab713f-2677-4952-8869-5f3576986ebd

**Review by mohabbasd — APPROVED** [review]
Hello, I tested you PR and it works perfectly. Great Job! Below is a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91215370/f73f3f38-c155-49dd-a2c3-8f326da50379

**Comment by MQChen211** [comment]
Hi, I tested your PR and it works as expected. 
截屏2024-04-04 15 43 11
截屏2024-04-04 15 43 28
截屏2024-04-04 15 43 43

**Review by MQChen211 — APPROVED** [review]

**Review by SushmithaPrathap — APPROVED** [review]
Hey, I've gone through the PR and tested it according to the steps you provided. Tried out different combinations and everything works smoothly. Also, it correctly notifies if the role name already exists. Nicely done!

Here is the screen recording:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113482457/5cc8294d-e6e9-489b-a7d2-f8e8f67e28bb

**Review by Jaiwin-4998 — APPROVED** [review]
Hi, I just reviewed your PR and is working fine.

Screenshot 2024-04-04 at 10 26 05 PM
Screenshot 2024-04-04 at 10 25 12 PM

**Review by SRamen1999 — APPROVED** [review]
Everything works as expected.  When create a role without giving role name and without selecting any permission, it throws an error.  Also, it correctly notifies if the role name already exists. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/d4ad5711-059c-4d20-80d3-c7f2b1e14897


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56932664/805a98b5-ad94-4b02-859a-92478fb7e92a

**Comment by anandsesha** [comment]
Hi, I tested your PR, and its working as expected. Role name and at least one permission needed, else shows appropriate UI error.
Screenshot (749)
Screenshot (750)
Screenshot (751)
Screenshot (752)

**Comment by MQChen211** [comment]
Hi, I tested your PR and all works as expected.

截屏2024-04-12 14 50 26
截屏2024-04-12 14 50 32
截屏2024-04-12 14 50 44
截屏2024-04-12 14 50 56

**Review by MQChen211 — APPROVED** [review]

**Review by KurtisIvey — APPROVED** [review]
Approved. Everything functions as it should without any errors on the front or backend. Code changes are minimal while still accomplishing the desired fix. Photos attached for verification of clean error popup when criteria not met for creating new role. 

Fantastic job! 
Screenshot 2024-04-20 at 11 57 57 AM
Screenshot 2024-04-20 at 11 58 13 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
