### PR TITLE
Olga _ unittests for FoundUser

### PR DESCRIPTION
**Pull request by cvtqx**
# Description
Unit tests for FoundUser component

## How to test:
1. check into current branch
2. do `npm install` 
3. `npm test FoundUser.test.jsx`
4. verify that all tests pass

## Screenshots or videos of changes:
Screen Shot 2023-10-24 at 11 07 36 AM

### CODE REVIEW

**Comment by wantingxu7** [comment]
Hi, I tested the PR. I got the same "PASS" message from the description but also got some warning as below. Is this expected?

**Comment by Jiyuanxia** [comment]
Hi @cvtqx , I have reviewed your pull request and tested. I also got the same "PASS" message as the description with some error message.

Screenshot 2023-10-24 150003
Screenshot 2023-10-24 150042
Screenshot 2023-10-24 150051
Screenshot 2023-10-24 150101

**Review by DavidC0126 — COMMENTED** [review]
Hi @cvtqx I tested your PR and I passed all tests, but I encountered the warning messages the same as the others have mentioned.

unitest_founder

**Comment by Chuehleo** [comment]
Hi, I have ran and passed the test, but I also encountered the errors that others mentioned above.
Screenshot 2023-10-25 013050

**Comment by beblicarl** [comment]
This test passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by cvtqx** [comment]
@emunkh404 @Chuehleo @DavidC0126 @Jiyuanxia @wantingxu7 the console error has been fixed. Please review again when you can.

**Review by tsunami776 — APPROVED** [review]
Hi @cvtqx, your unit test for FoundUser component looks good to me. I ran the test and no console error was cast. 
CleanShot 2023-10-26 at 16 02 29

**Review by StrawberryCalpico — APPROVED** [review]
All test passed! Great work!
Screen Shot 2023-10-27 at 12 55 39 PM

**Review by KurtisIvey — APPROVED** [review]
Fantastic! Way to keep the tests DRY

pr1445 passes test without issue from recent commits

approved. Once it gets a few more approvals and re-reviews, I imagine it'll be merged without issue.

**Review by ChirayuRai — APPROVED** [review]
I checked out your PR and all tests seem to pass. Good job!

Screenshot 2023-10-27 at 4 47 30 PM

**Pull request merged**
