### PR TITLE
Tim fix task info changes modal close bug

### PR DESCRIPTION
**Pull request by tdkent**
# Description
(PRIORITY LOW) Tim: Fix Task Info Changes modal (Dashboard > Tasks > Click red bell icon) to close properly. Clicking the close button or Mark As Read button does not fully close the modal. The modal header remains on screen. In this state the close button no longer has any effect. A page refresh is required to return to the Dashboard. 

## Related PRS (if any):
N/A

## Main changes explained:
- Simple fix: the state setter controlling modal on/off did not receive the latest state directly from the `showTaskNotificationModal` state value. The state setter function has been updated to ensure the latest state is used.
- A `key` prop has been added to the modal map function to remove a key prop bug.

## How to test:
- `git checkout Tim_fix_task_info_changes_modal_close_bug` to check into current branch
- `npm install` to ensure your modules are up to date (no new modules are added in this PR)
- `npm run start:local` to run this PR locally
- log in as an admin user to access the full list of tasks
- under **Dashboard > Team Member Tasks**, find a task  with a red bell icon and click to open the **Task Info Changes** modal.
   - Note: the task should preferably be one of your own tasks so you also have access to the **Mark as Read** button. If you don't have a task of your own you can create one as an admin. You can also temporarily remove the logic in **TaskDifferenceModal.jsx** that only allows the task owner access to **Mark as Read** (see below)

markasread

- click the `x` icon to close the modal. The modal should completely close out and you should have full access to the Dashboard again.
- reopen the modal and click the `Mark as Read` button to test the same. (Note: this will clear the bell icon, so test this after testing the regular close button).
   - Note: you can generate a new red bell icon for a task you own by changing the name

## Screenshots or videos of changes:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98129080/90c0a836-4220-4b05-a839-56a99f4d0440

## Notes:
N/A

### CODE REVIEW

**Review by GaryB93 — APPROVED** [review]
Great work! The task notifications modal can now be closed without refreshing the page.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/0f168075-8a18-4e46-8284-12045c00db5e

However, I do have one suggestion that doesn't necessarily pertain to the bug but I noticed the component in question is called TaskDifferenceModal and then it's being referenced in state as taskNotificationModal. Is there any way we can change TaskDifferenceModal to TaskNotificationModal just for consistency?

Screenshot 2023-08-22 at 1 31 29 PM

**Review by tsunami776 — APPROVED** [review]
I reviewed the PR by adding a task to one of my projects. With the newly assigned task now visible on the dashboard, I observed that clicking either the "Close" or "Mark as Read" button returns the user to the dashboard without necessitating a page refresh. This behavior aligns with the intended functionality.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/56c6fb07-8f49-4a28-abc6-8db996694c85

**Review by DavidC0126 — APPROVED** [review]
Hi @tdkent I tested your PR and it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/ed776c9a-e242-4ef8-bdca-c93e38390ccb

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great!

[screencast-meet.jit.si-2023.08.23-09_33_05.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/17d220b1-f61a-4bfb-9742-9e72330e32e1)

**Review by beblicarl — APPROVED** [review]

**Review by harshidad — APPROVED** [review]
Working good!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/109878936/9c70a4bd-ba97-4f9e-87e5-dca63240e542

**Comment by eduvarjaor** [comment]
Hi @tdkent 

How can I create a task as an admin?

**Review by iTvX — APPROVED** [review]
Tested, it worked as intended.
Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/617f352a-08e0-4b68-9b0d-225cfd4bd374

**Review by navneeeth — APPROVED** [review]
LGTM! The PR works as intended. I temporarily removed the logic in TaskDifferenceModal.jsx that only allows the task owner access to 'Mark as Read' button and then performed the tests.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/d4f0b7c6-a3a0-477c-9114-01c8f15e64eb

**Comment by one-community** [comment]
Thank you all, merging!!

**Pull request merged**
