### PR TITLE
Peterson fix the bug that causes the time log page to reload indefinitely

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request has been opened to fix two bugs: the first one causes the loading indicator to remain indefinitely on the time log page, and the second one removed the blue color and bold style from the hours in the Leaderboard table and the Total Time column.

## Related PRS (if any):
None
…

## Main changes explained:
The component Header has been modified to fix the bug that causes the loading indicator to remain indefinitely on the time log page.

The component Leaderboard has been modified to fix the bug that removed the blue color and bold style of the hours in the Leaderboard table and in RIGHT the Total Time column. If a person has INTANGIBLE TIME, that total will be different from the total on the left and it should also be bold and blue to make the difference obvious. 
…

## How to test:
1. Check into current branch
2. Do npm install and ... to run this PR locally
3. Clear site data/cache
4. Log any user
5 . Go to the time log and check if your ID was sent along with the URL.
6. The time log page should display a loading indicator, and after the page has successfully loaded, the loading indicator should disappear and a table should appear.
7.  Go to the dashboard page and check if the hours in the leaderboard table, in the total column, are displayed in blue color and bold style if the total intangible time is greater than zero.
gif

## Screenshots or videos of changes:
Before my fix:
Before my fix

After my fix:
After my fix

## Note:
None.

### CODE REVIEW

**Review by kabraambika — APPROVED** [review]
The build is failing because of test cases. Merging the development branch again should resolve this issue. 

The feature is functioning as described in the pull request

https://github.com/user-attachments/assets/109c1fde-77fc-4b70-822a-41092128f51c

**Review by Chetan0606 — APPROVED** [review]
Tested as per the description and everything looks good

image

**Comment by ReinaT5678** [comment]
I tested the program using the description and everything looks as expected! I received no errors in the console.

Screenshot 2024-07-23 at 10 11 37 PM


Screenshot 2024-07-23 at 10 14 38 PM

**Review by ReinaT5678 — APPROVED** [review]

**Review by Ramaruva — APPROVED** [review]
Hi, I have checked your code changes and also tested in my local env, working as expected good work!

https://github.com/user-attachments/assets/ca5122de-663a-407b-a0c2-147bd6d27eac

**Comment by souravwalke** [comment]
I have checked your changes and tested them in my local environment, working as expected.

https://www.loom.com/share/99c91c8b0ffe442ab502b976bfaf1502?sid=8a6fcb6c-d792-4c4b-b5cb-4ab0e4a3fe24

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
