### PR TITLE
Ramya Unit Test : UsersProfile/ AssignBadgePopup

### PR DESCRIPTION
**Pull request by scoopstroop92**
# Description
Unit test for src/components/UserProfile/AssignBadgePopup
## Main changes explained:
-  New file
      - **_AssignBadgePopup.test.jsx_** : unit test cases 
      - **_MockAssignTabelRow.jsx_** : mock component
-  Existing file
      - **_AssignBadgePopup_**  : Added  test id to the objects for unit testing 
####  Test cases 
image

## How to test:
1. check into current branch
2. Uncomment the following line to  test the test cases in local 
    - jest.mock('axios')(Line No : 37)
3. do npm test AssignBadgePopup.test.jsx
4. check if all the test cases pass

## Screenshots or videos of changes:
image

## Note : 
Kindly take a look at the test cases and  suggest if more validations can be added

### CODE REVIEW

**Review by bienzguoa — COMMENTED** [review]
Hi Ramya, 
I checked the unit test. All test cases look good! It covers all basic rendering, test cases are passed. But I received such warnings related to component structures:
Screenshot 2023-12-29 at 4 33 06 PM

**Review by Alforoan — APPROVED** [review]
They all passed and the codes look good. Nice!

image

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 18 - PR6

**Comment by n0vay** [comment]
Test cases pass, getting the following warning:
There is another file with the same name in src/__tests__, but with .js extension. So, I would recommend changing the name as it could cause some confusion.
image

**Review by abdel-lall — APPROVED** [review]
Works as described. Good job!

Screenshot 2023-12-30 193827

**Comment by one-community** [comment]
> Test cases pass, getting the following warning:
> There is another file with the same name in src/**tests**, but with .js extension. So, I would recommend changing the name as it could cause some confusion.

Please list things like this as a change request, so we're sure to integrate them

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
