### PR TITLE
Deepthi add i icon permissions management

### PR DESCRIPTION
**Pull request by deepthikannan**
# Description
image
…

## Main changes explained:
- Imported FaInfoCircle from react-icons/fa and ReactTooltip from react-tooltip.
- Implemented an info icon next to the "User Roles" title.
- Configured a tooltip to display detailed information about permissions when the icon is hovered over.
…

## How to test:
1. Check out this branch.
2. Run npm install to install dependencies.
3. Clear site data/cache.
4. Log in as an owner user.
5. Navigate to Dashboard → Permissions Management.
6. Verify that the i icon appears next to the "User Roles" title.
7. Hover over the icon to ensure the tooltip displays the correct and detailed information.

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by manikittu810 — APPROVED** [review]
Hello @deepthikannan 
I have gone through every step mentioned and the changes made are working as mentioned above. Good work!
Screenshot 2024-08-04 at 4 33 03 PM

Thank you.

**Review by vijay10pk — APPROVED** [review]
All the changes are working as expected.
image

**Review by DiyaWadhwani — APPROVED** [review]
Hi Deepthi,
Reviewed your changes and they work as expected. Attached a screenshot below.
Thank you

**Review by gowthamdongari — APPROVED** [review]
All changes working as expected!
355653523-e9a37450-b507-4dab-a08b-7115b29f9ee4

**Review by Aishwarya0898 — APPROVED** [review]
Hi @deepthikannan 
The PR is working as expected, Here is the screenshot for reference.

PR #2536

**Comment by jayyy-s** [comment]
Tested and tooltip shows up the same and working as expected
PR 2536 sc

**Review by Pranay-ai — APPROVED** [review]
Hey  @deepthikannan 
I have reviewed the PR it's working as expected, please find the ss for reference
image

Thank You

**Review by preethamdnr — APPROVED** [review]
Hello Deepthi,
This Pr is working as expected in both the modes.
Screenshot (148)
Screenshot (147)

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
