### PR TITLE
Eduardo CopyToClipboard unit test

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
Created a unit test for the CopyToClipboard component to confirm whether it working as intended.

## Main changes explained:
- Created `src/__tests__/common/Clipboard/CopyToClipBoard.test.js`

## How to test:

1. check into current branch
2. do npm install
3. run `npm test CopyToClipBoard.test.js`

## Screenshot:
image

### CODE REVIEW

**Review by navneeeth — APPROVED** [review]
Hello, @eduhorta! The unit test passes! Good implementation!
unit_test_passing

**Review by yi-lin-1234 — APPROVED** [review]
Hello, all the test cases are passed. Great work!
Screenshot 2023-10-31 at 4 31 47 PM

**Review by vikrambadhan — APPROVED** [review]
All the test cases passed! Great Job!

Week10 - PR1

**Review by tsunami776 — APPROVED** [review]
Hi @eduhorta, your unit test looks good to me. I ran the test locally and it passed with no error thrown. Nice work!
CleanShot 2023-10-31 at 20 11 24

**Review by sahilpatel18 — APPROVED** [review]
All test cases have passed successfully, great job!  

Screenshot 2023-10-31 at 11 33 54 PM

**Review by DavidC0126 — APPROVED** [review]
Hi @eduhorta I tested the PR and it works as intended!
Screenshot 2023-10-31 at 10 30 38 PM

**Review by wantingxu7 — APPROVED** [review]
Got "PASS" after running tests. Good work!

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Review by Jiyuanxia — APPROVED** [review]
Hi @eduhorta , I have reviewed your pull request and tested it. It works as you intended. Good job!
Screenshot 2023-11-02 134052

**Review by Chuehleo — APPROVED** [review]
Everything works as expected, great job!
Screenshot 2023-11-02 163659

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
