### PR TITLE
shefali-Unit-Test-TeamReport-selectors

### PR DESCRIPTION
**Pull request by SMitta11**
# Description

Unit test for src/components/Reports/TeamReport/selectors.js

Created test cases for selectors.js
selectors.test.js file created and added test cases in it.

- should return the team data from state
- should return an empty object if team data is not present in state

## How to test:
1. check into current branch
2. npm install
3. run below command:
Screen Shot 2024-09-20 at 5 49 40 PM

## Screenshots of changes:
Screen Shot 2024-09-19 at 7 35 21 PM

### CODE REVIEW

**Comment by geetamatkar** [comment]
Hi @SMitta11 ,
I tested this PR and I'm getting following error.

PR2697

**Review by RishithaMamidala — CHANGES_REQUESTED** [review]
@SMitta11 
The PR passes all the test cases but there is a error in the instructions.
It should be 
npm test src/components/Reports/TeamReport/__tests__/selectors.test.js
instead of 
npm test src/components/Reports/TeamReport/tests/selectors.test.js
so, please correct the instructions
PR 2697

**Review by Lexie5212 — CHANGES_REQUESTED** [review]
Hi, I have tested the PR, and there is error. Test failed.

Screenshot 2024-09-19 at 21 29 28

**Review by Watchdog00 — APPROVED** [review]
I have completed the testing and got the expected results. Good job!

**Review by ashmita123 — APPROVED** [review]
The test cases are passing.
Screenshot 2024-09-20 at 12 59 30 PM

**Review by manikittu810 — APPROVED** [review]
Hello @SMitta11 
Everything is working as mentioned. But there's a slight change that needed to be addressed, there's a mistake in the path mentioned i.e., 

Screenshot 2024-09-20 at 3 44 38 PM

If every reviewer run(s) this command, they can pass the test cases.
Here are the tests passing : 
Screenshot 2024-09-20 at 3 42 21 PM


Thank you

**Comment by SMitta11** [comment]
Please use updated command, there was some mistake in giving the command, I have added a screenshot, please use that to run the tests.

**Review by jinxyou — APPROVED** [review]
image
All test passed. Great work!

**Review by linkhanthtel — APPROVED** [review]
Test cases passed as expected! Nice work!

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the test cases are passing.
Screenshot 2024-09-21 at 7 14 32 AM

**Review by mohangadde1 — APPROVED** [review]
image
Test cases have been verified and passed

**Review by panchalvatneu — APPROVED** [review]
test passes but possibly include a test for when state doesn't contain a team field to ensure it behaves as expected in such cases
image

**Comment by mianmiantea2019** [comment]
Test cases have been verified and passed. 

image

**Review by Lexie5212 — APPROVED** [review]
Hi, I tested the PR again following the instructions. All tests passed! 
Screenshot 2024-09-23 at 17 48 57

**Comment by tharunaa-1** [comment]
The test cases passed.

image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (206)

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture2697

**Review by Gauravmg6 — APPROVED** [review]
All the test cases are passing. Change the command mentioned in the instructions. It should be, npm test src/components/Reports/TeamReport/__tests__/selectors.test.js
Screenshot 2024-09-29 125622

**Review by ptrpengdev — APPROVED** [review]
All tests passed.
Screenshot 2024-10-05 at 10 44 08 PM

**Review by ziyanw52 — APPROVED** [review]
I have tested this PR and all the test suites passed.
981728190448_ pic_hd

**Review by slidracoon72 — APPROVED** [review]
#2697 
@SMitta11 
I have test the PR and it passes all test cases.

Screenshot 2024-10-24 at 3 06 00 PM

**Review by SharadhaS24 — APPROVED** [review]
I have tested this PR, and it is functioning as expected.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
