### PR TITLE
Lucile T make cursor start in fields second part

### PR DESCRIPTION
**Pull request by LucileTech**
# Description 
(PRIORITY LOW) 
I’d like to have the cursor start in the available fields so it is more efficient when using these pages. Modals with individual empty fields automatically put the cursor in the empty field, so I can immediately start typing rather than having to manually put the cursor in the field and then do my typing. 

Make cursor start in fields on : 
Other Links → User Management → Set Final Date
Other Links → User Management → Reset Password
Other Links → Badge Management
Other Links → Projects → click WBS icon
Other Links → Teams → click Members icon
Other Links → Teams → Create New Team
Other Links → Popup Management

## Main changes explained:
- Autofocus was added on inputs 

## How to test:
1. git checkout Lucile_T_make_cursor_start_in_fields_second_part
2. git pull
3. `npm install` and `npm run start:local` to run this PR locally
4. log as admin user
5. go to dashboard→ 
Other Links → User Management → Set Final Date
Other Links → User Management → Reset Password (If reset password unusable, the problem is on Development too)
Other Links → Badge Management
Other Links → Projects → click WBS icon
Other Links → Teams → click Members icon
Other Links → Teams → Create New Team
Other Links → Popup Management

## Screenshots :
Screenshot 2023-07-31 at 10 38 31
Screenshot 2023-07-31 at 10 55 28
Screenshot 2023-07-31 at 10 56 21
Screenshot 2023-07-31 at 10 56 37
Screenshot 2023-07-31 at 10 56 55
Screenshot 2023-07-31 at 10 57 12

### CODE REVIEW

**Review by Indujaks — DISMISSED** [review]
Tested your changes for all the below steps:
Other Links → User Management → Set Final Date
Other Links → User Management → Reset Password (If reset password unusable, the problem is on Development too)
Other Links → Projects → click WBS icon
Other Links → Teams → click Members icon
Other Links → Teams → Create New Team
Other Links → Popup Management

It works as expected for all except  "Other Links → Badge Management"
Screenshot 2023-07-31 at 2 59 26 PM

**Review by TheDescendant39 — COMMENTED** [review]
Hi, @LucileTech I reviewed your changes and checked all the cases you mentioned above. Everything works as intended except the autofocus on the first name in "Badge Management". 
*Please see the attached video below:*

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47534216/981df3f2-54f7-464b-be45-b3169ad0e7c2

- Autofocus only works after refreshing the page and not the first time it is rendered. 
- @Indujaks Has already requested a change regarding this so I am only leaving a comment.

**Comment by LucileTech** [comment]
> Tested your changes for all the below steps: Other Links → User Management → Set Final Date Other Links → User Management → Reset Password (If reset password unusable, the problem is on Development too) Other Links → Projects → click WBS icon Other Links → Teams → click Members icon Other Links → Teams → Create New Team Other Links → Popup Management
> 
> It works as expected for all except "Other Links → Badge Management" Screenshot 2023-07-31 at 2 59 26 PM

Thank you, I fixed it, it should work without reloading the page now.

**Comment by LucileTech** [comment]
> Hi, @LucileTech I reviewed your changes and checked all the cases you mentioned above. Everything works as intended except the autofocus on the first name in "Badge Management". _Please see the attached video below:_
> 
>  Screen.Recording.2023-07-31.at.5.15.15.PM.mov 
> * Autofocus only works after refreshing the page and not the first time it is rendered.
> * @Indujaks Has already requested a change regarding this so I am only leaving a comment.

Thank you! I fixed it in the last commit, it should work without refreshing the page now.

**Review by sxiong5 — APPROVED** [review]
The PR worked as expected!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/38602e19-ad7d-4549-80e2-4215c2d3ef61

**Comment by iTvX** [comment]
I have tested your pr, and no bugs found it.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/2c63326e-8c2e-4e72-acbb-afc2bb8f921e

**Review by zuhang2000 — APPROVED** [review]
Hi I've tested your PR. All cases are working as expected! Good Job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123051008/7f455446-a7fd-43a7-afcb-17458588e2ae

**Review by veronicacheng2 — APPROVED** [review]
Hi @LucileTech, I have tested the PR and everything works perfectly, the cursor starts automatically as soon as I navigate to these pages as stated

Other Links → User Management → Set Final Date:
image

Other Links → User Management → Reset Password
image

Other Links → Badge Management
image

Other Links → Projects → click WBS icon
image


Other Links → Teams → click Members icon
image



Other Links → Teams → Create New Team
image


Other Links → Popup Management
image

**Review by yurisokolovicz — APPROVED** [review]
Hi @LucileTech 
I have reviewed all the scenarios you mentioned. This is working perfectly fine for me in the Admin account, including all the fields. Great job! Please take a look at the video below.

Make cursor start in fields on :
Other Links → User Management → Set Final Date
Other Links → User Management → Reset Password
Other Links → Badge Management
Other Links → Projects → click WBS icon
Other Links → Teams → click Members icon
Other Links → Teams → Create New Team
Other Links → Popup Management


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/7b5dfb5b-750e-4f63-9d29-e0f6ad065357

**Comment by Lin1404** [comment]
Hi @LucileTech , I have tested your PR and the it works well in all the scenarios you mentioned.

Other Links → User Management → Set Final Date
image


Other Links → User Management → Reset Password (If reset password unusable, the problem is on Development too)
image


Other Links → Badge Management
image


Other Links → Projects → click WBS icon
image


Other Links → Teams → click Members icon
image


Other Links → Teams → Create New Team
image


Other Links → Popup Management
image

**Review by Lin1404 — APPROVED** [review]

**Review by navneeeth — APPROVED** [review]
LGTM!

Logged in as an admin user and tested the following navigations and the cursor starts in the available fields as expected: 

Other Links → User Management → Set Final Date
Other Links → User Management → Reset Password
Other Links → Badge Management
Other Links → Projects → click WBS icon
Other Links → Teams → click Members icon
Other Links → Teams → Create New Team
Other Links → Popup Management

Good use of autofocus!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44264834/4e4e7409-62b5-41d8-9a6a-343319c3ca6e

**Comment by one-community** [comment]
Thank you all, moving to final review!

**Review by cvtqx — APPROVED** [review]
Everything works as described.
Other Links → User Management → Set Final Date


Other Links → User Management → Reset Password


Other Links → Badge Management


Other Links → Projects → click WBS icon


Other Links → Teams → click Members icon


Other Links → Teams → Create New Team


Other Links → Popup Management

**Review by EdwinLauM — APPROVED** [review]
Hey @LucileTech, everything works as expected! Good job!

Set Final Date:

Screen Shot 2023-08-09 at 1 13 30 PM

Reset Password:

Screen Shot 2023-08-09 at 1 15 25 PM

Badge Management:

Screen Shot 2023-08-09 at 1 15 33 PM

WBS Icon:

Screen Shot 2023-08-09 at 1 15 45 PM

Members Icon:

Screen Shot 2023-08-09 at 1 15 56 PM

Create New Team:

Screen Shot 2023-08-09 at 1 16 05 PM

Popup Management:

Screen Shot 2023-08-09 at 1 16 12 PM

**Review by ThapeloMasasa — APPROVED** [review]
The Changes work as intended 
Screenshot 2023-08-09 at 1 24 46 PM
Screenshot 2023-08-09 at 1 31 57 PM
Screenshot 2023-08-09 at 1 32 33 PM

Screenshot 2023-08-09 at 1 33 05 PM
Screenshot 2023-08-09 at 1 33 43 PM



Screenshot 2023-08-09 at 1 34 30 PM

**Comment by one-community** [comment]
Thank you all, merged!

**Pull request merged**
