### PR TITLE
Induja Fix regular expression for Google doc and media url

### PR DESCRIPTION
**Pull request by Indujaks**
# Description
Screenshot 2023-09-19 at 9 43 32 PM

## Main changes explained:
added a step to trim url before validating the expression.
…

## How to test:
1. check into current branch
2. do npm install and ... to run this PR locally
3. log as admin user
4. Navigate to: Dashboard → Other Links → User Management → Create New User.
5. Fill in user details as per instructions.
6. Verify Admin Document and Media Folder accept valid links with space character

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/11251850/85a6e2fe-1690-4d79-b056-c9dd52494a36

### CODE REVIEW

**Review by eduhorta — DISMISSED** [review]
Working as expected 👍 

image
image

**Comment by beblicarl** [comment]
This functionality works as seen in the video below. However, there seem to be issues with the summary bar

[screencast-hgnapplication_react_beta.surge.sh-2023.09.20-15_41_17.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/5b1c2301-a72b-437f-8377-23e98300ac2d)

###  Summary bar

image

**Review by iTvX — CHANGES_REQUESTED** [review]
The summary bar doesn't show properly, The PR itself works fine.:
CleanShot 2023-09-20 at 12 06 48@2x

**Comment by dah00** [comment]
Hey, the PR works as intended; both the Admin Document field and Media Folder field accept valid links with space characters. However, the summary bar isn't displaying its content
PR1324_Linked_created
PR1324_Links_with_spaces
PR1324_missing_badges
PR1324_user_profile_created

**Review by wantingxu7 — DISMISSED** [review]
Hi, I've logged in as Admin and tried to create a new user but came across an error. Please find the recording of this:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105323719/47b0800a-3f1a-46d2-9546-9cea17914dff

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
I'm unable to update the Drop Box URL in the user profile edit links section despite my excessive whitespace at the end dropbox url being approved during user creation. In addition, the State seems like it should refresh to not show errors when the links are empty.

Might I suggest instead trying this:
   `export const isValidGoogleDocsUrl = url => {`
        `url = url.trim()`
        `  const googleDocsPattern = /^https:\/\/docs\.google\.com\/document\/d\/[a-zA-Z0-9_-]+\/edit(?:\?.*)?$/;`
        `return googleDocsPattern.test(url); `
        `};`
        
This way you don't have to complicate things with more regex. Your old solution worked just fine and it seems easier to just get rid of the whitespace with the built in trim method. Jay's copy and paste should work just fine with that too

Haven't tested it myself, so I could be totally wrong

Screenshot 2023-09-20 at 3 05 52 PM

Screenshot 2023-09-20 at 3 09 12 PM

**Review by Bhagyashree444 — COMMENTED** [review]
Good work Induja, I'm able to create a new user , however while adding google doc link and media link  it accepts several spaces instead of just one space.

PR#1324
PR #1324

**Comment by Indujaks** [comment]
> I'm unable to update the Drop Box URL in the user profile edit links section despite my excessive whitespace at the end dropbox url being approved during user creation. In addition, the State seems like it should refresh to not show errors when the links are empty.
> 
> Might I suggest instead trying this: `export const isValidGoogleDocsUrl = url => {` `url = url.trim()` ` const googleDocsPattern = /^https:\/\/docs\.google\.com\/document\/d\/[a-zA-Z0-9_-]+\/edit(?:\?.*)?$/;` `return googleDocsPattern.test(url); ` `};`
> 
> This way you don't have to complicate things with more regex. Your old solution worked just fine and it seems easier to just get rid of the whitespace with the built in trim method. Jay's copy and paste should work just fine with that too
> 
> Haven't tested it myself, so I could be totally wrong. I also have the weird bar thing that everyone else is experiencing, but you didn't touch any of that code, so it might just be the frontend you built this fix off of.
> 
> Screenshot 2023-09-20 at 3 05 52 PM
> 
> Screenshot 2023-09-20 at 3 09 12 PM

Thank you for the suggestion, updated accordingly! Please review.

**Comment by Indujaks** [comment]
> Good work Induja, I'm able to create a new user , however while adding google doc link and media link it accepts several spaces instead of just one space.
> 
> PR#1324 PR #1324

It should be able to accept any number of spaces.

**Comment by Indujaks** [comment]
> Hi, I've logged in as Admin and tried to create a new user but came across an error. Please find the recording of this:
> 
>  PR.1324.mp4

Please pull latest changes to validate this, error seems to be different

**Comment by DavidC0126** [comment]
Hi @Indujaks I tested the PR and it works as intended, however, I encountered disappeared dashboard icons problem as well.

profile

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/1887795c-35c0-4897-a214-208e25e5ffbd

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
So I tried testing everything again. Noticed there may have some conflicting variables in EditLinkModal.jsx. I was trying to console.log the before and after of the urls, but couldn't access the drop box one in the console.

You import {IsValidUrl} inside EditLinkModal.jsx, but also declare an arrow function within that component called IsValidUrl. This is causing the IsValidUrl in your checkValidURLs file to not be called, but rather the one declared within the file that isn't updated.

I would suggest clearing that up, and then I'll give another re-review. Might be worth double checking these files that have these url validators in them to ensure more local regex checks aren't bypassing the new ones in utils.

Btw, it would also be better inside the checkValidURL.js inside the isValidUrl arrow function to use "const" instead of var just as best practice. we don't need urlPattern to be hoisted inside the application therefore const is better.
pr1324 not accessed isvalidurl
pr1324 locally declared isvalidurl accessed instead

**Comment by Jiyuanxia** [comment]
Hi @Indujaks , I have reviewed your pull request and tested it. Urls are accepted with space in both ends. But when I was creating a new user, some error messages appear in my console.

Screenshot 2023-09-21 175523

Screenshot 2023-09-21 175834

Error messages
Screenshot 2023-09-21 175728

**Comment by astrjc0326** [comment]
I tested with a blank at the end of the URL, and it worked perfectly. But the dashboard icons were disappeared as well.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/98345990/e4f53e05-0306-4ef3-9527-56c9de7ad44a

**Review by Haoj1 — COMMENTED** [review]
@Indujaks The regex works perfect but I have the same issues with the summary display

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/c4691cb0-b896-4968-8209-ee3ed3873a6b

**Comment by Indujaks** [comment]
> So I tried testing everything again. Noticed there may have some conflicting variables in EditLinkModal.jsx. I was trying to console.log the before and after of the urls, but couldn't access the drop box one in the console.
> 
> Your import {IsValidUrl} inside EditLinkModal.jsx, but there's also an arrow function declared within that component called IsValidUrl. This is causing the IsValidUrl in your checkValidURLs file to not be called, and instead the one declared within the file that isn't updated.
> 
> I would suggest clearing that up, and then I'll give another re-review. Might be worth double checking these files that have these url validators in them to ensure more local regex checks aren't bypassing the new ones in utils.
> 
> Btw, it would also be better inside the checkValidURL.js inside the isValidUrl arrow function to use "const" instead of var just as best practice. we don't need urlPattern to be hoisted inside the application therefore const is better. pr1324 not accessed isvalidurl pr1324 locally declared isvalidurl accessed instead

Updated the url name

**Review by JeffLi117 — DISMISSED** [review]
I am able to create a new user with single or multiple spaces at the end of the "Admin Document" or "Link to Media Files" links. Works as intended.

image
image

**Review by zuhang2000 — COMMENTED** [review]
Hi I've tested your PR following your instructions. The functionality is working working as expected. However, the badges on dashboard are incorrectly displaying. There is an error with that please check about it. I can successfully add spaces after url.
Screenshot 2023-09-23 at 7 34 55 PM

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
So they've got me looking a little deeper into things now. Sorry for all the new things that keep popping up that I find lol. That's just kinda how things go, but you're spot on with the regex for those links now.

Fixes that needed to be implemented on this:
   - sanitize the data on the frontend before the async request is done that creates/updates a user and their links. This can be done in the following manner by adding the .trim(). You could even trim it before it's sent to regex validators you've made it you want to lessen the overall code that's written. This sanitization needs to be done on every url that's submitted. This is also an issue in the backend, but that's a problem for someone else to deal with.
   
   unsanitized:
pr1324 unsanitized

 sanitized:
pr1324 santitized

  - I'm also getting this visual error whenever I've successfully created a new user. I didn't look too much into this one since I'm not as familiar with this part of the code base. It triggered when adding a user with urls with no whitespace and also when making users with excessive whitespace.
pr1324 error when making new user successfully

**Comment by Indujaks** [comment]
> So they've got me looking a little deeper into things now. Sorry for all the new things that keep popping up that I find lol. That's just kinda how things go, but you're spot on with the regex for those links now.
> 
> Fixes that needed to be implemented on this:
> 
> * sanitize the data on the frontend before the async request is done that creates/updates a user and their links. This can be done in the following manner by adding the .trim(). You could even trim it before it's sent to regex validators you've made it you want to lessen the overall code that's written. This sanitization needs to be done on every url that's submitted. This is also an issue in the backend, but that's a problem for someone else to deal with.
> 
> unsanitized: pr1324 unsanitized
> 
> sanitized: pr1324 santitized
> 
> * I'm also getting this visual error whenever I've successfully created a new user. I didn't look too much into this one since I'm not as familiar with this part of the code base. It triggered when adding a user with urls with no whitespace and also when making users with excessive whitespace.
>   pr1324 error when making new user successfully
> * That weird icon malfunction is still there as well, but I know you didn't actually touch that. It might be worth considering just doing these changes on a new pull request off a recently updated branch, so that doesn't get merged over accidentally. I could be wrong on this though, so I'd wait for someone else's input too.
> 
> pr1324 badge error

Updated the code with sanitized version and rebased the changes to avoid missing summary bar icons!

**Review by KurtisIvey — CHANGES_REQUESTED** [review]
Good job on sanitizing the URLs as they're entered in the database. 

I'm still receiving the error as shown here despite my new user being created successfully:
pr1324 media folder link error still there
I dug into the issue a bit and it seems like it's comparing two things that either don't exist or are undefined and indicated by the useEffect that I initiated upon render of the page.
pr1324 mediaurl and mediafolder link

You can see that isDifferentMediaUrl is called and triggers that visual error, but it's use case is not up to date with the rest of the code on the page anymore. This has to be corrected since it's part of  the URL visual validation on the front end for users.
Screenshot 2023-09-28 at 4 26 41 PM


This issue is still here too:
Screenshot 2023-09-28 at 4 16 08 PM

This is the user that I created:
pr1324 user

**Comment by Indujaks** [comment]
> Good job on sanitizing the URLs as they're entered in the database.
> 
> I'm still receiving the error as shown here despite my new user being created successfully: pr1324 media folder link error still there I dug into the issue a bit and it seems like it's comparing two things that either don't exist or are undefined and indicated by the useEffect that I initiated upon render of the page. Screenshot 2023-09-28 at 4 52 02 PM
> 
> You can see that isDifferentMediaUrl is called and triggers that visual error, but it's use case is not up to date with the rest of the code on the page anymore. This has to be corrected since it's part of the URL visual validation on the front end for users. Screenshot 2023-09-28 at 4 26 41 PM
> 
> IsDifferentMediaUrl needs to be updated with the following code: Screenshot 2023-09-28 at 4 53 17 PM
> 
> This issue is still here too: Screenshot 2023-09-28 at 4 16 08 PM

Resolved the error

**Review by KurtisIvey — APPROVED** [review]
Good to go 👍🏻 Nice job getting all the stuff implemented properly. I know this definitely went a little farther than originally expected with the extra changes. 

visual error fixed:
pr1324 finally good to merge

editlink modal no longer showing err on url due to code fix:
pr1324 visual error no longer present with isdifferentmediaurl code change

**Pull request merged**
