### PR TITLE
Jonathan - Add Edit Weekly Summary Options to Permissions

### PR DESCRIPTION
**Pull request by jonathancarpena**
# Description
Edit Weekly Summaries Options

## Related PRS (if any):
This frontend PR is related to the [#970](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/970)

## Main changes explained:
- Added Edit Weekly Summary Options under the roles in UserRoleTab.jsx

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Log as Owner user
4. Other Links → Permissions Management → Manage User’s Permissions
5. Verify that "Edit Weekly Summary Options" is being displayed.

## Screenshots or videos of changes:
Screenshot

### CODE REVIEW

**Review by luisarevalo21 — APPROVED** [review]
Hello [jonathancarpena](https://github.com/jonathancarpena),
Screenshot 2023-07-10 at 7 56 05 PM

I test your PR and works as intended. I am able to see "Edit Weekly Summary Options" via the owner and admin accounts. 
I can also add that privilege to other accounts.
Great work!

I do have one question though. What exactly does the privilege do? I added the privilege to my volunteer account but wasn't sure how to test it if I have that permission. If you can enlighten me that would be great.

**Review by AaronPersaud — APPROVED** [review]
I've tested and it looks good!

<b> Edit Weekly Summary Options in Permissions </b>

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/10265513/ba07eac7-a77e-483c-ac45-102436123450

- new permission appears in 'Manage User Permissions' dropdown

I'm curious, how come this PR adds the option but not the functionality? I'm guessing that's coming in a separate PR? Thanks.

**Review by BaileyM96 — APPROVED** [review]
Hello @jonathancarpena,

I have tested your changes and everything is working fine and looks great!

## Video Walkthrough

[Edit Weekly Summary Options.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108101478/bc045bbb-b3b4-452c-aa7e-f9c753989153)

**Comment by Lucas-E** [comment]
Great job everyone! Moving this one to final review!

**Comment by AnishPandita** [comment]
Hi @jonathancarpena, the PR works as intended. Looks great.
Screenshot 2023-07-11 at 7 56 17 PM

**Comment by igorrochadasilva** [comment]
Hi @jonathancarpena!

I logged as Owner and I had the access to "Manage User Permissions" button. Everything worked as well
Great job!

993_button_submit

993_button manager-user-permissions

Obs: This access is only for Owner ? or for Admin too?

**Review by xaanders — APPROVED** [review]
I've tested it. Logged in as an owner,
I can see a new permission in the bottom:
permission

**Review by NidaZaki — APPROVED** [review]

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @jonathancarpena. I have tested your PR and everything is working as intended. Great job! 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/3e441a41-51f4-4ed3-a578-fdfbe2b3f5aa

**Pull request merged**
