### PR TITLE
Vedant Fix project dashboard and add multi-select option

### PR DESCRIPTION
**Pull request by vedantg24**
# Description
Fixed the project dashboard by adding multi-select options for projects. Also, made the design of table better by making the scrollable region more clear

Screenshot 2024-10-25 at 10 24 11 PM

## Related PRS (if any):
This frontend PR is related to the development backend PR.

## Main changes explained:
- Update `ProjectsList.jsx` to include multi-select option and filter projects based on the selected projects
- Update styles in `BMDashboard.css`, `BMDashboard.jsx`, `ProjectSelectForm.jsx`

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to bmdashboard
6. select a few projects in the multi-select option
7. verify that the project list is filtered based on the projects selected.
8. verify that scrollable region is now more clear and visible

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/3e8202ea-1870-4994-9541-82f46c9a3137

### CODE REVIEW

**Review by samarth9201 — APPROVED** [review]
Verified the changes, the scrolling area is clearly visible and correct projects are displayed.

Screenshot (163)
Screenshot (164)
Screenshot (165)

**Review by Muhideenthegreat — COMMENTED** [review]
Verification:

- It's still a drop down but the multiselect option is now available
- Scrollable region is clear and the layout is much better

Suggested Improvements:

- The arrangement of the various buttons in the project dashboard can be better organized as they are currently disparse. 
- The button colors also need visual hierarchy. For example the "Create New Team" button's color doesn't clearly indicate it's a primary action

**Comment by vedantg24** [comment]
> Verification:
> 
> * It's still a drop down but the multiselect option is now available
> * Scrollable region is clear and the layout is much better
> 
> Screenshot 2024-10-26 at 11 30 15 AM
> Suggested Improvements:
> 
> * The arrangement of the various buttons in the project dashboard can be better organized as they are currently disparse.
> * The button colors also need visual hierarchy. For example the "Create New Team" button's color doesn't clearly indicate it's a primary action
> 
> Screenshot 2024-10-26 at 11 31 33 AM

@Muhideenthegreat  Thank you for your suggestions regarding the button arrangement and color hierarchy in the project dashboard. However, these improvements are out of scope for the current bug fix. We can consider these enhancements as a separate fix or improvement for future development.

**Comment by ShreyaLaheri** [comment]
Works as expected - however I couldn't switch from light mode to dark mode to test.
image

**Review by vijay10pk — APPROVED** [review]
Functionality is working as expected. But there are some UI issue in mobile view. let me know if it doesn't come under the scope of the task.
Screenshot 2024-10-28 at 11 05 50 PM
Screenshot 2024-10-28 at 11 05 16 PM

**Review by CodewithKoushica — CHANGES_REQUESTED** [review]
Thank you for your work on this PR! I noticed an issue with the UI responsiveness; the layout breaks on smaller screens. Please address this to ensure a better user experience across different device sizes.
Screenshot 2024-10-29 at 11 24 45 PM

**Review by hqzhu0913 — DISMISSED** [review]
The changes include the dropdown selections, and multiple select function. And if multiple choices are selected, items can be arranged accordingly.
Screenshot 2024-10-30 at 3 11 33 PM
Screenshot 2024-10-30 at 3 06 29 PM

**Comment by beblicarl** [comment]
This feature works as intended

[80cfb8ad-efa2-43dd-b4d1-c75a0e398bd7.webm](https://github.com/user-attachments/assets/378aabec-9c99-4a3d-90a1-45f5c41ee032)

**Review by beblicarl — DISMISSED** [review]

**Review by anirudhsk2107 — APPROVED** [review]
The for project list is working and is filtering result accordingly. 

Screen Shot 2024-11-01 at 12 56 32 PM 
Screen Shot 2024-11-01 at 12 56 17 PM

**Review by nikhilgiri0226 — APPROVED** [review]
Hi Vedant,

I have reviewed this PR and the Functionality is working as expected. The projects table is not wasting the free space now.

image


There were some issues with the mobile view. I can see that a part of the row was aligned outside the table but I believe that wasn't a part of this fix. So, overall it works fine.

image

**Review by varun-elango — APPROVED** [review]
The functionality is working as expected. The projects are filtered based on the projects selected and the scrollable region is clear and not wasting space. However on smaller screens, the rows which are longer than the size of the screen are not aligned properly. But approving the PR assuming that is not in the current scope of this PR.
PR2821_1
PR2821_2

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the multi-select feature works as expected and the screen is properly scrollable.

https://github.com/user-attachments/assets/bcd466e0-70b5-4ea3-8e6b-e3bc64af45e6

**Review by Rui-Liu-github — APPROVED** [review]
Hi, I reviewed the PR #2821 , selected a few projects in the multi-select option
1) I tested the project list is filtered based on the projects selected.
2) I tested that scrollable region is now more clear and visible.

image
image
image
image

**Review by CodewithKoushica — APPROVED** [review]
Everything works fine now. I checked the page with different dimensions. 
Screenshot 2024-11-14 at 9 40 57 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Review by NazaninHashemian — COMMENTED** [review]
I have checked out the current branch and installed the necessary dependencies with npm install.
I cleared the site data/cache to ensure there is no outdated content.
Logged in as an admin user successfully.
Navigated to the BM Dashboard and tested the multi-select option by selecting a few projects.
Verified that the project list is filtered correctly based on the selected projects.
Checked the scrollable region and confirmed that it is now more clear and visible.
I have reviewed all the code changes and comments, and everything seems in order.

**Comment by pallavithorat** [comment]
I have tested the PR by verifying the multi-select functionality and the filtered project list on the BM Dashboard.
The scrollable section is now more prominent, and all updates function seamlessly as intended.
Screenshot 2024-12-04 at 12 46 42 PM
Screenshot 2024-12-04 at 12 48 59 PM
Screenshot 2024-12-04 at 12 49 24 PM

**Pull request merged**
