### PR TITLE
Dev new max personal record badge

### PR DESCRIPTION
**Pull request by navyasrim**
New Max Personal Record Badge Needs to be Updated
Files modified :
src/components/Badge/Badge.css
Added lines 41 to 55 for Max personal badge css style and postion
src/components/Badge/BadgeImage.jsx
Line 18 added condition to display Css name based on badge type
src/components/UserProfile/Badge.css
Added lines 49 to 62 for Max personal badge css style and postion
src/components/UserProfile/BadgeImage.jsx
Line 18 added condition to display Css name based on badge type

I made .CSS file changes for displaying the badge number of hours position as per the requirement
Also implemented the logic to display style based on badge condition like personal Max badge or other badge in css display.
As per Jae requirement I also adjusted the sizing of the badge number so i just changed the pixel ,font in other css method.
Badge_SizeAdjustment

### CODE REVIEW

**Review by KitanGarcia — APPROVED** [review]
Just tested it and looked over the code, and it looks good!

**Review by pranav1416 — APPROVED** [review]
Everything looks good with the new changes, however, I see changes related to your previous PR #336 here. Please make sure you don't merge them with this PR and keep them separate.

**Comment by navyasrim** [comment]
I am closing this PR and raising as a NEW PR  with Rebase...

**Comment by rauleffting** [comment]
Reviewed yesterday to help Yiyun figure out what was happening. PR is working, but we need to change the .env file on deployment.

**Pull request closed without merging**
