### PR TITLE
Shiwani Role Permissions unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/PermissionsManagement/RolePermissions.jsx`

## Main changes explained:
- Added 10 test cases: check if role name is displaying properly, check if permission list header is displaying as expected, check if presets option do not show when the role is not Owner, check if clicking on Create New Preset displays toast success message when the post request is successful, check if clicking on Create New Preset displays toast error message when the post request fails, check if clicking on Load Presets opens modal, check save button toast success message, check delete role button works as expected, check if delete role modal content displays as expected, check if edit role modal content displays as expected 

## How to test:
1. check into current branch
2. do `npm test src/components/PermissionsManagement/__tests__/RolePermissions.test.js` 
3. check if all the test cases pass without any error or warning

## Screenshots or videos of changes:
Screenshot 2024-04-11 at 2 09 10 AM

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected! Nice work!

**Review by aaryaneil — APPROVED** [review]
All the test cases passed. Good work.
Screenshot 2024-04-11 at 12 27 01 PM

**Comment by alla0810** [comment]
all tests passed successfully.  Great work.

**Review by AaronPersaud — APPROVED** [review]
Hi @Shiwani99, I've tested and all cases passed. Well done!

image

**Comment by iTvX** [comment]
Good work! Your unit test seems good.

2024-04-13 at 19 23 47@2x

**Review by hbodgal — APPROVED** [review]
image


All tests passed.

**Review by curiousfancier — APPROVED** [review]
All test cases worked successfully
review_2141

**Review by dkt6 — APPROVED** [review]
All test cases are working as expected! LGTM

RolePermissionsUnitTest

**Review by KurtisIvey — APPROVED** [review]
You've got great test coverage that seems to handle all scenarios that the component would be used under. You've made sure to test both success and failure conditions. Fantastic job!

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
