### PR TITLE
Shihao - BadgeImage Unit Test

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Unite test for `BadgeImage.jsx`

## Main changes explained:
- Add the unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test BadgeImage.test.js` to run the test
4. Verify that all 4 tests have passed

## Screenshots or videos of changes:
Screenshot 2023-11-30 at 15 12 18

### CODE REVIEW

**Review by sahilpatel18 — DISMISSED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-01 at 2 27 06 PM

**Comment by Cavein254** [comment]
Hi @sxiong5, your tests are running as expected
Screenshot from 2023-12-02 22-19-23

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 14 - PR6

**Review by scoopstroop92 — DISMISSED** [review]
hello @shihao good job on the test cases 
image

**Comment by DragonSlayer2401** [comment]
I tested your PR and all of the tests worked as expected. Please watch my below overview video for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/3bf0a1d2-18af-4b1b-95db-93633d838b6e

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-18 at 10 42 05 PM
All tests have passed successfully. Excellent job!

**Comment by beblicarl** [comment]
All tests passed

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
