### PR TITLE
Shiwani TimeEntriesViz unit test

### PR DESCRIPTION
**Pull request by Shiwani99**
# Description
Unit test for `src/components/Reports/TimeEntriesViz.jsx`

## Main changes explained:
- Added 8 test cases: check if component renders properly without crashing, check if Show Time Entries Graph button is shown when show is set to false, check if Hide Time Entries Graph button is not shown when show is set to false, check if Hide Time Entries Graph button is shown when show is set to true, check if Show Time Entries Graph button is not shown when show is set to true, check if Total Hours displays 0 when period key is not present in timeEntries, check if Total Hours displays as expected when period key is present, check if Labels Off, Show Daily Hours, Show Dates button are present when show is set to false 

## How to test:
1. check into current branch
2. do `npm test src/components/Reports/__tests__/TimeEntriesViz.test.js` 
3. check if all the test cases passes without any errors or warnings.

## Screenshots or videos of changes:
Screenshot 2024-06-06 at 12 05 20 AM

### CODE REVIEW

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I tested your PR and it passed all the test cases. Please refer the screenshot attached.
PR 2321

**Review by Kavil-Jain-514 — APPROVED** [review]
All test cases have passed without any error or warning.
image

**Review by deepthikannan — APPROVED** [review]
image
All test cases passed.

**Review by shradac — APPROVED** [review]
All tests passed. The tests cover all specified scenarios. Good Work!

week1-16

**Comment by beblicarl** [comment]
All tests passed. Test cases cover all specified scenarios 

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
