### PR TITLE
Tapan Fixed the Pagination UI in Members Table for Project Reports

### PR DESCRIPTION
**Pull request by TapanPathak**
# Description
Screenshot 2024-04-26 at 4 45 30 PM

Pagination Overlaps with table values. 

## Related PRS (if any):
N/A
…

## Main changes explained:
- Fixed UI for handling overlap of pagination and table values
- Fixed CSS styling for responsiveness 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user
5. Go to Reports -> Projects -> Any project with 7 or more members
6. Make Screen Smaller
7. Check that pagination doesn't overlaps with table values

## Screenshots or videos of changes:

Before - 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/15e5ec5c-235b-4ece-b1ed-0bbaa775f5b8

After - 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/73526712/f67c176e-af26-4a60-873b-c95ffea8a76d

### CODE REVIEW

**Review by linkhanthtel — APPROVED** [review]
There is no pagination overlapping in project members table. Nice work!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95618937/b1513faa-9d65-472a-876d-3c150d375563

**Review by aaryaneil — APPROVED** [review]
Tested the PR and the pagination doesn't overlap when the screen size is reduced.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39597927/e4d9af71-5085-4e61-a954-4b5ec0a93336

**Review by MinSun0814 — APPROVED** [review]
There is no overlapping when resizing the window now.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/5105910a-0877-4b9c-afd4-637e10ce8d3a

**Review by TareqMia — APPROVED** [review]
Changes look good and there is no overlap when making the screen size smaller 👍 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/84e26ae8-8ad8-49a5-aeb2-bbb874c867e9

**Review by peter6866 — APPROVED** [review]
Hi, I have reviewed your PR and it works with smaller screen sizes. 
image
image

**Comment by FayeLV** [comment]
Hi,
Great job! I tested the PR, and the overlap issue is resolved. I also tested it on smaller screen sizes, and the changes work as expected.
PR 2525
Snipaste_2024-09-07_21-32-35
Snipaste_2024-09-07_21-32-55

**Pull request merged**
