### PR TITLE
Shuhua - create different view for !summary

### PR DESCRIPTION
**Pull request by Shuhua-L**
# Description
task-description

## Related PRS (if any):
N/A

## Main changes explained:
- Update the file **`src/components/SummaryBar/SummaryBar.jsx`** to incorporate a different view for users exempt from summary submission

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Verify that Mentor users see the desired view, and summary submission function still works
  4.1. Log in as a Mentor user, and confirm that the !summary view meets the expectations
  4.2. Click the text “You don’t need to …” to submit a summary
5. Verify that the view updates properly as summary requirements change
  5.1. Log in as an Admin user, and verify that the Summary Bar shows the default view
  5.2. Change the Weekly Summary requirement: Go to View Profile → Volunteering Times tab, set "**Weekly Summary Options**" to "**Not Required**", and save the change
  5.3. Go back to the Dashboard and verify the updated view
  5.4. (Optional) Toggle the "**Weekly Summary Options**" back and see the updated view
6. (Optional) Verify step 5 with a user other than Mentor/Admin

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83729360/f3ee7431-45c2-4892-bc1a-f90ca15803da

## Note:
1. Use a backslash to escape `!` if you switch branches in the terminal: 
  `git checkout -b Shuhua-create-different-view-\!summary`
2. These 400 bad request errors with the message “MongoError: QueryExceededMemoryLimitNoDiskUseAllowed” exist on the `dev` branch and are unrelated to the SummaryBar component

error-messages

### CODE REVIEW

**Review by eduhorta — DISMISSED** [review]
Hi there, @Shuhua-L 

I did test your PR and everything is working as expected!
Here is a video:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/c6bddf04-ca55-41a8-8b09-7409d55f6374

Great job! 👍

**Comment by Shuhua-L** [comment]
> I tested your PR on both the Admin and Mentor account. The summary bar changes color as intended. I noticed, however, that after going to the summary page, you can't navigate back to the Dashboard. Please watch the overview video below for more details:
> 
>  2023-12-08.16-07-39.mov

@DragonSlayer2401 Thanks for reviewing! If by "navigate back to the Dashboard" you mean clicking the "Dashboard" in the navbar, then this is expected, since submitting a summary doesn't render a new page, just a new window/view within the Dashboard page. You can close the Weekly Summaries view by clicking the "Close the window" button or the text as shown below
how-to-close-the-window

**Review by Alforoan — DISMISSED** [review]
Everything worked well. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/7c4b2eb8-8d53-4120-b5f9-f3c4ae36f36b

**Review by pika-chu11 — APPROVED** [review]
Hi @Shuhua-L , I have tested you PR and it works as expected! Great job!

- Log in as Mentor/Accounts that "Not Required to submit a weekly summary"
    - I did see the text stating: "You don't need to..." and I was still able submit one when I clicked on it as expected.

- Log in as Admin with the Requirement for submitting Weekly summary
    - I did see that the text saying "You still need to complete the Weekly summary..." initially.
    - The text changed to "You don't need to ..." and the color of "! summary" became purple when I switch the option for not require submitting a summary under Profile -> Volunteering Times tabs.

- After submitting a summary, "! summary" section turned green as before.

PR 1652 - after submit


Please watch the video for the workflow.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/0eabdaa7-e49f-49ff-b460-48692cf5b92b

**Review by yvonnep165 — DISMISSED** [review]
Hi @Shuhua-L ,
I have tested your codes with the mentor and admin accounts and everything works as expected. Nice work!

with mentor account:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/820af726-466d-4e99-af9f-1171b1341042

with admin account:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/d9941c79-28d8-45cf-9f01-c3066f14627e

**Review by Renanluizssx — DISMISSED** [review]
Hi @Shuhua-L, i tested your application and it's running correctly:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/346fbfb7-af64-4221-8519-797b8ee30953

**Pull request closed without merging**
