### PR TITLE
Aaryaneil - Added test cases for AddTeamsAutoComplete

### PR DESCRIPTION
**Pull request by aaryaneil**
# Description

Unit tests for `src/components/UserProfile/TeamsAndProjects/AddTeamsAutoComplete.jsx`

## Related PRS (if any):
Updated PR from #1914 

## Main changes explained:
Added test cases for the following:

1. Should not error out due to no tests (popper.js.js)
2. Renders without crashing
3. Dropdown does not show when `searchText` is empty
4. Dropdown shows when `searchText` is not empty
5. Input is auto-focused when component mounts
6. Filters team list case insensitively
7. Correctly handles special characters in search
8. Handles case when no teams are available
9. Renders input field
10. Selects a team from the dropdown
11. Creates a new team when no match is found

## How to test:
1. check into current branch
2. do `npm install` and `npm test AddTeamsAutoComplete.test.js`

## Screenshots or videos of changes:
Screenshot 2024-09-05 at 1 46 00 PM

### CODE REVIEW

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (190)

**Review by RishithaMamidala — APPROVED** [review]
@aaryaneil 
Reviewed the PR and code passes all the test cases.
PR 2646

**Review by AJAYINAVOLU — APPROVED** [review]
Tests are passing successfully.

image

Thank You

**Review by Saniya98 — APPROVED** [review]
All tests are passing.
image

Thank you

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and all test cases passed successfully!!!!

Screenshot 2024-09-06 150418

**Review by sri0606 — APPROVED** [review]
@aaryaneil , I have tested your PR and tests passed as expected.

Screenshot 2024-09-06 125237

**Review by CillianRen — APPROVED** [review]
Everything worked as expected. Great job!
image

**Review by jinxyou — APPROVED** [review]
image
All test cases have passed

**Review by panchalvatneu — APPROVED** [review]
All tests passed!
image
Here are some thoughts on improving your test suite for the `AddTeamsAutoComplete` component:

- **Error Handling:** For the test `handles case when no teams are available`, it looks like you’re checking for a `No teams found` message. If this message is supposed to be handled by a toast, make sure you’re verifying that the toast actually appears. Since you're mocking `react-toastify`, it’s important to ensure your test accounts for this.

- **Avoid Redundancy:** I noticed the `renders input field` test is duplicated. You can remove one of these to keep your test suite clean and avoid redundancy.

- **Use of `waitFor`:** When dealing with asynchronous behavior, like network requests or updates that might take some time, it’s a good idea to use `waitFor`. This helps in cases where elements might not appear immediately. For example, if the dropdown or toast takes a moment to show up, wrapping your assertions in `waitFor` will make your tests more reliable.

  ```javascript
  await waitFor(() => {
    expect(screen.getByText('Engineering')).toBeInTheDocument();
  });
  ```

- **Test Cleanup:** You’re already using `jest.clearAllMocks()` in `afterEach`, which is great. Just make sure any setup or teardown code is managed well to prevent test pollution.

- **User Feedback Testing:** Make sure your component provides feedback to users. For instance, if there are no matching teams, ensure that the component appropriately informs the user. Check scenarios where the user needs to know that their search didn’t return results.

- **Edge Cases:** It might be worth adding tests for edge cases, such as:
  - What happens if `teamsData` is `null` or `undefined`?
  - What if the `searchText` consists of special characters or spaces?

- **Mocking External Libraries:** Double-check that your mock for `react-toastify` is comprehensive and covers all scenarios that could impact the component’s behavior.

These tweaks should help make your tests more robust and maintainable. Let me know if you need any more help!

**Comment by mianmiantea2019** [comment]
All tests passed!

image

**Review by Gauravmg6 — APPROVED** [review]
All the test cases have passed. 
Screenshot 2024-09-08 020651

**Review by ddshah878 — APPROVED** [review]
I've tested the PR, and all the test cases have passed. Good job!

image

**Comment by beblicarl** [comment]
All tests passed successfully

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
