### PR TITLE
Niketha Anand- Rotate indefinitely after adding project

### PR DESCRIPTION
**Pull request by nikethaanand**
# Description
Fix creating new project setting the loading Indicator to rotate indefinitely.
(WIP Niketha)
Dashboard ->Otherlinks ->Projects
Create a New Project with selecting a category, It sets the loading Indicator to rotate indefinitely.
Please find the [video explanation link.](https://www.loom.com/share/ecab345beb374d74b7d93666084159e3?sid=f1c99746-bf8d-4633-8de4-e7b19924450c)

Fixes # ( priority low)
## Main changes explained:
- Update Addproject.js, Projects.js file

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Other Links → Projects
6. Type a new project name, select category and click + to create new project. 
7. The new project will load with a rotate button till the project is being created. After it has been created and added the type project name and the rotate button will be refreshed. The changes work both on light mode and dark mode.

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/26e50e2b-afe5-40cd-9977-1c2ed4d99ac5

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by Pranay-ai — APPROVED** [review]
Hey @nikethaanand 
The Pr is Working as intended too, please find the recording of the demo.

https://github.com/user-attachments/assets/b88f8b40-ad21-4466-a3c1-a80d399eaef3
Thank you.

**Review by kdaga81 — APPROVED** [review]
image

Functionality working as expected

**Review by kdaga81 — COMMENTED** [review]
image

When we are creating the new project and selecting the category, still there's a dropdown in the rows below (shouldn't it be the category we selected initially while creating the project). Please let me know if this is an expected behavior. Thanks!

**Review by Gauravmg6 — APPROVED** [review]
Works as expected.
Screenshot 2024-08-25 021121

**Review by RishithaMamidala — APPROVED** [review]
Works as expected
PR 2596

**Review by gowthamdongari — APPROVED** [review]
Hello Niketha,
I have revi

https://github.com/user-attachments/assets/22b132e3-c2ac-402e-b85e-347fa78d2b29

ewed this PR and it is working as expected.

**Review by AJAYINAVOLU — APPROVED** [review]
Changes are working as expected. 

PR 2596
PR 2596-1

Thank You

**Review by sam19981 — APPROVED** [review]
A new project is being created without getting stuck in an infinite loading screen.

Screenshot 2024-09-07 at 11 38 50 PM

https://github.com/user-attachments/assets/9fa97bdc-a82d-451b-8d08-15192e311492

**Review by Saniya98 — APPROVED** [review]
The changes are working fine for both light and dark mode 
image

image

**Review by mohangadde1 — APPROVED** [review]
image
changes works as expected

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
