### PR TITLE
Shrey add unit test cases for EffortBar

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for Timelog component EffortBar.jsx

## How to test:
1. check into current branch
2. do `npm install` 
3. npm run test EffortBar.test.js
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-12-08 at 11 46 12 PM

### CODE REVIEW

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 15 PR2

**Comment by DragonSlayer2401** [comment]
I tested your PR everything works as intended. Please watch the overview video for more details:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/aaa39512-be71-4d1a-bc68-107b3ab11889

**Review by Alforoan — APPROVED** [review]
All of them passed. Nice!
image

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work!
Screenshot 2023-12-09 at 12 57 58 AM

**Review by Hemsharavanan — APPROVED** [review]
- Your tests effectively validate the key functionalities of the EffortBar component.
- Refactoring to reduce redundant rendering and simplifying the mock data representation could further enhance the test suite's clarity and maintainability. 
- Good work overall!
PR #1654 Shrey add unit test cases for EffortBar

**Review by ZichanYang324 — APPROVED** [review]
I have run the test, and all the test cases passed!

Screenshot 2023-12-09 at 16 23 03

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-09 at 3 02 11 PM
Good job, @Shreyj14 ! All the test cases passed!

**Comment by Shreyj14** [comment]
@one-community this can be merged.

**Pull request merged**
