### PR TITLE
Shereen- Equipment List View Component

### PR DESCRIPTION
**Pull request by pshereen**
Created Equipment List View Component
Created URL for equipment List View
Created actions for Equipment List View

# Description
Created components for Equipment list view
Implements # (WBS) 9.1.1

## Related PRS (if any):
This frontend PR is related to the (https://github.com/OneCommunityGlobal/HGNRest/pull/992) backend PR.
To test this frontend PR you need to checkout the (https://github.com/OneCommunityGlobal/HGNRest/pull/992) backend PR.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. login as any user
5. Go to /bmdashboard (http://localhost:3000/bmdashboard) and log in again.
6. Navigate to [/bmdashboard/equipment] (http://localhost:3000/bmdashboard/equipment)
7. Verify all the table functionalities like open/close modals, sorting, and filtering for equipment view is working

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/7041610/914f2a4d-b04d-48ac-b91d-0f6fdec93b15

### CODE REVIEW

**Comment by Vijeth-V** [comment]
Hello Shereen,

I am working on the front-end and back-end PR branches that you mentioned. After logging in as an admin user, I was unable to fetch any equipment data. I also tried accessing the data with different volunteer accounts, but the issue persists. Could you please investigate this issue? I have attached a video for reference.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/8227941c-b933-4daf-8c22-36cf3d9bbfae

**Comment by jinxyou** [comment]
Hi, 
I have followed the steps you provided, and after several tries with different users, I'm still unable to fetch an equipment list. Can you please provide more details concerning how you fetch the list and what other steps are required?
Screenshot 2024-06-15 143204

**Review by Kavil-Jain-514 — COMMENTED** [review]
No data is available when routed to the equipment tab.
I added a video for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/4ffb2257-cace-4840-9cee-52f45c18f8b7

Thank you for your feedback.
Fixed the issue.
Kindly pull again and verify it.

**Review by aaryaneil — COMMENTED** [review]
I've reviewed the changes and left a review on the [backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/992#pullrequestreview-2121083905).

**Review by Logeshwari-Renu — CHANGES_REQUESTED** [review]
I have tested the PR and the page bmdashboard/equipment page table is empty. However the api "/api/bm/equipments" is successfully returning the response but the data is not getting rendered to the table.
Please look into the issue.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/166590596/cab29005-3b32-4ee0-9c3e-0d6bc64bc036

**Review by PabloWang — COMMENTED** [review]
Hi pshereen,

I followed the steps you listed but it's not data available on the equipment page.

image

**Comment by pshereen** [comment]
> Hello Shereen,
> 
> I am working on the front-end and back-end PR branches that you mentioned. After logging in as an admin user, I was unable to fetch any equipment data. I also tried accessing the data with different volunteer accounts, but the issue persists. Could you please investigate this issue? I have attached a video for reference.
> 
>  Screen.Recording.2024-06-14.at.10.46.54.PM.mov

Thank you for your feedback.
Fixed the issue.
Kindly verify again.

**Comment by pshereen** [comment]
> Hello Shereen,
> 
> I am working on the front-end and back-end PR branches that you mentioned. After logging in as an admin user, I was unable to fetch any equipment data. I also tried accessing the data with different volunteer accounts, but the issue persists. Could you please investigate this issue? I have attached a video for reference.
> 
>  Screen.Recording.2024-06-14.at.10.46.54.PM.mov



> No data is available when routed to the equipment tab. I added a video for your reference.
> 
>  PR.2359.mp4

Thank you for your feedback.
Fixed the issue.
Kindly verify again.

**Comment by pshereen** [comment]
> I've reviewed the changes and left a review on the [backend PR](https://github.com/OneCommunityGlobal/HGNRest/pull/992#pullrequestreview-2121083905).

Thank you for your feedback.
Fixed the issue.
Kindly verify again.

**Comment by pshereen** [comment]
> Hi pshereen,
> 
> I followed the steps you listed but it's not data available on the equipment page.
> 
> image

Thank you for your feedback.
Fixed the issue.
Kindly verify again.

**Comment by pshereen** [comment]
> I have tested the PR and the page bmdashboard/equipment page table is empty. However the api "/api/bm/equipments" is successfully returning the response but the data is not getting rendered to the table. Please look into the issue.
> 
>  2359.mp4

Thank you for your feedback.
Fixed the issue.
Kindly verify again.

**Review by Sarath-3119 — CHANGES_REQUESTED** [review]
Hi ,
I have pulled the right branches as mentioned but still the issue with equipments page seems to be persisting .
Kindly check!
image

**Review by vishavk1992 — CHANGES_REQUESTED** [review]
Hi Shreen, 
I have tested this PR with backend PR 992 and opened the page bmdashboard/equipment. The page table is empty. However the api "(http://localhost:4500/api/bm/equipments)" is not working and gives error 404 not found.
PR-2359+992

**Review by HowieMiao — DISMISSED** [review]
Seems like problems have been fixed, table, interactables and drop-down menus all work for me

image

**Comment by IchinnorovTuguldur** [comment]
Hello Shereen, I was not able to fetch the data and got 404 not found error. I am not sure if this is due to any permission. let me know if you have fixed the issue. I will debug on my end regarding permission as well.

Screenshot 2024-06-28 at 6 20 28 PM

**Review by pavanswaroopl — CHANGES_REQUESTED** [review]
Hello,

Great work, but I found a potential Filtering Issue, not sure whether it's an expected behavior, but they are:

1. When I select any equipment type, and then sort by name or project, all the projects with sorted results pop-up, I feel this step should show sorted results with the equipment type filter applied.
2. Similar one with project type.

Both of them were recorded in these videos, kindly check for them.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/dd680bc0-070d-4832-80d4-e679068af6f5


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/58074011/16c050af-40dc-4ff8-8ebf-9559b0a6c44d

**Review by nyelmela — DISMISSED** [review]
I tested the PR for the Equipment List View and verified that all functionalities are working correctly. This includes creating the Equipment List View component, URL, and actions like sorting, filtering.
image

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/123037122/5eecc091-e9b0-40e7-9be4-4df14ad9c98e

**Review by DiyaWadhwani — CHANGES_REQUESTED** [review]
Hi Shereen,

I tested out the changes as per your instructions.
I can see data on both /bmdashboard and on /bmdashboard/equipment.
Sorting the data based on 'Project' and 'Name' works fine, and I can filter data based on project and equipment as well.
However, filtering the data and then trying to sort based on Project and Name, is sorting all of the data and not the filtered data as you would expect.
I have dropped a video implementation. Kindly review this.
Thank you 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/72cd7268-2aad-4714-bf86-baf1f2c8b21d

**Comment by pshereen** [comment]
> Hi Shereen,
> 
> I tested out the changes as per your instructions. I can see data on both /bmdashboard and on /bmdashboard/equipment. Sorting the data based on 'Project' and 'Name' works fine, and I can filter data based on project and equipment as well. However, filtering the data and then trying to sort based on Project and Name, is sorting all of the data and not the filtered data as you would expect. I have dropped a video implementation. Kindly review this. Thank you
> 
>  992+2359.mp4

Hi Diya,
Thank you for your detailed feedback.
Fixed the issue. Kindly pull and check again.
Note: Selecting 'All Projects' will automatically set Equipment to 'All Equipments'. That is the default feature given.

**Comment by pshereen** [comment]
> Hello,
> 
> Great work, but I found a potential Filtering Issue, not sure whether it's an expected behavior, but they are:
> 
> 1. When I select any equipment type, and then sort by name or project, all the projects with sorted results pop-up, I feel this step should show sorted results with the equipment type filter applied.
> 2. Similar one with project type.
> 
> Both of them were recorded in these videos, kindly check for them.
> 
>  Screen.Recording.2024-06-28.at.10.57.50.PM.mov 
>  Screen.Recording.2024-06-28.at.10.58.36.PM.mov

Hi Pavan,

Hi Diya,
Thank you for your detailed feedback.
Fixed the issue. Kindly pull and check again.
Note: Selecting 'All Projects' will automatically set Equipment to 'All Equipments'. That is the default feature given.

**Comment by pshereen** [comment]
> Hi Shreen, I have tested this PR with backend PR 992 and opened the page bmdashboard/equipment. The page table is empty. However the api "(http://localhost:4500/api/bm/equipments)" is not working and gives error 404 not found. PR-2359+992

Kindly Pull the front end and related backend again.
Make sure to clear cache before testing.

**Comment by pshereen** [comment]
> I have tested the PR and the page bmdashboard/equipment page table is empty. However the api "/api/bm/equipments" is successfully returning the response but the data is not getting rendered to the table. Please look into the issue.
> 
>  2359.mp4

Please pull the frontend and backend again.
Clear cache before testing.

**Comment by pshereen** [comment]
> Thank you for your feedback.
> Fixed the issue.
> Kindly pull again and verify.

Thank you for your feedback.
Fixed the issue.
Kindly pull again and verify.
Mahe sure to clear cache before testing.

**Comment by Vigneshwar-Muriki** [comment]
I have tested this functionality as mentioned in the instructions. Since its mentioned that selecting all projects will set to all equipment. I have no issues with it. The sorting and filtering works as expected. However, when I click equipment update history, it doesn't display anything where as for the purchase history, it displays the content.
Screenshot 2024-07-04 172407
Screenshot 2024-07-04 172413
Screenshot 2024-07-04 172430
Screenshot 2024-07-04 172438
Screenshot 2024-07-04 172448

**Review by Vigneshwar-Muriki — CHANGES_REQUESTED** [review]
I have tested this functionality as mentioned in the instructions. Since its mentioned that selecting all projects will set to all equipment. I have no issues with it. The sorting and filtering works as expected. However, when I click equipment update history, it doesn't display anything where as for the purchase history, it displays the content.
Screenshot 2024-07-04 172407
Screenshot 2024-07-04 172413
Screenshot 2024-07-04 172430
Screenshot 2024-07-04 172438
Screenshot 2024-07-04 172448

**Comment by pshereen** [comment]
> I have tested this functionality as mentioned in the instructions. Since its mentioned that selecting all projects will set to all equipment. I have no issues with it. The sorting and filtering works as expected. However, when I click equipment update history, it doesn't display anything where as for the purchase history, it displays the content. Screenshot 2024-07-04 172407 Screenshot 2024-07-04 172413 Screenshot 2024-07-04 172430 Screenshot 2024-07-04 172438 Screenshot 2024-07-04 172448

Thank you for your feedback.
No equipment has updated yet.
That's why no data is visible there in the history.

**Review by Vigneshwar-Muriki — APPROVED** [review]
The code and feature works as expected.

**Review by Sarath-3119 — APPROVED** [review]
The changes are now working as mentioned. Approving the PR. Good work on the changes .

**Review by DiyaWadhwani — APPROVED** [review]
Hi Shereen,
I have tested your changes again. Added a video of the testing below.
Thank you.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/54880903/a9b6be0a-bd40-43db-b1e5-4dc31309b76f

**Review by vishavk1992 — APPROVED** [review]
Hi shereen , i have tested your PR again as per your request and it works as expected and i successfully tested your PR functionality now. i have attached video for your reference 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/148455293/c00349e4-45fd-4087-b0c1-b6127704d9c4

**Review by HowieMiao — APPROVED** [review]
Changes look great and PR is working as intended

**Review by Kavil-Jain-514 — APPROVED** [review]
The PR works perfectly fine. I have replicated the video and everything on the video works.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112303944/e2b4bf96-3126-4933-b2f5-652bfb2b00d1

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
