### PR TITLE
Changhao - added new unit tests for usertablefooter

### PR DESCRIPTION
**Pull request by lichanghaogit**
# Description
added new unit tests for usertablefooter trace the page summary.

## How to test:
1. check into current branch
2. do `npm install` and `npm test UserTableFooter.test.js` to run this PR locally
3. verify all 14 tests are passed

## Screenshot:
Screenshot 2024-01-15 at 10 04 27 PM

### CODE REVIEW

**Comment by beblicarl** [comment]
All tests passed 

image

**Review by beblicarl — DISMISSED** [review]

**Review by 666saofeng — APPROVED** [review]
All tests passed
Screenshot 2024-01-16 at 7 45 07 PM

**Review by KevHnh — DISMISSED** [review]
All tests passed
image

**Review by pshereen — DISMISSED** [review]
All tests passed.
Screenshot 2024-01-17 194355

**Review by Renanluizssx — DISMISSED** [review]
It´s correct, very nice.
pull#1840

**Review by bajajtushar094 — APPROVED** [review]
@Changhao3220K All test cases passed. Thanks 
Screenshot 2024-01-18 at 23 30 16

**Comment by DragonSlayer2401** [comment]
I tested the PR all of the tests passed as intended. Please watch the overview video for more details:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/bc3ddf52-03ea-43ff-b145-f995c9e3215a

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 21 - PR3

**Review by X1aoZhang99 — DISMISSED** [review]
Hi Changhao,

All tests passed. Congrats! 

Screenshot 2024-01-24 at 16 55 37

**Review by cvtqx — CHANGES_REQUESTED** [review]
Excellent job! 
All the tests pass:

Screen Shot 2024-01-26 at 10 42 10 AM

All test cases are covered:

coverage report

However, I see that there are two test folders in this component. We have to store all tests in __tests__. Can you move your test to this folder? Also would you be able to move all other tests so they are all consolidated in __tests__ and remove the __test__ folder?

Screen Shot 2024-01-26 at 10 42 27 AM

**Review by peterson337 — DISMISSED** [review]
All tests passed

a

**Comment by xmyoot** [comment]
Hello, 
all 14 tests passed, great work! 
PR#1840

**Review by Pandani07 — DISMISSED** [review]
All tests passed, great work. Checked how the app works and everything was fine. All components were rendered and found no bugs

**Review by TapanPathak — DISMISSED** [review]
Hi, All test cases passed!

Screenshot 2024-02-16 at 7 00 27 PM

**Review by XiaohanMeng — COMMENTED** [review]
Hi, all test cases have passed! Great work!
FE-1840-result

However, I noticed that the test folders are duplicated. I believe consolidating all tests into a single folder would be better.
FE-1840-improve

**Review by ShengjieMao — DISMISSED** [review]
All tests passed. While instructions said there should be 14 tests, I only got 12 tests when ran the test. Other components were comprehensively tested.
PR_1840

**Review by ClemarNunes — DISMISSED** [review]
I tested your PR and worked as expected.


Captura de tela 2024-02-17 232340

**Comment by dhairya-mehta** [comment]
Hey I verified all the test cases!
12/12 passed
image

**Review by aaryaneil — COMMENTED** [review]
All test cases passed.
Screenshot 2024-03-30 at 9 22 07 PM

**Review by KaushikMreddy — CHANGES_REQUESTED** [review]
Hi, 

your test cases have passed
image


But please mind the folder structure, check if there needs to be a separate folder called test under another folder in Timelog, if the folder is created only for test files. Move them to the test folder under Timelog
image

**Review by dkt6 — DISMISSED** [review]
All test cases are working as expected! LGTM

test

**Comment by Changhao3220K** [comment]
Hi @KaushikMreddy , @cvtqx 
Thank you very much for pointing out the issue in the test file folder, the unit test has been moved to __tests__ now.

**Review by cvtqx — DISMISSED** [review]

**Review by Sandhya1236 — APPROVED** [review]
I have successfully tested the new unit tests for UserTableFooter. After checking into the current branch, running npm install, and executing npm test UserTableFooter.test.js, I verified that all 14 test cases passed successfully. This confirms that the unit tests for UserTableFooter are functioning as expected and correctly trace the page summary.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
