### PR TITLE
Nida Fix - Save Changes Fix on User Profile

### PR DESCRIPTION
**Pull request by NidaZaki**
# Description
image

# Fixes (bug list priority medium)
- Added `setOriginalProjects(projects)` and ` setOriginalTeams(teams)` functions in each of the methods, `checkIsProjectsEqual()` and `checkIsTeamsEqual()` respectively.

## Main changes explained:
- Added `setOriginalProjects(projects)` and `setOriginalTeams(teams)` functions in each of the methods, `checkIsProjectsEqual()` and `checkIsTeamsEqual()` respectively, to ensure that the latest project value and the latest team value is being set when the save button is clicked.

## How to test:
1. check into current branch
2. log as admin user
3. go to User’s profile → Projects tab → Assign/Delete projects → Save changes
4. verify that when assigning or deleting projects in a user’s profile, the save changes warning does not appear, hence indicating that the changes have been saved on first click.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/32549172/72791192-c810-40fe-bfd6-b388e263dcfa

### CODE REVIEW

**Comment by iTvX** [comment]
Test Video: https://www.dropbox.com/s/4188ln2w3pwx1s7/1.mp4?dl=0

Functionality works as described.

**Review by iTvX — APPROVED** [review]

**Comment by AnishPandita** [comment]
Hi @NidaZaki, it works as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/ecfbaea6-3ef6-47c4-8c3a-e33b09b82c22

**Review by cone-7 — APPROVED** [review]

**Comment by beblicarl** [comment]
The functionality works as intended. Great work!

[Save-Changes-Fix_3000-2023.06.30-09_36_33.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/08b07ca6-0ed4-438b-80a0-6e28c77fc67d)

**Review by beblicarl — APPROVED** [review]

**Review by HectorAgudelo — APPROVED** [review]
The changes work as intended.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/8adef88f-5103-4af9-a5fe-d6108c2c479c

**Review by cvtqx — APPROVED** [review]
Tested this by assigning and deleting a project to a user. As ave changes warning does not appear. Works as described.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/e093a7a3-9ecc-4f46-9ba9-f893ed44d7f9

**Comment by one-community** [comment]
Thank you all, moving this one to final review.

**Review by mahamakhan — APPROVED** [review]
Works as mentioned. Great job

**Comment by Lucas-E** [comment]
Working as intended! Great job!

**Pull request merged**
