### PR TITLE
Ajay - fix tab preview names

### PR DESCRIPTION
**Pull request by AJAYINAVOLU**
# Description
This PR adds a feature that allows users to see a preview name for each tab in the application without needing to click and view the content. By utilizing useLocation and dynamically updating document.title, improves navigation and user experience across the entire project.

## Related PRS (if any):
This frontend PR is related to the development branch of the [backend](https://github.com/OneCommunityGlobal/HGNRest) repository.

## Main changes explained:
Updated the following files to add tab preview functionality using **useLocation** and **document.title**:

**- src/components/Announcements/index.jsx
- src/components/BMDashboard/AddMaterial/AddMaterial.jsx
- src/components/BMDashboard/BMDashboard.jsx
- src/components/BMDashboard/ConsumablePurchaseRequest/PurchaseConsumable.jsx
- src/components/BMDashboard/Equipment/Add/AddEquipmentType.jsx
- src/components/BMDashboard/Equipment/Detail/EquipmentDetail.jsx
- src/components/BMDashboard/Equipment/Update/UpdateEquipment.jsx
- src/components/BMDashboard/EquipmentPurchaseRequest/PurchaseEquipment.jsx
- src/components/BMDashboard/InventoryTypesList/InventoryTypesList.jsx
- src/components/BMDashboard/Lesson/LessonForm.jsx
- src/components/BMDashboard/LessonList/LessonListForm.jsx
- src/components/BMDashboard/LogTools/LogTools.jsx
- src/components/BMDashboard/Login/BMLogin.jsx
- src/components/BMDashboard/Projects/ProjectDetails/ProjectDetails.jsx
- src/components/BMDashboard/PurchaseRequests/MaterialPurchaseRequest/MaterialPurchaseForm.jsx
- src/components/BMDashboard/PurchaseRequests/ReusablePurchaseRequest/ReusablePurchaseForm.jsx
- src/components/BMDashboard/ToolPurchaseRequest/PurchaseTool.jsx
- src/components/BMDashboard/Tools/AddTool.jsx
- src/components/BMDashboard/Tools/ToolDetailPage.jsx
- src/components/BMDashboard/Tools/ToolsList.jsx
- src/components/BMDashboard/UpdateMaterials/UpdateMaterialsBulk/UpdateMaterialsBulk.jsx
- src/components/BMDashboard/UpdateReusables/UpdateReusablesBulk/UpdateReusablesBulk.jsx
- src/components/Badge/BadgeManagement.jsx
- src/components/Dashboard/Dashboard.jsx
- src/components/EmailSubscribeForm/Unsubscribe/index.js
- src/components/EmailSubscribeForm/index.js
- src/components/ForcePasswordUpdate/ForcePasswordUpdate.jsx
- src/components/Inventory/Inventory.jsx
- src/components/Login/ForgotPassword.jsx
- src/components/Login/Login.jsx
- src/components/Logout/Logout.jsx
- src/components/PermissionsManagement/PermissionsManagement.jsx
- src/components/PermissionsManagement/RolePermissions.jsx
- src/components/Projects/Members/Members.jsx
- src/components/Projects/Projects.jsx
- src/components/Projects/WBS/SameFolderTasks/SameFolderTasks.js
- src/components/Projects/WBS/SingleTask/SingleTask.js
- src/components/Projects/WBS/WBSDetail/WBSTasks.jsx
- src/components/Reports/PeopleReport/PeopleReport.jsx
- src/components/Reports/ProjectReport/ProjectReport.jsx**

Test Files:
Updated the following test files to import **MemoryRouter** and **mock location** for tests:

**- src/components/BMDashboard/Login/__tests__/BMLogin.test.js
- src/components/BMDashboard/_tests_/BMDashboard.test.jsx
- src/components/Login/Login.test.jsx
- src/components/Projects/WBS/__tests__/SameFolderTasks.test.js
- src/components/Projects/__tests__/Projects.test.jsx
- src/components/Reports/ProjectReport/__tests__/ProjectReport.test.js
- src/components/TaskEditSuggestions/__tests__/TaskEditSuggestions.test.js
- src/components/UserManagement/__tests__/NewUserPopup.test.js
- src/components/UserProfile/EditableModal/__tests__/roleInfoModal.test.js
- src/components/WeeklySummariesReport/WeeklySummariesReport.test.jsx**

## How to test:
1. Check into the current frontend branch and the development backend branch.
2. Do npm install and npm run start:local to run this PR locally.
3. Clear site data/cache.
4. Log in as an owner-user.
5. For each endpoint, please: -> Navigate to the URL.
6. Check that the browser tab displays a relevant preview name based on the current page content.
7. The list of endpoints are:
1. **Dashboard:**
   - `/dashboard`
   - `/dashboard/:userId`

2. **Profile Setup:**
   - `/ProfileInitialSetup/:token`

3. **Timelog:**
   - `/timelog/`
   - `/timelog/:userId`

4. **Members:**
   - `/project/members/:projectId`

5. **People Report:**
   - `/peoplereport/:userId`

6. **Project Report:**
   - `/projectreport/:projectId`

7. **Team Report:**
   - `/teamreport/:teamId`

8. **Task Edit Suggestions:**
   - `/taskeditsuggestions`

9. **Inventory:**
   - `/inventory/:projectId`
   - `/inventory/:projectId/wbs/:wbsId`

10. **Weekly Summaries Report:**
    - `/weeklysummariesreport`

11. **Reports:**
    - `/reports`

12. **Team Locations:**
    - `/teamlocations`

13. **Projects:**
    - `/projects`
    - `/wbs/tasks/:wbsId/:projectId/:wbsName`

14. **WBS:**
    - `/project/wbs/:projectId`
    - `/wbs/tasks/:taskId`
    - `/wbs/samefoldertasks/:taskId`

15. **User Management:**
    - `/usermanagement`

16. **Badge Management:**
    - `/badgemanagement`

17. **Permissions Management:**
    - `/permissionsmanagement`
    - `/permissionsmanagement/:userRole`

18. **Teams:**
    - `/teams`

19. **Announcements:**
    - `/announcements`

20. **Total Organization Summary:**
    - `/totalorgsummary`

### BM Dashboard Routes:

21. **BM Dashboard:**
    - `/bmdashboard`
    - `/bmdashboard/login`

22. **BM Purchase Routes:**
    - `/bmdashboard/materials/purchase`
    - `/bmdashboard/reusables/purchase`
    - `/bmdashboard/equipment/purchase`
    - `/bmdashboard/tools/purchase`

23. **BM Projects:**
    - `/bmdashboard/projects/:projectId`

24. **BM Lesson List:**
    - `/bmdashboard/lessonlist/`

25. **BM Material and Reusable Updates:**
    - `/bmdashboard/materials/update`
    - `/bmdashboard/reusables/update`

26. **BM Materials and Consumables Add:**
    - `/bmdashboard/materials/add`
    - `/bmdashboard/consumables/add`

27. **BM Equipment and Tools:**
    - `/bmdashboard/equipment/add`
    - `/bmdashboard/equipment/:equipmentId`
    - `/bmdashboard/tools`
    - `/bmdashboard/tools/add`
    - `/bmdashboard/tools/log`
    - `/bmdashboard/tools/:toolId`
    - `/bmdashboard/tools/:equipmentId/update`

28. **BM Lesson Form:**
    - `/bmdashboard/lessonform/:projectId`
    - `/bmdashboard/lessonform/`

29. **BM Inventory Types:**
    - `/bmdashboard/inventorytypes`

### Other Routes:

30. **Login:**
    - `/login`
    - `/logout`
    - `/forgotpassword`

31. **Email Subscription:**
    - `/email-subscribe`
    - `/email-unsubscribe`

32. **Profile and Password Update:**
    - `/userprofile/:userId`
    - `/userprofileedit/:userId`
    - `/updatepassword/:userId`
    - `/forcePasswordUpdate/:userId`

33. **Other Pages:**
    - `/infoCollections`
    - `/` (default route)

## Screenshots or videos of changes:

dashboard
reports
timelog
total organization summary
weekly summary report

## Note:
In some cases, it may take up to 1 second for the tab preview name to load because it depends on data from the page. Please allow the page to fully load before verifying the tab preview.

### CODE REVIEW

**Review by samarth9201 — APPROVED** [review]
The code works, just a suggestion, a good way to implement these changes could have been to create a custom hook. This way, we wouldn’t have to write the useEffect for setting titles in every component—just call the hook instead. It would make the code a lot cleaner and easier to maintain, too!

For example:

```
import { useEffect } from 'react';

function useDocumentTitle(title) {
  useEffect(() => {
    document.title = title;
  }, [title]);
}

export default useDocumentTitle;
```

And use it like this:

```
import useDocumentTitle from '../../hooks/useDocumentTitle';

function Announcements() {
  useDocumentTitle('Announcements');

  // Component code here...
}
```

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/308f5229-7ad0-4ed5-88f8-0400ac557332

**Review by vishavk1992 — APPROVED** [review]
I have tested this PR and everything working as expected.


https://github.com/user-attachments/assets/4593e4ad-6a01-4a91-b319-11c0789e6188

**Review by anirudhsk2107 — APPROVED** [review]
Tested for all pages and they are working as expected. 
I attached a few screenshots for reference. 

Screen Shot 2024-10-26 at 12 31 45 AM
Screen Shot 2024-10-26 at 12 31 39 AM
Screen Shot 2024-10-26 at 12 31 32 AM
Screen Shot 2024-10-26 at 12 31 19 AM
Screen Shot 2024-10-26 at 12 30 44 AM
Screen Shot 2024-10-26 at 12 30 36 AM
Screen Shot 2024-10-26 at 12 30 24 AM

**Review by anji-annavarapu — APPROVED** [review]
everything working fine

**Review by CodewithKoushica — CHANGES_REQUESTED** [review]
Hello @AJAYINAVOLU,
Thank you for implementing dynamic document titles! The feature is useful, but updating 67 files for this change may become difficult to maintain. A more centralized approach might simplify things, making it easier to adjust titles from one place as new routes or changes are added.

### Suggested Approach:
1. Define titles as an object  in `routes.js`:
   ```
    const pageTitle = {
     '/dashboard': 'Dashboard',
     '/timelog': 'Time Log',
     '/projects': 'Projects',
     // Additional routes as needed
   };
   ```

2. Update the document title with `useEffect` based on `location.pathname`:
   ``` 
     useEffect(() => {
           const path = location.pathname;
           document.title = pageTitle[path] || "Default Title";
      }, [location]);
   ```

4. In `App.jsx`, ensure `Routes` component is wrapped in `Router`:
   ```
   <Router>
     <Routes />
   </Router>
   ```

This approach centralizes title management, making it easy to add or modify titles without editing multiple files. Would you consider refactoring this way? Thanks again for your work on this feature!

**Comment by AJAYINAVOLU** [comment]
There is a new pull request for tab preview names with minimal file changes.

**Pull request closed without merging**
