### PR TITLE
update the pie chart details

### PR DESCRIPTION
**Pull request by EvianTan**
# Description
This PR is for resolving the REPORTS COMPONENT bug #3
image

## Related PR
#660 Previous developer Shaun worked on this bug but didn't finish, after checking his PR and walkthrough video, it's easier for me to just close his PR and create a new one.

## Mainly changes explained:
`PeopleTasksPieChart.jsx`: update the texts per Jae's requirement
`PieChart.jsx`: 
1. create `totalValue` for summing up the total values of the donut chart
2. put this value in the center of the donut chart
3. add a new div to show it in text

## How to test:
check into current branch
do `npm install` and `...` to run this PR locally
log as admin/owner user
go to Dashboard → Reports → Reports → People → Choose “Yiyun Admin”
verify the pie chart changes

## Screenshots or videos of changes:
Before:
image
After:
image

### CODE REVIEW

**Review by kangjay88 — COMMENTED** [review]
Hi @EvianTan, I have tested the PR and it works as expected.
1. Using Admin account, value is shown in center of pie chart
PR687_1
PR687_2

**Review by vanelnw — DISMISSED** [review]
Hi @EvianTan, I have tested the PR and it works well.
Capture d’écran 2023-02-25 à 02 30 29

**Comment by NyahJ** [comment]
Hi @EvianTan, 

I have tested your changes and it works as intended: the pie charts are updated to the new version. Good work, thanks!
截屏2023-02-24 下午5 57 17

**Comment by angelinatr15** [comment]
Hi @EvianTan, 

This PR looks great visually! the total number really stands out being in the center of the pie chart. For consistency should we also change the title of the last task to be "Last Tasks With Completed Hours"? 

Before:
Screenshot 2023-02-25 at 12 18 26 AM

After:
Screenshot 2023-02-25 at 12 20 50 AM

**Comment by ayush0904** [comment]
Hello @EvianTan I have tested the functionality and it is working as intended.. Excellent work!!!

**Comment by vitorsaa2k** [comment]
Its working as intended.

I agree with @angelinatr15 suggestion to keep consistency, change "Last tasks with committed hours" to "Last Tasks With Completed Hours"

image

**Review by kamtoeddy — APPROVED** [review]
Hi @EvianTan,

Tested and it's all good. Well done
Screenshot (525)

But I noticed that the total number of hours do not get computed in the chart in the modal. You can check this by clicking on the "View all" button of the card with title "Last tasks with committed hours".

Here is a screenshot:
Screenshot (527)

**Review by Lucas-E — COMMENTED** [review]
Hey! How are you doing? I've reviewd your PR, and things are working! Great Job!
However, when i click the "View All" modal, hours seems to not be summed.
EvianTanPR687SECOND
EvianTanPR687FIRST

**Comment by mpavithr** [comment]
Hi @EvianTan,

PR seems to be working as intended! With the total hours at the center of the chart
yiyun_pr1

However, when clicking View All, the hours at the center go to 0 despite it not being 0
yiyun_pr2

**Comment by Jorge-Nerd** [comment]
HI @EvianTan seems to me to be working correctly how you can see
Before the update
image
and after the changes 
image

**Review by suigunfjc — COMMENTED** [review]
Hi @EvianTan , the pie charts and total hours are displayed correctly. The code changes look good to me too except for the pie chart in the modal.
Screenshot 2023-02-25 185659
Screenshot 2023-02-25 185714
I tried to fixed the bug by moving line 21-23 in PieChart.jsx to line 38 in the useEffect() function and make the pie chart use `totalValue` rather than `totalHours`. I believe there is a conflict between `NewModal` and `PieChart` that caused the bug but I can't figure it out. Hope this would help!!
Screenshot 2023-02-25 192024

**Comment by EvianTan** [comment]
> Hi @EvianTan,
> 
> This PR looks great visually! the total number really stands out being in the center of the pie chart. For consistency should we also change the title of the last task to be "Last Tasks With Completed Hours"?
> 
> Before: Screenshot 2023-02-25 at 12 18 26 AM
> 
> After: Screenshot 2023-02-25 at 12 20 50 AM

Great catch! thank you, I'll change it shortly.

**Comment by EvianTan** [comment]
hey @kamtoeddy @Lucas-E @suigunfjc 

Thanks for catching that, I'll try to rework on this PR to make the "View All" modal can also show the total hours as the center text shortly.

**Review by tingedudu8 — DISMISSED** [review]
Hi @EvianTan, I tested your PR and the number of completed hours is correctly shown in the center of each pie. The title has been updated and when click on the "View All" button, the center number has also been correted. Thanks! I will approve this PR.
Screen Shot 2023-02-27 at 8 17 35 PM
Screen Shot 2023-02-27 at 8 19 03 PM

**Comment by Lunaliar** [comment]
This works great! On wider screens, the layout adjusts well to fill in gaps. I don't know if it's too late/out of scope for this PR but I feel like a back button to return to people reports could be nice for the flow of this page, instead of clicking through the report dropdown, etc. Also, some padding on the buttons is weird at my screen size but I didn't see it in anyone else's screenshots. All in all great work!
padding
Screenshot from 2023-02-28 10-08-17
Screenshot from 2023-02-28 10-09-40

**Review by vitorsaa2k — APPROVED** [review]
Tested, and requested changes was added.

image

image

**Comment by RafaelCastilhoCastro** [comment]
Thanks for your reviews. I just want to remind everyone to always check the code and make sure everything seems fine.
@EvianTan when possible please take a look at the padding issue experienced by @Lunaliar and @vitorsaa2k. Thank you.
I'm moving this PR to be tested by the leadership team.

**Comment by EvianTan** [comment]
Hey @Lunaliar , thank you for pointing out that padding issue. I did some change in my last commit "fix the padding on the time-log-block", hope that could fix the issue. Since I'm using the normal 16:9 screen so I cannot reproduce the issue on 
 myside, so I cannot make sure my last commit fix it. It would be really helpful for me if you can provide your screen size, so hopefully I can test on my side by changing the dimensions like below.
image

**Comment by crystalsong2021** [comment]
Tested the functionality of the PR#687 and confirmed that hours showed in the middle of the pie chart. Confirmed the modal works and closed properly. Great job Evian!
Screenshot 2023-03-01 at 4 10 01 PM
Screenshot 2023-03-01 at 3 04 43 PM

**Review by kamtoeddy — APPROVED** [review]
Hi @EvianTan,

I retested your PR and everything looks great. Thanks

Screenshot (555)

**Comment by Lunaliar** [comment]
Hey @EvianTan, it looks great! for the CSS changes I would just suggest using max-width or min-width for responsiveness, they both look fine even if its a subtle difference. Good job!
PieChart

**Comment by agujjar2206** [comment]
Hello @EvianTan, I have tested this PR, and the changes look good. However, it would be better if the hours were rounded to 2 decimal places. 

For example:

Here, the Hours can be rounded to 0.25 instead to improve readability.

The other changes and the code look good.

Before:


After:


Thank you.

**Comment by one-community** [comment]
All the charts seem to have disappeared here… Checked the Dev and the Main. Is this due to Kaixiang or Akshay's PR too? I tried to revert Kaixiang's but Git wouldn’t let me because it said changes had already been made that blocked that.

**Comment by EvianTan** [comment]
This PR works as expected, nothing broke on the pie chart reports. 
You cannot see the charts just because of no hours logged into tasks on the user you're checking.
Testing steps:
1. pick a user
2. assign multi tasks to the user
3. log hours to each of the tasks
4. check the pie chart report page of the user

**Pull request merged**
