### PR TITLE
Abdel add home country option to user setup

### PR DESCRIPTION
**Pull request by abdel-lall**
# Description
a.	(PRIORITY MEDIUM) Jae: Later PR/AFTER ABOVE: Create option for “home country”(WIP Abdel)
i.	When people fill out their own Onboarding details (see PR [1073](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/1073)), I’d like them to have an option to represent their home country if it is different from the country they are currently residing in. If they choose that option, it should update the map with their details for their country option instead of their location input for timezone purposes. 
ii.	Field: “Do you represent a country other than your current residence?”
iii.	“i”: One Community is a global effort and international team that has had volunteers volunteering from and/or representing <# (currently 60)> countries around the world. Complete this field if you are currently residing in a country other than your own and wish to be represented on our global contributors <link it> map with your birth country instead of your current country or residence.
iv.	This option also needs a “Read the requirements” box AND a followup confirmation popup:
1.	Box mouseover of the “Read the requirements” text: Please only choose this option if you were born and lived for a fair amount of time (10+ years) in the country you are stating you represent.
a.	Please make this editable by Owners using the already existing code for this 
2.	Popup: Thank you for representing our global community! By stating you are a native of a country other than the one you are currently living in, you certify you were born and/or lived the majority of your life and call it “home”.
a.	Yes option: input is accepted and it says: Thank you!
b.	No option: input is cleared and it says: No problem, thank you! 
3.	Please add the popup field in # 2 to the Other Links>Popup Management too
v.	ALSO: Request they add a photo, see below.

## Related PRS (if any):
This frontend PR is related to the [#628](https://github.com/OneCommunityGlobal/HGNRest/pull/628) backend PR.

## How to test:
1. check into current branch

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/02b78029-fbf5-4ebf-a90e-eba2525ecc89

### CODE REVIEW

**Review by sucheta90 — COMMENTED** [review]
Hello @abdel-lall, I started the local branch and tried to login as ADMIN, however it keeps throwing a CORS error. I am not sure if it's just my user profile. I would be happy to take a look again, once someone confirms it. Please refer to the video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/944953ef-27af-4e40-8e08-9a6d0b5ffd47

**Review by Alforoan — CHANGES_REQUESTED** [review]
It doesn't seem to be able to send a new link to the user.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/61172610-0ca1-4c0f-bc33-255257f9b33c

**Review by ljrirene — COMMENTED** [review]
Hi Abdel, when logged in as an admin, I didn't get the correct response after clicking the "send link" button. Here is my recording.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/72fec523-805f-4cc7-a444-26d86d305bcc

**Comment by this-journey** [comment]
Hello @abdel-lall! When logged in as admin it will not allow me to send a setup link.
Screenshot 2023-12-02 at 8 38 13 PM (2)


I tried to log in as owner as well and got the same response.
Screenshot 2023-12-02 at 8 41 08 PM (2)

**Comment by abdel-lall** [comment]
Hello team,
@sucheta90 the error you're getting might be because of frontend environment variables. Ensure this line is included in the .env file:
`REACT_APP_APIENDPOINT="http://localhost:4500/api"`

@this-journey , @ljrirene , @Alforoan to enable email sending, you first need to set up the backend environment variables. Please refer to the video below it shows how to get the client ID, client secret, and refresh token:

https://www.youtube.com/watch?v=-rcRf7yswfM&t=10s&ab_channel=MafiaCodes

```
REACT_APP_EMAIL =<your_test_email>
REACT_APP_EMAIL_CLIENT_ID =<follow the video for instructions>
REACT_APP_EMAIL_CLIENT_SECRET =<follow the video for instructions>
REACT_APP_EMAIL_REFRESH_TOKEN =<follow the video for instructions>
REACT_APP_EMAIL_CLIENT_REDIRECT_URI = https://developers.google.com/oauthplayground
sendEmail = TRUE
```

**Review by sucheta90 — COMMENTED** [review]
Hey @abdel-lall thank you so much for sharing the link to set up the backend environment variables. I was able to login as Admin and was able to send the email link successfully. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/52782357-d071-4b94-a909-e146e8aa57a8

The only **challenge** I had was the Geolocation API key. I did create one for myself to test , however couldn't make it work. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/101291283/b656028f-99cb-4f73-af48-1e9ca2fc98d8

Otherwise, well done with the code.

**Review by ljrirene — COMMENTED** [review]
Hi Abdel, I can successfully send the setup email to a new user from the admin user. However, I got an error when set the time zone. 
Here is the error I got:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/34266880/e1370ba2-859b-467d-aee4-a725f189dc6d

You can find that I got Geocoding API missing error here at 1'50''.

**Comment by abdel-lall** [comment]
Hi @ljrirene, 
To solve the error message you're getting, you need obtain free API key from https://opencagedata.com/pricing
and add it to the env variables (backend).
```
TIMEZONE_PREMIUM_KEY=<API Key>
TIMEZONE_COMMON_KEY=<API Key>
```

**Review by pika-chu11 — COMMENTED** [review]
Hi @abdel-lall , I have tested your PR. You did a good job!

- The 'Send Setup Link' button is functional
   - I was able to send a link to create a new user
- I have checked that I need to agree with the requirement before setting Home Country.
- I was able to find my home country and set it with a Popuo asking "Do you want to represent [city], [country]?" ([your can fill in whatever city you like])
    - Yes potion: input message "Thank you" did show up.
    - No option: input message "No Proble, thank you!" did show up.

> However,  
> I cannot create a new user after I fill in all the information that required. I am not sure what happened.

Please watch the video for more detail:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67128170/d187034f-2990-40d5-aaf1-66ad89ad6d71

**Review by cvtqx — CHANGES_REQUESTED** [review]
I was able to set up the email sending and started filling out the form. All the form functionality (the popup window, the info modal on hover) works as described. However, I had an issue with geolocation, that feature did not work even though I obtained the API key as you noted in one of your comments.
Can you please include the instructions in the PR description on how to set up this API?

See video of my test:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/5bcc7863-0f1f-4131-8cf7-e625b038eaf7

**Comment by keyunhuangg** [comment]
I tried to send link to a email that is not on the system and the page seem to be stuck. However the system does detect sending set up link to user email that is already in the system.
Screenshot 2023-12-21 at 2 58 41 PM

**Comment by abdel-lall** [comment]
@cvtqx The issue should now be resolved. Please take a moment to test it when you have a chance.

**Comment by abdel-lall** [comment]
@keyunhuangg Please use the updated instructions for the backend. to setup the env variables.

**Comment by cvtqx** [comment]
Thanks for updating the instructions! Everything works as described. Great work! One thing to consider - and this is the reason why I wasn't able to find my location yesterday - you need to enter a city name not a country name to be able to locate yourself. If you only enter a country name, it does not work. Perhaps this needs to be added as a placeholder or something. see video for clarification:

Adding location:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/f236f65e-b480-4e2b-a839-41f8ca5b8cfb

Map:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/be63d5c6-52f8-461a-8bd5-5da76b0b59b8

**Comment by abdel-lall** [comment]
@cvtqx The changes I pushed yesterday were aimed at enabling the input of country names, not just city names. Please ensure you update your local branch before testing to incorporate these updates. Thank you!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49083865/63d31a52-29d1-4f68-8404-5cc1af4d7b9d

**Review by cvtqx — APPROVED** [review]
Awesome job! I've been able to set my location with just a country name.

Screen Shot 2023-12-22 at 9 56 20 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
