### PR TITLE
Crystal fix teams toggle 

### PR DESCRIPTION
**Pull request by crystallow1168**
# Description
image

Bug priority urgent

## Related PRS (if any):
This frontend PR is related to the development branch on the backend.

## Main changes explained:
- Updated the default visibility setting for newly added team members from "toggle off" to "toggle on."
- Implemented a condition to retrieve the updated team members list after a new user is added.
- Added a loading spinner to indicate when team member data is being retrieved.
- Added a message to display on the team members table when no team members are present.
- Added a message to display in the dropdown options when no users match the search input.

## How to test:
1. Check into current branch: `git checkout crystal-fix-teams-toggle`
2. Do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. Log as admin user
5. Go to Dashboard→ Other Links→ Team→…
6. Verify newly added users to a team have the default visibility toggle set to "on."
7. Verify when closing and reopening the modal, the team members list displays the correct and updated team members.

## Screenshots or videos of changes:

Before changes (refer to video link below):
https://www.loom.com/share/a00fb6d198ac4a37b32e52d046d8eee0?sid=7889af68-36f7-418c-9c2c-481e28473512

New changes reflecting newly added users to a team have the default visibility toggle set to "on." (refer to video below)

https://github.com/user-attachments/assets/dc0b3d81-2ffe-42eb-b247-e3e5e5981c7f

New changes reflecting when closing and reopening the modal, the team members list displays the correct and updated team members. (refer to video below)

https://github.com/user-attachments/assets/b06495ac-0c60-441e-9273-f5d83f2d18ab

### CODE REVIEW

**Review by chu-ziyu — DISMISSED** [review]
I tested this PR and everything worked as expected in both light mode and dark mode.👍

https://github.com/user-attachments/assets/4c5158e6-2112-470a-bde7-38e06fdde437

**Review by RishithaMamidala — DISMISSED** [review]
@crystallow1168 
PR works correctly, newly added users have the default visibility toggle set to on and team members are displayed correctly with loading.
PR 2718
PR 2718-1

**Review by manikittu810 — APPROVED** [review]
Hello @crystallow1168 
Everything is working as mentioned.


https://github.com/user-attachments/assets/4efbb92b-f4a4-442b-9af5-0fdee341859d



Thanks.

**Review by Lexie5212 — APPROVED** [review]
I tested the PR, and the code worked as expected. People are added with the toggle on.



https://github.com/user-attachments/assets/2193d600-4e82-4709-9f01-341d858be833

**Review by slidracoon72 — APPROVED** [review]
#2718
@crystallow1168
1. I verified that newly added users to a team have the default visibility toggle set to "on" as expected.
2. I also checked that when closing and reopening the modal, the team members list accurately displays the correct and up-to-date team members.

Video Demonstration:
[https://www.loom.com/share/87811876c6e04cf8beaa57d464ff12a4?sid=5fac31e8-229d-4299-bfe7-960ac3f48bdc](url)

**Review by vishavk1992 — DISMISSED** [review]
I have tested this PR and Everything works as expected. I am able to add and remove member .


https://github.com/user-attachments/assets/3ed76612-1170-4fb1-8511-0ab0d0382b60

**Review by Dk-21 — DISMISSED** [review]
Tested the PR changes and Worked as described.


https://github.com/user-attachments/assets/296c984c-ad6a-44b7-8852-75512b906acf

PR-2718(1)
Pr-2718(2)
PR-2718(3)
PR-2718(4)

**Review by nikhilpittala16 — DISMISSED** [review]
I have tested the PR and everything works as expected.

https://github.com/user-attachments/assets/bb2123e2-a567-4437-a76a-db3addf8d1cf

**Review by anirudhsk2107 — DISMISSED** [review]
The changes are working properly 

Screen Shot 2024-09-26 at 11 14 10 AM
Screen Shot 2024-09-27 at 2 56 00 AM
Screen Shot 2024-09-27 at 2 56 20 AM

**Review by ziyanw52 — COMMENTED** [review]
I have test this and it works. Members can be added and deleted, and can be visible or invisible.
281727467137_ pic

**Review by Vigneshwar-Muriki — DISMISSED** [review]
Tested this PR and its working as expected. When new members added to the team, the toggle is on by default.


https://github.com/user-attachments/assets/c25ce7bd-cc01-4351-9671-a144fda0f217

**Review by jinxyou — APPROVED** [review]
Screenshot 2024-09-27 223121
Screenshot 2024-09-27 223247
The team toggle fix is working properly. Great work!

**Review by aaryaneil — DISMISSED** [review]
The changes work as expected and the newly added team members have their visibility on and the changes are see even when the modal is closed.

https://github.com/user-attachments/assets/2f0d93e4-253e-4c9a-a7e2-587e626dc8cb

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
