### PR TITLE
Shengwei Enhancement: badge assignment and modification will not remove earned date

### PR DESCRIPTION
**Pull request by ptrpengdev**
# Description
image

## Related PRS (if any):
This frontend PR is related to the #[703](https://github.com/OneCommunityGlobal/HGNRest/pull/703) backend PR.
To test this PR you need to checkout both PRs.
…

## Main changes explained:
- Code rewrite for the countChange function in BadgeReport.jsx due to logic updates and bug fixes.
- Update the badge report UI to include an immediate update for the record earned date when the badge count changes
- Update code in BadgeReport.jsx to keep earned date when the badge count decreases (aka badge deletion)
- Update code in BadgeReport.jsx and BadgeSummaryViz.jsx to display an asterisk mark on specific badge records with a tooltip to explain the mismatch in badge earned date and badge count
- Update code in BadgeReport.jsx logic to handle new property in badge collection
- Update inline style in BadgeReport.jsx and BadgeSummaryViz.jsx to align the date button and asterisk mark within the Badge table.

## How to test:
1. check into the current branch and backend PR
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as an admin user
5. go to userprofile→ selected features
6. 
image
image

7. Verify the following cases are passing:
   - **Case 1: Badge count increases should not flag the record with an asterisk mark and will not create a mismatch between earned dates and badge count**
         - Assign a new badge to the user and increase the count a few times.
         - Save the records by clicking save changes.
         - Refresh the page and verify the record is without an asterisk mark and that the count of earned dates is greater than the badge count. 
   - **Case 2: Badge count decrease should flag the record with an asterisk mark and will not remove the earned dates for the records**
         - Assign a new badge to the user and increase the count a few times.
         - Save the records by clicking save changes.
         - Refresh the page and verify the records is without an asterisk mark. 
         - Decrease the badge count to a number smaller than the original badge count.
         - Save the records by clicking save changes.
         - Refresh the page and verify the record is flagged with an asterisk mark and that the count of earned dates is greater than the badge count (no earned date should be deleted). 
    - **Case 3: Badge count increases for a flagged record should not remove the asterisk mark for the record.**
         - Find a record with an asterisk mark.
         - Increase the count a few times.
         - Save the records by clicking save changes.
         - Refresh the page and verify the record is marked with an asterisk mark and the earned date is updated. (new earned date should be pushed to the collection)
    - **Case  4:  Badge count decrease for a flagged record should not remove the asterisk mark for the record and should not remove any earned dates.**
         - Find a record with an asterisk mark.
         - Decrease the count a few times.
         - Save the records by clicking save changes.
         - Refresh the page and verify the record is marked with an asterisk mark and no earned date is not removed.
     - **Case 5: Increase the badge count then decrease it to a number smaller than the original count.**
         - Find a record without an asterisk mark.
         - Increase the count a few times then decrease it to a number smaller than the original count.
         - An asterisk mark should displayed.
         - Save the records by clicking save changes.
         - Refresh the page and verify the record is marked with an asterisk mark and the no earned date is removed. 
      - **Case 6: Decrease the badge count then increase it to a number larger than the original count.**
           - Find a record without an asterisk mark.
           - decrease the count a few times then increase it to a number larger than the original count.
           - An asterisk mark should displayed first and disappear after the new count goes over the original count.
           - Save the records by clicking save changes.
           - Refresh the page and verify the record is NOT marked with an asterisk mark and a new earned date added.
   - **Case 9:  Asterisk mark or earned date (any changes for the record) should not be saved before clicking the save changes button.**
           - Test with the previous cases and close the modal without clicking on the save changes button.
           - All updates should be temporary.  -> Refresh the page will restore the records from db.
- Once all test cases are passed. Verify the result in the Report component has same as what you see in profile -> selected features
      -  Go to reports -> people ->  search the user -> click on the user name -> click on show badge
image

image
image

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69882989/f7767923-de25-4f84-9e97-3bb4d6669881

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by X1aoZhang99 — COMMENTED** [review]
Hi Shengwei,

I test your PR with admin role and edit the badges of a volunteer. All functionality worked as intended, please refer to the video. Nice work! 

### Case 1-3:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/0f03fd5a-3038-4af0-94b5-9f14f707151c

### Case 4-9:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/c8f32b64-1e5e-4a74-b030-39ce4eed9ad9

### Show badges:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/36ea5174-8d62-43db-9da8-68977183a6ff

**Review by X1aoZhang99 — APPROVED** [review]

**Review by peterson337 — APPROVED** [review]
Hi ptrpengdev, I tested your application, and everything worked as expected. Good job!

one comunnity

**Review by Pandani07 — APPROVED** [review]
Tested this PR and verified that all 9 cases work as intended! Nice work

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/63fa8e60-0802-49e3-bb57-271369ae7317


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/d4f3f0b7-3f36-4087-8e87-d89148dd004b


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/631a8012-669e-4e1a-bc40-264d35318401

**Review by TareqMia — APPROVED** [review]
Hi @ptrpengdev, I have reviewed this PR with the related backend PR and everything worked as expected. See the videos for reference. Great work on this 👏 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/5c2eb95e-db07-4860-a6e5-7532dbb11a35


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/70c91477-807c-4142-bb1e-b864ee277664


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/39747003/7606c3d4-ca1c-47d9-b1c7-d6bc12057dfb

**Review by ClemarNunes — APPROVED** [review]
I tested your PR and worked as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/6ca4fbdf-c335-4a24-8e87-45b3a65d2314

**Review by mohabbasd — APPROVED** [review]
Hello, I tested you PR and it working as you mentioned it. I first added some badges, saved the changes and then tried to lower the number of badges and then I got a flag. Good Work.
Screenshot 2024-02-12 at 12 57 42 AM
Screenshot 2024-02-12 at 12 58 23 AM

**Review by XiaohanMeng — APPROVED** [review]
Hi, I have tested this PR with the cases, and the results show that it works as intended. Great job.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113215317/85cd691f-08c8-4578-9031-528e3e853723

**Review by Jingyii800 — CHANGES_REQUESTED** [review]
Hi @ptrpengdev, I tested your functions. Most work well, but I got an issue on the display of the asterisk mark after decreasing the badges. While decreasing the badges, I can see the asterisk mark. However, after decreasing the badges and saving changes, in "Dates" I can view all the dates of badges, but there is no asterisk mark beside it. I don't know if I miss something... Please refer to my video.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/7680a2ac-4dde-4629-8b45-ef29473e1f1b

**Review by Coops023 — APPROVED** [review]
Hi I reviewed this PR and checked functionality

-  Logged as admin
- Select user profile
- functionality of each case works as expected 
- Report component is the same as what was seen in the profile. 

Everything works as you have described in the case tests. Well done!

PR-1830-1

PR-1830-2

**Review by brandta-1 — APPROVED** [review]
# Review
Verified all test cases using the front end web application and MongoDB Compass. Code is fully functional.

#Videos

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/c3979495-dfad-44ac-a428-8b1c698f8cae


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/3e8e9346-1a54-4006-a8be-b9141bcd2eef


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/65309ccd-5146-4e75-a3c6-4d634d26297f


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/556eabf7-9e1c-4ec4-8abb-9f91650356d5


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/7bc67d16-cd91-470e-923d-f2cb3f4e2275



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/8b185f4a-ba9d-4897-928a-b5e9010751fc



https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/116298512/02faf6d1-5577-4361-9cb2-bf27aa0f09a9



Badges

**Review by 666saofeng — APPROVED** [review]
It worked as intended on my side. Please refer to the video for details

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/7962b3a3-d6d1-4281-ad57-f3899c930287

**Review by Renanluizssx — COMMENTED** [review]
Hi @ptrpengdev, i tested your application and it's working correct, but i noticed when i reflash the page, the counter backs in normal even i saving the changes, look my review:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/099bb22c-9085-40a2-bd5a-f73b850fed77

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
