### PR TITLE
Luis fix app crash on duplicate permission

### PR DESCRIPTION
**Pull request by luisarevalo21**
# Description

Screenshot 2023-08-31 at 7 39 15 PM

demo of bug
https://www.dropbox.com/scl/fi/2ldg8vjgxm6tujbfbsv73/Permissions-Management-bug.mov?rlkey=wyocl5dxp9sfvz4gdvq8kq09k&dl=0

## Related PRS (if any):
n/a

## Main changes explained:
For this PR, I passed the rolenames from Permissionmanagement.jsx into the NewRolePopUp.jsx it's name is CreateNewRolePopup via props as rolenames. 

Inside of NewRolePopUp I added a new state "isNotDuplicateRole" and added a checkIfDuplicate method to check if the new role is a duplicate. I added an else method to display an error if it exists and prevent the user' from submitting the new role by displaying an error if they tried. 

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as an owner user
4. go to dashboard→ other links → Permission Management → Add new role. 
5. Create a new role and should create a new role.
6. Attempt to create a duplicate role like "Volunteer" will provide an error. uppercase and lowercase will be tested. 
7. Attempting to create it will display an error asking to try again with a new role.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/c94d0948-40b4-4971-886d-bde89ada532b

## Note:
Include the information the reviewers need to know.
The following warnings appear inside of Permission Management. The warnings are unrelated to this PR.
Also, if you cannot see "other links" you may need to delete your owner account an create a new one. 

Screenshot 2023-08-31 at 7 54 46 PM

### CODE REVIEW

**Review by gabi-lima — DISMISSED** [review]
Well done Luis! It's working as expected. :)

image
image

**Review by yurisokolovicz — DISMISSED** [review]
Dear @luisarevalo21 

The duplicate permission problem has been resolved. Good job! Please check the video below.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/121908988/7c0a3233-588b-40af-93d3-38853769420b

**Review by Haoj1 — DISMISSED** [review]
@luisarevalo21 App did not crash after trying to create a new role using an existing name. Good job!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/99279909/6f050e10-dfbc-4212-bb1a-c7acd57e0f2e

**Comment by iTvX** [comment]
Hi @luisarevalo21,

I can not found the button that add new role. I know this is not your issue, but I have no idea how to fix it, I have tried to change other browser and change to my windows PC, this issues is still there. And after I hard refresh, the other link disappear, and I can no longer use my owner account to do any admin operation. Anyone know how to fix it?

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/1a0d6454-b281-428d-8645-117b7771977d

**Comment by luisarevalo21** [comment]
> Hi @luisarevalo21,
> 
> I can not found the button that add new role. I know this is not your issue, but I have no idea how to fix it, I have tried to change other browser and change to my windows PC, this issues is still there. And after I hard refresh, the other link disappear, and I can no longer use my owner account to do any admin operation. Anyone know how to fix it?
> 
>  CleanShot.2023-09-01.at.11.09.35.mp4

Hello, I think the links are missing because your owner account account doesn't has access to it. 
You may need to create a new owner account and try again. 

Let me know if you still have problems

**Review by EdwinLauM — DISMISSED** [review]
hi @luisarevalo21! Tested your PR and code changes and everything works as expected!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/42288987/0105c6e0-944c-4d19-8191-223d0935a5af

**Review by DavidC0126 — DISMISSED** [review]
Hi @luisarevalo21 I tested your PR and it works as described.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/20834234-1a2b-47cb-a7e6-40b59e2579f9

**Review by AuroraLovesWhales — APPROVED** [review]
Hi @luisarevalo21. I have tested your PR and it is working as intended. Great work!

The warning appears when entering a duplicate user role (upper and lowercase checked), and if the user ignores the warning, an error shows up after clicking the "create" button.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/29b21cde-bb92-4254-8669-0732b83187ed

**Review by winghojackyli — DISMISSED** [review]
Hi @luisarevalo21 , I've tested the PR and it works as intended. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/b60a9079-81ca-4373-864b-79d691e233bd

**Review by GaryB93 — CHANGES_REQUESTED** [review]
When adding a new role, an error message populates informing the user if they entered a duplicate role and prevents the user from adding a duplicate role. This fixes the original issue.

Screenshot 2023-09-04 at 1 17 01 PM

However, upon reviewing the files changed, I noticed changes in TeamMembersPopup.jsx and went to check out the Teams link in Other Links and found the page doesn't load and an error occurs. See Below.

Screenshot 2023-09-04 at 1 31 24 PM

**Review by belagaam — APPROVED** [review]
Tested the PR as per the instructions. Everything works as expected.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47104198/dea22ed9-2d54-408e-ba4c-310e55b801b1

**Comment by AriaYu927** [comment]
Hi @luisarevalo21 , I've tested your PR. Everything on permission management page works as expected. Great job!

截屏2023-09-06 11 27 35

However, I encounter the same error that @GaryB93 mentioned. Other Links -> Teams cannot open since setDuplicateUserAlert is not defined.

截屏2023-09-06 11 36 10

**Comment by luisarevalo21** [comment]
> When adding a new role, an error message populates informing the user if they entered a duplicate role and prevents the user from adding a duplicate role. This fixes the original issue.
> 
> Screenshot 2023-09-04 at 1 17 01 PM
> 
> However, upon reviewing the files changed, I noticed changes in TeamMembersPopup.jsx and went to check out the Teams link in Other Links and found the page doesn't load and an error occurs. See Below.
> 
> Screenshot 2023-09-04 at 1 31 24 PM

Hello @Gary
Great catch! I reviewed the code and removed that method, as it wasn't being used. 
I am unsure where that came from as I didn't touch that file. 
I've requested a re-review of the code. Thanks!

**Review by GaryB93 — APPROVED** [review]
Great work! You are able add a new role and when trying to add a preexisting role the user is warned. Also, the previous issue with accessing the Teams page has been resolved.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108501006/ec40b121-44fa-4ace-82d4-48392cc97645

**Pull request merged**
