### PR TITLE
Aditya Sure - Fixed Bell Notification Logic for Task Deadline Completion

### PR DESCRIPTION
**Pull request by adityasure9**
# Description:
This pull request resolves the issue with the bell notifications for task deadlines when 50%, 75%, and 90% of the task deadline is reached. This update ensures that users are appropriately notified as they approach these milestones.

image

# Main changes explained:
BellNotification Component: Enhanced the BellNotification component to include logic for triggering notifications at 50%, 75%, and 90% of task deadlines.
Modal Dialog: Updated the bell icon to trigger a modal dialog that informs the user of their task completion percentage and encourages communication with their manager if additional time is needed.
Task List Integration: Implemented a list feature where multiple task notifications are displayed if applicable. These items mirror the tasks tab in terms of information.
Reset Logic: Notifications reset upon viewing or when a new percentage milestone is reached. The logic was refined to ensure accurate behavior under various conditions.

# How to test:
1. Copy the Code: Apologies, but I’m currently unable to push changes directly to the main repository due to permission issues. Please copy the code from the files changed in this pull request.
2. Run npm install and run npm run start:local.
3. Clear site data/cache to avoid conflicts with existing notifications.
4. Log in as any user.
5. Navigate to the Dashboard and view the task list.
6. Verify that the notification bell triggers when 50%, 75%, and 90% of the task deadline is completed.
7. Click the bell to view the modal, ensuring that the correct task completion percentage is displayed.
8. Check that the notifications list items in the same manner as the tasks tab.
9. Test in both light and dark mode to ensure UI consistency.

# Screenshots or videos of changes:

https://github.com/user-attachments/assets/163f826c-1f9a-4281-a25f-36cd53d7d709
https://github.com/user-attachments/assets/3d1edfa3-8850-49a1-b768-235f00ef1c0a

# Note:
Please ensure that the notification logic is thoroughly tested across different user roles and scenarios. The notification bell is located in the dashboard, and the functionality can be tested by adjusting task deadlines to trigger notifications at 50%, 75%, and 90%. Remember to clear cookies and site data between tests to simulate a fresh user experience.

# Additional Note:
Apologies for the inconvenience. I’m currently unable to push changes directly to the main repository due to permission issues. I’ve contacted Jae Sabol regarding this, and once I receive the necessary permissions to create a new branch, I will update you. In the meantime, please copy the code from the files changed in this pull request to test the updates. If you need any assistance or have questions, feel free to reach out. I’m here to help!

### CODE REVIEW

**Review by JatinAgrawal94 — CHANGES_REQUESTED** [review]
Message is shown at 50,75 and 90% of time completion of the task assigned. But when I change the time to task and then try to reach 50% of the new time, the message is not shown. It should show. Please refer to the video for this.

https://github.com/user-attachments/assets/34f9328a-a492-46e2-bde9-600dd2c4afc5

**Comment by adityasure9** [comment]
> Message is shown at 50,75 and 90% of time completion of the task assigned. But when I change the time to task and then try to reach 50% of the new time, the message is not shown. It should show. Please refer to the video for this.
> 
>  2631.mp4

Hi Jathin, Thank you for pointing that out. You were absolutely right—the message should adjust when the task time changes, but it didn't. I apologize for the oversight, and I've now fixed the code so that it works as expected. Please let me know if you encounter any further issues.

**Review by manikittu810 — COMMENTED** [review]
Hello @adityasure9 
Unable to checkout on the current branch.
Thank you.

**Comment by sri0606** [comment]
@adityasure9 , Cannot checkout the current branch. Instead of forking the repository and commit to that, I believe you are supposed to create a branch in this repository itself.

**Comment by adityasure9** [comment]
> Hello @adityasure9 Unable to checkout on the current branch. Thank you.



> @adityasure9 , Cannot checkout the current branch. Instead of forking the repository and commit to that, I believe you are supposed to create a branch in this repository itself.

Hi @manikittu810, @sri0606 ,

Apologies for the confusion. I was unable to push directly to the main repository due to permission issues. If it's easier, you can copy the code from my fork or make the changes directly. The updates are simple, and I'm happy to help if needed.

Thanks for understanding!

**Comment by manikittu810** [comment]
>> Hi @manikittu810, @sri0606 ,

>> Apologies for the confusion. I was unable to push directly to the main repository due to permission issues. If it's easier, >> you can copy the code from my fork or make the changes directly. The updates are simple, and I'm happy to help if 
>> needed.

>> Thanks for understanding!

Hello @adityasure9 
I review it again.
Thanks

**Review by sam19981 — CHANGES_REQUESTED** [review]
hi @adityasure9 

I tried testing the changes, but I'm unable to log in after checking out your branch. Could you please rebase it with the development branch ? cause i am able to login with development branch.

**Pull request closed without merging**
