### PR TITLE
Chengyan   unit test for badge.jsx

### PR DESCRIPTION
**Pull request by ChengyanOo**
# Description
Unit test for Badge.jsx component

## Main Changes Explained:
- **Tooltip Visibility Tests**: Implemented unit tests to confirm the correct functionality of tooltip visibility. These tests ensure that tooltips associated with the 'CountInfo' and 'BadgeInfo' icons are displayed when hovered over and are hidden when the cursor is moved away.

- **Footer Text Content Tests**: Added unit tests to verify the footer text content within the Badge component. These tests check for the accurate display of messages based on the badge collection's state, ensuring that messages like 'You have no badges' and 'Bravo! You have earned...' are correctly shown according to the underlying data.

- **Store State Reflection Tests**: Conducted tests to ensure that the Badge component's UI correctly reflects changes in the Redux store's state. These tests involve modifying the state (like adding badges) and asserting that the component's rendered output matches expectations, confirming the component's reactivity and state management efficiency.

## How to test:
1. check into current branch
2. **Please temporarily comment out line 108 'BadgeSummaryViz badges={props.userProfile.badgeCollection} dashboard={true} /;' in Badge.jsx to avoid conflicts with the current changes.**
Screenshot 2024-01-18 at 17 28 24
3. do `npm install` and `npm test src/components/Badge/__tests__/Badge.test.js` to run this PR locally
4. examine the tests and verify if all tests are passed

## Screenshots or videos
Screenshot 2024-01-18 at 17 21 44

### CODE REVIEW

**Comment by Cavein254** [comment]
@ChengyanOo I tested the pr and everything works as expected

- [x] Please temporarily comment out line 108 'BadgeSummaryViz badges={props.userProfile.badgeCollection} dashboard={true} /;' in Badge.jsx to avoid conflicts with the current changes.

PR 1851

**Review by AaronPersaud — APPROVED** [review]
Hi @ChengyanOo, I've tested with the line commented out and everything looks good!

image

Please note that the test fails when line 108 is not commented out, so I think this is going to have to be merged after that gets changed.

**Review by ShengjieMao — APPROVED** [review]
Temporarily commended out the line as directed. All tests passed.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/56333697/9ded364a-3f90-44ec-a9df-ac1573935a0f

**Comment by beblicarl** [comment]
All tests passed 

image

**Review by beblicarl — APPROVED** [review]

**Review by 666saofeng — APPROVED** [review]
Hi, all tests passed! Congrats!
image

**Review by Renanluizssx — DISMISSED** [review]
Hi @ChengyanOo, i tested your unit tests and all passed
Screenshot 2024-01-31 093950

**Review by vikrambadhan — COMMENTED** [review]
Hi, I tested your and and the test cases failed!

Week 23 - PR5

**Comment by ChengyanOo** [comment]
Please make sure to comment the line as described and run rest again.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
