### PR TITLE
Xiao F Vertically align partial label of team code filter dropdown

### PR DESCRIPTION
**Pull request by tsunami776**
# Description
CleanShot 2023-10-13 at 15 54 37

## Related PRS (if any):
N/A

## Main changes explained:
- Update file `src/components/WeeklySummariesReport/WeeklySummariesReport.css` to use monospaced font to align numbers in parenthesis vertically

## How to test:
1. Check into current branch
2. Do `npm install` and `npm run start:local` to run this PR locally
3. Log in as admin/owner user
4. Go to Reports→ Weekly Summaries Report→ Select Team Code
5. Verify that numbers in parenthesis are vertically aligned equally for all 4-letter codes and 5-letter codes

## Screenshots or videos of changes:
Before:
CleanShot 2023-10-13 at 16 03 40

After:
CleanShot 2023-10-13 at 16 01 55

## Note:
I tried to put HTML tags and stylings into teamCodes's label variable, but I found that it conflicts with what is defined in `react-multi-select-component` package. So this is a workaround to make alignment work.

### CODE REVIEW

**Review by JeffLi117 — COMMENTED** [review]
Hi @tsunami776 , when I checked out this PR, this is what I did.

Logged in on an Owner account→ Reports→ Weekly Summaries Report→ Select Team Code.
However, this is the view that I got:
image

Upon clicking either one of the two selections, they are both selected as such:
image

Unsure if this is an intended change (or being addressed in another PR, or perhaps an issue on my end?), but the styling for what I see so far seems to match your intended change (although I cannot verify if that same styling is applicable to the numbers in parentheses, as I cannot see them.

**Comment by tsunami776** [comment]
@JeffLi117 Thanks for your feedback! I used an admin account for testing, and I currently do not have an owner account. I will ask for one to test it later.

**Comment by tsunami776** [comment]
> Hi @tsunami776 , when I checked out this PR, this is what I did.
> 
> Logged in on an Owner account→ Reports→ Weekly Summaries Report→ Select Team Code. However, this is the view that I got: image
> 
> Upon clicking either one of the two selections, they are both selected as such: image
> 
> Unsure if this is an intended change (or being addressed in another PR, or perhaps an issue on my end?), but the styling for what I see so far seems to match your intended change (although I cannot verify if that same styling is applicable to the numbers in parentheses, as I cannot see them.

Hi @JeffLi117, I tested on my owner account too. As shown in my test video, it shows all the team codes from the dropdown. It is strange that I cannot reproduce the issue you showed. My best guess is to pull the latest for BE and run `npm run build` then `npm start` to see if anything changes for you.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/aa343578-68f4-40f3-a356-eea64e10edb8

**Comment by mounica-dingari-by** [comment]
Hi @tsunami776 , I've tried to test your PR. But I can see this:

Screenshot from 2023-10-13 18-31-36

I've pulled the latest but I'm  unable to see the codes.

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and it works as intended!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/74b70835-4129-4c7a-a0ee-05bf4e86cbaf

**Comment by Vishala09** [comment]
Awesome work with minimal changes. It looks really great now. Great Job!

image

**Review by Vishala09 — DISMISSED** [review]

**Review by malikjahanzaib — DISMISSED** [review]
Hi @tsunami776, I have tested your PR locally and the "Select Team Code" dropdown looks pretty neat now. Great job!!!

Test rec:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46221334/15f22061-6f14-4a85-8ab1-c29090efc78c

**Review by shubhankarval — APPROVED** [review]
Hey @tsunami776, I have checkout your code and everything works well. The numbers in parenthesis are vertically aligned for all the codes. 
</br>
pr1

**Review by TuanDinh140194 — APPROVED** [review]
Hi! I have test your PR with my owner account. I have test the align numbers with all four tab on navbar (this week, last week, ... ). The font end look good as describe for all 4 tab. When I try to click on the team code of the Select Team Code, it seem to be freeze a little bit. But I think it is in the back end responsible. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/0c81dd1f-b653-4bb1-a84b-7b1903c3def6

**Comment by RheaWu1212** [comment]
Hi it works as expected, good job!
Screen Shot 2023-10-14 at 12 13 14
Screen Shot 2023-10-14 at 12 12 24

**Comment by Cloid** [comment]
Hi there.
I tested this by looking through all the dropdown menu options on both "Team Code" and "Color" to see if all the text is aligned. I also tested if the functionality in filters still works. Both work fine.
Tested this in both Admin/Manager roles.

image

image

**Review by Sssky-18 — APPROVED** [review]
Hi @tsunami776, I have tested the team code filter dropdown, and it worked as expected. All the numbers are in the same column, great work! 

PR#1413

**Review by JYXiao-2021 — COMMENTED** [review]
Hi, I test this pr. I log in as the owner account. I do not see the intended content. Leave my case for you to check.
Screenshot 2023-10-14 at 3 33 06 PM

**Review by StrawberryCalpico — APPROVED** [review]
Hi I tested your PR, it worked as expected. Great Job
Screenshot 2023-10-14 at 3 45 42 PM

**Review by Cloid — APPROVED** [review]

**Comment by AnishPandita** [comment]
Hey, I tested the PR and alignment seems good. Tested for smaller screens as well.
Screenshot 2023-10-14 at 2 21 08 PM

**Comment by palakgosalia** [comment]
Hey, I have tested the PR and the alignment looks good. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/104417272/31ab315f-799e-49b0-8895-9fa297b7725e

**Review by yangfan2001 — APPROVED** [review]
Hi, I have tested your PR and it works as expected. Great Job!
image

**Review by zuhang2000 — APPROVED** [review]
Working as expected!
The codes are aligning exactly the same. The alignment is good.
Screenshot 2023-10-15 at 12 44 39 AM

**Review by yi-lin-1234 — APPROVED** [review]
Hello, I tested your PR and works as intended. Great work!
Screenshot 2023-10-15 at 4 48 44 PM

**Review by DavidC0126 — APPROVED** [review]
Hi @tsunami776 I tested your PR and it works as intended!

align
color

**Review by lacnoskillz — APPROVED** [review]
Hello @tsunami776 
I pulled your code and the changes look good!
nice work
image

**Review by Chuehleo — APPROVED** [review]
The modifications works as intended, great job!
Screenshot 2023-10-19 140550

**Review by Jiyuanxia — APPROVED** [review]
Hi @tsunami776 , I have reviewed your pull request and tested it. It works as you intended. Well done!

Screenshot 2023-10-19 215120

**Comment by mounica-dingari-by** [comment]
Hi @tsunami776 , I'm unable to test your PR, since I can only see two options in the dropdown . Hence, unable to test your alignment.

Screenshot from 2023-10-20 23-20-03

**Review by Shubhu0 — APPROVED** [review]
HI @tsunami776 The reviewed the PR and it is working as intended. Good job!

image

**Review by KurtisIvey — APPROVED** [review]
Everything checks out. Implementation functions exactly as intended

pr1413 checks out

Tried my hand at centering the little checkbox input, and came up with a successful css implementation, only to then encounter the issue of the text itself being off by a few pixels. Price we pay I suppose for using a prebuilt component. Therefore, it's a non issue for me.

**Comment by one-community** [comment]
Excellent, thank you everyone! Merging!

**Pull request merged**
