### PR TITLE
Shrey Fix Team member showing already added member and limit set to 10

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Fix Teams showing members already there and limited view issue
i) Login as admin/Owner-> Other Links-> Teams-> In an existing team or create a new team -> Click on Add members icon
When the user searches for a team member to add, the search list should not show already added team members. It should only show active members not already on the team. 
ii) There should not be a limit on the number of  items that are displayed. Currently only 10 items are getting displayed

## Main changes explained:
Changed the filter in MemberAutoComplete.jsx file to add the existing member condition.
Also changed the dropdown style to fit the add team member modal, and removed the limit 10.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as admin user
4. go to Other Links→ Teams→ Select Members for a team→ Add Team member
5. verify function that if a member is already in the team, he is not visible in the add list.
6. verify that add team member list doen not have a hard limit of 10, but is scrollable if there are more users.

## Screenshots or videos of changes:
Before Change

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/3b6b22f4-cc3d-4d23-b3a0-cb6bfbf45572

After Change

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/bcee0134-b146-4da5-99e8-a40b9ff6ef2a

### CODE REVIEW

**Comment by AriaYu927** [comment]
Hi @Shreyj14 , I've tested the PR and it works as you descripted.

The user isn't visible if has already added to the team, and the user list is limited to 10 and scrollable: 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/94303659/23687427-5d6f-4f71-9451-813ca687b014

However, the users table doesn't refresh automatically after added a new user. Is that possible to maintain that refresh feature?

**Review by JeffLi117 — CHANGES_REQUESTED** [review]
When testing your PR on my Admin account, I was able to add users to my team, and was unable to search for those members already on my team (as you intended).

Added user: 
image

Trying to search for user already on team: 
image

I was also able to see more than 10 users from the dropdown as I was typing: 
image

However, the "biggest" issue I ran across that @AriaYu927 mentioned was not seeing the newly added member immediately. One must close the team pop-up window, then select that same team again, and only then can see the whole team (with newly added member). While this may be outside the scope of this PR, I think it's a significant enough issue to warrant a revision before final implementation.

A much smaller issue is that when the team pop-up is showing, there is a strange bar on the right of the screen (to the left of the scrollbar) - a visual imperfection that I noticed.
image

**Review by vikrambadhan — COMMENTED** [review]
Hi, I tested your Pr and it works as intended!
However, the issue that I came across was not seeing the newly added member of the team immediately. One has to close the tab and open the team tab again to see the changes.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/85417946/b7c2fb87-4a47-4467-9cf8-ee072f42aabb

**Comment by emunkh404** [comment]
**Test Results:**

During testing, the following issues were identified:

1. When testing, a new team is successfully created. However, when adding a new member to the created team, it displays 10 people. After adding my members, I attempted to add the same person by typing their name in the search box, and the person was found. This behavior is inconsistent with the expected result, as the person should not be found if they are already in the team.

2. Additionally, when adding a new member, the system does not provide a response indicating success or failure. A clear indication of whether the operation was successful or not would greatly improve the user experience.

3. Furthermore, when removing a member, there is no visual feedback or notification to inform the user that the action is taking place. Adding a confirmation message or some visual feedback would enhance the user experience by providing assurance that the removal action is in progress.

**Comment by olenadanykh** [comment]
Hi @Shreyj14 , I tested the PR, and it functions as expected. I successfully verified that if a member is already on the team, they are not visible in the add list. However, I noticed the same issue as others regarding newly added team members not being dynamically updated in the table. To see the updates, you have to close and reopen the table.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/49422649/1f8096a7-afa3-427c-89d9-6132cb0e5f08

**Comment by DavidC0126** [comment]
Hi @Shreyj14, I tested your PR and it works as described, but I also would want the team members to be updated dynamically after adding a new member. In addition, it would be better if any label pop up after adding or removing a member.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/74082492/f656ba01-caef-48b8-b1ab-58c1484b314b

**Comment by Jiyuanxia** [comment]
Hi @Shreyj14 , I have reviewed your pull request and tested it. It works as you intended. Good job! Just a little issue that after I add someone to the team, there is no any message saying I did it successfully or not and the page is not automatically refreshes so I have to manully refrash the page to see the change.
Screenshot 2023-09-28 220800
Screenshot 2023-09-28 220824

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @Shreyj14,

I tested your PR and works as intended. Great work!
I'm not able to view members who are currently in my team.
Searching for another member I can scroll more than 10 members.

As others have pointed out, adding a member doesn't add them to the list. I need to refresh or close the modal for the changes to reflect. 
That should be fixed. See the video for reference. 
Overall great work! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/ade7047b-9cc7-4bb7-a81b-5f71a873178f

**Comment by Shreyj14** [comment]
@Jiyuanxia @DavidC0126 The feedback regarding showing a pop-up message is not a part of this task. It was supposed to fix the already added member shown in the list to add and the limit of searched member was fixed to 10. For showing a message while adding or deleting a team member should be part of another fix.

@emunkh404 I think you need to checkout to my branch and test, because everyone else is able to test the desired changes, and are facing an issue with the list not updating instantly.

**Comment by Shreyj14** [comment]
@JeffLi117 @AriaYu927 can you guys please help me in the code to which part to fix, because I tried and I am not able to fix the render part, and there are not many changes made apart from the filter. If you can help me pin pointing where the issue might would be really helpful.
Thanks

**Pull request closed without merging**
