### PR TITLE
Shrey unit test History Modal

### PR DESCRIPTION
**Pull request by Shreyj14**
# Description
Unit tests for History Modal component

## How to test:
1. check into current branch
2. do `npm install`
3. npm test HistoryModal.test.jsx
4. verify that all tests pass

## Screenshots or videos of changes:
Screenshot 2023-12-31 at 10 17 32 AM

### CODE REVIEW

**Review by bienzguoa — COMMENTED** [review]
All test passed! Suggestion: could you add some addtional tests to verify correct data formatting and tests for modal closed? 
Screenshot 2023-12-30 at 9 49 11 PM

**Review by scoopstroop92 — COMMENTED** [review]
Hello Shrey ! good coverage on the test cases .
Kindly  update the test case path 
image

**Review by ChengyanOo — APPROVED** [review]
Hi @Shreyj14,

Excellent work on testing the History Modal! I've reviewed your testing scripts and am impressed with their clarity and structure. It's great to see that all tests have successfully passed, which speaks to the thoroughness and effectiveness of your approach.

HighestGoodNetworkApp_PR#1764_test

**Review by Alforoan — APPROVED** [review]
All tests passed and everything looks well-structuered. Nice!

image

**Comment by beblicarl** [comment]
All tests passed successfully.

image

**Review by beblicarl — APPROVED** [review]

**Comment by mianmiantea2019** [comment]
All tests passed.

image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
