### PR TITLE
Shihao - Lint Fix Weekly Summaries

### PR DESCRIPTION
**Pull request by sxiong5**
# Description
Lint Fix `src/component/WeeklySummary/**`

## Main changes explained:
- Change the code style according to ESLint and Prettier

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. log as any user
4. go to dashboard→ summary
5. check the app works as normal
6. set up ESLint and Prettier in VSCode
7. check all files in `src/component/WeeklySummary/**` doesn't have errors

## Screenshots or videos of changes:
Screenshot 2023-08-29 at 16 09 44 (2)

### CODE REVIEW

**Comment by gabi-lima** [comment]
Everything works as expected. Great job!


imagem_2023-08-30_103502179

**Review by gabi-lima — DISMISSED** [review]
Everything works as expected. Great job!
264359582-f64b22ea-56cd-492e-99be-6efaf863466e

**Review by yurisokolovicz — APPROVED** [review]
Dear @sxiong5 

I have reviewed all the files in the Weekly Summary. The components appear to be adjusted correctly. Good job!

Screenshot 2023-08-30 135941

**Comment by Arsamat** [comment]
Works as expected!
Снимок экрана (269)

**Comment by iTvX** [comment]
I tested your PR, and I didn't see any error. Good job!

CleanShot 2023-08-30 at 16 49 34@2x

**Review by Jiyuanxia — COMMENTED** [review]
Works perfectly. Well done.
Screenshot 2023-08-30 200006

**Review by DavidC0126 — COMMENTED** [review]
Hi @sxiong5 I tested your PR and it performs as expected.
PR1200

**Review by GaryB93 — DISMISSED** [review]
Verified weekly summary functionality and checked all files for any lint errors. No lint errors present.
Screenshot 2023-08-30 at 7 34 27 PM
Screenshot 2023-08-30 at 7 51 44 PM
Screenshot 2023-08-30 at 6 39 09 PM

**Review by tsunami776 — DISMISSED** [review]
I tested the PR using vscode with ESLint and prettier plugin enabled. There is no lint problem with the files in src/component/WeeklySummary/**


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/43768723/ab712efe-d579-4a2b-8880-7f4493d44b5d

**Review by ss23046 — APPROVED** [review]
Hi @sxiong5 ,
The components are adjusted correctly and checked for the errors, no errors are present. Looks good!

Screen Shot 2023-08-31 at 4 31 37 PM

**Review by yaow62023 — DISMISSED** [review]
Hi, I have tested your PR. Looks good for me, no error detected. 
Screenshot 2023-09-01 at 5 07 19 PM
Screenshot 2023-09-01 at 5 06 55 PM

**Review by robertoooc — DISMISSED** [review]
Hi @sxiong5, I tested your branch and found no issues at all. The website itself seems completely the same and the files were well linted. 

Screenshot 2023-09-01 at 6 06 14 PM

**Review by EdwinLauM — APPROVED** [review]
Hey @sxiong5! I have reviewed the code changes and have tested them as well. Everything works as expected!

Screen Shot 2023-09-01 at 9 01 53 PM

**Comment by Shreyj14** [comment]
Hi @sxiong5  code works well.
Screenshot 2023-09-02 at 2 19 26 PM
Screenshot 2023-09-02 at 2 19 09 PM

**Comment by one-community** [comment]
Thank you everyone! Resolve the merge conflicts here and I'll merge this one!

**Pull request merged**
