### PR TITLE
Bhuvan - tableFilter.jsx test cases

### PR DESCRIPTION
**Pull request by bhuvan-dv**
# Unit test for **TableFilter**  component

## Main changes explained:

Added Five new files names 
[tableFilter.test.js](src/components/Reports/TableFilter/__test__/TableFilter.test.js)

## How to test:
1. check into current branch 
 ```bash
   git checkout bhuvan-tableFilter
```
2. do `npm install` and `...` to run this PR locally

3. run this command 
```bash 
npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/Reports/TableFilter/__test__/TableFilter.test.js
```

image

## Note:
check if all the test cases pass without any errors pertaining to **TableFilter** files only

### CODE REVIEW

**Review by kdaga81 — APPROVED** [review]
image
All test cases passed!

**Review by aaryaneil — APPROVED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-07-12 at 8 37 28 PM

**Review by nyelmela — APPROVED** [review]
I have checked out the `bhuvan-tableFilter` branch, executed `npm install`, and ran the provided test command `npm run test:coverage D:/HGN/HighestGoodNetworkApp/src/components/Reports/TableFilter/__test__/TableFilter.test.js`. All tests for the TableFilter component passed successfully without any errors, as shown in the attached screenshot. The implementation is verified and meets the required standards.

image

**Review by sahithidhulipala9 — APPROVED** [review]
Test cases passed succesfully
PR 2450

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (89)
Screenshot (90)

**Review by KaushikMreddy — APPROVED** [review]
Hi, 
I've tested your PR, and all your test cases work. Good work!
image
The code is very clear and organised.

**Review by jinxyou — APPROVED** [review]
All test cases have passed! Great work! 
Screenshot 2024-07-13 134811

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and all test cases have passed. 
Screenshot 2024-07-13 174533

**Comment by nikethaanand** [comment]
All the test cases have passed as expected 
image

**Review by JatinAgrawal94 — APPROVED** [review]
All test cases passed. Good work.
Screenshot 2024-07-13 at 11 15 17 PM (2)

**Review by vijay10pk — APPROVED** [review]
All the test cases passed.
Screenshot 2024-07-15 at 2 07 12 PM

**Comment by beblicarl** [comment]
All tests passed successfully. The test covers specified scenarios

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
