### PR TITLE
Yi TaskCompletedModal unit test

### PR DESCRIPTION
**Pull request by yi-lin-1234**
# Description
Unite test for `TaskCompletedModal.jsx`

## Main changes explained:
- Add the unit test

## How to test:
1. check into current branch
2. do npm install
3. do `npm test TaskCompletedModal.test.js` to run the test
4. Verify that all 4 tests have passed

## Screenshots or videos of changes:

Screenshot 2023-12-05 at 10 00 01 PM

### CODE REVIEW

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-06 at 7 46 16 PM

**Review by ZichanYang324 — APPROVED** [review]
I have run the test, and all the test cases has passed, good job!
Screenshot 2023-12-06 at 22 39 42

**Comment by DragonSlayer2401** [comment]
I tested your PR, and all 4 tests passed. There was a warning in the terminal, but it doesn't appear to have interfered with the tests. Please watch the overview video below:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/e3feeb02-13c9-43e4-a9ac-7440a2c46a64

**Review by pika-chu11 — APPROVED** [review]
Hi @yi-lin-1234 , I have tested it and it passed! Great job!
PR 1643

**Review by Alforoan — APPROVED** [review]
Tests passed. Nice!

image

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases passed!

Week 15 - PR 1

**Comment by wanglu1207** [comment]
Screen Shot 2023-12-18 at 10 34 04 PM
All tests have passed successfully. Excellent job!

**Comment by beblicarl** [comment]
All test cases passed successfully 

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
