### PR TITLE
Fixed alignment issue with time off icons

### PR DESCRIPTION
**Pull request by pavanswaroopl**
# Description
A. Fixes # (PRIORITY LOW) Jae: Fix alignment of the scheduled time off icon (WIP Pavan)

## Related PRS (if any):
This frontend PR is not related to the any backend PR.
…

## Main changes explained:
Added alignment attributes to style.css file in order to remove any further alignment issues with time off icons
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to dashboard→ Tasks→ look for timeoff icons
6. verify function “A” (feel free to include screenshot here)
7. verify this new feature works in [dark mode]

## Screenshots or videos of changes:

https://github.com/user-attachments/assets/f4ca85a0-5d2b-4ead-86ce-561c760fc06c

Screenshot 2024-08-03 at 7 35 40 PM
Screenshot 2024-08-03 at 8 09 45 PM
Screenshot 2024-08-03 at 8 09 54 PM
Screenshot 2024-08-03 at 8 10 05 PM

### CODE REVIEW

**Review by manikittu810 — COMMENTED** [review]
Hello @pavanswaroopl 
Here , in the below screenshot i was trying to move the page to the left side, but i wasn't able to do it . I have cleared my cache and tried multiple ways . 
Screenshot 2024-09-05 at 3 06 48 PM
Thank you.

**Review by CillianRen — COMMENTED** [review]
On my computer, it still needs to be extended to make sure all items are fully visible on the page.

https://github.com/user-attachments/assets/5281989e-de3e-4b09-a993-c09ed5689857

**Review by nikhilpittala16 — CHANGES_REQUESTED** [review]
I have tested the PR and it's not working as expected. the icon is being split in half. please fix it. 

https://github.com/user-attachments/assets/085a7f24-604b-4808-b543-076d7764f860

**Review by Jingyii800 — CHANGES_REQUESTED** [review]
Hi, I have tested this function, but it didn't work as expected, the icons are not aligned well when the width of the screen decreasing.

https://github.com/user-attachments/assets/de489483-fdb3-4995-a3bd-7c3cb2ae22b9

**Review by AJAYINAVOLU — CHANGES_REQUESTED** [review]
Changes are not working as expected. The icons are getting cut when resized.

image

**Review by sri0606 — CHANGES_REQUESTED** [review]
@pavanswaroopl , Alignment of icons is still off on many screen dimensions. Plase update the styling.
Screenshot 2024-09-06 131337
Screenshot 2024-09-06 131438

**Review by mohangadde1 — CHANGES_REQUESTED** [review]
Screen Shot 2024-09-07 at 01 13 25
Not working as expected. Icons are not fully visible.

**Review by panchalvatneu — APPROVED** [review]
image
image
image
Changes working as expected on different sizes.

**Review by Gauravmg6 — CHANGES_REQUESTED** [review]
Alignment is not working for smaller screens. Please take a look.
Screenshot 2024-09-08 020014

**Pull request closed without merging**
