### PR TITLE
Dhrumil save message and darkmode fix

### PR DESCRIPTION
**Pull request by ddshah878**
# Description
In the Badge Management full-view history, the header row is not visible in Dark Mode, and saving a badge does not display any confirmation message.

## Related PRS (if any):
Related PRs: https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2569 and https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/2825
…

## Main changes explained:

- Added a confirmation message for badge saves.
- Fixed color contrast issues in Dark Mode for improved visibility.

## How to test:

1. Check into the current branch
2. Do npm install and ... to run this PR locally
3. Clear site data/cache
4. log as admin/owner
5. Go to View Profile → Select Featured
6. Switch to Dark Mode
7. Verify that the header row is visible.
8. Click on save changes and check for the confirmation message: "Badges saved successfully."

## Screenshots or videos of changes:
Before: -
https://github.com/user-attachments/assets/c02e5234-63e1-4b6a-bf63-4a88253d28ab

After:-
https://github.com/user-attachments/assets/6c3dfc07-4fed-40c5-b0e5-aec6907cae9d

### CODE REVIEW

**Review by vijay10pk — APPROVED** [review]
Changes are working as expected.
image

**Review by nikhilgiri0226 — APPROVED** [review]
I have reviewed the PR and the fix works as expected. The header in the dark mode is looking fine now.

image

**Review by aaryaneil — DISMISSED** [review]
Tested the PR and the changes work as expected. The header is displayed properly in dark mode and the confirmation pops up on saving changes correctly.
Screenshot 2024-11-16 at 11 40 05 AM
Screenshot 2024-11-16 at 11 40 14 AM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
