### PR TITLE
Roberto- fixes intangible time entries round to 2nd decimal place

### PR DESCRIPTION
**Pull request by robertoooc**
# Description
The intangible time entry time in a user profile is not rounded to 2 decimals.
Screenshot 2023-11-21 at 4 32 45 PM

## Related PRS (if any):
Use latest backend dev 

## Main changes explained:
- Added logic to VolunteerTimesTab.jsx to prohibit user from entering value into input with more than 2 decimal points.
- To TimeEntryForm.jsx, UserProfile.jsx, and DeleteModal.jsx added basic logic to round the intangible time.
- Removed userProfile value from props in DeleteModal.jsx and retrieved that value from redux state, fixes a deleting time entry problem not updating the hours correctly.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as any user
4. go to your profile page
5. verify that the intangible time if any is rounded properly.
6. go to timelog → add some intangible time → go back to your profile
7. verify that the changes resulted in rounded time accordingly.
8. verify that removing intangible time entries works as well.

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/117053202/f448395c-96b7-4e5d-93ec-969bf6c69402

## Note:
Switching the tangibility of existing time might result in the intangible hours being affected poorly. - Looks like another developer is working on a pr for this.

### CODE REVIEW

**Review by lichanghaogit — DISMISSED** [review]
Hi @robertoooc 
Thank you for submitting this PR, I tested the time entry on my local machine using volunteer account. All functions as expected, nice work!

Screenshot 2023-11-22 at 10 01 04 AM
Screenshot 2023-11-22 at 10 01 14 AM

**Comment by ptrpengdev** [comment]
Hi @robertoooc, I have tested this PR with the Admin role. The rounding feature works as expected. Great work! 

Screenshot attached.

image

**Review by Alforoan — DISMISSED** [review]
It worked as intended. Nice!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118868270/641e30ce-5e57-4cb9-ab97-d85a95c1c380

**Review by keyunhuangg — APPROVED** [review]
1) Add intangible time for 59 mins which is 0.9833333 hours. 
2) Verified that in dashboard was rounded to 0.98
3) Verified that in profile->volunteer-hour was rounded to 0.98
Screenshot 2023-12-15 at 2 01 46 PM
Screenshot 2023-12-15 at 2 02 34 PM

**Review by Renanluizssx — COMMENTED** [review]
Hi @robertoooc, i reviewed your application and i had some issues, apparently the timelog is correct, but i didn't get to return to the dashboard, the site turns white, and i didn't get to return to the dashboard or another menu, i cleaned the cache in the browser before i logging in.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/f205ae82-bf5d-4689-a4a9-4075422d4924

**Review by 666saofeng — APPROVED** [review]
Hi, I tested with volunteer and admin account. It works as expected.

Uploading HGN APP - Google Chrome 2024-01-26 10-15-02.mp4…

**Review by yvonnep165 — COMMENTED** [review]
Hi @robertoooc ,

I have followed the instruction to run the code with admin, mentor and manager accounts but I got a 400 error when trying to submit the time as below:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/0a141ffc-2923-4627-81bc-3e0f3798138e

**Comment by galgalinidhi** [comment]
Hi @robertoooc, I tested the PR using the Admin and Volunteer accounts but I get the following error-

PR 1572 1

PR 1572 2

**Review by SRamen1999 — APPROVED** [review]

**Review by SRamen1999 — CHANGES_REQUESTED** [review]
I have tested this PR using the Admin role.

When adding new intangible time I keep getting an error.

Screen Shot 2024-01-29 at 9 25 34 PM

**Comment by robertoooc** [comment]
@Renanluizssx, @yvonnep165, @galgalinidhi, @SRamen1999 
All of these errors seem to be caused due to this branch being old and outdated, it has just been updated. Please try again and make sure everything works well.

**Comment by 666saofeng** [comment]
> Hi, I tested with volunteer and admin account. It works as expected.
> 
> Uploading HGN APP - Google Chrome 2024-01-26 10-15-02.mp4…

Uploading HGN APP - Google Chrome 2024-01-26 10-15-02.mp4…

**Review by Pandani07 — CHANGES_REQUESTED** [review]
Works as intended. Logged in with my admin account and the intangible time was rounded off to 2 decimal places. I added more intangible time and that was rounded as well.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/2734e609-d638-4754-83a7-e5ad6fbebce3



But the tasks part of the dashboard page has been blacked out for some reason

Screenshot 2024-02-01 at 11 51 59 AM

**Review by yvonnep165 — APPROVED** [review]
Hi @robertoooc ,

I have tested this PR with manager, owner, mentor and volunteer accounts as below. When I added the intangible time, it rounded to 2nd decimal correctly in the profile page.  Nice work!


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/8858d222-93d1-43ab-aec6-f3e6640146f9

I also verified that removing intangible time entries works for these accounts.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/103622026/4139ddcc-3a59-435d-ae06-776414d6cebe

**Review by Sophie-lei — APPROVED** [review]
Hey, I just tested this PR review. the intangible time can be entered 2nd decimal. Everything works as expected. please view the video for details.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/70113822/e4141b47-242e-4ecb-9788-8f18a4627174

**Review by KevHnh — APPROVED** [review]
I tested using an owner account and the changes work as expected. The intangible time rounds properly to the 2nd decimal place. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/83934825/a52655db-19af-413d-bf7e-c2813f457b74

**Comment by one-community** [comment]
Thank you all, moving to final review.

**Comment by robertoooc** [comment]
@Pandani07, is this something you are able to replicate again, I have not ran into this issue at all. 

I assume the team member task list is just taking a long time to load but that's a different backend problem not targeted with this pr, but It should have a skeleton loading not be completely dark like that. 

Do you have any dark mode extensions that might affect this and make it look like this? If not, is there anything in your console?

**Review by cvtqx — APPROVED** [review]
Everything works as described. Intangible hours are rounded off correctly and deletion of time entries also works well.

Adding an intangible time entry:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/f79a1e58-f4d0-413f-95fc-28bc403cf9f9

Deleting an intangible time entry:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/43a35508-acde-4fd7-9139-d45294112e5b

**Pull request merged**
