### PR TITLE
Aditya-Added-Testing-for-Login

### PR DESCRIPTION
**Pull request by adityasure9**
# Description
This PR introduces unit tests for the `Login` component, focusing on testing the structure of the login page, handling user input, and ensuring correct login behavior. These tests cover input field changes, form validation, and the submission process to ensure that the `Login` component functions as expected.

## Main changes explained:
- **Created** `Login.test.jsx` to introduce unit tests for the `Login` component.
- **Tested** the structure of the login page, ensuring correct rendering of inputs, buttons, and headers.
- **Simulated** user interactions such as typing into input fields and submitting the login form.
- **Validated** form submission logic, ensuring the correct function (`loginUser`) is called with the right credentials.
- **Checked** if errors are properly handled and displayed when form inputs are invalid or incomplete.

## How to test:
1. Check into the current branch.
2. Run `npm install` to install dependencies.
3. Run `npm test Login.test.jsx` to execute the unit tests.
4. Ensure all tests pass, including structure validation, input handling, and login behavior.

## Screenshots or videos of changes:
image

### CODE REVIEW

**Review by Lexie5212 — APPROVED** [review]
I tested the PR, all tests passed!
Screenshot 2024-09-27 at 21 04 51

**Review by jinxyou — APPROVED** [review]
All test case have passed. Great work
Screenshot 2024-09-27 211308

**Review by ziyanw52 — APPROVED** [review]
I have test this, and all the test cases passed.
571727502471_ pic_hd

**Review by linkhanthtel — APPROVED** [review]
All test cases passed as expected! Nice work!

**Review by Vincent-space — APPROVED** [review]
Hi, I tested all cases, all of them passed.
image

**Review by Nahiyan-16 — APPROVED** [review]
Hi Aditya, great job on the initial tests for the Login page! Your tests are well-organized and cover important features like the page layout, input handling, and login actions. Using both `shallow` and `mount` rendering helps get more accurate results by simulating the component behavior properly. The focus on error handling and updating the state, especially for form validation and submission, is excellent and makes your tests more reliable. Overall, these tests are a strong start for ensuring the Login page works correctly.

Screenshot 2024-09-28 131135

**Review by Dk-21 — APPROVED** [review]
PR 2734
@adityasure9 
Tested the test file and all the test cases passed.
PR 2734

**Review by ishangoel17 — COMMENTED** [review]
All test cases are passing. Below is the screenshot for reference:
Capture2734

**Review by Watchdog00 — COMMENTED** [review]
I have completed the testing and got the expected results. Good job!

**Review by Muzammil603 — APPROVED** [review]
image
Results as expected

**Review by aaryaneil — COMMENTED** [review]
Tested the PR and all the test cases passed.
Screenshot 2024-09-28 at 8 59 19 PM

**Comment by tharunaa-1** [comment]
All the test cases passed.

image

**Review by Vigneshwar-Muriki — APPROVED** [review]
Tested this PR and all test cases passed successfully.

**Review by Vincent-space — APPROVED** [review]
Hi, all test cases passed.
image

**Review by nikhilpittala16 — APPROVED** [review]
I have tested the PR and all the test cases have passed.
Screenshot (218)

**Comment by geetamatkar** [comment]
I tested this PR. All test cases have passed.

PR2734

**Comment by mianmiantea2019** [comment]
All test cases have passed.

image

**Review by manikittu810 — APPROVED** [review]
Hello @adityasure9 
Everything is working as mentioned.
Screenshot 2024-10-18 at 10 12 17 AM

Thank you.

**Comment by SatyashanthiT** [comment]
I have reviewed this PR, which introduces unit tests for the Login component. The tests effectively cover key areas such as input handling, form validation, and login behavior. After running the tests as outlined, everything works as expected, with no issues detected during the review process.
image

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
