### PR TITLE
Jacob - Completed fixing the badge management feature

### PR DESCRIPTION
**Pull request by DragonSlayer2401**
# Description
image

## Related PRS (if any):
N/A

## Main changes explained:
- Change badge assigning to use ID instead of name

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin user
5. go to Other Links → Badge Management
6. assign a badge to a user that has the same first and last name as another user
7. verify the badge was assigned to only one of the users 

## Screenshots or videos of changes:
Before:
Image

After:
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/102876103/8086b343-98ca-4c5e-8755-2222912be771

### CODE REVIEW

**Review by ChengyanOo — APPROVED** [review]
Hi @DragonSlayer2401, 

I've thoroughly tested your recent changes and am happy to report that everything is working perfectly. The code is also notably clean and well-organized. Great job!Attached is a screenshot of the successful test outcomes for your reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/69735000/02c0dc68-8779-462e-8938-e7078743d539

**Review by Nahiyan-16 — APPROVED** [review]
## Good job Jacob!
The code is very well written and formatted.
Created two users with the same first name and last.
Assigned badges to one of them. 
Upon logging into both users, it looks like only one has badges added to them while the other one has none. Works perfectly fine.
I should mention that there needs to be a better way for the admin to distinguish two users with the same name when searching for them in 'badgemanagement'

[demonstration.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/71025942/fa805423-2295-4ec8-8d34-de466b940e18)
Screenshot 2024-01-23 154422

**Review by X1aoZhang99 — APPROVED** [review]
Hi Jacob,

I have tested your PR with 2 volunteer users whose names are the same. When I assign badges to one of the users, the badge doesn't appear in another user's profile. Nice work! 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/113070229/cbc1547c-ef14-481e-91f9-06cbf27634f0

**Review by Pandani07 — APPROVED** [review]
I tested this PR and the functionality works as intended. In the case of users with the same first and last name, only the selected user will get the badge. I have attached a video and photos showing this, great job!

Screenshot 2024-02-06 at 1 06 38 PM
Screenshot 2024-02-06 at 1 06 19 PM

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44672833/619e721b-2fde-4c0b-8317-a96bc5492793

**Review by swathyjayaseelan — APPROVED** [review]
The changes look good.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13806470/71fcfa20-f7b1-4e7e-9693-df2d7845138d

**Review by mohabbasd — APPROVED** [review]
Hello, I tested you PR, I encountered a lot of bugs while searching in the reports page for a user but ultimately it was working just like you it was mentioned. But please look into those bugs.
Screenshot 2024-02-13 at 12 52 05 AM
Screenshot 2024-02-13 at 12 52 29 AM
Screenshot 2024-02-13 at 12 52 37 AM

**Comment by DragonSlayer2401** [comment]
> Hello, I tested you PR, I encountered a lot of bugs while searching in the reports page for a user but ultimately it was working just like you it was mentioned. But please look into those bugs.
> 
> Screenshot 2024-02-13 at 12 52 05 AM
> 
> Screenshot 2024-02-13 at 12 52 29 AM
> 
> Screenshot 2024-02-13 at 12 52 37 AM
> 
> 

Is one image from the development branch and the other the PR? I didn't modify the code on that page in anyway.

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Review by 666saofeng — APPROVED** [review]
Using two volunteer participants with identical names, we observed that when a badge is allocated to one participant, it does not subsequently appear in the profile of the other participant.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62363348/2ce8115f-b033-4392-b167-fc5aa3d36b49

**Review by Renanluizssx — APPROVED** [review]
Hi @DragonSlayer2401 , i reviewed your application and it's working as well, good job:


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/91035340/41be017b-f0aa-4e18-8b6f-20d2651b5ea4

**Pull request merged**
