### PR TITLE
Jiayu Add WBS icon in userprofile page projects

### PR DESCRIPTION
**Pull request by peter6866**
# Description
image

## Related PRS (if any):
Use the development branch of backend to test this PR.

## Main changes explained:
- Updated `UserProjectsTable.jsx` to include WBS icon for users with `postTask` permission.

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. Clear site data/cache
4. log as admin/owner user or user with `postTask` permission
5. go to dashboard→ Profile→ Projects tab
6. verify function “A” (feel free to include screenshot here)
7. verify that you can see and click the wbs icon to navigate to the wbs page according to the project
8. verify that you can see the mouseover text of the wbs icon when you hover on it

## Screenshots or videos of changes:
image

image

### CODE REVIEW

**Review by Logeshwari-Renu — DISMISSED** [review]
I have tested the PR and verified the WBS column availability to right of Project Name.  Selecting the icon redirects to WBS page and Mouse hover info  is displayed correctly!!

**Review by pavanswaroopl — DISMISSED** [review]
Hello,

Excellent work, code looks clean and good, and also the functionality works perfectly fine.
Screenshot 2024-06-29 at 5 33 07 PM
Screenshot 2024-06-29 at 5 35 26 PM

**Review by cvtqx — DISMISSED** [review]
Tested this from an owner's account and the functionality works as described. I can see the WBS icons next to a project name and when hovering over a WBS icon a tooltip with description text appears. When clicking on a WBS icon I was directed to the WBS page for the respective project.

Screenshot 2024-06-29 at 7 02 40 PM


Screenshot 2024-06-29 at 7 02 53 PM

I then logged in as volunteer (user without posttask permission) and the above icon did not show up in the projects list.

**Review by jennZhang93 — DISMISSED** [review]
Tested with admin account. I can see the mouseover text and also able to see the project detail page. Good work! 

 Screenshot 2024-06-29 at 7 01 28 PM
Screenshot 2024-06-29 at 7 01 53 PM

**Comment by agryash** [comment]
Verified the addition of the WBS icon. Changes work as expected.

image

**Review by yash-lbs — APPROVED** [review]

**Review by agryash — DISMISSED** [review]

**Review by JatinAgrawal94 — DISMISSED** [review]
Logged in as Owner Account.
WBS icons are visible under  profile->projects.
WBS of the specific project page is visible.
ON using the back button on the WBS page, it takes us to list of projects instead of profile page. Please fix that.
Rest everything looks great.


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/47699187/fe64417d-1014-439e-ad49-4d56cdf1df25

**Review by Parth-tech — DISMISSED** [review]
Hey Jiayu,
The required functionality is met and the codebase looks great.
Great job!

`Reference:`

Screenshot 2024-06-29 at 4 32 24 PM

Screenshot 2024-06-29 at 4 32 13 PM

**Review by jinxyou — DISMISSED** [review]
I tested that I can see the wbs icon, and if I click it, it will navigate to the wbs page. Also the mouseover text is working fine. Great work!
Screenshot 2024-06-29 193024
Screenshot 2024-06-29 193033

**Comment by peter6866** [comment]
> Logged in as Owner Account. WBS icons are visible under profile->projects. WBS of the specific project page is visible. ON using the back button on the WBS page, it takes us to list of projects instead of profile page. Please fix that. Rest everything looks great.
> 
>  2402.mp4

Hi @JatinAgrawal94 ,
I believe this is not related to this PR as the back button on WBS page is designed to navigate to the Projects page as shown by the text. 
image

**Review by AnujVakil — APPROVED** [review]
Looks good to me 🚀

**Review by HowieMiao — DISMISSED** [review]
Tested PR, changes working as intended, projects tab, WBS interactable and hover text is as expected.

image

Problem I am running into is when cookies are stored that I am running dark mode, the site does not render, after clearing, there is no dark mode toggle button. Back-end is on Development Branch and Front End on 2402 PR

image

**Review by vishavk1992 — APPROVED** [review]
i have tested this PR and confirmed the WBS column availability and Mouse hover info is displayed correctly,  after  Selecting the icon redirects to WBS page .

PR-2402
PR-2402-1

**Review by Trip2310 — APPROVED** [review]
Tested this PR as an owner and the functionality works perfectly and looks clean. When hovering on WBS icon showing tooltip and after clicking on a WBS icon I was directed to the WBS page.
PR_2402
PR_2402a

**Comment by peter6866** [comment]
> Tested PR, changes working as intended, projects tab, WBS interactable and hover text is as expected.
> 
> image
> 
> Problem I am running into is when cookies are stored that I am running dark mode, the site does not render, after clearing, there is no dark mode toggle button. Back-end is on Development Branch and Front End on 2402 PR
> 
> image

Hi @HowieMiao , are you approving this PR?

**Comment by beblicarl** [comment]
This functionality works as intended and the code is great

image

**Review by beblicarl — APPROVED** [review]

**Review by nikhilpittala16 — COMMENTED** [review]
I have tested the PR with an admin account.  The WBS icon is available on the right of the project name and clicking the icon takes us to the WBS page. Mouse hover info is accurate. Overall the code looks clean and the functionalities work perfectly fine. 
Screenshot (2)
Screenshot (3)

**Review by nikhilpittala16 — APPROVED** [review]

**Comment by Vigneshwar-Muriki** [comment]
Tested using owner account and the functionality works as expected. I was able to see WBS icon next to project in the profile page. When hovered, it displays a message. When clicked it navigates to the WBS page of that particular project. Overall code looks good.
Screenshot 2024-07-04 163648
Screenshot 2024-07-04 163823
Screenshot 2024-07-04 164817

**Review by Vigneshwar-Muriki — APPROVED** [review]

**Review by KaushikMreddy — APPROVED** [review]
Hi Peter, 

The WBS button on the project section of the profile page works perfectly. Dark Mode works as well. Goof work!
image

**Comment by KaushikMreddy** [comment]
@peter6866 , Please merge development into this branch, The line 520 in TimeentryForm.jsx file needs to be commented. The page does not load if this change is not made.
image

**Review by MinSun0814 — APPROVED** [review]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/145076494/758e4a33-b4e5-456b-bcf6-65d1c0da8abe

The changes work as intended. I can see the icon which correctly navigates to wbs page now. Nice work.

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
