### PR TITLE
TuanDinh_WbsTable.jsx_UnitTest

### PR DESCRIPTION
**Pull request by TuanDinh140194**
# Description
Create the Unit Test for WbsTable.jsx

## Main changes explained:
- Add new file WbsTable.test.js
- I have Added 8 test cases to test the WbsTable component
- In the test file, I have check if WBS items are rendered. Next check if all table headers are rendered. Ensure WBS items within specified range are rendered. Check if the IDs are truncated when window width is less than 1100. Check if the component renders enough WBS items, Finally, check if component renders "Active" and "Inactive" icon correctly.
…

## How to test:
1. check into current branch
2. do `npm install` 
3. do `npm test WbsTable.test.js to run the test
4. Verify all 8 test cases have passed

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/81892917/586c5650-ab6a-4dfb-b127-5d2c60f30485

## Note:
Include the information the reviewers need to know.

### CODE REVIEW

**Review by lacnoskillz — APPROVED** [review]
Hello @TuanDinh140194 
I pulled your changes and ran your test and all passed!
Nice work

image

**Review by scoopstroop92 — APPROVED** [review]
Hello @TuanDinh140194  good work on the test cases. You have covered all possible cases in your test

**Review by Hemsharavanan — APPROVED** [review]
- Great work with eight test cases validating different aspects of the WbsTable component, ensuring rendered content, correct headers, pagination, responsive behavior, and icon display.
- Your tests are well-organized, addressing specific functionalities and scenarios, making the codebase more robust.
- You have followed best practices by utilizing queries like getByText, queryByText.
- Overall tests effectively cover diverse aspects of the WbsTable component, ensuring content rendering, pagination, responsiveness, and icon display for active and inactive items. 
PR #1580 TuanDinh_WbsTable jsx_UnitTest

**Review by vikrambadhan — APPROVED** [review]
Hi, I tested your PR and all the test cases ran! good work!

Week 13 - PR8

**Comment by palakgosalia** [comment]
Hey, I tested your PR and all test cases ran successfully. Thank you

image

**Review by sahilpatel18 — APPROVED** [review]
All test cases passed successfully. Great work! 

Screenshot 2023-12-01 at 2 37 26 PM

**Review by ZichanYang324 — APPROVED** [review]
I have run this unit test and all 8 cases have passed successfully, good job.
Screenshot 2023-12-01 at 3 22 18 PM

**Review by Alforoan — COMMENTED** [review]
All tests passed. Nice!

image

**Pull request merged**
