### PR TITLE
Ajay - fix optimize total projects people teams page

### PR DESCRIPTION
**Pull request by AJAYINAVOLU**
# Description
This PR introduces frontend changes to optimize the reports page while displaying the graphs for total projects, people, and teams reports. Previously, the frontend made unnecessary API calls to the backend, wasting resources and resulting in slow page loading times. I have optimized the component structure and modified the data-fetching logic to ensure only essential API calls are made. This reduces the load on the server, improves data rendering speed, and enhances the overall user experience on the reports page. I have also resolved the issue of zeros appearing in the graph by applying a filter to exclude zero values.
Fixes issue: (PRIORITY HIGH) - Jae: Fix Show Total Project/People/Team reports.

## Related PRS (if any):
This frontend PR is related to the [#1119](https://github.com/OneCommunityGlobal/HGNRest/pull/1119) backend PR.
To test this fronted PR you need to checkout the [#1119](https://github.com/OneCommunityGlobal/HGNRest/pull/1119) backend PR.
…

## Main changes explained:
- Update src/actions/userManagement.js: Updated actions to fetch and manage basic user profile information, reducing the size of user-related data.
- Update src/components/Reports/Reports.jsx: Refined data-fetching logic and component structure to minimize unnecessary API calls, improving page load performance.
- Update src/components/Reports/TotalReport/TotalPeopleReport.jsx: Optimized the rendering logic for people reports by using the new API endpoints and managing the state more efficiently.
- Update src/components/Reports/TotalReport/TotalProjectReport.jsx: Integrated the new project reports API, reducing the amount of data fetched and optimizing graph rendering.
- Update src/components/Reports/TotalReport/TotalTeamReport.jsx: Enhanced data management for team reports, utilizing optimized API calls to decrease response time.
- Update src/constants/userManagement.js: Added constants for new API endpoints and actions, ensuring consistent use across the application.
- Update src/reducers/allUserProfilesBasicInfoReducer.js: Implemented a new reducer to handle basic user profile data, minimizing state complexity and improving performance.
- Update src/reducers/index.js: Integrated the new basic info reducer into the root reducer, facilitating better state management.
- Update src/utils/URL.js: Updated URL utility functions to include new API endpoints for optimized data retrieval.

## How to test:
1. Check into the current branch and the [#1119](https://github.com/OneCommunityGlobal/HGNRest/pull/1119) backend PR.
2. Do **npm install** and **npm run start:local** to run this PR locally.
3. Clear site data/cache.
4. Log in as an owner-user.
5. Go to dashboard→ Reports → Reports.
6. Verify that the page is rendered and the number of projects, people, and teams are shown.
7. image
8. Click on the "Show Total Project Report" button.
9. Verify that the graph is rendered and the number of projects and tangible hours are shown.
10. image
11. Click on the "Show Total People Report" button.
12. Verify that the graph is rendered and the number of members and tangible hours are shown.
13. image
14. Click on the "Show Total Team Report" button.
15. Verify that the graph is rendered and the number of teams and tangible hours are shown.
16. image

## Note:
The page load time has been significantly reduced; however, please note that the page and graphs still take around 5 seconds to render. A message is displayed during this period to inform users of the loading status.
image

### CODE REVIEW

**Review by Dk-21 — CHANGES_REQUESTED** [review]
PR 2724
@AJAYINAVOLU 
I tested the code changes.
I used the owner account still
1. Total Number people is 0
2. No graph showing on Show Total Project Report
3. App crashes while clicking on Show Total Team Report.

PR 2724(2)
PR 2724

**Review by manikittu810 — DISMISSED** [review]
Hello @AJAYINAVOLU 
Everything is working as mentioned.

Screenshot 2024-09-27 at 4 31 20 PM
Thank you.

**Review by ishangoel17 — COMMENTED** [review]
Verified the PR and the changes are working as expected. The graphs are rendering as expected and the loading message is also visible while the graphs are loading. Below are the screenshots for reference:
Capture2724_1
Capture2724_2
Capture2724_3
Capture2724_4

**Review by nikhilgiri0226 — DISMISSED** [review]
I did the review of this PR. Everything was working as expected. However the graph was not aligned to the right of the screen, it was present at the bottom of the screen. It might be because of the screen size.

When I went to dashboard→ Reports → Reports, the number of projects, people, and teams were visible.

Screenshot_2724_Projects_People_Teams


When I clicked on the "Show Total Project Report" button, the graph was rendered and the number of projects and tangible hours were visible.

Screenshot_2724_Project_Report


When I clicked on the "Show Total People Report" button, the graph was rendered and the number of members and tangible hours were visible.

Screenshot_2724_People_Report


When I clicked on the "Show Total Team Report" button, the graph was rendered and the number of teams and tangible hours were visible.

Screenshot_2724_Team_Report

**Review by Saniya98 — APPROVED** [review]
Everything is working as expected

**Pull request merged**
