### PR TITLE
Task notification on adding and editing a task with modal differences

### PR DESCRIPTION
**Pull request by esk47**
### Before testing
1. Pull this [PR on HGNRest](https://github.com/OneCommunityGlobal/HGNRest/pull/166)
2. Make sure to run 'npm install' and 'npm run build' on backend.
3. Pull this PR.
4. Make sure to run 'npm install' on frontend

### Test adding task:
1. Add a task (make sure to assign it to a user in the currently logged in user's team - otherwise it shouldn't show up)
5. Go to dashboard and find user/task - it should have a red bell next to it.
6. Click on the red bell to open a modal that shows the differences

### Test editing task:
1. Edit a task (again, make sure to edit a task that belongs to a person on the team of currently logged in user)
2. Go to dashboard and find user/task - it should have a red bell next to it.
3. Click on the red bell to open a modal that shows the differences

### CODE REVIEW

**Comment by EvianTan** [comment]
This PR is very impressive!!! The notification func is super clean and clear 👍 
The "add new task" notification part is perfect, as for the "edit existing task" notification part, I do find several details that can be improved based on our design doc:

1. About "User can view other's notification, but cannot dismiss it."
a.) I feel you can just get rid of this "Mark as read" button when user view other's notification, instead of keeping it but it doesn't do anything after clicking.
b.) "Mark as read" button doesn't work for people want to dismiss himself or herself task notification.
image

2. About "task info changes"
a.) I know below image is the before and after task info table, but they look totally same to me.
b.) "Assigned" field, use "yes or no" instead of "true or false" would be more meaningful and also match the task table when you create or edit.
image

**Comment by esk47** [comment]
> 1. About "User can view other's notification, but cannot dismiss it."
>    a.) I feel you can just get rid of this "Mark as read" button when user view other's notification, instead of keeping it but it doesn't do anything after clicking.

Good point! I forgot about that.

>    b.) "Mark as read" button doesn't work for people want to dismiss himself or herself task notification.

Yeah, I hadn't implemented that yet when I made the PR. This PR was only for making the red bell appear when a task is added or edited.
I worked on that this week and I just added it to the PR.

> 2. About "task info changes"
>    a.) I know below image is the before and after task info table, but they look totally same to me.

I probably should include a header comment explaining what each color means.

- Black = not changed
- Green = added
- Red with strikethrough = deleted

Does that make it clear?

>    b.) "Assigned" field, use "yes or no" instead of "true or false" would be more meaningful and also match the task table when you create or edit.

Good idea

**Comment by EvianTan** [comment]
About the 2.a, I get your color logic here. I think it's more about a UI design problem. In my mind you can go either two ways when clicking the red bell sign:
1. Task info changes with one table. In this table it will have black/green/red part.
2. Task info changes with two tables. The first one is before one, totally black; the second one is after one, with black/green/red part.

**Comment by EvianTan** [comment]
About the merge conflicts things, I just checked there only three PRs changes you need take 
[give different users different views](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/438/files)
[implement three clock icons](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/441/files)
[implement progress bar](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/467/files)
None of them is huge change, so solving merge conflicts won't be that bad 😄

**Comment by esk47** [comment]
I just added all the changes we talked about. I'll try to fix the merge conflicts tomorrow

**Comment by EvianTan** [comment]
The merge work is great! Woohoo! 👍 

I found couple things still confused :
1. About task info changes table
a.) Sometimes I got 3 task info tables, sometimes I got 2, sometimes I only get 1. Pretty weird for me...don't know what's going on(see below images)
b.)For the "No changes", "Deleted" and "Added" description, can you be more clear like "Note: black texts mean no changes for this task; ~~red strikethrough texts~~ mean have been deleted; green text mean newly added".
c.) Like I said above, we can get rid of "Mark as read" button for non-self user.
d.) I changed "Classification", but it only shows newly added green without a red strikethrough of previous classification.
image
image
image

2. For current user "Mark as read" button still doesn't work for dismissing notification
If it's not the scope of this PR in your plan, just let me know. 😄 

3. Management-dashboard content is missing for manager/mentor/core team/volunteer user
I suppose it's just a merge problem, you can see this [PR]
(https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/438/files)
manager/mentor user should see same people like leaderboard on below image
core team/volunteer user should only see core team/volunteer in the same group
image

**Comment by esk47** [comment]
I completed all the changes you pointed out.👍

The "Mark as Read" button is working for me, did you make sure to pull the backend update, npm install, build, and run?

**Comment by EvianTan** [comment]
Awesome work!

Verified changes:
1. More clear explanations for black/red/green texts ✅ 
2. "Mark as read" button removed for non-self user when click the task info bell sign ✅ 

Things need to fixed before this PR closed:
1. Non-admin/owner user management-dashboard is totally empty ❗ 
We need to make this work in this PR, either it will be pushed to Dev and Main.
image

Things may take too much time to dig/fix, consider filing into a bug:
1. All changes info shows one table version ❓ 
When logging as owner/admin, you can check the bell of "16 Test add hours Field Task", it shows three duplicate changes tables; while "1 David Task test 1111" bell has two duplicate tables

Bugs need filed:
1. "Mark as red" button need refresh to effect (Both of us agreed on that 😄 )

**Comment by esk47** [comment]
> Things need to fixed before this PR closed:
> 
> 1. Non-admin/owner user management-dashboard is totally empty ❗
>    We need to make this work in this PR, either it will be pushed to Dev and Main.

Fixed. Good catch!

> Things may take too much time to dig/fix, consider filing into a bug:
> 
> 1. All changes info shows one table version ❓
>    When logging as owner/admin, you can check the bell of "16 Test add hours Field Task", it shows three duplicate changes tables; while "1 David Task test 1111" bell has two duplicate tables

Definitely a bug that should be filed. Could you add that to the bug doc and/or the management dashboard outline doc with steps on how to reproduce it? I can't recreate it.

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
