### PR TITLE
update circleci config

### PR DESCRIPTION
**Pull request by EvianTan**
# Description
This PR is a part of re-enabling ESLint for the whole repo.
image

## Related PRS (if any):
#527 I disabled it in this PR

## Main changes explained:
Just update the circleCI configuration

## How to test:
Technically nothing you can test from your local, but you still can use the same procedure to make sure this PR didn't break anything.
1. check into current branch
2. do npm install and ... to run this PR locally
3. log as any user account
4. test if any function work as normal, which means nothing break because of this PR.

## Screenshots or videos of changes:
N/A

## Note:
If anyone is interested in re-enabling ESLint things, just let me know.

### CODE REVIEW

**Comment by Shreyj14** [comment]
Hi @EvianTan at the start the functionality works properly, but on the dashboard page, it seems to break. The page becomes unresponsive. I have attached the video. If no one else is facing this issue then please ignore it.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/118795427/311c01e3-211d-4560-b259-54c76e8a6ee9

**Review by sxiong5 — APPROVED** [review]
Hey, I have tested your PR, and everything looks normal.

Screenshot 2023-07-25 at 15 32 58 (2)

**Comment by sxiong5** [comment]
> Hi @EvianTan at the start the functionality works properly, but on the dashboard page, it seems to break. The page becomes unresponsive. I have attached the video. If no one else is facing this issue then please ignore it.
> 
> Screenshot 2023-07-25 at 1 43 11 PM
>  new_recording_-_7_25_2023._1_38_59_pm.Original.mp4

This may not because of this PR since the DEV version has the same issue and it happened randomly. I think it's a performance issue. The team member tasks list took so long to render.

**Comment by AnishPandita** [comment]
Hey @EvianTan the PR looks good. Everything seems to be working normally.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/111321945/4c38b4c8-5206-4066-8592-34afb64a16fd

**Review by winghojackyli — APPROVED** [review]
Hi @EvianTan , I've tested the PR and it works as usual. Nothing crashed. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/84722cfe-ced6-49bc-b708-2e176873765e

**Review by Shreyj14 — APPROVED** [review]

**Review by eduvarjaor — COMMENTED** [review]
Hi @EvianTan 

I tested this PR and almost all pages work well, except the dashboard and weekly summaries page that still breaking. 

Screenshot_1

Screenshot_2

**Comment by iTvX** [comment]
I feel that the webpage is very laggy, but it's hard to say if it's because of this PR update or not. Sometimes, it even leads to the webpage showing 'no response'.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/1cfd850c-5ed3-464a-9f77-513c9406c04b

**Comment by igorrochadasilva** [comment]
Hi @EvianTan !
I hope you are well = D
I tried to teste the app, other pages looks ok, but the dashboard  is very laggy, I think it's because the size of the page.


1037_01_dashboard-page

**Review by DavidC0126 — APPROVED** [review]
Hi @EvianTan,

I tested your PR and everything works just great! The freezing dashboard problem is still remaining but it is not related to this PR.
profile
weekly_report

**Comment by beblicarl** [comment]
The app was very laggy and I was not able to test it because everything kept crashing

issue #1037

**Review by veronicacheng2 — APPROVED** [review]
Hi @EvianTan, I have tested the PR and everything works as usual. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/95119686/9cc93eb8-dc9b-4ab5-97dc-c77d17b9efc1

**Review by vemanamadhu — COMMENTED** [review]
Everything looks good. 
I couldnt test much because the app is very laggy but it is unrelated to this PR.
image

**Review by Indujaks — APPROVED** [review]
Tested your changes, everything works!
Screenshot 2023-07-28 at 12 22 54 PM

**Review by shiva2096 — APPROVED** [review]
Hi @EvianTan 

Application is working as expected without any issues.

Screenshot 2023-07-28 at 8 09 58 PM

**Comment by Lucas-E** [comment]
Thank you everyone! Moving this one to final review!

**Review by yaow62023 — APPROVED** [review]
Tested all functionalities under the admin account, and everything works smoothly. Well done!

**Review by n0vay — APPROVED** [review]
Everything  works perfectly, Good job!
image

**Review by joyceiphone — APPROVED** [review]
LGTM.

**Comment by Lin1404** [comment]
Hi @EvianTan, I have tested this PR. Everything works well!

image

**Review by Lin1404 — APPROVED** [review]

**Comment by one-community** [comment]
Thank you everyone, merging this one too

**Pull request merged**
