### PR TITLE
Johny create button earned date

### PR DESCRIPTION
**Pull request by johny4437**
# Description
DASHBOARD COMPONENT 1 -(PRIORITY MEDIUM) Jae:  Need a “Details” button or other way to see when specific badges were earned. Some badges are earned multiple times, so the button needs to show all dates when they were earned.
Dashboard → Badges Section → Badges Report

## Related PRS (if any):
This frontend PR is related to the [#311 ](https://github.com/OneCommunityGlobal/HGNRest/pull/311) backend PR.

## Mainly changes explained:
1 - added a dropdown button in the Badge Report modal that show all the dates for each earned badges
2 - Was added some lines of code in the badgeManagment.js file, to get the specified date when the badge is earned.
…

## How to test:
check into current branch
do `npm install` and `...` to run this PR locally
log as admin user
go to dashboard → Welcome, user →  Featured Badges → Assign Badge
go to dashboard→ scroll the screen→ Badges→ Badge Reports Button.
verify that the button dates is there.
Captura de Tela (317)
Captura de Tela (316)

### CODE REVIEW

**Comment by AnishPandita** [comment]
hi @johny4437 I tested your PR and it doesn't seem to be working for me. I checkout into 755 for frontend and 311 for backend but the badge reports page seems to not load. I am not sure if I am missing something?

https://user-images.githubusercontent.com/111321945/230308681-fde054cd-6a5f-4469-8ec9-c4b935909233.mov

**Review by ToobaJamal — COMMENTED** [review]
Hi Johny, I tested the PR multiple times, the dates button is there but when I click on the Dates button, it opens an empty dates list.

https://user-images.githubusercontent.com/52610124/230323354-eb324572-4e5f-4e55-98c8-085b33d46670.mp4

**Comment by LucileTech** [comment]
hi @johny4437 I tested your PRs #755 on the front and #311 on the back and I have the same error as @AnishPandita, I recorded the test with the console open, the servers are not crashing : 

https://user-images.githubusercontent.com/111132148/230509481-88ba05c4-3604-4628-b31d-379e9dac2928.mp4

**Comment by johny4437** [comment]
> Hi Johny, I tested the PR multiple times, the dates button is there but when I click on the Dates button, it opens an empty dates list.

ypu have to test with the backend here https://github.com/OneCommunityGlobal/HGNRest/pull/311

**Comment by johny4437** [comment]
> hi @johny4437 I tested your PR and it doesn't seem to be working for me. I checkout into 755 for frontend and 311 for backend but the badge reports page seems to not load. I am not sure if I am missing something?
In the backend PR are you doing `npm install` and then `npm run build`??

**Comment by johny4437** [comment]
> hi @johny4437 I tested your PRs #755 on the front and #311 on the back and I have the same error as @AnishPandita, I recorded the test with the console open, the servers are not crashing :

Hi @LucileTech, are you  using those commands `npm install` and `npm run build` in the backend PR??

**Comment by LucileTech** [comment]
> npm run build

I was sure I did but restarted the whole process and it worked this time. The 3 badges without dates are the ones I created for my first comment and the 2 badges with a date are the ones I created for this comment. 
It is working well!
Here is the recording:

https://user-images.githubusercontent.com/111132148/230516314-be953a8b-2560-4409-a9c5-73585be2e8a2.mp4

**Review by LucileTech — DISMISSED** [review]

**Review by ypan710 — COMMENTED** [review]
Hi @johny4437, I've tested your PR but I didn't see the badge dates as expected (I already have 20 badges assigned already for my account before testing this PR). What is the maximum number of badges allowed?

Screen Shot 2023-04-11 at 11 37 21 AM



Screen Shot 2023-04-11 at 11 29 36 AM

Screen Shot 2023-04-11 at 11 30 04 AM

**Review by vitorsaa2k — APPROVED** [review]
The changes works well, I'm getting the dates button and the correct date is being shown. The only concern is that, when I increased the count of the badge it didn't get a new date assingned to it, should this really happen?

image

**Comment by one-community** [comment]
Good catch Vitor! Johny, please fix what he found.

**Comment by one-community** [comment]
Yes, please add that to the bugs doc and comment on it for my review. Good catch, definitely something that needs to be fixed!

**Comment by AuroraLovesWhales** [comment]
Hi Johny. I have tested your PR and am able to see the date modified information. I am also facing the page frozen when I try to save changes. However, I am a bit confused about the increase/decrease badge count functionality from the badge report window here. Why do we need this functionality here? Shouldn't the user be able to assign badges from Welcome, user → Featured Badges → Assign Badge already? 

image

**Comment by johny4437** [comment]
@AuroraLovesWhales this functionality was already implemented, I just fixed the related bug. @one-community can give you the answer about this question.

**Comment by johny4437** [comment]
> Hi Johny. I have tested your PR and am able to see the date modified information. I am also facing the page frozen when I try to save changes. However, I am a bit confused about the increase/decrease badge count functionality from the badge report window here. Why do we need this functionality here? Shouldn't the user be able to assign badges from Welcome, user → Featured Badges → Assign Badge already?
> 
> image

Please look at the comments above I made a video saying this is happening even in te development branch.

**Comment by one-community** [comment]
Welcome, user → Featured Badges → Assign Badge already is where you assign a new badge. This is where you increase or decrease the number of an existing badge. Only Admins/Owners should be able to see the Assign Badges button and/or edit the number of badges here.

**Review by vitorsaa2k — DISMISSED** [review]
Requested changes done and working as expected!

**Comment by one-community** [comment]
Thank you all, moving to final review

**Comment by EvianTan** [comment]
Hey @johny4437 
I just tested PR 311 & 755 with your latest front/backend branch. After assigning badges, I still didn't get any dates in my badge report. Please check my video here - https://www.dropbox.com/s/0i6ot0zp95i2u5j/test%20Johny%27s%20PR.mp4?dl=0

**Comment by johny4437** [comment]
> Hey @johny4437 I just tested PR 311 & 755 with your latest front/backend branch. After assigning badges, I still didn't get any dates in my badge report. Please check my video here - https://www.dropbox.com/s/0i6ot0zp95i2u5j/test%20Johny%27s%20PR.mp4?dl=0

I tested here and for me is working normally, the mean thing is, the badge you got before test my PR they won't have the earned date.
here is a video that I recorded testing this PR.

https://www.dropbox.com/s/9lsk8wtzgesqdxc/date_badge.mp4?dl=0

**Comment by EvianTan** [comment]
Checked on Johny's latest video, everything works fine on his side. Not sure why it doesn't work on my side. Might be a some weird differences between accounts. I trend to merge those PRs now. I'll keep an eye on this functionality after it gets merged into development. Thank you @johny4437 you did a fantastic job here.

**Review by EvianTan — APPROVED** [review]

**Pull request merged**
