### PR TITLE
Peterson_Fix_Tasks_tab_revert_to_Current_Week_Timelog_tab_for_Volunte…

### PR DESCRIPTION
**Pull request by peterson337**
# Description
This pull request has been opened to fix the tasks tab reverting to the Current Week Timelog tab for the Volunteer user account, but for any other type of user, the selected tab should be tasks.

## Related PRS (if any):
None
…

## Main changes explained:
The Timelog.jsx component has been modified to fix the bug.
…

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache
4. Log in as a volunteer user with or without tasks, or any other type of user.
5. go to dashboard
6. After the page reloads, if your volunteer user has tasks, the selected tab should be "Tasks". If your volunteer user does not have tasks, the selected tab should be "Current Week Timelog". If you test with any other type of user, the selected tab should be "Tasks".

## Screenshots or videos of changes:
Peterson_Fix_Tasks_tab_revert_to_Current_Week_Timelog_tab_for_Volunteer_user_accoun

## Note:
None.

### CODE REVIEW

**Review by Logeshwari-Renu — APPROVED** [review]
I have tested the PR and the "Task" tab is current for the volunteers with task and "Current Week Timelog" is current for the volunteers without task. Verified for the "Admin" and "Owner" account, the "Current Week Timelog" is highlighted on page load. The functionalities work fine.

**Comment by sahithidhulipala9** [comment]
Reviewed the PR, For Volunteer without Tasks, After dashboard loaded, selected tab is Current Week Timelog Tab, where as for Admin and Owner Role, even without tasks, Selected tab is Task Tab. Great Work!
Screenshot (79)
Screenshot (80)
Screenshot (83)

**Review by sahithidhulipala9 — APPROVED** [review]

**Review by Jingyii800 — APPROVED** [review]
I have tested this PR, and it worked well. When I logged in as a volunteer with task, the dash board showed "Task" tag. When I logged in as a volunteer without task, the dashboard showed"Current Timelog" tag.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112589476/c98c5b89-3c1a-4ad7-9251-927971740d87

**Review by ishan-miglani — APPROVED** [review]
I have verified the changes. If I log in with volunteer user without tasks the selected tab is "Current Week Timelog". After I add a task and log in with volunteer user with tasks the default selected tab is "Tasks". With all other user types the selected tab is "Tasks". Thanks!
Screenshot 2024-07-19 at 7 30 37 PM
Screenshot 2024-07-19 at 7 31 10 PM
Screenshot 2024-07-19 at 7 31 42 PM
Screenshot 2024-07-19 at 8 00 53 PM

**Review by jinxyou — DISMISSED** [review]
I tested my volunteer account and while it has no tasks, it stays on the "Current week timelog", and while it has tasks, it will open on "Tasks" tab. 
Screenshot 2024-07-20 193611
Screenshot 2024-07-20 193619

**Comment by cecilia-uu** [comment]
截屏2024-07-21 下午3 05 29
Great!

**Review by angelalalacheng — APPROVED** [review]
Hi, 
I use your branch `Peterson_Fix_Tasks_tab_revert_to_Current_Week_Timelog_tab_for_Volunteer_user_accoun` for frontend and the latest development for backend. It all works good!

Owner and Admin account
Screenshot 2024-07-21 at 4 30 01 PM
Screenshot 2024-07-21 at 4 00 43 PM

Volunteer without tasks
Screenshot 2024-07-21 at 4 01 58 PM

Volunteer with tasks
Screenshot 2024-07-21 at 4 04 24 PM

**Review by kabraambika — APPROVED** [review]
I have tested this PR with latest development branch in backend Repository. Feature is working in all cases as shown below:

Case 1: Volunteer having no task, Current week timelog tab is active
image

Case 2: Volunteer having project but no task, current week timelog is active
image

Case 3: Volunteer has assigned task, task tab is active
image

**Review by Pranay-ai — APPROVED** [review]
Hey @peterson337 
I have reviewed the PR and working as expected
image
image
Thank You

**Comment by arunsrao9** [comment]
I tested the PR as a  Volunteer having no task, Current week timelog tab is active:
 
Screenshot 2024-08-02 at 10 04 02 PM
Screenshot 2024-08-02 at 10 02 54 PM

It works as expected, Good Job!

**Review by varunreddy03 — DISMISSED** [review]
I have reviewed this PR and it is working as expected. I have tested it on Volunteer, Testing, Owners accounts and in both light and dark mode they are working fine.

PR 2342_1
PR 2342_2
PR 2342_3

**Review by AnkitLall — APPROVED** [review]
I have tested the feature, following the instructions in the PR, and it works as expected. Please refer the screenshots attached below.

Volunteer without task:
Screen Shot 2024-08-09 at 7 33 27 PM

Volunteer with task:
Screen Shot 2024-08-09 at 7 34 45 PM

Screen Shot 2024-08-09 at 7 32 56 PM

**Review by SnelPatare — APPROVED** [review]
I have tested the PR. For volunteer without task, owner and admin. It is working well for me

image

image

**Comment by one-community** [comment]
Thank you all, moving this to final review!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
