### PR TITLE
Eduardo make reports page and all reports look as good as possible on phones

### PR DESCRIPTION
**Pull request by eduhorta**
# Description
image
## Implements Mobile Reports Page
Make Reports Page looks good as possible on phones.

## Related PRS:
Previous PR addressing this feature [PR#865](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/865)

## Main changes explained:
- Added Media Queries to adjust the style deppending on the screen's width
- Created `classNames` for some components to implement the feature
- Adjusted overlapping style of Reports Page Components

## How to test:
1. check into current branch
2. do `npm install` and `npm run start:local` to run this PR locally
3. log as owner/admin user
4. go to Reports → Reports → Right click to Inspect the Page (F12) → Toogle Device Tool Bar (Ctrl + Shift + M)
5. select a pre-defined width (Tablet - 768px / Mobile L - 425px / Mobile M - 375px / Mobile S - 320px)
6. click on each card (Projects/People/Teams) → Scroll Down → Pick a Project/Person/Team
7. verify if the important/relevant information are "looking good" on phones.

## Video of changes (Turn sound On to hear my disclaimer on how I addressed this feature)

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/40707b21-e4d3-4c81-9d4c-4e4d6ae18d2c

## Screenshots of changes:

People Report
Reports Page
Team Report

## Note:
About the "Tasks Table Total: 0" on the bottom of the page when accessing Reports -> Projects -> Pick Any
This part of the app is not yet finished.
So what you are seeing is it's expected behaviour for now.
There will be another PR addressing this feature/style but it's not this one.

If you find any issue, please follow these steps first:

1. Close Inspect Window (F12) with Toogle Device Bar On (Ctrl + Shift + M)
2. Reload the page (Ctrl + R)
3. Re-open Inspect Window (F12)
4. Reload the page once more with Toogle Device Bar On (Ctrl + Shift + M)
5. Check if the issue is still persisting

## Video of expected behaviour (Turn sound On)
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/8919d256-ddef-4351-86b4-dcba21bb5c71

### CODE REVIEW

**Review by HectorAgudelo — COMMENTED** [review]
The app's recent updates work fine, except for one issue: when users choose projects or people within the app, the task cards in those sections don't adjust properly for smaller screens on devices. As a result, they appear too wide and need to be re-evaluated for better fit.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/37153730/1b6a149b-774b-49ac-a5db-eee6c2cdcfbb

**Review by sxiong5 — CHANGES_REQUESTED** [review]
Hey @eduhorta, I tested your changes and found some issues.

At first, the **Reports Page**, **People Report Page**, and **Team Report Page** worked as expected, but the table in Project Page is in a mass styling. Also, when I tried to go back to the previous page or refresh the project page, there was no action from the browser. There could be some reasons that impact the operation and kill the process. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/62367016/84b70d9b-4885-40d3-8feb-81c391e7c313

FYI, I did some debugging on this issue. The problem could come from `ProjectMemberTable`; check the details from React Dev Tools.
Screenshot 2023-07-19 at 17 02 23

**Review by freecode23 — CHANGES_REQUESTED** [review]
Overall it looks good. I propose 2 improvements:

**1. Mobile S issue:** 
For these 3 cases, the radio button and the “All” is separated which can be quite confusing. Maybe move the radio button down as well?
Screenshot 2023-07-19 at 5 39 09 PM

Video description (please turn audio on): 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/02090a03-d834-47fe-a429-5819b9108b54





**2. After a category is clicked, it should automatically scroll up** 

Video description (please turn audio on):

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/67333705/d53ed2de-acff-4cca-abe9-9a8bb5a9d57c

**Comment by eduhorta** [comment]
> The app's recent updates work fine, except for one issue: when users choose projects or people within the app, the task cards in those sections don't adjust properly for smaller screens on devices. As a result, they appear too wide and need to be re-evaluated for better fit.
> 
>  PR.1020.mp4

Hey @HectorAgudelo!
Can you please confirm if you are talking about the transform/scale when the card gets clicked?
If so, I agree with you. 👍

> Hey @eduhorta, I tested your changes and found some issues.
> 
> At first, the **Reports Page**, **People Report Page**, and **Team Report Page** worked as expected, but the table in Project Page is in a mass styling. Also, when I tried to go back to the previous page or refresh the project page, there was no action from the browser. There could be some reasons that impact the operation and kill the process.
> 
>  Screen.Recording.2023-07-19.at.16.51.25.mov 
> FYI, I did some debugging on this issue. The problem could come from `ProjectMemberTable`; check the details from React Dev Tools. Screenshot 2023-07-19 at 17 02 23

Hello @sxiong5!
Really glad for the feedback.
About the "Freezing" issue when accessing Projects report page, I'd like you to know that I've faced the same issue when I first started developing this feature.
I did talk to other members who've confirmed the same behaviour.
So I did [Raise PR#999 - Eduardo - Bug fix project report page freezes ](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/pull/999)
`git pull` on dev branch then should do the job. 🤞



> Overall it looks good. I propose 2 improvements:
> 
> **1. Mobile S issue:** For these 3 cases, the radio button and the “All” is separated which can be quite confusing. Maybe move the radio button down as well? Screenshot 2023-07-19 at 5 39 09 PM
> 
> Video description (please turn audio on):
> 
>  Screen.Recording.2023-07-19.at.5.33.34.PM.mov 
> **2. After a category is clicked, it should automatically scroll up**
> 
> Video description (please turn audio on):
> 
>  Screen.Recording.2023-07-19.at.5.25.35.PM.mov

Hi @freecode23 !!
Thank you very much for such a detailed feedback! 🙌

1. Mobile S issue:
Can you please confirm if you are talking about the same thing as I mentioned to @HectorAgudelo?
The transform/scale behaviour from the cards.
If so, I also agree with you guys. 👍

2. After a category is clicked, it should automatically scroll up
I think that's a great idea! 
But I'd like to mention that the scope of this PR is only about styling the Reports Page. (At least what I understood at first)

Hey @one-community! Can you please give your opinion if I'm allowed to add this functionality suggested by @freecode23?

**Comment by freecode23** [comment]
> Hi @freecode23 !! Thank you very much for such a detailed feedback! 🙌
> 
> 1. Mobile S issue:
>    Can you please confirm if you are talking about the same thing as I mentioned to @HectorAgudelo?
>    The transform/scale behaviour from the cards.
>    If so, I also agree with you guys. 👍

Hi @eduhorta ,
I'm just talking about mobile S size. Just change from:
Screenshot 2023-07-19 at 6 45 23 PM

  to:
Screenshot 2023-07-19 at 6 45 25 PM

I don't find any issues in other sizes.

**Comment by one-community** [comment]
> 2. After a category is clicked, it should automatically scroll up

Yes to both of @freecode23's suggestions! Please do the one quoted here in a followup PR though

**Comment by iTvX** [comment]
Almost good enough.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/46791134/0b80930a-ee46-487b-8f1a-e069415d9cb1
As you can see, when I scroll down to the tasks, the "total:0" part is not fully displayed.

**Review by BaileyM96 — CHANGES_REQUESTED** [review]
Hello @eduhorta I tested your changes and everything is working great but their is a few issues that me and other users have pointed out.

## Issues

When using the Mobile Small Screen size 320px clicking on the "People", and "Teams" buttons the filter buttons do not line up instead the "All" button wraps down below the other button options.

The "Filter" option looks great under the "Projects" Section though, the other filter options in the different sections should look like that.

## Screenshots

UI Error

UI Filter Error Mobile S

As you can see the filter option "All" looks correct here for Large mobile screens

PR #1022 Mobile L

Medium Mobile Screen

PR #1022 Mobile M

Small Mobile Screen

PR #1022 Mobile S

Tablet Screen

PR #1022 Tablet Reports

**Review by luisarevalo21 — CHANGES_REQUESTED** [review]
Hello @eduhorta 

I reviewed your PR and looks great!
Overall great work!

I reviewed some of the other commenteres and agree with them. A few that stood out are the following
1. when using screens smaller than 320px the radio buttons do not lineup as noted by others.
Screenshot 2023-07-19 at 9 19 57 PM


2. Tasks contributed should be adjusted when on mobile. Instead it is hidden from view
Screenshot 2023-07-19 at 9 21 39 PM]

3. When clicking on a project and selecting one, the user' should be taken to the top of the page the same for the rest of the options i.e. people and teams. 
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/22454953/f97bcb1e-2311-4237-89fc-95d2dc99c197

However, overall great work!

**Comment by eduhorta** [comment]
> Almost good enough.
> 
>  CleanShot.2023-07-19.at.16.32.49.mp4 
> As you can see, when I scroll down to the tasks, the "total:0" part is not fully displayed.

Hello @iTvX!
Thank you for the feedback!
About the "Tasks Table Total: 0", I'd like you to know that this part of the app is not yet finished. 
So what you are seeing is it's expected behaviour for now.
There will be another PR addressing this feature but it's not this one. 👍

> Hello @eduhorta I tested your changes and everything is working great but their is a few issues that me and other users have pointed out.
> 
> ## Issues
> When using the Mobile Small Screen size 320px clicking on the "People", and "Teams" buttons the filter buttons do not line up instead the "All" button wraps down below the other button options.
> 
> The "Filter" option looks great under the "Projects" Section though, the other filter options in the different sections should look like that.
> 
> ## Screenshots
> UI Error
> 
> UI Filter Error Mobile S

Hey @BaileyM96!
Thank you for the feedback!
This was also pointed by other members so I'll be addressing this on the next commit. 👍

> 1. when using screens smaller than 320px the radio buttons do not lineup as noted by others.
> 2. Tasks contributed should be adjusted when on mobile. Instead it is hidden from view
>    Screenshot 2023-07-19 at 9 21 39 PM
> 3. When clicking on a project and selecting one, the user' should be taken to the top of the page the same for the rest of the options i.e. people and teams.

Hey @luisarevalo21!
Thank you for the feedback!

1. I'll fix the radio button on the next commit 👍

2. I couldn't understand this one. Can you please explain what do you mean by tasks contributed should be adjusted when on mobile? I also didn't understand what you meant by it's hidden from view.

3. I agree with you. This was also pointed by @freecode23 and approved by @one-community. But I was told to implement this in a follow up PR.

**Comment by eduhorta** [comment]
Here are changes after the feedback:

Radio Button on small screens:
image

Aligned itens inside Tasks contributed Table:
task-contributed-table

Please, let me know if I forgot anything! 🙌

**Review by vemanamadhu — CHANGES_REQUESTED** [review]
Hello @eduhorta 

I review your PR and good job on the coding. The code looks good.

I saw 2 places where I feel like changes are required.
1. When you navigate back(after the first time) to a team and click on an existing team. It doesnt load the team page from the top. It loads up with the screen focus somewhere in the middle. The back to top functionality also seems to working only when clicked the second or thrid time.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/13665284/0005caa6-f811-4716-bf71-61a10ef800c3

2. When you scroll down to the team members after clicking reports->team->selecting a team, the active inactive checkbox are out of alignment. It is a small fix but I feel like that needs to be fixed too

Please let me know what you think

**Review by n0vay — CHANGES_REQUESTED** [review]
Good Job on the code. Tested website on every dimension, everything works well.
I just have a few recommendations on the design. 
In tablet mode, the top icon for each Category seem to small, width wise.

the team boxes too.


And for longer lists [>50 items] dialogue boxes such as this



saves page space to show other items , this is my personal preference though.

**Review by eduvarjaor — CHANGES_REQUESTED** [review]
Hi @eduhorta

I tested this PR and when I did a search in Mobile S size for a result that doesn't exist, the column "Active" wasn't responsive.

And this problem persists in Mobile M and L sizes. Only started to be responsive since Tablet size.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/86692035/511c729f-9afe-42e8-84b3-905c5898bd61

**Review by freecode23 — APPROVED** [review]
Looks good! See you in follow up PR

**Comment by iTvX** [comment]
> 

Ok, I see! Great work!

**Comment by iTvX** [comment]
> > Almost good enough.
> > CleanShot.2023-07-19.at.16.32.49.mp4
> > As you can see, when I scroll down to the tasks, the "total:0" part is not fully displayed.
> 
> Hello @iTvX! Thank you for the feedback! About the "Tasks Table Total: 0", I'd like you to know that this part of the app is not yet finished. So what you are seeing is it's expected behaviour for now. There will be another PR addressing this feature but it's not this one. 👍
> 
> > Hello @eduhorta I tested your changes and everything is working great but their is a few issues that me and other users have pointed out.
> > ## Issues
> > When using the Mobile Small Screen size 320px clicking on the "People", and "Teams" buttons the filter buttons do not line up instead the "All" button wraps down below the other button options.
> > The "Filter" option looks great under the "Projects" Section though, the other filter options in the different sections should look like that.
> > ## Screenshots
> > UI Error
> > UI Filter Error Mobile S
> 
> Hey @BaileyM96! Thank you for the feedback! This was also pointed by other members so I'll be addressing this on the next commit. 👍
> 
> > 1. when using screens smaller than 320px the radio buttons do not lineup as noted by others.
> > 2. Tasks contributed should be adjusted when on mobile. Instead it is hidden from view
> >    Screenshot 2023-07-19 at 9 21 39 PM
> > 3. When clicking on a project and selecting one, the user' should be taken to the top of the page the same for the rest of the options i.e. people and teams.
> 
> Hey @luisarevalo21! Thank you for the feedback!
> 
> 1. I'll fix the radio button on the next commit 👍
> 2. I couldn't understand this one. Can you please explain what do you mean by tasks contributed should be adjusted when on mobile? I also didn't understand what you meant by it's hidden from view.
> 3. I agree with you. This was also pointed by @freecode23 and approved by @one-community. But I was told to implement this in a follow up PR.

OK I see. Great work!

**Review by yurisokolovicz — COMMENTED** [review]
Hi Eduardo,

Great job! I have the same question as the others mentioned above. I verified that the issue on small mobile devices regarding selecting "All" in 320px has already been resolved.

- However, the problem with the Task still needs to be addressed for both iPad and mobile.

- I believe the "card" header with class="report-header" is not properly adjusted for iPad and mobile devices. It would be nice to decrease the min-height from 35vh to 25vh for tablets (768) and also from 35vh to 25vh for mobile sizes (<390). Please check to the pictures below for comparison.

Screenshot from 2023-07-24 11-45-41
Screenshot from 2023-07-24 11-45-56

Screenshot from 2023-07-24 11-42-17

Screenshot from 2023-07-24 11-43-22
Screenshot from 2023-07-24 11-58-40
Screenshot from 2023-07-24 11-58-50

**Comment by eduhorta** [comment]
> Hello @eduhorta
> 
> I review your PR and good job on the coding. The code looks good.
> 
> I saw 2 places where I feel like changes are required.
> 
> 1. When you navigate back(after the first time) to a team and click on an existing team. It doesnt load the team page from the top. It loads up with the screen focus somewhere in the middle. The back to top functionality also seems to working only when clicked the second or thrid time.
> 
>  PR.1022.mp4 
> 2. When you scroll down to the team members after clicking reports->team->selecting a team, the active inactive checkbox are out of alignment. It is a small fix but I feel like that needs to be fixed too
> 
> Please let me know what you think

Hey @vemanamadhu!
Thank you for the feedback!

Here are my considerations.

1. The automatic scroll up was mentioned by other members and I was oriented to raise another PR just for this functionality.
2. Checkboxes aligned:
image




> Good Job on the code. Tested website on every dimension, everything works well. I just have a few recommendations on the design. In tablet mode, the top icon for each Category seem to small, width wise.  the team boxes too. 
> 
> And for longer lists [>50 items] for eg: 
> 
> dialogue boxes such as this saves page space to show other items , this is my personal preference though.
> 
> 

Hey @n0vay!
Thanks for the feedback!

I'd like to mention that this feature was described as "make reports page and all reports look as good as possible on phones".
About the recommendations on the design, there was nothing about it on the scope of this PR.
What I am trying to address here is only to make Reports page look good and useful on phones/tablets.

> Hi @eduhorta
> 
> I tested this PR and when I did a search in Mobile S size for a result that doesn't exist, the column "Active" wasn't responsive.
> 
> And this problem persists in Mobile M and L sizes. Only started to be responsive since Tablet size.
> 
>  responsivity_test.mp4

Hey @eduvarjaor!
Thanks for the feedback!

image

Just fixed the search/responsive column you mentioned. Thank you! 👍

> Hi Eduardo,
> 
> Great job! I have the same question as the others mentioned above. I verified that the issue on small mobile devices regarding selecting "All" in 320px has already been resolved.
> 
> * However, the problem with the Task still needs to be addressed for both iPad and mobile.
> * I believe the "card" header with class="report-header" is not properly adjusted for iPad and mobile devices. It would be nice to decrease the min-height from 35vh to 25vh for tablets (768) and also from 35vh to 25vh for mobile sizes (<390). Please check to the pictures below for comparison.
> 
> Screenshot from 2023-07-24 11-45-41 Screenshot from 2023-07-24 11-45-56
> 
> Screenshot from 2023-07-24 11-42-17
> 
> Screenshot from 2023-07-24 11-43-22 Screenshot from 2023-07-24 11-58-40 Screenshot from 2023-07-24 11-58-50

Hello @yurisokolovicz!
Thank you for the detailed feedback!
I would like to say that I didn't change any file/component regarding the `report-header`.
Did you watch the "Video of expected behaviour (Turn sound On)" I posted on description? Could you try?
Also I'm not sure if the header component is in the scope of this PR since it would affect other components (correct me if I'm wrong plz) 👍

**Review by BaileyM96 — COMMENTED** [review]
Hello @eduhorta I reviewed your newest changes and you have fixed the issue of the filter "all" option that was wrapping underneath the other options.

## Issues 

When reviewing the actual reports for "user", "projects" and "teams" everything looks great except the "Tasks" section at the bottom of the page. 

## Solutions

Making a table responsive on the screen is kind of a challenge but I thought of some solutions that might help:

1. Shorten up the table and take away some columns and rows that are presented on smaller screens.
2. Make a collapsed table that has the left side of the table fixed to the page so it does not move and you swipe the rest of the data.
3.  Or make the table rows into separate cards.

Either way it will take some redesigning to make the table feel and look more responsive.

## Screenshots
375 px

PR #1022 375px Medium Mobile

425px

PR #1022 425px Mobile Large error

Tablet

PR #1022 reports page responsive

**Comment by eduhorta** [comment]
> Hello @eduhorta I reviewed your newest changes and you have fixed the issue of the filter "all" option that was wrapping underneath the other options.
> 
> ## Issues
> When reviewing the actual reports for "user", "projects" and "teams" everything looks great except the "Tasks" section at the bottom of the page.
> 
> ## Solutions
> Making a table responsive on the screen is kind of a challenge but I thought of some solutions that might help:
> 
> 1. Shorten up the table and take away some columns and rows that are presented on smaller screens.
> 2. Make a collapsed table that has the left side of the table fixed to the page so it does not move and you swipe the rest of the data.
> 3. Or make the table rows into separate cards.
> 
> Either way it will take some redesigning to make the table feel and look more responsive.
> 
> ## Screenshots
> 375 px
> 
> PR #1022 375px Medium Mobile
> 425px
> 
> PR #1022 425px Mobile Large error
> Tablet
> 
> PR #1022 reports page responsive

Hey @BaileyM96!
The "Tasks" section on the bottom of the page is not yet finished.
Considering that, it would be wiser to style it after it's features are implemented/working properly. 👍

**Review by sxiong5 — APPROVED** [review]
Hey @eduhorta , I have rechecked, and the issues have been solved! Great job!
Screenshot 2023-07-26 at 13 27 23
Screenshot 2023-07-26 at 13 27 07

**Review by n0vay — APPROVED** [review]
Good job! Works as described.

**Comment by one-community** [comment]
Thank you everyone, moving this to final review...
image

**Comment by eduhorta** [comment]
Hey @cvtqx! 
Thank you for such a detailed feedback! 🙌

> 3. **Tasks Table in Projects -> Project and Task Contributed table in People -> User and all users tables in Teams -> Team are not responsive and are too big for small screens.**
>You've mentioned in one of your comments that The "Tasks" section on the bottom of the page is not yet finished and it would be wiser to style it after it's features are implemented/working properly. However, can you include this disclaimer in your PR description? I've reviewed the description and your videos several times and did not find this info (please correct me if I'm wrong), so I expected that these tables would be made responsive by your fix. This needs more clarification.

You are right! It does need more clarification. 👍
Added this disclaimer on "Note".

> 5. **When you scroll down to the team members after clicking reports->team->selecting a team, the active inactive checkbox are out of alignment.** You've fixed this in all views except Tablet width 768:

>    TabletView_AlignmentIssue

Here is how the checkboxes are looking for me at my latest commit:
image

**Review by cvtqx — COMMENTED** [review]
Thanks for adding that note, now it makes things clear!

I am still seeing that misalignment in tablet mode (did hard refresh and clear cache), see video: 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/107726913/2a133457-b065-49f6-a48d-10517fde7144

Maybe we can ask someone else to review it to see if they have the same issue.

**Comment by Lin1404** [comment]
Hi @eduhorta! I have tested your PR, and I found the header is not full filled for Moblie S -320px/Moblie M -375px/Moblie L -425px.

Moblie S -320px:
image

Moblie M -375px:
image

Moblie L -425px:
image

**Comment by eduhorta** [comment]
> Thanks for adding that note, now it makes things clear!
> 
> I am still seeing that misalignment in tablet mode (did hard refresh and clear cache), see video:
> 
> Maybe we can ask someone else to review it to see if they have the same issue.

Hey @cvtqx!
Fixed the misalignment. 👍

> Hi @eduhorta! I have tested your PR, and I found the header is not full filled for Moblie S -320px/Moblie M -375px/Moblie L -425px.
> 
> Moblie S -320px: image
> 
> Moblie M -375px: image
> 
> Moblie L -425px: image
> 
> It works well for Tablet: image

Hey @Lin1404!
This is the expected behaviour.
Can you follow what I've done on this video to see if this issue still persists?

## Video of expected behaviour (Turn sound On)
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/105796041/8919d256-ddef-4351-86b4-dcba21bb5c71

**Comment by AuroraLovesWhales** [comment]
Hi @eduhorta. I have tested this PR and great work! The only thing I want to point out is: it seems like the Active & Inactive radio buttons for the Teams page only align for tablets, but not phones. Please see my recording below for reference.

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/44281916/e2a7f2b9-d1be-4e08-bb6f-b2bc604cdf8e

**Comment by eduhorta** [comment]
> Hi @eduhorta. I have tested this PR and great work! The only thing I want to point out is: it seems like the Active & Inactive radio buttons for the Teams page only align for tablets, but not phones. Please see my recording below for reference.
> 
>  Screen.Recording.2023-08-11.at.7.58.57.PM.mov

Hi @AuroraLovesWhales !
Thank you for the feedback!

I'd like to mention that my intention was to align the checkboxes like this on mobile devices.

Tablet:
image

Large screen:
image

Medium screen:
image

Small screen:
image

This is how it looks like on my latest commit.

**Review by winghojackyli — APPROVED** [review]
I've tested this PR and it works great. 
It looks good on tablet and mobile device. 


https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/ae57ac1a-4c6b-43f2-a23c-9854cc568099

**Comment by beblicarl** [comment]
The responsivity works as intended on all screen sizes. Great work!

[screencast-localhost_3000-2023.08.24-10_04_47.webm](https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/68056104/3f436a8e-8eae-4b86-ac14-c0b597607024)

**Review by beblicarl — APPROVED** [review]

**Comment by Lin1404** [comment]
> > Thanks for adding that note, now it makes things clear!
> > I am still seeing that misalignment in tablet mode (did hard refresh and clear cache), see video:
> > Maybe we can ask someone else to review it to see if they have the same issue.
> 
> Hey @cvtqx! Fixed the misalignment. 👍
> 
> > Hi @eduhorta! I have tested your PR, and I found the header is not full filled for Moblie S -320px/Moblie M -375px/Moblie L -425px.
> > Moblie S -320px: image
> > Moblie M -375px: image
> > Moblie L -425px: image
> > It works well for Tablet: image
> 
> Hey @Lin1404! This is the expected behaviour. Can you follow what I've done on this video to see if this issue still persists?
> 
> ## Video of expected behaviour (Turn sound On)
>  2023-07-19.13-51-38.mp4



Hi @eduhorta , I have re-tested this PR, it looks good now! Good Job! 
And sorry for the mistake of the changes I make on the PR, I have reverted it. Please let me know if there is anything I can do to help.

-320px:
image

-375px:
image

-425px:
image

**Review by Lin1404 — APPROVED** [review]

**Review by beblicarl — APPROVED** [review]

**Review by beblicarl — APPROVED** [review]

**Review by Lin1404 — DISMISSED** [review]

**Review by winghojackyli — APPROVED** [review]
I've tested this PR and it works great after changes.
It looks good on tablet and mobile device. 

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/108389005/34c77e5e-2bda-40cb-99d4-ccf5a3c1df2d

**Comment by AnishPandita** [comment]
Hey, the PR looks much better now. Checked on various sizes. Seems to work well.
Screenshot 2023-08-26 at 2 59 55 PM
Screenshot 2023-08-26 at 2 59 15 PM
Screenshot 2023-08-26 at 2 58 45 PM
Screenshot 2023-08-26 at 2 58 24 PM
Screenshot 2023-08-26 at 2 58 01 PM

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
