### PR TITLE
Nicolle fix user profile header

### PR DESCRIPTION
**Pull request by nicollext**
# Description

 In the User Profile page the User Profile Header is not being displayed properly in some widths. There was also an additional scroll bar being mistakenly displayed.

## How to test:
check into current branch
do `npm install` and `...` to run this PR locally
log as any user
go to dashboard→ View Profile

## Screenshots or videos of changes:

**Before**

https://user-images.githubusercontent.com/101591708/229894847-9d83df94-4cf5-4995-b75c-6cc12cf8aae7.MP4

…

**After**

https://user-images.githubusercontent.com/101591708/229894869-56fb4a43-ab1f-4578-9a7b-d4bc958265ea.MP4

### CODE REVIEW

**Comment by AnishPandita** [comment]
Hi @nicollext I tested your PR and the User Profile Header is being displayed properly. I checked on multiple screen sizes and it didn't break.

https://user-images.githubusercontent.com/111321945/229933521-f0640ec2-d3a4-4341-adcc-3f6c2d5f4505.mov

**Comment by LucileTech** [comment]
Hi @nicollext I tested your PR and the User Profile Header is not being displayed properly under 500px width and between  767px and 993px width on my Chrome browser. 
I tried on Safari and the issue appears only under 500px.

https://user-images.githubusercontent.com/111132148/229951186-28f0983d-83e9-427d-aad5-f47715bc14a4.mp4
[](https://user-images.githubusercontent.com/111132148/229951186-28f0983d-83e9-427d-aad5-f47715bc14a4.mp4)
[](https://www.loom.com/share/75854fff18cd43ab9d4974b7167f9916)

Screenshot 2023-04-04 at 17 25 36

**Comment by nicollext** [comment]
> Hi @nicollext I tested your PR and the User Profile Header is not being displayed properly under 500px width and between 767px and 993px width on my Chrome browser. I tried on Safari and the issue appears only under 500px.
> 
> Screenshot 2023-04-04 at 17 25 36

Hi @LucileTech are you testing with the updated nicolle_fix_user_profile_header branch ? At your video I can see that some changes are not updated with the current branch.

**Comment by LucileTech** [comment]
> nicolle_fix_user_profile_header

Hi @nicollext yes everything is up to date I pulled again the branch just in case and did the tests again. But my Chrome has strange behaviors that's why I am always testing with Safari also. Here is the complete test with Chrome at 100%, Safari, and the code running on the branch up to date:
https://user-images.githubusercontent.com/111132148/230135881-bcbe8fe1-dcbf-45c2-8f23-e1092bd6e01a.mp4

**Comment by LucileTech** [comment]
> > Hi @nicollext I tested your PR and the User Profile Header is not being displayed properly under 500px width and between 767px and 993px width on my Chrome browser. I tried on Safari and the issue appears only under 500px.
> > Screenshot 2023-04-04 at 17 25 36
> 
> Hi @LucileTech are you testing with the updated nicolle_fix_user_profile_header branch ? At your video I can see that some changes are not updated with the current branch.

Hi @nicollext ! I was on the updated branch but retried it with a blank Chrome session and everything is okay, here is the recording of the test and the branch on which the code is running : 


https://user-images.githubusercontent.com/111132148/230142324-3d9bacf7-6ab7-43e2-98d9-2cba74687f68.mp4

**Review by LucileTech — APPROVED** [review]
Works well as explain in the pr

**Review by ypan710 — APPROVED** [review]
@nicollext I've tested your PR and profile header is displayed properly and no additional scrollbar being displayed.

Screen Shot 2023-04-05 at 11 23 54 AM

Screen Shot 2023-04-05 at 11 24 06 AM

Screen Shot 2023-04-05 at 11 26 19 AM

**Review by ToobaJamal — APPROVED** [review]
Hi Nicolle, I tested your PR, and the user profile header is displayed properly. 


https://user-images.githubusercontent.com/52610124/230315721-57746f0c-7e9a-466c-a3a7-5941a11e3059.mp4

**Comment by one-community** [comment]
Thank you everyone, moving this to final review.

**Comment by agujjar2206** [comment]
I have tested the changes in this PR and they work as expected. The User Profile Header now displays properly across all screen widths, resolving the previous issue. Additionally, the extra scrollbar that was mistakenly displayed has been removed, resulting in a cleaner user interface. Great job on addressing these issues! 👍

Screenshots:

Before:


After:

**Review by agujjar2206 — APPROVED** [review]

**Review by Elisaudo — APPROVED** [review]
@nicollext I tested your PR and the profile header is displayed correctly and no additional scrollbars are displayed. It has been checked for various screen sizes and works correctly.

BEFORE:

https://user-images.githubusercontent.com/64317219/230641843-d36e78c4-a35d-4cfc-ab12-ed22f81b2237.mp4

AFTER:


https://user-images.githubusercontent.com/64317219/230641929-456ebf6a-4dc4-4037-9b62-b73093b28ba5.mp4

**Comment by KaixiangGU** [comment]
ALL looks good!

**Pull request merged**
