### PR TITLE
Nidhi- Unit tests for BMDashboard.jsx

### PR DESCRIPTION
**Pull request by galgalinidhi**
# Description
Unit tests for BMDashboard.

## Related PRS (if any):
N/A

## Main changes explained:
Created a Unit test file ---> src/components/BMDashboard/_tests_/BMDashboard.test.jsx

## How to test:
1. check into current branch
2. do `npm install` 
3. run npm test BMDashboard.test.jsx to run the unit tests

## Screenshots or videos of changes:
W8_all_tests_pass

### CODE REVIEW

**Comment by nnamdixobi** [comment]
https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/80783443/8c3159c7-3d1e-4133-bbcf-1d763bfd3a15

Screenshot 2024-03-09 203650

Tests seem to have passed but a bunch of errors where generated that need to be addressed. Also the "yarn test" command does not work to test it has to be "npm test"

**Review by nnamdixobi — CHANGES_REQUESTED** [review]
Tests seem to have passed but a bunch of errors where generated that need to be addressed. Also the "yarn test" command does not work to test it has to be "npm test"

**Comment by dhairya-mehta** [comment]
Hey Nidhi, verified all the test cases, good job!
image

**Review by meetpadhiar4 — CHANGES_REQUESTED** [review]
Hi, I reviewed your PR. It passed all the test cases but it is giving errors before and after the test suite is executed. Please refer the screenshot attached.

PR 2044

**Review by 20chen-7 — COMMENTED** [review]
Screenshot 2024-03-14 at 12 12 48 PM
Screenshot 2024-03-14 at 12 12 08 PM
Unit test works for BMDashboard.jsx file, while other comments said that the npm test command shows more errors, which I think that is related to other unit test files. Overall, the BMDashboard.jsx looks good.

**Review by Abi-Liu — COMMENTED** [review]
I'm getting the same error messages as others. Not 100% sure why some are getting these error logs while others aren't, but I have a feeling it's due to the asynchronous call that is being made inside the useEffect in the BMDashboard component which isn't mocked. Either way the tests seem to do what they are expected to do.

EDIT: Now that I think about it, it's probably because they have their backend up and running when doing the tests, so they're not getting the `ERRCONN REFUSED` error because, the server is up and running.

BMDashboard

**Review by sameersdeshpande — DISMISSED** [review]
Hello @galgalinidhi 
I tested this and all tests passed successfully. Attaching the screenshot. Approving 
Screenshot 2024-03-23 at 7 05 31 PM

**Review by vikrambadhan — DISMISSED** [review]
Hi, I tested your PR and all the test cases passed!

Week 30 - PR5

**Comment by aaryaneil** [comment]
Looks good to me, I didn't receive any error like others probably cause my backend was running.

Screenshot 2024-03-29 at 2 26 44 PM

**Review by iven-yao — COMMENTED** [review]
I ran the test, and got the same error as others while passing all test cases.
image

**Review by aaryaneil — DISMISSED** [review]
Looks good to me, I didn't receive any error like others probably cause my backend was running.
318133667-27a7fb48-f3b1-466c-99f9-2580b8f9a9c8

**Comment by galgalinidhi** [comment]
Hi everyone, thank you for reviewing my PR! I realized I hadn't mocked the fetchBMProjects action and that was throwing an error if the backend was not running. I have pushed the changes. Please let me know if the issue persists.

**Review by yvonnep165 — COMMENTED** [review]
Hi @galgalinidhi I checked the test cases and ran the tests. They all passed. Nice work! Please refer to the screenshot below:
Screenshot 2024-04-26 at 4 38 53 PM

**Review by meetpadhiar4 — APPROVED** [review]
Hi, I reviewed your PR again and it passed all test cases.

**Review by iven-yao — APPROVED** [review]
Hi, I reviewed again, and it passed all test cases without error.

**Comment by beblicarl** [comment]
All tests passed successfully without the errors.

image

**Review by beblicarl — APPROVED** [review]

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
