### PR TITLE
Sai Preetham taking over for Clemar add a reminder to save changes modal to permissions management page

### PR DESCRIPTION
**Pull request by ClemarNunes**
# Description
 when a new permission is granted, a modal will appear reminding to save their changes.
will also open a modal informing you that you must log out and log back in for the permissions to take effect.

 Additionally, if an admin receives a new permission, a modal will notify them that they need to log out and log back in for the changes to take effect.

## Related PRS (if any):
none

## Main changes explained:
-User reminder modal: Added a modal that appears when a new permission is granted, reminding to save their changes.
-permission modal: Created a modal that informs need to log out and log back in for new permissions to take effect.

## How to test:
1. check into current branch
2. do `npm install` and `...` to run this PR locally
3. Clear site data/cache (Don't skip this or use incognito)
4. log as Owner user
5. go to dashboard→ Other Links→ Permissions Management→Manage User Permissions
6. choose an admin or other users and assign some permissions
7. make sure you open a modal to save when adding a permission 
8. Log in to the account that received the permission
9. check if a modal informs you that you must log out and log in

## Screenshots or videos of changes:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/134466562/6d88d2c6-f870-444c-b808-be838f8ebf41

After fix:

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/112666943/c2c0a5ab-26e8-4712-9295-a33cb518959b

### CODE REVIEW

**Review by peter6866 — CHANGES_REQUESTED** [review]
Great work on implementing the permission reminder modals for users and admins! Here's the review based on the provided testing steps:

✅ User Reminder Modal:
   - Verified that when a new permission is granted to a user, a modal appears reminding them to save their changes.
   - Confirmed that the modal is displayed correctly and contains the appropriate message.

✅ Permission Modal:
   - Tested that after granting a new permission, a modal is displayed informing the user that they need to log out and log back in for the new permissions to take effect.
   - Verified that the modal is triggered correctly and provides clear instructions to the user.

✅ Admin Notification Modal:
   - Logged in as an Owner user and navigated to the Permissions Management section (Dashboard → Other Links → Permissions Management → Manage User Permissions).
   - Assigned new permissions to a user.
   - Confirmed that the user receives a modal notification informing them to log out and log back in for the changes to take effect.

✅ Modal Behavior:
   - Tested the modal behavior by granting permissions to different users and admins.
   - Verified that the modals are displayed consistently and contain the correct information.

Suggestions:
- It was noticed that users may scroll within the reminder modal, so the permissions list will not scroll according causing a bad user experience.
- There seems to be a typo in the "Close" button text on the modal that appears after logging in.

https://www.loom.com/share/30b9bac3ab744a71a2583c34411bacb1?sid=1b970a9d-f482-4699-9995-0ddee8a2eff2

**Comment by Vijeth-V** [comment]
After the permissions are updated the user gets a popup of the permission updated. That works perfectly well. After logging out and logging back in the pop up is still popping everytime i logged back in.
I Think this is not the expected result. I am attaching the video took on my end do check if that happens on your end as well.
Thanks!

https://github.com/OneCommunityGlobal/HighestGoodNetworkApp/assets/72465725/90e77e73-8b92-4e71-8dd1-a2ea00ddfe6a

**Review by tianyangL11 — APPROVED** [review]
After the permissions changes the user gets a popup of the permission updated.  But when I logged out and re-log in, it will still pop up, I think it may have some issue
977e8eaf4c1f7a6bb89ea5f3cad8100

**Comment by cecilia-uu** [comment]
The "Close" button text in the modal that appears after logging in has a typo.
There are some conflicts with other files. 
截屏2024-06-08 下午10 03 19

**Review by Sudershhh — CHANGES_REQUESTED** [review]
The functionality is working as expected. The Modal is not responsive at all. Pplease make sure it is centered and the backdrop is grayed out. 

PR 2309 - 2

PR 2309 - 3

PR 2309

**Comment by peter6866** [comment]
Hi, could you resolve the merge conflicts?

**Review by angelalalacheng — APPROVED** [review]
Hi,
I use your branch `clemar_Add_a_reminder_to_save_changes_modal_to_Permissions_Management_page` to test the feature. The modal works good for me but the popup "Remember to save your changes!" seems that no content is under it.
Screenshot 2024-07-21 at 5 32 48 PM
Screenshot 2024-07-21 at 5 32 58 PM

The user who was informed to logout again.
Screenshot 2024-07-21 at 5 33 40 PM

**Review by ishan-miglani — CHANGES_REQUESTED** [review]
Hi, I have verified the changes in your PR. 
Most of the functionality looks good.
The user reminder modal that informs to log out and log back is slightly unresponsive while closing.
The modal that appears when a new permission is granted does not work in dark mode. Please address this. Thanks!

https://github.com/user-attachments/assets/2c7c2111-2489-4b74-b440-e49d3bf24239

**Comment by souravwalke** [comment]
Hi, I have verified the changes in your PR. The functionality looks good.

Screenshot 2024-07-27 at 11 42 47 PM

**Review by AnkitLall — CHANGES_REQUESTED** [review]
I've tested the feature according to the instructions in the PR, and it generally works as expected. However, I did notice a couple of issues:

1. The "Manage User Permissions" and "Remember to save your changes!" popups are not responsive, and when they are open, you can still scroll the background. (Refer attached screen recording)
2. The user reminder modal appears only when the user logs into their account, not when they are already logged in.

Additionally, I’m not sure, but shouldn’t this feature be designed to work only when the user is already logged into their account, rather than when they log in freshly?


https://github.com/user-attachments/assets/17f1cd12-5892-4cf1-8143-a9740436a794

**Review by nishitag5 — CHANGES_REQUESTED** [review]
While editing user permissions, the system displays a dialog box prompting a logout and login to apply the changes. Upon logging in as the user with the updated permissions, I can confirm that the changes have been successfully applied. However, the prompt indicating 'Permissions have been updated, please log out and log back in to see the changes' does not appear.

https://github.com/user-attachments/assets/17c2417d-0df1-444d-ada0-78c391c9826a

**Review by lcohen730 — CHANGES_REQUESTED** [review]
Followed instructions to test, but when logging into test account after setting new permission, there was no modal pop-up to inform me to log out then back in, and I waited a few minutes.

Also, small note: I noticed a grammatical error in the toaster notification that pops up after assigning permissions. It says "Be sure to tell them that you are changing these permissions and for that they need to log out and log back in..." 

Screenshot 2024-09-28 at 15 28 28

The "for" should be removed. It should say "Be sure to tell them that you are changing these permissions and that they need to log out...".

**Review by mrinalini-raghavendran19 — CHANGES_REQUESTED** [review]
Hello, 

I followed the instructions to test and a modal did not appear on the user account with the change in permissions informing them to log out. Please let me know if there's something else missing. 

Besides that, I notice a few changes that could be made:

1) When I minimize the screen, the save changes modal is hidden and does not appear to the user.

Screenshot 2024-10-01 at 2 20 18 PM

Screenshot 2024-10-01 at 2 20 42 PM

2) The green modal telling users the permissions have been updated appears too many times, once when you save changes and the next when you submit the changes. This may be a potential bug.

Screenshot 2024-10-01 at 2 21 31 PM

Do take a look!

**Comment by VMD281** [comment]
I reviewed this PR and the functionality works perfectly!
PR#2309_1
PR#2309_2
PR#2309_3

**Comment by preethamdnr** [comment]
Hello all,

I've made the following updates based on the feedback provided:

Reminder Modal Centering: Ensured that the "Remember to Save Your Changes" modal is properly centered on the screen, with equal spacing on both the left and right sides, especially for smaller screens.

Responsive Adjustments: Adjusted the modal's width and padding to make it responsive, so it remains within screen boundaries and looks balanced across different screen sizes.

Green Popup Notification Frequency: Updated the green popup notification to display only once per permission update action, avoiding multiple pop-ups and enhancing the user experience.

Please review the changes

Thank you!

**Comment by one-community** [comment]
Thank you all, merging!

**Pull request merged**
